### ISSUE TITLE
使用 docker 部署 canal-server 无法使用 docker-restart 命令

### ISSUE THREAD

**Issue by ForeGotto** [alibaba/canal#1001]
- 现象
当使用 docker 部署官方 canal-server 镜像（canal/canal-server:v1.1.0）并成功启动后，调用
```shell
docker restart
```
会有以下错误信息：
```log
mv: cannot stat `/home/admin/canal-server/conf/example': No such file or directory
```

- 原因
检查 docker 启动脚本，发现 https://github.com/alibaba/canal/blob/master/docker/image/admin/app.sh 的 84-92 行引发的错误：
```shell
destination=`perl -le 'print $ENV{"canal.destinations"}'`
if [[ "$destination" =~ ',' ]]; then
    echo "multi destination:$destination is not support"
    exit 1;
else
    if [ "$destination" != "" ] && [ "$destination" != "example" ] ; then
        mv /home/admin/canal-server/conf/example /home/admin/canal-server/conf/$destination
    fi 
fi
```
这里的行为是每次启动时，如果指定了 destination 且 destination 的值不是 example，会把
```path
/home/admin/canal-server/conf/example
```
目录重命名为指定的 destination 值。
由于我指定了 destination 且值不是 example，所以这个行为导致了执行
```shell
docker restart
```
时，由于容器内已经没有 example 文件夹，所以容器无法启动。

- 问题
各位大佬是如何解决这个问题的？自己打镜像还是有其他姿势？

**Comment by WithLin** [comment]
你可以写一个 docker-compose的yml，映射一下即可，可以参考下我写的[docker-compose.yml](https://github.com/CanalSharp/CanalSharp/blob/692672b5e7ecec9c91019cd254a1e73adfea7289/docker/docker-compose.yml)

**Comment by agapple** [comment]
mv操作做了下判断目录存在处理

**Comment by ForeGotto** [comment]
> 你可以写一个 docker-compose的yml，映射一下即可，可以参考下我写的[docker-compose.yml](https://github.com/CanalSharp/CanalSharp/blob/692672b5e7ecec9c91019cd254a1e73adfea7289/docker/docker-compose.yml)

@WithLin 试过这种方法，但是重启时会报其他错误：
```log
server_1  | mv: cannot move `/home/admin/canal-server/conf/example' to `/home/admin/canal-server/conf/uc': Device or resource busy
```
