### ISSUE TITLE
Canal写kafka的逻辑没有考虑kafka的message size限制?

### ISSUE THREAD

**Issue by firnsan** [alibaba/canal#1003]
https://github.com/alibaba/canal/blob/e4b6385dcc439fcf495c81b0c0f89da858dd377b/server/src/main/java/com/alibaba/otter/canal/kafka/CanalKafkaProducer.java#L104-L113

如果需要发送的record大小超过kafka限制(默认1MB), 是不是无法继续处理?

**Comment by 282857484** [comment]
我是自己处理的

**Comment by rewerma** [comment]
canal batchSize配置不要超过1M
```
servers: localhost:9092 #for rocketmq: means the nameserver
retries: 0
batchSize: 16384
lingerMs: 1
bufferMemory: 33554432

# Canal的batch size, 默认50K, 由于kafka最大消息体限制请勿超过1M(900K以下)
canalBatchSize: 50
```

**Comment by firnsan** [comment]
canalBatchSize意义是什么呢， 控制的粒度是事务级别 or event 级别 or row级别 or 字段级别？如果DB单个字段超过了1M， 如何处理呢。

**Comment by rewerma** [comment]
canalBatchSize是拉取canal拉取的发送的批大小,具体请参考canal 的配置说明
如果有单个字段大于1M的情况暂时可以先调整kafka的消息体限制上限
