### ISSUE TITLE
binlog-rows-query-log-events=1 中的queryevent事件少库名，row数据少GTID

### ISSUE THREAD

**Issue by 282857484** [alibaba/canal#1005]
5.6数据库中含有配置
binlog-rows-query-log-events=1 中的queryevent事件少库名，row数据少GTID。我看了binlog，binlog中确实也少这俩，canal能帮把这俩属性补全了吗？
header {
  version: 1
  logfileName: "mysql-bin.000945"
  logfileOffset: 430773470
  serverId: 1346306
  serverenCode: "UTF-8"
  executeTime: 1539165635000
  sourceType: MYSQL
  schemaName: ""    ----------------------------少库名
  tableName: "product_sc_id"
  eventLength: 374
  eventType: QUERY
  gtid: "816fb525-8e3c-11e7-b7b0-525400730122:1-212612172,73aa9f66-8e18-11e7-b6c5-525400730120:1-358980,b064380d-0559-11e6-b5be-005056996b87:1-1593948705"
}
entryType: ROWDATA
storeValue: "xxx"
, header {------------------------少gtid
  version: 1
  logfileName: "mysql-bin.000945"
  logfileOffset: 430773918
  serverId: 1346306
  serverenCode: "UTF-8"
  executeTime: 1539165635000
  sourceType: MYSQL
  schemaName: "gome_jiaoyu"
  tableName: "product_sc_id"
  eventLength: 126
  eventType: UPDATE
  props {
    key: "rowsCount"
    value: "1"
  }
}
entryType: ROWDATA
storeValue: "xxx"

**Comment by agapple** [comment]
binlog-rows-query-log-events schema没法获取到，binlog里就没有

**Comment by agapple** [comment]
ROWDATA里增加gtid里已添加，不过需要理解gtid的一个语义，如果是事务中的一行记录gtid为位点，会造成发送给mysql之后，丢弃当前事务的剩余记录.
