### ISSUE TITLE
对于mysql enum类型 canal默认返回int（即1，2，3，...），如何返回enum中的value？

### ISSUE THREAD

**Issue by alexlgj** [alibaba/canal#1008]
对于mysql enum类型 canal默认返回int（即1，2，3，...），现需要canal返回enum类型字段的具体值value，如何实现呢？

// ***********
我之前的做法：
1. 修改parser模块的rowslogbuffer的mysqlToJavaType方法，对于enum返回Types.CHAR; 
2. 修改rowslogbuffer的fetchValue方法，对于enum类型按照string类型修改，即返回string，但是报错：
Caused by: com.alibaba.otter.canal.parse.exception.CanalParseException: parse row data failed.
Caused by: java.lang.IllegalArgumentException: limit excceed: 63
	at com.taobao.tddl.dbsync.binlog.LogBuffer.getFullString(LogBuffer.java:1122)

<img width="1125" alt="enum1" src="https://user-images.githubusercontent.com/28953872/47005872-44beed00-d167-11e8-83a9-bb56a2cae283.png">
<img width="1121" alt="enum2" src="https://user-images.githubusercontent.com/28953872/47005873-45578380-d167-11e8-8512-1b0eee9b05cc.png">
<img width="981" alt="enum3" src="https://user-images.githubusercontent.com/28953872/47005875-45578380-d167-11e8-84a4-b942af2f2816.png">

请教大神该如何修改呢？

**Comment by agapple** [comment]
枚举特殊字符的各种情况，实际测试一下
