### ISSUE TITLE
meta.dat not update

### ISSUE THREAD

**Issue by warrenwx** [alibaba/canal#1009]
[canal 1.1.0] 
Canal server and client consumes data normally, but the timestamp and content of meta.dat not change, which will cause an exception 'Could not find first log file name in binary log index file' when restart canal server.
Pls check the configurations in attachment.

[instance.log](https://github.com/alibaba/canal/files/2486428/instance.log)
[canal.log](https://github.com/alibaba/canal/files/2486429/canal.log)

**Comment by agapple** [comment]
Could not find first log file name in binary log index file ,   代表mysql主机上binlog已被删除

**Comment by warrenwx** [comment]
I got more information with adding log in canal server. something unexpected occurs,
the updateCursor does not execute.
![image](https://user-images.githubusercontent.com/9636488/47079731-b9ae2780-d238-11e8-8fe6-41fedf6ac8df.png)

**Comment by warrenwx** [comment]
finally, I compile a new canal server with source code and deploy, the meta.dat was updated normally.
