### ISSUE TITLE
canal.kafka 用bin/kafka-console-consumer.sh命令收到乱码

### ISSUE THREAD

**Issue by brightsong** [alibaba/canal#1013]
在mysql数据库中插入一条记录后，用命令bin/kafka-console-consumer.sh --zookeeper 192.168.206.128:2181 --topic canal1 --from-beginning，看到消费端输出乱码：
`*:
mysql-bin.000027*UTF-80BJP229
*7
mysql-bin.000027*UTF-80BJPF mysql-bin.000027*UTF-80Bcan_dbJ      user_testP+Xb
        _-+_C-+++1Pb_id (0B6Ri++(11)
                                                       +a+e (0BdafdR
                                                                        +a_cha_(40)age (0B15Ri++(11):
+y_-+-bi+.000027 *UTF-80,8BJP261
*7
+y_-+-bi+.000027 *UTF-80,8BJPF 
+y_-+-bi+.000027 *UTF-80,8Bca+_dbJ      +_e__+e_+P*Xb
        _-+_C-+++1Pb^id (0B7Ri++(11)
                                                       +a+e (0BeeeR
                                                                       +a_cha_(40)age (0B11Ri++(11):
+y_-+-bi+.000027 *UTF-80,8BJP262`
然后看了kafka-client中的代码，改了AbstractKafkaTest.java相应的配置参数，如
`public static String  topic     = "canal1";
    public static Integer partition = 0;
    public static String  groupId   = "";
    public static String  servers   = "192.168.206.128:6667";
    public static String  zkServers = "192.168.206.128:2181";`
后，当往mysql中插入新记录后，但运行KafkaClientRunningTest.java没有收到数据包。各位有没有遇到过这种情况。

**Comment by rewerma** [comment]
canal kafka 模式默认是发送Message对象的序列化字节不是可见字符串,client接收到会反序列化.
如要发送可见字符串,请用 flatMessage模式,将会发送json格式数据

**Comment by liugaozy** [comment]
> canal kafka 模式默认是发送Message对象的序列化字节不是可见字符串,client接收到会反序列化.
> 如要发送可见字符串,请用 flatMessage模式,将会发送json格式数据

请问在哪里可以配置呢？

**Comment by brightsong** [comment]
我也没有配置，我是这样的，接受到Message对象后，解析里面的内容，然后把内容放在json中发送到另一个kafka中。

在 2018-10-23 17:12:59，"liugaozy" <notifications@github.com> 写道：


canal kafka 模式默认是发送Message对象的序列化字节不是可见字符串,client接收到会反序列化.
如要发送可见字符串,请用 flatMessage模式,将会发送json格式数据

请问在哪里可以配置呢？

**Comment by obforfair** [comment]
> canal kafka 模式默认是发送Message对象的序列化字节不是可见字符串,client接收到会反序列化.
> 如要发送可见字符串,请用 flatMessage模式,将会发送json格式数据

我们这边没有用canal kafka,是直接client 解析后自己发送到kafka的，也会遇到中文乱码的问题，但是不太容易复现，不知道什么原因
