### ISSUE TITLE
求指导：canal获取的事务号(tranactionID)和mysql中的事务号(transactionID)不一致，如何解决？

### ISSUE THREAD

**Issue by alexlgj** [alibaba/canal#1015]
1.canal的transactionID获取方法：
TransactionEnd txEnd = TransactionEnd.parseFrom(entry.getStoreValue());
String txID = txEnd.getTransactionId();

结果：46

2. mysql中查询结果：
Trx id counter 88363

**Comment by agapple** [comment]
你mysql中怎么一个查询办法？是从mysqlbinlog命令中获取？

**Comment by alexlgj** [comment]
谢谢您的回复！不好意思，之前查询的方法错了。canal获取的transactionID没有问题。

现使用的查询方法：
sudo mysqlbinlog --no-defaults  /usr/local/mysql/data/mysql-bin.000149

只是MySQL的DDL语句是非事务的，不能对DLL语句进行回滚操作，请问canal是如何处理ddl的呢？

**Comment by agapple** [comment]
canal只是解析binlog里的DDL，binlog里记录的内容已经事务提交成功的
