### ISSUE TITLE
有没有计划支持mysql 8

### ISSUE THREAD

**Issue by lulu2panpan** [alibaba/canal#1018]
有没有计划对8版本的mysql数据库进行支持？

**Comment by agapple** [comment]
下一个版本会支持一下，现在你们正式环境已经上到mysql8了么？

**Comment by agapple** [comment]
顶DataLink的开源精神，看了下大概的思路还是比较赞的，应该是结合了内部的一些批量业务场景运维经验做了蛮多的优化改进.

**Comment by agapple** [comment]
参考文档: https://github.com/alibaba/canal/wiki/BinlogChange%28MySQL8%29

**Comment by agapple** [comment]
mysql 8已经支持
