### ISSUE TITLE
canal-kafka 数据同步到kafka之后，kafka topic乱码

### ISSUE THREAD

**Issue by guanshanyue** [alibaba/canal#1020]
![default](https://user-images.githubusercontent.com/6134206/47210704-34587d80-d3c6-11e8-805c-0c7ed3772058.png)

canal启动之后，数据能同步到kafka,但是同步的数据乱码

**Comment by guanshanyue** [comment]
canal版本是：1.1.0，单节点部署的，本地查看topic乱码

**Comment by rewerma** [comment]
kafka默认传输的是序列化Message字节码,不是可见字符,需用client中的kafka模块反序列化为Message

**Comment by guanshanyue** [comment]
喔，好的

**Comment by guanshanyue** [comment]
我用的python客户端消费kafka，希望能支持明文发送json数据导kafka，方便消费，不用考虑反序列化的问题。
