### ISSUE TITLE
1.0.24 canal hv模式下解析mysql timestamp问题

### ISSUE THREAD

**Issue by yelandu** [alibaba/canal#1021]
单机情况下解析mysql timestamp 数据返回是正确
实例： mysql 时间 2018-10-19 19:09:09 单机解析过来，canal获取到是 2018-10-19 19:09:09
           hv模式下 解析获取到为2018-10-19 07:02:09 相差为12小时 单机和hv为同一个服务器 hv三台服务器时间均为CTC时区 时间也是正确的，有没有大佬知道是什么问题导致

**Comment by agapple** [comment]
hv是啥？canal是以binlog里的数据为准，可以先通过mysqlbinlog看一下原始binlog数据
