### ISSUE TITLE
c.a.o.canal.parse.inbound.mysql.dbsync.LogEventConvert - table parser error

### ISSUE THREAD

**Issue by dkqCoder** [alibaba/canal#1023]
WARN  c.a.o.canal.parse.inbound.mysql.dbsync.LogEventConvert - table parser error : header{}
今天突然遇到这样一个异常，导致这张表同步不成功。

**Comment by dkqCoder** [comment]
之前还是正常的，今天突然发现有这个异常，是怎么回事呢？

**Comment by agapple** [comment]
估计是binlog里对应的表被删除，重置位点跳过，后续可以开启TSDB来规避
