### ISSUE TITLE
canal 怎么支持DRDS数据库

### ISSUE THREAD

**Issue by daoshunli** [alibaba/canal#1024]
[destination = example1 , address = *************************:3306 , EventParser] ERROR c.a.o.canal.parse.inbound.mysql.dbsync.DirectLogFetcher - I/O error while reading from client socket
java.io.IOException: Received error packet: errno = 1047, sqlstate = HY000 errmsg = [dc26f11c5801000][172.16.22.194:3306][zbtsteam_test]Unknown command

**Comment by agapple** [comment]
@daoshunli canal是模拟mysql的binlog dump协议，DRDS目前没有对binlog协议有直接支持，可以直连DRDS底下的RDS来直接订阅
