### ISSUE TITLE
canal varchar null处理

### ISSUE THREAD

**Issue by ttting** [alibaba/canal#1026]
使用canal-kafka，收到消息，column值为null被设置成"", 
int , date 类型收到"" 可以默认理解为null,
对于varchar, text类型如何区分 null和""

**Comment by 1241407808** [comment]
单个column对象有个getisNull的方法来判断这个列对应的value是不是null

**Comment by 1241407808** [comment]
CanalEntry.Column 这个类

**Comment by agapple** [comment]
LS正解
