### ISSUE TITLE
RocketMQ 增加对FlatMessage的支持

### ISSUE THREAD

**Issue by duhengforever** [alibaba/canal#1027]
为了提升rocketmq binlog分发性能，需要增加数据分片支持。

**Comment by zygfengyuwuzu** [comment]
如果增加了分片数据一致性就不好保证了

**Comment by agapple** [comment]
这个是否分片应该是根据用的选择，做到表级别是否开启。针对主键不会发生修改的或者只是监听一下事件本身不关注顺序的，应该是比较适合

**Comment by agapple** [comment]
代码已提交
