### ISSUE TITLE
如何将canal 客户端接收到的CanalEntry 解析成可执行的sql 语句

### ISSUE THREAD

**Issue by wangyj00** [alibaba/canal#1034]
Master Mysql A 中执行的sql ,然后 Slave  canal  接收到CanalEntry 的对象，如何解析该对象 成为 可执行的sql ,然后同步到数据库 mysql B中呢？费了很大的劲拼装sql 发现自己拼装的要不情景不全，要不各种瑕疵，有没有方便的方法呢？

**Comment by wangyj00** [comment]
1.1.0 版本中 DDL操作可以直接拿到sql ,那DML操作是否可以直接拿到sql呢？

**Comment by agapple** [comment]
canal.example工程里，看下同步到DB的样例代码：https://github.com/alibaba/canal/tree/master/example/src/main/java/com/alibaba/otter/canal/example/db

**Comment by just-do-it-for-everything** [comment]
https://github.com/alibaba/canal/tree/master/example/src/main/java/com/alibaba/otter/canal/example/db
这个找不到
