### ISSUE TITLE
Docker部署canal后客户端连接不了

### ISSUE THREAD

**Issue by fengtansong** [alibaba/canal#1036]
首先canal在docker已经部署启动完毕，服务端口11112,
然后docker是有宿主IP 和 虚拟IP，本机电脑访问是通过虚拟IP：192.168.102.111:6633
然后客户端使用192.168.102.111:6633连接canal，启动服务之后客户端接收不到信息，而canal服务端一直输出c.a.otter.canal.server.netty.handler.SessionHandler - message receives in session handler...

请问IP问题怎么解决？

**Comment by agapple** [comment]
按照Docker QuickStart里的脚本，启动为host模式，并做端口映射
