### ISSUE TITLE
Canal 发送到Kafka Topic 消息的同时，实现Partition 分区

### ISSUE THREAD

**Issue by jkl0898** [alibaba/canal#1038]
Canal 1.1.0 版本消息发送到Kafka的同时，支持指定消息按Partition Key 分发到不同的分区吗？

**Comment by agapple** [comment]
https://github.com/alibaba/canal/wiki/Canal-Kafka-RocketMQ-QuickStart，即将发布的1.1.1支持这样的散列功能
