### ISSUE TITLE
canal.example-1.1.0.tar.gz包下的startup.bat脚本提示命令语法不正确

### ISSUE THREAD

**Issue by runong** [alibaba/canal#1041]
我目前是在windows7环境下进行测试的

**Comment by agapple** [comment]
语法报错的内容，或者提交一个修复的PR给我

**Comment by runong** [comment]
![2018-10-29_134009](https://user-images.githubusercontent.com/12081348/47631335-a710e800-db80-11e8-8825-06467c7045da.png)

**Comment by agapple** [comment]
很低级的问题，基本的bat用法你先google一下
