### ISSUE TITLE
Canal无法解析mysql5.6的binlog求大神帮忙

### ISSUE THREAD

**Issue by shubiao-yao** [alibaba/canal#1043]
操作系统：Centos6.5 
数据库版本：mysql5.6

首先我在mysql的/etc/my.cnf文件中添加在这三条

[mysqld]
server-id=1
log-bin=mysql-bin
binlog-format=ROW
配置完查看了一下，如图：
![image](https://user-images.githubusercontent.com/32409300/47547957-f4dfe300-d929-11e8-9cfb-c6bac9679f58.png)

给我的mysql新增的了一个canal账户,开启了所有的权限。Repl_slave_priv=Y
![image](https://user-images.githubusercontent.com/32409300/47548081-6750c300-d92a-11e8-942b-9b5bba436b97.png)

监测canal的日志tail -f logs/example/example.log ，开始启动canal, 日志内容如下图：
![image](https://user-images.githubusercontent.com/32409300/47548180-bdbe0180-d92a-11e8-9a64-7608dccd144f.png)

我的canal配置项：
![image](https://user-images.githubusercontent.com/32409300/47548240-05dd2400-d92b-11e8-8dc2-d7a1bced6de3.png)

这个参数不在截图中：canal.instance.filter.regex=.*\\..*

执行sql查看binlog日志中的文件是有变化的：
![image](https://user-images.githubusercontent.com/32409300/47548333-5785ae80-d92b-11e8-9d0f-5ed4882955b9.png)

上图中查看binlog的姿势有点问题，正确的姿势是：/usr/bin/mysqlbinlog -v mysql-bin.000003

![image](https://user-images.githubusercontent.com/32409300/47548446-a7647580-d92b-11e8-9bd1-69c495fb00b7.png)
test是我的数据库名，user是我的表名。

我执行完sql之后 canal日志没有发生任何改变。

canal客户端可以正常连接到canal服务端。但是canal服务端无法正常解析mysql的binlog，求大神帮忙解决。

**Comment by shubiao-yao** [comment]
如果哪里描述的不清晰请大神指正。

**Comment by agapple** [comment]
example工程是打印到另外的目录的，仔细找找

**Comment by shubiao-yao** [comment]
打印到另外的目录的？大神的意思是如果产生了binlog日志，在logs/example/example.log这个日志文件中是看不到的是吗 @agapple

**Comment by shubiao-yao** [comment]
![image](https://user-images.githubusercontent.com/32409300/47554077-1dbca400-d93b-11e8-88ce-4cf6082b9646.png)

**Comment by indextg** [comment]
请问您解决这个问题了吗？  我也遇到了，不知道怎么办。。。

**Comment by shubiao-yao** [comment]
@indextg 我遇到的这个问题是因为虚拟机CPU核数设置的1核导致的，修改成2核就好了
