### ISSUE TITLE
列类型是tinyint(1) unsigned，但实际数据值大于127时，canal获取的列值错误

### ISSUE THREAD

**Issue by penghcn** [alibaba/canal#1046]
列类型是tinyint(1) unsigned，但实际数据值大于127，在128～255之间，canal是按照boolean来处理的，直接转化成string，值变成了负数。在LogEventConvert.java的674行，建议修改如下(未充分测试)

            // if (isSingleBit && javaType == Types.TINYINT) {
            //     javaType = Types.BIT;
            // }
            if (buffer.isNull()) {
                columnBuilder.setIsNull(true);
            } else {
                final Serializable value = buffer.getValue();

                if (isSingleBit && javaType == Types.TINYINT && ((Number) value).intValue() >= 0) {
                    javaType = Types.BIT;
                }
                //...

https://github.com/alibaba/canal/blob/master/parse/src/main/java/com/alibaba/otter/canal/parse/inbound/mysql/dbsync/LogEventConvert.java

**Comment by agapple** [comment]
方便提供一下测试的SQL？
