### ISSUE TITLE
求解！canal搞了两天了还是运行不了第一个demo！求大神解惑

### ISSUE THREAD

**Issue by Passer-Bye** [alibaba/canal#1048]
1.环境
    mysql5.6
    centos7
    jdk8
    canal 1.1.1

   配置文件和mysql的canal用户都照着quickstart里面配置好了

2.问题
   1) 启动canal的时候example.log日志里面会有一个错误信息，难得上截图了，手打 。。。

     ERROR com.alibaba.druid.pool.DruidDataSource - testWhileIdle is true, validationQuery not set

  2) 查看mysql的日志 /var/log/mysql/mysqld.log的时候有这样的信息：

    Aborted connection 7 to db: 'unconnected' user:'canal' host:'vm02' (Got an error reading communication packets)

  3) binlog日志里面只有建库建表的日志，没有DML操作语句的日志

  4) 有时候example.log里面还会有空指针的异常，我看日志里面有 `gtid=<null>` 这样的日志，是因为这个吗

各位有没有遇到相同的问题求解答呀，感谢了！！！

**Comment by panholly** [comment]
canal权限的问题排查一下。

**Comment by shubiao-yao** [comment]
我在mac上用的mysql5.7 canal1.1.1  现在按照文档说的已经在单机跑起来一个demo了。  你把5.6换成5.7试试，我在centos5.6中使用的mysql5.6 canal1.1.1 ，canal无法解析binlog日志，我也不知道为什么。

**Comment by Charlieblu** [comment]
在canal.properties中 将canal.instance.tsdb.spring.xml=classpath:spring/tsdb/h2-tsdb.xml 注释掉，就可以运行了

**Comment by peyneee** [comment]
解决了吗？同问 我用的mysql5.7 出现了同样的问题  是不是和我的系统配置有关？1核2g的腾讯云服务器

**Comment by shubiao-yao** [comment]
@peyneee 可以提高下CPU的核数试试，我之前是用的1核CPU导致的这个问题，貌似现在最新版本修复了这个问题。
