### ISSUE TITLE
binlog变化client无响应

### ISSUE THREAD

**Issue by Dreamroute** [alibaba/canal#1051]
mysql、canal均使用docker方式部署，二者启动都正常，mysql binlog文件映射在宿主机的/var/lib/mysql/目录，操作数据库client端无响应，始终打印empty count，是否是binlog文件位置有问题？

**Comment by panholly** [comment]
一样的问题

**Comment by agapple** [comment]
检查canal server里对应的日志

**Comment by Dreamroute** [comment]
我是使用单机模式，需要把parallel参数设置成false，但是错误日志只显示一个空指针，错误信息提示不太友好
