### ISSUE TITLE
canal是否支持事务分组

### ISSUE THREAD

**Issue by yuquanhuang** [alibaba/canal#1053]
在数据库操作中包含事务性质的多表操作，在数据输出的时候能不能对这部分数据进行分组或打包为一个数据包。还是自己根据事务id进行分组

**Comment by agapple** [comment]
数据事务有begin/end进行包裹，业务上可以基于这块进行组合

**Comment by yuquanhuang** [comment]
> 数据事务有begin/end进行包裹，业务上可以基于这块进行组合

canal是否支持python对接，将数据同步到kafka

**Comment by yuquanhuang** [comment]
> 新的1.1.1版本会支持直接将数据投递到kafka，可用对应kafka的python客户端进行消费

谢谢，那我直接可以配置好之后通过python从kafka取数据了是吧

**Comment by agapple** [comment]
是的

**Comment by yuquanhuang** [comment]
> 是的

我看到GitHub上的1.1.1版本中提交记录写道‘去掉kafka server端TRANSACTIONBEGIN和TRANSACTIONEND的判断’，这个版本要处理事务操作的话通过什么方式判断？有事务id吗？
