### ISSUE TITLE
AdminGuide文档未更新

### ISSUE THREAD

**Issue by luoqingming110** [alibaba/canal#1060]
1. 操作系统
    a.  纯java开发，windows/linux均可支持

    b.  jdk建议使用1.6.25以上的版本，稳定可靠，目前阿里巴巴使用基本为此版本. 

 

2. mysql要求
   a. 目前canal支持mysql 5.5版本以下，对mysql5.6暂不支持，(mysql4.x版本没有经过严格测试，理论上是可以兼容)

**Comment by agapple** [comment]
改好了
