### ISSUE TITLE
1.1.0版本golang客户端

### ISSUE THREAD

**Issue by woodcutter007** [alibaba/canal#1064]
报错信息：Fatal error: proto: Messages: illegal tag 0 (wire type 0)exit status 1

**Comment by WithLin** [comment]
可以提供一下你是怎么调用的呢？

**Comment by WithLin** [comment]
你可以去 [canal-go-issue](https://github.com/CanalClient/canal-go/issues) 提issue。

**Comment by woodcutter007** [comment]
看了一下，这个报错发生在get操作proto那边解码的时候，而且当时数据库没有任何操作

**Comment by WithLin** [comment]
我这边测试是pass的喔，现在依然报错吗？

**Comment by woodcutter007** [comment]
偶然出现的，不是一直有，而且当时数据库没有操作，应该没有数据才对

**Comment by WithLin** [comment]
已经解决

**Comment by jackerzz** [comment]
@agapple 请问一下，如何解决在golang 中出现，数据库是中文，客户端解析处理是“？？？“
![5dac6daaf23fd64fbe53f5dbaa7a8ac](https://user-images.githubusercontent.com/35586448/69512688-f8f09100-0f7f-11ea-89ae-31df8c15d0b8.png)
