### ISSUE TITLE
binlog同步过程中ddl有丢失

### ISSUE THREAD

**Issue by yxzhang666** [alibaba/canal#1066]
mysql版本 5.6.26
canalserver版本 1.0.24
我们在实时同步binlog处理dml的过程中（万条/秒），发送了一条ddl语句，发现client端并没有拿到这条ddl语句，请问是什么原因。
canal.instance.get.ddl.isolation 和这个配置有关系吗？我用的是默认值false

**Comment by agapple** [comment]
关闭issue？原因自己找到了？

**Comment by yxzhang666** [comment]
> 关闭issue？原因自己找到了？ @yxzhang666 
我们的DBA添加表字段的逻辑和我们的处理方式不一致。我们通过CanalEntry.EventType.ALTER 获取ddl 并处理该ddl语句；dba是通过克隆表，更换表名之后添加的字段，然后把之前的表drop，再更改克隆表名为之前的表名，新表名我们没有去关注，所以没拿到该条ddl。严格来说，canal server并没有丢失该条binlog ，是我们没拿到，虚惊一场！
canal.instance.get.ddl.isolation，这个isolation我们要不要打开，有没有建议呢？

**Comment by spccold** [comment]
这不是pt-schema-change-online和ghost的做法吗

**Comment by yxzhang666** [comment]
> 个batch一个ddl，没有啥本质区别。可以用在做数据同步上

明白了。谢谢！

**Comment by yxzhang666** [comment]
> 这不是pt-schema-change-online和ghost的做法吗

不太了解这块。。
