### ISSUE TITLE
关于 canal-1.0.26-preview-3 中 EntryProtocol.proto 和 CanalEntry.java 的一致性

### ISSUE THREAD

**Issue by ovictorain** [alibaba/canal#1073]
### 简述：
在基于 `canal-1.0.26-preview-3`，即 `commit: b734a32` 做修改时，发现 _proto_ 文件与生成的 _java_ 文件不一致。
如下图， _EntryProtocol.proto_ 中新增了两个字段：`XACOMMIT / XAROLLBACK`；_CanalEntry.java_ 中除 `XACOMMIT / XAROLLBACK` 外，还多出 `XASTART / XAEND`。
但后续文件中均未看到多出的这两个字段。

### 截图：
EntryProtocol.proto
![image](https://user-images.githubusercontent.com/18032427/47699902-63d17a80-dc4f-11e8-99c4-a40f9f71c53e.png)

CanalEntry.java
![image](https://user-images.githubusercontent.com/18032427/47700072-0f7aca80-dc50-11e8-8494-9324b7687b37.png)

### 疑问：
请问修改时应该以 _CanalEntry.java_ 为准？即：在 `canal-1.0.26-preview-3`上做改动时，保留 `XASTART / XAEND` ？

**Comment by agapple** [comment]
建议直接使用1.1.1版本了，向前兼容的
