### ISSUE TITLE
canal1.1.1版本报com.google.protobuf.InvalidProtocolBufferException$InvalidWireTypeException: Protocol message tag had invalid wire type.

### ISSUE THREAD

**Issue by brightsong** [alibaba/canal#1074]
报错场景为：mq.yml中的flatMessage:false,执行List<Message> messages = connector.getList(5L, TimeUnit.SECONDS);报上述错误，当把groupId换一个后就好使了。这是什么情况。
如果不想换groupId的话，有解决方法吗

**Comment by agapple** [comment]
你估计之前写入了部分MQ的数据，换一个groupId就相当于消费最新的数据
