### ISSUE TITLE
rocketmq分区键支持正则？

### ISSUE THREAD

**Issue by xesygao** [alibaba/canal#1080]
比如mysql用了分库，从db1-db9，数据分发到rocketmq多个分区，然后我mq.yml是不是要这么设置   
partitionHash:
     db1.table: pk
     db2.table: pk
     ......
从代码看目前是不支持正则的
能否支持正则，比如
partitionHash:
     regex: db[1-9].table.pk

**Comment by agapple** [comment]
最新代码已修复
