### ISSUE TITLE
cana-kafak1.1.0版本，搭建kafka消费客户端，怎么对ROWDATA类型的storeValue进行解析

### ISSUE THREAD

**Issue by redoorzhou** [alibaba/canal#1082]
2018-10-31 15:49:04.318 [Thread-1] INFO  c.a.o.canal.client.running.kafka.CanalKafkaClientExample - Message[id=12,entries=[header {
  version: 1
  logfileName: "mysql-bin.000002"
  logfileOffset: 1206761
  serverId: 1
  serverenCode: "UTF-8"
  executeTime: 1540972144000
  sourceType: MYSQL
  schemaName: ""
  tableName: ""
  eventLength: 79
}
entryType: TRANSACTIONBEGIN
storeValue: " _"
, header {
  version: 1
  logfileName: "mysql-bin.000002"
  logfileOffset: 1206909
  serverId: 1
  serverenCode: "UTF-8"
  executeTime: 1540972144000
  sourceType: MYSQL
  schemaName: "smart_meter"
  tableName: "sys_region_new"
  eventLength: 46
  eventType: INSERT
  props {
    key: "rowsCount"
    value: "1"
  }
}
entryType: ROWDATA
storeValue: "\b\212\001\020\001P\000b\217\001\022\036\b\000\020\004\032\002id \001(\0010\000B\00530026R\aint(11)\022\037\b\001\020\f\032\004name \000(\0010\000B\000R\vvarchar(20)\022!\b\002\020\004\032\tparent_id \000(\0010\000B\0012R\aint(11)\022)\b\003\020\371\377\377\377\377\377\377\377\377\001\032\005level \000(\0010\000B\0011R\ntinyint(1)"
, header {
  version: 1
  logfileName: "mysql-bin.000002"
  logfileOffset: 1206955
  serverId: 1
  serverenCode: "UTF-8"
  executeTime: 1540972144000
  sourceType: MYSQL
  schemaName: ""
  tableName: ""
  eventLength: 31
}
entryType: TRANSACTIONEND
storeValue: "\022\0049961"
],raw=true,rawEntries=[]]

想知道storeValue怎么解析？

**Comment by qinfuhong** [comment]
同问，折腾好久了

**Comment by rewerma** [comment]
可以参考: MessageUtil.parse4Dml
