### ISSUE TITLE
扁平发送RocketMQ出现发送空包现象kafka应该存在同样问题

### ISSUE THREAD

**Issue by zygfengyuwuzu** [alibaba/canal#1083]
[https://github.com/alibaba/canal/blob/master/server/src/main/java/com/alibaba/otter/canal/rocketmq/CanalRocketMQProducer.java](url)
代码 96行处返回数组，数组中值可能为空，但是下面没有判断，会给mq发送空消息，kafka应该也存在同样问题。

另外一个问题还请大神帮忙回答一下
FlatMessage 这个对象 的属性 data length 什么情况下是**大于1**的

**Comment by rewerma** [comment]
有发生dml操作data size就会大于1

**Comment by hookover** [comment]
问题仍然存在： kafka消息 = 操作行数 x 2
2019.6.24  cannal v1.1.3
