### ISSUE TITLE
版本1.1.1 docker启动失败

### ISSUE THREAD

**Issue by Dreamroute** [alibaba/canal#1087]
使用1.1.1直接投递消息到kafka方案，按照wiki文档修改相关参数，成功。
然而：同样的配置，使用docker方式容器启动不成功，查看canal以及instance日志，无任何错误信息，把日志级别开到debug一行一行查看日志，也未发现异常情况。
有其他大神遇到类似情况么？搞了一天了，实在是没辙了。

**Comment by Dreamroute** [comment]
tcp模式下没毛病，容器不会退出，设置canal.serverMode = kafka时，启动没报错，服务可以正常运行10来秒，消息可以投递到kafka，10来秒之后容器就会自动退出

**Comment by agapple** [comment]
应该是这个问题 : https://github.com/alibaba/canal/issues/1083

**Comment by agapple** [comment]
docker bash上去看过了?

**Comment by Dreamroute** [comment]
@agapple 是的

**Comment by agapple** [comment]
@Dreamroute 你可以启动一下docker，指定一下entrypoint为bash，然后bash登录节点后，人为/home/admin/app.sh试试，看看是否进程有自动退出

**Comment by SteveFrank** [comment]
有检查docker容器内网络是否可以连通容器外kafka 或者 zK吗？

**Comment by Dreamroute** [comment]
逐行分析了启动脚本，目前定位问题在（host模式）：执行了startup.sh脚本里面的CanalLauncher之后，本来应该占用11111端口，然而该端口并未被占用，导致执行app.sh里面的checkStart函数时，nc 127.0.0.1 11111 -w 1 -z | wc -l的返回值始终为0，于是脚本里面30秒检测通不过，造成容器启动不起来。后续还需要进一步分析原因。不知道其他人有没有遇到过这种问题，我在issue里面搜了下，没发现类似的情况

**Comment by Dreamroute** [comment]
似乎说错了，貌似11111端口不会被占用。

**Comment by Dreamroute** [comment]
@agapple nc 127.0.0.1 11111 -w 1 -z | wc -l这里老是返回0，过不了脚本里面的checkStart函数，但是，我注释掉checkStart函数，启动，投递消息都没毛病，非docker模式由于不存在这个过程就不存在这个问题，求解下惑，谢谢，实在不知道怎么解决这个问题了。

**Comment by agapple** [comment]
这个我下个版本修复一下
