### ISSUE TITLE
canal.kafka 1.1.0版本 canal.instance.filter.regex 无法过滤

### ISSUE THREAD

**Issue by whiney** [alibaba/canal#1088]
设置了canal.instance.filter.regex= dm.orders 。但是别的表还是订阅了。

**Comment by agapple** [comment]
多看wiki的FAQ

**Comment by whiney** [comment]
FAQ之前就看过了。


检查下CanalConnector是否调用subscribe(filter)方法；有的话，filter需要和instance.properties的canal.instance.filter.regex一致，否则subscribe的filter会覆盖instance的配置，如果subscribe的filter是.*\..*，那么相当于你消费了所有的更新数据 【特别注意】

我觉得问题出现在这里。但是canal.kafka里面，但是canal.kafka。让canal继承了kafka。然后我们的Java代码只作为消费端来消费的kafka的信息。

` 
 KafkaCanalConnector kafkaCanalConnector = KafkaCanalConnectors.newKafkaConnector(zkServers, servers, topic, partition, groupId);
        kafkaCanalConnector.connect();
        // 指定filter，格式 {database}.{table}，这里不做过滤，过滤操作留给用户
        kafkaCanalConnector.subscribe();`

它这里的subscribe,是这样的。没法设置filter，这里订阅设置的是topic。我觉得按道理，应该只在instance.properties设置过滤就可以

```
    /**
     * 订阅topic
     */
    public void subscribe() {
        waitClientRunning();
        if (!running) {
            return;
        }

        if (partition == null) {
            if (kafkaConsumer != null) {
                kafkaConsumer.subscribe(Collections.singletonList(topic));
            }
            if (kafkaConsumer2 != null) {
                kafkaConsumer2.subscribe(Collections.singletonList(topic));
            }
        } else {
            TopicPartition topicPartition = new TopicPartition(topic, partition);
            if (kafkaConsumer != null) {
                kafkaConsumer.assign(Collections.singletonList(topicPartition));
            }
            if (kafkaConsumer2 != null) {
                kafkaConsumer2.assign(Collections.singletonList(topicPartition));
            }
        }
    }
```

**Comment by agapple** [comment]
表达式需要注意一下，需要有转义符

**Comment by FCRc** [comment]
我也是同样的问题

**Comment by whiney** [comment]
更新到了canal 1.1.1之后，还是这个问题

经过验证。应该是和数据库有关系。

我本地测试的数据库可以过滤，正式环境的数据库不可以。

我正式环境是订阅的数据库的从库。但是具体原因还不是很清楚。想对比一下数据库的信息，在看看。

不过按照它的FAQ应该能解决大部分的问题。

你的问题，可以多看看这个FAQ。
https://github.com/alibaba/canal/wiki/FAQ
