### ISSUE TITLE
rocketmq收到消息总数等于真实消息数乘以队列数

### ISSUE THREAD

**Issue by xesygao** [alibaba/canal#1091]
这么配置，mysql插入1000条数据，同步到rocketmq，16个队列每个队列都有1000条数据，即总数据16000条。不应该是1000条数据分布在这16个队列？
\- canalDestination: host1
topic: canal
\# partition: 1
\# 对应topic分区数量
partitionsNum: 16
partitionHash:
\# 库名.表名: 唯一主键
db1.table: UUID
db2.table: UUID
db3.table: UUID
...

**Comment by agapple** [comment]
1000条数据分布在这16个队列

**Comment by zygfengyuwuzu** [comment]
#1083  看看是不是这个问题 @xesygao

**Comment by xesygao** [comment]
> #1083 看看是不是这个问题 @xesygao

是这个问题，FlatMessage[] partitionMessages = new FlatMessage[partitionsNum]，每个分区都有一条数据，但是只有一条是有内容的。
现在看代码已经加了非空判断，是最近修复了？

**Comment by rewerma** [comment]
嗯,昨天修复的
