### ISSUE TITLE
canal+zookeeper 集群 客户端第一次启动成功第二次不能启动

### ISSUE THREAD

**Issue by liangxiaoshanhf** [alibaba/canal#1092]
3台canal +3台zookeeper，搭建好环境后用源码中的ClusterCanalClientTest类测试 并能正常消费。关闭这个客户端后再ClusterCanalClientTest类测试就不能起来程序一直阻塞，发现ZOOKEEPER中的信息未变导致不能正常启动
  
[zk: localhost:2181(CONNECTED) 6] get /otter/canal/destinations/example/1001/running
{"active":true,"address":"192.168.0.59:54224","clientId":1001}
cZxid = 0x20000001a
ctime = Thu Nov 01 22:56:35 EDT 2018
mZxid = 0x200000031
mtime = Thu Nov 01 23:17:07 EDT 2018
pZxid = 0x20000001a
cversion = 0
dataVersion = 2
aclVersion = 0
ephemeralOwner = 0x0
dataLength = 62
numChildren = 0

**Comment by jiacheo** [comment]
按理说,/otter/canal/destinations/example/1001/running 这个节点应该是ephemeral的，而你这个明显不是。。你是自己写的这个节点么？

**Comment by agapple** [comment]
如果client非正常关闭, zookeeper的临时节点消失需要等待session timeout, 默认应该是15秒

**Comment by liangxiaoshanhf** [comment]
问题解决了，原因是一台canal关掉后zk中的/otter/canal/destinations/example/1001/running信息还没有过期，再启别的机器时client检查不是自己的IP会一直等待，现在是等它过期再启就没问题了。
