### ISSUE TITLE
关于PeriodMixedLogPositionManager可能存在点位数据读取不及时导致日志丢失问题

### ISSUE THREAD

**Issue by jiacheo** [alibaba/canal#1093]
## 上下文
看代码中， PeriodMixedLogPositionManager.getLatestIndexBy 如果从 MemoryLogPositionManager 拿到是空，就直接返回null了，就会导致parser去别的地方（配置文件、mysql master）取上次的点位数据，也就是保存在zookeeper里的点位数据其实是没用的。。

在系统启动的过程中，首次调用这个接口，实际上就是会返回null，后面有了事件处理之后，MemoryLogPositionManager中才有数据，难道这个Manager要搭配其他LogPositionManager组合使用吗？

## 重现  
例如我做了下测试，zk中的parse数据如下：
>  {"identity":{"slaveId":-1,"sourceAddress":{"address":"localhost","port":3306}},"postion":{"gtid":"","included":false,"journalName":"mysql-bin.000005","position":21704,"serverId":1,"timestamp":1541179545000}}  

杀掉进程后，多写几条mysql数据，此时mysql binlog已经滚动到新位置。
重新启动canal后，因为zk这个值没加载到内存，所以读取到的是mysql master最新的数据：
>  2018-11-03 01:28:27.804 [destination = example , address = localhost/127.0.0.1:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - find start position : EntryPosition[included=false,journalName=mysql-bin.000005,position=22955,serverId=<null>,gtid=<null>,timestamp=<null>]  

## 解决办法  
建议可以参考 FileMixedLogPositionManager 或者 MixedLogPositionManager那种实现

```
 public LogPosition getLatestIndexBy(String destination) {
        LogPosition logPosition = memoryLogPositionManager.getLatestIndexBy(destination);
        if (logPosition != null) {
            return logPosition;
        }
        //首次读取不到数据，从zk中捞
        logPosition = loadDataFromZookeeper(destination);
        if (logPosition == null) {
            return nullPosition;
        }
        return logPosition;
    }

```

**Comment by agapple** [comment]
你可以看下我的一些设计文档, 当时设计的是有parse position和ack position两类, 引入这两个position主要是围了解决多种store的实现. 

如果是实现file的store, parse和ack position肯定是不一致的, parser下次重启时读取上一次的parse position. 如果实现的是memory的store, parse和ack position就是一致的, parser下次重启时读取的就是ack position (这也是failback的实现)

**Comment by agapple** [comment]
目前外部也有团队在实现基于本地文件的store

**Comment by jiacheo** [comment]
@agapple 你的设计思路我理解，不过这里的PeriodMixedLogPositionManager 的实现确实比较奇怪的，你会发现zookeeper存的那一份一直没有被用上，仅仅是存起来。

**Comment by littleneko** [comment]
同时persistLogPosition的逻辑也是有问题的，
```
persistTasks.add(destination);
memoryLogPositionManager.persistLogPosition(destination, logPosition);
```
这两句顺序应该换一下，如果在`persistTasks.add`之后，`memoryLogPositionManager.persistLogPosition`之前，刚好定时任务被执行，这时定时任务是取不到这次位点更新的，只有等到下次调用`persistLogPosition`才会刷新`memoryLogPositionManager`中的位点到zk上

**Comment by agapple** [comment]
@littleneko 可以提交一个PR
