### ISSUE TITLE
drop table导致canal启动失败

### ISSUE THREAD

**Issue by chenyu9390** [alibaba/canal#1094]
删除表A之后,手动把节点值前移至对表A进行增删改的节点之前，导致cannal启动时报message=Table 'kapp_tms_prd.rs_route_temp' doesn't exist,请问是否有配置去过滤这种情况的发生
![image](https://user-images.githubusercontent.com/8199403/47947598-c0d47580-df5a-11e8-847b-9341e2c672b6.png)

**Comment by spccold** [comment]
了解一下[TSDB](https://github.com/alibaba/canal/wiki/TableMetaTSDB)

**Comment by agapple** [comment]
LS正解
