### ISSUE TITLE
canal ha模式主备切换数据延迟接收问题

### ISSUE THREAD

**Issue by panholly** [alibaba/canal#1096]
canal server和canal client的HA模式，server搞死一个会自动切换，client搞死一个也会自动切换，主备切换的瞬间数据数据接收延迟时间是多少？这个是不是不可避免？有哪位知道请指教。

**Comment by panholly** [comment]
@agapple 求教

**Comment by f-zhao** [comment]
感觉没法避免，具体时间自己测试下就好了呀
