### ISSUE TITLE
 column size is not match for table:xx,30 vs 17

### ISSUE THREAD

**Issue by bingzhan0613** [alibaba/canal#1097]
遇到了这种错误，用的是canal v1.1.0

我在canal.properties中配置的对tsdb的支持，好像没有启作为，
这个配置必须要配置在instance下的instance.properties里吗？？

**Comment by spccold** [comment]
你把ddl过滤了?

**Comment by bingzhan0613** [comment]
这是我的配置
# binlog filter config
canal.instance.filter.druid.ddl = true
canal.instance.filter.query.dcl = false
canal.instance.filter.query.dml = false
canal.instance.filter.query.ddl = false
canal.instance.filter.table.error = false
canal.instance.filter.rows = false

**Comment by spccold** [comment]
你的配置没看出什么问题，你是怎样的使用过程

**Comment by agapple** [comment]
检查一下tsdb是否正常起作用吧
