### ISSUE TITLE
编码问题

### ISSUE THREAD

**Issue by SteveFrank** [alibaba/canal#1101]
作者您好，
      非常感谢您开源该产品。
      我们现在遇到一个编码问题，想请教一下，我们使用的是阿里的RDS数据编码格式为utf8mb4/utf8mb4_general_ci，现在我们canal-server侧具体配置如下：
      `canal.instance.connectionCharsetNumber=45`
        `canal.instance.connectionCharset=UTF-8`
       在canal-client侧使用：
       `CanalEntry.RowChange rowChange = ignore(() -> CanalEntry.RowChange.parseFrom(e.getStoreValue()));`

当我们解析完成后发现，client侧获取到的数据被自动去除了字段中的中文，只留下了非中文相关内容。我们在client侧还需要进行一些显示的数据转换格式配置吗？

**Comment by SteveFrank** [comment]
example:
 字段：articleTitle -> 文章标题测试123 
 修改为：articleTitle -> 123-文章标题测试-123-test
 最后获取到的before 和 after 分别为 ：123，123--123-test 中文被去掉了

**Comment by agapple** [comment]
估计是中间乱码了吧

**Comment by SteveFrank** [comment]
> 估计是中间乱码了吧

好的，我们跟一下，看一下是哪一步的序列化出现问题了

**Comment by obforfair** [comment]
> example:
> 字段：articleTitle -> 文章标题测试123
> 修改为：articleTitle -> 123-文章标题测试-123-test
> 最后获取到的before 和 after 分别为 ：123，123--123-test 中文被去掉了

是中间问题吗？我们这边也有

> > 估计是中间乱码了吧
> 
> 好的，我们跟一下，看一下是哪一步的序列化出现问题了

是中间环节问题吗？我们这边直接copy的entry也出现了乱码问题

**Comment by SteveFrank** [comment]
> > example:
> > 字段：articleTitle -> 文章标题测试123
> > 修改为：articleTitle -> 123-文章标题测试-123-test
> > 最后获取到的before 和 after 分别为 ：123，123--123-test 中文被去掉了
> 
> 是中间问题吗？我们这边也有
> 
> > > 估计是中间乱码了吧
> > 
> > 
> > 好的，我们跟一下，看一下是哪一步的序列化出现问题了
> 
> 是中间环节问题吗？我们这边直接copy的entry也出现了乱码问题

我们使用最新master分支打包，该问题没有重现了
