### ISSUE TITLE
canal server使用一段时间后就会报错

### ISSUE THREAD

**Issue by WillSwift** [alibaba/canal#1105]
canal server使用几天之后，就会报java.io.IOException: EOF encountered。查看了下源码，出问题的地方是com.alibaba.otter.canal.parse.driver.mysql.socket.BioSocketChannel#read(byte[], int, int, int)。报了一段时间（不到24h）EOF encountered错误后，就开始报Could not find first log file name in binary log index file。之后再过一段时间（不到1h），server就不工作了。请问是什么原因呢？

**Comment by WillSwift** [comment]
@agapple 大神麻烦进来看下。

**Comment by SanmuWangZJU** [comment]
可能是找不到binlog文件了

**Comment by WillSwift** [comment]
> 可能是找不到binlog文件了

确实是找不到binlog文件了，但这个不是根本原因。我认为原因是发生EOF encountered后，server找不到上一次解析成功的最后一条记录，只能从保存的binlog最开始位置开始读取。但是binlog后面定期清理了，所以找不到。问题是，我不知道导致频繁EOF encountered的原因，也就是不知道为啥BioSocketChannel的read方法为什么会频繁失败。

**Comment by SanmuWangZJU** [comment]
> > 可能是找不到binlog文件了
> 
> 确实是找不到binlog文件了，但这个不是根本原因。我认为原因是发生EOF encountered后，server找不到上一次解析成功的最后一条记录，只能从保存的binlog最开始位置开始读取。但是binlog后面定期清理了，所以找不到。问题是，我不知道导致频繁EOF encountered的原因，也就是不知道为啥BioSocketChannel的read方法为什么会频繁失败。

记得最近解析成功的位点信息是记录在zookeeper中的，你可以读取zk相关路径下节点中存放的数据，确认下最后解析的位置，还有如果订阅的库表始终没有更新且对其它库表中数据的更新没有开启autoCommit的话，位点信息应该是不会更新到zk中的。

**Comment by WillSwift** [comment]
> 相关路径下
好的，多谢，我看看

**Comment by WillSwift** [comment]
> > > 可能是找不到binlog文件了
> > 
> > 
> > 确实是找不到binlog文件了，但这个不是根本原因。我认为原因是发生EOF encountered后，server找不到上一次解析成功的最后一条记录，只能从保存的binlog最开始位置开始读取。但是binlog后面定期清理了，所以找不到。问题是，我不知道导致频繁EOF encountered的原因，也就是不知道为啥BioSocketChannel的read方法为什么会频繁失败。
> 
> 记得最近解析成功的位点信息是记录在zookeeper中的，你可以读取zk相关路径下节点中存放的数据，确认下最后解析的位置，还有如果订阅的库表始终没有更新且对其它库表中数据的更新没有开启autoCommit的话，位点信息应该是不会更新到zk中的。bio的read方法我不是很了解了。

好的，多谢，我看下

**Comment by WillSwift** [comment]
> > > 可能是找不到binlog文件了
> > 
> > 
> > 确实是找不到binlog文件了，但这个不是根本原因。我认为原因是发生EOF encountered后，server找不到上一次解析成功的最后一条记录，只能从保存的binlog最开始位置开始读取。但是binlog后面定期清理了，所以找不到。问题是，我不知道导致频繁EOF encountered的原因，也就是不知道为啥BioSocketChannel的read方法为什么会频繁失败。
> 
> 记得最近解析成功的位点信息是记录在zookeeper中的，你可以读取zk相关路径下节点中存放的数据，确认下最后解析的位置，还有如果订阅的库表始终没有更新且对其它库表中数据的更新没有开启autoCommit的话，位点信息应该是不会更新到zk中的。bio的read方法我不是很了解了。

我使用canal example默认的配置，里面没有配置zookeeper，会是因为这个么？

**Comment by agapple** [comment]
默认配置是存储在本地文件里的，看一下conf/xxx/meta.dat
