### ISSUE TITLE
1.1.1可以使用阿里云的mq（RocketMQ）吗

### ISSUE THREAD

**Issue by rainLeelzr** [alibaba/canal#1109]
1.1.1可以使用阿里云的mq（RocketMQ）吗

**Comment by agapple** [comment]
@duhengforever  可以考虑支持一下AK/SK的写入模式

**Comment by agapple** [comment]
最新代码已支持

**Comment by rainLeelzr** [comment]
请问在哪里配置写入阿里云RocketMQ的 AK/SK，我看了wiki好像找不到，是不是还没更新文档

**Comment by ymwneu** [comment]
> 请问在哪里配置写入阿里云RocketMQ的 AK/SK，我看了wiki好像找不到，是不是还没更新文档

发送消息时，MQProperties.java中可以配置ak/sk。消费的时候，RocketMQCanalConnector.java提供了新的构造方法。

**Comment by rainLeelzr** [comment]
docker1.1.2 启动几秒后，自动停了，日志也不知道怎么看。
run.sh如下：
#!/bin/bash

function check_port() {
    local port=$1
    local TL=$(which telnet)
    if [ -f $TL ]; then
        data=`echo quit | telnet 127.0.0.1 $port| grep -ic connected`
        echo $data
        return
    fi

    local NC=$(which nc)
    if [ -f $NC ]; then
        data=`nc -z -w 1 127.0.0.1 $port | grep -ic succeeded`
        echo $data
        return
    fi
    echo "0"
    return
}

function getMyIp() {
    case "`uname`" in
        Darwin)
         myip=`echo "show State:/Network/Global/IPv4" | scutil | grep PrimaryInterface | awk '{print $3}' | xargs ifconfig | grep inet | grep -v inet6 | awk '{print $2}'`
         ;;
        *)
         myip=`ip route get 1 | awk '{print $NF;exit}'`
         ;;
  esac
  echo $myip
}

NET_MODE=""
case "`uname`" in
    Darwin)
        bin_abs_path=`cd $(dirname $0); pwd`
        ;;
    Linux)
        bin_abs_path=$(readlink -f $(dirname $0))
        NET_MODE="--net=host"
        ;;
    *)
        NET_MODE="--net=host"
        bin_abs_path=`cd $(dirname $0); pwd`
        ;;
esac
BASE=${bin_abs_path}

DATA="$BASE/data/logs"
CONF_DIR="$BASE/data/conf"

mkdir -p $DATA
VOLUMNS="-v $DATA:/home/admin/canal-server/logs -v $CONF_DIR:/home/admin/canal-server/conf"
PORTLIST="8000 2222 11111 11112"
PORTS=""
for PORT in $PORTLIST ; do
    #exist=`check_port $PORT`
    exist="0"
    if [ "$exist" == "0" ]; then
        PORTS="$PORTS -p $PORT:$PORT"
    else
        echo "port $PORT is used , pls check"
        exit 1
    fi
done

MEMORY="-m 4096m"
LOCALHOST=`getMyIp`
cmd="docker run -d -h $LOCALHOST \
		  -e canal.auto.scan=false \
		  -e canal.destinations=example \
		  -e canal.instance.master.address=xxxxxxx.mysql.rds.aliyuncs.com:3306  \
		  -e canal.instance.dbUsername=canal  \
		  -e canal.instance.dbPassword=xxxxxx  \
		  -e canal.instance.connectionCharset=UTF-8 \
		  -e canal.instance.tsdb.enable=true \
		  -e canal.instance.gtidon=false  \
		  -e canal.serverMode=RocketMQ  \
		  -e canal.mq.aliyun.accessKey=xxxxxx \
		  -e canal.mq.aliyun.secretKey=xxxxxx \
		  -e canal.mq.topic=TOPIC_PRE_CANAL_NORMAL \
		  -e canal.mq.producerGroup=PID_PRE_CANAL_NORMAL \
		  --name=canal-server $VOLUMNS $NET_MODE $PORTS $MEMORY canal/canal-server:v1.1.2"
echo $cmd
eval $cmd



启动时的截图：
![image](https://user-images.githubusercontent.com/12439084/49362294-65dc9c80-f719-11e8-9af5-f52c5e5628f0.png)

**Comment by agapple** [comment]
这不是自动停啊，docker ps -a

**Comment by rainLeelzr** [comment]
![image](https://user-images.githubusercontent.com/12439084/49503656-f0a4cf00-f8b2-11e8-9353-4bf8a6fb55e3.png)
![image](https://user-images.githubusercontent.com/12439084/49504365-75dcb380-f8b4-11e8-9d18-c87a3f1c364c.png)
![image](https://user-images.githubusercontent.com/12439084/49504390-842acf80-f8b4-11e8-8938-a758452d3546.png)

请问有什么地方还没配置或者配置错了？阿里云

**Comment by duhengforever** [comment]
@rainLeelzr 看报错应该是没有先创建topic

**Comment by rainLeelzr** [comment]
@duhengforever 看阿里云mq资源的截图，已经创建了这个topic

**Comment by zhouluoyang0406** [comment]
@rainLeelzr   你的问题解决了么？我也有类似的问题，我想知道一下 nameserver 应该配置什么？http://onsaddr-internal.aliyun.com:8080/rocketmq/nsaddr4client-internal 还是curl http://onsaddr-internal.aliyun.com:8080/rocketmq/nsaddr4client-internal 后返回的100.XXX.XX.1:8080;100.XXX.XX.2:8080;100.XXX.XX.3:8080

**Comment by godlike110** [comment]
> ![image](https://user-images.githubusercontent.com/12439084/49503656-f0a4cf00-f8b2-11e8-9353-4bf8a6fb55e3.png)
> ![image](https://user-images.githubusercontent.com/12439084/49504365-75dcb380-f8b4-11e8-9d18-c87a3f1c364c.png)
> ![image](https://user-images.githubusercontent.com/12439084/49504390-842acf80-f8b4-11e8-8938-a758452d3546.png)
> 
> 阿里云mq资源：
> ![image](https://user-images.githubusercontent.com/12439084/49504611-fb606380-f8b4-11e8-9e18-3ef37cafd78c.png)
> ![image](https://user-images.githubusercontent.com/12439084/49504631-09ae7f80-f8b5-11e8-89db-57665530a0ce.png)
> 
> 请问有什么地方还没配置或者配置错了？阿里云Mq是有PID的，但是canal没有PID可以配置，把PID配在canal.mq.producerGroup也不行。
> 我的是免费版的阿里云mq，没问题吧

canal 开源版本rocketmq版本没有升级 使用阿里云的ons-client-1.7.9.final 重写rockmq发送逻辑，亲测解决问题  CanalRocketMQProducer 类init方法修改：
        logger.info("rocket mq config:{}",JSON.toJSON(rocketMQProperties));

        this.mqProperties = rocketMQProperties;
        RPCHook rpcHook = null;
        if (rocketMQProperties.getAliyunAccessKey().length() > 0
            && rocketMQProperties.getAliyunSecretKey().length() > 0) {
            SessionCredentials sessionCredentials = new SessionCredentials();
            sessionCredentials.setAccessKey(rocketMQProperties.getAliyunAccessKey());
            sessionCredentials.setSecretKey(rocketMQProperties.getAliyunSecretKey());
            rpcHook = new ClientRPCHook(sessionCredentials);
        }

        defaultMQProducer = new DefaultMQProducer(rocketMQProperties.getProducerGroup(), rpcHook);
        defaultMQProducer.setNamesrvAddr(rocketMQProperties.getServers());
        defaultMQProducer.setRetryTimesWhenSendFailed(rocketMQProperties.getRetries());
        defaultMQProducer.setVipChannelEnabled(false);
        logger.info("##Start RocketMQ producer##");
        try {
            defaultMQProducer.start();
        } catch (MQClientException ex) {
            throw new CanalServerException("Start RocketMQ producer error", ex);
        }
 }

类中的send 方法对应修改即可
