### ISSUE TITLE
1.1.1版本kafka取出的json数据 缺少data字段 什么原因

### ISSUE THREAD

**Issue by CodeLulu318** [alibaba/canal#1115]
1.1.1版本 kafka 取json数据，本地测试有data字段data:[{name:"abc"}]，canal连接linux上的数据库后 就没有data这个字段了  什么原因啊

**Comment by CodeLulu318** [comment]
官方能不能给下说明，缺少data字段不好操作呀

**Comment by CodeLulu318** [comment]
是不是 只有delete和update语句才有 data字段 ，为什么insert没有呢

**Comment by CodeLulu318** [comment]
追加描述：linux mysql为5.6版本 win为5.5

**Comment by rewerma** [comment]
flatMessage没有data数据？你用工程里的client-adapter接收打印一下dml信息看看是否正确

**Comment by CodeLulu318** [comment]
> flatMessage没有data数据？你用工程里的client-adapter接收打印一下dml信息看看是否正确

对的 ，没有data但是有SQL语句，

**Comment by rewerma** [comment]
有sql的说明是ddl操作
你可以清理一下position和mq的offset

**Comment by CodeLulu318** [comment]
> 有sql的说明是ddl操作
> 你可以清理一下position和mq的offset
可是比较奇怪的是  有的update delete语句有data字段，但是sql字段没有信息，方便加Q指导一下么

**Comment by CodeLulu318** [comment]
> 有sql的说明是ddl操作
> 你可以清理一下position和mq的offset

可是比较奇怪的是 有的update delete语句有data字段，但是sql字段没有信息，方便加Q指导一下么

**Comment by CodeLulu318** [comment]
追加描述：navicat 写SQL语句执行 flatMessage没有data字段，直接修改表数据有data字段

**Comment by rewerma** [comment]
断掉调试一下CanalKafkaProducer send方法

**Comment by Czjcunzhang** [comment]
@CodeLulu318    能给个联系方式吗， 我kafka什么消息都收不到
