### ISSUE TITLE
canal源码生成发布包

### ISSUE THREAD

**Issue by jkl0898** [alibaba/canal#1117]
1. 请问如何通过canal 源码生成发布包， 有提供打包的方式吗 ？

**Comment by jkl0898** [comment]
@littleneko Thanks for your replied, but I afraid you haven't get my question.

**Comment by jiacheo** [comment]
1. git 下载源码
2. 进入canal目录， 执行 `mvn clean install -Dmaven.test.skip -Denv=release`
3. 编译完成后，会在target下面生成一个 canal.deploy-xxx.tar.gz 的文件，用tar 解压就能用

4. 以上在wiki里面「启动步骤」那一部分都说明了
