### ISSUE TITLE
当有新的instance加入后且消息需要投入MQ(kafka)时，需要重启canal才会生效

### ISSUE THREAD

**Issue by linweijiang** [alibaba/canal#1125]
当canal server已经启动，有一个instance（instanceA）已经在运行，并且将接收到的binlog数据投递到kafka。

当需要新增instance（instanceB），且该instance也是需要canal server自动将接收到的binlog数据投递到kafka，

这时虽然canal server虽然有启动新的instance，但是将binlog的数据投递到了instanceA对应的kafka topic中去了。

望能完善！

thanks！~

**Comment by agapple** [comment]
@rewerma 可以考虑一下
