### ISSUE TITLE
支持全量同步吗

### ISSUE THREAD

**Issue by wjyheropk** [alibaba/canal#1130]
一般情况下会有初始或定期触发全量同步的需求，以保障两边数据一致，请问这个能支持吗？

**Comment by agapple** [comment]
目前不行,后续可以在client-adapter工程里扩展一下

**Comment by wjyheropk** [comment]
那如何实现全量同步呢，靠同步binlog能实现吗，还是需要select * from来实现？

**Comment by agapple** [comment]
select * from

**Comment by rewerma** [comment]
可以支持全量同步的, 
adapter有全量etl更新的接口, 例如:
curl http://127.0.0.1:8081/etl/hbase/mytest_person2.yml -X POST
@agapple

**Comment by Dearxiaonan** [comment]
2020年了，目前是否已经支持全量同步了

**Comment by Dearxiaonan** [comment]
您好，目前是否已经支持mysql全量迁移了？

**Comment by wo8335224** [comment]
我这勉强支持了，但是不知道够不够提PR，有点粗暴。只适用于数据库镜像模式，即mirrorDb

**Comment by wo8335224** [comment]
我这勉强支持了，但是不知道够不够提PR，有点粗暴。只适用于数据库镜像模式，即mirrorDb=true
@Dearxiaonan

**Comment by MasterXuZ** [comment]
> 我这勉强支持了，但是不知道够不够提PR，有点粗暴。只适用于数据库镜像模式，即mirrorDb=true @Dearxiaonan

方便说明下mirrorDb=true时怎么解决的吗，我想全量库中所有表
