### ISSUE TITLE
canal-1.0.25 版本，数据表结构发生了变更新增加列，消费的时候，出现列跟值不匹配的情况。

### ISSUE THREAD

**Issue by wangjinzhao** [alibaba/canal#1138]
canal-1.0.25 版本，数据表结构发生了变更新增加列，消费的时候，出现列跟值不匹配的情况。删除h2.mv.db 文件后，重启canal后能够对上了，这是一个bug吗？

**Comment by WithLin** [comment]
建议升级到最新版本
