### ISSUE TITLE
启动server后，想再次更改position，只能删除掉之前在zk上注册节点再重启吗？

### ISSUE THREAD

**Issue by jianghaibolxy** [alibaba/canal#1144]
启动server后，想再次更改position，只能删除掉之前在zk上注册节点再重启吗？

**Comment by Velsson** [comment]
修改zk上节点记录的json信息中的position就好了。再次消费时会从那个位置开始的。但要注意别超过处理binlog文件的大小

**Comment by jianghaibolxy** [comment]
好的谢谢
