### ISSUE TITLE
求解！Canal-1.1.1版本,客户端无法获取表名（TableName）

### ISSUE THREAD

**Issue by Charlieblu** [alibaba/canal#1150]
System.out.println(String.format("================&gt; binlog[%s:%s] , name[%s,%s] , eventType : %s",
                    entry.getHeader().getLogfileName(), entry.getHeader().getLogfileOffset(),
                    entry.getHeader().getSchemaName(), entry.getHeader().getTableName(),
                    eventType));

binlog名字 和 位置  操作类型都可以获取到，只有 entry.getHeader().getSchemaName(), entry.getHeader().getTableName() 这两个无法获取

**Comment by Velsson** [comment]
你获取到了binlog记录是不是dml语句或ddl(包含表名)，要是transcation begin或end就没的。

**Comment by agapple** [comment]
LS正解
