### ISSUE TITLE
CanalRocketMQClientExample中空指针问题

### ISSUE THREAD

**Issue by ymwneu** [alibaba/canal#1158]
CanalRocketMQClientExample#process中，如果connector.getListWithoutAck()第一次返回的messages大小为0，则RocketMQCanalConnector中的lastGetBatchMessage仍未null，后续调用connector.ack()时会抛空指针。

**Comment by agapple** [comment]
https://github.com/alibaba/canal/commit/b6f1e0d13c4feb3e93a200688008dad4e5cf6b07
