### ISSUE TITLE
ClientAdapter

### ISSUE THREAD

**Issue by elim051** [alibaba/canal#1161]
[ClientAdapter](https://github.com/alibaba/canal/releases/download/canal-1.1.1/client-adapter.launcher-1.1.1.tar.gz) 下载后并没有 [文档](https://github.com/alibaba/canal/wiki/ClientAdapter)所说的那种目录，没有bin文件夹，请问那些启动脚本从何处找到？谢谢。
还有一个疑问，就是 ClientSample 与ClientAdapter怎么才能整合？

**Comment by rewerma** [comment]
下载最新代码, mvn clean install 将会在 canal/client-adapter/launcher/target/canal-adapter 目录下生成相应的文件
ClientAdapter已经集成了CanalClient及MQClient
