### ISSUE TITLE
mysql修改数据canal一直是TRANSACTIONEND非rowdata

### ISSUE THREAD

**Issue by liangxiaoshanhf** [alibaba/canal#1162]
Message[id=4,entries=[header {
  version: 1
  logfileName: "mysql-bin.000001"
  logfileOffset: 4716
  serverId: 1
  serverenCode: "UTF-8"
  executeTime: 1542636899000
  sourceType: MYSQL
  schemaName: ""
  tableName: ""
  eventLength: 77
}
entryType: TRANSACTIONBEGIN
storeValue: " \002"
, header {
  version: 1
  logfileName: "mysql-bin.000001"
  logfileOffset: 4982
  serverId: 1
  serverenCode: "UTF-8"
  executeTime: 1542636899000
  sourceType: MYSQL
  schemaName: ""
  tableName: ""
  eventLength: 31
}
entryType: TRANSACTIONEND
storeValue: "\022\003349"
],raw=true,rawEntries=[]]

**Comment by agapple** [comment]
1.  数据是否被过滤
2. 数据库的binlog格式
