### ISSUE TITLE
getWithoutAck偶现阻塞

### ISSUE THREAD

**Issue by Kosho1996** [alibaba/canal#1167]
自己在代码里统计的调用耗时，设置了超时时间100ms，偶尔getWithoutAck方法会阻塞一小时左右。

**Comment by Kosho1996** [comment]
1.0.24版本，是不是和这个有关，https://stackoverflow.com/questions/2866557/timeout-for-socketchannel-doesnt-work

**Comment by agapple** [comment]
我记得中间版本有修复过soTimeout，可以升级下版本试试
