### ISSUE TITLE
现在很多时候binlog-format都是mixed

### ISSUE THREAD

**Issue by zhenglu1989** [alibaba/canal#117]
现在很多时候binlog-format都是mixed,以后会支持这类型么

**Comment by agapple** [comment]
目前canal版本解析支持mixed/statement/row格式

**Comment by pencilso** [comment]
> 目前canal版本解析支持mixed/statement/row格式

但是我用1.1.4的canal 对mixed类型不行哎，首先是过滤失效了，其次，监听不到我设置的数据库的变更信息
