### ISSUE TITLE
1.1.1版本，kafka模式,flatMessage为false时,filter.black设置无效

### ISSUE THREAD

**Issue by jackzkage** [alibaba/canal#1172]
**配置如下：**
_**/conf/example/instance.properties 配置**_
canal.instance.filter.black.regex=quartz_db.*

_**/conf/mq.yml 配置**_
flatMessage: false

**现象：**
kafka模式,filter.black设置了过滤quartz_db所有的表:
设置flatMessage为false时,
当quartz_db下的表有更新时还是会向kafka发送消息；

设置flatMessage为true时,
当quartz_db下的表有更新时，则不会向kafka发送消息；

**Comment by rewerma** [comment]
没有发现这样的问题, 过滤规则和kafka的是否flat message投递没有关系. 过滤规则是正则表达式, 看一下是否配置错误.

**Comment by agapple** [comment]
表达式的问题都看一下FAQ

**Comment by wzyzdn** [comment]
设置flatMessage为false时，rocketmq只能接收transaction begin和transaction end，无法收到ROWDATA消息是哪里的问题

**Comment by wzyzdn** [comment]
@agapple 请帮忙解答下
