### ISSUE TITLE
canal client监听另外一台机器上的canal server无法得到binlog变更记录

### ISSUE THREAD

**Issue by shubiao-yao** [alibaba/canal#1181]
恳请大神指点迷津。

首先，我的canal server服务器由以下几点构成：
1. mysql5.6.41
2. canal.deployer-1.1.1   
3. centos6.5
4. ip地址192.168.50.87这台机器
5 .canal对外开放的端口是11111
6. java version "1.8.0_191"

我使用mysql -ucanal -pcanal登录我的mysql数据库，查看mysql相关配置：
![image](https://user-images.githubusercontent.com/32409300/48880033-7f443580-ee49-11e8-9b6f-57e23e475763.png)
![image](https://user-images.githubusercontent.com/32409300/48880065-a3a01200-ee49-11e8-8085-1b5596cb13d1.png)
我使用canal client监听的是xin库下面的user表，表结构如下：
![image](https://user-images.githubusercontent.com/32409300/48880105-d4804700-ee49-11e8-97e3-d40d7bfc796c.png)

我的canal server的 canal/conf/example/instance.properties 配置如下：
![image](https://user-images.githubusercontent.com/32409300/48880751-c4b63200-ee4c-11e8-84d2-350144c03a0d.png)

这是我启动canal server后，并用canal client监听canal server的日志 canal/logs/example/example.log 的日志内容截图
![image](https://user-images.githubusercontent.com/32409300/48879706-f2e54300-ee47-11e8-9c0d-41f8d35f267d.png)

canal client的机器ip是：192.168.90.25 代码如图所示：

![image](https://user-images.githubusercontent.com/32409300/48880878-502fc300-ee4d-11e8-9700-7030626478ee.png)

我使用canal client监听我本地的canal server是可以得到变更的binlog的。 

我mac本地使用的配置是mysql5.7 ，canal server的配置与centos的上一致。

**Comment by agapple** [comment]
过滤条件的问题，先看下FAQ

**Comment by shubiao-yao** [comment]
好的，我根据您的提示，查了下canal过滤条件问题，发现之前有人提过跟我类似的问题，明天我到公司试试，谢谢

**Comment by shubiao-yao** [comment]
![image](https://user-images.githubusercontent.com/32409300/48928181-51c5bd80-ef17-11e8-9f92-95d1b779ef3f.png)
我的过滤规则是这样的 @agapple  尝试修改成了 xin.*    xin\\..* 这两种 也无法解析到binlog日志

**Comment by shubiao-yao** [comment]
这是我canal客户端和服务端的过滤条件配置。现在写成一样了。

![image](https://user-images.githubusercontent.com/32409300/48930755-8c3a5500-ef2d-11e8-80d4-2e496d98895c.png)

![image](https://user-images.githubusercontent.com/32409300/48930768-9ceacb00-ef2d-11e8-851a-378b1c1403dd.png)

![image](https://user-images.githubusercontent.com/32409300/48930793-ca377900-ef2d-11e8-9ce1-3d1f6a820f7b.png)

现在canal客户端还是监控不到canal服务端的日志
