### ISSUE TITLE
关于mq分发到topic和partition规则的建议

### ISSUE THREAD

**Issue by RickJou** [alibaba/canal#1182]
目前想法是一个instance对应mysql中一个database
1目前只能将一个instance配置为一个topic,其可以配置为一个kafka partition或根据 hash[库名.表名.id]到多个kafka partition  

2在某些场景下,如:实时计算某个表中的数据,如果只有一个partition,则会在拉取数据时拉取到大量的其他表的binlog数据;或者根据 hash[库名.表名]分区时,对应的kafka消费者不清楚表的消息到底发送到了那个分区里面,
这种情况也存在预设分区数满了,导致多个表数据进入一个分区的情况;也会出现大量分区空置的情况.

3如果将一个表作为一个instance......那么维护起来非常麻烦

能不能考虑一下可以做成根据数据库中的表生成topic,可选根据主键进行自定义分区数量限制呢

**Comment by agapple** [comment]
最新分支已经支持了

**Comment by RickJou** [comment]
谢谢

**Comment by Bruce2jiang** [comment]
RickJou  你好 canal 1.1.12支持   根据数据库中的表生成topic,可选根据主键进行自定义分区数量  吗
