### ISSUE TITLE
CREATE DATABASE `teacher_data` CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_general_ci'

### ISSUE THREAD

**Issue by ziFieYu** [alibaba/canal#1183]
com.alibaba.fastsql.sql.parser.ParserException: syntax error, error in :'CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4', expect null, actual null, pos 54, line 1, column 46, token LITERAL_CHARS utf8mb4

好像是编码问题 utf8mb4

**Comment by agapple** [comment]
create database没有很好的支持

**Comment by agapple** [comment]
先暂时忽略，create database/create user不影响tablemeta的结构
