### ISSUE TITLE
RocketMQ flatMessage为false时候，解析异常

### ISSUE THREAD

**Issue by cocoZwwang** [alibaba/canal#1184]
RocketMQ flatMessage为false时候，解析异常：Caused by: com.google.protobuf.InvalidProtocolBufferException: Protocol message end-group tag did not match expected tag.
我canal这边有配置flatMessage为false，RocketMQCanalConnector构造参数flatMessage传的也是false。有没有大神解答一下？

**Comment by ihanyong** [comment]
有没有可能是mq里有之前没有消费掉的其它类型消息

**Comment by cocoZwwang** [comment]
> 有没有可能是mq里有之前没有消费掉的其它类型消息

但是我重启了recketMQ 甚至还下了个新的 结果还是一样

**Comment by agapple** [comment]
感觉是你的protobuf版本不对齐吧，你看看是否client和server的版本不一致

**Comment by cocoZwwang** [comment]
是我没把RokectMQ之前的持久化数据清除，删了CommitLog文件之后就可以了
