### ISSUE TITLE
something goes wrong with channel

### ISSUE THREAD

**Issue by whiney** [alibaba/canal#1185]
```
2018-11-22 16:23:07.263 [New I/O server worker #1-12] ERROR c.a.otter.canal.server.netty.handler.SessionHandler - something goes wrong with channel:[id: 0x2287633a, /192.168.33.13:56532 => /192.168.26.246:11111], exception=java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:322)
	at org.jboss.netty.channel.socket.nio.NioWorker.processSelectedKeys(NioWorker.java:281)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:201)
	at org.jboss.netty.util.internal.IoWorkerRunnable.run(IoWorkerRunnable.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```
报和这个错误。参考了
https://github.com/alibaba/canal/issues/289
这个issue 没有解决问题。

我的代码是这样：
```
@PostConstruct
    public void startCanel() {
        Thread   thread = new Thread(new Runnable() {
            public void run() {
                process();
            }
        });
        thread.setUncaughtExceptionHandler(handler);
        thread.start();
    }

    protected void process() {
        // 创建链接
        CanalConnector connector = CanalConnectors.newSingleConnector(new InetSocketAddress(canalHost,
                Integer.valueOf(canalPort)), canalDestination, canalUsername, canalPassword);
        while (true) {
            int batchSize = 1000;
            try {
                connector.connect();
                connector.subscribe(;
                connector.rollback();
                while (true) {
                    Message message = connector.getWithoutAck(batchSize); // 获取指定数量的数据
                    long batchId = message.getId();
                    int size = message.getEntries().size();
                    if (batchId == -1 || size == 0) {
                        try {
                            Thread.sleep(1000);
                        } catch (InterruptedException e) {
                        }
                    } else {
                        printEntry(message.getEntries());
                    }
                    connector.ack(batchId); // 提交确认
                }
            } finally {
                connector.disconnect();
            }
        }
    }
```
每次while(true)的时候，应该重新连接的把。

**Comment by whiney** [comment]
https://github.com/alibaba/canal/issues/640

关注了一下这个，我用的canal 1.1.1 版本。看到了对于超时做了处理。但还是经常报这个错误

**Comment by whiney** [comment]
@Scheduled(fixedDelay = 10)
    @Override
    public void run() {
        // 创建链接
        CanalConnector connector = CanalConnectors.newSingleConnector(new InetSocketAddress(canalHost,
                Integer.valueOf(canalPort)), canalDestination, canalUsername, canalPassword);

        int batchSize = 1000;
        try {
            connector.connect();
            connector.subscribe();
            connector.rollback();
            while (true) {
                Message message = connector.getWithoutAck(batchSize); // 获取指定数量的数据
                long batchId = message.getId();
                int size = message.getEntries().size();
                if (batchId == -1 || size == 0) {
                    try {
                        Thread.sleep(1000);
                    } catch (InterruptedException e) {
                    }
                } else {
                    List<CanalEntry.Entry> entries = message.getEntries();
                    if(entries.size() > 0){
                        entries.forEach(entry -> {
                            if (entry.getEntryType() == CanalEntry.EntryType.ROWDATA) {
                                publishCanalEvent(entry);
                            }
                        });
                    }
                }
                connector.ack(batchId); // 提交确认
            }
        } finally {
            connector.disconnect();
        }
    }

利用定时的方式，不报错了。

**Comment by yygnai** [comment]
> 

感谢问题解决了
