### ISSUE TITLE
canal.destinations没有配置example，但启动时容器会自动加载进去

### ISSUE THREAD

**Issue by bai020** [alibaba/canal#1186]
我用最新的镜像：docker.io/canal/canal-server:v1.1.1
配置的canal.destinations= a1,a2,a3 这样
但是每次启动后还是会把destination=example的也加载进去，容器内也是：
![image](https://user-images.githubusercontent.com/22534679/48893538-8d12ae80-ee7b-11e8-859e-2cb40fff5576.png)
查了下app.sh中有mv操作，请问有办法避免每次都加载example节点吗？
![image](https://user-images.githubusercontent.com/22534679/48893557-9865da00-ee7b-11e8-8f0d-fc336c41653b.png)

**Comment by agapple** [comment]
docker模式canal.destinations只能支持一个

**Comment by bai020** [comment]
抱歉，这个 "canal.destinations只能支持一个” 是什么意思？
就是说这个example必须存在呗？

**Comment by agapple** [comment]
docker模式暂时无法支持-e指定多份配置
