### ISSUE TITLE
canal客户端只返回了已更新的字段，binlog格式为row，也没有在代码作过滤操作

### ISSUE THREAD

**Issue by jinyse** [alibaba/canal#1187]
![image](https://user-images.githubusercontent.com/27431009/48902614-07e7c380-ee94-11e8-96a1-23d8aa56f2a1.png)
有十几二十个字段，但是afterColumnList只有更新过的字段，某些重要的字段并没有返回。

![image](https://user-images.githubusercontent.com/27431009/48902659-2d74cd00-ee94-11e8-8e6c-12eda1f2c6d9.png)
binlog格式为row

![image](https://user-images.githubusercontent.com/27431009/48902678-3c5b7f80-ee94-11e8-8dca-dd167870fb63.png)
canal订阅的格式

![image](https://user-images.githubusercontent.com/27431009/48902701-4da48c00-ee94-11e8-91c6-ebbb8c26f893.png)
并没有做字段的过滤。

所以现在的问题是不知道什么地方过滤了。

**Comment by agapple** [comment]
show variables like 'binlog_image' ， 检查下这个

**Comment by jinyse** [comment]
> show variables like 'binlog_image'

![image](https://user-images.githubusercontent.com/27431009/48926171-85e4b280-ef06-11e8-8c29-4064a273af8f.png)
没有设置值

**Comment by agapple** [comment]
show variables like 'binlog_row_image'，写错，试试这个

**Comment by windyyong** [comment]
请问找到了是什么问题吗,出现同样的情况,现在是id也没有过来,无法跟新
