### ISSUE TITLE
journalName 乱码 

### ISSUE THREAD

**Issue by 724135220** [alibaba/canal#1189]
@apple
数据库版本：5.6.42
![0001](https://user-images.githubusercontent.com/9330886/48912131-c5cc7b00-eeaf-11e8-8c68-11629d6d949f.png)
![0002](https://user-images.githubusercontent.com/9330886/48912134-c7963e80-eeaf-11e8-8aec-97b15e1c1575.png)
![0003](https://user-images.githubusercontent.com/9330886/48912135-c8c76b80-eeaf-11e8-85f5-1abb212c6f9f.png)
![0004](https://user-images.githubusercontent.com/9330886/48912140-cbc25c00-eeaf-11e8-8eab-67a7b38e3a85.png)
第一次启动项目，回进入重连状态，在重连前，获取的journalName的名字是正常的，重连的时候，读取出来的journalName的就出现乱码了，代码debug出来的结果如图所示，请问一下是什么原因，看GitHub上出现这个问题的都是MariaDB，但我的事mysql，所以不知道是什么原因，烦请解释解释，谢谢

**Comment by agapple** [comment]
使用我最新的master分支再测试一下，这两天刚修复过

**Comment by 724135220** [comment]
嗯，谢谢，经过一上午的测试，已经没有问题了，能麻烦之前那样是因为什么原因吗？

**Comment by agapple** [comment]
checksum问题
