### ISSUE TITLE
批处理条数过多,导致消息过大

### ISSUE THREAD

**Issue by RickJou** [alibaba/canal#1190]
如DBA初始化新增表字段
一个delete/update/insert into values(xxx),(xxx),(xxx) 批处理操作时影响了几百万行数据
client会发往MQ的消息中data是一个巨大的数组结构........................可能导致超过消息上限
so........我认为需要进行分为多个消息发送

**Comment by agapple** [comment]
可以获取一下最新的代码，目前已支持设置kafka的发送最大包大小

**Comment by ranqiqiang** [comment]
> batchSize 支持单条发送吗？ 如果设置得很小的情况？ 比如1 ？
