### ISSUE TITLE
通过canal获取sql的问题

### ISSUE THREAD

**Issue by junjie-tang99** [alibaba/canal#1195]
由于项目需要，需要在获取变更数据时，同时能记录下SQL语句。我看com.alibaba.otter.canal.protocol.CanalEntry.RowChange中有一个getSql()方法，但是在数据库上执行了insert、update、delete语句后，无法通过getSql()方法获取SQL语句。
麻烦各位大神帮忙指点下。非常感谢。

**Comment by agapple** [comment]
只有>=5.6，并且my.cnf里开启binlog-rows-query-log-events=true

**Comment by pengyouak** [comment]
数据库版本5.7.28-0ubuntu0.16.04.2-log，开启了binlog-rows-query-log-events，但是com.alibaba.otter.canal.protocol.CanalEntry.RowChange中的Sql 还是没有数据呢？@agapple

**Comment by mossGKX** [comment]
这个问题解决了吗，我的现在也是出现这个问题 ，数据库是5.8 的 ，

mysqld.cnf 配置如下：
**symbolic-links = 0
server-id = 1
log-bin = /var/lib/mysql/mysql-bin
binlog_format = ROW
binlog-rows-query-log-events = true**


但是拿到的 语句明明是update 语句 ，rowChange.getEventType()  确实query 类型的.

求解答？？？？？

**Comment by johnxiaohe** [comment]
> 这个问题解决了吗，我的现在也是出现这个问题 ，数据库是5.8 的 ，
> 
> mysqld.cnf 配置如下：
> **symbolic-links = 0 server-id = 1 log-bin = /var/lib/mysql/mysql-bin binlog_format = ROW binlog-rows-query-log-events = true**
> 
> 但是拿到的 语句明明是update 语句 ，rowChange.getEventType() 确实query 类型的.
> 
> 求解答？？？？？

https://github.com/alibaba/canal/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E8%A7%A3%E7%AD%94第一条就是。需要我们自己判断query中sql类型或者去掉true这个设置。我们自己通过rowdatalist封装生成sql方法

**Comment by catxiong** [comment]
我也有这样的需求，要怎么搞，求助，求助，求助！

**Comment by Singein** [comment]
binlog有三种格式，优缺点如下：

statement-based：优点是技术成熟，日志文件占用空间少，备份和恢复速度快，日志文件可以用于审计数据库。缺点是有些语句不安全或不确定，无法正确复制，比如依赖于随机数或时间戳的语句。
row-based：优点是能够复制所有的数据变化，不受语句的安全性或确定性的影响，避免了触发器和存储过程的级联复制问题。缺点是日志文件占用空间大，可能导致网络带宽和磁盘空间的压力，日志文件不易于人类阅读。
mixed-based：优点是结合了statement-based和row-based的优势，能够根据语句的类型自动切换日志格式，提高了复制的效率和可靠性。缺点是切换日志格式可能导致一些问题，比如临时表的处理，以及在某些情况下无法切换。
简言之，binglog如果是row-based，你是不可能拿得到真正的原始SQL的，如果用statement-based可以，但是大多数生产环境不可能让你改的....放弃吧少年。
