### ISSUE TITLE
Releases v1.1.2版本Mysql新增记录在Kafka多分区模式下报空指针异常

### ISSUE THREAD

**Issue by zhaozhiwei2017** [alibaba/canal#1201]
由于新增Mysql记录时FlatMessage的old属性为null，但是在FlatMessage.messagePartition()没有判断old是否为null直接使用，导致空指针异常，如图
![tim 20181127164014](https://user-images.githubusercontent.com/28380264/49068990-23234c00-f263-11e8-8f38-40f82f410779.png)

**Comment by rewerma** [comment]
tks
