### ISSUE TITLE
就像知道 canal.instance.filter.regex 怎么能让这个配置生效

### ISSUE THREAD

**Issue by dats0407** [alibaba/canal#1206]
本人写python的，不太擅长写java，用的是编译的代码，怎么操作，能让 canal.instance.filter.regex 这个配置能生效？

**Comment by dats0407** [comment]
看了FAQ，还要改源代码，难道还要我修改后 编译一遍吗！？

**Comment by xuminwlt** [comment]
都在配置里，下载deployer包，conf目录有配置，都编译好的程序

**Comment by FCRc** [comment]
file-instance.xml修改这句，过滤会生效但是SQL不在打印，变成了数据
<bean id="eventSink" class="com.alibaba.otter.canal.sink.entry.EntryEventSink">
		<property name="eventStore" ref="eventStore" />
		<property name="filterTransactionEntry" value="${canal.instance.filter.transaction.entry:false}"/>
		<property name="filter">
			<bean class="com.alibaba.otter.canal.filter.aviater.AviaterRegexFilter" >
				<constructor-arg index="0" value="${canal.instance.filter.regex:.*\..*}" />
			</bean>
		</property>
	</bean>

**Comment by FCRc** [comment]
file-instance.xml修改这句，过滤会生效但是SQL不在打印，变成了数据
**<bean id="eventSink" class="com.alibaba.otter.canal.sink.entry.EntryEventSink">
		<property name="eventStore" ref="eventStore" />
		<property name="filterTransactionEntry" value="${canal.instance.filter.transaction.entry:false}"/>
		<property name="filter">
			<bean class="com.alibaba.otter.canal.filter.aviater.AviaterRegexFilter" >
				<constructor-arg index="0" value="${canal.instance.filter.regex:.*\..*}" />
			</bean>
		</property>
	</bean>**

**Comment by FCRc** [comment]
file-instance.xml修改这句，过滤会生效但是SQL不在打印，变成了数据
`<bean id="eventSink" class="com.alibaba.otter.canal.sink.entry.EntryEventSink">
		<property name="eventStore" ref="eventStore" />
		<property name="filterTransactionEntry" value="${canal.instance.filter.transaction.entry:false}"/>
		<property name="filter">
			<bean class="com.alibaba.otter.canal.filter.aviater.AviaterRegexFilter" >
				<constructor-arg index="0" value="${canal.instance.filter.regex:.*\..*}" />
			</bean>
		</property>
	</bean>`
