### ISSUE TITLE
【代码细节】parse阶段已经做了filter，为什么sink阶段还要做filter

### ISSUE THREAD

**Issue by gaoxiangyu** [alibaba/canal#1207]
看了代码，发现parse阶段和sink阶段都有filter的逻辑，sink阶段的filter逻辑是否是没有必要的？

**parse阶段：**
ddl的过滤
![image](https://user-images.githubusercontent.com/8179551/49084501-97251a80-f28a-11e8-805e-a115209152b5.png)
dml的过滤
![image](https://user-images.githubusercontent.com/8179551/49084630-fedb6580-f28a-11e8-83b5-3adebf547db7.png)

**sink阶段：**
![image](https://user-images.githubusercontent.com/8179551/49084772-609bcf80-f28b-11e8-9353-e07ea04c6da1.png)

实际测试了下，不相关的dml也确实不会走到sink阶段。

请问下sink阶段做filter是基于什么考虑？是否可以去掉sink阶段的filter逻辑。

**Comment by agapple** [comment]
现在sink里的filter是NULL，没有启作用。 

早期设计的思路是为支持多client订阅不同表来做的，parser会解析多个client的共同条件，sink可以按照不同的用户filter提前分出多个store，所以会有两层filter的设计
