### ISSUE TITLE
数据不正确

### ISSUE THREAD

**Issue by cjj137783** [alibaba/canal#1209]
![1543369172715](https://user-images.githubusercontent.com/12795327/49123004-e8b4c000-f2f1-11e8-88ee-cef8bf30d1a0.jpg)

详细请参见图，我mysql中的格式是int类型的，但是通过canal接收到的时候，数据居然变成了一个非数字的字符串，这种非字符的字符串在int类型的字段中是不可能录入的到mysql的，所以，应该是canal采集数据的问题吧,我用的是1.0.24的版本，能麻烦看下吗？谢谢

**Comment by cjj137783** [comment]
我检查了下数据，canal是将我的数据读错乱了，这个数据其实是另一个字段的值，这应该是个bug

**Comment by cjj137783** [comment]
> 肯定做过表结构的DDL变更，列对不齐

有没有做过ddl倒是不知道，因为数据库属于另一个开发团队的，这种情况如何解决？

**Comment by ZhichX** [comment]
> 肯定做过表结构的DDL变更，列对不齐

大佬   请问，针对 有表结构DDL变更导致 列对不齐的问题，canal有解决吗？
我们有遇到几次，回放业务库的binlog，重新消费 就会数据错乱
实现上如果不按最新表结构拉取，而是拉取对应时间生效的那个版本的表结构可以吗，同时解析binlog的ALTER消息，是不是可以做到表结构随binlog而更新呢？

**Comment by agapple** [comment]
可以看一下新版本的canal TableMetaTSDB能力，可以回溯到当时binlog里的表结构

**Comment by ZhichX** [comment]
> 可以看一下新版本的canal TableMetaTSDB能力，可以回溯到当时binlog里的表结构

THX！看到了~

**Comment by chenlisong** [comment]
两种可能：
1. 开始监听测试库，然后再监听正式库，然后binlog有存在时间，切换时，canal未监听到ddl语句，所以未更新表结构。
2. 曾经发生了ddl，有可能未被canal监听到。
解决办法：删除db结构文件，让canal重新拉取。
位置：canal/example/canal1/conf/example/h2.mv.db
