### ISSUE TITLE
这个怎么解决啊

### ISSUE THREAD

**Issue by zlandyberg** [alibaba/canal#1210]
![image](https://user-images.githubusercontent.com/23549720/49124307-e739c680-f2f6-11e8-864e-fcc0b6d96aa6.png)
cause by: com.alibaba.otter.canal.protocal.exception.canalClientException: some thing goes wrong with reason:something goes wrong with channel:[id: 0x1536403f, /192.168.41.1:52312 => /192.168.41.1:11111], exception=com.alibaba.otter.canal.meta.exception.CanalMetaManagerException: batchId 37 is not the firstly:35
at com.alibab.otter.canal.client.CanalMessageDeserializer.deserializer

**Comment by agapple** [comment]
了解MQ消息flatMessage=false, 需要使用protobuf来解析数据

**Comment by xmt1139057136** [comment]
这个问题解决了吗？怎么解决的？求分享！！！！

**Comment by ChineseJavaer** [comment]
Java客户端报这个错误怎么解决呢？
