### ISSUE TITLE
请问canal的访问账号和密码怎么配置？

### ISSUE THREAD

**Issue by liuquanal** [alibaba/canal#1214]
`
SimpleCanalConnector connector = new SimpleCanalConnector(
	new InetSocketAddress(
              <host>,
              <port>,
	      <username>, 
              <password>,
	      <dest>)
);
`

这里可以送用户名和密码，但是canal的配置文件里，貌似怎么都找不到用户名和密码的配置。
请问是我哪里理解错了？

如果生产部署canal的话，canal怎么保证自己不被非法客户端连接？除了用户名和密码策略，是否还有其它策略？

**Comment by xuminwlt** [comment]
看了源码，未发现可配置的地方。

**Comment by junjie-tang99** [comment]
自己写在项目的配置文件里面，然后就OK了呀

**Comment by agapple** [comment]
LS正解

**Comment by LewissPan** [comment]
LS，具体配置过程可以给个说明么？多谢啦
需求跟一楼一样，canal client 连 canal server 需用户名密码验证；

**Comment by maguanggit** [comment]
canal账号密码怎么配置, 配置项名称是什么?

**Comment by csoftware** [comment]
这个issues怎么就关闭了呢，没给出明确的解答啊。。。

**Comment by agapple** [comment]
1.1.4版本，在canal.properties里加上这两个配置
```
# canal instance user/passwd
canal.user = canal
canal.passwd = E3619321C1A937C46A0D8BD1DAC39F93B27D4458
```

**Comment by wo8335224** [comment]
@agapple 
在1.1.4 在canal server 加上
canal.user = canal
canal.passwd = E3619321C1A937C46A0D8BD1DAC39F93B27D4458

在客户端加上账号：canal，密码：E3619321C1A937C46A0D8BD1DAC39F93B27D4458

一直报错auth failed for user:canal

见鬼了

**Comment by maguanggit** [comment]
我了解的canal1.3之前的版本都是不支持密码认证的, 1.3之后的就没有了解了, 如果必须认证的话, 你可以改源码完成自己的功能
如果能加密, 麻烦告知我, 谢谢
------------------ 原始邮件 ------------------
发件人: "wo8335224"<notifications@github.com>;
发送时间: 2019年9月5日(星期四) 上午9:53
收件人: "alibaba/canal"<canal@noreply.github.com>;
抄送: "676666590"<676666590@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [alibaba/canal] 请问canal的访问账号和密码怎么配置？ (#1214)




@agapple
 在1.1.4 在canal server 加上
 canal.user = canal
 canal.passwd = E3619321C1A937C46A0D8BD1DAC39F93B27D4458
 
在客户端加上账号：canal，密码：E3619321C1A937C46A0D8BD1DAC39F93B27D4458
 
一直报错auth failed for user:canal
 
见鬼了

**Comment by wo8335224** [comment]
已经解决了。
canal客户端需要明文密码，但是你不能随便输入个JHY123，或者123456，不然就报错

 exception=java.lang.IllegalArgumentException: illegal hex-string: alibaba123      (明文密码)

你必须传的密码是：E3619321C1A937C46A0D8BD1DAC39F93B27D4458这种格式。

然后在mysql中执行select 

password('E3619321C1A937C46A0D8BD1DAC39F93B27D4458')=670B6226BD8EF3A3C35475DB40EAB2EDCA578E34

结果：

canal server配置文件如下

canal.user = canal
canal.passwd = 670B6226BD8EF3A3C35475DB40EAB2EDCA578E34

canal客户端
用户名：canal
密码：E3619321C1A937C46A0D8BD1DAC39F93B27D4458

参考源码
![image](https://user-images.githubusercontent.com/10435131/64306475-716d3480-cfc5-11e9-8d31-9a57c8d16859.png)

**Comment by maguanggit** [comment]
, 感谢告知




------------------ 原始邮件 ------------------
发件人: "wo8335224"<notifications@github.com>;
发送时间: 2019年9月5日(星期四) 上午10:12
收件人: "alibaba/canal"<canal@noreply.github.com>;
抄送: "676666590"<676666590@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [alibaba/canal] 请问canal的访问账号和密码怎么配置？ (#1214)




已经解决了。
 canal客户端需要明文密码，但是你不能随便输入个JHY123，或者123456，不然就报错
 
exception=java.lang.IllegalArgumentException: illegal hex-string: alibaba123      (明文密码)
 
你必须传的密码是：E3619321C1A937C46A0D8BD1DAC39F93B27D4458这种格式。
 
然后在mysql中执行select
 
password('E3619321C1A937C46A0D8BD1DAC39F93B27D4458')=670B6226BD8EF3A3C35475DB40EAB2EDCA578E34
 
结果：
 
canal server配置文件如下
 
canal.user = canal
 canal.passwd = 670B6226BD8EF3A3C35475DB40EAB2EDCA578E34
 
canal客户端
 用户名：canal
 密码：E3619321C1A937C46A0D8BD1DAC39F93B27D4458
 
参考源码

**Comment by youwen21** [comment]
> 已经解决了。
> canal客户端需要明文密码，但是你不能随便输入个JHY123，或者123456，不然就报错
> 
> exception=java.lang.IllegalArgumentException: illegal hex-string: alibaba123 (明文密码)
> 
> 你必须传的密码是：E3619321C1A937C46A0D8BD1DAC39F93B27D4458这种格式。
> 
> 然后在mysql中执行select
> 
> password('E3619321C1A937C46A0D8BD1DAC39F93B27D4458')=670B6226BD8EF3A3C35475DB40EAB2EDCA578E34
> 
> 结果：
> 
> canal server配置文件如下
> 
> canal.user = canal
> canal.passwd = 670B6226BD8EF3A3C35475DB40EAB2EDCA578E34
> 
> canal客户端
> 用户名：canal
> 密码：E3619321C1A937C46A0D8BD1DAC39F93B27D4458
> 
> 参考源码
> ![image](https://user-images.githubusercontent.com/10435131/64306475-716d3480-cfc5-11e9-8d31-9a57c8d16859.png)

我的是1.1.4版本，没有启动admin， 你的这个方法密码验证不能通过了。   是不是下面这个密码验证做了变更？
```
public static final boolean scrambleServerAuth(byte[] token, byte[] pass, byte[] seed)
            throws NoSuchAlgorithmException {
        MessageDigest md = MessageDigest.getInstance("SHA-1");
        md.update(seed);
        byte[] pass1 = md.digest(pass);
        for (int i = 0; i < pass1.length; i++) {
            pass1[i] = (byte) (token[i] ^ pass1[i]);
        }

        md = MessageDigest.getInstance("SHA-1");
        byte[] pass2 = md.digest(pass1);
        return Arrays.equals(pass, pass2);
    }
```

**Comment by lujinke** [comment]
> LS正解

配置文件application.yml里面的密码配置已经没用了，你的账号密码已经写死到数据库里面了，而且admin/admin的密码也无法登录，因为前端直接拦截掉了提示：密码长度必须大于6个字符，正确做法是，使用源码中的SecurityUtil.scrambleGenPass来生产密码字符串，并且更新数据库中对应的password字段，才能正确登录admin

**Comment by 43278047** [comment]
1.随机生成一个 这种长度的 密码 E3619321C1A937C46A0D8BD1DAC39F93B27D4458
2.随便找个数据库执行  select  password('E3619321C1A937C46A0D8BD1DAC39F93B27D4458')  会返回一个 字符串把这个字符串 放到canal.paasword 配置文件里面
3.java客户端链接的时候 直接使用 E3619321C1A937C46A0D8BD1DAC39F93B27D4458
CanalConnector connector = CanalConnectors.newSingleConnector(
                new InetSocketAddress(canalHost, canalPort),
                destination, canalUser,"E3619321C1A937C46A0D8BD1DAC39F93B27D4458");
