### ISSUE TITLE
开启binlog_rows_query_log_events之后，一条sql语句，会获取个两个binlog Entry？

### ISSUE THREAD

**Issue by junjie-tang99** [alibaba/canal#1215]
由于项目需要，需要获取Insert/Update/Delete等具体的SQL语句，但是在开启binlog_rows_query_log_events之后，执行一条Insert语句，可以获取两个binlog Entry对象。一个Entry对象的Event Type是QUERY，另外一个Entry对象的Envent Type是INSERT。并且，只有在Event Type是QUERY的Entry时，才能获取到SQL语句。
我想知道为啥会有这种情况？另外，是否有办法将这两个Entry关联起来？召唤大神！！！！
![image](https://user-images.githubusercontent.com/45141175/49138732-eae74080-f32a-11e8-966c-e2b30e5a7269.png)
![image](https://user-images.githubusercontent.com/45141175/49138269-b8891380-f329-11e8-98eb-ba54007bad99.png)

**Comment by agapple** [comment]
看mysql5.6的binlog格式，理解binlog_rows_query_log_events参数语义
