### ISSUE TITLE
 Could not find first log file name in binary log index file

### ISSUE THREAD

**Issue by shyboy0358** [alibaba/canal#1216]
目前用的是canal.deployer-1.1.2.tar版本。rds oss binlog也做了相应设置。
但是server停18小时之后，还是会出现下列错误：
Received error packet: errno = 1236, sqlstate = HY000 errmsg = Could not find first log file name in binary log index file。

**Comment by agapple** [comment]
重新启动之后，这样的错误会持续几次之后会自动去下载oss  binlog
