### ISSUE TITLE
不同表的数据可以分到不同的topic或者partition

### ISSUE THREAD

**Issue by 362228416** [alibaba/canal#1225]
现在想要不同的表数据能分开订阅，这样订阅端就不会收到其他表的数据，配置了 canal.mq.partitionHash 没有用啊

**Comment by 362228416** [comment]
qq 群加不了，能加下吗

**Comment by rewerma** [comment]
考虑到表的关联关系, 同一库内表间并行消费的话会有数据不一致问题
