### ISSUE TITLE
mysql 针对实例到实例层面的同步，应该选用怎么样的方案？

### ISSUE THREAD

**Issue by Near-Zhang** [alibaba/canal#1226]
- canal + canal_client
好像不支持 rocketmq 作为消息中间件，因此担心在 canal 到 canal_client 之间的网络存在波动时，有丢失数据的可能

- canal + rocketmq + canal_adapter
只能做到表对表之间的数据同步，并且无法同步DDL语句 

请问下大大，应该使用怎么样的方案，能够实现 mysql 实例到实例层面的同步

**Comment by agapple** [comment]
canal + canal_client ，不会丢数据

**Comment by Near-Zhang** [comment]
> canal + canal_client ，不会丢数据

但当前的 canal_client，应该不支持rocketmq作为消息中间件的

咱们使用canal的愿景，是希望通过 canal_server 和  rocketmq +消费端  分别部署在异地，到达一个避免网络波动影响主从同步的效果

如果使用 canal + canal_client，如果没有 mq 来作为跨异地网络的中间件，是不是就相当于通常的主从了呢，

理解可能有不当，请教一下，谢谢

**Comment by rewerma** [comment]
可以扩展adapter功能, adapter是一个自由式的可插拔插件

**Comment by agapple** [comment]
LS正解
