### ISSUE TITLE
HA + MQ 模式下,  主从切换后, CanalMQStarter未启动对应的 destination,  造成events堆积在 eventStore , 未发往对应的消息中间件

### ISSUE THREAD

**Issue by ihanyong** [alibaba/canal#1229]
版本1.1.2。
看代码, CanalMQStarter 在服务拉起时启动相应的线程来处理当前服务上已经运行的 instance 获取的 event， 
如果服务拉起时， 所有的instance 都是备份 ， 就不会有相应的canalMQWork 启动。
 当主服务挂掉， 备份服务的instance 开启， 但没启动对应的 canalMQWork 把拉取 binlog 投送到消息服务。

**Comment by ihanyong** [comment]
你贴的这段代码没有走到，   




![default](https://user-images.githubusercontent.com/8663378/49210794-f86afc00-f3f8-11e8-8bad-6e2ec664637e.png)

**Comment by rewerma** [comment]
嗯,mq.yml配置去掉后产生的问题
