### ISSUE TITLE
Update event被识别为INSERT EVENT当表格存储为ndbcluster同时设置有pk的情况下

### ISSUE THREAD

**Issue by suxingfate** [alibaba/canal#123]
创建这样的表格，这里要同时有PK和ndbcluster engine的指定。只指定其一，不会触发这种情况。
create table test3col(id int(3), name varchar(10), last varchar(10), primary key(id))engine=ndbcluster; 

mysql> insert into test3col values(1,'a','b');
mysql> update test3col set last='c' where id=1;

SimpleCilent打印出来的log，可以发现update命令被认为是insert类型，同时只显示了主键和更新列
================> binlog[log-bin.000001:3946366] , name[cudb_user_data,test3col] , eventType : CREATE
empty count : 1
empty count : 2
empty count : 3
empty count : 4
empty count : 5
empty count : 6
================> binlog[log-bin.000001:3946753] , name[mysql,ndb_apply_status] , eventType : INSERT
server_id : 501    update=true
epoch : 15301516776701952    update=true
log_name :     update=true
start_pos : 0    update=true
end_pos : 0    update=true
================> binlog[log-bin.000001:3946814] , name[cudb_user_data,test3col] , eventType : INSERT
id : 1    update=true
name : a    update=true
last : b    update=true
================> binlog[log-bin.000001:3947108] , name[mysql,ndb_apply_status] , eventType : INSERT
server_id : 501    update=true
epoch : 15301538251538433    update=true
log_name :     update=true
start_pos : 0    update=true
end_pos : 0    update=true
================> binlog[log-bin.000001:3947169] , name[cudb_user_data,test3col] , eventType : INSERT
id : 1    update=true
last : c    update=true

**Comment by agapple** [comment]
1. 只显示主键和变更列，估计和你mysql版本有关，mysql5.6之后支持minial image模式，只会记录变更列和主键
2. 至于update被认为insert，个人初步判断和ndbcluster有关，以前没测试过

**Comment by agapple** [comment]
建议你直接看一下show binlog events看一下对应update sql的binlog对象

**Comment by suxingfate** [comment]
mysql 5.6 

mysql> show binlog events in 'log-bin.000001' from 3960268 limit 100;
+----------------+---------+------------+-----------+-------------+-----------------------------------------+
| Log_name       | Pos     | Event_type | Server_id | End_log_pos | Info                                    |
+----------------+---------+------------+-----------+-------------+-----------------------------------------+
| log-bin.000001 | 3960268 | Write_rows |       501 |     3960329 | table_id: 34                            |
| log-bin.000001 | 3960329 | Write_rows |       501 |     3960368 | table_id: 521 flags: STMT_END_F         |
| log-bin.000001 | 3960368 | Query      |       501 |     3960433 | COMMIT                                  |
| log-bin.000001 | 3960433 | Query      |       501 |     3960497 | BEGIN                                   |
| log-bin.000001 | 3960497 | Table_map  |       501 |     3960560 | table_id: 521 (cudb_user_data.test3col) |
| log-bin.000001 | 3960560 | Table_map  |       501 |     3960622 | table_id: 34 (mysql.ndb_apply_status)   |
| log-bin.000001 | 3960622 | Write_rows |       501 |     3960683 | table_id: 34                            |
| log-bin.000001 | 3960683 | Write_rows |       501 |     3960723 | table_id: 521 flags: STMT_END_F         |
| log-bin.000001 | 3960723 | Query      |       501 |     3960788 | COMMIT                                  |
+----------------+---------+------------+-----------+-------------+-----------------------------------------+
9 rows in set (0.00 sec)

其中
| log-bin.000001 | 3960329 | Write_rows |       501 |     3960368 | table_id: 521 flags: STMT_END_F
对应一个insert 语句
| log-bin.000001 | 3960683 | Write_rows |       501 |     3960723 | table_id: 521 flags: STMT_END_F         
对应一个update语句。

从这里看不出来insert和update的区别。

而针对一张InnoDB的表，可以看到event_type区分为Write_rows和Update_rows

mysql> show binlog events in 'log-bin.000001' from 3960268 limit 100;
+----------------+---------+-------------+-----------+-------------+-----------------------------------------+
| Log_name       | Pos     | Event_type  | Server_id | End_log_pos | Info                                    |
+----------------+---------+-------------+-----------+-------------+-----------------------------------------+
| log-bin.000001 | 3960268 | Write_rows  |       501 |     3960329 | table_id: 34                            |
| log-bin.000001 | 3960329 | Write_rows  |       501 |     3960368 | table_id: 521 flags: STMT_END_F         |
| log-bin.000001 | 3960368 | Query       |       501 |     3960433 | COMMIT                                  |
| log-bin.000001 | 3960433 | Query       |       501 |     3960497 | BEGIN                                   |
| log-bin.000001 | 3960497 | Table_map   |       501 |     3960560 | table_id: 521 (cudb_user_data.test3col) |
| log-bin.000001 | 3960560 | Table_map   |       501 |     3960622 | table_id: 34 (mysql.ndb_apply_status)   |
| log-bin.000001 | 3960622 | Write_rows  |       501 |     3960683 | table_id: 34                            |
| log-bin.000001 | 3960683 | Write_rows  |       501 |     3960723 | table_id: 521 flags: STMT_END_F         |
| log-bin.000001 | 3960723 | Query       |       501 |     3960788 | COMMIT                                  |
| log-bin.000001 | 3960788 | Query       |       501 |     3960852 | BEGIN                                   |
| log-bin.000001 | 3960852 | Table_map   |       501 |     3960915 | table_id: 521 (cudb_user_data.test3col) |
| log-bin.000001 | 3960915 | Table_map   |       501 |     3960977 | table_id: 34 (mysql.ndb_apply_status)   |
| log-bin.000001 | 3960977 | Write_rows  |       501 |     3961038 | table_id: 34                            |
| log-bin.000001 | 3961038 | Write_rows  |       501 |     3961078 | table_id: 521 flags: STMT_END_F         |
| log-bin.000001 | 3961078 | Query       |       501 |     3961143 | COMMIT                                  |
| log-bin.000001 | 3961143 | Query       |       501 |     3961207 | BEGIN                                   |
| log-bin.000001 | 3961207 | Table_map   |       501 |     3961270 | table_id: 521 (cudb_user_data.test3col) |
| log-bin.000001 | 3961270 | Table_map   |       501 |     3961332 | table_id: 34 (mysql.ndb_apply_status)   |
| log-bin.000001 | 3961332 | Write_rows  |       501 |     3961393 | table_id: 34                            |
| log-bin.000001 | 3961393 | Write_rows  |       501 |     3961431 | table_id: 521 flags: STMT_END_F         |
| log-bin.000001 | 3961431 | Query       |       501 |     3961496 | COMMIT                                  |
| log-bin.000001 | 3961496 | Query       |       501 |     3961574 | BEGIN                                   |
| log-bin.000001 | 3961574 | Table_map   |       501 |     3961630 | table_id: 510 (cudb_user_data.test)     |
| log-bin.000001 | 3961630 | Write_rows  |       501 |     3961668 | table_id: 510 flags: STMT_END_F         |
| log-bin.000001 | 3961668 | Xid         |       501 |     3961695 | COMMIT /* xid=17139826 */               |
| log-bin.000001 | 3961695 | Query       |       501 |     3961773 | BEGIN                                   |
| log-bin.000001 | 3961773 | Table_map   |       501 |     3961829 | table_id: 510 (cudb_user_data.test)     |
| log-bin.000001 | 3961829 | Update_rows |       501 |     3961876 | table_id: 510 flags: STMT_END_F         |
| log-bin.000001 | 3961876 | Xid         |       501 |     3961903 | COMMIT /* xid=17139887 */               |
+----------------+---------+-------------+-----------+-------------+-----------------------------------------+

通过binlog的event type无法区分insert和update的情况下，还可以有其他方式区分吗

**Comment by agapple** [comment]
Write_rows/Update_rows/Delete_rows，binlog针对不同的类型会有严格区分，你这里就是记录为insert类型，估计和你选择的ndb存储有关
