### ISSUE TITLE
1.1.2 adapter RdbSyncService同步部分表，NPE异常

### ISSUE THREAD

**Issue by jackzkage** [alibaba/canal#1233]
场景：
对业务库的**所有的表**通过canal-server发送kafka消息；
消费方有很多个，
其中一个消费方是使用adapter同步到rdb，但是我只想同步tb_user表过来；

这时adapter的RdbSyncService 81行会报空指针错误，因为发来的消息中的表没有匹配到rdb的表映射；
能否修改下？如果没有匹配到就弃掉消息呢？

![image](https://user-images.githubusercontent.com/3030294/49213719-dd4fba80-f3ff-11e8-9bc3-5a5f263e9927.png)

**Comment by rewerma** [comment]
更最新代码,已解决
