### ISSUE TITLE
canal.adapter-1.1.2.tar.gz  spring jar 版本问题

### ISSUE THREAD

**Issue by ihanyong** [alibaba/canal#1234]
V1.1.2的release包 [canal.adapter-1.1.2.tar.gz](https://github.com/alibaba/canal/releases/download/canal-1.1.2/canal.adapter-1.1.2.tar.gz)   lib里 有些spring 依赖掺杂的有 3.2.18.RELEASE 的包， 启动不了。

 源码打包出来的话都是5.0.5.RELEASE， 没有问题。

![default](https://user-images.githubusercontent.com/8663378/49263328-049c9b00-f485-11e8-8c43-ae374df5d6db.png)

**Comment by agapple** [comment]
最新的代码已修复,打包问题
