### ISSUE TITLE
canal中解析的日志包含用户信息么？或者binlog中包含用户信息么？

### ISSUE THREAD

**Issue by theonesmx** [alibaba/canal#1235]
binlog中有没有包含用户信息，例如userA向表A中insert一条语句，binlog中是否解析出此insert是userA操作的，从而可以针对用户进行过滤等

**Comment by agapple** [comment]
没有的

**Comment by theonesmx** [comment]
好吧

**Comment by LOpSSH** [comment]
有什么折中的方案来实现传递业务系统的自定义字段吗？例如某一次数据变更可以联系到业务系统中的某个操作员的ID。
