### ISSUE TITLE
binlog消费跟不上，如何配置资源

### ISSUE THREAD

**Issue by JSK520** [alibaba/canal#1236]
问题：
消费binlog速度跟不上，于是我设置三个配置：
1、jvm ：startup.sh的参数 -Xms14336m -Xmx16384m -Xmn5461m   后面的为默认值
2、canal.instance.memory.buffer.size = 32768
3、network
canal.instance.network.receiveBufferSize = 32768
canal.instance.network.sendBufferSize = 32768

最后发现，canal server内存最大使用5.5g，但binlog消费依旧跟不上，为什么不使用xms的内存？

提问：
1、资源配置是否有最优方案或建议？
2、binlog消费跟不上与什么原因有关，暂觉得与server 和 client 的内存配置有关？

以上，希望得到大神的解答，thanks~

**Comment by agapple** [comment]
消费跟不上，你看了是canal server还是canal client哪块性能不足没？

**Comment by JSK520** [comment]
@agapple 目前从client切入。想问下：
client是主动拉取server数据，server相当于缓存数据的中间件嘛？

**Comment by agapple** [comment]
理解正确
