### ISSUE TITLE
关于canal zk 指定位置重复消费

### ISSUE THREAD

**Issue by bingzhan0613** [alibaba/canal#1238]
canal zk三台集群，在主canal 的实例中，我配置了
canal.instance.master.address 
canal.instance.master.journal.name
canal.instance.master.position
为什么消费还是接着最新的位置消费呢？
没有按照我给定的位置消费？
该怎么配置，可以现实重新消费数据呢？

**Comment by agapple** [comment]
多看下wiki，需要清理一下zk的位点
