### ISSUE TITLE
mariadb中 AnnotateRowsEvent 和 canal 设置当前session变量，是否有具体操作步骤

### ISSUE THREAD

**Issue by Charlieblu** [alibaba/canal#1239]
Canal关于对于mariadb中的日志解析，只是做了一个大概的描述，没有说明具体操作

1. AnnotateRowsEvent使用

mariadb需要在my.cnf中设置binlog_annotate_row_events = true，开启记录annotate事件
canal在发送COM_BINLOG_DUMP指令中需要设置binlog_flags |= BINLOG_SEND_ANNOTATE_ROWS_EVENT，不然mariadb默认不会发送AnnotateRowsEvent，而是以空的QueryLogEvent来代替.

2. 新增的binlog类型使用

canal需要设置当前session变量
SET @mariadb_slave_capability='" + LogEvent.MARIA_SLAVE_CAPABILITY_MINE + "'"

### 请问是如何操作的

**Comment by agapple** [comment]
你不用关心，canal代码里已经处理好了，这个文档只是告诉其他做类似mariadb的binlog解析时需要额外做的工作时啥

**Comment by Charlieblu** [comment]
但是我EventType只能获取Query类型的日志，其它类型的都无法获取

**Comment by Charlieblu** [comment]
> 你不用关心，canal代码里已经处理好了，这个文档只是告诉其他做类似mariadb的binlog解析时需要额外做的工作时啥

但是我EventType只能获取Query类型的日志，其它类型的都无法获取

**Comment by agapple** [comment]
多看FAQ

**Comment by mortimer-cra** [comment]
@agapple 我FAQ看了N遍，现在也是这个问题，请大神指出问题在哪？
