### ISSUE TITLE
canal 推送到liunx上的rocketMQ 失败

### ISSUE THREAD

**Issue by cocoZwwang** [alibaba/canal#1241]
canal 推送到liunx上的rocketMQ 失败，首先topic无法自动创建，broker有设置autoCreateTopicEnable为true，收到创建tpoic后，能连接但是无法推送数据，但是windwos上运行的rocketMQ就行，有没有大神解答一下

**Comment by duhengforever** [comment]
@cocoZwwang 手工创建一下topic试一下。

**Comment by flackyang** [comment]
手动创建了名称为example的 topic还是不行，一直报org.apache.rocketmq.client.exception.MQClientException: No route info for this topic, example错误

**Comment by agapple** [comment]
建议测试一下最新的1.1.3 alpha-3版本,可以自动创建topic

**Comment by wzyzdn** [comment]
> 建议测试一下最新的1.1.3 alpha-3版本,可以自动创建topic

目前用的1.1.5还是不能自动创建topic，手动创建后也不能正常生产，而且canal相关日志并没有报错
