### ISSUE TITLE
怎么把canal内嵌到应用里

### ISSUE THREAD

**Issue by 362228416** [alibaba/canal#1242]
请教一下，怎么把canal内嵌到应用里，就是把订阅端跟canal绑定在一起启动

**Comment by 362228416** [comment]
按照测试用例写了一个启动类，启动了，但是一直获取不到数据。

**Comment by zwangbo** [comment]
@362228416 使用CanalServerWithEmbedded这个类

**Comment by 362228416** [comment]
@zwangbo 
我用的是测试用例的代码，在最新版跑起来，能捕获到binlog，但是获取到数据是null，提示 data is null，不止为何

**Comment by zwangbo** [comment]
mysql binlog用的row模式吗

**Comment by 362228416** [comment]
@zwangbo 
我改变数据的时候，会打印这个，说明有收到log，但是没有数据，用 OpenReplicator 却可以拿到数据
[main] DEBUG c.a.o.c.s.e.CanalServerWithEmbedded - get successfully, clientId:1 batchSize:11 but result is null

**Comment by zwangbo** [comment]
[main] DEBUG c.a.o.c.s.e.CanalServerWithEmbedded - get successfully, clientId:1 batchSize:11 but result is null  
这个日志是指的MemoryEventStoreWithBuffer中的tryGet方法拿出了空的Events，不代表拉取到了数据哦，只能说明buffer中是empty状态

**Comment by 362228416** [comment]
@zwangbo 
能否给出个栗子呢，我的数据库配置应该是没错的，直接下载 canal.deployer 能拿到数据，但是内嵌的拿不到，客户端配置比较多，试了很久，没什么进展

**Comment by agapple** [comment]
学会看测试用例

**Comment by awenzhangc** [comment]
@362228416 
你好，我和你遇到一样的问题
问下你现在是怎么解决的？

**Comment by zender-projects** [comment]
请问最终是怎么解决的这个问题？ 我也碰到了

**Comment by EmDark** [comment]
ps吐槽一下: 各位大哥的解决完了也贴出来一下啊, 真的服气了, 最后还是要自己解决
@362228416  大哥你的FILETER 写错了吧  你的原版代码  
`protected static final String FILTER = ".*";`
改成这样就行了

附上 官方说明
  * 多个正则之间以逗号(,)分隔，转义符需要双斜杠(\\)
     *
     *
     * 常见例子：
     *
     * 1.  所有表：.*   or  .*\\..*
     * 2.  canal schema下所有表： canal\\..*
     * 3.  canal下的以canal打头的表：canal\\.canal.*
     * 4.  canal schema下的一张表：canal\\.test1
     *
     * 5.  多个规则组合使用：canal\\..*,mysql.test1,mysql.test2 (逗号分隔)

**Comment by EmDark** [comment]
@awenzhangc  @zender-projects  @zzllkk2003  不知道你们现在解决没有,  我刚解决了, 希望对你们有帮助
