### ISSUE TITLE
canal.instance.filter.regex没生效

### ISSUE THREAD

**Issue by jbshen** [alibaba/canal#1243]
已经看过关于正则表达式的FAQ了，下面是关于过滤表的配置
canal.instance.filter.regex=bi.small_loan_borrow
在kafka中按理说只有这一个表的更新数据，但是kafka里有所有的表的更新数据。
请大佬帮忙解答一下！！！

**Comment by jbshen** [comment]
还有一个问题，就是kafka里面保存的是：
{"data":null,"database":"","es":1543723390000,"id":1,"isDdl":false,"mysqlType":null,"old":null,"sql":"UPDATE `JOB_EXECUTION_LOG` SET `is_success` = 1, `complete_time` = '2018-12-02 12:03:00.017' WHERE id = 'eb2e855f-f9a3-4bb2-8496-3d5aab3bd91b'","sqlType":null,"table":"JOB_EXECUTION_LOG","ts":1543727446802,"type":"QUERY"}
{"data":null,"database":"","es":1543723390000,"id":1,"isDdl":false,"mysqlType":null,"old":null,"sql":"UPDATE `JOB_EXECUTION_LOG` SET `is_success` = 1, `complete_time` = '2018-12-02 12:03:00.027' WHERE id = 'f09dc4d6-5355-4da6-b9c5-c75e72e4f656'","sqlType":null,"table":"JOB_EXECUTION_LOG","ts":1543727446802,"type":"QUERY"}
{"data":null,"database":"","es":1543723390000,"id":1,"isDdl":false,"mysqlType":null,"old":null,"sql":"UPDATE `JOB_EXECUTION_LOG` SET `is_success` = 1, `complete_time` = '2018-12-02 12:03:00.022' WHERE id = 'daba8475-1b0d-47a7-9fdf-4903888bd79c'","sqlType":null,"table":"JOB_EXECUTION_LOG","ts":1543727446802,"type":"QUERY"}
{"data":null,"database":"","es":1543723390000,"id":1,"isDdl":false,"mysqlType":null,"old":null,"sql":"UPDATE `JOB_EXECUTION_LOG` SET `is_success` = 1, `complete_time` = '2018-12-02 12:03:00.022' WHERE id = '4c77f36c-49b0-4705-befc-909d06cf4297'","sqlType":null,"table":"JOB_EXECUTION_LOG","ts":1543727446802,"type":"QUERY"}

data、sqlType,old字段都是空的，是哪里还需要配置吗？

**Comment by 362228416** [comment]
客户端 调用 connector.subscribe 会覆盖服务端的 filter

**Comment by jbshen** [comment]
我不用客户端消费可以吗？比如我用spark消费server端存放在kafka里面的消息。

**Comment by jbshen** [comment]
这个参数对于server端没有作用，只是对于client端进行过滤的吗？

**Comment by 362228416** [comment]
有效的吧，格式是： 数据库.表名   
我试过是可以的，如果有客户端订阅的话，客户端会覆盖server的filter，没有订阅则以服务端为主
我试过发到kafka这种模式，我用的版本是 1.1.2 没有问题

**Comment by jbshen** [comment]
需要我把我的配置文件贴出来看一下吗？如果配置文件没问题的话，是不是跟mysql的版本也有关系？

**Comment by 362228416** [comment]
我在是5.6上面跑的

**Comment by jbshen** [comment]
5.6.36 我的是这个，要不我还是把配置文件贴出来，您给看看吧

**Comment by 362228416** [comment]
我也不是特别懂，我也遇到问题了。不一定能帮上你

**Comment by jbshen** [comment]
**canal.properties配置文件**
#################################################
######### 		common argument		############# 
#################################################
canal.id = 1
canal.ip =
canal.port = 111111
canal.metrics.pull.port = 11112
canal.zkServers = hadoop02:2181,hadoop03:2181,hadoop05:2181
# flush data to zk
canal.zookeeper.flush.period = 1000
canal.withoutNetty = false
# tcp, kafka, RocketMQ
canal.serverMode = kafka
# flush meta cursor/parse position to file
canal.file.data.dir = ${canal.conf.dir}
canal.file.flush.period = 1000
## memory store RingBuffer size, should be Math.pow(2,n)
canal.instance.memory.buffer.size = 16384
## memory store RingBuffer used memory unit size , default 1kb
canal.instance.memory.buffer.memunit = 1024 
## meory store gets mode used MEMSIZE or ITEMSIZE
canal.instance.memory.batch.mode = MEMSIZE
canal.instance.memory.rawEntry = true

## detecing config
canal.instance.detecting.enable = false
#canal.instance.detecting.sql = insert into retl.xdual values(1,now()) on duplicate key update x=now()
canal.instance.detecting.sql = select 1
canal.instance.detecting.interval.time = 3
canal.instance.detecting.retry.threshold = 3
canal.instance.detecting.heartbeatHaEnable = false

# support maximum transaction size, more than the size of the transaction will be cut into multiple transactions delivery
canal.instance.transaction.size =  1024
# mysql fallback connected to new master should fallback times
canal.instance.fallbackIntervalInSeconds = 60

# network config
canal.instance.network.receiveBufferSize = 16384
canal.instance.network.sendBufferSize = 16384
canal.instance.network.soTimeout = 30

# binlog filter config
canal.instance.filter.druid.ddl = true
canal.instance.filter.query.dcl = true
canal.instance.filter.query.dml = false
canal.instance.filter.query.ddl = false
canal.instance.filter.table.error = true
canal.instance.filter.rows = false
canal.instance.filter.transaction.entry = true

# binlog format/image check
#canal.instance.binlog.format = ROW,STATEMENT,MIXED 
canal.instance.binlog.format = ROW
canal.instance.binlog.image = FULL,MINIMAL,NOBLOB

# binlog ddl isolation
canal.instance.get.ddl.isolation = false

# parallel parser config
canal.instance.parser.parallel = true
## concurrent thread number, default 60% available processors, suggest not to exceed Runtime.getRuntime().availableProcessors()
#canal.instance.parser.parallelThreadSize = 16
## disruptor ringbuffer size, must be power of 2
canal.instance.parser.parallelBufferSize = 256

# table meta tsdb info
canal.instance.tsdb.enable = true
canal.instance.tsdb.dir = ${canal.file.data.dir:../conf}/${canal.instance.destination:}
canal.instance.tsdb.url = jdbc:h2:${canal.instance.tsdb.dir}/h2;CACHE_SIZE=1000;MODE=MYSQL;
canal.instance.tsdb.dbUsername = canal
canal.instance.tsdb.dbPassword = canal
# dump snapshot interval, default 24 hour
canal.instance.tsdb.snapshot.interval = 24
# purge snapshot expire , default 360 hour(15 days)
canal.instance.tsdb.snapshot.expire = 360

# aliyun ak/sk , support rds/mq
canal.aliyun.accesskey =
canal.aliyun.secretkey =

#################################################
######### 		destinations		############# 
#################################################
canal.destinations = hexin_bill
# conf root dir
canal.conf.dir = ../conf
# auto scan instance dir add/remove and start/stop instance
canal.auto.scan = true
canal.auto.scan.interval = 5
canal.instance.tsdb.spring.xml = classpath:spring/tsdb/h2-tsdb.xml
#canal.instance.tsdb.spring.xml = classpath:spring/tsdb/mysql-tsdb.xml

canal.instance.global.mode = spring
canal.instance.global.lazy = false
#canal.instance.global.manager.address = 127.0.0.1:1099
#canal.instance.global.spring.xml = classpath:spring/memory-instance.xml
canal.instance.global.spring.xml = classpath:spring/file-instance.xml
#canal.instance.global.spring.xml = classpath:spring/default-instance.xml

##################################################
######### 		     MQ 		     #############
##################################################
canal.mq.servers = hadoop03:9092,hadoop05:9092
canal.mq.retries = 0
canal.mq.batchSize = 16384
canal.mq.maxRequestSize = 1048576
canal.mq.lingerMs = 1
canal.mq.bufferMemory = 33554432
canal.mq.canalBatchSize = 50
canal.mq.canalGetTimeout = 100
canal.mq.flatMessage = true
canal.mq.compressionType = none
canal.mq.acks = all




instance.properties文件


#################################################
## mysql serverId , v1.0.26+ will autoGen 
# canal.instance.mysql.slaveId=0

# enable gtid use true/false
canal.instance.gtidon=false

# position info
canal.instance.master.address=172.16.0.142:3307
canal.instance.master.journal.name=
canal.instance.master.position=
canal.instance.master.timestamp=
canal.instance.master.gtid=

# rds oss binlog
canal.instance.rds.accesskey=
canal.instance.rds.secretkey=
canal.instance.rds.instanceId=

# table meta tsdb info
canal.instance.tsdb.enable=false
#canal.instance.tsdb.url=jdbc:mysql://127.0.0.1:3306/canal_tsdb
#canal.instance.tsdb.dbUsername=canal
#canal.instance.tsdb.dbPassword=canal

#canal.instance.standby.address =
#canal.instance.standby.journal.name =
#canal.instance.standby.position =
#canal.instance.standby.timestamp =
#canal.instance.standby.gtid=

# username/password
canal.instance.dbUsername=debezium
canal.instance.dbPassword=debezium
canal.instance.connectionCharset =UTF-8
canal.instance.defaultDatabaseName =bi
# enable druid Decrypt database password
canal.instance.enableDruid=false
#canal.instance.pwdPublicKey=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALK4BUxdDltRRE5/zXpVEVPUgunvscYFtEip3pmLlhrWpacX7y7GCMo2/JM6LeHmiiNdH1FWgGCpUfircSwlWKUCAwEAAQ==

# table regex
canal.instance.filter.regex=bi.small_loan_borrow
# table black regex
canal.instance.filter.black.regex=

# mq config
canal.mq.topic=bills_his
canal.mq.partition=0
# hash partition config
#canal.mq.partitionsNum=3
#canal.mq.partitionHash=mytest.person:id,mytest.role:id
#################################################

**Comment by fqybzhangji** [comment]
canal.instance.filter.query.dml = false  修改成  canal.instance.filter.query.dml = true  看看是不是你想要的 FAQ里面有这个

**Comment by cyhbyw** [comment]
> 我也遇到这个问题了，会把所有表的操作都发给kafka，最后咋解决的呢

我也遇到这个问题了

首先确认一下是不是 binlog_rows_query_log_events=ON 这个开关打开了，如果不是的话就跳过
如果是的话，修改这一行配置 canal.instance.filter.query.dml = true （默认为 false，改为 true）试试
参见：https://github.com/alibaba/canal/issues/4265
