### ISSUE TITLE
canal只能同步eventType：Query类型的数据，不能同步其它类型的，求解决

### ISSUE THREAD

**Issue by Charlieblu** [alibaba/canal#1244]
环境：
    canal版本：1.1.1
    mariadb版本：10.2.x

现在出现的问题是，可以同步数据，但只能同步eventType：Query类型的，其它的都无法获取，同步回来的的数据，内容缺少schemaName  和 tableName

###########version: 1
logfileName: "mysql-bin.000004"
logfileOffset: 2096618
serverId: 86
serverenCode: "UTF-8"
executeTime: 1543819484000
sourceType: MYSQL
schemaName: ""
tableName: ""
eventLength: 6296
eventType: QUERY

**Comment by agapple** [comment]
多看WIKI里的FAQ
