### ISSUE TITLE
HA启动问题

### ISSUE THREAD

**Issue by wjyheropk** [alibaba/canal#1249]
设置zookeeper以HA方式启动，第一个实例正常启动工作，但第二个实例启动后就自动停掉了，debug看ServerRunningMonitor在执行initRunning时，创建zk临时节点失败，进入ZkNodeExistsException分支，最后赋值了activeData，然后程序就退出了，请问这是什么原因？

另外我看到代码里ServerRunningMonitor.waitForActive()方法没有被调用到，请问这个正常吗？

**Comment by agapple** [comment]
HA是一个热备模式

**Comment by wjyheropk** [comment]
> HA是一个热备模式

所以第二个实例不应该自动退出吧，应该一直阻塞等待zk的事件

**Comment by wjyheropk** [comment]
补充一下：canal.serverMode = kafka

**Comment by agapple** [comment]
#1229, 确认一下是否这个问题？
