### ISSUE TITLE
canal 1.0.20与otter.canal-client 1.0.20使用的protobuf版本不同

### ISSUE THREAD

**Issue by smilingleo** [alibaba/canal#125]
一个是2.4.1一个是2.5，导致用canal-client连接 canal时报错：
```java
java.lang.UnsupportedOperationException: This is supposed to be overridden by subclasses.
        at com.google.protobuf.GeneratedMessage.getUnknownFields(GeneratedMessage.java:180) ~[protobuf-java-2.5.0.jar:na]
```

**Comment by agapple** [comment]
目前canal和otter使用的protobuf版本均为2.4.1.  目前看来是2.4.1生成的class，2.5无法支持，需要测试使用2.5之后，部分老版本用户使用2.4.1版本是否可以正常使用

**Comment by smilingleo** [comment]
问题是在maven repository里面，canal.protocol的dependency中protobuf没有指定版本：
http://search.maven.org/#artifactdetails%7Ccom.alibaba.otter%7Ccanal.protocol%7C1.0.20%7Cjar
```xml
       <dependency>
            <groupId>com.google.protobuf</groupId>
            <artifactId>protobuf-java</artifactId>
        </dependency>
```
默认会用2.5.0

**Comment by agapple** [comment]
https://repo1.maven.org/maven2/com/alibaba/otter/canal/1.0.20/canal-1.0.20.pom，父工程会显示声明protobuf版本为2.4.1

**Comment by chaopengio** [comment]
在pom里面更改protobuf版本，然后再本地重新生成protocol文件放到protocol/src/main/java/com/alibaba/otter/canal/protocol/里面，可以解决这个问题。或者直接clone我的代码 https://github.com/chaopengio/canal

**Comment by agapple** [comment]
https://github.com/alibaba/canal/commit/c86fba6092979c4d42734903829843c3d62342ae，有人已经提交了PR，升级到了2.6.1
