### ISSUE TITLE
批量更新数据库时，canal不稳定或报错

### ISSUE THREAD

**Issue by jinyse** [alibaba/canal#1250]
![image](https://user-images.githubusercontent.com/27431009/49485435-ffb95c00-f875-11e8-94b0-8d839f75aa7f.png)
经常会有对数据库进行批量操作时canal会挂掉，或者消费很慢很慢

**Comment by jinyse** [comment]
加大堆内存后，现在消费1秒钟消费1,2条，有办法可以加快速度吗，或者排查问题吗

**Comment by agapple** [comment]
1. 确认一下canal版本
2. jvm gc stat (canal server/client)

**Comment by jinyse** [comment]
@agapple canal版本是1.0.24

**Comment by agapple** [comment]
有新的反馈再reopen
