### ISSUE TITLE
canal启动正常，客户端没有消费

### ISSUE THREAD

**Issue by szjackwyc** [alibaba/canal#1251]
![image](https://user-images.githubusercontent.com/15084501/49500515-d7e4eb00-f8ab-11e8-916f-421b9c42e24e.png)

canal 1.1.1版本 mysql 5.7

**Comment by agapple** [comment]
connection reset by peer , 估计是get/ack之间空闲时间过长被服务端给关闭了

**Comment by ChrisZjf** [comment]
怎么解决的？
