### ISSUE TITLE
begin to find start position, it will be long time for reset or first position

### ISSUE THREAD

**Issue by 362228416** [alibaba/canal#1254]
begin to find start position, it will be long time for reset or first position
首次启动超级慢，有什么办法能快一点，手动填了
canal.instance.master.journal.name=mysql-bin.002531
canal.instance.master.position=149641215
canal.instance.master.timestamp=
没有效果
上面mysql参数是 show master status 得到的，timestamp 不知道从哪里来

**Comment by agapple** [comment]
timestamp是数据对应的时间戳，第一次启动会基于offest收集对应的时间戳，所以启动会比较慢

**Comment by everydata** [comment]
初始化的逻辑，是不是还有优化的余地，
com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser
第746行
mysqlConnection.seek(searchBinlogFile, 4L, endPosition.getGtid(), new SinkFunction<LogEvent>() {
这里的 4L 是不是可以改成 endPosition.getPosition()

**Comment by zl-pangu** [comment]
搜了一圈好像没人说解决这个问题的办法，用canal进行测试的时候，启动canal，查看日志和进程都是正常的，但是我修改数据库，发现MQ里面topic没有创建消息也没收到。

于是查看canal的日志，发现有个警告：
`WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - ---> begin to find start position, it will be long time for reset or first position
`
大概就是需要花很长的时间去找到这个同步开始的位置。
我去mysql，show processlist;和show master status；发现都是正常的。
timestamp 刚开始不知道是什么，没设置。再次启动还是找了半天还是没同步好。
于是我尝试timestamp 设置为当前的时间戳（毫秒），再次启动，修改数据，MQ有我刚刚修改过的数据了。

**Comment by TKYV** [comment]
请问，这个问题最后怎么解决的？
