### ISSUE TITLE
1.1.2 alibaba_rds_row_id 解析错误

### ISSUE THREAD

**Issue by towFish** [alibaba/canal#1256]
rds用1.1.2版本的canal，表没有主键的情况下，会从tableMeta里面获取最后一列，导致异常：
com.alibaba.otter.canal.parse.exception.CanalParseException: parse row data failed.
Caused by: com.alibaba.otter.canal.parse.exception.CanalParseException: parse row data failed.
Caused by: java.lang.IndexOutOfBoundsException

**Comment by agapple** [comment]
RDS 5.7 ?

**Comment by towFish** [comment]
5.6

**Comment by towFish** [comment]
LogEventConvert:640这里

**Comment by agapple** [comment]
@towFish 我手头没有RDS，你可以用我最新代码测试一下
