### ISSUE TITLE
关于hash分区的问题

### ISSUE THREAD

**Issue by ZSH9053** [alibaba/canal#1259]
# mq config
canal.mq.topic=XXXXXX
#canal.mq.partition=0
# hash partition config
canal.mq.partitionsNum=4
canal.mq.partitionHash=？？？？
关于这个canal.mq.partitionHash的问题，如果我需要投递我所有的表，那我如何写？
或者，我需要我的部分表，他们的主键都是ID，如何写？
最后，如果我的部分表的主键是ID，另一部分是NAME,如何写？
麻烦大神解答下，谢谢！

**Comment by agapple** [comment]
最新版本1.1.3, 配置格式：schema.table#pk1^pk2，多个配置之间使用逗号分隔
* 例子1：test\.test#pk1^pk2 指定匹配的单表，对应的hash字段为pk1 + pk2
* 例子2：.\..#id 正则匹配，指定所有正则匹配的表对应的hash字段为id
* 例子3：.\.. ，正则匹配，指定所有正则匹配的表对应的hash字段为表主键(自动查找)

静待正式版发布吧
