### ISSUE TITLE
Canal有计划支持基于GTID去做数据同步么

### ISSUE THREAD

**Issue by dawnbreaks** [alibaba/canal#126]
如果MySQL使用VIP是去HA，当MYSQL发生主从切换的时候，canal会可能会报错，因为和备机上的binlog和position对不上。如果是基于GTID去拉binlog，应该就能解决这个问题。

**Comment by agapple** [comment]
基于主备复制的mysql，GTID可以解决切换后位点查找的问题，技术上可以实现，具体时间不可保证

**Comment by dawnbreaks** [comment]
嗯，明白。感谢@agapple 同学。代码提交的时候关下这个issue，好让我知道去试用下。

**Comment by archerwq** [comment]
这个进展如何呢？有计划支持么

**Comment by haitaoyao** [comment]
@agapple 所以就是迄今为止 canal 也没有支持 GTID 是么?

**Comment by cloudAndMonkey** [comment]
请问现在支持GTID？

**Comment by agapple** [comment]
暂时没有，期待有完成的同学贡献一个PR

**Comment by dawnbreaks** [comment]
很久以前我完成了这个功能，代码略糙，没法PR

**Comment by hiwjd** [comment]
我在1.0.25的基础上增加了GTID的支持，需要帮助review。

## 改动说明

1. 增加instance级配置`gtidon`，指示该instance是否启用GTID模式。
2. driver包增加GTID相关类：`GTIDSet`，`UUIDSet`是GTID表示，`BinlogDumpGTIDCommandPacket`是`COM_BINLOG_DUMP_GTID`命令。
3. 补全dbsync包下的`GtidLogEvent`事件的解析。
4. protocol包下，增加了`EntryType`枚举项`GTIDLOG`，是binlog流中的GTIDLOG事件；`Header`增加了字段`gtid`，这里后面单独段落详细说明。
5. parse包下，`ErosaConnection`增加根据GTID同步的dump方法。
6. parse包下，`AbstractEventParser.start内`，如果instance使用GTID模式，则发送`COM_BINLOG_DUMP_GTID`命令给mysql。

## 关于`CanalEntry.Header`增加`gtid`字段

slave通过文件位点的方式同步binlog时，每个事件头里都携带了filename,position信息，后续存储最新同步位点只要取客户端ack过的最后一条事件的filename,position即可。

对应的，GTID模式则需要记录消费过的[GTIDSet](https://dev.mysql.com/doc/refman/5.7/en/replication-gtids-concepts.html)。

一个事务提交后，slave收到如下一连串事件，`GTID_LOG`，`TRANSACTIONBEGIN`，`ROWDATA`，`TRANSACTIONEND`，其中只有`GTID_LOG`有本次事务的GTID信息。现在通过`com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvertGTID`类，记录合并最后一个GTID，并赋值给后续事件的Header.gtid。

**Comment by hiwjd** [comment]
@agapple com.alibaba.fastsql包2.0.0_preview_228版可以提供一份吗？

**Comment by hiwjd** [comment]
@agapple com.alibaba.fastsql包2.0.0_preview_228版可以提供一份吗？

**Comment by agapple** [comment]
@hiwjd 在alpha的二进制包里有一份fastsql的jar

**Comment by agapple** [comment]
gtid的PR已经合并了，非常感谢 @hiwjd 的贡献

**Comment by agapple** [comment]
https://dev.mysql.com/doc/refman/5.7/en/replication-mode-change-online-enable-gtids.html，开启gtid的方案

**Comment by cuihz** [comment]
> 我在1.0.25的基础上增加了GTID的支持，需要帮助review。#618
> 
> ## 改动说明
> 1. 增加instance级配置`gtidon`，指示该instance是否启用GTID模式。
> 2. driver包增加GTID相关类：`GTIDSet`，`UUIDSet`是GTID表示，`BinlogDumpGTIDCommandPacket`是`COM_BINLOG_DUMP_GTID`命令。
> 3. 补全dbsync包下的`GtidLogEvent`事件的解析。
> 4. protocol包下，增加了`EntryType`枚举项`GTIDLOG`，是binlog流中的GTIDLOG事件；`Header`增加了字段`gtid`，这里后面单独段落详细说明。
> 5. parse包下，`ErosaConnection`增加根据GTID同步的dump方法。
> 6. parse包下，`AbstractEventParser.start内`，如果instance使用GTID模式，则发送`COM_BINLOG_DUMP_GTID`命令给mysql。
> 
> ## 关于`CanalEntry.Header`增加`gtid`字段
> slave通过文件位点的方式同步binlog时，每个事件头里都携带了filename,position信息，后续存储最新同步位点只要取客户端ack过的最后一条事件的filename,position即可。
> 
> 对应的，GTID模式则需要记录消费过的[GTIDSet](https://dev.mysql.com/doc/refman/5.7/en/replication-gtids-concepts.html)。
> 
> 一个事务提交后，slave收到如下一连串事件，`GTID_LOG`，`TRANSACTIONBEGIN`，`ROWDATA`，`TRANSACTIONEND`，其中只有`GTID_LOG`有本次事务的GTID信息。现在通过`com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvertGTID`类，记录合并最后一个GTID，并赋值给后续事件的Header.gtid。

如果用default-instance.xml中的配置，如果Client消费中事务被截断是有可能会丢数据的吧，比如在TransactionBegin中截断了事务，Zookeeper中的cursor记录的则是正在处理的GTIDSET，但是这个GTIDSET并没有完全被处理，这时候如果重启Canal服务以这个GTIDSET去Dump日志是不是就会丢失掉数据啊。

**Comment by agapple** [comment]
位点是server端管理的，gtid模式最后记录的位点是以事务结尾

**Comment by xiangtao** [comment]
> 我在1.0.25的基础上增加了GTID的支持，需要帮助review。#618
> 
> ## 改动说明
> 1. 增加instance级配置`gtidon`，指示该instance是否启用GTID模式。
> 2. driver包增加GTID相关类：`GTIDSet`，`UUIDSet`是GTID表示，`BinlogDumpGTIDCommandPacket`是`COM_BINLOG_DUMP_GTID`命令。
> 3. 补全dbsync包下的`GtidLogEvent`事件的解析。
> 4. protocol包下，增加了`EntryType`枚举项`GTIDLOG`，是binlog流中的GTIDLOG事件；`Header`增加了字段`gtid`，这里后面单独段落详细说明。
> 5. parse包下，`ErosaConnection`增加根据GTID同步的dump方法。
> 6. parse包下，`AbstractEventParser.start内`，如果instance使用GTID模式，则发送`COM_BINLOG_DUMP_GTID`命令给mysql。
> 
> ## 关于`CanalEntry.Header`增加`gtid`字段
> slave通过文件位点的方式同步binlog时，每个事件头里都携带了filename,position信息，后续存储最新同步位点只要取客户端ack过的最后一条事件的filename,position即可。
> 
> 对应的，GTID模式则需要记录消费过的[GTIDSet](https://dev.mysql.com/doc/refman/5.7/en/replication-gtids-concepts.html)。
> 
> 一个事务提交后，slave收到如下一连串事件，`GTID_LOG`，`TRANSACTIONBEGIN`，`ROWDATA`，`TRANSACTIONEND`，其中只有`GTID_LOG`有本次事务的GTID信息。现在通过`com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvertGTID`类，记录合并最后一个GTID，并赋值给后续事件的Header.gtid。

具体使用方法 能否有一个详细文档说明？
