### ISSUE TITLE
我插入一条数据 canal的log报了如下错

### ISSUE THREAD

**Issue by ZSH9053** [alibaba/canal#1260]
com.alibaba.otter.canal.meta.exception.CanalMetaManagerException: batchId:88 is not the firstly:29
2018-12-06 16:04:33.127 [pool-5-thread-1] ERROR com.alibaba.otter.canal.server.CanalMQStarter - batchId:89 is not the firstly:29
com.alibaba.otter.canal.meta.exception.CanalMetaManagerException: batchId:89 is not the firstly:29
2018-12-06 16:04:33.127 [pool-5-thread-1] ERROR com.alibaba.otter.canal.server.CanalMQStarter - batchId:89 is not the firstly:29
com.alibaba.otter.canal.meta.exception.CanalMetaManagerException: batchId:89 is not the firstly:29
2018-12-06 16:04:39.234 [pool-5-thread-1] ERROR com.alibaba.otter.canal.server.CanalMQStarter - batchId:90 is not the firstly:29
com.alibaba.otter.canal.meta.exception.CanalMetaManagerException: batchId:90 is not the firstly:29
2018-12-06 16:04:39.234 [pool-5-thread-1] ERROR com.alibaba.otter.canal.server.CanalMQStarter - batchId:90 is not the firstly:29
com.alibaba.otter.canal.meta.exception.CanalMetaManagerException: batchId:90 is not the firstly:29
2018-12-06 16:04:45.141 [pool-5-thread-1] ERROR com.alibaba.otter.canal.server.CanalMQStarter - batchId:91 is not the firstly:29
com.alibaba.otter.canal.meta.exception.CanalMetaManagerException: batchId:91 is not the firstly:29
2018-12-06 16:04:45.141 [pool-5-thread-1] ERROR com.alibaba.otter.canal.server.CanalMQStarter - batchId:91 is not the firstly:29
com.alibaba.otter.canal.meta.exception.CanalMetaManagerException: batchId:91 is not the firstly:29

**Comment by agapple** [comment]
对应版本是啥？可以考虑用最新的1.1.2

**Comment by itmifen** [comment]
89 is not the firstly 。应该是batchId对不上，可以把meta.bat删掉试试

**Comment by LuVx21** [comment]
> 对应版本是啥？可以考虑用最新的1.1.2

意思是 无序消费在1.1.2中解决了? 但我现在用的1.1.2也出现这个问题了.

**Comment by suzawalee** [comment]
我用的多个client（CanalSharp），服务端canal只配置了一个instance，用的1.1.3Release版，多个客户端跑了一段时间就出现上面同样的错误。。。

**Comment by agapple** [comment]
多个客户端之间是否无序消费了？binlog本身是顺序的，要求get和ack的batchId顺序是一致的

**Comment by suzawalee** [comment]
> 多个客户端之间是否无序消费了？binlog本身是顺序的，要求get和ack的batchId顺序是一致的

`                    var message = connector.GetWithoutAck(1024);
                    var batchId = message.Id;
                    if (batchId == -1 || message.Entries.Count <= 0)
                    {
                        Console.WriteLine(string.Format(@"总处理量：{0},总耗时:{1}毫秒", cnt, millsec));
                        connector.Ack(batchId);
                        Thread.Sleep(100);
                        continue;
                    }
                    var dic = PrintEntry(message.Entries);
                    cnt += dic.Count;
                    foreach (KeyValuePair<string, string> kvp in dic)
                    {
                        try
                        {
//业务处理
                        }
                        catch (Exception ex)
                        {
                            Log.Exception(ex);
                        }

                    }
                    connector.Ack(batchId);`

**Comment by agapple** [comment]
多个client需要使用cluster模式才行，否则两个client分别做了get操作，但对应的ack顺序又不一致就会报错了

**Comment by suzawalee** [comment]
> 多个client需要使用cluster模式才行，否则两个client分别做了get操作，但对应的ack顺序又不一致就会报错了

谢谢
