### ISSUE TITLE
请问1.1.3版本大概什么时候release?

### ISSUE THREAD

**Issue by SteveFrank** [alibaba/canal#1262]
1.1.2版本中如果使用消息投递模式，存在节点切换异常，两个节点将会同时失效的问题。

**Comment by SteveFrank** [comment]
> 提供一下复现的操作步骤

环境：线下；
测试数据库：RDS 5.6
canal-server版本：1.1.2 & 2台 
部署方式：Docker 桥接网络 & 2核8G 2台
其他物料：ZK 集群，Kafka集群
操作复现流程：
使用kafka模式启动（我们针对这里做了些许修改，通过实现 CanalMQProducer 接口自定义了一些操作，但是经过不是bug引发点）；当我们停止了其中一台后，另外的一台并不会进行消息发送，通过观察ZK节点，cursor节点下的数据仍在发生变化，但是MQ不正常；切换版本回到 1.1.1 该问题回归正常。

**Comment by SteveFrank** [comment]
似乎和配置文件读取有关

**Comment by agapple** [comment]
我们线下分析一下， 有条件你可以尝试debug定位一下问题

**Comment by agapple** [comment]
https://github.com/alibaba/canal/issues/1229, 确认一下是否这个问题？

**Comment by SteveFrank** [comment]
> #1229, 确认一下是否这个问题？

好的，从描述来看的确是相似的问题，我到家再仔细确认一下，感激。

**Comment by SteveFrank** [comment]
> #1229, 确认一下是否这个问题？

是的，是同一类问题
