### ISSUE TITLE
canal1.1.2 ha有问题

### ISSUE THREAD

**Issue by chengqipeng** [alibaba/canal#1264]
### centos7

* canal 1.1.2
* mysql 5.7.22

### Issue Description
两台服务器已ha模式安装，但是一台停止，另外一台能正常起来，zk数据也正常就是没法同步binlog，切换到1.1.1正常

**Comment by agapple** [comment]
https://github.com/alibaba/canal/issues/1229, 确认一下是否这个问题？

**Comment by chengqipeng** [comment]
同步rocketmq的场景

**Comment by Fanduzi** [comment]
同步kafka也有问题

**Comment by agapple** [comment]
最新的主干代码已经修复

**Comment by agapple** [comment]
CharsetConversion问题我已经修复，建议都使用1.1.3，可以解决HA问题

**Comment by Fanduzi** [comment]
请问各位测试1.1.3 HA没? 能正常failover吗? 我测了还是不行啊
