### ISSUE TITLE
canal rowChange.getRowDatasList null

### ISSUE THREAD

**Issue by JesseNi** [alibaba/canal#1267]
canal 监听aws rds mysql rowChange.getRowDatasList 不管是什么事件都是Null

**Comment by bestzhao** [comment]
getRowDataList 如果为空的话 我劝你去看看你的过滤规则 是不是把表过滤了，他就是把表过滤了也会传过来，但是你会发现他getRowDataList会是空。

**Comment by liuhuijun11832** [comment]
binlog-format确认为row的话，检查一下instance.properties里的filter.regex和filter.black.regex是不是配置的有问题。
