### ISSUE TITLE
canal是否支持主子表同步的方式

### ISSUE THREAD

**Issue by itmifen** [alibaba/canal#1279]
在使用canal同步到ES的过程中，遇到如下场景：

主表 商品“分类 ID 分类名”
子表 商品 “ID 商品名 分类ID 分类名”

现有的ES同步支持直接生成 “ID 商品名 分类ID 分类名”这样结构的ES，但是如果修改了分类名，那么对应的商品的ES如何把所有的分类名更新到。求指教。

**Comment by rewerma** [comment]
查看wiki有详细配置说明

**Comment by jy02739244** [comment]
@itmifen 子表在left join里，我用adapter测试的结果是字表更新并不能更新es，请问你是怎么配置的

**Comment by natici** [comment]
遇到和楼上相同的问题了，请问楼主是如何配置的？
