### ISSUE TITLE
【canal-1.1.1】 【是否忽略事务头和尾】配置不生效

### ISSUE THREAD

**Issue by panjianping** [alibaba/canal#1284]
### environment

* canal 1.1.1
* mysql 5.7.20

### Issue Description
想忽略事务头和尾，配置如下：
canal.instance.filter.transaction.entry = true
但还是能收到事务消息：
header {
  version: 1
  logfileName: "master-bin.000009"
  logfileOffset: 379366832
  serverId: 1
  serverenCode: "UTF-8"
  executeTime: 1544755025000
  sourceType: MYSQL
  schemaName: ""
  tableName: ""
  eventLength: 85
}
entryType: TRANSACTIONEND
storeValue: "\022\0010"

如果配置：canal.instance.filter.transaction.entry = false，则事务头和尾都会收到

**再则就是，事务消息会定时产生（注：没有对数据库做任务修改）**

**Comment by agapple** [comment]
1. 事务头尾用于记录ack位点，没法直接忽略，在后续业务接收到之后可以做忽略
2. 定时消息是MySQL心跳数据
