### ISSUE TITLE
大数字显示科学记数法

### ISSUE THREAD

**Issue by chenyu9390** [alibaba/canal#1286]
### environment

* canal version 1.1.1
* mysql version

### Issue Description

大数字1111110589612032.000在更新后,收到的值变成科学计数法1111E13
### Expected behaviour

![Uploading grossweight.png…]()

**Comment by chenyu9390** [comment]
![grossweight](https://user-images.githubusercontent.com/8199403/49983459-d4352080-ff9d-11e8-813d-8347bf0c3657.png)

**Comment by agapple** [comment]
float类型是有这个问题，建议换decimal

**Comment by chenyu9390** [comment]
因为是监控已经运行的数据库，字段类型已经不能去更改了，还有别的办法去改正这个BUG吗？我实际测试了2个mysql数据库,用的也是ROW模式,数据同步是正常的，canal既然伪装成mysql的从,应该也是一样的数据呀
