### ISSUE TITLE
canal1.1.1指定pos点canal.instance.filter.regex无效

### ISSUE THREAD

**Issue by chengqipeng** [alibaba/canal#1287]
### environment

* canal version 1.1.1
* mysql version 5.7.22

### Issue Description
canal1.1.1指定将pos点指到数据库起点发现整个所有db实例的所有binlog都过来了，
canal.instance.filter.regex没有起到任何作用

**Comment by agapple** [comment]
多看下wiki的FAQ

**Comment by bestzhao** [comment]
其实是有效的，我终于研究了出来。他过滤是会成功的 ，但是不会把所有信息过滤掉，但凡某个表更改了他会发消息，但是，消息里面不会告诉你具体的消息。
总结：
如果你过滤规则写对了，他其实是过滤了的，比如你数据库有两张表一个叫test 一个叫 info，如果你过滤，写的是test ，那么 你还是会收到test的变更消息，但是你无法收到test的变更具体内容，也就是rowdateList 是空。但是info里面是对的，就会有信息。
