### ISSUE TITLE
【canal-1.1.1】canal-client 能否获取 Kafka 消息的 offset 及 指定从哪个 offset 消费消息？

### ISSUE THREAD

**Issue by panjianping** [alibaba/canal#1290]
### environment

* canal 1.1.1
* mysql 5.7.20

### Issue Description
1.现在业务情况是，使用canal把数据库的变更记录推送到 kafka，再通过 canal-client 消费kafka中的消息，但在消费消息的时候可能失败，想再次重新消费消息

2.使用了 KafkaCanalConnector 来获取消息
`java
KafkaCanalConnector connector = KafkaCanalConnectors.newKafkaConnector(kafkaServers, topic, partition, groupId);
`
查看 KafkaCanalConnector 的相关代码，没有发现获取kafka消息offset的方法，及 seek 方法

**3.请问1.1.1版本有没有重新消费kafka消息的机制或功能？**

**Comment by agapple** [comment]
@panjianping 可以考虑提交一个PR给我

**Comment by panjianping** [comment]
已经提交了PR[https://github.com/alibaba/canal/pull/1308](https://github.com/alibaba/canal/pull/1308)
基于canal 1.1.1 进行了测试，新增了 KafkaOffsetCanalConnector ，可以指定offset重新获取消息

**Comment by agapple** [comment]
赞一个
