### ISSUE TITLE
有计划将canal的配置文件提到配置中心吗？

### ISSUE THREAD

**Issue by wangjinzhao** [alibaba/canal#1291]
最近一直在使用canal，监控binlog将业务数据写入ES。做界面配置化,用java字节码自动生成client业务类。但是如果监控新库，都要去更改canal的配置文件。所以想问，canal的配置文件能否提到类似zk，configserver的配置中心里面。

**Comment by wingerx** [comment]
其实可以换个思路，将canal的配置文件放到zk里，为需要被启动的canal server生成一份文件写到canal需要的位置就可以了.
