### ISSUE TITLE
关于canal的安全策略

### ISSUE THREAD

**Issue by liuquanal** [alibaba/canal#1292]
### environment

* canal 1.1.1
* mysql 8.x

### Issue Description
canal如何应对非法连接？
由于canal的源代码里面没有找到相关安全配置，自己在ClientAuthenticationHandler的messageReceived方法里面写了一个简单的IP过滤、用户名密码检测。
![ipfilter](https://user-images.githubusercontent.com/15682710/50037378-78c16c00-004b-11e9-81ec-5a3c8b9a82fb.png)

经测试，确实可以防止非法客户端连接。
但是还是没有安全感，因为canal开放了两个端口，11111和11112，而且不确定messageReceived方法是否是端口的必经之路。想知道安全策略模块，写在哪个地方，才算真正的安全。

**Comment by agapple** [comment]
ClientAuthenticationHandler这是唯一的路径
