### ISSUE TITLE
canal server HA架构下对接 rocketmq时，发生主备切换后不再正常解析和接收binlog 

### ISSUE THREAD

**Issue by flackyang** [alibaba/canal#1293]
### environment

* canal version 1.1.2
* mysql version 5.7.23

### Issue Description
canal server HA架构下，使用tcp模式，发生主备切换时可以正常解析binlog的接收binlog,
但是对接 rocketmq时，发生主备切换后不再正常解析和接收binlog

手动停止当前running的节点后，主备切换成功了，instance正常启动，也从zookeeper获取到了上次解析的位点信息，但是对于新的binlog，没有继续解析并投递到消息组件

**Comment by agapple** [comment]
已知问题，需要更新主干代码
