### ISSUE TITLE
mysql 5.6版本 datetime值为null时 sqltype解析异常

### ISSUE THREAD

**Issue by yancai** [alibaba/canal#130]
问题描述：
mysql 版本为5.6.12，
在插入数据时，DATETIME类型的字段（如update_time字段）设置为NULL时，在从canal客户端获取到的数据中，对应字段的sqlType为1111（OTHER）

而在mysql 5.5.*版本中做同样的测试，DATETIME为null时，canal客户端获取到的对应sqlType为93（TIMESTAMP）

这个是BUG么？

**Comment by agapple** [comment]
我先验证下

**Comment by agapple** [comment]
确认是一个bug，mysql5.6增加了新的LogEvent类型，增加swtich判断后即可修复
