### ISSUE TITLE
 配置了canal.instance.defaultDatabaseName 和 canal.instance.filter.regex ,但是还是能够监控到 所有库 所有表的信息

### ISSUE THREAD

**Issue by liuwei19920518** [alibaba/canal#1302]
canal.instance.defaultDatabaseName = test1,test2
# enable druid Decrypt database password
canal.instance.enableDruid=false
#canal.instance.pwdPublicKey=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALK4BUxdDltRRE5/zXpVEVPUgunvscYFtEip3pmLlhrWpacX7y7GCMo2/JM6LeHmiiNdH1FWgGCpUfircSwlWKUCAwEAAQ==

# table regex
canal.instance.filter.regex=.*\\..*

1、canal.instance.defaultDatabaseName这个参数到底有没有用；
2、如果有用的话 defaultDatabaseName  和 regex 还有客户端的 connector.subscribe 三者的关系

**Comment by liuwei19920518** [comment]
1、很感谢楼上的回答；
2、针对第一点， 那么defaultDatabaseName这个参数感觉不配置也可以生效！所以能否具体一下怎么使用；
3、针对第二和第三点，如果客户端的subscribe 不配置而直接使用filter进行配置的情况下也是会监控到全部的表（或者说subscribe 默认监控全库全表？？？？？）；

**Comment by bestzhao** [comment]
兄弟，我来回答你，我终于研究出来了。他这个服务端的reg或者说是客户端的connector.subscribe，你写完匹配规则以后 虽然你能收到表的信息，但是你无法收到具体表的更新，也就是你的rowDateList 是空，但是你分析entry的时候 他会有消息告诉你，type会是query 。
总结：
  如果你过滤规则写对了，他其实是过滤了的，比如你数据库有两张表一个叫test 一个叫 info，如果你过滤，写的是test ，那么 你还是会收到test的变更消息，但是你无法收到test的变更具体内容，也就是rowdateList 是空。但是info里面是对的，就会有信息。

**Comment by agapple** [comment]
@bestzhao 你看一下FAQ的wiki就知道了，query的event是没有库和表的完整信息，所以没法做过滤
