### ISSUE TITLE
部分mysql 更新的数据，kafka中没有同步.

### ISSUE THREAD

**Issue by jkl0898** [alibaba/canal#1307]
### environment

* canal version 1.1.0
* mysql version 5.7

### Issue Description
有一些在mysql 更新的数据，canal 没有发送到kafka.

### Steps to reproduce
环境正常运行
### Expected behaviour
更新数据到MySQL
### Actual behaviour
数据未更新到MySQL

1. 是MySQL 中的更新没有写入到binlog还是 mysql 中已经写到binlog 但是canal 没有检测到，导致数据丢失了呢 ？ 请问如何确认？

**Comment by agapple** [comment]
建议使用最新的1.1.3

**Comment by jkl0898** [comment]
@agapple 你好。首先非常感谢你的答复。之所以现在才回复你，是因为期间我一直在找这个问题的原因。目前，发现一个有可能导致的问题的点。我们因为业务的需要，需要根据相同的表名将数据发送到相同的Kafka 分区中去。为此，写了一个自定义的Partititoner 。其代码片段如下：`public int partition(String topic, Object key, byte[] keyBytes, Object value, byte[] valueBytes, Cluster cluster) {

        int partitions = cluster.partitionCountForTopic(topic);
        Message message;
        String schemaName = null;
        String tableName = null;
        if (value instanceof Message) {
            message = new MessageDeserializer().deserialize(null, valueBytes);
            List<CanalEntry.Entry> entrys = message.getEntries();
            for (CanalEntry.Entry entry : entrys) {
                CanalEntry.EntryType  entryType = entry.getEntryType();
                logger.info("Entry type:{}", entryType);
                if (entryType == CanalEntry.EntryType.TRANSACTIONBEGIN
                        || entryType == CanalEntry.EntryType.TRANSACTIONEND) {
                    continue;
                }

                if (entryType == CanalEntry.EntryType.ROWDATA) {
                    schemaName = entry.getHeader().getSchemaName();
                    tableName = entry.getHeader().getTableName();
                    if((!StringUtils.isNullOrEmpty(schemaName) && !StringUtils.isNullOrEmpty(tableName)) {
                        break;
                    }
                }
            }
        } else {
            logger.error("Value:{} is no instance of Message", value);
        }

        int partition;
        if (!StringUtils.isNullOrEmpty(schemaName) && !StringUtils.isNullOrEmpty(tableName)) {
            partition = Math.abs((schemaName + tableName).hashCode()) % partitions;
        } else {
            partition = random.nextInt(partitions) % (partitions - 0 + 1) + 0;
        }
        logger.info("Schema name:{}, table name:{}, topic:{}, partition counts:{}, and message will send to partition[{}]", schemaName, tableName, topic, partitions, partition);

        return partition;
    }` 。主要思路是通过获取消息中的schema 和 table 名字， 取它们的hash 值，并求余。 

目前，发现List<CanalEntry.Entry> entrys 里面可能含有不同Schema和不同的table的数据。原有的假设是只会含有相同schema 和 table 的数据。所以就可能造成不同schema 和不同的表的数据可能被分发到相同的kafka partition 去了。在对消费消息有序性的要求下，这是一个潜在的问题，有可能造成消息丢失，但也不确定是否是这个原因真正造成消息丢失的，我们还排查了mysql 的binlog 和 kafka的可能性。


想咨询下的是， 如果我们要实现自定义的分区， 相同schema 和table 的数据发送到同一个分区， 即要避免上述问题， 请问你有什么好的建议吗？ 非常感谢。

**Comment by jkl0898** [comment]
@agapple 你好。经过解析mysql 中的binlog和写出kafka 的数据进行比对，发现该kafka(该kafka服务 是购买的，无法查阅详细日志) 会丢数据，导致最终部分数据丢失。目前我们自己搭建了kafka的集群，取自官网的kafka 2.0版本， 目前运行，暂无发现数据丢失。谢谢你的帮助。
