### ISSUE TITLE
filterEmtryTransactionEntry的问题

### ISSUE THREAD

**Issue by lulu2panpan** [alibaba/canal#132]
在EntryEventSink类的sinkData方法中，有对filterEmtryTransactionEntry进行判断的代码段，如下所示：
            if (filterEmtryTransactionEntry && !CollectionUtils.isEmpty(events)) {
                long currentTimestamp = events.get(0).getEntry().getHeader().getExecuteTime();
                // 基于一定的策略控制，放过空的事务头和尾，便于及时更新数据库位点，表明工作正常
                if (Math.abs(currentTimestamp - lastEmptyTransactionTimestamp) > emptyTransactionInterval
                    || lastEmptyTransactionCount.incrementAndGet() > emptyTransctionThresold) {
                    lastEmptyTransactionCount.set(0L);
                    lastEmptyTransactionTimestamp = currentTimestamp;
                    return doSink(events);
                }
            }

请问这里的判断基于什么目的？不太明白。
把canal.instance.transaction.size的大小设置为1024，在mysql上运行一个事务，进行1023次插入，那么canal-server会产生1025个event，按照EventTransactionBuffer的逻辑达到1024的时候会flush一次，随后剩下的一个event(Transactionend类型)会单独进行flush，但是由于上述代码的缘故，该event被忽略了，这应该不尽合理吧？？？？

**Comment by agapple** [comment]
事务头和尾主要是用来区分事务边界，本身数据没啥意义.  1025的transaction end事件的确可能被忽略了。 在canal+otter产品配合实施中，otter对于过滤后的空事务事件不是强需求，反而占用了过多的canal eventStore的ringBuffer空间，导致整体业务的处理速度变慢，所以当时设计默认值为true，待考虑和优化

**Comment by lulu2panpan** [comment]
感谢您的回复。
的确，出现事务被截断的情况是个小概率事件，并且像1025例子这样被截断后恰好出现了一个空事务事件更是一个极端事件。
您说的“反而占用了过多的canal eventStor的ringBuffer空间”指的应该是mysql的binlog-format不等于row的情况吧。当binlog-format等于row的时候，每次EventTransactionBuffer都是攒够一个事务才flush一次，除非事务太大被截断，否则不会出现【空事务事件】的情况。而当binlog-format比如等于mixed时，下面的代码段会进入if语句，基本上每条语句都会flush一次，导致很多【空事务事件】。
case ROWDATA:
                put(entry);
                // 针对非DML的数据，直接输出，不进行buffer控制
                EventType eventType = entry.getHeader().getEventType();
                if (eventType != null && !isDml(eventType)) {
                    flush();  //当binlog-format为mixed时，eventtyp为Query，isDml返回false，会flush
                }
                break;

**Comment by lulu2panpan** [comment]
您说的 “ 在canal+otter产品配置实施中，otter对于过滤后的空事务事件不是强需求 ”，这个该怎么理解呢？还是1025那个例子，如果1025对应的TRANSACTIONEND事件被过滤，otter怎么来界定事务边界呢？

**Comment by agapple** [comment]
otter非事务敏感性，其主要利用事务头和尾来更新位点而已，不是以事务单元进行整体提交，具体可以看下数据导入的wiki

**Comment by lulu2panpan** [comment]
恩 “非事务敏感性、主要利用事务头和尾来更新位点”  这个明白了。
上述关于binlog-format的表述是否正确？如果事务不被截断，并且binlog-foramt为row，那出现【空事务事件】的场景应该就没有了吧？

**Comment by lulu2panpan** [comment]
关于【空事务事件】，我找到另外的场景了，当配置filter的时候，如果某个表被过滤，那这张表的rowdata event会被过滤掉，但是TRANSACTIONBEGIN和TRANSACTIONEDN并没有被过滤掉，所以还是需要通过filterEmtryTransactionEntry 进行控制。您说的“反而占用了过多的canal eventStor的ringBuffer空间”应该主要指这种情况吧？

**Comment by agapple** [comment]
是的，理解正确. RingBuffer是固定数组大小的设计，所以空的事务头和尾会影响整体的吞吐量
