### ISSUE TITLE
canal.ip配置校验不完整

### ISSUE THREAD

**Issue by RickJou** [alibaba/canal#1322]
### environment

* canal version v1.1.2
* mysql version 5.7

### Issue Description
canal.ip校验规则不够严谨
### Steps to reproduce
两台机器21.79 和21.80
但是在配置时疏忽了,将79的canal.ip配置成了21.78.结果居然启动成功了
然后将79的canal整个目录scp复制到21.80(忘记改canal.ip了),启动....居然也成功了,在zookeeper里面cluster只显示一个
然后将21.80的cannal 执行stop.sh 此时却将79的也下线了......

随便选一个ip这种做法不太方便,比如可以做成通配符匹配网卡ip段的,如:192.168.* /172.20.*之类的,因为生产环境一台机器三四块网卡或者虚拟ip很正常啊.....

**Comment by agapple** [comment]
不要指定ip就行，指定ip是针对多网卡ip绑定监听用的

**Comment by RickJou** [comment]
举个栗子,生产环境必须指定ip对吧
但是指定的ip不是本机ip列表中的任何一个也可以成功...

**Comment by agapple** [comment]
指定ip只是socket bind的监听ip ,并没有做严格路由
