### ISSUE TITLE
Canal Server投递RocketMQ是保证顺序投递的吗？还有Adater中消费RocketMQ消息是顺序消费的吗？

### ISSUE THREAD

**Issue by flackyang** [alibaba/canal#1325]
### environment

* canal version 1.1.3
* mysql version 5.7.20

### Issue Description
Canal Server 对接RocketMQ， 使用RDB Adapter消费RocketMQ消费同步到数据库
请问 Canal Server投递RocketMQ是保证顺序投递的吗？还有Adater中消费RocketMQ消息是顺序消费的吗？

**Comment by agapple** [comment]
都是顺序写入、顺序消费

**Comment by flackyang** [comment]
@agapple  谢谢回复，另外再问一下，如果创建topic时使用了多个队列，对顺序写入和顺序消费有影响吗？

**Comment by liusir11** [comment]
Canal Server 对接RocketMQ过程中，是直接按文档配置的吗，自动到mq中吗，中间不需要写啥代码吗，我这块还没配置通，过来人指点下谢谢

**Comment by cysg** [comment]
保证顺序的前提是：所创建的topic类型是分区顺序消息，而非普通消息吧。
