### ISSUE TITLE
KeeperErrorCode

### ISSUE THREAD

**Issue by robert1070** [alibaba/canal#1327]
### environment

* canal 1.1.1
* 5.6.42-log

### 
客户端一直报错，NoNode for /otter/canal/destinations/test/cluster

**Comment by agapple** [comment]
问题需要详细, 需要有复现步骤

**Comment by shaoyou520** [comment]
这个问题解决了吗， canal-admin 部署的， 然后用canal client 连接zk 的方式报这个问题
