### ISSUE TITLE
Canal Adapter运行时启动过多线程导致服务器卡死

### ISSUE THREAD

**Issue by flackyang** [alibaba/canal#1328]
### environment

* canal version 1.1.3
* mysql version 5.7.20

### Issue Description
在Linux服务器上启动Canal Adapter从RocketMQ中消费消息，经常出现Canal Adapter启动过多线程导致服务器卡死的情况

**Comment by agapple** [comment]
可以在卡死状态一下, jstack和jmap观察一下jvm内容
