### ISSUE TITLE
解析变慢，20w的一个表，1秒产生1k条记录，变得很慢

### ISSUE THREAD

**Issue by jianghaibolxy** [alibaba/canal#1333]
### environment

* canal version
1.1.0
* mysql version
5.7
### Actual behaviour

以前订阅数据量比较少的表，解析比较快，现在订阅了一个20w条记录的表，1秒产生1k条记录的变化，变得很慢。
我看性能报告应该支持这个数据量级别的啊。

**Comment by jianghaibolxy** [comment]
哪个wiki有监控啊

**Comment by gsfeng179** [comment]
> 哪个wiki有监控啊

看一下wiki的【[Prometheus监控](https://github.com/alibaba/canal/wiki/Prometheus-QuickStart)】部分
