### ISSUE TITLE
canal 无法hash分区

### ISSUE THREAD

**Issue by ZSH9053** [alibaba/canal#1334]
我设置了canal.mq.partitionsNum=4，为什么还是只有第一个分区有数据？
# table regex
canal.instance.filter.regex=.*\\..*
# table black regex
canal.instance.filter.black.regex=

# mq config
canal.mq.topic=TP_oms2bi_oms4_bi_carrier
canal.mq.partition=0
# hash partition config
canal.mq.partitionsNum=4
canal.mq.partitionHash=a.b:id,a.c:id

**Comment by agapple** [comment]
canal.mq.partition=0 注释掉

**Comment by ZSH9053** [comment]
>           canal.mq.partition=0 注释掉

我注释掉了。似乎还是不行

**Comment by xForMe** [comment]
> canal.mq.partition=0 注释掉

`canal.mq.partitionHash=a.b:id,a.c:id`
这个表太多还是注释着可以吗？
这个是不是值默认根据id分区

**Comment by xForMe** [comment]
有解决吗

**Comment by Bruce2jiang** [comment]
这个问题我也发现了，hash 应该是不起作用的

**Comment by agapple** [comment]
参考MQ的最新文档，详细解释了下几个参数以及partition多分区、多topic的配置方式

**Comment by Jerryd99** [comment]
1.1.3 alpha版本 单topic 多分区，注释掉canal.mq.partition，配置hash为示范里按主键的情况，失败，一直都是发到0的分区

**Comment by mjjian0** [comment]
我注释掉了canal.mq.partition=0，但是发现如果开启单topic，按主键多分区，同步到的数据，会少。

**Comment by hjcdj** [comment]
> 
> 
> 1.1.3 alpha版本 单topic 多分区，注释掉canal.mq.partition，配置hash为示范里按主键的情况，失败，一直都是发到0的分区

我也是一样的问题，请问一下你的问题解决了么？是怎么解决的？这个对我来说挺重要的，谢谢啦大佬

**Comment by farsunset** [comment]
我也是一样的问题，请问一下你的问题解决了么？是怎么解决的？这个对我来说挺重要的，谢谢啦大佬
