### ISSUE TITLE
server启动显示 一只在binlog dump 再也没有下一步了

### ISSUE THREAD

**Issue by bestzhao** [alibaba/canal#1335]
### environment

* canal version 1.13
* mysql version 5.7.11

### Issue Description
我是第一次使用canal 想测试一下，配置好instance.properties,./startup.sh 启动了以后，日志一只停留在 next step is binlog dump ，是我哪里没有配好吗。

**Comment by agapple** [comment]
正常的，需要开启client消费，看一下quickstart

**Comment by haishui211** [comment]
我这边的现象也是一样，日志一直停留在 next step is binlog dump，开启client消费打印出empty。请问是怎么解决的呢？

**Comment by bestzhao** [comment]
我这边 换了一台服务器 就好了，我估计这边分析  大概率是以下两种原因：
1.权限问题，服务器权限，因为我这边运维配给的服务器用户 以及数据库用户等各种权限问题，我觉得可能会导致这个，我换了一台服务器 就好了。
2.内存问题，这个问题感觉概率比较大，因为原先机器确实有出现过内存不足导致启动不起来了，后面虽然启动起来了 但是一只empty，这个也是我换了一台服务器以后才想起来的，也没回过头检查了，你们可以检查一下。

**Comment by haishui211** [comment]
> 我这边 换了一台服务器 就好了，我估计这边分析 大概率是以下两种原因：
> 1.权限问题，服务器权限，因为我这边运维配给的服务器用户 以及数据库用户等各种权限问题，我觉得可能会导致这个，我换了一台服务器 就好了。
> 2.内存问题，这个问题感觉概率比较大，因为原先机器确实有出现过内存不足导致启动不起来了，后面虽然启动起来了 但是一只empty，这个也是我换了一台服务器以后才想起来的，也没回过头检查了，你们可以检查一下。

好的，谢谢，估计是内存不足引起，我这边再check下。

**Comment by lily-lee** [comment]
我也遇到这个问题。大家都解决了吗？
