### ISSUE TITLE
canal 如果根据数据库名进行hash分区

### ISSUE THREAD

**Issue by Cribugw** [alibaba/canal#1337]
* canal version 1.1.3
* mysql version

canal.mq.partitionsNum=10
canal.mq.partitionHash=？？？？
mysql数据库建立了十多个库，如何根据库名投递到不同的分区？
一个库下所有的表都发到一个分区里，我应该怎么写canal.mq.partitionHash？
麻烦大神解答下，谢谢！

**Comment by agapple** [comment]
看一下历史的issue

**Comment by Cribugw** [comment]
@agapple 你好，有关分区的issue的历史记录，我都翻看了，只见到了根据表分区或者主键进行分区的，没有发现根据数据库名进行分区的，还请大神指导下

**Comment by agapple** [comment]
配置一个 schema\\.*的匹配来做hash到多个分区，或者dymaicTopics配置按照库名发送到多个topic

wiki里都有
