### ISSUE TITLE
关于max memory size的问题

### ISSUE THREAD

**Issue by lulu2panpan** [alibaba/canal#134]
Hi jianghang：
在类MemoryEventStoreWithBuffer的checkFreeSlotAt方法中，
if (batchMode.isMemSize()) {
                final long memsize = putMemSize.get() - ackMemSize.get();
                if (memsize < bufferSize * bufferMemUnit) {
                    return true;
                } else {
                    return false;
                }
            } else {
                return true;
            }
只判断memsize < bufferSize * bufferMemUnit还不够吧，应该用 ”当前空闲内存量+新加入事件所占内存量”和bufferSize * bufferMemUnit进行比较才对吧？？
望指教。

**Comment by agapple** [comment]
putMemSize.get() - ackMemSize.get()， 这个得出来的结果就是当前在内存中未被get的数据，也就是使用中的内存块，因为Ringbuffer的特性是lazy set模式，在几个位点之间会有部分内存数据未被及时清理，不过一般在数据高速get/put过程中，总的内存量是可控的，并不是非常精确

**Comment by lulu2panpan** [comment]
恩 明白 tks
