### ISSUE TITLE
canal从RocketMQ中获取消息是单条消费，是否可以使用批量消费？批量消费对顺序消费有什么影响？

### ISSUE THREAD

**Issue by flackyang** [alibaba/canal#1346]
### environment

* canal version 1.1.3
* mysql version 5.7.20

### Issue Description
目前Canal Adapter消费RocketMQ时使用的时单条消费，是否可以使用批量消费，比如把consumeMessageBatchMaxSize调大一些？
如果使用批量拉取消息进行消费，对消息的顺序消费和 消费的可靠性(offset控制）有什么影响？

**Comment by agapple** [comment]
1.  canal client里的sdk已经是批处理，一次性获取多个Message，每个Message里有多条记录
2. canal adapter里也是批处理，批量获取到数据，循环处理多个Message(每个Message里有多条记录)

**Comment by flackyang** [comment]
@agapple 在消费flatMessage的情形下，调试 RocketMQCanalConnector类中process方法发现默认情况下每次是获取一条message进行处理的；如果增加rocketMQConsumer.setConsumeMessageBatchMaxSize(100);配置后就是批量消费 。
@rewerma 所以在flatMessage情形下需要自己配置 consumeMessageBatchMaxSize 才会批量消费对吧

**Comment by agapple** [comment]
如果在追上的状态，canal server投递到metaq上可能每个Message里就只有一条记录

**Comment by rewerma** [comment]
flatmessage下
生产端修改：
canal.mq.batchSize = 16384
canal.mq.lingerMs = 100

消费端修改:
canal.conf:
  batchSize: 500 大小

**Comment by flackyang** [comment]
@agapple @rewerma Adaper 中，只有CanalAdapterKafkaWorker和CanalAdapterWorkert处理了batshSize配置，CanalAdapterRocketMQWorker没有处理 ，有什么特殊考虑吗？

**Comment by agapple** [comment]
没有特殊考虑，现在已经加了

**Comment by ZhXinBin** [comment]
@agapple flatmessage下 投递RocketMQ每次都是只投递一条message，这是否会对性能有影响？
