### ISSUE TITLE
值由Null变为空字符串时，isUpdated属性为false

### ISSUE THREAD

**Issue by zhenghub** [alibaba/canal#135]
mysql版本是5.5
将一个varchar类型的列的值由NULL，改为''时，从canal获取的entry的column里，isupdated属性为false。看了下LogEventConverter，感觉是isUpdated方法有个bug。newValue为""，旧值为NULL时，旧的column.getValue()为""。

**Comment by agapple** [comment]
column.isNull()方法可以判断是否为null值

**Comment by zhenghub** [comment]
这是在otter中发现的，otter使用了canal的column.isUpdated方法来判断是否发生了变更，然后就有些列同步错误了。

**Comment by agapple** [comment]
多谢反馈，问题代码已经修复，下个版本可发布

**Comment by zhenghub** [comment]
不客气。期待canal与otter更加完善
