### ISSUE TITLE
请问读取kafka的数据， 发现没有iskey这个属性， 请问该如何设置？

### ISSUE THREAD

**Issue by guojingzoe** [alibaba/canal#1352]
### environment

* canal version1.1.2
* mysql version 5.7.13
kafka 接受的数据如下：
{"data":[{"mm":"11","mm2":"guo"}],"database":"test_canal","es":1545908671000,"id":1,"isDdl":false,"mysqlType":{"mm":"bigint(255)","mm2":"varchar(255)"},"old":null,"sql":"","sqlType":{"mm":-5,"mm2":12},"table":"table222","ts":1545908671246,"type":"INSERT"}
{"data":[{"mm":"11","mm2":"guo"}],"database":"test_canal","es":1545908671000,"id":2,"isDdl":false,"mysqlType":{"mm":"bigint(255)","mm2":"varchar(255)"},"old":null,"sql":"","sqlType":{"mm":-5,"mm2":12},"table":"table222","ts":1545908671345,"type":"INSERT"}
{"data":[{"mm":"11","mm2":"guo"}],"database":"test_canal","es":1545908671000,"id":2,"isDdl":false,"mysqlType":{"mm":"bigint(255)","mm2":"varchar(255)"},"old":null,"sql":"","sqlType":{"mm":-5,"mm2":12},"table":"table222","ts":1545908671245,"type":"INSERT"}
{"data":[{"mm":"12","mm2":"guo"}],"database":"test_canal","es":1545908679000,"id":3,"isDdl":false,"mysqlType":{"mm":"bigint(255)","mm2":"varchar(255)"},"old":null,"sql":"","sqlType":{"mm":-5,"mm2":12},"table":"table222","ts":1545908679794,"type":"INSERT"}
 发现没有iskey 属性

**Comment by liusir11** [comment]
@guojingzoe  canal 配置kafka过程是直接配置的吗，不需要些东西吗，我这kafka一直没数据啊

**Comment by guojingzoe** [comment]
> @guojingzoe canal 配置kafka过程是直接配置的吗，不需要些东西吗，我这kafka一直没数据啊

嗯呢， 我用的1.1.2版本直接配置， 没有通过读取api 方式， 在wiki 里面有说明， 操作文档哈

**Comment by guojingzoe** [comment]
> flatMessage没有列的具体信息，1.1.3会增加pkNames的列信息

谢谢哈， 期待升级

**Comment by cjk87927** [comment]
@agapple 
v1.1.3版本, flatMessage pkNames 为空
```
"pkNames": null, 
```
已确认表中包含主键字段

**Comment by Zhifeiyu** [comment]
> @agapple
> v1.1.3版本, 投递至RocketMQ, flatMessage pkNames 为空
> 
> ```
> "pkNames": null, 
> ```
> 
> 已确认表中包含主键字段

+1

**Comment by cjk87927** [comment]
@Zhifeiyu 
问题已找到,在对`flatMessage`进行分片的方法中`com.alibaba.otter.canal.common.MQMessageUtils#messagePartition`对flatMessageTmp赋值漏了PkNames
![image](https://user-images.githubusercontent.com/6744728/59649672-0e35e800-91b6-11e9-8d54-b7e41830845f.png)
