### ISSUE TITLE
canal-adapter启动后报错

### ISSUE THREAD

**Issue by didi909** [alibaba/canal#1353]
### environment

* canal-server version
deployer-1.1.3
* canal-adaptor version
adapter-1.1.3
* es version
Version: 6.5.1, Build: default/tar/8c58350/2018-11-16T02:22:42.182257Z, JVM: 1.8.0_191

### Issue Description
启动canal-server正常
启动canal-adapter正常，大概1分钟左右，出现报错(期间没有任何操作)
后续的同步到es可以正常完成

### Steps to reproduce
cd canal-server
./bin/startup.sh
cd canal-adapter
./bin/startup.sh
### Expected behaviour
无异常
### Actual behaviour
出现异常
<img width="1280" alt="1" src="https://user-images.githubusercontent.com/25740515/50508839-7dac0400-0abe-11e9-8a30-534c8bda83c4.png">

**Comment by agapple** [comment]
建议获取一下1.1.3 alpha-3的最新版，近期有修复过adapter的问题
