### ISSUE TITLE
为什么过滤的正则无效

### ISSUE THREAD

**Issue by bestzhao** [alibaba/canal#1361]
### environment

* canal version
* mysql version

### Issue Description

无论是我服务端还是client端，设置的reg都无效 一只获取所有表的binlog 十分的浪费，有几十个表，很雷。

**Comment by bestzhao** [comment]
好了，这个问题结了。
具体原因是这样的，只要你过滤正则写的是对的，那么其实你的过滤是生效了。发生一条变更会发送两条entry过来（出去transactionbegin 和end） ，一个entry是query ，一个是具体的更新（insert / update/delete）。
你没过滤的表会发两个entry过来 ，但是你过滤的表只会发一个entrytype是query的信息。其实看到这里你自己回去试一下你就恍然大悟了。
这里可能他设计的有坑或者说明的不够清楚，导致我一只很奇怪，官方回答也是根本牛头不对马嘴。其实就是这个问题。明明过滤了为什么也会发变更消息...

**Comment by bestzhao** [comment]
希望官方可以修复一下这个问题，或者写在wiki上，我看issues上有好多都是这个问题 ，希望大家能看到我的回答。

**Comment by agapple** [comment]
参考一下FAQ里的解释：https://github.com/alibaba/canal/wiki/FAQ

---
问1：INSERT/UPDATE/DELETE被解析为Query或DDL语句？

答1：
出现这类情况主要原因为收到的binlog就为Query事件，比如:
1. binlog格式为非row模式，通过show variables like 'binlog\_format'可以查看. 针对statement/mixed模式，DML语句都会是以SQL语句存在
2. mysql5.6+之后，在binlog为row模式下，针对DML语句通过一个开关(binlog-rows-query-log-events=true)，记录DML的原始SQL，对应binlog事件为RowsQueryLogEvent，同时也有对应的row记录.  ps. canal可以通过properties设置来过滤：canal.instance.filter.query.dml = true
  

---


问2：设置了数据表的过滤条件，但貌似没有生效？

答2：
1. 首先看文档[AdminGuide](AdminGuide)，了解<span data-type="color" style="color:rgb(36, 41, 46)"><span data-type="background" style="background-color:rgb(255, 255, 255)">canal.instance.filter.regex的书写格式</span></span>
    ```plain
    mysql 数据解析关注的表，Perl正则表达式.
    多个正则之间以逗号(,)分隔，转义符需要双斜杠(\\) 
    常见例子：
    1.  所有表：.*   or  .*\\..*
    2.  canal schema下所有表： canal\\..*
    3.  canal下的以canal打头的表：canal\\.canal.*
    4.  canal schema下的一张表：canal.test1
    5.  多个规则组合使用：canal\\..*,mysql.test1,mysql.test2 (逗号分隔)
    ```
2. 检查binlog格式，过滤条件只针对row模式的数据有效(ps. mixed/statement因为不解析sql，所以无法准确提取tableName进行过滤)
3. 检查下CanalConnector是否调用subscribe(filter)方法；有的话，filter需要和instance.properties的canal.instance.filter.regex一致，否则subscribe的filter会覆盖instance的配置，如果subscribe的filter是.\*\\..\*，那么相当于你消费了所有的更新数据 <span data-type="color" style="color:#F5222D">【特别注意】</span>
4. 检查一下[历史的issue列表](https://github.com/alibaba/canal/issues?utf8=%E2%9C%93&q=subscribe)，很有可能你的提问别人已经遇到过并解决了，比如表达式不对，特别是双斜杠的问题

**Comment by mathsyouth** [comment]
@agapple “检查下CanalConnector是否调用subscribe(filter)方法”， 对于 Kafka 该如何处理？

**Comment by vagusss** [comment]
> 希望官方可以修复一下这个问题，或者写在wiki上，我看issues上有好多都是这个问题 ，希望大家能看到我的回答。

我也遇到这个问题了, 我理解的是:  对于transactionbegin和end的binlog信息是无法过滤的(是不是因为事务binlog里并没有额外的信息,只有开始和结束? ), 所以即使你设置了过滤条件, 当不符合你过滤条件的表发生事务时,依然会把相应的binlog发过来.不知道我理解的对不对

**Comment by Guoqing815** [comment]
不要用\\ 用\就够了！
