### ISSUE TITLE
canalv1.1.2使用HA模式对接kafka

### ISSUE THREAD

**Issue by shubiao-yao** [alibaba/canal#1366]
### environment

* canal 1.1.2
* mysql 5.6

### Issue Description

canal server HA模式下
使用tcp模式，发生主备切换时可以正常解析binlog的接收binlog

对接kafka时，发生主备切换后不再正常解析和接收binlog

手动停止当前running的节点后，主备切换成功了，instance正常启动，也从zookeeper获取到了上次解析的位点信息，但是对于新的binlog，没有继续解析并投递到kafka。

我这里准备了2台canal server 和 3台zookeeper，出现上述情况后，我将所有的canal server都停掉，然后启动其中一台，这时就自动从上次解析的点位正常投递到kafka中了。

请大神解答疑惑。

**Comment by shubiao-yao** [comment]
@agapple 大神，麻烦有时间解决下我的疑惑

**Comment by agapple** [comment]
1.1.2的一个已知问题，可以尝试一下1.1.3

**Comment by shubiao-yao** [comment]
@agapple 好的，谢谢大神回复

**Comment by Fanduzi** [comment]
> @agapple 好的，谢谢大神回复

请问您换了1.1.3解决了这个问题了么. 我用1.1.3还是有问题

**Comment by agapple** [comment]
1.1.3我等下更新一下最新包
