### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class com.taobao.tddl.dbsync.binlog.CharsetConversion

### ISSUE THREAD

**Issue by shoueb** [alibaba/canal#1369]
### environment

* canal 1.1.2
* mysql 5.7

### Issue Description
源码启动CanalLauncher，过一会就报
java.lang.NoClassDefFoundError: Could not initialize class com.taobao.tddl.dbsync.binlog.CharsetConversion

**Comment by pupuwudi** [comment]
我的也是同样的问题。

**Comment by waters321** [comment]
我也是同样的问题

**Comment by agapple** [comment]
已修复，可以更新一下最新的代码

**Comment by agapple** [comment]
可以尝试一下1.1.3 alpha-3版本，charset问题有修复
