### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: 0 com.alibaba.otter.canal.parse.inbound.mysql.dbsync.SimpleDdlParser.parseTableName(SimpleDdlParser.java:163)

### ISSUE THREAD

**Issue by xianjingfeng** [alibaba/canal#137]
版本1.0.19
错误如下：
![qq 20151218092517](https://cloud.githubusercontent.com/assets/11752250/11886867/b88a512a-a569-11e5-9dba-1feaa8a6637c.png)

binlog位置如下：
![qq 20151218092527](https://cloud.githubusercontent.com/assets/11752250/11886874/c864b91e-a569-11e5-8677-c808ef22c33d.png)

 使用pt-online-schema-change变更字段后出现这种情况

**Comment by agapple** [comment]
https://github.com/alibaba/canal/pull/128，已经有用户修复，新版本发布后即可，或者可自行打包当前master
