### ISSUE TITLE
canal.mq.dynamicTopic配置不起作用

### ISSUE THREAD

**Issue by althen** [alibaba/canal#1371]
### environment

* canal version 1.1.3
* mysql version 5.6

### Issue Description

canal.mq.dynamicTopic配置不起作用

canal.serverMode = kafka

canal.mq.topic = test
canal.mq.dynamicTopic = mydb
mydb的binlog仍然发送到 test  topic

**Comment by rewerma** [comment]
更新一下最新的代码
