### ISSUE TITLE
如果配置了这个参数，会导致Insert语句的Binlog数据不能同步 canal.mq.partitionHash=

### ISSUE THREAD

**Issue by Bruce2jiang** [alibaba/canal#1374]
如果配置了这个参数，会导致Insert语句的Binlog数据不能同步
canal.mq.partitionHash=

补充 ：
我在instance.properties 配置如下，insert语句同步不到kafka
canal.instance.filter.regex=bigdata\\.testtable.*
canal.mq.topic=example8
canal.mq.partitionsNum=3
canal.mq.partitionHash=bigdata.testtable:uid

后来我修改成下面配置(canal.mq.partitionHash没有设置)，就可以在kafka中获取到insert语句了
canal.instance.filter.regex=bigdata\\.testtable.*
canal.mq.topic=example8
canal.mq.partitionsNum=3
canal.mq.partitionHash=

**Comment by Bruce2jiang** [comment]
请大神解答一下，这个对我满重要的

**Comment by agapple** [comment]
之前应该是做partition路由的时候忽略了RowsQueryLogEvent，最新的代码已修复
