### ISSUE TITLE
canal 支持监控不同库的 canal server 注册到同一个zk上吗？

### ISSUE THREAD

**Issue by baibingzhi** [alibaba/canal#1376]
canal 支持监控不同库的 canal server 注册到同一个zk上吗？谢谢！

**Comment by shubiao-yao** [comment]
canal.properties这个配置文件中有个canal.destinations选项，它是指的当前server上部署的instance列表

每个instance可以对应一个"**数据库**"，这块的配置你可以参考：
https://github.com/alibaba/canal/wiki/AdminGuide

HA模式中已经提及canal server怎么与zookeeper如何交互

当你配置canal.destinations为多个example后。
例：canal.destinations = example1,example2

去zookeeper client中去分别查看example1,example2 当前最后一次消费成功的binlog位点。

[zk: localhost:2181(CONNECTED) 16] get /otter/canal/destinations/example1/1001/cursor
[zk: localhost:2181(CONNECTED) 16] get /otter/canal/destinations/example2/1001/cursor

使用canal client去分别订阅消费canal server中的binlog
CanalConnector connector = CanalConnectors.newClusterConnector("10.70.120.158:2181", "example1", "", "");

CanalConnector connector = CanalConnectors.newClusterConnector("10.70.120.158:2181", "example2", "", "");

以上内容我已经亲自尝试过了，希望可以帮助到你。

**Comment by agapple** [comment]
LS正解

**Comment by baibingzhi** [comment]
非常感谢！
