### ISSUE TITLE
canal.properties配置问题

### ISSUE THREAD

**Issue by mengzhibule** [alibaba/canal#1379]
EventType这个枚举里有很多事件，请问能否在canal.properties里或者其他配置了，只让canal.entry里存insert,update,delete的数据？

**Comment by shubiao-yao** [comment]
我们可以通过配置来筛选需要监控的类型

![image](https://user-images.githubusercontent.com/32409300/50678158-5a420580-1038-11e9-9ba6-8bacf6b0e38c.png)

https://github.com/alibaba/canal/wiki/AdminGuide

**Comment by shubiao-yao** [comment]
SQL 语句主要可以划分为以下 3 个类别。

DDL（Data Definition Languages）语句：数据定义语言，这些语句定义了不同的数据段、数据库、表、列、索引等数据库对象的定义。常用的语句关键字主要包括 create、drop、alter等。

DML（Data Manipulation Language）语句：数据操纵语句，用于添加、删除、更新和查询数据库记录，并检查数据完整性，常用的语句关键字主要包括 insert、delete、udpate 和select 等。(增添改查）

DCL（Data Control Language）语句：数据控制语句，用于控制不同数据段直接的许可和访问级别的语句。这些语句定义了数据库、表、字段、用户的访问权限和安全级别。主要的语句关键字包括 grant、revoke 等。

**Comment by agapple** [comment]
LS正解
