### ISSUE TITLE
canal server Ha 切换失效

### ISSUE THREAD

**Issue by githubkevinyou** [alibaba/canal#1380]
### environment

* canal 1.1.2
* mysql 5.7.24
zookeeper3.4.13 集群
kafka 2.11-2.0.0

### Issue Description
canal server ha配置（两台机器） 
1。 同时启动canal server A和canal server B，canal serverA工作正常，如果canal server A stop下，canal server B无法消费binlog， zookeeper 监控信息也显示canal server B running，此时canal server B stop后startup下又正常消费binlog了
2。 canal server A和canal server B 开始时只有一个启动，另外一个不启动，能正常消费binlog；停掉运行的canal server后再启动另外一个canal server也能正常工作；感觉和zookeeper有关，不如用keeperalived脚本监控

**Comment by shubiao-yao** [comment]
看到你的描述好像跟我遇到的情况差不多，我的是对接了kafak

https://github.com/alibaba/canal/issues/1366

**Comment by rewerma** [comment]
升级1.1.3最新版本已解决这个问题

**Comment by Fanduzi** [comment]
请问您有测试1.1.3吗,解决了这个问题没?

**Comment by hcnysa** [comment]
我是1.1.3 对接了kafka，遇到了同样的问题。
首先AB两台机器做了HA,环境配置等都相同。
A 机器 手动停止，从B机器从日志中看到已经开始消费，但是并没有向kafka投递任何数据，日志也没有报错。
