### ISSUE TITLE
可以支持Sqlserver嘛

### ISSUE THREAD

**Issue by wsxe9988** [alibaba/canal#1384]
### environment

* canal version
* mysql version

### Issue Description
现在项目急需基于Sqlserver数据库增量日志解析，提供增量数据订阅&消费，canal后续有这个计划嘛

**Comment by singgel** [comment]
兄弟，找到解决方案了吗？

**Comment by singgel** [comment]
烙铁，我解决了：https://blog.csdn.net/singgel/article/details/86162990
