### ISSUE TITLE
Adaper 中，只有CanalAdapterKafkaWorker和CanalAdapterWorkert处理了batshSize配置，CanalAdapterRocketMQWorker没有处理 ，有什么特殊考虑吗？

### ISSUE THREAD

**Issue by flackyang** [alibaba/canal#1394]
### environment

* canal version 1.2
* mysql version 5.7.20

### Issue Description
Adaper 中，只有CanalAdapterKafkaWorker和CanalAdapterWorkert处理了canal.conf 中的batshSize配置，CanalAdapterRocketMQWorker没有处理 ，有什么特殊考虑吗？

**Comment by agapple** [comment]
最新的代码已经增加rocketMQConsumer.setConsumeMessageBatchMaxSize(batchSize);
