### ISSUE TITLE
mysql binlog日志问题---canal  storeValue

### ISSUE THREAD

**Issue by ferry1376122** [alibaba/canal#1395]
canal连接两个数据库实例，有一个数据库有问题，根据canal打印的storeValue有如下区别：
好的库：
应该是个二进制文件
storeValue: "\b\223\207\261z\020\001P\000b\260\f\0220\b\000\020\373\377\377\377\377\377\377\377\377\001\032\

不好的库：
打印出sql语句了
storeValue: "\020\002Z\231\002update t_crm_multi_account\n     SET sys_status = 3,\n      \n      \n        business_status = 1

哪位大神知道是什么问题吗？感觉是数据库binlog配置问题

**Comment by ferry1376122** [comment]
问题找到了：binlog打开的模式问题
　　mysql默认没有开启binlog，修改mysql的my.cnf文件，添加如下配置，注意binlog-format必须为row，因为binlog如果为
STATEMENT或者MIXED,则binlog中记录的是sql语句，不是具体的数据行，canal就无法解析到具体的数据变更了
log-bin=E:/mysql5.5/bin_log/mysql-bin.log 
binlog-format=ROW
server-id=123

**Comment by lovely960823** [comment]
老哥，我的数据库配置没问题，通过canal打印出来的中文也是二进制文件，这个怎么处理
