### ISSUE TITLE
删除修改不会同步，只有添加可以同步

### ISSUE THREAD

**Issue by acuitong** [alibaba/canal#1398]
canalApdater装上后，mysql的同步，添加同步正常，可是删除和修改就会nullpoint，dml获取啥的都正常，请问是不是哪个配置配置了可以删除修改的权限!!!!

**Comment by acuitong** [comment]
我这个问题的原因可能是使用了作者有bug的gz包引起的，重新下载最新的gz，安装后问题解决了

**Comment by acuitong** [comment]
是的，目前git上的1.1.3的adapter是最新的，我这边已经在本地测试通过了

**Comment by gqxie** [comment]
> 是的，目前git上的1.1.3的adapter是最新的，我这边已经在本地测试通过了

好的，我是前几天下载的1.1.3版本的adapter包，可能最近有更新，我重新下载一个试试

**Comment by gqxie** [comment]
> 是的，目前git上的1.1.3的adapter是最新的，我这边已经在本地测试通过了

感谢！

**Comment by gqxie** [comment]
> 是的，目前git上的1.1.3的adapter是最新的，我这边已经在本地测试通过了

我这边仍然有问题，可否qq私聊一下

**Comment by agapple** [comment]
可以尝试一下1.1.3 alpha-3版本，对于adapter做了蛮多的问题修复
