### ISSUE TITLE
是否支持python客户端读取同步的binlog?

### ISSUE THREAD

**Issue by wcc526** [alibaba/canal#140]
是否支持python客户端读取同步的binlog?

**Comment by agapple** [comment]
canal目前只提供了java版本，server采用了protobuf协议进行通讯，可以按照协议需求自行完成一个python client版本开发

**Comment by haozi3156666** [comment]
我实现了一个 python 客户端，欢迎使用哈：https://github.com/haozi3156666/canal-python

**Comment by agapple** [comment]
https://github.com/haozi3156666/canal-python，赞一个，我已经加入到wiki引用
