### ISSUE TITLE
目前canal还不支持mysql8的新的加密方式？没看到文档怎么使用mysql8啊

### ISSUE THREAD

**Issue by INTERESTING-OMG** [alibaba/canal#1400]
### environment

* canal version ：1.1.3-alpha-2
* mysql version 8.0.13

### Issue Description
我目前使用的是最新的mysql，发现新的加密方式不支持？我看到文档更新了支持mysql8

**Comment by agapple** [comment]
issue里有说，只支持老的加密方式

**Comment by windyyong** [comment]
issue哪里有?没有看到
