### ISSUE TITLE
Canal对接RocketMQ时，修改将表名作为Message的topic,没有自动创建对应的Topic

### ISSUE THREAD

**Issue by flackyang** [alibaba/canal#1405]
### environment

* canal version 1.1.3
* mysql version 5.7.20

### Issue Description
将canal CanalRocketMQProducer 代码修改将表名作为Message的topic
~~~
Message message = new Message(flatMessage.getTable(),
                                JSON.toJSONString(flatMessage, SerializerFeature.WriteMapNullValue).getBytes());
~~~
启动后 Canal一直报错提示：
~~~
org.apache.rocketmq.client.exception.MQClientException: No route info for this topic, 
~~~
### Expected behaviour
自动根据表名创建Topic
### Actual behaviour
没有创建表名对应的Topic

**Comment by wolfLoveFish** [comment]
你好，我现在也在考虑开发针对表级topic，有没有什么实现想法？谢谢

**Comment by rewerma** [comment]
现在已支持动态topic，可以针对表级建topic
