### ISSUE TITLE
请教几个Canal使用的几个问题，多谢

### ISSUE THREAD

**Issue by zhufeizzz** [alibaba/canal#141]
1、文档说多个canal实例的serverId不能重复，请问有啥影响？我试的好像没什么问题
2、instance.properties里面的正则监听一个表和多个表对canal服务端性能影响大吗，因为我们的表是动态生成的，如果影响不大在客户端动态订阅就好了
3、多个otter客户端连接同一个canal时我发现一条消息只会收到一次，请问这个特性靠谱吗？

**Comment by agapple** [comment]
1. 同一个mysql主备集群serverId，出现重复的时候，mysql会随机kill一个客户端链接 
2. 正则表达式会有长度限制，相比于正则计算，网络I/O会先成为瓶颈
3. 建议一个server只有一个client，server和client都使用HA的模式，可以保证只有一个client工作，并且client能收到全部数据
