### ISSUE TITLE
批次更新数据，canal跟踪的数据错误

### ISSUE THREAD

**Issue by NotTheSameWorld** [alibaba/canal#1415]
### environment

* canal version
 canal.deployer-1.1.3-SNAPSHOT
![image](https://user-images.githubusercontent.com/23094497/51033279-d5c62880-15dd-11e9-903c-0fc93a2e56c2.png)

* mysql version
![image](https://user-images.githubusercontent.com/23094497/51032043-91d12480-15d9-11e9-80e2-5c08f12b039e.png)

### Issue Description
UPDATE  daily SET stat=1 WHERE name='张三'
当我根据某个条件更新数据时，更新的数据有311条，结果canal监听到了311条，但是311条却是大量的
重复数据，有很多数据遗漏

批次更新：监听的资料笔数对，数据不对
麻烦各位大神帮忙解答一下，如何解决

**Comment by NotTheSameWorld** [comment]
版本：canal.deployer-1.1.3-SNAPSHOT也有此问题

**Comment by NotTheSameWorld** [comment]
已经解决

**Comment by jinguangyu** [comment]
> 已经解决
@NotTheSameWorld，怎么解决的啊兄弟
