### ISSUE TITLE
canal1.0.21版本中zkclient和kafka zkclient版本冲突问题

### ISSUE THREAD

**Issue by fangzhucode** [alibaba/canal#142]
canal和kafka一块用的时候 canal1.0.21版本中zkclient(com.github.sgroschupf )和kafka中zkclient版本(com.101tec:zkclient)冲突
artifactId不一样 不好排除包
 这种问题有什么解决方案吗 多谢啊 
为什么当时不使用com.101tec这个稍微大众的zkclient版本

**Comment by alexandnpu** [comment]
这个issue为什么关掉了呀，我今天在1.0.24版本上也遇到这个问题

**Comment by agapple** [comment]
这个包历史有点悠久，如果方便可以提交一个PR给我
