### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by fantessti** [alibaba/canal#1426]
### environment

* canal 1.1.3
* mysql 5.6

### Issue Description
java.lang.NoSuchMethodError: com.google.common.collect.MapMaker.makeComputingMap(Lcom/google/common/base/Function;)Ljava/util/concurrent/ConcurrentMap;

直接启动的canal服务端，里面guava是18版本，为什么会报错呢

**Comment by agapple** [comment]
建查一下是否有版本冲突
