### ISSUE TITLE
尝试多次，客户端一直读取不到binlog变更，和cpu个数有关，需要大于1

### ISSUE THREAD

**Issue by fairychao** [alibaba/canal#1429]
### environment

* canal version
   canal.deployer-1.1.2.tar.gz
   客户端用的是 1.1.2源码 example 的客户端Test

* mysql version
  5.7.24-linux-glibc2.12-x86_64

* linux version
  CentOS-7-x86_64

### Issue Description
  1、canal 和 mysql  在一台虚机linux服务器、客户端为本地
  2、配置都是按  example 的配置没有变，新建了 canal用户，密码canal，test数据库，给了全部权限
  3、my.cnf 配置
       [mysqld]
       basedir=/usr/local/mysql
       datadir=/usr/local/mysql/data
       socket=/usr/local/mysql/mysql.sock
       log-bin=mysql-bin
       binlog-format=ROW
       server_id=1
       port=3306
       bind-address=127.0.0.1
  4、canal 启动无异常，日志正常，日志开了DEBUG（开始有一个 testWhileIdle=true 没有配置查询检查的异常，暂时改为testWhileIdle=false）
  5、新建表（DDL）操作，canal.log 和 example.log 日志相关DDL信息，h2 有更新
  6、binlog 日志有更新，ddl、dml都会记录更新，dml记录非明文
  
  尝试解决：
  1、客户端连接不到canal  11111端口，关闭linux防火墙，可以建立连接
  2、开始看到 canal 和 mysql 3306端口有4条链，2个tcp4，2个tcp6，发现 3306 端口是 tcp6监听，关闭了tcp6，my.cnf增加 bind-address=127.0.0.1，3306监听为 tcp4了，但是客户端仍无法获取binlog

**Comment by fairychao** [comment]
3、整个内存 2G，看内存启动后还有100多MB，canal.instance.memory.buffer.size 修改为1024，内存只用 1M，但是还是读不到数据

**Comment by fairychao** [comment]
4、安装了perl，仍然不行
5、改了虚机cpu个数，由1改为2，读取到了..........

**Comment by shubiao-yao** [comment]
尝试下1.1.3版本，我在使用1.1.2利用虚拟机搭建高可用模式中也遇到过这个问题

**Comment by DinoZhang** [comment]
单核cpu设置  `canal.instance.parser.parallel = false`

**Comment by bee0045** [comment]
这个问题困扰了我很久 终于在你这边解决了, 什么配置都正确就是 同步不到 binlog的变动, 浪费了我很多时间     这个注意项感觉有必要在明显的地方 提示出来

**Comment by agapple** [comment]
我加一下文档描述

**Comment by teddylu007** [comment]
hi,楼主，我使用的是canal1.1.4版本的，我遇到的问题是当MySQL数据有更新了之后，canal无法马上读取到，我是通过看canal的日子发现的，但是只要我重启了canal之后，日志才会显示mysql的更新记录，每次都是这样，我也是用得cpu=1得服务器

**Comment by AndyWangJL** [comment]
数据库更新监听不到任何数据，日志也不更新

WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - ---> find start position successfully, EntryPosition[included=false,journalName=mysql-bin.000004,position=94484,serverId=1,gtid=,timestamp=1745601084000] cost : 194ms , the next step is binlog dump
WARN  c.a.otter.canal.parse.inbound.mysql.MysqlConnection - load MySQL @@version_comment : MySQL Community Server - GPL

一直卡在这里
