### ISSUE TITLE
Sync ES是如何保证mysql中与es中的数据是一致的呢？

### ISSUE THREAD

**Issue by shubiao-yao** [alibaba/canal#1435]
### environment

* canal 1.1.3
* mysql 5.7
* kafka 2.0

### Issue Description

请教各位大神：

将mysql中的数据同步至es中是如何保证两者之间数据是一致的呢？

我现在使用canal将mysql中的binlog同步至 kafka 中，然后java client从kafka中取出binlog使用es的bulk方式向es的一个索引中进行同步。

mysql中使用canal监听4张表，es中将这4张表所有的字段组合成1个索引，凡是涉及到这4张表的binlog都写入到kafka。

现在设想，如果从kafka中取出binlog向es同步的过程中出现了异常，就导致mysql和es的数据不一致，请问各位大神是否也在做mysql同步es呢？你们是怎么解决的呢? 

感谢各位大神的分享

**Comment by liuquanal** [comment]
目前我们公司是这样做的:

源表定义一个时间戳字段(比如：seq_id)，加索引，时间戳越精确越好，可惜的就是MySQL没有像SQLServer那样的版本戳字段。
监控语句可以这样写：select max(seq_id) as max_key,min(seq_id) as min_key,count(seq_id) as totals from src_table;

es里面也有对应的写法：

{
  "size": 0,
  "sort": [],
  "aggs": {
    "max_key": {
      "max": {
        "field": "seq_id"
      }
    },
    "min_key": {
      "min": {
        "field": "seq_id"
      }
    }
  }
}

定时查源库和目标库，对比max_key,min_key,totals,即可以知道源库和目标库的实时同步情况。
写个监控程序，定时写监控日志。运维发现有错误，则手动对齐两边的数据。

手动对齐的方法，可以有：
1.调整binlog的时间戳，重新同步一遍
2.自己写程序，直接查源表，把数据重写一遍到es

**Comment by shubiao-yao** [comment]
感谢分享，但我感觉这种还是不靠谱 @liuquanal

**Comment by rewerma** [comment]
通过 _id 啊
