### ISSUE TITLE
canal adapter1.1.3怎么配置同步到mysql实例中所有库和所有表

### ISSUE THREAD

**Issue by githubkevinyou** [alibaba/canal#1439]
### environment

* canal adapter1.1.3
* mysql 5.7.24

### Issue Description
conf/rdb/mytest_user.yml 配置中
dataSourceKey: defaultDS
destination: canal_mysql
outerAdapterKey: mysql1
concurrent: true
dbMapping:
  database: cloud_dev1
#  table: customer
#  targetTable: cloud_dev1.customer
#  targetPk:
#    id: id
  mapAll: true

### Steps to reproduce
这样设置同步失败，如果指定table、targetTable、targetPk、id等能成功同步单个表，请问怎么设置成同步database中所有table？还有一个实例多个库的同步怎么配置？

**Comment by liuquanal** [comment]
1.1.3的支持一对多的同步吧

至于批量同步表，貌似还不支持，但是可以自己想办法实现。比如自己在同步启动前，自动生成所有表的独立配置文件。

**Comment by githubkevinyou** [comment]
mysql数据库自带的M-S同步很简单配置，能实现一个实例的所有库所有表同步；canal adapter文档不清楚具体配置，targetPk 关于联合主键也配置不成功。

**Comment by githubkevinyou** [comment]
经过源码测试，application.yml配置多个name: rdb（ 每个key: mysql1命名不同），rdb文件夹下要为每个表配置dataSourceKey、destination、outerAdapterKey、dbMapping等对应参数，期中
targetPk: # 联合主键时多行
   c_id: c_id
   s_id: s_id
这样就可以单实例多个库多个表同步。

**Comment by liusir11** [comment]
请教下如何配置canal到kafka 单表对应单个topic

**Comment by githubkevinyou** [comment]
没配置过单表对应单个topic，目前同步的都是同一个topic

**Comment by agapple** [comment]
单表对应topic，可以参考一下wiki里的dymaicTopic的配置

**Comment by chaplinthink** [comment]
> 单表对应topic，可以参考一下wiki里的dymaicTopic的配置

具体在ClientAdapter中如何配置?
``` 
 canalAdapters:                            # 适配器列表
  - instance: example                       # canal 实例名或者 MQ topic 名
    groups:                                 # 分组列表
    - groupId: g1                           # 分组id, 如果是MQ模式将用到该值
      outerAdapters:                        # 分组内适配器列表
      - name: logger                        # 日志打印适配器
```
 instance 参数只能对应一个topic, 单表对应一个topic 如何配置呢 @agapple
