### ISSUE TITLE
canal mysql 5.5.20 启动报错

### ISSUE THREAD

**Issue by jingbo0534** [alibaba/canal#1445]
### environment

* canal canal.deployer-1.1.3-SNAPSHOT
* mysql 5.5.20-log

### Issue Description
    canal 启动的时候报错 如下
    java.io.IOException: ErrorPacket [errorNumber=1193, fieldCount=-1, message=Unknown system variable 'binlog_checksum', sqlState=HY000, sqlStateMarker=#]
    with command: set @master_binlog_checksum= @@global.binlog_checksum
![image](https://user-images.githubusercontent.com/12147590/51294977-58247180-1a50-11e9-9ba8-c12ec1d737d1.png)

**Comment by agapple** [comment]
只是warn打印，可以忽略
