### ISSUE TITLE
关于延迟监控的一些疑问

### ISSUE THREAD

**Issue by adamliheng** [alibaba/canal#1447]
### environment

* canal version
1.1.2
* mysql version
5.7.23

### Issue Description
![qq20190117-152952](https://user-images.githubusercontent.com/30104232/51302229-bcedc500-1a6c-11e9-8777-d996a2097101.png)

delay中的master都是几秒，而且变化幅度很大。但是mysql和canal是在一台机器上的，最多几十ms的延迟，我如果使用脚本持续插入这个延迟就回降到300ms左右，我对这个指标的计算有些不太理解。

**Comment by agapple** [comment]
https://github.com/alibaba/canal/wiki/Prometheus-QuickStart

针对没有数据的情况下，delay的计算是依赖于mysql的heartbeat报，如果10秒钟mysql才发我一个报，在这10秒钟内的dealy计算就是 now - lastExecTime
