### ISSUE TITLE
kafka模式重启后消息重复

### ISSUE THREAD

**Issue by waters321** [alibaba/canal#1454]
### environment

canal version 1.1.3
mysql version 5.7.20

### Issue Description
最新代码编译，zookeeper存储消费位点，kafka模式，每次重启后都会把重启前最后一次的消息信息重新发一次，造成kafka里面有重复信息。是设计本如此还是bug，如果要改应该在哪里处理？谢谢，研究半天没找到具体修改位置。

**Comment by rewerma** [comment]
重启的是server端还是client端

**Comment by waters321** [comment]
> 重启的是server端还是client端

server端，zookeeper里记录的位点好像是beginTransaction的位置，然后重启以后貌似会从这个位置把这条数据重新解析一下。是不是zookeeper应该记录endTransaction的位置

**Comment by agapple** [comment]
重复消息是无法避免的, kafka重启/canal重启都会有概率, 加了事务发送只是降低kafka重启带来的重复问题
