### ISSUE TITLE
HA模式 采用H2存储，server切换的时候 消费错误

### ISSUE THREAD

**Issue by bestzhao** [alibaba/canal#1455]
### environment

* canal version
* mysql version

### Issue Description
HA模式的时候，A服务器已经消费了一个星期了，B处于准备状态，当A关闭的时候，B又从配置文件读取到了一个星期前的gtid进行了读取 这个就有问题了

**Comment by agapple** [comment]
你说的HA应该是zookeeper模式把，你得确认切换到B时拿到对应zookeeper的配置是否正确？ 也确认canal的版本，1.1.0的早期几个版本针对写MQ的有HA的问题
