### ISSUE TITLE
如果同时建两个实例（destination）监听同一个数据库 会不会有问题？

### ISSUE THREAD

**Issue by bestzhao** [alibaba/canal#1458]
### environment

* canal version
* mysql version

### Issue Description
故事是这样的：我测试的时候创建了一个destination A监听数据库 db，然后创建了ES-adapter，然后我又创建了destination B 还是监听db，然后有一天A挂了，然后ES-adapter都去用B了，A就没用了 ，这情况正常吗，我看代码是根据数据库-表明作为key去查的，那不是没destination什么事情了。 （ES-Adapter那边）

**Comment by agapple** [comment]
每个destination都有各自独立的adapter
