### ISSUE TITLE
tsdb 中 meta_history与meta_snapshot 编码问题

### ISSUE THREAD

**Issue by lee123lee123** [alibaba/canal#1460]
### environment
* canal version  1.1.0
* mysql version 1.6+

### 数据库有表字段为 utf8mb4 格式，使用 canal_tsdb 时候，
在同步时插入数据进入
 meta_history表 sql_text 字段默认UTF8编码、
 meta_snapshot表中data字段默认UTF8编码，

### 预测条件
在数据进入meta_history ，meta_snapshot 报编码错误

### 复制步骤
监控同步数据

### 实际情况
在数据进入meta_history ，meta_snapshot 报错，utf8mb4 对指定utf8编码字段 入库报错，编码错误，

**Comment by agapple** [comment]
可以提交一个PR给我
