### ISSUE TITLE
[文档纠错]wiki首页时序表结构超链接错误

### ISSUE THREAD

**Issue by smileMrLee** [alibaba/canal#1461]
![image](https://user-images.githubusercontent.com/10806592/51507794-87aaf380-1e2d-11e9-8d9a-d292740f2ecb.png)

现在超链接（错误）：https://github.com/alibaba/canal/wiki/%E6%97%B6%E5%BA%8F%E8%A1%A8%E7%BB%93%E6%9E%84%E6%96%B9%E6%A1%88  该地址是空白页，内容仅“test”。

正确应该链接至：https://github.com/alibaba/canal/wiki/TableMetaTSDB

**Comment by agapple** [comment]
已更新
