### ISSUE TITLE
 canal.adapter-1.1.2  windows start.bat无法启动

### ISSUE THREAD

**Issue by HaoObama** [alibaba/canal#1463]
### environment

* canal version
  canal.adapter-1.1.2  windows start.bat无法启动
* mysql version
  5.7.19-log

### Issue Description
  canal.adapter-1.1.2  windows start.bat无法启动 报错如下：

### Steps to reproduce
1
### Expected behaviour
1
### Actual behaviour
1

**Comment by agapple** [comment]
提问不清晰
