### ISSUE TITLE
mysql 主从binlog差距太大，会导致canal的主备切换失败

### ISSUE THREAD

**Issue by wangjinzhao** [alibaba/canal#1466]
### environment

* canal version  1.1.1(其他版本也是如此)
* mysql version  5.7

### Issue Description
master与standby切换场景，如果mysql本身的主从 binlog文件差别很大的话，会导致切换失败，会找不到position。后面canal的主备切换改变目前的实现方式吗？

**Comment by agapple** [comment]
从 -> 主的切换？

**Comment by wangjinzhao** [comment]
主>从 切换。很多时候切换是正常的能够做到，但是一旦binlog的差有点大的时候，就会切换失败，找不到position，应该是跟目前的切换实现方式有关系吧，每次都需要去停掉canal server,停掉canal-client 然后去zk上删除destination node，然后重启 server 跟client。

**Comment by agapple** [comment]
如果从落后于主，我们会找到主库里最后的binlog timestamp(比如5分钟)，从落后于主(比如在2分钟)，基于5分钟的时间戳去定位，我们会在从库中找到最后一条为2分钟的offest，从这个位点开始继续消费，因为主从关系的存在，从库会慢慢应用2分~5分的binlog数据，确保主从切换不丢binlog消费

**Comment by wangjinzhao** [comment]
切换的大体原理我了解一些，但是确实公司的mysql主从binlog有时候会差距大一点，极端情况下从都没有找到相同序号的binlog文件，canal的切换就形同虚设，这块有没有可能这种切换的策略能考虑下这种情况呢？比如，即使在从上找不到相应的offset，那么可否就从>主 ，找到当前最新的binlog,前推2分钟进行订阅呢，不然订阅就中断了。

**Comment by agapple** [comment]
切换的时候是以时间戳进行定位的，在从上找到最接近这个时间的，如果你走GTID订阅就没这个办法
