### ISSUE TITLE
同步的太慢了 需要改哪些参数吗？

### ISSUE THREAD

**Issue by bestzhao** [alibaba/canal#1468]
### environment

* canal version
* mysql version

### Issue Description
在高峰期的时候发现同步有延时，需要+u 还是+内存呢

**Comment by agapple** [comment]
多大的变更TPS?

**Comment by WentHao** [comment]
也发现类似问题，我的是一张700w表的全量同步到es，最终到es每秒只有100条数据。从现在来看server端cpu一直单核100%，加u没用，内存也没压力，就是效率低，有办法多u并发么

**Comment by WhatisAnt** [comment]
> 也发现类似问题，我的是一张700w表的全量同步到es，最终到es每秒只有100条数据。从现在来看server端cpu一直单核100%，加u没用，内存也没压力，就是效率低，有办法多u并发么

你这个瓶颈是在es数据插入，你可以尝试批量往es写入数据
