### ISSUE TITLE
为什么现在不指定起始位置的时候，默认的是最后一条事件之前的的位置，而不是show master status现实的位置

### ISSUE THREAD

**Issue by zhouluoyang0406** [alibaba/canal#1470]
### environment
mac
* canal version
1.1.3-snapshot
* mysql version
5.7
### Issue Description
为什么现在不指定起始位置的时候，默认的是最后一条事件之前的的位置，而不是show master status现实的位置,文档中描述不是说是show master status 的位置么;是有什么特殊考量么？
### Expected behaviour
mysql 最新的位点
![image](https://user-images.githubusercontent.com/42863611/51665050-d7d4b200-1ff5-11e9-8069-a6da90c8a405.png)
canal client 的消费日志
![image](https://user-images.githubusercontent.com/42863611/51665079-e3c07400-1ff5-11e9-9cfb-0f0d807ca514.png)
canal server启动日志
![image](https://user-images.githubusercontent.com/42863611/51665572-0901b200-1ff7-11e9-919d-30024589bd6b.png)

**Comment by agapple** [comment]
需要获取binlog GTID/timestamp的准确信息
