### ISSUE TITLE
请问下为什么canal-client要内置一个rocketmq,导致和现有的rocketmq依赖冲突.

### ISSUE THREAD

**Issue by WintererOoO** [alibaba/canal#1471]
### environment

* canal version
1.1.2
* mysql version
5.7

### Issue Description
请问下为什么canal-client要内置一个rocketmq,导致和现有的rocketmq依赖冲突.内置的TransactionMQProducer缺少setExecutorService方法.

### Steps to reproduce
引入canal和rocketmq,new TransactionMQProducer()并调用setExecutorService方法.
### Expected behaviour
启动成功
### Actual behaviour
启动失败

**Comment by agapple** [comment]
如果有版本差异，可以提交一个PR给我
