### ISSUE TITLE
pom转gradle出现异常

### ISSUE THREAD

**Issue by wurongjun** [alibaba/canal#1472]
### environment
最新Master分支代码
* canal version
* mysql version

### Issue Description
根目录下运行 **gradle init --type pom** 后，gradle build时出现异常
canal.prometheus模块加载失败
`A problem occurred evaluating project ':canal.prometheus'`
`Could not find method providedCompile() for arguments [project ':canal.instance.core']`

**Comment by agapple** [comment]
gradle没怎么用过，可以提交一个优化PR给我
