### ISSUE TITLE
rowChage.getRowDatasList() sizes是0.

### ISSUE THREAD

**Issue by jerrysbest** [alibaba/canal#1474]
### environment

* canal version 1.1.2
* mysql version 5.7

### Issue Description
rowChage.getRowDatasList() sizes是0.

### Steps to reproduce
可以解析到sql语句，insert,update和delete，rowChage.getRowDatasList() sizes是0.
是不是因为binlog模式是 mixed，mixed就无法使用canal了吗？
公司目前都是用的mixed
### Expected behaviour
   希望可以获取数据
### Actual behaviour
目前无法获取到数据

**Comment by agapple** [comment]
mixed可以获取到binlog，但无法获取row模式里的DML数据

**Comment by liangzhaoqiang** [comment]
> mixed可以获取到binlog，但无法获取row模式里的DML数据

获取DML（insert,update和delete）的数据时rowChage.getRowDatasList()里面可以获取数据字段，但是想要获取的形式是sql形式要怎么弄呢？rds上面要配置什么参数吗？
