### ISSUE TITLE
canal server对接RocketMq没有使用rocketmq集群

### ISSUE THREAD

**Issue by flackyang** [alibaba/canal#1476]
### environment

* canal version 1.1.3
* mysql version 5.7.20

### Issue Description
canal server 对接RocketMQ集群(2主2从模式），集群中两个主broker上都创建了同一个topic，但是canal server 写消息到RocketMQ集群时固定只写入其中一个broker，没有往两个broker中的topic分配数据

**Comment by agapple** [comment]
看一下MQ wiki看看是否有配置正确的topic hash规格

**Comment by flackyang** [comment]
@agapple 配置使用了dynamicTopic，没有使用partitionHash配置，数据一直投递到一个固定的broker(broker-a), 没有在不同的broker上分配数据

**Comment by agapple** [comment]
可以使用table hash来分散到多个broker上

**Comment by liujiansgit** [comment]
@flackyang 你这个问题解决了吗，我搭建起来也是只投递到broker-a，只是不同的分区
