### ISSUE TITLE
canal目前支持oracle吗？

### ISSUE THREAD

**Issue by kingzone** [alibaba/canal#148]
canal目前支持oracle吗？刚看了一下代码，貌似还不支持吧？
[https://github.com/alibaba/canal/blob/master/instance/manager/src/main/java/com/alibaba/otter/canal/instance/manager/CanalInstanceWithManager.java#L295](https://github.com/alibaba/canal/blob/master/instance/manager/src/main/java/com/alibaba/otter/canal/instance/manager/CanalInstanceWithManager.java#L295)
是不是意味着otter也只支持mysql，读和写都是？

**Comment by agapple** [comment]
可以看下wiki，都有明确描述，目前不支持oracle，对于oracle有需求可以参考我的另一个项目：https://github.com/alibaba/yugong

**Comment by kingzone** [comment]
Yugong 支持oracle到mysql ，反过来从mysql 到oracle也支持吗

**Comment by agapple** [comment]
yugong开源不支持mysql->oracle

**Comment by OpenZYK** [comment]
请问oracle版的canal就是yugong么？还是有另一个基于ogg实现的版本？

**Comment by agapple** [comment]
https://github.com/alibaba/yugong，yugong是基于oracle物化视图来做的

**Comment by hhj970815** [comment]
2020年了 可以支持canal吗

**Comment by 981476460** [comment]
都2021年，canal可以支持oracle吗

**Comment by aistocker** [comment]
2021年7月5日，canal不会支持oracle的！
