### ISSUE TITLE
如何实现canal1.3配置动态topic，实现单表单topic

### ISSUE THREAD

**Issue by liusir11** [alibaba/canal#1480]
### environment

* canal version 1.1.3
* mysql version 5.7.24

### Issue Description
利用canal1.3实现 指定表到kafka指定topic中，如何配置

### Steps to reproduce
我的配置是这样的，

  1 #################################################
  2 ## mysql serverId , v1.0.26+ will autoGen
  3 # canal.instance.mysql.slaveId=0
  6 canal.instance.gtidon=false
  7 
  8 # position info
  9 canal.instance.master.address=10.6.10.221:3306
 10 canal.instance.master.journal.name=
 11 canal.instance.master.position=
 12 canal.instance.master.timestamp=
 13 canal.instance.master.gtid=
 14 
 15 # rds oss binlog
 16 canal.instance.rds.accesskey=
 17 canal.instance.rds.secretkey=
 18 canal.instance.rds.instanceId=
 19         
 20 # table meta tsdb info
 21 canal.instance.tsdb.enable=true 
 22 #canal.instance.tsdb.url=jdbc:mysql://127.0.0.1:3306/canal_tsdb
 23 #canal.instance.tsdb.dbUsername=canal
 24 #canal.instance.tsdb.dbPassword=canal
 25 
 26 #canal.instance.standby.address =
 27 #canal.instance.standby.journal.name =
 28 #canal.instance.standby.position =
 29 #canal.instance.standby.timestamp =
 30 #canal.instance.standby.gtid=  
 31 
 32 # username/password 
 33 canal.instance.dbUsername=root
 34 canal.instance.dbPassword=123456
 35 canal.instance.connectionCharset = UTF-8
 36 canal.instance.defaultDatabaseName =test_sqoop
 37 # enable druid Decrypt database password
 38 canal.instance.enableDruid=false
 39 #canal.instance.pwdPublicKey=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALK4BUxdDltRRE5/zXpVEVPUgunvscYFtEip3pmLlhrWpacX7y7GCMo2/JM6LeHm
    iiNdH1FWgGCpUfircSwlWKUCAwEAAQ==
 40 
 41 # table regex
 42 canal.instance.filter.regex=test_sqoop\\..*
 43 # table black regex
 44 canal.instance.filter.black.regex=
 45 
 46 # mq config
 47  canal.mq.topic=test_sqoop
 48 # dynamic topic route by table regex
 49 #canal.mq.dynamicTopic=.*,mytest\\..*,mytest2.user,.*\\..*
 50 #canal.mq.dynamicTopic=canaltest:test_sqoop.student;canal113test1:test_sqoop.user_tab
 51 canal.mq.dynamicTopic=test_sqoop\\.student
 52 canal.mq.partition=0
 53 auto.create.topics.enable =true
 54 # hash partition config
 55 #canal.mq.partitionsNum=3
 56 #canal.mq.partitionHash=test.table:id^name,.*\\..*
 57 #################################################
### Expected behaviour
配置中50行是希望test_sqoop.student这个表输出到canaltest这个topic，test_sqoop.user_tab到 canal113test1这个topic
### Actual behaviour
kafka中没有创建相关的topic，消费不到topic消息

**Comment by flackyang** [comment]
看下wiki中关于对接MQ的部分，dynamicTopic配置的说明
