### ISSUE TITLE
对设计方式的疑问

### ISSUE THREAD

**Issue by wurongjun** [alibaba/canal#1483]
### environment
最新master分支代码
* canal version
* mysql version

### Issue Description
适配器模块，近期提供了从数据库拉取配置更新application.yml的逻辑。如果现在有个管理平台会更新这条配置，管理端是不是维护一整个application.yml配置文件的内容

![image](https://user-images.githubusercontent.com/22488212/51894046-af77f980-23e1-11e9-951c-39931f1b4a8c.png)

**Comment by rewerma** [comment]
adapter launcher会对application.yml进行监听，有修改会重启整个spring容器
