### ISSUE TITLE
单表单topic多分区同步数据量不稳定

### ISSUE THREAD

**Issue by mjjian0** [alibaba/canal#1486]
### environment

* canal version：1.1.3
* mysql version：5.6.16

### Issue Description
以下是canal instance 配置：
canal.mq.topic=test
#canal.mq.partition=0

canal.mq.partitionsNum=6
canal.mq.partitionHash=test.test1:id

**问题**：
如果多分区配置，发现同步出来的数据会根据 hash的字段或多或多（比如按id  hash  就会少，按order_id 
 hash  会多，id是主键。）
如果是但分区同步到 分区 0，那数据就是正常的

**Comment by agapple** [comment]
hash之后针对对应字段值的变化，可能就会乱序，需要注意这点

**Comment by mjjian0** [comment]
@agapple hash的字段值并不会变化，因为id是主键。顺序变，但是数据量应该不会变化吧，我这边测试下来，如果是单独一个分区的话，数据量不会少，根据id字段hash到不同分区，数据会少。

**Comment by agapple** [comment]
你是怎么判断数据量有多和少，直接数MQ里的数据和记录的DML操作次数对比？

**Comment by mjjian0** [comment]
@agapple 
是这样的：
我用storm取 canal同步到kafka的数据按小时计算销售额，然后用离线数据取对比，每当我用canal同步到单topic 单partition的数据时，数据结果和离线就是对上的，当用单topic多partition配置的数据时，数据就是不正确的

**Comment by agapple** [comment]
可以尝试一下1.1.3 alpha-3版本，目前已经对partition hash的做了修复
