### ISSUE TITLE
新增canal client 无法正常消费

### ISSUE THREAD

**Issue by sdmjhca** [alibaba/canal#1487]
### environment

* canal version 1.0.24
* mysql version 5.6

### Issue Description
在原有的canal服务的基础上新增了一个destination：example2，example2的log过一段时间就会报这个错
，而原example1的log一直是正常的。

![image](https://user-images.githubusercontent.com/26153843/51955198-f5829b00-247d-11e9-8773-673f0319acfc.png)

**Comment by agapple** [comment]
尝试升级一下最新版吧 1.1.3
