### ISSUE TITLE
关于BINLOG_SEND_ANNOTATE_ROWS_EVENT

### ISSUE THREAD

**Issue by OpenZYK** [alibaba/canal#149]
在mysql官方文档中，基于COM_BINLOG_DUMP协议的dump请求中flags只看到BINLOG_DUMP_NON_BLOCK这一种，请问BINLOG_SEND_ANNOTATE_ROWS_EVENT代表什么意思？在官方文档的哪里可以找到相关说明？

**Comment by agapple** [comment]
搜索： mysql binlog protocol
