### ISSUE TITLE
Canal-1.1.2 RDS支持无效 Could not find first log file name in binary log index file

### ISSUE THREAD

**Issue by zhouluoyang0406** [alibaba/canal#1491]
### environment
Canal-1.1.2
* canal version
canal.instance.master.address=rm-2zebsf82n67u4ahbl.mysql.rds.aliyuncs.com:3306
canal.instance.master.journal.name=mysql-bin.000128
canal.instance.master.position=588537
canal.instance.master.timestamp=1548610582000
canal.instance.master.gtid=
# rds oss binlog
canal.instance.rds.accesskey=LTAI3XXXXXX
canal.instance.rds.secretkey=etotOyQ8reXXXXXXXXXXXX
canal.instance.rds.instanceId=rm-2zebsf82nXXXXXXXXXXXX
* mysql version

### Issue Description
java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = Could not find first log file name in binary log index file
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:102) ~[classes/:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:225) [classes/:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:257) [classes/:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_192]

### Actual behaviour
###下列的测试
public class RdsBinlogOpenApiTest {
    @Test
    public void testSimple() throws Throwable {
        Date startTime = DateUtils.parseDate("2018-08-10 12:00:00", new String[] { "yyyy-MM-dd HH:mm:ss" });
        Date endTime = DateUtils.parseDate("2018-08-11 12:00:00", new String[] { "yyyy-MM-dd HH:mm:ss" });
        String url = "https://rds.aliyuncs.com/";
        String ak = "";
        String sk = "";
        String dbInstanceId = "";

        RdsBackupPolicy backupPolicy = RdsBinlogOpenApi.queryBinlogBackupPolicy(url, ak, sk, dbInstanceId);
        System.out.println(backupPolicy);

        List<BinlogFile> binlogFiles = RdsBinlogOpenApi.listBinlogFiles(url, ak, sk, dbInstanceId, startTime, endTime);
        System.out.println(binlogFiles);
    }
}
1.能够成功返回binlogFiles,并通过binlogFiles里面的路径可以下载binlog文件。
2.通过打断点确定一直重试失败，RdsBinlogOpenApi.listBinlogFiles未调用该方法

**Comment by zhouluoyang0406** [comment]
find start position successfully----看canal的代码只有抛出PositionNotFoundException异常才会启动读取RDS OSS中binlog的逻辑。

**Comment by zhouluoyang0406** [comment]
看了canal 1.1.2代码 如果meta.log或者zk里面为空的时候，如果配置binlog的位置在oss中，是不会去主动去oss里面拉取数据的。也就是说现在的代码逻辑是不支持 配置的binlog位置直接在oss中的。

**Comment by lt5227** [comment]
请问这个问题现在是怎么解决的？
