### ISSUE TITLE
BUG:  配置  mapAll: true  时出现的bug

### ISSUE THREAD

**Issue by silentwu** [alibaba/canal#1492]
![image](https://user-images.githubusercontent.com/5729336/51974912-fd613000-24bb-11e9-9e82-a3baae043671.png)

我配置的是
mapAll: true 

如果数据库的字段是大写的 ，比如：personName  
那么会出现下面的错误，主要是字段被转换成了小写：
![image](https://user-images.githubusercontent.com/5729336/51975210-a1e37200-24bc-11e9-8d8a-32a14009ed2e.png)

**Comment by wurongjun** [comment]
你代码不是最新的
https://github.com/alibaba/canal/blob/43f869599d48008a966e7b000b889dc4bac0bb9a/client-adapter/rdb/src/main/java/com/alibaba/otter/canal/client/adapter/rdb/service/RdbSyncService.java#L311-L318

**Comment by silentwu** [comment]
好吧 ，我用的版本是 v1.1.3-alpha-2

**Comment by rewerma** [comment]
最新版的已经解决
