### ISSUE TITLE
关于canal高可用的问题

### ISSUE THREAD

**Issue by qq960826** [alibaba/canal#1493]
2台主机进行备份一台mysql，一台为running，另外一台为standby，那么如果running挂掉后，standby的数据是从running读取binlog的位置开始读取还是从standby上次读取的位置开始读取呢？

**Comment by mycat-lulin** [comment]
从zk读取running提交到zk的binlog的位置。

**Comment by iorilchen** [comment]
那running的server会频繁地写binlog位置到zk的话，性能不会很好。

**Comment by mycat-lulin** [comment]
不是实时写的,你可以看看源码

**Comment by qq960826** [comment]
那running备份mysql之后，standby同时也会同步running吗
