### ISSUE TITLE
canal-1.1.2从oss上同步数据后，不能切回binlog上进行同步

### ISSUE THREAD

**Issue by zhouluoyang0406** [alibaba/canal#1494]
### environment
* canal version
Canal-1.1.2
* mysql version

### Issue Description
canal从oss上同步数据后，不能切回binlog上进行同步

### Steps to reproduce
rds的binlog中有138-141的几个日志
![image](https://user-images.githubusercontent.com/42863611/52024232-fc231800-253a-11e9-854b-31d300c1db16.png)
canalserver卡在140
![image](https://user-images.githubusercontent.com/42863611/52024244-15c45f80-253b-11e9-8b8c-717f6c98e452.png)
canalclient也卡在140
![image](https://user-images.githubusercontent.com/42863611/52024254-24127b80-253b-11e9-8403-7d9d88c6847d.png)
jstack表示卡在下载
![image](https://user-images.githubusercontent.com/42863611/52024324-781d6000-253b-11e9-8fdb-a0fc2d557275.png)
### Actual behaviour
切回普通模式的时候报错
![image](https://user-images.githubusercontent.com/42863611/52025647-23301880-2540-11e9-9fed-07c61ed3b475.png)
排查出信息点，是在计划同步binlong-000141,offset=4的时候报错的。
![image](https://user-images.githubusercontent.com/42863611/52025926-28da2e00-2541-11e9-8e82-628eb3d7a48f.png)
解决方案
![image](https://user-images.githubusercontent.com/42863611/52026347-74410c00-2542-11e9-97ce-660fb16af939.png)

**Comment by zhouluoyang0406** [comment]
加上 这句解决了问题 dumpErrorCount = 0;

**Comment by zhouluoyang0406** [comment]
@agapple 看下这种改发可以不。

**Comment by agapple** [comment]
你指定的起始位点是啥？

**Comment by zhouluoyang0406** [comment]
@agapple 起始位点是binlog.000127

**Comment by agapple** [comment]
不太记得是否有修复过，先试试1.1.3最新版本
