### ISSUE TITLE
使用内嵌canal的方法启动canal,zk地址错误的情况下，调用CanalServerWithEmbedded.stop()，zk连接尝试不会停止

### ISSUE THREAD

**Issue by zhouluoyang0406** [alibaba/canal#1499]
### environment

* canal version
canal-1.1.2
* mysql version

### Issue Description
使用内嵌canal的方法启动canal
使用zk存储meta信息如果
zk地址错误的情况下，调用
  canalServer.stop(destination);
  canalServer.stop();
### Steps to reproduce
![image](https://user-images.githubusercontent.com/42863611/52162736-655d8380-2713-11e9-8d93-9c4243770d9d.png)

### Actual behaviour
otter也有类型的问题,不能关闭zk连接

**Comment by pc-fuqq** [comment]
Up

**Comment by agapple** [comment]
没太懂问题，是说启动的时候给了一个错误的zk地址，stop无法退出？

**Comment by zhouluoyang0406** [comment]
@agapple 是的。给了一个错误的zk地址。然后执行
canalServer.stop(destination);
canalServer.stop();
zk的报错仍在继续就是上面的截图。一直报错connection refused。定位到最下面是zk的超时默认好像是240天。

**Comment by agapple** [comment]
canalServer里的stop没有去关闭zk，如果用的是otter，zk链接是不会去关闭的

**Comment by zender-projects** [comment]
请问，canal内嵌的代码示例在哪？
