### ISSUE TITLE
监听mysql从库,报错

### ISSUE THREAD

**Issue by NotTheSameWorld** [alibaba/canal#1501]
### environment

* canal version
canal.deployer-1.1.3-SNAPSHOT
* mysql version
5.6
### Issue Description

监听mysql从库时
配置:从库是按着https://github.com/alibaba/canal/wiki/AdminGuide进行配置
报错如下：
我创建了canal账号，instance.properties配置的也是canal账号，报错却报另外一个账号
![canal](https://user-images.githubusercontent.com/23094497/52553177-ae04f300-2e1d-11e9-9eb2-7d2c8e043379.jpg)

大神，有没有什么解决办法

**Comment by agapple** [comment]
这个是binlog里的SQL语句在解析的时候报错，和你binlog dump的账号没啥关系，可以忽略
