### ISSUE TITLE
canal client 客户端只能一直循环吗

### ISSUE THREAD

**Issue by IRambler** [alibaba/canal#1502]
canal client 客户端只能一直循环吗
try {
            connector.connect();
            connector.subscribe(systemConfigs.getSubscribe());//joyshebao schema下joy_document开头的所有表
            while (true) {
                Message message = connector.getWithoutAck(batchSize); // 获取指定数量的数据
                batchId = message.getId();
                int size = message.getEntries().size();
                if(batchId != -1 && size != 0) {//存在数据
                    printEntry(message.getEntries());
                }
//                if (batchId == -1 || size == 0) {//空数据
//                } else {//有数据
//                }

                connector.ack(batchId); // 提交确认
                // connector.rollback(batchId); // 处理失败, 回滚数据
            }

**Comment by agapple** [comment]
是的，可以看下client example的代码
