### ISSUE TITLE
canalclient 谁有使用实例

### ISSUE THREAD

**Issue by IRambler** [alibaba/canal#1503]
canalclient 谁有使用实例

**Comment by wurongjun** [comment]
https://github.com/alibaba/canal/wiki/ClientExample

**Comment by IRambler** [comment]
请问您一下，我使用canal service取mysql的binlog，隔一段时间就会造成mysql数据库的cpu过高，导致数据库异常；

还有一点，请问canal client只能使用
---------------------
CanalConnector connector = CanalConnectors.newSingleConnector(new InetSocketAddress(AddressUtils.getHostIp(),
                                                                                        11111), "example", "", "");
    int batchSize = 1000;
    int emptyCount = 0;
    try {
        connector.connect();
        connector.subscribe(".*\\..*");
        connector.rollback();
        int totalEmptyCount = 120;
        while (emptyCount < totalEmptyCount) {
            Message message = connector.getWithoutAck(batchSize); // 获取指定数量的数据
            long batchId = message.getId();
            int size = message.getEntries().size();
            if (batchId == -1 || size == 0) {
                emptyCount++;
                System.out.println("empty count : " + emptyCount);
                try {
                    Thread.sleep(1000);
                } catch (InterruptedException e) {
                }
            } else {
                emptyCount = 0;
                // System.out.printf("message[batchId=%s,size=%s] \n", batchId, size);
                printEntry(message.getEntries());
            }

            connector.ack(batchId); // 提交确认
            // connector.rollback(batchId); // 处理失败, 回滚数据
        }

        System.out.println("empty too many times, exit");
    } finally {
        connector.disconnect();
    }这种形式去不断的请求数据吗？如何能做到，有数据库的数据更新时，canal client才会获取到信息，而不是这种一直去请求刷新的形式；

**Comment by wurongjun** [comment]
> 请问您一下，我使用canal service取mysql的binlog，隔一段时间就会造成mysql数据库的cpu过高，导致数据库异常；
> 
> ## 还有一点，请问canal client只能使用
> CanalConnector connector = CanalConnectors.newSingleConnector(new InetSocketAddress(AddressUtils.getHostIp(),
> 11111), "example", "", "");
> int batchSize = 1000;
> int emptyCount = 0;
> try {
> connector.connect();
> connector.subscribe("._\.._");
> connector.rollback();
> int totalEmptyCount = 120;
> while (emptyCount < totalEmptyCount) {
> Message message = connector.getWithoutAck(batchSize); // 获取指定数量的数据
> long batchId = message.getId();
> int size = message.getEntries().size();
> if (batchId == -1 || size == 0) {
> emptyCount++;
> System.out.println("empty count : " + emptyCount);
> try {
> Thread.sleep(1000);
> } catch (InterruptedException e) {
> }
> } else {
> emptyCount = 0;
> // System.out.printf("message[batchId=%s,size=%s] \n", batchId, size);
> printEntry(message.getEntries());
> }
> 
> ```
>         connector.ack(batchId); // 提交确认
>         // connector.rollback(batchId); // 处理失败, 回滚数据
>     }
> 
>     System.out.println("empty too many times, exit");
> } finally {
>     connector.disconnect();
> }这种形式去不断的请求数据吗？如何能做到，有数据库的数据更新时，canal client才会获取到信息，而不是这种一直去请求刷新的形式；
> ```
==有数据库的数据更新时，canal client才会获取到信息==，那就要用推模式，不是拉模式，这里设计推和拉的优劣区别，你可以研究下

**Comment by IRambler** [comment]
那请问想要使用推模式，那如何配置才能改为这种推模式呢？

**Comment by wurongjun** [comment]
> 那请问想要使用推模式，那如何配置才能改为这种推模式呢？

推和拉不是可以随便调整的，一般在设计整个系统架构时就确定了使用哪一种。canal client采用了拉的模式。如果想使用推的方式，需要canal server做相应的调整，现在来看应该是不支持的。

**Comment by IRambler** [comment]
canal server不能通过参数改为推的模式是吗？ 请问canal获取binlog导致mysql数据库cpu高是因为canal client 拉取问题导致，还是canal server导致的呢？请问是否有什么建议

**Comment by wurongjun** [comment]
> canal server不能通过参数改为推的模式是吗？ 请问canal获取binlog导致mysql数据库cpu高是因为canal client 拉取问题导致，还是canal server导致的呢？请问是否有什么建议

跟canal没有关系的。canal server就是模拟自己是一个mysql slave节点。mysql推送binlog导致cpu高应该是mysql自己的问题吧 
@agapple maintanter你怎么看

**Comment by IRambler** [comment]
目前我在生产环境中部署的canal服务，过一段时间就会出现cpu彪高的现象，导致其他服务的查询不能执行，我们运维就得关闭canal服务，再重启，然后过一段时间后又会出现同样的问题

**Comment by IRambler** [comment]
@agapple 请问这种情况您是否遇到过，该如何解决？

**Comment by agapple** [comment]
cpu过高的情况，使用的canal版本是啥？之前有一些while循环处理不好，会有单cpu被耗尽的问题，可以考虑升级1.1.3版本
