### ISSUE TITLE
canalclient直接同步到elasticsearch的时候，必现丢失数据的情况

### ISSUE THREAD

**Issue by zihaoCheng** [alibaba/canal#1504]
### environment

* canal 1.1.2/1.1.3
* mysql 5.7

### Issue Description
当mysql中的某个字段为null或者空字符串，更新该字段的值，cannal adapter中有update日志记录，但是es中不会更新。其它任何情况都正常。
### Steps to reproduce
数据库中的一个字段的值为null，修改它的值为123，查看es

### Expected behaviour
该值为123
### Actual behaviour
该值为null

**Comment by zihaoCheng** [comment]
这个bug还存在的

**Comment by bee0045** [comment]
/**
     * 将dml的data, old转换为es的data
     *
     * @param mapping 配置mapping
     * @param dmlData dml data
     * @param esFieldData es data
     * @return 返回 id 值
     */
    public Object getESDataFromDmlData(ESMapping mapping, Map<String, Object> dmlData, Map<String, Object> dmlOld,
                                       Map<String, Object> esFieldData) {
        SchemaItem schemaItem = mapping.getSchemaItem();
        String idFieldName = mapping.get_id() == null ? mapping.getPk() : mapping.get_id();
        Object resultIdVal = null;
        for (FieldItem fieldItem : schemaItem.getSelectFields().values()) {
            String columnName = fieldItem.getColumnItems().iterator().next().getColumnName();

            if (fieldItem.getFieldName().equals(idFieldName)) {
                resultIdVal = getValFromData(mapping, dmlData, fieldItem.getFieldName(), columnName);
            }

            if (dmlOld.get(columnName) != null && !mapping.getSkips().contains(fieldItem.getFieldName())) {
                esFieldData.put(fieldItem.getFieldName(),
                    getValFromData(mapping, dmlData, fieldItem.getFieldName(), columnName));
            }
        }
        return resultIdVal;
    }

这个bug在 上段代码中的dmlOld.get(columnName) != null   改为 dmlOld.containsKey(columnName) 即可修复
