### ISSUE TITLE
是否支持mysql多表同步到es

### ISSUE THREAD

**Issue by linyongfu2013** [alibaba/canal#1506]
### environment

* canal version    1.1.3
* mysql version   5.7.20
* es version   6.5.0

### Issue Description
如何一次批量同步mysql 单库里的所有表到 es 里

看文档介绍，好像只能单表同步？是否支持多表同步，需要如何配置？

**Comment by agapple** [comment]
肯定支持多表同步啊，先看下wiki摸索一下吧
