### ISSUE TITLE
[pool-4-thread-1] ERROR com.alibaba.otter.canal.server.CanalMQStarter - batchId:289 is not the firstly:92 com.alibaba.otter.canal.meta.exception.CanalMetaManagerException: batchId:289 is not the firstly:92

### ISSUE THREAD

**Issue by Memory30** [alibaba/canal#1508]
### environment

* canal version 1.3
* mysql version 5.50

### Issue Description
使用canal配置动态topic时，出现如下的错误
[pool-4-thread-1] ERROR com.alibaba.otter.canal.server.CanalMQStarter - batchId:289 is not the firstly:92
com.alibaba.otter.canal.meta.exception.CanalMetaManagerException: batchId:289 is not the firstly:92
请问这个是哪里造成的啊

instance.propertites中的动态topic

#canal.instance.filter.regex=.*\\..*
canal.instance.filter.regex=DMS\\.table_design,DMS\\.column_design,DMS\\.test,DMS\\.task
# table black regex
canal.instance.filter.black.regex=

# mq config
#canal.mq.topic=example
# dynamic topic route by table regex
#canal.mq.dynamicTopic=.*,mytest\\..*,mytest2.user
canal.mq.dynamicTopic=DMS\\..*

**Comment by Memory30** [comment]
@agapple 同时，再想问下canal.instance.filter.regex的长度有没有限制

**Comment by agapple** [comment]
regex有长度限制的，最长应该是4k

**Comment by duanshouliang** [comment]
请问这个问题怎么解的呢？

**Comment by Millet2020** [comment]
请问这个问题怎么解的呢？

**Comment by stevensam-lin** [comment]
请问这个问题怎么解的呢？

**Comment by comin2013** [comment]
我也遇到这个问题了, 请问你是怎么解决的啊?

**Comment by comin2013** [comment]
https://blog.csdn.net/u013645668/article/details/117670104?spm=1001.2014.3001.5501

**Comment by comin2013** [comment]
可以参考这个:https://blog.csdn.net/u013645668/article/details/117670104
