### ISSUE TITLE
canal版本切换的平滑演进

### ISSUE THREAD

**Issue by gezhongwunai** [alibaba/canal#1509]
### environment
* canal version 1.1.1
* mysql version 5.6.36

### Issue Description
如何从canal 1.1.1 平滑演进的 canal 1.1.3
### Steps to reproduce
暂时还没有方案
### Expected behaviour
平滑演进，并且数据不丢失
### Actual behaviour
现在要停服重启canal

**Comment by gezhongwunai** [comment]
有人能回答吗，谢谢啦

**Comment by DinoZhang** [comment]
使用`HA`模式，添加部署`canal 1.1.3`，关闭`canal 1.1.1`

**Comment by agapple** [comment]
LS正解
