### ISSUE TITLE
canal adapter无法接收到ddl更新表结构数据

### ISSUE THREAD

**Issue by jiuchengspotorg** [alibaba/canal#1511]
canal版本使用的master
mysql5.6
canal adapter无法接收到ddl更新表结构数据，dml数据能接收到。

CanalConnector connector = CanalConnectors.newSingleConnector(new InetSocketAddress(AddressUtils.getHostIp(), 11111), "example", "canal", "canal"); ddl数据也无法获取

**Comment by rewerma** [comment]
adapter不会对ddl做处理，rdb配置为mirrorDB: true 可以同步库表，其它情况都需要手动修改映射配置

**Comment by AlfredNing** [comment]
canal-adapter 对于ddl 和dml是如何处理的，我看代码写的是一批数据中，有ddl立即执行，之后执行dml 集合，这个不保证顺序的嘛
