### ISSUE TITLE
zk位点信息会被删除

### ISSUE THREAD

**Issue by yxzhang666** [alibaba/canal#1515]
canal version 1.0.24
停止canal 客户端的时候，调用了CanalConnector.unsubscribe() 和 CanalConnector.close()
发现有些instance的在zk中的 ../1001/cursor 节点会被删除
看到源码里当 执行unsubscribe()方法的时候会递归删除  ../1001的所有信息。
为什么要有这个逻辑？为保证我们关闭client的时候，cursor信息不丢失，我们该怎么处理

**Comment by agapple** [comment]
不要做unsubscribe操作啊，只做disconnect就可以
