### ISSUE TITLE
adapter 模块如何调试

### ISSUE THREAD

**Issue by linyongfu2013** [alibaba/canal#1519]
### environment

* canal version    1.1.3
* mysql version   5.7.20

### Issue Description
在 idea 工具里，直接运行 client-adapter.launcher，报异常，找不到es配置文件：
```
2019-02-18 11:53:46.722 ERROR 93313 --- [           main] c.a.o.c.a.l.loader.CanalAdapterLoader    : Load canal adapter: es failed
java.lang.RuntimeException: java.lang.RuntimeException: Config dir not found.
```

可以看出是，这样启动launcher 没有把 es adapter 组件一起打包，所以在classes 目录下找不到es 的配置文件，请问有什么办法可以调试代码？

**Comment by JunRzz** [comment]
把es配置文件放class路径下就可以了

**Comment by linyongfu2013** [comment]
> 把es配置文件放class路径下就可以了

确实可以了，谢谢
