### ISSUE TITLE
canal是否和MQ消息一样只能保证最少一次，不能保证只有一次。

### ISSUE THREAD

**Issue by minotaursu** [alibaba/canal#152]
在数据库主备切换，canal崩溃重启等情况，canal是否会重复发送消息？出现相同的insert语句。

**Comment by agapple** [comment]
没法保证

**Comment by minotaursu** [comment]
除了网络因素，是否有情况一定会出现重复消息，例如kill -9 canal pid,然后重启。如果有必然出现重复的情况方便进行一些测试。

**Comment by agapple** [comment]
kill -9就是一种网络不确定因素，我数据发给你了，你还没返回ack给我，我只能下次再发给你
