### ISSUE TITLE
数据同步缓慢

### ISSUE THREAD

**Issue by acuitong** [alibaba/canal#1521]
同步测试10万条后会出现数据同步缓慢的情况，必须进行重启才能恢复，再次同步十万多条就又缓慢了，是什么情况啊

**Comment by agapple** [comment]
测试的是canal 1.1.3版本？

**Comment by acuitong** [comment]
测试的是最新版的，大约测试到十万条数据的时候，会出现数据同步缓慢，cpu占用率上升gc线程占用升高

**Comment by acuitong** [comment]
测试的是最新版的，大约测试到十万条数据的时候，会出现数据同步缓慢，cpu占用率上升gc线程占用升高

**Comment by acuitong** [comment]
测试的是最新版的，大约测试到十万条数据的时候，会出现数据同步缓慢，cpu占用率上升gc线程占用升高

**Comment by withlin** [comment]
看下 监控？ 瓶颈在哪？

**Comment by acuitong** [comment]
瓶颈是在十万条以后，需要重启client才会恢复，机器整体负载正常，client端CPU使用率达到100%以上

**Comment by acuitong** [comment]
![image](https://user-images.githubusercontent.com/40566190/52988383-f170ea00-3439-11e9-90aa-6982527bc53c.png)
十万条前面RES这项一直在增长，十万后就开始不增长了，然后就同步缓慢

**Comment by acuitong** [comment]
推测为内存溢出了，代码层的漏洞应该存在一定问题

**Comment by acuitong** [comment]
![image](https://user-images.githubusercontent.com/40566190/53002451-b1c0f700-3467-11e9-84ff-c205236f62a4.png)
堆空间分配6G，同步数据15万，这些类占用的内存释放不了，当占用内存达到分配的堆空间内存值，服务直接停掉

**Comment by acuitong** [comment]
![image](https://user-images.githubusercontent.com/40566190/53147864-ccb87600-35e3-11e9-940e-81d1795770ef.png)
问题已解决，通过分析发现此问题，已经测试

**Comment by wurongjun** [comment]
> ![image](https://user-images.githubusercontent.com/40566190/53147864-ccb87600-35e3-11e9-940e-81d1795770ef.png)
> 问题已解决，通过分析发现此问题，已经测试

你用的什么版本的jdk，1.7之后实现了AutoCloseable接口，应该可以实现自动关闭

**Comment by acuitong** [comment]
jdk8的，但是进行关闭以后这边就没问题了

**Comment by acuitong** [comment]
![image](https://user-images.githubusercontent.com/40566190/53154532-f8445c00-35f5-11e9-8809-c9819a1c0cd9.png)
关闭的只是连接对象，并没有对PreparedStatement进行关闭

**Comment by wurongjun** [comment]
connection关闭后 应该其他都会被关闭吧

**Comment by acuitong** [comment]
![image](https://user-images.githubusercontent.com/40566190/53154961-f202af80-35f6-11e9-99af-934958a3e93a.png)
我们分析dump文件明显发现这个对象一直被引用

**Comment by wurongjun** [comment]
看代码  connection在应用关闭后才会关闭  这么说起来  PreparedStatement没能被即使关闭

**Comment by acuitong** [comment]
@wurongjun 你们大数据量操作没有遇到这种情况吗？内存不会往上彪吗？

**Comment by wurongjun** [comment]
> @wurongjun 你们大数据量操作没有遇到这种情况吗？内存不会往上彪吗？

我们目前还没正式上线，还在基于adapter做一些改造中

**Comment by acuitong** [comment]
@wurongjun 你们目前的测试server端有没有出现insert,和delete语句运行，内存占用随着数据量增大缓慢上升，且并更新完毕也不会下降的情况？？

**Comment by acuitong** [comment]
@wurongjun  你们目前的测试server端有没有出现update,和delete语句运行，内存占用随着数据量增大缓慢上升，且并更新完毕也不会下降的情况？？
