### ISSUE TITLE
请问支持kafka2.1.0版本吗？

### ISSUE THREAD

**Issue by czy006** [alibaba/canal#1522]
### environment
* canal version 1.1.3
* mysql version 5.6
### Issue Description
我在配置了canal.mq.dynamicTopic=.\\..*
时候无法生效，首先我已经打开了自动创建topic（kafka）按照官方说这个意思是根据表名发到各自topic上，然而我现在是配置后，仍然发送到canal.mq.topic 这个默认topic上
例子2：.\\..* 匹配所有表，每个表都会发送到各自表名的topic上

**Comment by finefuture** [comment]
canal.mq.dynamicTopic=.*\\..*，这样配就可以按表创建topic并将消息发送到相应topic上，
官网文档可能有点不正确

**Comment by agapple** [comment]
LS正解，需要双斜杆
