### ISSUE TITLE
请教下，如果有个GTID事务不想同步，在otter中如何跳过呢？

### ISSUE THREAD

**Issue by cnodin** [alibaba/canal#1527]
### environment

* canal version
1.1.2
* mysql version
5.7.23

### Issue Description
在mysql主从同步中，如果想跳过某个GTID事务，可以通过在主库上重做个空事务跳过。那在OTTER上如何操作可以跳过某个GTID事务的同步呢？

**Comment by agapple** [comment]
需要otter写一个过滤代码，识别一下不需要同步的数据忽略掉，没有直接基于GTID忽略的能力

**Comment by cnodin** [comment]
谢谢agapple，能否稍详细说明下，给个示例或者给份参考文档。感谢。@agapple
