### ISSUE TITLE
求教: 获取到完整的一个事务结束为止

### ISSUE THREAD

**Issue by LuVx21** [alibaba/canal#1528]
### environment

* canal version: canal.deployer-1.1.2
* mysql version: 5.6

### Issue Description
现在想使用定时任务获取binlog的结果, 使用`connector.getWithoutAck(batchSize)`的话, 有可能获取到一个事务的中途就达到`batchSize`了,剩下`TRANSACTIONEND` 的没有获取, 请问有没有什么方法能获取到完整的事务? 
或者说 每次以事务为单位获取binlog
再或者说 只想获取1个事务的binlog
谢谢!

**Comment by agapple** [comment]
目前暂时没有保障获取一个完整的事务，batchSize默认最后一个事务可能只包含一半的数据
