### ISSUE TITLE
第一次全量同步到es应该怎么做

### ISSUE THREAD

**Issue by jianyun** [alibaba/canal#1529]
第一次全量同步到es应该怎么做

**Comment by JunRzz** [comment]
curl http://127.0.0.1:8081/etl/es/mytest_person2.yml -X POST 

[ wiki](https://github.com/alibaba/canal/wiki/ClientAdapter)上面说了的。

**Comment by jianyun** [comment]
> curl http://127.0.0.1:8081/etl/es/mytest_person2.yml -X POST
> 
> [ wiki](https://github.com/alibaba/canal/wiki/ClientAdapter)上面说了的。

多谢

**Comment by yangmingqi218** [comment]
您好，这种方式是增量更新，还是先删除之前的数据再全量同步呢？

**Comment by withlin** [comment]
用mysql-dump啊。

**Comment by withlin** [comment]
或者dataX
