### ISSUE TITLE
canal无法关闭的问题

### ISSUE THREAD

**Issue by lulu2panpan** [alibaba/canal#153]
当开启了canal.auto.scan功能，并且实际执行过动态增减instance的操作后。
执行sh stop.sh，无法关闭canal服务器，一直处于卡死等待状态，只能通过kill结束进程

**Comment by agapple** [comment]
执行stop之后，执行一下jstack获取一下线程堆栈

**Comment by agapple** [comment]
基于当前最新版暂无发现stop失败的问题
