### ISSUE TITLE
client服务启动，堆空间占满，问题已解决

### ISSUE THREAD

**Issue by acuitong** [alibaba/canal#1530]
数据同步后，6G的堆空间被占满，然后fullGC开始，堆中的示例不能被垃圾回收，越来越多，直到内存溢出

**Comment by acuitong** [comment]
详见数据同步缓慢的解答!!!

**Comment by agapple** [comment]
可以尝试调低一下batchsize，如果还无法解决，可以关注client的heap dump，分析一下如何优化内存占用
