### ISSUE TITLE
投递到kafka 不会自动创建topic

### ISSUE THREAD

**Issue by Bruce2jiang** [alibaba/canal#1535]
我这么配置的 canal.mq.dynamicTopic=per_employee:pms\\.per_employee;operator_config:pms\\.operator_config

但kafka不会自动创建per_employee和operator_config

**Comment by rewerma** [comment]
指定的库表不需要带\的：
canal.mq.dynamicTopic=per_employee:pms.per_employee;operator_config:pms.operator_config
另外确保kafka自动创建topic配置已打开

**Comment by Bruce2jiang** [comment]
你好，但加了\\也不应该有问题呀，楼主您这样配置成功了吗 ？

**Comment by Bruce2jiang** [comment]
去掉\,还是创建不了topic
