### ISSUE TITLE
rdb adapter如何支持多个源表同步到同一目标表

### ISSUE THREAD

**Issue by masterfengj** [alibaba/canal#1537]
不同的schema的多个表(这些表的表名和表结构一致), 需要同步到同一个目标表,  典型的场景如通过schema进行数据分片后的业务数据归集, 从目前配置结构看,需要为每一个源表配置规则, 一方面是比较繁琐,另一方面是分片规则可能是动态的, rdb adapter是否有比较好的方式支持这样的场景?

**Comment by suyiming3333** [comment]
请问最后是如何解决了？
