### ISSUE TITLE
SyncUtil.java 判断字段日期类型解析报错

### ISSUE THREAD

**Issue by likerai** [alibaba/canal#1538]
### environment
l
* canal version  1.1.3
* mysql version 

### Issue Description

SyncUtil.java  
Datetime dt=new Datetime(v) 
判断字段日期类型解析报错
当解析日期是  1988-04-10，1989-04-16，1990-04-15，1991-04-14 等特殊日期时
就会出现下面的异常：org.joda.time.IllegalInstantException: Cannot parse "1986-05-04": Illegal instant due to time zone offset transition (Asia/Shanghai)

**Comment by agapple** [comment]
有复现的表结构和SQL语句？

**Comment by likerai** [comment]
一个正常的mysql 表，其中一个字段是生日,字段类型是 date，保存的数据格式是 yyyy-MM-dd ，
 但像这种特殊日期   1986-05-04，1988-04-10，1989-04-16，1990-04-15，1991-04-14，就是报错。
org.joda.time.IllegalInstantException: Cannot parse "1986-05-04": Illegal instant due to time zone offset transition (Asia/Shanghai)。

查了原因 是，org.joda.datatime 处理这些日期时夏令时报错。
可以加上当前时区解决：
DateTime dt = new DateTime(v,DateTimeZone.forID("+08:00"));





likerai@163.com
 
发件人： agapple
发送时间： 2019-02-25 14:57
收件人： alibaba/canal
抄送： LiKe; Author
主题： Re: [alibaba/canal] SyncUtil.java 判断字段日期类型解析报错 (#1538)
有复现的表结构和SQL语句？

**Comment by likerai** [comment]
修改时问题时，当前时区不要写死东八区成呀。
DateTime dt = new DateTime(v,DateTimeZone.forID("### +08:00"));
