### ISSUE TITLE
启动canal，带宽陡升。

### ISSUE THREAD

**Issue by xxj123go** [alibaba/canal#1539]
### environment

* canal version 1.1.3
* mysql version 5.7

### Issue Description
开启canal后，canal 到 数据库的带宽监控每2h就会出现一次持续20min+的带宽占用，这个和什么设置有关么

**Comment by agapple** [comment]
没太看懂问题，带宽占用是有流量的意思？

**Comment by xxj123go** [comment]
找个问题原因了，源库有个event在跑
