### ISSUE TITLE
unsupported version at this client.

### ISSUE THREAD

**Issue by Lee-Think** [alibaba/canal#1552]
### environment

* canal version    1.1.3-SNAPSHOT
* mysql version   5.7

### Issue Description
我clone了master版本的源码并做了一些修改（没有修改handshake相关的逻辑），然后在本地编译后运行了deployer，之后再ide上启动了一个客户端。但是在SimpleCanalConnector的doConnect()方法中，对握手包的p.getVersion()返回结果检测失败，抛出了com.alibaba.otter.canal.protocol.exception.CanalClientException: unsupported version at this client.

**Comment by agapple** [comment]
主要是protobuf版本需要对齐，3.6.1
