### ISSUE TITLE
修改表结构后，canal_adapter不会自动生效，需要重启adapter是什么问题

### ISSUE THREAD

**Issue by acuitong** [alibaba/canal#1553]
canal1.3版本出现这个情况，修改了表结构，必须重启adapter才会生效。是不是配置的问题，还是这个版本的机制就是这个样子的

**Comment by rewerma** [comment]
修改表结构？adapter配置修改的话能够动态加载

**Comment by rewerma** [comment]
adapter不对对ddl做处理，修改了表结构需手动修改映射配置

**Comment by jinguangyu** [comment]
> 修改表结构？adapter配置修改的话能够动态加载

发现添加hbase/xxx.yml后不会自动开始同步新的表，需要通过修改application.yml让adapter重加载一下才行，这样会丢数据吗
