### ISSUE TITLE
canal发送到ons失败

### ISSUE THREAD

**Issue by dragontree101** [alibaba/canal#1554]
### environment

* canal version 
1.1.2
* mysql version
5.6

### Issue Description
通过debug后发现， 配置都是正确的， 并且mysql的binlog也获取到了， 但是在最终发送的时候，出了错误
![image](https://user-images.githubusercontent.com/1763935/53621728-6f9b7080-3c32-11e9-9563-a2d14e7abb00.png)

对应的topic， 已经在ons上创建
![image](https://user-images.githubusercontent.com/1763935/53621747-82ae4080-3c32-11e9-9bc9-0b88d9f40560.png)

并且对应的canal.mq.servers 配置也是正确的。

但是总是发送失败。

**Comment by agapple** [comment]
使用一下最新版1.1.3
