### ISSUE TITLE
canal.instance.filter.regex不生效问题

### ISSUE THREAD

**Issue by xxj123go** [alibaba/canal#1561]
### environment

* canal version ： 最新
* mysql version 5.1 

### Issue Description
需求: 只解析 mysql.test1,mysql.test2 两个表的数据。
配置 canal.instance.filter.regex=mysql.test1,mysql.test2  没生效。用法是正确的吧，还是说 写成  canal.instance.filter.regex=mysql\\.test1,mysql\\.test2 或其他。

**Comment by DinoZhang** [comment]
`mysql.test1,mysql.test2 `这个是ok的

**Comment by DinoZhang** [comment]
客户端去掉     ` connector.subscribe(".*\\..*");`

**Comment by ansontao** [comment]
@DinoZhang 请问在哪里的客户端去掉啊？

**Comment by panwuji** [comment]
问题解决了吗?
