### ISSUE TITLE
读取后记录的是事务结束的开始positon,而不是end_log_pos

### ISSUE THREAD

**Issue by LuVx21** [alibaba/canal#1562]
发现的一个现象,不知道是不是bug. 姑且反映一下!
### environment

* canal version 5.6
* mysql version canal.deployer-1.1.2

### Issue Description

1. 循环读取binlog时, 某个事务的事务结束事件(假设为a)也读取到并处理掉了(后续循环是空循环,不再读取到新的binlog), 
2. 但meta.dat中记录的是这和事务结束的开始position,
3. 此时停止canal,再次启动后,运行client代码,会将a事件(事务结束事件)再读取一次

效果大致如下图:
meta.dat
```json
                "postion": {
                    "gtid": "",
                    "included": false,
                    "journalName": "mysql-bin.000019",
                    "position": 6170,
                    "serverId": 1021,
                    "timestamp": 1551686429000
                }
```
binlog:
```log
mysql-bin.000019	5834	Query	1021	5906	BEGIN
mysql-bin.000019	5906	Rows_query	1021	5999	# UPDATE `boot`.`user_xxxxx` SET `password` = 'barfoo' WHERE `id` = 2
mysql-bin.000019	5999	Table_map	1021	6063	table_id: 76 (boot.xxxxx)
mysql-bin.000019	6063	Update_rows	1021	6170	table_id: 76 flags: STMT_END_F
mysql-bin.000019	6170	Xid	1021	6201	COMMIT /* xid=356 */
```
重启canal后再次运行client:
![image](https://user-images.githubusercontent.com/10940827/53719148-3b28ee00-3e98-11e9-88b2-fc9e5c212a10.png)

### Expected behaviour
按照正常的想法,meta.dat中记录的应该是6201吧

**Comment by agapple** [comment]
位点记录的的确是最后一个事件的开始position，设计上的问题
