### ISSUE TITLE
请问为什么我用官方的教程启动好canal，用netstat -lntp | grep命令监听不到11111端口

### ISSUE THREAD

**Issue by itlihuaxin** [alibaba/canal#1563]
### environment

* canal 1.1.2
* mysql 5.7.24

### Issue Description
请问为什么我用官方的教程启动好canal，用netstat -lntp | grep命令监听不到11111端口
后台日志都启动成功了## start the canal server[192.168.99.102:11111]
netstat -lntp | grep只能看到11112端口

**Comment by bestchenwu** [comment]
我也是这样的。 有解答吗

**Comment by agapple** [comment]
确认canal.serverMode是否为tcp模式，MQ模式没有11111端口
