### ISSUE TITLE
canal server修改删除FGC问题

### ISSUE THREAD

**Issue by acuitong** [alibaba/canal#1568]
![image](https://user-images.githubusercontent.com/40566190/53852474-1ef29180-3ffd-11e9-8a53-b9ae875cad38.png)
![image](https://user-images.githubusercontent.com/40566190/53852659-c374d380-3ffd-11e9-9d3a-7a4dea216a22.png)

server端修改删除，FGC次数多，常驻内存居高不下，ringbuffer已调1024，，iparallelBufferSize也调到了最低，nstance实例只有一个，请问是不是还是配置的问题啊

**Comment by agapple** [comment]
dump一份内存可以精确分析一下，ringbuffer可以再调低

**Comment by acuitong** [comment]
@agapple
![image](https://user-images.githubusercontent.com/40566190/53854140-346aba00-4003-11e9-8b5a-47653ce8e4e1.png)
依旧是event的占用，这个常驻内存每次大批量的修改或者删除操作，就会增加，目前的设置增加幅度不是很高，但是FGC频繁影响同步的性能啊！而且总会有占满堆空间的时候。 
ringbuffer值1024已经是最低了，测试低于1024不会进行同步操作，

**Comment by acuitong** [comment]
@agapple
![image](https://user-images.githubusercontent.com/40566190/53854550-d8a13080-4004-11e9-8bc7-7c76c57896fa.png) 
现在的event对象实例2036个，预计随着批量修改的次数增加，这个实例还会继续增加

**Comment by agapple** [comment]
单个Event 200kb，2036个的内存占用基本就明确了。要么调大内存，要么减少ringbuffer size，其他没办法. 

ps.  ringbuffer没有最小1024的限制，只要是2的指数倍 并且 大于 canal.instance.transaction.size的设置
