### ISSUE TITLE
枚举类型的字段值怎么以字符串形式读取

### ISSUE THREAD

**Issue by idreamshen** [alibaba/canal#157]
当 mysql 字段类型为 enum 时，`column.getValue()` 返回的是 int 值，我想问下能否方便地获取和 mysql 中一样的 enum 字符串值呢？

**Comment by agapple** [comment]
binlog协议里数据包就是int类型，可以拿到数据库表结构定义，将int转为对应的enum值

**Comment by idreamshen** [comment]
@agapple canal 有提供获取数据库表结构定义的方法吗？我查了下 wiki 没有找到。

**Comment by agapple** [comment]
有个mysql type

**Comment by jarlun** [comment]
比如说mysql中：enum('0','1','2','3')

**Comment by yl-yue** [comment]
这是binlog不支持枚举类型以value进行解析而非下标，是这样么？
