### ISSUE TITLE
1.1.2 canal.mq.partitionsNum=3 配置失效

### ISSUE THREAD

**Issue by ziFieYu** [alibaba/canal#1572]
### environment

* canal version 1.1.2
* mysql version

### Issue Description
1.1.2 canal.mq.partitionsNum=3 配置失效

我在instance.properties配置文件中配置了如下配置：
canal.mq.topic=testmusic4
#canal.mq.partition=
# hash partition config
canal.mq.partitionsNum=3
canal.mq.partitionHash=test.testmusic4:name

启动canal后，kafka中的topic为testmusic4只有一个partition。

**Comment by agapple** [comment]
多看wiki，把canal.mq.partitions给注释掉

**Comment by agapple** [comment]
尝试用1.1.3最新版
