### ISSUE TITLE
canal-1.1.3版本  日志出现这个问题 ，没办法自动创建topic是什么原因呢？

### ISSUE THREAD

**Issue by CodeLulu318** [alibaba/canal#1577]
##-----------canal日志--------
[kafka-producer-network-thread | producer-1] WARN  org.apache.kafka.clients.NetworkClient - [Producer clientId=producer-1] Bootstrap broker 172.16.55.23:9092 (id: -1 rack: null) disconnected

##--------------------canal.properties-----------------
canal.id = 1
canal.ip =
canal.port = 11111
canal.metrics.pull.port = 11112
canal.zkServers =

canal.zookeeper.flush.period = 1000
canal.withoutNetty = false

canal.serverMode = kafka
canal.file.data.dir = ${canal.conf.dir}
canal.file.flush.period = 1000
canal.instance.memory.buffer.size = 16384
canal.instance.memory.buffer.memunit = 1024 
canal.instance.memory.batch.mode = MEMSIZE
canal.instance.memory.rawEntry = true

canal.instance.detecting.enable = false

canal.instance.detecting.sql = select 1
canal.instance.detecting.interval.time = 3
canal.instance.detecting.retry.threshold = 3
canal.instance.detecting.heartbeatHaEnable = false
 
canal.instance.transaction.size =  1024
canal.instance.fallbackIntervalInSeconds = 60

canal.instance.network.receiveBufferSize = 16384
canal.instance.network.sendBufferSize = 16384
canal.instance.network.soTimeout = 30

canal.instance.filter.druid.ddl = true
canal.instance.filter.query.dcl = false
canal.instance.filter.query.dml = false
canal.instance.filter.query.ddl = false
canal.instance.filter.table.error = false
canal.instance.filter.rows = false
canal.instance.filter.transaction.entry = false

canal.instance.binlog.format = ROW,STATEMENT,MIXED 
canal.instance.binlog.image = FULL,MINIMAL,NOBLOB

canal.instance.get.ddl.isolation = false

canal.instance.parser.parallel = true
 canal.instance.parser.parallelBufferSize = 256

canal.instance.tsdb.enable = true
canal.instance.tsdb.dir = ${canal.file.data.dir:../conf}/${canal.instance.destination:}
canal.instance.tsdb.url = jdbc:h2:${canal.instance.tsdb.dir}/h2;CACHE_SIZE=1000;MODE=MYSQL;
canal.instance.tsdb.dbUsername = canal
canal.instance.tsdb.dbPassword = canal
canal.instance.tsdb.snapshot.interval = 24
canal.instance.tsdb.snapshot.expire = 360

canal.aliyun.accesskey =
canal.aliyun.secretkey =

canal.destinations = dis,inte
canal.conf.dir = ../conf
canal.auto.scan = true
canal.auto.scan.interval = 5

canal.instance.tsdb.spring.xml = classpath:spring/tsdb/h2-tsdb.xml

canal.instance.global.mode = spring
canal.instance.global.lazy = false
canal.instance.global.spring.xml = classpath:spring/file-instance.xml

canal.mq.servers = 172.16.55.23:9092,172.16.55.24:9092,172.16.55.39:9092
canal.mq.retries = 0
canal.mq.batchSize = 16384
canal.mq.maxRequestSize = 1048576
canal.mq.lingerMs = 1
canal.mq.bufferMemory = 33554432
canal.mq.canalBatchSize = 50
canal.mq.canalGetTimeout = 100
canal.mq.flatMessage = true
canal.mq.compressionType = none
canal.mq.acks = all
canal.mq.transaction = true

##-------------------instance.properties-------------------------
canal.instance.mysql.slaveId=80003

canal.instance.gtidon=false

canal.instance.master.address=172.16.55.38:3306
canal.instance.master.journal.name=
canal.instance.master.position=
canal.instance.master.timestamp=
canal.instance.master.gtid=

canal.instance.rds.accesskey=
canal.instance.rds.secretkey=
canal.instance.rds.instanceId=

canal.instance.tsdb.enable=true
canal.instance.tsdb.dir=${canal.file.data.dir:../conf}/${canal.instance.destination:}
canal.instance.tsdb.url=jdbc:h2:${canal.instance.tsdb.dir}/h2;CACHE_SIZE=1000;MODE=MYSQL;
canal.instance.tsdb.dbUsername=canal
canal.instance.tsdb.dbPassword=canal

canal.instance.dbUsername=canal
canal.instance.dbPassword=Fumin1234
canal.instance.defaultDatabaseName=dis
canal.instance.connectionCharset=UTF-8
canal.instance.enableDruid=false

canal.instance.filter.regex=.*\\..*
canal.instance.filter.black.regex=

canal.mq.dynamicTopic=.\\..* 
canal.mq.partition=0
canal.mq.partitionsNum=1

求大佬解答

**Comment by xuej2s** [comment]
是不是你的kafka集群需要进行权限认证？

**Comment by CodeLulu318** [comment]
> 是不是你的kafka集群需要进行权限认证？

是的  需要kerberos权限认证， 已经解决了，修改了 下canal的源码
