### ISSUE TITLE
FlatMessage中类属性是何时赋值的呢？

### ISSUE THREAD

**Issue by shubiao-yao** [alibaba/canal#1578]
包地址：
package com.alibaba.otter.canal.protocol;

类的名字：
public class FlatMessage implements Serializable {}

像此类中的setData方法，该方法是什么时候调用的啊，请大神指点迷津
public void setData(List<Map<String, String>> data) {
        this.data = data;
}

**Comment by DinoZhang** [comment]
`com.alibaba.otter.canal.common.MQMessageUtils`   
```
    /**
     * 将Message转换为FlatMessage
     *
     * @param message 原生message
     * @return FlatMessage列表
     */
    public static List<FlatMessage> messageConverter(Message message)
```

**Comment by shubiao-yao** [comment]
在canal1.1.2中没有您说的这个包 ：com.alibaba.otter.canal.common.MQMessageUtils

我却在：package com.alibaba.otter.canal.protocol 这个包中找到了messageConverter这个方法，也在这个方法中找到setData方法，但是我还是不知道什么时候调用了messageConverter这个方法，我使用的ItellIj IDEA 这个强大的编辑器也没有追踪到。 @DinoZhang

**Comment by DinoZhang** [comment]
https://github.com/alibaba/canal/blob/5e2eabb3c261ea8bb145a69a1394b235fa4fab7d/server/src/main/java/com/alibaba/otter/canal/common/MQMessageUtils.java

投递到mq时会调用的：
![image](https://user-images.githubusercontent.com/8003615/54744266-7863de80-4c01-11e9-815b-185e2658c5f0.png)

**Comment by shubiao-yao** [comment]
![image](https://user-images.githubusercontent.com/32409300/54746148-659fd880-4c06-11e9-8610-1a22d089736c.png)
嗯，这个地方是canal server中调用的吧，我是在canal client中使用FlatMessage类中的getData方法，我不明白的是canal serve中设置的data属性，怎么可以在canal client 中使用呢？这不可能啊
@DinoZhang

**Comment by shubiao-yao** [comment]
如图所示，这是canal官方给的kafka 消费者demo
![image](https://user-images.githubusercontent.com/32409300/54746662-b6640100-4c07-11e9-800d-c7f8b9e15218.png)

我在获取到message后，直接调用了getData方法就可以获取到消息
![image](https://user-images.githubusercontent.com/32409300/54746671-be23a580-4c07-11e9-9e40-4bdadb5b2ccf.png)
@DinoZhang

**Comment by DinoZhang** [comment]
没问题的，`canal-server` 写入`kafka`会将`Message`转换为`FlatMessage`，`FlatMessage`包含了`data`信息，你的`client`接可以直接使用了

**Comment by shubiao-yao** [comment]
@DinoZhang 看来我需要把canal server的代码先搞明白 = =#
