### ISSUE TITLE
为什么在CanalLauncher 中运行报错

### ISSUE THREAD

**Issue by shuhuiguo** [alibaba/canal#158]
java.io.IOException: connect /127.0.0.1:3306 failure:java.nio.channels.ClosedChannelException

而打包后运行startup.sh却不会呢？很奇怪

**Comment by agapple** [comment]
debug代码，和你自己环境有太多相关性

**Comment by he037** [comment]
遇到同样问题，不知道@shuhuiguo   你是怎么解决的

**Comment by shuhuiguo** [comment]
没有，应该是线程模型有问题
