### ISSUE TITLE
canal example无法读取数据

### ISSUE THREAD

**Issue by wkhapy** [alibaba/canal#1584]
### environment

* canal version
1.1.3
* mysql version
5.7.25-0ubuntu0.16.04.2
### Issue Description
搭建了环境但是canal客户端无法读取数据

**Comment by wkhapy** [comment]
canal实例配置
canal.instance.mysql.slaveId=1234
canal.instance.master.address=localhost:3306

canal.instance.dbUsername=dbuser
canal.instance.dbPassword=dbuser
canal.instance.connectionCharset = UTF-8
canal.instance.defaultDatabaseName = test


日志
2019-03-11 02:39:48.667 [destination = example , address = localhost/127.0.0.1:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - ---> find start position successfully, EntryPosition[included=false,journalName=mysql-bin.000004,position=4318,serverId=<null>,gtid=<null>,timestamp=<null>] cost : 38ms , the next step is binlog dump
2019-03-11 02:40:02.810 [New I/O server worker #1-1] INFO  c.a.otter.canal.instance.core.AbstractCanalInstance - subscribe filter change to .*\..*

**Comment by wkhapy** [comment]
但是我插入test库的表数据在用客户端消费时没有显示一直empty count : 117

**Comment by shubiao-yao** [comment]
可以看下我之前提的issue, 我之前的配置没问题，因为我用的是虚拟机，因为linux给的是1核CPU导致的。
https://github.com/alibaba/canal/issues/1181

**Comment by wkhapy** [comment]
确实虚拟机核数问题

**Comment by wkhapy** [comment]
连kafka无数据
canal.properties
##################################################
#########                    MQ                      #############
##################################################
canal.mq.servers = localhost:9092
canal.mq.retries = 0
canal.mq.batchSize = 16384
canal.mq.maxRequestSize = 1048576
canal.mq.lingerMs = 1
canal.mq.bufferMemory = 33554432
canal.mq.canalBatchSize = 50
canal.mq.canalGetTimeout = 100
canal.mq.flatMessage = true
canal.mq.compressionType = none
canal.mq.acks = all
canal.mq.transaction = false


nazaio/instance.properties

canal.instance.dbUsername=root
canal.instance.dbPassword=root
canal.instance.connectionCharset = UTF-8
canal.instance.defaultDatabaseName =test
# enable druid Decrypt database password
canal.instance.enableDruid=false
#canal.instance.pwdPublicKey=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALK4BUxdDltRRE5/zXpVEVPUgunvscYFtEip3pmLlhrWpacX7y7GCMo2/JM6LeHmiiNdH1FWgGCpUfircSwlWKUCAwEAAQ==

# table regex
canal.instance.filter.regex=nazaio.contact,nazaio.contact_identity,nazaio.event,nazaio.event_metadata,nazaio.contact_attr,nazaio.contact_utm,nazaio.event_utm,nazaio.contact_group_member
# table black regex
canal.instance.filter.black.regex=

# mq config
canal.mq.topic=nazaio
canal.mq.partition=0
# hash partition config
#canal.mq.partitionsNum=3
#canal.mq.partitionHash=mytest.person:id,mytest.role:id
#################################################

只有example有
换了一个topic就没数据了

**Comment by shubiao-yao** [comment]
检查kafka中是否存在nazaio这个topic

**Comment by wkhapy** [comment]
> 检查kafka中是否存在nazaio这个topic

谢谢你的热心，我发现了是因为没有数据写表所以topic没建，感谢你的帮助
