### ISSUE TITLE
词法分析不支持mysql 虚列

### ISSUE THREAD

**Issue by weitong1105** [alibaba/canal#1587]
### environment
* canal version
1.1.1
* mysql version
5.7.19

### Issue Description
com.alibaba.fastsql.sql.parser.ParserException: syntax error, error in :'int(11) GENERATED ALWAYS AS ((`cur', expect ), actual null, pos 1190, line 24, column 38, token IDENTIFIER GENERATED

fastsql-2.0.0_preview_644 词法分析看上去不支持 mysql虚列 ..

**Comment by ldfengl4j** [comment]
同问，遇到有虚列的表数据就无法同步？还是有办法忽略虚列。

**Comment by agapple** [comment]
目前虚拟列的解析的确是不支持

**Comment by agapple** [comment]
1.1.4 当前主干已支持虚拟列的解析
