### ISSUE TITLE
ack 能实现对某一个 Message 中的某个 Entry 提交吗

### ISSUE THREAD

**Issue by idreamshen** [alibaba/canal#159]
`com.alibaba.otter.canal.client.CanalConnector.get` 方法中有 batchSize 参数。当我设置成 100 时，假如我在处理某些 `entry` 出错，然后调用 `connector.rollback(batchId)`，这就会导致此次的所有 `entry` 回滚吗？那是否会导致接下来出现重复处理相同 `entry` 的问题 ？

我想问下 canal 有提供 "ack 提交某个 Message Entry" 的方案吗？

**Comment by idreamshen** [comment]
我现在的思路是在记录 "库名+表名+主键" 做唯一判断，防止 rollback 后重复处理

**Comment by agapple** [comment]
没有单条ack的功能，get的时候设置batchSize小一点.  
ps.  主要是性能考虑

**Comment by timqq** [comment]
那怎么处理重复呢？

**Comment by agapple** [comment]
需要业务上设计为可幂等执行，软件层面没法避免不重复
