### ISSUE TITLE
aws rds mysql 当binlog被定时清除时，canal会报找不到binlog，并且不会读取新的binlog，需要重启后才能读取到新的binlog

### ISSUE THREAD

**Issue by liu391447823** [alibaba/canal#1594]
### environment

* canal version
1.1.2
* mysql version
5.7.1
### Issue Description
aws rds mysql 会定时清除掉binlog，这个时候canal会报找不到binlog的错误，并且不会读取新的binlog，
需要重启canal服务端后才能读取到新的binlog

**Comment by agapple** [comment]
1.1.3+ 支持RDS在binlog删除时基于时间戳自动重新下载oss binlog文件
