### ISSUE TITLE
canal中有唯一的一个标识可以确定到每一个binlog中的操作事件吗

### ISSUE THREAD

**Issue by xuej2s** [alibaba/canal#1596]
举例：数据库执行了三个事件1insert、 2update、 3delete
这三个事件各自有没有一个递增的参数可以唯一确定他们这个操作的顺序

我本来以为可以通过header中的getLogfileOffset方法获取position参数来唯一确定的，但是测试发现多个操作传回来的position可能是重复的，

所以想问有没有一个递增的参数是可以确定每一个事件的顺序的？

求教，感谢！

**Comment by agapple** [comment]
filename+offest就是唯一的，批量insert可能出现在一个binlog事件里

**Comment by peachestao** [comment]
@agapple 我是用canal同步mysql 数据到rabbitmq，消费者从rabbitmq中拿到的数据格式如下：

`
{
	"data": [{}],
	"database": "resource",
	"es": 1732287602000,
	"gtid": "",
	"id": 2849284,
	"table": "tiku_task_member",
	"ts": 1732287602415,
	"type": "UPDATE"
}
`
我想找一个表示mysql binlog位置的字段来保证消费端的消费顺序，但我发现es和ts都是毫秒级的时间戳，如果同一毫秒内发生了2个binglog事件就无法确定顺序了，想问下id字段是什么意思？我发现ts相同的情况下id也是一样的
