### ISSUE TITLE
取不到ROWDATA数据

### ISSUE THREAD

**Issue by changsong** [alibaba/canal#160]
从应用日志上看取到了EntryType为 TRANSACTIONBEGIN和TRANSACTIONEND 数据
没有取得ROWDATA。请问一下这是什么原因
Canal版本 1.0.21
mysq 版本   PXC架构 5.6.20

**Comment by changsong** [comment]
自己回答一下，是数据库端口配置的问题
数据库是pxc，起了两个实例3306,3307.
奇怪的是连接了错误的端口，没有任何报错

**Comment by haiger** [comment]
你确定下你的mysql配置中binlog-format=ROW吗？

发自我的 iPhone

**Comment by changsong** [comment]
canal.instance.binlog.format = ROW,STATEMENT,MIXED 
默认的，没有改过。
原因已经查出来了，见上面的回答，主要奇怪的是canal没有任何报错.各个日志都正常

**Comment by agapple** [comment]
canal会默认解析所有的binlog，你这里开启了所有日志格式，当然不会报错了

**Comment by oyunlong** [comment]
我用的canal 1.0.25-SNAPSHOT对应MySQL 5.6、5.7也会出现这个问题。
端口没改，配置也是采用默认的支持所有格式
canal.instance.binlog.format = ROW,STATEMENT,MIXED
默认解析所有binlog也不会导致rowdata解析不了吧？

**Comment by oyunlong** [comment]
改成canal.instance.binlog.format = ROW，真就可以了。

**Comment by oyunlong** [comment]
经过验证，filter过滤掉的库、表信息，rowdata信息收不到了，但是对应的Transaction Begin、Transaction End还是有的。

**Comment by shijiebei2009** [comment]
同样的问题
connector.subscribe("actionlog\\d{8}");我想订阅所有actionlog打头接数字的表，结果没有ROWDATA了，是正则错了，还是哪里错了？？？

**Comment by agapple** [comment]
你现在本地用canal的PattenUtils跑一下testcase

**Comment by qingo00o** [comment]
> 经过验证，filter过滤掉的库、表信息，rowdata信息收不到了，但是对应的Transaction Begin、Transaction End还是有的。

我也遇到这个问题了，在客户端subscribe中不配置的话就没有问题，配置了之后进行单条数据更新就收不到ROWDATA，只有TRANSACTIONBEGIN和TRANSACTIONEND。我的版本是1.1.3，配置的是指定的几个表，格式为：database.table1,database.table2,database.table3.现在不知道是啥原因

**Comment by wdqzdd** [comment]
我也遇到了。不知道都是什么玩意

**Comment by PBlueSky** [comment]
我的也是，我的mysql版本是mysql-8.0.20，ROWDATA没有，只有TRANSACTIONBEGIN和TRANSACTIONEND 数据，而且mysql的binlog模式是ROW,不知道咋搞，请问有什么解决方法吗？

**Comment by gxstax** [comment]
数据库8.0，客户端在subscribe(".*\\..*");加上过滤条件才能有rowdata数据，不加的话没有，但是我是在管理端设置了过滤器的，官网上也说，如果客户端不配置，是取管理端配置的信息的
