### ISSUE TITLE
[QUESTION] Where I can find the CI service?

### ISSUE THREAD

**Issue by gustavosizilio** [alibaba/canal#1612]
Is this project using continuous integration services (e.g., Travis-CI or Jenkings)? Or has it used at any point of its lifetime?

**Comment by agapple** [comment]
https://travis-ci.com/alibaba/canal

**Comment by gustavosizilio** [comment]
Thank you very much. I was looking in the https://travis-ci.org which is for public repos according to the API. Sorry for my mistake.
