### ISSUE TITLE
canal.serverMode 同时支持tcp和kafka么？

### ISSUE THREAD

**Issue by alynnchen** [alibaba/canal#1623]
### environment

* canal version v1.1.3-alpha-2
* mysql version v5.7.20
* kafka version v1.0

### Issue Description
我启动了一个canal server , 用了adapter 同步Hbase，canal.serverMode配置的tcp，一切正常。

现在我需要另外传给kafka一份，能用同一个canal server么？还是必须重新部署个server？

我是这么做的，在canal.properties 
canal.instance.mq_test.serverMode = kafka
canal.instance.mq_test.mq.servers = test-01:9092,test-02:9092
mq_test 是我建的一个用于kafka的instance.properties

求解惑，谢谢

**Comment by agapple** [comment]
需要重新部署
