### ISSUE TITLE
动态topic  名称

### ISSUE THREAD

**Issue by chenchuanyuan** [alibaba/canal#1625]
### environment

* canal version  v1.1.3-alpha-3
* mysql version 5.6

### Issue Description

![image](https://user-images.githubusercontent.com/40780933/54863733-3ebce000-4d87-11e9-95af-6bb3663fdad4.png)
使用canal.deployer-1.1.3-SNAPSHOT.tar.gz直接运行，在用canal.mq.dynamicTopic=.*\\..*动态topic方式发送mq时报错。源码是有做转换处理的，用源码构建运行，没这个错误。
### Expected behaviour
库名_表名
### Actual behaviour
库名.表名

**Comment by agapple** [comment]
发送目标是kafka还是rocketmq ?

**Comment by penghaige** [comment]
是发送到kafka

> 发送目标是kafka还是rocketmq ?

**Comment by rewerma** [comment]
可能是alpha版的bug，用最新代码吧

**Comment by agapple** [comment]
之前MQ的动态匹配规则略微有一些问题，现在修复过，可以使用最新版测试一下
