### ISSUE TITLE
表字段位置改变，数据同步错乱

### ISSUE THREAD

**Issue by alynnchen** [alibaba/canal#1626]
### environment

* canal version  v1.1.3
* mysql version v5.7.20
* kafka version v1.0

### Issue Description

> 在同步mysql数据时，如果移动表字段位置，canal只捕获alter操作但没有处理，导致数据同步错乱。在canal  -->  kafka、adapter的hbase  均重现该问题

### Steps to reproduce

比如重现步骤：
```
1. 创建了一个hello库quniya4表
2. 表里有三个字段（name,value,id）
3. 我先建的name，value，最后建的id主键自增。现在我把id的位置移动到name、value的上面，
   也就是说id的字段位置变成了 frist，现在的表字段位置为（id,name,value）
4. 我插入数据（1,a,aaa）=> (aaa,1,a) ; name变成了1，value变成了a，
   而id还是没有移动位置前的第三位，所以kafka消费这条数据时id=aaa，hbase亦是如此
```

### Expected behaviour

kafka预期显示：
```
{"data":[{"id":"1","name":"a","value":"aaa"}]      ...}
```

### Actual behaviour

kafka结果显示：
```
{"data":[{"name":"1","value":"a","id":"aaa"}],"database":"hello","es":1553330817000,"id":20,"isDdl":false,"mysqlType":{"name":"varchar(255)","value":"varchar(255)","id":"int"},"old":null,"pkNames":["id"],"sql":"","sqlType":{"name":4,"value":12,"id":12},"table":"quniya4","ts":1553330817903,"type":"INSERT"}
```

hbase结果显示：
```
hbase(main):009:0> scan 'hello.quniya4'
ROW                 COLUMN+CELL                                          
 ccc|3              column=cf:id, timestamp=1553331439400, value=ccc     
 ccc|3              column=cf:name, timestamp=1553331439400, value=3     
 ccc|3              column=cf:value, timestamp=1553331439400, value=c
```

**Comment by agapple** [comment]
canal是否有开启tablemeta tsdb ?  可以提供一下对应的DDL语句

**Comment by alynnchen** [comment]
```
{"data":null,"database":"hello","es":1553330627000,"id":17,"isDdl":true,"mysqlType":null,"old":null,"pkNames":null,"sql":"/* ApplicationName=DataGrip 2018.3.1 */ create table quniya4\n(\n\tname varchar(255) null,\n\tvalue varchar(255) null,\n\tid int not null,\n\tconstraint quniya4_pk\n\t\tprimary key (id)\n)","sqlType":null,"table":"quniya4","ts":1553330627130,"type":"CREATE"}
```

```
{"data":null,"database":"hello","es":1553330711000,"id":18,"isDdl":true,"mysqlType":null,"old":null,"pkNames":null,"sql":"/* ApplicationName=DataGrip 2018.3.1 */ alter table quniya4 modify id int not null first","sqlType":null,"table":"quniya4","ts":1553330711411,"type":"ALTER"}
```

```
{"data":null,"database":"hello","es":1553330789000,"id":19,"isDdl":true,"mysqlType":null,"old":null,"pkNames":null,"sql":"/* ApplicationName=DataGrip 2018.3.1 */ alter table quniya4 modify id int auto_increment","sqlType":null,"table":"quniya4","ts":1553330789377,"type":"ALTER"}
```

配置为true了啊
```
# table meta tsdb info
canal.instance.tsdb.enable = true
canal.instance.tsdb.dir = ${canal.file.data.dir:../conf}/${canal.instance.destination:}
canal.instance.tsdb.url = jdbc:h2:${canal.instance.tsdb.dir}/h2;CACHE_SIZE=1000;MODE=MYSQL;
canal.instance.tsdb.dbUsername = canal
canal.instance.tsdb.dbPassword = canal
# dump snapshot interval, default 24 hour
canal.instance.tsdb.snapshot.interval = 24
# purge snapshot expire , default 360 hour(15 days)
canal.instance.tsdb.snapshot.expire = 360
```

**Comment by rewerma** [comment]
adapter 的es、hbase和rdb(mirrorDB配置除外)，不会对ddl语句做处理，需要手动修改配置映射

**Comment by alynnchen** [comment]
@rewerma  请问 在哪里配置，在canal server的canal.properties  or instance.properties 还是adapter的application.yml  又怎么写呢 ?  
> hbase是用的adapter，kafka没有用adapter

**Comment by rewerma** [comment]
确认tsdb是否开启

**Comment by agapple** [comment]
确认是tablemeta tsdb针对DDL支持问题，针对alter table quniya4 modify id int not null first

**Comment by alynnchen** [comment]
@agapple  正式1.3会更新这个问题吗？

**Comment by agapple** [comment]
1.1.3最新版会安排修复

**Comment by hqch0708** [comment]
你好，我目前使用的是canal v1.1.3。但是这个问题还是没有修复。我这边不是主键顺序，是其他的同步字段顺序有变动，值是错乱的。开启了tablemeta tsdb，是直接通过deployer发送kafka

**Comment by alynnchen** [comment]
建议v1.14，已验证无该问题

**Comment by tiantiantian888** [comment]
> 建议v1.14，已验证无该问题

您好，请问现在adapter是会对DDL进行操作了吗？

**Comment by yuanweikang2020** [comment]
请问是哪一个commit解决了这个bug呢？

**Comment by gunagyu001** [comment]
请问我用的是1.1.4，这个问题仍然没有得到解决，我有6个destinations，其中有一个发现同步过来的数据字段值仍然是错乱的

**Comment by yuanweikang2020** [comment]
可以参考我提交的一个pr，自己测试没有问题

**Comment by gunagyu001** [comment]
好的，我会去看下你的提交，刚刚我直接在配置文件里设置canal.instance.tsdb.enable=false，这样没有错乱了

**Comment by xiechenghuan** [comment]
canal.instance.tsdb.enable  是否开启时序表结构的能力   refer:https://github.com/alibaba/canal/wiki/TableMetaTSDB
解决这个问题：可以把instance下的mate.bat、h2.mv.db移除；
canal.instance.tsdb.enable  还是建议true的
--

**Comment by yuanweikang2020** [comment]
> ## canal.instance.tsdb.enable 是否开启时序表结构的能力 refer:https://github.com/alibaba/canal/wiki/TableMetaTSDB
> 解决这个问题：可以把instance下的mate.bat、h2.mv.db移除；
> canal.instance.tsdb.enable 还是建议true的

每次都在出问题了`把instance下的mate.bat、h2.mv.db移除`肯定不是一个长期解决方案

**Comment by xiechenghuan** [comment]
> > ## canal.instance.tsdb.enable 是否开启时序表结构的能力 refer:https://github.com/alibaba/canal/wiki/TableMetaTSDB
> > 解决这个问题：可以把instance下的mate.bat、h2.mv.db移除；
> > canal.instance.tsdb.enable 还是建议true的
> 
> 每次都在出问题了`把instance下的mate.bat、h2.mv.db移除`肯定不是一个长期解决方案

和mate.bat没有关系，是h2.mv.db有影响，其实也可以自己维护表结构

**Comment by xiechenghuan** [comment]
> > > ## canal.instance.tsdb.enable 是否开启时序表结构的能力 refer:https://github.com/alibaba/canal/wiki/TableMetaTSDB
> > > 解决这个问题：可以把instance下的mate.bat、h2.mv.db移除；
> > > canal.instance.tsdb.enable 还是建议true的
> > 
> > 
> > 每次都在出问题了`把instance下的mate.bat、h2.mv.db移除`肯定不是一个长期解决方案
> 
> 和mate.bat没有关系，是h2.mv.db有影响，其实也可以自己维护表结构

每次有出问题是什么意思，你们有频繁变更表结构的场景？

**Comment by yuanweikang2020** [comment]
> > > > ## canal.instance.tsdb.enable 是否开启时序表结构的能力 refer:https://github.com/alibaba/canal/wiki/TableMetaTSDB
> > > > 解决这个问题：可以把instance下的mate.bat、h2.mv.db移除；
> > > > canal.instance.tsdb.enable 还是建议true的
> > > 
> > > 
> > > 每次都在出问题了`把instance下的mate.bat、h2.mv.db移除`肯定不是一个长期解决方案
> > 
> > 
> > 和mate.bat没有关系，是h2.mv.db有影响，其实也可以自己维护表结构
> 
> 每次有出问题是什么意思，你们有频繁变更表结构的场景？

1. 表结构变更对于每一张表都是一个很常见的现象，无论是否变更频繁；
2. 无论是做什么操作可以进行恢复，这都不是一个长期解决方案，只能是一个紧急解决方案，比如，线上故障内存oom，我重启一下机器；

**Comment by lustm** [comment]
这个问题在1.1.5版本上依旧存在

**Comment by laurel-he** [comment]
1.1.6问题依旧存在，我们线上表结构变动比较频繁，因此经常去删instance下的mate.bat、h2.mv.db，感觉很麻烦，而且有时候是客户提出的，感觉非常麻烦
