### ISSUE TITLE
wiki文档中给的url，4040问题

### ISSUE THREAD

**Issue by keji94** [alibaba/canal#1627]
页面地址：
https://github.com/alibaba/canal/wiki/Canal-Kafka-RocketMQ-QuickStart

3.7 MQ数据消费
canal.client下有对应的MQ数据消费的样例工程,包含数据编解码的功能

kafka模式: com.alibaba.otter.canal.client.running.kafka.CanalKafkaClientExample
rocketMQ模式: com.alibaba.otter.canal.client.running.rocketmq.CanalRocketMQClientExample

[com.alibaba.otter.canal.client.running.rocketmq.CanalRocketMQClientExample](com.alibaba.otter.canal.client.running.rocketmq.CanalRocketMQClientExample) 404

**Comment by agapple** [comment]
已调整
