### ISSUE TITLE
关于canal和mysql主备的问题

### ISSUE THREAD

**Issue by ZSH9053** [alibaba/canal#1628]
现在有种情况，比如主库一共要插入100W条，插入到50W的时候 ，canal挂了。然后主库插入到70W的时候，主库也挂了，之前我配置了canal的备库信息，把canal启动，canal自动连到了备库上，这时候开始抽取的时间点是50W的位置还是70W的位置？

**Comment by agapple** [comment]
canal的位点记录是以事务为边界，切换到备库是50w的位置。 
ps. 如果主库异常crash后导致备库binlog丢失，这个canal也同样拿不到丢失的数据

**Comment by ZSH9053** [comment]
如果我备库binlog日志没有丢失呢

**Comment by ZSH9053** [comment]
> canal的位点记录是以事务为边界，切换到备库是50w的位置。
> ps. 如果主库异常crash后导致备库binlog丢失，这个canal也同样拿不到丢失的数据

如果我备库binlog日志没有丢失呢

**Comment by agapple** [comment]
那就是切换到50w的位置，继续消费，不会丢失数据

**Comment by ZSH9053** [comment]
> 那就是切换到50w的位置，继续消费，不会丢失数据

如何获取canal宕的时候的位置啊？然后如何指定位置继续消费啊，麻烦能否说明，谢谢

**Comment by agapple** [comment]
多看一下wiki，切换到备库是按照位点的时间戳进行重新定位的

**Comment by ZSH9053** [comment]
> 多看一下wiki，切换到备库是按照位点的时间戳进行重新定位的

你好，我看了那个adminguide，我是不是可以认为，即使是canal宕了，主库无论做什么操作，只要备库binlog不丢失，canal启动之后都会定位到canal宕的那个时间点的**备库binlog**，继续消费，不会丢失数据

**Comment by agapple** [comment]
理解是对的

**Comment by KinYu668** [comment]
咨询一下，主备库的binlog名字未必是一致的。当主库出现异常宕机，canal会切换到备库。这个时候，消费备库的位点会不会失败？
