### ISSUE TITLE
canal1.1.2 批量同步数据到kafka速度很慢

### ISSUE THREAD

**Issue by Sky8080** [alibaba/canal#1630]
### environment

* canal version1 1.1.2
* mysql version 5.7

### Issue Description
我配置的canal直接同步数据到kafka里存储到kafka里的数据是json格式的，发现数据同步的很慢写入到kafka里的速度大概是7M/S，差不多是400条信心每秒。
看到官方文档上说canal 1.0.26经过优化之后的性能，从业务binlog入库到canal client拿到数据，基本可以达到10~20w的差不多也是10M/S，我现在用的是canal1.1.2的版本，我这种情况瓶颈是不是canal-client到kafka这一块呀

**Comment by DinoZhang** [comment]
可以看下 `prometheus`  的 `Blocking` 指标，确定是`server`还是`client`的问题

**Comment by cun123** [comment]
LZ，找到好的解决方式了吗？

**Comment by agapple** [comment]
写入MQ考虑binlog保序性，是一个串行、同步刷盘的写入行为，可以考虑做partition散列提升写入效率
