### ISSUE TITLE
es同步,删除步骤逻辑错误

### ISSUE THREAD

**Issue by violet250** [alibaba/canal#1631]
### environment

* canal 1.1.3
* mysql 5.7

### Issue Description
mainTableDelete 方法逻辑问题, 既然是主表删除操作, 然后该方法又是通过查询sql语句后进行es数据操作, mysql的主表数据都已经删除了, 怎么可能sql语句得到结果呢?

**Comment by rewerma** [comment]
如果主键是不带函数的单一字段，删除时不会通过sql反查数据。带函数或者复合主键暂不支持物理删除的同步
