### ISSUE TITLE
创建一个 Canal 交流群吧！

### ISSUE THREAD

**Issue by xmt1139057136** [alibaba/canal#1632]
创建一个 Canal 交流群吧！
最近遇到一个问题，QQ群不能加入了！
钉钉没有群！
![image](https://user-images.githubusercontent.com/23303979/54972057-b035a200-4fc4-11e9-918c-1d4d33629a78.png)
所以，我创建了一个微信群。希望大家相互交流学习吧！
![image](https://user-images.githubusercontent.com/23303979/54972074-c17eae80-4fc4-11e9-810a-73d4a1253f96.png)
如果人满了或者二维码过期了，不能扫描进入，加我微信号：xmtxtt，备注：canal。我拉大家！

**Comment by agapple** [comment]
建议issue交流，qq群交流还是开放的
