### ISSUE TITLE
通过canal同步数据，消费kafka数据时出现了别的数据库里的信息

### ISSUE THREAD

**Issue by Sky8080** [alibaba/canal#1633]
### environment

* canal version v1.1.2
* mysql version v5.7.22
* kafka version v1.1.0

### Issue Description
我在instance.properties里配置的数据库是canal_test，但是在kafka上手动消费canal_test对应的topic时总是不定时的出现另外一个数据库信息，这个数据库是Metabash这个开源工具的这个工具一直在运行着。下面是kafka里出现的错误的消息内容：
{"data":null,"database":"","es":1553581724000,"id":291,"isDdl":false,"mysqlType":null,"old":null,"sql":"UPDATE QRTZ_SCHEDULER_STATE SET LAST_CHECKIN_TIME = 1553581724317 WHERE SCHED_NAME = 'MetabaseScheduler' AND INSTANCE_NAME = 'e4bbb2ef0fcc1551666458397'","sqlType":null,"table":"QRTZ_SCHEDULER_STATE","ts":1553581724502,"type":"QUERY"}
{"data":[{"SCHED_NAME":"MetabaseScheduler","INSTANCE_NAME":"e4bbb2ef0fcc1551666458397","LAST_CHECKIN_TIME":"1553581724317","CHECKIN_INTERVAL":"7500"}],"database":"metabase","es":1553581724000,"id":291,"isDdl":false,"mysqlType":{"SCHED_NAME":"varchar(120)","INSTANCE_NAME":"varchar(200)","LAST_CHECKIN_TIME":"bigint(20)","CHECKIN_INTERVAL":"bigint(20)"},"old":[{"LAST_CHECKIN_TIME":"1553581716816"}],"sql":"","sqlType":{"SCHED_NAME":12,"INSTANCE_NAME":12,"LAST_CHECKIN_TIME":-5,"CHECKIN_INTERVAL":-5},"table":"QRTZ_SCHEDULER_STATE","ts":1553581724502,"type":"UPDATE"}

消费kafka里的数据时，上面消息里的id值是会增加的，但是我看了一下metabase数据库里的QRTZ_SCHEDULER_STATE表的内容并没有发生任何改变

### Expected behaviour
消费kafka对应的topic应该只会出现和该topic对应的数据库里的信息
### Actual behaviour
消费kafka topic里的数据出现了别的数据库里的信息

**Comment by agapple** [comment]
需要通过table filter做精确过滤，参考一下FAQ里的描述

**Comment by mathsyouth** [comment]
@agapple 我也发现了同样的问题，FAQ 里的描述搞不定

**Comment by brucefeng10** [comment]
> @agapple 我也发现了同样的问题，FAQ 里的描述搞不定

也是看了FAQ搞不定，过滤无用，然后发现issue里面关于这个问题太多了，希望官方认真看一下
