### ISSUE TITLE
canal往一个topic的多个分区传，canal.mq.partitionHash 不起作用

### ISSUE THREAD

**Issue by hittanic** [alibaba/canal#1638]
### environment
cent7.5
* canal version  1.1.2
* mysql version 5.7.20

### Issue Description
# mq config
canal.mq.topic=NewCanalDBTopic
#canal.mq.partition=1
# hash partition config
canal.mq.partitionsNum=5
canal.mq.partitionHash=.\\..*

配置不起作用， 数据还是只会往NewCanalDBTopic 的partition 0分区传， 其余分区都没有消息进来。

**Comment by agapple** [comment]
之前canal.mq.partition和canal.mq.partitionsNum会互斥，而且以canal.mq.partition配置为优先，1.1.3最新版本做了调整，以canal.mq.partitionNum做优先，升级最新版本测试吧

**Comment by hjcdj** [comment]
> 
> 
> 之前canal.mq.partition和canal.mq.partitionsNum会互斥，而且以canal.mq.partition配置为优先，1.1.3最新版本做了调整，以canal.mq.partitionNum做优先，升级最新版本测试吧

我现在就是用的version1.1.4版本，设置了canal.mq.partitionHash=.\..*之后，canal过来的数据还只是在0分区中，有大神指导一下么

**Comment by hjcdj** [comment]
> 
> 
> 之前canal.mq.partition和canal.mq.partitionsNum会互斥，而且以canal.mq.partition配置为优先，1.1.3最新版本做了调整，以canal.mq.partitionNum做优先，升级最新版本测试吧

我现在就是用的version1.1.4版本，设置了canal.mq.partitionHash=.\..*之后，canal过来的数据还只是在0分区中，有大神指导一下么

**Comment by everior** [comment]
也遇到这个问题，只往一个分区里写，求大神知道。

**Comment by jianghanfen** [comment]
> 之前canal.mq.partition和canal.mq.partitionsNum会互斥，而且以canal.mq.partition配置为优先，1.1.3最新版本做了调整，以canal.mq.partitionNum做优先，升级最新版本测试吧

@agapple 解决了没？  canal1.1.5 也存在这个问题，新加分区后，主要往pattition-1上报，其它分区偶尔上报几条。

**Comment by farsunset** [comment]
同问 解决了吗
