### ISSUE TITLE
canal.mq.partitionHash是否会支持根据多表之间的关联字段值，来将多表的数据hash到相同分区

### ISSUE THREAD

**Issue by wangsaner** [alibaba/canal#1640]
# environment

* canal version 1.1.3
* mysql version

### Issue Description

canal.mq.partitionHash是否会支持根据多表之间的关联字段值，来将多表的数据hash到相同分区.

例如：
存在两张表 salesorder（销售单主表）、salesorderitem（销售单明细表）
salesorder.id = salesorderitem.orderid

canal.mq.partitionHash = schema.salesorder:id,schema.salesorderitem:orderid

**Comment by wangsaner** [comment]
看了下源码当前好像不支持（目前是table.hashCode() ^ column.getValue().hashCode()），
不知以后是否考虑支持呢？

**Comment by agapple** [comment]
计算hash的时候不想加入tablename么？只要值相同就路由到相同partition ？

**Comment by lunarzzz** [comment]
请问现在实现了吗？多表根据关联字段Hash到同一分区
