### ISSUE TITLE
canal可以启动但是连接不上rds/mysql

### ISSUE THREAD

**Issue by purevirtual** [alibaba/canal#1642]
### environment

* canal version
canal.deployer-1.1.2

* mysql version
5.6.16

### Issue Description
安装正常 启动正常 然后在mysql-client上数据库连接串也能正常访问 但是canal启动后却总是报host找不到 连接不上

> 
> OpenJDK 64-Bit Server VM warning: ignoring option PermSize=96m; support was removed in 8.0
> OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
> OpenJDK 64-Bit Server VM warning: UseCMSCompactAtFullCollection is deprecated and will likely be removed in a future release.
> 2019-03-28 12:12:52.248 [main] INFO  com.alibaba.otter.canal.deployer.CanalLauncher - ## set default uncaught exception handler
> 2019-03-28 12:12:52.328 [main] INFO  com.alibaba.otter.canal.deployer.CanalLauncher - ## load canal configurations
> 2019-03-28 12:12:52.340 [main] INFO  com.alibaba.otter.canal.deployer.CanalLauncher - ## start the canal server.
> 2019-03-28 12:12:52.369 [main] WARN  com.alibaba.otter.canal.common.utils.AddressUtils - Failed to retriving local host ip address, try scan netwo
> rk card ip address. cause: newdev: newdev: Name or service not known
> 2019-03-28 12:12:52.369 [main] WARN  com.alibaba.otter.canal.common.utils.AddressUtils - Failed to retriving local host ip address, try scan netwo
> rk card ip address. cause: newdev: newdev: Name or service not known
> 2019-03-28 12:12:52.374 [main] INFO  com.alibaba.otter.canal.deployer.CanalController - ## start the canal server[192.168.48.1:11111]
> 2019-03-28 12:12:53.267 [main] WARN  o.s.beans.GenericTypeAwarePropertyDescriptor - Invalid JavaBean property 'connectionCharset' being accessed!
> Ambiguous write methods found next to actually used [public void com.alibaba.otter.canal.parse.inbound.mysql.AbstractMysqlEventParser.setConnectio
> nCharset(java.nio.charset.Charset)]: [public void com.alibaba.otter.canal.parse.inbound.mysql.AbstractMysqlEventParser.setConnectionCharset(java.l
> ang.String)]
> 2019-03-28 12:12:53.586 [main] ERROR com.alibaba.druid.pool.DruidDataSource - testWhileIdle is true, validationQuery not set
> 2019-03-28 12:12:54.273 [destination = example , address = /127.0.0.1:3306 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserPr
> oxy - dump address /127.0.0.1:3306 has an error, retrying. caused by
> com.alibaba.otter.canal.parse.exception.CanalParseException: Unknown host
> Caused by: java.net.UnknownHostException: newdev: newdev: Name or service not known
>         at java.net.InetAddress.getLocalHost(InetAddress.java:1505) ~[na:1.8.0_141]
>         at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.generateUniqueServerId(MysqlEventParser.java:342) ~[canal.parse-1.1.2.jar:
> na]
>         at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.buildMysqlConnection(MysqlEventParser.java:326) ~[canal.parse-1.1.2.jar:na
> ]
>         at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.buildErosaConnection(MysqlEventParser.java:75) ~[canal.parse-1.1.2.jar:na]
>         at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:169) ~[canal.parse-1.1.2.jar:na]
>         at java.lang.Thread.run(Thread.java:748) [na:1.8.0_141]
> Caused by: java.net.UnknownHostException: newdev: Name or service not known
>         at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method) ~[na:1.8.0_141]
>         at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928) ~[na:1.8.0_141]
>         at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323) ~[na:1.8.0_141]
>         at java.net.InetAddress.getLocalHost(InetAddress.java:1500) ~[na:1.8.0_141]
>         ... 5 common frames omitted
> 2019-03-28 12:12:54.276 [destination = example , address = /127.0.0.1:3306 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandl
> er - destination:example[com.alibaba.otter.canal.parse.exception.CanalParseException: Unknown host
> Caused by: java.net.UnknownHostException: newdev: newdev: Name or service not known
>         at java.net.InetAddress.getLocalHost(InetAddress.java:1505)
>         at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.generateUniqueServerId(MysqlEventParser.java:342)
>         at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.buildMysqlConnection(MysqlEventParser.java:326)
>         at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.buildErosaConnection(MysqlEventParser.java:75)
>         at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:169)
>         at java.lang.Thread.run(Thread.java:748)
> Caused by: java.net.UnknownHostException: newdev: Name or service not known
>         at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
>         at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
>         at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
>         at java.net.InetAddress.getLocalHost(InetAddress.java:1500)
>         ... 5 more
> ]
> 2019-03-28 12:12:54.276 [destination = example , address = /127.0.0.1:3306 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - parse events has an error
> com.alibaba.otter.canal.parse.exception.CanalParseException: illegal connection is null
> 2019-03-28 12:12:54.305 [main] INFO  com.alibaba.otter.canal.deployer.CanalLauncher - ## the canal server is running now ......

### Steps to reproduce
```
1.mysql 环境均ok
2.canal在原配置文件的基础上修改内容为:
instance.properties
canal.instance.master.address=127.0.0.1:3306
# username/password
canal.instance.dbUsername=****[realUserName]
canal.instance.dbPassword=******[realPassword]
```

**Comment by agapple** [comment]
Caused by: java.net.UnknownHostException: newdev: Name or service not known，报错很明显了啊

**Comment by purevirtual** [comment]
> Caused by: java.net.UnknownHostException: newdev: Name or service not known，报错很明显了啊

喔 明白了 灯下黑了 主要是这两个环境里的数据库用户名也是dev/newdev 我就一直以为是mysql的host解析有问题了 没想到是local host的问题 谢啦
