### ISSUE TITLE
canal mysql多节点解析 master/standby 切换怎么保证binlog位置的正确

### ISSUE THREAD

**Issue by Sky8080** [alibaba/canal#1646]
### environment
官方文档里说多节点解析需要两台mysql机器而且需要设置为M-M模式，而且需要分别配置两台机器的binlog起始位置；如果两台机器的binlog起始位置设置的不一样canal在从master切换到standby时，canal在standby机器上获取到的第一条数据是紧接着master上的最后一条数据的吗？
如果两台机器的起始binlog位置完全相同，canal能够做到master/standb切换之后再次获取到的数据是紧挨着的吗？
如果配置两台mysql机器为M-S主从模式是不是会对master/standby切换有影响，有什么办法能解决吗？
* canal version 1.1.2
* mysql version 5.7.5

**Comment by agapple** [comment]
基于时间戳进行定位，对于M-M或者M-S模式没有直接依赖
