### ISSUE TITLE
求教canal-adapter配置srcDataSources的作用是什么

### ISSUE THREAD

**Issue by standinhell** [alibaba/canal#1648]
在配置文件里已经配置了canal-server，为什么还要配置源数据库？如果是分库场景该怎么配置？求教

**Comment by standinhell** [comment]
我看了一下源码，好像是做数据回查用的，在es模块里不支持配置多个dataSourceKey是吗，求指教 @rewerma

**Comment by rewerma** [comment]
一些场景无法直接从binlog dml的信息中直接提取到信息需要反查sql，
srcDataSources是个map可以配置多个

**Comment by walkaroundby** [comment]
如何配置多个srcDataSources？
