### ISSUE TITLE
canal + zookeeper 不能正确找到点位

### ISSUE THREAD

**Issue by songjian0270** [alibaba/canal#165]
zookeeper启动正常

> canal配置`

- canal.instance.global.spring.xml = classpath:spring/default-instance.xml

> example/instance.properties

canal.instance.master.address = 172.16.20.120:3306
canal.instance.master.journal.name =
canal.instance.master.position =
canal.instance.master.timestamp =

> 使用除classpath:spring/default-instance.xml以外都能正常捕捉数据库改动，一旦换成classpath:spring/default-instance.xml就不能正常获取

1. 
2. - 2016-04-14 15:41:06.202 [Thread-4] INFO  c.a.otter.canal.instance.spring.CanalInstanceWithSpring - stop CannalInstance for 1-example 
3. - 2016-04-14 15:41:06.204 [Thread-4] INFO  c.a.otter.canal.instance.spring.CanalInstanceWithSpring - stop successful....
4. - [root@Note_140_canal ~]# tailf -n 300 /usr/local/canal.deployer-1.0.21/logs/example/example.log 
5. - 2016-04-14 15:41:34.578 [main] INFO  c.a.o.c.i.spring.support.PropertyPlaceholderConfigurer - Loading properties file from class path resource [canal.properties]
6. - 2016-04-14 15:41:34.588 [main] INFO  c.a.o.c.i.spring.support.PropertyPlaceholderConfigurer - Loading properties file from class path resource [example/instance.properties]
7. - 2016-04-14 15:41:34.645 [main] WARN  org.springframework.beans.TypeConverterDelegate - PropertyEditor [com.sun.beans.editors.EnumEditor] found through deprecated global PropertyEditorManager fallback - consider using a more isolated form of registration, e.g. on the BeanWrapper/BeanFactory!
8. - 2016-04-14 15:41:34.759 [main] INFO  c.a.otter.canal.instance.spring.CanalInstanceWithSpring - start CannalInstance for 1-example 
9. - 2016-04-14 15:41:34.788 [main] INFO  c.a.otter.canal.instance.spring.CanalInstanceWithSpring - subscribe filter change to .*\..*
10. - 2016-04-14 15:41:34.789 [main] INFO  c.a.otter.canal.instance.spring.CanalInstanceWithSpring - start successful....
11. - 2016-04-14 15:41:34.832 [destination = example , address = /172.16.20.120:3306 , EventParser] WARN  c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - prepare to find start position by switch ::1460100169000
12. - 2016-04-14 15:41:34.970 [destination = example , address = /172.16.20.120:3306 , EventParser] WARN  c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - Didn't find the corresponding binlog files from mysql-bin.000001 to mysql-bin.000004
13. - 2016-04-14 15:41:34.979 [destination = example , address = /172.16.20.120:3306 , EventParser] ERROR c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - dump address /172.16.20.120:3306 has an error, retrying. caused by 
14. - com.alibaba.otter.canal.parse.exception.CanalParseException: can't find start position for example
15. - 2016-04-14 15:41:34.983 [destination = example , address = /172.16.20.120:3306 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:example[com.alibaba.otter.canal.parse.exception.CanalParseException: can't find start position for example
16. - ]
17. 
18. ```

**Comment by suhuaguo** [comment]
通过 时间戳 1460100169000。找不到 对应的 binlog 日志文件

**Comment by songjian0270** [comment]
现在已经解决了，压缩包传到linux被损坏了
