### ISSUE TITLE
能否支持针对topic设置partitionsNum

### ISSUE THREAD

**Issue by xesygao** [alibaba/canal#1652]
### environment

* canal version 1.1.3 alpha3
* mysql version  5.7.23

### Issue Description
1.1.3支持动态topic，但是分区数只能针对实例设置。能否针对实例的topic分别设置分区数

**Comment by agapple** [comment]
canal.mq.partitionHash和canal.mq.dynamicTopic 可以对齐一下，针对同一张表设置不同的partition策略，但partitionNum需要每个topic不同，有具体的诉求点么？

**Comment by xesygao** [comment]
> canal.mq.partitionHash和canal.mq.dynamicTopic 可以对齐一下，针对同一张表设置不同的partition策略，但partitionNum需要每个topic不同，有具体的诉求点么？

我考虑的是不同表的数据量不同，针对数据量比较大的表设置更多的队列来提升消费能力

**Comment by agapple** [comment]
暂时不支持，目前动态创建topic时也没法指定分区数

**Comment by gabrywu** [comment]
其实这个需求还是有的，毕竟每个topic都设置相同的分区数还是很不合理的，我刚刚把所有的topic分区数改成一致！！！
