### ISSUE TITLE
canal.mq.dynamicTopic类型问题 ：大神，我想把多个分表写入同一个topic,配置如下，但现在问题是kafka按照表的名字创建出几百个topic出来 

### ISSUE THREAD

**Issue by Bruce2jiang** [alibaba/canal#1654]
大神，我想把多个分表写入同一个topic,配置如下，但现在问题是kafka按照表的名字创建出几百个topic出来，我只是想创建一个topic:  oms_waybill_01_waybill 。这是我的配置 ：canal.mq.dynamicTopic=oms_waybill_01_waybill:^oms_waybill_0\\.waybill_([1-9]\\d|\\d)$,^oms_waybill_1\\.waybill_([1-9]\\d|\\d)$  

 解释一下 :

^oms_waybill_0\\.waybill_([1-9]\\d|\\d)$是0号库的100个分表，
^oms_waybill_1\\.waybill_([1-9]\\d|\\d)$是1号库的1百个分表

还有个问题 ：你们的这个提交问题的编辑器会把  双斜杠，保存后变成  单斜杠

**Comment by agapple** [comment]
多个分隔条件，不要用逗号分隔，写两遍.  
oms_waybill_01_waybill:^oms_waybill_0\.waybill_([1-9]\d|\d)$ ; oms_waybill_01_waybill:^oms_waybill_1\.waybill_([1-9]\d|\d)$

**Comment by Bruce2jiang** [comment]
谢谢，我试一下

**Comment by yangyiweigege** [comment]
user:^demo\\.user_([1-9]\\d|\\d)$
