### ISSUE TITLE
canal发kafka性能偏低

### ISSUE THREAD

**Issue by zhdogit** [alibaba/canal#1656]
### environment

* canal version: 1.1.2
* mysql version: 5.5.5-10.1.37-MariaDB MariaDB Server

### Issue Description
通过canal server直接发flatten message到Kafka，性能偏低。对于写入量很大的表（比如：7k 条记录每秒），canal server的offset和mysql从库的差距一直在拉大。

**Comment by agapple** [comment]
参考用1.1.3最新版做下测试，印象中有修复类似问题

**Comment by rewerma** [comment]
使用最新代码，flatMessage模式下调大canal.mq.lingerMs，比如50-200
