### ISSUE TITLE
5.7版本mysql数据库初始化脚本执行报错

### ISSUE THREAD

**Issue by AlexRenCN** [alibaba/canal#1657]
### environment

* canal version
* mysql version

**Comment by AlexRenCN** [comment]
脚本来源：
https://raw.githubusercontent.com/alibaba/otter/master/manager/deployer/src/main/resources/sql/otter-manager-schema.sql

按这个脚本执行的时候，出现报错：
-- 11:11:56	CREATE TABLE `ALARM_RULE` (   `ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT,   `MONITOR_NAME` varchar(1024) DEFAULT NULL,   `RECEIVER_KEY` varchar(1024) DEFAULT NULL,   `STATUS` varchar(32) DEFAULT NULL,   `PIPELINE_ID` bigint(20) NOT NULL,   `DESCRIPTION` varchar(256) DEFAULT NULL,   `GMT_CREATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',   `GMT_MODIFIED` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,   `MATCH_VALUE` varchar(1024) DEFAULT NULL,   `PARAMETERS` text DEFAULT NULL,   PRIMARY KEY (`ID`) ) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8	Error Code: 1067. Invalid default value for 'GMT_CREATE'	0.047 sec

错误原因和5.7版本初始值不兼容有关，可以在session级别进行临时修改，确保脚本正常运行：
set sql_mode='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';;


在mysql执行select version() 结果为5.7.21-log

**Comment by agapple** [comment]
建议提交一个PR到otter 项目吧
