### ISSUE TITLE
canal源库高可用问题

### ISSUE THREAD

**Issue by gggyd123** [alibaba/canal#1659]
目前canal连接的mysql数据库是一个单点，如果该库出问题无法快速恢复，不知道这个问题有什么解决办法？如果单点出现问题后，快速切换到另外一个库上，不知道canal是否支持按照时间戳定位位点的功能？

**Comment by agapple** [comment]
多看wiki，canal有HA的能力

**Comment by gggyd123** [comment]
> 多看wiki，canal有HA的能力

不好意思，看了下文档确实有这个功能，但是有个问题想请教一下，如果发生了数据库的切换，那位点是怎么定位的，因为不同数据库binlog文件名和position可能都不一样，这种切换会通过时间戳去定位吗？
