### ISSUE TITLE
从1.0.24升级到1.1.3 alpha后同步速度变得非常慢

### ISSUE THREAD

**Issue by lvcheng1031** [alibaba/canal#1663]
### environment

* canal version 1.1.3 alpha
* mysql version 5.7 5.6 8.0.x

### Issue Description
打算从1.0.24升级到1.1.3以接入8.0.x 但是升级以后发现同步速度变得非常慢，并确认非client处理问题。
### Expected behaviour
期望同步速度跟以前保持一致

**Comment by agapple** [comment]
你这问题提问的，让我没法回答，没一点有体感和有用的信息

**Comment by lvcheng1031** [comment]
日志里也没有报错... 就是位点走得非常慢 现象就是这样的

**Comment by Tangkysin** [comment]
老哥你这个慢的有解决么？
我用1.1.1 - 1.1.3 这些版本都很慢。
数据回来都对，就是慢得发指。
