### ISSUE TITLE
canal1.1.3 不会刷新binlog位点信息到zookeeper

### ISSUE THREAD

**Issue by Sky8080** [alibaba/canal#1666]
### environment

* canal version 1.1.3
* mysql version 5.7.5

### Issue Description
早上我使用canal1.1.2测试HA高可用，发现两者之间切换有问题但是全部关闭再起一个canal server服务是能接着正常抽取的，而且在zkui里能看到position的实时变化。下午换成了canal1.1.3发现position信息并不会实时更新到zookeeper里，而且两个canal server之间来回切换每次总是获取的固定不变的position，就算之起一个canal server然后停止再启动在zookeeper里获取的还是固定不变的position

**Comment by agapple** [comment]
1.1.3的最新包么？

**Comment by Sky8080** [comment]
是最新的今天刚下载的，我在instance里设置了binlog的起点位置，这个位置点是一个历史位置点在这个点之后我手动插入了一张表的数据；我起来canal服务之后在zookeeper里看到position更新到了一个新的数值，但是之后就不再变化，同时canal还在不停的往kafka里发送数据。其实我就是想验证一下在canal serer进行切换时候能不能准确的继续上次位点继续抽取，换成了一个只有两个字段的表从开始到结束中间切换了两次canal server都能看到position的变化，不过有canal server切换比没有canal server切换在kafka里的数据量大了70M

**Comment by agapple** [comment]
数据重复是难免的，你业务上没用大事务来做测试吧？

**Comment by Sky8080** [comment]
没有使用大事务，我是先导入的数据，然后手动设置的binlog位点是插入数据之前的，插入的表字段有70个左右SQL脚本文件有600M左右；不知道为什么就不更新position了，是不是我在使用navicat手动导入数据时导致binlog文件出错了，不过我看了一下canal的日志并没有报任何错误

**Comment by agapple** [comment]
jstack和meta.log看一下

**Comment by Sky8080** [comment]
我再测试一遍，然后把详细的错误信息传上来，我有个疑问canal server切换的时候是从zookeeper获取的binlog位点信息，为什么还会难免有重复的数据呢？还有就是这个切换的过程会不会有数据丢失的可能呢

**Comment by agapple** [comment]
zookeeper的位点是异步定时刷新的

**Comment by shengmingzhu** [comment]
老哥，请教一下，为什么不能用大事务测试？我用一条update语句更新全表，100万行，发现canal异常了，后面不再往kafka写数据了。@Sky8080，@agapple

**Comment by agapple** [comment]
具体异常贴出来

**Comment by zhangqh01** [comment]
> 没有使用大事务，我是先导入的数据，然后手动设置的binlog位点是插入数据之前的，插入的表字段有70个左右SQL脚本文件有600M左右；不知道为什么就不更新position了，是不是我在使用navicat手动导入数据时导致binlog文件出错了，不过我看了一下canal的日志并没有报任何错误

你好 请教一下  手动设置的binlog位点怎么设置呢？  我在 instance.properties 中配置canal.instance.standby.journal.name =mysql-bin.000001   似乎zk中并不会同步  canal版本也是1.1.3
