### ISSUE TITLE
MySQL重新连接报错

### ISSUE THREAD

**Issue by sosozhuang** [alibaba/canal#1668]
### environment

* canal version 1.1.2
* mysql version 5.7

### Issue Description
运行一段时间后，连接mysql出现socket timeout，重新创建MysqlConnector，使用InetSocketAddress.getHostString()再构造InetSocketAddress，在服务器有多个网卡的情况下，构造出来的address可能会是另外一个地址，导致连接不上mysql。这里为什么不直接使用传进来的address？
```java
    public MysqlConnector(InetSocketAddress address, String username, String password){
        String addr = address.getHostString();
        int port = address.getPort();
        this.address = new InetSocketAddress(addr, port);

        this.username = username;
        this.password = password;
    }
```

**Comment by agapple** [comment]
hostname -i 最好绑定一下本机ip

**Comment by sosozhuang** [comment]
hostname -i有两个ip，第2个才是连接数据库的网络IP，destination配置文件也是配置第2个IP，但这里构造的address获取的是第1个IP。
