### ISSUE TITLE
请问1.13 flatMessages为何没有同步发送kafka

### ISSUE THREAD

**Issue by undeadwing** [alibaba/canal#1672]
请问1.13源码里，CanalKafkaProducer类在发送probuf数据时使用同步发送方式，发送json时候仍然使用异步发送，之前用异步会出现丢数情况，请问这里是否应该改成同步发送

private void produce(String topicName, int partition, FlatMessage flatMessage) throws ExecutionException,
                                                                                  InterruptedException {
        ProducerRecord<String, String> record = new ProducerRecord<String, String>(topicName,
            partition,
            null,
            JSON.toJSONString(flatMessage, SerializerFeature.WriteMapNullValue));
        if (kafkaProperties.getTransaction()) {
            producer2.send(record);
        } else {
            producer2.send(record);
        }
    }

**Comment by agapple** [comment]
已调整为同步模式
