### ISSUE TITLE
1.1.3同步到ES报空指针异常

### ISSUE THREAD

**Issue by aa138002441** [alibaba/canal#1673]
![image](https://user-images.githubusercontent.com/22810287/55788059-3801cd00-5aea-11e9-9d4b-85a7acff7702.png)
  demo的mytest_user可以成功，但是我新建个索引和表就不行了

**Comment by aa138002441** [comment]
我跟代码看 这个对象是null的 不知所以然
![image](https://user-images.githubusercontent.com/22810287/55788207-7a2b0e80-5aea-11e9-9498-d787d6086a1e.png)

**Comment by shenxiangwei** [comment]
是啥问题，咋解决的
