### ISSUE TITLE
canal针对现有数据同步怎么处理？

### ISSUE THREAD

**Issue by aa138002441** [alibaba/canal#1682]
canal针对现有数据同步怎么处理？

**Comment by agapple** [comment]
可以用mysql现有的全量工具

**Comment by gangh** [comment]
> canal针对现有数据同步怎么处理？

对于全量可以使用 mysqldump 导出再导入, 对与现有数据的差异部分可以使用 pt-table-sync 来 diff 获取差异部分再处理

**Comment by kittsai** [comment]
> 

请问使用mysql slave同步，是否会和canal产生冲突？表数据是否会同步重复呢？
