### ISSUE TITLE
同步ｈｂａｓｅ数据一致性的疑问

### ISSUE THREAD

**Issue by 88265920** [alibaba/canal#1683]
现有ｈｂａｓｅ的同步方案，需要每张表配置表映射文件，就有几个疑问：

１、ｍｙｓｑｌ主库修改了表结构，而ｃａｎａｌ对应的表映射文件没有修改，那么这时数据会丢失吗?

2、ｍｙｓｑｌ主库新建了表，之后在ｃａｎａｌ配置表映射文件，中间这部分时间的数据会丢失吗？

**Comment by rewerma** [comment]
会丢失
