### ISSUE TITLE
canal是否支持启用了searchguard权限认证的es集群？

### ISSUE THREAD

**Issue by sanaLiu** [alibaba/canal#1684]

**Comment by MrYZD** [comment]
同问，解决了吗？ 看起来是不支持的

**Comment by sanaLiu** [comment]
你可以试试 https://github.com/siddontang/go-mysql-elasticsearch这个工具，是支持https基础认证的mysql同步到es，我是想多表连查生成新表，但是不行，如果你是单表的话是可以的
