### ISSUE TITLE
Canal配置文件中的canal.instance.filter.black.regex 正则问题

### ISSUE THREAD

**Issue by qiu-zhiwei** [alibaba/canal#1695]
Canal的配置canal.instance.filter.black.regex= 要求写过滤正则,多个以逗号分隔。
如果我的正则本身就有逗号，是不是这里就会有问题？    类似   dbs[0-9]{1,2}\.person$

**Comment by agapple** [comment]
目前是会有这么一个问题

**Comment by cun123** [comment]
canal.instance.filter.regex不起作用，lz有遇到吗？

**Comment by agapple** [comment]
@cun123 看一下FAQ，已经被filter常见问题都说明了
