### ISSUE TITLE
一个CanalServer是否支持多个CanalClient？

### ISSUE THREAD

**Issue by leveysama** [alibaba/canal#1698]
## Question

目前服务器需要集群，这样的架构将会变成，多台Canal客户端，一台Canal服务端
是否支持这样的方式？
想实现一条Canal消息被多台Canal客户端消费，有没有其他可行的方式？

**Comment by wgqazll** [comment]
目前一个服务端不支持多个客户端，你可以利用mq的topic模式

**Comment by wgqazll** [comment]
按照这（https://github.com/alibaba/canal/wiki/ClientAPI）里面的说明，目前是不支持的，但是你可以利用mq的特性来满足你的需求，新版本是支持写到kafka和rocketmq的

**Comment by leveysama** [comment]
@wgqazll 谢谢 我尝试一下
