### ISSUE TITLE
canal怎么和RocketMQ集成？

### ISSUE THREAD

**Issue by cupid255** [alibaba/canal#170]
因为要实现多客户端订阅的效果，貌似canal本身是不支持的。
所以考虑和RocketMQ结合使用。 
能否不需要canal-client，直接canal-server中消息直接推到MQ中？
是不是要定制canal-server才可以？ 定制的工作量大吗？

**Comment by agapple** [comment]
使用canal client获取到消息后写入Rocketmq

**Comment by alswl** [comment]
我现在就是写了一个中间应用，使用 Redis 订阅一个 instance，然后在 Redis 里面多次消费。
