### ISSUE TITLE
Server端的空闲连接中断异常解决方案

### ISSUE THREAD

**Issue by acuitong** [alibaba/canal#1703]
请问目前canal对于server端的
[New I/O server worker #1-4] ERROR c.a.otter.canal.server.netty.handler.SessionHandler - something goes wrong with channel:[id: 0x56a9344c, /107.8.1.16:50558 => /107.8.1.20:11111], exception=java.io.IOException: Connection reset by peer异常解决方案是什么？？

**Comment by agapple** [comment]
client断开连接，做好重试
