### ISSUE TITLE
canal server对接RocketMQ集群环境，使用partitionHash, 但是数据一直投递到同一个Broker

### ISSUE THREAD

**Issue by flackyang** [alibaba/canal#1706]
- [ ] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment

* canal version 1.1.3
* mysql version 5.7.20

### Issue Description
Canal Server 对接 RocketMQ集群环境（2主2从集群，Broker a 和 Broker b），instance.properties配置信息如下
~~~
# mq config
canal.mq.topic=example
canal.mq.dynamicTopic=.*\\..*
#canal.mq.partition=0
# hash partition config
# topic默认队列大小为4
canal.mq.partitionsNum=4
# 基于表名进行hash
canal.mq.partitionHash=.*\\..*
~~~

解析的Binlog数据一直投递到Broker a,  Broker b中无数据
(担心热点表数据过大，一直投递到同一个Broker对集群性能产生影响）
### Expected behaviour
期望： 根据表名Hash, 不同的表可以分散到不现的Broker, 数据在RocketMQ上均衡分布

### Actual behaviour
实际：解析的Binlog数据一直投递到Broker a,  Broker b中无数据

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by agapple** [comment]
看一下MQ多个topic对应分区的数据分布情况，确认是否都集中到了一个分区还是多个分区？

**Comment by farsunset** [comment]
兄弟 你这个问题解决了吗 同问

**Comment by MeetMax** [comment]
partitionsNum 需要>= broker-a+broker-b 的 queue数，baoker-a、baoker-b才能均匀分配消息
