### ISSUE TITLE
canal非正常关闭进程，数据是否会丢失

### ISSUE THREAD

**Issue by hektor8603** [alibaba/canal#1707]
canal在Parse阶段 将mysql binlog日志解析后 通过Sink组件发送到Store阶段里的一个环形队列MemoryEventStoreWithBuffer中去，在Parse阶段，一旦发送成功后就会直接ack，ack就会将binlog的偏移量先保存在内存，并1s秒钟持久化一次到zk中，但是这个时候数据还在环形缓存队列里 用户客户端还没有消费ack，一旦这个时候进程崩了 是不是会造成数据丢失呢？

**Comment by SwaggyQ** [comment]
你好，能不能提供一下你说的parse完直接ack的相关代码？因为我并没有看到这部分的东西，我看到的是parse完，放入ringbuffer之后。embeddedServer会提供一个getWithAck的方法，客户端接收数据成功之后会再发送ack，从而最后移动zk上的位点信息。还提供了一个get的方法，是取数据之后，直接ack的可能会有问题的方法。但是没看到你说的那部分，所以最好可以贴出那部分代码，一起讨论一下:)

**Comment by hektor8603** [comment]
详情可以看下AbstractEventParser 这个构造方法里
 boolean successed = consumeTheEventAndProfilingIfNecessary(transaction);
                if (!running) {
                    return;
                }

                if (!successed) {
                    throw new CanalParseException("consume failed!");
                }

                LogPosition position = buildLastTransactionPosition(transaction);
                if (position != null) { // 可能position为空
                    logPositionManager.persistLogPosition(AbstractEventParser.this.destination, position);
                }
consumeTheEventAndProfilingIfNecessary这个是调用sink组件向store里的环形队列发送数据，这个环形队列是阻塞的，发送成功后，就会返回true，接下来buildLastTransactionPosition这遍历这批已经发送的binlog数据，找到最大的位点，再调用  logPositionManager.persistLogPosition将起持久化，而客户端用户的ack仅仅针对环形队列里的数据，但真正将binlog偏移量持久化的地方在Parse阶段

**Comment by SwaggyQ** [comment]
我看了你说的这里的代码，你说的 logPositionManager.persistLogPosition方法是positionManager去持久化，一般默认的实现方式是FailbackLogPositionManager，也就是内部有primary (内存实现)和secondary(在这边是zk实现的方式)。可以看到这个default-instance.xml文件
![image](https://user-images.githubusercontent.com/16660199/56207749-1d979880-6082-11e9-84e1-039fbe38571b.png)

所以看一些你说的这一个方法内部。


    @Override
    public void persistLogPosition(String destination, LogPosition logPosition) throws CanalParseException {
        try {
            primary.persistLogPosition(destination, logPosition);
        } catch (CanalParseException e) {
            logger.warn("persistLogPosition use primary log position manager exception. destination: {}, logPosition: {}",
                destination,
                logPosition,
                e);
            secondary.persistLogPosition(destination, logPosition);
        }
    }


也就是首选是在MemoryLogPositionManager，也就是内存中存一份，如果内存存储失败，就会在MetaLogPositionManager中存一份，默认的实现是donothing的

    @Override
    public void persistLogPosition(String destination, LogPosition logPosition) throws CanalParseException {
        // do nothing
        logger.info("persist LogPosition:{}", destination, logPosition);
    }

所以默认情况是不会有问题的，如果不是默认的，而是采用ZooKeeperLogPositionManager这种方式的话，看到这个方法的实现，


    @Override
    public LogPosition getLatestIndexBy(String destination) {
        // 这里是不同于真正cursor的存储路径的，这里的路径是/otter/canal/destinations/{destination}/parse
        String path = ZookeeperPathUtils.getParsePath(destination);
        byte[] data = zkClientx.readData(path, true);
        if (data == null || data.length == 0) {
            return null;
        }

        return JsonUtils.unmarshalFromByte(data, LogPosition.class);
    }


所以也不会有提前就移动zk中实际位点的可能。
这是我的理解，有不对的地方可以再讨论一下:)

**Comment by hektor8603** [comment]
这代码有点乱，找到原因了Parse阶段那个persistLogPosition持久化仅仅是将最新位点信息存放在内存中，方便dump binlog日志的时候取最新位点，而真正持久化位点信息是在CanalServerWithEmbedded的ack操作，这个ack会把之前get到的这批数据里找到可以ack的位点，然后调用PeriodMixedMetaManager类里updateCursor方法 里面会将数据进行持久到zk，最后再对环形队列进行ack，环形队列会移除ack的数据，
CanalServerWithEmbedded里ack的代码如下：
`  // 更新cursor
        if (positionRanges.getAck() != null) {
            canalInstance.getMetaManager().updateCursor(clientIdentity, positionRanges.getAck());
            if (logger.isInfoEnabled()) {
                logger.info("ack successfully, clientId:{} batchId:{} position:{}",
                    clientIdentity.getClientId(),
                    batchId,
                    positionRanges);
            }
        }
        // 可定时清理数据
        canalInstance.getEventStore().ack(positionRanges.getEnd());`

再看看PeriodMixedMetaManager的updateCursor方法
`public void updateCursor(ClientIdentity clientIdentity, Position position) throws CanalMetaManagerException {
        super.updateCursor(clientIdentity, position);
        updateCursorTasks.add(clientIdentity);// 添加到任务队列中进行触发
    }`

先将数据放到内存中，再将这个clientIdentity添加到更新任务集合中
`  // 启动定时工作任务
        executor.scheduleAtFixedRate(new Runnable() {

            public void run() {
                List<ClientIdentity> tasks = new ArrayList<ClientIdentity>(updateCursorTasks);
                for (ClientIdentity clientIdentity : tasks) {
                    try {
                        // 定时将内存中的最新值刷到zookeeper中，多次变更只刷一次
                        zooKeeperMetaManager.updateCursor(clientIdentity, getCursor(clientIdentity));
                        updateCursorTasks.remove(clientIdentity);
                    } catch (Throwable e) {
                        // ignore
                        logger.error("period update" + clientIdentity.toString() + " curosr failed!", e);
                    }
                }
            }
        }, period, period, TimeUnit.MILLISECONDS);`
这个定时任务默认1秒钟往zk中更新一次数据，假如在这个1秒范围内突然canal进程非正常关闭，还没来得及将位点信息持久化到zk，这个时候，canal再次启动时候会重复消费一段数据，但能保证不丢数据

上面的是对位点信息持久化，下面看看当canal首次启动时候如何从zk中加载最新位点，里面代码也是很曲折的，主要是通过FailbackLogPositionManager这个位点管理类来实现的，在Parse阶段调用getLatestIndexBy方法
` @Override
    public LogPosition getLatestIndexBy(String destination) {
        LogPosition logPosition = primary.getLatestIndexBy(destination);
        if (logPosition != null) {
            return logPosition;
        }
        return secondary.getLatestIndexBy(destination);
    }`

这个是取位点信息，primary里对应的是MemoryLogPositionManager，先从内存里取，取不到之后再从secondary里取，secondary对应的是MetaLogPositionManager，代码如下
` @Override
    public LogPosition getLatestIndexBy(String destination) {
        List<ClientIdentity> clientIdentities = metaManager.listAllSubscribeInfo(destination);
        LogPosition result = null;
        if (!CollectionUtils.isEmpty(clientIdentities)) {
            // 尝试找到一个最小的logPosition
            for (ClientIdentity clientIdentity : clientIdentities) {
                LogPosition position = (LogPosition) metaManager.getCursor(clientIdentity);
                if (position == null) {
                    continue;
                }

                if (result == null) {
                    result = position;
                } else {
                    result = CanalEventUtils.min(result, position);
                }
            }
        }

        return result;
    }`

MetaLogPositionManager类依赖PeriodMixedMetaManager类，会调用其getCursor方法，而PeriodMixedMetaManager类在初始化的时候会从zk中拉数据到内存中代码如下
`       protected Map<ClientIdentity, Position>      cursors;
  cursors = MigrateMap.makeComputingMap(new Function<ClientIdentity, Position>() {

            public Position apply(ClientIdentity clientIdentity) {
                Position position = zooKeeperMetaManager.getCursor(clientIdentity);
                if (position == null) {
                    return nullCursor; // 返回一个空对象标识，避免出现异常
                } else {
                    return position;
                }
            }
        });`

这个类的getCursor方法如下
`public Position getCursor(ClientIdentity clientIdentity) throws CanalMetaManagerException {
        Position position = super.getCursor(clientIdentity);
        if (position == nullCursor) {
            return null;
        } else {
            return position;
        }
    }`
其中Position position = super.getCursor(clientIdentity);这行代码就是从刚才从zk里拉出放到map里的数据

以上就是canal位点的信息zk持久化以及启动时候初始化功能，有点绕，本来以为CanalLogPositionManager相关的类才是对位点信息生命周期的管理包括持久化和初始化，结果还有CanalMetaManager接口相关实现类的参与，开始看源码的时候完全没注意到

**Comment by SwaggyQ** [comment]
是的，canal这种机制保证不会丢数据，可能会有重复数据
我之前看代码的时候你说的persistLogPosition方法我也没有仔细看过，昨天你提出了我才去看了一下，感谢交流:)
