### ISSUE TITLE
ES 同步数据库由非null update 成 null  更新有问题

### ISSUE THREAD

**Issue by bestzhao** [alibaba/canal#1711]
- [ ] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment

* canal version 1.1.3
* mysql version

### Issue Description
当数据库变更某字段为null且该字段对应es mapping类型为 keyword 或者text类型的时候，ESSyncUtil这个类下的typeConvert方法，最后会采用val.toString(),由于是null会返回Object.toString() ,就是getClass().getName()+"@"+hashCode()，导致存到es里面不正确
![image](https://user-images.githubusercontent.com/19585900/56263736-b7a92080-6116-11e9-9cb4-0a24ddb16690.png)

### Actual behaviour

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by rewerma** [comment]
最新版本好像没这个问题，es中的内容会被更新成空串
