### ISSUE TITLE
canal mysql 同步数据到 elasticsearch 非常慢

### ISSUE THREAD

**Issue by zhuxiaokang0223** [alibaba/canal#1718]
MySql批量新增100000条数据， 
查看canal adapter es 1.1.3的adapter日志，发现打印的DML日志比较慢， elasticsearch的对应索引中只插入了几条数据，然后等很久都没有数据插入。 同步速度太慢了。

将批量插入的数据量改为1000条， 大概2秒同步一条数据到es

 请问是什么原因？

**Comment by rewerma** [comment]
配置贴出来看看

**Comment by Mysia** [comment]
调整一下jvm的内存试试呢？

**Comment by house0128** [comment]
canal-adpater同步性能性能不够高，我们是
1.改造成了单线程拉取数据，多线程同步的策略，
2.重写了同步逻辑，在两个表join的时候，尽量少的反查数据库降低数据库反查对数据库的压力。
目前改造后10个线程同步qps能达到3k-4k。

**Comment by KerryJava** [comment]
`2019-04-23 16:01:17.289 [Thread-5] DEBUG c.a.o.canal.adapter.launcher.loader.CanalAdapterWorker CanalAdapterWorker.java 122 - destination: xxx batchId: 13 elapsed time: 38777 ms
`    参考一下

**Comment by KerryJava** [comment]
> `2019-04-23 16:01:17.289 [Thread-5] DEBUG c.a.o.canal.adapter.launcher.loader.CanalAdapterWorker CanalAdapterWorker.java 122 - destination: xxx batchId: 13 elapsed time: 38777 ms ` 参考一下 8核16G es也是8核16G

`2019-04-23 17:04:49.415 [pool-4-thread-1] TRACE c.a.otter.canal.client.adapter.es.service.ESSyncService ESSyncService.java 69 - Sync elapsed time: 3327 ms, affected indexes count：1, destination: xxx`

**Comment by KerryJava** [comment]
已经修复 #1743

**Comment by JKTerrific** [comment]
@KerryJava  你好。commitBulk的动作是在从db对sql查询之后完成的。以wholeSqlOperation方法为例。每次都需要查询完整数据后才进入commitBulk环节。换句话说阻塞操作的情况下，sql的执行效率会严重影响条binlog消息的处理时长。这方面有什么好的建议去处理吗

**Comment by luojun0513** [comment]
请问下，你写的sql包含left join  或 子查询吗   如果包含了，有没有看看sql的执行性能？adapter会拼装sql，反查数据库，如果拼装出来的SQL查询很慢，也会导致同步数据很慢。

**Comment by CoderLiuyang** [comment]
> canal-adpater同步性能性能不够高，我们是
> 1.改造成了单线程拉取数据，多线程同步的策略，
> 2.重写了同步逻辑，在两个表join的时候，尽量少的反查数据库降低数据库反查对数据库的压力。
> 目前改造后10个线程同步qps能达到3k-4k。

我们现在也是因为同步时反查的性能卡住了，由于子查询过于复杂，请问你们是怎么减少反查的，接收到binlog日志后查的es吗？

**Comment by KerryJava** [comment]
#2645
