### ISSUE TITLE
rds配置了主从库，主从库切换时候出现异常。

### ISSUE THREAD

**Issue by chenyishun** [alibaba/canal#172]
异常报错如下：
16-04-22 07:11:24.236 [destination = crm_csc_03 , address = rdst58y130m2pdn0th48.mysql.rds.aliyuncs.com/10.248.4.8:3306 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:crm_csc_03[java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = Could not find first log file name in binary log index file
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:95)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:113)
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:209)
	at java.lang.Thread.run(Thread.java:745)
]
主从库切换从库上没有找到binlog,fetch时报错。
我看canal监听可以配置主从库地址。这个方法可以解决该问题吗？
像这种问题有没有好的解决方案？

**Comment by agapple** [comment]
错误的位点，需要按照时间戳进行订阅

**Comment by chenyishun** [comment]
大哥，Could not find first log file name in binary log index file 不是错误的位点吧！！！这是fetch时候bingo文件丢失了。重启错误依旧，只能跳过。这bingo丢失应该是主从库切换引起的。你们有没有遇到过这种问题。

**Comment by chenyishun** [comment]
问题是错误的位点没错，但是canal一直在运行。这是运行中的异常。设置时间戳可以跳过这段。但会引起数据丢失。我是想知道。这种错误应该怎么样去避免。instance.properties配置standby可以避免这种问题发生吗？或者有什么好的解决方案。

**Comment by agapple** [comment]
rds的vip模式，canal无法感知主备切换的操作，用之前主库的binlog位点去备库(新的主库)去找，当然会找不到

**Comment by owenludong** [comment]
目前只能做好监控 当发现主备切换 及时在binlog被删除前 做到按时间重置

**Comment by agapple** [comment]
我后续版本会考虑下，可以提供一个思路，如果同学有兴趣可以按照实现之. 

1. 订阅binlog之后，获取一下binlog事件的mysql server id，作为position的一部分记录到位点中
2. 节点发生binlog位点不可用时，通过新建链接判断一下mysql server id是否有所不同，如果不同则自动按照时间戳进行订阅 

查询mysql的server_id的办法:
```
show variables like 'server_id';
```

**Comment by chenyishun** [comment]
这个修改建议非常好，不过按此修改还是会出现一些问题。rds在有些时候binlog也会被清除。如rds规格升级等，我总结了一些规律当出现IOException的时候错误基本不可恢复。企业应用很多情况。希望跳过错误继续后面的操作，并且告知相关维护人员，我现在修改的方案是：
1、当出现IOException时retry指定次数。超过次数时获取当前最新的位点，重新连接。
2、错误日志输出和报警输出(建议以后可以实现邮件预警)
3、ExceptionRetryCount可在配置文件配置。不配置的话。按以前的方式处理。
相关代码我已经修改并且已经测试通过应用到了生产环境，如果版主觉得我思路正确，我可以提交相关代码。

**Comment by agapple** [comment]
建议提交下代码，一起看下代码，希望canal未来能更好的支持这一类vip模式的主备集群，你和我的两个方法可以结合处理

**Comment by zhufeizzz** [comment]
我现在也遇到这个问题了，我们用的亚马逊的RDS，对mysql的flush logs的权限做了限制
我尝试了清空zookeeper里面的信息并重启canal还不行，请问还有什么方式手动修复吗？

**Comment by zhufeizzz** [comment]
哎 知道了问题 RDS默认只保留10分钟的binlog，如果canal中断了10分钟以上就再也起不来了。。。
希望能提供个简单的命令或者配置文件重置为最新位点，每次手工操作好麻烦

**Comment by chenyishun** [comment]
我修改了一些代码。当出现这种错误一定的次数。自动重置最新的位点。代码提交了。看看阿里的哥们会不会采用了。

**Comment by agapple** [comment]
PR代码已合并，会适当再精确识别一下异常内容，判断需要进行主备切换，尽可能保证不丢数据

**Comment by simba-1** [comment]
貌似mysql GTID 有这个功能
