### ISSUE TITLE
client-adapter pom文件好像缺少了

### ISSUE THREAD

**Issue by wushihua** [alibaba/canal#1720]
- [ ] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment

* canal version
1.1.3
* mysql version
8.0
### Issue Description
client-adapter找不到类
import org.apache.curator.framework.CuratorFramework;
pom文件加上
        <dependency>
            <groupId>org.apache.curator</groupId>
            <artifactId>curator-framework</artifactId>
            <version>4.2.0</version>
        </dependency>

### Actual behaviour

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by rewerma** [comment]
?在launcher/pom.xml里的啊，怎么会报类找不到
