### ISSUE TITLE
MemoryEventStore内存管理

### ISSUE THREAD

**Issue by pc-fuqq** [alibaba/canal#1724]
## Question

先说下我的情况，我采用嵌入式方式将canalServer嵌入业务系统，并且针对MemoryEventStore设置了batchMode=MEMSIZE，bufferSize=16*1024，按理说每一个MemoryEventStore的最大内存都不会超过16M，但是我在分析jvm内存试发现某个MemoryEventStore的内存升到了32M，很是不理解，求解，谢谢！

**Comment by zwangbo** [comment]
我记得这里的MEMSIZE是根据binlog里面的二进制大小计算的，实际的heap占用还要算上对象的膨胀会大一些

**Comment by agapple** [comment]
LS正解,  新的版本在store里针对raw=false时 直接存储proto的byteString, 这样就可以精确内存管理
