### ISSUE TITLE
请问这正常吗?

### ISSUE THREAD

**Issue by Fanduzi** [alibaba/canal#1727]
## Question

![image](https://user-images.githubusercontent.com/24428128/56467992-b3536f00-6458-11e9-905f-a9da6ffb3565.png)
忽略没数据的那段, 是我重启instance来着
为啥TPS(MySQL transaction)是0 而 TPS(table rows)确是1,2k

**Comment by agapple** [comment]
遇到大事务了？

**Comment by Fanduzi** [comment]
> 遇到大事务了？

没有. 什么情况会这样?
