### ISSUE TITLE
是否支持mysql与es的实时同步？

### ISSUE THREAD

**Issue by yzhuwei** [alibaba/canal#1729]
## Question

你好，我手上的一个项目由于数据量很大可能是亿级别的，需要用到递归查询出关联ID，然后通过关联ID查询出业务数据。所以想问下 是否支持mysql与es是否能实时同步 或者 间隔1s同步 ？

**Comment by Thirtyfat** [comment]
问题解决了吗？我目前也有这个需求...

**Comment by agapple** [comment]
wiki里有介绍同步到ES

**Comment by Thirtyfat** [comment]
嗯嗯 已经用上了 tks




| |
s*******
|
|
邮箱：syenging@163.com
|

Signature is customized by Netease Mail Master

在2019年06月18日 15:10，agapple 写道：

Closed #1729.
