### ISSUE TITLE
一个canal监听同名数据库，发到不同kafka集群

### ISSUE THREAD

**Issue by 2973868605** [alibaba/canal#1735]
我有几个数据库，名字一样， 然后想发送到不同的kafka集群，

是不是只能启动多个canal节点，    

一个canal节点能支持这种配置吗？

**Comment by chenxyz707** [comment]
名字一样的几个数据库，应该是不同的数据库实例吧？这样的话canal是支持多个destination的，每个destination里面配置就可以了。可以参考conf目录下的example，example就是一个destination或者称为实例。

**Comment by waterlang** [comment]
@chenxyz707  在destination里面的instance.properties去配置新的kafka么，包括kafka集群地址。但是我配置了没有生效，从源码里面看，他们取的还是最外层的properties啊：String conf = System.getProperty("canal.conf", "classpath:canal.properties");

**Comment by miyazawatomoka** [comment]
<=1.16版本是不支持的，在`CanalStarer`中，已经初始化了`canalMQProducer`，此处创建了KafkaProducer，所以只能支持单kafka集群。
