### ISSUE TITLE
canal v1.1.3 column size is not match for table:user.user_public_info,47 vs 45

### ISSUE THREAD

**Issue by kzw11** [alibaba/canal#1737]
## Question

com.alibaba.otter.canal.parse.exception.CanalParseException: com.alibaba.otter.canal.parse.exception.CanalParseException: parse row data failed.
Caused by: com.alibaba.otter.canal.parse.exception.CanalParseException: parse row data failed.
Caused by: com.alibaba.otter.canal.parse.exception.CanalParseException: column size is not match for table:user.user_public_info,47 vs 45

哪位伙计也遇到过类似问题

**Comment by chenxyz707** [comment]
是否启用了tsdb？

**Comment by kzw11** [comment]
> 是否启用了tsdb？

启用了，这个在配置里默认就启动的呀

**Comment by chenxyz707** [comment]
那可能是tsdb里面存储的`user_public_info`表结构和你现在的表结构不一样。如果没有其他考虑，可以尝试清除tsdb中的这个表的记录这样就会重新拉取表结构。当然需要**慎重**考虑删除表结构是否有业务影响。说实话，在使用中确实发现tsdb是有点bug的:-)。

**Comment by kzw11** [comment]
> 那可能是tsdb里面存储的`user_public_info`表结构和你现在的表结构不一样。如果没有其他考虑，可以尝试清除tsdb中的这个表的记录这样就会重新拉取表结构。当然需要**慎重**考虑删除表结构是否有业务影响。说实话，在使用中确实发现tsdb是有点bug的:-)。

好的，非常感谢

**Comment by agapple** [comment]
tsdb最大的问题就是DDL的sql兼容性不是100% , 我们内部也在努力用更科学的方式来全面回归tsdb

**Comment by gabrywu** [comment]
这个问题有什么根本性的解决方案或者临时的解决方案么？我们也遇到了，是删除 h2.mv.db这个文件，然后重启解决的

**Comment by sunytonyli** [comment]
这个问题还存在，期待官方解决
