### ISSUE TITLE
大家如何解决pt-osc改表导致无法获取DDL问题?

### ISSUE THREAD

**Issue by Fanduzi** [alibaba/canal#1739]
## Question
![image](https://user-images.githubusercontent.com/24428128/56625474-18cd7880-6670-11e9-8f1f-4a8f39251ec2.png)
我们不可能限制业务不使用pt-osc或gh-ost之类的工具.毕竟DDL对业务还是会有影响的. 那么大家如何解决这个问题呢?

**Comment by RedHou** [comment]
自己在下游做兼容
