### ISSUE TITLE
Canal 选用group-instance 模式的话，怎么配置destination name呢？

### ISSUE THREAD

**Issue by Hinsteny** [alibaba/canal#174]
怎么配置逻辑上的把多个instance融合后的总得destination name吗？

**Comment by agapple** [comment]
看一下group-instance.xml配置示例

**Comment by Hinsteny** [comment]
项目给的example中是配置file-instance.xml做的示例，麻烦可以给下group-instance.xml配置示例的地址吗？

**Comment by agapple** [comment]
https://raw.githubusercontent.com/alibaba/canal/master/deployer/src/main/resources/spring/group-instance.xml

**Comment by liutaihua** [comment]
group-instance的destnation name有配置示例吗
