### ISSUE TITLE
支持多客户端消费，目前有计划进行改造吗

### ISSUE THREAD

**Issue by lulu2panpan** [alibaba/canal#1742]
![image](https://user-images.githubusercontent.com/15853650/56645447-4508e980-66b0-11e9-9d14-22134dc83bb0.png)

linkedin的databus是可以支持多客户端订阅消费的，并且是互不影响的。
目前canal有没有计划支持？

**Comment by agapple** [comment]
可以对接到MQ之后进行多客户端订阅模式
