### ISSUE TITLE
多个destination实例客户端订阅问题

### ISSUE THREAD

**Issue by newWSmile** [alibaba/canal#1744]
## Question

线上环境是用的多数据库实例，所以我canal要做多个destination实例，这样客户端订阅的时候如何解决？是只能起多个客户端分别指定具体的destination实例去订阅吗？还是有什么其他解决方法？我看`newSingleConnector(SocketAddress address, String destination, String username,
                                                    String password)`这个方法只能指定一个实例去启东，但是在canal.properties 里面可以指定`canal.destinations = example,example2` 我想的是能不能在客户端也可以有类似这样的一起订阅出来

**Comment by xiaoshikun801** [comment]
解决了么

**Comment by xiaoshikun801** [comment]
解决了吗

**Comment by JonSnow996** [comment]
客户端除了newSingleConnector，还有一个newClusterConnector，支持集群模式。

**Comment by newWSmile** [comment]
> 客户端除了newSingleConnector，还有一个newClusterConnector，支持集群模式。

但是你这样我在数据库那边还是配置不了多个实例啊，这个`newClusterConnector(List<? extends SocketAddress> addresses, String destination,
                                                     String username, String password)`
说到底还是只能支持一个destination ，而且一个destination 只能配一个服务器的数据库实例吧

**Comment by newWSmile** [comment]
> 解决了吗

目前是通过起多个destination 然后这边同时监听多个destination 达到目的

**Comment by lmikoto** [comment]
> > 解决了吗
> 
> 目前是通过起多个destination 然后这边同时监听多个destination 达到目的

如何启多个destination呢。是启多个adapter然后配置不同？
