### ISSUE TITLE
canal binlog dump报Writing to net，之后连接断开

### ISSUE THREAD

**Issue by shengmingzhu** [alibaba/canal#1747]
## Question

在k8s环境里跑canal的docker镜像，连mysql数据库，将数据导入kafka。数据量小时没什么问题，但一次对一个120万行记录的表进行update时，发现canal会死掉。
具体现象：在mysql客户端show PROCESSLIST，发现canal的连接处于Writing to net状态；一段时间后连接断开，不会重连。查看canal的容器，确认java进程还在。
canal的内存配置：buffer.memunit=1024（1024字节？），buffer.size=256。
求大神指导。

**Comment by agapple** [comment]
需要看一下canal对应java进程的运行情况，最好是把prometheus监控给看看

**Comment by mlixytz** [comment]
@shengmingzhu 你好，问题解决了吗？遇到同样的问题了

**Comment by shengmingzhu** [comment]
@mlixytz 你好。不好意思现在才回复。问题已解决。我当时问题是配置的最大事务size > buffer size，导致一个大于buffer size的事务过来时，canal buffer满了出现假死现象。
