### ISSUE TITLE
file-instance.xml配置模式下，设置的table过滤不起作用？

### ISSUE THREAD

**Issue by Hinsteny** [alibaba/canal#175]
1. 在example instance中配置
   `# table regex
   canal.instance.filter.regex = canal\\.ad.*`, debug调试发现变量确实被设置进了instance实例的eventParser.eventFilter里面了
2. 创建client进行数据请求
3. 修改数据库canal下面的advice表，client可以收到对应的message.
4. 修改数据库test下面的advice表，client同样可以收到对应的message.
   注: 两个数据库都是创建在本地的

**Comment by agapple** [comment]
1. 确认设置了row模式
2. filter条件只针对row数据有效，其余的query查询不会进行过滤

**Comment by Hinsteny** [comment]
我在对项目本身的 deployer.CanalLuncher进行debug的过程中，发现一个问题，在启动canal server附属的EventParser服务时，关于table过滤的表达式还是正确的，但是在处理过滤业务的线程中会发现表达式pattern被改变了，下面是我的调试过程，麻烦请看一下

1. 初始EventParser并启动
![qq 20160509143520](https://cloud.githubusercontent.com/assets/5526657/15105668/0aa5d130-15f6-11e6-8007-b427efec5baf.png)
2. 构造Erosa连接之前
![qq 20160509143526](https://cloud.githubusercontent.com/assets/5526657/15105742/ce1a585c-15f6-11e6-8407-a71284ce097c.png)
3. 构造Erosa连接之后
![qq 20160509145114](https://cloud.githubusercontent.com/assets/5526657/15105758/dbd62980-15f6-11e6-8335-25b6dea0f4f2.png)

**Comment by agapple** [comment]
client的subscribe传入的过滤条件优先级最高，会忽略掉服务端的设置

**Comment by alan5959249** [comment]
@agapple 但是我想用服务器端的设置，如果我不写subscribe在程序中就报错，写了就把server端的regex覆盖，这可如何是好啊，我就是想用instance中的内容
