### ISSUE TITLE
canal.mq.dynamicTopic不起作用

### ISSUE THREAD

**Issue by caofb** [alibaba/canal#1751]
docker-compose配置如下
version: '2'

services:
  canal-server:
    image: canal/canal-server:v1.1.3
    environment:
      canal.zkServers: "192.168.0.10:2182"
      canal.destinations: "ggg"
      canal.instance.mysql.slaveId : "1234688"
      canal.instance.master.address : "1"
      canal.instance.dbUsername: "1"
      canal.instance.dbPassword: "1"
      canal.instance.defaultDatabaseName: "test"
      canal.instance.connectionCharset: "UTF-8"
      canal.instance.filter.regex : "test.storeproducts,test.products"
      canal.instance.global.spring.xml : "classpath:spring/default-instance.xml"
      canal.instance.tsdb.enable : "true"
      canal.instance.gtidon : "false"
      canal.serverMode : "kafka"
      canal.mq.servers : "192.168.0.10:9092,192.168.0.11:9092,192.168.0.12:9092"
      canal.mq.retries : "5"
      canal.mq.flatMessage : "true"
      canal.mq.canalBatchSize  : "100"
      canal.mq.canalBatchSize  : "50"
      canal.mq.transaction : "true"
      canal.mq.topic : "fail"
      canal.mq.dynamicTopic : "products:.*\\.products,storeproducts:.*\\.storeproducts"
      canal.mq.partitionsNum: "16"
      canal.mq.partitionHash : ".*\\..*:id"
    ports:
      - "11112:11111"
    restart: unless-stopped
但是一直报如下错误WARN  org.apache.kafka.clients.NetworkClient - [Producer clientId=producer-1, tranansactional-id] Error while fetching metadata with correlation id 78 : {fail=UNKNOWN_TOPIC_OR_PARTITION}
也就是把消息投递到了fail这个topic下，但是我没有建立fail这个topic，问题时为什么没有投递到正确的topic
canal.mq.dynamicTopic我测试了如下配置都不行，都被投递到fail这个topic下
canal.mq.dynamicTopic : "products:test.products,storeproducts:test.storeproducts"
canal.mq.dynamicTopic : "products:test\\.products,storeproducts:test\\.storeproducts"
只有 canal.mq.dynamicTopic: ".*\\..*"  这个生效，但是topic的加了数据库名，我希望只是用表名作为topic

**Comment by BigData-YC** [comment]
楼主找到答案了吗？我也是这样想的，在分库分表的情况下希望不同的库相同的表的数据，发送到同一个topic里面，但是官网给出的都是加上了库的名字。。。。求答案
