### ISSUE TITLE
单表映射，修改表的数据不会同步更新么，只支持增加么

### ISSUE THREAD

**Issue by hecyxy** [alibaba/canal#1754]
es映射配置：
dataSourceKey: defaultDS
destination: instanceB
groupId:
esMapping:
  _index: testorder
  _type: default
  _id: _id
  pk: id
  sql: "select a.id as _id, a.id ,a.title from project  a"
  etlCondition: ""
  commitBatch: 3000

当更新这个表的数据，日志打印如下，但是不会更新ES。
2019-04-25 15:57:11.974 [pool-2-thread-1] DEBUG c.a.otter.canal.client.adapter.es.service.ESSyncService - DML: {"data":[{"title":"水杯123456","updated_at":1556179029000}],"database":"dev","destination":"instanceB","es":1556179029000,"groupId":null,"isDdl":false,"old":null,"pkNames":[],"sql":"","table":"project","ts":1556179031841,"type":"UPDATE"} 
Affected indexes: testorder

**Comment by aa138002441** [comment]
我的也是这样  完全不知道为什么

**Comment by rewerma** [comment]
要也配置pk！！！

**Comment by aa138002441** [comment]
@rewerma  能帮忙看下么  我的没有配置PK 也是这样的现象  
![image](https://user-images.githubusercontent.com/22810287/56786145-74dbfc80-682a-11e9-88bc-ab9e30a68219.png)

**Comment by rewerma** [comment]
最好别用大写

**Comment by hecyxy** [comment]
> 不要配置pk！！！

不配pk也测了，也无法更新

**Comment by aa138002441** [comment]
@rewerma  应该不是大小写的问题 大写有另外个问题 取别名会导致ES识别不了不取别名就没事儿    这个更新我另一个环境是可以的  但是换了个环境就不行了 实在对比不出来有任何差异

**Comment by aa138002441** [comment]
![image](https://user-images.githubusercontent.com/22810287/56786501-c9cc4280-682b-11e9-9731-994b0d9761a5.png)
trace日志

**Comment by aa138002441** [comment]
@rewerma   能看下么  还是不能更新

**Comment by wedog** [comment]
https://blog.csdn.net/actiontech/article/details/81701362

**Comment by wedog** [comment]
腾讯云mysql5.7的binlog_row_image默认是MINIMAL，其实默认应该是FULL。否则更新时，canal的message无法获取更新前的内容，导致无法更新。ps：腾讯云mysql改了必须重启（它提示不重启），客户端show variables能很好检查出来配置是否生效。
