### ISSUE TITLE
ESAdapter:152行调用commit后 是否忘记重新resetBulkRequestBuilder ？

### ISSUE THREAD

**Issue by FancyKong** [alibaba/canal#1761]
## Question

每次如果是一条一条修改，每次都会执行一次 commit，并且会把之前留在 bulk 中的记录重新拿出来执行，假如顺序执行当然不会有问题，顶多耗费一些带宽和性能。但是如果es 对bulk内的request 是并行处理的，那不是会造成数据不一致？？？
为什么不在commit的时候 resetBulkRequestBuilder  呢？是有什么设计意图吗？

**Comment by FancyKong** [comment]
/**
     * 提交批次
     */
    public void commit() {
        esTemplate.commit();
        esTemplate.resetBulkRequestBuilder();
    }

**Comment by agapple** [comment]
@rewerma
