### ISSUE TITLE
JSON类型"null"值bug

### ISSUE THREAD

**Issue by oscar-zyh** [alibaba/canal#1762]
- [x] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment

* canal version 1.1.3
* mysql version 5.7

### Issue Description
canal 把 json 类型字段的 "null" 值转换成了 "NULL" 值，再往 mysql 插入这个字段会报错，json "NULL" 无法解析

[MySQL](https://dev.mysql.com/doc/refman/8.0/en/json.html) 遵循 [RFC 7159](https://tools.ietf.org/html/rfc7159) 规范使用 JSON
规范里面表明 JSON 的几个 literal 类型必须是小写：

> 3.  Values
   A JSON value MUST be an object, array, number, or string, or one of
   the following three literal names:
      false null true
   The literal names MUST be lowercase.  No other literal names are
   allowed.
      value = false / null / true / object / array / number / string

所以 MySQL 的 json 字段合法值要么是字符串 "null"，要么是空值 null/NULL，而字符串 "NULL" 不合法

canal 代码在：https://github.com/alibaba/canal/blob/master/dbsync/src/main/java/com/taobao/tddl/dbsync/binlog/JsonConversion.java
```
case LITERAL_NULL:
    buf.append("NULL");
    break
```
不知道这里的考虑是怎样的，能否改回 "null" ？

### Steps to reproduce
create table t (data json);
insert into t values ('null');
insert into t values ('NULL');
insert into t values (NULL);

If there is an exception, please attach the exception trace:

```
mysql> insert into t values ('NULL');
ERROR 3140 (22032): Invalid JSON text: "Invalid value." at position 0 in value for column 't.data'.
```

**Comment by agapple** [comment]
应属于边界值问题, 可以考虑提交一个MR给我

**Comment by sheiy** [comment]
啥时候合并？遇到了同样的问题

**Comment by agapple** [comment]
https://github.com/alibaba/canal/pull/1959
