### ISSUE TITLE
canal的batchsize设置多大合适？

### ISSUE THREAD

**Issue by jianghaibolxy** [alibaba/canal#1764]
## Question

canal1.1.0版本
有时候我们client无缘无故出现client qps 为0的情况，很久不恢复，客户端和服务端都不报错。是不是batch size设置太少的原因啊。此时只有重启客户端和服务端才能恢复。

**Comment by shengmingzhu** [comment]
是不是执行了一个超大的事务之后（可能超出了Canal的缓存）就会出现？我遇到的情况是在k8s配置canal的缓存1024*1024，然后执行一条update全表的语句，行数120万行。之后Canal就不再同步数据了，没有错误日志，java进程也在正常跑。查看mysql连接，发现Canal的连接状态为wait to net writting，一段时间后连接就断开了

**Comment by agapple** [comment]
得看一下链接断开的具体异常，初步怀疑和超大binlog事件有关，找个时间我再测试一下120w的更新

**Comment by zhouluoyang0406** [comment]
@shengmingzhu 你好 你的k8s 是怎么注入环境变量的？

**Comment by zhouluoyang0406** [comment]
canal.port 这些怎么注入

**Comment by shengmingzhu** [comment]
@jianghaibolxy @agapple 经验证，transaction.size(超过这个size的事务拆分处理)不能大于缓存memory.buffer.size。否则当有一个事务真的超过transaction.size时，会因为缓存不足但又没达到拆分size，导致canal停止工作。这里canal应该可以优化下，当用户配置错时，应保证transaction.size不大于memory.buffer.size。
这个是我现在生产用的配置：
```
canal.instance.memory.buffer.size = 256 # 这个配置的缓存占用内存1G左右，适合K8S调度
canal.instance.transaction.size =  64
```

**Comment by shengmingzhu** [comment]
@zhouluoyang0406 我没理解你的问题。我用的是官方的docker镜像作为基础层，然后重新打包镜像将官方的配置文件覆盖掉，启动参数和环境变量都没动，由官方的几个sh文件处理。dockerfile文件主要操作如下：
```
RUN rm -rf /home/admin/canal-server/conf/example
COPY canal.properties /home/admin/canal-server/conf/
#COPY logback.xml /home/admin/canal-server/conf/
COPY ./auraptDataproductCache/ /home/admin/canal-server/conf/auraptDataproductCache/
COPY ./aurayouDataproductCache/ /home/admin/canal-server/conf/aurayouDataproductCache/
```

你上面提到的canal.port是指怎么把pod(容器)的端口暴露出去吗？canal.port配置在canal.properties文件内，监听容器的端口。你需要做的就是根据需要创建k8s的deploy、svc、ingress的yaml文件，将端口映射到服务及宿主机nodeport，这些是k8s的基本操作。
