### ISSUE TITLE
canal.adapter下面的配置如下，请问一下如果mode:kafka，也要配置 canal地址吗：canalServerHost: 127.0.0.1:11111 ，因为数据同步流程是这样的 canal -- >kafka-->hbase ,如果mode:kafka，那就没必要设置  canalServerHost: 127.0.0.1:11111了吧

### ISSUE THREAD

**Issue by Bruce2jiang** [alibaba/canal#1766]
canal.adapter下面的配置如下，请问一下如果mode:kafka，也要配置 canal地址吗：canalServerHost: 127.0.0.1:11111 ，因为数据同步流程是这样的
canal -- >kafka-->hbase ,如果mode:kafka，那就没必要设置  canalServerHost: 127.0.0.1:11111了吧

ps :

canal.conf:
  canalServerHost: 127.0.0.1:11111
  batchSize: 500
  syncBatchSize: 1000
  retries: 0
  timeout:
  mode: tcp # kafka rocketMQ

**Comment by agapple** [comment]
如果是MQ模式，只需要填写mqServers即可
