### ISSUE TITLE
请问，没有订阅的表被解析到DDL 并且报错，是怎么回事？

### ISSUE THREAD

**Issue by sherlock111** [alibaba/canal#1773]
## Question

canal版本1.1.1

报了一个错：

2019-04-28 10:20:41.802 [[scheduler-table-meta-snapshot]] ERROR c.a.o.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta - pls submit github issue, show create table ddl:CREATE TABLE `certification_program_member__c` ( 
  .......太长，都是表的定义，此处被我省略
 `Id` varchar(50) NOT NULL,
  `RecordType` varchar(100) DEFAULT NULL,
  `Account__c` varchar(50) DEFAULT NULL,
  `Number_of_Salers__c` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`Id`),
  KEY `idx_Account__c` (`Account__c`) USING BTREE,
  KEY `INDEX_Rep_Office__c` (`Rep_Office__c`),
  KEY `INDEX_Partner_Type__c` (`Partner_Type__c`),
  KEY `INDEX_Partner_Sub_Type__c` (`Partner_Sub_Type__c`),
  KEY `INDEX_Partner_CSP_level__c` (`Partner_CSP_level__c`),
  KEY `INDEX_Certification_Program__c` (`Certification_Program__c`) USING BTREE,
  KEY `idx_lastmodifidDate` (`LastModifiedDate`) USING BTREE,
  FULLTEXT KEY `INDEX_Certification_Country__c` (`Certification_Country__c`),
  FULLTEXT KEY `INDEX_CNBG_Acount_Number__c` (`CNBG_Account_Number__c`),
  FULLTEXT KEY `INDEX_Current_Handler__c` (`Current_Handler__c`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 , compare failed . 
 db : TableMeta [schema=cpribcm, table=certification_program_member__c, fileds=
	FieldMeta [columnName=Grace_Period__c, columnType=text, nullable=true, key=false, defaultValue=null, extra=null, unique=false]
	FieldMeta [columnName=Apply_Certification_Type_CN__c, columnType=text, nullable=true, key=false, defaultValue=null, extra=null, unique=false]
	FieldMeta [columnName=Apply_Certification_Type_EN__c, columnType=text, nullable=true, key=false, defaultValue=null, extra=null, unique=false]
	FieldMeta [columnName=Customer_Display_Code__c, columnType=text, nullable=true, key=false, defaultValue=null, extra=null, unique=false]
	FieldMeta [columnName=External_ID__c, columnType=text, nullable=true, key=false, defaultValue=null, extra=null, unique=false]
	FieldMeta [columnName=ID_18__c, columnType=text, nullable=true, key=false, defaultValue=null, extra=null, unique=false]
	FieldMeta [columnName=Is_Authorized_Country__c, columnType=text, nullable=true, key=false, defaultValue=null, extra=null, unique=false]
 .......太长，都是表的定义，此处被我省略

mem : TableMeta [schema=cpribcm, table=certification_program_member__c, fileds=
 .......太长，都是表的定义，此处被我省略

大意就是说： db的表结构和mem缓存中的不一样。

【情况说明】分析过，确实是 在任务执行过程中，修改过表，但是问题是，我没有订阅这张表.....我订阅的是其他表，为啥也会拉取到这张表结构呢？？

另外，请问大大，一定需要每次都对比db中的表结构和men中的表结构吗？可以问问为啥波？请问可以关闭吗？

**Comment by chenxyz707** [comment]
可以参考[ISSUE-1737](https://github.com/alibaba/canal/issues/1737)

**Comment by agapple** [comment]
早期canal的TSDB不支持fulltext的关键字解析，1.1.4最新版本已解决，可升级验证
