### ISSUE TITLE
使用canal-adapter做mysql-es增量同步之前，全量同步需要用什么工具？

### ISSUE THREAD

**Issue by wajika** [alibaba/canal#1778]
## Question

我先用logstash导入后，产生的mapping和canal产生的不同，启动adapter后，等了半天es里就是没有数据新增。 我不太确定一定是mapping的问题，不知道你们是如何做的？

**Comment by mrvon2015** [comment]
同求，全量同步初始化，使用什么工具。如果canal可以提供这种工具就好了

**Comment by purevirtual** [comment]
mysqldump即可 或者 直接用这个 https://github.com/siddontang/go-mysql-elasticsearch

**Comment by wajika** [comment]
> mysqldump即可 或者 直接用这个 https://github.com/siddontang/go-mysql-elasticsearch

mysqldump怎么导入到es？

**Comment by purevirtual** [comment]
https://github.com/siddontang/go-mysql-elasticsearch 这个工具直接可以用

**Comment by JunRzz** [comment]
mapping手动建，直接用adapter 全量etl

**Comment by wajika** [comment]
> mapping手动建，直接用adapter 全量etl

adapter全量怎么设置？

**Comment by JunRzz** [comment]
> > mapping手动建，直接用adapter 全量etl
> 
> adapter全量怎么设置？

文档里面有介绍的 https://github.com/alibaba/canal/wiki/ClientAdapter
直接
curl http://127.0.0.1:8081/etl/es/mytest_person2.yml -X POST

**Comment by wajika** [comment]
> > > mapping手动建，直接用adapter 全量etl
> > 
> > 
> > adapter全量怎么设置？
> 
> 文档里面有介绍的 https://github.com/alibaba/canal/wiki/ClientAdapter
> 直接
> curl http://127.0.0.1:8081/etl/es/mytest_person2.yml -X POST

canal全量读取是怎么实现的？

**Comment by wajika** [comment]
> > > mapping手动建，直接用adapter 全量etl
> > 
> > 
> > adapter全量怎么设置？
> 
> 文档里面有介绍的 https://github.com/alibaba/canal/wiki/ClientAdapter
> 直接
> curl http://127.0.0.1:8081/etl/es/mytest_person2.yml -X POST

```
[root@localhost adapter_kafka]# curl http://localhost:8081/etl/es/mytest.yml -X POST
{"timestamp":"2019-05-14 14:31:52","status":500,"error":"Internal Server Error","message":"No message available","path":"/etl/es/mytest.yml"}
```

执行之后报错了，我之前用过另一条命令，感觉es模块不支持这种查询
`curl http://127.0.0.1:8081/count/hbase/mytest_person2.yml`

**Comment by JunRzz** [comment]
> > > > mapping手动建，直接用adapter 全量etl
> > > 
> > > 
> > > adapter全量怎么设置？
> > 
> > 
> > 文档里面有介绍的 https://github.com/alibaba/canal/wiki/ClientAdapter
> > 直接
> > curl http://127.0.0.1:8081/etl/es/mytest_person2.yml -X POST
> 
> ```
> [root@localhost adapter_kafka]# curl http://localhost:8081/etl/es/mytest.yml -X POST
> {"timestamp":"2019-05-14 14:31:52","status":500,"error":"Internal Server Error","message":"No message available","path":"/etl/es/mytest.yml"}
> ```
> 
> 执行之后报错了，我之前用过另一条命令，感觉es模块不支持这种查询
> `curl http://127.0.0.1:8081/count/hbase/mytest_person2.yml`

就是从头读取binlog，用transportClient插入更新，建议你看下ESEtlService的代码就知道了，你这个应该是哪里配置有问题吧。。。

**Comment by wajika** [comment]
> > > > > mapping手动建，直接用adapter 全量etl
> > > > 
> > > > 
> > > > adapter全量怎么设置？
> > > 
> > > 
> > > 文档里面有介绍的 https://github.com/alibaba/canal/wiki/ClientAdapter
> > > 直接
> > > curl http://127.0.0.1:8081/etl/es/mytest_person2.yml -X POST
> > 
> > 
> > ```
> > [root@localhost adapter_kafka]# curl http://localhost:8081/etl/es/mytest.yml -X POST
> > {"timestamp":"2019-05-14 14:31:52","status":500,"error":"Internal Server Error","message":"No message available","path":"/etl/es/mytest.yml"}
> > ```
> > 
> > 
> > 执行之后报错了，我之前用过另一条命令，感觉es模块不支持这种查询
> > `curl http://127.0.0.1:8081/count/hbase/mytest_person2.yml`
> 
> 就是从头读取binlog，用transportClient插入更新，建议你看下ESEtlService的代码就知道了，你这个应该是哪里配置有问题吧。。。

如果是从头读取不还是获取的增量的部分吗？ 我不会java所以一直解决不掉，是adapter的配置有问题？

**Comment by wajika** [comment]
> > > > > mapping手动建，直接用adapter 全量etl
> > > > 
> > > > 
> > > > adapter全量怎么设置？
> > > 
> > > 
> > > 文档里面有介绍的 https://github.com/alibaba/canal/wiki/ClientAdapter
> > > 直接
> > > curl http://127.0.0.1:8081/etl/es/mytest_person2.yml -X POST
> > 
> > 
> > ```
> > [root@localhost adapter_kafka]# curl http://localhost:8081/etl/es/mytest.yml -X POST
> > {"timestamp":"2019-05-14 14:31:52","status":500,"error":"Internal Server Error","message":"No message available","path":"/etl/es/mytest.yml"}
> > ```
> > 
> > 
> > 执行之后报错了，我之前用过另一条命令，感觉es模块不支持这种查询
> > `curl http://127.0.0.1:8081/count/hbase/mytest_person2.yml`
> 
> 就是从头读取binlog，用transportClient插入更新，建议你看下ESEtlService的代码就知道了，你这个应该是哪里配置有问题吧。。。

请问你的配置可以给我看看嘛

**Comment by swq-github** [comment]
https://www.clougence.com。这个工具可以支持可是话编辑

**Comment by wajika** [comment]
> [https://www.clougence.com。这个工具可以支持可是话编辑](https://www.clougence.com%E3%80%82%E8%BF%99%E4%B8%AA%E5%B7%A5%E5%85%B7%E5%8F%AF%E4%BB%A5%E6%94%AF%E6%8C%81%E5%8F%AF%E6%98%AF%E8%AF%9D%E7%BC%96%E8%BE%91)

谢谢分享
