### ISSUE TITLE
关于持久化到文件或ZK的时间间隔问题

### ISSUE THREAD

**Issue by matrixtk** [alibaba/canal#178]
我这边测试，发现如果将canal.zookeeper.flush.period或者canal.file.flush.period这两个时间间隔设久一点，由于Client的cursor信息还在内存中没有持久化到文件或者ZK，那么重启Canal或者HA切换至另一个节点会收到重复数据。我想问的是，直连Canal，是否客户端要自己做消息去重的逻辑？我目前想到的是根据binlog的position？

**Comment by agapple** [comment]
是的，会有重复，去重的思路基本正确
