### ISSUE TITLE
canal-adapter支持高可用吗，如果支持请问如何配置？

### ISSUE THREAD

**Issue by jinguangyu** [alibaba/canal#1782]

**Comment by civilian95** [comment]
把它当做canal-client就可以了，集成的是搭配zookeeper

**Comment by jinguangyu** [comment]
> 把它当做canal-client就可以了，集成的是搭配zookeeper
我现在是用canal0和canal1两台机器做了canal-server的HA，如果要做canal-adapter的HA是需要把canal-adapter分别部署到这两台机器上，配置一模一样吗？canal.conf->zookeeperHosts: xxx.xxx.xxx.xxx:2181

**Comment by civilian95** [comment]
如果你用了一个zookeeper的话，配置一样的就可以了。如果多个就逗号隔开




------------------ 原始邮件 ------------------
发件人: "靳光宇"<notifications@github.com>;
发送时间: 2019年5月9日(星期四) 下午5:28
收件人: "alibaba/canal"<canal@noreply.github.com>;
抄送: "."<550481584@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [alibaba/canal] canal-adapter支持高可用吗，如果支持请问如何配置？ (#1782)



 
把它当做canal-client就可以了，集成的是搭配zookeeper
 我现在是用canal0和canal1两台机器做了canal-server的HA，如果要做canal-adapter的HA是需要把canal-adapter分别部署到这两台机器上，配置一模一样吗？canal.conf->zookeeperHosts: xxx.xxx.xxx.xxx:2181

**Comment by jinguangyu** [comment]
> 如果你用了一个zookeeper的话，配置一样的就可以了。如果多个就逗号隔开

谢谢，成功了！

**Comment by PostgreSQL1989** [comment]
> 如果你用了一个zookeeper的话，配置一样的就可以了。如果多个就逗号隔开

我遇到了非常奇怪的情况。

1. canal server使用单节点的zookeeper，adapter也使用单节点的zookeeper，可以从zookeeper获取binlog和postion信息，进行数据解析，zookeeper里面有cursor保存binlog和position。
canal.properties`zookeeperHosts: zookeeper.xxxx.com:2181`
application.yml `canal.zkServers = zookeeper.xxxx.com:2181`

3. canal server使用了集群模式的zookeeper，adapter直接请求canal server，可以解析数据，zookeeper里面有cursor保存binlog和position。
canal.properties `canal.zkServers = zookeeper01.xxxx.com:2181,zookeeper02.xxxx.com:2181,zookeeper03.xxxx.com:2181`
application.yml `  canalServerHost: 127.0.0.1:11111`

4. canal server使用了集群模式的zookeeper，adapter也使用集群模式的zookeeper，无法解析数据，并且zookeeper里面也没有cursor。
canal.properties `canal.zkServers = zookeeper01.xxxx.com:2181,zookeeper02.xxxx.com:2181,zookeeper03.xxxx.com:2181`
application.yml `   zookeeperHosts: zookeeper01.xxxx.com:2181,zookeeper02.xxxx.com:2181,zookeeper03.xxxx.com:2181`

我看了server和adapter的日志，没有任何报错信息。
