### ISSUE TITLE
1.1.3可以使用阿里云的mq（RocketMQ）吗？

### ISSUE THREAD

**Issue by robustwang** [alibaba/canal#1789]
1.1.3可以使用阿里云的mq（RocketMQ）吗？
另想问下，canal.properties 里的canal.mq.servers 应该填哪个地址？

**Comment by chenxyz707** [comment]
可以。`canal.properties`使用rocketMQ中为nameserver列表
请参考[Canal Kafka RocketMQ QuickStart](https://github.com/alibaba/canal/wiki/Canal-Kafka-RocketMQ-QuickStart)
