### ISSUE TITLE
canal1.1.2 with MariaDB 10.1.9

### ISSUE THREAD

**Issue by BreatherLeiYu** [alibaba/canal#1791]
## Question

![image](https://user-images.githubusercontent.com/40288715/57365631-0565f580-71b8-11e9-965e-680c6c4d2045.png)

> caused by 

> java.io.IOException: Received error packet: errno = 1047, sqlstate = 08S01 errmsg = Unknown command

canal1.1.2 同步 mariaDB10.1.x 日志出现上述错误，请问mariaDB获取gtid需要额外的配置吗？
MySQL5.6 MySQL5.7 均能正确fetch binlog

**Comment by agapple** [comment]
这个gtid的支持，网上查询一下吧，估计和mysql版本有关
