### ISSUE TITLE
发现adapter在同步到hbase时，在服务运行的情况下往conf/hbase目录下添加一个新的yml文件，不会自动开始同步这个新表

### ISSUE THREAD

**Issue by jinguangyu** [alibaba/canal#1797]
只是在日志中会打印一行Add了一个新的yml，但并不会随着mysql的变动而开始同步，除非修改了application.yml中的outerAdapters，比如把- name: logger的注释打开，这时日志显示刷新了配置，才开始同步新加的hbase/yml，此时将- name: logger再注释掉，日志显示adapter服务竟然重启了，由于做了adapter的HA，服务自动切换到了另一台机器，可另一台机器还没有添加yml文件，所以
也不会同步这张新表

**Comment by soocold** [comment]
修改原有的yml文件也没有生效

**Comment by rewerma** [comment]
修改配置文件会导致springboot refresh config或者重启application，如果是HA模式下需要注意，可以采用mysql存储配置来统一配置
