### ISSUE TITLE
2019 Alibaba Summer of Code/2019 阿里巴巴编程之夏

### ISSUE THREAD

**Issue by agapple** [alibaba/canal#1800]
# 2019 Alibaba Summer of Code
----
Welcome to the open source world! If you haven't planned how to spend this summer, come to the Alibaba Summer of Code and coding with us! 💻

Alibaba Summer of Code is a global program focused on engaging students directly into open source software development. Under the guidance of the mentor in the Alibaba open source project, students experience software development in the real world. Alibaba Summer of code will begin between June 28th and September 20th. Students can use the summertime to participate in the open source project and work with the core members of the project.

# What you can get?
----
On this exclusive developer journey, students will have the opportunity to:

Participate in the top projects of the International Open Source Foundation;
* Get a scholarship from Alibaba;
* Obtain an open source contributor certificate;
* Get a fast pass of Alibaba Internship/recruitment;
* Get your code adopted and used by the open source project！

# Our Mentor
----
KaimingWan
GitHub ID: KaimingWan
Alibaba Cloud Engineer

agapple
GitHub ID: agapple
Alibaba Cloud Engineer

# Apply Now!
----
You can click on this link to apply directly:  https://github.com/alibaba/canal/labels/type%2FSoC2019

full list of Alibaba Summer of Code Projects：https://developer.aliyun.com/summerofcode2019

# Timeline⏳
<p><a target="_blank" rel="noopener noreferrer" href="https://user-images.githubusercontent.com/4089452/57369720-dc962e00-71c0-11e9-9bc3-61cfa8c545b4.png"><img src="https://user-images.githubusercontent.com/4089452/57369720-dc962e00-71c0-11e9-9bc3-61cfa8c545b4.png" alt="图片22" style="max-width:100%;"></a></p>

# Contact us!
Email Address: aliopensource@alibabacloud.com

**Comment by jyizheng** [comment]
I just got to know this project. Is it too late for me to apply?
