### ISSUE TITLE
cancel不能支持azure for MySQL 订阅服务的database吗？

### ISSUE THREAD

**Issue by mrszhangmmd** [alibaba/canal#1803]
## Question
我们在微软云上订阅了 arzue mysql 服务，但是cancel无法定位到binglog,并报错cannot connect to mysql 。和https://github.com/alibaba/canal/issues/1477遇到的问题一致

**Comment by agapple** [comment]
最新的1.1.3，解决过azure mysql的登录问题

**Comment by bai020** [comment]
> 最新的1.1.3，解决过azure mysql的登录问题

但是我使用还是报错，问题和以前一样
