### ISSUE TITLE
hbase 和es 都有这个配置dataSourceKey: defaultDS，我的疑问是：hbase和es 是从canal 的instance或者kafka的topic中取数据，为什么要链接数据库

### ISSUE THREAD

**Issue by Bruce2jiang** [alibaba/canal#1804]
hbase 和es 都有这个配置dataSourceKey: defaultDS，我的疑问是：hbase和es 是从canal 的instance或者kafka的topic中取数据，为什么要链接数据库

**Comment by wajika** [comment]
dataSourceKey 这个可以注释掉，具体什么用 我也不知道

**Comment by zk279444107** [comment]
某些情况下是需要反查数据的

**Comment by yangyiweigege** [comment]
源码部分大致逻辑是这样 如果是简单的单表操作之类的。会直接用binLog解析 但如果是复杂的sql 连表之类的 会根据你配置的datasourceKey 反查。。。但这里我又发现一个BUG。。。datasourceKey必须和 订阅的库 要一致  不然消费不了 ....
