### ISSUE TITLE
对数据库高频度变化，对 canal 的消息堆积存在疑虑。群里有小伙伴遇到过，canal 消息堆积以后效率急剧下降，然后处理特别慢的情况

### ISSUE THREAD

**Issue by Bruce2jiang** [alibaba/canal#1805]
群主你好，
对数据库高频度变化，对 canal 的消息堆积存在疑虑。群里有小伙伴遇到过，canal 消息堆积以后效率急剧下降，然后处理特别慢的情况
这个问题有解决吗，我用1.1.2遇到过这样的问题，以前用otter也遇到这样问题，一旦堆积，处理的很慢

**Comment by JunRzz** [comment]
> 群主你好，
> 对数据库高频度变化，对 canal 的消息堆积存在疑虑。群里有小伙伴遇到过，canal 消息堆积以后效率急剧下降，然后处理特别慢的情况
> 这个问题有解决吗，我用1.1.2遇到过这样的问题，以前用otter也遇到这样问题，一旦堆积，处理的很慢

我也遇到了这个问题，lz有解决方案了吗

**Comment by Bruce2jiang** [comment]
没有

**Comment by cun123** [comment]
LZ有解决方案了吗？一个canal部署的实例较多是不是也会导致延时较大呢？

**Comment by agapple** [comment]
从我之前的benchmark测试来看，都是基于历史堆积消息的方式来不停的验证，从单纯的canal parse来看不存在这个消费过慢的问题.  

可以考虑配置一下canal promethues来观察一下瓶颈点在哪个环境，比如binlog fetch or parser or client ？
