### ISSUE TITLE
Client连接问题

### ISSUE THREAD

**Issue by BrightMi** [alibaba/canal#181]
SimpleCanalConnector.java
doConnect()方法调用的readNextPacket()
int bodyLen = readHeader.getInt(0);
bodyLen 的值1308622848
这个数怎么读出这么大。然后就内存溢出了

**Comment by agapple** [comment]
这应该是异常数据流

**Comment by agapple** [comment]
建议先增加客户端重试或者HA机制保证，如有新的信息再reopen issue
