### ISSUE TITLE
版本1.1.3，阿里云RDS没有SHOW权限导致报错

### ISSUE THREAD

**Issue by deadwind4** [alibaba/canal#1811]
报错内容如下，但是阿里云RDS无法给账号SHOW权限，怎么办呢？
SHOW command denied to user

**Comment by zuonidelaowang** [comment]
解决了吗 我也遇到这个问题

**Comment by zuonidelaowang** [comment]
看到别人给的解决办法
canal.instance.filter.black.regex=mysql\..*
把不需要订阅的库, 加入黑名单, 这样就不会报错了

**Comment by agapple** [comment]
LS正解

**Comment by deadwind4** [comment]
谢谢你们
