### ISSUE TITLE
官方qq交流群已满能否新建微信群

### ISSUE THREAD

**Issue by arthas-171** [alibaba/canal#1813]
## Question

官方qq交流群已满能否新建微信群

**Comment by Mrshengjie** [comment]
是的添加个新群吧。。

**Comment by arthas-171** [comment]
我自己建了一个群 有需求的小伙伴们加一下吧 397070972

**Comment by cdmalcl** [comment]
![canal](https://user-images.githubusercontent.com/8749073/59034698-32ccbe80-889e-11e9-9610-0f2e26b98657.jpg)
弄了一个 平时好互相研究

**Comment by agapple** [comment]
群主的QQ号即为微信号
