### ISSUE TITLE
写入kafka的数据没有binlog的文件、position信息

### ISSUE THREAD

**Issue by gabrywu** [alibaba/canal#1815]
## Question
官方自带的CanalKafkaProducer写入kafka时，没有当前消息所属的binlog文件名和position信息，是否可以添加这些信息？

**Comment by Fanduzi** [comment]
支持, 麻烦把GTID也加上谢谢🙏🙏🙏 @agapple @rewerma

**Comment by gabrywu** [comment]
另外写入kafka的消息，key也不要为空，把表的主键信息放到key吧。因为有时候需要利用到kafka的compact功能的，节约空间啊。其实主键相同的数据更新，只需要保留最后一条就行了，没必要所有的都存起来。

**Comment by agapple** [comment]
可以考虑提交一个PR给我
