### ISSUE TITLE
Canal投递MQ能否控制字段

### ISSUE THREAD

**Issue by cjk87927** [alibaba/canal#1818]
canal版本: v1.1.3
MQ: RocketMQ 4.2
新闻表的内容字段没有投递到MQ,能否控制该字段不进行投递,否则会导致报错
```
org.apache.rocketmq.client.exception.MQClientException: CODE: 13  DESC: the message body size over max value, MAX: 4194304
```

PS:
canal.mq.retries 配置为1,但还是会失败一直投递,导致卡住

**Comment by Bruce2jiang** [comment]
你好这个问题解决了吗

**Comment by cjk87927** [comment]
没有

**Comment by agapple** [comment]
发送的MQ消息超过了body限制，4194304

可以考虑：
1. 调大MQ的body大小限制
2. 调小canal发送MQ的批次大小，如果单条binlog记录都超过body限制，那就没招了
