### ISSUE TITLE
对opensearch的支持

### ISSUE THREAD

**Issue by qiqizjl** [alibaba/canal#1819]
## Why you need it?
阿里云的opensearch其实是支持从RDS同步数据到Opensearch。但是非常尴尬的是,目前我们有些MySQL实例是在ECS中,自维护。暂时也没计划迁移至RDS。所以暂时无法使用OpenSearch/RDS同步的功能。看到了canal这个项目是有对ES支持的。请问后续有计划对OpenSeach支持么

## How it could be?
非RDS的MySQL实例，需要同步到opensearch。增量全量

**Comment by agapple** [comment]
canal支持自建MySQL同步到ES，如果同步到opensearch需要基于订阅方式二次开发了

**Comment by qiqizjl** [comment]
所以目前还没计划接入opensearch？
