### ISSUE TITLE
Sync RDB 是否支持手动ETL功能

### ISSUE THREAD

**Issue by mjevon** [alibaba/canal#1821]
我理解的是用它来进行全量同步
> 执行 curl http://127.0.0.1:8081/etl/rdb/mytest_user.yml -X POST

执行后报错

> {"timestamp":"2019-05-20 09:49:39","status":500,"error":"Internal Server Error","message":"No message available","path":"/count/rdb/mytest_user.yml"}

不清楚是否支持全量同步，求大佬指教

**Comment by rewerma** [comment]
https://github.com/alibaba/canal/wiki/ClientAdapter#324-%E6%89%8B%E5%8A%A8etl
多看wiki
