### ISSUE TITLE
订阅过滤不正确

### ISSUE THREAD

**Issue by sherlock111** [alibaba/canal#1825]
canal版本使用1.1.3

最后出现的订阅是如下：
c.a.o.canal.instance.core.AbstractCanalInstance[AbstractCanalInstance.java:48] | subscribe filter change to ebod_svc\.contact

但是拿到的数据是：
ebod_svc.tpl_huawei_log_events_t

subscribe filter 是通过 ClientIdentity 代码设置的。

请问，能否提供分析该问题的思路？

**Comment by fqybzhangji** [comment]
canal.instance.filter.query.dml = false 修改成 canal.instance.filter.query.dml = true 看看是不是你想要的 FAQ里面有这个
