### ISSUE TITLE
关于canal对于statement 格式日志的解析

### ISSUE THREAD

**Issue by simba-1** [alibaba/canal#183]
请问下canal  有可以解析statement格式日志的方法和类吗？类似对row日志的解析，可以解析出数据库名称，表名，操作类型……而不是一条单纯的sql 语句

**Comment by agapple** [comment]
可以自行依赖sql解析器，对于输出的内容进行解析，得到你想要的结果

**Comment by sun5411** [comment]
![aaa](https://cloud.githubusercontent.com/assets/533322/17732757/f8b3440e-64a5-11e6-8daf-4b4dc96b824c.png)
请问，为什么图中这段，canal会解析为空，但作为一条解析输出了？
