### ISSUE TITLE
binlog处理dml的null值问题

### ISSUE THREAD

**Issue by acuitong** [alibaba/canal#1831]
对于sql中 空串‘ ’，dml中会收到null，所以当字段设置不能为null时，会出现异常

**Comment by acuitong** [comment]
![image](https://user-images.githubusercontent.com/40566190/58160207-99ec4f80-7cb0-11e9-9255-a0e376a26d8a.png)
client获取该参数的值为null

**Comment by agapple** [comment]
复现的sql和表结构提供一下
