### ISSUE TITLE
canal.instance.filter.regex  在什么地方生效

### ISSUE THREAD

**Issue by leiwangouc** [alibaba/canal#1832]

**Comment by leiwangouc** [comment]
我在一台服务器上起了一个 canal 的进程，只接收 mysql 指定表的 binglog 然后发送到 rocketMQ 下面哪个是叙述是正确的呢？ 

1    所有表的 binlog 都发送到了 canal 进程所在的服务器，由 canal 进程负责 做 filter 
2    只是指定表的 binlog 发送到了 canal 进程坐在的服务器， filter 在 mysql server 端就生效了。

**Comment by cun123** [comment]
canal.instance.filter.regex不起作用，LZ有解决吗？

**Comment by agapple** [comment]
1 所有表的 binlog 都发送到了 canal 进程所在的服务器，由 canal 进程负责 做 filter
