### ISSUE TITLE
sync es 现在是不是还不能聚合同步多张表

### ISSUE THREAD

**Issue by poloxue** [alibaba/canal#1833]
sync es 现在是不是还不能聚合同步多张表，我发现join多表的时候，全量可以，但是增量并没有同步过来

**Comment by 1044730317** [comment]
说明文档中不是有多表对一的SQL示例吗？ 在增量同步中可以把2个表的数据同步到一个索引中哦。
我倒是还不知道全量同步是怎么操作的？

**Comment by rewerma** [comment]
当然可以
