### ISSUE TITLE
Canal+kafka,'data': [{...],所有字段均成String类型？

### ISSUE THREAD

**Issue by windtalkerbj** [alibaba/canal#1835]
在kafka上监控CANAL写入的数据，其中data部分，所有字段的值均变成String,如 'RENTAL_INCOME_I1': '0.0', 'RENTAL_INCOME_I2':'0.0', 'RECE_PRINCIPAL': '0'，在MYSQL中均是decimal类型，请问是为什么出现这现象呢？

**Comment by Bruce2jiang** [comment]
我也遇到这个问题了
，请问你是怎么解决的

**Comment by windtalkerbj** [comment]
Canal解析出来的东西里有sqltype，我自己做了to int,float的转换


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: Bruce2jiang <notifications@github.com>
发送时间: 2019年6月12日 17:06
收件人: alibaba/canal <canal@noreply.github.com>
抄送: windtalkerbj <22272889@qq.com>, Author <author@noreply.github.com>
主题: 回复：[alibaba/canal] Canal+kafka,'data': [{...],所有字段均成String类型？ (#1835)




我也遇到这个问题了
 ，请问你是怎么解决的

**Comment by agapple** [comment]
json格式的数据，全部为string类型，需要特殊处理一下blob类型即可

**Comment by jianghanfen** [comment]
> json格式的数据，全部为string类型，需要特殊处理一下blob类型即可

blob 是怎么特殊处理的？
