### ISSUE TITLE
partitionHash设置后，相同key的消息并不能按照分发到相同的partition中

### ISSUE THREAD

**Issue by tigerxn** [alibaba/canal#1836]
canal 版本：1.1.3
mq使用kafka。

配置参数如下：
## Question

# table regex
canal.instance.filter.regex=database\\.xxxxxx_temp_.*

# mq config
canal.mq.topic=xxx-topic
# dynamic topic route by table regex
canal.mq.partition=0
# hash partition config
canal.mq.partitionsNum=10
canal.mq.partitionHash=dbn\\.xxxxxx_temp_.*:address

发现同一个address的数据并不能写入到相同的分区，请帮忙看下。

**Comment by Level1Accelerator** [comment]
我也有这个问题

**Comment by agapple** [comment]
有复现的方式么？比如表结构和测试insert数据
