### ISSUE TITLE
支持kafka使用用户名密码

### ISSUE THREAD

**Issue by Denon** [alibaba/canal#1838]
方法：
1. 在canal.properties下添加两行
```
canal.mq.properties.security.protocol = SASL_PLAINTEXT
canal.mq.properties.sasl.mechanism = PLAIN
```
2. 修改startup.sh/startup.bat文件，在JAVA_OPTS中添加参数
```
-Djava.security.auth.login.config=/path/jaas.conf
```
其中/pah/jaas.con为kafka的认证文件
文件内容应为:
```
KafkaClient {
        org.apache.kafka.common.security.plain.PlainLoginModule required
        username="your_username"
        password="your_password";
};
```

希望能更新到wiki上，thanks

**Comment by agapple** [comment]
可以结合pr：https://github.com/alibaba/canal/pull/1895
调整一下对应的wiki

**Comment by linus-lc** [comment]
> 可以结合pr：#1895
> 调整一下对应的wiki

请问一下，canal目前只能使用Kerberos的认证方式吗？上面用户提到的PLAIN的方式不可以吗？

**Comment by XuYijing2018** [comment]
> PLAIN

同问，上面提到的PLAIN方式，试了，不可以，报下面的错误：

2020-09-28 10:46:50.386 [kafka-producer-network-thread | producer-1] WARN  org.apache.kafka.clients.NetworkClient - [Producer clientId=producer-1] Error while fetching metadata with correlation id 14740 : {T_binlog_air=TOPIC_AUTHORIZATION_FAILED}

**Comment by smallbellpapa** [comment]
> 方法：
> 
> 1. 在canal.properties下添加两行
> 
> ```
> canal.mq.properties.security.protocol = SASL_PLAINTEXT
> canal.mq.properties.sasl.mechanism = PLAIN
> ```
> 
> 1. 修改startup.sh/startup.bat文件，在JAVA_OPTS中添加参数
> 
> ```
> -Djava.security.auth.login.config=/path/jaas.conf
> ```
> 
> 其中/pah/jaas.con为kafka的认证文件
> 文件内容应为:
> 
> ```
> KafkaClient {
>         org.apache.kafka.common.security.plain.PlainLoginModule required
>         username="your_username"
>         password="your_password";
> };
> ```
> 
> 希望能更新到wiki上，thanks





不知道你用的canal的版本是多少，我使用了1.1.5，配置需要进行一些修改
kafka.security.protocol = SASL_PLAINTEXT
kafka.properties.sasl.mechanism = PLAIN

**Comment by zhuwenxiang2** [comment]
PLAIN 认证，认证文件jaas.con也加了，canal.properties 也配置了，但是还是会下面的报错，有人知道是怎么回事吗？？

WARN  org.apache.kafka.clients.NetworkClient - [Producer clientId=producer-1] Connection to node -1 terminated during authentication. This may indicate that authentication failed due to invalid credentials.

**Comment by maxianwei** [comment]
我的kafka和canal不在一台机器上，我在cananl目录下见了jaas.conf, 报如下错误，有人了解嘛
2021-06-23 15:53:15.326 [kafka-producer-network-thread | producer-1] WARN  org.apache.kafka.clients.NetworkClient - [Producer clientId=producer-1] Error while fetching metadata with correlation id 12 : {canal_test_src.test_table=LEADER_NOT_AVAILABLE}

**Comment by XuYijing2018** [comment]
> PLAIN 认证，认证文件jaas.con也加了，canal.properties 也配置了，但是还是会下面的报错，有人知道是怎么回事吗？？
> 
> WARN org.apache.kafka.clients.NetworkClient - [Producer clientId=producer-1] Connection to node -1 terminated during authentication. This may indicate that authentication failed due to invalid credentials.

我用上面的方法是可以的；
下面这个文件你改了吗？
修改startup.sh/startup.bat文件，在JAVA_OPTS中添加参数
-Djava.security.auth.login.config=/path/jaas.conf

**Comment by sgjr** [comment]
canal版本为v1.1.7时，通过添加/pah/jaas.con认证文件的方式无法认证，需要在canal.properties下添加如下参数即可

```
kafka.sasl.mechanism = PLAIN
kafka.security.protocol = SASL_PLAINTEXT
kafka.sasl.jaas.config = org.apache.kafka.common.security.plain.PlainLoginModule required username='your_username' password='your_password';

```
