### ISSUE TITLE
关于canal_adapter rdb 中基于数据源或个性化的同步

### ISSUE THREAD

**Issue by githubkevinyou** [alibaba/canal#1839]
## Why you need it?

关于rbd的同步，目前数据库有几百张表，每个表都要写适配文件非常繁琐，能不能做个类似mysql 自带的主从同步方法，可以同步整个数据源，而个性化的同步才需要配置适配映射文件

**Comment by 1044730317** [comment]
想法很好，你可以开始做了……

**Comment by rewerma** [comment]
指定schema配置mirrorDb: true就可以同步全库
