### ISSUE TITLE
(zookeeper + rds) oss读取binlog失败

### ISSUE THREAD

**Issue by aries010** [alibaba/canal#1841]
canal.zkServers =xxx:2181
canal.zookeeper.flush.period = 1000

instance信息:

canal.instance.master.address=xxxxxxxx.mysql.rds.aliyuncs.com:3306
canal.instance.master.journal.name=
canal.instance.master.position=
canal.instance.master.timestamp=
canal.instance.master.gtid=

canal.instance.rds.accesskey=xxxx
canal.instance.rds.secretkey=xxxxx
canal.instance.rds.instanceId=xxxxxx(实际已填)

oss 信息:
mysql-bin.000582 2019-05-21 21:26:12 2019-05-22 03:26:19

zk节点信息:
get /otter/canal/destinations/example/1001/cursor 
{
    "@type":"com.alibaba.otter.canal.protocol.position.LogPosition",
    "identity":{
        "slaveId":-1,
        "sourceAddress":{
            "address":"xxxxxxxx.mysql.rds.aliyuncs.com",
            "port":3306
        }
    },
    "postion":{
        "gtid":"",
        "included":false,
        "journalName":"mysql-bin.000582",
        "position":383556921,
        "serverId":1458968752,
        "timestamp":1558433625000
    }
}

canal读取binlog提示错误:
Could not find first log file name in binary log index file
详细错误如下图

![image](https://user-images.githubusercontent.com/22288527/58306453-1fe1d500-7e2e-11e9-909c-9cc593543338.png)

**Comment by nothing-do** [comment]
您好，我遇到同样的问题，您是如何解决的呢 ？

**Comment by aries010** [comment]
> 您好，我遇到同样的问题，您是如何解决的呢 ？

当时因为急着要数据,把zk的节点删除掉重启了就正常了,但是之前的变更数据已经丢失(binlog已经被rds删除).
