### ISSUE TITLE
同步 阿里云 Polar 数据库速度好慢

### ISSUE THREAD

**Issue by Tangkysin** [alibaba/canal#1843]
## Question

配置完之后数据是正常的，client 能拿到数据。
但是非常慢，看网络占用是 十几秒 才有 1秒 有 1M/s 的数据传输。
是需要修改什么配置么？docker 启动参数如下
sh run.sh -e canal.auto.scan=false -e canal.destinations=xxx -e canal.instance.master.address=x.x.x.x:3306 -e canal.instance.dbUsername=xxx -e canal.instance.dbPassword=xxx -e canal.instance.connectionCharset=UTF-8 -e canal.instance.tsdb.enable=true -e canal.instance.gtidon=false -e canal.instance.memory.buffer.memunit=10240 -e canal.instance.memory.buffer.size=65536 -e canal.instance.master.timestamp=1558000000000

polar 里面 innodb_flush_log_at_trx_commit 值是 1 ， 并且无法修改

**Comment by agapple** [comment]
建议把promethues监控配置，参考FAQ观察一下瓶颈在哪一环节
