### ISSUE TITLE
canal 怎么过滤表的字段，比如我想剔除表里的某些字段，不发给后面kafka

### ISSUE THREAD

**Issue by Bruce2jiang** [alibaba/canal#1844]
canal 怎么过滤表的字段，比如我想剔除表里的某些字段，不发给后面kafka

**Comment by cjk87927** [comment]
@Bruce2jiang  我也想知道如何解决,我的新闻表没必要把内容发送到MQ
请问你解决这个问题了吗?

**Comment by Bruce2jiang** [comment]
我现在还没找到办法


------------------ 原始邮件 ------------------
发件人: "cjk87927"<notifications@github.com>;
发送时间: 2019年6月10日(星期一) 中午11:30
收件人: "alibaba/canal"<canal@noreply.github.com>;
抄送: "快乐生活"<16010164@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [alibaba/canal] canal 怎么过滤表的字段，比如我想剔除表里的某些字段，不发给后面kafka (#1844)




@Bruce2jiang  我也想知道如何解决,我的新闻表没必要把内容发送到MQ
 请问你解决这个问题了吗?

**Comment by cun123** [comment]
canal.instance.filter.regex过滤表不起作用个，LZ有遇到吗？

**Comment by cjk87927** [comment]
@cun123 
这个配置倒是正常,没有问题,这是我的配置
canal.instance.filter.regex=test\\.t_company,test\\.t_product,test\\.t_company_news

**Comment by cjk87927** [comment]
@Bruce2jiang 
如果使用flatMessage的前提下可以自己改代码来实现过滤
`com.alibaba.otter.canal.common.MQMessageUtils#messageConverter`里进行过滤

**Comment by agapple** [comment]
目前还没有字段级别的过滤能力，如果真有如此特殊的需求，建议暂时单拉分支来维护吧

**Comment by koupeng** [comment]
都有这个需求吧。

**Comment by cjk87927** [comment]
@koupeng
[https://github.com/alibaba/canal/pull/1914](url)
这个已经合并到master,可以实现对字段的过滤
