### ISSUE TITLE
我采用是的spring/default-instance.xml，位点记录在zk，但我在zk只看到binlog一个消费位点信息，但应该有两个，另外一个解析位点 在哪里可以找到 ？

### ISSUE THREAD

**Issue by Bruce2jiang** [alibaba/canal#1846]
[zk: localhost:2181(CONNECTED) 17] get /otter/canal/destinations/example2/1001/cursor               
{"@type":"com.alibaba.otter.canal.protocol.position.LogPosition","identity":{"slaveId":-1,"sourceAddress":{"address":"10.124.18.235","port":3306}},"postion":{"gtid":"","included":false,"journalName":"mysql-bin.000026","position":560566916,"serverId":2353306,"timestamp":1558771237000}}
cZxid = 0x13000f2ecd
ctime = Wed May 22 14:56:36 CST 2019
mZxid = 0x1300165d44
mtime = Sat May 25 16:00:38 CST 2019
pZxid = 0x13000f2ecd
cversion = 0
dataVersion = 49146
aclVersion = 0
ephemeralOwner = 0x0
dataLength = 285
numChildren = 0
[zk: localhost:2181(CONNECTED) 18]

**Comment by Bruce2jiang** [comment]
谁能回答一下

**Comment by 54nidong** [comment]
zk里面本来就是存放1个位点信息的，它是canal解析完放到ZK的位点信息，你说的2个位点是mysql执行完语句产生的起始和结束位点信息，但这个位点信息需要你在二次开发，从CanalEntry中取出来

**Comment by Bruce2jiang** [comment]
CanalEntry  @54nidong 这段代码加在哪里
