### ISSUE TITLE
请问 canal 中如何获取索引相关信息 ？

### ISSUE THREAD

**Issue by jkl0898** [alibaba/canal#1861]
## Question

请问如何获取索引相关的信息。例如：
1. 创建索引时， 获取索引名index_test、索引作用字段 aa、bb。
alter table test add index index_test ( aa, bb );

2. 删除索引时， 如何获取索引名index_test 。
alter table test drop index index_test;

**Comment by agapple** [comment]
可以参考对应fastsql的代码
