### ISSUE TITLE
mysql 外键没有发送kafka

### ISSUE THREAD

**Issue by jkl0898** [alibaba/canal#1862]
- [ ] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment

* canal version 1.1.0
* mysql version 5.7

### Issue Description
mysql 增加外键语句没有发送kafka。
1.外键语句：alter table test add  CONSTRAINT c_name foreign key index_mid(id) REFERENCES cp_test(id);
2.观察canal 日志， 无消息。

### Actual behaviour

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by agapple** [comment]
可以考虑升级1.1.3版本，印象中有修复过DDL的发送问题
