### ISSUE TITLE
有没有直接读取最新binlog的配置

### ISSUE THREAD

**Issue by shizhengchao** [alibaba/canal#1864]
## Question
我现在的问题是：
当我有一个canal server长时间不消费mysql的binlog,  我想启动server时 直接读取mysql的最新binlog接着消费，而不是一直等到canal消费完前面的binlog。类似于kafka的startOflatest设置

**Comment by gaohuia** [comment]
你可以在启动之前清掉缓存的pos...

**Comment by agapple** [comment]
LS正解
