### ISSUE TITLE
canal 哪个参数可以指定kafka副本数量

### ISSUE THREAD

**Issue by Bruce2jiang** [alibaba/canal#1871]
canal 哪个参数可以指定kafka副本数量

如下 ：
canal.mq.servers =10.121.18.13:9092,10.121.18.14:9092,10.121.18.15:9092
canal.mq.retries = 0
canal.mq.batchSize = 16384
canal.mq.maxRequestSize = 1048576
canal.mq.lingerMs = 1
canal.mq.bufferMemory = 33554432
canal.mq.canalBatchSize = 50
canal.mq.canalGetTimeout = 100
canal.mq.flatMessage = true
canal.mq.compressionType = none
canal.mq.acks = 1
# use transaction for kafka flatMessage batch produce
canal.mq.transaction = false
#canal.mq.properties. =

**Comment by hookover** [comment]
@Bruce2jiang 可以分享一下你的instance配置吗？我kafka入库都没成功。。

**Comment by agapple** [comment]
目前没有指定kafka副本这参数
