### ISSUE TITLE
现在zk只能看到消费位点，我现在想拿到解析问点

### ISSUE THREAD

**Issue by Bruce2jiang** [alibaba/canal#1872]
谁能回答现在zk只能看到消费位点，我现在想拿到解析问点
一下，这个怎么获取到 ？紧急........................

**Comment by Bruce2jiang** [comment]
@agapple   谁能回答现在zk只能看到消费位点，我现在想拿到解析问点
一下，这个怎么获取到 ？紧急........................

**Comment by Bruce2jiang** [comment]
@agapple 大神

**Comment by 54nidong** [comment]
String binlog = entry.getHeader().getLogfileName();
            Long startPos = entry.getHeader().getLogfileOffset();
            Long endPos = entry.getHeader().getLogfileOffset() + entry.getHeader().getEventLength();

你说的解析位点就是这条sql执行的时候，在mysql中的位点吗？   这个位点有2个，一个start，一个end

**Comment by 54nidong** [comment]
@Bruce2jiang

**Comment by Bruce2jiang** [comment]
你好这段代码要写在哪里，我要改源码吗

**Comment by Bruce2jiang** [comment]
@54nidong  你好这段代码要写在哪里，我要改源码吗
