### ISSUE TITLE
canal 同步报错exception，ErrorPacket [errorNumber=1193， mysql 版本5.5.41

### ISSUE THREAD

**Issue by jacky3721** [alibaba/canal#1874]
## Question
canal 同步报错exception，ErrorPacket [errorNumber=1193， mysql 版本5.5.41。 突然报错，mysql版本没有换过

CanalParseException: java.io.IOException: ErrorPacket [errorNumber=1193, fieldCount=-1, message=Unknown system variable 'binlog_checksum', sqlState=HY000, sqlStateMarker=#]
with command: select @@global.binlog_checksum
Caused by: java.io.IOException: ErrorPacket [errorNumber=1193, fieldCount=-1, message=Unknown system variable 'binlog_checksum', sqlState=HY000, sqlStateMarker=#]
with command: select @@global.binlog_checksum

**Comment by 54nidong** [comment]
你做了什么操作出现了这个错？

**Comment by shengmingzhu** [comment]
Mysql 5.6.2以前的版本没有末尾校验协议，即没有'binlog_checksum'参数。经测，canal v1.1.3版本在启动时会获取该参数导致报错，但不影响后面的数据解析，可以忽略，无需处理。

**Comment by agapple** [comment]
LS正解
