### ISSUE TITLE
设置了kafka分区规则为主键，消息的pkNames为null了

### ISSUE THREAD

**Issue by Level1Accelerator** [alibaba/canal#1876]
## Question

![Uploading image.png…]()第一条是默认的分区规则，第二条是主键分区，结果pkname为null了

**Comment by cjk87927** [comment]
flatMessage=true 并且使用了分区的情况下 会导致pkname为空
在分区处理的时候漏了赋值pkname
https://github.com/alibaba/canal/issues/1352#issuecomment-502923540

**Comment by agapple** [comment]
https://github.com/alibaba/canal/commit/5bea876ec98c3f4e3ca0a2eb21996f8ee6cf9bad

**Comment by wangweihb** [comment]
@cjk87927 pkNames 是意思呢？
