### ISSUE TITLE
关于kafka模式投递消息的几点疑问

### ISSUE THREAD

**Issue by fruit-forest** [alibaba/canal#1877]
1、CanalKafkaProducer里面如果flatMessage=true并且开启kafka事务使用的是异步发送；但是动态topic情况使用的是同步发送；这两种情况有什么差别吗？
2、flatMessage=false + 动态topic lingMs=1的话发送消息性能会很差，应该要lingMs设置成0吗
3、文档有说多topic情况不开启事务可能消息丢失或者重复，重复可以理解，什么情况会丢失？

**Comment by fruit-forest** [comment]
@agapple

**Comment by agapple** [comment]
目前flatMessage=true/false都是同步发送，可以使用事务消息来做批量发送

**Comment by fruit-forest** [comment]
只要是异步就可能造成数据丢失，重复/乱序（开启重试的话）；
至于数据重复的问题暂时无解，至少重启的时候会重复；
这么理解对吧

**Comment by agapple** [comment]
理解正确
