### ISSUE TITLE
Canal1.3  启动报错

### ISSUE THREAD

**Issue by yhq-842488805** [alibaba/canal#1878]
## Question
按照wiki文档修改完配置文件之后，进行启动，观察canal日志：

Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=96m; support was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: UseCMSCompactAtFullCollection is deprecated and will likely be removed in a future release.
Error: Could not find or load main class com.alibaba.otter.canal.deployer.CanalLauncher

**Comment by agapple** [comment]
是用二进制包启动还是？
