### ISSUE TITLE
canal到elasticsearch同步，数组结构无法同步删除操作

### ISSUE THREAD

**Issue by 1075482900** [alibaba/canal#1879]
使用官方提供的sql案例，执行如下语句：
delete from label；  
elasticsearch中label数据不会删除。
而执行：
delete from user；
elasticsearch中user数据可以删除成功。

这两个数据的区别为label在es中以数组形式存储，所以猜测是因为数组发生无法同步删除操作的bug。

**Comment by rewerma** [comment]
子表删除应该也会触发更新聚合的数据的
