### ISSUE TITLE
canal的数据库连接信息会在otter-manager内自动解析为ip的问题

### ISSUE THREAD

**Issue by nickfan** [alibaba/canal#189]
canal的数据库连接信息会在otter-manager内自动解析为ip
但我们用的服务域名，会不定期更新ip，会导致canal连接不上mysql服务。
请问如何让配置中保持域名而不是解析为ip.

**Comment by agapple** [comment]
研究一下，提交一个PR给我吧

**Comment by weikuo0506** [comment]
这个问题我们也遇到了，我们通过配置vpn解决的

**Comment by tangcongzhen** [comment]
能说下配置vpn如何解决otter-manager把域名解析成IP的问题吗？

**Comment by agapple** [comment]
https://github.com/alibaba/otter/issues/172, fix了
