### ISSUE TITLE
canal服务端和客户端如何确保高可用？

### ISSUE THREAD

**Issue by yibin001** [alibaba/canal#1891]
## canal服务端和客户端如何确保高可用？

现在业务场景是线上的mysql数据变化需要实时同步到mssql，准备用Cacal+rocketMQ，如何解决单点问题？如果有多个客户端去消费MQ，能否确保顺序？

**Comment by agapple** [comment]
canal同步到MQ，只能保证分区有序性，如果没有分区键值的变更，多客户端消费是可以保证顺序的
