### ISSUE TITLE
如何通过canal 区分 create table 和 create table as select ？

### ISSUE THREAD

**Issue by jkl0898** [alibaba/canal#1892]
## Question

1. 查看 canal 日志，**‘ create table test_copy_010 as select * from test_010; ‘** 建表语句的 
entry header 信息如下 ：

2019-06-14 11:30:26.182 [pool-7-thread-1] WARN   - ==entry:header {
  version: 1
  logfileName: "mysql-bin.000144"
  logfileOffset: 644868733
  serverId: 216
  serverenCode: "UTF-8"
  executeTime: 1560483039000
  sourceType: MYSQL
  schemaName: "test"
  tableName: "test_copy_010"
  eventLength: 282
  eventType: CREATE
}
entryType: ROWDATA
storeValue: "\020\004P\001Z\327\001CREATE TABLE `test_copy_010` (\n  `name` int(11) DEFAULT NULL,\n  `des` varchar(10) DEFAULT NULL,\n  `id` int(11) DEFAULT NULL,\n  `id1` int(11) DEFAULT NULL,\n  `id2` int(11) DEFAULT NULL,\n  `id3` int(11) DEFAULT NULL\n)r\004test"

其中storeValue 是已经过转化后的内容。 
并且  eventType: CREATE 而非 CREATE TABLE AS;

**请问canal如何获取原始的建表语句 create table test_copy_010 as select * from test_010; 或者以何种方式区分 create table 和 create table as  select  ？**

**Comment by agapple** [comment]
canal本身不会做这个create table as select的转换，请确认一下物理binlog的数据内容
