### ISSUE TITLE
timestamp字段类型，读取数据有误

### ISSUE THREAD

**Issue by barlowzj** [alibaba/canal#1896]
### environment
版本：canal.deployer-1.1.3    mysql5.7.2
timestamp类型的字段，通过column.getValue()时，取出时间有误。相差12小时。

字段定义：
 `event_time` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(4) ON UPDATE CURRENT_TIMESTAMP(4),

**Comment by barlowzj** [comment]
insert into  tm(event_time,start_date) VALUES('2019-06-15 11:27:01.9051','2019-06-15 11:27:01')
读取到的数据：
ventType : INSERT
id : 15    update=true
event_time : 2019-06-14 23:27:01.0000    update=true
start_date : 2019-06-15 11:27:01    update=true

**Comment by agapple** [comment]
估计是数据库的时区问题，可以查询物理的binlog文件，通过mysqlbinlog解析看看

**Comment by barlowzj** [comment]
应该不是时区设置问题吧。
如果是时区问题，那start_date的值也应该异常啊

以下是start_date的字段类型
`start_date` datetime(0) DEFAULT NULL,

这是binlog的物理文件解析出的内容
### INSERT INTO `oee`.`tm`
### SET
###   @1=5
###   @2=1560569221.905
###   @3='2019-06-15 11:27:01'

**Comment by agapple** [comment]
datetime类型没有时区的概念，timestamp有时区的问题，所以没影响
你运行canal的时区对么？
