### ISSUE TITLE
mysql同步中文到elasticsearch出现乱码

### ISSUE THREAD

**Issue by 1075482900** [alibaba/canal#1898]
* canal version ：1.1.3
* mysql version ： 5.7.20
*elasticsearch version ：6.6.2

mysql同步到elasticsearch出现乱码，mysql相应的中文字段使用utf8mb4编码，其他配置如下：
| character_set_client     | latin1                                 |
| character_set_connection | latin1                                 |
| character_set_database   | latin1                                 |
| character_set_filesystem | binary                                 |
| character_set_results    | latin1                                 |
| character_set_server     | latin1                                 |
| character_set_system     | utf8                                   |
| character_sets_dir       | /usr/local/mysql5.7.20/share/charsets/ |

canal连接数据库的配置如下：
canal.instance.dbUsername=mmqspace
canal.instance.dbPassword=for4qspace
canal.instance.connectionCharset = UTF-8 
canal.instance.enableDruid=false

请问这是哪里的问题呢？ 猜测是connectionCharset配置的问题，但是实在不知道要配置什么，求指点。

**Comment by agapple** [comment]
分开两部分来看，首先单独部署canal server和client，看看中文显示是否正常，然后再接入es看看

**Comment by 1075482900** [comment]
日志来看就是乱码，目前来分析是因为这条配置导致：
canal.instance.connectionCharset = UTF-8

因为数据库里的字段用的是utf8mb4编码，所以当使用上面这条配置去连接数据库会出现乱码。我手工连接mysql使用UTF-8字符集也会出现同样的乱码。

那我要怎么配置？

**Comment by agapple** [comment]
你弄一个mac的电脑看一下，utf8mb4在java里用utf8是可以正确表示的
