### ISSUE TITLE
kafka的json消息接入hive表

### ISSUE THREAD

**Issue by brightsong** [alibaba/canal#1899]
## Question
使用canal-developer-1.1.3，将mysql的数据增量到kafka中，在kafka consume中看到是json类型的数据；如
`{"data":[{"id":"11","name":"abcd","age":"112"}],"database":"can_db","es":1560383376000,"id":1,"isDdl":false,"mysqlType":{"id":"int(11)","name":"varchar(40)","age":"int(11)"},"old":null,"pkNames":["id"],"sql":"","sqlType":{"id":4,"name":12,"age":4},"table":"user_test","ts":1560326879510,"type":"INSERT"}`
如何将json的数据解析后再将数据同步到hive中。可否使用flume，使用flume的话，配置文件应该怎么写，大家有谁有一样的需求吗。谢谢

**Comment by liujianmin11** [comment]
有相同需求 用spark消费写到hive 有很多小文件

**Comment by rewerma** [comment]
可以通过hbase-adapter先消费到hbase，然后hive创建外部表访问hbase
