### ISSUE TITLE
mysql表有中文时，使用canal-developer-1.1.3传输到kafka 的消息中中文是乱码

### ISSUE THREAD

**Issue by brightsong** [alibaba/canal#1900]
## Question

如题，mysql是utf8编码，修改mysql的数据，其中包含中文，发现同步到kafka中中文是乱码。怎么解决？

**Comment by 1075482900** [comment]
我也遇到了这个问题 ，楼主解决了吗

**Comment by agapple** [comment]
1.  show create table看一下表结构
2. 单独使用canal server+client模式看一下中文内容是否乱码
