### ISSUE TITLE
canal.deployer-1.1.3启动报错

### ISSUE THREAD

**Issue by chubenli** [alibaba/canal#1906]
启动日志：
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=96m; support was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: UseCMSCompactAtFullCollection is deprecated and will likely be removed in a future release.
Error: Could not find or load main class com.alibaba.otter.canal.deployer.CanalLauncher

**Comment by csoftware** [comment]
同样的报错 +1

**Comment by csoftware** [comment]
解压方式 tar -xzvf canal.deployer-1.1.3.tar.gz

**Comment by csoftware** [comment]
@chubenli 
 这个原因我是因为解压文件方式不对造成的，正确的做法如下：
 解压方式 tar -xzvf canal.deployer-1.1.3.tar.gz
 希望能帮到你

**Comment by agapple** [comment]
估计jdk版本过高，部分启动参数不识别
