### ISSUE TITLE
自动更新时间同步后 源和目标时间不一致

### ISSUE THREAD

**Issue by xiaobiaoge** [alibaba/canal#1908]
## Question
update_at这个列的时间从源库同步过来后，要比源库的该列的时间落后，该chanal下其他表没有发现这个问题，不知道是怎么回事。
表结构如下

CREATE TABLE `table_aa` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `code` VARCHAR(32) NOT NULL COMMENT '',
  `merchant_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '',
  `white_list_id` BIGINT(20) UNSIGNED DEFAULT NULL COMMENT '',
  `name` VARCHAR(50) DEFAULT NULL COMMENT '',
  `id_card` VARCHAR(50) NOT NULL COMMENT '',
  `mobile` VARCHAR(20) NOT NULL COMMENT '',
  `birthday` DATE DEFAULT NULL COMMENT '',
  `gender` VARCHAR(20) DEFAULT NULL COMMENT '',
  `valid_start` VARCHAR(10) DEFAULT NULL COMMENT '',
  `valid_end` VARCHAR(10) DEFAULT NULL COMMENT '',
  `id_card_front_image` VARCHAR(20) DEFAULT NULL COMMENT '',
  `id_card_back_image` VARCHAR(20) DEFAULT NULL COMMENT '',
  `id_card_with_head_image` VARCHAR(20) DEFAULT NULL COMMENT '',
  `head_image` VARCHAR(20) DEFAULT NULL COMMENT '',
  `third_user_no` VARCHAR(32) DEFAULT NULL COMMENT '',
  `step` VARCHAR(20) DEFAULT NULL COMMENT '',
  `customer_id` BIGINT(20) DEFAULT NULL COMMENT '',
  `product_no` VARCHAR(20) NOT NULL COMMENT '',
  `ocr_valid_status` VARCHAR(50) NOT NULL DEFAULT 'NOT_VALID' COMMENT '',
  `id5_valid_status` VARCHAR(50) NOT NULL DEFAULT 'NOT_VALID' COMMENT '',
  `three_valid_status` VARCHAR(50) NOT NULL DEFAULT 'NOT_VALID' COMMENT '',
  `other_loan` VARCHAR(20) NOT NULL DEFAULT 'NONE' COMMENT '',
  `id_card_op_valid` VARCHAR(20) NOT NULL DEFAULT 'NOT_VALID' COMMENT '(枚举)',
  `update_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  `create_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `external` json DEFAULT NULL COMMENT '',
  `core_enterprises` TEXT COMMENT '',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uniq_code` (`code`) USING BTREE,
  UNIQUE KEY `uniq_mobile_merchantid` (`mobile`,`merchant_id`) USING BTREE,
  UNIQUE KEY `uniq_idcard_merchantid` (`merchant_id`,`id_card`) USING BTREE
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT=''

**Comment by agapple** [comment]
给我复现的测试SQL和错误结果例子
