### ISSUE TITLE
主备同步问题

### ISSUE THREAD

**Issue by liuyouqian** [alibaba/canal#191]
现在有两台MySQL数据库 ：M1（主）-》M2（备）
我现在的情况是otter部署在M2上，两个有相同的数据库与一张表
条件：M1，M2均正常运行，otter未启动同步
1.在M1中insert一条数据，此时由于未启动同步，M2不会出现这条数据
2.启动otter同步
3.修改M1中刚才插入的数据，M2中不会出现数据
这种情况应该如何解决？
谢谢各位了

**Comment by agapple** [comment]
update转insert，可以开启otter的行同步模式

**Comment by liuyouqian** [comment]
我在测试的时候用的基于数据库反查就不能就会出现不同步，今天我使用基于当前日志变更的时候能够成功同步过来
就想问下数据库反查和日志变更在使用上分别的用途？

2016年8月4日星期四，agapple <notifications@github.com> 写道：

**Comment by liuyouqian** [comment]
看到文档了，就不麻烦你了哈，谢谢

2016年8月4日星期四，刘欢 <askingneil@gmail.com> 写道：
