### ISSUE TITLE
使用疑问

### ISSUE THREAD

**Issue by chenchuanyuan** [alibaba/canal#1911]
## Question

canal.instance.tsdb.enable=true  

canal.instance.filter.query.ddl = true
canal.instance.filter.query.dcl = true

出现column size is not match for table  解析问题，数据库表结构改变导致的，需要手动删除h2.mv.db 文件；不会自动更新本地的表结构信息，是哪个配错了吗？

另外我是将数据发送至mq，是不是只会发送dml 的数据？ddl 和dcl 不会发送？ 上面最后两个filter 是过滤发送mq 的吗？

**Comment by cjk87927** [comment]
后面两个是解析binlog的,和是否发送没关系,解析完后保存到canal的内部存储,后一步才是发送到MQ
如果你过滤掉了,当然就不会发送到mq

**Comment by cjk87927** [comment]
第一个问题可以看看 #1737
