### ISSUE TITLE
canal 对ES 5.X版本的配置

### ISSUE THREAD

**Issue by liulishaccc** [alibaba/canal#1915]
## Question

es5.X 版本在adapter 中esMapping 中如何配置

**Comment by 1044730317** [comment]
说明文档不是有说嘛？ 配置是一样了，只是你需要重新编译，由于依赖关系。

**Comment by liulishaccc** [comment]
我试过，配置不变启动报错的

**Comment by liulishaccc** [comment]
> 说明文档不是有说嘛？ 配置是一样了，只是你需要重新编译，由于依赖关系。

我试过，配置不变启动报错的

**Comment by aweneves** [comment]
> > 说明文档不是有说嘛？ 配置是一样了，只是你需要重新编译，由于依赖关系。
> 
> 我试过，配置不变启动报错的

今天才踩的坑，可以参考一下是不是这个原因：
https://blog.csdn.net/u013257679/article/details/93897898

**Comment by rewerma** [comment]
es的adapter是基于6.x开发调试的，5.x的api可能会不一样，需要自行修改包依赖调试适配
