### ISSUE TITLE
canal 多实例启动，某实例会出现起始消费位延后的情况及大量重复消费单条记录

### ISSUE THREAD

**Issue by MrYueQ** [alibaba/canal#1916]
***基础资源信息***
- 操作系统版本
```bash
uname -mrs 
Linux 3.10.0-862.14.4.el7.x86_64 x86_64
cat /etc/redhat-release 
CentOS Linux release 7.5.1804 (Core) 
```
- canal 版本
```bash
v1.1.2
```
- 数据库版本
```bash
mysql> select version();
+------------+
| version()  |
+------------+
| 5.7.22-log |
+------------+
1 row in set (0.00 sec)
```
- jdk 信息
```bash
java -version 
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)
```
### 数据流
canal 从mysql 获取数据然后同步到kafka 队列中，其中canal 只部署一个服务，但有 18个 canal 实例。消费过程中的元消息暂存到zk 中。异常实例的数量为1.
### 排故过程
在维护过程中，发现某实例数据消费大量重复。
- 登录zk 集群，查看实例当前的消费状态及偏移量
发现实例消费状态及偏移量保持不变。
- 通过辅助 kibana 验证，一条数据重复次数达2亿多条
- 跟dba 确认。对应数据库的 binlog 日志未删除。
    手动设置异常canal 实例消费状态
        设置 canal.instance.master.journal.name + canal.instance.master.position 指定从凌晨开始消费数据,故障复现
       注释上一步设置，设置 canal.instance.master.timestamp 指定从凌晨开始消费，故障复现
       注释前两部设置， 使用当前状态进行消费数据，故障复现。
观察异常实例的启动日志，发现无论变更其对应实例的配置策略及参数。实例启动时，都从特定的一个  journalName position 开始消费数据，然重复数据是在这个点之后。
### 备注
 每次变更参数后，都会在 zk CLI 删除对应的消费位点
--- 
### 临时解决方案
将异常实例的配置文件夹重命名，然后启动canal 服务。故障未出现。

**Comment by agapple** [comment]
我理解一下问题，canal处于一个位点无法前进的意思么？重置位点之后，对应的canal队列日志有关注过么？是否有正常定位和数据解析异常

**Comment by MrYueQ** [comment]
> 我理解一下问题，canal处于一个位点无法前进的意思么？重置位点之后，对应的canal队列日志有关注过么？是否有正常定位和数据解析异常

> 大佬，应该是我们配置的问题。
---
问题引起时错误的配置参数
```bash
.*\\..*:$pk$ 正则匹配，指定所有正则匹配的表对应的hash字段为表主键(自动查找)
```
经排查，数据库中的某些表是没有主键的[测试环境]。后续调整为
```bash
.*\\..* ，不指定pk信息的正则匹配，将所有正则匹配的表,对应的hash字段为表名
```

**Comment by agapple** [comment]
最新的版本应该是修复过pk NPE的情况，针对flatMessage的情况
