### ISSUE TITLE
com.alibaba.fastsql 2.0.0_preview_914未更新导致编译报错

### ISSUE THREAD

**Issue by yuanx1** [alibaba/canal#1920]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 50.848 s
[INFO] Finished at: 2019-06-23T15:15:11+08:00
[INFO] Final Memory: 47M/630M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project canal.parse: Could not resolve dependencies for project com.alibaba.otter:canal.parse:jar:1.1.4-SNAPSHOT: Failure to find com.alibaba.fastsql:fastsql:jar:2.0.0_preview_914 in http://repo1.maven.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :canal.parse

**Comment by yuanx1** [comment]
<dependency>
                <groupId>com.alibaba.fastsql</groupId>
                <artifactId>fastsql</artifactId>
                <version>2.0.0_preview_914</version>
            </dependency>

**Comment by agapple** [comment]
新版fastsql，还未提交maven中央仓库

**Comment by mark988** [comment]
能不能发一下？ 或者提供一个下载地址？

**Comment by yuanx1** [comment]
@mark988 这个问题已经修复～！
