### ISSUE TITLE
Adapter适配器理论上是支持greenplum的吗，有实际尝试的么

### ISSUE THREAD

**Issue by clverhack** [alibaba/canal#1921]
## Question
如题，我看适配器支持jdbc , greenplum 是否也支持，有没有谁实际测试的情况

**Comment by wingerx** [comment]
理论上是支持的，可以试一下。

**Comment by clverhack** [comment]
> 理论上是支持的，可以试一下。

多谢，回头试一下

**Comment by rewerma** [comment]
理论上可以通过扩展开发adapter支持任何库的数据落地。gp支持jdbc，应该可以直接在rdb-adapter中进行配置即可
