### ISSUE TITLE
mysqlType为set类型时，canal取值为数值，对应的实际值如何取到

### ISSUE THREAD

**Issue by MonikaSophin** [alibaba/canal#1925]
## Question
rowData其中mysqlType为set类型的 afterColumns_的值

index: 11
sqlType: -7
name: "media"
isKey: false
updated: false
isNull: false
value: "21"
mysqlType: "set(\'SITE_SET_QQCLIENT\',\'SITE_SET_QZONE\',\'SITE_SET_PENGYOU\',\'SITE_SET_QQCOM\',\'SITE_SET_MUSIC\',\'SITE_SET_WECHAT\',\'SITE_SET_MOBILE_UNION\',\'SITE_SET_MOBILE_INNER\')"

canal客户端取到的value值为21，实际值是SITE_SET_QQCLIENT、SITE_SET_PENGYOU和SITE_SET_MUSIC,请问实际值怎么取到。同样还有，当mysqlType为enum时，如何取到实际值？

**Comment by agapple** [comment]
21应该是mysql实际存储的数据格式，它是一个bit位的表示方式. 

21转化为二进制：10101
也就是对应于set的第1、3、5号位的值，最终值是：SITE_SET_QQCLIENT, SITE_SET_PENGYOU, SITE_SET_MUSIC

**Comment by MonikaSophin** [comment]
@agapple 谢谢大佬

**Comment by MonikaSophin** [comment]
@agapple  这个只能通过去解析mysqlType的String串，然后根据二进制值去匹配么？
canal有没有相关的方法啊?

**Comment by agapple** [comment]
你照着我刚才描述的思路，是很容易实现的，需要的元数据都有了

**Comment by MonikaSophin** [comment]
我知道，但是比较懒。我还是自己去实现这个功能吧 QAQ

**Comment by MonikaSophin** [comment]
我感觉还是有必要补充一下，MySQL用二进制数保存set值，所保存值的低阶位对应第1个set成员。

先将21转化为二进制：10101 然后翻转过来变成10101, 然后再去对应于set的第1、3、5号位的值。
（这个是对称的，所以举个值为22的例子: 22 --> 10110 --> 01101） 
或者将set成员值翻转，然后用对应二进制数值进行set值的匹配。
