### ISSUE TITLE
canal是否可以投递数据到阿里AMQP产品

### ISSUE THREAD

**Issue by zhanjianS** [alibaba/canal#1930]
## Question

1.1.3 canal是否可以投递数据到阿里AMQP产品 ？

**Comment by bucketli** [comment]
hi, issue 请按标准模板填充，谢谢

**Comment by letwang** [comment]
> ## Question
> 1.1.3 canal是否可以投递数据到阿里AMQP产品 ？



> hi, issue 请按标准模板填充，谢谢

https://github.com/alibaba/canal/issues/2070
