### ISSUE TITLE
请问支持nested类型的文档同步吗？

### ISSUE THREAD

**Issue by aweneves** [alibaba/canal#1934]
mappings的接口如下，有嵌套的对象，canal能够支持这种结构的同步吗？如果可以应该怎么搞
"mappings": {
	"order": {
		"properties": {
			"status_id": {
				"type": "keyword"
			},
			"company_name": {
				"type": "text"
			},
			"company_code": {
				"type": "integer"
			},
			"order_id": {
				"type": "keyword"
			},
			"order_item": {
				"type": "nested",
				"properties": {
					"product_id": {
						"type": "text"
					}
				}
			}
		}
	}
}

**Comment by chai-zhenhua** [comment]
请问这个问题解决了吗？我也在思考同样的问题，还请不吝赐教，谢谢

**Comment by aweneves** [comment]
> 请问这个问题解决了吗？我也在思考同样的问题，还请不吝赐教，谢谢

后面试了一下，配置文件里面objFields配object 就行了，一样能兼容nested

**Comment by HappyJoeJoe** [comment]
> > 请问这个问题解决了吗？我也在思考同样的问题，还请不吝赐教，谢谢
> 
> 后面试了一下，配置文件里面objFields配object 就行了，一样能兼容nested

能贴一个demo吗

**Comment by a378042176** [comment]
> > 请问这个问题解决了吗？我也在思考同样的问题，还请不吝赐教，谢谢
> 
> 后面试了一下，配置文件里面objFields配object 就行了，一样能兼容nested

请问下你的sql怎样配的呢？可以给个demo么

**Comment by aweneves** [comment]
> > > 请问这个问题解决了吗？我也在思考同样的问题，还请不吝赐教，谢谢
> > 
> > 
> > 后面试了一下，配置文件里面objFields配object 就行了，一样能兼容nested
> 
> 请问下你的sql怎样配的呢？可以给个demo么
demo如下，不过不建议使用canal的client，最好自己写一个客户端进行消费，比较灵活，我这边的服务后面也放弃canal-client了
`dataSourceKey: defaultDS
destination: example
groupId: 
esMapping:
  _index: order
  _type: order_header
  _id: _id
  upsert: true
#  pk: id
  sql: "select t.ORDER_ID _id, concat('[', t.order_item,']') order_item 
        from (
        select oi.ORDER_ID,
        group_concat(
        concat(
        '{\"field_1\": \"',IFNULL(oi.field_1,''),
        '\", \"field_2\":\"',IFNULL(oi.field_2,''),
        '\", \"field_3\":\"',IFNULL(oi.field_3,''),
        '\"}')) as order_item
        from order_item oi
        group by oi.ORDER_ID) t"
  objFields:
    order_item: object
`

**Comment by a378042176** [comment]
试了下，可以用，先谢谢了
只是order_item新增可以正常插入es，但修改和删除好像不对
在mysql修改里面的item，索引并不会更新
在mysql里删除一个item，会把整个主项删除
大佬有碰到过这个问题么

还有，大佬不建议这种方式消费，原因大概是啥？

**Comment by a378042176** [comment]
@aweneves

**Comment by a378042176** [comment]
![image](https://user-images.githubusercontent.com/10397370/97161989-86a0b600-17b9-11eb-800e-a749b70e2437.png)
![image](https://user-images.githubusercontent.com/10397370/97162049-9cae7680-17b9-11eb-9dc4-2cbb0140f4ca.png)
这是我的配置

**Comment by a378042176** [comment]
mysql修改一条细项的summery，es的summery不会修改
mysql删除一条细项，es的整条记录都会删了，
etl工作正常

**Comment by sunwulovelove1** [comment]
SQL 不对
