### ISSUE TITLE
canal adapter中只用tcp消费模式使用zk做了高可用，对接kafka和rocketMQ时没有做高可用

### ISSUE THREAD

**Issue by flackyang** [alibaba/canal#1939]
## Question

在canal adapter中只用tcp消费模式使用zk做了高可用，
但是对接kafka和rocketMQ时没有做高可用
是否老师增加对接kafka和rocketmq进也使用zk做高可用，类型canal server端高可用的效果，当canal adapter master 异常退出时，stand by节点继续进行同步

**Comment by agapple** [comment]
对接MQ的高可用，这个是MQ自身提供的，你可以同时启动多个client，会自行由MQ的客户端分配不同的partition的高可用清空

**Comment by MickeyWZC** [comment]
> 对接MQ的高可用，这个是MQ自身提供的，你可以同时启动多个client，会自行由MQ的客户端分配不同的partition的高可用清空

mq --> 多个adapter --> es(rdb)
这样的场景下，数据会在并发情况下出现问题。因为一个队列有多个adapter消费者，无法保证顺序写入es
这样的高可用会带来数据问题。

**Comment by zebozhuang** [comment]
kafka对接的adapter只要保证table在partition的数据唯一，多个Adapter就可以保证高可用
