### ISSUE TITLE
在docker环境下配置canal-server和zookeeper

### ISSUE THREAD

**Issue by visionYiu** [alibaba/canal#1940]
canal-client 链接zookeeper获取服务，获取的是canal-server容器的ip。
将配置文件canal.ip改成宿主ip，又无法启动canal-server服务

**Comment by bucketli** [comment]
hi, 请按照标准模板提交 bug 或者问题，方面我们精确定位并修复问题，如果您有余力，也欢迎提交代码 fix 问题，感谢

**Comment by zixcon** [comment]
实测v1.1.4-alpha-2这个版本通过canal.register.ip 参数解决docker容器HA的canal部署问题
