### ISSUE TITLE
ClientAdapter（ES）启动后到第二天看就假死在哪里，关停都没反应只能KILL9重启

### ISSUE THREAD

**Issue by 1044730317** [alibaba/canal#1948]
ClientAdapter启动后到第二天看就假死在哪里，关停都没反应只能KILL9重启
重启ClientAdapter 后我还会手动etl 一次， 这样ES库里面的数据就同步了， 如果这时候MYSQL有数据写入，看到adapter的日志就有日志打印，数据也会进入到ES库中。
----
请问这是什么问题？ 要如何处理
----
我感觉是不是长时间没有数据写入MYSQL,导致整个同步体系什么地方出BUG了？
因为我的同步经常晚上是没有数据跑的。当然这是测试环境。

**Comment by 1044730317** [comment]
设置了心跳检测，这样就不会有假死的情况了。但是遇到大数据量更新的时候，还是会出现阻塞，然后需要重启才能再次消费数据。

**Comment by rewerma** [comment]
如果是mq模式，看一下消费情况是否有阻塞的情况，如果是client模式看一下grafana中client消费是不是有阻塞，一般大批量订正数据或者修改一堆多的数据时可能会发生阻塞

**Comment by 1044730317** [comment]
> 如果是mq模式，看一下消费情况是否有阻塞的情况，如果是client模式看一下grafana中client消费是不是有阻塞，一般大批量订正数据或者修改一堆多的数据时可能会发生阻塞

请问 mq模式下的 消费阻塞这种情况怎么处理呢？ 能不能说下思路

**Comment by aiguo123** [comment]
请问下解决了吗，我也有这个问题
