### ISSUE TITLE
node节点运行一段时间后,产生的tmp日志文件由于被多个线程占用,强制删除后句柄未释放,导致磁盘空间紧张

### ISSUE THREAD

**Issue by Yanxinwei** [alibaba/canal#1955]
###如题描述,产生的临时日志文件无法清除,附相关截图如下:
![image](https://user-images.githubusercontent.com/2412443/60571375-18570980-9da6-11e9-96c0-50310199514e.png)

###补充相关信息:
1.多个线程同时访问一个临时日志文件;
2.可以强制删除,但是由于文件句柄未被释放,磁盘空间未能真正释放,必须重启实例.

**Comment by agapple** [comment]
可以考虑关闭otter的同步日志
