### ISSUE TITLE
canal adapter向es同步时会重复提交以往的请求

### ISSUE THREAD

**Issue by mantfort** [alibaba/canal#1957]
- [x] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment

* canal version
1.1.3
* mysql version
5.7

### Issue Description
数据库的一次DML操作会触发canal adapter向ES发起插入或更新请求，但是这样的请求会添加到一个Request中，所以之后的DML操作会继续向同一个数组中添加。向ES请求时会依次调用这个Request中的内容，导致以前的请求在之后每次触发时都会被调用。

具体的地方是EsTemplate类里面的 getBulk().add() 相关的代码，request会增加，但是一直用的是同一个request。
在commitBulk提交到ES之后会遍历返回值，这个时候能看到以前的变更都被提交到es了。

**Comment by rewerma** [comment]
已经修复
