### ISSUE TITLE
eclipse导入项目编译报错

### ISSUE THREAD

**Issue by renshui1983** [alibaba/canal#196]
问题描述：

代码版本: 1.0.22
maven 版本: 3.3.3
jdk版本: 1.7.0_80

在根目录下执行mvn eclipse:eclipse 命令后，将项目导入eclipse，大面积报错，大概原因是：driver项目依赖canal.common, 但是eclipse中导入的common项目的项目名是"common", 项目名不匹配。大家有碰到类似问题吗？

![qq20160828-1](https://cloud.githubusercontent.com/assets/13866684/18031262/31068e26-6d0a-11e6-8257-f8b21a2e4681.png)

**Comment by agapple** [comment]
我工程依赖树定义都是canal.xxx，全名的，你看下其他工程的pom.xml定义

**Comment by renshui1983** [comment]
@agapple  我看了下其他工程的pom.xml定义，依赖也都是全名依赖，但是被依赖的项目导入eclipse后就不是全名了，可以见问题中的截图“common”。
是不是该项目对maven版本有要求还是我执行的mvn eclipse:eclipse命令缺少参数。

**Comment by renshui1983** [comment]
我自己在eclipse中将项目名手工改了，现在编译已经没问题了。
