### ISSUE TITLE
the safe about canal

### ISSUE THREAD

**Issue by hailianghe** [alibaba/canal#1964]
## Question
1. I find the canal use the '11111' port when it run, i want  know is it safe when the port is open for all ?
2. I find there is a '92.119.160.124 ip address in the 'netstat -tn' when the canal is running,  is it safe ?
![image](https://user-images.githubusercontent.com/29939806/60657866-9ee21880-9e84-11e9-816b-c77b42042383.png)

**Comment by agapple** [comment]
canal.properties
```
canal.ip = xxx
```

you can fixed netty bind ip
