### ISSUE TITLE
设置ES用户名和密码

### ISSUE THREAD

**Issue by lwhero** [alibaba/canal#1976]
## Question

如何在canal配置文件中设置ES的用户名和密码？

**Comment by MrYZD** [comment]
同求

**Comment by Mycheers** [comment]
同求 +1

**Comment by confuse0** [comment]
目前还不行的，参考#2001提到的改进，需要自己下载源代码，修改client-adapter.elasticsearch里面的源代码，SyncES是用TransportClient方式，需要修改ESAdapter的源代码，找到transportClient = new PreBuiltTransportClient(settings);这一句，替换成PreBuiltXPackTransportClient的XPack方式，然后把配置文件中加入用户密码，自己实现一下即可，这种基于transportClient的方法简单修改即可。
但是如果是访问http方式的，就麻烦了，你要把所有transportClient改成RestHighLevelClient方式，代码里面所有ES的操作你都要改，如果要连接阿里云ES的话，只支持http方式，就都要改，我已经把源码改了，才能支持。

**Comment by fengbird** [comment]
> 目前还不行的，参考#2001提到的改进，需要自己下载源代码，修改client-adapter.elasticsearch里面的源代码，SyncES是用TransportClient方式，需要修改ESAdapter的源代码，找到transportClient = new PreBuiltTransportClient(settings);这一句，替换成PreBuiltXPackTransportClient的XPack方式，然后把配置文件中加入用户密码，自己实现一下即可，这种基于transportClient的方法简单修改即可。
> 但是如果是访问http方式的，就麻烦了，你要把所有transportClient改成RestHighLevelClient方式，代码里面所有ES的操作你都要改，如果要连接阿里云ES的话，只支持http方式，就都要改，我已经把源码改了，才能支持。

请问大佬所说的连接阿里云es只支持http方式，若是所有的服务都是在阿里云上， 然后走内网的方式访问的话是不是就可以支持transportClient的方式了？

**Comment by fengbird** [comment]
在阿里云看到了：
公网：
阿里云ES 6.7.0 with Commercial Feature版本不支持通过Transport Client访问9300端口。
阿里云ES 6.3.2 with Commercial Feature版本不支持通过Transport Client访问9300端口。
内网：
阿里云ES 6.7.0 with Commercial Feature版本不支持通过Transport Client访问9300端口。
阿里云ES 6.3.2 with Commercial Feature版本不支持通过Transport Client访问9300端口。
只有5.5.3的版本才支持tcp的访问方式。。。

**Comment by confuse0** [comment]
请参考我上面提到的方案，修改client-adapter.elasticsearch源代码，把所有TransportClient方式都改成RestHighLevelClient方式即可，需要自己动手，不复杂1-2天就能改完。

**Comment by lnwbzmt** [comment]
> 请参考我上面提到的方案，修改client-adapter.elasticsearch源代码，把所有TransportClient方式都改成RestHighLevelClient方式即可，需要自己动手，不复杂1-2天就能改完。

请问可以分享下修改的代码吗？

**Comment by rewerma** [comment]
最新版本已支持

**Comment by mage694** [comment]
> 支持

能给一下配置项吗？是这个：security.auth
