### ISSUE TITLE
fastjson 版本过低，是否有安全隐患？

### ISSUE THREAD

**Issue by Code2Life** [alibaba/canal#1986]
Canal依赖的fastjson版本是1.2.28, 是否有安全问题？
[https://github.com/alibaba/fastjson/issues/2542](https://github.com/alibaba/fastjson/issues/2542)

**Comment by agapple** [comment]
bd974e3da82dd0be95ed1f7fb55828463aba2835，已升级并关闭了autoTypeSupport
