### ISSUE TITLE
解析异常exception.CanalParseException

### ISSUE THREAD

**Issue by Huai-Ming** [alibaba/canal#1990]
2019-07-12 11:58:17.967 [destination = example , address = EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - dump address has an error, retrying. caused by
com.alibaba.otter.canal.parse.exception.CanalParseException: java.io.IOException: ErrorPacket [errorNumber=1064, fieldCount=-1, message=You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'db_user_info_0db_user_info_2;show create table db_user_info_2.t_user_info_e' at line 1, sqlState=42000, sqlStateMarker=#] with command: show create table db_user_info_2.t_live_user_info_0;show create table db_user_info_2.t_live_user_info_1;show create table db_user_info_2.t_live_user_info_2;show create table db_user_info_2.t_live_user_info_3;show create table db_user_info_2.t_live_user_info_4;show create table db_user_info_2.t_live_user_info_5;show create table db_user_info_2.t_live_user_info_6;show create table db_user_info_2.t_live_user_info_7;show create table db_user_info_2.t_live_user_info_8;show create table db_user_info_2.t_live_user_info_9;show create table db_user_info_2.t_user_certification_info_0;show create table db_user_info_2.t_user_certification_info_1;show create table db_user_info_2.t_user_certification_info_2;show create table db_user_info_2.t_user_certification_info_3;show create table db_user_info_2.t_user_certification_info_4;show create table db_user_info_2.t_user_certification_info_5;show create table db_user_info_2.t_user_certification_info_6;show create table db_user_info_2.t_user_certification_info_7;show create table db_user_info_2.t_user_certification_info_8;show create table db_user_info_2.t_user_certification_info_9;show create table db_user_info_2.t_user_cfh_info_0`;

**Comment by agapple** [comment]
升级最新的canal版本吧
