### ISSUE TITLE
docker compose 把canal的conf挂载到本地，动态新增instance，报创建tsdb错误

### ISSUE THREAD

**Issue by jintonghuoya** [alibaba/canal#1993]
## Question
docker compose 把canal的conf挂载到本地，创建h2.mv.db报错
我观察日志发现是在docker容器内部路径创建，并没有在我映射的本地地址创建
现在在看源码，不知道大家有没有遇到相同的问题？

**Comment by jintonghuoya** [comment]
environment:
      - canal.zkServers=zk1:2181,zk2:2182,zk3:2183
      - canal.serverMode=RocketMQ
      - canal.mq.servers=http://MQ_INST_1681425618067285_Ba4yBi8I.mq-internet-access.mq-internet.aliyuncs.com:80
      - canal.aliyun.accessKey=
      - canal.aliyun.secretKey=
      - canal.mq.producerGroup=
    volumes:
      - /root/development/workspace/compose/canal/canal-server/conf:/home/admin/canal-server/conf
      - /root/development/workspace/compose/canal/canal-server/01/logs:/home/admin/canal-server/logs

**Comment by jintonghuoya** [comment]
我怀疑，因为bin目录和lib目录还是在docker容器内部，所以导致新增instance的时候会错乱直接用当前的classpath。

**Comment by xieh1995** [comment]
怎么解决哦
