### ISSUE TITLE
往KAFA发数据有重复

### ISSUE THREAD

**Issue by wpy222** [alibaba/canal#1994]
## Question

往KAFA发数据有重复

offset: 102 position: 117061 CreateTime: 1562922268545 isvalid: true keysize: -1 valuesize: 1132 magic: 2 compresscodec: NONE producerId: -1 producerEpoch: -1 sequence: -1 isTransactional: false headerKeys: [] payload: {"data":[{"id":"28102","category_code":"020301","category_name":"","material_code":"0203010005","material_name":"","code":"02030100050937","name":"7.5*1500*12220","disabled":"0","status":"0","creator_id":"203407","create_time":"1562922268491","updator_id":"203407","update_time":"1562922268488","last_access":"1562922268491","version":"0"}],"database":"sku","es":1562922268000,"id":5846,"isDdl":false,"mysqlType":{"id":"bigint(20) unsigned","category_code":"varchar(20)","category_name":"varchar(100)","material_code":"varchar(20)","material_name":"varchar(100)","code":"varchar(20)","name":"varchar(100)","disabled":"tinyint(2)","status":"tinyint(2)","creator_id":"bigint(20)","create_time":"bigint(20)","updator_id":"bigint(20)","update_time":"bigint(20)","last_access":"bigint(20)","version":"int(10)"},"old":null,"pkNames":null,"sql":"","sqlType":{"id":-5,"category_code":12,"category_name":12,"material_code":12,"material_name":12,"code":12,"name":12,"disabled":-6,"status":-6,"creator_id":-5,"create_time":-5,"updator_id":-5,"update_time":-5,"last_access":-5,"version":4},"table":"sku_spec","ts":1562922268545,"type":"INSERT"}
offset: 103 position: 121688 CreateTime: 1562922268845 isvalid: true keysize: -1 valuesize: 1132 magic: 2 compresscodec: NONE producerId: -1 producerEpoch: -1 sequence: -1 isTransactional: false headerKeys: [] payload: {"data":[{"id":"28103","category_code":"020301","category_name":"","material_code":"0203010005","material_name":"","code":"02030100050938","name":"7.5*1500*11030","disabled":"0","status":"0","creator_id":"203407","create_time":"1562922268546","updator_id":"203407","update_time":"1562922268543","last_access":"1562922268546","version":"0"}],"database":"sku","es":1562922268000,"id":5847,"isDdl":false,"mysqlType":{"id":"bigint(20) unsigned","category_code":"varchar(20)","category_name":"varchar(100)","material_code":"varchar(20)","material_name":"varchar(100)","code":"varchar(20)","name":"varchar(100)","disabled":"tinyint(2)","status":"tinyint(2)","creator_id":"bigint(20)","create_time":"bigint(20)","updator_id":"bigint(20)","update_time":"bigint(20)","last_access":"bigint(20)","version":"int(10)"},"old":null,"pkNames":null,"sql":"","sqlType":{"id":-5,"category_code":12,"category_name":12,"material_code":12,"material_name":12,"code":12,"name":12,"disabled":-6,"status":-6,"creator_id":-5,"create_time":-5,"updator_id":-5,"update_time":-5,"last_access":-5,"version":4},"table":"sku_spec","ts":1562922268845,"type":"INSERT"}
offset: 104 position: 122890 CreateTime: 1562990510223 isvalid: true keysize: -1 valuesize: 1128 magic: 2 compresscodec: NONE producerId: -1 producerEpoch: -1 sequence: -1 isTransactional: false headerKeys: [] payload: {"data":[{"id":"28104","category_code":"030303","category_name":"","material_code":"0303030002","material_name":"","code":"03030300020072","name":"34*2200*L","disabled":"0","status":"0","creator_id":"300045","create_time":"1562990510110","updator_id":"300045","update_time":"1562990510107","last_access":"1562990510110","version":"0"}],"database":"sku","es":1562990510000,"id":10603,"isDdl":false,"mysqlType":{"id":"bigint(20) unsigned","category_code":"varchar(20)","category_name":"varchar(100)","material_code":"varchar(20)","material_name":"varchar(100)","code":"varchar(20)","name":"varchar(100)","disabled":"tinyint(2)","status":"tinyint(2)","creator_id":"bigint(20)","create_time":"bigint(20)","updator_id":"bigint(20)","update_time":"bigint(20)","last_access":"bigint(20)","version":"int(10)"},"old":null,"pkNames":null,"sql":"","sqlType":{"id":-5,"category_code":12,"category_name":12,"material_code":12,"material_name":12,"code":12,"name":12,"disabled":-6,"status":-6,"creator_id":-5,"create_time":-5,"updator_id":-5,"update_time":-5,"last_access":-5,"version":4},"table":"sku_spec","ts":1562990510221,"type":"INSERT"}
offset: 105 position: 124088 CreateTime: 1563000701957 isvalid: true keysize: -1 valuesize: 1129 magic: 2 compresscodec: NONE producerId: -1 producerEpoch: -1 sequence: -1 isTransactional: false headerKeys: [] payload: {"data":[{"id":"28105","category_code":"030501","category_name":"","material_code":"0305010002","material_name":"","code":"03050100020184","name":"18*2200*9200","disabled":"0","status":"0","creator_id":"409987","create_time":"1563000701727","updator_id":"409987","update_time":"1563000701723","last_access":"1563000701727","version":"0"}],"database":"sku","es":1563000701000,"id":265,"isDdl":false,"mysqlType":{"id":"bigint(20) unsigned","category_code":"varchar(20)","category_name":"varchar(100)","material_code":"varchar(20)","material_name":"varchar(100)","code":"varchar(20)","name":"varchar(100)","disabled":"tinyint(2)","status":"tinyint(2)","creator_id":"bigint(20)","create_time":"bigint(20)","updator_id":"bigint(20)","update_time":"bigint(20)","last_access":"bigint(20)","version":"int(10)"},"old":null,"pkNames":null,"sql":"","sqlType":{"id":-5,"category_code":12,"category_name":12,"material_code":12,"material_name":12,"code":12,"name":12,"disabled":-6,"status":-6,"creator_id":-5,"create_time":-5,"updator_id":-5,"update_time":-5,"last_access":-5,"version":4},"table":"sku_spec","ts":1563000701956,"type":"INSERT"}
offset: 106 position: 124088 CreateTime: 1563000701958 isvalid: true keysize: -1 valuesize: 1129 magic: 2 compresscodec: NONE producerId: -1 producerEpoch: -1 sequence: -1 isTransactional: false headerKeys: [] payload: {"data":[{"id":"28106","category_code":"030501","category_name":"","material_code":"0305010002","material_name":"","code":"03050100020185","name":"18*2200*9250","disabled":"0","status":"0","creator_id":"409987","create_time":"1563000701841","updator_id":"409987","update_time":"1563000701834","last_access":"1563000701841","version":"0"}],"database":"sku","es":1563000701000,"id":265,"isDdl":false,"mysqlType":{"id":"bigint(20) unsigned","category_code":"varchar(20)","category_name":"varchar(100)","material_code":"varchar(20)","material_name":"varchar(100)","code":"varchar(20)","name":"varchar(100)","disabled":"tinyint(2)","status":"tinyint(2)","creator_id":"bigint(20)","create_time":"bigint(20)","updator_id":"bigint(20)","update_time":"bigint(20)","last_access":"bigint(20)","version":"int(10)"},"old":null,"pkNames":null,"sql":"","sqlType":{"id":-5,"category_code":12,"category_name":12,"material_code":12,"material_name":12,"code":12,"name":12,"disabled":-6,"status":-6,"creator_id":-5,"create_time":-5,"updator_id":-5,"update_time":-5,"last_access":-5,"version":4},"table":"sku_spec","ts":1563000701956,"type":"INSERT"}
offset: 107 position: 126425 CreateTime: 1563000701975 isvalid: true keysize: -1 valuesize: 1131 magic: 2 compresscodec: NONE producerId: -1 producerEpoch: -1 sequence: -1 isTransactional: false headerKeys: [] payload: {"data":[{"id":"28105","category_code":"030501","category_name":"","material_code":"0305010002","material_name":"","code":"03050100020184","name":"18*2200*9200","disabled":"0","status":"0","creator_id":"409987","create_time":"1563000701727","updator_id":"409987","update_time":"1563000701723","last_access":"1563000701727","version":"0"}],"database":"sku","es":1563000701000,"id":11595,"isDdl":false,"mysqlType":{"id":"bigint(20) unsigned","category_code":"varchar(20)","category_name":"varchar(100)","material_code":"varchar(20)","material_name":"varchar(100)","code":"varchar(20)","name":"varchar(100)","disabled":"tinyint(2)","status":"tinyint(2)","creator_id":"bigint(20)","create_time":"bigint(20)","updator_id":"bigint(20)","update_time":"bigint(20)","last_access":"bigint(20)","version":"int(10)"},"old":null,"pkNames":null,"sql":"","sqlType":{"id":-5,"category_code":12,"category_name":12,"material_code":12,"material_name":12,"code":12,"name":12,"disabled":-6,"status":-6,"creator_id":-5,"create_time":-5,"updator_id":-5,"update_time":-5,"last_access":-5,"version":4},"table":"sku_spec","ts":1563000701974,"type":"INSERT"}
offset: 108 position: 126425 CreateTime: 1563000701975 isvalid: true keysize: -1 valuesize: 1131 magic: 2 compresscodec: NONE producerId: -1 producerEpoch: -1 sequence: -1 isTransactional: false headerKeys: [] payload: {"data":[{"id":"28106","category_code":"030501","category_name":"","material_code":"0305010002","material_name":"","code":"03050100020185","name":"18*2200*9250","disabled":"0","status":"0","creator_id":"409987","create_time":"1563000701841","updator_id":"409987","update_time":"1563000701834","last_access":"1563000701841","version":"0"}],"database":"sku","es":1563000701000,"id":11595,"isDdl":false,"mysqlType":{"id":"bigint(20) unsigned","category_code":"varchar(20)","category_name":"varchar(100)","material_code":"varchar(20)","material_name":"varchar(100)","code":"varchar(20)","name":"varchar(100)","disabled":"tinyint(2)","status":"tinyint(2)","creator_id":"bigint(20)","create_time":"bigint(20)","updator_id":"bigint(20)","update_time":"bigint(20)","last_access":"bigint(20)","version":"int(10)"},"old":null,"pkNames":null,"sql":"","sqlType":{"id":-5,"category_code":12,"category_name":12,"material_code":12,"material_name":12,"code":12,"name":12,"disabled":-6,"status":-6,"creator_id":-5,"create_time":-5,"updator_id":-5,"update_time":-5,"last_access":-5,"version":4},"table":"sku_spec","ts":1563000701974,"type":"INSERT"}
offset: 109 position: 128766 CreateTime: 1563000702059 isvalid: true keysize: -1 valuesize: 1129 magic: 2 compresscodec: NONE producerId: -1 producerEpoch: -1 sequence: -1 isTransactional: false headerKeys: [] payload: {"data":[{"id":"28107","category_code":"030501","category_name":"","material_code":"0305010002","material_name":"","code":"03050100020186","name":"18*2200*9000","disabled":"0","status":"0","creator_id":"409987","create_time":"1563000701942","updator_id":"409987","update_time":"1563000701939","last_access":"1563000701942","version":"0"}],"database":"sku","es":1563000701000,"id":266,"isDdl":false,"mysqlType":{"id":"bigint(20) unsigned","category_code":"varchar(20)","category_name":"varchar(100)","material_code":"varchar(20)","material_name":"varchar(100)","code":"varchar(20)","name":"varchar(100)","disabled":"tinyint(2)","status":"tinyint(2)","creator_id":"bigint(20)","create_time":"bigint(20)","updator_id":"bigint(20)","update_time":"bigint(20)","last_access":"bigint(20)","version":"int(10)"},"old":null,"pkNames":null,"sql":"","sqlType":{"id":-5,"category_code":12,"category_name":12,"material_code":12,"material_name":12,"code":12,"name":12,"disabled":-6,"status":-6,"creator_id":-5,"create_time":-5,"updator_id":-5,"update_time":-5,"last_access":-5,"version":4},"table":"sku_spec","ts":1563000702059,"type":"INSERT"}
offset: 110 position: 128766 CreateTime: 1563000702159 isvalid: true keysize: -1 valuesize: 1129 magic: 2 compresscodec: NONE producerId: -1 producerEpoch: -1 sequence: -1 isTransactional: false headerKeys: [] payload: {"data":[{"id":"28108","category_code":"030501","category_name":"","material_code":"0305010002","material_name":"","code":"03050100020187","name":"18*2200*9650","disabled":"0","status":"0","creator_id":"409987","create_time":"1563000702091","updator_id":"409987","update_time":"1563000702088","last_access":"1563000702091","version":"0"}],"database":"sku","es":1563000702000,"id":267,"isDdl":false,"mysqlType":{"id":"bigint(20) unsigned","category_code":"varchar(20)","category_name":"varchar(100)","material_code":"varchar(20)","material_name":"varchar(100)","code":"varchar(20)","name":"varchar(100)","disabled":"tinyint(2)","status":"tinyint(2)","creator_id":"bigint(20)","create_time":"bigint(20)","updator_id":"bigint(20)","update_time":"bigint(20)","last_access":"bigint(20)","version":"int(10)"},"old":null,"pkNames":null,"sql":"","sqlType":{"id":-5,"category_code":12,"category_name":12,"material_code":12,"material_name":12,"code":12,"name":12,"disabled":-6,"status":-6,"creator_id":-5,"create_time":-5,"updator_id":-5,"update_time":-5,"last_access":-5,"version":4},"table":"sku_spec","ts":1563000702159,"type":"INSERT"}
offset: 111 position: 131104 CreateTime: 1563000702076 isvalid: true keysize: -1 valuesize: 1131 magic: 2 compresscodec: NONE producerId: -1 producerEpoch: -1 sequence: -1 isTransactional: false headerKeys: [] payload: {"data":[{"id":"28107","category_code":"030501","category_name":"","material_code":"0305010002","material_name":"","code":"03050100020186","name":"18*2200*9000","disabled":"0","status":"0","creator_id":"409987","create_time":"1563000701942","updator_id":"409987","update_time":"1563000701939","last_access":"1563000701942","version":"0"}],"database":"sku","es":1563000701000,"id":11596,"isDdl":false,"mysqlType":{"id":"bigint(20) unsigned","category_code":"varchar(20)","category_name":"varchar(100)","material_code":"varchar(20)","material_name":"varchar(100)","code":"varchar(20)","name":"varchar(100)","disabled":"tinyint(2)","status":"tinyint(2)","creator_id":"bigint(20)","create_time":"bigint(20)","updator_id":"bigint(20)","update_time":"bigint(20)","last_access":"bigint(20)","version":"int(10)"},"old":null,"pkNames":null,"sql":"","sqlType":{"id":-5,"category_code":12,"category_name":12,"material_code":12,"material_name":12,"code":12,"name":12,"disabled":-6,"status":-6,"creator_id":-5,"create_time":-5,"updator_id":-5,"update_time":-5,"last_access":-5,"version":4},"table":"sku_spec","ts":1563000702076,"type":"INSERT"}
offset: 112 position: 132305 CreateTime: 1563000702176 isvalid: true keysize: -1 valuesize: 1131 magic: 2 compresscodec: NONE producerId: -1 producerEpoch: -1 sequence: -1 isTransactional: false headerKeys: [] payload: {"data":[{"id":"28108","category_code":"030501","category_name":"","material_code":"0305010002","material_name":"","code":"03050100020187","name":"18*2200*9650","disabled":"0","status":"0","creator_id":"409987","create_time":"1563000702091","updator_id":"409987","update_time":"1563000702088","last_access":"1563000702091","version":"0"}],"database":"sku","es":1563000702000,"id":11597,"isDdl":false,"mysqlType":{"id":"bigint(20) unsigned","category_code":"varchar(20)","category_name":"varchar(100)","material_code":"varchar(20)","material_name":"varchar(100)","code":"varchar(20)","name":"varchar(100)","disabled":"tinyint(2)","status":"tinyint(2)","creator_id":"bigint(20)","create_time":"bigint(20)","updator_id":"bigint(20)","update_time":"bigint(20)","last_access":"bigint(20)","version":"int(10)"},"old":null,"pkNames":null,"sql":"","sqlType":{"id":-5,"category_code":12,"category_name":12,"material_code":12,"material_name":12,"code":12,"name":12,"disabled":-6,"status":-6,"creator_id":-5,"create_time":-5,"updator_id":-5,"update_time":-5,"last_access":-5,"version":4},"table":"sku_spec","ts":1563000702176,"type":"INSERT"}

**Comment by wpy222** [comment]
offset:  102  position:  117061  CreateTime:  1562922268545  isvalid:  true  keysize:  -1  valuesize:  1132  magic:  2  compresscodec:  NONE  producerId:  -1  producerEpoch:  -1  sequence:  -1  isTransactional:  false  headerKeys:  []  payload:  {"data":[{"id":"28102","category_code":"020301","category_name":"","material_code":"0203010005","material_name":"","code":"02030100050937","name":"7.5*1500*12220","disabled":"0","status":"0","creator_id":"203407","create_time":"1562922268491","updator_id":"203407","update_time":"1562922268488","last_access":"1562922268491","version":"0"}],"database":"sku","es":1562922268000,"id":5846,"isDdl":false,"mysqlType":{"id":"bigint(20)  unsigned","category_code":"varchar(20)","category_name":"varchar(100)","material_code":"varchar(20)","material_name":"varchar(100)","code":"varchar(20)","name":"varchar(100)","disabled":"tinyint(2)","status":"tinyint(2)","creator_id":"bigint(20)","create_time":"bigint(20)","updator_id":"bigint(20)","update_time":"bigint(20)","last_access":"bigint(20)","version":"int(10)"},"old":null,"pkNames":null,"sql":"","sqlType":{"id":-5,"category_code":12,"category_name":12,"material_code":12,"material_name":12,"code":12,"name":12,"disabled":-6,"status":-6,"creator_id":-5,"create_time":-5,"updator_id":-5,"update_time":-5,"last_access":-5,"version":4},"table":"sku_spec","ts":1562922268545,"type":"INSERT"}
offset:  103  position:  121688  CreateTime:  1562922268845  isvalid:  true  keysize:  -1  valuesize:  1132  magic:  2  compresscodec:  NONE  producerId:  -1  producerEpoch:  -1  sequence:  -1  isTransactional:  false  headerKeys:  []  payload:  {"data":[{"id":"28103","category_code":"020301","category_name":"","material_code":"0203010005","material_name":"","code":"02030100050938","name":"7.5*1500*11030","disabled":"0","status":"0","creator_id":"203407","create_time":"1562922268546","updator_id":"203407","update_time":"1562922268543","last_access":"1562922268546","version":"0"}],"database":"sku","es":1562922268000,"id":5847,"isDdl":false,"mysqlType":{"id":"bigint(20)  unsigned","category_code":"varchar(20)","category_name":"varchar(100)","material_code":"varchar(20)","material_name":"varchar(100)","code":"varchar(20)","name":"varchar(100)","disabled":"tinyint(2)","status":"tinyint(2)","creator_id":"bigint(20)","create_time":"bigint(20)","updator_id":"bigint(20)","update_time":"bigint(20)","last_access":"bigint(20)","version":"int(10)"},"old":null,"pkNames":null,"sql":"","sqlType":{"id":-5,"category_code":12,"category_name":12,"material_code":12,"material_name":12,"code":12,"name":12,"disabled":-6,"status":-6,"creator_id":-5,"create_time":-5,"updator_id":-5,"update_time":-5,"last_access":-5,"version":4},"table":"sku_spec","ts":1562922268845,"type":"INSERT"}
offset:  104  position:  122890  CreateTime:  1562990510223  isvalid:  true  keysize:  -1  valuesize:  1128  magic:  2  compresscodec:  NONE  producerId:  -1  producerEpoch:  -1  sequence:  -1  isTransactional:  false  headerKeys:  []  payload:  {"data":[{"id":"28104","category_code":"030303","category_name":"","materia l_code":"0303030002","material_name":"","code":"03030300020072","name":"34*2200*L","disabled":"0","status":"0","creator_id":"300045","create_time":"1562990510110","updator_id":"300045","update_time":"1562990510107","last_access":"1562990510110","version":"0"}],"database":"sku","es":1562990510000,"id":10603,"isDdl":false,"mysqlType":{"id":"bigint(20) unsigned","category_code":"varchar(20)","category_name":"varchar(100)","material_code":"varchar(20)","material_name":"varchar(100)","code":"varchar(20)","name":"varchar(100)","disabled":"tinyint(2)","status":"tinyint(2)","creator_id":"bigint(20)","create_time":"bigint(20)","updator_id":"bigint(20)","update_time":"bigint(20)","last_access":"bigint(20)","version":"int(10)"},"old":null,"pkNames":null,"sql":"","sqlType":{"id":-5,"category_code":12,"category_name":12,"material_code":12,"material_name":12,"code":12,"name":12,"disabled":-6,"status":-6,"creator_id":-5,"create_time":-5,"updator_id":-5,"update_time":-5,"last_access":-5,"version":4},"table":"sku_spec","ts":1562990510221,"type":"INSERT"}
offset: 105 position: 124088 CreateTime: 1563000701957 isvalid: true keysize: -1 valuesize: 1129 magic: 2 compresscodec: NONE producerId: -1 producerEpoch: -1 sequence: -1 isTransactional: false headerKeys: [] payload: {"data":[{"id":"28105","category_code":"030501","category_name":"","material_code":"0305010002","material_name":"","code":"03050100020184","name":"18*2200*9200","disabled":"0","status":"0","creator_id":"409987","create_time":"1563000701727","updator_id":"409987","update_time":"1563000701723","last_access":"1563000701727","version":"0"}],"database":"sku","es":1563000701000,"id":265,"isDdl":false,"mysqlType":{"id":"bigint(20) unsigned","category_code":"varchar(20)","category_name":"varchar(100)","material_code":"varchar(20)","material_name":"varchar(100)","code":"varchar(20)","name":"varchar(100)","disabled":"tinyint(2)","status":"tinyint(2)","creator_id":"bigint(20)","create_time":"bigint(20)","updator_id":"bigint(20)","update_time":"bigint(20)","last_access":"bigint(20)","version":"int(10)"},"old":null,"pkNames":null,"sql":"","sqlType":{"id":-5,"category_code":12,"category_name":12,"material_code":12,"material_name":12,"code":12,"name":12,"disabled":-6,"status":-6,"creator_id":-5,"create_time":-5,"updator_id":-5,"update_time":-5,"last_access":-5,"version":4},"table":"sku_spec","ts":1563000701956,"type":"INSERT"}
offset: 106 position: 124088 CreateTime: 1563000701958 isvalid: true keysize: -1 valuesize: 1129 magic: 2 compresscodec: NONE producerId: -1 producerEpoch: -1 sequence: -1 isTransactional: false headerKeys: [] payload: {"data":[{"id":"28106","category_code":"030501","category_name":"","material_code":"0305010002","material_name":"","code":"03050100020185","name":"18*2200*9250","disabled":"0","status":"0","creator_id":"409987","create_time":"1563000701841","updator_id":"409987","update_time":"1563000701834","last_access":"1563000701841","version":"0"}],"database":"sku","es":1563000701000,"
加载更多

**Comment by uniorder** [comment]
在canal.properties 中加配置：
canal.mq.transaction = true
但是在HA模式下好像会报错，单机不会。

**Comment by jbshen** [comment]
方便把你的配置发出来吗？看一下配置 就知道了

**Comment by wpy222** [comment]
> 方便把你的配置发出来吗？看一下配置 就知道了

CANAL只支持UTF8 么 如果数据库不是UTF8影响么

**Comment by changwenwen** [comment]
楼主问题解决了吗，我这里也是有重复数据的

**Comment by changwenwen** [comment]
> 在canal.properties 中加配置：
> canal.mq.transaction = true
> 但是在HA模式下好像会报错，单机不会。

添加了，没有用

**Comment by agapple** [comment]
尝试最新的主干，修复过批量DML变更时发送kafka数据重复的问题
