### ISSUE TITLE
用SyncES（canal-adapter-elasticsearch-1.1.3）做mysql同步ES，当id字段为stirng的时候出现查询sql文报错

### ISSUE THREAD

**Issue by confuse0** [alibaba/canal#1999]
用canal-adapter-elasticsearch-1.1.3做mysql同步ES时当id字段为stirng的时候出现查询sql文报错，原因如下：
ESTemplate中的updateByQuery方法里面有一行
sql.append("_v.").append(fieldName).append("=").append(value).append(" AND ");
这行里面value有可能是字符串（id字段），所以这里=号拼接的时候，需要判断是不是String，如果是需要加入单引号'，否则执行该sql直接报错!

**Comment by rewerma** [comment]
已经修复
