### ISSUE TITLE
项目使用log4j2与canal的logback发生冲突

### ISSUE THREAD

**Issue by raoshaoquan** [alibaba/canal#200]
`SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/raoshaoquan/.m2/repository/org/slf4j/slf4j-log4j12/1.6.1/slf4j-log4j12-1.6.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/raoshaoquan/.m2/repository/ch/qos/logback/logback-classic/1.1.3/logback-classic-1.1.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
log4j:WARN No appenders could be found for logger (cn.mwee.search.job.misc.MyApplicationContext).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.`

**Comment by agapple** [comment]
canal默认依赖的是slf4j，你可以排除logback来启用你自己的logger选择

**Comment by raoshaoquan** [comment]
谢谢 已解决
