### ISSUE TITLE
用SyncES（canal-adapter-elasticsearch-1.1.3）做mysql同步到ES，报json解析错误！

### ISSUE THREAD

**Issue by confuse0** [alibaba/canal#2000]
用SyncES（canal-adapter-elasticsearch-1.1.3）做mysql同步到ES，报json解析错误，原因如下：
ESSyncUtil类的convertToEsObj方法中做的json解析，源代码如下：
 else if (fieldInfo.startsWith("object")) {
            return JSON.parse(val);
        }
这里，参数val是Object的，令人尴尬的是如果mysql里通过group_concat sql拼接出一个json字符串的时候，这个val返回的是byte[],这个是没法直接toJson的，后来查看源代码发现canal是用getObject获取这列的值的，可能不同mysql驱动getObject返回的类型不一样，出问题的是返回json字符串的byte[]类型，应该考虑到这种兼容情况，要不这种object类型的就用getString方式返回json字符串啥的。
出问题的sql如下，order_merchandises列是配置成object的（objFields:
    order_merchandises: object），具体如下：
select o.id as _id, o.order_status, concat('[', oms.group_oms, ']') as order_merchandises
        from orders o
        left join (
            select om.order_id,
            group_concat(json_object('id', om.id, 'merchandise_id', om.merchandise_id, 'merchant_code', om.merchant_code, 'refund_status', om.refund_status, 'live_refund', om.live_refund))
        as group_oms
            from order_merchandise om group by order_id
        ) as oms on o.id = oms.order_id

**Comment by rewerma** [comment]
暂不支持json类型的字段，如需要用object可以先在sql中拼接json串
