### ISSUE TITLE
同步ES过程中，ES集群全部挂掉，数据会丢失

### ISSUE THREAD

**Issue by okamiv** [alibaba/canal#2007]
同步ES过程中，ES集群全部挂掉，数据会ack掉，es重启后，数据就会丢失这种情况是我配置的问题吗，还是机制就是这样呢

**Comment by okamiv** [comment]
![image](https://user-images.githubusercontent.com/21301874/61344062-827dad00-a882-11e9-9a74-6fd1528235d0.png)

**Comment by fengbird** [comment]
你的配置有问题，默认配置下失败了是没有重试然后直接提交的，你只需将application.yml中的canal.conf.retries的值改为-1即可，这样子当有异常发生时会回滚并一直重试，-1即无限重试

**Comment by rewerma** [comment]
楼上正解
