### ISSUE TITLE
有测试过腾讯云数据库吗

### ISSUE THREAD

**Issue by yangsishu** [alibaba/canal#2010]
## Question

测试腾讯云数据库的时候，已经配置了是row模式，但是读过来的数据却是TRANSACTIONBEGIN；

**Comment by 1044730317** [comment]
哈哈，  请用阿里RDS .

**Comment by agapple** [comment]
腾讯云的没做过测试，可以提供测试的binlog文件

**Comment by liguobao** [comment]
@yangsishu 可以给一份你这边的配置看一下吗？ 我这里没有任何报错但是find start position一直没有成功。
