### ISSUE TITLE
MemoryEventStoreWithBuffer中 MEMSIZE模式下，计算getMemSize的问题

### ISSUE THREAD

**Issue by happyzhouhuan** [alibaba/canal#2014]
在MemoryEventStoreWithBuffer 类中，doGet()方法中
long maxMemSize = batchSize * bufferMemUnit;
            for (; memsize <= maxMemSize && next <= maxAbleSequence; next++) {
                // 永远保证可以取出第一条的记录，避免死锁
                Event event = entries[getIndex(next)];
                if (ddlIsolation && isDdl(event.getEntry().getHeader().getEventType())) {
                    // 如果是ddl隔离，直接返回
                    if (entrys.size() == 0) {
                        entrys.add(event);// 如果没有DML事件，加入当前的DDL事件
                        end = next; // 更新end为当前
                    } else {
                        // 如果之前已经有DML事件，直接返回了，因为不包含当前next这记录，需要回退一个位置
                        end = next - 1; // next-1一定大于current，不需要判断
                    }
                    break;
                } else {
                    entrys.add(event);
                    memsize += calculateSize(event);
                    end = next;// 记录end位点
                }
            }

如果是ddl隔离，且event为ddl事件，且当前第一个就是ddl事件。但是代码中并没有将当前event长度计算在memsize中。当然memsize最终会在getMemSize进行累加。但是在数据doPut过程中，又会将所有的event数据长度计算在putMemSize中，
// 记录一下gets memsize信息，方便快速检索
        if (batchMode.isMemSize()) {
            long size = 0;
            for (Event event : data) {
                size += calculateSize(event);
            }

            putMemSize.getAndAdd(size);
        }
所以是否会出现 putMemSize和getMemSize这个连个数据存在差距，导致放置数据失败。例如出现大批量的ddl事件。
麻烦解答一下

**Comment by agapple** [comment]
issue内容整理清楚一点，不太明白问题
