### ISSUE TITLE
canal同步字段错乱

### ISSUE THREAD

**Issue by hczc** [alibaba/canal#2017]
- [ ] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment

* canal deployer-1.1.3
* mysql 5.6.38-log

### Issue Description
canal 客户端监听server推送的数据，发现字段和值是错乱的，不知道是配置的问题，还是本身的BUG

### Actual behaviour

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```
![image](https://user-images.githubusercontent.com/7982313/61459134-a504e880-a99e-11e9-94a5-5f135159549a.png)

**Comment by rewerma** [comment]
修改过表结构吧？删除position重启一下server
