### ISSUE TITLE
测试环境CPU一直保持100%以上

### ISSUE THREAD

**Issue by snowonbridge** [alibaba/canal#2030]
测试没有太多的数据同步，canal.auto.scan = false一般有哪些配置有影响到CPU的占比呢。
jstack 打印出来的高耗用CPU线程
"main" #1 prio=5 os_prio=0 tid=0x00007f81dc00d000 nid=0x3486 runnable [0x00007f81e553d000]

**Comment by agapple** [comment]
top -Hp 找出最耗cpu的线程
