### ISSUE TITLE
canal启动后如何直接从oss上拉取日志文件开始解析？

### ISSUE THREAD

**Issue by zuiyue** [alibaba/canal#2031]
因为canal的日志位置信息被写入到zookeeper，停止canal一段时间后，再次启动canal，这时候日志里显示找到上次解析的位置点，但是日志文件已经删除，这是canal无法启动。想请教一下，canal能配置启动的时候如果找到位置点，但是mysql已经闪出去的情况下，直接从oss上拉去，直到追上，然后切换为从mysql服务器上获取？

**Comment by zuiyue** [comment]
不好意思，写了一个错误字，是‘删除’，不是‘闪出’

**Comment by zhouluoyang0406** [comment]
最新版本的 可以配置rds的ak和sk 就会拉了
