### ISSUE TITLE
MQ消息投递相关配置问题请教

### ISSUE THREAD

**Issue by shizhengchao** [alibaba/canal#2032]
@agapple 你好，MQ的相关配置可以独立配置到instance级别吗？意思是instance.properties里配置，会覆盖canal.properties里的配置，并且不影响各个instance吗？比如下面的配置:
```properties
canal.mq.servers = 10.204.245.46:9092,10.204.245.46:9093,10.204.245.46:9094
canal.mq.retries = 0
canal.mq.batchSize = 262144
canal.mq.maxRequestSize = 1048576
canal.mq.lingerMs = 100
canal.mq.bufferMemory = 33554432
canal.mq.canalBatchSize = 50
canal.mq.canalGetTimeout = 100
canal.mq.flatMessage = true
canal.mq.compressionType = none
canal.mq.acks = all
```

**Comment by shizhengchao** [comment]
我测试了下，并不行,但是有个问题想提一下需求：

1. canal.serverMode的配置，不能在instance.properties里配置，只能在canal.properties里配置，
这就导致 我想要 保留tcp的功能，同时要有mq的功能比如kafka。

目前我使用的是tcp的投递，然后再发kafka，发kafka的是自己写的，大体配置和canal新增的差不多，然后我想使用canal的新增 的kafka投递功能，但是如果使用了，我不得不舍弃原来的tcp投递然后适配新的kafka模式。所以我想能不能把`canal.serverMode`配置改成 instance级别。

**Comment by yetHandsome** [comment]
我看文档是可以配置多个instance不知道能否满足你描述的情况
在canal.properties定义了canal.destinations后，需要在canal.conf.dir对应的目录下建立同名的文件
比如：
canal.destinations = example1,example2
 这时需要创建example1和example2两个目录，每个目录里各自有一份instance.properties.
 ps. canal自带了一份instance.properties demo，可直接复制conf/example目录进行配置修改
cp -R example example1/
cp -R example example2/

**Comment by yetHandsome** [comment]
可以用多个从来解决吧，就是再起一个cannal 配置不同都server id,没有实测过

**Comment by shizhengchao** [comment]
> 可以用多个从来解决吧，就是再起一个cannal 配置不同都server id,没有实测过

再启一个canal,如果连接同一个zookeeper，就成HA模式了。

**Comment by agapple** [comment]
开两个canal server？
