### ISSUE TITLE
Es Adapter下的case执行出错

### ISSUE THREAD

**Issue by fanmo3yuan** [alibaba/canal#2033]
## Question

`com.alibaba.otter.canal.client.adapter.es.test.sync` 下的测试case执行直接报NullPointerException。
出错行是`esAdapter.getEsSyncService().sync(esSyncConfigs.values(), dml);` 
主要原因是`com.alibaba.otter.canal.client.adapter.es.test.sync.Common.init()` 里对esAdapter的初始化传参问题，`esAdapter.init(outerAdapterConfig, null);`
请问这里的envProperties应该如何定义

**Comment by fengbird** [comment]
这个问题不是报空指针是因为这一行无法获取对应的配置文件，这里有一个拼接 destination  database  table 三者的逻辑，case中给的拼接方式有误，你将拼接逻辑替换为：Map<String, ESSyncConfig> esSyncConfigs = esAdapter.getDbTableEsSyncConfig().get(destination + "_" + database + "-" + table);  就可以了

**Comment by agapple** [comment]
可以提交一个PR
