### ISSUE TITLE
canal 1.1.3 同步mysql5.6 到kafka启动正常，但是kafka没有收到消息

### ISSUE THREAD

**Issue by zhangqiang603zq** [alibaba/canal#2043]
## Question

canal 1.1.3 同步mysql5.6 到kafka启动正常，但是kafka没有收到消息，日志也没有报错。怎么定位问题，谢谢

**Comment by GeekerDream** [comment]
你的filter过滤规则能生效吗？ 我过滤的A库下的A表，结果我改B表也会发消息到mq。你的filter生效吗?

**Comment by zhangqiang603zq** [comment]
canal.instance.filter.regex=.*\\..*  我采用的是默认的配置

**Comment by GeekerDream** [comment]
canal.instance.filter.regex=.\.. 你把这个配置成某库某表，然后你修改其他表或者其他库的表，看看会不会发送到mq，辛苦您测一下，然后告诉我结果。 我也是1.1.3版本，发现这个配置不生效。

**Comment by zhangqiang603zq** [comment]
我改了配置后，还是没有消息

**Comment by zhangqiang603zq** [comment]
转发到kafka的网络配置有问题，已经解决

**Comment by GeekerDream** [comment]
canal.instance.filter.regex=... 你把这个配置成某库某表，然后你修改其他表或者其他库的表，看看会不会发送到mq，辛苦您测一下，然后告诉我结果。 我也是1.1.3版本，发现这个配置不生效。 你那边能测试下吗？
