### ISSUE TITLE
不知道为什么久了后虚拟机会退出

### ISSUE THREAD

**Issue by yetHandsome** [alibaba/canal#2049]
版本: canal 1.1.3 , JDK 1.8 ,MySQL 5.7 
Mac 电脑 vagrant 安装了4台虚拟机 centos7
172.20.10.14 mysql 
172.20.10.15 canal(伪装mysql slave) 
172.20.10.16 canal-client  接收来自canal 的消息
172.20.10.17 kafka

整体运行测试没问题，但是

172.20.10.14、172.20.10.16、172.20.10.17 这3台一直都没有问题，过了一天后仍然正常没有退出
但是172.20.10.15 过了一天就自动退出了，不知道什么原因，期间没有数据变动

**Comment by agapple** [comment]
检查一下linux主机的dmesg日志
