### ISSUE TITLE
instance的lazy启动在HA模式下不成立

### ISSUE THREAD

**Issue by lulu2panpan** [alibaba/canal#205]
在HA模式下，instance的lazy启动不成立。

**首先看CanalController的代码**
for (Map.Entry<String, InstanceConfig> entry : instanceConfigs.entrySet()) {
            final String destination = entry.getKey();
            InstanceConfig config = entry.getValue();
            // 创建destination的工作节点
            if (!config.getLazy() && !embededCanalServer.isStart(destination)) {
                // HA机制启动
                ServerRunningMonitor runningMonitor = ServerRunningMonitors.getRunningMonitor(destination);
                if (!runningMonitor.isStart()) {
                    runningMonitor.start();
                }
            }

```
        if (autoScan) {
            instanceConfigMonitors.get(config.getMode()).register(destination, defaultAction);
        }
    }
```

lazy模式下，ServerRunningMonitor不会启动，那么在zookeeper的/otter/canal/destinations/destination/cluster节点下不会有数据，running节点也不会有数据

**再看ClusterNodeAccessStrategy的代码**
    public SocketAddress nextNode() {
        if (runningAddress != null) {// 如果服务已经启动，直接选择当前正在工作的节点
            return runningAddress;
        } else if (!currentAddress.isEmpty()) { // 如果不存在已经启动的服务，可能服务是一种lazy启动，随机选择一台触发服务器进行启动
            return currentAddress.get(0);// 默认返回第一个节点，之前已经做过shuffle
        } else {
            throw new CanalClientException("no alive canal server");
        }
    }

由于cluster和running节点都不存在，此处会进入else分支，客户端会一直报错，没办法触发laze启动。

**Comment by lulu2panpan** [comment]
个人认为lazy启动是个比较鸡肋的功能，增加了代码的复杂度，性价比不高。
我们内部使用时，完全屏蔽了这种模式，把ClusterNodeAccessStrategy类中的这段代码直接注释掉了
` else if (!currentAddress.isEmpty()) { // 如果不存在已经启动的服务，可能服务是一种lazy启动，随机选择一台触发服务器进行启动
return currentAddress.get(0);// 默认返回第一个节点，之前已经做过shuffle
} `

找不到running节点就直接抛错，免去了无谓的网络交互，使高可用场景下的切换时间尽可能的小

**Comment by lulu2panpan** [comment]
server端改造的话，想到的一个思路是
为ServerRunningMonitor的start方法增加一个 boolean lazy 参数

**Comment by agapple** [comment]
ServerRunningMonitor只是检测running节点的变化，不管是否lazy模式，都会为每个instance创建一个cid节点，这里的currentAddress拿的应该是这个list.

**Comment by agapple** [comment]
看了下代码，目前cid节点的注册是依赖了ServerRunningMonitor.start()方法，逻辑上这里的确会有一点问题

**Comment by lulu2panpan** [comment]
恩   这个可行   monitor的生命周期和instance并不在一条线上 init中只负责启动monitor
这个问题倒是没那么严重，估计lazy也极少有人用

subscribe那个问题建议还是及时处理下，我们在生产环境已经遇见过两次问题了：维护的时候，停掉一台canal-server，另外一台接管instance，然后position重置为几天前的了

**Comment by agapple** [comment]
position为啥会是几天前？第一次subscrite拿到了历史store的数据更新掉了？

**Comment by agapple** [comment]
如有新信息，再reopen该issue
