### ISSUE TITLE
指定binlog文件和位置的问题

### ISSUE THREAD

**Issue by GeekerDream** [alibaba/canal#2050]
## Question

我之前是1.0.24的canal-server，采取的tcp传输。现在要升级1.1.3，换成mq传输数据，但是发现启动的时候把db所有的binlog都发送到了mq里（包括很久之前tcp已经传输过的），这要怎么避免呢？

**Comment by yetHandsome** [comment]
可以配置读取位置
https://github.com/alibaba/canal/wiki/AdminGuide


canal.instance.gtidon | 是否启用mysql gtid的订阅模式 

canal.instance.master.gtid | mysql主库链接时对应的gtid位点

**Comment by agapple** [comment]
LS正解
