### ISSUE TITLE
每隔8s都会发空消息到mq

### ISSUE THREAD

**Issue by GeekerDream** [alibaba/canal#2051]
## Question

我打开log级别为debug，发现canal.log里每隔8s左右都会输出如下三条log，我并没有改变表数据和结构，消息体的空的，导致binlog的positon一直在递增，这是什么情况呢？
![image](https://user-images.githubusercontent.com/22268180/62617966-ad20ca00-b945-11e9-80e6-49cbb3641048.png)

**Comment by cddon** [comment]
我也遇到这种情况，请问你后来是怎么解决的
