### ISSUE TITLE
canal问题ERROR com.alibaba.otter.canal.server.CanalMQStarter - batchId:317 is not the firstly:1

### ISSUE THREAD

**Issue by ZSH9053** [alibaba/canal#2057]
现在是不是我只要开启了canal.mq.partitionHash=.*\\..*:$pk$
如果我投递的表，没有主键，是不是就会爆这个错 
ERROR com.alibaba.otter.canal.server.CanalMQStarter - batchId:317 is not the firstly:1

**Comment by agapple** [comment]
这个报错和主键没关系，针对无主键的问题建议1.1.4版本
