### ISSUE TITLE
SUBSCRIPTION存在bug

### ISSUE THREAD

**Issue by lulu2panpan** [alibaba/canal#206]
直接上SessionHandler的代码段
`case SUBSCRIPTION:
                    Sub sub = Sub.parseFrom(packet.getBody());
                    if (StringUtils.isNotEmpty(sub.getDestination()) && StringUtils.isNotEmpty(sub.getClientId())) {
                        clientIdentity = new ClientIdentity(sub.getDestination(),
                            Short.valueOf(sub.getClientId()),
                            sub.getFilter());
                        MDC.put("destination", clientIdentity.getDestination());
                        embeddedServer.subscribe(clientIdentity);

```
                    // 尝试启动，如果已经启动，忽略
                    if (!embeddedServer.isStart(clientIdentity.getDestination())) {
                        ServerRunningMonitor runningMonitor = ServerRunningMonitors.getRunningMonitor(clientIdentity.getDestination());
                        if (!runningMonitor.isStart()) {
                            runningMonitor.start();
                        }
                    }

                    ctx.setAttachment(clientIdentity);// 设置状态数据
                    NettyUtils.ack(ctx.getChannel(), null);
                } else {
                    NettyUtils.error(401,
                        MessageFormatter.format("destination or clientId is null", sub.toString()).getMessage(),
                        ctx.getChannel(),
                        null);
                }
                break;
```

`

问题代码为：embeddedServer.subscribe(clientIdentity);
instance还没有启动就可以执行subscribe？？？
个人认为正确的逻辑应该是：先启动runningMonitor，再判断instance是否启动，最后再执行subscribe。

按目前的代码逻辑，会产生如下的问题：
1.两台canalserver和两台canalclient正在运行，其中有个instance名称为xxx
2.将xxx的Active置为false，xxx会被release掉，然后触发重新抢占
3.在抢占的过程中，zk上xxx/cluster节点和xxx/running节点的注册是有时间间隔的
4.因为有时间间隔，所以，按照ClusterNodeAccessStrategy的逻辑，canalclient在进行connect时拿到的ip不一定是以后抢占到running节点的那个canalserver的ip
5.即使ip有问题，仍然可以进行connect和subscribe操作，但在get的时候会报错，然后重连
6.虽然重连了，但是subscribe时产生了脏数据，position信息被缓存到metaManager了
7.过了几天xxx处于running状态的那台canal关了，此时slave-canal接管，会启动instance，但是metaManager已经启动过了，postion定位到了几天前
8.悲剧了

备注：
1.此处判断runningMonitor的目的是想触发lazy-start，但是lazy-start在HA模式下不成立，请参见
https://github.com/alibaba/canal/issues/205
2.强烈建议改造一下ClusterNodeAccessStrategy，HA模式下取Address的时候只认running节点，就甭支持lazy了，按现在的设计为了支持lazy徒增了复杂度，导致客户端的高可用切换的时间有时非常长

**Comment by agapple** [comment]
HA模式下的确lazy是一个鸡肋，之前代码配置里有支持，后来默认值改成了false.

**Comment by lulu2panpan** [comment]
恩，即使不是lazy模式，当
1，Active置为false的时候
2，或者，instance重启的时候(autoscan)
会出现只有cluster节点，没有running节点的情况，此时客户端会随机取cluster节点下的一个ip进行重连，而这个ip很可能是本次抢占的slave，那么就会触发subscribe的bug
需要改两处代码：
1、SessionHander中变更【启动runningmonitor】和【调用subscribe】的顺序
2、CanalServerWithEmbedded中的subscribe方法中第一行增加checkStart方法

**Comment by agapple** [comment]
checkStart方法增加会有风险是失败的，即使你SessionHander调用了start方法，走到subscribe方法时可能还没初始化完成

**Comment by agapple** [comment]
我记得以前我是特意去掉的，不知道这个没有checkstart校验，对于你们的影响是？
