### ISSUE TITLE
在开启远程mysql管理instance情况下，首次切换standy会失败

### ISSUE THREAD

**Issue by yc7799** [alibaba/canal#2062]
背景：1.1.3版本下，如题，我使用了远程mysql配置管理，修改mysql中instance配置自动刷新canalserver的instance config，并且开启kafka，flatmessage 投递消息。
描述：当**首次**在mysql中新增一个instance配置后，能正常消费数据，但是停止instance master切换为standby时binlog消费将会停止，并且任何异常。然后重启两台canal-server才能恢复此instance的正常，但假如我再加一个新的instance，这个新的instance将会出现同样的首次问题，我试着改了一点代码，修复了一下，有问题请大佬指出。
![image](https://user-images.githubusercontent.com/29529214/62854780-e9c43b00-bd22-11e9-905f-a845269e6ca8.png)
![image](https://user-images.githubusercontent.com/29529214/62854933-61926580-bd23-11e9-8d8b-7a9dc2afdcfc.png)
![image](https://user-images.githubusercontent.com/29529214/62854954-6d7e2780-bd23-11e9-9f6c-746ca8162290.png)

**Comment by agapple** [comment]
可以考虑提交一个PR
