### ISSUE TITLE
canal 1.1.4-SNAPSHOT register bad local ip in zookeeper

### ISSUE THREAD

**Issue by threedays163** [alibaba/canal#2068]
- [x] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment
wsl Ubuntu

* canal version
canal 1.1.4-SNAPSHOT

* mysql version
5.7.13

### Issue Description
由于我本机上有多个网卡, 以及配置了多个虚拟网络. 而canal在启动时会把自己所在的IP注册在zookeeper中, 经观察发现, canal注册的IP是虚拟网络IP, 或者其他不可用的IP. 将这些网络禁掉后, 只剩下可用的IP后,再次启动, 注册的IP才是对的. 客户端才可以拿到正确的canal server地址. 

### Actual behaviour

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by agapple** [comment]
可以在canal.properties指定ip
