### ISSUE TITLE
请问canal交流群有吗

### ISSUE THREAD

**Issue by janvinal** [alibaba/canal#2069]
## Question

请问官方有canal交流群吗，在哪里呀，能发出来加一下吗

**Comment by letwang** [comment]
QQ群号：679116380 小友不防进来讨论下～
![HookPHP_社区_QQ](https://github.com/letwang/HookPHP/blob/master/public/demo/qq.jpg?raw=true)

**Comment by janvinal** [comment]
能不能不打广告😓

**Comment by ghost068** [comment]
同求，提交issues没响应，希望有个公共交流群。

**Comment by changwenwen** [comment]
> 同求，提交issues没响应，希望有个公共交流群。

 加了群估计一样没响应

**Comment by xuej2s** [comment]
> > 同求，提交issues没响应，希望有个公共交流群。
> 
> 加了群估计一样没响应
https://mp.weixin.qq.com/s/Mu4wG3K8eZWUhrSV9wSGkQ 我整理了一些自己遇到的坑，希望对你有所帮助
