### ISSUE TITLE
canal.adapter-1.1.3 启动失败 无日志输出

### ISSUE THREAD

**Issue by glenn2wang** [alibaba/canal#2073]
## Question

 

启动后无进程存活，
日志目录下无日志文件

启动日志
cd to /data/server/elasearch/canal.adapter/bin for workaround relative path
CLASSPATH :/data/server/elasearch/canal.adapter/bin/../conf:/data/server/elasearch/canal.adapter/bin/../lib/zookeeper-3.4.5.jar:/data/server/elasearch/canal.adapter/bin/../lib/zkclient-0.10.jar:/data/server/elasearch/canal.adapter/bin/../lib/validation-api-2.0.1.Final.jar:/data/server/elasearch/canal.adapter/bin/../lib/tomcat-embed-websocket-8.5.29.jar:/data/server/elasearch/canal.adapter/bin/../lib/tomcat-embed-el-8.5.29.jar:/data/server/elasearch/canal.adapter/bin/../lib/tomcat-embed-core-8.5.29.jar:/data/server/elasearch/canal.adapter/bin/../lib/spring-webmvc-5.0.5.RELEASE.jar:/data/server/elasearch/canal.adapter/bin/../lib/spring-web-5.0.5.RELEASE.jar:/data/server/elasearch/canal.adapter/bin/../lib/spring-tx-5.0.5.RELEASE.jar:/data/server/elasearch/canal.adapter/bin/../lib/spring-security-crypto-5.0.4.RELEASE.jar:/data/server/elasearch/canal.adapter/bin/../lib/spring-orm-5.0.5.RELEASE.jar:/data/server/elasearch/canal.adapter/bin/../lib/spring-jdbc-5.0.5.RELEASE.jar:/data/server/elasearch/canal.adapter/bin/../lib/spring-jcl-5.0.5.RELEASE.jar:/data/server/elasearch/canal.adapter/bin/../lib/spring-expression-5.0.5.RELEASE.jar:/data/server/elasearch/canal.adapter/bin/../lib/spring-core-5.0.5.RELEASE.jar:/data/server/elasearch/canal.adapter/bin/../lib/spring-context-5.0.5.RELEASE.jar:/data/server/elasearch/canal.adapter/bin/../lib/spring-cloud-context-2.0.0.RELEASE.jar:/data/server/elasearch/canal.adapter/bin/../lib/spring-boot-starter-web-2.0.1.RELEASE.jar:/data/server/elasearch/canal.adapter/bin/../lib/spring-boot-starter-tomcat-2.0.1.RELEASE.jar:/data/server/elasearch/canal.adapter/bin/../lib/spring-boot-starter-logging-2.0.1.RELEASE.jar:/data/server/elasearch/canal.adapter/bin/../lib/spring-boot-starter-json-2.0.1.RELEASE.jar:/data/server/elasearch/canal.adapter/bin/../lib/spring-boot-starter-2.0.1.RELEASE.jar:/data/server/elasearch/canal.adapter/bin/../lib/spring-boot-autoconfigure-2.0.1.RELEASE.jar:/data/server/elasearch/canal.adapter/bin/../lib/spring-boot-2.0.1.RELEASE.jar:/data/server/elasearch/canal.adapter/bin/../lib/spring-beans-5.0.5.RELEASE.jar:/data/server/elasearch/canal.adapter/bin/../lib/spring-aop-5.0.5.RELEASE.jar:/data/server/elasearch/canal.adapter/bin/../lib/snappy-java-1.1.7.1.jar:/data/server/elasearch/canal.adapter/bin/../lib/snakeyaml-1.19.jar:/data/server/elasearch/canal.adapter/bin/../lib/slf4j-api-1.7.25.jar:/data/server/elasearch/canal.adapter/bin/../lib/rocketmq-remoting-4.3.0.jar:/data/server/elasearch/canal.adapter/bin/../lib/rocketmq-logging-4.3.0.jar:/data/server/elasearch/canal.adapter/bin/../lib/rocketmq-common-4.3.0.jar:/data/server/elasearch/canal.adapter/bin/../lib/rocketmq-client-4.3.0.jar:/data/server/elasearch/canal.adapter/bin/../lib/protobuf-java-3.6.1.jar:/data/server/elasearch/canal.adapter/bin/../lib/postgresql-42.1.4.jar:/data/server/elasearch/canal.adapter/bin/../lib/ojdbc6-11.2.0.3.jar:/data/server/elasearch/canal.adapter/bin/../lib/netty-tcnative-boringssl-static-1.1.33.Fork26.jar:/data/server/elasearch/canal.adapter/bin/../lib/netty-all-4.1.23.Final.jar:/data/server/elasearch/canal.adapter/bin/../lib/netty-3.2.2.Final.jar:/data/server/elasearch/canal.adapter/bin/../lib/mysql-connector-java-5.1.40.jar:/data/server/elasearch/canal.adapter/bin/../lib/mssql-jdbc-7.0.0.jre8.jar:/data/server/elasearch/canal.adapter/bin/../lib/lz4-java-1.4.1.jar:/data/server/elasearch/canal.adapter/bin/../lib/logback-core-1.2.3.jar:/data/server/elasearch/canal.adapter/bin/../lib/logback-classic-1.2.3.jar:/data/server/elasearch/canal.adapter/bin/../lib/log4j-to-slf4j-2.10.0.jar:/data/server/elasearch/canal.adapter/bin/../lib/log4j-api-2.10.0.jar:/data/server/elasearch/canal.adapter/bin/../lib/kafka-clients-1.1.1.jar:/data/server/elasearch/canal.adapter/bin/../lib/jul-to-slf4j-1.7.25.jar:/data/server/elasearch/canal.adapter/bin/../lib/jsr305-3.0.2.jar:/data/server/elasearch/canal.adapter/bin/../lib/joda-time-2.9.9.jar:/data/server/elasearch/canal.adapter/bin/../lib/jcl-over-slf4j-1.7.25.jar:/data/server/elasearch/canal.adapter/bin/../lib/jboss-logging-3.3.2.Final.jar:/data/server/elasearch/canal.adapter/bin/../lib/javax.annotation-api-1.3.2.jar:/data/server/elasearch/canal.adapter/bin/../lib/jackson-module-parameter-names-2.9.5.jar:/data/server/elasearch/canal.adapter/bin/../lib/jackson-datatype-jsr310-2.9.5.jar:/data/server/elasearch/canal.adapter/bin/../lib/jackson-datatype-jdk8-2.9.5.jar:/data/server/elasearch/canal.adapter/bin/../lib/jackson-databind-2.9.5.jar:/data/server/elasearch/canal.adapter/bin/../lib/jackson-core-2.9.5.jar:/data/server/elasearch/canal.adapter/bin/../lib/jackson-annotations-2.9.0.jar:/data/server/elasearch/canal.adapter/bin/../lib/hibernate-validator-6.0.9.Final.jar:/data/server/elasearch/canal.adapter/bin/../lib/guava-18.0.jar:/data/server/elasearch/canal.adapter/bin/../lib/fastjson-1.2.28.jar:/data/server/elasearch/canal.adapter/bin/../lib/druid-1.1.9.jar:/data/server/elasearch/canal.adapter/bin/../lib/curator-recipes-2.10.0.jar:/data/server/elasearch/canal.adapter/bin/../lib/curator-framework-2.10.0.jar:/data/server/elasearch/canal.adapter/bin/../lib/curator-client-2.10.0.jar:/data/server/elasearch/canal.adapter/bin/../lib/commons-lang3-3.7.jar:/data/server/elasearch/canal.adapter/bin/../lib/commons-lang-2.6.jar:/data/server/elasearch/canal.adapter/bin/../lib/commons-io-2.4.jar:/data/server/elasearch/canal.adapter/bin/../lib/commons-codec-1.11.jar:/data/server/elasearch/canal.adapter/bin/../lib/client-adapter.launcher-1.1.3.jar:/data/server/elasearch/canal.adapter/bin/../lib/client-adapter.common-1.1.3.jar:/data/server/elasearch/canal.adapter/bin/../lib/classmate-1.3.4.jar:/data/server/elasearch/canal.adapter/bin/../lib/canal.protocol-1.1.3.jar:/data/server/elasearch/canal.adapter/bin/../lib/canal.common-1.1.3.jar:/data/server/elasearch/canal.adapter/bin/../lib/canal.client-1.1.3.jar:/data/server/elasearch/canal.adapter/bin/../lib/aliware-apache-rocketmq-cloud-1.0.jar:
cd to /data/server/elasearch/canal.adapter/bin for continue

**Comment by glenn2wang** [comment]
已经解决，原来使用Jdk1.7 修改使用1.8后解决

**Comment by hubaoquan** [comment]
可能是有一个参数错误，去掉启动脚本中该参数就可以了。
Unrecognized VM option 'PrintAdaptiveSizePolicy'
Did you mean '(+/-)UseAdaptiveSizePolicy'? Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
