### ISSUE TITLE
使用canal对接rocketmq时，数据库批量更新，但是canal只能发送1个消息

### ISSUE THREAD

**Issue by stevenlii** [alibaba/canal#2077]
使用canal对接rocketmq时，数据库批量更新，但是canal只能发送1个消息，数据库binlog配置是row模式，使用tcp可以看到收到了多条消息，但是使用mq就只有一条，好奇怪，也不知道怎么排查

**Comment by agapple** [comment]
确认使用了最新的canal版本

**Comment by happyguy1986** [comment]
是不是被canal压缩了

**Comment by stevenlii** [comment]
> 是不是被canal压缩了
确实被压缩了，以为是和tcp一样的一个一条呢
