### ISSUE TITLE
canal同步mysql发现INSERT和UPDATE的表结构不一致

### ISSUE THREAD

**Issue by YuanWeiKang** [alibaba/canal#2079]
- [ ] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment

* canal v1.1.3
* mysql 5.7

### Issue Description
canal同步mysql发现INSERT和UPDATE的表结构不一致

### Actual behaviour

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by agapple** [comment]
问题没描述清楚

**Comment by YuanWeiKang** [comment]
找到原因了，是因为binlog日志开启的是精简模式
