### ISSUE TITLE
Decimal类型处理

### ISSUE THREAD

**Issue by wroldchinalee** [alibaba/canal#2081]
你好，使用canal server1.1.2版本，mysql中decimal类型的数据，假设是decimal(10,2)，mysql中的数值是500.00，通过canal server解析后变为500.0了，少了一位，请问是bug吗，该怎么解决？

**Comment by agapple** [comment]
这个数据是以mysql binlog解析的数据，500.0和500.00只是一个显示精度问题，业务上可自行处理
