### ISSUE TITLE
mq只收到变更列的数据,其他不变的列没收到

### ISSUE THREAD

**Issue by meikunbing** [alibaba/canal#2082]
## Question

mq只收到变更列的数据,其他不变的列没收到
比如我修改了一个字段，mq消息只有这一个字段，其他列都没有

**Comment by agapple** [comment]
检查binlog的image配置，是否为最简化模式

**Comment by meikunbing** [comment]
> 检查binlog的image配置，是否为最简化模式
我在测试环境是好的，我们线上用的腾讯云，我用的都是 row 模式
