### ISSUE TITLE
canal-adapter-1.1.3重复插入

### ISSUE THREAD

**Issue by liuqunqi** [alibaba/canal#2087]
批量的导入数据4W多条数据，触发同步，发现日志adaper日志不断的重复插入前2W条
![image](https://user-images.githubusercontent.com/14833774/63507941-746b1e00-c50b-11e9-9c1a-85d5b943cb36.png)

dataSourceKey: defaultDS
destination: example
groupId: g1
esMapping:
_index: building_message
_type: _doc
_id: _id
sql: "select id as _id,buildingId ,newsId , from message"
commitBatch: 3000

**Comment by rewerma** [comment]
你先用logger适配器输出一遍看看是否正常
