### ISSUE TITLE
org.jboss.netty.channel.ChannelException: Failed to bind to: /ip:11111

### ISSUE THREAD

**Issue by zixcon** [alibaba/canal#2088]
我有一个问题实在不是很明白，docker容器HA部署canal的时候，为了链接注册zk使用宿主机地址，这里使用了canal.ip配置了注册的ip，但是在canal docker服务启动的时候，报错org.jboss.netty.channel.ChannelException: Failed to bind to: /ip:11111。经过排查
// 启动
        if (StringUtils.isNotEmpty(ip)) {
            this.serverChannel = bootstrap.bind(new InetSocketAddress(this.ip, this.port));
        } else {
            this.serverChannel = bootstrap.bind(new InetSocketAddress(this.port));
        }
这段代码在指定ip的时候绑定方式也是指定ip。这里有什么特别的考虑吗？

我的理解是docker内部绑定了port地址，这个port:port经过了映射，那么也就是实际上绑定了宿主机port的映射把。这样的话，直接绑定port就可以了吧，还是有其他考虑？望答疑解惑

**Comment by zixcon** [comment]
这里解释下为什么必须配置ip，因为docker内部网络取值是docker0的地址172.x.x.x这类地址，注册到zk上并没有什么用

**Comment by agapple** [comment]
bind ip主要是为了支持单机多网络ip模式，只监听来自某个ip的请求

你们docker的网络方式都是啥配置？

**Comment by zixcon** [comment]
实测v1.1.4-alpha-2这个版本通过canal.register.ip 参数解决docker容器HA的canal部署问题
