### ISSUE TITLE
canal客户端认为insert\update\delete是DDL语句了

### ISSUE THREAD

**Issue by Mrbug001** [alibaba/canal#211]
如题，今天做了个测试，连接本机mysql，测试insert等语句，客户端example执行后，将insert、update、delete等语句看成了DDL语句，但是，连接开发服务器上的mysql就正常，请问这是为什么呢？

**Comment by Mrbug001** [comment]
找到原因了

**Comment by agapple** [comment]
估计是mysql5.6的rows query log，canal不会转换为sql

**Comment by agapple** [comment]
有具体信息再reopen
