### ISSUE TITLE
Canal最新版1.1.4 还是无法接入阿里云RocketMQ

### ISSUE THREAD

**Issue by GuanLeo** [alibaba/canal#2113]
阿里云管理后台，并没有具体的namespace
报错：
No route info for this topic, NORMAL_MESSAGE

**Comment by agapple** [comment]
需要新建topic吧？

**Comment by guoeq** [comment]
<dependency>
                <groupId>org.apache.rocketmq</groupId>
                <artifactId>rocketmq-client</artifactId>
                <version>4.5.1</version>
            </dependency>
升级mq的版本就可以了

**Comment by GuanLeo** [comment]
> 需要新建topic吧？

应该不是topic的问题，com.alibaba.otter.canal.rocketmq.CanalRocketMQProducer这个类的producer init和send方法我用阿里云的依赖
<groupId>com.aliyun.openservices</groupId>
<artifactId>ons-client</artifactId>
重新实现了一下，目前是没问题了

**Comment by ljz0721cx** [comment]
升级版本后需要将原来的otter中依赖的版本替换掉

**Comment by agapple** [comment]
@guoeq 可以考虑提交一个PR给我

**Comment by agapple** [comment]
我看最新的1.1.4 alpha-2版本，rocketmq版本已经为4.5.2

**Comment by duhenglucky** [comment]
@GuanLeo 能说下是哪里具体有问题吗？看上去是云上服务里面没有新建topic导致的，但是看你的描述不是

**Comment by sunnyfrank** [comment]
![image](https://user-images.githubusercontent.com/21972943/64154947-6a7ae080-ce64-11e9-9c31-4aad5b16cf3b.png)

**Comment by sunnyfrank** [comment]
你可能配置错了
# aliyun ak/sk , support rds/mq
canal.aliyun.accessKey = XXX
canal.aliyun.secretKey = XXX
在这里配置rocketMq的密钥

**Comment by gomcarter** [comment]
> 你可能配置错了
> 
> # aliyun ak/sk , support rds/mq
> canal.aliyun.accessKey = XXX
> canal.aliyun.secretKey = XXX
> 在这里配置rocketMq的密钥

再加上
canal.mq.accessChannel = cloud
canal.mq.servers = 内网接入点
canal.mq.producerGroup = GID_**group（在后台创建）
canal.mq.namespace = rocketmq实例id

**Comment by 521daichen** [comment]
必须是内网接入点吗

**Comment by wzyzdn** [comment]
canal1.1.5+rocketmq启动无任何报错，rocketmq日志也没有，但就是无法创建topic，请问这个是什么原因
