### ISSUE TITLE
HA模式下，如何查看当前读取binlog信息

### ISSUE THREAD

**Issue by ZSH9053** [alibaba/canal#2118]
启动了canal.instance.global.spring.xml = classpath:spring/default-instance.xml
我看日志目录和conf/项目目录下 都没有meta.dat这个文件了

**Comment by chai-zhenhua** [comment]
HA模式下消费位点信息默认记录在ZK上，你可以通过这样获取相关信息
[zk: localhost:2181(CONNECTED) 0] get /otter/canal/destinations/item/1001/cursor
{"@type":"com.alibaba.otter.canal.protocol.position.LogPosition","identity":{"slaveId":-1,"sourceAddress":{"address":"XXX","port":3306}},"postion":{"gtid":"","included":false,"journalName":"mysql-bin.001835","position":469345149,"serverId":1475919189,"timestamp":1567404979000}}
