### ISSUE TITLE
关于binlog离线消费的bug

### ISSUE THREAD

**Issue by lulu2panpan** [alibaba/canal#212]
设计binlog离线消费(LocalBinlogEventParser)的初衷是什么？在阿里内部有没有大批量使用过这个功能？
我们在尝试使用的过程中，发现有很多问题，如：
1、离线消费时tableMetaCache为null，构造出来的event不带元数据，这样的event应该是没法儿用
2、事件解析也存在bug
      \* 比如LocalBinLogConnection中的dump方法，被注释的代码才是正确的代码
      \* LocalBinLogConnection中第二个dump方法，应该增加decoder.handle(LogEvent.FORMAT_DESCRIPTION_EVENT);语句，否则((QueryLogEvent) event).getQuery()返回的字符串带乱码
      \* local模式下获取不到ROTATE_EVENT类型的事件，导致构造的event的binlogFileName始终都是mysql-bin.000001

**Comment by agapple** [comment]
LocalBinlogEventParser主要用来做日志重发解析用的，内部用的少.

**Comment by agapple** [comment]
已有人提交PR解决
