### ISSUE TITLE
canal投递kafka消息(FlatMessage) 可能会存在同一分区消息乱序。

### ISSUE THREAD

**Issue by yangyiweigege** [alibaba/canal#2124]
版本：1.1.4-SNAPSHO
描述:canal投递kafka(库.表 多分区模式)  动态topic 单表数据 按照id分片 投递消息为flatMessage可能会存在 同一个topic下同一分区消息乱序，核心代码如下:
// 发送扁平数据json
            List<FlatMessage> flatMessages = MQMessageUtils.messageConverter(message);
            List<ProducerRecord> records = new ArrayList<ProducerRecord>();
            if (flatMessages != null) {
                for (FlatMessage flatMessage : flatMessages) {
                    if (canalDestination.getPartitionHash() != null && !canalDestination.getPartitionHash().isEmpty()) {
                        FlatMessage[] partitionFlatMessage = MQMessageUtils.messagePartition(flatMessage,
                            canalDestination.getPartitionsNum(),
                            canalDestination.getPartitionHash());
                        int length = partitionFlatMessage.length;
                        for (int i = 0; i < length; i++) {
                            FlatMessage flatMessagePart = partitionFlatMessage[i];
                            if (flatMessagePart != null) {
                                records.add(new ProducerRecord<String, String>(topicName,
                                    i,
                                    null,
                                    JSON.toJSONString(flatMessagePart, SerializerFeature.WriteMapNullValue)));
                            }
                        }
                    } else {
                        final int partition = canalDestination.getPartition() != null ? canalDestination.getPartition() : 0;
                        records.add(new ProducerRecord<String, String>(topicName,
                            partition,
                            null,
                            JSON.toJSONString(flatMessage, SerializerFeature.WriteMapNullValue)));
                    }

                    // 每条记录需要flush
                    produce(topicName, records, true);
                    records.clear();
                }
            }
投递kafka端代码:
 // 异步发送，因为在partition hash的时候已经按照每个分区合并了消息，走到这一步不需要考虑单个分区内的顺序问题
            for (ProducerRecord record : records) {
                futures.add(producerTmp.send(record));
            }

以上两处代码存在一个逻辑漏洞:
假设此处十条flatMessage， 这边逻辑是for循环对 单条flatMessage进行了分区,并非十条flatMessage的分区,最终拼接的发送顺序可能如下:
flatMessage1[0],flatMessage1[1],flatMessage2[0],flatMessage2[1]........
然后kafka异步发送这个序列（kafka底层是nio发送 并不会阻塞） ，最终到达到kafka服务端 可能会是如下顺序:
flatMessage2[0],flatMessage2[1],flatMessage1[0],flatMessage1[1]........
然后 同一分区 顺序 就乱了------

建议：把这十条 flatMessage  进行统一分区   再异步提交  或者 单条分区完成后 就同步提交一次。

**Comment by agapple** [comment]
kafka底层会按照分区做batch批量提交，同一个分区batch的合并过程是上层的for循环顺序，不同分区之间顺序无法保证

**Comment by yangyiweigege** [comment]
> kafka底层会按照分区做batch批量提交，同一个分区batch的合并过程是上层的for循环顺序，不同分区之间顺序无法保证

但这边 kafka提交 有个 canal.mq.lingerMs = 1参数 假如  for循环 中间发生了两次异步发送。由于网络问题 两次发送的数据包 顺序是有可能乱掉的 会间接导致一个分区内的数据 乱序。
![图片](https://user-images.githubusercontent.com/23202824/64097664-78166480-cd97-11e9-8c59-e864641972ac.png)

**Comment by yangyiweigege** [comment]
非 flatMessage不会有这个问题 是因为  上层合并后 最终 只会产生 几条数据 都落在不同分区。最终可能就是 1 2 3 异步发送 。不会影响同一分区顺序。  但是flatMessage 上层合并完后 结果可能 会是 1 2 3 3 2 1 1 2 3 多条分区数据。。。最后 kafka send提交的时候。 如果触发了多次(canal.mq.lingerMs)..就会出问题了。

**Comment by agapple** [comment]
可以看下kafka的Sender代码：
1.  异步消息会暂存为ProducerBatch
2.  同一个kafka node的消息会是一个顺序发送，在开了max.in.flight.requests.per.connection=1参数只有，会通过RecordAccumulator.muted做了异步互斥

**Comment by yangyiweigege** [comment]
那我是不是可以理解为 如果我不设置 max.in.flight.requests.per.connection=1(默认是5), 这段代码 中途发生过两次 发送  比如 a  b 两批。但在网络中 并不能确保 a b到达 broker的顺序。。就乱序了？

**Comment by agapple** [comment]
是的，max.in.flight可以确保每个分区只有一个request

**Comment by yangyiweigege** [comment]
但 canal wiki中并没有max.in.flight.requests.per.connection可以配置，然后CanalKafkaProducer类的初始化kafka连接中。也没有配置这个参数（默认值是5）。。所以我感觉这边的代码 应该要对 flatMessage 做一个整体分区（参照非flatMessage模式，而不是for循环 单条分区） 最终合并结果 只会是 几个不同的分区。无论怎么发送 都不影响最终结果。。。才能保证单分区顺序不乱吧。。。。

**Comment by agapple** [comment]
![image](https://user-images.githubusercontent.com/834743/64225477-2fcd8280-cf0e-11e9-8d74-f7781a665468.png)

目前是代码里写死l了

**Comment by yangyiweigege** [comment]
好吧....这样的话的确是没有问题...这个配置我看漏了......





------------------ 原始邮件 ------------------
发件人: agapple <notifications@github.com&gt;
发送时间: 2019年9月4日 12:20
收件人: alibaba/canal <canal@noreply.github.com&gt;
抄送: yangyiweigege <2873824885@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[alibaba/canal] canal投递kafka消息(FlatMessage) 可能会存在同一分区消息乱序。 (#2124)





 
目前是代码里写死l了
