### ISSUE TITLE
canal日志写满磁盘

### ISSUE THREAD

**Issue by wuxingye** [alibaba/canal#2127]
- [ ] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment

* canal version
1.1.3
* mysql version
5.7

### Actual behaviour

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

![image](https://user-images.githubusercontent.com/9107702/64089357-48a42f80-cd78-11e9-8950-1647fdc79d70.png)

**Comment by agapple** [comment]
1.  logback默认开启了stdout.log
2. startup.sh标准输出指向了canal/canal.log，导致logback滚动时标准输出还会写到已经被删除的文件句柄了

1.1.4已经调整
