### ISSUE TITLE
canal admin 添加instance 异常

### ISSUE THREAD

**Issue by liyong945** [alibaba/canal#2129]
![image](https://user-images.githubusercontent.com/13311296/64124784-8e91df80-cdda-11e9-9686-b9059ee83fc4.png)
server状态是OK的，添加instance报异常：
![image](https://user-images.githubusercontent.com/13311296/64124835-b1bc8f00-cdda-11e9-8eff-7a48dae84d2e.png)
没有instance任务日志，应该是启动instance 异常
我看server端报异常：
2019-09-02 23:33:53.203 [New I/O server worker #1-6] ERROR com.alibaba.otter.canal.common.utils.FileUtils - Negative seek offset
java.io.IOException: Negative seek offset
	at java.io.RandomAccessFile.seek(RandomAccessFile.java:555) ~[na:1.8.0_112]
	at com.alibaba.otter.canal.common.utils.FileUtils.readFileFromOffset(FileUtils.java:32) [canal.common-1.1.4.jar:na]
	at com.alibaba.otter.canal.common.utils.FileUtils.readFileFromOffset(FileUtils.java:15) [canal.common-1.1.4.jar:na]

**Comment by agapple** [comment]
canal/canal.log日志里看一下，是否有收到instance的启动配置变化

**Comment by liyong945** [comment]
![image](https://user-images.githubusercontent.com/13311296/64139985-713e2f00-ce35-11e9-8d76-4a145a6348dd.png)
上面就是canal日志
![image](https://user-images.githubusercontent.com/13311296/64140166-1e18ac00-ce36-11e9-964e-2f5ea3993a42.png)

server 启动后，就报这个了。

**Comment by agapple** [comment]
这是查询空日志文件的报错

**Comment by liyong945** [comment]
> 这是查询空日志文件的报错

验证确实是的，我绑定机器上的example instance是OK的，但是我无法通过admin web控制example instance;
![image](https://user-images.githubusercontent.com/13311296/64144637-05b18d00-ce48-11e9-9459-f7ecbeca1c47.png)
我看文档，admin是可以用过web来控制instance的，但是我这边看无法控制。
请帮忙分析下；
就是当前只能监控到本地起到instance状态无法通过admin 来管理本地的instance；同时通过admin创建的instance也无法启动;server同样的问题。

**Comment by rewerma** [comment]
你的server远程主配置里面
```
canal.auto.scan = true
```

必须为true，还有canal.destinations 配置不需要设置

**Comment by gumutianqi** [comment]
同楼主的问题，在 canal-admin 里面新建 Instance ，配置目录以及配置文件并没有同步到canal-server 里面，并且点击查看日志，server 方抛出找不到日志文件的异常，也是由于日志目录和日志文件没有同步创建的原因。

**Comment by rewerma** [comment]
server的配置使用canal_local.properties覆盖canal.properties，你可能是直接使用了canal.properties了。
我这边测试过是正常的

**Comment by agapple** [comment]
请把启动脚本改为 sh startup.sh local 或者删除老的canal.properties配置文件

**Comment by liyong945** [comment]
> 请把启动脚本改为 sh startup.sh local 或者删除老的canal.properties配置文件

感谢，这样操作后OK了。

**Comment by gumutianqi** [comment]
@agapple Docker 启动的 canal-server 怎么把启动脚本改为：sh startup.sh local

**Comment by agapple** [comment]
只要指定canal.admin.manager值，就会自动选择sh startup.sh local进行启动

**Comment by basebase** [comment]
我也遇到了，上面都没解决，尴尬啊。1.1.4

**Comment by cnn007** [comment]
> 只要指定canal.admin.manager值，就会自动选择sh startup.sh local进行启动

sh run.sh -e canal.admin.manager=ecsip:8089 \
         -e canal.admin.port=11110 \
         -e canal.port=11121 \
         -e canal.admin.user=admin \
         -e canal.admin.passwd=4ACFE3202A5FF5CF467898FC58AAB1D615029441
1.1.5 docker，还是同样的问题。日志文件找不到。
