### ISSUE TITLE
请问如何同步mysql经纬度字段数据至es的geo_point型数据

### ISSUE THREAD

**Issue by xhx1304** [alibaba/canal#2132]
请问如何同步mysql经纬度字段数据至es的geo_point型数据？
试过如下结构但是直接sql报错
s.latitude as location.lat,s.longitude AS location.lon,

**Comment by xmuyoucai** [comment]
select ... concat(IFNULL(a.latitude, 0), ',', IFNULL(a.longitude, 0)) AS location, ...

**Comment by xhx1304** [comment]
I had solve the problem,thank you all the same!


------------------ 原始邮件 ------------------
发件人: "Jeary Li"<notifications@github.com>;
发送时间: 2019年9月9日(星期一) 中午11:45
收件人: "alibaba/canal"<canal@noreply.github.com>;
抄送: "为何不可"<1587211986@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [alibaba/canal] 请问如何同步mysql经纬度字段数据至es的geo_point型数据 (#2132)




select ... concat(IFNULL(a.latitude, 0), ',', IFNULL(a.longitude, 0)) AS location, ...
