### ISSUE TITLE
页面和系统日志都报错不能为空

### ISSUE THREAD

**Issue by ZSH9053** [alibaba/canal#2138]
Caused by: com.alibaba.otter.canal.common.CanalException: requestGet for canal config error: Error[Column 'modified_time' cannot be null]
![image](https://user-images.githubusercontent.com/42639504/64165575-efbbc080-ce77-11e9-8c97-a4266120031a.png)

**Comment by rewerma** [comment]
你建表不是用的项目里提供的脚本吧：
```
-- ----------------------------
-- Table structure for canal_cluster
-- ----------------------------
DROP TABLE IF EXISTS `canal_cluster`;
CREATE TABLE `canal_cluster` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `name` varchar(63) NOT NULL,
  `zk_hosts` varchar(255) NOT NULL,
  `modified_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

 **`modified_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE**

**Comment by ZSH9053** [comment]
其实 是 explicit_defaults_for_timestamp 改成0就好了 mysql 5.7

**Comment by jerrunning** [comment]
> 你建表不是用的项目里提供的脚本吧：
> 
> ```
> -- ----------------------------
> -- Table structure for canal_cluster
> -- ----------------------------
> DROP TABLE IF EXISTS `canal_cluster`;
> CREATE TABLE `canal_cluster` (
>   `id` bigint(20) NOT NULL AUTO_INCREMENT,
>   `name` varchar(63) NOT NULL,
>   `zk_hosts` varchar(255) NOT NULL,
>   `modified_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
>   PRIMARY KEY (`id`)
> ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
> ```
> 
> **`modified_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE**

用了项目提供的脚本建立依旧还是报这个错，怎么解决

**Comment by jerrunning** [comment]
> 你建表不是用的项目里提供的脚本吧：
> 
> ```
> -- ----------------------------
> -- Table structure for canal_cluster
> -- ----------------------------
> DROP TABLE IF EXISTS `canal_cluster`;
> CREATE TABLE `canal_cluster` (
>   `id` bigint(20) NOT NULL AUTO_INCREMENT,
>   `name` varchar(63) NOT NULL,
>   `zk_hosts` varchar(255) NOT NULL,
>   `modified_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
>   PRIMARY KEY (`id`)
> ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
> ```
> 
> **`modified_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE**

在把modified_time数据库改成null之后才能创建集群，但是在之后的倒入配置时又报了modified_time不能为null的错

**Comment by jerrunning** [comment]
> 其实 是 explicit_defaults_for_timestamp 改成0就好了 mysql 5.7

mysql5.6有好的解决方法吗，你提供的方法5.6用不了
