### ISSUE TITLE
v1.1.4中canal/canal-admin镜像 账号密码设置无效

### ISSUE THREAD

**Issue by Wandering** [alibaba/canal#2139]
镜像中设置账号密码无效,追踪发现,自带数据库中canal_user中的数据不跟随设置变化

**Comment by agapple** [comment]
镜像里传入的参数，不是用来修改webUI登录的密码的，而是用来和canal-server之间做ACL交互的。

canal-admin/canal-server之间，会有一个双向的ACL机制，去互相验证双方是否是受信任的
