### ISSUE TITLE
canal 一个server怎么能监听一个数据库的不同表？

### ISSUE THREAD

**Issue by JoeyFan** [alibaba/canal#214]
canal 一个server怎么能监听一个数据库的不同表？复制多份example文件夹，然后配置文件里面分别配置不同的连接表信息？麻烦作者看看有没有好的解决方案？

**Comment by agapple** [comment]
一个配置里写多张表的匹配正则

**Comment by JoeyFan** [comment]
@agapple  可以弄个配置的例子给我看看吗，wiki里也没有相关文档，我这一头雾水。
