### ISSUE TITLE
cancal1.1.4版本，配置canal_admin报错

### ISSUE THREAD

**Issue by csoftware** [alibaba/canal#2142]
- [ ] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment

* canal version 1.1.4
* mysql version 5.7

### Issue Description
cancal1.1.4版本，配置canal_admin报错

### Steps to reproduce
1.配置启动成功cancal_admin，配置yml的端口为3034
2.cancal_server里用使用canal_local.properties的配置覆盖canal.properties，然后 sh bin/startup.sh 

### Expected behaviour
预期cancal_server启动成功，但报错了
### Actual behaviour
**以下是我的预猜原因:**
cancal_server启动的时候会发送http://127.0.0.1:3034/api/v1/config/server_polling?ip=127.0.0.1&port=11110&md5&register=1&cluster，但此时报错，原因是没有指定header的user和passwd

If there is an exception, please attach the exception trace:

```
2019-09-04 10:16:43.629 [main] ERROR com.alibaba.otter.canal.deployer.CanalLauncher - ## Something goes wrong when starting up the canal Server:
com.alibaba.otter.canal.common.CanalException: load manager config failed.
Caused by: com.alibaba.otter.canal.common.CanalException: requestGet for canal config error: canal.properties config is empty
```

**Comment by csoftware** [comment]
已解决

**Comment by MengyouEryi** [comment]
> 已解决

怎么解决的我也是这个错

**Comment by cslingjun** [comment]
> 已解决

同问 ，怎么解决的呀

**Comment by sudo5zzb** [comment]
配置文件加上
canal.admin.register.auto = true
canal.admin.register.cluster = xxx
即可

**Comment by hcnysa** [comment]
补充一点，
如果你是如下步骤也会有此问题
1. 先在admin界面创建了集群
2. 在canal-server端使用canal_local.properties 覆盖了 canal.properties
3. 启动canal-server，这样的步骤也会报同样的错误

---
解决办法：
出现这个问题主要是因为你覆盖了 canal.properties，但是又没有在admin界面中配置模版导致的，先要在admin配置模板后，再覆盖server本地配置

**Comment by sixleaves** [comment]
国内搞技术的真是一点分享精神都没有,已解决也不说下杂解决

**Comment by c0609003** [comment]
1、canal_local.properties设置canal.admin.register.cluster = xxx
2、admin界面创建xxx同名cluster
3、admin 集群管理->操作->主配置->载入模板->保存
启动canal

**Comment by asd51731** [comment]
我嚓，墙裂建议把这个issue写到wiki里面去，写好了怎么操作，这个操作快给我整崩了

**Comment by good-good** [comment]
我也遇到了类似的问题，但是我的前提条件有点不一样：
我配置了HA之后直接编辑的 conf/canal.properties
canal.admin.manager = hadoop102:8089
# admin auto register
canal.admin.register.auto = true
canal.admin.register.cluster =
server启动时也会报错 example config is not found 但是server能起来，但是HA无效了。
解决方案：
放弃在 conf/canal.properties的修改，直接在UI界面增加集群并在集群中配置server

**Comment by simonkuang** [comment]
> 我也遇到了类似的问题，但是我的前提条件有点不一样：
> 我配置了HA之后直接编辑的 conf/canal.properties
> canal.admin.manager = hadoop102:8089
> 
> # admin auto register
> canal.admin.register.auto = true
> canal.admin.register.cluster =
> server启动时也会报错 example config is not found 但是server能起来，但是HA无效了。
> 解决方案：
> 放弃在 conf/canal.properties的修改，直接在UI界面增加集群并在集群中配置server

我现在遇到的情况是，在 admin webui 中修改的内容不生效。canal server 没有连接 admin 的动作，直接配置 conf/canal.properties 也没看到效果。log 中没有太多有价值的信息。

**Comment by john8169** [comment]
canal_local.properties配置如下：
# register ip
canal.register.ip = 127.0.0.1

# canal admin config
canal.admin.manager = 127.0.0.1:8089
canal.admin.port = 11110
canal.admin.user = admin
canal.admin.passwd = 4ACFE3202A5FF5CF467898FC58AAB1D615029441
# admin auto register
canal.admin.register.auto = true
canal.admin.register.name = 127.0.0.1
canal.admin.register.cluster = 

cluster要置空
