### ISSUE TITLE
zookeeper记录binlog位置 经常出现找不着的问题 不知道什么原因

### ISSUE THREAD

**Issue by ruixiong-kong** [alibaba/canal#2154]
Received error packet: errno = 1236, sqlstate = HY000 errmsg = Could not find first log file name in binary log index file

**Comment by agapple** [comment]
binlog文件被删除

**Comment by lyl8213** [comment]
我也是这样经常出现，也没有人去删除binlog文件啊

**Comment by lyl8213** [comment]
是不是因为mysql有定时清理

> binlog文件被删除
