### ISSUE TITLE
alter ddl语句写入kafka的topic 分区规则是啥样的

### ISSUE THREAD

**Issue by Bruce2jiang** [alibaba/canal#2158]
你好，我现在遇到一个问题，我们是canal --> kafka ，一个topic 三个partition ,通过hash将dml语句写入某个partition,现在问题是，对ddl语句，里面是没有数据字段使用hash 落到某个partition的，请问对于ddl语句是按照什么规则写入哪个partition的 ？

**Comment by yangyiweigege** [comment]
if (rowChange.getIsDdl()) {
                partitionEntries[0].add(entry);
            }  
具体看类 MQMessageUtils的messagePartition 206行  DDL语句统一写到0分区

**Comment by agapple** [comment]
LS正解

**Comment by roamerway** [comment]
这样又该如何保证ddl与其前后dml的顺序呢？
