### ISSUE TITLE
canal如何支持sql server

### ISSUE THREAD

**Issue by feipengnju** [alibaba/canal#216]
目前，我们有个项目，通过监听binlog变化来更新索引，上线前发现有的客户的数据库用的是sql server的，canal目前不支持sql server，不知道作者有没有思路来支持sql server？

**Comment by feipengnju** [comment]
网上找了下，sql server有个cdc模式（https://msdn.microsoft.com/en-us/library/cc645937.aspx），开启这个模式就能track变更记录

**Comment by agapple** [comment]
对于sql server没啥研究，抱歉

**Comment by YELLOWH** [comment]
> 网上找了下，sql server有个cdc模式（[https://msdn.microsoft.com/en-us/library/cc645937.aspx），开启这个模式就能track变更记录](https://msdn.microsoft.com/en-us/library/cc645937.aspx%EF%BC%89%EF%BC%8C%E5%BC%80%E5%90%AF%E8%BF%99%E4%B8%AA%E6%A8%A1%E5%BC%8F%E5%B0%B1%E8%83%BDtrack%E5%8F%98%E6%9B%B4%E8%AE%B0%E5%BD%95)

老哥，你们实现了canal对接sql server了吗
