### ISSUE TITLE
我使用ES同步数据，一个数据库下所有的消费都只能指定一个dataSourceKey来消费吗

### ISSUE THREAD

**Issue by JDalready** [alibaba/canal#2165]
## Question

我现在监听了一个数据库，有一个唯一的srcDataSources
我在es文件夹下面有多个yaml，我想知道我如何让这些yaml对应相应的数据库里的特定的数据表，谁能解释下吗？因为我不是java开发，看源码很吃力，十分感谢解答

**Comment by wangwengeek** [comment]
配置文件不是可以指定用哪个datasources

**Comment by xmuyoucai** [comment]
你的意思应该是想支持多个库的监听吧，这应该在  Canal 中启动多个实例，Canal 实例可以监听不同的库不同表，通过 canal.instance.filter.regex 和 canal.instance.filter.black.regex 来过滤，然后 Adapter 中就可以定义相应的 srcDataSources 了，有几个就可以定义几个，然后在 ES Adapter 文件中就可以指定连接哪个 DataSource 了

**Comment by JDalready** [comment]
> 配置文件不是可以指定用哪个datasources

不好意思 才回复。  是可以指定datasources  我的意思是想知道如何确定多个yaml对应数据库每张表时，canal如何确定用哪个yaml。我发现canal已经能很正确的找到正确的index并更新，前面是我自己的问题

> 你的意思应该是想支持多个库的监听吧，这应该在 Canal 中启动多个实例，Canal 实例可以监听不同的库不同表，通过 canal.instance.filter.regex 和 canal.instance.filter.black.regex 来过滤，然后 Adapter 中就可以定义相应的 srcDataSources 了，有几个就可以定义几个，然后在 ES Adapter 文件中就可以指定连接哪个 DataSource 了

**Comment by rewerma** [comment]
一个库可以配置多个DS
