### ISSUE TITLE
Canal ES Adapter 连接数据库的目的为何？

### ISSUE THREAD

**Issue by xmuyoucai** [alibaba/canal#2169]
## Question

Canal 连接数据库，读取 BINLOG，将数据推送至 Kafka，ES Adapter 从Kafka 读取数据后是如何操作的呢，连接数据库具体意义是什么呢？

**Comment by yangyiweigege** [comment]
主要是为了连表操作 比如我yml配置的SQL是连表的。写入主表数据的时候 需要 left join从表 补全数据。

**Comment by xmuyoucai** [comment]
> 主要是为了连表操作 比如我yml配置的SQL是连表的。写入主表数据的时候 需要 left join从表 补全数据。

如果是这样，那应该存在问题啊，如果  adapter 处理 binlog 存在时延，可能 left join 的表是新数据，并非当前 binlog 处理位置时的数据，这样 ES 的数据就不对了

**Comment by yangyiweigege** [comment]
> 如果是这样，那应该存在问题啊，如果 adapter 处理 binlog 存在时延，可能 left join 的表是新数据，并非当前 binlog 处理位置时的数据，这样 ES 的数据就不对了

换个角度想想。即便你是订阅了binlog自己处理。遇到了 这种连表的场景。。你代码里还不是要反查一次。。。哪怕你不是订阅binlog处理这种场景。。你业务代码里处理 也会存在那么几十毫秒的延迟把。。。比如网络开销啥的。。所以这种问题。其实意义不大。。。不用过分纠结这个。

**Comment by ynuosoft** [comment]
无需连表操作，ES本身支持upsert操作，哪个表的数据先更新，就更新哪个到ES，通过2个表的ID关联一起

**Comment by xmuyoucai** [comment]
> > 如果是这样，那应该存在问题啊，如果 adapter 处理 binlog 存在时延，可能 left join 的表是新数据，并非当前 binlog 处理位置时的数据，这样 ES 的数据就不对了
> 
> 换个角度想想。即便你是订阅了binlog自己处理。遇到了 这种连表的场景。。你代码里还不是要反查一次。。。哪怕你不是订阅binlog处理这种场景。。你业务代码里处理 也会存在那么几十毫秒的延迟把。。。比如网络开销啥的。。所以这种问题。其实意义不大。。。不用过分纠结这个。

你可能没有明白我的意思<br>
我们假设一下，有 A，B 两张表：A left join B<br>
现在我们修改 A 表数据，然后对 B 表进入更新操作 N 次<br>
如果在以上操作完成后，再启动 adapter 进入 ES 数据同步<br>
按照数据补全逻辑，同步 A 表更新操作时，去 B 表查询数据，查询结果将是第 N 次修改后的数据，但事实上在操作 A 表时，B 表数据并没有发生改变（应该还是 N 次更新操作之前的数据才对），这样将导致 ES 中的数据不一致<br>

**Comment by rewerma** [comment]
中间状态无法保证一致，最终数据保证一致的

**Comment by rewerma** [comment]
而且这里也看情况的，不是所有的join类型的update操作都会去反查sql
