### ISSUE TITLE
canal 客户端接收blob字段解析成 Google Protocol Buffer协议失败

### ISSUE THREAD

**Issue by AnakinSkyW** [alibaba/canal#217]
数据库的表中存的是Google Protocol Buffer协议，然而在canal接收后，解析报错。
想问一下，canal支不支持非基本类型解析

**Comment by agapple** [comment]
blob类型为new String("ISO-8859-1")处理后的字符串，可以通过string.getBytes("ISO-8859-1")还原出来

**Comment by AnakinSkyW** [comment]
谢谢，已经解决
