### ISSUE TITLE
能解释一下这些字段是什么意思吗

### ISSUE THREAD

**Issue by Bruce2jiang** [alibaba/canal#2170]
{"data":[{"id":"103","name_":"77","orders":"88","deml":"99"}],"database":"canal","es":1567995973000,"id":421,"isDdl":false,"mysqlType":{"id":"bigint(14)","name_":"varchar(255)","orders":"varchar(255)","deml":"varchar(255)"},"old":null,"pkNames":["id"],"sql":"","sqlType":{"id":-5,"name_":12,"orders":12,"deml":12},"table":"examplev1","ts":1567995973598,"type":"INSERT"}

**Comment by Bruce2jiang** [comment]
其中 id  sqltype是什么意思，其他我都知道了

**Comment by D-YuLin** [comment]
可以理解为es 是canalserver dumpBinlog的执行时间和ts 是mysql数据dml的时间戳么

**Comment by agapple** [comment]
1. es是指mysql binlog里原始的时间戳，也就是数据原始变更的时间
2. ts是指canal收到这个binlog，构造为自己协议对象的时间

a. canal的消费延迟  =  ts - es
b. 应用消费的延迟 = now - ts
