### ISSUE TITLE
canal client高可用问题

### ISSUE THREAD

**Issue by wroldchinalee** [alibaba/canal#2174]
## Question

在看Canal Client高可用的时候，其中ClientRunningMonitor类里面，有一个成员变量mutex，只有waitForActive()方法调用了mutex.get()方法，其他对mutex变量进行操作的方法都是更新mutex的true/false状态，而waitForActive()方法也没有调用的地方，那么monitor类里面的mutex不是没有作用吗？实际上有用的只是SimpleCanalConnector的mutex的变量，是这样吗？
请作者帮忙解答一下，多谢

**Comment by agapple** [comment]
理解没错
