### ISSUE TITLE
canal adapter的esMapping  es自动生成id问题

### ISSUE THREAD

**Issue by ssjewcw** [alibaba/canal#2177]
配置一：
dataSourceKey: defaultDS
destination: example
groupId: g1
outerAdapterKey: example-es-key
esMapping:
  _index: mytest_user
  _type: doc
  _id:  _id
  upsert: true
  sql: "select a.id as _id,a.name, a.role_id, a.c_time from user a"
  etlCondition: "where a.c_time>={}"
  commitBatch: 3000

如果是上面的，可以成功

现在想让es自动生成id
dataSourceKey: defaultDS
destination: example
groupId: g1
outerAdapterKey: example-es-key
esMapping:
  _index: mytest_user
  _type: doc
  upsert: true
  pk: id
  etlCondition: "where a.c_time>={}"
  commitBatch: 3000

按照文档指示的，注释掉_id，开启pk，但是一直无法插入成功？ 请问如何解决，或者有什么方法？

**Comment by ssjewcw** [comment]
通过在select id后加上前缀

**Comment by EstellaHuang** [comment]
@ssjewcw 遇到了同样的问题：注释掉_id，开启pk，但是一直无法插入成功。请问“在select id后加上前缀”可以再解释下吗？加上什么前缀插入进去的数据_id是es自动生成的id。

**Comment by ssjewcw** [comment]
select a.id as _id,a.name, a.role_id, a.c_time from user a
类似的，es只是想要一个_id，&nbsp;可以在语句的 select uuid什么的+a.id as _id，这样的唯一id来作为_id，大概就是这样




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/canal"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月28日(星期二) 晚上10:52
收件人:&nbsp;"alibaba/canal"<canal@noreply.github.com&gt;;
抄送:&nbsp;"Michael"<370199117@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [alibaba/canal] canal adapter的esMapping  es自动生成id问题 (#2177)





 
@ssjewcw 遇到了同样的问题：注释掉_id，开启pk，但是一直无法插入成功。请问“在select id后加上前缀”可以再解释下吗？加上什么前缀插入进去的数据_id是es自动生成的id。

**Comment by EstellaHuang** [comment]
@ssjewcw  我想用es生成的id，有办法吗？不同通过指定id的形式，虽然用uuid确实也可行

**Comment by ssjewcw** [comment]
es的id也只是uuid，其他的暂时没有试过，给不出意见，你可以再试试




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/canal"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月29日(星期三) 上午10:00
收件人:&nbsp;"alibaba/canal"<canal@noreply.github.com&gt;;
抄送:&nbsp;"Michael"<370199117@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [alibaba/canal] canal adapter的esMapping  es自动生成id问题 (#2177)





 
@ssjewcw  我想用es生成的id，有办法吗？不同通过指定id的形式，虽然用uuid确实也可行

**Comment by EstellaHuang** [comment]
@ssjewcw 好的，谢谢！我看了下adapter里面es的源码，它好像是想去查询id，然后再用id去更新数据的。

**Comment by ssjewcw** [comment]
是的，查询id，然后es决定是插入还是更新




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/canal"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月29日(星期三) 上午10:05
收件人:&nbsp;"alibaba/canal"<canal@noreply.github.com&gt;;
抄送:&nbsp;"Michael"<370199117@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [alibaba/canal] canal adapter的esMapping  es自动生成id问题 (#2177)





 
@ssjewcw 好的，谢谢！我看了下adapter里面es的源码，它好像是想去查询id，然后再用id去更新数据的。

**Comment by EstellaHuang** [comment]
@ssjewcw 嗯嗯，谢啦！

**Comment by EstellaHuang** [comment]
`dataSourceKey: defaultDS
destination: example
groupId:
esMapping:
  _index: spaceuser
  _type: _doc
  _id: _id
  upsert: true
  sql: "select replace(uuid(),'-','') as _id, id, user, create_time as createTime, create_user as createUser, deleted, space_id as spaceId, update_time as updateTime from t_space_user"
  commitBatch: 3000`
你好，我发现我像上面一样用uuid也行不通，你能帮忙指出一下错误吗？
