### ISSUE TITLE
canal-admin里面怎么配置canal server的高可用，在1.13版本有两个canal.properties

### ISSUE THREAD

**Issue by BigData-YC** [alibaba/canal#2180]
## Question

在canal-admin的UI界面怎么，配置集群模式的多个canal.properties

**Comment by agapple** [comment]
一个集群只能有一个canal.properties，如果多个就分多个集群

**Comment by BigData-YC** [comment]
高可用模式下，server有多个， 我就想问主配置的canal.ip怎么填。
# tcp bind ip    hadoop01，hadoop02
canal.ip =
