### ISSUE TITLE
canal-1.1.4中 元数据更新超时

### ISSUE THREAD

**Issue by JustBeginning** [alibaba/canal#2182]
## Question

我把canal服务开启，然后在canal监控的mysql库中创建的一个database和user，然后导致canal服务起不来了 这是什么原因呢  报错是 
java.lang.RuntimeException: java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.TimeoutException: Failed to update metadata after 60000 ms.

**Comment by agapple** [comment]
org.apache.kafka.common.errors.TimeoutException: Failed to update metadata after 60000 ms.
去kafka的社区找寻答案吧

**Comment by BigData-YC** [comment]
兄弟怎么解决的啊？？？

**Comment by zhiyuan192shine** [comment]
> org.apache.kafka.common.errors.TimeoutException: Failed to update metadata after 60000 ms.
> 去kafka的社区找寻答案吧

这个问题还真存在，我的示例正常运行几天就会出现这个问题，Kafka 版本也是 kafka_2.11-1.1.1，版本也完全匹配

**Comment by a526107856** [comment]
我也遇到过这个问题，可以参考下面两点看是否可以解决
1. 使用动态topic生成，要设置canal.mq.topic=
2. kafka端，某些topic无法写入，可以看canal的server端的canal.log看具体是哪个表的同步出了问题，如我的报错如下
2020-04-09 14:28:56.768 [kafka-producer-network-thread | producer-1] WARN  org.apache.kafka.clients.NetworkClient - [Producer clientId=producer-1] Error while fetching metadata with correlation id 219999 : {prism_zz.company_tele_communication_annual_report=INVALID_TOPIC_EXCEPTION}

**Comment by zhiyuan192shine** [comment]
> 我也遇到过这个问题，可以参考下面两点看是否可以解决
> 
> 1. 使用动态topic生成，要设置canal.mq.topic=
> 2. kafka端，某些topic无法写入，可以看canal的server端的canal.log看具体是哪个表的同步出了问题，如我的报错如下
>    2020-04-09 14:28:56.768 [kafka-producer-network-thread | producer-1] WARN  org.apache.kafka.clients.NetworkClient - [Producer clientId=producer-1] Error while fetching metadata with correlation id 219999 : {prism_zz.company_tele_communication_annual_report=INVALID_TOPIC_EXCEPTION}

谢谢，这个问题，https://github.com/alibaba/canal/issues/1716 按照这个 issuse 解决了
