### ISSUE TITLE
解析的log,database为空，显示type都是query，这些都是无效的数据

### ISSUE THREAD

**Issue by Layoomielie** [alibaba/canal#2193]
## Question

![image](https://user-images.githubusercontent.com/43427749/64908260-4656b380-d730-11e9-89d9-d4ab1eafbf6b.png)
语句过滤也不管用，DQL，DDL的语句也会被解析到

**Comment by agapple** [comment]
可以看下wiki的adminGuide，可以有参数过滤掉

**Comment by soutp** [comment]
> 可以看下wiki的adminGuide，可以有参数过滤掉

请教, 是  `canal.instance.filter.query.dml = true ` 这个吗?

**Comment by helpisyou** [comment]
> query

我配置了这个参数也是跟你上面一样的问题，还是出现type: QUERY这种没用的记录
