### ISSUE TITLE
canal正常启动 但是没有数据传

### ISSUE THREAD

**Issue by woniud** [alibaba/canal#2199]
canal 刚开始是没有问题的，可以从 mysql 正常的传数据到 es，但是最近不知道什么情况，先是日志不正常，现在连日志都没有了，但是canal 启动又是很正常的，debug打出来

Exclusions:
-----------

    None

Unconditional classes:
----------------------

    org.springframework.boot.autoconfigure.context.PropertyPlaceholderAutoConfiguration

    org.springframework.boot.autoconfigure.web.embedded.EmbeddedWebServerFactoryCustomizerAutoConfiguration

    org.springframework.cloud.autoconfigure.LifecycleMvcEndpointAutoConfiguration

    org.springframework.boot.autoconfigure.security.reactive.ReactiveSecurityAutoConfiguration

    org.springframework.boot.autoconfigure.context.ConfigurationPropertiesAutoConfiguration

    org.springframework.boot.autoconfigure.info.ProjectInfoAutoConfiguration

但是配置什么的都没有改

**Comment by wangwindlong** [comment]
版本是1.1.5-SNAPSHOT吗，ES版本是7.3.x？我也纠结了好久，是代码里改错了。把adapter的错误信息发出来，看看是不是和我的问题一样。

**Comment by woniud** [comment]
> 版本是1.1.5-SNAPSHOT吗，ES版本是7.3.x？我也纠结了好久，是代码里改错了。把adapter的错误信息发出来，看看是不是和我的问题一样。

我那个是因为 canalserver 的 meta.dat 的版本号不一致导致的   删掉重启就可以了
