### ISSUE TITLE
canal client中Entry未包括操作用户

### ISSUE THREAD

**Issue by chenyishun** [alibaba/canal#220]
一个问题想请教一下。
canal client中Entry未包括操作用户，这个原因是因为binlog里面本身就没有operator user，还是canal没qe去封装解析？mysql binlog包含的具体内容，有相关的资料吗？在网上都说的不全。如果有，我想尝试着增加。

**Comment by ihaolin** [comment]
个人觉得，这部分信息不应该放在binlog里，对于备份完全多余，mysql应该有权限管理相关的处理，操作日志等等。

**Comment by agapple** [comment]
没有在binlog里
