### ISSUE TITLE
邮箱用户名后面有空格会无法连接，建议格式化去掉前后空格处理

### ISSUE THREAD

**Issue by jin544642965** [alibaba/canal#2200]
- [ ] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment

* canal version
* mysql version

### Issue Description
邮箱用户名后面有空格会无法连接，建议做格式化去掉前后空格处理
otter.manager.monitor.email.host = smtp.163.com
otter.manager.monitor.email.username = xxx@163.com
otter.manager.monitor.email.password = xxx

### Actual behaviour

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by agapple** [comment]
可以考虑提交一个MR
