### ISSUE TITLE
canal client获取字段值为空字符串（本身应为null）

### ISSUE THREAD

**Issue by yingchen92** [alibaba/canal#221]
在使用canal的过程中发现一个问题，我在master机器上插入一条数据 比如说insert into test1 values(17,NULL);  在获取canal解析结果
column的值为''空字符串  采用的方法是
String columnValue=column.getValue();   这个是canal框架的问题 还是我本身获取字段值的方法不对。
column.getValue()中column对象是import com.alibaba.otter.canal.protocol.CanalEntry.Column对象

**Comment by agapple** [comment]
column.isNull()使用这个进行判断是否null

**Comment by a522692160** [comment]
我也遇到了这个问题。请问你后面是怎么解决的
