### ISSUE TITLE
使用rocketmq做为消息投递时，多个nameserver直接使用";" 而不是"," ，文档内的不正确

### ISSUE THREAD

**Issue by missops** [alibaba/canal#2215]
使用rocketmq做为消息投递时，多个nameserver直接使用";" 而不是"," ，文档内的不正确

**Comment by yangyiweigege** [comment]
用逗号问题也不大,代码里有做自动转换。。。
        String[] router = StringUtils.split(StringUtils.replace(dynamicTopicConfigs, ",", ";"), ";");
看MQMessageUtils.java matchTopics方法
