### ISSUE TITLE
OSS功能未能配通，请问是哪里出了问题？

### ISSUE THREAD

**Issue by 724686158** [alibaba/canal#2216]
## Question

配置了：
canal.instance.rds.accesskey
canal.instance.rds.secretkey
canal.instance.rds.instanceId
也是用的是canal.instance.master.timestamp作为起始位置。
结果启动报找不到position。
目前从OSS下载binlog的功能是否可用呢？我在v.1.1.4上测试的结果也一样。

**Comment by agapple** [comment]
#2229 ，一个问题

**Comment by liguobao** [comment]
我这边用的是阿里云但是也一样报错....
