### ISSUE TITLE
RDS mysql.mysql ha_health_check表找不到

### ISSUE THREAD

**Issue by iadmirezhe** [alibaba/canal#222]
- 在canal启动时报mysql.mysql ha_health_check表找不到这个错

- 去binlog查看了events，确实有ha_health_check这张表的记录

- 然而，通过show tables等sql语句却查不到这张表

**Comment by agapple** [comment]
估计是表权限的问题

2016-11-14 10:07 GMT+08:00 iadmirezhe <notifications@github.com>:

**Comment by agapple** [comment]
https://github.com/alibaba/canal/commit/96dca0b9e6b6dcc12fc439d2f17d85a4656485df , 特别支持了下阿里云的RDS

**Comment by happyer** [comment]
这个不是➕个过滤就可以了吗

**Comment by agapple** [comment]
是的，现在默认识别为RDS增加了过滤机制

**Comment by iadmirezhe** [comment]
嗯，加了过滤，把mysql过滤掉
