### ISSUE TITLE
fastjson修复了拒绝服务安全问题，建议升级到安全版本

### ISSUE THREAD

**Issue by Kosho1996** [alibaba/canal#2221]
https://github.com/alibaba/fastjson/releases/tag/1.2.60

**Comment by agapple** [comment]
可以提交一个PR给我

**Comment by Walle-w** [comment]
现在是要大于1.2.60啦
https://help.aliyun.com/noticelist/articleid/1060056174.html?spm=5176.12809143.sas.3.224f1PNk1PNkoD

**Comment by Kosho1996** [comment]
> 现在是要大于1.2.60啦
> https://help.aliyun.com/noticelist/articleid/1060056174.html?spm=5176.12809143.sas.3.224f1PNk1PNkoD



> 现在是要大于1.2.60啦
> https://help.aliyun.com/noticelist/articleid/1060056174.html?spm=5176.12809143.sas.3.224f1PNk1PNkoD

实测1.2.60和1.2.61还有些兼容性问题，最好是使用当前1.2.58的安全兼容版本1.2.58.sec06

**Comment by Kosho1996** [comment]
> 现在是要大于1.2.60啦
> https://help.aliyun.com/noticelist/articleid/1060056174.html?spm=5176.12809143.sas.3.224f1PNk1PNkoD

实测1.2.60和1.2.61还有些兼容性问题，最好是使用当前1.2.58的安全兼容版本1.2.58.sec06

**Comment by Kosho1996** [comment]
> 可以提交一个PR给我

ok，已提交
