### ISSUE TITLE
mysql json to es

### ISSUE THREAD

**Issue by zhangxiaoyinghao** [alibaba/canal#2222]
## Question

m.json->>'$.o'  as o  这种SQL映射到es成了[B@6ea0616b  如何是好？

**Comment by zhangxiaoyinghao** [comment]
ESTemplate类的getValFromRS 方法增加如下判断 解决
if(value instanceof byte[]){
            value = new String((byte[])value);
}

**Comment by rewerma** [comment]
暂时不支持json类型的字段，可以先用拼接json串和
```
objFields:
  description: object
```
配置配合来代替

**Comment by Tango-Chen** [comment]
整个json串存入，
`
配置适配器映射文件 conf/es/mytest_user.yml
objFields:
  _obj: object
`
**另外：mysql json对象 ——》 es object
mysql json数组 ——》 es nested**
