### ISSUE TITLE
canal-admin docker  did not start

### ISSUE THREAD

**Issue by OTAKU-Wang** [alibaba/canal#2223]
- [√ ] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [ √] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment

* canal-admin version V1.1.4
* mysql version

### Issue Description

The docker startup shell in the canal-admin docker tutorial can't pull the docker image, you need to fill in the version number.
Canal/canal-admin: v1.1.4

### Steps to reproduce
```
./run_admin.sh -e server.port=8089 \
>  -e canal.adminUser=admin \
>          -e canal.adminPasswd=admin
```
### Expected behaviour
Service start
### Actual behaviour
Service did not start

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by agapple** [comment]
检查一下本机是否存在mysql 3306端口冲突

**Comment by OTAKU-Wang** [comment]
> 检查一下本机是否存在mysql 3306端口冲突

```
Using default tag: latest

Error response from daemon: manifest for canal/canal-admin:latest not found
```
使用docker命令pull 没有latest这个版本 需要填写具体的v1.1.4版本

**Comment by agapple** [comment]
我找个时间推送一下latest版本
