### ISSUE TITLE
mysql double精度问题

### ISSUE THREAD

**Issue by undeadwing** [alibaba/canal#2224]
## Question

请问mysql字段结构为double（11，2），原值为4.56
binlog解析flatmessage，发送到kafka，取出后发现值为4.5600000000000005
有两个同样结构字段都是这种情况，但不是每次都发生，有时是正常的
请问是bug吗

**Comment by undeadwing** [comment]
没有第二位小数的时候都正常

**Comment by undeadwing** [comment]
使用的版本是v1.1.4-alpha-1

**Comment by undeadwing** [comment]
又试了下，45.56就没有问题，4.56就变成4.5600000000000005了，跟值有关

**Comment by agapple** [comment]
mysql和java针对float/double本身存储层面就不是一个精确值，计算机针对float/double误差在0.000001之内的都是正常的

如果需要绝对的精确值，请使用decimal

**Comment by undeadwing** [comment]
> mysql和java针对float/double本身存储层面就不是一个精确值，计算机针对float/double误差在0.000001之内的都是正常的
> 
> 如果需要绝对的精确值，请使用decimal

@agapple 
感谢回复，但是不理解为何使用jdbc查询出的结果没问题，rs.getBytes后转字符串或者double后也是4.56，不会出现4.5600000000000005，是因为mysql或者java特殊处理了吗？binlog是取的mysql实际存储的二进制数据？
