### ISSUE TITLE
canal.instance.master配置未生效

### ISSUE THREAD

**Issue by SHUlibee** [alibaba/canal#223]
您好，请问一下
我配置一下参数（~/conf/example/instance.properties里）
canal.instance.master.journal.name
canal.instance.master.position
canal.instance.master.timestamp
操作 ./bin/stop.sh  ./bin/start.sh 没有生效啊。
例如，我配置 timestamp=1479370130，在这个时间戳之前的update，也在这之后的update都会得到message不知道什么原因啊？

**Comment by agapple** [comment]
时间戳定位默认会回溯60秒
