### ISSUE TITLE
mysql  单个行变更数据过大 导致canal  内存溢出  除了调大canal的jvm参数，还有其他办法吗？

### ISSUE THREAD

**Issue by alibabazxw** [alibaba/canal#2233]

**Comment by alibabazxw** [comment]
比如插入一行含有blob字段的数据，blob字段内容分为250M 发现canal的jvm设置为6G也不行

**Comment by alibabazxw** [comment]
![image](https://user-images.githubusercontent.com/55686587/65410719-aaa70080-de1d-11e9-808d-76e8c73a7a8d.png)报错信息如图

**Comment by wo8335224** [comment]
厉害250M放mysql.....

**Comment by huchenxiao** [comment]
250M，好数字...

**Comment by chenxyz707** [comment]
减小memsize

**Comment by agapple** [comment]
要不考虑配置列的黑名单吧？忽略掉这个大列
