### ISSUE TITLE
请问什么时候能支持es7.X呢，我试了下现在通过canal同步es7.X和mysql不能成功

### ISSUE THREAD

**Issue by zhangxiaofanL** [alibaba/canal#2237]

**Comment by huchenxiao** [comment]
我用es7.x也不成功，我降到6.8.3是成功同步的

**Comment by zhangxiaofanL** [comment]
是的，我之前用的6.5是成功同步的；现在升级到7.3然后就不能同步了

**Comment by huchenxiao** [comment]
> 是的，我之前用的6.5是成功同步的；现在升级到7.3然后就不能同步了

我猜测是因为es7.x移除了索引的_type概念，但canal的es配置文件里会要求写_type

**Comment by rewerma** [comment]
已经支持 https://github.com/alibaba/canal/pull/2246
