### ISSUE TITLE
私有云RDS环境中，想使用oss功能，设置rdsOpenApiUrl遇到困难。

### ISSUE THREAD

**Issue by 724686158** [alibaba/canal#2238]
## Question

     @agapple 您之前告诉我要将rdsOpenApiUrl修改为私有云的OPEN API。
    请问私有云的RDS Open API是怎样一个URL地址，在RDS控制面板上能查到这个值么。

**Comment by agapple** [comment]
联系一下阿里云驻场咨询openapi的地址
