### ISSUE TITLE
请问如何用本地IDE环境调试Canal

### ISSUE THREAD

**Issue by 724686158** [alibaba/canal#2239]
## Question

请问下载了Canal的完整源码后，能否在本地运行调试。
如何可以的话，需要如何做？我发现仅仅在deployer模块下执行bin/startup.sh，并不能使程序运行。
抱歉我不太擅长Java环境，希望能得到大家的帮助。

**Comment by Kosho1996** [comment]
有两种方式，1.在ide里启动canal的Main方法进行debug，2.在canal的jvm参数中添加debug参数，用ide远程debug，这种方便些，可以google Java remote debug

**Comment by changwenwen** [comment]
可以从启动脚本startup.sh中看到，启动类是CanalLauncher.java，由此开始，enjoy~

**Comment by agapple** [comment]
LS正解
