### ISSUE TITLE
client获取不到更新事件

### ISSUE THREAD

**Issue by yjp211** [alibaba/canal#224]
update操作，对应的binlog如下：
![image](https://cloud.githubusercontent.com/assets/3926181/20453252/ab62af26-ae58-11e6-8c27-2c14ea9a441b.png)
connector.getWithoutAck(batchSize)只能获取到TRANSACTIONBEGIN和TRANSACTIONEND，如图
![image](https://cloud.githubusercontent.com/assets/3926181/20453255/c911f216-ae58-11e6-90a4-e77bfee52348.png)

db的配置如下：
```
[mysqld]
pid-file	= /var/run/mysqld/mysqld.pid
socket		= /var/run/mysqld/mysqld.sock
datadir		= /data/mysql
log-error	= /var/log/mysql/error.log
# By default we only accept connections from localhost
#bind-address	= 127.0.0.1
# Disabling symbolic-links is recommended to prevent assorted security risks
symbolic-links=0

#自定义参数
explicit_defaults_for_timestamp
lower_case_table_names=1
max_connections = 2000
# Recommended in standard MySQL setup
sql_mode=NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES
innodb_open_files=65535

max_connect_errors=3500
max_connections=3100
max_user_connections=3000
open_files_limit=65535

#connect_timeout=30
#interactive_timeout=200
#wait_timeout=200

log-bin=mysql-bin #添加这一行就ok
binlog-format=ROW #选择row模式
server_id=1 #配置mysql replaction需要定义，不能和canal的slaveId重复
#skip-name-resolve

innodb_log_file_size=1000M
innodb_buffer_pool_size=2g
innodb_log_buffer_size=10M
innodb_sync_array_size=16
thread_cache_size=256
max_binlog_size=500M
binlog_cache_size=1M
key_buffer_size=8M

#开启慢查询 slow_query_log值为1或on表示开启，为0或off为关闭
slow_query_log=on
#设置慢查询日志放在哪里
slow_query_log_file=mysql-slow
#设置sql执行时间多长为慢查询
long_query_time=2
#表示没有使用索引的sql查询也会记录下来
#log-queries-not-using-indexes

#支持emoji
character-set-server=utf8mb4
collation-server=utf8mb4_unicode_ci
```

**Comment by yjp211** [comment]
经过验证，当canal部署到mysql同一台机器时可以获取到 ROWDATA事件（canal.instance.master.address = 使用 127.0.0.1:3306获 真实地址:3306都可以）

如果使用阿里云rds，这该怎么办- -

**Comment by agapple** [comment]
没这回事，不需要部署到同一台mysql上.  检查下过滤条件，会以client提交的为准

**Comment by yjp211** [comment]
截图红色框住的状况很奇怪， 我检查过两个canal的两个环境，配置是一样。 client是同一个，测试的方式就是通过同一个client切换canal地址

**Comment by agapple** [comment]
debug看看server端的过滤条件，可以试试使用RDS的情况

**Comment by yjp211** [comment]
过滤条件两个环境是一样的 
```
test\\..*
```
这样的格式。
把过滤条件删除（空白），远程部署的canal就可以获取到正常的Event了。但和mysql同机的canal，不受这个影响

**Comment by yjp211** [comment]
进一步对比测试，发现是canal.instance.filter.regex的问题，总结如下：

> 1、没有命中canal.instance.filter.regex的SQL操作，不管canal部署在哪，client只能获取到TRANSACTIONBEGIN和TRANSACTIONEND (为什么没有命中也会获取到这两个事件 也是很不解)
> 2、部署在DB本机和远程的canal，对于regex的解析不同
> > 2.1、和DB同机部署canal的regx=test\\..*和 test.*都能获取到row event
> >  2.2、和DB远程部署的cancal  regx=test\\..*这种方式获取不到row event 但  regx=test.*可以正常工作

**Comment by agapple** [comment]
这个表达式，还要看一下你client调用subscribe里指定的参数
