### ISSUE TITLE
canal server和admin必须部署到一起吗？

### ISSUE THREAD

**Issue by gaoquan6297** [alibaba/canal#2247]
默认配置：
canal.admin.manager = 127.0.0.1:8089
canal.admin.port = 11110
canal.admin.user = admin

问题：
假设admin部署到192.168.1.10
canal server部署到192.168.1.11
那么在canal server的配置文件该怎么配置呢？如果配置成下面这个配置会报错：
canal.admin.manager = 192.168.1.10:8089
canal.admin.port = 11110
canal.admin.user = admin

2019-09-25 20:30:20.918 [main] ERROR com.alibaba.otter.canal.deployer.CanalLauncher - ## Something goes wrong when starting up the canal Server:
java.lang.IllegalArgumentException: managerAddress:192.168.1.10:8089 can't not found config for [192.168.1.10:11110]

**Comment by c5433137** [comment]
你好请问是怎么解决的呢？

**Comment by jdktomcat** [comment]
我也遇到这个问题了

**Comment by demobin8** [comment]
@c5433137 @jdktomcat @gaoquan6297 docker安装举例，修改conf/canal_local.properties，内容为：
```
canal.register.ip = 192.168.1.11
 
canal.admin.manager = 192.168.1.10:8089
canal.admin.port = 11110
canal.admin.user = admin
canal.admin.passwd = 6BB4837EB74329105EE4568DDA7DC67ED2CA2AD9

canal.admin.register.auto = true
canal.admin.register.cluster =
```
然后在bin目录下执行
`sh stop.sh`
`sh startup.sh local`
这样就能连上了
