### ISSUE TITLE
建议增加一个属性，针对根据某一字段hash时，hash算法可以不根据database算出

### ISSUE THREAD

**Issue by acongfly** [alibaba/canal#2248]
## Why you need it?

当我想针对多个数据库中的数据表根据某一个字段比如orderId进行hash到一个topic时候，期望的效果是，如果所有的单子中，比如支付,渠道都有这个orderId的时候，希望hash到同一个partition。但是基于现在的hash算法是对dataBase进行了hashCode,所以不能满足。目前是只有同一个库中可以进行hash到同一个partition.
## How it could be?

是否可以增加一个属性开关，让其自由选择是否需要根据database进行hash.
目前本人做法比较粗暴，对dataBase取hash值时候写死了一个固定值。（MQMessageUtils.java）这个类
![image](https://user-images.githubusercontent.com/4744448/65602501-95290680-dfd6-11e9-9eb1-6557ec798ab8.png)

**Comment by agapple** [comment]
可以考虑提交一个MR给我，引入一个参数标记是否需要使用schema进行hash，默认为true，如果为false的时候只是用对应的pk或者拆分键进行hashcode计算
