### ISSUE TITLE
elasticsearch-adapter  使用 [/etl/索引别名/任务名] 同步数据报NullPointerException

### ISSUE THREAD

**Issue by zhangjiaty** [alibaba/canal#2251]
### environment

* canal version 1.1.4
* mysql version 5.7.23

### Issue Description
elasticsearch-adapter 在使用etl全量同步数据时,使用索引别名,当别名和索引名称不一致时,会报空指针异常.es连接方式使用的rest.
ESConnetion 类中getMapping 方法中获取mappingMetaData时,因为前面获取到的mapping中索引名是真实索引名,从mapping获取时使用的是别名,因此获取不到数据.建议修改获取_mapping方式支持,别名,或者直接从mapping values中获取

**Comment by rewerma** [comment]
sql查询字段别名必须和索引属性名称一致
