### ISSUE TITLE
kafka数据重复

### ISSUE THREAD

**Issue by yuanzhangjun** [alibaba/canal#2255]
## Question

我使用canal-admin1.1.4版本，配置集群下2个server服务，集群下配置了一个Instance写入kafka，结果2个server都会写入一次，导致数据重复。请问server不是作为高可用吗？只有当一台挂掉，才会其另一台，我是配了zookeeper的。

**Comment by agapple** [comment]
你先看一下wiki里的adminGuide，确保一下HA机制是生效的

**Comment by teemoer** [comment]
> 你先看一下wiki里的adminGuide，确保一下HA机制是生效的

十分感谢 我也按照这个在解决了  感谢老哥的热心回复  不亏是大厂的大佬
