### ISSUE TITLE
MQ消息发送性能优化

### ISSUE THREAD

**Issue by agapple** [alibaba/canal#2258]
目前canal原生支持了kafka/rocketmq/rabbitmq的消息发送，目前收到比较多的用户反馈发送MQ消息，存在部分的性能瓶颈，近期会更新一下相关的优化思路供大家参考

ps.  pulsar官方也采用了canal作为默认的connector

**Comment by agapple** [comment]
初步的性能测试 (发送kafka)
--
机器环境：2台24core的物理机，1台部署kafka，1台部署canal (额外部署了kafka-manager/promethues来做监控)

--
测试场景：
1.  关闭flatMessage
2. 开启flatMessage

**Comment by 724686158** [comment]
flatMessage支持一下包含GTID好不好。

**Comment by 724686158** [comment]
现在如果ringbuffer设置太大，消息生产太快，kafkaproducer会OOM。

**Comment by rewerma** [comment]
之前有issue提到多个topic下producer是串行执行的，可以改成并行执行

**Comment by changwenwen** [comment]
目前写kafka是单producer，写入没毛病但是consumer在poll的时候就非常少，每次1条1条的。
改为kafka多producer写入就OK了

**Comment by agapple** [comment]
# rocketmq 优化测试

混合的DML场景测试：(canal server的cpu消耗大概在4个core)

|  场景 |  1个topic + 单分区 | 1个topic+3分区|  2个topic+1分区 | 2个topic+3分区 | 
| -------- | -------- | -------- | -------- | -------- |
| 不开启flatMessage |   29.6k tps (10.71k rps) |  23.3k tps (8.59k rps) |  26.7k tps (9.46k rps) |  21.7k tps (7.66k rps)  |
| 开启flatMessage  |  16.75k tps (6.17k rps)   |  11.91k tps (4.41k rps)  |17.83k tps (6.63k rps)  |  13.24k tps (4.93k rps)  |

**Comment by rewerma** [comment]
同样是开启flatMessage为什么kafka和rocketmq差了一倍多？

**Comment by agapple** [comment]
@rewerma 应该是后面优化的代码，我重新测试对齐了，差距没那么大，但rocketmq还是有一些优势.  
我的判断，rocketmq的性能优势主要在于他是一个可控的batch和并行机制，有直接的batch send接口 以及针对指定分区的并行处理

**Comment by agapple** [comment]
文档可参见：https://github.com/alibaba/canal/wiki/Canal-MQ-Performance

**Comment by luxuebao** [comment]
> 之前有issue提到多个topic下producer是串行执行的，可以改成并行执行

请问如何将Producer改成并行的
