### ISSUE TITLE
Canal Server启动成功后dump时 mysql断开连接

### ISSUE THREAD

**Issue by liqianlove** [alibaba/canal#2259]
environment

  canal version 1.1.4
  mysql version 5.7

Description
   本地部署canal server ，通过日志能看到 start CanalInstances[example] successfully  ,同时zk集群也能看到节点在运行，开始dump数据，但总是在fetch 时候断开连接，以下为部分打印日志：
  ....
  Register slave RegisterSlaveCommandPacket...
  COM_BINLOG_DUMP with position: BinlogDumpCommandPacket[binlogPosition=325139189,slaveServerId=101,binlogFileName=mysqld-bin.000033,command=18]
  common_header_len= 19, number_of_event_types= 38
  DirectLogFetcher - I/O interrupted while reading from client socket java.nio.channels.ClosedByInterruptException: null
    
--

**Comment by JNSimba** [comment]
楼主怎么处理的，我也遇到了这个问题
