### ISSUE TITLE
canal正常启动，instance连不上mysql

### ISSUE THREAD

**Issue by herico516** [alibaba/canal#2261]
## Question

2019-09-27 13:40:24.460 [main] INFO  c.a.otter.canal.instance.core.AbstractCanalInstance - start successful....
2019-09-27 13:40:24.508 [destination = example , address = /192.168.3.94:3306 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - dump address /192.168.3.94:3306 has an error, retrying. caused by 
com.alibaba.otter.canal.parse.exception.CanalParseException: Unknown host
Caused by: java.net.UnknownHostException: serv4-app1: serv4-app1: unknown error
	at java.net.InetAddress.getLocalHost(InetAddress.java:1505) ~[na:1.8.0_65]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.generateUniqueServerId(MysqlEventParser.java:338) ~[canal.parse-1.1.0.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.buildMysqlConnection(MysqlEventParser.java:322) ~[canal.parse-1.1.0.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.buildErosaConnection(MysqlEventParser.java:78) ~[canal.parse-1.1.0.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:167) ~[canal.parse-1.1.0.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_65]
Caused by: java.net.UnknownHostException: serv4-app1: unknown error
	at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method) ~[na:1.8.0_65]
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928) ~[na:1.8.0_65]
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323) ~[na:1.8.0_65]
	at java.net.InetAddress.getLocalHost(InetAddress.java:1500) ~[na:1.8.0_65]
	... 5 common frames omitted
2019-09-27 13:40:24.511 [destination = example , address = /192.168.3.94:3306 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:example[com.alibaba.otter.canal.parse.exception.CanalParseException: Unknown host
Caused by: java.net.UnknownHostException: serv4-app1: serv4-app1: unknown error
	at java.net.InetAddress.getLocalHost(InetAddress.java:1505)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.generateUniqueServerId(MysqlEventParser.java:338)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.buildMysqlConnection(MysqlEventParser.java:322)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.buildErosaConnection(MysqlEventParser.java:78)
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:167)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.UnknownHostException: serv4-app1: unknown error
	at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
	at java.net.InetAddress.getLocalHost(InetAddress.java:1500)
	... 5 more
]
2019-09-27 13:40:24.512 [destination = example , address = /192.168.3.94:3306 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - parse events has an error
java.lang.NullPointerException: null
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.afterDump(MysqlEventParser.java:139) ~[canal.parse-1.1.0.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:295) ~[canal.parse-1.1.0.jar:na]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_65]

`#################################################
#################################################
canal.id= 104
#canal.ip=
canal.port=11111
canal.metrics.pull.port=11112
canal.zkServers=192.168.3.89:2181,192.168.3.91:2181,192.168.3.92:2181,192.168.3.104:2181,192.168.3.105:2181
# flush data to zk
canal.zookeeper.flush.period = 1000
canal.withoutNetty = false
# flush meta cursor/parse position to file
canal.file.data.dir = ${canal.conf.dir}
canal.file.flush.period = 1000
## memory store RingBuffer size, should be Math.pow(2,n)
canal.instance.memory.buffer.size = 16384
## memory store RingBuffer used memory unit size , default 1kb
canal.instance.memory.buffer.memunit = 1024 
## meory store gets mode used MEMSIZE or ITEMSIZE
canal.instance.memory.batch.mode = MEMSIZE

## detecing config
canal.instance.detecting.enable = true
#canal.instance.detecting.sql = insert into retl.xdual values(1,now()) on duplicate key update x=now()
canal.instance.detecting.sql = select 1
canal.instance.detecting.interval.time = 3
canal.instance.detecting.retry.threshold = 3
canal.instance.detecting.heartbeatHaEnable = true

# support maximum transaction size, more than the size of the transaction will be cut into multiple transactions delivery
canal.instance.transaction.size =  1024
# mysql fallback connected to new master should fallback times
canal.instance.fallbackIntervalInSeconds = 60

# network config
canal.instance.network.receiveBufferSize = 16384
canal.instance.network.sendBufferSize = 16384
canal.instance.network.soTimeout = 30

# binlog filter config
canal.instance.filter.druid.ddl = true
canal.instance.filter.query.dcl = false
canal.instance.filter.query.dml = false
canal.instance.filter.query.ddl = false
canal.instance.filter.table.error = false
canal.instance.filter.rows = false
canal.instance.filter.transaction.entry = false

# binlog format/image check
canal.instance.binlog.format = ROW,STATEMENT,MIXED 
canal.instance.binlog.image = FULL,MINIMAL,NOBLOB

# binlog ddl isolation
canal.instance.get.ddl.isolation = false

# parallel parser config
canal.instance.parser.parallel = true
## concurrent thread number, default 60% available processors, suggest not to exceed Runtime.getRuntime().availableProcessors()
#canal.instance.parser.parallelThreadSize = 16
## disruptor ringbuffer size, must be power of 2
canal.instance.parser.parallelBufferSize = 256

# table meta tsdb info
canal.instance.tsdb.enable=true
canal.instance.tsdb.dir=${canal.file.data.dir:../conf}/${canal.instance.destination:}
canal.instance.tsdb.url=jdbc:h2:${canal.instance.tsdb.dir}/h2;CACHE_SIZE=1000;MODE=MYSQL;
canal.instance.tsdb.dbUsername=canal
canal.instance.tsdb.dbPassword=canal

# rds oss binlog account
canal.instance.rds.accesskey =
canal.instance.rds.secretkey =

#################################################
#################################################
canal.destinations= example,cstation_example,user_example,license_example,cstationin_example,cstationout_alarm_example,cstationin_alarm_example,cstationin_second_ocr_example,cstationout_second_ocr_example
# conf root dir
canal.conf.dir = ../conf
# auto scan instance dir add/remove and start/stop instance
canal.auto.scan = true
canal.auto.scan.interval = 5

canal.instance.tsdb.spring.xml=classpath:spring/tsdb/h2-tsdb.xml
#canal.instance.tsdb.spring.xml=classpath:spring/tsdb/mysql-tsdb.xml

canal.instance.global.mode = spring 
canal.instance.global.lazy = false
canal.instance.global.manager.address = 192.168.3.104:1099
#canal.instance.global.spring.xml = classpath:spring/memory-instance.xml
canal.instance.global.spring.xml = classpath:spring/default-instance.xml
#canal.instance.global.spring.xml = classpath:spring/default-instance.xml
`

instance.properties
`#################################################
## mysql serverId , v1.0.26+ will autoGen 
# canal.instance.mysql.slaveId=0

# enable gtid use true/false
canal.instance.gtidon=true

# position info
canal.instance.master.address=192.168.3.94:3306
canal.instance.master.journal.name=
canal.instance.master.position=
canal.instance.master.timestamp=
canal.instance.master.gtid=

# rds oss binlog
canal.instance.rds.accesskey=
canal.instance.rds.secretkey=
canal.instance.rds.instanceId=

# table meta tsdb info
canal.instance.tsdb.enable=true
#canal.instance.tsdb.url=jdbc:mysql://127.0.0.1:3306/canal_tsdb
#canal.instance.tsdb.dbUsername=canal
#canal.instance.tsdb.dbPassword=canal

canal.instance.standby.address=192.168.3.113:3306
#canal.instance.standby.journal.name =
#canal.instance.standby.position = 
#canal.instance.standby.timestamp =
#canal.instance.standby.gtid=

# username/password
canal.instance.dbUsername=canal
canal.instance.dbPassword=canal
canal.instance.connectionCharset=UTF-8
canal.instance.defaultDatabaseName=elupay_user

# table regex
canal.instance.filter.regex=elupay_user\\u_userinfo_issued
# table black regex
canal.instance.filter.black.regex=
#################################################
`
配置文件中未出现主机名，配置中采用IP配置，
mysql用户连接正常，cannal启动能看到zk中生成对应信息，请教各位大牛

canal version: canal.deployer-1.1.0.tar.gz

**Comment by herico516** [comment]
@agapple 求助

**Comment by Guanpx** [comment]
是不是少了某些配置行？

**Comment by gaohanghbut** [comment]
我也遇到了连接不上的情况，求助

**Comment by YuanTianyang** [comment]
> @agapple 求助



> 是不是少了某些配置行？



> 我也遇到了连接不上的情况，求助



> ## Question
> 2019-09-27 13:40:24.460 [main] INFO c.a.otter.canal.instance.core.AbstractCanalInstance - start successful....
> 2019-09-27 13:40:24.508 [destination = example , address = /192.168.3.94:3306 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - dump address /192.168.3.94:3306 has an error, retrying. caused by
> com.alibaba.otter.canal.parse.exception.CanalParseException: Unknown host
> Caused by: java.net.UnknownHostException: serv4-app1: serv4-app1: unknown error
> at java.net.InetAddress.getLocalHost(InetAddress.java:1505) ~[na:1.8.0_65]
> at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.generateUniqueServerId(MysqlEventParser.java:338) ~[canal.parse-1.1.0.jar:na]
> at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.buildMysqlConnection(MysqlEventParser.java:322) ~[canal.parse-1.1.0.jar:na]
> at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.buildErosaConnection(MysqlEventParser.java:78) ~[canal.parse-1.1.0.jar:na]
> at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:167) ~[canal.parse-1.1.0.jar:na]
> at java.lang.Thread.run(Thread.java:745) [na:1.8.0_65]
> Caused by: java.net.UnknownHostException: serv4-app1: unknown error
> at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method) ~[na:1.8.0_65]
> at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928) ~[na:1.8.0_65]
> at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323) ~[na:1.8.0_65]
> at java.net.InetAddress.getLocalHost(InetAddress.java:1500) ~[na:1.8.0_65]
> ... 5 common frames omitted
> 2019-09-27 13:40:24.511 [destination = example , address = /192.168.3.94:3306 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:example[com.alibaba.otter.canal.parse.exception.CanalParseException: Unknown host
> Caused by: java.net.UnknownHostException: serv4-app1: serv4-app1: unknown error
> at java.net.InetAddress.getLocalHost(InetAddress.java:1505)
> at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.generateUniqueServerId(MysqlEventParser.java:338)
> at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.buildMysqlConnection(MysqlEventParser.java:322)
> at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.buildErosaConnection(MysqlEventParser.java:78)
> at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:167)
> at java.lang.Thread.run(Thread.java:745)
> Caused by: java.net.UnknownHostException: serv4-app1: unknown error
> at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
> at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
> at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
> at java.net.InetAddress.getLocalHost(InetAddress.java:1500)
> ... 5 more
> ]
> 2019-09-27 13:40:24.512 [destination = example , address = /192.168.3.94:3306 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - parse events has an error
> java.lang.NullPointerException: null
> at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.afterDump(MysqlEventParser.java:139) ~[canal.parse-1.1.0.jar:na]
> at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:295) ~[canal.parse-1.1.0.jar:na]
> at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_65]
> 
> `#################################################
> ######### common argument	#############
> #################################################
> canal.id= 104
> #canal.ip=
> canal.port=11111
> canal.metrics.pull.port=11112
> canal.zkServers=192.168.3.89:2181,192.168.3.91:2181,192.168.3.92:2181,192.168.3.104:2181,192.168.3.105:2181
> 
> # flush data to zk
> canal.zookeeper.flush.period = 1000
> canal.withoutNetty = false
> 
> # flush meta cursor/parse position to file
> canal.file.data.dir = ${canal.conf.dir}
> canal.file.flush.period = 1000
> 
> ## memory store RingBuffer size, should be Math.pow(2,n)
> canal.instance.memory.buffer.size = 16384
> 
> ## memory store RingBuffer used memory unit size , default 1kb
> canal.instance.memory.buffer.memunit = 1024
> 
> ## meory store gets mode used MEMSIZE or ITEMSIZE
> canal.instance.memory.batch.mode = MEMSIZE
> 
> ## detecing config
> canal.instance.detecting.enable = true
> #canal.instance.detecting.sql = insert into retl.xdual values(1,now()) on duplicate key update x=now()
> canal.instance.detecting.sql = select 1
> canal.instance.detecting.interval.time = 3
> canal.instance.detecting.retry.threshold = 3
> canal.instance.detecting.heartbeatHaEnable = true
> 
> # support maximum transaction size, more than the size of the transaction will be cut into multiple transactions delivery
> canal.instance.transaction.size = 1024
> 
> # mysql fallback connected to new master should fallback times
> canal.instance.fallbackIntervalInSeconds = 60
> 
> # network config
> canal.instance.network.receiveBufferSize = 16384
> canal.instance.network.sendBufferSize = 16384
> canal.instance.network.soTimeout = 30
> 
> # binlog filter config
> canal.instance.filter.druid.ddl = true
> canal.instance.filter.query.dcl = false
> canal.instance.filter.query.dml = false
> canal.instance.filter.query.ddl = false
> canal.instance.filter.table.error = false
> canal.instance.filter.rows = false
> canal.instance.filter.transaction.entry = false
> 
> # binlog format/image check
> canal.instance.binlog.format = ROW,STATEMENT,MIXED
> canal.instance.binlog.image = FULL,MINIMAL,NOBLOB
> 
> # binlog ddl isolation
> canal.instance.get.ddl.isolation = false
> 
> # parallel parser config
> canal.instance.parser.parallel = true
> 
> ## concurrent thread number, default 60% available processors, suggest not to exceed Runtime.getRuntime().availableProcessors()
> #canal.instance.parser.parallelThreadSize = 16
> 
> ## disruptor ringbuffer size, must be power of 2
> canal.instance.parser.parallelBufferSize = 256
> 
> # table meta tsdb info
> canal.instance.tsdb.enable=true
> canal.instance.tsdb.dir=${canal.file.data.dir:../conf}/${canal.instance.destination:}
> canal.instance.tsdb.url=jdbc:h2:${canal.instance.tsdb.dir}/h2;CACHE_SIZE=1000;MODE=MYSQL;
> canal.instance.tsdb.dbUsername=canal
> canal.instance.tsdb.dbPassword=canal
> 
> # rds oss binlog account
> canal.instance.rds.accesskey =
> canal.instance.rds.secretkey =
> 
> #################################################
> ######### destinations	#############
> #################################################
> canal.destinations= example,cstation_example,user_example,license_example,cstationin_example,cstationout_alarm_example,cstationin_alarm_example,cstationin_second_ocr_example,cstationout_second_ocr_example
> 
> # conf root dir
> canal.conf.dir = ../conf
> 
> # auto scan instance dir add/remove and start/stop instance
> canal.auto.scan = true
> canal.auto.scan.interval = 5
> 
> canal.instance.tsdb.spring.xml=classpath:spring/tsdb/h2-tsdb.xml
> #canal.instance.tsdb.spring.xml=classpath:spring/tsdb/mysql-tsdb.xml
> 
> canal.instance.global.mode = spring
> canal.instance.global.lazy = false
> canal.instance.global.manager.address = 192.168.3.104:1099
> #canal.instance.global.spring.xml = classpath:spring/memory-instance.xml
> canal.instance.global.spring.xml = classpath:spring/default-instance.xml
> #canal.instance.global.spring.xml = classpath:spring/default-instance.xml
> `
> 
> instance.properties
> `#################################################
> 
> ## mysql serverId , v1.0.26+ will autoGen
> # canal.instance.mysql.slaveId=0
> # enable gtid use true/false
> canal.instance.gtidon=true
> 
> # position info
> canal.instance.master.address=192.168.3.94:3306
> canal.instance.master.journal.name=
> canal.instance.master.position=
> canal.instance.master.timestamp=
> canal.instance.master.gtid=
> 
> # rds oss binlog
> canal.instance.rds.accesskey=
> canal.instance.rds.secretkey=
> canal.instance.rds.instanceId=
> 
> # table meta tsdb info
> canal.instance.tsdb.enable=true
> #canal.instance.tsdb.url=jdbc:mysql://127.0.0.1:3306/canal_tsdb
> #canal.instance.tsdb.dbUsername=canal
> #canal.instance.tsdb.dbPassword=canal
> 
> canal.instance.standby.address=192.168.3.113:3306
> #canal.instance.standby.journal.name =
> #canal.instance.standby.position =
> #canal.instance.standby.timestamp =
> #canal.instance.standby.gtid=
> 
> # username/password
> canal.instance.dbUsername=canal
> canal.instance.dbPassword=canal
> canal.instance.connectionCharset=UTF-8
> canal.instance.defaultDatabaseName=elupay_user
> 
> # table regex
> canal.instance.filter.regex=elupay_user\u_userinfo_issued
> 
> # table black regex
> canal.instance.filter.black.regex=
> #################################################
> `
> 配置文件中未出现主机名，配置中采用IP配置，
> mysql用户连接正常，cannal启动能看到zk中生成对应信息，请教各位大牛
> 
> canal version: canal.deployer-1.1.0.tar.gz

兄弟们，解决办法在这里https://blog.csdn.net/lmb55/article/details/51264707，不懂就回复我。

**Comment by agapple** [comment]
LS正解
