### ISSUE TITLE
canal Adapter是否可以同步多个schema到一个同一个mysql

### ISSUE THREAD

**Issue by ckungit** [alibaba/canal#2263]
现在有多个schema需要同步，比如A1，A2，A3。
需要从database1把这些schema同步到database2
但是无论如何设置，都只能同步其中一个schema的数据。
通过设置destination，已经把多个库的改变传到Adapter了，Adapter的log里面也有显示
但是却无法改变对应库的数据。
请问Adapter应该怎样设置才可以。rdb下面的设置文件要怎样设置才行？

**Comment by D-YuLin** [comment]
mark

**Comment by D-YuLin** [comment]
一样的，改了配置，看了代码。发现不行啊
canalAdapters:
    - instance: example # canal instance Name or mq topic name
      groups:
        - groupId: g1
          outerAdapters:
            #      - name: logger
            - name: rdb
              key: mysql1
              properties:
                jdbc.driverClassName: com.mysql.jdbc.Driver
                jdbc.url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true
                jdbc.username: root
                jdbc.password: 123456
    - instance: example1 # canal instance Name or mq topic name
      groups:
        - groupId: g2
          outerAdapters:
            #      - name: logger
            - name: rdb
              key: mysql2
              properties:
                jdbc.driverClassName: com.mysql.jdbc.Driver
                jdbc.url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true
                jdbc.username: root
                jdbc.password: 123456
