### ISSUE TITLE
配置都ok,数据库变更，canal 客户端接收不到消息

### ISSUE THREAD

**Issue by xianqiangzhao** [alibaba/canal#2266]
## Question

docker 部署 canal 服务端和mysql 
mysql：
  log_bin	ON
canal :
  ==> START ...
start canal ...
start canal successful
==> START SUCCESSFUL ...

java canal 客户端：
 empty count : 1
empty count : 2
empty count : 3
empty count : 4
empty count : 5
empty count : 6

这时候数据库有数据插入，java cannal 客户端接收不了消息。

**Comment by agapple** [comment]
show binlog events in 'xxx' from xxx，先确认一下binlog里是否有数据

**Comment by xianqiangzhao** [comment]
解决了，谢谢！
