### ISSUE TITLE
HA server 切换时，最近一条binlog被重复解析

### ISSUE THREAD

**Issue by SnailDev** [alibaba/canal#2268]
- [x] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment

* canal version 1.1.4
* mysql version  5.7

### Issue Description
HA server 切换时，最近一条binlog被重复解析

**Comment by agapple** [comment]
这个是合理的，不保证不重复
