### ISSUE TITLE
canal仓库代码编译之后,不支持mysql5.1的问题

### ISSUE THREAD

**Issue by alexwangx** [alibaba/canal#227]
hi
canal开发团队,我使用canal仓库中master分支的代码编译.
Mysql Server version: 5.1.73
错误信息:
> ERROR:
[destination = example , address = test/192.168.10.16:3306 , EventParser] WARN  c.a.otter.canal.parse.inbound.mysql.MysqlConnection - java.io.IOException: ErrorPacket [errorNumber=1193, fieldCount=-1, message=Unknown system variable 'binlog_checksum', sqlState=HY000, sqlStateMarker=#]
 with command: set @master_binlog_checksum= @@global.binlog_checksum

changed file:https://github.com/alibaba/canal/commit/0c9eecd758a8cba0f218a121f83d3e8f01c4dee8

![image](https://cloud.githubusercontent.com/assets/9983697/20620006/5bffa586-b332-11e6-80b6-3dd104c87c00.png)

这篇答案说`binlog_checksum`变量是从mysql5.6才开始支持.[参考](http://dba.stackexchange.com/questions/66226/mysql-slave-database-wont-start)

如果是这样的话,时候意味着canal以后不会支持mysql5.6以下版本?

thx

**Comment by agapple** [comment]
可以增加try lock机制忽略异常设置的情况.

**Comment by alexwangx** [comment]
Mysql Server version: 5.1.73
[MysqlConnection.java#L282](https://github.com/alibaba/canal/blob/3f38ad6f4927e1d3bcf43faca8501df1e706405c/parse/src/main/java/com/alibaba/otter/canal/parse/inbound/mysql/MysqlConnection.java#L282
)  
抛出 NullPointerException

**Comment by boboChina** [comment]
遇到了同样的问题，老版本的5.1.73 ，楼上最终的解决方案？

**Comment by agapple** [comment]
使用当前主干试试
