### ISSUE TITLE
canal-admin中启动(停止)server、instance的设计

### ISSUE THREAD

**Issue by tracythink** [alibaba/canal#2270]
## Question
V1.1.4
canal-admin中启动(停止)server、instance设计上分别实现什么功能目标 
<img width="602" alt="AAA" src="https://user-images.githubusercontent.com/6290708/65828992-71fe9f80-e2d3-11e9-9c63-9b7b55a11570.png">
?
A 启动（停止）server当前是否是关闭canal进程? 执行操作发现日志"[New I/O server worker #2-5] ERROR com.alibaba.otter.canal.admin.handler.SessionHandler - something goes wrong with channel:[id: 0x402cd1ae, /127.0.0.1:50400 => /127.0.0.1:11110], exception=java.io.IOException: 远程主机强迫关闭了一个现有的连接。";
B 启动（停止）instance看了下源码,在V1.1.4版本中只看到了做了持久化。

**Comment by agapple** [comment]
#2269 重复了
