### ISSUE TITLE
fail by docker run with host network_mode

### ISSUE THREAD

**Issue by ryankong** [alibaba/canal#2277]
docker run with host network_mode
get error "hostname: Unknown host"

docker-compose.yml
version: '2'
services:
  canal-server:
      image: canal/canal-server:v1.1.3
      restart: always
      container_name: canal-server
      network_mode: host

Starting crond: [  OK  ]
==> INIT DONE
==> RUN /home/admin/app.sh
hostname: Unknown host

**Comment by agapple** [comment]
https://github.com/alibaba/canal/issues/2280，类似问题
