### ISSUE TITLE
启动startup.sh报错

### ISSUE THREAD

**Issue by hrdxwandg** [alibaba/canal#228]
下载的master版本1.0.23-SNAPSHOT。
根据QuickStart中启动：sh bin/startup.sh 报错如下：
: not found 2: startup.sh: 
startup.sh: 4: startup.sh: Syntax error: word unexpected (expecting "in")

**Comment by agapple** [comment]
估计是和你环境所有的shell环境不兼容导致，你可以本地测试修复一下，提交一个PR吧

**Comment by keyganker** [comment]
我也遇到同样的问题，不过最后排查下来是换行符导致的
下载一个dos2linux转换转换一下就搞定了

**Comment by hrdxwandg** [comment]
@keyganker 
我的不是这个原因，是shell环境不兼容导致的。
我的linux版本是ubuntu 4.4.0-36-generic，这个版本自带的sh估计和官方的不一样。
命令改为用bash stop.sh就没有问题了。

**Comment by caojiaqing** [comment]
:set ff=unix
