### ISSUE TITLE
hostname: Unknown host

### ISSUE THREAD

**Issue by hifer** [alibaba/canal#2280]
## Question

docker 1.12.6 启动canal-server报错：
DOCKER_DEPLOY_TYPE=VM
==> INIT /alidata/init/02init-sshd.sh
==> EXIT CODE: 0
==> INIT /alidata/init/fix-hosts.py
==> EXIT CODE: 0
==> INIT DEFAULT
Generating SSH1 RSA host key:                              [  OK  ]
Starting sshd:                                             [  OK  ]
Starting crond:                                            [  OK  ]
==> INIT DONE
==> RUN /home/admin/app.sh
hostname: Unknown host

docker 1.13.1+ 没有这个问题

**Comment by agapple** [comment]
可以看一下run.sh脚本，应该是有显示设置hostname

**Comment by hifer** [comment]
> 可以看一下run.sh脚本，应该是有显示设置hostname

这个看过了，传入的命令没问题，能获取到$LOCALHOST这个变量
docker run -d -it -h 10.2.104.29 -e canal.instance.master.address=10.2.104.29:3309 -e canal.instance.dbUsername=canal -e canal.instance.dbPassword=canal -e canal.instance.connectionCharset=UTF-8 -e canal.instance.tsdb.enable=true -e canal.instance.gtidon=false -e canal.instance.filter.regex=.*\..* --name=canal-server --net=host -m 4096m canal/canal-server

这个问题我在6台机器上测试过，三台centos7.2 docker 1.12.6的都会必现这个问题
另外三台centos7.4+ docker1.13+ 都没问题
ps:run.sh wget下来并没有做任何修改

**Comment by agapple** [comment]
这个我没在更多的docker版本上测试，canal会依赖hostname -i命令获取主机ip信息，只要确保这个命令能执行成功即可

**Comment by hifer** [comment]
> 这个我没在更多的docker版本上测试，canal会依赖hostname -i命令获取主机ip信息，只要确保这个命令能执行成功即可

这样就说的通了，不过我看run.sh脚本里面是这样的：
LOCALHOST=`getMyIp`

cmd="docker run -d -it -h $LOCALHOST $CONFIG --name=canal-server $VOLUMNS $NET_MODE $PORTS $MEMORY canal/canal-server"

function getMyIp() {
    case "`uname`" in
        Darwin)
         myip=`echo "show State:/Network/Global/IPv4" | scutil | grep PrimaryInterface | awk '{print $3}' | xargs ifconfig | grep inet | grep -v inet6 | awk '{print $2}'`
         ;;
        *)
         myip=`ip route get 1 | awk '{print $NF;exit}'`
         ;;
  esac
  echo $myip
}

不是用这个取的ip吗？hostname  -i很多机器会有多个ip啊

**Comment by 12345ZMTHL** [comment]
> 这个我没在更多的docker版本上测试，canal会依赖hostname -i命令获取主机ip信息，只要确保这个命令能执行成功即可

win系统这里怎么改呢？直接返回127.0.0.1嘛？
