### ISSUE TITLE
ES-Adapter ESTemplate.getESDataFromDmlData(ESTemplate.java:407)报错

### ISSUE THREAD

**Issue by saihide** [alibaba/canal#2288]
ESTemplate.getESDataFromDmlData(ESTemplate.java:407)报错，
canal的版本是：1.1.4
报错的代码是：
String columnName = fieldItem.getColumnItems().iterator().next().getColumnName();
mytest_user.yml的配置如下：
dataSourceKey: defaultDS
outerAdapterKey: es6
destination: saihide
groupId:
esMapping:
  _index: mytest_user
  _type: _doc
  _id: _id
  sql: "select * from aaa"
  commitBatch: 3000

**Comment by Ecli2h** [comment]
不支持select * 吧

**Comment by rewerma** [comment]
是的，不支持select *
