### ISSUE TITLE
canal监听问题

### ISSUE THREAD

**Issue by JoeyFan** [alibaba/canal#230]
canal服务，我设置监听了一个数据库的**tjxt-busi-cs**表，但是程序连接到此canal上，却能打印出别的数据库**tjxt-busi-ln**的表数据变化。两个数据库在同一个机器的mysql中。

这是我canal instance的配置信息
```
canal.instance.mysql.slaveId = 2283306
canal.instance.master.address = 192.168.10.100:3306
canal.instance.master.journal.name = 
canal.instance.master.position = 
canal.instance.master.timestamp = 
#canal.instance.standby.address = 
#canal.instance.standby.journal.name =
#canal.instance.standby.position = 
#canal.instance.standby.timestamp = 
canal.instance.dbUsername = canal
canal.instance.dbPassword = canal
canal.instance.defaultDatabaseName = tjxt-busi-cs
canal.instance.connectionCharset = UTF-8
canal.instance.filter.regex = .*\\..*
canal.instance.filter.black.regex =  
```
我程序里连接这个caanl，打印binlog信息，居然监听到了别的数据库的binlog日志
c.f.s.c.listener.BusiAnscWatcherThread - ================> binlog[mysqld-bin.000015:687343087] , name[**tjxt-busi-ln**,busi_wife_b_value] , eventType : INSERT

不清楚为什么这样。

**Comment by AllenRay** [comment]
canal.instance.defaultDatabaseName = tjxt-busi-cs 这个属性不是用来指定canal只监听这一个数据库的。你想一下binlog是针对一个DB实例的。不是针对一个数据库的。

**Comment by JoeyFan** [comment]
@AllenRay 嗯嗯。知道原理了。谢谢。。我想想通过别的方式进行解决一下
