### ISSUE TITLE
canal-admin[v1.1.4]搭建失败，请求帮助

### ISSUE THREAD

**Issue by ZhangHuirui** [alibaba/canal#2306]
**canal-admin v1.1.4搭建失败**

不知道什么原因，是不是那里配置不对，原来的单server是可以正常发送至kafka的，这次想升级一下，看这个新版本不错搭建下，没有成功不知道什么原因，点击Instance管理->操作->日志，没有反应。能不能给一个示例（包含三个server的集群，一个发送可以发送至kafka的Instance），可以照着示例改就行了。

**Docker 容器**

- f1efba9ca51d        canal/canal-server:v1.1.4            "/alidata/bin/main.sh"   3 hours ago         Up 28 minutes       0.0.0.0:9900->9100/tcp, 0.0.0.0:11910->11110/tcp, 0.0.0.0:11911->11111/tcp, 0.0.0.0:11912->11112/tcp   canal-server-2

- 9f5ba59314ea        canal/canal-server:v1.1.4            "/alidata/bin/main.sh"   3 hours ago         Up 28 minutes       0.0.0.0:9800->9100/tcp, 0.0.0.0:11810->11110/tcp, 0.0.0.0:11811->11111/tcp, 0.0.0.0:11812->11112/tcp   canal-server-1

- 451dfedfd916        canal/canal-server:v1.1.4            "/alidata/bin/main.sh"   3 hours ago         Up 3 minutes        0.0.0.0:9700->9100/tcp, 0.0.0.0:11710->11110/tcp, 0.0.0.0:11711->11111/tcp, 0.0.0.0:11712->11112/tcp   canal-server-0

- 67d4a57f4354        canal/canal-admin:v1.1.4             "/alidata/bin/main.sh"   5 hours ago         Up About an hour    0.0.0.0:8089->8089/tcp                                                                                 canal-admin

- c54a97261094        mysql:5.7                            "docker-entrypoint.sh"   5 hours ago         Up 5 hours          0.0.0.0:3306->3306/tcp, 33060/tcp                                                                      mysql-canal-manager

**Docker 容器配置（canal-server-0~2）**
**/home/admin/canal-server/conf/canal_local.properties**

\# register ip
canal.register.ip =
\# canal admin config
canal.admin.manager = 10.136.44.16:8089
canal.admin.port = 11110
canal.admin.user = admin
canal.admin.passwd = 4ACFE3202A5FF5CF467898FC58AAB1D615029441
\# admin auto register
canal.admin.register.auto = true
canal.admin.register.cluster =

**/home/admin/canal-server/conf/canal.properties**
\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#
\#\#\#\#\#\#\#\#\#               common argument         \#\#\#\#\#\#\#\#\#\#\#\#\#
\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#
\# tcp bind ip
canal.ip =
\# register ip to zookeeper
canal.register.ip =
canal.port = 11111
canal.metrics.pull.port = 11112
\# canal instance user/passwd
\# canal.user = canal
\# canal.passwd = E3619321C1A937C46A0D8BD1DAC39F93B27D4458

\# canal admin config
canal.admin.manager = 10.136.44.16:8089
canal.admin.port = 11110
canal.admin.user = admin
canal.admin.passwd = 4ACFE3202A5FF5CF467898FC58AAB1D615029441
\# admin auto register
canal.admin.register.auto = true
canal.admin.register.cluster =

canal.zkServers =
\# flush data to zk
canal.zookeeper.flush.period = 1000
canal.withoutNetty = false
\# tcp, kafka, RocketMQ
canal.serverMode = tcp
\# flush meta cursor/parse position to file
canal.file.data.dir = ${canal.conf.dir}
canal.file.flush.period = 1000
\#\# memory store RingBuffer size, should be Math.pow(2,n)
canal.instance.memory.buffer.size = 16384
\#\# memory store RingBuffer used memory unit size , default 1kb
canal.instance.memory.buffer.memunit = 1024
\#\# meory store gets mode used MEMSIZE or ITEMSIZE
canal.instance.memory.batch.mode = MEMSIZE
canal.instance.memory.rawEntry = true

\#\# detecing config
canal.instance.detecting.enable = false
\#canal.instance.detecting.sql = insert into retl.xdual values(1,now()) on duplicate key update x=now()
canal.instance.detecting.sql = select 1
canal.instance.detecting.interval.time = 3
canal.instance.detecting.retry.threshold = 3
canal.instance.detecting.heartbeatHaEnable = false

\# support maximum transaction size, more than the size of the transaction will be cut into multiple transactions delivery
canal.instance.transaction.size =  1024
\# mysql fallback connected to new master should fallback times
canal.instance.fallbackIntervalInSeconds = 60

\# network config
canal.instance.network.receiveBufferSize = 16384
canal.instance.network.sendBufferSize = 16384
canal.instance.network.soTimeout = 30

\# binlog filter config
canal.instance.filter.druid.ddl = true
canal.instance.filter.query.dcl = false
canal.instance.filter.query.dml = false
canal.instance.filter.query.ddl = false
canal.instance.filter.table.error = false
canal.instance.filter.rows = false
canal.instance.filter.transaction.entry = false
\# binlog format/image check
canal.instance.binlog.format = ROW,STATEMENT,MIXED
canal.instance.binlog.image = FULL,MINIMAL,NOBLOB

\# binlog ddl isolation
canal.instance.get.ddl.isolation = false

\# parallel parser config
canal.instance.parser.parallel = true
\#\# concurrent thread number, default 60% available processors, suggest not to exceed Runtime.getRuntime().availableProcessors()
\#canal.instance.parser.parallelThreadSize = 16
\#\# disruptor ringbuffer size, must be power of 2
canal.instance.parser.parallelBufferSize = 256

\# table meta tsdb info
canal.instance.tsdb.enable = true
canal.instance.tsdb.dir = ${canal.file.data.dir:../conf}/${canal.instance.destination:}
canal.instance.tsdb.url = jdbc:h2:${canal.instance.tsdb.dir}/h2;CACHE_SIZE=1000;MODE=MYSQL;
canal.instance.tsdb.dbUsername = canal
canal.instance.tsdb.dbPassword = canal
\# dump snapshot interval, default 24 hour
canal.instance.tsdb.snapshot.interval = 24
\# purge snapshot expire , default 360 hour(15 days)
canal.instance.tsdb.snapshot.expire = 360

\# aliyun ak/sk , support rds/mq
canal.aliyun.accessKey =
canal.aliyun.secretKey =

\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#
\#\#\#\#\#\#\#\#\#               destinations            \#\#\#\#\#\#\#\#\#\#\#\#\#
\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#
canal.destinations = example
\# conf root dir
canal.conf.dir = ../conf
\# auto scan instance dir add/remove and start/stop instance
canal.auto.scan = true
canal.auto.scan.interval = 5

canal.instance.tsdb.spring.xml = classpath:spring/tsdb/h2-tsdb.xml
\#canal.instance.tsdb.spring.xml = classpath:spring/tsdb/mysql-tsdb.xml

canal.instance.global.mode = spring
canal.instance.global.lazy = false
canal.instance.global.manager.address = ${canal.admin.manager}
\#canal.instance.global.spring.xml = classpath:spring/memory-instance.xml
canal.instance.global.spring.xml = classpath:spring/file-instance.xml
\#canal.instance.global.spring.xml = classpath:spring/default-instance.xml

\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#
\#\#\#\#\#\#\#\#\#                    MQ                      \#\#\#\#\#\#\#\#\#\#\#\#\#
\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#
canal.mq.servers = 127.0.0.1:6667
canal.mq.retries = 0
canal.mq.batchSize = 16384
canal.mq.maxRequestSize = 1048576
canal.mq.lingerMs = 100
canal.mq.bufferMemory = 33554432
canal.mq.canalBatchSize = 50
canal.mq.canalGetTimeout = 100
canal.mq.flatMessage = true
canal.mq.compressionType = none
canal.mq.acks = all
\#canal.mq.properties. =
canal.mq.producerGroup = test
\# Set this value to "cloud", if you want open message trace feature in aliyun.
canal.mq.accessChannel = local
\# aliyun mq namespace
\#canal.mq.namespace =

\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#
\#\#\#\#\#\#\#\#\#     Kafka Kerberos Info    \#\#\#\#\#\#\#\#\#\#\#\#\#
\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#
canal.mq.kafka.kerberos.enable = false
canal.mq.kafka.kerberos.krb5FilePath = "../conf/kerberos/krb5.conf"
canal.mq.kafka.kerberos.jaasFilePath = "../conf/kerberos/jaas.conf"

**canal-admin**
canal-cluster | 10.136.44.16:2181,10.136.131.16:2181,10.136.132.33:2181
\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#
\#\#\#\#\#\#\#\#\# 		common argument		\#\#\#\#\#\#\#\#\#\#\#\#\#
\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#
\# tcp bind ip
canal.ip = 10.136.44.16
\# register ip to zookeeper
canal.register.ip = 10.136.44.16
canal.port = 11111
canal.metrics.pull.port = 11112
\# canal instance user/passwd
\# canal.user =
\# canal.passwd =

\# canal admin config
canal.admin.manager = 10.136.44.16:8089
canal.admin.port = 11110
canal.admin.user = admin
canal.admin.passwd = 4ACFE3202A5FF5CF467898FC58AAB1D615029441

canal.zkServers = 10.136.44.16:2181,10.136.131.16:2181,10.136.132.33:2181
\# flush data to zk
canal.zookeeper.flush.period = 1000
canal.withoutNetty = false
\# tcp, kafka, RocketMQ
canal.serverMode = kafka
\# flush meta cursor/parse position to file
canal.file.data.dir = ${canal.conf.dir}
canal.file.flush.period = 1000
\#\# memory store RingBuffer size, should be Math.pow(2,n)
canal.instance.memory.buffer.size = 16384
\#\# memory store RingBuffer used memory unit size , default 1kb
canal.instance.memory.buffer.memunit = 1024 
\#\# meory store gets mode used MEMSIZE or ITEMSIZE
canal.instance.memory.batch.mode = MEMSIZE
canal.instance.memory.rawEntry = true

\#\# detecing config
canal.instance.detecting.enable = false
\#canal.instance.detecting.sql = insert into retl.xdual values(1,now()) on duplicate key update x=now()
canal.instance.detecting.sql = select 1
canal.instance.detecting.interval.time = 3
canal.instance.detecting.retry.threshold = 3
canal.instance.detecting.heartbeatHaEnable = false

\# support maximum transaction size, more than the size of the transaction will be cut into multiple transactions delivery
canal.instance.transaction.size =  1024
\# mysql fallback connected to new master should fallback times
canal.instance.fallbackIntervalInSeconds = 60

\# network config
canal.instance.network.receiveBufferSize = 16384
canal.instance.network.sendBufferSize = 16384
canal.instance.network.soTimeout = 30

\# binlog filter config
canal.instance.filter.druid.ddl = true
canal.instance.filter.query.dcl = false
canal.instance.filter.query.dml = false
canal.instance.filter.query.ddl = false
canal.instance.filter.table.error = false
canal.instance.filter.rows = false
canal.instance.filter.transaction.entry = false

\# binlog format/image check
canal.instance.binlog.format = ROW,STATEMENT,MIXED 
canal.instance.binlog.image = FULL,MINIMAL,NOBLOB

\# binlog ddl isolation
canal.instance.get.ddl.isolation = false

\# parallel parser config
canal.instance.parser.parallel = true
\#\# concurrent thread number, default 60% available processors, suggest not to exceed Runtime.getRuntime().availableProcessors()
\#canal.instance.parser.parallelThreadSize = 16
\#\# disruptor ringbuffer size, must be power of 2
canal.instance.parser.parallelBufferSize = 256

\# table meta tsdb info
canal.instance.tsdb.enable = true
canal.instance.tsdb.dir = ${canal.file.data.dir:../conf}/${canal.instance.destination:}
canal.instance.tsdb.url = jdbc:h2:${canal.instance.tsdb.dir}/h2;CACHE_SIZE=1000;MODE=MYSQL;
\#canal.instance.tsdb.url=jdbc:mysql://10.136.44.16:3306/canal_tsdb
canal.instance.tsdb.dbUsername = canal
canal.instance.tsdb.dbPassword = canal
\# dump snapshot interval, default 24 hour
canal.instance.tsdb.snapshot.interval = 24
\# purge snapshot expire , default 360 hour(15 days)
canal.instance.tsdb.snapshot.expire = 360

\# aliyun ak/sk , support rds/mq
canal.aliyun.accessKey =
canal.aliyun.secretKey =

\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#
\#\#\#\#\#\#\#\#\# 		destinations		\#\#\#\#\#\#\#\#\#\#\#\#\#
\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#
canal.destinations = instance-wemedia-nebula
\# conf root dir
canal.conf.dir = ../conf
\# auto scan instance dir add/remove and start/stop instance
canal.auto.scan = true
canal.auto.scan.interval = 5

canal.instance.tsdb.spring.xml = classpath:spring/tsdb/h2-tsdb.xml
\#canal.instance.tsdb.spring.xml = classpath:spring/tsdb/mysql-tsdb.xml

canal.instance.global.mode = manager
canal.instance.global.lazy = false
canal.instance.global.manager.address = ${canal.admin.manager}
\#canal.instance.global.spring.xml = classpath:spring/memory-instance.xml
canal.instance.global.spring.xml = classpath:spring/file-instance.xml
\#canal.instance.global.spring.xml = classpath:spring/default-instance.xml

\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#
\#\#\#\#\#\#\#\#\# 		     MQ 		     \#\#\#\#\#\#\#\#\#\#\#\#\#
\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#
canal.mq.servers = 10.136.44.16:9092,10.136.131.16:9092,10.136.132.33:9092
canal.mq.retries = 3
canal.mq.batchSize = 16384
canal.mq.maxRequestSize = 1048576
canal.mq.lingerMs = 100
canal.mq.bufferMemory = 33554432
canal.mq.canalBatchSize = 50
canal.mq.canalGetTimeout = 100
canal.mq.flatMessage = true
canal.mq.compressionType = none
canal.mq.acks = all
\#canal.mq.properties. =
canal.mq.producerGroup = test
\# Set this value to "cloud", if you want open message trace feature in aliyun.
canal.mq.accessChannel = local
\# aliyun mq namespace
\#canal.mq.namespace =

\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#
\#\#\#\#\#\#\#\#\#     Kafka Kerberos Info    \#\#\#\#\#\#\#\#\#\#\#\#\#
\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#
canal.mq.kafka.kerberos.enable = false
canal.mq.kafka.kerberos.krb5FilePath = "../conf/kerberos/krb5.conf"
canal.mq.kafka.kerberos.jaasFilePath = "../conf/kerberos/jaas.conf"

**Server 管理**

- | 172.17.0.6 | 172.17.0.6 | 11110 | 11111 | 11112 | 启动 | 操作
canal-cluster | canal-server-0 | 10.136.44.16 | 11710 | 11711 | 11712 | 启动 | 操作
canal-cluster | canal-server-1 | 10.136.44.16 | 11810 | 11811 | 11812 | 启动 | 操作
canal-cluster | canal-server-2 | 10.136.44.16 | 11910 | 11911 | 11912 | 启动 | 操作
- | 172.17.0.10 | 172.17.0.10 | 11110 | 11111 | 11112 | 启动 | 操作
- | 172.17.0.11 | 172.17.0.11 | 11110 | 11111 | 11112 | 启动 | 操作

错误
2019-10-17 20:33:27.825 [main] INFO  com.alibaba.otter.canal.deployer.CanalLauncher - \#\# load canal configurations
2019-10-17 20:33:28.317 [main] INFO  com.alibaba.otter.canal.deployer.CanalStarter - \#\# start the canal server.
2019-10-17 20:33:28.348 [main] INFO  com.alibaba.otter.canal.deployer.CanalController - \#\# start the canal server[172.17.0.6(172.17.0.6):11111]
2019-10-17 20:33:28.427 [main] INFO  com.alibaba.otter.canal.deployer.CanalStarter - \#\# the canal server is running now ......
2019-10-17 20:33:32.373 [New I/O server worker \#2-3] ERROR com.alibaba.otter.canal.admin.handler.SessionHandler - something goes wrong with channel:[id: 0x0d9143da, /127.0.0.1:58893 => /127.0.0.1:11110], exception=java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:322)
	at org.jboss.netty.channel.socket.nio.NioWorker.processSelectedKeys(NioWorker.java:281)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:201)
	at org.jboss.netty.util.internal.IoWorkerRunnable.run(IoWorkerRunnable.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Instance**

\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#
\#\# mysql serverId , v1.0.26+ will autoGen
\# canal.instance.mysql.slaveId=0

\# enable gtid use true/false
canal.instance.gtidon=false

\# position info
canal.instance.master.address=10.136.13.18:3306
canal.instance.master.journal.name=
canal.instance.master.position=
canal.instance.master.timestamp=
canal.instance.master.gtid=

\# rds oss binlog
canal.instance.rds.accesskey=
canal.instance.rds.secretkey=
canal.instance.rds.instanceId=

\# table meta tsdb info
canal.instance.tsdb.enable=false
\#canal.instance.tsdb.url=jdbc:mysql://127.0.0.1:3306/canal_tsdb
\#canal.instance.tsdb.dbUsername=canal
\#canal.instance.tsdb.dbPassword=canal

\#canal.instance.standby.address =
\#canal.instance.standby.journal.name =
\#canal.instance.standby.position =
\#canal.instance.standby.timestamp =
\#canal.instance.standby.gtid=

\# username/password
canal.instance.dbUsername=wemediaCanal
canal.instance.dbPassword=r!aqUhk4
canal.instance.connectionCharset = UTF-8
\# enable druid Decrypt database password
canal.instance.enableDruid=false
\#canal.instance.pwdPublicKey=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALK4BUxdDltRRE5/zXpVEVPUgunvscYFtEip3pmLlhrWpacX7y7GCMo2/JM6LeHmiiNdH1FWgGCpUfircSwlWKUCAwEAAQ==

\# table regex
canal.instance.filter.regex=media\\.media,media\\.post_history.*,media\\.post_unaudited,media\\.rss_post.*,media\\.mcn_relationship,media\\.phoenix_media_map,media\\.taurus_fixed_income_manage,media\\.verification,media\\.taurus_cpm_income.*,media\\.taurus_operate_income,media\\.taurus_fixed_income_20.*,media\\.taurus_fixed_income_history,media\\.taurus_tax_free_income,media\\.invite_income_log,media\\.taurus_tort_income,media\\.reward_record,media\\.log_flow,media\\.media_history
\# table black regex
canal.instance.filter.black.regex=
\# table field filter(format: schema1.tableName1:field1/field2,schema2.tableName2:field1/field2)
\#canal.instance.filter.field=test1.t_product:id/subject/keywords,test2.t_company:id/name/contact/ch
\# table field black filter(format: schema1.tableName1:field1/field2,schema2.tableName2:field1/field2)
\#canal.instance.filter.black.field=test1.t_product:subject/product_image,test2.t_company:id/name/contact/ch

\# mq config
canal.mq.topic=canal_wemedia_nebula_bin_log
\# dynamic topic route by schema or table regex
\#canal.mq.dynamicTopic=mytest1.user,mytest2\\..*,.*\\..*
\#canal.mq.partition=0
\# hash partition config
canal.mq.partitionsNum=30
canal.mq.partitionHash=media\\.media:id,media\\.post_history.*:media_id,media\\.post_unaudited:media_id,media\\.rss_post.*:source_id,media\\.log_flow:object_id,media\\.mcn_relationship:member,media\\.phoenix_media_map:media_id,media\\.taurus_fixed_income_manage:media_id,media\\.verification:media_id,media\\.taurus_cpm_income.*:media_id,media\\.taurus_operate_income:media_id,media\\.taurus_fixed_income_20.*:media_id,media\\.taurus_tax_free_income:media_id,media\\.taurus_tort_income:media_id,media\\.invite_income_log:invitor_media_id,media\\.reward_record:media_id,media\\.taurus_fixed_income_history:media_id,media\\.media_history:id
\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#

**Comment by jackerzz** [comment]
@ZhangHuirui 我觉得你可以查一查你的设备分配给他运行的内存是否大于2G,

**Comment by ZhangHuirui** [comment]
fixed
