### ISSUE TITLE
Not found the mapping info of index异常

### ISSUE THREAD

**Issue by xingxishen** [alibaba/canal#2309]
## Question

canal版本：1.1.4
es版本：7.4.0
已经创建了index和mapping了，还是会有这个问题是为什么呢？

**Comment by xingxishen** [comment]
是因为canal不支持7.0以上版本吗？

**Comment by 1044730317** [comment]
楼主关闭了问题，应该是解决了问题， 是怎么解决呀？

**Comment by xingxishen** [comment]
> 楼主关闭了问题，应该是解决了问题， 是怎么解决呀？

应该是不支持7.0以上的吧，我换成6.x就好了

**Comment by 1044730317** [comment]
> > 楼主关闭了问题，应该是解决了问题， 是怎么解决呀？
> 
> 应该是不支持7.0以上的吧，我换成6.x就好了

那你用ES库有没有加密码验证？

**Comment by xingxishen** [comment]
> > > 楼主关闭了问题，应该是解决了问题， 是怎么解决呀？
> > 
> > 
> > 应该是不支持7.0以上的吧，我换成6.x就好了
> 
> 那你用ES库有没有加密码验证？

没有

**Comment by findfz** [comment]
亲测，版本由7.4.0切换到6.7.0就好了
