### ISSUE TITLE
canal-adapter同步数据至es时，date字段会把数据为10点以前的数据加一个小时

### ISSUE THREAD

**Issue by mgqonline** [alibaba/canal#2312]
mapping设置如下：
`"mappings": {
    "_doc": {
      "properties": {
                  
                    "cardid": {
                        "type": "keyword"
                    },
                    "machid": {
                        "type": "keyword"
                    },
                    "machcode": {
                        "type": "keyword"
                    },
                    "machtypeid": {
                        "type": "keyword"
                    },
                    "schid": {
                        "type": "keyword"
                    },
                    "userid": {
                        "type": "keyword"
                    },
                    "usertype": {
                        "type": "keyword"
                    },
                    "phycno": {
                        "type": "keyword"
                    },
                    "py_phycno": {
                        "type": "keyword"
                    },
                    "phycno1": {
                        "type": "keyword"
                    },
                    "machname": {
                        "type": "keyword"
                    },
                    "cardtime_date": {
                        "type": "date"
                    },
                    "direction": {
                        "type": "keyword"
                    },
                    "remark": {
                        "type": "keyword"
                    },
                    "recdtime_date": {
                        "type": "date"
                    },
                    "name": {
                        "type": "keyword"
                    },
                    "sex": {
                        "type": "keyword"
                    },
                    "code": {
                        "type": "keyword"
                    },
                    "orgid": {
                        "type": "keyword"
                    },
                    "orgname": {
                        "type": "keyword"
                    },
                    "parentorgid": {
                        "type": "keyword"
                    },
                    "areaid": {
                        "type": "keyword"
                    },
                    "areaname": {
                        "type": "keyword"
                    },
                    "areatype": {
                        "type": "keyword"
                    },
                    "imgid": {
                        "type": "keyword"
                    },
                    "imgur": {
                        "type": "keyword"
                    },
                    "isstay": {
                        "type": "keyword"
                    },
                    "blockname": {
                        "type": "keyword"
                    },
                    "dormname": {
                        "type": "keyword"
                    },
                    "phycnotype": {
                        "type": "keyword"
                    }
                }
    }
  }`

同步过来数据cardtime_date字段由08点变成了09点，es版本6.3.2,canal版本1.1.4，还请各位大神帮忙看看：
`{
  "took": 1,
  "timed_out": false,
  "_shards": {
    "total": 1,
    "successful": 1,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": 4,
    "max_score": 11.456225,
    "hits": [
      {
        "_index": "uther_index_atndetail",
        "_type": "_doc",
        "_id": "1285445876",
        "_score": 11.456225,
        "_source": {
          "cardid": "21423269",
          "machid": "16185",
          "machcode": "61",
          "machtypeid": "10002",
          "schid": "4414019",
          "userid": "10438384",
          "usertype": "st",
          "imgurl": null,
          "isstay": "zs",
          "blockname": "14栋",
          "dormname": "603",
          "phycno": "3760656717",
          "cardtime_date": "2019-10-21T09:12:41-05:00",
          "direction": "ex",
          "remark": null,
          "recdtime_date": "2019-10-21T09:12:42-05:00",
          "name": "凌佳艳",
          "sex": "男",
          "code": "191500058855",
          "blockid": 16028070,
          "dormid": 16033394,
          "orgid": "16006099",
          "orgname": "高三(10)班",
          "parentorgid": "16006044",
          "areaname": "学校大门（左）",
          "areatype": "public",
          "areaid": "16005625",
          "imgid": "0",
          "machname": "校门远距离考勤01",
          "py_phycno": "1292969952",
          "phycno1": "3760656717",
          "phycnotype": "at"
        }
      },
      {
        "_index": "uther_index_atndetail",
        "_type": "_doc",
        "_id": "1285445902",
        "_score": 11.456225,
        "_source": {
          "cardid": "21423269",
          "machid": "16186",
          "machcode": "62",
          "machtypeid": "10002",
          "schid": "4414019",
          "userid": "10438384",
          "usertype": "st",
          "imgurl": null,
          "isstay": "zs",
          "blockname": "14栋",
          "dormname": "603",
          "phycno": "3760656717",
          "cardtime_date": "2019-10-21T09:12:43-05:00",
          "direction": "ex",
          "remark": null,
          "recdtime_date": "20`

**Comment by rewerma** [comment]
2019-10-21T09:12:42-05:00? 你这个时区不对，adapter默认会取操作系统的时区，你看一下你操作系统的时区是否不是东八区
