### ISSUE TITLE
create kafak topic partition number invalid

### ISSUE THREAD

**Issue by antsbean** [alibaba/canal#2316]
- [ ] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment

* canal version
1.14
* mysql version
5.7
* kafka version 
2.0.0
### Issue Description
config see below
```shell
# table regex
canal.instance.filter.regex=.*\\.xa.*
# table black regex
canal.instance.filter.black.regex=
# table field filter(format: schema1.tableName1:field1/field2,schema2.tableName2:field1/field2)
#canal.instance.filter.field=test1.t_product:id/subject/keywords,test2.t_company:id/name/contact/ch
# table field black filter(format: schema1.tableName1:field1/field2,schema2.tableName2:field1/field2)
#canal.instance.filter.black.field=test1.t_product:subject/product_image,test2.t_company:id/name/contact/ch

# mq config
#canal.mq.topic=example
# dynamic topic route by schema or table regex
canal.mq.dynamicTopic=.*\\..*
#canal.mq.partition=0
# hash partition config
canal.mq.partitionsNum=3
canal.mq.partitionHash=.*\\..*:id
```
I'm sure topic ```test.xa_user_info ``` is not exist before when firstly updated database test, table xa_user_info.
but use  kafka  cli  see just only one partition, 
```shell
/ # kafka-topics.sh --zookeeper xxxx --topic test.xa_user_info --desc
ribe
Topic:test.xa_user_info	PartitionCount:1	ReplicationFactor:1	Configs:
	Topic: test.xa_user_info	Partition: 0	Leader: 1001	Replicas: 1001	Isr: 1001
/ #
```
create topic partition numbers invalid

why topic is  not  ```test_xa_user_info``` ,  

please help me, thank you!
### Actual behaviour

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by zhuzhan** [comment]
> create topic partition numbers invalid

Have u yet resolved this? It seems that canal did not  create kafka topic with partitionsNum .

**Comment by antsbean** [comment]
> > create topic partition numbers invalid
> 
> Have u yet resolved this? It seems that canal did not create kafka topic with partitionsNum .

no
