### ISSUE TITLE
使用rocketmq 消费 message body乱码

### ISSUE THREAD

**Issue by shineabel** [alibaba/canal#2325]
## Question

public class Consumer implements CommandLineRunner {

    private String namesrvAddr = "192.168.186.129:9876";

    public void messageListener(){

        DefaultMQPushConsumer consumer=new DefaultMQPushConsumer("SilktechDashboardConsumer");

        consumer.setNamesrvAddr(namesrvAddr);
        try {

            consumer.subscribe("example4", "*");

            consumer.setConsumeFromWhere(ConsumeFromWhere.CONSUME_FROM_LAST_OFFSET);
            consumer.setConsumeMessageBatchMaxSize(1);

            consumer.registerMessageListener((MessageListenerConcurrently) (msgs, context) -> {

                for(Message msg:msgs){

                    try {
                    	System.out.println(msg.getBody());
                    	
						System.out.println("Received message====>"+new String(msg.getBody(),"utf-8"));
					} catch (UnsupportedEncodingException e) {
						e.printStackTrace();
					}
                }
                return ConsumeConcurrentlyStatus.CONSUME_SUCCESS;
            });

            consumer.start();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    @Override
    public void run(String... args) throws Exception {
        this.messageListener();
    }
}

rocketmq版本:4.4.0
canal版本：1.1.4 flatMessage=false

**Comment by agapple** [comment]
flatMessage=false，对应的数据内容是protobuf协议
