### ISSUE TITLE
请问现在支持mysql 5.7的xa事务吗

### ISSUE THREAD

**Issue by chenweida123** [alibaba/canal#2328]
如题，我们使用了mysql 的xa事务，发现抽取到xacommit时出现异常，请问现在支持xa了吗

**Comment by agapple** [comment]
最新的版本支持XA协议的解析

**Comment by chenweida123** [comment]
> 最新的版本支持XA协议的解析

再请问下，我使用了otter，是否可以替换新版的canal组件？

**Comment by czxin788** [comment]
> > 最新的版本支持XA协议的解析
> 
> 再请问下，我使用了otter，是否可以替换新版的canal组件？

我也想问otter遇到xa，怎么办，otter好几年没更新过了
