### ISSUE TITLE
多表进行数据聚合

### ISSUE THREAD

**Issue by opensourcezhiwei** [alibaba/canal#235]
出现源库表的id 会覆盖 目的表库的id,,
导致多条只有一条记录

有什么解决方案~?

**Comment by agapple** [comment]
源和目标设置不同的id段

**Comment by opensourcezhiwei** [comment]
这样就很不合理了,设置不同的id段,是源1-100目标是100-200吗?
我有设置过把id映射到mid,,然后就会多出记录来,而不是在值相同的地方进行覆盖~
聚合方面的不能整合吗?



2016-12-20 22:45 GMT+08:00 agapple <notifications@github.com>:

**Comment by agapple** [comment]
分布式场景下，不同分区的id都要求唯一，否则落到一个库上怎么判断是否是一条记录
