### ISSUE TITLE
Canal ---> Kafka --->消费者的问题?

### ISSUE THREAD

**Issue by baoyang23** [alibaba/canal#2359]
## Question

你好;我想问下,从Canal 到 Kafka 然后再到Kafka消费者这里。我每次最多能拿到的数据是 250到270条.然后我想问下,有什么配置或者方法,可以让我一次从Kafka中拿到 大于这么多条的数据.

**Comment by Guanpx** [comment]
你这个问题为啥要在这问.....这很明显不是canal的问题啊
