### ISSUE TITLE
关于canal嵌入式模式重启后数据丢失问题

### ISSUE THREAD

**Issue by zqhget1** [alibaba/canal#237]
大神好：
 本人使用的canal-1.0.22版本，参照otter写了一个数据订阅平台，由于目前canal的event store只有memory模式，当eventstore中的数据还没有来得及消费时，进行重启后，canal会从上次解析的位置进行数据重新装载消费，于是导致了重启前未消费eventstore的数据丢失。请问针对这个问题目前有没有好的处理思路，或者新的版本规划?

**Comment by agapple** [comment]
不会丢失数据的，下次重启前会以你最后消费ack的位点进行重拉binlog，包括之前内存里没消费的数据

**Comment by zqhget1** [comment]
看了一下代码，ack只是清空了store中数据，没有看到写zookeeper，下次重启后，读取到了zookeeper parse节点的binlog位置，导致数据丢失的


发自网易邮箱大师
在2016年12月20日 22:45，agapple 写道:

不会丢失数据的，下次重启前会以你最后消费ack的位点进行重拉binlog，包括之前内存里没消费的数据

**Comment by agapple** [comment]
你要选择default-instance.xml模式，就可以保证刷到zookeeper，可以先看下adminGuide wiki

**Comment by zqhget1** [comment]
大概发现问题了，我在初始化CanalLogPositionManager时使用的ZOOKEEPER模式，导致并不会解析MetaLogPosition，另外我的MetaManager刚好也是MEMORY模式，也并不写MetaLogPosition，多谢！
