### ISSUE TITLE
canal-1.1.4 kafka配置Kerberos认证后出现异常

### ISSUE THREAD

**Issue by zhiyuan192shine** [alibaba/canal#2392]
## Question

1. **在 canal.properties 中  Kafka Kerberos Info 配置如下(原始配置文件中给的示例是带引号的 "")**
`canal.mq.kafka.kerberos.enable = true`
`canal.mq.kafka.kerberos.krb5FilePath = "/etc/krb5.conf"`
`canal.mq.kafka.kerberos.jaasFilePath = "/etc/krb5.conf.d/jaas.conf"`

- **通过以上配置会出现如下异常：**

> 2019-11-13 14:14:23.046 [main] ERROR com.alibaba.otter.canal.server.CanalMQStarter - ## Something goes wrong when starting up the canal MQ workers:
java.lang.RuntimeException: ERROR # The kafka kerberos configuration file does not exist! please check it

- **原因**
在 `com.alibaba.otter.canal.kafka.CanalKafkaProducer` 类中的 `init(MQProperties kafkaProperties)` 方法中的 `if (krb5File.exists() && jaasFile.exists()) `  判断出结果为 false （配置文件中的引号""导致）

</br>

2. **在 canal.properties 中  Kafka Kerberos Info 配置如下(去掉引号"")**
`canal.mq.kafka.kerberos.enable = true`
`canal.mq.kafka.kerberos.krb5FilePath = /etc/krb5.conf`
`canal.mq.kafka.kerberos.jaasFilePath = /etc/krb5.conf.d/jaas.conf`

- 此处我的jaas.conf 如下
`KafkaClient {`
    `com.sun.security.auth.module.Krb5LoginModule required`
    `useKeyTab=true`
    `storeKey=true`
    `serviceName=kafka`
    `keyTab="/etc/security/keytab/bigdata.keytab"`
    `principal="bigdata@GLPROP.COM";`
`};`
`Client {`
    `com.sun.security.auth.module.Krb5LoginModule required`
    `useKeyTab=true`
    `storeKey=true`
    `keyTab="/etc/security/keytab/bigdata.keytab"`
    `principal="bigdata@GLPROP.COM";`
`};`

- **再次配置出现以下异常**
> Caused by: java.lang.IllegalArgumentException: Could not find a 'KafkaClient' entry in the JAAS configuration. System property 'java.security.auth.login.config' is /etc/krb5.conf.d/jaas.conf
- **原因**
在 `org.apache.kafka.common.security.JaasContext` 类中的 `defaultContext(JaasContext.Type contextType, String listenerContextName, String globalContextName)`  方法中 使用 `Configuration jaasConfig = Configuration.getConfiguration();` 并未获取到 jaas 相关的配置，获取结果为 `null`

- **解决**
canal.properties 中 Kafka Kerberos Info 配置不使用引号，并在 `com.alibaba.otter.canal.kafka.CanalKafkaProducer`  `init(MQProperties kafkaProperties)` 中 配置 kerberos 的代码中直接加入 jaas.conf 内容后，重启canal，拉binlog到kafka一切正常
> properties.put("sasl.jaas.config", "com.sun.security.auth.module.Krb5LoginModule required " +
                    "useKeyTab=true " +
                    "storeKey=true " +
                    "keyTab=\"/etc/security/keytab/bigdata.keytab\" " +
                    "principal=\"bigdata@GLPROP.COM\";");

**Comment by BigData-YC** [comment]
配置了文件jaas.conf还需要在改源码吗？？？？

**Comment by zhiyuan192shine** [comment]
> 配置了文件jaas.conf还需要在改源码吗？？？？

就是因为配置了 jaas.conf 没有生效才在源码里面配置的

**Comment by hashmapybx** [comment]
canal=>1.1.5kafka配置kerberos认证不要参考官方文档，配置；

**Comment by hashmapybx** [comment]
security.protocol=SASL_PLAINTEXT
sasl.mechanism=GSSAPI
sasl.kerberos.service.name=xxxx
sasl.jaas.config=com.sun.security.auth.module.Krb5LoginModule required useKeyTab=true storeKey=true keyTab="${keytab path}" principal="${principal name}";
