### ISSUE TITLE
为什么有了otter还要开发client-adapter？

### ISSUE THREAD

**Issue by liuquanal** [alibaba/canal#2421]
## Question
我觉得otter的功能已经很强大了，就是同步的目标有些少，只支持mysql和oracle，这是一个遗憾。但是很奇怪，为什么作者宁愿重写一个client-adapter项目也不愿重构otter，让它支持更多的输出目标呢？

以前网上有大神基于otter扩展了一些数据库，比如es、postgreSQL等等，这证明otter的扩展还是有潜力的。本人也想做一个优秀的异构数据库实时同步系统，但是client-adapter和otter让我犯了困难选择症。

**Comment by soocold** [comment]
感觉client-adapter偏离了Canal的中心，作为一个增量数据订阅功能，其实同步到那中下游（es、Hbase、MQ）是业务方的选择，不是Canal应该做的，canal提供好功能支持和扩展性就可以了（Client-server或内嵌模式已支持），而不是针对每种存储介质都提供一个client-adpater。当然有人提供稳定的adapter是值得肯定的，但是不是应该以plugin形式由使用者去选择，而不是全都集成进canal？canal应该专注以Binlog解析的性能、稳定性、故障快速资源、全量数据同步等核心功能。个人看法，不喜勿喷。

**Comment by agapple** [comment]
adapter支持同步db以外的存储，比如hbase、ES等

**Comment by ljnszu** [comment]
> ## Question
> 我觉得otter的功能已经很强大了，就是同步的目标有些少，只支持mysql和oracle，这是一个遗憾。但是很奇怪，为什么作者宁愿重写一个client-adapter项目也不愿重构otter，让它支持更多的输出目标呢？
> 
> 以前网上有大神基于otter扩展了一些数据库，比如es、postgreSQL等等，这证明otter的扩展还是有潜力的。本人也想做一个优秀的异构数据库实时同步系统，但是client-adapter和otter让我犯了困难选择症。

好问题。我也很好奇，如果想支持hbase,es ，完全可以在otter 上面继续改。而不需要新起一个adapter。 感觉是otter 要放弃了，将近两年没commit 了
