### ISSUE TITLE
我使用canal的HA模式运行canal但是遇到重复读取binlog

### ISSUE THREAD

**Issue by nick-yangg** [alibaba/canal#2423]
我使用canal的HA模式运行canal，在做切换测试的时候遇到主canal读取的最后一条，会在切换到从canal时还回读到，并且推送到kafka中了，请问这是一个bug还是原本的机制就是这样的，如果是，我该如何修改它。

**Comment by aaron1989041** [comment]
我也碰到这个问题了，即使把canal.instance.fallbackIntervalInSeconds设置为0还是会有少量的重复。

**Comment by dingyufei615** [comment]
@nick-yangg 我也遇到了这个问题 现在解决了么

**Comment by agapple** [comment]
重复数据是难免的
