### ISSUE TITLE
canal-admin启动后，WebUI中看到的server管理中的配置信息与在后台运维看到不一样

### ISSUE THREAD

**Issue by brightsong** [alibaba/canal#2424]
运行canal-admin1.1.4，启动成功，后台启动canal-server后，进入WebUI中，在server 管理模块可看到server列表信息，点开配置信息，发现与在后台手工配置的canal.properties不一样。怎么回事

**Comment by lyd5726892** [comment]
你启动admin之后，admin加载的是数据库里存的，并不是canal.propertiesd的内容，这个文件相当于模板。

**Comment by agapple** [comment]
LS正解
