### ISSUE TITLE
protoc文件转java代码工具选择问题

### ISSUE THREAD

**Issue by TRockis** [alibaba/canal#2425]
## 想问下项目中是用什么工具来得到CanalPacket.java这个文件的

我在尝试利用google的protoc来将CanalPacket.protoc这个文件转化成java文件的时候发现，我得到的java文件一些地方与项目中的文件差距很大

所以我想问一下项目中是用什么来产生这个文件的，谢谢。

**Comment by agapple** [comment]
google的protoc工具
