### ISSUE TITLE
Kafka用控制台消费者测试时发现有丢数据的情况

### ISSUE THREAD

**Issue by nd49782** [alibaba/canal#2433]
数据库版本：MariaDB 5.5.6
基本上都是默认配置，没有改特别的，Kafka中是单Topic单分区。用控制台消费者消费时发现数据消费不全，很奇怪的现象。而且测试多次，测了多个表均没有100%消费到。
<img width="540" alt="22" src="https://user-images.githubusercontent.com/45928087/69631520-f6c62980-1088-11ea-89ac-29fe1d757d39.png">

如图中所示，导入了100条数据，测试多次，并且换其它节点进行单独消费，每次测试时消费都只有22条
<img width="826" alt="11" src="https://user-images.githubusercontent.com/45928087/69631278-afd83400-1088-11ea-8109-29fcd0e70702.png">

INSTANCE MQ的配置就指定了个topic，其它都是模板默认的
#mq config
canal.mq.topic=test_ebitg_mytest2
#dynamic topic route by schema or table regex
#canal.mq.dynamicTopic=mytest1.user,mytest2\\..*,.*\\..*
canal.mq.partition=0
#hash partition config
#canal.mq.partitionsNum=3
#canal.mq.partitionHash=test.table:id^name,.*\\..*

请教下，这种情况该怎么排查？是哪里配置的不对吗？
我这个表里没有主键，跟表的主键有关系吗？（我测试好像没有关系）
我看到文档中关于mariaDB有以下设置，但是我不太清楚图中的两个地方应该在哪里配置？谢谢！
<img width="570" alt="33" src="https://user-images.githubusercontent.com/45928087/69685912-02513900-10f9-11ea-92ff-f0d514ff70a9.png">

**Comment by CESAEREE** [comment]
给层主点个赞

**Comment by nd49782** [comment]
解决了，不能单凭接收消息数来比较数量。一条json串里可能会有很多条数据，应该是跟batch commit有关。
