### ISSUE TITLE
不能正常关闭Mysql心跳连接

### ISSUE THREAD

**Issue by dangxia** [alibaba/canal#244]
## MysqlEventParser.stopHeartBeat
![screenshot_20161230_112811](https://cloud.githubusercontent.com/assets/1852661/21559222/32776da4-ce83-11e6-9cdb-e0671014de96.png)

## AbstractEventParser.stopHeartBeat
![screenshot_20161230_112756](https://cloud.githubusercontent.com/assets/1852661/21559229/5bae9b34-ce83-11e6-8de1-258aac961da3.png)

**Comment by agapple** [comment]
tks
