### ISSUE TITLE
canal-1.1.4版本本地配置和管理端配置不一致

### ISSUE THREAD

**Issue by jiakai908** [alibaba/canal#2440]
![配置](https://user-images.githubusercontent.com/32918492/69851890-c87d5f80-12bd-11ea-9ebd-9b8e51ba08a0.png)

本地配置和服务端配置不一致，目前管理服务存在的情况下，我认为配置应该可以以管理端为准。

**Comment by agapple** [comment]
目前设计策略是本地个性化定制覆盖远程。主要的考虑：远程配置应该是主要维护方式，那本地模式属于个性配置，优先级需要更高
