### ISSUE TITLE
希望canal支持 dml 过滤功能

### ISSUE THREAD

**Issue by sun642514265** [alibaba/canal#2443]
希望canal 可以支持自定义过滤dml功能（例如可以根据需求，只收集insert、过滤delete）。

**Comment by soocold** [comment]
可以在client adapter端做

**Comment by billge0402** [comment]
Cancal有没有办法根据某个表中的字段来过滤？比如，我想过滤TableA中IdFiled = 1的记录？

**Comment by dingchuanbin** [comment]
可以做到忽略delete操作吗
