### ISSUE TITLE
canal能发送延迟消息吗

### ISSUE THREAD

**Issue by shinerdeng** [alibaba/canal#2445]
https://www.jianshu.com/p/b0fa28f1c9fb
在binlog收到更新的时候查询数据，偶尔查不到，想引入延迟消息解决，查了没有相关的配置。问下是否有此功能？

**Comment by liguobao** [comment]
延时消息首先要消息队列先支持，然后才能做吧

**Comment by shinerdeng** [comment]
> 延时消息首先要消息队列先支持，然后才能做吧

支持。就是不知道canal能不能配置

**Comment by agapple** [comment]
canal本身不支持延时发送
