### ISSUE TITLE
关于canal 1.1.4的用户名密码问题

### ISSUE THREAD

**Issue by CoderLiuyang** [alibaba/canal#2447]
## Question

已知
server中的passwd是通过 select password（‘’）获取
那么问题来了 我试过多种密码都不成功 包括 默认的 
客户端  
CanalConnector connector =
                CanalConnectors.newSingleConnector(new InetSocketAddress("xxxxxxxx",
                        11111), "example", "canal", "canal");
服务端
# canal instance user/passwd
canal.user = canal
canal.passwd = E3619321C1A937C46A0D8BD1DAC39F93B27D4458
都会报错不知道什么原因

**Comment by CoderLiuyang** [comment]
something goes wrong when doing authentication: auth failed for user:canal

**Comment by LiYaoheng** [comment]
你好，解决了？

**Comment by CoderLiuyang** [comment]
> 你好，解决了？

没有啊 你有什么方案吗

**Comment by LiYaoheng** [comment]
> > 你好，解决了？
> 
> 没有啊 你有什么方案吗

都试了，还是不行，issue里别人也没有这个问题，咋俩哪里没整对吗 🤔

**Comment by LiYaoheng** [comment]
> > 你好，解决了？
> 
> 没有啊 你有什么方案吗

换一下最新的canal client 包就可以了。。。升级到1.1.4，try~

[https://mvnrepository.com/artifact/com.alibaba.otter/canal.client/1.1.4](url)

**Comment by CoderLiuyang** [comment]
> > > 你好，解决了？
> > 
> > 
> > 没有啊 你有什么方案吗
> 
> 换一下最新的canal client 包就可以了。。。升级到1.1.4，try~
> 
> https://mvnrepository.com/artifact/com.alibaba.otter/canal.client/1.1.4

解决了  么么哒
