### ISSUE TITLE
单队列消息发送时，队列选择可以根据自定义规则设置

### ISSUE THREAD

**Issue by zbjice** [alibaba/canal#2452]
当选择N topic-单队列发送消息时，默认发送到0队列，也可以根据自定义规则选择发送的队列。这样在多 broker 情况下，可以让不同 topic 队列路由到不同 broker，达到broker 负载相对均衡（否则0队列默认都进入一个 broker,导致单点压力过大）

**Comment by agapple** [comment]
没太看懂具体问题
