### ISSUE TITLE
canal server 无状态服务化改造

### ISSUE THREAD

**Issue by 565407548** [alibaba/canal#2462]
## Why you need it?

服务通过k8s部署，需要服务无状态，而目前数据（日志偏移）存于本地文件，是有状态的应用

## How it could be?

可以把数据存于数据库．目前有 FileMixedMetaManager,　可以扩展实现 RdbMixedMetaManager.
同时，需要暴露接口给K8s集群监听服务运行状态

**Comment by agapple** [comment]
可以考虑提交一个PR给我
