### ISSUE TITLE
adapter es 数据丢失

### ISSUE THREAD

**Issue by xuej2s** [alibaba/canal#2465]
v1.1.4版本
1、测试过程中发现pk项的设置是没有效果的，必须设置_id数据才能同步
2、数据同步过程中发现，会出现数据库发生变更，但adapter端没有任何反应的情况，日志没有任何变化，也不报错，也不打印同步日志，并且概率不低
想问一下大家有没有遇到同样情况的，是如何解决的？

**Comment by CoderLiuyang** [comment]
遇到过，没有解决，我想加个mq试试

**Comment by yipingw** [comment]
遇到了, 只能定时跑个etl解决一下

**Comment by PROMETHEUS-MH** [comment]
您好，请问您这个问题解决了吗？在下也碰到了不同步的问题

**Comment by xuej2s** [comment]
> 您好，请问您这个问题解决了吗？在下也碰到了不同步的问题

注意同步配置文件application.yml和的key属性和映射表文件中的outerAdapterKey属性必须配置
https://mp.weixin.qq.com/s/Mu4wG3K8eZWUhrSV9wSGkQ 这里面是我使用canal时遇到的一些问题的总结，希望可以帮到你

**Comment by PROMETHEUS-MH** [comment]
谢谢您
