### ISSUE TITLE
Azure connect failure V1.1.4  docker 

### ISSUE THREAD

**Issue by bai020** [alibaba/canal#2467]
![image](https://user-images.githubusercontent.com/22534679/70693092-af31d580-1cf7-11ea-8c7a-5261699a31a4.png)

**Comment by bai020** [comment]
Caused by: java.io.IOException: Error When doing Client Authentication:ErrorPacket [errorNumber=9999, fieldCount=-1, message=An internal error has occurred. Please retry or report your issues., sqlState=28000, sqlStateMarker=#]

**Comment by bai020** [comment]
之前微软云帮我们自测的也是失败。
我们的连接架构如下图所示，连接的请求会先到达A zure Gateway。
![image](https://user-images.githubusercontent.com/22534679/70693680-e3f25c80-1cf8-11ea-9b86-3fb02f5bf117.png)
简单来说，这个连接建立的过程会有三步：
客户端连接请求到达Gateway。 Gateway有一个公有IP地址监听3066端口
根据负载均衡及相应连接策略，Gateway会把请求代理到合适的cluster
Cluster中，连接会被转到您的数据库
 
这个Gateway的地址您可以直接通过ping您的MySQL地址得到。这个地址只是gateway地址并不是您的MySQL所分配的地址。根据上述Canal报错，似乎该服务没有正确连接到Azure MySQL 。
 
按照Canal的文档，该服务会把自己伪装成从服务器而读取主服务器的relay log进行数据复制。Azure MySQL是可以做类似的主从复制的。建议您尝试配置Canal看是否有相应的报错信息，并尝试联系阿里巴巴咨询Canal连接Azure MySQL的文档。

**Comment by bai020** [comment]
看是canal  dump binlog的时候，是从网关ip不是数据库实际地址。导致失败。或者其他原因

**Comment by lv12312** [comment]
有相同的需求，请考虑下如何做下适配

**Comment by lv12312** [comment]
现在测试下来应该都 OK 了，这个问题应该可以 close 了
