### ISSUE TITLE
canal是否支持只订阅“特定记录中某几个字段的变化”的binlog日志，并将其写入到kafka、mq等？

### ISSUE THREAD

**Issue by fielixlv** [alibaba/canal#2468]
看到canal支持ElasticSearch适配器，在适配器表映射文件中配置sql映射，即可以把“特定记录中某几个字段的变化”写入到ES，想问下如果想把变化的数据写入到kafka或mq是否也支持sql的配置方式。
我的需求场景是，我只想订阅a表中记录对应b表中status字段的变化。a.id是唯一键，b.bid是主键
select a.id，b.status from a left join b on a.id=b.bid

**Comment by agapple** [comment]
支持的，多看一下wiki
