### ISSUE TITLE
1.1.4版本的服务器端在“win10家庭中文版”下启动报错

### ISSUE THREAD

**Issue by jiang-jian-jian** [alibaba/canal#2469]
1、错误信息如下所示
![image](https://user-images.githubusercontent.com/38133323/70716477-698d0100-1d27-11ea-8c23-8b0b406f0fab.png)
2、instance.properties配置文件信息如下

canal.instance.mysql.slaveId=1234

canal.instance.gtidon=false

canal.instance.master.address=127.0.0.1:3306
canal.instance.master.journal.name=
canal.instance.master.position=
canal.instance.master.timestamp=
canal.instance.master.gtid=

canal.instance.dbUsername=test
canal.instance.dbPassword=123456
canal.instance.connectionCharset = UTF-8
canal.instance.defaultDatabaseName =test

canal.instance.enableDruid=false

canal.instance.filter.regex=.*\\..*`

3、instance.properties同样的配置在1.1.3版本下启动正常

**Comment by mzd123** [comment]
我也遇到了，但是放在mac和linux下又是正常的

**Comment by lwm2326** [comment]
解决方法：打开startup.bat ，将11 行的 @rem 去掉

**Comment by jiang-jian-jian** [comment]
> 解决方法：打开startup.bat ，将11 行的 @rem 去掉

去掉之后还是报一样的错误

**Comment by 191824852** [comment]
试一下用 gitbash 执行sh脚本

**Comment by suzawalee** [comment]
装一下java 8的包，我的Win 10 专业版

**Comment by jiang-jian-jian** [comment]
> 装一下java 8的包，我的Win 10 专业版
我的java 版本"1.8.0_162"

**Comment by agapple** [comment]
win的支持可以考虑提交PR给我
