### ISSUE TITLE
MysqlConnecter.negotiate方法报错信息

### ISSUE THREAD

**Issue by ChanKunggc** [alibaba/canal#2477]
## Question

[https://github.com/alibaba/canal/blob/master/driver/src/main/java/com/alibaba/otter/canal/parse/driver/mysql/MysqlConnector.java#L170](url) 请问这里的英文意思是未预料到的错误吗？ 是写错了吗?

**Comment by ChanKunggc** [comment]
[https://github.com/alibaba/canal/blob/master/driver/src/main/java/com/alibaba/otter/canal/parse/driver/mysql/MysqlConnector.java#L273](url)

**Comment by agapple** [comment]
正常情况不会遇到
