### ISSUE TITLE
1.1.3版本，设置canal.instance.filter.regex不生效

### ISSUE THREAD

**Issue by koupeng** [alibaba/canal#2481]
- [ ] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment

* canal version 1.1.3
* mysql version 5.7

### Issue Description
我使用了Kafka消费数据，发现kefka仍然接收到了其他表的数据。

1.1.3版本，设置canal.instance.filter.regex不生效
### Actual behaviour

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by wyoldfour** [comment]
是否开启了binlog_rows_query_log_events事件？
