### ISSUE TITLE
canal发送的json中能只要data项吗？

### ISSUE THREAD

**Issue by zcheneng** [alibaba/canal#2488]
我想从canal到kafka间发送的数据量为最小，不知道能不能定制只发送几个数据项，比如data、table、type这几项？

**Comment by zcheneng** [comment]
我改了源码，改后只发送data,database,es,id,,pkNames,table,type,ts数据项，这样消息体减少了50%，从kafka中消费出的字符串在jvm里占的内存也得到了改善，欢迎讨论。

**Comment by yinlingshishangS** [comment]
亲，源码可以粘贴出来么？

**Comment by everior** [comment]
666，求源码~
