### ISSUE TITLE
canal.instance.defaultDatabaseName该字段的作用是什么

### ISSUE THREAD

**Issue by yalunwang** [alibaba/canal#2493]
canal指定了canal.instance.master.address=a地址,
a地址上有多个数据库，canal.instance.defaultDatabaseName =b数据库
这样配置后为什么还是会收到a地址上对应的所有数据库的数据而不只是b数据库的数据？
还是说canal本身就不支持指定一个数据库？
麻烦有空指导一下，感谢。

**Comment by 313715295** [comment]
抱着一样的疑问来找答案没找到，后面在wiki中找到了解决方法。
下的1.1.5 已经没有这个配置了，如果想要只订阅指定库的数据，可以instance. properties中配置canal.instance.filter.regex 或者客户端中配置connector.subscribe(),正则表达式。客户端配置会覆盖instance的。

**Comment by agapple** [comment]
LS正解，defaultDatabaseName已经废弃了

**Comment by yalunwang** [comment]
好的，感谢回复@ @agapple @313715295

**Comment by Dr-wgy** [comment]
canal.instance.defaultDatabaseName 这个里面对应db 如果在 数据库中删除 
Caused by: java.io.IOException: Error When doing Client Authentication:ErrorPacket [errorNumber=1049, fieldCount=-1, message=Unknown database 'xxxx', sqlState=42000, sqlStateMarker=#]
会导致 同步卡住 这个地方强行依赖这个 defaultDatabaseName 吗
