### ISSUE TITLE
mysql text/longtext类型在解析时被识别为LONGVARBINARY，导致下游同步时解析乱码

### ISSUE THREAD

**Issue by flackyang** [alibaba/canal#2494]
- [ ] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment

* canal version 1.1.3
* mysql version 5.7

### Issue Description
{
	"data": [],
	"database": "XXX",
	"es": 1577088014000,
	"id": 1233420,
	"isDdl": false,
	"mysqlType": {
		"ID": "BIGINT",
		"COMPANY_ID": "BIGINT",
		"PUNISH_OBJECT_ID": "BIGINT",
		"PUNISH_OBJECT": "VARCHAR(200)",
		"PUNISH_OBJECT_TYPE": "DOUBLE",
		"RELATION": "VARCHAR(200)",
		"TITLE": "VARCHAR(1500)",
		"CONTENT": "LONGTEXT",
		"NOTICE_DT": "DATETIME",
		"CASE_CATEGORY": "VARCHAR(60)",
		"NOTICE_WEBSITE": "VARCHAR(255)",
		"DECISION_DT": "DATETIME",
		"DECISION_GOV_ID": "BIGINT",
		"DECISION_GOV": "VARCHAR(300)",
		"REF_NUMBER": "VARCHAR(255)",
		"PUNISH_TYPE": "VARCHAR(1000)",
		"PENALTY_BASIS": "LONGTEXT",
		"PENALTY_REASON": "LONGTEXT",
		"PENALTY_RESULT": "LONGTEXT",
		"PUNISH_AMT": "DECIMAL(24,6)",
		"PENALTY_COMMENT": "LONGTEXT",
		"IS_DEL": "INTEGER",
		"CREATE_DT": "DATETIME(6)",
		"UPDT_DT": "DATETIME(6)"
	},
	"old": null,
	"pkNames": ["ID"],
	"sql": "",
	"sqlType": {
		"ID": -5,
		"COMPANY_ID": -5,
		"PUNISH_OBJECT_ID": -5,
		"PUNISH_OBJECT": 12,
		"PUNISH_OBJECT_TYPE": 8,
		"RELATION": 12,
		"TITLE": 12,
		"CONTENT": 2005,
		"NOTICE_DT": 93,
		"CASE_CATEGORY": 12,
		"NOTICE_WEBSITE": 12,
		"DECISION_DT": 93,
		"DECISION_GOV_ID": -5,
		"DECISION_GOV": 12,
		"REF_NUMBER": 12,
		"PUNISH_TYPE": 12,
		"PENALTY_BASIS": 2005,
		"PENALTY_REASON": 2005,
		"PENALTY_RESULT": -4,
		"PUNISH_AMT": 3,
		"PENALTY_COMMENT": -4,
		"IS_DEL": 4,
		"CREATE_DT": 93,
		"UPDT_DT": 93
	},
	"table": "XXX",
	"ts": 1577088012412,
	"type": "INSERT"
}

字段在mysql 中为 text 或 longtext类型， 但是canal解析对应的标准sql类型变成了LONGVARBINARY（-4），在canal-adapter解析时当作byte[] 来解析字段数据（实际上字段数据人String), 导致乱码
### Expected behaviour
mysql 中 text/longtext 对应为 clob类型  ，字段内容当作String处理
### Actual behaviour
mysql 中 text/longtext 被解析为 LONGVARBINARY类型，字段内容被当作byte[] 来解析字段数据（实际上字段数据人String), 导致乱码

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by agapple** [comment]
可以看下example，有正确处理blob的例子

**Comment by hoey94** [comment]
后续怎么样了，遇到了相同的问题。
