### ISSUE TITLE
MultiStageCoprocessor-Parser-example-10] WARN  c.a.o.canal.parse.inbound.mysql.dbsync.LogEventConvert - table parser error 

### ISSUE THREAD

**Issue by zhangqh01** [alibaba/canal#2497]
- [x] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment

* canal 1.3
* mysql 5.7.26

### Issue Description
   使用load data  加载csv文件导入mysql，canal服务 以及 instance 报错：
             WARN  c.a.o.canal.parse.inbound.mysql.dbsync.LogEventConvert - table parser error 
    使用常规insert语法可以正常导入

### Steps to reproduce
1.canalserver 正常启动，使用client 同步 DB1 

2.使用load data 加载数据文件到数据库 DB1
 LOAD DATA LOCAL INFILE  '/tmp/test.csv' INTO TABLE OralLogDay_20191218  

### Actual behaviour

If there is an exception, please attach the exception trace:

```
2019-12-25 09:32:49.049 [MultiStageCoprocessor-Parser-example-10] WARN  c.a.o.canal.parse.inbound.mysql.dbsync.LogEventConvert - table parser error : header { version: 1
  logfileName: "mysql-bin.000152"
  logfileOffset: 46874
  serverId: 1
  serverenCode: "UTF-8"
  executeTime: 1577237568000
  sourceType: MYSQL
  schemaName: "testsync"
  tableName: "OralLogDay_20191218"
  eventLength: 7912
  eventType: INSERT
  props {
    key: "rowsCount"
    value: "4"
  }
}
```

**Comment by zhangqh01** [comment]
canal将每一条记录都分别在server  和  instance 中 打印：
2019-12-25 09:32:49.048 [MultiStageCoprocessor-Parser-example-11] WARN  c.a.o.canal.parse.inbound.mysql.dbsync.LogEventConvert - table parser error : header {
  version: 1
  logfileName: "mysql-bin.000152"
  logfileOffset: 54786
  serverId: 1
  serverenCode: "UTF-8"
  executeTime:  154
  sourceType: MYSQL
  schemaName: "testsync"
  tableName: "OralLogDay_20191218"
  eventLength: 1469
  eventType: INSERT
  props {
    key: "rowsCount"
    value: "2"
  }
}
entryType: ROWDATA
storeValue: ""
storeValue: tableId: 172
eventType: INSERT
isDdl: false
rowDatas {
  afterColumns {
    index: 0
    sqlType: 12
    updated: true
    isNull: false
    value: ""
  }
  afterColumns {
    index: 1
    sqlType: 12
    updated: true
    isNull: false
    value: ""
  }

。。。。。。

**Comment by zhangqh01** [comment]
fix mysql

**Comment by cion-J** [comment]
请问一下原因是什么，遇到同样的问题。。

**Comment by zhangqh01** [comment]
> 请问一下原因是什么，遇到同样的问题。。

我这边也没有找到原因 
最后是更换了没有mysql版本为：5.7.28 解决
