### ISSUE TITLE
求解一个关于消费MQ消息之后的顺序性问题

### ISSUE THREAD

**Issue by Dreamroute** [alibaba/canal#2498]
目前我们是把MQ消息经过转换发往ES，消息的投递和消费都是有序的，但是消息从MQ出来到达ES这一段路程如何保证书顺序呢？例如同时批量修改数据库数据，原则上是按照事务顺序去更新ES。但是由于网络问题，这并不一定能够保证，如果引入zk分布式锁感觉有些太重了，性能方面可能无法接受。能否给个方向呢？谢谢。

**Comment by agapple** [comment]
选择kafka或者RocketMQ，支持顺序消费
