### ISSUE TITLE
canal-admin，初始化脚本字段不能为  `modified_time`  null

### ISSUE THREAD

**Issue by xuebinwang** [alibaba/canal#2500]
原始字段脚本：创建为当前时间，更新时间自动变化
`modified_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
版本：MySQL5.6.45，创建完后，启动canal-server 异常字段不能为  `modified_time` not is null ，是我版本的问题吗？
谢谢大佬！

**Comment by leonGravel** [comment]
mysql 配置文件加上
```
explicit_defaults_for_timestamp=false
```
应该是mysql版本导致的这个问题
https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_explicit_defaults_for_timestamp

**Comment by xuebinwang** [comment]
谢谢大佬。是版本问题，explicit_defaults_for_timestamp=false，对于不指定此列的显式值的插入行，该列将分配“0000-00-00 00:00:00”，并且不会发生警告。当explicit_defaults_for_timestamp=true时，对于不为此列指定显式值的插入行，结果取决于SQL模式。 如果启用了严格的SQL模式，则会发生错误。 如果未启用严格的SQL模式，则会为列分配隐式默认值“0000-00-00 00:00:00”，并发出警告。

**Comment by xuebinwang** [comment]
已解决

**Comment by duhanmin** [comment]
怎么解决explicit_defaults_for_timestamp=false没用

**Comment by wangyu22202** [comment]
建表语句加了 NOT NULL，后续插入值又有 NULL 值导致的，可以在建表语句里删除相关字段的 NOT NULL 声明。

**Comment by hlcen66** [comment]
> 已解决

怎么解决的呀？就是explicit_defaults_for_timestamp=false解决的吗？还是修改表结构not null 的勾去掉？
