### ISSUE TITLE
canal客户端是否可以通过client_id，来创建多个canal客户端消费者去不共享地消费一个canal instance

### ISSUE THREAD

**Issue by Vvegetables** [alibaba/canal#2507]
#### 目前我遇到的情况是这样的：
我通过canal-python去连接我创建的一个canal instance。
这里我有两个canal-python客户端，分别赋予了不同的client_id。这里会发生这样的现象，client_id1和client_id2会使用相同的消费记录。client_id1消费了一部分binlog更新之后，client_id1停止，client_id2启动时，会继续client_id1消费的节点继续消费，而不是从头开始消费。这是为什么呢？一个canal instance不支持多个client消费么？

**Comment by Lintel-X** [comment]
一个instance不支持多个client，可以新建多个相同的instance暂时解决你的问题
