### ISSUE TITLE
请问支持10.0.10版本的MariaDB吗

### ISSUE THREAD

**Issue by minotaursu** [alibaba/canal#251]
> ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:example[com.  alibaba.otter.canal.parse.exception.CanalParseException: com.alibaba.otter.canal.parse.exception.CanalParseException: parse row data failed.
Caused by: com.alibaba.otter.canal.parse.exception.CanalParseException: parse row data failed.
Caused by: java.lang.IllegalArgumentException: bad format, x exceed: 1207926783, 999999999

mysql使用10.0.10版本的MariaDB，canal启动后解析binlog就会报以上错误。试了1.0.22，1.0.23版本的canal都不行

**Comment by agapple** [comment]
这个估计要看看mariadb在10.0.10上改动了哪些

**Comment by zhongjimax** [comment]
@minotaursu 可以试试maxscale的binlogserver组件。

**Comment by agapple** [comment]
@zhongjimax binlog server组件只是解决binlog远程下载吧，具体解析工作还得自己做

**Comment by minotaursu** [comment]
试过了，无法解析mariadb的10.0.10版本。
