### ISSUE TITLE
idea maven 依赖无法下载源码代码，换了jdk1.7 无效

### ISSUE THREAD

**Issue by geekyouth** [alibaba/canal#2510]
### environment

		
		<dependency>
			<groupId>com.alibaba.otter</groupId>
			<artifactId>canal.client</artifactId>
			<version>1.1.2</version>
		</dependency>
* canal version 1.1.2
* idea version 2019.2.4

### Issue Description
想看 canal 源码的时候，点击download source 没反应，attach 总提示无法识别，更换了阿里云和官方maven仓库都不行，甚至到mvnrepository.com 手动下载对应的文件，还是无法加载源代码。更换了jdk1.7也不行，重启神马的都试了无效啊。。。😂

![image](https://user-images.githubusercontent.com/12899262/71503210-3e6dea00-28af-11ea-924b-871a3c93202e.png)

**Comment by agapple** [comment]
mvn clean install eclips:eclipse -Dmaven.test.skip，手工导入
