### ISSUE TITLE
regarding the type as tinyint format

### ISSUE THREAD

**Issue by Suaron-Biliu** [alibaba/canal#2520]
regarding the type as tinyint format, I obtained on the client that the field type expression in JOSN is a string format. Sample: "0"

![image](https://user-images.githubusercontent.com/41983216/71654661-f1d25500-2d6d-11ea-818b-10cec8920a28.png)

![image](https://user-images.githubusercontent.com/41983216/71654683-0adb0600-2d6e-11ea-8f75-995ba01caad5.png)

**Comment by agapple** [comment]
这个是json格式输出的文本
