### ISSUE TITLE
关于timestamp转换为datetime时区问题

### ISSUE THREAD

**Issue by YuanWeiKang** [alibaba/canal#2522]
canal在同步binlog到kafka时会默认将timestamp类型字段转换为datetime字段，这里有做时区转换吗？默认都是北京时间吗？目前我们在中东机房mysql到北京机房kafka发现有这个问题

**Comment by agapple** [comment]
这个是按照canal-server主机时区，没有做时区转换。如有特殊需求，可以考虑提交一个PR
