### ISSUE TITLE
client-adapter canal.conf 不需要配置canal-server instance的用户名和密码吗?

### ISSUE THREAD

**Issue by bigkun** [alibaba/canal#2523]
client-adapter canal.conf 不需要配置canal-server instance的用户名和密码吗?

**Comment by bigkun** [comment]
`
public class CanalAdapterWorker extends AbstractCanalAdapterWorker {

    private static final int BATCH_SIZE = 50;
    private static final int SO_TIMEOUT = 0;

    private CanalConnector   connector;

    /**
     * 单台client适配器worker的构造方法
     *
     * @param canalDestination canal实例名
     * @param address canal-server地址
     * @param canalOuterAdapters 外部适配器组
     */
    public CanalAdapterWorker(CanalClientConfig canalClientConfig, String canalDestination, SocketAddress address,
                              List<List<OuterAdapter>> canalOuterAdapters){
        super(canalOuterAdapters);
        this.canalClientConfig = canalClientConfig;
        this.canalDestination = canalDestination;
        connector = CanalConnectors.newSingleConnector(address, canalDestination, "", "");
`

`connector = CanalConnectors.newSingleConnector(address, canalDestination, "", "");`
这里username和password为"",

**Comment by bigkun** [comment]
@rewerma

**Comment by CoderLiuyang** [comment]
要不你就定义一个变量 要不直接把那个username password放进去 要不就写死

**Comment by agapple** [comment]
最新代码已经修复
