### ISSUE TITLE
canal可以获得binlog中SQL的执行用了多少时间么（exe_time）

### ISSUE THREAD

**Issue by daihaochen** [alibaba/canal#2524]
## Question
如题：想获得SQL的执行的耗费时间，通过mysqlbinlog日志文件中可以看到有exe_time这个属性，但是canal中获得的数据却没有这个属性，只有个执行的时间戳

**Comment by agapple** [comment]
印象中binlog里没有这个exe_time的属性，可以找下mysql官方文档
