### ISSUE TITLE
data键对应的数组长度和获取值的问题

### ISSUE THREAD

**Issue by kingkongpoon** [alibaba/canal#2525]
方法一：
insert into table_a VALUES ("tt1",11,"s","HR"),("tt3",12,"m","RD"),("tt4",13,"s","PR");
发出的消息是一条，然后json里面data的是一个有3个元素的数组。

方法二：
insert into table_a VALUES ("tt1",11,"s","HR");
insert into table_a VALUES ("tt3",12,"m","RD");
insert into table_a VALUES ("tt4",13,"s","PR");
发出的消息是三条，然后json里面data的数组只需要取下标为0就能取出数据

是否有一种模式，可以让第一种的发送消息变为发3条，然后在消息里都取下标0的数据就能用，而现在是，不能确定发过来的data键对应的数组长度是多少，还需要再写程序清洗？

**Comment by agapple** [comment]
数据路由切分是把每行数据进行路由，一行数据发送多份不合适
