### ISSUE TITLE
库名表名正则过滤配置，默认是逗号分割，这就藐视了正则语义中的逗号

### ISSUE THREAD

**Issue by juaby** [alibaba/canal#2527]
## 库名表名正则过滤配置，默认是逗号分割，这就藐视了正则语义中的逗号
AviaterRegexFilter
这个类构造时，String[] ss = StringUtils.split(pattern, SPLIT);
如果过滤器规则是这样：xxx_[0-9]{2}.table_name_[0-9]{4}_[0-9]{1,2},yyy_[0-9]{2}.table_name_[0-9]{3}_[0-9]{1,2} 然后就傻了，傻了，Perl5正则匹配失败了
所以逗号分割藐视了正则语义中的逗号
阿门
愿上帝保佑

**Comment by agapple** [comment]
只能有一种分隔符，势必都会和文本冲突，建议先绕开吧
