### ISSUE TITLE
prepare to find start position just last position

### ISSUE THREAD

**Issue by happyer** [alibaba/canal#253]
部署了两台机器 A，机器 和B 机器，A 机器先启动成功，然后看日志 一直处于 prepare to find start position just last position，之后我把 A 机器关闭了，然后去观察B 机器，然后迅速 获取到postion ，这是问题难道每次都要关闭一台机器吗？

**Comment by boboChina** [comment]
我遇到了类似的问题，我只部署了一个canal节点 ，一直卡在定位这一步

**Comment by happyer** [comment]
@boboChina  单机的话你就不用用zk 了，就可以用了，我怀疑是zk ,有问题日志上面显示一直ping  zk

**Comment by boboChina** [comment]
我怀疑过，我后台做过几次重试：
1先把canal停了，把zk上面数据删了 这种不行
2 设置binlog文件、位点、时间戳 也不行
根据打印的日志，去对照配置项，和源码里面走到的if else分支对不上

**Comment by boboChina** [comment]
不用zk也试了下，没效果，怀疑和mysql设置有关，换了其他的mysql有的很快恨得定位就卡死了，但是具体不知道是哪些配置项会有影响

**Comment by happyer** [comment]
按照你这样的逻辑应该是数据库的问题咯，但是我把Zk关闭了，然后单机模式就可以，数据库没有变化啊

**Comment by agapple** [comment]
prepare to find start position just last position , 这个是代表用最后的位点已经启动成功的意思

**Comment by happyer** [comment]
可是启动成功过后，一直就停在那里了，然后客户端去消费的时候，也会一直卡在哪里的
