### ISSUE TITLE
kafka可不可以不同instance配置不同的client.id

### ISSUE THREAD

**Issue by sudo5zzb** [alibaba/canal#2531]
## Question
我们这里的kafka都是根据topic基于client.id进行权限控制的。每申请一个topic都会有一个对应的client.id 。我们把client.id配置到集群配置里面是可以的，这样配置：canal.mq.properties.client.id = topic。但是如果要实现每个instance 对应一个不同的client.id的话是不是现在是不支持的呀。不行的话我们只能考虑改源码了。

**Comment by agapple** [comment]
这个建议是定制自己的connector吧
