### ISSUE TITLE
关于Canal高可用方案

### ISSUE THREAD

**Issue by fl613258** [alibaba/canal#2533]
## Question

想问下，如何扩展Canal，我们试用了主从，然后开启从库binlog，发现这样还是不行，有什么样的方案让我们扩展吗？

**Comment by fl613258** [comment]
我们试用了log_slave_updates参数，不知道会不会对主从产生影响

**Comment by agapple** [comment]
log_slave_updates会让从库把主库同步过来的日志落盘，不会有啥影响
