### ISSUE TITLE
canal-adapter 可以设置同步到多个mysql数据库吗？

### ISSUE THREAD

**Issue by chenhp** [alibaba/canal#2535]
canal-adapter 可以设置同步到多个mysql数据库吗？

**Comment by yangqiangqiang0327** [comment]
可以需要不同的 group id

**Comment by chenhp** [comment]
> 可以需要不同的 group id

我试试

**Comment by yangqiangqiang0327** [comment]
我在同步mysql的遇到点不明白的地方，能加下您的联系方式吗？这是我qq:1206783019

**Comment by chenhp** [comment]
> 我在同步mysql的遇到点不明白的地方，能加下您的联系方式吗？这是我qq:1206783019

直接说呗，我也还在探索。。。

**Comment by yangqiangqiang0327** [comment]
不能发图片。。。我在同步mysql数据到另一个mysql数据库 在运行 adapter 启动日志报了这样的异常 [main] ERROR c.a.o.canal.adapter.launcher.loader.CanalAdapterService - ## something goes wrong when starting up the canal client adapters:
java.lang.NullPointerException: null

**Comment by chenhp** [comment]
> 不能发图片。。。我在同步mysql数据到另一个mysql数据库 在运行 adapter 启动日志报了这样的异常 [main] ERROR c.a.o.canal.adapter.launcher.loader.CanalAdapterService - ## something goes wrong when starting up the canal client adapters:
> java.lang.NullPointerException: null

你看下 issue里面有人提过这个没
