### ISSUE TITLE
Canal 的交流群，Canal 太难了！

### ISSUE THREAD

**Issue by xmt1139057136** [alibaba/canal#2536]
## Question

Canal 的交流群，Canal 太难了！
我太难了！
![image](https://user-images.githubusercontent.com/23303979/71806970-30854980-30a5-11ea-9fc2-22eb2e1a5d5b.png)

**Comment by pangjianhua** [comment]
> ## Question
> Canal 的交流群，Canal 太难了！
> 我太难了！
> ![image](https://user-images.githubusercontent.com/23303979/71806970-30854980-30a5-11ea-9fc2-22eb2e1a5d5b.png)

过期了，兄弟

**Comment by alberta0714** [comment]
大年底的, 大佬们都巨忙~  另外还有裁员风波!~

**Comment by alberta0714** [comment]
咱们程序猿的业余脑力价值越来越没精力实现了.

**Comment by linjiaolin** [comment]
还有交流群呢？？？



---原始邮件---
发件人: "alberta0714"<notifications@github.com&gt;
发送时间: 2020年1月16日(周四) 中午11:11
收件人: "alibaba/canal"<canal@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [alibaba/canal] Canal 的交流群，Canal 太难了！ (#2536)



大年底的, 大佬们都巨忙~  另外还有裁员风波!~

**Comment by lengmianshi** [comment]
太难用，明明对着教程来，server启动了客户端无无法连接。第1步不受阻，无语

**Comment by kinbod** [comment]
> 太难用，明明对着教程来，server启动了客户端无无法连接。第1步不受阻，无语

https://blog.csdn.net/puhaiyang/article/details/100171395
对着这篇文档一步一步来，so easy,,只是代码有更新，需要修改部分代码，good luck

**Comment by kinbod** [comment]
> > ## Question
> > Canal 的交流群，Canal 太难了！
> > 我太难了！
> > ![image](https://user-images.githubusercontent.com/23303979/71806970-30854980-30a5-11ea-9fc2-22eb2e1a5d5b.png)
> 
> 过期了，兄弟

码代码也是一场修行，耐心耐心

**Comment by agapple** [comment]
https://github.com/alibaba/canal/wiki，wiki里有交流渠道

**Comment by xuej2s** [comment]
> > > ## Question
> > > Canal 的交流群，Canal 太难了！
> > > 我太难了！
> > > ![image](https://user-images.githubusercontent.com/23303979/71806970-30854980-30a5-11ea-9fc2-22eb2e1a5d5b.png)
> > 
> > 
> > 过期了，兄弟
> 
> 码代码也是一场修行，耐心耐心

https://mp.weixin.qq.com/s/Mu4wG3K8eZWUhrSV9wSGkQ 整理了一些自己实践时遇到的一些问题
