### ISSUE TITLE
docker启动canal总是不成功

### ISSUE THREAD

**Issue by XswSavage** [alibaba/canal#2541]
使用的镜像版本v1.1.4，mysql : 8.0.18

请问一下各位我这边如下命令启动不起来是什么情况
`docker run -d --name canal-server --net net-cluster  -p 11111:11111\
-e canal.instance.master.address=mysql:3306\
-e canal.instance.dbUsername=root\
-e canal.instance.dbPassword=123\
-e canal.instance.connectionCharset=UTF-8\
canal/canal-server:v1.1.4`

#日志
`[root@localhost canal]# docker logs canal-server 
DOCKER_DEPLOY_TYPE=VM
==> INIT /alidata/init/02init-sshd.sh
==> EXIT CODE: 0
==> INIT /alidata/init/fix-hosts.py
==> EXIT CODE: 0
==> INIT DEFAULT
Generating SSH1 RSA host key: [  OK  ]
Starting sshd: [  OK  ]
Starting crond: [  OK  ]
==> INIT DONE
==> RUN /home/admin/app.sh
==> START ...
start canal ...
[root@localhost canal]# 
`

是不是不支持8.0.18版本的mysql呀

**Comment by XswSavage** [comment]
`mysql`数据库换成5.7是ok的

**Comment by agapple** [comment]
建议先看下8.0.18对应的报错内容

**Comment by MutaoCn** [comment]
我也是卡在start canal ...

**Comment by hrjchampion** [comment]
我也是卡在start canal ..

**Comment by wyj-hb** [comment]
我也是卡在start canal ..
