### ISSUE TITLE
adapter不支持一个数据源同步到2个mysql目标吗？

### ISSUE THREAD

**Issue by chenhp** [alibaba/canal#2543]
groups配置了多个mysql目标始终只有第一个生效

**Comment by chenhp** [comment]
我的配置;
 - instance: example # canal instance Name or mq topic name
    groups:
    - groupId: g1
      outerAdapters:
      - name: rdb
        key: mysql1
        properties:
          jdbc.driverClassName: com.mysql.jdbc.Driver
          jdbc.url: jdbc:mysql://ip1:3306/test?useUnicode=true
          jdbc.username: xx
          jdbc.password: xx
    - groupId: g2
      outerAdapters:
      - name: rdb
        key: mysql2
        properties:
          jdbc.driverClassName: com.mysql.jdbc.Driver
          jdbc.url: jdbc:mysql://ip2:3306/othertest?useUnicode=true
          jdbc.username: xx
          jdbc.password: xx

**Comment by yangqiangqiang0327** [comment]
能把第二个 key: mysql2 换成 key: mysql1 再试下呢？

**Comment by chenhp** [comment]
> 能把第二个 key: mysql2 换成 key: mysql1 再试下呢？

没用

**Comment by yangqiangqiang0327** [comment]
在 conf/rdb/ 下面的 yml 文件，一张表一个 yml文件即可。如果同步数据量大，可以用两个instance实例分别检测一张表

**Comment by chenhp** [comment]
> 在 conf/rdb/ 下面的 yml 文件，一张表一个 yml文件即可。如果同步数据量大，可以用两个instance实例分别检测一张表

我是需要一张表数据同步到2个数据库，并且canal-adapter要求schema必须一样，有点不符合我的需求了

**Comment by yangqiangqiang0327** [comment]
我想，用两个实例 去分别同步到 两个数据库，是否可以？

**Comment by chenhp** [comment]
> 我想，用两个实例 去分别同步到 两个数据库，是否可以？

可以

**Comment by Minho-cyber** [comment]
所以您这个配置成功了么，同步到2个mysql目标

**Comment by Minho-cyber** [comment]
请教一下，配置一个数据源同步到2个mysql目标，两个目标端的库名和表名都不同。用的两个instance，怎么配置
  canalAdapters:
  - instance: example_model # canal instance Name or mq topic name
    groups:
    - groupId: g1
      outerAdapters:
      - name: logger
      - name: rdb
        key: mysql1
        properties:
          jdbc.driverClassName: com.mysql.jdbc.Drive
  - instance: db_12_test_3306
    groups:
    - groupId: g2
      outerAdapters:
      - name: logger
      - name: rdb
        key: mysql2
        properties:
          jdbc.driverClassName: com.mysql.jdbc.Driver

**Comment by yangqiangqiang0327** [comment]
可以。https://blog.csdn.net/qq_42496461/article/details/103927145?spm=1001.2014.3001.5501


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/canal"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月10日(星期一) 晚上6:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/canal] adapter不支持一个数据源同步到2个mysql目标吗？ (#2543)





 
请教一下，配置一个数据源同步到2个mysql目标，两个目标端的库名和表名都不同。用的两个instance，怎么配置
 canalAdapters:
  
instance: example_model # canal instance Name or mq topic name
 groups:  
groupId: g1
 outerAdapters:  
name: logger
 
name: rdb
 key: mysql1
 properties:
 jdbc.driverClassName: com.mysql.jdbc.Drive
  
  
 
instance: db_12_test_3306
 groups:  
groupId: g2
 outerAdapters:  
name: logger
 
name: rdb
 key: mysql2
 properties:
 jdbc.driverClassName: com.mysql.jdbc.Driver

**Comment by Minho-cyber** [comment]
> 可以。https://blog.csdn.net/qq_42496461/article/details/103927145?spm=1001.2014.3001.5501
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "alibaba/canal" ***@***.***&gt;; 发送时间:&nbsp;2021年5月10日(星期一) 晚上6:24 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [alibaba/canal] adapter不支持一个数据源同步到2个mysql目标吗？ (#2543) 请教一下，配置一个数据源同步到2个mysql目标，两个目标端的库名和表名都不同。用的两个instance，怎么配置 canalAdapters: instance: example_model # canal instance Name or mq topic name groups: groupId: g1 outerAdapters: name: logger name: rdb key: mysql1 properties: jdbc.driverClassName: com.mysql.jdbc.Drive instance: db_12_test_3306 groups: groupId: g2 outerAdapters: name: logger name: rdb key: mysql2 properties: jdbc.driverClassName: com.mysql.jdbc.Driver — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

你好，instance.properties，canal.properties，application.yml都按照文档配置了。
adapter日志，实例"example_model"有两条，写入目标成功。但另外一个实例"db_12_test_3306"只有一条日志，并且没有写入另一个目标库：
2021-05-11 13:46:14.818 [pool-41-thread-1] INFO  c.a.o.canal.client.adapter.logger.LoggerAdapterExample - DML: {"data":[{"rowid":7572,"task_id":"321","log_type":"2","trigger_type":"1","enter_the_reference":null,"antiparametric":"","request_time":"14pk","create_id":"system","create_date":1620613020000}],"database":"db_product_queue_out","destination":"db_12_test_3306","es":1620711974000,"groupId":null,"isDdl":false,"old":[{"request_time":"qwer"}],"pkNames":["rowid"],"sql":"","table":"t_model_record_log","ts":1620711974818,"type":"UPDATE"}
2021-05-11 13:46:14.912 [pool-40-thread-1] INFO  c.a.o.canal.client.adapter.logger.LoggerAdapterExample - DML: {"data":[{"rowid":7572,"task_id":"321","log_type":"2","trigger_type":"1","enter_the_reference":null,"antiparametric":"","request_time":"14pk","create_id":"system","create_date":1620613020000}],"database":"db_product_queue_out","destination":"example_model","es":1620711974000,"groupId":null,"isDdl":false,"old":[{"request_time":"qwer"}],"pkNames":["rowid"],"sql":"","table":"t_model_record_log","ts":1620711974912,"type":"UPDATE"}
2021-05-11 13:46:15.214 [pool-34-thread-1] DEBUG c.a.o.canal.client.adapter.rdb.service.RdbSyncService - DML: {"data":{"rowid":7572,"task_id":"321","log_type":"2","trigger_type":"1","enter_the_reference":null,"antiparametric":"","request_time":"14pk","create_id":"system","create_date":1620613020000},"database":"db_product_queue_out","destination":"example_model","old":{"request_time":"qwer"},"table":"t_model_record_log","type":"UPDATE"}
请问老师怎么解决

**Comment by Minho-cyber** [comment]
> > 可以。https://blog.csdn.net/qq_42496461/article/details/103927145?spm=1001.2014.3001.5501
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: "alibaba/canal" _**@**_._**>; 发送时间: 2021年5月10日(星期一) 晚上6:24 _**@**_.**_>; _**@**_._**_**@**_.**_>; 主题: Re: [alibaba/canal] adapter不支持一个数据源同步到2个mysql目标吗？ (#2543) 请教一下，配置一个数据源同步到2个mysql目标，两个目标端的库名和表名都不同。用的两个instance，怎么配置 canalAdapters: instance: example_model # canal instance Name or mq topic name groups: groupId: g1 outerAdapters: name: logger name: rdb key: mysql1 properties: jdbc.driverClassName: com.mysql.jdbc.Drive instance: db_12_test_3306 groups: groupId: g2 outerAdapters: name: logger name: rdb key: mysql2 properties: jdbc.driverClassName: com.mysql.jdbc.Driver — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> 你好，instance.properties，canal.properties，application.yml都按照文档配置了。
> adapter日志，实例"example_model"有两条，写入目标成功。但另外一个实例"db_12_test_3306"只有一条日志，并且没有写入另一个目标库：
> 2021-05-11 13:46:14.818 [pool-41-thread-1] INFO c.a.o.canal.client.adapter.logger.LoggerAdapterExample - DML: {"data":[{"rowid":7572,"task_id":"321","log_type":"2","trigger_type":"1","enter_the_reference":null,"antiparametric":"","request_time":"14pk","create_id":"system","create_date":1620613020000}],"database":"db_product_queue_out","destination":"db_12_test_3306","es":1620711974000,"groupId":null,"isDdl":false,"old":[{"request_time":"qwer"}],"pkNames":["rowid"],"sql":"","table":"t_model_record_log","ts":1620711974818,"type":"UPDATE"}
> 2021-05-11 13:46:14.912 [pool-40-thread-1] INFO c.a.o.canal.client.adapter.logger.LoggerAdapterExample - DML: {"data":[{"rowid":7572,"task_id":"321","log_type":"2","trigger_type":"1","enter_the_reference":null,"antiparametric":"","request_time":"14pk","create_id":"system","create_date":1620613020000}],"database":"db_product_queue_out","destination":"example_model","es":1620711974000,"groupId":null,"isDdl":false,"old":[{"request_time":"qwer"}],"pkNames":["rowid"],"sql":"","table":"t_model_record_log","ts":1620711974912,"type":"UPDATE"}
> 2021-05-11 13:46:15.214 [pool-34-thread-1] DEBUG c.a.o.canal.client.adapter.rdb.service.RdbSyncService - DML: {"data":{"rowid":7572,"task_id":"321","log_type":"2","trigger_type":"1","enter_the_reference":null,"antiparametric":"","request_time":"14pk","create_id":"system","create_date":1620613020000},"database":"db_product_queue_out","destination":"example_model","old":{"request_time":"qwer"},"table":"t_model_record_log","type":"UPDATE"}
> 请问老师怎么解决



> > 可以。https://blog.csdn.net/qq_42496461/article/details/103927145?spm=1001.2014.3001.5501
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: "alibaba/canal" _**@**_._**>; 发送时间: 2021年5月10日(星期一) 晚上6:24 _**@**_.**_>; _**@**_._**_**@**_.**_>; 主题: Re: [alibaba/canal] adapter不支持一个数据源同步到2个mysql目标吗？ (#2543) 请教一下，配置一个数据源同步到2个mysql目标，两个目标端的库名和表名都不同。用的两个instance，怎么配置 canalAdapters: instance: example_model # canal instance Name or mq topic name groups: groupId: g1 outerAdapters: name: logger name: rdb key: mysql1 properties: jdbc.driverClassName: com.mysql.jdbc.Drive instance: db_12_test_3306 groups: groupId: g2 outerAdapters: name: logger name: rdb key: mysql2 properties: jdbc.driverClassName: com.mysql.jdbc.Driver — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> 你好，instance.properties，canal.properties，application.yml都按照文档配置了。
> adapter日志，实例"example_model"有两条，写入目标成功。但另外一个实例"db_12_test_3306"只有一条日志，并且没有写入另一个目标库：
> 2021-05-11 13:46:14.818 [pool-41-thread-1] INFO c.a.o.canal.client.adapter.logger.LoggerAdapterExample - DML: {"data":[{"rowid":7572,"task_id":"321","log_type":"2","trigger_type":"1","enter_the_reference":null,"antiparametric":"","request_time":"14pk","create_id":"system","create_date":1620613020000}],"database":"db_product_queue_out","destination":"db_12_test_3306","es":1620711974000,"groupId":null,"isDdl":false,"old":[{"request_time":"qwer"}],"pkNames":["rowid"],"sql":"","table":"t_model_record_log","ts":1620711974818,"type":"UPDATE"}
> 2021-05-11 13:46:14.912 [pool-40-thread-1] INFO c.a.o.canal.client.adapter.logger.LoggerAdapterExample - DML: {"data":[{"rowid":7572,"task_id":"321","log_type":"2","trigger_type":"1","enter_the_reference":null,"antiparametric":"","request_time":"14pk","create_id":"system","create_date":1620613020000}],"database":"db_product_queue_out","destination":"example_model","es":1620711974000,"groupId":null,"isDdl":false,"old":[{"request_time":"qwer"}],"pkNames":["rowid"],"sql":"","table":"t_model_record_log","ts":1620711974912,"type":"UPDATE"}
> 2021-05-11 13:46:15.214 [pool-34-thread-1] DEBUG c.a.o.canal.client.adapter.rdb.service.RdbSyncService - DML: {"data":{"rowid":7572,"task_id":"321","log_type":"2","trigger_type":"1","enter_the_reference":null,"antiparametric":"","request_time":"14pk","create_id":"system","create_date":1620613020000},"database":"db_product_queue_out","destination":"example_model","old":{"request_time":"qwer"},"table":"t_model_record_log","type":"UPDATE"}
> 请问老师怎么解决

已经解决。。 用了一个instance即可。
