### ISSUE TITLE
CanalParseException: parse row data failed. column size is not match for table:user.user_public_info,47 vs 45

### ISSUE THREAD

**Issue by BigData-YC** [alibaba/canal#2544]
问几个问题：
1、集群模式是不是就是canal—server的高可用模式？？
2、instance出现问题之后，会不会自动切换到另一个server重启？？
3、比如ddl之后，表结构h2和mysql不一样了，instance会死，会自动切换server吗？？
4、使用tsdb开启功能，集群模式，需要配置tsdb数据库吗？？
5、使用了canal—admin，重启instance会不会重新生成h2文件？？

由于使用的canal-admin管理配置文件，canal-server使用的是集群模式？？？？

**Comment by user-GitHub-user** [comment]
> 问几个问题：
> 1、集群模式是不是就是canal—server的高可用模式？？
> 2、instance出现问题之后，会不会自动切换到另一个server重启？？
> 3、比如ddl之后，表结构h2和mysql不一样了，instance会死，会自动切换server吗？？
> 4、使用tsdb开启功能，集群模式，需要配置tsdb数据库吗？？
> 5、使用了canal—admin，重启instance会不会重新生成h2文件？？
> 
> 由于使用的canal-admin管理配置文件，canal-server使用的是集群模式？？？？

我的理解：
1.集群一般是指做了HA高可用的集群，canal的HA有server和client两种。
2 and 3.instance出现问题得看是什么问题，如再server详情里手动停止instance,HA的各个server会抢占instance，手动停止一台server，instance会转移到其他server，instance如果发生内部错误，如题主的列不对应的问题，instance就不会切换，会导致数据问题。
4.集群建议配置tsdb数据库，我通过设置tsdb为mysql，解决了ddl可能出现列不对应的情况。
5.我之前测试的结果是重启instance，不会重新生成h2元数据文件，列不一致的错误还是会出现。
6.是否使用admin和是否集群模式没有关系，是否集群模式要看你是否配置了zk，实现了server、client高可用。

**Comment by BigData-YC** [comment]
谢谢你的回答



---Original---

**Comment by BigData-YC** [comment]
我按照官网的配置：https://github.com/alibaba/canal/wiki/TableMetaTSDB
第一步、canal.properties里面配置选择使用了mysql-tsdb
--canal.instance.tsdb.spring.xml=classpath:spring/tsdb/h2-tsdb.xml
canal.instance.tsdb.spring.xml=classpath:spring/tsdb/mysql-tsdb.xml
第二步、在instance.properties里面配置了mysql的连接地址（canal_tsdb库存在，root所有权限）
canal.instance.tsdb.enable=true
canal.instance.tsdb.url=jdbc:mysql://hadoop:3306/canal_tsdb
canal.instance.tsdb.dbUsername=root
canal.instance.tsdb.dbPassword=root

也报错了！！！！
2020-01-10 17:22:23.857 [Druid-ConnectionPool-Create-1405329096] ERROR com.alibaba.druid.pool.DruidDataSource - create connection SQLException, url: jdbc:h2:../conf/hadoop/h2;CACHE_SIZE=1000;MODE=MYSQL;, errorCode 0, state null
java.sql.SQLException: connect error, url jdbc:h2:../conf/hadoop/h2;CACHE_SIZE=1000;MODE=MYSQL;, driverClass com.mysql.jdbc.Driver
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1582) ~[druid-1.1.9.jar:1.1.9]
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2466) ~[druid-1.1.9.jar:1.1.9]
2020-01-10 17:22:24.358 [Druid-ConnectionPool-Create-1405329096] ERROR com.alibaba.druid.pool.DruidDataSource - create con
请问，你怎么配置tsdb的数据库的？？？？？

我的canal是1.1.4版本，在本地集群canal-server单个topic测试时，添加删除字段再做dml处理都没有问题？？？？

**Comment by user-GitHub-user** [comment]
> 我按照官网的配置：https://github.com/alibaba/canal/wiki/TableMetaTSDB
> 第一步、canal.properties里面配置选择使用了mysql-tsdb
> --canal.instance.tsdb.spring.xml=classpath:spring/tsdb/h2-tsdb.xml
> canal.instance.tsdb.spring.xml=classpath:spring/tsdb/mysql-tsdb.xml
> 第二步、在instance.properties里面配置了mysql的连接地址（canal_tsdb库存在，root所有权限）
> canal.instance.tsdb.enable=true
> canal.instance.tsdb.url=jdbc:mysql://hadoop:3306/canal_tsdb
> canal.instance.tsdb.dbUsername=root
> canal.instance.tsdb.dbPassword=root
> 
> 也报错了！！！！
> 2020-01-10 17:22:23.857 [Druid-ConnectionPool-Create-1405329096] ERROR com.alibaba.druid.pool.DruidDataSource - create connection SQLException, url: jdbc:h2:../conf/hadoop/h2;CACHE_SIZE=1000;MODE=MYSQL;, errorCode 0, state null
> java.sql.SQLException: connect error, url jdbc:h2:../conf/hadoop/h2;CACHE_SIZE=1000;MODE=MYSQL;, driverClass com.mysql.jdbc.Driver
> at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1582) ~[druid-1.1.9.jar:1.1.9]
> at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2466) ~[druid-1.1.9.jar:1.1.9]
> 2020-01-10 17:22:24.358 [Druid-ConnectionPool-Create-1405329096] ERROR com.alibaba.druid.pool.DruidDataSource - create con
> 请问，你怎么配置tsdb的数据库的？？？？？
> 
> 我的canal是1.1.4版本，在本地集群canal-server单个topic测试时，添加删除字段再做dml处理都没有问题？？？？

看错误，你连接的还是h2,却用的jdbc驱动，你可以检查你的canal.properties里是否还有h2配置未注释掉，并将mysql的tsdb配置也配置一份到canal.properties：
canal.instance.tsdb.enable=true
canal.instance.tsdb.url=jdbc:mysql://hadoop:3306/canal_tsdb
canal.instance.tsdb.dbUsername=root
canal.instance.tsdb.dbPassword=root
不一致主要是因为h2用本地文件存储元数据，当你有配置client HA时，多台client的h2元数据文件不一致导致。用mysql可以统一管理。

**Comment by BigData-YC** [comment]
#canal.instance.tsdb.url=jdbc:h2:${canal.instance.tsdb.dir}/h2;CACHE_SIZE=1000;MODE=MYSQL;
canal.instance.tsdb.url=jdbc:mysql://127.0.0.1:3306/canal_tsdb
要把这个注释了，可以了。。。
配置了这个instance由于ddl挂掉了会不会在另一个server端自动重启？？？？
其他原因导致instance挂了能不能设置重启时间或者次数？？？？

**Comment by user-GitHub-user** [comment]
> #canal.instance.tsdb.url=jdbc:h2:${canal.instance.tsdb.dir}/h2;CACHE_SIZE=1000;MODE=MYSQL;
> canal.instance.tsdb.url=jdbc:mysql://127.0.0.1:3306/canal_tsdb
> 要把这个注释了，可以了。。。
> 配置了这个instance由于ddl挂掉了会不会在另一个server端自动重启？？？？
> 其他原因导致instance挂了能不能设置重启时间或者次数？？？？

配置了mysql的tsdb后ddl应该就不会导致instance错误，按我理解，instance进程如果停止，就切换server,但instance内部发生类似列不一致的错误，与zk的连接没有断的话，应该不会切换，没有碰到具体案例，不好说。
第二点不知道，没有相关功能文档说明。

**Comment by eskyzdt** [comment]
好多文档阿里自己拿着用了,才不会轻易放出来

**Comment by changwenwen** [comment]
> > 问几个问题：
> > 1、集群模式是不是就是canal—server的高可用模式？？
> > 2、instance出现问题之后，会不会自动切换到另一个server重启？？
> > 3、比如ddl之后，表结构h2和mysql不一样了，instance会死，会自动切换server吗？？
> > 4、使用tsdb开启功能，集群模式，需要配置tsdb数据库吗？？
> > 5、使用了canal—admin，重启instance会不会重新生成h2文件？？
> > 由于使用的canal-admin管理配置文件，canal-server使用的是集群模式？？？？
> 
> 我的理解：
> 1.集群一般是指做了HA高可用的集群，canal的HA有server和client两种。
> 2 and 3.instance出现问题得看是什么问题，如再server详情里手动停止instance,HA的各个server会抢占instance，手动停止一台server，instance会转移到其他server，instance如果发生内部错误，如题主的列不对应的问题，instance就不会切换，会导致数据问题。
> 4.集群建议配置tsdb数据库，我通过设置tsdb为mysql，解决了ddl可能出现列不对应的情况。
> 5.我之前测试的结果是重启instance，不会重新生成h2元数据文件，列不一致的错误还是会出现。
> 6.是否使用admin和是否集群模式没有关系，是否集群模式要看你是否配置了zk，实现了server、client高可用。

大佬好，canal HA模式下需要给各个节点配置相同的tsdb，这样切换节点的时候才不会报列不对应的错吗？

**Comment by BigData-YC** [comment]
是的，HA需要将不同的Server配置同一个tsdb。官网介绍配置了tsdb是可以解决列不对应的问题。



---Original---

**Comment by liujiansgit** [comment]
> > 我按照官网的配置：https://github.com/alibaba/canal/wiki/TableMetaTSDB
> > 第一步、canal.properties里面配置选择使用了mysql-tsdb
> > --canal.instance.tsdb.spring.xml=classpath:spring/tsdb/h2-tsdb.xml
> > canal.instance.tsdb.spring.xml=classpath:spring/tsdb/mysql-tsdb.xml
> > 第二步、在instance.properties里面配置了mysql的连接地址（canal_tsdb库存在，root所有权限）
> > canal.instance.tsdb.enable=true
> > canal.instance.tsdb.url=jdbc:mysql://hadoop:3306/canal_tsdb
> > canal.instance.tsdb.dbUsername=root
> > canal.instance.tsdb.dbPassword=root
> > 也报错了！！！！
> > 2020-01-10 17:22:23.857 [Druid-ConnectionPool-Create-1405329096] ERROR com.alibaba.druid.pool.DruidDataSource - create connection SQLException, url: jdbc:h2:../conf/hadoop/h2;CACHE_SIZE=1000;MODE=MYSQL;, errorCode 0, state null
> > java.sql.SQLException: connect error, url jdbc:h2:../conf/hadoop/h2;CACHE_SIZE=1000;MODE=MYSQL;, driverClass com.mysql.jdbc.Driver
> > at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1582) ~[druid-1.1.9.jar:1.1.9]
> > at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2466) ~[druid-1.1.9.jar:1.1.9]
> > 2020-01-10 17:22:24.358 [Druid-ConnectionPool-Create-1405329096] ERROR com.alibaba.druid.pool.DruidDataSource - create con
> > 请问，你怎么配置tsdb的数据库的？？？？？
> > 我的canal是1.1.4版本，在本地集群canal-server单个topic测试时，添加删除字段再做dml处理都没有问题？？？？
> 
> 看错误，你连接的还是h2,却用的jdbc驱动，你可以检查你的canal.properties里是否还有h2配置未注释掉，并将mysql的tsdb配置也配置一份到canal.properties：
> canal.instance.tsdb.enable=true
> canal.instance.tsdb.url=jdbc:mysql://hadoop:3306/canal_tsdb
> canal.instance.tsdb.dbUsername=root
> canal.instance.tsdb.dbPassword=root
> 不一致主要是因为h2用本地文件存储元数据，当你有配置client HA时，多台client的h2元数据文件不一致导致。用mysql可以统一管理。

大佬请教下，目前已经是集群模式，但是tsdb没有使用mysql可以直接切换为使用mysql吗？目前经常出现列不对应的问题
