### ISSUE TITLE
关于发送kafka的异常处理优化建议

### ISSUE THREAD

**Issue by yc7799** [alibaba/canal#2545]
大佬，发kafka那块，感觉有些异常可以考虑忽略，比如这个异常，是kafka集群限制的，否则canal位点得不到提交，需要成本运维。本人愚见如下：
1、计数这种可以忽略的异常。
2、根据不同场景，能够选择控制是否过滤。
祝好！

![image](https://user-images.githubusercontent.com/29529214/72132363-b4974400-33b9-11ea-8c18-0b711fc83c2f.png)

**Comment by agapple** [comment]
是数据包过大导致写入失败么？ 这个adapter写消息的时候有一个重试次数的限制，默认是无限制重试，可以调整
