### ISSUE TITLE
按照Canal Admin Guide操作，启动不起来

### ISSUE THREAD

**Issue by pangjianhua** [alibaba/canal#2547]
## Question
`sh  bin/startup.sh`
`cd to /tmp/canal-admin/bin for workaround relative path`
`CLASSPATH :/tmp/canal-admin/bin/../conf:/tmp/canal-admin/bin/../lib/zookeeper-3.4.5.jar:/tmp/canal-admin/bin/../lib/zkclient-0.10.jar:/tmp/canal-admin/bin/../lib/xmlunit-core-2.5.1.jar:/tmp/canal-admin/bin/../lib/validation-api-2.0.1.Final.jar:/tmp/canal-admin/bin/../lib/tomcat-embed-websocket-8.5.29.jar:/tmp/canal-admin/bin/../lib/tomcat-embed-el-8.5.29.jar:/tmp/canal-admin/bin/../lib/tomcat-embed-core-8.5.29.jar:/tmp/canal-admin/bin/../lib/spring-webmvc-5.0.5.RELEASE.jar:/tmp/canal-admin/bin/../lib/spring-web-5.0.5.RELEASE.jar:/tmp/canal-admin/bin/../lib/spring-tx-5.0.5.RELEASE.jar:/tmp/canal-admin/bin/../lib/spring-test-5.0.5.RELEASE.jar:/tmp/canal-admin/bin/../lib/spring-orm-5.0.5.RELEASE.jar:/tmp/canal-admin/bin/../lib/spring-jdbc-5.0.5.RELEASE.jar:/tmp/canal-admin/bin/../lib/spring-jcl-5.0.5.RELEASE.jar:/tmp/canal-admin/bin/../lib/spring-expression-5.0.5.RELEASE.jar:/tmp/canal-admin/bin/../lib/spring-core-5.0.5.RELEASE.jar:/tmp/canal-admin/bin/../lib/spring-context-5.0.5.RELEASE.jar:/tmp/canal-admin/bin/../lib/spring-boot-test-autoconfigure-2.0.1.RELEASE.jar:/tmp/canal-admin/bin/../lib/spring-boot-test-2.0.1.RELEASE.jar:/tmp/canal-admin/bin/../lib/spring-boot-starter-web-2.0.1.RELEASE.jar:/tmp/canal-admin/bin/../lib/spring-boot-starter-tomcat-2.0.1.RELEASE.jar:/tmp/canal-admin/bin/../lib/spring-boot-starter-test-2.0.1.RELEASE.jar:/tmp/canal-admin/bin/../lib/spring-boot-starter-logging-2.0.1.RELEASE.jar:/tmp/canal-admin/bin/../lib/spring-boot-starter-json-2.0.1.RELEASE.jar:/tmp/canal-admin/bin/../lib/spring-boot-starter-jdbc-2.0.1.RELEASE.jar:/tmp/canal-admin/bin/../lib/spring-boot-starter-2.0.1.RELEASE.jar:/tmp/canal-admin/bin/../lib/spring-boot-autoconfigure-2.0.1.RELEASE.jar:/tmp/canal-admin/bin/../lib/spring-boot-2.0.1.RELEASE.jar:/tmp/canal-admin/bin/../lib/spring-beans-5.0.5.RELEASE.jar:/tmp/canal-admin/bin/../lib/spring-aop-5.0.5.RELEASE.jar:/tmp/canal-admin/bin/../lib/snakeyaml-1.19.jar:/tmp/canal-admin/bin/../lib/slf4j-api-1.7.25.jar:/tmp/canal-admin/bin/../lib/protobuf-java-3.6.1.jar:/tmp/canal-admin/bin/../lib/persistence-api-2.2.2.jar:/tmp/canal-admin/bin/../lib/objenesis-2.6.jar:/tmp/canal-admin/bin/../lib/netty-all-4.1.23.Final.jar:/tmp/canal-admin/bin/../lib/netty-3.2.2.Final.jar:/tmp/canal-admin/bin/../lib/mysql-connector-java-5.1.40.jar:/tmp/canal-admin/bin/../lib/mockito-core-2.15.0.jar:/tmp/canal-admin/bin/../lib/logback-core-1.2.3.jar:/tmp/canal-admin/bin/../lib/logback-classic-1.2.3.jar:/tmp/canal-admin/bin/../lib/log4j-to-slf4j-2.10.0.jar:/tmp/canal-admin/bin/../lib/log4j-api-2.10.0.jar:/tmp/canal-admin/bin/../lib/jul-to-slf4j-1.7.25.jar:/tmp/canal-admin/bin/../lib/jsr305-3.0.2.jar:/tmp/canal-admin/bin/../lib/json-smart-2.3.jar:/tmp/canal-admin/bin/../lib/json-path-2.4.0.jar:/tmp/canal-admin/bin/../lib/jsonassert-1.5.0.jar:/tmp/canal-admin/bin/../lib/jcl-over-slf4j-1.7.25.jar:/tmp/canal-admin/bin/../lib/jboss-logging-3.3.2.Final.jar:/tmp/canal-admin/bin/../lib/javax.annotation-api-1.3.2.jar:/tmp/canal-admin/bin/../lib/jackson-module-parameter-names-2.9.5.jar:/tmp/canal-admin/bin/../lib/jackson-datatype-jsr310-2.9.5.jar:/tmp/canal-admin/bin/../lib/jackson-datatype-jdk8-2.9.5.jar:/tmp/canal-admin/bin/../lib/jackson-databind-2.9.5.jar:/tmp/canal-admin/bin/../lib/jackson-core-2.9.5.jar:/tmp/canal-admin/bin/../lib/jackson-annotations-2.9.0.jar:/tmp/canal-admin/bin/../lib/HikariCP-2.7.8.jar:/tmp/canal-admin/bin/../lib/hibernate-validator-6.0.9.Final.jar:/tmp/canal-admin/bin/../lib/hamcrest-library-1.3.jar:/tmp/canal-admin/bin/../lib/hamcrest-core-1.3.jar:/tmp/canal-admin/bin/../lib/guava-18.0.jar:/tmp/canal-admin/bin/../lib/fastjson-1.2.58.jar:/tmp/canal-admin/bin/../lib/ebean-types-1.3.jar:/tmp/canal-admin/bin/../lib/ebean-migration-11.16.2.jar:/tmp/canal-admin/bin/../lib/ebean-datasource-api-4.5.jar:/tmp/canal-admin/bin/../lib/ebean-datasource-4.5.2.jar:/tmp/canal-admin/bin/../lib/ebean-annotation-4.11.jar:/tmp/canal-admin/bin/../lib/ebean-11.41.1.jar:/tmp/canal-admin/bin/../lib/commons-logging-1.1.1.jar:/tmp/canal-admin/bin/../lib/commons-lang-2.6.jar:/tmp/canal-admin/bin/../lib/commons-io-2.4.jar:/tmp/canal-admin/bin/../lib/commons-codec-1.11.jar:/tmp/canal-admin/bin/../lib/commons-beanutils-1.8.2.jar:/tmp/canal-admin/bin/../lib/classmate-1.3.4.jar:/tmp/canal-admin/bin/../lib/canal.protocol-1.1.4.jar:/tmp/canal-admin/bin/../lib/canal.common-1.1.4.jar:/tmp/canal-admin/bin/../lib/canal-admin-server-1.1.4.jar:/tmp/canal-admin/bin/../lib/caffeine-2.6.2.jar:/tmp/canal-admin/bin/../lib/byte-buddy-agent-1.7.11.jar:/tmp/canal-admin/bin/../lib/byte-buddy-1.7.11.jar:/tmp/canal-admin/bin/../lib/avaje-classpath-scanner-api-2.2.jar:/tmp/canal-admin/bin/../lib/avaje-classpath-scanner-3.1.1.jar:/tmp/canal-admin/bin/../lib/assertj-core-3.9.1.jar:/tmp/canal-admin/bin/../lib/asm-5.0.4.jar:/tmp/canal-admin/bin/../lib/antlr4-runtime-4.7.2.jar:/tmp/canal-admin/bin/../lib/android-json-0.0.20131108.vaadin1.jar:/tmp/canal-admin/bin/../lib/accessors-smart-1.2.jar:`
`cd to /tmp/canal-admin for continue`
只有这些内容，没有其他错误提示，日志什么的也没有，求解答

**Comment by bitmyth** [comment]
修改 bin/startup.sh 66行
JAVA_OPTS="$JAVA_OPTS -XX:+UseG1GC -XX:MaxGCPauseMillis=250 -XX:+UseGCOverheadLimit -XX:+ExplicitGCInvokesConcurrent"

然后重新启动

**Comment by Brainhu** [comment]
修改脚本咩用用。

**Comment by ChenShnegLi** [comment]
> 修改脚本咩用用。



> 修改脚本咩用用。

修改vm内存参数，可以试试看

**Comment by sliever** [comment]
方便说一下是怎么解决这个问题的吗

**Comment by LDWBFS** [comment]
根本没用，1.15不行，1.14也不行，按照步骤启动，启动不起来，日志也没有，就尼玛离谱

**Comment by ChanaLii** [comment]
> 修改 bin/startup.sh 66行
> JAVA_OPTS="$JAVA_OPTS -XX:+UseG1GC -XX:MaxGCPauseMillis=250 -XX:+UseGCOverheadLimit -XX:+ExplicitGCInvokesConcurrent"
> 
> 然后重新启动

Doesn't work.

**Comment by zyu** [comment]
方便说一下是怎么解决这个问题的吗

**Comment by zyu** [comment]
根本没用，1.16不行，1.15不行，1.14也不行，

**Comment by wbh0505** [comment]
canal admin启动不起来 没日志 有方案解决吗

**Comment by RoanFan** [comment]
> anal admin启动不起来 没日志

老哥, 解决了吗?
