### ISSUE TITLE
canal支不支持字符加小数的库名匹配?

### ISSUE THREAD

**Issue by eskyzdt** [alibaba/canal#2548]
目前我司有个库名为abc4.0的表,用perl表达式匹配时总是匹配不上
我的写法是abc4.*\\..*    abc.*\\..
都无法匹配,
请问应该如何解决
canal是不是不支持字符加小数的库名格式呢?

**Comment by BigData-YC** [comment]
支持正则表达式

**Comment by eskyzdt** [comment]
> 
> 
> 支持正则表达式

不支持带小数点的正则表达式,而且你没说清楚,他是支持perl正则
