### ISSUE TITLE
docker环境，修改canal.metrics.pull.port后无法启动

### ISSUE THREAD

**Issue by ljjlinjunjie** [alibaba/canal#2549]
- [`*`] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [`*`] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment

* canal version
canal/canal-server:v1.1.4 
* mysql version
5.6.29

### Issue Description
修改canal.metrics.pull.port后，docker无法正常启动，1分钟左右重启一次，改回默认值则正常
修改后的docker日志输出

> DOCKER_DEPLOY_TYPE=VM
> ==> INIT /alidata/init/02init-sshd.sh
> ==> EXIT CODE: 0
> ==> INIT /alidata/init/fix-hosts.py
> ==> EXIT CODE: 0
> ==> INIT DEFAULT
> Starting sshd: [  OK  ]
> Starting crond: [  OK  ]
> ==> INIT DONE
> ==> RUN /home/admin/app.sh
> ==> START ...
> start canal ...
> DOCKER_DEPLOY_TYPE=VM
> ==> INIT /alidata/init/02init-sshd.sh
> ==> EXIT CODE: 0
> ==> INIT /alidata/init/fix-hosts.py
> ==> EXIT CODE: 0
> ==> INIT DEFAULT
> Starting sshd: [  OK  ]
> Starting crond: [  OK  ]
> ==> INIT DONE
> ==> RUN /home/admin/app.sh
> ==> START ...
> start canal ...

如此反复，不见successfull输出 
### Steps to reproduce
修改canal.metrics.pull.port端口，启动容器，canal日志无异常信息
### Expected behaviour
正常启动
### Actual behaviour
无法正常工作，一直自动重启

**Comment by aaron1989041** [comment]
我是用-e传入canal.admin.port=21110，过一会也是会挂掉，我趁着没挂之前去容器里看了下，发现传入的环境变量没生效，容器里面还是用11110.

**Comment by agapple** [comment]
建议-e变量指定后 bash模式启动，然后手工sh -x app.sh运行，看一下变量的读取情况
