### ISSUE TITLE
增加可指定订阅EventType的配置项

### ISSUE THREAD

**Issue by alberta0714** [alibaba/canal#2555]
## Why you need it?
下游业务(直连canal或通过kafka)大都仅用到了  EventType中的INSERT,DELETE,UPDATE.    其余类型大都用不到,   其中QUERY类型的消息巨大,  占用了大量kafka, Canal-client的IO. 造成性能损耗!

## How it could be?
希望在配置项中为每个instance增加自定义  事件类型, 如: 
example.eventTypes = INSERT, DELETE, UPDATE
或
example.eventTypes.filter = QUERY 

## Other related information
RocketMQ, kafka 提供了消息堆积, 大IO 和专业消费的方案. 意味着, 向MQ中发送消息越来越重要.  因此目前企业向MQ中存放消息的意愿非常强烈. 但同时也引发了我的顾虑:
1. canal专攻解析binlog 2. kafka专攻多消费  
基于以上背景那么Qa: 
1. kafka版本过低或才高怎么办?  接入成本如何
> 目前自己的解决方案是: 复用canal-server中的发送MQ的代码, 做定制化发送. 包括flat.
> kafka消费端可自由选择  使用官方的client 或  直接做常规flat类型消费. 

All those were what I thinked of , on pasted 2 monthes that I used canal.  -- by. Zhanchao sun

**Comment by alberta0714** [comment]
`
# binlog filter config
canal.instance.filter.druid.ddl = true
canal.instance.filter.query.dcl = false
canal.instance.filter.query.dml = false
canal.instance.filter.query.ddl = false
canal.instance.filter.table.error = false
canal.instance.filter.rows = false
canal.instance.filter.transaction.entry = false
`
找到了

**Comment by godchou** [comment]
canal.instance.filter.transaction.entry = false
我设置了这个也不好使
