### ISSUE TITLE
表字段新增删除,会报 CanalParseException: parse row data failed

### ISSUE THREAD

**Issue by Jmadman2** [alibaba/canal#2557]
## 版本 
canal 1.1.4
数据库 5.7

## 问题 
     对单表新增或删除字段都会引起表结构解析异常

## 原因
     instance的 h2.mv.db 缓存文件未更新

## 解决
1. 停止canal-server服务
2. 删除缓存文件 h2.mv.db
3. 启动canal-server服务

**Comment by agapple** [comment]
问题描述不清楚，提供一下问题复现的具体步骤

**Comment by shyandsy** [comment]
这个文件一般在什么位置
h2.mv.dbh2.mv.db
