### ISSUE TITLE
canal如何优雅的从1.1.3升级至1.1.4？

### ISSUE THREAD

**Issue by hcnysa** [alibaba/canal#2566]
## Question

如题，如何优雅的从1.1.3升级至1.1.4？

我希望将配置的管理交给canal-admin处理，能在不停服务的情况下平滑的升级吗？

如果停掉服务，怎么做才能保证数据的不丢失？(小部分重复数据可以接受)

**Comment by agapple** [comment]
canal-admin需要新的部署，不能直接原位升级
