### ISSUE TITLE
请问我改怎样解决：找不到或无法加载主类 com.alibaba.otter.canal.deployer.CanalLauncher的问题

### ISSUE THREAD

**Issue by cheapWhite** [alibaba/canal#2574]
## Question

问题：在window 64下，执行 startup.bat
<img width="783" alt="Snipaste_2020-02-13_16-10-02" src="https://user-images.githubusercontent.com/35496849/74413997-77701700-4e7b-11ea-80c1-d6345aa31a4d.png">
ng…]()

**Comment by agapple** [comment]
请先打包后再运行
