### ISSUE TITLE
server 端上报给 zk 的ip地址是无效的，此问题发生在多网卡机器上

### ISSUE THREAD

**Issue by geekyouth** [alibaba/canal#2579]
### environment

* canal version
canal.admin-1.1.4
canal.deployer-1.1.4

* mysql version
mysql  Ver 14.14 Distrib 5.7.29, for Linux (x86_64) using  EditLine wrapper

### Issue Description
canal server 集群上报给 zk集群的 address ip 地址是虚拟的地址，并没有实际意义。此问题发生在虚拟机搭建的centos7机器。ifconfig 出现三个网卡，只有ens33 网卡才是用来集群交互的网卡，理论上应该上报这个ip给zk。但实际上上报了虚拟的virbr0 ip，该ip并不能用来集群通信。
![image](https://user-images.githubusercontent.com/12899262/74614765-ba6d0b80-5155-11ea-87bd-b7aec103de74.png)
![image](https://user-images.githubusercontent.com/12899262/74614767-bd67fc00-5155-11ea-9383-aa4dffd40b48.png)

# 临时解决方案：
ifconfig virbr0 down
systemctl disable libvirtd
禁用centos 虚拟网卡，重启canal server，会上报ens33 网卡 ip

**Comment by Lintel-X** [comment]
canal.register.ip 好像就是解决这个问题的

**Comment by agapple** [comment]
LS正解
