### ISSUE TITLE
启停脚本能不能判断一下路径再执行啊？

### ISSUE THREAD

**Issue by geekyouth** [alibaba/canal#2580]
### environment

* canal version
canal.admin-1.1.4
canal.deployer-1.1.4

* mysql version
mysql  Ver 14.14 Distrib 5.7.29, for Linux (x86_64) using  EditLine wrapper

### Issue Description
在canal 家目录执行 bin/restart.sh
sh: stop.sh: 没有那个文件或目录
sh: startup.sh: 没有那个文件或目录

然后进入bin 路径，才可以执行。能否优化一下脚本？

![image](https://user-images.githubusercontent.com/12899262/74614892-c9a08900-5156-11ea-8e77-29e6603b3694.png)

**Comment by agapple** [comment]
可以提交一个PR给我
