### ISSUE TITLE
canal同步数据到kafka，监控delay显示延迟很大

### ISSUE THREAD

**Issue by luojun0513** [alibaba/canal#2583]
## Question

最近使用canal同步一张表的数据到kafka，每天晚上1点多会有一个定时任务批量更新这个表，会出现波峰情况，但是从监控上看，延迟最大竟然有4个多小时，有点理解不了。请大佬帮忙分析下，
监控图如下
![image](https://user-images.githubusercontent.com/12065622/74897402-f2808280-53d1-11ea-8c4b-70e5f6f1fb61.png)

kafka的配置如下：
`
canal.mq.retries = 1
canal.mq.batchSize = 49152
canal.mq.maxRequestSize = 1048576
canal.mq.lingerMs = 200
canal.mq.bufferMemory = 33554432
canal.mq.canalBatchSize = 50
canal.mq.canalGetTimeout = 100
canal.mq.flatMessage = true
canal.mq.compressionType = none
canal.mq.acks = 1
canal.mq.producerGroup = test
canal.mq.accessChannel = local
`

instance配置
`
canal.mq.topic=t_order
canal.mq.partitionsNum=20
canal.mq.partitionHash=d_business.t_order:id
`

还有我在开发环境进行了测试，同样的kafka配置，表结构。使用存储过程批量插入10000条数据，kafka消费端能很快消费完所有数据，但是监控的delay指标依然很高，blocking指标没有显示存在柱塞情况，不太清楚put get ack delay指标的计算方式，请大佬指点
![image](https://user-images.githubusercontent.com/12065622/74897464-25c31180-53d2-11ea-953d-28fc61d88ef5.png)

**Comment by kirin-13** [comment]
同问

**Comment by jianghanfen** [comment]
@luojun0513 @kirin-13 用的1.1.5也有这个问题，解决了没？

**Comment by kirin-13** [comment]
> @luojun0513 @kirin-13 用的1.1.5也有这个问题，解决了没？

kafka ack all改为1
