### ISSUE TITLE
canal1.1.4启动报错could not create java virtual machine (Java11)

### ISSUE THREAD

**Issue by mwz1994** [alibaba/canal#2587]
##canal1.1.4启动报错could not create java virtual machine (Java11)

OpenJDK 64-Bit Server VM warning: Ignoring option PermSize; support was removed in 8.0
OpenJDK 64-Bit Server VM warning: Ignoring option MaxPermSize; support was removed in 8.0
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
Unrecognized VM option 'UseCMSCompactAtFullCollection'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

**Comment by mwz1994** [comment]
用jdk8是可以的

**Comment by Oranzh** [comment]
看来我只能换成jdk8了
