### ISSUE TITLE
阿里云DRDS使用canal

### ISSUE THREAD

**Issue by Fox-Legend** [alibaba/canal#2590]
## Question
你好，咨询下使用阿里云的DRDS，一直报错，can't find start position和Variable @master_binlog_checksum can't be set to the value of @@global.binlog_checksum，请问是什么原因？

在使用canal时，怎么使用数据库已经有的账号？还是一定要用账号名为canal，密码为canal的账号才行？

**Comment by agapple** [comment]
canal无法直接链接DRDS，需要获取DRDS下RDS的列表，挨个创建一个canal instance进行消费
