### ISSUE TITLE
canal filter支持通配符

### ISSUE THREAD

**Issue by kirin-13** [alibaba/canal#2592]
## canal server的filter支持通配符问题

  使用canal server时有一个需求，数据库中有n多子表，子表名称如: mon_day_202002(按月创建) 或者day_table_20200227(按天创建).在配置canal server 发送消息到kafka时，
使用了如下配置
```
canal.mq.dynamicTopic=test:mydata.mon_day_2020_* 
```
或者
```
canal.mq.dynamicTopic=test:mydata.mon_day_2020_\\..*
```
但是canal server无法匹配到配置，无法创建topic。

请问该如何进行统配操作？

**Comment by Rmuyu** [comment]
您好，您这个有解决办法了吗？

**Comment by kirin-13** [comment]
> 您好，您这个有解决办法了吗？

已经解决了。

**Comment by leefj** [comment]
怎么解决的，麻烦贴个配置参考一下

**Comment by kirin-13** [comment]
> 怎么解决的，麻烦贴个配置参考一下

```
canal.mq.topic=default_topic
``` 

增加了这个配置
