### ISSUE TITLE
生产环境版本考量

### ISSUE THREAD

**Issue by keyganker** [alibaba/canal#260]
我们准备在生产环境使用`canal`，之前在测试环境同事搭建的是`1.0.22`版本，测试使用过程中发现了一些bug（如kill connection的问题），目前看基本上都在`1.0.23`修复了。后来注意到官方wiki推荐的是`1.0.19`版本，请问@agapple基于稳定性而言是推荐使用`1.0.19`版本吗？

**Comment by agapple** [comment]
估计是还没有及时更新文档，可以使用最新版本

**Comment by keyganker** [comment]
多谢多谢~ 我们也选了最新版本，这几天正在测试
