### ISSUE TITLE
canal-adapter怎么做集群？

### ISSUE THREAD

**Issue by maguanggit** [alibaba/canal#2608]
请问各位大佬， 我要同步到es上至少要保证稳定啊， canal-adapter怎么做集群呀？

**Comment by gaohanghbut** [comment]
有同样的需求，粗略看了下代码，感觉默认没法做集群。

要做集群做高可用可以用zk自己写个分配算法，有机器挂了就触发重新分配

**Comment by Hueason** [comment]
server做不了集群，官方给的方案是主备，是用抢占zk节点的方式做的，主挂了之后，备就会启动。
client的话如果是tcp方式，可以和server一样的主备；如果是mq方式，可以做集群，依赖mq的能力保证稳定

**Comment by maguanggit** [comment]
offset交给zookeeper, 也是一种方案.  要用canal这一套,  还要准备zk高可用,  感觉很麻烦.

**Comment by gongxg0302** [comment]
adapter tcp模式下canal.tcp.zookeeper.hosts配上，canal.tcp.server.host留白就行了
