### ISSUE TITLE
java客户端CanalConnector.subscribe()使用以下第二种正则过滤无效

### ISSUE THREAD

**Issue by githubchencai** [alibaba/canal#261]
使用canal的java api， 为什么用第三,四种有效；第二种正则无效，过滤全部呢
ps:canal server的conf/example/instance.properties的canal.instance.filter.regex没有配置

1.  所有表：.*   or  .*\\..*
2.  canal schema下所有表： canal\\..*
3.  canal下的以canal打头的表：canal\\.canal.*
4.  canal schema下的一张表：canal.test1
5.  多个规则组合使用：canal\\..*,mysql.test1,mysql.test2 (逗号分隔)

**Comment by alswl** [comment]
朋友，你这个 Issue 后来有什么结论么？
