### ISSUE TITLE
当mysql数据类型为enum时，监听到canal的数据变成了0，1，并不是枚举值

### ISSUE THREAD

**Issue by JDreamchaser** [alibaba/canal#2610]

**Comment by ShuningWan** [comment]
可以这样做临时解决
```java
private String getValue(Column column) {
		//目前只对 enum 做特殊处理 Set目前暂没处理 
		if (column.getMysqlType().startsWith("enum")) {
			String columnType = column.getMysqlType();
			String tempStr = columnType.substring(columnType.indexOf("(") + 1);
			tempStr = tempStr.substring(0, tempStr.length() - 1).replace("\'", "");
			List<String> typeList = SplitterUtil.splitList(tempStr);
			return StringUtil.isNotBlank(column.getValue()) ? typeList.get(Integer.valueOf(column.getValue()) - 1) : null;
		}
		return column.getValue();
	}

```

**Comment by agapple** [comment]
binlog里记录的就是对应二进制数据

**Comment by ShuningWan** [comment]
> binlog里记录的就是对应二进制数据

说的是 Entry ，很明显 拿到的数据 描述的像是下标一样的东西，并非只有 0,1，但是 Set 没有看懂

**Comment by jia2118290** [comment]
> 可以这样做临时解决
> 
> ```java
> private String getValue(Column column) {
> 		//目前只对 enum 做特殊处理 Set目前暂没处理 
> 		if (column.getMysqlType().startsWith("enum")) {
> 			String columnType = column.getMysqlType();
> 			String tempStr = columnType.substring(columnType.indexOf("(") + 1);
> 			tempStr = tempStr.substring(0, tempStr.length() - 1).replace("\'", "");
> 			List<String> typeList = SplitterUtil.splitList(tempStr);
> 			return StringUtil.isNotBlank(column.getValue()) ? typeList.get(Integer.valueOf(column.getValue()) - 1) : null;
> 		}
> 		return column.getValue();
> 	}
> ```
这是哪个版本？

**Comment by ShuningWan** [comment]
> > 可以这样做临时解决
> > ```java
> > private String getValue(Column column) {
> > 		//目前只对 enum 做特殊处理 Set目前暂没处理 
> > 		if (column.getMysqlType().startsWith("enum")) {
> > 			String columnType = column.getMysqlType();
> > 			String tempStr = columnType.substring(columnType.indexOf("(") + 1);
> > 			tempStr = tempStr.substring(0, tempStr.length() - 1).replace("\'", "");
> > 			List<String> typeList = SplitterUtil.splitList(tempStr);
> > 			return StringUtil.isNotBlank(column.getValue()) ? typeList.get(Integer.valueOf(column.getValue()) - 1) : null;
> > 		}
> > 		return column.getValue();
> > 	}
> > ```
> 
> 这是哪个版本？

当时是 1.1.3

**Comment by jia2118290** [comment]
> > > 可以这样做临时解决
> > > ```java
> > > private String getValue(Column column) {
> > > 		//目前只对 enum 做特殊处理 Set目前暂没处理 
> > > 		if (column.getMysqlType().startsWith("enum")) {
> > > 			String columnType = column.getMysqlType();
> > > 			String tempStr = columnType.substring(columnType.indexOf("(") + 1);
> > > 			tempStr = tempStr.substring(0, tempStr.length() - 1).replace("\'", "");
> > > 			List<String> typeList = SplitterUtil.splitList(tempStr);
> > > 			return StringUtil.isNotBlank(column.getValue()) ? typeList.get(Integer.valueOf(column.getValue()) - 1) : null;
> > > 		}
> > > 		return column.getValue();
> > > 	}
> > > ```
> > 
> > 
> > 这是哪个版本？
> 
> 当时是 1.1.3

采用你这个思路解决了  版本 1.1.4

**Comment by ShuningWan** [comment]
> > > > 可以这样做临时解决
> > > > ```java
> > > > private String getValue(Column column) {
> > > > 		//目前只对 enum 做特殊处理 Set目前暂没处理 
> > > > 		if (column.getMysqlType().startsWith("enum")) {
> > > > 			String columnType = column.getMysqlType();
> > > > 			String tempStr = columnType.substring(columnType.indexOf("(") + 1);
> > > > 			tempStr = tempStr.substring(0, tempStr.length() - 1).replace("\'", "");
> > > > 			List<String> typeList = SplitterUtil.splitList(tempStr);
> > > > 			return StringUtil.isNotBlank(column.getValue()) ? typeList.get(Integer.valueOf(column.getValue()) - 1) : null;
> > > > 		}
> > > > 		return column.getValue();
> > > > 	}
> > > > ```
> > > 
> > > 
> > > 这是哪个版本？
> > 
> > 
> > 当时是 1.1.3
> 
> 采用你这个思路解决了 版本 1.1.4

嗯  现在用的是 1.1.4

**Comment by jia2118290** [comment]
> > > 可以这样做临时解决
> > > ```java
> > > private String getValue(Column column) {
> > > 		//目前只对 enum 做特殊处理 Set目前暂没处理 
> > > 		if (column.getMysqlType().startsWith("enum")) {
> > > 			String columnType = column.getMysqlType();
> > > 			String tempStr = columnType.substring(columnType.indexOf("(") + 1);
> > > 			tempStr = tempStr.substring(0, tempStr.length() - 1).replace("\'", "");
> > > 			List<String> typeList = SplitterUtil.splitList(tempStr);
> > > 			return StringUtil.isNotBlank(column.getValue()) ? typeList.get(Integer.valueOf(column.getValue()) - 1) : null;
> > > 		}
> > > 		return column.getValue();
> > > 	}
> > > ```
> > 
> > 
> > 这是哪个版本？
> 
> 当时是 1.1.3

当时修改的位置你还记得吗，我发现还有部分数据有问题

**Comment by hhalei** [comment]
当前版本对这个问题做处理了吗

**Comment by jia2118290** [comment]
> 当前版本对这个问题做处理了吗

需要你自己做处理

**Comment by hhalei** [comment]
> > 当前版本对这个问题做处理了吗
> 
> 需要你自己做处理

好的，多谢，引用了上面的代码做了处理。

**Comment by yl-yue** [comment]
我是canal发送数据到mq里面时，枚举值已经是下标了，貌似只能改数据库类型解决么？
实体解析感觉工作量更大

**Comment by vincentwc** [comment]
> 可以这样做临时解决
> 
> ```java
> private String getValue(Column column) {
> 		//目前只对 enum 做特殊处理 Set目前暂没处理 
> 		if (column.getMysqlType().startsWith("enum")) {
> 			String columnType = column.getMysqlType();
> 			String tempStr = columnType.substring(columnType.indexOf("(") + 1);
> 			tempStr = tempStr.substring(0, tempStr.length() - 1).replace("\'", "");
> 			List<String> typeList = SplitterUtil.splitList(tempStr);
> 			return StringUtil.isNotBlank(column.getValue()) ? typeList.get(Integer.valueOf(column.getValue()) - 1) : null;
> 		}
> 		return column.getValue();
> 	}
> ```

你好，请问这个代码是要加在那个地方呢？

**Comment by vincentwc** [comment]
> 可以这样做临时解决
> 
> ```java
> private String getValue(Column column) {
> 		//目前只对 enum 做特殊处理 Set目前暂没处理 
> 		if (column.getMysqlType().startsWith("enum")) {
> 			String columnType = column.getMysqlType();
> 			String tempStr = columnType.substring(columnType.indexOf("(") + 1);
> 			tempStr = tempStr.substring(0, tempStr.length() - 1).replace("\'", "");
> 			List<String> typeList = SplitterUtil.splitList(tempStr);
> 			return StringUtil.isNotBlank(column.getValue()) ? typeList.get(Integer.valueOf(column.getValue()) - 1) : null;
> 		}
> 		return column.getValue();
> 	}
> ```

请教一下，这部分代码应该加在哪里呢？

**Comment by vincentwc** [comment]
> 可以这样做临时解决
> 
> ```java
> private String getValue(Column column) {
> 		//目前只对 enum 做特殊处理 Set目前暂没处理 
> 		if (column.getMysqlType().startsWith("enum")) {
> 			String columnType = column.getMysqlType();
> 			String tempStr = columnType.substring(columnType.indexOf("(") + 1);
> 			tempStr = tempStr.substring(0, tempStr.length() - 1).replace("\'", "");
> 			List<String> typeList = SplitterUtil.splitList(tempStr);
> 			return StringUtil.isNotBlank(column.getValue()) ? typeList.get(Integer.valueOf(column.getValue()) - 1) : null;
> 		}
> 		return column.getValue();
> 	}
> ```

你好，请问这段代码要添加到哪里呢？

**Comment by ShuningWan** [comment]
> > 可以这样做临时解决
> > ```java
> > private String getValue(Column column) {
> > 		//目前只对 enum 做特殊处理 Set目前暂没处理 
> > 		if (column.getMysqlType().startsWith("enum")) {
> > 			String columnType = column.getMysqlType();
> > 			String tempStr = columnType.substring(columnType.indexOf("(") + 1);
> > 			tempStr = tempStr.substring(0, tempStr.length() - 1).replace("\'", "");
> > 			List<String> typeList = SplitterUtil.splitList(tempStr);
> > 			return StringUtil.isNotBlank(column.getValue()) ? typeList.get(Integer.valueOf(column.getValue()) - 1) : null;
> > 		}
> > 		return column.getValue();
> > 	}
> > ```
> 
> 你好，请问这段代码要添加到哪里呢？

呃   这个应该蛮好理解的  只是替换了 column.getValue()  你自己再看下你的业务逻辑吧

**Comment by vincentwc** [comment]
> > > 可以这样做临时解决
> > > ```java
> > > private String getValue(Column column) {
> > > 		//目前只对 enum 做特殊处理 Set目前暂没处理 
> > > 		if (column.getMysqlType().startsWith("enum")) {
> > > 			String columnType = column.getMysqlType();
> > > 			String tempStr = columnType.substring(columnType.indexOf("(") + 1);
> > > 			tempStr = tempStr.substring(0, tempStr.length() - 1).replace("\'", "");
> > > 			List<String> typeList = SplitterUtil.splitList(tempStr);
> > > 			return StringUtil.isNotBlank(column.getValue()) ? typeList.get(Integer.valueOf(column.getValue()) - 1) : null;
> > > 		}
> > > 		return column.getValue();
> > > 	}
> > > ```
> > 
> > 
> > 你好，请问这段代码要添加到哪里呢？
> 
> 呃 这个应该蛮好理解的 只是替换了 column.getValue() 你自己再看下你的业务逻辑吧

我现在是使用canal-server去读取binlog日志，然后通过canal-adapter去解析然后直接将sql入库到目标库了，所以不是太了解你所说的的业务逻辑，现在我发现canal在同步的时候，枚举字段对应的是索引，然后直接把索引当成值存入数据库了，请问您是怎么解决该问题的呢

**Comment by jia2118290** [comment]
> > > > 可以这样做临时解决
> > > > ```java
> > > > private String getValue(Column column) {
> > > > 		//目前只对 enum 做特殊处理 Set目前暂没处理 
> > > > 		if (column.getMysqlType().startsWith("enum")) {
> > > > 			String columnType = column.getMysqlType();
> > > > 			String tempStr = columnType.substring(columnType.indexOf("(") + 1);
> > > > 			tempStr = tempStr.substring(0, tempStr.length() - 1).replace("\'", "");
> > > > 			List<String> typeList = SplitterUtil.splitList(tempStr);
> > > > 			return StringUtil.isNotBlank(column.getValue()) ? typeList.get(Integer.valueOf(column.getValue()) - 1) : null;
> > > > 		}
> > > > 		return column.getValue();
> > > > 	}
> > > > ```
> > > 
> > > 
> > > 你好，请问这段代码要添加到哪里呢？
> > 
> > 
> > 呃 这个应该蛮好理解的 只是替换了 column.getValue() 你自己再看下你的业务逻辑吧
> 
> 我现在是使用canal-server去读取binlog日志，然后通过canal-adapter去解析然后直接将sql入库到目标库了，所以不是太了解你所说的的业务逻辑，现在我发现canal在同步的时候，枚举字段对应的是索引，然后直接把索引当成值存入数据库了，请问您是怎么解决该问题的呢

我是在canal-adapter中调整的，canal-adapter获取到binlog数据后，会进行解析，在解析的时候获取值，这个节点进行的调整
详见工具类：com.alibaba.otter.canal.client.adapter.support.MessageUtil

**Comment by vincentwc** [comment]
> > > > > 可以这样做临时解决
> > > > > ```java
> > > > > private String getValue(Column column) {
> > > > > 		//目前只对 enum 做特殊处理 Set目前暂没处理 
> > > > > 		if (column.getMysqlType().startsWith("enum")) {
> > > > > 			String columnType = column.getMysqlType();
> > > > > 			String tempStr = columnType.substring(columnType.indexOf("(") + 1);
> > > > > 			tempStr = tempStr.substring(0, tempStr.length() - 1).replace("\'", "");
> > > > > 			List<String> typeList = SplitterUtil.splitList(tempStr);
> > > > > 			return StringUtil.isNotBlank(column.getValue()) ? typeList.get(Integer.valueOf(column.getValue()) - 1) : null;
> > > > > 		}
> > > > > 		return column.getValue();
> > > > > 	}
> > > > > ```
> > > > 
> > > > 
> > > > 你好，请问这段代码要添加到哪里呢？
> > > 
> > > 
> > > 呃 这个应该蛮好理解的 只是替换了 column.getValue() 你自己再看下你的业务逻辑吧
> > 
> > 
> > 我现在是使用canal-server去读取binlog日志，然后通过canal-adapter去解析然后直接将sql入库到目标库了，所以不是太了解你所说的的业务逻辑，现在我发现canal在同步的时候，枚举字段对应的是索引，然后直接把索引当成值存入数据库了，请问您是怎么解决该问题的呢
> 
> 我是在canal-adapter中调整的，canal-adapter获取到binlog数据后，会进行解析，在解析的时候获取值，这个节点进行的调整
> 详见工具类：com.alibaba.otter.canal.client.adapter.support.MessageUtil

你好，方便把你的修改的代码贴出来看一下吗？我是刚接触canal这一块的，对代码不是很熟，不知道该怎么修改

**Comment by vincentwc** [comment]
> > > > > > 可以这样做临时解决
> > > > > > ```java
> > > > > > private String getValue(Column column) {
> > > > > > 		//目前只对 enum 做特殊处理 Set目前暂没处理 
> > > > > > 		if (column.getMysqlType().startsWith("enum")) {
> > > > > > 			String columnType = column.getMysqlType();
> > > > > > 			String tempStr = columnType.substring(columnType.indexOf("(") + 1);
> > > > > > 			tempStr = tempStr.substring(0, tempStr.length() - 1).replace("\'", "");
> > > > > > 			List<String> typeList = SplitterUtil.splitList(tempStr);
> > > > > > 			return StringUtil.isNotBlank(column.getValue()) ? typeList.get(Integer.valueOf(column.getValue()) - 1) : null;
> > > > > > 		}
> > > > > > 		return column.getValue();
> > > > > > 	}
> > > > > > ```
> > > > > 
> > > > > 
> > > > > 你好，请问这段代码要添加到哪里呢？
> > > > 
> > > > 
> > > > 呃 这个应该蛮好理解的 只是替换了 column.getValue() 你自己再看下你的业务逻辑吧
> > > 
> > > 
> > > 我现在是使用canal-server去读取binlog日志，然后通过canal-adapter去解析然后直接将sql入库到目标库了，所以不是太了解你所说的的业务逻辑，现在我发现canal在同步的时候，枚举字段对应的是索引，然后直接把索引当成值存入数据库了，请问您是怎么解决该问题的呢
> > 
> > 
> > 我是在canal-adapter中调整的，canal-adapter获取到binlog数据后，会进行解析，在解析的时候获取值，这个节点进行的调整
> > 详见工具类：com.alibaba.otter.canal.client.adapter.support.MessageUtil
> 
> 你好，方便把你的修改的代码贴出来看一下吗？我是刚接触canal这一块的，对代码不是很熟，不知道该怎么修改

你好，在MessageUtil类里面加这个方法，发现代码没有走到这里面来，我用的是rdb的模式，全库同步，可以帮忙分析一下吗

**Comment by jia2118290** [comment]
> > > > > > > 可以这样做临时解决
> > > > > > > ```java
> > > > > > > private String getValue(Column column) {
> > > > > > > 		//目前只对 enum 做特殊处理 Set目前暂没处理 
> > > > > > > 		if (column.getMysqlType().startsWith("enum")) {
> > > > > > > 			String columnType = column.getMysqlType();
> > > > > > > 			String tempStr = columnType.substring(columnType.indexOf("(") + 1);
> > > > > > > 			tempStr = tempStr.substring(0, tempStr.length() - 1).replace("\'", "");
> > > > > > > 			List<String> typeList = SplitterUtil.splitList(tempStr);
> > > > > > > 			return StringUtil.isNotBlank(column.getValue()) ? typeList.get(Integer.valueOf(column.getValue()) - 1) : null;
> > > > > > > 		}
> > > > > > > 		return column.getValue();
> > > > > > > 	}
> > > > > > > ```
> > > > > > 
> > > > > > 
> > > > > > 你好，请问这段代码要添加到哪里呢？
> > > > > 
> > > > > 
> > > > > 呃 这个应该蛮好理解的 只是替换了 column.getValue() 你自己再看下你的业务逻辑吧
> > > > 
> > > > 
> > > > 我现在是使用canal-server去读取binlog日志，然后通过canal-adapter去解析然后直接将sql入库到目标库了，所以不是太了解你所说的的业务逻辑，现在我发现canal在同步的时候，枚举字段对应的是索引，然后直接把索引当成值存入数据库了，请问您是怎么解决该问题的呢
> > > 
> > > 
> > > 我是在canal-adapter中调整的，canal-adapter获取到binlog数据后，会进行解析，在解析的时候获取值，这个节点进行的调整
> > > 详见工具类：com.alibaba.otter.canal.client.adapter.support.MessageUtil
> > 
> > 
> > 你好，方便把你的修改的代码贴出来看一下吗？我是刚接触canal这一块的，对代码不是很熟，不知道该怎么修改
> 
> 你好，在MessageUtil类里面加这个方法，发现代码没有走到这里面来，我用的是rdb的模式，全库同步，可以帮忙分析一下吗

没有使用过rdb模式，一直使用row模式
