### ISSUE TITLE
是否支持7.4版本的es呢

### ISSUE THREAD

**Issue by niyangbaba** [alibaba/canal#2613]
## Question

使用7.4版本es测试，adapter.log 会出现
java.lang.IllegalArgumentException: Not found the mapping info of index: es_test
使用6.7版本es测试，插入数据正常

**Comment by Castleeee** [comment]
我也想知道,所以偶俺暂时用的7.6

**Comment by sqskg** [comment]
1.1.5支持7X

**Comment by Leme34** [comment]
下载1.1.4源码一看就知道了，es依赖都是6版本的，自己升级依赖重新编译打包就行了
