### ISSUE TITLE
fastsql parse error when DDL contains 'ALGORITHM=inplace'

### ISSUE THREAD

**Issue by deanwong** [alibaba/canal#2617]
- [ ✅ ] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [ ✅ ] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment

* canal version
1.1.4
* mysql version
RDS 5.7

### Issue Description
Please see the attachment

### Steps to reproduce
execute DDL with 'ALGORITHM=inplace'

### Expected behaviour
parse correct 

### Actual behaviour
parse error

If there is an exception, please attach the exception trace:

the sql_text in table tsdb.`meta_snapshot`
```
CREATE TABLE `contact` (
`id` bigint(20) NOT NULL AUTO_INCREMENT,
`version` bigint(20) NOT NULL,
`tenant_id` bigint(20) NOT NULL,
PRIMARY KEY (`id`),
KEY `idx_t_id` (`tenant_id`, `id`)
) ENGINE = InnoDB AUTO_INCREMENT = 33104879 CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci ALGORITHM = inplace; 
```
We have no idea why there is a `ALGORITHM = inplace` appended after create DDL

<img width="1475" alt="canal_parse" src="https://user-images.githubusercontent.com/4144156/76276220-40e1bc80-62c0-11ea-8f4e-d82ddb26c589.png">

**Comment by agapple** [comment]
对应myql版本是？感觉不是一个合法的ddl语法
