### ISSUE TITLE
canal能否获取阿里云 数据库mysql的数据

### ISSUE THREAD

**Issue by zzzxx** [alibaba/canal#2619]
canal能否获取阿里云 数据库mysql的数据

**Comment by 54nidong** [comment]
同问，canal目前支持 抽取域名的binlog日志吗？ 因为阿里云上面提供的是域名，IP会一直变的

**Comment by agapple** [comment]
可以，多看wiki或者issue

**Comment by newtoncy** [comment]
在常见问题解答里面可以找到。我也找了好久
