### ISSUE TITLE
Canal HA 切换数据重复发送

### ISSUE THREAD

**Issue by zhiyuan192shine** [alibaba/canal#2621]
### environment

* canal version
    canal-1.1.4

* mysql version
    mysql-5.7

### Issue Description
通过界面停止Canal Server 来进行切换后，数据会重复发送到Kafka

**Comment by Fanduzi** [comment]
这个应该是正常现象, 我的理解是canal HA, A,B两个instance, A为主, 持续获取binlog, 并将位点记录到zk, 但是这个做不到想mysql主从一样sql_thread应用完后原子更新mysql.slave_relay_log_info表, 于是就会有消费binlog到点11 和zk只记录到5的情况, 那么此时A宕机, B实例接管后从zk获取位点信息就是从5开始消费binlog, 就会造成重复binlog.

理论上我理解flush 位点信息到zk频率由参数`canal.zookeeper.flush.period`控制, 默认1000ms刷一次, 但是实际使用中发现不是这么回事, 可以看我提的issue
https://github.com/alibaba/canal/issues/2616

也期待作者能给个答复

**Comment by dingyufei615** [comment]
@Fanduzi 大佬 应该不是flush位点信息到zk频率问题，我在测试HA时也出现了这个问题 通过界面停止Canal Server 来进行切换后，最后一条数据会在切换后重复发到Kafka
也就是zk记录的position这个点位的数据，理论上说 zk记录的点位已经是成功消费过的binlog了（send 到kafka） 为什么在canal server 切换后这一条数据会再发到kafka一遍？

**Comment by Fanduzi** [comment]
> @Fanduzi 大佬 应该不是flush位点信息到zk频率问题，我在测试HA时也出现了这个问题 通过界面停止Canal Server 来进行切换后，最后一条数据会在切换后重复发到Kafka
> 也就是zk记录的position这个点位的数据，理论上说 zk记录的点位已经是成功消费过的binlog了（send 到kafka） 为什么在canal server 切换后这一条数据会再发到kafka一遍？

我也不是很清楚, 我这现在有的canal instance zk位点一个月都不刷..... 难受

**Comment by agapple** [comment]
see #2616
