### ISSUE TITLE
binlog解析出来的message数据不准确

### ISSUE THREAD

**Issue by iamforrest** [alibaba/canal#2625]
你好，我用的当前的master源代码版本，发现解析出来的Message有问题，以yu_bao_cai_ji这个字段，是decimal类型的，但是解析出来的value竟然是日期字符串。

<img width="1100" alt="image" src="https://user-images.githubusercontent.com/2240276/76699657-9b2cb400-66ea-11ea-894d-a64177419577.png">

message 的源数据参考附件

[message.txt](https://github.com/alibaba/canal/files/4334024/message.txt)

**Comment by iamforrest** [comment]
<img width="1664" alt="image" src="https://user-images.githubusercontent.com/2240276/76699704-12fade80-66eb-11ea-9a37-bba0cfb91270.png">

**Comment by iamforrest** [comment]
估计是我将这个配置打开了的原因

`canal.instance.filter.query.ddl = true`
我看了代码，这个打开之后，tablemeta的tsdb代码就不往下执行了，这样table meta错乱导致parse binlog也错乱了。

<img width="1129" alt="image" src="https://user-images.githubusercontent.com/2240276/76701194-ea2e1580-66f9-11ea-8721-facf7ad3a36d.png">

**Comment by agapple** [comment]
ddl不要过滤，否则会导致tableMeta无法正常维护
