### ISSUE TITLE
MySQL 同步ES数据时，有没有初始化全量同步数据的接口

### ISSUE THREAD

**Issue by lt5227** [alibaba/canal#2627]
## Question
当首次同步数据到ES时，原MySQL数据表中的数据有个接口或者程序入口能根据配置的SQL初始化同步数据至ES或者根据SQL查询的数据做批次更新的操作。

**Comment by lt5227** [comment]
CommonRest已经有了

**Comment by Azleal** [comment]
> CommonRest已经有了

@lt5227 请问一下，这个CommonRest相关的文档有吗? 麻烦贴一下，谢谢~
