### ISSUE TITLE
[updated]binlog解析疑问

### ISSUE THREAD

**Issue by gbfvip** [alibaba/canal#263]
canal能够解析现在mysql中的Percona分支吗,如果不能,有支持的计划吗

**Comment by keyganker** [comment]
支持的
不过这种问题你试一下不就知道了，来问一下至少等1天才会有答复，何必呢

**Comment by gbfvip** [comment]
我表述不够清楚,是这样的
由percona的源库,同步至mysql主分支的目的库
需同步的源表既有innodb,也有tokudb,同步至的目的表均为innodb,源表中均无blob等大字段类型
同步时发生了解析错误(没有更详细的错误堆栈)
pid:17 nid:8 exception:canal:test_canal:com.alibaba.otter.canal.parse.exception.CanalParseException: Unsupported BinlogImage NOBLOB

配置上并没有修改使用默认配置,即支持的image为[FULL,MINIMAL,NOBLOB]

**Comment by keyganker** [comment]
@agapple 求解答

**Comment by agapple** [comment]
otter不支持image模式为NOBLOB
