### ISSUE TITLE
canal 生成docker基础镜像Dockerfile 下载oracle jdk 失败 

### ISSUE THREAD

**Issue by jkl0898** [alibaba/canal#2631]
![image](https://user-images.githubusercontent.com/14175165/77040071-2dd29900-69f2-11ea-9dc1-dac3cde3bbd2.png)
图1
![image](https://user-images.githubusercontent.com/14175165/77040400-d1bc4480-69f2-11ea-80d0-e21a85fb1e88.png)
图2

1. Docker file 文件路径docker/base/Dockerfile 
2. 下载oracle jdk 如上图1
3. 下载失败原因如图2

建议：
更改下载方式或连接以适配oracle 下载方式。如：
wget --no-check-certificate -c --header "Cookie: oraclelicense=accept-securebackup-cookie" https://download.oracle.com/otn-pub/java/jdk/8u131-b11/d54c1d3a095b4ff2b6607d096fa80163/jdk-8u131-linux-x64.rpm

**Comment by agapple** [comment]
cookie信息估计会过期，可以提交一个PR给我
