### ISSUE TITLE
Canal推送方式的选择

### ISSUE THREAD

**Issue by BinaryXu** [alibaba/canal#2633]
## Question

我的业务场景是mysql同步至mongoDB。
1.推送方式TCP和Kafka有什么区别呢？
2.直接TCP不是更方便吗？
3.是因为Kafka，消费端可以订阅消息减少了内存消耗吗, 不需要像TCP方式一样一直监听

**Comment by foamzou** [comment]
我的理解是这样的：
canal把消息给到下游前，需要将消息储存在服务维护的队列结构里。这个队列相对于专业的消息中间件来说，从高可用和可靠消息传输来说都不那么可靠。因此将消息尽可能快的传输给MQ就很有必要了。
等着消费者慢慢消费吧。
--
如理解不对，欢迎纠正补充

**Comment by luispater** [comment]
> 我的理解是这样的：
> canal把消息给到下游前，需要将消息储存在服务维护的队列结构里。这个队列相对于专业的消息中间件来说，从高可用和可靠消息传输来说都不那么可靠。因此将消息尽可能快的传输给MQ就很有必要了。
> 等着消费者慢慢消费吧。
> 
> 如理解不对，欢迎纠正补充

另外可以通过消息订阅转发给多个消费者，可以同步给es的同时再同步给mongo

**Comment by CosmoYhh** [comment]
如果你的两个数据库都不能对外暴露端口，可以通过 Kafka/RocketMQ 中转
