### ISSUE TITLE
es adapter 解析sql时，两个表有相同的字段名称，更新时，会有bug

### ISSUE THREAD

**Issue by guozhenjiang01** [alibaba/canal#2634]
SELECT
	a.id AS id,
	a.name AS user_name,
	a.role_id AS role_id,
	b.name AS role_name 
FROM
	myuser a
	LEFT JOIN myrole b ON a.role_id = b.id
例如配置文件中写以上sql

然后我实际执行update role set name='newname' where role_id='1';
会将a.name也都修改掉，原因

            if (dmlOld.containsKey(columnName) && !mapping.getSkips().contains(fieldItem.getFieldName())) {
                esFieldData.put(Util.cleanColumn(fieldItem.getFieldName()),
                        getValFromData(mapping, dmlData, fieldItem.getFieldName(), columnName));
            }
用containsKey来判断修改了哪些字段，应该加上表的限定吧???

看是不是我理解错了，我使用时确实该rule表的name,es中，use表的也会被改掉

**Comment by guozhenjiang01** [comment]
@bucketli  大佬，辛苦看下

**Comment by yangyiweigege** [comment]
1.13版本是有这个问题的。后来官方 已经改好了的。。。
