### ISSUE TITLE
ddl默认投递到partition 0(队列0)的问题

### ISSUE THREAD

**Issue by flackyang** [alibaba/canal#2636]
## Question

canal对接RocketMQ，启用 partitionHash时，ddl语句都固定投递到队列0，与数据是同一个队列
请问这样做是基于什么考虑呢？
MQMessageUtils.messagePartition方法中
if (flatMessage.getIsDdl()) {
    partitionMessages[0] = flatMessage;
}
另外这中情况下，ddl 和  dml不在同一个队列中，对client 顺序消息处理有什么影响？

**Comment by gongwenjun2019** [comment]
> ## Question
> canal对接RocketMQ，启用 partitionHash时，ddl语句都固定投递到队列0，与数据是同一个队列
> 请问这样做是基于什么考虑呢？
> MQMessageUtils.messagePartition方法中
> if (flatMessage.getIsDdl()) {
> partitionMessages[0] = flatMessage;
> }
> 另外这中情况下，ddl 和 dml不在同一个队列中，对client 顺序消息处理有什么影响？

这个问题我也提了。。。不知道主要的因素是什么。按理来说，既然是按照表进行hash,无论是ddl或者是dml都应该是按照表进行hash后存入到对应的patition中去

**Comment by agapple** [comment]
query语句除了ddl以外还有部分dml query，没法获取完整的dbname和tbname，所以统一按照分区0进行发送
