### ISSUE TITLE
开启binlog_rows_query_log_events事件后是否可以设置个开关过滤该事件

### ISSUE THREAD

**Issue by wyoldfour** [alibaba/canal#2637]
目前由于业务需求数据库需要开启binlog_rows_query_log_events事件，但是我们通过canal进行监听后由于该事件不会进行过滤导致我们会收到整个库的sql数据，能否增加个该事件解析开关啦？

**Comment by user-GitHub-user** [comment]
遇到了同样的问题，希望有个过滤开关

**Comment by lchainl** [comment]
支持，应该增加个开关，要不然消息真的很乱

**Comment by Fanduzi** [comment]
canal.instance.filter.query.dml=true  上线之前自己测测
看这个issue https://github.com/alibaba/canal/issues/1361

**Comment by wyoldfour** [comment]
@Fanduzi 这个开关影响的不仅是这一个事件，通过源码和实际测试效果确实会影响到正常的业务，所以还是建议搞一个单独的开关，目前我们自己的实现是搞了一个单独的开关

**Comment by Fanduzi** [comment]
> @Fanduzi 这个开关影响的不仅是这一个事件，通过源码和实际测试效果确实会影响到正常的业务，所以还是建议搞一个单独的开关，目前我们自己的实现是搞了一个单独的开关

@agapple 看来你这参数不能用了啊

**Comment by Fanduzi** [comment]
> @Fanduzi 这个开关影响的不仅是这一个事件，通过源码和实际测试效果确实会影响到正常的业务，所以还是建议搞一个单独的开关，目前我们自己的实现是搞了一个单独的开关

感谢, 看来我还是把这个binlog_rows_query_log_events关了吧. 这个canal真是各种坑和bug!

**Comment by Fanduzi** [comment]
> @Fanduzi 这个开关影响的不仅是这一个事件，通过源码和实际测试效果确实会影响到正常的业务，所以还是建议搞一个单独的开关，目前我们自己的实现是搞了一个单独的开关

提个merge吧大佬, 等着作者修复猴年马月了

**Comment by lemontree8801** [comment]
> @Fanduzi 这个开关影响的不仅是这一个事件，通过源码和实际测试效果确实会影响到正常的业务，所以还是建议搞一个单独的开关，目前我们自己的实现是搞了一个单独的开关

想知道遇到了什么问题 。。。。

**Comment by agapple** [comment]
canal.instance.filter.query.dml=true
