### ISSUE TITLE
HA 部署canal之后，zk中活跃节点get不到信息

### ISSUE THREAD

**Issue by ChrisZjf** [alibaba/canal#2640]
高可用部署完canal之后，zk中
`[zk: localhost:2181(CONNECTED) 33] ls /otter/canal/destinations/example/cluster
[dev-bigdata5:11111, dev-bigdata6:11111]
[zk: localhost:2181(CONNECTED) 34] ls /otter/canal/destinations/example/running
[]
`
如上，zk中可以get到cluster信息，但是get到running信息为空

![微信图片_20200323194452](https://user-images.githubusercontent.com/31039208/77313403-c93f7300-6d3e-11ea-8e11-5fbc0dd14a1f.png)

求各位大神帮助解答

**Comment by Lintel-X** [comment]
get /otter/canal/destinations/example/running

**Comment by xiechenghuan** [comment]
我也遇到了，怎么解决的
