### ISSUE TITLE
Could not find first log file name in binary log index file

### ISSUE THREAD

**Issue by charliejinc** [alibaba/canal#2643]
重启 canal后 报错，
EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:example[java.io.IOException: Received error packet: errno =
 1236, sqlstate = HY000 errmsg = Could not find first log file name in binary log index file

**Comment by Lintel-X** [comment]
https://github.com/alibaba/canal/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E8%A7%A3%E7%AD%94
