### ISSUE TITLE
canalAdmin 管理工具下对 instance 的状态显示有误

### ISSUE THREAD

**Issue by botao-git** [alibaba/canal#2644]
安装了canalAdmin后，在Server管理界面运行状态正常，但是 instance的运行状态一直显示是停止
![image](https://user-images.githubusercontent.com/20434732/77407016-7920e900-6df0-11ea-93c5-1a38a463aaed.png)
![image](https://user-images.githubusercontent.com/20434732/77407058-8dfd7c80-6df0-11ea-8433-be7ba51619b9.png)

**Comment by Brainhu** [comment]
你们的admin 用于集群模式嘛，新建集群后，修改配置canal_local 覆盖到 canal 直接启动不了。报config empty

**Comment by user-GitHub-user** [comment]
> 安装了canalAdmin后，在Server管理界面运行状态正常，但是 instance的运行状态一直显示是停止
> ![image](https://user-images.githubusercontent.com/20434732/77407016-7920e900-6df0-11ea-93c5-1a38a463aaed.png)
> ![image](https://user-images.githubusercontent.com/20434732/77407058-8dfd7c80-6df0-11ea-8433-be7ba51619b9.png)

你需要启动对应的adapter或客户端，web才会显示启动状态

**Comment by user-GitHub-user** [comment]
> 你们的admin 用于集群模式嘛，新建集群后，修改配置canal_local 覆盖到 canal 直接启动不了。报config empty
集群模式要删除本地配置，配置应该在mysql里面
