### ISSUE TITLE
canal.adapter 配置多个数据库 或多个database

### ISSUE THREAD

**Issue by CosmoYhh** [alibaba/canal#2650]
已经解决，这里只做问题记录

首先application.yml中配置多个 name, key也做区分mysql1,mysql2 数据库也做区分

canalAdapters:
  - instance: example # canal instance Name or mq topic name
    groups:
    - groupId: g1
      outerAdapters:
      - name: logger
      - name: rdb
        key: mysql1
        properties:
          jdbc.driverClassName: com.mysql.jdbc.Driver
          jdbc.url: jdbc:mysql://192.168.1.72:3306/test_db1?useUnicode=true
          jdbc.username: root
          jdbc.password: 123456
      - name: rdb
        key: mysql2
        properties:
          jdbc.driverClassName: com.mysql.jdbc.Driver
          jdbc.url: jdbc:mysql://192.168.1.72:3306/test_db2?useUnicode=true
          jdbc.username: root
          jdbc.password: 123456

然后在 conf/rdb/下创建两个 文件 test_db1.yml, test_db2.yml
内容如下 ：

test_db1.yml的：

dataSourceKey: defaultDS1
destination: example
groupId: g1
outerAdapterKey: mysql1
concurrent: true
dbMapping:
  mirrorDb: true
  database: test_db1

test_db2.yml的：

dataSourceKey: defaultDS2
destination: example
groupId: g1
outerAdapterKey: mysql2
concurrent: true
dbMapping:
  mirrorDb: true
  database: test_db2

**Comment by CosmoYhh** [comment]
1

**Comment by lishuo5263** [comment]
麻烦卤煮讲解下这是什么情况呢

**Comment by JMandZM** [comment]
> 已经解决，这里只做问题记录
> 
> 首先application.yml中配置多个 name, key也做区分mysql1,mysql2 数据库也做区分
> 
> canalAdapters:
> 
> * instance: example # canal instance Name or mq topic name
>   groups:
>   
>   * groupId: g1
>     outerAdapters:
>     
>     * name: logger
>     * name: rdb
>       key: mysql1
>       properties:
>       jdbc.driverClassName: com.mysql.jdbc.Driver
>       jdbc.url: jdbc:mysql://192.168.1.72:3306/test_db1?useUnicode=true
>       jdbc.username: root
>       jdbc.password: 123456
>     * name: rdb
>       key: mysql2
>       properties:
>       jdbc.driverClassName: com.mysql.jdbc.Driver
>       jdbc.url: jdbc:mysql://192.168.1.72:3306/test_db2?useUnicode=true
>       jdbc.username: root
>       jdbc.password: 123456
> 
> 然后在 conf/rdb/下创建两个 文件 test_db1.yml, test_db2.yml 内容如下 ：
> 
> test_db1.yml的：
> 
> dataSourceKey: defaultDS1 destination: example groupId: g1 outerAdapterKey: mysql1 concurrent: true dbMapping: mirrorDb: true database: test_db1
> 
> test_db2.yml的：
> 
> dataSourceKey: defaultDS2 destination: example groupId: g1 outerAdapterKey: mysql2 concurrent: true dbMapping: mirrorDb: true database: test_db2

**Comment by JMandZM** [comment]
你好，请问你是配置canal.adapter去同步写入多个库或者表的吗？
配置文件就是这样写的吗

**Comment by JMandZM** [comment]
> 已经解决，这里只做问题记录
> 
> 首先application.yml中配置多个 name, key也做区分mysql1,mysql2 数据库也做区分
> 
> canalAdapters:
> 
> * instance: example # canal instance Name or mq topic name
>   groups:
>   
>   * groupId: g1
>     outerAdapters:
>     
>     * name: logger
>     * name: rdb
>       key: mysql1
>       properties:
>       jdbc.driverClassName: com.mysql.jdbc.Driver
>       jdbc.url: jdbc:mysql://192.168.1.72:3306/test_db1?useUnicode=true
>       jdbc.username: root
>       jdbc.password: 123456
>     * name: rdb
>       key: mysql2
>       properties:
>       jdbc.driverClassName: com.mysql.jdbc.Driver
>       jdbc.url: jdbc:mysql://192.168.1.72:3306/test_db2?useUnicode=true
>       jdbc.username: root
>       jdbc.password: 123456
> 
> 然后在 conf/rdb/下创建两个 文件 test_db1.yml, test_db2.yml 内容如下 ：
> 
> test_db1.yml的：
> 
> dataSourceKey: defaultDS1 destination: example groupId: g1 outerAdapterKey: mysql1 concurrent: true dbMapping: mirrorDb: true database: test_db1
> 
> test_db2.yml的：
> 
> dataSourceKey: defaultDS2 destination: example groupId: g1 outerAdapterKey: mysql2 concurrent: true dbMapping: mirrorDb: true database: test_db2

你好，请问你是配置canal.adapter去同步写入多个库或者表的吗
同步写入多个库或者表的配置文件应该怎么写
