### ISSUE TITLE
.a.o.canal.parse.inbound.mysql.dbsync.LogEventConvert - table parser error : header

### ISSUE THREAD

**Issue by BigData-YC** [alibaba/canal#2651]
使用canal同步数据，同步一段时间就出现这个问题。同时日志文件里面会有大量数据。
 afterColumns {
    index: 23
    sqlType: 12
    updated: false
    isNull: false
    value: "\346\265\267\345\215\227"
  }
  afterColumns {
    index: 24
    sqlType: 12
    updated: false
    isNull: false
    value: "B\347\272\247"
  }
  afterColumns {
    index: 25
    sqlType: 12
    updated: false
    isNull: false
    value: "\345\206\267\350\227\217"
  }
  afterColumns {
    index: 26
    sqlType: 12
    updated: false
    isNull: false
    value: ""
  }
  afterColumns {
    index: 27
    sqlType: 12
    updated: false
    isNull: false
    value: ""
  }
  afterColumns {
    index: 28
    sqlType: 12
    updated: false
    isNull: false
    value: "2"
  }
  afterColumns {
    index: 29
    sqlType: 12
    updated: false
    isNull: true
  }
  afterColumns {
    index: 30
    sqlType: 12
    updated: false
    isNull: false
    value: "S"
  }

**Comment by Lintel-X** [comment]
canal.instance.filter.table.error设置成了true？
这个错误应该是tsdb维护的表字段和真实表字段不一致导致的

**Comment by jikuanyu** [comment]
刚用都遇见，这个canal靠谱吗？

**Comment by EllenAdams** [comment]
> canal.instance.filter.table.error
canal.instance.filter.table.error=true，也遇到了这个问题，报错一样。目前需要设置成false还是怎么来更改tsdb的数据呢？

**Comment by EllenAdams** [comment]
@agapple @LintelXu 两位麻烦看一下，谢谢~

**Comment by 542928492** [comment]
请问这个问题解决了吗？ 我在使用tsdb 的时候也遇到了，此问题。 尝试了很多参数。还没知道 最佳实践是啥，
现在表结构一变更就报错这个
