### ISSUE TITLE
单节点客户端重复消费问题

### ISSUE THREAD

**Issue by satifxin** [alibaba/canal#2652]
使用demo的客户端代码，消费mysql日志，使用create table 建表语句，发现客户端捕获的消费会重复3-4次以上，请问这是什么问题。

日志如下：
================> binlog[mysql-bin.000018:4227429] , name[test,canal_0331] , eventType : CREATE
empty count : 1
empty count : 2
empty count : 3
empty count : 4
empty count : 5
empty count : 6
empty count : 7
empty count : 8
empty count : 9
empty count : 10
empty count : 11
empty count : 12
empty count : 13
empty count : 14
empty count : 15
empty count : 16
empty count : 17
empty count : 18
empty count : 19
empty count : 20
empty count : 21
empty count : 22
empty count : 23
empty count : 24
empty count : 25
empty count : 26
empty count : 27
empty count : 28
empty count : 29
empty count : 30
empty count : 31
empty count : 32
empty count : 33
empty count : 34
empty count : 35
empty count : 36
empty count : 37
empty count : 38
empty count : 39
message_Id：69
================> binlog[mysql-bin.000018:4227429] , name[test,canal_0331] , eventType : CREATE
empty count : 1
empty count : 2
empty count : 3
empty count : 4
empty count : 5
empty count : 6
empty count : 7
empty count : 8
empty count : 9
empty count : 10
empty count : 11
empty count : 12
empty count : 13
empty count : 14
empty count : 15
empty count : 16
empty count : 17
empty count : 18
empty count : 19
empty count : 20
empty count : 21
empty count : 22
empty count : 23
empty count : 24
empty count : 25
empty count : 26
empty count : 27
empty count : 28
empty count : 29
empty count : 30
empty count : 31
empty count : 32
empty count : 33
empty count : 34
empty count : 35
empty count : 36
empty count : 37
empty count : 38
empty count : 39
empty count : 40
empty count : 41
empty count : 42
empty count : 43
message_Id：70
================> binlog[mysql-bin.000018:4227429] , name[test,canal_0331] , eventType : CREATE
empty count : 1

**Comment by Eternal88** [comment]
你好,你这个问题有解决掉嘛

**Comment by agapple** [comment]
检查一下服务端是否有异常
