### ISSUE TITLE
canal-adapter启动错误

### ISSUE THREAD

**Issue by mloveing** [alibaba/canal#2654]
环境：jdk1.8
centos7
elasticsearch:7.6.0
canal:1.1.4

我在做canal同步数据库数据到es的时候，发现启动canal-adapter报如下错误（canal-adapter在centos7运行）
java.lang.IllegalStateException: Extension instance(name: es7, class: interface com.alibaba.otter.canal.client.adapter.OuterAdapter)  could not be instantiated: class could not be found

**Comment by KerryJava** [comment]
要先把配置文件贴出来，是否配置错了？

**Comment by mloveing** [comment]
> 要先把配置文件贴出来，是否配置错了？

谢谢，问题已经解决，原因未知，我把es7换为es6，重新配置了一遍就可以了
