### ISSUE TITLE
提一个小bug点.同时有个问题: 为什么要将ddl语句全部放到kafka 分区0中

### ISSUE THREAD

**Issue by gongwenjun2019** [alibaba/canal#2655]
## Question

首先提一个代码上得小bug.
模块client-adapter 中: 类com.alibaba.otter.canal.client.adapter.support.MessageUtil
![image](https://user-images.githubusercontent.com/50264213/78122157-eced7200-743e-11ea-87c0-4b8b4621573a.png)
这个里面重复set了这个属性.
问题:
前题需求:一个实例库中得所有表按照表进行hash然后放到对应得kafka topic 分区中.
但是源码中将所有得ddl语句都强制放到partition 0中得意图是是什么?

**Comment by gongwenjun2019** [comment]
模块client-adapter 中: 类com.alibaba.otter.canal.client.adapter.support.MessageUtil ,重复setIsDdl......

**Comment by gsxuan** [comment]
![image](https://user-images.githubusercontent.com/32562519/78203619-0c7dac80-74ca-11ea-9fc1-4be56fd1fe81.png)

**Comment by linfeiyu** [comment]
计算partition是根据CanalEntry.Column计算出来的，DDL里没有相应的数据计算数据哪个分区。

**Comment by gongwenjun2019** [comment]
> 计算partition是根据CanalEntry.Column计算出来的，DDL里没有相应的数据计算数据哪个分区。

partitionHash是可以根据表进行hash的，根据表的hash然后和partitionNum取模就能得到对应的分区.
canal的wiki文档也有说明 :
![image](https://user-images.githubusercontent.com/50264213/78214312-8a9c7c00-74e7-11ea-92d9-d4da2da80297.png)
而且ddl语句解析后的数据也是包含库表的.

**Comment by agapple** [comment]
DDL语句并没有完整解析dbName和tbName，所以统一按照0分区发送
