### ISSUE TITLE
DDL过滤对 DROP 不生效

### ISSUE THREAD

**Issue by linfeiyu** [alibaba/canal#2657]
- [ ] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment

* canal version   1.1.4
* mysql version  5.7

### Issue Description

![image](https://user-images.githubusercontent.com/26424218/78205658-51581200-74cf-11ea-8626-3f0a64d6f42b.png)

### Expected behaviour
能正确的过滤DROP  table/database
### Actual behaviour
DDL过滤对 DROP  table/database不生效

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by agapple** [comment]
ERASE就是对应DROP
