### ISSUE TITLE
canal的docker部署是不是只能有一个实例？

### ISSUE THREAD

**Issue by BigData-YC** [alibaba/canal#2659]
目前使用的canal是集群模式，部署在三台机器上。实例有20多个。公司想要把canal重新部署到docker上，官网现在给的案例是单机canal和单实例的docker。请问有多实例的吗？以及集群模式的docker部署吗？

**Comment by wedog** [comment]
部署docker只能用docker run，不支持镜像自动化部署。docker貌似是不能ha的。

**Comment by agapple** [comment]
可以了解一下canal-admin的集群管理
