### ISSUE TITLE
CanalRabbitMQProducer中的ConnectionFactory创建过于简单并且不支持设置端口

### ISSUE THREAD

**Issue by jiuweidaji** [alibaba/canal#2660]
ConnectionFactory factory = new ConnectionFactory();
        factory.setHost(mqProperties.getServers());
        if (mqProperties.getAliyunAccessKey().length() > 0 && mqProperties.getAliyunSecretKey().length() > 0
            && mqProperties.getAliyunUID() > 0) {
            factory.setCredentialsProvider(new AliyunCredentialsProvider(mqProperties.getAliyunAccessKey(),
                mqProperties.getAliyunSecretKey(),
                mqProperties.getAliyunUID()));
        } else {
            factory.setUsername(mqProperties.getUsername());
            factory.setPassword(mqProperties.getPassword());
        }
        factory.setVirtualHost(mqProperties.getVhost());

当想使用rabbitmq的时候，canal.mq.servers不能设置多个Address，并且设置的ip不能带端口，只能使用默认的rabbitmq端口5672

spring-rabbit中有现成的处理，可以把里面的相关片段取出来

**Comment by agapple** [comment]
可以提交一个PR给我
