### ISSUE TITLE
能否在canal解析Binlog的结果文本里添加上自定义的RDB编号？

### ISSUE THREAD

**Issue by bosen365** [alibaba/canal#2664]
我描述下我的问题：
我们有很多阿里云的RDB实例，现在要用canal进行归集，canal解析Binlog并发送json数据到Kafka，现在我们想在这个json数据里增加特定字段属性，该字段属性用于标记这条数据是来自哪个RDB实例，请问这个如何配置？

请大神们留心看下，盼回复！

**Comment by leiwangouc** [comment]
我也有这样的需求，求大神指点。

**Comment by agapple** [comment]
可以考虑提交一个PR给我
