### ISSUE TITLE
admin有adapter的远程配置数据库，为什么不能再ui在操作adapter的配置？

### ISSUE THREAD

**Issue by ACEZOORO** [alibaba/canal#2669]
## Question

admin有adapter的远程配置数据库，为什么不能再ui在操作adapter的配置？
admin只能线上操作server的配置，不能动态调整adapter的配置

**Comment by user-GitHub-user** [comment]
> ## Question
> admin有adapter的远程配置数据库，为什么不能再ui在操作adapter的配置？
> admin只能线上操作server的配置，不能动态调整adapter的配置
现在只支持server,看文档有实现adapter自动配置的计划

**Comment by agapple** [comment]
可以提交一个PR给我

**Comment by znicholas** [comment]
继续adapter的可视化配置，有计划什么时候完成吗？
