### ISSUE TITLE
支持多线程消费吗？

### ISSUE THREAD

**Issue by hezhiqiang** [alibaba/canal#2670]
我目前的程序是单线程消费，日志来不及消费，有很大的延后，可以支持多线程消费吗？目前的Java代码如下：
		while(true) {
			CanalConnector connector = CanalConnectors.newSingleConnector(new InetSocketAddress("127.0.0.1", 11111), "example", "", "");
	        int batchSize = 100;
	        long batchId = 0;
	        try {
	            connector.connect();
	            connector.subscribe();
	            while (true) {
	            	try {
		                Message message = connector.getWithoutAck(batchSize);
		                batchId = message.getId();
		                int size = message.getEntries().size();
		                if (batchId == -1 || size == 0) {
		                    try {
		                        Thread.sleep(1000);
		                    } catch (Exception e) {}
		                } else {
		                    printEntry(message.getEntries());
		                }
		                
		                connector.ack(batchId);
	            	} catch(Exception ex) {
	            		app.logger.error("main", ex);
	            		connector.rollback(batchId);
	            	}
	            }
	        } catch(Exception ex) {
	        	app.logger.error("main", ex);
	        } finally {
	        	try {
	        		connector.disconnect();
	        	} catch(Exception ex) {}
	        }

**Comment by wedog** [comment]
支持的，adapter的源码就是使用的多线程模式。AbstractCanalAdapterWorker这个类，ExecutorService的submit方法。

**Comment by hezhiqiang** [comment]
@wedog 我上面的程序大概如何改造（改成多线程消费），能给个大概的思路不？谢谢~

**Comment by hezhiqiang** [comment]
@wedog AbstractCanalAdapterWorker这个类我在github中没有找到噢

**Comment by wedog** [comment]
int threadCount = Runtime.getRuntime().availableProcessors();
ExecutorService executor = AdcUtils.newFixedThreadPool(threadCount, 5000L);
for (long i = 0; i < x; i++) {
                    offset = size * i;
                    String sqlFinal = sql + " LIMIT " + offset + "," + size;
                    Future<Boolean> future = executor.submit(() -> task());
                    futures.add(future);
                }
                executor.shutdown();

**Comment by wedog** [comment]
```
int threadCount = Runtime.getRuntime().availableProcessors();
ExecutorService executor = new ThreadPoolExecutor(nThreads,
                nThreads,
                5000L,
                TimeUnit.MILLISECONDS,
                new SynchronousQueue<>(),
                (r, exe) -> {
                    if (!exe.isShutdown()) {
                        try {
                            exe.getQueue().put(r);
                        } catch (InterruptedException e) {
                            // ignore
                        }
                    }
                });
for (long i = 0; i < x; i++) {
offset = size * i;
String sqlFinal = sql + " LIMIT " + offset + "," + size;
Future future = executor.submit(() -> task());
futures.add(future);
}
executor.shutdown();
```

**Comment by hezhiqiang** [comment]
我已经实现了~

`
	private static ExecutorService threadPool = Executors.newFixedThreadPool(50);
	private static List<TaskStatus> listTaskStatus = Collections.synchronizedList(new ArrayList<>());

	private static void consumeMessage(CanalConnector connector, Message msg) {
		TaskStatus taskStatus = new TaskStatus();
		taskStatus.batchId = msg.getId();
		listTaskStatus.add(taskStatus);
		
		threadPool.execute(new Runnable() {
			@Override
			public void run() {
				while(true) {
					try {
						printEntry(msg.getEntries());
						taskStatus.finished = true;
						break;
					} catch (Exception e) {
						app.logger.error("consumeMessage", e);
						
						try {
							Thread.sleep(1000);
						} catch (Exception e2) {}
					}
				}
			}
		});
	}
	
	public static void main(String[] args) {
		ConfigurableApplicationContext applicationContext = SpringApplication.run(CanalClientApplication.class, args);
		app = applicationContext.getBean(CanalClientApplication.class);
		app.initJedisPool();
		
		Executors.newSingleThreadScheduledExecutor().scheduleWithFixedDelay(new Runnable() {
			@Override
			public void run() {
				try {
					int removeCount = 0;

					int length = listTaskStatus.size();
					for (int i = 0; i < length; i++) {
						TaskStatus item = listTaskStatus.get(i);
						if (item.finished) {
							removeCount++;
							connector.ack(item.batchId);
						} else break;
					}

					for (int j = 0; j < removeCount; j++) listTaskStatus.remove(0);
				} catch (Exception e) {
					app.logger.error("scheduleWithFixedDelay", e);
				}
			}
		}, 0, 1, TimeUnit.SECONDS);
		
		while(true) {
			connector = CanalConnectors.newSingleConnector(new InetSocketAddress("127.0.0.1", 11111), "example", "", "");
	        int batchSize = 100;
	        long batchId = 0;
	        try {
	            connector.connect();
	            connector.subscribe();
	            while (true) {
	            	try {
		                Message message = connector.getWithoutAck(batchSize);
		                batchId = message.getId();
		                int size = message.getEntries().size();
		                if (batchId == -1 || size == 0) {
		                    try {
		                        Thread.sleep(1000);
		                    } catch (Exception e) {}
		                } else {
		                	consumeMessage(connector, message);
		                }
	            	} catch(Exception ex) {
	            		app.logger.error("main", ex);
	            	}
	            }
	        } catch(Exception ex) {
	        	app.logger.error("main", ex);
	        } finally {
	        	try {
	        		connector.disconnect();
	        	} catch(Exception ex) {}
	        }
	        
	        try {
				Thread.sleep(10*1000);
			} catch (Exception e) {}
		}
	}
`

**Comment by hihozhou** [comment]
@hezhiqiang 有办法多线程执行getWithoutAck吗？

**Comment by hezhiqiang** [comment]
@hihozhou 我们是自已实现了多线程，多线程去消费，具体的代码我找一下，或者加微信18621082288
