### ISSUE TITLE
canal adapt 连有密码的elasticsearch问题

### ISSUE THREAD

**Issue by hjpsss333** [alibaba/canal#2671]
在elasticsearch 没有设密码的时候，canal adapt是可以正常抽数据。
后来elasticsearch设置了密码，改了canal adapt配置文件
- name: es
  #      key: addressOriginalKey
        hosts: 192.168.9.85:9200,192.168.9.86:9200,192.168.9.87:9200  # 127.0.0.1:9200 for rest mode
        properties:
          mode: rest
          security.auth: elastic:123456
          cluster.name: my-es64

这里配置了密码，首先在es中创建了索引mytest,但是一直报Not found the mapping info of index: mytest。 如果YML配置文件中的index 改为ES没有设置密码前的索引mytest_user，就没问题。
YML文件如下：
cat mytest_user2.yml 
dataSourceKey: defaultDS
destination: example
groupId: g1
esMapping:
  _index: mytest
  _type: _doc
  _id: _id
  upsert: true
#  pk: id
  sql: "select a.id as _id, a.id, a.name, a.role_id, a.c_time from user2 a"
#  objFields:
#    _labels: array:;
#  etlCondition: "where a.c_time>={}"
  commitBatch: 3000

**Comment by hjpsss333** [comment]
补充一下，版为 canal.adapter-1.1.4

**Comment by wedog** [comment]
我用的有密码的es没问题呢，你的index是不是创建了哦。

**Comment by hjpsss333** [comment]
我先创建了index，就是报 Not found the mapping info of index

**Comment by wedog** [comment]
那你es的cluster.name是否是正确的。

**Comment by hjpsss333** [comment]
原因找到了，要有keyword的字段放在建es mapping中的第一个，要不就会报Not found the mapping info of index。 我是全量用logstash, logstash建的索引，es mapping中第一个字段不一定是keyword这种类型，这算是一个坑啊
"name": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword"
            }
          }
        }

**Comment by hjpsss333** [comment]
谢谢大神wedog 的回答与帮助
