### ISSUE TITLE
Prometheus监控 是否有计划支持 关于 kafka 的监控

### ISSUE THREAD

**Issue by casualzao** [alibaba/canal#2675]
## Question

Prometheus监控  上，看到只集成了 canal client 的相关操作，如果采取的是发送的mq 消息的，这种server 端的监控，目前支持吗

**Comment by kirin-13** [comment]
可以考虑直接通过kafka exporter 监控kafka的数据。

**Comment by casualzao** [comment]
> 可以考虑直接通过kafka exporter 监控kafka的数据。

好的，我去了解下，感谢
