### ISSUE TITLE
tcp模式和kafka模式数据格式partition、 offset和timestamp有问题

### ISSUE THREAD

**Issue by tercel** [alibaba/canal#2676]
## Question

问题1:tcp模式返回的excuteTime时间有问题，是秒级的timestamp，但是kafka模式是毫秒级的timestamp， 建议tcp模式也是毫秒级的timestamp
问题2:kafka返回数据没有 partition 和 offset， 但是tcp模式是有的，建议kafka也加上partition 和 offset

**Comment by tercel** [comment]
问题1:tcp模式返回的excuteTime时间有问题，是秒级的timestamp，但是kafka模式是毫秒级的timestamp， 建议tcp模式也是毫秒级的timestamp
问题2:kafka返回数据没有 partition 和 offset， 但是tcp模式是有的，建议kafka也加上partition 和 offset

**Comment by agapple** [comment]
可以考虑提交一个PR给我
