### ISSUE TITLE
RocketMQ aliyun ak set error

### ISSUE THREAD

**Issue by 563377969** [alibaba/canal#2680]
- [ ] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment

* canal version
1.1.4 and 1.1.5
* mysql version

### Issue Description
title rocketmq aliyun ak set error!
pakage com.alibaba.otter.canal.connector.core.producer.AbstractMQProducer

String aliyunAccessKey = properties.getProperty(CanalConstants.CANAL_ALIYUN_ACCESS_KEY);
        if (!StringUtils.isEmpty(aliyunAccessKey)) {
            mqProperties.setAliyunAccessKey(aliyunAccessKey);
        }
        String aliyunSecretKey = properties.getProperty(CanalConstants.CANAL_ALIYUN_SECRET_KEY);
        if (!StringUtils.isEmpty(aliyunSecretKey)) {
            mqProperties.setAliyunAccessKey(aliyunSecretKey);
        }

### Actual behaviour

If there is an exception, please attach the exception trace:
ERROR com.alibaba.otter.canal.rocketmq.CanalRocketMQProducer - send flat message to hashed partition error
org.apache.rocketmq.client.exception.MQClientException: No route info for this topic
```
Just put your stack trace here!
```

**Comment by agapple** [comment]
No route info for this topic，topic不存在
