### ISSUE TITLE
List<CanalEntry.RowData>[]收到很多日志中该集合中都是空的

### ISSUE THREAD

**Issue by lovegames** [alibaba/canal#2681]
## Question
List<CanalEntry.RowData>[]
在调试线上环境时,发现,能够得到是哪个表被修改,修改的类型,但是具体拿到修改的集合时,里面是空数据导致无法正常同步到ES,想问下可能导致这种情况的原因,canal版本是1.1.0

**Comment by agapple** [comment]
确认一下mysql的binlog格式，确保binlog_format=row
