### ISSUE TITLE
Canal Adapter 同步mysql数据到es上 es时间比mysql多了12小时，时区是东八区没错

### ISSUE THREAD

**Issue by studyhuang1996** [alibaba/canal#2683]
## Question

![image](https://user-images.githubusercontent.com/27665214/79524313-c2ccbe80-8092-11ea-8502-1c4e2a34ccda.png)
库里是：2020-04-16 10:09:47
同步到es上是
   {
        "_index": "credit_zz_sxbzxr_v1",
        "_type": "_doc",
        "_id": "88685",
        "_score": 1,
        "_source": {
          "id": 88685,
          "rkbh": 56,
          "zzbh": 45,
          "zzmc": "dfd",
          "tyshxydm": "sfds",
          "zzjgdm": null,
          "zch": null,
          "swdjh": null,
          "fddbrxm": null,
          "ah": null,
          "lasj": null,
          "fbsj": null,
          "sfgs": "1",
          "deptId": null,
          "areaId": "201200",
          "xyZhgxsj": "2020-04-16T22:09:47+08:00",
          "catalogId": "1232",
          "createTime": null,
          "deptName": null,
          "businessCreateDate": null
        }

**Comment by studyhuang1996** [comment]
数据库类型是timestamp才会多12小时，其他不会，请问有遇到过该问题的吗

**Comment by studyhuang1996** [comment]
这个应该是数据库时区出错导致的。 又遇到过的可以看下数据库时区对不对

**Comment by 2pc** [comment]
schema呢？
`               "effectBegin": {
                    "type": "date",
                    "format": "yyyy-MM-dd HH:mm:ss"
                }`

**Comment by EstellaHuang** [comment]
请问楼主的问题解决了吗？我的mysql和adapter时区都是东八区，日期类型数据同步到es，加了8小时。es中查出来是"updateTime": "2020-07-23T15:47:32+08:00"，DML里面的日期是"update_time":1595490452000。

**Comment by chenzy2017** [comment]
我多14个小时, 为啥, 怎么解决的; 
我两个库, 数据源是cst时区, 目标库是上海时区, 为何差14小时
