### ISSUE TITLE
canal运行startup.sh 服务安装不上

### ISSUE THREAD

**Issue by Mrwch** [alibaba/canal#2688]
bash: /c/Program: No such file or directory
bash: /c/Program: No such file or directory
bash: /c/Program: No such file or directory
bash: /c/Program: No such file or directory
bash: /c/Program: No such file or directory
这是错误日志
出现错误的地方是下面的语句：
$JAVA $JAVA_OPTS $JAVA_DEBUG_OPT $CANAL_OPTS -classpath .:$CLASSPATH com.alibaba.otter.canal.deployer.CanalLauncher 1>>$base/logs/canal/canal_stdout.log 2>&1 &
我建了一个c/Program 目录 ，然后又报错了：
bash: /c/Program: Is a directory

**Comment by agapple** [comment]
检查一下自己的环境目录

**Comment by xigua2333** [comment]
你好这个问题解决了么？遇到了一样的问题，半天没弄明白。。。
