### ISSUE TITLE
使用docker启动-e指定的参数是怎么传进去的，想了解一下实现方法？？？

### ISSUE THREAD

**Issue by BigData-YC** [alibaba/canal#2690]
example 1 :本地
  run.sh -e canal.instance.master.address=127.0.0.1:3306 \
         -e canal.instance.dbUsername=canal \
         -e canal.instance.dbPassword=canal \
         -e canal.instance.connectionCharset=UTF-8 \
         -e canal.instance.tsdb.enable=true \
         -e canal.instance.gtidon=false \
         -e canal.instance.filter.regex=.*\\\..*
example 2 :admin
  run.sh -e canal.admin.manager=127.0.0.1:8089 \
         -e canal.admin.port=11110 \
         -e canal.admin.user=admin \
         -e canal.admin.passwd=4ACFE3202A5FF5CF467898FC58AAB1D615029441

这些-e 的参数怎么传入程序的？？？？？
追踪过run.sh---->main.sh---->app.sh----->start.sh
有一个参数一直没明白$ENV，想明白参数怎么传进来的？？？
启动时还会自动加载canal.properties和instance.properties

**Comment by dingyufei615** [comment]
-e是ENV 通过设置环境变量的方式读的

**Comment by agapple** [comment]
LS正解
