### ISSUE TITLE
canal-adapter针对保留字的处理

### ISSUE THREAD

**Issue by nerverbe** [alibaba/canal#2692]
## Question

完全使用canal-adapter时，出现了insert语句保留字问题。这一块在新表自己做映射？

**Comment by station19** [comment]
我也遇到同样问题,生产环境遇到 表中字段名竟然有  order,update,create 等字段,... 如兄弟有解决方案了麻烦 分享下, 谢谢

**Comment by nerverbe** [comment]
@station19 1.1.5版本以上就解决了问题。源码里加上了反引号
