### ISSUE TITLE
canal解析proto格式的消息

### ISSUE THREAD

**Issue by godchou** [alibaba/canal#2697]
## Question

tidb同步到kafka中的消息格式为protobuf,直接用CanalMessageDeserializer反序列化会报错，有什么解决方案吗

**Comment by leipengcheng** [comment]
我们也遇到了这个问题，Protocol message end-group tag did not match expected tag.

**Comment by godchou** [comment]
可以先把tidb的protobuf 转换成JAVA对象，在与canal.entry互转，就是太麻烦了
