### ISSUE TITLE
canal-adapter在1.1.4版本中启动器在启动时找不到配置目录问题

### ISSUE THREAD

**Issue by hoofungson** [alibaba/canal#2704]
## Question
**操作环境：** IDEA中

昨天拉取1.1.4的源码后，启动canal-adapter的启动器后出现异常了“Config dir not found.”。跟踪代码后发现是com.alibaba.otter.canal.client.adapter.support.Util#getConfDirPath(String subConf)方法里加载映射资源时的目录指向错了，源码启动后指向了~/tartget/classess目录下，而映射资源文件在~/tartget/canal-adapter目录下。

**Comment by bestming** [comment]
https://github.com/alibaba/canal/issues/4208
