### ISSUE TITLE
canal adapter是否支持通配符匹配多表数据到一个index？

### ISSUE THREAD

**Issue by MistRay** [alibaba/canal#2705]
## Question
我有很多message_开头的表，例如message_1,message_2,message_3......message_999，这些表的结构都是相同的。

我想把这些表里的数据同步到同一个index中，我能否使用通配符或其他更方便的方式进行配置，还是只能在es文件夹下创建999个yml配置文件？

**Comment by MistRay** [comment]
@agapple 希望大佬解答一下，如果不支持我就多弄点配置文件。。。

**Comment by flyingonthebed** [comment]
每个 adpter 里面有多个组 groups，在每个 group 里面配置同步的 mapping

**Comment by MistRay** [comment]
@flyingonthebed 
可以具体一点么,我在`application.yml`确实有看到group.
但是并没有看到能设置mapping的地方,目前仅发现conf/es文件夹下可以配置mapping.

**Comment by MistRay** [comment]
最终解决方案:
自己写脚本生成配置文件.
配置文件很多,不是很容易维护.
