### ISSUE TITLE
 user:Canal Manager passwd incorrect!

### ISSUE THREAD

**Issue by sunyaf** [alibaba/canal#2706]
## Question

登陆admin web 页面，报错 user:Canal Manager passwd incorrect!，但是我的用户密码肯定是对的

**Comment by sunyaf** [comment]
123456 第一次

**Comment by mdp1230** [comment]
Web页面的密码和 canal-admin中的密码不是同一套认证体系。

**Comment by yangsai7** [comment]
> 123456 第一次

牛逼的设计
