### ISSUE TITLE
同时发送两条消息至kafka

### ISSUE THREAD

**Issue by ProLik** [alibaba/canal#2708]
在canal-admin 下配置了一个集群
集群下部署了两台 server
创建了一个instance

消费kafka 消息时，是发现有每条消息都有 一条与之相同的数据，（id不一样，有时ts 不一样 ）

当把一个server 停掉时，就只会收到一条唯一消息

请问是不是，每台server 都会处理相同的 binlog，导致会发相同的消息至 kafka
如何处理才能让两server 发送不同的 消息

**Comment by agapple** [comment]
binlog是顺序的，如果是集群模式同一时间点只有一个server和client工作
