### ISSUE TITLE
Canal Server拉取带中文的表名的日志循环报错，看到帮忙解答一下，拜谢/抱拳！！！

### ISSUE THREAD

**Issue by 17628282586** [alibaba/canal#2711]
- [ ] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment

* canal version
v1.1.4
* mysql version
5.7.17-log

### Issue Description
在同步一个中文表名的数据的时候，报了下面的错误，然后就会一直循环去抓取binlog日志，也就一直循环报错。不知道针对中文表名这种是否需要增加什么配置，或者有没有什么机制，抓取的时候达到了报错的指定次数，就跳过该条binlog日志，继续后面的日志解析，这样不影响后面的解析工作？？？

### Actual behaviour

If there is an exception, please attach the exception trace:

com.alibaba.otter.canal.parse.exception.CanalParseException: com.alibaba.otter.canal.parse.exception.CanalParseException: com.alibaba.otter.canal.parse.exception.CanalParseException: fetch failed by table meta:`test_canal`.`èµæº201908_copy`

![002](https://user-images.githubusercontent.com/44051592/80583520-e4d72100-8a42-11ea-95d7-d99a13517c39.png)

Just put your stack trace here!
```

**Comment by agapple** [comment]
#2714，类似的问题，最新的版本已经修复
