### ISSUE TITLE
使用原生的mq发到kafka，binlog日志的数据为什么没有偏移量信息。。写代码的时候可以拿到偏移量的。

### ISSUE THREAD

**Issue by everior** [alibaba/canal#2713]
如题，之前写过代码试过拿binlog日志，可以拿到该条binlog日志的偏移量。但是使用原生的mq发送到kafka里时候，只有数据操作的一些信息，没有这条信息在binlog的偏移量。 
![QQ截图20200430094708](https://user-images.githubusercontent.com/35693323/80663952-075f4d80-8ac8-11ea-94ea-30ff4772843a.png)

**Comment by agapple** [comment]
flatMessage简化格式没有位点信息，原生的protobuf对象会有完整的信息
