### ISSUE TITLE
同步mysql到kafka延迟非常高

### ISSUE THREAD

**Issue by lanmaodage** [alibaba/canal#2717]
## Question
同步mysql到kafka延迟有时非常高，达1个多小时都有
同时在grafana发现Store remain events和buffer size差不多一样高，怀疑是消费太慢导致堆积了，这个应该是调整哪个参数要解决呢，麻烦如有遇到的朋友分享一下，谢谢大家！

**Comment by baoyang23** [comment]
消费是太慢是指 canal 解析 mysql 的binlog 获取数据太慢, 还是 你的业务逻辑代码消费 kafka 很慢?
