### ISSUE TITLE
启动adapter 报错

### ISSUE THREAD

**Issue by sunyaf** [alibaba/canal#2721]
something goes wrong when starting up the canal client adapters:
java.lang.NullPointerException: null
        at java.util.Hashtable.put(Hashtable.java:460) ~[na:1.8.0_181]

**Comment by sunyaf** [comment]
已经解决

**Comment by liminglin1995** [comment]
遇到了同样的问题，请问你怎么解决的

**Comment by sunyaf** [comment]
我忘了呀，太久了，记得好像是表里面有特殊名字字段，比如name这种，在binlog里面是NAME

**Comment by sunyaf** [comment]
> 遇到了同样的问题，请问你怎么解决的

我忘了呀，太久了，记得好像是表里面有特殊名字字段，比如name这种，在binlog里面是NAME
