### ISSUE TITLE
canal首次同步数据的问题

### ISSUE THREAD

**Issue by xlyyy** [alibaba/canal#2725]
## Question

在binlog可能已经被清理的情况下，canal有没有同步历史数据的方案？

**Comment by VincentLiSH** [comment]
这肯定不支持的。我采用变通的办法，创建一个影子表 然后出发消费逻辑执行。

> drop table if exists fi_task_etl_init;
create table fi_task_etl_init as select * from fi_task where state not in('invalid','creater_closed','close_co_rejected','close_co_cancelled');

**Comment by agapple** [comment]
全量触发一次

**Comment by wo8335224** [comment]
Mysql 库间镜像schema DDL DML同步，即数据库镜像（Sync RDB）

配置参数mirrorDb=true，想先同步历史全量数据，好像目前不支持。我自己扩展稍微修改了rdb adapter的代码，能满足要求，但
是有点儿小粗暴。
