### ISSUE TITLE
canal.instance.filter.regex配置不生效

### ISSUE THREAD

**Issue by codedart2018** [alibaba/canal#2730]
## Question
canal version:1.1.4
mysql version: 8.0.19
client: go
environment: docker
docker volumes: /conf/canal/example/
我在instance.properties里面配置了 ```canal.instance.filter.regex=example:test\\.test```指定 example实例test库test表，保存后重启docker相关服务，运行客户端服务。发现在example目录下生成的 meta.dat 文件中 filter 并未来生效。还是默认的 ".*\\..*"。
贴一个完整的meta.dat
```
{
    "clientDatas": [
        {
            "clientIdentity": {
                "clientId": 1001,
                "destination": "example",
                "filter": ".*\\..*"
            },
            "cursor": {
                "identity": {
                    "slaveId": -1,
                    "sourceAddress": {
                        "address": "mysql",
                        "port": 3306
                    }
                },
                "postion": {
                    "gtid": "",
                    "included": false,
                    "journalName": "mysql-bin.000032",
                    "position": 696,
                    "serverId": 1,
                    "timestamp": 1589189724000
                }
            }
        }
    ],
    "destination": "example"
}
```
执行sql语句
```
INSERT INTO `test`.`test`(`name`) VALUES ('4');
```
客户端正常接收到消息。
执行sql语句
```
INSERT INTO `test`.`test1`(`name`) VALUES ('4');
```
同样正常接收到消息。
我在客户端无论如何设置 Subscribe。除了默认的 ```Subscribe(".*\\..*")```，能正常读取外，其它都不能正确读取！

然后我想问下在 instance.properties 文件里设置regex为何没有生效，还是我 ```example:test\\.test```本身有问题，然后它不正确读取默认的配置？
客户端的Subscribe一定要与  instance.properties 里的 regex配置一样嘛？

**Comment by fananzhi** [comment]
请问 问题解决了吗？ 同遇到该问题

**Comment by codedart2018** [comment]
> 请问 问题解决了吗？ 同遇到该问题

最后我发现在配置文件中无论如何配置都会被覆盖，只能在程序中配置。程序中配置正确就没事正确了！我的客户端是go版本java我不清楚！

**Comment by wentaotang0** [comment]
请问问题怎么解决的

**Comment by wowo666** [comment]
> 

我配置的 canal.instance.filter.regex=test\\..*  （test库所有表, test库里有table01，table02， table03）， 在go的客户端程序里Subscribe("test.table01") 却能收到操作test库里其他表的事务数据，如table01、table02的事务数据 ； 请问要怎么设置才可以不收到其他表的数据？

**Comment by Byrontoo** [comment]
开启了sql, 设置：canal.instance.filter.query.dml=false，发现另外一个配置项：canal.instance.filter.regex 过滤数据库功能失效了
