### ISSUE TITLE
同步数据失效

### ISSUE THREAD

**Issue by suinxinliulang** [alibaba/canal#2731]
canal-client运行后监听到sever的消息处理后报错
CanalServerException: ack error clientId: xxx batchId: xxx is not exist , please check

这是什么问题

**Comment by duanshouliang** [comment]
这个问题解决吗，同样碰到这个问题

**Comment by agapple** [comment]
canal-server估计做了rollback，client做一下重试

**Comment by songhejia** [comment]
遇到同样问题，偶尔出现一次
