### ISSUE TITLE
canal.mq.dynamicTopic 无法满足我的需求

### ISSUE THREAD

**Issue by panda-lab** [alibaba/canal#2734]
我有一个kafka集群， 里面有很多topic
我希望 我canal 写入的topic都加上一个前缀 :

canal-<database>.<table>

以此来方便区分我的其他 topic 与 我canal产生的topic

**Comment by zherenyu831** [comment]
@panda-lab 
你可以每个instance都设置 
```
canal.mq.dynamicTopic=canal-topic_name:database.table
```

**Comment by yangyiweigege** [comment]
建议二次开发。配置前缀。。。我就是这么干的

**Comment by agapple** [comment]
可以考虑提交一个PR给我

**Comment by Level1Accelerator** [comment]
我也有此需要，建议动态topic可自定义前缀或者后缀这类的
