### ISSUE TITLE
1.1.4 版本 使用default-instance.xml zk没有位点信息是为什么呀

### ISSUE THREAD

**Issue by maiyatanglxn** [alibaba/canal#2739]
wiki中的信息是：
default-instance.xml介绍：

   store选择了内存模式，其余的parser/sink依赖的位点管理选择了持久化模式，目前持久化的方式主要是写入zookeeper，保证数据集群共享. 

   特点：支持HA

   场景：生产环境，集群化部署. 

但是我启动后zk上并没有位点信息

**Comment by Fanduzi** [comment]
同样的问题, 感觉作者不维护了呢?
https://github.com/alibaba/canal/issues/2616

**Comment by VincentLiSH** [comment]
启动zk

> docker run --privileged=true -d --network=cluster-net --name zk -p 2181:2181 -d zookeeper:latest

启动canalAdmin
> docker run --privileged=true -d --network=cluster-net --name canalAdmin -p 8089:8089 -p 11110:11110 -e server.port=8089 -e canal.adminUser=admin -e canal.adminPasswd=admin canal/canal-admin:v1.1.4

在集群主配置里面放开如下配置；
> canal.instance.global.spring.xml = classpath:spring/default-instance.xml

然后启动canal server，
> docker service create --name canal --network cluster-net --publish 11111:11111 --publish 11112:11112 -e canal.register.ip=canal -e canal.admin.manager=canalAdmin:8089 -e canal.admin.port=11110 -e canal.admin.user=admin -e canal.admin.passwd=4ACFE3202A5FF5CF467898FC58AAB1D615029441 -e canal.admin.register.auto=true -e canal.admin.register.cluster=etl -d canal/canal-server:v1.1.4

然后还需要客户端订阅canal，这时 取查看zookeeper就能看的cursor了：
> get /otter/canal/destinations/destName/1001/cursor

**Comment by agapple** [comment]
LS正解

**Comment by Fanduzi** [comment]
> LS正解

麻烦大佬看一下 https://github.com/alibaba/canal/issues/2616 , 实际生产1.1.4遇到了curor没有, 或者cursor更新周期异常的问题
