### ISSUE TITLE
多实例同步至同一es的场景中，ESBulkRequest.commit()批次提交实现会出现数据丢失，未同步

### ISSUE THREAD

**Issue by zhangyuan324** [alibaba/canal#2743]
### environment
elasticsearch version
6.4.3
* canal version
1.1.4
* mysql version
5.7
### Issue Description
增量同步时在并发情况下偶现，估计是在resetBulk的时候，将bulk过程中新增的数据清空了，导致数据未同步到es

**Comment by agapple** [comment]
可以提交一个PR给我
