### ISSUE TITLE
可以为每个instance定义canal.mq.servers吗?

### ISSUE THREAD

**Issue by Fanduzi** [alibaba/canal#2744]
## Question
请问可以为每个instance单独指定canal.mq.servers吗, 实现不同instance写入不同kafka集群?

我自己测试了一下在instance.propertites文件添加canal.mq.servers参数指定与canal.properties不同的kafka, 启动后发现还是写入了canal.properties中定义的kafka中

**Comment by agapple** [comment]
一个canal-server进程只能配置1个kafka集群
