### ISSUE TITLE
canal编码问题

### ISSUE THREAD

**Issue by qianjiangtao** [alibaba/canal#2746]
## Question

**com.alibaba.fastsql.sql.parser.ParserException: syntax error, error in :'CTER SET 'utf8'', expect null, actual null, pos 43, line 1, column 38, token LITERAL_CHARS utf8**
尝试使用utf-8和utf8mb4都报错，看提示是希望是null？

**Comment by duhanmin** [comment]
没人管了？

**Comment by lianbitangjin** [comment]
唉，没人维护了

**Comment by agapple** [comment]
完整的DDL语句提供一下

**Comment by sproutcat** [comment]
CREATE DATABASE `uat_zz_quartz` CHARACTER SET 'utf8mb4'
