### ISSUE TITLE
docker v1.1.4 modified_time存在问题

### ISSUE THREAD

**Issue by duhanmin** [alibaba/canal#2747]
https://hub.docker.com/r/canal/canal-admin/tags/v1.1.4
报错如下：
Error[Column 'modified_time' cannot be null]

**Comment by mdp1230** [comment]
把表中的modified_time字段定义全部由not null更改成null。
程序insert 的时候送了 null字给modified_time，程序写的有点烂。

**Comment by agapple** [comment]
最新的已经修复
