### ISSUE TITLE
canal.instance.filter.regex 参数不起作用

### ISSUE THREAD

**Issue by rocky-peng** [alibaba/canal#275]
canal.instance.filter.regex = demodbname\\\\.user

这样设置后，client端还是会接受到接收到非user表的binlog日志信息。
使用版本：
1.0.23

**Comment by liutizhong** [comment]
[zk: localhost:2181(CONNECTED) 44] get /otter/canal/destinations/example/1001/filter
.*\..*
cZxid = 0x1000013e8
ctime = Fri Mar 03 11:26:12 CST 2017
.....................
....................

[zk: localhost:2181(CONNECTED) 48] set /otter/canal/destinations/example/1001/filter demodbname\\.user  

试试，zk 中貌似记录了初始值，修改配置文件后，重启服务，貌似zk中的值没有修改过来，导致的 参数不起作用，个人猜测的
