### ISSUE TITLE
canal client need do connector.rollback() when catching exception

### ISSUE THREAD

**Issue by hxy91819** [alibaba/canal#2756]
- [x] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment

* canal version = 1.1.4
* mysql version = 5.7

### Issue Description

I have been continuing suffering a data loss when using canal. I found there always been some exceptions (like connect problems) happened with data loss.

So I check the client code in [AbstractCanalClientTest.java](https://github.com/alibaba/canal/blob/master/example/src/main/java/com/alibaba/otter/canal/example/AbstractCanalClientTest.java)

In line 79, we got `// connector.rollback(batchId); // 处理失败, 回滚数据`

I think it will be good if we add `connector.rollback(batchId)` when we got an exception.

Such as:
```
while (running) {
    Message message = connector.getWithoutAck(batchSize); // 获取指定数量的数据
    long batchId = message.getId();
    try {
        int size = message.getEntries().size();
        if (batchId == -1 || size == 0) {
            // 无效信息，可以考虑休眠
        } else {
            printSummary(message, batchId, size);
            printEntry(message.getEntries());
            if (handleEntry != null) {
                handleEntry.invoke(message.getEntries());
            }
        }

        if (batchId != -1) {
            connector.ack(batchId); // 提交确认
        }
    } catch (Exception e) {
        try {
            Thread.sleep(1000L);
        } catch (InterruptedException e1) {
            Thread.currentThread().interrupt();
        }
        if (batchId != -1) {
            connector.rollback(batchId); // 处理失败, 回滚数据
        }
    }
}
```

The question is : why you guys didn't do this in the code of examples? Is this irregular?

### Actual behaviour

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by agapple** [comment]
默认rollbackOnConnect=true，会在下一轮自动rollback，不过代码的确是可以优化一下
