### ISSUE TITLE
1.1.4 通过adapter 普通mysql同步，dml中 insert语句可以同步，delete和update无法同步，刚研究canal 感觉某个配置有问题

### ISSUE THREAD

**Issue by yuzn** [alibaba/canal#2759]
## Question

主要配置：

# enable gtid use true/false
canal.instance.gtidon=false

# position info
canal.instance.master.address=127.0.0.1:3306
canal.instance.master.journal.name=
canal.instance.master.position=
canal.instance.master.timestamp=
canal.instance.master.gtid=

# rds oss binlog
canal.instance.rds.accesskey=
canal.instance.rds.secretkey=
canal.instance.rds.instanceId=

# table meta tsdb info
canal.instance.tsdb.enable=true

# username/password
canal.instance.dbUsername=canal
canal.instance.dbPassword=canal
canal.instance.connectionCharset = UTF-8
canal.instance.enableDruid=false

canal.instance.defaultDatabaseName=master
canal.instance.filter.black.regex=master.t_order   #监控的数据库表
canal.instance.filter.black.regex=

server:
  port: 8081
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

canal.conf:
  mode: tcp # kafka rocketMQ
  canalServerHost: 127.0.0.1:11111
  batchSize: 500
  syncBatchSize: 1000
  retries: 0
  timeout:
  accessKey:
  secretKey:
  srcDataSources:
    defaultDS:
      url: jdbc:mysql://127.0.0.1:3306/master?useUnicode=true
      username: root
      password: root
  canalAdapters:
  - instance: example # canal instance Name or mq topic name
    groups:
    - groupId: g1
      outerAdapters:
      - name: logger
      - name: rdb
        key: mysql1
        properties:
          jdbc.driverClassName: com.mysql.jdbc.Driver
          jdbc.url: jdbc:mysql://127.0.0.1:3306/slave0?useUnicode=true
          jdbc.username: root
          jdbc.password: root

dataSourceKey: defaultDS
destination: example
groupId: g1
outerAdapterKey: mysql1
concurrent: true
dbMapping:
  database: master
  table: t_order
  targetTable: slave0.t_order
  targetPk:
    order_id: 
  mapAll: true
  commitBatch: 1 # 批量提交的大小

**Comment by station19** [comment]
怎么样, 解决了吗

**Comment by station19** [comment]
我也遇到同样问题,

**Comment by yfsmmr777** [comment]
这个问题是怎么解决的呢? 我现在用1.1.7版本,还是出现这个问题
