### ISSUE TITLE
canal-client-1.1.4，停电关机client，zookeeper节点不会被清除

### ISSUE THREAD

**Issue by mrwutong** [alibaba/canal#2761]
由于不可控因素，某台canal-client节点所在宿主机，断电停机。
重启之后发现，该canal-client所属的zookeeper的runner节点并没有清除，
这样的现象会导致，同集群其他canal-client节点无法自动切换，
而且即使重新启动canal-client也不会消费来自canal-server的binlog数据。
除非人肉手动删除zookeeper的runner节点才可以恢复正常。
所以这种情况，除了监控机制，仍然需要人肉操作，应用在生产环境风险较大。
该场景经【kill -9】命令强制中断服务，即可再现。
期待改进。

**Comment by zherenyu831** [comment]
我也有一样的问题，我是部署在k8s上的，结果每次roll update 总要手动删除canal server，特别麻烦

**Comment by mrwutong** [comment]
经过一番调查，发现可能是由于zookeeper服务器的问题。本地搭建了一套集群模式，kill -9 强杀client，默认40秒过后 running节点会被自动清除。
zookeeper服务器默认配置ticketTime=2000意思是2秒，zookeeper有一个最大最小会话超时时间，具体逻辑可以网上搜一下。结果就是最小sessiontimeout时间4秒，最大sessiontimeout时间40秒。

**Comment by agapple** [comment]
running节点都是zookeeper的临时节点，随着断网或者节点crash，zookeeper会自动清楚临时节点
