### ISSUE TITLE
本地从CanalAdapterApplication启动报错: java.lang.NullPointerException。 放到linux上, startup.sh启动没有问题。

### ISSUE THREAD

**Issue by stevenxia2016** [alibaba/canal#2762]
类 AdapterProcessor， 方法 AdapterProcessor：

`        Properties properties = canalClientConfig.getConsumerProperties();
        properties.put(CanalConstants.CANAL_MQ_FLAT_MESSAGE, canalClientConfig.getFlatMessage());`

由于canalClientConfig.getConsumerProperties() 返回空，下面一行 put的时候就出错了：
java.lang.NullPointerException

**Comment by agapple** [comment]
可以考虑提交一个PR给我
