### ISSUE TITLE
Canal可以支持drds吗？   如果可以、需要怎么配置操作

### ISSUE THREAD

**Issue by s124513009** [alibaba/canal#2764]
Canal可以支持drds吗？   如果可以、需要怎么配置操作

**Comment by agapple** [comment]
可以链接drds下的物理rds，每个rds单独配置一个canal instance即可

**Comment by Tw0d0gs** [comment]
@agapple  您好 我链接了drds下的物理rds并配置canal instance ，但是instance给我返回如下错误，我想请问一下可能是什么原因导致的。

**Comment by masami-7** [comment]
解决了吗，我链接drds下的物理rds，监听到的不是正常的sql
