### ISSUE TITLE
wiki中canal.mq.dynamicTopic详细配置说明的错误

### ISSUE THREAD

**Issue by OpenOpened** [alibaba/canal#2770]
### environment

* canal version  1.1.4
* mysql version  - mariadb 10.1.37

### Issue Description
wiki中【例子4：test\\.* 指定匹配的表达式，针对匹配的表会发送到各自表名的topic上】，针对相同库的所有表，应该是test\\..*而不是test\\.*。不然会报
```
 Error while fetching metadata with correlation id 667 : {=INVALID_TOPIC_EXCEPTION}
```

**Comment by dingyufei615** [comment]
你好 我在配置动态topic时 一直没能正确的动态的根据规则发送
我的配置是这样的 对于同库下的所有表 \\..* 的语法是否正确
canal.mq.dynamicTopic=binlog-chd:chd\\..*,binlog-sns01:sns01\\..*,binlog-sns02:sns02\\..*,binlog-sns03:sns03\\..*,binlog-sns04:sns04\\..*,binlog-trademd:trademd\\..*,binlog-ask00:ask00\\..*,binlog-we_dchat_main:we_dchat_main\\..*,binlog-oc_course_test:oc_course_test\\..*,binlog-oc_course_dev:oc_course_dev

**Comment by agapple** [comment]
instance.properties都有例子
```
#canal.mq.dynamicTopic=mytest1.user,mytest2\\..*,.*\\..*
```
