### ISSUE TITLE
canal1.1.4开启kafka的ack后特别慢

### ISSUE THREAD

**Issue by ZYZ0001** [alibaba/canal#2771]
求大神解答:
使用canal-kafka模式, 开启ack后(1或者all),tps极低, 只有300到500, 数据量大的时候延迟瞬间上去了, blocking一直处于100%, 采用的是canal-admin管理, canal.properties和instance.properties参数基本是默认, 服务器是16C 64G; 将ack设置0, tps能达到7k左右. 但看wiki上测试tps都是几十万级别的, 怎么达到的? 是我配置有问题吗? ack开启后为什么这么慢? 是什么参数没设置好吗?

**Comment by dreamInHeart** [comment]
这个和你的消费速度有关系吧。我是从mysql导入ES，消费的过程需要反查mysql，消费速度肯定不高，sql慢的时候更明显。

**Comment by ZYZ0001** [comment]
这个和消费没有关系, 只是kafka的生产, 相同条件下将ack设置为0, 虽然没官方测试的几十万的tps, 但是也很快了, 就是将ack设置1或all很慢; kafka的压测的时候也还是很快的, 所有想问问是不是我什么参数没设置正确

**Comment by chenfei7357** [comment]
请问这个问题有人解决的吗？我也遇到这个情况。

**Comment by ZYZ0001** [comment]
> 请问这个问题有人解决的吗？我也遇到这个情况。

没解决, 你有好的方式吗?

**Comment by miaobf** [comment]
使用canal.mq.flatMessage = false ，acks=all，延迟大约在230ms，已经很快了，flatMessage解析数据应该比较耗时，可以尝试一下看下效果

**Comment by agapple** [comment]
参考一下：https://github.com/alibaba/canal/wiki/Canal-MQ-Performance
