### ISSUE TITLE
canal-1.1.2 在遇到数据高峰期，不能拿更多数据，需要重启instance 消费binlog速度才提升

### ISSUE THREAD

**Issue by haocode** [alibaba/canal#2776]
当rds 数据低峰时候 canal 消费数据一直处在正常的，当数据高峰来的时候，canal不能及时拿到更多数据，导致canal数据消费延迟，对 instance  重启以后 canal 消费能力 增强。下次遇到突然数据高峰 还有可能需要重启

**Comment by agapple** [comment]
打开一下监控，判断一下是下游消费速度跟不上还是解析跟不上？从之前的测试数据来看，解析速度可以有10w+的吞吐
