### ISSUE TITLE
mysql百万数据更新，同步太慢 ，有什么优化的办法吗

### ISSUE THREAD

**Issue by zxxrawy** [alibaba/canal#2777]
## Question
有什么办法能够让一次批量update放到一个消息里面发送到kafka，而不是分成多个消息进行发送

**Comment by minicx** [comment]
关注下，遇到同样的问题。经常堵塞了

**Comment by qqxx6661** [comment]
关注下，也是类似的问题。

**Comment by luger1990** [comment]
有解决的吗 或者有什么参数可以调优的吗

**Comment by KylinShinlyLin** [comment]
同样关注

**Comment by luger1990** [comment]
@KylinShinlyLin @qqxx6661 @minicx @zxxrawy 我通过这个优化了一下  感觉好多了 https://github.com/alibaba/canal/wiki/Canal-MQ-Performance  
另外还优化了canal.mq.bufferMemory 这个也调大了

**Comment by agapple** [comment]
LS正解
