### ISSUE TITLE
canal server cpu 100%

### ISSUE THREAD

**Issue by keyganker** [alibaba/canal#278]
@agapple 
版本是最新的master，我是从4天前的一个binlog pos点开始同步的，发现同步速度跟之前相比慢很多，top发现canal server cpu一直100%，经过定位找到如下栈：
![cpu](https://cloud.githubusercontent.com/assets/3198806/23615030/0adf5ef2-02c0-11e7-9334-fc3c3e399d6e.png)
内存当时是：
             total       used       free     shared    buffers     cached
Mem:         32047      24349       7698          0        274      13740
-/+ buffers/cache:      10333      21713
Swap:          511        189        322

**Comment by agapple** [comment]
这块是有新同学提交的netty4的实现，可能存在一些问题

**Comment by agapple** [comment]
可以尝试用最新的1.1.1版本，已优化
