### ISSUE TITLE
canal存在fastjson远程命令执行漏洞，请更新

### ISSUE THREAD

**Issue by sevck** [alibaba/canal#2781]
### environment

* canal version N/A
* mysql version N/A

### Issue Description
目前最新版本，使用fastjson存在远程命令执行漏洞，请更新相关组件。
https://github.com/alibaba/fastjson/releases
```
这是一个关键的安全修复版本，修复新发现高危autotype开关绕过安全漏洞，请大家尽快升级到1.2.69或者更新版本。
```
阿里官网公告：
https://github.com/alibaba/fastjson/wiki/security_update_20200601

### Actual behaviour

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by agapple** [comment]
可以考虑提交一个PR给我
