### ISSUE TITLE
第一次运行canal.example出错，显示pom.xml有问题，命令行和eclipse内部都不行

### ISSUE THREAD

**Issue by LIN-ALOHA** [alibaba/canal#2782]
错误日志：
Project build error: Non-resolvable parent POM for 
 com.alibaba.otter:canal:1.1.4: Failure to find org.sonatype.oss:oss-
 parent:pom:7 in http://repo1.maven.org/maven2 was cached in the local 
 repository, resolution will not be reattempted until the update interval of 
 central has elapsed or updates are forced and 'parent.relativePath' points at 
 wrong local POM

运行mvn exec:java -Dexec.mainClass="com.alibaba.otter.canal.example.SimpleCanalClientTest"
出错：
[INFO] Scanning for projects...
Downloading: http://repo1.maven.org/maven2/org/sonatype/oss/oss-parent/7/oss-parent-7.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for com.alibaba.otter:canal:1.1.5-SNAPSHOT: Could not transfer artifact org.sonatype.oss:oss-parent:pom:7 from/to central (http://repo1.maven.org/maven2): Failed to transfer file: http://repo1.maven.org/maven2/org/sonatype/oss/oss-parent/7/oss-parent-7.pom. Return code is: 501 , ReasonPhrase:HTTPS Required. and 'parent.relativePath' points at wrong local POM @ com.alibaba.otter:canal:1.1.5-SNAPSHOT, /home/lin/Desktop/canal-canal-1.1.5-alpha-1/pom.xml, line 9, column 13
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project com.alibaba.otter:canal.example:[unknown-version] (/home/lin/Desktop/canal-canal-1.1.5-alpha-1/example/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for com.alibaba.otter:canal:1.1.5-SNAPSHOT: Could not transfer artifact org.sonatype.oss:oss-parent:pom:7 from/to central (http://repo1.maven.org/maven2): Failed to transfer file: http://repo1.maven.org/maven2/org/sonatype/oss/oss-parent/7/oss-parent-7.pom. Return code is: 501 , ReasonPhrase:HTTPS Required. and 'parent.relativePath' points at wrong local POM @ com.alibaba.otter:canal:1.1.5-SNAPSHOT, /home/lin/Desktop/canal-canal-1.1.5-alpha-1/pom.xml, line 9, column 13 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.

每次打开工程文件example（canal1.1.4)出错。不知道该怎么改

**Comment by agapple** [comment]
mvn clean install eclipse:eclipse -Dmaven.test.skip=true
