### ISSUE TITLE
请问canal的密码明文是多少？

### ISSUE THREAD

**Issue by farsunset** [alibaba/canal#2784]
canal.user = canal
canal.passwd = E3619321C1A937C46A0D8BD1DAC39F93B27D4458

客户端连接的时候需要带上账号密码 但是这个E3619321C1A937C46A0D8BD1DAC39F93B27D4458 明文是多少？ 客户端如何指定passwor参数

**Comment by mdp1230** [comment]
明文密码是canal， 在mysql中select password('canal') 去掉*号就是这个密文

**Comment by farsunset** [comment]
> 明文密码是canal， 在mysql中select password('canal') 去掉*号就是这个密文

好的谢谢
