### ISSUE TITLE
fastsql ParserException

### ISSUE THREAD

**Issue by DinoZhang** [alibaba/canal#2791]
### environment

* canal version   1.4
* mysql version 5.7

### Issue Description
对于table前有点操作符的无db名的ddl解析异常,Alter操纵一般为`ALTER TABLE db.config` 或者`ALTER TABLE config`,下列ddl在mysql中可以正常运营，fastsql token解析失败

```sql
ALTER TABLE .`config`  ADD COLUMN `delay` int(11) NOT NULL DEFAULT 0 COMMENT '延迟(ms)' AFTER `memo`"
```

**Comment by agapple** [comment]
这个应该是fatsql解析bug  @wenshao
