### ISSUE TITLE
ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:example[java.lang.NullPointerException报错怎么解决？

### ISSUE THREAD

**Issue by DragonPrince1992** [alibaba/canal#2794]
## Question

![image](https://user-images.githubusercontent.com/63100745/83843272-3b690680-a737-11ea-8c55-3c98b58838ea.png)

ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:example[java.lang.NullPointerException报错

**Comment by agapple** [comment]
问题描述不够清楚，请提供问题复现的步骤
