### ISSUE TITLE
使用docker部署在windows环境下无法运行

### ISSUE THREAD

**Issue by wvfeng** [alibaba/canal#2798]
- [x] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment

* canal v1.1.4
* mysql 5.6

### Issue Description
Microsoft Windows [版本 10.0.19041.264]环境下使用`wsl2`开启的`docker`发现服务运行服务

### Steps to reproduce
# ① 没有任何提示直接退出
`docker run --rm -it  canal/canal-server:latest`
# ② 尝试运行到容器，也是直接退出，没有任何提示
`docker run --rm -it  --entrypoint "bash" canal/canal-server:latest`

附图如下：
![image](https://user-images.githubusercontent.com/33809027/83936993-7f254400-a7fb-11ea-967f-63b46867601d.png)

### Expected behaviour
可以成功运行
### Actual behaviour
无法运行

If there is an exception, please attach the exception trace:
没有任何提示和日志

**Comment by aaaweisen** [comment]
我也遇到同样的问题，请指教

**Comment by agapple** [comment]
--entrypoint "bash" 不要指定，可以参考wiki里的run.sh脚本启动docker

**Comment by pbby** [comment]
@wvfeng 哥们，你解决没？ 
同wsl2开启时起不来，但是关闭wsl2就可以。

**Comment by wvfeng** [comment]
@pbby 没有解决

**Comment by RainingNight** [comment]
@wvfeng 哥们解决没，同没有任何提示直接退出

**Comment by wvfeng** [comment]
@RainingNight 没有解决，对我来说影响不大，服务器上没事，本地不用docker也可以，只是感觉很奇怪，看样子官方也没有好的解决方案，问题直接给关了也没有正面回应

**Comment by RainingNight** [comment]
@wvfeng 感觉这项目被废弃了吧。。。。
