### ISSUE TITLE
[bug]TableMetaCache 在连接断了后的reconnect功能无效

### ISSUE THREAD

**Issue by cclehui** [alibaba/canal#280]
master上的源代码：
```
public TableMetaCache(MysqlConnection con){
        this.connection = con;
        tableMetaCache = MigrateMap.makeComputingMap(new Function<String, TableMeta>() {

            public TableMeta apply(String name) {
                try {
                    return getTableMeta0(name);
                } catch (IOException e) {
                    // 尝试做一次retry操作
                    try {
                        connection.reconnect();
                        System.out.println("cclehui 重新 connect master");
                        return getTableMeta0(name);
                    } catch (IOException e1) {
                        throw new CanalParseException("fetch failed by table meta:" + name, e1);
                    }
                }
            }

        });
```

可以看到在捕获到IOException 后会自动重连一次，然后在获取表结构。但问题在于如果mysql master主动关闭了连接，根本不会抛出这个IOException, 相反抛出的是一个 RuntimeException，相应的异常抛出代码在 MysqlQueryExecutor  29行：
```
public MysqlQueryExecutor(MysqlConnector connector) throws IOException {
        if (!connector.isConnected()) {//服务器关闭连接后会走这个逻辑抛出异常
            throw new RuntimeException("should execute connector.connect() first");
        }

        this.channel = connector.getChannel();
    }
```

如上所述，重连逻辑没有生效。

bug复现方法：
把 master mysql 的 wait_timeout 设置成20秒， 启动canal后等20秒， 去master做一些insert或update操作， canal slave得到这个binlog后，解析，如果本地没有标结构信息，就会通过一个非slave连接去master获取表结构信息， 但20秒后master已关闭该连接，这时候就抛出了RuntimeException ， 然后这个binlog事件就解析失败了。

我的解决方法:把RuntimeException 改成 IOException 抛出，但不知道会不会有什么别的问题,当然我自己测试OK

```
public MysqlQueryExecutor(MysqlConnector connector) throws IOException {
        if (!connector.isConnected()) {
//            throw new RuntimeException("should execute connector.connect() first");
            throw new IOException("should execute connector.connect() first");
        }

        this.channel = connector.getChannel();
    }
```

**Comment by keyganker** [comment]
我也遇到了同样的问题

**Comment by keyganker** [comment]
还有另外一个信息，理论上canal server在遇到异常之后是会重试的，如下：
![retry](https://cloud.githubusercontent.com/assets/3198806/23950250/4cf424ba-09c5-11e7-8439-a683e064a3ee.png)

从日志上来看也确实重试了，并且恢复了正常：
![retry_log_1](https://cloud.githubusercontent.com/assets/3198806/23950630/937491f8-09c6-11e7-83c6-bd15f16b34a7.png)

但是后面过段时间DB链接再次断掉之后却没有重试成功日志：
![retry_log_2](https://cloud.githubusercontent.com/assets/3198806/23950657/b04fb302-09c6-11e7-919a-61e1f6b488cf.png)
然后手动停止canal server，会报以下错误：
![retry_log_3](https://cloud.githubusercontent.com/assets/3198806/23950700/d4f989a8-09c6-11e7-9e19-ed071a0caf11.png)

**Comment by liutizhong** [comment]
期待完美解决方案..................
