### ISSUE TITLE
同步速度太慢跟canal.mq.acks 参数有关系吗？

### ISSUE THREAD

**Issue by Rainstyed** [alibaba/canal#2805]
## Question

同步数据时间太长，延迟特别高。

**Comment by ZSH9053** [comment]
改成1 加速，all太慢了  0 不安全

**Comment by Rainstyed** [comment]
每天的binlog的文件的position大概有50亿，有什么方法可以处理完？

**Comment by agapple** [comment]
这个参数是为了binlog保序，如果client发送有重试，需要确保重试成功之后再进行下一批
