### ISSUE TITLE
canal 是否支持mysql 8

### ISSUE THREAD

**Issue by ZSH9053** [alibaba/canal#2811]
目前使用的版本是1.4 我投递mysql8，现在报错如下 
WARN  com.taobao.tddl.dbsync.binlog.LogDecoder - Skipping unrecognized binlog event Unknown from: mysqlbin_117173306.000002:723726077
只能投递 ddl，dml似乎无法识别，有遇到过的嘛？

**Comment by agapple** [comment]
canal支持mysql 8，这个忽略的binlog非DML，请检查其他配置

**Comment by Flyfoxs** [comment]
我用canal-1.1.4, mysql8.0.21 遇到了一样的问题.

**Comment by xuxl58** [comment]
请问解决了吗？谢谢请问怎样解决的？

**Comment by ShelwinSu** [comment]
kipping unrecognized binlog event Unknown from: mysql-bin.000124:1016820167
是不是mysql 8.0 MGR 识别不了

**Comment by wly1618** [comment]
有没有解决 ？

**Comment by xiaokuan1234** [comment]
解决了吗
