### ISSUE TITLE
canal不能正确解析MySQL数据库enum类型数据

### ISSUE THREAD

**Issue by jxzdoing** [alibaba/canal#2813]
## Question

在我们的数据库里有一个表的字段数据类型是enum，值为0和1。但是通过canal解析后，发现有的值是变为2，想问一下这个是不是canal的bug或者应该怎么解决，谢谢。

**Comment by agapple** [comment]
问题描述不够清楚，请提供一下完整的复现步骤

**Comment by yl-yue** [comment]
貌似binlog解析的是枚举下标，而非值，是否有一种配置，可以让binlog解析枚举值
