### ISSUE TITLE
canal 服务端这边是不是默认缓存数只有16kb? 如果消费者没去消费超过了怎么办

### ISSUE THREAD

**Issue by Xuzan9396** [alibaba/canal#2815]
![image](https://user-images.githubusercontent.com/24741439/84251969-a43ded80-ab40-11ea-9140-90631dba5c3b.png)

**Comment by YiuTerran** [comment]
接kafka啊…

**Comment by Xuzan9396** [comment]
@YiuTerran 好的， 线上用的rabbitmq 不知道支持不支持
