### ISSUE TITLE
有什么开源组件可以替换Canal

### ISSUE THREAD

**Issue by laizuan** [alibaba/canal#2820]
alibaba 开源项目太多这种老项目估计不会维护了。各位有什么好的替代产品推荐！！！

**Comment by hanlukk** [comment]
maxwell, go版本的canal

**Comment by lightzhao** [comment]
1.debzium下的connect-mysql结合kafka-connect
2.mysql-binlog-connector-java

**Comment by dingyufei615** [comment]
spark-binlog 
不过目前还在更新。

**Comment by agapple** [comment]
canal会持续更新
