### ISSUE TITLE
两个字段设置联合唯一索引，一个事物，先执行delete，后insert，会出现报错，Duplicate entry 'XXXXXXXX' for key

### ISSUE THREAD

**Issue by CurtisYang1989** [alibaba/canal#2824]
## Question

两个字段设置联合唯一索引，一个事物，先执行delete，后insert，会出现报错，Duplicate entry 'XXXXXXXX' for key

**Comment by agapple** [comment]
RDB同步时会有并行机制，导致老记录的delete和新记录的insert会有并发
