### ISSUE TITLE
版本升级

### ISSUE THREAD

**Issue by qiuchunliu** [alibaba/canal#2825]
## Question

请问如何进行版本升级？
那里有文档进行说明吗？
升级后旧版的客户端代码必须要进行调整吗？

请了解过的大佬帮忙解答一下。谢谢！

**Comment by ruyin-zh** [comment]
我这边升级过1.1.0与1.1.3版本的(升级到1.1.4)，目前暂时还未发现问题，如果需要使用1.1.4版本的，先按照官方的配置本地或测试环境验证下

**Comment by agapple** [comment]
LS正解
