### ISSUE TITLE
rocketmq 可以监听多个topic 么

### ISSUE THREAD

**Issue by wz2cool** [alibaba/canal#2826]
## Question

![image](https://user-images.githubusercontent.com/11556152/84985846-14b3c280-b170-11ea-8875-1e08c0ab65e7.png)
这里我们是否支持subscribe 多个topic呢
主要想问一下 如果我个人改了这边代码会不会有bug 啊

**Comment by agapple** [comment]
这个是MQ的消费逻辑，多个topic不影响，设计上没有约束
