### ISSUE TITLE
我通过canal-client投递到业务方，如何让投递的消息过去带上唯一的消息id不重复消费啊

### ISSUE THREAD

**Issue by liaoliang** [alibaba/canal#2830]
目前好像只有messageid和binlog-position
但是在主从切换，或者监控group组的实例的时候都不能唯一确定

**Comment by yangyiweigege** [comment]
二次开发。带上binlog 的position 完美解决

**Comment by liaoliang** [comment]
> 二次开发。带上binlog 的position 完美解决
如果是带这个还需要带上serverid吧
如果服务器在切换的时候 这个serverid没有用了吧
