### ISSUE TITLE
RocketMQ Caused by: java.lang.IndexOutOfBoundsException: Index: 16, Size: 16

### ISSUE THREAD

**Issue by sunnyfrank** [alibaba/canal#2837]
RocketMQ的分区到底是配置几呢？琢磨不透，3，4，15，16，24都试了 ，都在不停的重复发消息
canal.mq.partitionsNum=16
canal.mq.partitionHash=.*\\..*:id

**Comment by agapple** [comment]
多看一下wiki和issue，或者加入微信群
