### ISSUE TITLE
wiki可否写的稍微再清晰一点

### ISSUE THREAD

**Issue by sunnyfrank** [alibaba/canal#2838]
canal.mq.partition
canal.mq.partitionsNum
canal.mq.partitionHash
这三个参数搞不懂到底怎么用，wiki可否写的稍微再清晰一点？
配置的要么只有单机消费，要么就是超index,疯狂重试，要么就是4个节点只有3个能消费

**Comment by agapple** [comment]
多看一下wiki或者issue

**Comment by farsunset** [comment]
> 多看一下wiki或者issue

issues 里面已经好多人提出了同样的问题，没一个解决的方案
