### ISSUE TITLE
canal.adapter srcDataSources 配置疑问

### ISSUE THREAD

**Issue by lhp609661060** [alibaba/canal#2839]
## Question

1、使用 canal.adapter 同步数据到es中  srcDataSources 为啥还要数据库配置，读数据不是从canal.deployer里面读数据吗？
2、canal.adapter目前发现数据库版本不对链接不上。但是canal.deployer可以链接上。  这2个可否统一

**Comment by agapple** [comment]
canal.deployer是做binlog dump，adapter 里主要做数据库ETL的，需求不一样
