### ISSUE TITLE
adapter同步源库中一个表的数据出现了 下游秀昂痛的表数据比源库的多而且在不停的增加

### ISSUE THREAD

**Issue by MJY934356565** [alibaba/canal#2841]
- [ ] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment

* canal version
* mysql version

### Actual behaviour

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by agapple** [comment]
问题描述不清楚
