### ISSUE TITLE
CustomExceptionHandler - auth :admin is failed

### ISSUE THREAD

**Issue by cun123** [alibaba/canal#2846]
ERROR c.a.otter.canal.admin.handler.CustomExceptionHandler - auth :admin is failed
java.lang.RuntimeException: auth :admin is failed
        at com.alibaba.otter.canal.admin.controller.PollingConfigController.canalConfigPoll(PollingConfigController.java:51)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)

什么原因？

感谢！

**Comment by LiuFuyuan** [comment]
你好，请问你这个问题是怎么解决的，我现在也遇到这问题了

**Comment by jackylvm** [comment]
admin/conf/application.yml里面有个adminPasswd密码是明文的
其他地方密码都是加密的,使用时这个密码要一致
在admin的网页上改的密码应该不影响上面的密码
加密密码的方法,在mysql的shell里面执行select password("your password")

**Comment by 741082214** [comment]
> admin/conf/application.yml里面有个adminPasswd密码是明文的
> 其他地方密码都是加密的,使用时这个密码要一致
> 在admin的网页上改的密码应该不影响上面的密码
> 加密密码的方法,在mysql的shell里面执行select password("your password")

还是不行，还是显示 auth :admin is failed

**Comment by hfpf** [comment]
> > admin/conf/application.yml里面有个adminPasswd密码是明文的
> > 其他地方密码都是加密的,使用时这个密码要一致
> > 在admin的网页上改的密码应该不影响上面的密码
> > 加密密码的方法,在mysql的shell里面执行select password("your password")
> 
> 还是不行，还是显示 auth :admin is failed

解决了吗？

**Comment by simonkuang** [comment]
> > admin/conf/application.yml里面有个adminPasswd密码是明文的
> > 其他地方密码都是加密的,使用时这个密码要一致
> > 在admin的网页上改的密码应该不影响上面的密码
> > 加密密码的方法,在mysql的shell里面执行select password("your password")
> 
> 还是不行，还是显示 auth :admin is failed

后来解决了吗？

**Comment by pawnZzz** [comment]
有解决的吗？

**Comment by pawnZzz** [comment]
> ERROR c.a.otter.canal.admin.handler.CustomExceptionHandler - auth :admin is failed
> java.lang.RuntimeException: auth :admin is failed
> at com.alibaba.otter.canal.admin.controller.PollingConfigController.canalConfigPoll(PollingConfigController.java:51)
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:498)
> 
> 什么原因？
> 
> 感谢！

楼主解决这个问题了吗？

**Comment by fengjiangbo** [comment]
admin/conf/application.yml  和 canal_local.properties(canal.properties) 两边的用户名和密码是对应的
canal:
  adminUser: admin
  adminPasswd: admin
和
canal.admin.user = admin
canal.admin.passwd = 4ACFE3202A5FF5CF467898FC58AAB1D615029441(admin的密文)
这2个密码要维护一致
admin的登录密码是直接存储在mysql数据库中的 和这边的password没有关系
