### ISSUE TITLE
CanalRocketMQProducer.java不支持批量发送MQ，并有空循环的问题

### ISSUE THREAD

**Issue by newlipeng** [alibaba/canal#2850]
## Question

学习canal时，发现CanalRocketMQProducer的sendMessage不支持批量发送message。
CanalRocketMQProducer.java Line 141-148
1，当MQMessageUtils解析data，循环分配PartitionHash时，此时设计为收集到集合中，并批量发送比较合理
2，Line 149行，因为partitionFlatMessage中只有一行数据，此时的partitonFlatMessage不循环比较好。

刚学习JAVA，也不知道是不是看错了。

**Comment by newlipeng** [comment]
自己尝试修改了一下，有兴趣的人批评批评，瞎搞。

             List<FlatMessage> flatMessages = MQMessageUtils.messageConverter(data);
             if (flatMessages != null) {
+                Integer partitionsNum = destination.getPartitionsNum();
+                if (partitionsNum == null) {
+                    partitionsNum = 1;
+                }
+
+                //对message进行分类处理
+                List<Message>[] producerMessages = new ArrayList[partitionsNum];
+                for (int i = 0; i < partitionsNum; i++) {
+                    producerMessages[i] = new ArrayList();
+                }
                 for (FlatMessage flatMessage : flatMessages) {
                     if (destination.getPartitionHash() != null && !destination.getPartitionHash().isEmpty()) {
                         FlatMessage[] partitionFlatMessage = MQMessageUtils.messagePartition(flatMessage,
-                            destination.getPartitionsNum(),
+                            partitionsNum,
                             destination.getPartitionHash());
                         int length = partitionFlatMessage.length;
                         for (int i = 0; i < length; i++) {
@@ -156,9 +168,9 @@ public class CanalRocketMQProducer implements CanalMQProducer {
                                 }
                                 final int index = i;
                                 try {
-                                    Message message = new Message(topicName, JSON.toJSONString(flatMessagePart,
+                                    Message message = new Message(topicName, JSON.toJSONString(flatMessagePart.getData(),
                                         SerializerFeature.WriteMapNullValue).getBytes());
-                                    sendMessage(message, index);
+                                    producerMessages[index].add(message);
                                 } catch (Exception e) {
                                     logger.error("send flat message to hashed partition error", e);
                                     throw e;
@@ -170,19 +182,46 @@ public class CanalRocketMQProducer implements CanalMQProducer {
                             final int partition = destination.getPartition() != null ? destination.getPartition() : 0;
                             if (logger.isDebugEnabled()) {
                                 logger.debug("send message: {} to topic: {} fixed partition: {}",
-                                    JSON.toJSONString(flatMessage, SerializerFeature.WriteMapNullValue),
+                                    JSON.toJSONString(flatMessage.getData(), SerializerFeature.WriteMapNullValue),
                                     topicName,
                                     partition);
                             }
                             Message message = new Message(topicName, JSON.toJSONString(flatMessage,
                                 SerializerFeature.WriteMapNullValue).getBytes());
-                            sendMessage(message, partition);
+                            producerMessages[partition].add(message);
                         } catch (Exception e) {
                             logger.error("send flat message to fixed partition error", e);
                             throw e;
                         }
                     }
                 }
+
+                //获取rocketmq queue list, 分批发送消息，增强对消息的处理能力
+                List<MessageQueue> msgQueues = this.defaultMQProducer.fetchPublishMessageQueues(topicName);
+                for (int i=0; i<partitionsNum; i++) {
+                    final Integer index = i;
+                    MessageQueue msgQ;
+                    final int size = msgQueues.size();
+                    if (index > size) {
+                        msgQ = msgQueues.get(index % size);
+                    } else {
+                        msgQ = msgQueues.get(index);
+                    }
+                    MessageListSplitter splitter = new MessageListSplitter(producerMessages[index]);
+                    while (splitter.hasNext()) {
+                        try {
+                            List<Message>  listItem = splitter.next();
+                            this.defaultMQProducer.send(listItem, msgQ);
+                        } catch (Exception e) {
+                            e.printStackTrace();
+                            //处理error
+                        }
+                    }
+                }
+
+                if (logger.isDebugEnabled()) {
+                    logger.debug("send message to rocket topic: {}", destination.getTopic());
+                }
             }

**Comment by agapple** [comment]
你这版本看的有点老吧，默认已经做了相同分区的message合并，多个分区之间并行提交
