### ISSUE TITLE
一条update语句更新若干条数据时，收到的修改数少于真正更新的数量

### ISSUE THREAD

**Issue by wow786141060** [alibaba/canal#2853]
单机canal，配置直接发送到kafka
用例如下：
1.一条update语句更新100条，kafka永远只接收到重复的28条数据。
2.一条update语句更新2条，kafka永远只接收到重复的1条数据
3.在一个事务中，分别使用两条update语句更新用例2中的2条数据，kafka可以接收到两条

**Comment by wow786141060** [comment]
开启canal的日志后，看到确实是在canal的服务端向kafka的发送过程中就少发了数据

**Comment by Darrenzzy** [comment]
同问，求尽快解决 谢谢

**Comment by ZYZ0001** [comment]
canal可能会将同一时间同一类型的binlog解析成一条, 如果开启了, 看看kafka接收的数据中data是json数组, 会有多条数据....如果不是这个问题就不清楚了

**Comment by agapple** [comment]
LS的判断是对的
