### ISSUE TITLE
如何设置才能同时获得执行的SQL和mysql数据的变化信息。

### ISSUE THREAD

**Issue by chiwanmin** [alibaba/canal#2854]

**Comment by chiwanmin** [comment]
目前mysql的binlog_format = "ROW" ，配置kafka，将数据库数据变更推到kafka中。
kafka中消费的message中只包含data的变更信息，sql为空。
目前业务既需要需要sql又需要data信息。如何处理

**Comment by lujinke** [comment]
正常情况下binlog是不包含原始的sql的，你可以开启binlog_rows_query_log_events=ON，让binlog记录原始的sql语句，然后canal应该可以解析除这个query event

**Comment by chiwanmin** [comment]
谢谢，这么处理了，发现有其他问题，就是所有的Query Event都会接受到，我这边需要根据配置的表去过滤。
