### ISSUE TITLE
用 Docker 安装 Canal Admin ， 如何使用宿主机的mysql  docker 容器

### ISSUE THREAD

**Issue by eey** [alibaba/canal#2855]
## Question
 canal-admin， canal-server 都使用docker 安装，  canal-admin 我想使用另一个 容器的mysql 该如果使用
![image](https://user-images.githubusercontent.com/793242/86347713-43ae5600-bc91-11ea-9a33-70246efaf6e4.png)
canal-admin 默认启动mysql 进程，mysql启动失败  导致canal-admin 也启动失败。 我该如果使用 宿主机的mysql  docker 容器？

**Comment by dingyufei615** [comment]
docker run -it --name canal-admin \
      -e server.port=8089 \
      -e canal.adminUser=admin \
      -e canal.adminPasswd=123456 \
      -e spring.datasource.address=192.168.202.206:3306 \
      -e spring.datasource.database=canal_manager \
      -e spring.datasource.username=** \
      -e spring.datasource.password=** \
      -p 8089:8089 \
      -d canal/canal-admin:v1.1.4

例如mysql在192.168.202.206:3306
提前在mysql建好canal_manager数据库 建表语句文档里有

**Comment by agapple** [comment]
LS正解
