### ISSUE TITLE
清除了日志文件reset master，然后不同步了 

### ISSUE THREAD

**Issue by yang771036958** [alibaba/canal#2860]
## Question

什么原因？

**Comment by Hunter0125** [comment]
在conf/example/mate.dat文件中记录了canal当前同步binlog的文件名称及position；但是当数据库执行reset master之后，binlog会被清空，重新开始记录，但是canal server记录的信息尚未发生变化，所以无法实现自动同步【因为找不到对应的日志文件】。
此时，可以先停止canal服务，然后在mysql通过`show binary logs`查看目前所有的日志文件，然后选定canal需要开始同步的位置，之后手动修改conf/example/meta.dat文件中的journalName和position，然后重启canal server即可实现自动同步，

**Comment by agapple** [comment]
LS正解
