### ISSUE TITLE
-e canal.admin.port=11120 不生效问题

### ISSUE THREAD

**Issue by xinyangbest** [alibaba/canal#2861]
- [x] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment

* canal/canal-server:latest

启动命令

```
docker run -d -it -h 10.216.xx.xxx -e canal.admin.manager=127.0.0.1:8089 -e canal.admin.port=11120 -e canal.port=11121 -e canal.metrics.pull.port=11122 -e canal.admin.user=admin -e canal.admin.passwd=4ACFE3202A5FF5CF467898FC58AAB1D615029441 --name=canal-server  -m 4096m canal/canal-server

```

容器内截图 端口好像变成了11113 请问是怎么回事 而且canal-admin 连接状态为断开

![image](https://user-images.githubusercontent.com/26601064/86775634-1f37ec80-c08a-11ea-83dd-2f1f6bef2c60.png)

**Comment by dingyufei615** [comment]
进到容器内 看-e指定的环境变量是否生效

**Comment by VincentLiSH** [comment]
docker inspect canal-server

**Comment by xinyangbest** [comment]
问题已经解决，需要 canal/canal-server:v1.1.4版本 latest 版本不可以

**Comment by xinyangbest** [comment]
> 进到容器内 看-e指定的环境变量是否生效

是镜像版本问题 v1.1.4 可以  latest 版本不行

**Comment by xinyangbest** [comment]
> docker inspect canal-server

是镜像版本问题 v1.1.4 可以  latest 版本不行

**Comment by cun123** [comment]
> 
> 
> > docker inspect canal-server
> 
> 是镜像版本问题 v1.1.4 可以 latest 版本不行

canal-admin是什么版本的呢？现在一直无法修改canal.admin.port参数
