### ISSUE TITLE
关于meta同步位置的疑问，新建库导入数据，再进行同步

### ISSUE THREAD

**Issue by farsunset** [alibaba/canal#2864]
假如目前停止掉canal-server
1、然后我新建一个数据库，导入了10000条数据
2、修改canal-server的数据源修改为新库
3、 再启动canal-server 
这个时候会不会同步这10000个记录给canal客户端，还是只同步导入之后的变动数据

谢谢

**Comment by farsunset** [comment]
通过自己测试已经得到答案。只会同步导入之后的变动数据
canal-server启动时获取mysql的binlog 的同步position，从这个position之后的变动才会被监听到。
但是切换数据库的话，需要删除meta.log

**Comment by agapple** [comment]
可以指定canal-server到历史时间，回溯binlog
