### ISSUE TITLE
json类型字段bug

### ISSUE THREAD

**Issue by yufeng0528** [alibaba/canal#287]
有个bug在1.0.23下
com.alibaba.otter.canal.parse.exception.CanalParseException: parse row data failed. Caused by: com.alibaba.otter.canal.parse.exception.CanalParseException: parse row data failed. Caused by: java.lang.IllegalArgumentException: illegal json data at com.taobao.tddl.dbsync.binlog.JsonConversion.parse_scalar(JsonConversion.java:150) at com.taobao.tddl.dbsync.binlog.JsonConversion.parse_value(JsonConversion.java:67)

数据库版本 mysql-5.7.11-winx64
数据库结构
CREATE TABLE customer_data (
id bigint(19) unsigned NOT NULL AUTO_INCREMENT,
supplier_id bigint(19) unsigned NOT NULL COMMENT '商户id',
customer_id bigint(19) unsigned NOT NULL,
customer_data json DEFAULT NULL COMMENT '顾客标准属性',
customer_ext_data json DEFAULT NULL COMMENT '顾客扩展属性',
PRIMARY KEY (id),
UNIQUE KEY uk_cust (customer_id)
) ENGINE=InnoDB AUTO_INCREMENT=26036 DEFAULT CHARSET=utf8mb4;

debug后就是149行str_len==0 @agapple

**Comment by agapple** [comment]
给出你有问题的json字符串

**Comment by yufeng0528** [comment]
`{"性别": "男", "手机号": "18606520112", "cardNumber": "", "微信昵称": "Peter"}`
