### ISSUE TITLE
canal 1.1.4版本，关于mysql binlog位置信息

### ISSUE THREAD

**Issue by lanmaodage** [alibaba/canal#2874]
在canal采到kafka的数据中发现有时ts字段有时是一样的，这样没有办法确定数据记录改变的先后顺序了，有没哪个参数开关是可以打印出binlog的位置信息的呢？求大家解答一下，谢谢！

**Comment by agapple** [comment]
MQ本身分区内是有顺序的，如果要记录位点，保持flatMessage=false，并不开启partition模式，这样会把原始的protobuf对象投递出来
