### ISSUE TITLE
canal 1.1.5问题应该还蛮多的

### ISSUE THREAD

**Issue by liuchenbaidu** [alibaba/canal#2875]
## Question

在canal/es7/config/下命名为speech_qa.yml的文件，这个配置就会出错，
同样文件内容，命名为其他例如speech_qa_2.yml都可以。这样的错误！

**Comment by DearZh** [comment]
配置出错，是出什么错？方便的话，可以直接发出来，不然您这边新开一个issue也没有啥效果不是嘛

**Comment by agapple** [comment]
问题请描述清楚
