### ISSUE TITLE
Canal Client 收到的Json数据格式问题

### ISSUE THREAD

**Issue by ShadowsGtt** [alibaba/canal#2876]
在终端Select出来的数据是这样的：
```
id:1
name:张三
other: {"name":"张三\n李四"} 
```
但是在Canal Client打印出来数据是这样的：
```
id:1
name:张三
other: {"name":"张三
李四"} 
```

看样子是other字段丢了一个 反斜杠

**Comment by YiuTerran** [comment]
你这个不是\n直接被解释为换行了么

**Comment by ShadowsGtt** [comment]
> 你这个不是\n直接被解释为换行了么

我认为存储的数据应该是这样：\\n ，所以我们输出到终端就是\n ，但是client拿到的数据是这样：\n，所以打印出来的就是换行，而不是字符 \ 和 字符 n。但是不知道为什么丢了一个\，找不到问题出在哪里

**Comment by agapple** [comment]
你不要用肉眼看，使用程序来解析，你这里明显有\n的字符，打印内容都已经换行了
