### ISSUE TITLE
能发布一个 k8s ，能调度的镜像么 

### ISSUE THREAD

**Issue by hush0** [alibaba/canal#2879]
## Question

官方镜像修改后，本地运行后无法启动实例，放到K8S上调度失败，直接就无法运行

**Comment by agapple** [comment]
可以考虑提交一个PR给我

**Comment by cndarren** [comment]
写了一篇文章，仅供参考，canal 1.1.6版本的：https://www.cnblogs.com/cndarren/p/17100468.html
