### ISSUE TITLE
something goes wrong with channel

### ISSUE THREAD

**Issue by tutulvlv** [alibaba/canal#289]
ERROR c.a.otter.canal.server.netty.handler.SessionHandler - something goes wrong with channel:[id: 0x68949ed6, /10.253.0.5:59418 => /10.124.134.173:11111], exception=java.io.IOException: Connection reset by peer

**Comment by agapple** [comment]
网络重置，客户端增加一下重连机制吧

**Comment by tutulvlv** [comment]
这是服务端的出错异常，客户端没有异常，没有断连，服务端开启HA（default-instance.xml）后就出现了这种情况

**Comment by wangminli** [comment]
我这里是多个客户端连接了服务器报的错，多地监听会有这个问题，只启一个就好了。

**Comment by tutulvlv** [comment]
谢谢大牛们，问题解决了，是zookeeper的问题，重安了一个好了，新手学习，多多包涵

**Comment by jnliao** [comment]
@agapple 我也出现了这种情况，客户端怎么增加重连机制呢？

**Comment by agapple** [comment]
看一下example的client代码
