### ISSUE TITLE
DDL过滤不生效

### ISSUE THREAD

**Issue by LeoLiang666** [alibaba/canal#2890]
## Question

你好，
canal 1.1.5
MySQL 5.7

# binlog filter config
canal.instance.filter.druid.ddl = false
canal.instance.filter.query.dcl = true
canal.instance.filter.query.dml = false
canal.instance.filter.query.ddl = true
canal.instance.filter.table.error = false
canal.instance.filter.rows = false
canal.instance.filter.transaction.entry = true

不能过滤ddl和dcl，请问是否配置有问题？thanks！

**Comment by LeoLiang666** [comment]
使用了 canal-admin

**Comment by LeoLiang666** [comment]
解决了

**Comment by Level1Accelerator** [comment]
> 解决了

请问如何解决的啊

**Comment by hanxuanqing** [comment]
是如何解决的？不使用 canal-admin？
