### ISSUE TITLE
maridb - row模式下，column字段的类型和名称都正确，但是赋值却是错误的

### ISSUE THREAD

**Issue by yzj114477** [alibaba/canal#2898]
这个截图是代码拦截示意
![image](https://user-images.githubusercontent.com/13463298/88364152-b0120600-cdb4-11ea-9d4f-8f11682b0688.png)
实际的dml插入语句是
insert into oc_third_anniversary_enroll (CREATE_TIME, CREATOR, MODIFIER, MODIFY_TIME, COMPANY, NAME, NUMBER, PHONE, PRODUCT_ID, USID) values ('2020-07-15 09:25:05.298', 0, 0, '2020-07-15 09:25:05.298', '测试', '测试', 'THIRD202007150001', '15750787193', 2, 177671)

(大部分时候蛮正常的，就是部分情况我是真看不懂为什么映射会不对)
不知道是什么情况会导致这种字段和赋值对不上的情况，麻烦请帮忙看一下，谢谢
mariadb的版本是 mariadb:10.5.4

**Comment by yzj114477** [comment]
然后我补充下binlog日志里的信息，会发现最后一个字段是 LONGINT 类型，跟上面解析出来的结果是不一致的（上面的截图其实好像是从index7开始就不对了）
### INSERT INTO `xzwpro`.`oc_third_anniversary_enroll`
### SET
###   @1=11 /* LONGINT meta=0 nullable=0 is_null=0 */
###   @2='THIRD202007150001' /* VARSTRING(128) meta=128 nullable=1 is_null=0 */
###   @3='测试' /* VARSTRING(128) meta=128 nullable=1 is_null=0 */
###   @4='15750787193' /* VARSTRING(128) meta=128 nullable=1 is_null=0 */
###   @5='测试' /* VARSTRING(256) meta=256 nullable=1 is_null=0 */
###   @6=2 /* LONGINT meta=0 nullable=1 is_null=0 */
###   @7=177671 /* LONGINT meta=0 nullable=1 is_null=0 */
###   @8='0' /* STRING(4) meta=65028 nullable=0 is_null=0 */
###   @9='N' /* STRING(4) meta=65028 nullable=0 is_null=0 */
###   @10=0 /* LONGINT meta=0 nullable=1 is_null=0 */
###   @11='2020-07-15 09:25:05' /* DATETIME(0) meta=0 nullable=1 is_null=0 */
###   @12='2020-07-15 09:25:05' /* DATETIME(0) meta=0 nullable=1 is_null=0 */
###   @13=0 /* LONGINT meta=0 nullable=1 is_null=0 */
# Number of rows: 1

**Comment by yzj114477** [comment]
后面我咨询了一下，原来是这个表结构中间插入过字段，并且有调整过表结构字段的名字。。。

**Comment by yuanweikang2020** [comment]
可以观察一下DDL语句分析一下；我之前一直遇到这种问题
例如，如果当前内存中已经存在 table_x1表结构，表结构如下：

```sql
CREATE TABLE `table_x1` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT,
    `key1` int(11) NOT NULL COMMENT 'key1',
    `value1` longtext NOT NULL COMMENT 'value1',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
```
这个时候再执行下面建表语句：

```sql
CREATE TABLE IF NOT EXISTS `table_x1` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT,
    `key1` longtext NOT NULL COMMENT 'key1',
    `value1` longtext NOT NULL COMMENT 'value1',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
```

更新了内存中的表结构；但是这个时候实际上MySQL的表结构并没有改变，这个时候如果有DML语句的话就会出现这样的情况；

**Comment by yzj114477** [comment]
谢谢你的回复，我这边后来自己写了一套架构完美的解决了。。。
       使用canal只能满足数据一致性的普通需求，结构一致性很难达成，如果碰到一些异常情况，都需要人工协助和制定标准化，但是在非正式环境执行时，总会有”新手“给你趟雷，所以我自己将这些情况汇总后，读日志，解析，拆包，拆语句，拆结构，完美适配各种场景的自动同步，可变更结构、改表名等特殊场景应用，这样子开发环境上就省心了，然后生产上会规范好添加规定，也不需要停止同步，会自动匹配数据结构，完美一致性，包括新增表、改表名等操作完美复制和保留，就跟 mysql 自带的 binlog自动同步一致
