### ISSUE TITLE
TableMetaTSDB - create table XXX like xxx

### ISSUE THREAD

**Issue by leegaox** [alibaba/canal#2899]
## TableMetaTSDB- create table ...like...建表sql，数据同步有问题。
使用 " create table xxx1 (like xxx)" 创建副本表 同样会出现 内存表结构镜像不一致问题，导致com.alibaba.otter.canal.parse.exception.CanalParseException: parse row data failed.

使用“ create table xxx1 (
  `id` bigint(20) NOT NULL,
...
)” 创建 没有问题。
如何解决该问题？

**Comment by agapple** [comment]
麻烦提供一下复现的过程

**Comment by yuanweikang2020** [comment]
可以观察一下DDL语句分析一下；我之前一直遇到这种问题
例如，如果当前内存中已经存在 table_x1表结构，表结构如下：

```sql
CREATE TABLE `table_x1` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT,
    `key1` longtext NOT NULL COMMENT 'key1',
    `value1` longtext NOT NULL COMMENT 'value1',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
```
这个时候再执行下面建表语句：

```sql
CREATE TABLE IF NOT EXISTS `table_x1` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT,
    `key1` longtext NOT NULL COMMENT 'key1',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
```

更新了内存中的表结构；但是这个时候实际上MySQL的表结构并没有改变，这个时候如果有DML语句的话就会出现这样的错误；

**Comment by agapple** [comment]
升级druid版本为1.2.6后已解决
