### ISSUE TITLE
生产配置咨询

### ISSUE THREAD

**Issue by zqhget1** [alibaba/canal#290]
线上环境，通过canal嵌入式方式使用，现在想将CanalLogPositionManager配置为FailbackLogPositionManager模式，CanalMetaManager配置为PeriodMixedMetaManager，是否存在重复消费问题？比如：PeriodMixedMetaManager客户端消费某条数据后，还未更新cursor如zookeeper中，任务进行重启，客户端将按照zookeeper中cursor进行重复消费。
为了追求一致性，是否将CanalMetaManager配置为ZooKeeperMetaManager更为合适？

**Comment by agapple** [comment]
重复消费这块无法避免，位点重复只是一方面，还有就是batch一批数据的处理，如果进程挂了，下次还是会整个batch进行处理。so.  这样的改造没有太多的意义
