### ISSUE TITLE
canal对接rocketmq集群，数据仅发送到一个broker上的不同分区，其他broker上没有数据

### ISSUE THREAD

**Issue by lijun535535** [alibaba/canal#2904]
## Question

# mq config
**canal.mq.topic=topic-orderpush
canal.mq.partitionsNum=32
canal.mq.partitionHash=.*\\..***

使用的canal对接rocketmq，使用的表名做partitionHash，mq集群是三主三从，但实际发现，消息数距仅发送到其中一个broker上的不同分区，其他broker上没有数据
![image](https://user-images.githubusercontent.com/31472166/88611355-6f1f3780-d0bb-11ea-8c47-099f62309225.png)

**Comment by Garlichead** [comment]
是否zk选举的处理结果就是这样？

**Comment by agapple** [comment]
MQ的配置问题吧，找一下RocketMQ社区问一下吧

**Comment by catalpa-tree** [comment]
@lijun535535 这个问题有解决吗？我们也遇到了

**Comment by authorXiao** [comment]
@lijun535535  这个问题解决没有，我也遇到了

**Comment by MeetMax** [comment]
> 

partitionsNum 需要>= broker-a+broker-b 的 queue数，baoker-a、baoker-b才能均匀分配消息
