### ISSUE TITLE
当库名带点.字段，parse 解析报错 如 demo.02库中的user解析异常

### ISSUE THREAD

**Issue by studyhuang1996** [alibaba/canal#2908]
## Question

ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:example[com.alibaba.otter.canal.parse.exception.CanalParseException: com.alibaba.fastsql.sql.parser.ParserException: error : pos 7, line 1, column 6, token LITERAL_INT
Caused by: com.alibaba.fastsql.sql.parser.ParserException: error : pos 7, line 1, column 6, token LITERAL_INT

**Comment by eskyzdt** [comment]
不要带点. 也不要以数字开头

**Comment by agapple** [comment]
提供一下对应的测试表结构和canal代码版本

**Comment by studyhuang1996** [comment]
> 提供一下对应的测试表结构和canal代码版本
复现了步骤：
当主库的某些数据库名带有.字符。即使表白名单只配置订阅 demo库的数据变化，但是当demo.02库中某些表存在数据变化。就会把此错误。
![image](https://user-images.githubusercontent.com/27665214/90324970-0505fe00-dfa8-11ea-8d7a-21a26af4a36e.png)
当demo.02 库中的某张表数据变更，报错如下
![image](https://user-images.githubusercontent.com/27665214/90324984-531b0180-dfa8-11ea-9593-f58458157c92.png)

目前我们环境是很少存在库名带特殊字符，但是以前历史库名会带有版本号 比如xx-v.1这样的库名。
然后这个问题我这边的解决方式是：
在黑名单的表正则中，直接过滤该库 是可以解决的。
这边有一点疑问，在解析binlog日志的时候，是全文件解析的吗？然后才在sink模块过滤这些表，那么不管我是配置白名单正则过滤还是黑名单过滤，都会报这个异常才会。怎么会是  只配白名单规则订阅某个库报错，配上黑名单过滤demo.02库就没错了。

**Comment by studyhuang1996** [comment]
> 提供一下对应的测试表结构和canal代码版本

这边用的是canal 版本是最新的 1.1.5版本

**Comment by agapple** [comment]
最新代码已修复
