### ISSUE TITLE
单个CanalInstance是否能支持多个clinet，该如何配置？

### ISSUE THREAD

**Issue by zhoujinsong** [alibaba/canal#2910]
当多个下游都需要消费同一个MySQL实例的binlog信息时，如何配置来实现这个需求？
每个下游可能消费进度、filter存在差异

**Comment by Kaiux** [comment]
可以参考：https://github.com/alibaba/canal/wiki/ClientAdapter

> 一份数据可以被多个group同时消费, 多个group之间会是一个并行执行, 一个group内部是一个串行执行多个outerAdapters, 比如例子中logger和hbase

**Comment by agapple** [comment]
LS正解
