### ISSUE TITLE
rowChange.RowDatas为空

### ISSUE THREAD

**Issue by QianYS** [alibaba/canal#2912]
in my test 

rowChange.EventType hasvalue
but rowChange.RowDatas is null

**Comment by QianYS** [comment]
![image](https://user-images.githubusercontent.com/28479614/88993991-f7027d00-d319-11ea-8478-e39e71055604.png)

**Comment by QianYS** [comment]
binlog_format 为ROW时  可以获取到rowChange.RowDatas  但是没有sql
为MIXED时  无法获取到rowChange.RowDatas  但是有sql

**Comment by vidorchan** [comment]
我也是遇到这个问题。Canal1.1.5版本，mysql5.7 row=MIXED模式。但是Canal1.1.5不是支持MIXED吗？你后面怎么解决的？修改mysql的ROW？？
