### ISSUE TITLE
canal-server集群停止一个节点后另外节点从头开始同步的问题

### ISSUE THREAD

**Issue by luger1990** [alibaba/canal#2913]
目前搭建canal集群有两个节点，N个instance。其中一个canal-server节点挂掉后，instance会转移到其他节点继续和mysql进行主从同步。但是原来的canal-server本来同步到【mysql-bin.002374,316785316】这个位置了，但是转移到其他canal-server后又重新从【mysql-bin.002373,375776674】这个位置开始同步。是不是有问题呢？还是我没有配置对。
多些各位了。

**Comment by dingyufei615** [comment]
canal.instance.global.spring.xml = classpath:spring/default-instance.xml
看下是否用的是这个 建议记录binlog信息可以保存在zk中

**Comment by luger1990** [comment]
> canal.instance.global.spring.xml = classpath:spring/default-instance.xml
> 看下是否用的是这个 建议记录binlog信息可以保存在zk中

多谢，我试一试。

**Comment by luger1990** [comment]
已经解决了 解决的方式就是 配置改为如下。
canal.instance.global.spring.xml = classpath:spring/default-instance.xml
