### ISSUE TITLE
怎么在docker中启动canal server

### ISSUE THREAD

**Issue by yujinsong** [alibaba/canal#292]
怎么在docker中启动canal server

**Comment by yujinsong** [comment]
问题解决了

**Comment by wenzj-code** [comment]
run.sh -e canal.instance.master.address=127.0.0.1:3306 \
         -e canal.instance.dbUsername=canal \
         -e canal.instance.dbPassword=canal \
         -e canal.instance.connectionCharset=UTF-8 \
         -e canal.instance.tsdb.enable=true \
         -e canal.instance.gtidon=false \
         -e canal.instance.filter.regex=.*\\..*
		 
		DOCKER_DEPLOY_TYPE=VM
==> INIT /alidata/init/02init-sshd.sh
==> EXIT CODE: 0
==> INIT /alidata/init/fix-hosts.py
==> EXIT CODE: 0
==> INIT DEFAULT
Generating SSH1 RSA host key:                              [  OK  ]
Starting sshd:                                             [  OK  ]
Starting crond:                                            [  OK  ]
==> INIT DONE
==> RUN /home/admin/app.sh
==> START ...
start canal ...
### **su: incorrect password**
有没有遇这个问题呢，密码出错是指什么的密码
