### ISSUE TITLE
Bug report: CanalServerWithEmbedded authentication

### ISSUE THREAD

**Issue by BetaCat0** [alibaba/canal#2920]
https://github.com/alibaba/canal/blob/9f6021cf36f78cc8ac853dcf37a1769f359b868b/server/src/main/java/com/alibaba/otter/canal/server/embedded/CanalServerWithEmbedded.java#L125-L128

This section of codes seems not to work well since client **only** passes the encoded password that is generated from function `SecurityUtil.scrambleGenPass`. I guess the author here may want to leave a raw password for ``canal.password`` and validate somehow like following:

https://github.com/alibaba/canal/blob/9f6021cf36f78cc8ac853dcf37a1769f359b868b/server/src/test/java/com/alibaba/otter/canal/server/SecurityUtilTest.java#L13-L20

However, the auth function did not work correctly as I expected.  I think can make a PR for it if I'm not mistaken :)

**Comment by agapple** [comment]
```
MySQL > select password('admin')

+-------------------------------------------+
| password('admin')                         |
+-------------------------------------------+
| *4ACFE3202A5FF5CF467898FC58AAB1D615029441 |
+-------------------------------------------+
```
