### ISSUE TITLE
master上存在的两个问题，已经修复

### ISSUE THREAD

**Issue by nibaohua** [alibaba/canal#2921]
1、hbase 由于guava 版本问题， 升级hbase版本即可
2、kudu 启动找不到类，仔细看了一下代码，断点调试后发现作者有一个小错误，就是META-INF.canal直接新建的包，不是层级结构，导致没有加载到类 代码中这段 loadFile(extensionClasses, CANAL_DIRECTORY, localClassLoader); 修改方式， 重新创建META-INF，再创建canal， 删除掉原来的META-INF.canal，重新打包就可以了。 后续发现问题再提交吧， 看看有没有机会一起参与这个项目，由于最近在使用canal+kafka+kudu 做订单中心， 就仔细看了一下我们的代码，还是发现有些小问题， master上不应该有这样的错误哦

**Comment by agapple** [comment]
可以考虑提交一个PR给我
