### ISSUE TITLE
[canal.instance.tsdb ] 相关的配置应该写在哪儿？

### ISSUE THREAD

**Issue by happyycm** [alibaba/canal#2923]
看项目示例里，在canal.properties和instance.properties中都有tsdb相关的配置，应该配置到哪里比较合适？
或者说canal.properties里instance相关的配置是不是可以删掉，统一由各instance自己来配置？

**Comment by dingyufei615** [comment]
在instance里配置会覆盖canal.properties里的
优先级是instance.properties > canal.properties

我配置在canal.properties  instace里就没配置了

**Comment by happyycm** [comment]
> 在instance里配置会覆盖canal.properties里的
> 优先级是instance.properties > canal.properties
> 
> 我配置在canal.properties instace里就没配置了

好的，谢谢
