### ISSUE TITLE
配置了subscribe后获取不到ROWDATA数据？

### ISSUE THREAD

**Issue by qingo00o** [alibaba/canal#2924]
> 经过验证，filter过滤掉的库、表信息，rowdata信息收不到了，但是对应的Transaction Begin、Transaction End还是有的。

我也遇到这个问题了，在客户端subscribe中不配置的话就没有问题，配置了之后进行单条数据更新就收不到ROWDATA，只有TRANSACTIONBEGIN和TRANSACTIONEND。我的版本是1.1.3，配置的是指定的几个表，格式为：database.table1,database.table2,database.table3.现在不知道是啥原因

_Originally posted by @qingo00o in https://github.com/alibaba/canal/issues/160#issuecomment-669115333_

**Comment by agapple** [comment]
检查一下subscribe条件，看着应该是数据都被过滤了

**Comment by qingo00o** [comment]
> 检查一下subscribe条件，看着应该是数据都被过滤了

我现在换成1.1.4了，换成1.1.4同样的配置就没问题了😶

**Comment by johnxiaohe** [comment]
是否客户端有覆盖订阅，如果有的话试着去掉客户端覆盖配置的一个\转义符试试。客户端不想覆盖订阅的话subscribe()参数空着就好
https://blog.csdn.net/he1154910941/article/details/108790548
