### ISSUE TITLE
Canal支持读取阿里云数据库PolarDB的binlog吗？

### ISSUE THREAD

**Issue by hezhiqiang** [alibaba/canal#2925]
Canal支持读取阿里云数据库PolarDB 8.0的binlog吗？

**Comment by Garlichead** [comment]
![image](https://user-images.githubusercontent.com/45086633/89591312-7218e580-d87c-11ea-9742-3451358a944b.png)
看了下canal的driver模块
这个模块在canal中主要负责与数据库建立链接并且获得binglog
多半只支持mysql

**Comment by zhuzhan** [comment]
支持的，我们内部在用

**Comment by agapple** [comment]
LS正解
