### ISSUE TITLE
请问把配置canal.instance.global.mode 改为manager需要怎么做？

### ISSUE THREAD

**Issue by ajie425** [alibaba/canal#2932]
现在需要控制二进制日志的开始读取的位置，需要通过instance配置里面的时间戳来控制，但是不知道这个怎么实现CanalConfigClient，请帮帮忙！

**Comment by Garlichead** [comment]
![image](https://user-images.githubusercontent.com/45086633/89696700-9f809480-d94b-11ea-9dad-f50d6562aa59.png)
看到这里是通过mysql语句 show binlog events limit 1 所以这里的bin log的位置应该和mysql配置binlog日志有关

**Comment by agapple** [comment]
查看一下wiki里的admin配置
