### ISSUE TITLE
假设在一种的正常的场景中 canal 停止了 重新启动之后 canal 如何去定位上次停止的时候同步到的binlog位点呢？

### ISSUE THREAD

**Issue by Garlichead** [alibaba/canal#2934]
## Question

假设在一种的正常的场景中 canal 停止了 重新启动之后 canal 如何去定位上次停止的时候同步到的binlog位点呢？ canal定位位点的流程是怎样的呢？

**Comment by dingyufei615** [comment]
默认情况下解析的binlog位置信息保存在文件中
canal.instance.global.spring.xml = classpath:spring/file-instance.xml
HA是保存在zk中 默认1000ms刷新一次
canal.instance.global.spring.xml = classpath:spring/default-instance.xml

**Comment by agapple** [comment]
LS正解
