### ISSUE TITLE
指定binlog起始位置，重启canal设置没有生效

### ISSUE THREAD

**Issue by qinzl1** [alibaba/canal#2937]
canal 1.1.4
mysql RDS

![image](https://user-images.githubusercontent.com/20242930/89749711-7e5ea600-dafb-11ea-8656-9b2e12a267d2.png)

**Comment by dingyufei615** [comment]
binlog的消费记录保存在哪里了？在zookeeper还是文件?

**Comment by qinzl1** [comment]
@dingyufei615 
刚用的canal 不知道存在哪。canal.properties配置了zk，应该是存在zk吧

**Comment by qinzl1** [comment]
@dingyufei615 
查了一下zk
![image](https://user-images.githubusercontent.com/20242930/89751213-bec12280-db01-11ea-8b7f-811acd149a47.png)
里面有记录
这个要怎么修改呢

**Comment by 275975194** [comment]
比如用默认example，目录canal/conf/example里边有个 meta.dat，改变相应的 journalName和position
`oot@57eb59cf6155:/usr/local/canal/conf/example# cat meta.dat
{"clientDatas":[{"clientIdentity":{"clientId":1001,"destination":"example","filter":""},"cursor":{"identity":{"slaveId":-1,"sourceAddress":{"address":"mariadb-test-1.canal","port":3306}},"postion":{"gtid":"","included":false,"journalName":"mysql-bin.000009","position":15154,"serverId":1,"timestamp":1597025212000}}}],"destination":"example"}`

**Comment by qinzl1** [comment]
@275975194 
canal1.1.4版本的，在conf的instance目录先没有 meta.dat文件，至于h2的db文件

**Comment by 275975194** [comment]
> @275975194
> canal1.1.4版本的，在conf的instance目录下没有 meta.dat文件，只有h2的db文件
实例配置文件instance.properties里也可以设置：
# position info
canal.instance.master.address=172.18.0.2:3306
canal.instance.master.journal.name=
canal.instance.master.position=

**Comment by agapple** [comment]
LS正解
