### ISSUE TITLE
Canal整合阿里云RocketMQ报错

### ISSUE THREAD

**Issue by YuKiSuperMan** [alibaba/canal#2943]
## Question

![image](https://user-images.githubusercontent.com/30115071/89879284-48055180-dbf5-11ea-8b26-7e953c0858e9.png)

**Comment by agapple** [comment]
报错很明显了啊，没有topic信息

**Comment by neojayway** [comment]
> ## Question
> ![image](https://user-images.githubusercontent.com/30115071/89879284-48055180-dbf5-11ea-8b26-7e953c0858e9.png)

这个问题解决了吗
