### ISSUE TITLE
instance提示找不到库

### ISSUE THREAD

**Issue by qinzl1** [alibaba/canal#2945]
ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:dev-instance[com.alibaba.otter.canal.parse.exception.CanalParseException: java.io.IOException: ErrorPacket [errorNumber=1049, fieldCount=-1, message=Unknown database 'yxy_third_todayearn', sqlState=42000, sqlStateMarker=#]
 with command: show full tables from `yxy_third_todayEarn` where Table_type = 'BASE TABLE'

**Comment by agapple** [comment]
清空一下tsdb再试试

**Comment by qinzl1** [comment]
@agapple 
我把它提示的这个库创建了，解决的。在测试环境倒是没啥，如果线上这个提示就不太好处理了。
