### ISSUE TITLE
PeriodMixedLogPositionManager获取位置点的问题

### ISSUE THREAD

**Issue by 516669850** [alibaba/canal#2948]
PeriodMixedLogPositionManager使用了MemoryLogPositionManager和ZooKeeperLogPositionManager，每次存储位置点会先存内存再定时刷到ZK，但是获取位置点只到内存获取，请问这样使用ZK的意义是什么呢？一点疑问，希望能够解答，谢谢。
    @Override
    public LogPosition getLatestIndexBy(String destination) {
        LogPosition logPosition = memoryLogPositionManager.getLatestIndexBy(destination);
        if (logPosition == nullPosition) {
            return null;
        } else {
            return logPosition;
        }
    }

**Comment by agapple** [comment]
ZK记录可以在进程重启时恢复状态用
