### ISSUE TITLE
不支持数据库PERSISTENT关键词  需要怎么解决

### ISSUE THREAD

**Issue by liweihao15** [alibaba/canal#2954]
例子    我们项目中有用到这个字段 需要怎么解决 非常感谢
create table example_vc_tbl(
c1 int not null auto_increment primary key,
c2 varchar(70),
vc1 int as (length(c2)) virtual,
DIM_SUM varchar(128) AS (MD5(UPPER(CONCAT(c2, c1)))) PERSISTENT
);

**Comment by DearZh** [comment]
你的这个具体是什么意思？通过canal获取到ddl语句后，执行该语句到其它db库吗？还是什么问题？建议描述清楚一些

**Comment by liweihao15** [comment]
canal的日志里面 会一直报错  不支持PERSISTENT关键词  canal监听到数据变动的时候本地好像会执行建表 但是这个关键词canal识别不了  我们的数据库版本是mariaDB 10.0.24 里面有用到这个字段

**Comment by liweihao15** [comment]
@DearZh

**Comment by agapple** [comment]
@wenshao

**Comment by agapple** [comment]
druid升级为1.2.6已解决
