### ISSUE TITLE
docker 

### ISSUE THREAD

**Issue by githawks** [alibaba/canal#2955]
## Question

docker 启动里面写的啥啊  又是docker pull 又是从git clone  写的乱七八糟 阿里的员工就是这么垃圾的吗

**Comment by githawks** [comment]
一点规范都没有

**Comment by liweihao15** [comment]
路人都看不下去   菜的理直气壮的人都有.....     有些公司都是需要自己git clone 自己编译的    多学习吧 黑子

**Comment by ricohgag** [comment]
canal算不算kpi开源项目，唉。

**Comment by dingyufei615** [comment]
人家提供了两种获取docker image的方式而已，别上来这么说话。
1.直接docker pull 现成的 直接用
2.git上自己拉下来代码 自己编译build

**Comment by agapple** [comment]
LS正解
