### ISSUE TITLE
1.1.4 发送MQ消息消费端消费极其不均匀的问题

### ISSUE THREAD

**Issue by farsunset** [alibaba/canal#2959]
4台服务集群使用同一个groupId。但是由canal发送的消息 总是被其中一台消费，其余3台基本是没有接收到过消息
MQ是用的阿里云服务，在订阅关系里面可以看到4台机器，canal机器配置如下
就是普通的消息，我们是在canal里面配置的MQ发出去的，配置如下见机密配置
消费端的GID和这里canal.mq.producerGroup配置的是同一个值GID_MQ_CANAL
canal.mq.servers = xxxxxxx.cn-xxx.mq-internal.aliyuncs.com:8080
canal.mq.retries = 0
canal.mq.batchSize = 16384
canal.mq.maxRequestSize = 1048576
canal.mq.lingerMs = 100
canal.mq.bufferMemory = 33554432
canal.mq.canalBatchSize = 50
canal.mq.canalGetTimeout = 100
canal.mq.flatMessage = true
canal.mq.compressionType = none
canal.mq.acks = all
canal.mq.properties. =
canal.mq.producerGroup = GID_MQ_CANAL
canal.mq.accessChannel = cloud
canal.aliyun.accessKey = xxxxxxx
canal.aliyun.secretKey = xxxxxxxxx
canal.mq.namespace = MQ_I**_**********************
canal.mq.topic= GID_MQ_CANAL_MESSAGE

**Comment by farsunset** [comment]
没有人遇到过这个问题吗

**Comment by agapple** [comment]
你的MQ消息发送，估计没开启partition模式，查看一下canal.mq.partition配置

**Comment by farsunset** [comment]
> 你的MQ消息发送，估计没开启partition模式，查看一下canal.mq.partition配置
配置了依然无效

阿里云的RocketMq服务 topic下的同一个group有4台机器消费集群

instance.propertios配置如下参数

```
#canal.mq.partition=1
canal.mq.partitionsNum=4
canal.mq.partitionHash=.*\\..*:id
```
但是收到的消息依然是其中一台，剩余3台没有过消息接收
不知道如果配置能够分散到多台机器消费
