### ISSUE TITLE
单Server情况下ClusterCanalConnector在与server断开重连时NullPointException导致restart无法执行问题

### ISSUE THREAD

**Issue by JeffreyQiu** [alibaba/canal#296]
以getWithoutAck方法举例：
```java
while (times < retryTimes) {
    try {
        Message msg = currentConnector.getWithoutAck(batchSize);
        return msg;
    } catch (Throwable t) {
        logger.warn("something goes wrong when getWithoutAck data from server:{}\n{}",
            currentConnector.getAddress(),
            ExceptionUtils.getFullStackTrace(t));
        times++;
        restart();
        logger.info("restart the connector for next round retry.");
    }
}
```
当与server连接断开（网络原因或server被停止）时currentConnector.getWithoutAck抛出异常，进入restart方法，在调用connect方法依然连接失败时，会将currentConnector置为null，超过重试次数后抛出Exception。此时再次尝试调用getWithoutAck方法时，因currentConnector为null，currentConnector.getWithoutAck抛出NullPotionException，然后被catch住，在 logger.warn打印日志的时候使用了currentConnector，又会抛出NullPotionException，从而导致restart方法无法被执行。在server恢复后，由于相同原因，客户端依然无法连接上server。

**Comment by fengye2663** [comment]
1.0.26-SNAPSHOT 版本上，getWithoutAck并没有对这个问题做修改，请问是出于什么考虑？
