### ISSUE TITLE
关于MySQL Instance、Canal Server、Canal Server Instance的理解

### ISSUE THREAD

**Issue by uzdz** [alibaba/canal#2960]
请问，是不是Canal Server会维护一个MySQL的SlaveId，而不是Canal Server Instance维护？

也就是说一个Canal Server里的所有Canal Server Instance都必须绑定不同的MySQL Instance，否则如果多个Canal Server Instance监听同一个MySQL Instance，但是他们只是并行消费的关系，新建立的Instance并不会从头开始消费MySQL的Binlog。

不知道这个理解是否正确？

**Comment by dingyufei615** [comment]
个人理解：
canal server里维护多个instance 每个instance可以是同一个mysql的slave ，因为不同instance 他们的slaveID都是不同的。
你说的并行消费这个应该是不对的，每个slave都会和mysql master保持同步关系。

**Comment by uzdz** [comment]
哦，我理解了，还有一个问题是，是不是默认情况下会从master最后的位置开始读取，而不是从最开始的位置读取？

**Comment by dingyufei615** [comment]
> ，

是的 默认是最新位置开始读取，也可以指定binlog文件 position timestamp的方式读取

#mysql主库链接时起始的binlog文件
canal.instance.master.journal.name=
#mysql主库链接时起始的binlog偏移量
canal.instance.master.position=
#mysql主库链接时起始的binlog的时间戳
canal.instance.master.timestamp=

**Comment by uzdz** [comment]
也就是说如果我的MySQL已经运行一段时间了，这时候启动CanalServerInstance，它并不会拉取之前的修改，只监听最新的修改操作，这么理解对的吧。看源码好像是这么描述的。
