### ISSUE TITLE
一个canal实例支持连接多少个客户端呢

### ISSUE THREAD

**Issue by Panpannn** [alibaba/canal#2961]
我使用canal-client测试，多个client连接到同一个实例上，只有一个能client接受到数据，关闭能接收数据的client后，另外一个client才能正常接收数据，想问是需要哪里配置吗，能不能在一个实例下同时让两个client都接收到数据呢？还是说只能一对一连接？

**Comment by agapple** [comment]
binlog有顺序性要求，只能是一个client消费，如果需要多client消费，可以把binlog消息投递到MQ中
