### ISSUE TITLE
error='Cannot allocate memory' (errno=12)

### ISSUE THREAD

**Issue by caiwenglong** [alibaba/canal#2962]
## Question

在启动canal的时候，查看日志，没有看到canal.log, 就看到一个canal_stdout.log文件，然后看到里面的信息，所是内存分配错误，这个是什么问题呢，用1.1.5和1.1.4两个版本试了一下都是一样的起不来，求各位大佬帮忙看一下是什么原因导致的问题
![image](https://user-images.githubusercontent.com/34529745/90737186-9f47a800-e300-11ea-86e9-00bd7f5fef00.png)

**Comment by agapple** [comment]
检查一下主机内存资源，canal启动有最小的内存要求，startup.sh脚本有指定
