### ISSUE TITLE
请问CREATE TABLE IF NOT EXISTS DDL SQL导致canal内存中的表结构与实际表结构不一致的问题可以怎么解决呢

### ISSUE THREAD

**Issue by yuanweikang2020** [alibaba/canal#2965]
场景：
例如，如果当前内存中已经存在 table_x1表结构，表结构如下：

CREATE TABLE `table_x1` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT,
    `key1` longtext NOT NULL COMMENT 'key1',
    `value1` longtext NOT NULL COMMENT 'value1',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
这个时候再执行下面建表语句：

CREATE TABLE IF NOT EXISTS `table_x1` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT,
    `key1` longtext NOT NULL COMMENT 'key1',
    `value2` longtext NOT NULL COMMENT 'value2',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
本质上这条SQL是执行不成功的，但是canal这个时候会将内存中的表结构更新，同步出错误的数据；

**Comment by yangmingqi218** [comment]
您好，不好意思，我不是来回答您的问题的，我是来请教问题的，您帮忙看下https://github.com/alibaba/canal/issues/2964#issue-682617141这个case的问题，谢谢您Thanks♪(･ω･)ﾉ

**Comment by agapple** [comment]
druid升级为1.2.6已解决，已正确处理create table if not exist
