### ISSUE TITLE
FetcherPerformanceTest无法执行

### ISSUE THREAD

**Issue by simake2017** [alibaba/canal#2972]
## Question

FetcherPerformanceTest 该类 无法执行,提示如下错误
![image](https://user-images.githubusercontent.com/31234273/91031299-f61bed00-e632-11ea-9328-32108a336ee0.png)

**Comment by agapple** [comment]
mysql没有按预期返回包，检查一下网络、不要中间debug

**Comment by jackila** [comment]
当前的test中需要增加decode相关的代码才能执行
 LogDecoder decoder = new LogDecoder(LogEvent.UNKNOWN_EVENT, LogEvent.ENUM_END_EVENT);

 LogContext context = new LogContext();

while(){
LogEvent event = decoder.decode(fetcher, context);
}
