### ISSUE TITLE
1.1.5-alpha-2 生产者获取到的动态topic名称不正确

### ISSUE THREAD

**Issue by yansheng105** [alibaba/canal#2974]
- [x] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment

* canal version: 1.1.5-alpha-2
* mysql version: 5.7

### Issue Description
instance关键配置：
canal.mq.dynamicTopic=demo\\..*

canal server日志：
2020-08-25 09:37:26.602 [kafka-producer-network-thread | producer-1] WARN  org.apache.kafka.clients.NetworkClient - [Producer clientId=producer-1] Error while fetching metadata with correlation id 5468 : {demo_test=INVALID_TOPIC_EXCEPTION}

按照配置的动态topic规则生成的topic为：demo.test ， 而canal server投递的却是demo_test  ，导致消息无法正常投递

**Comment by agapple** [comment]
因为MQ的一些命名规则，统一将点号转化为下划线

**Comment by yansheng105** [comment]
> 因为MQ的一些命名规则，统一将点号转化为下划线

但是代码里面只转换了生产者的部分，应该还需要修改实例配置中的动态topic规则支持才行，现在的动态topic规则还是用的点号，两边topic名称不一致导致消息没法投递了。

**Comment by agapple** [comment]
@yansheng105 考虑提交一个PR给我吧

**Comment by melodicdeath** [comment]
这个问题解决了吗，我下了最新版本还是有这个问题
