### ISSUE TITLE
startup.sh脚本有错误

### ISSUE THREAD

**Issue by showcup** [alibaba/canal#298]
在linux环境中执行启动命令时报下面错误，可以推测startup.sh脚本有错误。
[root@localhost bin]# sh startup.sh
: command not found 
'tartup.sh: line 4: syntax error near unexpected token `in
'tartup.sh: line 4: `case "`uname`" in
[root@localhost bin]#

**Comment by agapple** [comment]
每人的环境不同，尝试调整一下shell脚本，可以提交一个PR给我

**Comment by caojiaqing** [comment]
:set ff=unix

**Comment by tankilo** [comment]
![image](https://user-images.githubusercontent.com/10413284/49629033-67aca580-fa22-11e8-84ff-6c9bbe48efef.png)

*.sh脚本不是unix格式的，是windows的，所以执行上面会出错。
