### ISSUE TITLE
rowChage.getEventType()获取的类型全部是是QUERY,但是rowChage.getSql()获取sql语句都是INSERT或者UPDATE或者DELETE

### ISSUE THREAD

**Issue by mossGKX** [alibaba/canal#2980]
- [ ] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment

* canal version  server ： canal.adapter-1.1.5-SNAPSHOT.tar.gz   
 client：  
 <dependency>
                <groupId>com.alibaba.otter</groupId>
                <artifactId>canal.client</artifactId>
                <version>1.1.4</version>
            </dependency>

* mysql version
5.7.30-log
### Issue Description
rowChage.getEventType()获取的类型全部是是QUERY,但是rowChage.getSql()获取sql语句都是INSERT或者UPDATE或者DELETE

### Steps to reproduce
`RowChange rowChange = RowChange.parseFrom(entry.getStoreValue());
      EventType eventType = rowChange.getEventType();
      System.out.println("sql ："+ rowChange.getSql());
      System.out.println(String.format("================> binlog[%s:%s] , name[%s,%s] , eventType : %s",
          entry.getHeader().getLogfileName(), entry.getHeader().getLogfileOffset(),
          entry.getHeader().getSchemaName(), entry.getHeader().getTableName(),
          eventType));
        for (RowData rowData : rowChange.getRowDatasList()) {
          if (eventType == EventType.DELETE) {
            printColumns(rowData.getBeforeColumnsList());
          } else if (eventType == EventType.INSERT) {
            printColumns(rowData.getAfterColumnsList());
          } else {
            System.out.println("-------> before");
            printColumns(rowData.getBeforeColumnsList());
            System.out.println("-------> after");
            printColumns(rowData.getAfterColumnsList());
          }
      }
`
### Actual behaviour

If there is an exception, please attach the exception trace:

mysqld.cnf 配置如下：
symbolic-links = 0
server-id = 1
log-bin = /var/lib/mysql/mysql-bin
binlog_format = ROW
binlog-rows-query-log-events = true

```
Just put your stack trace here!
![image](https://user-images.githubusercontent.com/9739484/91288090-272b2780-e7c3-11ea-83a9-55e9aca4d633.png)

```

请帮忙解答下？ 谢谢！!!

**Comment by ruanjl** [comment]
我也遇到了这个问题

**Comment by jxguosuspectx** [comment]
我也遇到了这个问题，你解决了吗？

**Comment by Yelloooooow** [comment]
我也遇到了这个问题

**Comment by agapple** [comment]
这个是mysql 5.7的rows query，针对每个DML既有row格式的binlog，也有statement格式的sql文本，可以通过canal.instance.filter.query.dml=true来关闭

**Comment by tiai-wei** [comment]
把mysql   ini配置文件  中的 binlog-format 改为 STATEMENT 就可以了
