### ISSUE TITLE
partitionsNum 和 partitionHash 无作用问题

### ISSUE THREAD

**Issue by farsunset** [alibaba/canal#2981]
阿里云的RocketMq服务 topic下的同一个group有4台机器消费集群

instance.propertios配置如下参数

```
#canal.mq.partition=1
canal.mq.partitionsNum=4
canal.mq.partitionHash=.*\\..*:id
```
但是收到的消息依然是其中一台，剩余3台没有过消息接收
如何配置才能够分散到多台机器消费呢

**Comment by farsunset** [comment]
issues里面我搜到了不下5个人提出同样的问题，从去年开始到现在，没有一个确切的答复和解决方案，果真又是KPI开源项目?

**Comment by agapple** [comment]
最新代码已修复

**Comment by farsunset** [comment]
> 最新代码已修复

是1.1.5版本吗
