### ISSUE TITLE
create table isDdl is false

### ISSUE THREAD

**Issue by ZhouYoung** [alibaba/canal#2985]
{"data":null,"database":"canal_test","es":1598515943000,"id":10,"isDdl":false,"mysqlType":null,"old":null,"pkNames":null,"sql":"/* ApplicationName=DataGrip 2019.3.1 */ create table canal_test2\n(\n\tid int auto_increment,\n\tconstraint canal_test2_pk\n\t\tprimary key (id)\n)","sqlType":null,"table":"canal_test2","ts":1598515925653,"type":"CREATE"}

create table isDdl is false,理论上不应该是true 么。请问这个是需要检查哪些配置项？

**Comment by ZhouYoung** [comment]
server 降级到 canal.deployer-1.1.4，问题没有在线。是canal.deployer-1.1.5-SNAPSHOT_2的bug?

**Comment by q2515045** [comment]
我也遇到这个问题了，问题我在1.1.5版本加了一些功能。。

**Comment by agapple** [comment]
1.1.5正式包已解决
