### ISSUE TITLE
FlatMessage 动态topic分区不会生效及分区产生垃圾null数据 1.1.5-SNAPSHOT

### ISSUE THREAD

**Issue by panyujiang** [alibaba/canal#2990]
- [ ] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment

* canal version
* mysql version

### Issue Description

![image](https://user-images.githubusercontent.com/45383131/91532256-a09c5480-e940-11ea-838c-2119031d7f55.png)

### Actual behaviour

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by agapple** [comment]
最新代码已经修复
