### ISSUE TITLE
canal内嵌的方式订阅Mariadb需要和mysql不同的设置吗？

### ISSUE THREAD

**Issue by CyanBP** [alibaba/canal#2991]
## Question

我用canal内嵌的方式实现了对mysql的配置，但是换为对mariadb10的订阅就订阅不了，请问需要额外的设置吗？

**Comment by agapple** [comment]
没有啥特殊的逻辑，主要mariadb有特定的binlog类型

**Comment by zender-projects** [comment]
请问，有代码示例吗
