### ISSUE TITLE
关于client的冷备

### ISSUE THREAD

**Issue by beautifulSoup** [alibaba/canal#3000]
## Question
想咨询下client的冷备是如何实现的，Sever不限制多client连接吗，client只能通过zk来实现冷备吗？

**Comment by wingerx** [comment]
目前canal 还不支持多client 同时连接一个Server进行数据获取. 
Client 冷备通过抢占注册zk 临时节点来实现的，当有任一Client id (default 1001)启动被注册成临时节点后，其他相同的client启动会被hold ，并一直监测zk 的临时节点的状态。
