### ISSUE TITLE
MQ为阿里云Rocket MQ的时候partitionsNum 和 partitionHash无效的超级BUG

### ISSUE THREAD

**Issue by farsunset** [alibaba/canal#3001]
去年开始issues里面就有很多人提出这个问题，但是依然无任何回复解决。

阿里云的RocketMq服务 topic下的同一个group有4台机器消费集群

instance.propertios配置如下参数

#canal.mq.partition=1
canal.mq.partitionsNum=4
canal.mq.partitionHash=.*\\..*:id
但是收到的消息依然是其中一台，剩余3台没有过消息接收
如何配置才能够分散到多台机器消费呢

**Comment by cddon** [comment]
+1

**Comment by agapple** [comment]
最新代码已经修复
