### ISSUE TITLE
从mysql的从库中同步数据该怎么解析？

### ISSUE THREAD

**Issue by hrdxwandg** [alibaba/canal#302]
手上有两台mysql，一台作为master，一台作为slave。想把canal接到slave上。但是slave机器为了和master机器同步，产生的是[hostname]-relay-bin命名的log。这种情况canal该如何和slave机器对接呢。官方文档中只有对接mysql-bin这种命名的方式。有配置的地方可以自己调整么？

**Comment by Sunkiss007** [comment]
看看下面这段话对你有没有帮助。
Slave的配置与master类似，你同样需要重启slave的MySQL。如下：
log_bin           = mysql-bin
server_id         = 2
relay_log         = mysql-relay-bin
log_slave_updates = 1
read_only         = 1
server_id是必须的，而且唯一。slave没有必要开启二进制日志，但是在一些情况下，必须设置，例如，如果slave为其它slave的master，必须设置bin_log。在这里，我们开启了二进制日志，而且显示的命名(默认名称为hostname，但是，如果hostname改变则会出现问题)。
relay_log配置中继日志，log_slave_updates表示slave将复制事件写进自己的二进制日志(后面会看到它的用处)。
有些人开启了slave的二进制日志，却没有设置log_slave_updates，然后查看slave的数据是否改变，这是一种错误的配置。所以，尽量使用read_only，它防止改变数据(除了特殊的线程)。但是，read_only并是很实用，特别是那些需要在slave上创建表的应用。

**Comment by phpwei** [comment]
canal 是模拟MySQL的主从  你从slave 中同步  ，slave 相对于canal 来说就是master 解析slave中的二进制文件。

**Comment by hrdxwandg** [comment]
多谢大家，已搞定！

**Comment by zaccheus** [comment]
请问是怎么搞定的？
