### ISSUE TITLE
admin模式下的server高可用

### ISSUE THREAD

**Issue by Level1Accelerator** [alibaba/canal#3033]
## Question
server local启动之后，测试往一个表中添加一条记录，会往kafka里发多条消息(与启动的server数目一样)，所以搞不清是哪儿不对。我觉得ha模式下不管启动多少server，如果只有一个binlog发生变化，应该就一条消息啊。好像单独起的server一样，并没有达到ha，但是配置文件里配了zk的地址啊。哪位大佬帮忙解答下

**Comment by dingyufei615** [comment]
集群和instance的配置贴下～

**Comment by Level1Accelerator** [comment]
> 集群和instance的配置贴下～
已经知道问题了，是admin中的集群管理，主配置中没加canal.zkServers。server中的配置加这个没用

**Comment by Level1Accelerator** [comment]
> 集群和instance的配置贴下～

感谢
