### ISSUE TITLE
canal+mysql5.5.35报错：can't find start position

### ISSUE THREAD

**Issue by zhangbug** [alibaba/canal#305]
pid:1 nid:2 exception:canal:CTSDB-CANAL-master:com.alibaba.otter.canal.parse.exception.CanalParseException: can't find start position for CTSDB-CANAL-master

目标数据库是mysql-community-server-5.7.18-1
正式业务环境的数据库是mysql-5.5.35

之前在测试环境源和目的都是mysql-community-server-5.7.18-1时，成功，换到正式业务环境的mysql5.5时报错。

canal.deployer-1.0.24
node.deployer-4.2.14
manager.deployer-4.2.14
zookeeper-3.4.10
aria2-1.19.0

**Comment by zjjott** [comment]
+1

**Comment by agapple** [comment]
can't find start position for CTSDB-CANAL-master，清空一下位点或者设置一个存在的位点

**Comment by linyongfu2013** [comment]
> can't find start position for CTSDB-CANAL-master，清空一下位点或者设置一个存在的位点

怎么清空或设置呢？
