### ISSUE TITLE
计算环形队列计算序号值：sequcnce % indexMask; 这里为什么是于运算

### ISSUE THREAD

**Issue by liuyao37511** [alibaba/canal#3059]
https://github.com/alibaba/canal/blob/362974b1c29b27639fe5bf06105180c9972ceb72/store/src/main/java/com/alibaba/otter/canal/store/memory/MemoryEventStoreWithBuffer.java#L582

**Comment by wingerx** [comment]
是对 "当**索引值**(sequence)和**初始值**(indexMask)相同时的临界情况处理“，**初始值**设定为`bufferSize - 1`
以bufferSize默认16 * 1024 为例，由于indexMask 初始化为 bufferSize - 1，即为 16383，所以当sequence 为`16383`时，应该是使用的`16383`这个位置，而非其他值。(若使用‘%’，这个位置就变成了`0`)

**Comment by liuyao37511** [comment]
可以可以

**Comment by liuyao37511** [comment]
可以可以，因为之前 bufferSize 没有取 2的次幂，就会有问题
