### ISSUE TITLE
怎么解析date类型

### ISSUE THREAD

**Issue by mi9944** [alibaba/canal#306]
怎么解析date类型

**Comment by luyee** [comment]
client 都是string了，只能自己转java  type？

**Comment by agapple** [comment]
是的，mysql的时间类型范围会比java Date对象定义的要大，所以用了string的泛类型

**Comment by alswl** [comment]
Canal 有提供 JDBC 多种类型通用的转换函数么？

**Comment by luyee** [comment]
没有吧， jdbc的化， 可以看看otter项目里的  com.alibaba.otter.node.etl.common.db.utils.SqlUtils.java
