### ISSUE TITLE
client的例子中，取到的ddl语句sql为什么是乱码

### ISSUE THREAD

**Issue by thl1207** [alibaba/canal#307]
看了下底层的实现是先回转成utf-8编码的，但是取出来的还是乱码

**Comment by awnuxkjy** [comment]
那是你mysql客户端 编码不是utf8造成的。

**Comment by dlnufox** [comment]
你这个问题解决了吗？是什么原因？

我现在也遇到类似的问题
https://github.com/alibaba/canal/issues/610
