### ISSUE TITLE
canal-server容器无法运行

### ISSUE THREAD

**Issue by yinzwii** [alibaba/canal#3075]
## Question

运行环境：
CentOS Linux release 7.7.1908 (Core)  
1核2G

命令：
docker run -d -it -h 172.31.198.157 -e canal.auto.scan=false -e canal.destinations=test -e canal.instance.master.address=127.0.0.1:3306 -e canal.instance.dbUsername=canal -e canal.instance.dbPassword=canal -e canal.instance.connectionCharset=UTF-8 -e canal.instance.tsdb.enable=true -e canal.instance.gtidon=false -e canal.instance.master.journal.name=mysql-bin.000001 -e canal.instance.master.position=4 -e canal.instance.mysql.slaveId=11 -e canal.instance.parser.parallel=false --name=canal-server --net=host -m 512m canal/canal-server:v1.1.4

运行日志：
DOCKER_DEPLOY_TYPE=VM
==> INIT /alidata/init/02init-sshd.sh
==> EXIT CODE: 0
==> INIT /alidata/init/fix-hosts.py
==> EXIT CODE: 0
==> INIT DEFAULT
Generating SSH1 RSA host key:                              [  OK  ]
Starting sshd:                                             [  OK  ]
Starting crond:                                            [  OK  ]
==> INIT DONE
==> RUN /home/admin/app.sh
==> START ...
start canal ...

（然后就没了）

查看并未运行，多次重启结果一致

**Comment by Lordeath** [comment]
我记得他这边提供的image是给Intel的处理器的用的，arm核应该要重新打
随口一说，不一定对

**Comment by agapple** [comment]
登录docker容器，检查一下日志
