### ISSUE TITLE
canal-admin 8089端口 运行一段时间后自动关闭

### ISSUE THREAD

**Issue by mahb2018** [alibaba/canal#3085]
docker安装的canal-admin，容器运行一段时间后 8089端口会自动关闭，11110和11112端口正常 ？

**Comment by mahb2018** [comment]
Oct 13 16:27:48 VM-14-168-centos kernel: java invoked oom-killer: gfp_mask=0x50, order=0, oom_score_adj=0
Oct 13 16:27:48 VM-14-168-centos kernel: java cpuset=9f46c2ad1873f94b674d40cc90937f4833766c8e09f9ab522e15a2151ef91cb2 mems_allowed=0
Oct 13 16:27:48 VM-14-168-centos kernel: CPU: 1 PID: 31745 Comm: java Kdump: loaded Tainted: G               ------------ T 3.10.0-1127.13.1.el7.x86_64 #1
Oct 13 16:27:48 VM-14-168-centos kernel: Hardware name: Smdbmds KVM, BIOS seabios-1.9.1-qemu-project.org 04/01/2014
Oct 13 16:27:48 VM-14-168-centos kernel: Call Trace:
Oct 13 16:27:48 VM-14-168-centos kernel: [<ffffffffb477ffa5>] dump_stack+0x19/0x1b
Oct 13 16:27:48 VM-14-168-centos kernel: [<ffffffffb477a8c3>] dump_header+0x90/0x229
Oct 13 16:27:48 VM-14-168-centos kernel: [<ffffffffb429c508>] ? ep_poll_callback+0xf8/0x220
Oct 13 16:27:48 VM-14-168-centos kernel: [<ffffffffb41c24ce>] oom_kill_process+0x25e/0x3f0
Oct 13 16:27:48 VM-14-168-centos kernel: [<ffffffffb4133a01>] ? cpuset_mems_allowed_intersects+0x21/0x30
Oct 13 16:27:48 VM-14-168-centos kernel: [<ffffffffb4240c06>] mem_cgroup_oom_synchronize+0x546/0x570
Oct 13 16:27:48 VM-14-168-centos kernel: [<ffffffffb4240080>] ? mem_cgroup_charge_common+0xc0/0xc0
Oct 13 16:27:48 VM-14-168-centos kernel: [<ffffffffb41c2d74>] pagefault_out_of_memory+0x14/0x90
Oct 13 16:27:48 VM-14-168-centos kernel: [<ffffffffb4778dd3>] mm_fault_error+0x6a/0x157
Oct 13 16:27:48 VM-14-168-centos kernel: [<ffffffffb478d8d1>] __do_page_fault+0x491/0x500
Oct 13 16:27:48 VM-14-168-centos kernel: [<ffffffffb478da26>] trace_do_page_fault+0x56/0x150
Oct 13 16:27:48 VM-14-168-centos kernel: [<ffffffffb478cfa2>] do_async_page_fault+0x22/0xf0
Oct 13 16:27:48 VM-14-168-centos kernel: [<ffffffffb47897a8>] async_page_fault+0x28/0x30
Oct 13 16:27:48 VM-14-168-centos kernel: Task in /docker/9f46c2ad1873f94b674d40cc90937f4833766c8e09f9ab522e15a2151ef91cb2 killed as a result of limit of /docker/9f46c2ad1873f94b674d40cc90937f4833766c8e09f9ab522e15a2151ef91cb2
Oct 13 16:27:48 VM-14-168-centos kernel: memory: usage 1048576kB, limit 1048576kB, failcnt 12363
Oct 13 16:27:48 VM-14-168-centos kernel: memory+swap: usage 1048576kB, limit 2097152kB, failcnt 0
Oct 13 16:27:48 VM-14-168-centos kernel: kmem: usage 0kB, limit 9007199254740988kB, failcnt 0
Oct 13 16:27:48 VM-14-168-centos kernel: Memory cgroup stats for /docker/9f46c2ad1873f94b674d40cc90937f4833766c8e09f9ab522e15a2151ef91cb2: cache:1316KB rss:1047260KB rss_huge:935936KB mapped_file:0KB swap:0KB inactive_anon:0KB active_anon:1047260KB inactive_file:660KB active_file:656KB unevictable:0KB
Oct 13 16:27:48 VM-14-168-centos kernel: [ pid ]   uid  tgid total_vm      rss nr_ptes swapents oom_score_adj name
Oct 13 16:27:48 VM-14-168-centos kernel: [20879]     0 20879     3221      404      10        0             0 app.sh
Oct 13 16:27:48 VM-14-168-centos kernel: [20917]     0 20917    16585      302      34        0             0 sshd
Oct 13 16:27:48 VM-14-168-centos kernel: [20935]     0 20935     5382      315      15        0             0 crond
Oct 13 16:27:48 VM-14-168-centos kernel: [21000]     0 21000     3221      396      11        0             0 mysqld_safe
Oct 13 16:27:48 VM-14-168-centos kernel: [21102]   498 21102   127208    11671      66        0             0 mysqld
Oct 13 16:27:48 VM-14-168-centos kernel: [21217]     0 21217     1413      147       9        0             0 tail
Oct 13 16:27:48 VM-14-168-centos kernel: [21218]     0 21218     1413      147       8        0             0 tail
Oct 13 16:27:48 VM-14-168-centos kernel: [22849]     0 22849     3255      476      11        0             0 bash
Oct 13 16:27:48 VM-14-168-centos kernel: [31683]     0 31683  2246718   252853     636        0             0 java
Oct 13 16:27:48 VM-14-168-centos kernel: [  922]     0   922     3255      478      11        0             0 bash
Oct 13 16:27:48 VM-14-168-centos kernel: Memory cgroup out of memory: Kill process 6396 (java) score 966 or sacrifice child
Oct 13 16:27:48 VM-14-168-centos kernel: Killed process 31683 (java), UID 0, total-vm:8986872kB, anon-rss:997792kB, file-rss:13620kB, shmem-rss:0kB

**Comment by mahb2018** [comment]
需要调大jvm的内存

**Comment by hfpf** [comment]
你是怎么排查出来的？

> 需要调大jvm的内存
