### ISSUE TITLE
canal同步binlog的时候blob类型存储字符串乱码问题

### ISSUE THREAD

**Issue by liqiongfan** [alibaba/canal#3095]
- [1 ] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [ 1] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment

* canal version
   1.1.14
* mysql version
   5.7.28-0ubuntu0.16.04.2-log

### Issue Description
canal同步binlog类型的字符串数据时候，客户端收到的数据是乱码的

### Steps to reproduce

复原的步骤为：

`create table test_blog ( id int not null primary key auto_increment, detail blob not null );`

`insert into test_blog (detail) values("测试");`

此时同步这条数据客户端收到的就是乱码。存储上而言，blob的数据是二进制的，如果存储ascii直接储存，如果是汉字则按照字节存储，所以这里获取出来也不应该乱码。并且无法完成从 byte 到 string的转换。

### Expected behaviour

   期待得到的数据是 “测试” 而非乱码的数据

### Actual behaviour
   乱码数据

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by wingerx** [comment]
可以尝试设置数据库的字符编码和表的字符编码均为utf8

**Comment by java2python** [comment]
不管用

**Comment by lzq1126** [comment]
blob 类型的数据是会出现中文乱码这个问题的。

**Comment by agapple** [comment]
column.getValue().getBytes("ISO-8859-1")，按这个读取为bytes，然后再转成你自己的GBK或者UTF8
