### ISSUE TITLE
数据更新时canal deployer写入到kafka中的json消息中，并没有old字段所对应的值

### ISSUE THREAD

**Issue by DearZh** [alibaba/canal#3096]
- [ √] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [ √] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment
* canal version
canal.deployer-1.1.5-SNAPSHOT.tar.gz
canal.adapter-1.1.5-SNAPSHOT.tar.gz
* mysql version
mysql版本：5.7.29-log

### Issue Description
本人所使用的方式是，采用canal deployer监控对应的表数据，将其对应的数据变更输出到Kafka中，然后使用canal client-adapter来接收kafka的消息，从而使对应的表更消息同步到对应的目标中；
但目前发现一个问题是，当我更新一个表数据时，我的ES适配器和rdb适配器，并没有同步我所修改的源数据；

以Rdb适配器下的RdbSyncService.java代码为例，此处只是copy出对应的代码片段：
```
  private void update(BatchExecutor batchExecutor, MappingConfig config, SingleDml dml) throws SQLException {
        Map<String, Object> data = dml.getData();
        if (data == null || data.isEmpty()) {
            return;
        }
        //可以看到，此处通过dml对象获取old数据，如果old数据为空，则不再执行update的业务逻辑
        Map<String, Object> old = dml.getOld();
        if (old == null || old.isEmpty()) {
            return;
        }
}
```
根据上述代码可知，dml下的old字段表示表字段更新前的内容，所以，如果无法获取到对应的old数据，则无法接着执行后续的业务逻辑（此处不仅仅是个判断，后续的业务中的确大量有使用该old的数据）；

所以我试图通过找寻kakfa中的原数据来获取信息，经过我的测试，验证路径如下

### Steps to reproduce
我当前所监控的是一个cls_lian_v1_article_arnold的表，当前该表所设置的主表字段只有一个，即 id字段；
1、当我修改了对应的title字段数据后，此时查看kafka中的json内容如下:
```
{
  "data": [
    {
      "title": "微光股份：目前公司配套冷链行业销售占比总销售70%以上.你"
    }
  ],
  "database": "gangtise_db",
  "es": 1603097613000,
  "id": 5,
  "isDdl": false,
  "mysqlType": {
    "title": "varchar(4000)"
  },
  "old": null,
  "pkNames": null,
  "sql": "",
  "sqlType": {
    "title": 12
  },
  "table": "cls_lian_v1_article_arnold",
  "ts": 1603097613323,
  "type": "UPDATE"
}
```
上述kafka的消息中，old字段所对应的结果为 null；
2、此时当我不再修改对应的title字段，而是直接修改对应的 id字段时，对应的kafka消息内容如下：
```
{
  "data": [
    {
      "id": "5418191"
    }
  ],
  "database": "gangtise_db",
  "es": 1603097660000,
  "id": 13,
  "isDdl": false,
  "mysqlType": {
    "id": "int(11)"
  },
  "old": [
    {
      "id": "541819"
    }
  ],
  "pkNames": [
    "id"
  ],
  "sql": "",
  "sqlType": {
    "id": 4
  },
  "table": "cls_lian_v1_article_arnold",
  "ts": 1603097660915,
  "type": "UPDATE"
}
```
可以看到，此时所对应的old字段对应的内容为id变更前的值，这是正确的，并且此时我所对应的canal client-adapter程序的确将所对应的id变更，实时的同步到我的目标库中了。

难道问题就是，当表做更新时，只针对主键表进行更新时才能获取到对应的old数据吗吗？？

3、此时，直接更新对应的id字段和title字段
```
{
  "data": [
    {
      "id": "541819",
      "title": "微光股份：目前公司配套冷链行业销售占比总销售70%以上.你323"
    }
  ],
  "database": "gangtise_db",
  "es": 1603097702000,
  "id": 19,
  "isDdl": false,
  "mysqlType": {
    "id": "int(11)",
    "title": "varchar(4000)"
  },
  "old": [
    {
      "id": "5418191"
    }
  ],
  "pkNames": [
    "id"
  ],
  "sql": "",
  "sqlType": {
    "id": 4,
    "title": 12
  },
  "table": "cls_lian_v1_article_arnold",
  "ts": 1603097702415,
  "type": "UPDATE"
}
```
此时old中还是只有针对id的变更，在对应的data中存在针对id和title的变更后的信息，但是此时client-adapter同步到目标库后，还是只同步了id字段对应的内容，并没有同步title内容到目标库中。（当然，此处的client-adapter的代码很好处理，我可以直接修改代码，来适配这种没有连带修改title字段的情况，但目前我还没有下手去更改这块代码，所以我只是先把这种现象和问题先描述给你们，另外，每次做update修改数据时，都需要连带修改 id才能获取到old数据，这本身应该就已经是一个不太合理的现象。）

### Expected behaviour
如上所述，预期的行为则时，当我进行update表的操作后，对应的kafka中old字段应该是有内容的。

### Actual behaviour
如上所述，结果则是，当我进行update表的操作后，对应的kafka中old字段是没有内容的，由于kafka中所获取到的解析后的数据源就有问题，所以这将导致客户端client-adapter是无法针对该情况做任何更新处理的。

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by SeekWinds** [comment]
你Mysql的binlog_format设置的是什么格式

**Comment by DearZh** [comment]
> 你Mysql的binlog_format设置的是什么格式

你们就没有出现类似的问题吗？我尝试重新下载了一个新的canal部署包，重新部署验证，还是一样的问题，所以如果你们使用canal的应用包没有类似问题的话，那大概率是我的mysql配置问题了？所以我打算今天重新部署一套测试用mysql，重新验证下这个问题

**Comment by DearZh** [comment]
> 你Mysql的binlog_format设置的是什么格式

重新部署了测试用mysql后，大概率是已经验证到问题的所在了，的确还是 binlog_row_image 的配置问题，针对不同的 binlog_row_image 配置，mysql中所记录的binlog的数据也是不同的，最终canal deployer推送到的kafka消息也是不同的，配置为FULL目前的确可以解决canal的问题 ，我之前配置存在问题是直接使用 set binlog_row_image ='FULL'; 的方式进行配置，这样修改只是修改当前一次connection会话才有效果，所以永久生效的测试方式直接更改my.cnf的配置即可，目前验证下来，推送kafka是已经得到我想要的结果了。感谢你

**Comment by DearZh** [comment]
问题已经解决了，感谢

**Comment by DearZh** [comment]
有出现同等问题的朋友，可以参考该链接：https://www.cnblogs.com/zh94/p/13995748.html

**Comment by ytrlmy521** [comment]
不知为何我返回的data是为空呢？
`{
    "data":null,
    "database":"cms-manage",
    "es":1632746791000,
    "id":2,
    "isDdl":false,
    "mysqlType":null,
    "old":null,
    "pkNames":null,
    "sql":"INSERT INTO `tb_commodity_info` (`id`, `commodity_name`, `commodity_price`, `number`, `description`)\nVALUES\n\t('3e71a81fd80711eaaed600163e04445', '44444rr5', '3.99', 3, '又大又香的叉烧包，老人小孩都喜欢')",
    "sqlType":null,
    "table":"tb_commodity_info",
    "ts":1632746792169,
    "type":"INSERT"
}`

**Comment by ytrlmy521** [comment]
`{
    "data":null,
    "database":"cms-manage",
    "es":1632746791000,
    "id":2,
    "isDdl":false,
    "mysqlType":null,
    "old":null,
    "pkNames":null,
    "sql":"INSERT INTO `tb_commodity_info` (`id`, `commodity_name`, `commodity_price`, `number`, `description`)\nVALUES\n\t('3e71a81fd80711eaaed600163e04445', '44444rr5', '3.99', 3, '又大又香的叉烧包，老人小孩都喜欢')",
    "sqlType":null,
    "table":"tb_commodity_info",
    "ts":1632746792169,
    "type":"INSERT"
}`

**Comment by WorkJun** [comment]
binlog_format ROW
binlog_row_image FULL

**Comment by WorkJun** [comment]
binlog_format ROW
binlog_row_image FULL

**Comment by WorkJun** [comment]
binlog_format ROW
binlog_row_image FULL

设置如上  ，当字段内容为null时，后修改为Y之后，canal的old的字段并不会监听到由null变为Y的信息，有知道这种情况的吗
