### ISSUE TITLE
canal同步的时候，有些binlog没有同步过来

### ISSUE THREAD

**Issue by dnfhujun** [alibaba/canal#310]
我使用的集群模式，同步一个数据库的数据，有更新的binlog同志同步过来，但是我自己修改数据库的数据，确没有同步过来，不知道啥情况~

**Comment by agapple** [comment]
关注一下你的操作binlog是否有生成

**Comment by dnfhujun** [comment]
嗯，是我的问题，同步的位点太前了，一直以为没有同步过来，非常感谢！
