### ISSUE TITLE
client能否支持geometry类型

### ISSUE THREAD

**Issue by RingTam** [alibaba/canal#3101]
client能否支持geometry类型

**Comment by RingTam** [comment]
client能否支持mysql geometry类型，解释后乱码

**Comment by zxpping** [comment]
同问

**Comment by agapple** [comment]
支持的，按照bytes类型来解析

**Comment by clip-tail** [comment]
> 
> 
> 支持的，按照bytes类型来解析

我的mysql版本是5.7，字符集是utf-8，但是canal客户端获取的geo类型字段还是乱码，使用column.getValue().getBytes()获取byte数组，再用new String(bytes)处理成字符串，还是乱码，这是怎么回事

**Comment by clip-tail** [comment]
能说一下是怎么处理乱码的的

**Comment by clip-tail** [comment]
能说一下是怎么处理乱码的么

**Comment by zxpping** [comment]
确实可以，不过转byte[] 的时候需要指定下字符集  value.getBytes(Charsets.ISO_8859_1)

**Comment by zxpping** [comment]
> 能说一下是怎么处理乱码的么

value.getBytes(Charsets.ISO_8859_1)
