### ISSUE TITLE
send MQ性能瓶颈，为什么每处理完一个批次数据，都必须做同步 canal ack 操作？

### ISSUE THREAD

**Issue by roamerway** [alibaba/canal#3106]
- [x] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment

* canal version 1.1.4

### Issue Description

本人在做canal性能优化的过程中发现，在其他条件不变的前提下，仅将CanalKafkaProducer::send()方法最后面的等待kakfa完成操作和canal ack操作移至另一个独立线程中异步执行，就可以将整体性能提升1倍以上。
那么问题来了，作者为什么要设计成canal ack同步提交呢？是出于对哪些因素的考量？

看过canal的设计原理，EventStore采用RingBuffer技术实现了异步get、put和ack操作，为的就是提高效率。然而CanalKafkaProducer在实际应用中却采用了与get同步的ack操作，即get到一个batch就会做一次ack操作，做完后才可以进行下一次的get，这样做完全放弃了异步的高效，尤其是在ack前等待kafka的操作，浪费了很多时间。不明白为何要这么设计，是有什么不得已的考虑吗？还请解答。谢谢！

目前canal的性能无法满足本人项目需要，急需提升至少1倍，因此该问题对我至关重要。我必须了解清楚，如果改为异步提交，会带来哪些问题和风险。还望大佬们多多支持，再次感谢！

### Expected behaviour
希望了解，当我将等待kafka和canal ack操作改为异步执行时，可能会遇到哪些风险

**Comment by lxc-123** [comment]
怕重复消费？

**Comment by roamerway** [comment]
经与人探讨，结论是异步ack方式逻辑太过复杂，不是必要的话应尽量避免采用。
同时发现，仅将主配置中的canal.mq.canal.batch.size参数调大后，其性能比仅改为异步提交还要高。该参数的默认值为50，改为500，1000或更高后，tps指标提升至原来的3倍左右。
从代码角度解释，由于之前batchSize过小，每一批次处理数据量很小，再加上分topic等处理，实际单批次向每个topic发送kafka的数量只有个位数。此时每批次都做flush并等待kafka发送完成，就无法利用kafka client自身的优化能力，从而导致频繁的小量发送kafka，将时间都浪费在了网络连接和延迟上。调整batchSize参数后，每批次送kafka的数量达到较为合理的范围，从而利用起kafka client的优化算法，消除了kafka这块的性能瓶颈。
测试证明，batchSize调整越大（最大调整到4000），经kafka优化后的网络总流量越小。batchSize=500的网络总流量还不到=50时的一半。
最后还有个疑问，为何batchSize的默认值只有50这么小。一个批次仅处理50条记录，无论对于kafka发送，还是对于多topic多partition的并行处理来说，都太过量少，无法发挥出其性能。而我将之加大到500，1000，甚至更高的话，会有什么风险吗？除了内存多占用一点以外（约几MB，最多十几MB而已），我想不到还会有什么问题。

**Comment by roamerway** [comment]
异步方案过于复杂，尤其在异常场景处理上会引出很多问题，容易出错。所以应尽量避免使用。
关于batchSize默认值50太小的问题，我单独提一个issue来跟踪吧。本issue先关闭了。

**Comment by lzq1126** [comment]
批次调大了，消息延迟会提高。 在实时计算里面，实时性就没那么好。看自己的取舍了。
