### ISSUE TITLE
replace into ... select 语句获取不到

### ISSUE THREAD

**Issue by read-notes** [alibaba/canal#3108]
## Question

问题复现：
使用pt-table-checksum工具检查A\B两个库数据是否一致(binlog-format=statement)，A为主库，B通过canal同步A的数据，pt-table-checksum会生成replace into ... select、delete、update语句到从库执行，现在只有delete和update同步到了，replace into ... select未获取到。
通过单独测试也是，replace into ... select 类型的语句canal只同步了一个事务开始和事务结束，中间把这个语句跳过了，不知是什么原因

**Comment by read-notes** [comment]
canal已支持binlog-format=statement的解析，但是replace into测试了解析不了

**Comment by agapple** [comment]
show binlog events in 'xxx' from xxx，检查一下binlog里记录的是啥
