### ISSUE TITLE
canal怎么只监听一个数据库

### ISSUE THREAD

**Issue by wql6** [alibaba/canal#311]
1.假如mysql中有多个数据库，只监听test数据库怎么配置？
2.假如可以的话，怎么此库下的配置某一张表？
3.canal.instance.defaultDatabaseName = 怎么使用

**Comment by liyong2008** [comment]
在配置文件里设置,如conf\example\instance.properties里有2个配置选项
canal.instance.filter.regex = .*\\..* 这个是白名单,如test\\..*只监听test数据库,test\\.test监控test库里的test表,多个的话用逗号隔开,但是注意这个配置是无效的,必须在客户端subscribe方法里配置,因为会覆盖
canal.instance.filter.black.regex =  这个是黑名单,排除库表,配置同上,这个配置有效

具体配置示例参照源码目录里filter部分

**Comment by mossGKX** [comment]
按照配置配了，没什么用啊

**Comment by xufeng888** [comment]
> 在配置文件里设置,如conf\example\instance.properties里有2个配置选项 canal.instance.filter.regex = ._\.._ 这个是白名单,如test\..*只监听test数据库,test\.test监控test库里的test表,多个的话用逗号隔开,但是注意这个配置是无效的,必须在客户端subscribe方法里配置,因为会覆盖 canal.instance.filter.black.regex = 这个是黑名单,排除库表,配置同上,这个配置有效
> 
> 具体配置示例参照源码目录里filter部分,canal.instance.defaultDatabaseName = 这个配置项也是无效的,配不配没有关系

canal.instance.filter.regex=test\\.user表示只监听test库的user表,记得要用双斜杠,启动服务后,conf\example\instance.properties下生成的meta.dat文件片段如下:
{"clientDatas":[{"clientIdentity":{"clientId":1001,"destination":"example","filter":"test.user"},...."destination":"example"}
注意filter字段是不是你自己配置的值,然后客户端千万不要调用CanalConnector.subscribe(),配置即可生效!!!
