### ISSUE TITLE
Canal '\n, \t' problem in mysql json type

### ISSUE THREAD

**Issue by zherenyu831** [alibaba/canal#3110]
- [x] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment

* canal version   1.1.4
* mysql version  5.6

### Issue Description
We got a problem with json type in mysql with '\\\n, \\\t'
Canal will parse them '\\\n, \\\t' to ''\n, \t''. which is different with the content in mysql

我们发现canal 会把 mysql的 json type 里的 '\\\n, \\\t' 转成 '\n, \t' 
这样会导致数据不一致

### Actual behaviour

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by lucien-paypay** [comment]
canal在把Json格式的数据发向下游message的时候，没有对数据进行json-string的相应转义。致使其发送的message(string类型)不是一个合法的json-string

这是一个合法的json string:
```
{"key":"va\nlue"}
```

这不是一个合法的json string，（然而Canal在发送这种形式的message）
```
{"key":"va
lue"}
```

**Comment by kk17** [comment]
We encountered this issue too. Does anybody know how to fix it?

**Comment by lucien-paypay** [comment]
@kk17 we solved it on our own by replacing all special characters in message by its corresponding escaped string.

**Comment by kk17** [comment]
> @kk17 we solved it on our own by replacing all special characters in message by its corresponding escaped string.

Do you do this before parsing the JSON data?

**Comment by lucien-paypay** [comment]
> > @kk17 we solved it on our own by replacing all special characters in message by its corresponding escaped string.
> 
> Do you do this before parsing the JSON data?

Yes, sure, otherwise it isn't parsable.

**Comment by agapple** [comment]
我看了最新的代码已经是对\n添加了转义，可以测试下最新的1.1.5

**Comment by 15898317421** [comment]
> 我看了最新的代码已经是对\n添加了转义，可以测试下最新的1.1.5

请问是哪里的代码？目前使用otter里面存在这个问题
