### ISSUE TITLE
canal 在connector下kafka-connector的CanalKafkaProducer类中自定义了一个参数

### ISSUE THREAD

**Issue by ghost** [alibaba/canal#3114]
## Question

canal 在connector下kafka-connector的CanalKafkaProducer类中自定义了一个参数没在canal-admin模式中，参数在其配置中不能生效，这是什么原因。。在单机版的 canal-server中是生效的。在canal-admin模式中，不能生效

**Comment by agapple** [comment]
canal-admin模式下，默认是以本地配置为主，本地配置会覆盖admin配置，检查一下
