### ISSUE TITLE
1.0.24升级1.1.4 CPU爆满，负载从2到100

### ISSUE THREAD

**Issue by lppsuixn** [alibaba/canal#3117]
机器硬件：Intel(R) Xeon(R) Silver 4110 CPU @ 2.10GHz  32核，256g内存，centos 6.9系统。
Java版本：1.8.0_172
背景：
最近准备升级canal版本，原1.0.24版本中有 150个同步实例，目前迁移到1.1.4的50个。

现象：
从1.0.24升级到1.1.4 CPU暴涨，负载暴涨。
下图是机器负载图，前一部分是1.1.4，后一部分是降级后的。
![image](https://user-images.githubusercontent.com/12748339/97397060-57a65380-1923-11eb-998e-d9c77720f4cf.png)

![image](https://user-images.githubusercontent.com/12748339/97397235-c08dcb80-1923-11eb-962e-79d949dd2c49.png)

canal server给了20g内存，无频繁gc。
top -Hp 

![image](https://user-images.githubusercontent.com/12748339/97397417-1febdb80-1924-11eb-9cf7-d68eb4f10839.png)

使用 jstack 分析

![image](https://user-images.githubusercontent.com/12748339/97397604-9b4d8d00-1924-11eb-8080-7d39e3773dd8.png)
![image](https://user-images.githubusercontent.com/12748339/97397670-c20bc380-1924-11eb-8af9-eb984c350ba9.png)
![image](https://user-images.githubusercontent.com/12748339/97397685-d223a300-1924-11eb-8219-587216686ad0.png)
--------------
请问有什么分析思路吗？

**Comment by walkaroundby** [comment]
后来是降级解决的？

**Comment by lppsuixn** [comment]
@walkaroundby 调低canal.instance.parser.parallelThreadSize，或者直接把并行关掉。默认百分之60的CPU给解析，实例数多的情况下是不合适的。
