### ISSUE TITLE
可以instance列表进行连接吗？

### ISSUE THREAD

**Issue by kervin521** [alibaba/canal#313]
canal.destinations=example，example2，......
服务器可以配置多个实例列表

而连接时只支持单个实例，为什么不支持多个？
String destination=example;
connector = CanalConnectors.newClusterConnector(addresses, destination, username, password);
connector = CanalConnectors.newSingleConnector(new InetSocketAddress(ip, port), destination,username, password);  

destination参数为什么不能和配置参数一样支持多个，比如: destination=example，example2，......

**Comment by liyong2008** [comment]
好像文档有说吧,一个client只支持单个instance

**Comment by luyee** [comment]
@liyong2008   这样的话  假设20个instance  需要部署20 个client？

**Comment by hucc007** [comment]
group-instance.xml介绍：

主要针对需要进行多库合并时，可以将多个物理instance合并为一个逻辑instance，提供客户端访问。

场景：分库业务。 比如产品数据拆分了4个库，每个库会有一个instance，如果不用group，业务上要消费数据时，需要启动4个客户端，分别链接4个instance实例。使用group后，可以在canal server上合并为一个逻辑instance，只需要启动1个客户端，链接这个逻辑instance即可.

**Comment by liutaihua** [comment]
group-instance 有配置使用文档吗。 需要用在分库的情况。
