### ISSUE TITLE
binlog同步到kafka，truncate操作动态分区错误

### ISSUE THREAD

**Issue by xiehaochn** [alibaba/canal#3141]
- [x] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment

* canal v1.1.5-alpha-2
* mysql 5.7

### Issue Description
场景：binlog同步到kafka，topic配置多partition，根据表名动态分区
问题：kafka中truncate事件的操作类型为dml（这个是否应该归类于ddl？），但是在配置了动态分区的情况下，并没有进行动态分区，而是作为dml操作默认进入partition 0

LogEventConvert.java
`boolean isDml = (type == EventType.INSERT || type == EventType.UPDATE || type == EventType.DELETE);`

MQMessageUtils.java
`if (rowChange.getIsDdl()) {
                partitionEntries[0].add(entry);
            } `

### Expected behaviour
truncate操作也可以根据表名进行动态分区

### Actual behaviour
truncate操作默认发送到0号分区

**Comment by agapple** [comment]
目前DDL在发送到MQ时，并没有对SQL做深度的表解析，所以统一按照默认行为处理，可以考虑提交一个PR给我
