### ISSUE TITLE
canal client可以做集群负载均衡方式吗？

### ISSUE THREAD

**Issue by jayws** [alibaba/canal#315]
你好！请问canal client可以做集群负载均衡方式吗？是否能有个例子简单说明一下，谢谢！

**Comment by luyee** [comment]
ClientRunningMonitor / ServerRunningMonitors  maybe useful

**Comment by jayws** [comment]
你说的应该是HA方式吧，但是我想实现，比如当一个节点负载太多，然后就会自动分配到另一个节点来运行，这可以吗？谢谢

**Comment by luyee** [comment]
不支持LB吧，其实是standby模式吧

**Comment by luyee** [comment]
see  https://github.com/alibaba/canal/issues/147

**Comment by jayws** [comment]
谢谢
