### ISSUE TITLE
分库分表如何匹配多个库下的多个表filter.regex

### ISSUE THREAD

**Issue by HaoWenQiang** [alibaba/canal#3151]
1.1.14，我想匹配 库名前缀为canal 下的 表名前缀为 canal的所有的表
canal.instance.filter.regex = canal.*\\.canal.*

**Comment by HaoWenQiang** [comment]
`canal.*//.canal.*`

**Comment by walkaroundby** [comment]
这样配置可以生效？

**Comment by HaoWenQiang** [comment]
> 这样配置可以生效？

不好使啊，想问问有没有人配置过分库分表的大佬

**Comment by walkaroundby** [comment]
http://www.perlfect.com/articles/regextutor.shtml 
用perl先测一下，可以用一个instance监听多个库

**Comment by walkaroundby** [comment]
你这个用canal.*\.canal.*试试

**Comment by walkaroundby** [comment]
canal.*\.canal.*

**Comment by walkaroundby** [comment]
canal.*\\.canal.*

**Comment by walkaroundby** [comment]
canal.\*.canal.*

**Comment by walkaroundby** [comment]
canal.*\\.canal.*

**Comment by walkaroundby** [comment]
canal.\*\.canal.*

**Comment by walkaroundby** [comment]
canal.\\*\.canal.*

**Comment by walkaroundby** [comment]
canal.\\\*\.canal.*

**Comment by walkaroundby** [comment]
你有用 adapter同步这些分库分表吗

**Comment by HaoWenQiang** [comment]
谢谢我试试，不过我这堆积了一些消息晚点才能看到效果；
我直接发送的kafka

**Comment by HaoWenQiang** [comment]
这个可以， `canal.\*.canal.*`
