### ISSUE TITLE
canal推送消息到kafka存在脏数据(非json格式推送)

### ISSUE THREAD

**Issue by PostgreSQL1989** [alibaba/canal#3156]
## Question

canal推送消息到kafka，flatMessage设置为binlog模式，发现会有记录binlog的脏数据，请问如何过滤？
奇怪的事，我只要改成json格式进行投递，没有脏数据。
![image](https://user-images.githubusercontent.com/6407688/98230852-99c03c80-1f96-11eb-8c44-5b5ac5233660.png)
![image](https://user-images.githubusercontent.com/6407688/98230879-a5136800-1f96-11eb-96dc-1cef21aa1191.png)

**Comment by PostgreSQL1989** [comment]
是不是无法过滤的？

**Comment by agapple** [comment]
问题描述不清楚
