### ISSUE TITLE
mysql两个表join操作，同步数据到es。无法增量更新。

### ISSUE THREAD

**Issue by songzhouran** [alibaba/canal#3159]
## Question
当mysql其中一个表改变数据时，es的数据没有更新，请问怎么解决这个问题的？

**Comment by zhaoymZYM** [comment]
如果是两个表在同一个数据库中,正常是可以同步的,你看看你是不是写的同步的sql有问题,导致了无法同步,我现在遇到的问题是,一个sql跨越了两个数据库,主表可以同步,但是从表不能同步.
