### ISSUE TITLE
left join连接了两个数据库,主表可以同步数据,从表无法同步数据,如何解决

### ISSUE THREAD

**Issue by zhaoymZYM** [alibaba/canal#3160]
## Question
因业务逻辑的特殊需要,导致了需要在一个SQL中跨越了数据库直接使用left join来进行连接,并且将查询的数据放到es中,但是测试发现主表的数据是可以同步的,但是跨越了数据库的从表无法同步增量的数据,问一下这个问题有什么解决的办法.

**Comment by dreamInHeart** [comment]
你的两张表是在同一个数据库实例上吗？
如果是，小改即可；目前只同步了主表schema下的表，跨schema的需要在过滤表的地方改一下就行了；
如果不在一个实例，整个syncService得大改。
