### ISSUE TITLE
canal.instance.filter.regex无效，照着wiki写都不生效

### ISSUE THREAD

**Issue by Uchiha-Peng** [alibaba/canal#3170]
## 想监听指定数据库的指定表，无论是在canal client还是canal server使用canal.instance.filter.regex，都无效。。。。。。
我的写法为
canal.instance.filter.regex=dbName.tableA,dbName.tableB,dbName.tableC,dbName.tableD,dbName.tableE
然而，不仅其他的表，其他库的变动也没有过滤掉，令人费解。我使用最新版本，Canal-Server使用Docker部署。

canal/canal-server    latest              6320d7133917        2 months ago        871MB

WIKI中是这样写的：
```
5.  多个规则组合使用：canal\\..*,mysql.test1,mysql.test2 (逗号分隔)
```

**Comment by yansheng105** [comment]
canal.instance.filter.regex=dbName\\.tableA,dbName\\.tableB,dbName\\.tableC,dbName\\.tableD,dbName\\.tableE

这样写就行了，点号要转义

**Comment by Uchiha-Peng** [comment]
> ```
> canal.instance.filter.regex=dbName\\.tableA,dbName\\.tableB,dbName\\.tableC,dbName\\.tableD,dbName\\.tableE
> ```
> 
> 这样写就行了，点号要转义

试了试，有效果，多谢。主要是被wiki误导了，canal\\..*,mysql.test1,mysql.test2 (逗号分隔)

**Comment by Uchiha-Peng** [comment]
非BUG，操作有误。不过WIKI请描述清楚啊，谢谢。

**Comment by lx5210** [comment]
canal.instance.filter.regex =test\\..*这种为啥动别的库也会检测到

**Comment by feng99** [comment]
> canal.instance.filter.regex =test\..*这种为啥动别的库也会检测到

把黑名单配置也加上

**Comment by zjh0x** [comment]
2023年再次踩坑

**Comment by wwwu** [comment]
```
docker run ... \
-e canal.destinations=xxx \
-e canal.instance.filter.query.ddl=true \
-e canal.instance.connectionCharset=UTF-8 \
-e canal.instance.tsdb.enable=true \
-e canal.instance.gtidon=false  \
-e canal.instance.filter.regex=dbName\\.table1,dbName\\.table2 \
... \
-d canal/canal-server:latest

//dbName.table1,dbName.table2
//dbName\.table1,dbName\.table2
//dbName\\.table1,dbName\\.table2
```
对应版本canal-1.1.7-alpha-2
转不转义都试了个遍，依然无效

**Comment by wwwu** [comment]
> ```
> docker run ... \
> -e canal.destinations=xxx \
> -e canal.instance.filter.query.ddl=true \
> -e canal.instance.connectionCharset=UTF-8 \
> -e canal.instance.tsdb.enable=true \
> -e canal.instance.gtidon=false  \
> -e canal.instance.filter.regex=dbName\\.table1,dbName\\.table2 \
> ... \
> -d canal/canal-server:latest
> 
> //dbName.table1,dbName.table2
> //dbName\.table1,dbName\.table2
> //dbName\\.table1,dbName\\.table2
> ```
> 
> 对应版本canal-1.1.7-alpha-2 转不转义都试了个遍，依然无效

解决办法：仔细阅读FAQ
https://github.com/alibaba/canal/wiki/FAQ

Check whether CanalConnectors have called subscribe(filter) method. If so, filters should be consistent with the canal.instance.filter.regex in instance.properties, otherwise filters of subscribe will overwrite the settings in the instance. Please NOTE that, if the filter for subscribe is .*/..*, then you have consumed all the data updated.
检查 CanalConnector 是否调用了订阅（过滤）方法。如果是这样，过滤器应与实例属性中的 canal.instance.filter.regex 一致，否则订阅过滤器将覆盖实例中的设置。请注意，如果订阅过滤器是.*/.。*，则您已使用更新的所有数据。


```
//C#的ClientSDK中filter 默认为“.*\\..*” ,
public async Task SubscribeAsync(string filter = ".*\\..*")
```
```
var conn = new SimpleCanalConnection(...);
await conn.ConnectAsync();
//导致覆盖了canal.instance.filter.regex 为 .*\\..*
await SubscribeAsync(); 

//与canal.instance.filter.regex一致，过滤有效
await SubscribeAsync("dbName\\.table1,dbName\\.table2"); 

//以canal.instance.filter.regex设置为准，过滤有效
await SubscribeAsync(""); 
```

**Comment by qq664042** [comment]
这个bug我找到了，canal-client的subscribe方法的参数会把canal-server的canal.instance.filter.regex的值覆盖，只能使用黑名单
