### ISSUE TITLE
通过k8s部署，canal.serverMode=rabbitmq不支持env环境变量

### ISSUE THREAD

**Issue by lp2021** [alibaba/canal#3176]
- [ ] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment

* canal version
 v1.1.5-alpha-2

* mysql version
MySQL：5.7
### Issue Description
通过k8s部署，canal.serverMode=rabbitmq不支持通过yaml文件设置env环境变量的方式修改，导致服务无法启动，需要额外挂载配置文件，修改配置文件中的参数。

### Actual behaviour

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by agapple** [comment]
最新代码已经支持
