### ISSUE TITLE
有个疑问 canal.mq.partitionsNum 如果设置分区为5，canal.mq.dynamicTopic动态topic 匹配到topicA，匹配不到默认到topicC，那么A为5个分区，默认的C也走散裂规则吗，还是只有动态topic走散裂规则？

### ISSUE THREAD

**Issue by xinyangbest** [alibaba/canal#3207]
## Question
有个疑问 canal.mq.partitionsNum 如果设置分区为5，canal.mq.dynamicTopic动态topic 匹配到topicA，匹配不到默认到topicC，那么A为5个分区，默认的C也走散裂规则吗，还是只有动态topic走散裂规则？

**Comment by xinyangbest** [comment]
有办法为不同topic设置不同的分区量吗

**Comment by agapple** [comment]
#canal.mq.dynamicTopicPartitionNum，可以指定不同topic有多少分区
