### ISSUE TITLE
生产环境遇到了一个bug

### ISSUE THREAD

**Issue by h1521277** [alibaba/canal#3215]
Could not resolve placeholder 'whoStr[0]' in value "{ thisHistID=`history 1|awk "{print \\$1}"`;lastCommand=`history 1| awk "{\\$1=\"\" ;print}"`;user=`id -un`;pwd=`pwd`;whoStr=(`who -u am i`);user=`id -un`;pwd=(`pwd`);realUser=${whoStr[0]};logMonth=${whoStr[2]};logDay=${whoStr[3]};logTime=${whoStr[4]};pid=${whoStr[6]};ip=${whoStr[7]};if [ ${thisHistID}x != ${lastHistID}x ];then echo -E `date"+%Y/%m/%d %H:%M:%S"` $user\($realUser\)@$ip[IP:$pid][PWD:$pwd][LOGIN:$logMonth $logDay $logTime] --- $lastCommand ;lastHistID=$thisHistID;fi; } >> $HISTORY_FILE"

**Comment by hlc0110** [comment]
在服务器上执行env命令，看是不是有${whoStr[0]}这样的变量

**Comment by wyaopeng** [comment]
卧槽.....
加了变量果然好了，这...
![image](https://user-images.githubusercontent.com/12064306/110302636-6cfb5f00-8034-11eb-977a-c8ca8c695ab1.png)
