### ISSUE TITLE
Alter语句无法识别为DDL

### ISSUE THREAD

**Issue by jscene** [alibaba/canal#3222]
version: 1.1.5-alpha-2
SQL : ALTER TABLE `asd_lmdm_dev`.`es_user` 
CHANGE COLUMN `es_usercol111` `es_usercol` VARCHAR(45) NULL DEFAULT NULL

LogEventConvert.parseQueryEvent解析出来type 为ALTER，但是设置ddl为true的语句如下
` 
if (type == EventType.QUERY && !isDml) {
     rowChangeBuider.setIsDdl(true);
}`

导致解析出来isDdl:false
DML: {"data":null,"database":"asd_lmdm_dev","destination":"asd_dev","es":1606999495000,"groupId":"asd_dev_group","isDdl":false,"old":null,"pkNames":[],"sql":"ALTER TABLE `asd_lmdm_dev`.`es_user` \nCHANGE COLUMN `es_usercol111` `es_usercol` VARCHAR(45) NULL DEFAULT NULL","table":"es_user","ts":1607000161626,"type":"ALTER"}

**Comment by brucehuang2** [comment]
+1，我遇到了同样的问题。

**Comment by ZoroRe** [comment]
+1，最近正好线上使用。 ddl 总是没有得到执行导致出错。
是不是Canal 最开始 ddl 是 QUERY，后来新版本增加了 ALTER 导致解析出错？

**Comment by 1454513232** [comment]
+1，测试了下1.1.4是没问题的，可以实现MySQL的ddl同步，但是1.1.5把ddl识别为dml操作，可以捕获到，但是没有应用

**Comment by agapple** [comment]
1.1.5 已修复

**Comment by lxz902** [comment]
@agapple  1.1.6版本还是有这个问题，我遇到了
