### ISSUE TITLE
canal.adapter-1.1.4 mysql主库同步到从库无法成功

### ISSUE THREAD

**Issue by hzh2005525** [alibaba/canal#3231]
insert可以；update和delete不行，日志报错直接显示java.lang.RuntimeException: Target column: test not matched

**Comment by station19** [comment]
> 2020-12-09 12:43:46.611 [pool-8-thread-1] INFO c.a.o.canal.client.adapter.logger.LoggerAdapterExample - DML: {"data":[{"settle_cust_name":"测试1"}],"database":"buscs-bs","destination":"example","es":1607489026000,"groupId":null,"isDdl":false,"old":null,"pkNames":[],"sql":"","table":"bc_freight","ts":1607489026541,"type":"UPDATE"}

老兄, 你的也是update和delete 不能同步吗?

**Comment by hzh2005525** [comment]
@station19 
insert可以；update和delete不行，日志报错直接显示java.lang.RuntimeException: Target column: test not matched

**Comment by hzh2005525** [comment]
同步的时候，目标库名称不支持中划线，目标库名称改为下划线就好了。
