### ISSUE TITLE
canal.adapter-1.1.4 普通mysql同步mysql ,delete和update无法同步

### ISSUE THREAD

**Issue by station19** [alibaba/canal#3232]
1, canal.adapter-1.1.4 普通mysql同步mysql ,delete和update无法同步,   但只是insert ,同步就没问题,  
2, 如果执行 delete 和update  语句后,  canal同步就会报错,后续的 insert也不会同步了, 啥情况

**Comment by weiccTest** [comment]
为啥业务应用里有delete 的权限？有点恐怕

**Comment by station19** [comment]
> 为啥业务应用里有delete 的权限？有点恐怕

更新总有吧, 更新也不行, delete 我是为了自己测试

**Comment by hzh2005525** [comment]
兄弟，你那边是不是日志报异常：java.lang.RuntimeException: Target column: test not matched？

**Comment by station19** [comment]
> 兄弟，你那边是不是日志报异常：java.lang.RuntimeException: Target column: test not matched？

不是, 我的已经解决了

**Comment by chenfuqing** [comment]
@station19 好兄弟呀，这个问题是怎么解决的，share with me。

**Comment by hzh2005525** [comment]
兄弟，你看你同步的时候，是不是目标库名称有特殊字符，比如目标库名称不支持中划线

**Comment by chenfuqing** [comment]
目标库存在中划线，已解决。谢谢。













在 2021-02-03 13:08:51，"hzh2005525" <notifications@github.com> 写道：

兄弟，你看你同步的时候，是不是目标库名称有特殊字符，比如目标库名称不支持中划线

**Comment by 123sunfuqiang** [comment]
大佬，想问下，你这边是怎么处理的，我这边也碰到这问题了，insert是可以，但是更新和删除出现问题了
