### ISSUE TITLE
plugin文件夹里的jar包，复制到 lib文件夹里面

### ISSUE THREAD

**Issue by dx94sg** [alibaba/canal#3234]
plugin文件夹里的jar包，复制到 lib文件夹里面

_Originally posted by @jvmtar in https://github.com/alibaba/canal/issues/3233#issuecomment-741627290_

弱弱的问一句这个plugin文件夹和lib文件夹在哪里。。。我是直接启动的client-adapter。。

**Comment by jvmtar** [comment]
在deployer项目里



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: dx94sg <notifications@github.com&gt;
发送时间: 2020年12月9日 16:56
收件人: alibaba/canal <canal@noreply.github.com&gt;
抄送: jvmtar <513669995@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[alibaba/canal] plugin文件夹里的jar包，复制到 lib文件夹里面 (#3234)





 
plugin文件夹里的jar包，复制到 lib文件夹里面
 
Originally posted by @jvmtar in #3233 (comment)
 
弱弱的问一句这个plugin文件夹和lib文件夹在哪里。。。我是直接启动的client-adapter。。
