### ISSUE TITLE
升级zkclient到0.10

### ISSUE THREAD

**Issue by alexandnpu** [alibaba/canal#324]
@agapple , 希望把zkclient升级到0.10

# 优点：

1. 在0.10版本里， Switch from Log4j to Slf4j，这方便我们把debug log打开调试
1. 一些bug fix

# 缺点

1.  0.10 对一些接口增加一些方法，canal要适当的做些调整

**Comment by agapple** [comment]
如果方便，给我提交一个PR吧

**Comment by alexandnpu** [comment]
#142

**Comment by alexandnpu** [comment]
#331 ， 提交了一个PR，还请review一下
