### ISSUE TITLE
canal.adapter能读取到数据,但是不写入数据库,求解

### ISSUE THREAD

**Issue by station19** [alibaba/canal#3241]
adapter 日志已打印出 log "type":"UPDATE" 等 ,但是 outerAdapters 的数据库  写入 一条数据也没有, 求解 ,服务端和client重启无数次了

curl -X POST http://localhost:8081/etl/rdb/mytest_user.yml
{"succeeded":false,"errorMessage":"Task not found"}

**Comment by muyable** [comment]
task not found 一般是没配对。

**Comment by station19** [comment]
> task not found 一般是没配对。我最近也在用，发现有时候也报这个。但这种，应该是配置文件的问题，反正我配对了就不报了。

能共享下配置么? 敏感字段可以替换下
