### ISSUE TITLE
canal的instance.propertios里canal.mq.dynamicTopic=canal_manager.topic-test点号自动转为下划线

### ISSUE THREAD

**Issue by MaErLian1988** [alibaba/canal#3255]
## topic名称里的点号自动转为下划线。请问如何才能保留点号。
使用canal处理mysql-binlog，本想以库名.表名的形式来命名topic，但canal自动将点号转为下划线。而由于mysql库名命名时也有下划线，这样导致下游在使用topic时不知道数据来源。
请问如何在canal.mq.dynamicTopic配置的topic命名有点号？

**Comment by balzaron** [comment]
转义呀, canal_manager\\.topic-test
