### ISSUE TITLE
Canal服务运行一段时间后日志会落后很多。Canal解析binlog跟不上上游数据库的日志产生，这种情况应该怎么解决？

### ISSUE THREAD

**Issue by tianyangang** [alibaba/canal#3258]
## Question

![image](https://user-images.githubusercontent.com/76166820/102495603-3eaf5880-40b1-11eb-834b-56ca8ee9acde.png)
![image](https://user-images.githubusercontent.com/76166820/102495674-5850a000-40b1-11eb-8186-64b3e3b256ed.png)
以上截图就是zk中记录的位置和实际数据库中产生的日志点。
谢谢大家

**Comment by tianyangang** [comment]
通过sql->show master status查询的位置。
journalName":"mysql-bin.004615","position":382444468这是mysql数据库的日志点
journalName":"mysql-bin.004610","position":459164724 这个是zk中记录的

**Comment by ja2py** [comment]
我们也遇到了这样的问题。。。

**Comment by tianyangang** [comment]
@ja2py 你可以观察一下你kafka中写入Topic的问题。你现在应该是配置的写入kafka需要ACK确认，kafka存在ACK确认机制，我把那个给改掉了。改成了0，几分钟就跟上了。

**Comment by dingyufei615** [comment]
`
## canal内存store中可缓存buffer记录数，需要为2的指数
canal.instance.memory.buffer.size = 131072
## 内存记录的单位大小，默认1KB，和buffer.size组合决定最终的内存使用大小
canal.instance.memory.buffer.memunit = 1024
## canal内存store中数据缓存模式
##1. ITEMSIZE : 根据buffer.size进行限制，只限制记录的数量
##2. MEMSIZE : 根据buffer.size * buffer.memunit的大小，限制缓存记录的大小
canal.instance.memory.batch.mode = MEMSIZE
canal.instance.memory.rawEntry = true

# 是否开启binlog并行解析模式(串行解析资源占用少,但性能有瓶颈, 并行解析可以提升近2.5倍+)
canal.instance.parser.parallel = true
#binlog并行解析的异步ringbuffer队列(必须为2的指数)
canal.instance.parser.parallelBufferSize = 256

## flagMessage模式下可以调大该值, 但不要超过MQ消息体大小上限
canal.mq.batchSize = 16384
canal.mq.maxRequestSize = 10240000
# kafka为ProducerConfig.LINGER_MS_CONFIG , 如果是flatMessage格式建议将该值调大,50～200
canal.mq.lingerMs = 200
canal.mq.bufferMemory = 33554432
# Canal的batch size, 默认50K, 由于kafka最大消息体限制请勿超过1M(900K以下)
canal.mq.canalBatchSize = 50
# Canal get数据的超时时间, 单位: 毫秒, 空为不限超时
canal.mq.canalGetTimeout = 100
canal.mq.parallelThreadSize = 16
# 是否为flat json格式对象
canal.mq.flatMessage = true
canal.mq.compressionType = none
# kafka消息投递是否使用事务
canal.mq.acks = 1
`


参考我在使用的配置

**Comment by szthanatos** [comment]
> `
> 
> ## canal内存store中可缓存buffer记录数，需要为2的指数
> canal.instance.memory.buffer.size = 131072
> 
> ## 内存记录的单位大小，默认1KB，和buffer.size组合决定最终的内存使用大小
> canal.instance.memory.buffer.memunit = 1024
> 
> ## canal内存store中数据缓存模式
> ##1. ITEMSIZE : 根据buffer.size进行限制，只限制记录的数量
> ##2. MEMSIZE : 根据buffer.size * buffer.memunit的大小，限制缓存记录的大小
> canal.instance.memory.batch.mode = MEMSIZE
> canal.instance.memory.rawEntry = true
> 
> # 是否开启binlog并行解析模式(串行解析资源占用少,但性能有瓶颈, 并行解析可以提升近2.5倍+)
> canal.instance.parser.parallel = true
> #binlog并行解析的异步ringbuffer队列(必须为2的指数)
> canal.instance.parser.parallelBufferSize = 256
> 
> ## flagMessage模式下可以调大该值, 但不要超过MQ消息体大小上限
> canal.mq.batchSize = 16384
> canal.mq.maxRequestSize = 10240000
> 
> # kafka为ProducerConfig.LINGER_MS_CONFIG , 如果是flatMessage格式建议将该值调大,50～200
> canal.mq.lingerMs = 200
> canal.mq.bufferMemory = 33554432
> 
> # Canal的batch size, 默认50K, 由于kafka最大消息体限制请勿超过1M(900K以下)
> canal.mq.canalBatchSize = 50
> 
> # Canal get数据的超时时间, 单位: 毫秒, 空为不限超时
> canal.mq.canalGetTimeout = 100
> canal.mq.parallelThreadSize = 16
> 
> # 是否为flat json格式对象
> canal.mq.flatMessage = true
> canal.mq.compressionType = none
> 
> # kafka消息投递是否使用事务
> canal.mq.acks = 1
> `
> 
> 参考我在使用的配置

mark
