### ISSUE TITLE
k8s docker通过nfs或ConfigMap方式更改canal.properties 启动不成功

### ISSUE THREAD

**Issue by penweizgx** [alibaba/canal#3262]
在k8s docker通过nfs或ConfigMap方式挂载，启动不了

<img width="1134" alt="WX20201218-162101@2x" src="https://user-images.githubusercontent.com/6983487/102591812-97343380-414d-11eb-90d7-09597f0f4185.png">

<img width="1134" alt="WX20201218-162101@2x" src="https://user-images.githubusercontent.com/6983487/102591865-a87d4000-414d-11eb-999f-db5292fe4ab5.jpg">

**Comment by penweizgx** [comment]
暂时解决，不晓得有没有其他问题。
注释掉 canal/docker/image/app.sh文件中的chown ** 和 su admin  ** 相关的，以默认的root权限运行

**Comment by cndarren** [comment]
我这块是通过configMap挂载方式部署的canal-server，也是报类似错误。我这块的解决方法是，通过在configMap中挂载一个app.sh文件覆盖掉/home/admin/app.sh文件，如下图所示
![image](https://user-images.githubusercontent.com/52493242/193212755-55e25200-d85e-47b6-9ab7-05e32833ddb8.png)
挂载的app.sh可以复制当前canal/docker/image/app.sh内容，然后注释掉下图内容
![image](https://user-images.githubusercontent.com/52493242/193213228-e0babd00-c10a-4769-a188-aae1b6dee32a.png)
之后全局搜索 su admin ，将su admin 内容替换为 su root，类似下图这样
![image](https://user-images.githubusercontent.com/52493242/193218922-016051f1-2fcb-4383-9a77-dc948188a0bd.png)
这样做，临时是解决了docker镜像用户admin与k8s pod用户root不一致，导致部署失败的问题；有更好的方式，欢迎交流
