### ISSUE TITLE
mysql同步到PGSQL 源表新增子段导致，目标表无法匹配报错  在rdb文件中添加字段的映射上传后无法动态加载

### ISSUE THREAD

**Issue by chris-chen23** [alibaba/canal#3274]
## Question

![image](https://user-images.githubusercontent.com/43943624/103132148-7be19f00-46de-11eb-8eb9-5414c3224a16.png)
mysql同步到PGSQL 源表新增子段导致，目标表无法匹配报错  在rdb文件中添加字段的映射排除新字段不同步
配置文件重新 上传后无法动态加载。
只能重启canal-adapter，有这样的问题吗

**Comment by wingerx** [comment]
canal-adapter 应该是不支持配置的动态加载

**Comment by chris-chen23** [comment]
> canal-adapter 应该是不支持配置的动态加载

支持删除和新增已经正常情况下的修改的动态加载 ，但是如果同步出现异常  即便修改或者删除rdb文件也不会动态加载，这是我测试得到的结论

**Comment by ccubec** [comment]
确实啊 只看到监听源数据表有一行添加字段的输出  同步的数据表并不会添加。。好心累啊
