### ISSUE TITLE
canal-adapter同步数据库部分事务手动提交的目的

### ISSUE THREAD

**Issue by xuej2s** [alibaba/canal#3278]
在使用canal-adapter的时候，发现adapter同步数据库时，在代码中是使用的手动提交事务的方式，这样写是出于哪方面的考虑？与自动提交相比有什么好处吗？

**Comment by wingerx** [comment]
控制一个batch 的数据尽量在一个事务内提交，若失败则整批失败，而不是部分，特别是针对目标端非merge 的情况，能极大减少人工介入(主键冲突)的几率。

**Comment by xuej2s** [comment]
> 控制一个batch 的数据尽量在一个事务内提交，若失败则整批失败，而不是部分，特别是针对目标端非merge 的情况，能极大减少人工介入(主键冲突)的几率。

我理解，因为adapter本身有处理重复执行dml的能力，所以哪怕在每条dml自动提交的方式下一个batch中的某条数据失败，重新执行也不会有什么影响吧，这个人工介入的情况是什么时候呢？

目前想把这个同步方式改成自动提交的原因是因为我这里有一个将数据同步到阿里drds的需求，使用一个batch手动提交事务的方式，会因为数据不在同一个分库，产生分布式事务的问题，而分布式事务drds是不支持的

**Comment by wingerx** [comment]
**重复执行没有什么影响** 的结论是基于sql 数据是通过幂等(`merge`)的方式执行的，你的这个场景可以使用自动提交

**Comment by xuej2s** [comment]
> **重复执行没有什么影响** 的结论是基于sql 数据是通过幂等(`merge`)的方式执行的，你的这个场景可以使用自动提交

大佬，可以对这个目标端非merge的场景举个例子吗？没有想明白具体会发生的情况，担心我的应用场景也会遇到这种情况

**Comment by wingerx** [comment]
目标端是否可以执行Merge语句，有很多场景，大部分关系型数据库都是支持的，但是前提是表有主键/唯一键
