### ISSUE TITLE
在canal-admin上配置了几个instance，运行十几天半个月后instance就不解析binlog了，这是为什么

### ISSUE THREAD

**Issue by dcy652701** [alibaba/canal#3280]

**Comment by wingerx** [comment]
建议分析一下日志，看看有没有异常的情况。

**Comment by zhaoymZYM** [comment]
有时候有可能是数据库表结构改变了，或者是增加了新的database，再或者是给canal的读取binlog的权限不足，这些都有可能导致不再读取binlog。解决问题以后，重新启动，就可以继续读取binlog了

**Comment by dcy652701** [comment]
> 建议分析一下日志，看看有没有异常的情况。
好的谢谢

**Comment by dcy652701** [comment]
> 有时候有可能是数据库表结构改变了，或者是增加了新的database，再或者是给canal的读取binlog的权限不足，这些都有可能导致不再读取binlog。解决问题以后，重新启动，就可以继续读取binlog了

好的，谢谢
