### ISSUE TITLE
canal server 重启后，client端如何自动重连呢？

### ISSUE THREAD

**Issue by Alibner** [alibaba/canal#3285]
Version:
canal server version: 1.0.24
canal client version: 1.0.24
Trouble:
canal server在手动关闭后，client端会报错`c.a.o.c.c.i.r.ClientRunningMonitor - There is an error when execute initRunning method, with destination`；
canal server启动后，client端卡住了。然后重启client才可以继续消费。

想问问有没有重新连接的机制，或者相关文档参考

**Comment by Alibner** [comment]
@wingerx   PTAL

**Comment by wingerx** [comment]
先升级最新版本再试试看吧，client 端是有自动重连的

**Comment by Alibner** [comment]
👌

**Comment by Enhengtaken** [comment]
> 👌

请问验证后，现在有自动重连么，因为最近我刚刚遇到一个现象就是没有重连的

**Comment by sunrisela** [comment]
若server端Host是域名，IP发生变动（比如k8s容器环境）会导致client无法自动重连，必须重启client。解决该问题的临时办法：
com.alibaba.otter.canal.client.impl.SimpleCanalConnector#getAddress:
`
public SocketAddress getAddress() {
    if (address != null && address instanceof InetSocketAddress) {
        InetSocketAddress sa = (InetSocketAddress) address;
        return new InetSocketAddress(sa.getHostName(), sa.getPort());
    }
    return address;
}
`
