### ISSUE TITLE
使用Canal实现全量+增量数据同步方案

### ISSUE THREAD

**Issue by MINCWANG** [alibaba/canal#3288]
## Question
历史的binlog已经丢失，如何使用canal实现全量+增量的数据同步。
先用类似于dataX触发一次全量同步？如果这样 ，那这增量binlog的位置怎么确定才能实现数据同步的exactly once？

求大佬解答

**Comment by wingerx** [comment]
1. 若场景允许，请通过下游目标端对数据的幂等处理来达到数据的最终一致性
2. 若业务场景需要全量和增量同步衔接上exactly once，可参考`debezium`的实现方案: 数据库锁+事务快照一致性读来解决这个问题。
3. Canal 本质是一个binlog 数据解析工具，在下游做了一些生态的适配
