### ISSUE TITLE
canal在同步报错的情况下，可以跳过这个错误么？

### ISSUE THREAD

**Issue by dnfhujun** [alibaba/canal#329]
据测试，canal在同步sql报错的时候，会一直重复的去执行这个sql，导致position位置停止，假如由于手误导致有一条binlog的sql，比如表不存在这种，就会导致canal停滞，请问大神有跳过同步错误的方法么？

**Comment by agapple** [comment]
目前只能重置一下位点，后续可以考虑增加DDL变更能力的支持
