### ISSUE TITLE
binlog 到canal server 等组件的时序

### ISSUE THREAD

**Issue by xinxinzhao1212** [alibaba/canal#3293]
## Question
])
关于canal 的时序，有几点想了解一下
parser/sink依赖的位点管理选择了持久化模式，是用zookeeper 的方式
1.canal server 在收到binlog 后，parser 模块用zookeeper 来做持久化处理，存储上一次binlog 解析的位置，是先存储binlog 位置再发送binlog 到mq 中，还是存储位置和发送binlog 是同时进行的？
2.canal server 这边是以怎样的方式发送到下游的，是积攒了一些再向mq 发送，还是边收边发，考虑到数据量多的时候，对zookeeper 的压力会不会很多

**Comment by agapple** [comment]
只有客户端有消费时才会定时更新到zookeeper
