### ISSUE TITLE
canal store中默认实例内存16M,可能存在丢数据的情况吗？

### ISSUE THREAD

**Issue by wyb92** [alibaba/canal#3298]
canal.instance.memory.buffer.size = 16384
canal.instance.memory.buffer.memunit = 1024 
canal.instance.memory.batch.mode = MEMSIZE
看代码中，store模块中MemoryEventStoreWithBuffer.tryPut的时候，如果没有空位是等待，但是有的兄弟说，超过16M是会丢失，和entries的数组大小有关。

**Comment by wingerx** [comment]
超过16MB会阻塞上游的数据解析，不会丢失数据
