### ISSUE TITLE
HA方式，kill掉进程不能切换

### ISSUE THREAD

**Issue by jayws** [alibaba/canal#332]
hi，HA方式时，我手工kiil掉正在运行的进程，客户端程序不能切换，在zookeeper查看已经服务已经切换，请问是什么回事呢？谢谢！
另：正常关闭服务时，程序可以切换服务

DEBUG org.apache.zookeeper.ClientCnxn - Got ping response for sessionid: 0x35ca6b0127d780e after 0ms

一直都在打印这样的语句

**Comment by agapple** [comment]
这个是DEBUG输出，忽略吧
