### ISSUE TITLE
请问canal 1.1.4版本如何访问阿里云的消息队列kafka版本？有参考配置么？

### ISSUE THREAD

**Issue by cangos2012** [alibaba/canal#3323]
请问canal 1.1.4版本如何访问阿里云的消息队列kafka版本？有参考配置么？阿里云的消息队列kafka版本设置了SASL_SSL安全协议，使用普通的连接kafka的方式无法连接，请问大神们能给个参考么？

**Comment by nmgliangwei** [comment]
@cangos2012 你解决了吗?我按照wiki 配置 sasl_ssl 怎么都配置不成功

**Comment by cangos2012** [comment]
@nmgliangwei 我换成了1.1.5版本，在整理文档，有需要的话可以给你一份

**Comment by nmgliangwei** [comment]
@cangos2012 非常感谢分享文档. 如果方便的话,您可以发我邮箱. nmgliangwei#gmail.com. 为了屏蔽邮件抓取所以@用#替代了.

**Comment by cangos2012** [comment]
@nmgliangwei https://mp.weixin.qq.com/s/5H-juplsnh43__s55EGSsw
