### ISSUE TITLE
为什么zookeeper上running节点中的运行节点地址始终是172.17.0.1 

### ISSUE THREAD

**Issue by Marxss** [alibaba/canal#3329]
## Question

如题，即使发生了故障转移，节点还是显示该实例运行在172.17.0.1 上。

**Comment by lanmaodage** [comment]
重启多次或删除conf里面对应的文件夹就会在另外的节点启动起来

**Comment by Marxss** [comment]
找到问题的原因了，在配置的时候要加上canal.register.ip = 10.1.1.134 (docker容器所在物理机IP地址)，也可以在docker容器启动的时候添加环境变量。
