### ISSUE TITLE
canal 输出到kafka的json结构，各个字段的含义能说明一下吗

### ISSUE THREAD

**Issue by chaixiaoxue** [alibaba/canal#3331]
## Question

canal 输出到kafka的json结构，各个字段的含义能说明一下吗

**Comment by yuanweikang2020** [comment]
> ## Question
> canal 输出到kafka的json结构，各个字段的含义能说明一下吗


data | array(map) | 修改改后的数据，包含每一个表结构字段的kv结构
-- | -- | --
database | string | 数据库名
es | int64 | binlog executeTime，单位：ms
id | int64 | batch_id
isDdl | bool | 是否是ddl语句
mysqlType | map | 数据表结构
old | array(map) | 未修改前字段的值，与data列表一一对应
pkNames | array(string) | pk字段名
sql | string |  
sqlType | map |  
table | string | 数据表名
ts | int64 | 操作执行当前时间，单位：ms
type | string | 数据库操作类型

**Comment by chaixiaoxue** [comment]
thank you

**Comment by karinemo1** [comment]
batch_id可以详细说一下吗

**Comment by yangkaiShi** [comment]
es：binlog executeTime，单位：ms，请问这个字段是数据库的binlog时间戳吗？
如果我现在有master库和slave库（两个数据库），canal从slave库同步数据，那es这个字段是slave库的binlog时间戳吗？canal有没有办法拿到master库的binlog时间戳
