### ISSUE TITLE
Canal MySQL Adapter增量同步数据update操作无效

### ISSUE THREAD

**Issue by clojure8** [alibaba/canal#3333]
如题。源表做update操作后，目标表不能同步update。具体DML的日志日下
`DML: {"data":[{"create_time":1611302394000,"p_id":2,"update_time":1611302394000}],"database":"dev","destination":"example","es":1611302394000,"groupId":"g1","isDdl":false,"old":null,"pkNames":[],"sql":"","table":"test1","ts":1611302395232,"type":"UPDATE"}`

（使用的canal 1.1.4版本）

**Comment by MasterXuZ** [comment]
方便说下怎么解决的吗，我现在只有插入能同步，update无效，delete会直接把从库中表删光
