### ISSUE TITLE
canal instance log: Could not find first log file name in binary log index file

### ISSUE THREAD

**Issue by xjliang2007** [alibaba/canal#3338]
## Question

操作过程：
1.adminUI查看instance日志，显示一片空白
2.尝试停止instance，然后重启instance，进入日志发现如标题所示异常

解决方式是：canal server conf/instance目录删除meta.dat文件，重启canal server即恢复正常(单台机器的集群)

网上看了下类似问题，说是数据库binlog被删除之类的，去数据库管理员确认过，日志没有删除，磁盘空间足够。

出问题时候的meta.dat文件内容如下：
{"clientDatas":[{"clientIdentity":{"clientId":1001,"destination":"gip-2020-12","filter":""},"cursor":{"identity":{"slaveId":-1,"sourceAddress":{"address":"rm-xxx.mysql.rds.aliyuncs.com","port":3306}},"postion":{"gtid":"","included":false,"journalName":"mysql-bin.000266","position":226987109,"serverId":2757725211,"timestamp":1610750948000}}}],"destination":"gip-2020-12"}

有人可以帮忙解答下原因么

**Comment by yuanweikang2020** [comment]
> ## Question
> 操作过程：
> 1.adminUI查看instance日志，显示一片空白
> 2.尝试停止instance，然后重启instance，进入日志发现如标题所示异常
> 
> 解决方式是：canal server conf/instance目录删除meta.dat文件，重启canal server即恢复正常(单台机器的集群)
> 
> 网上看了下类似问题，说是数据库binlog被删除之类的，去数据库管理员确认过，日志没有删除，磁盘空间足够。
> 
> 出问题时候的meta.dat文件内容如下：
> {"clientDatas":[{"clientIdentity":{"clientId":1001,"destination":"gip-2020-12","filter":""},"cursor":{"identity":{"slaveId":-1,"sourceAddress":{"address":"rm-xxx.mysql.rds.aliyuncs.com","port":3306}},"postion":{"gtid":"","included":false,"journalName":"mysql-bin.000266","position":226987109,"serverId":2757725211,"timestamp":1610750948000}}}],"destination":"gip-2020-12"}
> 
> 有人可以帮忙解答下原因么

这是因为源数据库binlog position发生了变更，canal记录到zk的postition无论与源数据库binlog postition保持连续性，所以canal这块会认为找不到初始同步位置，可以考虑源数据库开启gtid模式，canal也使用gtid模式，gtid全局唯一应该可以解决这个问题

**Comment by xjliang2007** [comment]
如果是源数据库binlog position发生了变更，canal是无法感知到并重置么？毕竟也不是所有复制都可以适合使用gtid模式

**Comment by yuanweikang2020** [comment]
> 如果是源数据库binlog position发生了变更，canal是无法感知到并重置么？毕竟也不是所有复制都可以适合使用gtid模式

这个也是canal比较尴尬的地方

**Comment by misstt123** [comment]
因此要干啥？

**Comment by nakeiven** [comment]
参考这个老哥的方式 https://github.com/alibaba/canal/issues/4539 解决了，我的版本是 1.1.7
另外，先停 adapter，再停 deployer，启动时先启动deployer，再启动 adapter
