### ISSUE TITLE
canal+kafka新建主题时，分区数为1

### ISSUE THREAD

**Issue by huan415** [alibaba/canal#3339]
## Question

canal+kafka 触发同步之后(改源码指定发送到partition=1)，然后通过kafka命令去查topic信息，partition=1都是1。
canal.mq.partitionsNum=3  有设置这个，看这个好像跟新建主题的分区数没有关系。
请问是什么时候新建分区的，怎么指定kafka主题的分区数
![image](https://user-images.githubusercontent.com/37132274/106075057-e2c3ff00-6147-11eb-82d0-205a89b925d0.png)

**Comment by agapple** [comment]
kafka上手工创建topic并制定分区数
