### ISSUE TITLE
启动canal1.1.4 之后 过几秒日志报错 

### ISSUE THREAD

**Issue by privatesql** [alibaba/canal#3345]
启动以后 应该是装canal的kafka节点挂了
canal日志报错:
ERROR com.alibaba.otter.canal.kafka.CanalKafkaProducer - java.util.concurrent.ExecutionException: org.ap
ache.kafka.common.errors.TimeoutException: Failed to update metadata after 60000 ms.
java.lang.RuntimeException: java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.TimeoutException: Failed to update metadata af
ter 60000 ms.
kafka报错:WARN Bootstrap broker 1*****:9092 disconnected (org.apache.kafka.clients.NetworkClient)

**Comment by privatesql** [comment]
kafka_2.10-0.10.2.0-transwarp-6.0.2.jar
canal.deployer-1.1.4
是不是版本问题呢

**Comment by EngineerFromJiangxi** [comment]
从日志上看确实是connect kafka异常，你可以把源码下载在本地跑一下connect test,在此之前还是先去确认配置文件有没有问题

**Comment by privatesql** [comment]
分享一下解决办法,(我开启了kerberos) 1  先检查环境变量  我这边用docker搞得kafka
                                                             2   conf目录下canal.properties  的canal.properties目录设置
                                                             3   enable改成ture

**Comment by XU-JIANLIN** [comment]
> 分享一下解决办法,(我开启了kerberos) 1 先检查环境变量 我这边用docker搞得kafka
> 2 conf目录下canal.properties 的canal.properties目录设置
> 3 enable改成ture

是把什么enable 改成true呢？
