### ISSUE TITLE
使用Prometheus对canal监控后，发现无canal_instance_client_*的指标

### ISSUE THREAD

**Issue by MINCWANG** [alibaba/canal#3347]
## Question

![image](https://user-images.githubusercontent.com/33626973/106424207-c0f6af00-649c-11eb-824b-4459d14bc567.png)

![image](https://user-images.githubusercontent.com/33626973/106424714-9d803400-649d-11eb-8444-f4d17bf3276f.png)

**Comment by agapple** [comment]
instance client的指标目前没有，可以提交一个PR给我
