### ISSUE TITLE
产生了大量binlog，处理性能比较低，延迟很高

### ISSUE THREAD

**Issue by stevenxia2016** [alibaba/canal#3348]
请看监控截图 - [canal监控](https://images.cnblogs.com/cnblogs_com/silva/693842/o_210201090417%E5%BE%AE%E4%BF%A1%E5%9B%BE%E7%89%87_20210201170359.png)

已经Delay了2个多小时。 看到网络带宽 1M-2M，这个正常吗？ 这是服务器上的，照说这么多binlog，不应该只有这么点带宽啊..
看TPS(table rows) 600 TPS，好像也不高。

不知道大家在大量binlog的情况下，同步性能如何？

我这里看起来是不是哪里有问题？性能看起来不高。

（不知道在这里提问合适不？ Submit new issue..？）

**Comment by stevenxia2016** [comment]
我用的1.1.4版本，尝试了修改canal server参数，和adapter 同步线程个数等参数，然后没有什么改善。

**Comment by yuanweikang2020** [comment]
> 我用的1.1.4版本，尝试了修改canal server参数，和adapter 同步线程个数等参数，然后没有什么改善。

canal binlog解析会有很多重复并且写入kafka或者其他第三方存储或者消息队列是同步模式，这样本身就会性能很低

**Comment by guoming** [comment]
同问，这个问题没解决方案？
