### ISSUE TITLE
wiki架构图片无法加载

### ISSUE THREAD

**Issue by BoulCheng** [alibaba/canal#3352]
## Question

https://github.com/alibaba/canal/wiki/%E7%AE%80%E4%BB%8B
简介中架构、原理、设计相关的图片都无法加载

**Comment by tomatofrommars** [comment]
![企业微信截图_15636eb8-1f8d-412b-ad21-f5e71a5c9e7c](https://user-images.githubusercontent.com/16113120/199152913-1d827a67-468a-4293-b595-fe9d0439524e.png)
还是有问题啊
