### ISSUE TITLE
what `id` means in kafka json msg?

### ISSUE THREAD

**Issue by SE2AI** [alibaba/canal#3370]
Dear authors,

recently I use canal in mysql-kafka scenario. I find that lots of items composed in the JSON message, among which there is a `KEY` named `id`. But it's really difficult for me to guess what `id` means, even after searching the issue history.

So would you please explain `id` detailedly? 
Does it mean that batch query within a `commit` has same `id`? OR different `commit`s but their operation time are so close that they share the same `id`? 
Which one is right?

**Comment by yuanweikang2020** [comment]
> Dear authors,
> 
> recently I use canal in mysql-kafka scenario. I find that lots of items composed in the JSON message, among which there is a `KEY` named `id`. But it's really difficult for me to guess what `id` means, even after searching the issue history.
> 
> So would you please explain `id` detailedly?
> Does it mean that batch query within a `commit` has same `id`? OR different `commit`s but their operation time are so close that they share the same `id`?
> Which one is right?

batch_id

**Comment by yuanweikang2020** [comment]
> Dear authors,
> 
> recently I use canal in mysql-kafka scenario. I find that lots of items composed in the JSON message, among which there is a `KEY` named `id`. But it's really difficult for me to guess what `id` means, even after searching the issue history.
> 
> So would you please explain `id` detailedly?
> Does it mean that batch query within a `commit` has same `id`? OR different `commit`s but their operation time are so close that they share the same `id`?
> Which one is right?

view https://github.com/alibaba/canal/issues/3331#issuecomment-774842646

**Comment by SE2AI** [comment]
> view [#3331 (comment)](https://github.com/alibaba/canal/issues/3331#issuecomment-774842646)

many thanks
