### ISSUE TITLE
对于同一条数据的插入，更新，删除能有唯一的标识符确定顺序吗

### ISSUE THREAD

**Issue by colin0000007** [alibaba/canal#3373]
目前我按照position@filename来确定这个顺序，position是升序的，filename也是升序的，比如有以下position@filename
1233@bin_4510
115@bin_4511
1236@bin_4510
那么操作顺序为（升序，先按照文件名再按照position排序）：
1233@bin_4510
1236@bin_4510
115@bin_4511

请问我这样的理解对吗

**Comment by KaimingWan** [comment]
position是binlog里面的概念，binlog都是按顺序生成的。关于canal顺序性的问题，这篇文章可以看看，也许有帮助：http://47.98.150.183/topic/13/canal%E5%A6%82%E4%BD%95%E4%BF%9D%E8%AF%81%E6%95%B0%E6%8D%AE%E7%9A%84%E9%A1%BA%E5%BA%8F%E6%80%A7-%E7%9B%B8%E5%90%8C%E4%B8%BB%E9%94%AE%E4%B8%8A%E7%9A%84%E6%8F%92%E5%85%A5%E6%9B%B4%E6%96%B0%E5%92%8C%E5%88%A0%E9%99%A4%E4%BC%9A%E4%BF%9D%E8%AF%81%E9%A1%BA%E5%BA%8F%E5%90%97
