### ISSUE TITLE
使用canal admin+deployer那一套，怎么拿到最开始的binlog

### ISSUE THREAD

**Issue by QAQ707631836** [alibaba/canal#3379]
使用canal admin+deployer那一套，怎么拿到最开始的binlog。就类似Maxwell中的--from-beginning参数。
下面这几个参数配置了也没用。
canal.instance.master.address=x.x.x.x:oooo
canal.instance.master.journal.name=
canal.instance.master.position=4
canal.instance.master.timestamp=
canal.instance.master.gtid=

**Comment by keer-dai** [comment]
我也是遇到这个问题，请问如何解决的？

**Comment by QAQ707631836** [comment]
> 我也是遇到这个问题，请问如何解决的？

client用adapter，通过rest可以做全量同步初始化。
就像这样，curl http://localhost:8081/etl/rdb/mysql/test.yml -X POST 
不带参数就全量同步。
