### ISSUE TITLE
rowChage.getRowDatasList()数据为空

### ISSUE THREAD

**Issue by wcxbbff** [alibaba/canal#338]
mysql版本5.6.19
开启binlog 
ROW 类型
解析文件事件类型都是eventType: QUERY，无update insert事件类型 ，请问是什么原因
canal.zkServers=192.168.0.14:2181
canal.instance.global.spring.xml  配置  file-instance.xml 内存+文件就有数据
canal.instance.global.spring.xml   使用default-instance.xml HA 方式无数据

**Comment by KL3711** [comment]
请问这个问题怎么解决的
