### ISSUE TITLE
canal-admin使用docker方式启动问题

### ISSUE THREAD

**Issue by ElanYoung** [alibaba/canal#3382]
## 一直卡在start admin..

![image](https://user-images.githubusercontent.com/39727435/108537505-98ace400-72d5-11eb-9665-161a788bcb43.png)

请问该怎么解决呢

详细日志怎么看

**Comment by michaelfyc** [comment]
Encountered the same situation. Any solution to this?

**Comment by ElanYoung** [comment]
> Encountered the same situation. Any solution to this?

The memory problem, I have not found a solution to it, except to replace a little bigger memory

**Comment by michaelfyc** [comment]
> > Encountered the same situation. Any solution to this?
> 
> The memory problem, I have not found a solution to it, except to replace a little bigger memory

I see. Thanks for ur reply.

**Comment by Marxss** [comment]
我也遇到过同样的问题，发现是启动超时了（可能是机器性能低），你可以进docker把启动脚本中的超时时间设置长一点
