### ISSUE TITLE
the max size of buffer must not more than 1G!!!

### ISSUE THREAD

**Issue by fusida** [alibaba/canal#339]
if buffer = bufferSize * bufferMemUnit = 2G
than
 (bufferSize * bufferMemUnit) = 2097152*1024 > max length of int;
 cause endless loop in MemoryEventStoreWithBuffer.tryPut & checkFreeSlotAt
so that
 the max size of buffer = 1G!!!
why not use long type?

**Comment by agapple** [comment]
bufferSize = 2097152 ? 

过大的bufferSize，并不会对性能有很大的帮助哦，建议bufferSize控制在32768，基本就有几万的TPS
