### ISSUE TITLE
master.journal.name和master.position不生效

### ISSUE THREAD

**Issue by yourgf** [alibaba/canal#3391]
## Question
MySQL=5.7.26

在服务器端执行 show master status 显示：
File : mysql.binlog-000341
Position: 729696697

于是在instance配置中写为：
canal.instance.master.journal.name=mysql-bin.000341
canal.instance.master.position=729696697

但是instance启动后显示：
"postion":{"gtid":"","included":false,"journalName":"mysql-bin.000341","position":299,"serverId":622536076,"timestamp":1614457009000}
position=299，与配置不一致

另，不写上面两个参数的话，启动后仍然是这个结果

请问我什么地方配置有误吗？

**Comment by Lovzi** [comment]
你的instance里面应该又一个meta.dat, 里面记录了下次要拉取的位点信息，如果你想指定消费，可能需要删除这个文件，他会重新读取你的master.journal.name 和 master.position等配置

**Comment by yourgf** [comment]
> 你的instance里面应该又一个meta.dat, 里面记录了下次要拉取的位点信息，如果你想指定消费，可能需要删除这个文件，他会重新读取你的master.journal.name 和 master.position等配置

明白了，多谢
