### ISSUE TITLE
zookeeper挂了重启后，canal server的同步停止了

### ISSUE THREAD

**Issue by gongfangjun** [alibaba/canal#341]
canal运行中，zookeeper不知什么原因挂了，然后canal server开始报连不上zookeeper的错误，

于是stop了canal server，然后重启zookeeper、canal server和canal_client。

     重启后发现canal_client在getWithoutAck()这个地方卡住了，一直获取不到Message，所以同步

也就卡住了，经检查主库的日志，发瑞已经到了binlog.000446，而canal_server从zookeeper中

获取到的日志为binlog.000440，已经差了6个日志没有同步了。

    后来发现，cannal每同步一段时间，就会停住，过一段时间后，会继续同步，然后周而复始的

**Comment by agapple** [comment]
卡主的异常原因要看看，是否是表结构删除性质导致
