### ISSUE TITLE
bug: canal rabbitmq binlog id 重复

### ISSUE THREAD

**Issue by zxf-thingsmatrix** [alibaba/canal#3414]
### environment

* canal version = 1.1.5
* mysql version 5.7

![image](https://user-images.githubusercontent.com/65008815/111788402-ffd0af00-88fa-11eb-8f99-bb362ce6dcc2.png)

**Comment by binlaniua** [comment]
+1 
we use id duplicate removal,  find miss many data

**Comment by agapple** [comment]
可以考虑提交一个PR给我
