### ISSUE TITLE
canal 输出到kafka 做DDL操作 isDdl属性一直是false 

### ISSUE THREAD

**Issue by liu-hai** [alibaba/canal#3418]
## Question

mysql 版本：select version();   -： 5.7.32-log
DDL操作：
CREATE TABLE `pvuv_sink3` (
  `entity_code` varchar(256) NOT NULL,
  `pv` bigint(20) DEFAULT NULL,
  `dt` varchar(30) DEFAULT NULL,
  PRIMARY KEY (`entity_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
select version();
alter table pvuv_sink add sj timestamp;  
ALTER TABLE pvuv_sink CHANGE sj mytime int;
alter table pvuv_sink drop column sj;
DROP TABLE  pvuv_sink;

kafka中的消息：
{"data":null,"database":"flink-test","es":1616465996000,"id":485855,"isDdl":false,"mysqlType":null,"old":null,"pkNames":null,"sql":"CREATE TABLE `pvuv_sink3` (\r\n  `entity_code` varchar(256) NOT NULL,\r\n  `pv` bigint(20) DEFAULT NULL,\r\n  `dt` varchar(30) DEFAULT NULL,\r\n  PRIMARY KEY (`entity_code`)\r\n) ENGINE=InnoDB DEFAULT CHARSET=utf8","sqlType":null,"table":"pvuv_sink3","ts":1616465997090,"type":"CREATE"}

{
  "data": null,
  "database": "flink-test",
  "es": 1616465293000,
  "id": 485805,
  "isDdl": false,
  "mysqlType": null,
  "old": null,
  "pkNames": null,
  "sql": "alter table pvuv_sink drop column sj",
  "sqlType": null,
  "table": "pvuv_sink",
  "ts": 1616465293391,
  "type": "ALTER"
}

isDdl属性一直是: false
请问是配置的原因吗？我配置的创建表自动创建topic

**Comment by liu-hai** [comment]
安装的 canal.deployer-1.1.5-SNAPSHOT.tar.gz

**Comment by fengpiaoxue** [comment]
可与看下这个,原因表明了
https://github.com/alibaba/canal/issues/3446

**Comment by wlxzd** [comment]
问下 我的mq没有收到ddl相关的消息，是配置这个吧：canal.instance.filter.query.ddl = false
