### ISSUE TITLE
怎样才能把数据同步到从库

### ISSUE THREAD

**Issue by akfdgg** [alibaba/canal#342]
本人新手一个，有问题想请教各位
 环境：v1.0.24
 mysql：5.6
 问题：客户端已经运行成功，能捕获到主数据的二进制文件，但是怎样把二进制文件还原成从库的数据？

**Comment by stone-cheng** [comment]
我理解是你需要自己解析读到的entry，然后把它转成SQL在从库中执行。
Canal 并没有提供数据存储的。

**Comment by luyee** [comment]
现成的是otter   db-->db
