### ISSUE TITLE
【多表映射sql】更新同步ES  BUG: 可能会抛出NoSuchElementException异常 | ES没有更新部分字段

### ISSUE THREAD

**Issue by cmazxiaoma** [alibaba/canal#3421]
- [ ] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment

canal version 1.1.5-alpha-2
mysql version 5.7.27-log

### Issue Description
> Test.yml
```
SELECT
	p.id as _id,
	p.id as id,
	p.visit_number AS visitNumber,
	r.visit_number AS visitNumber1,
	t.visit_number AS visitNumber2,
	o.visit_number AS visitNumber3,
	c.visit_number AS visitNumber4,
	pr.visit_number AS visitNumber5,
	p.`status` AS status,
CASE
		r.service_type 
		WHEN 2 THEN
		o.operation_room 
		WHEN 5 THEN
		t.sickroom 
		WHEN 6 THEN
		c.operation_room ELSE '' 
	END AS operationRoom,
CASE
		r.service_type 
		WHEN 2 THEN
		o.operation_room_start_time 
		WHEN 5 THEN
		t.sickroom_start_time 
		WHEN 6 THEN
		c.operation_room_start_time ELSE '' 
	END AS operationRoomStartTime 
FROM
	table1 p
	LEFT JOIN table2 r ON r.visit_number = p.visit_number
	LEFT JOIN table3 t ON t.visit_number = r.visit_number
	LEFT JOIN table4 o ON o.visit_number = r.visit_number
	LEFT JOIN table5 c ON c.visit_number = r.visit_number
	LEFT JOIN table6 pr ON pr.visit_number = r.visit_number
```
* 问题1: 报错 ![image](https://user-images.githubusercontent.com/26736167/112573585-8fa8b880-8e27-11eb-8f48-51236a601f3c.png)
* 问题2: status字段没有更新

### Steps to reproduce
错误可以定位到`ES6xTemplate`的第325行, 也就是`getESDataFromDmlData`这个方法

![image](https://user-images.githubusercontent.com/26736167/112573843-1067b480-8e28-11eb-9e66-6b9565beb94c.png)

### Expected behaviour
* 上图问题1：
    * `fieldItem.getColumnItems().iterator().next()`可能会抛出`NoSuchElementException`异常(碰上`operationRoomStartTime`的`FieldItem`, 此时它的`columnItems`集合为空)
    ![image](https://user-images.githubusercontent.com/26736167/112575151-b9171380-8e2a-11eb-8fa5-afdfbfecbef2.png)

    * 主表字段更新的时候,不应该获取所有的select fields。这里只需要获取主表的tableItem的所有fields即可。
* 上图问题2:  dmlOld有status字段, 但是此时columnName是`status`，`dmlOld.containsKey(columnName)`会返回false，所以es不会更新status字段(同样的问题也存在`ESSyncService`的`void update(ESSyncConfig config, Dml dml)`中)

### Actual behaviour

![image](https://user-images.githubusercontent.com/26736167/112574518-66892780-8e29-11eb-9cf5-3f740afe83e9.png)

**Comment by agapple** [comment]
可以考虑提交一个PR给我
