### ISSUE TITLE
mysql关键字表名解析报错的实践情况

### ISSUE THREAD

**Issue by 263874120** [alibaba/canal#3422]
例如\`order\`这个表,本身是个关键字,我在跟踪源码过程中发现,如果使用反引号在启动时不会报错,但无法触发DML插入ES,这是由于dbTableEsSyncConfig中的内容是根据sql中定义的表名获取,因此其组合可能为example_DBNAME-\`order\`,而在DML操作时,日志显示DML中CommonMessage对象的table名称为order,被去掉了反引号,导致由于键不一致在执行sync方法时,dbTableEsSyncConfig.get获取的configMap为空,导致插入失败,建议增加对关键字表名反引号的处理

**Comment by agapple** [comment]
可以考虑提交一个PR给我
