### ISSUE TITLE
canal v1.1.5和ES v7.12.0启动报错哦

### ISSUE THREAD

**Issue by issyu-summer** [alibaba/canal#3424]
![f3b26b79084bc097881295822e77b55](https://user-images.githubusercontent.com/61642788/112812917-38694900-90b0-11eb-9552-ccb18cc67a75.png)

**Comment by pt20180323** [comment]
在canal-adapter 中conf目录 修改   application.yml  
![image](https://user-images.githubusercontent.com/37704583/113408350-c8c1c980-93e1-11eb-9d7b-e6cbab828f48.png)
这个name 根据
![image](https://user-images.githubusercontent.com/37704583/113408387-da0ad600-93e1-11eb-909a-51603c0b492c.png)
进行配置

**Comment by jiejie2018** [comment]
哇哦，是的

**Comment by storeds** [comment]
改了，但是并没有什么用还是报一样的错
