### ISSUE TITLE
是否支持只请查阅mysql 表的指定字段 和指定记录

### ISSUE THREAD

**Issue by liminghuid** [alibaba/canal#3431]
## Question

canal写kafka时,是否支持以下功能:
1, 若某表有10个字段, 只想往kafka里写其中5个字段,是否支持?
2, 同步某表数据时,是否支持自定义sql,如只想往kafka里写type=1的记录

**Comment by fakeSerious** [comment]
功能1可以通过配置 canal 字段拦截,“canal.instance.filter.black.regex，canal.instance.filter.field“；
而功能2：是无法通过配置实现,可以自己根据业务需求修改源码,毕竟canal有些版本跟kafka数据对接功能并不是很理想,重新二次开发是最直接有效的办法

**Comment by liminghuid** [comment]
多谢

**Comment by vhypnus** [comment]
canal.instance.filter.field，我设置了不能过滤指定字段，请问如何处理
