### ISSUE TITLE
在开启tsdb的情况下，修改表结构之后，还是出现问题

### ISSUE THREAD

**Issue by wyb92** [alibaba/canal#3435]
## Question

最近发现一个问题，在开启tsdb的情况下，修改表结构之后，有的时候需要删除h2.mv.db缓存文件，重启就好了。但是有的修改表结构，不重启也没有问题。正常情况下应该不需要重启的。很奇怪，到底是什么影响到了表结构缓存。

**Comment by yonggandeliuguang** [comment]
是不是没有给Select权限给用户
CREATE USER canal IDENTIFIED BY 'canal';  
GRANT SELECT, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'canal'@'%';
-- GRANT ALL PRIVILEGES ON *.* TO 'canal'@'%' ;
FLUSH PRIVILEGES;

**Comment by wyb92** [comment]
权限是赋了的。额，可能还有其他问题吗？

**Comment by yonggandeliuguang** [comment]
> 权限是赋了的。额，可能还有其他问题吗？

那这我也不太清除了哦，我配置文件position是默认，并没有其它问题了，tsdb的配置是不需要改的，不知道你改过没

**Comment by wyb92** [comment]
额，这个没改过。还有这种情况，canal server做了HA之后，另外一台一直没有真正使用。但是后面切过去的时候，就报CanalParseException。删除h2文件又好了。这种的你有碰到过吗？

**Comment by yonggandeliuguang** [comment]
> 额，这个没改过。还有这种情况，canal server做了HA之后，另外一台一直没有真正使用。但是后面切过去的时候，就报CanalParseException。删除h2文件又好了。这种的你有碰到过吗？

哦，没有哦，我暂时是单机的

**Comment by fengpiaoxue** [comment]
tsdb开启之后,如果用的本地文件. 那么读取到ddl 变化之后.只会修改本机的 h2文件. 如果发生主备切换.备节点的h2文件不是最新的数据,这时候解析就报错了.

**Comment by fengpiaoxue** [comment]
tsdb开启之后,如果用的本地文件. 那么读取到ddl 变化之后.只会修改本机的 h2文件. 如果发生主备切换.备节点的h2文件不是最新的数据,这时候解析就报错了.

**Comment by fengpiaoxue** [comment]
tsdb开启之后,如果用的本地文件. 那么读取到ddl 变化之后.只会修改本机的 h2文件. 如果发生主备切换.备节点的h2文件不是最新的数据,这时候解析就报错了. 修改成使用mysql去存储tsdb数据就好了.

**Comment by yonggandeliuguang** [comment]
> tsdb开启之后,如果用的本地文件. 那么读取到ddl 变化之后.只会修改本机的 h2文件. 如果发生主备切换.备节点的h2文件不是最新的数据,这时候解析就报错了. 修改成使用mysql去存储tsdb数据就好了.

有道理哦，那你解决了吗

**Comment by fengpiaoxue** [comment]
换成mysql之后就解决了啊

**Comment by fengpiaoxue** [comment]
> > tsdb开启之后,如果用的本地文件. 那么读取到ddl 变化之后.只会修改本机的 h2文件. 如果发生主备切换.备节点的h2文件不是最新的数据,这时候解析就报错了. 修改成使用mysql去存储tsdb数据就好了.
> 
> 有道理哦，那你解决了吗

换成mysql之后就解决了啊

**Comment by yonggandeliuguang** [comment]
> > > tsdb开启之后,如果用的本地文件. 那么读取到ddl 变化之后.只会修改本机的 h2文件. 如果发生主备切换.备节点的h2文件不是最新的数据,这时候解析就报错了. 修改成使用mysql去存储tsdb数据就好了.
> > 
> > 
> > 有道理哦，那你解决了吗
> 
> 换成mysql之后就解决了啊

嗯嗯

**Comment by imzhouhao** [comment]
> > > tsdb开启之后,如果用的本地文件. 那么读取到ddl 变化之后.只会修改本机的 h2文件. 如果发生主备切换.备节点的h2文件不是最新的数据,这时候解析就报错了. 修改成使用mysql去存储tsdb数据就好了.
> > 
> > 
> > 有道理哦，那你解决了吗
> 
> 换成mysql之后就解决了啊

**Comment by imzhouhao** [comment]
> > > tsdb开启之后,如果用的本地文件. 那么读取到ddl 变化之后.只会修改本机的 h2文件. 如果发生主备切换.备节点的h2文件不是最新的数据,这时候解析就报错了. 修改成使用mysql去存储tsdb数据就好了.
> > 
> > 
> > 有道理哦，那你解决了吗
> 
> 换成mysql之后就解决了啊

我也遇到这个问题了，tsdb现在有三个问题，一是scheme没有持久化的问题，二是ddl解析是否准确，三是从tsdb获取的scheme，如何判断其是可靠的。第一个问题很好解决，剩下两个问题不知道如何解决，请问你有遇到相同问题么
