### ISSUE TITLE
1.1.5版本设置是否是ddl逻辑判断有误

### ISSUE THREAD

**Issue by fengpiaoxue** [alibaba/canal#3446]
1.15 版本 
![image](https://user-images.githubusercontent.com/42439600/113843913-92f85880-97c6-11eb-80c3-14d1dca8225c.png)

1.14 && 1.13 版本
![image](https://user-images.githubusercontent.com/42439600/113844113-bde2ac80-97c6-11eb-8b79-6ea9ce39aa84.png)

1.15版本判断给位 == 之后 isDdl 值设置不对. 源码位于 parse 模块 com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvertcom.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert  类

**Comment by agapple** [comment]
最新代码做了修复

**Comment by wlxzd** [comment]
问下 我的mq没有收到ddl相关的消息，是配置这个吧：canal.instance.filter.query.ddl = false
