### ISSUE TITLE
使用rabbitMQ，结合admin一起使用，远程关闭server报错，源码中存在bug

### ISSUE THREAD

**Issue by David0825** [alibaba/canal#3447]
- [ ] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment

* canal 1.1.5

### Issue Description
使用rabbitMQ，结合admin一起使用，远程关闭server报错，原因是在stop时，关闭rabbitMQ的channel时，connection已经被先关闭了

```

**Comment by agapple** [comment]
最新代码已修复
