### ISSUE TITLE
canal普通启动，自动绑定到docker的地址？？

### ISSUE THREAD

**Issue by issyu-summer** [alibaba/canal#3449]
## Question

![image](https://user-images.githubusercontent.com/61642788/114274268-34460f80-9a50-11eb-8acf-23b2d7a3caf1.png)

**Comment by issyu-summer** [comment]
![Uploading image.png…]()

**Comment by issyu-summer** [comment]
![image](https://user-images.githubusercontent.com/61642788/114274311-5e97cd00-9a50-11eb-872f-ba277c2a629c.png)

**Comment by agapple** [comment]
会自动识别本机ip

**Comment by gzpingtouge** [comment]
可以在/conf/canal.properties配置文件自动IP
# tcp bind ip
canal.ip = xxx,.xxx.xxx.xxx
