### ISSUE TITLE
canal为什么获取tableName和schemaName为空 

### ISSUE THREAD

**Issue by wjk1982** [alibaba/canal#345]
header {
  version: 1
  logfileName: "mysql-bin.000068"
  logfileOffset: 719945754
  serverId: 125
  serverenCode: "UTF-8"
  executeTime: 1500862055000
  sourceType: MYSQL
  schemaName: ""
  tableName: ""
  eventLength: 217
  eventType: QUERY
}
entryType: ROWDATA
storeValue: "\020\aZ\301\001insert into productinfotemp(SysId,Price,RealityPrice,SkuCount,Name,Code,SaleDate,Status) values (\'eab6d30a-2436-4c3b-b493-3c997fd8d8fb\',10.00,10.00,1.00,\'\',\'E0205004\',\'2017-07-24 00:00:00 \',99)"

**Comment by agapple** [comment]
QUERY语句，不是ROW模式的行记录吧

**Comment by yufeng0528** [comment]
我也有很多这样的数据
insert，update都有

2017-09-12 14:09:57,417[INFO]yike.canal.AbstractCanalClientTest.printEntry(AbstractCanalClientTest.java:206)
----------------> binlog[mysql-bin.002059:3086158] , name[xmall,] , eventType : UPDATE , executeTime : 1505196597000 , delay : 417ms
2017-09-12 14:09:57,417[INFO]yike.canal.AbstractCanalClientTest.printEntry(AbstractCanalClientTest.java:206)
----------------> binlog[mysql-bin.002059:3086397] , name[xmall,] , eventType : INSERT , executeTime : 1505196597000 , delay : 417ms
2017-09-12 14:09:57,606[INFO]yike.canal.AbstractCanalClientTest.printSummary(AbstractCanalClientTest.java:155)

**Comment by 4rnold** [comment]
entry.getHeader().getTableName() 为空，什么原因？RowChange中能取到sql语句。
![](http://o8n1hrt12.bkt.clouddn.com/2017-10-24-17-59-05.png) 
![](http://o8n1hrt12.bkt.clouddn.com/2017-10-24-18-00-46.png)

**Comment by agapple** [comment]
canal新版本已经通过SQL解析工具，完整提取tableName，schemaName在binlog里无记录

**Comment by wangruyu1** [comment]
> header {
> version: 1
> logfileName: "mysql-bin.000068"
> logfileOffset: 719945754
> serverId: 125
> serverenCode: "UTF-8"
> executeTime: 1500862055000
> sourceType: MYSQL
> schemaName: ""
> tableName: ""
> eventLength: 217
> eventType: QUERY
> }
> entryType: ROWDATA
> storeValue: "\020\aZ\301\001insert into productinfotemp(SysId,Price,RealityPrice,SkuCount,Name,Code,SaleDate,Status) values ('eab6d30a-2436-4c3b-b493-3c997fd8d8fb',10.00,10.00,1.00,'','E0205004','2017-07-24 00:00:00 ',99)"

你好，你这个问题还记得吗？解决没有

**Comment by wangruyu1** [comment]
> canal新版本已经通过SQL解析工具，完整提取tableName，schemaName在binlog里无记录

我用1.1.4为什么有时候能获取schemaName,有时候又不能呢？

**Comment by fankiwu** [comment]
binlog_direct_non_transactional_updates=ON
数据库配置加这个试试
