### ISSUE TITLE
mysql使用utf8mb4出现中文乱码

### ISSUE THREAD

**Issue by toruneko** [alibaba/canal#347]
![image](https://user-images.githubusercontent.com/5357638/28571083-c7fade36-7173-11e7-8cef-2484de5b1b04.png)
具体乱码的部分是这样的。因为有一些业务敏感字段，所以打了码，见谅。

**Comment by toruneko** [comment]
找到问题了。不是canal的问题、。

**Comment by dlnufox** [comment]
原因是什么呢，我也遇到类似的问题

**Comment by toruneko** [comment]
记不太清楚了。好像是我们用的druid版本太低还是什么。我再想想……
