### ISSUE TITLE
关于batch消费失败后重新获取的问题

### ISSUE THREAD

**Issue by xy720** [alibaba/canal#3471]
1、batch Id是一直自增的吗，如果中间出现了rollback，下一次个get的时候id是不变还是+1？
2、如果消费batch失败了，rollback此batch后再次get，获取的新batch的起始和结束位置是否会和上一次消费失败的batch一样？

**Comment by ujijuji** [comment]
> 1、batch Id是一直自增的吗，如果中间出现了rollback，下一次个get的时候id是不变还是+1？
> 2、如果消费batch失败了，rollback此batch后再次get，获取的新batch的起始和结束位置是否会和上一次消费失败的batch一样？

第一个如果metaManager是内存模式的话是递增且唯一的，zk模式不太清楚，不过应该也是递增的吧。
第二个是一样的，看了下代码新batch的起始位置是根据cursor来判断的，只有在消费成功的时候才会提交cursor。

**Comment by xy720** [comment]
> > 1、batch Id是一直自增的吗，如果中间出现了rollback，下一次个get的时候id是不变还是+1？
> > 2、如果消费batch失败了，rollback此batch后再次get，获取的新batch的起始和结束位置是否会和上一次消费失败的batch一样？
> 
> 第一个如果metaManager是内存模式的话是递增且唯一的，zk模式不太清楚，不过应该也是递增的吧。
> 第二个是一样的，看了下代码新batch的起始位置是根据cursor来判断的，只有在消费成功的时候才会提交cursor。

我只看了内存模式的代码，我发现rollback后新batch的起始位置确实是上一次ack成功的位置..
但是，rollback后重新消费的位置却不是cursor的位置，而是store内记录的上一次ack到的位置，这两个位置是不一样的
实际上cursor的位置更新后是上一次消费的batch内最后一条事务的开头(batch的最后一条事务可能只有一半数据)，
而且只有重新订阅时才会从cursor位置再次消费
