### ISSUE TITLE
先全量，再增量同步的操作步骤？

### ISSUE THREAD

**Issue by bglmmz** [alibaba/canal#3474]
## Question

看到说，可以通过使用 adapter 的 REST 接口手动触发 ETL 任务，实现全量同步。同时看到说，在全量同步时，在同一个 destination 的增量同步任务会被 阻塞，待全量同步完成被阻塞的增量同步会被 重新唤醒。

那就有个问题：在业务不停的情况下，即MySQL数据既有大量存量数据（部分binlog已经删除），又在不停增加的情况下。是
1. 先手工触发全量同步，完成后再启动adapter？这个好像比较符合逻辑，只是启动adapter后，如何保证增量是刚好接着全量最后一条记录开始的？
2. 还是首先启动adapter，再手工触发全量同步？这个顺序的话，adapter同步了一部分增量，再手工触发全量的话，以前增量同步的会不会重复同步？而且同样有全量结束后，adapte重新开始后，是如何接上的问题？

还是说，在全量同步时，业务要暂停，等全量同步结束后，在启动adapter和业务？那这样，也有增量同步如何接上的问题？

谢谢！

**Comment by yonggandeliuguang** [comment]
全量和增量都是在adapter完成的，所以这个不管如何都是需要启动的，先启动 deployer，再启动adapter，启动后就会自动增量更新，然后随时可以全量更新，全量更新时会暂停增量更新，然后重复的主键，数据会覆盖(反正都是最新的)，全量完成后，在全量过程中发生的增量会消费回来，不用担心。

**Comment by bglmmz** [comment]
多谢楼上答疑解惑！

**Comment by usedssl** [comment]
数据不会覆盖，是先删除在新增

**Comment by yangkaiShi** [comment]
我感觉canal-adapter它在进行全量同步的时候是有一点问题的，没法保证数据一致性。
假如数据库有200万数据需要全量同步到es，假设花费一个小时。canal-adapter在同步之前，先获取总条数(200万)，然后使用线程池分批插入（批次=200，每批最多1万条数据，使用limit）。如果已经插入了100批的数据（共100万），这时又在第1页插入了数据（1万条），那么最后是否会造成数据丢失？
我感觉会丢失数据，因为是用的limit，源码中的循环限制了最后只取到第200批，但最后可能数据不止200批。

**Comment by AlfredNing** [comment]
canal-adpater是不是没法保证数据一致性，有唯一索引这种，源码上根据主键分区，并发执行这里，是不是有问题

**Comment by usedssl** [comment]
没问题啊，上面已经说了，在全量更新时用zk分布式锁会停掉增量更新



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月29日(周三) 中午11:13
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [alibaba/canal] 先全量，再增量同步的操作步骤？ (#3474)




 
canal-adpater是不是没法保证数据一致性，有唯一索引这种，源码上根据主键分区，并发执行这里，是不是有问题

**Comment by AlfredNing** [comment]
其实我想问的是，在增量同步期间也是拉到一批数据，根据主键值分配到不同任务dmlPartitions里面，然后执行每个分区的任务吗。

**Comment by hashmapybx** [comment]
如何将做全量同步到kafka呢。目前我看canal-deployer只支持增量同步到kafka,历史数据是无法同步

**Comment by usedssl** [comment]
历史数据有全量同步的接口，可以看一下client-adapter - launcher&nbsp; 的 CommonRest.java的接口功能
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/canal"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月9日(星期四) 下午3:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/canal] 先全量，再增量同步的操作步骤？ (#3474)





 
如何将做全量同步到kafka呢。目前我看canal-deployer只支持增量同步到kafka,历史数据是无法同步

**Comment by zy-uu** [comment]
看到有说 “全量完成后，在全量过程中发生的增量会消费回来”，想请问这个这个是怎么实现的呢 ？ 我好像在代码中没有看到 .
