### ISSUE TITLE
能不能完善一下dockerhub的文档

### ISSUE THREAD

**Issue by angleGhost** [alibaba/canal#3490]
## Question

dockerhub仓库文档写得什么啊，啥也没有，一部署到处报错，感觉就是敷衍的上传一个镜像

**Comment by RainingNight** [comment]
哈哈哈，同感，而且使用MQ模式时没办法使用环境变量配置MQ连接信息。

**Comment by aaaweisen** [comment]
支持，确实文档应该完善一下子，我现在都是自己构建镜像的，比较麻烦！

**Comment by mailbyms** [comment]
Dockerfile 里写得很初级很业余的，都不敢相信是阿里巴巴出品。  
镜像里居然有个 /home/admin/node_exporter-0.18.1.linux-arm64 ，这是什么鬼，x86 的镜像里弄个 arm 的应用   
没有用多阶段构建，导致镜像超大  
启动镜像居然是用 .sh 脚本，起码给个 docker-compose.yml 吧  
真的很敷衍

**Comment by agapple** [comment]
有想法的可以提交一个PR给我
