### ISSUE TITLE
求分享：各位是否有迁移canal server的经验

### ISSUE THREAD

**Issue by justde** [alibaba/canal#3491]
我们需要迁移机房，涉及到MySQL、zk、canal server。
目前是打算把zk、canal server平移过去，然后修改canal中配置的MySQL信息和zk中的/otter/canal/destinations/${my_instance}/1001节点中的binlog游标信息。

请问以上操作可以保证启动新环境canal服务直接从原binlog点位开始同步么？

**Comment by renyansongno1** [comment]
我感觉可以在新的机房直接新启动canal，然后写好binlog的起点，下游消费服务做好幂等呢

**Comment by justde** [comment]
> 我感觉可以在新的机房直接新启动 canal，然后写好 binlog 的起点，下游消费服务做好幂等呢

感谢！
之前没有接触过canal，这两天看了下canal相关文档，正如您所说，可以通过指定binlog点位信息来无缝衔接。

我准备新环境的zk集群不迁移旧的canal相关数据，然后在新canal配置文件instance.properties的
canal.instance.master.journal.name=
canal.instance.master.position=
两个配置项写入从旧zk查到的binlog点位信息，然后重启canal。按照文档，会自动读取该配置文件并且写入到zk中。

今天晚上准备在测试环境试一下

**Comment by godchou** [comment]
选择instance，点击修改，进入instance的配置界面，点击上面可以修改服务器

**Comment by JiangRunqiang** [comment]
> 入instance的配置界面，点击上面可以修改服务器

感谢
