### ISSUE TITLE
能否设置只监听表的insert 和 update

### ISSUE THREAD

**Issue by farsunset** [alibaba/canal#3497]
因为在归档或者迁移数据时 会删除大量数据，这样的场景下有些业务其实并不需要发送MQ，不知道有没有支持配置只监听insert 和update

**Comment by agapple** [comment]
有的，可以配置忽略某一类的binlog事件
```
canal.instance.filter.dml.insert = false
canal.instance.filter.dml.update = false
canal.instance.filter.dml.delete = false
```

**Comment by yansheng105** [comment]
> 有的，可以配置忽略某一类的binlog事件
> 
> ```
> canal.instance.filter.dml.insert = false
> canal.instance.filter.dml.update = false
> canal.instance.filter.dml.delete = false
> ```

请问这个是instance的配置项还是server的配置项，我都试了一下貌似没效果啊

**Comment by feng99** [comment]
> insert

这几项配置  现在被删除了吗?  文档中  为何找不到了.
https://github.com/alibaba/canal/wiki/AdminGuide

**Comment by farsunset** [comment]
目前还是有用的，canal项目怎么说呢 文档不够清晰，还一堆bug，凑合着用吧
> > insert
> 
> 这几项配置 现在被删除了吗? 文档中 为何找不到了.
> https://github.com/alibaba/canal/wiki/AdminGuide
