### ISSUE TITLE
canal解析json类型出错

### ISSUE THREAD

**Issue by lan1994** [alibaba/canal#350]
和#330中提到的问题一致，mysql版本是5.7
sql如下：
a='"a"'+',"a"'*30000
sql="insert into canal_json_test(j_json) values('[%s]')" % (a)
即一个json字段的值为'["a","a","a"……]' 共30001个a，可以正常插入mysql，但是canal解析这个出错了

**Comment by lan1994** [comment]
和#330中提到的问题一致，
sql如下：
a='"a"'+',"a"'*30000
sql="insert into canal_json_test(j_json) values('[%s]')" % (a)
即一个json字段的值为'["a","a","a"……]' 共30001个a，可以正常插入mysql，但是canal解析这个出错了

**Comment by agapple** [comment]
我尽快修复一下，应该不难

**Comment by lan1994** [comment]
我已经试着修复了，应该是获取json值长度的时候用了getUnit16导致的，应该是用getUnit32吧
