### ISSUE TITLE
[Canal 1.1.5]deployer模块中，CanalController类重复代码优化

### ISSUE THREAD

**Issue by JasonCeng** [alibaba/canal#3500]
## Why you need it?

[Canal 1.1.5]deployer模块中，CanalController类中的initGlobalConfig和parseInstanceConfig方法重复代码较多，建议优化

## How it could be?

initGlobalConfig和parseInstanceConfig方法的相似部分建议提取为一个独立的方法

## Other related information

暂无

**Comment by agapple** [comment]
可以提交一个PR给我
