### ISSUE TITLE
【严重问题】数据库CPU莫名其妙居高不下，干掉canal dump binlog的线程后恢复正常

### ISSUE THREAD

**Issue by michael-liumh** [alibaba/canal#3501]
今天晚上接到CPU告警，一直居高不小，show processlist查看有哪些连接在跑，发现只有几个update语句在跑，update的表只有3万行，表有索引，一次update一行，正常情况下数据库CPU不应该那么高，然后我发现出了几个update语句外，就只有canal在拉取数据了，于是把canal干掉后，CPU直接就掉下来了。。。。看日志发现，某条日志重复出现了N遍，具体日志为：2021-05-04 20:41:20.337 - clientId:1001 cursor:[mysql-bin.001361,244220740,1620132080000,4093711201,b2ff1e79-9e03-11eb-9d42-b8599f33171b:1-209851388,df8952d2-0e95-11eb-af4f-0c42a14d6a62:1-1365296514] address[172.16.0.6/172.16.0.6:3306]
![image](https://user-images.githubusercontent.com/40595864/117006761-67ac4f00-ad1b-11eb-85c4-acc7d86502d3.png)
![image](https://user-images.githubusercontent.com/40595864/117006969-a4784600-ad1b-11eb-9b72-75d8b28fc76a.png)

查看拉取canal的机器，内存也是爆满的，怀疑是canal dump binlog过于频繁了，canal.adapter有频率限制方面的配置，但是canal.developer貌似并没有？

**Comment by agapple** [comment]
感觉是在大量重复消费，得检查下canal-server是否出现解析异常
