### ISSUE TITLE
batchSize指什么

### ISSUE THREAD

**Issue by lianqu1990** [alibaba/canal#351]
您好，试了下 有阻塞的getWithoutAck，发现在更新到很多次的时候才会打印(example)，但是batchSize设置的是1.

有点不太明白，batchSize到底指的是什么，我以为是一次修改，目前看应该不是的。

Batch Id: [3] ,count : [33] , memsize : [1050] , Time : 2017-07-29 23:52:08
* Start : [mysql-bin.000003:17576:1501343167000(2017-07-29 23:46:07)] 
* End : [mysql-bin.000003:19943:1501343529000(2017-07-29 23:52:09)] 

这是打印的日志。 

麻烦~

**Comment by lan1994** [comment]
batchSize 是在client端设置的，这个参数作用是控制 每次从server端的store中get数据的size

**Comment by lianqu1990** [comment]
那这个并不等于   数据库的一次修改是把？因为上面看的，一次有33个entries。  这个是在什么情况下server才会有一条数据啊

**Comment by wuchaooooo** [comment]
是啊，我也不是很明白batchSize具体的作用。当我设置batchSize=1的时候，每次拉取到的Message里面，是有多个entry的。

**Comment by agapple** [comment]
batchSize是刚好超过这个大小的，最合适的记录数.  最小是1个Message

**Comment by wuchaooooo** [comment]
@agapple 嗯嗯～谢谢啦
