### ISSUE TITLE
最新版本的canal-server docker启动的时候，如何通过参数指定kafka机器地址？

### ISSUE THREAD

**Issue by feideyang** [alibaba/canal#3515]
### -e kafka.bootstrap.servers=192.168.220.12:9092 这种方式又不生效，而且官方文档也没给出说明

**Comment by puppylpg** [comment]
canal的配置文档真的很不上心……看着有，实际跟没写差不多……

**Comment by puppylpg** [comment]
看了一下代码，原因应该是：其他变量都是先尝试从system env里读，再从canal.properties里读。而kafka的配置是直接从canal.properties里读的。所以给kafka设置环境变量没用。
