### ISSUE TITLE
要不考虑配置列的黑名单吧？忽略掉这个大列，其他的没啥好办法

### ISSUE THREAD

**Issue by best11589835** [alibaba/canal#3521]
要不考虑配置列的黑名单吧？忽略掉这个大列，其他的没啥好办法

_Originally posted by @agapple in https://github.com/alibaba/canal/issues/2233#issuecomment-539441012_

**Comment by best11589835** [comment]
怎么能配置列的黑名单,目前只看到表的黑名单

**Comment by Tsuiwiki** [comment]
可以在adapter表字段映射里面忽略该字段：
![image](https://user-images.githubusercontent.com/8910013/118746911-a0a40200-b88b-11eb-9b9e-5d418e250de3.png)
