### ISSUE TITLE
获取mysql中字段类型为point或是linestring的字段时乱码

### ISSUE THREAD

**Issue by clip-tail** [alibaba/canal#3525]

**Comment by agapple** [comment]
它是一个byte[]类型，需要业务按照二进制处理

**Comment by clip-tail** [comment]
> 
> 
> 它是一个byte[]类型，需要业务按照二进制处理

我的代码是这么处理的，结果还是乱码
![图片](https://user-images.githubusercontent.com/49085472/140873789-1d1adf7b-e9b0-4b77-88fe-e7dbbf17174c.png)

**Comment by Beauxie** [comment]
> > 它是一个byte[]类型，需要业务按照二进制处理
> 
> 我的代码是这么处理的，结果还是乱码 ![图片](https://user-images.githubusercontent.com/49085472/140873789-1d1adf7b-e9b0-4b77-88fe-e7dbbf17174c.png)

请问解决了吗，同样遇到了这个问题
