### ISSUE TITLE
canal如何配置多个数据库下的表

### ISSUE THREAD

**Issue by fuchun** [alibaba/canal#353]
请问下，canal如何指定订阅几个数据库的若干表，比如我只订阅 oschina库下的order表和oschina_user下的user表

**Comment by luyee** [comment]
翻翻之前的issue

**Comment by luyee** [comment]
正确的姿势应该是client写入filter,see https://github.com/alibaba/canal/issues/311

**Comment by luyee** [comment]
多个库？ 多个instance吧
