### ISSUE TITLE
Canal Admin修改密码且密码长度小于6，修改成功后，无法登录Canal  Admin

### ISSUE THREAD

**Issue by fchunbo** [alibaba/canal#3531]
本地将初始密码：123456，修改为：admin，再次登录的时候，无法登录，提示：**The password can not be less than 6 digits**

**Comment by dearcode2018** [comment]
最新版本不用配置文件中的密码，在canal_manager.canal_user.password 设置密码 密码生成方式:  String password = com.alibaba.otter.canal.protocol.SecurityUtil.scrambleGenPass("admin123".getBytes());

**Comment by agapple** [comment]
LS正解

**Comment by viaviaviavia** [comment]
> 最新版本不用配置文件中的密码，在canal_manager.canal_user.password 设置密码 密码生成方式: String password = com.alibaba.otter.canal.protocol.SecurityUtil.scrambleGenPass("admin123".getBytes());

没看懂呀，是要本地自己加密一下吗？  不用java的怎么办

**Comment by viaviaviavia** [comment]
数据库录入的是：6BB4837EB74329105EE4568DDA7DC67ED2CA2AD9，  启动的时候设置 canal.adminPasswd=123456
