### ISSUE TITLE
关于binlog枚举值解析探讨

### ISSUE THREAD

**Issue by yl-yue** [alibaba/canal#3536]
## 我的问题
关于binlog枚举值解析时，发现得到的是枚举下标而非枚举值，当我把这份数据同步至es后，es中就会存在即有枚举下标又有枚举值的情况，造成数据错误。

## 与此问题相关的票据
我确认了下canal的历史票据 #157 #1008 #1925 #2610 #2813 ，关于此问题的探讨在很久之前就已开始了。

## 此类问题能否有个最终导向？
基于上述提到的票据和我个人的了解，貌似这是binlog的存储机制，而非canal的错误。所以这个问题在binlog没有相应的配置之前，我的理解是无法妥善解决的。
那么是否有必要开个专题页面或者在常见问题中特殊说明一下，避免大家走弯路。

## 推荐解决方案
1. 通过映射枚举类反序列化
2. 修改mysql enum类型为varchar

**Comment by vincentwc** [comment]
我也遇到了同样的问题，第一次做数据同步的先关工作，目前还没有找到解决办法，有没有大佬可以提供下思路的，谢谢

**Comment by agapple** [comment]
message里包含了type类型，需要在应用多基于下标转化为枚举的文本值
