### ISSUE TITLE
admin单节点故障后集群内server无法切换

### ISSUE THREAD

**Issue by Rong11010523** [alibaba/canal#3541]
## Question

测试功能发现单节点admin故障后，不能实现server的HA切换，并且重启后需要收恢复。请问，现有针对admin的高可用方案么

**Comment by agapple** [comment]
admin需要部署一个多节点，它本身是无状态的。server的HA依赖zookeeper

**Comment by Fanduzi** [comment]
那么canal.admin.manager是可以像kafka broker那样写多个吗？ 还是说我canal admin自己搞个域名？ 多个canal admin公用一个mysql？

**Comment by RekiOwl** [comment]
老哥，这个解决了么，是要自己配域名搞负载，还是本身支持多节点的？
