### ISSUE TITLE
mysql 修改字段或新增字段后es同步失效问题

### ISSUE THREAD

**Issue by hatakes** [alibaba/canal#3545]
## Question

mysql 修改字段或者新增字段后,canal同步到es就失效了,有时候停机canal,修改同步的用的yml,新建es索引,canal同步还是失效的.
mysql修改字段后 canal 这边正确的处理应该是什么呢?

**Comment by xltxb** [comment]
停止adapter ，删除索引并重建，修改yml文件，启动adapter
我这边的流程是这样的。

**Comment by dc1209** [comment]
停掉adapter，删除h2.mv.db文件，重启adapter

**Comment by hatakes** [comment]
> 停止adapter ，删除索引并重建，修改yml文件，启动adapter，重新同步存量数据。
> 我这边的流程是这样的。

**Comment by hatakes** [comment]
> > 停止adapter ，删除索引并重建，修改yml文件，启动adapter，重新同步存量数据。
> > 我这边的流程是这样的。



> 停止adapter ，删除索引并重建，修改yml文件，启动adapter，重新同步存量数据。
> 我这边的流程是这样的。



> ## Question
> mysql 修改字段或者新增字段后,canal同步到es就失效了,有时候停机canal,修改同步的用的yml,新建es索引,canal同步还是失效的.
> mysql修改字段后 canal 这边正确的处理应该是什么呢?



> 停掉adapter，删除h2.mv.db文件，重启adapter

停掉之后的话,es那边索引还需要重新建立吗,

**Comment by hatakes** [comment]
> 停止adapter ，删除索引并重建，修改yml文件，启动adapter，重新同步存量数据。
> 我这边的流程是这样的。

好的非常感谢,我试一下之前,应该是没有先停止adpter的原因,数据不能正常同步,
