### ISSUE TITLE
DDL-alter这种语句如何同步

### ISSUE THREAD

**Issue by gaoqiang-0327** [alibaba/canal#3546]
canal 1.1.14
MySQL 8.0.23
数据同步MySQL到MySQL。
上游执行一条添加字段的SQL语句，可以解析出来，但是下游不执行，不生效。该如何配置参数，可以实现吗？
 INFO  c.a.o.canal.client.adapter.logger.LoggerAdapterExample - DML: {"data":null,"database":"gq_test","destination":"example","es":1621578218000,"groupId":null,"isDdl":true,"old":null,"pkNames":null,"sql":"Alter table `gq_test`.
`t`   \r\n\tadd column `address` varchar(100) DEFAULT '' NOT NULL after `ip`","table":"t","ts":1621578218957,"type":"ALTER"}

**Comment by wlxzd** [comment]
这个问题搞定了吗 兄弟 ddl语句可以发送给mq吗
