### ISSUE TITLE
canal1.1.5对接阿里云RocketMQ问题

### ISSUE THREAD

**Issue by nikolabai** [alibaba/canal#3549]
canal.mq.flatMessage = false的情况下
报错Caused by: org.apache.rocketmq.client.exception.MQBrokerException: CODE: 1  DESC: the topic[***] is batch send , not support. BROKER

**Comment by nikolabai** [comment]
阿里云rocketmq不支持批量发送

**Comment by MrJXL** [comment]
那要怎么处理

**Comment by MrJXL** [comment]
我线上也遇到这个问题了，需要怎么处理

**Comment by nikolabai** [comment]
改下canal源码，发送消息的地方改为非批量，或者不使用json消息，客户端解析protobuf数据

**Comment by nikolabai** [comment]
> 我线上也遇到这个问题了，需要怎么处理


改下canal源码，发送消息的地方改为非批量，或者不使用json消息，客户端解析protobuf数据

**Comment by MrJXL** [comment]
> > 我线上也遇到这个问题了，需要怎么处理
> 
> 改下canal源码，发送消息的地方改为非批量，或者不使用json消息，客户端解析protobuf数据

非常感谢，已经改为非批量发送了。
