### ISSUE TITLE
canal.properties和canal_local.properties有什么区别啊

### ISSUE THREAD

**Issue by jiangxiaoqiang** [alibaba/canal#3559]
## Question

看了下配置目录，有2个配置canal.properties和canal_local.properties， Kubernetes中编辑的是canal.properties，启动的时候貌似读取的canal_local.properties，有什么区别？ 为什么要设计2个配置？

**Comment by keer-dai** [comment]
> ## Question
> 看了下配置目录，有2个配置canal.properties和canal_local.properties， Kubernetes中编辑的是canal.properties，启动的时候貌似读取的canal_local.properties，有什么区别？ 为什么要设计2个配置？

local是为canalAdmin准备的
