### ISSUE TITLE
 同步到MySQL需要安装canal-adapter么

### ISSUE THREAD

**Issue by jiangxiaoqiang** [alibaba/canal#3563]
## Question

直接从MySQL -》 MySQL需要canal-adapter么？我看了源码，没有MySQL相关的代码啊。

![image](https://user-images.githubusercontent.com/4521375/119776752-e8fc9900-bef7-11eb-9044-c1b1ccd1fe71.png)

**Comment by programming-pupil** [comment]
canal-adapter里面有同步到rdb的相关代码和配置。蛮好用的

**Comment by jiangxiaoqiang** [comment]
> rdb

rdb是redis 么？

**Comment by jiangxiaoqiang** [comment]
兄弟你微信好多 交流一下
