### ISSUE TITLE
多客户端订阅问题请教

### ISSUE THREAD

**Issue by Shadowsay** [alibaba/canal#357]
多个canal客户端订阅一个canal服务，其中一个客户端进行取消订阅操作，其他canal客户端抛异常，会不会影响其他客户端的订阅、消息接收。 @agapple

**Comment by agapple** [comment]
建议只有一个客户端进行消费，否则数据顺序没法保证

**Comment by sun0110** [comment]
@agapple 如果对顺序要求不高的话，对于多客户端订阅同一个服务，其中一个客户端调用unsubscribe(),导致其他客户端抛异常了，此时会影响其他客户端的订阅及消息获取吗？

**Comment by NPCSun** [comment]
@agapple 如果客户端能自己保证顺序消费，对于多客户端订阅同一个服务，其中一个客户端调用unsubscribe(),导致其他客户端抛异常了，此时会影响其他客户端的订阅及消息获取吗？

**Comment by agapple** [comment]
目前是会影响其他客户端的

**Comment by NPCSun** [comment]
@agapple  实测过，确实影响，感谢。

**Comment by NPCSun** [comment]
@agapple canal能从RDS中获取数据吗

**Comment by agapple** [comment]
可以订阅RDS

**Comment by NPCSun** [comment]
@agapple 感谢。161559791这个群不能加入了，我的QQ：295826395，能否把我拉进去呢，谢啦。

**Comment by agapple** [comment]
@NPCSun 群已经可以加了

**Comment by alswl** [comment]
我现在使用方式是先写入 Redis 再进行消费订阅。
