### ISSUE TITLE
mycat和pxc使用canal

### ISSUE THREAD

**Issue by wangfuguier2009** [alibaba/canal#3574]
使用的kv+haproxy+mycat+pxc搭建的数据库集群。pxc是搭建的两个集群，用mycat分片，一个由四个数据库和2个分片
1.docker种一个容器能否监听多个数据库？文档上说得是需要多个instacne，要监听多个需要重建一个镜像，pxc下有四个数据库
2,每个数据库有2个分片，是不是每个数据库都得去运行一个容器，是不是每个分片就得去运行一个容器，一共运行8个canal？

**Comment by clannad2000** [comment]
https://github.com/alibaba/canal/wiki/AdminGuide

group-instance.xml介绍：

    主要针对需要进行多库合并时，可以将多个物理instance合并为一个逻辑instance，提供客户端访问。

    场景：分库业务。 比如产品数据拆分了4个库，每个库会有一个instance，如果不用group，业务上要消费数据时，需要启动4个客户端，分别链接4个instance实例。使用group后，可以在canal server上合并为一个逻辑instance，只需要启动1个客户端，链接这个逻辑instance即可.
