### ISSUE TITLE
IP可以支持配置域名么

### ISSUE THREAD

**Issue by jiangxiaoqiang** [alibaba/canal#3586]
## Why you need it?
在Kubernetes中重启后，IP变化了。

## How it could be?

支持域名，就不需要修改地址了

## Other related information

![image](https://user-images.githubusercontent.com/4521375/120419930-f2717f80-c395-11eb-8ab6-5323ea3f2586.png)

**Comment by wardseptember** [comment]
支持，之前不是回答过吗
