### ISSUE TITLE
关于mysql切主的问题

### ISSUE THREAD

**Issue by leslie-chu** [alibaba/canal#359]
我们这边有一种场景，mysql是一主两从，canal从主dump binlog，但是切主的话我们是切域名，域名不变，把域名挂的ip改变，这种情况下canal  是要重启？？

**Comment by awnuxkjy** [comment]
需要。mysql 主从  位点 ，文件名 都不一样，需要人肉修改到 从库的 文件名 ，位点。注意要保证 canal 连接到 新ip 上，确保主库 无写入 而且同步到 从库后 才能 切换。很多细节要注意。

**Comment by agapple** [comment]
新版本已经支持单vip的模式，会记录上一次的serverId，数据库主备切换时会判断serverId是否相同，不同则会自动进行位点切换

**Comment by firnsan** [comment]
@agapple 请问非gtid的情况下，canal怎么进行自动找到正确的binlog file&pos？

**Comment by agapple** [comment]
基于时间戳

**Comment by firnsan** [comment]
具体是什么原理呢？同一个event，在新master上的timestamp，已经和旧master上的已经不同的吧，只有evnet的serverid还是保持不变。

**Comment by uang520** [comment]
同问，在新master上的timestamp，已经和旧master上的已经不同的吧？怎么能确定log position？

**Comment by agapple** [comment]
会通过timestmap在备库上二分查找到对应的binlog，最接近该timestamp的binlog事件，以它为起始位点进行备库消费。 这里的一个假定主备库的时间是有NTP同步保证的，不会相差超过60秒(默认值)

**Comment by uang520** [comment]
我看代码主备库切换，根据timestmap前推了60s，这样可能会重复消费吧？

**Comment by uang520** [comment]
是否可以消费的时候记录最新的entry，在主备库切换的时候，前推60s，再通过MD5或者hash（entry)找到备库最新消费的entry，确定点位，然后再消费，这样是不是就不会重复消费了？
