### ISSUE TITLE
flatMessage为false模式下, 消息体只有TRANSACTIONBEGIN和TRANSACTIONEND的数据一直增加.

### ISSUE THREAD

**Issue by Eisen-L** [alibaba/canal#3603]
canal1.1.5 设置canal.mq.flatMessage = false , canal.serverMode = rabbitMQ , 只监听一张表, 发现表数据没有变动的情况下 , mq的消息数量一直在递增 . 消息内容只有 TRANSACTIONBEGIN和TRANSACTIONEND , 将canal.mq.flatMessage 改成 true , 也就是json格式的情况下 , 不会出现这个情况 . 
另外使用protobuf接收数据, 只有tableId , 没有对应的表名 , 能否优化或者是哪里配置不对 , 请指出.

感谢canal团队, 麻烦解答.

**Comment by godchou** [comment]
TRANSACTIONBEGIN和TRANSACTIONEND会在MQMessageUtils中被过滤掉，你确定你的消息发到消息中间件里面去了？
![image](https://user-images.githubusercontent.com/18279365/124229026-938f5980-db3f-11eb-910b-a248be678569.png)

**Comment by zjfwjm1987** [comment]
> TRANSACTIONBEGIN和TRANSACTIONEND会在MQMessageUtils中被过滤掉，你确定你的消息发到消息中间件里面去了？ ![image](https://user-images.githubusercontent.com/18279365/124229026-938f5980-db3f-11eb-910b-a248be678569.png)


可以将TRANSACTIONBEGIN和TRANSACTIONEND过滤掉，但是还会发非白名单表的操作消息，只是消息是4个空格，等于说白名单没有完全生效

**Comment by agapple** [comment]
canal.instance.filter.transaction.entry = true，可以打开这个参数进行空事务过滤

**Comment by jackila** [comment]
tcp模式不支持空事务过滤吗 @agapple
