### ISSUE TITLE
canal支持通过ssl连kafka吗？

### ISSUE THREAD

**Issue by zhuwenxiang2** [alibaba/canal#3607]
## Question

想请问下，目前canal支持通过SASL_SSL方式连接kafka吗？如果支持需要如何配置呢？？

**Comment by kongchongjie** [comment]
同问

**Comment by flowell** [comment]
#3066 支持的
1. 我的adapter(V1.1.5)的application.yml添加以下配置
2. 在./lib/下添加kafka-clients-1.1.1.jar
```
kafka.security.protocol: "SASL_PLAINTEXT"
kafka.sasl.mechanism: "PLAIN"
kafka.sasl.jaas.config: "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"your_username\" password=\"your_password\";"

```

**Comment by XuYijing2018** [comment]
> #3066 支持的
> 
> 1. 我的adapter(V1.1.5)的application.yml添加以下配置
> 2. 在./lib/下添加kafka-clients-1.1.1.jar
> 
> ```
> kafka.security.protocol: "SASL_PLAINTEXT"
> kafka.sasl.mechanism: "PLAIN"
> kafka.sasl.jaas.config: "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"your_username\" password=\"your_password\";"
> ```
SASL_PLAINTEXT和SASL_SSL方式不一样吧，后者需要提供ssl证书才能对接上吧
