### ISSUE TITLE
canal-server报错问题

### ISSUE THREAD

**Issue by vincentwc** [alibaba/canal#3615]
## Why you need it?
使用canal-server和canal-adapter同步数据的问题
1. 源数据库： 10.5.5-MariaDB
2. 目标数据库：5.7.34-mYSQL

使用canal-server连接源数据量，log显示报错信息如下：
ErrorPacket [errorNumber=1932, fieldCount=-1, message=Table 'mysql.gtid_slave_pos' doesn't exist in engine, sqlState=42S02, sqlStateMarker=#]
![image](https://user-images.githubusercontent.com/31959888/122873613-8f578500-d364-11eb-9f50-a8bcf7ea997c.png)

顺便说一下，使用的是MyIsam引擎，本地测试过没问题，但是服务器报错，期待您的解答，谢谢

**Comment by agapple** [comment]
忽略下这张表的订阅
