### ISSUE TITLE
客户端获取不到数据库更新

### ISSUE THREAD

**Issue by Tigojiang** [alibaba/canal#3622]
## Question

哈喽，在跟着官方的教程走后，springboot客户端还是获取不了数据库更改的message。每一次都会提示是empty的message。

sh run.sh -e canal.auto.scan=false -e canal.destinations=test -e canal.instance.master.address=127.0.0.1:3306 -e canal.instance.dbUsername=canal -e canal.instance.dbPassword=canal  -e canal.instance.connectionCharset=UTF-8 -e canal.instance.tsdb.enable=true -e canal.instance.gtidon=false -e canal.instance.parser.parallelThreadSize=16

通过这个命令来运行的canal。

// 创建链接
CanalConnector connector = CanalConnectors.newSingleConnector(new InetSocketAddress(AddressUtils.getHostIp(),
                11111), "test", "", "");
springboot是这样连接的。

显示的连接是成功的，但是在更新数据库的时候，客户端springboot没有什么反应。查询了logbin是没有问题的。在update完可以看到logbin的更新。下面为sql配置信息。
server-id = 1
binlog-format = ROW
log-bin = mysql-bin

操作的数据库是127.0.0.1:3306的test, 表为SpringTest。Springboot的filter信息是connector.subscribe(".*\\..*");所以应该没有影响。在sql里面也给过canal用户的权限了。所以有些奇怪为啥客户端还是不会有提醒呀

**Comment by usedssl** [comment]
看看是不是参数的问题flatMessage=false

**Comment by Tigojiang** [comment]
@usedssl 应该不是。我把这个flag设置成true/false都试过了。但都没响应诶，有些奇怪

**Comment by cnyangfy** [comment]
你好 解决了吗

**Comment by usedssl** [comment]
你加我好友吧&nbsp; QQ：591724551




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月16日(星期五) 下午2:41
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [alibaba/canal] 客户端获取不到数据库更新 (#3622)





 
你好 解决了吗

**Comment by GZUCMHjy** [comment]
我也遇到这个问题了，请问如何解决呢？
