### ISSUE TITLE
踩坑，库表过滤不支持正则\d匹配数字

### ISSUE THREAD

**Issue by Ayhan-Huang** [alibaba/canal#3629]
instance.properties：
canal.instance.filter.regex=db_\d+\\.table_\d+

因为使用场景是分库分表的，比如db_00.table_0000, db_01.table_0001，这样配置后，无法投递变更到Kafka，经过多次测试，要用[0-9] 代替 \d 才行

**Comment by godchou** [comment]
试下这个:库名\\.表名[\\d]$,代码里面有测试类，写完可以去里面测试一下

**Comment by agapple** [comment]
![image](https://user-images.githubusercontent.com/834743/168736392-d580f372-0122-488a-84c2-1090ee5292ca.png)

配置文件里要写双斜杠，转义符的问题
