### ISSUE TITLE
canal有计划支持类似mysql5.7中组提交类似的功能么？

### ISSUE THREAD

**Issue by lan1994** [alibaba/canal#363]
mysql升级5.7后，由于主从同步性能提高， 主库写入qps的限制也随之降低，这样带来一个问题就是业务写入速度加快，可能会快于我们收集的速度，这样可能无法作到实时收集了。canal有计划支持mysql5.7提到的组提交吗？

**Comment by agapple** [comment]
canal是以binlog写入之后为准，不关心mysql的组提交的
