### ISSUE TITLE
Specify the name of the network interface to obtain the IP

### ISSUE THREAD

**Issue by xiaoyao9184** [alibaba/canal#3632]
- [x] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment

* docker canal/canal-server:v1.1.5

### Issue Description

When i use docker swarm with canal-server, 
multiple container services will start, 
each container has multiple network interfaces (like docker-ingress network or join a custom network),
the interfaces order is uncontrollable in java.

`canal.ip` cannot be specified, so canal-server use these code to get ip.

https://github.com/alibaba/canal/blob/474063af3b51c86b173bd6753ff98727aca1e44a/deployer/src/main/java/com/alibaba/otter/canal/deployer/CanalLauncher.java#L60-L62

At that time, the following code will get the wrong IP, when the order of the network interfaces is disrupted.

https://github.com/alibaba/canal/blob/474063af3b51c86b173bd6753ff98727aca1e44a/common/src/main/java/com/alibaba/otter/canal/common/utils/AddressUtils.java#L46-L77

So I want to specify the name of the network interface to ensure that the correct IP is obtained.

**Comment by agapple** [comment]
可以提交一个PR给我
