### ISSUE TITLE
maven update Missing artifact com.alibaba.otter:canal.instance.core:jar:1.0.25-SNAPSHOT

### ISSUE THREAD

**Issue by freshpomelo** [alibaba/canal#364]
请问这个如何解决，我从master抓了最新的代码，进行maven的update的时候，提示

Missing artifact com.alibaba.otter:canal.instance.core:jar:1.0.25-SNAPSHOT
Missing artifact com.alibaba.otter:canal.instance.manager:jar:1.0.25-SNAPSHOT
Missing artifact com.alibaba.otter:canal.instance.spring:jar:1.0.25-SNAPSHOT

**Comment by luyee** [comment]
本来就是1.0.25-SNAPSHOT 何来Miss？

**Comment by M2shad0w** [comment]
先在 canal  根目录 run
```
mvn clean
mvn install
```
