### ISSUE TITLE
canal/rabbitmq应该使用rabbitmq chanal的confirm特性以及发送消息时设置消息的durable特性，以保证binlog传输的可靠性

### ISSUE THREAD

**Issue by zouzg7829** [alibaba/canal#3647]
## Why you need it?
1、目前canal.properties中的rabbitmq.deliveryMode属性好像没有作用, 也没有说明文档，https://github.com/alibaba/canal/blob/master/connector/rabbitmq-connector/src/main/java/com/alibaba/otter/canal/connector/rabbitmq/config/RabbitMQProducerConfig.java代码中也没有对应的属性
2、当canal连接到rabbitmq后, 在rabbitmq admin webui 查看cannal使用的channal属性, Mode属性为空
3、当有binlog增量同步到rabbitmq后，在rabbitmq admin webui 查看queue中message属性的Persistent属性为0，重启rabbitmq，消息丢失

**Comment by guozhe001** [comment]
支持添加配置来开启confirm模式

**Comment by agapple** [comment]
可以考虑提交一个PR给我
