### ISSUE TITLE
heartbeatHaEnable设置成true，但是没有standby的mysql配置的时候，成功启动

### ISSUE THREAD

**Issue by superheizai** [alibaba/canal#365]
heartbeatHaEnable设置成true，但是没有standby的mysql配置的时候，成功启动。但是做mysql stop & start动作的时候，由于parser会做switch操作，这个操作会造成空指针退出。由于这个空指针是停止了心跳线程和解析线程之后，启动新的心跳和解析线程之前，所以canal没法继续dump消息。

**Comment by agapple** [comment]
版本是多少？
