### ISSUE TITLE
dynamicTopic 动态topic只匹配一个topic这是基于什么考虑，针对一表发送多topic情况怎么处理？

### ISSUE THREAD

**Issue by panyujiang** [alibaba/canal#3663]
## Why you need it?

在使用1.1.4的是时候是可以 topic1:table1;topic2:table1。当table1产生binlog的时候可发送给topic1和topic2。
![Dingtalk_20210716154927](https://user-images.githubusercontent.com/45383131/125913019-99b5e563-eb66-4599-901c-db0f8be27920.jpg)
1.1.5 使用的时候仅可匹配第一个。此功能显得尤为鸡肋。

**Comment by panyujiang** [comment]
fixed issue #2258 , optimizer rabbitmq send perf & matchTopics only match one Topic

**Comment by panyujiang** [comment]
![image](https://github.com/alibaba/canal/assets/45383131/6af1b30c-27fa-4522-b0da-7314fa1b0cb1)
删除两个break，重新打包即可

**Comment by las1991** [comment]
> ![image](https://user-images.githubusercontent.com/45383131/264522520-6af1b30c-27fa-4522-b0da-7314fa1b0cb1.png) 删除两个break，重新打包即可

可以升级到master么
