### ISSUE TITLE
canal 监控告警怎么做的？

### ISSUE THREAD

**Issue by lanyuange** [alibaba/canal#3664]
canal 监控告警怎么做的？

**Comment by crossmaya** [comment]
写个shell脚本，每几分钟运行一次，查看canal进程是否存在，不存在就重启并发送告警信息。我们是这么做的

**Comment by lanyuange** [comment]
canal + prometheus  不能用rule 吗？

**Comment by agapple** [comment]
基于prometheus的监控，可以配置一下告警规则
