### ISSUE TITLE
关于解析位点和消费位点的zk存储未到flush时间数据丢失？

### ISSUE THREAD

**Issue by uninxc** [alibaba/canal#367]
在default-instance.xml  中配置为周期性的输入zk，如果在未到flush时间，server挂掉，另外的备机启动，读取的位点落后于最新的位点（因为主server未flush到zk），这样会造成重复读取数据？？怎么办？？

**Comment by agapple** [comment]
分布式高可用系统，不可能设计做到数据不重复
