### ISSUE TITLE
Canal支持非标准mysql binlog吗

### ISSUE THREAD

**Issue by hey-hoho** [alibaba/canal#3673]
## Question

如题，我们的mysql是在5.6开源版本上自己改的，binlog格式做了一些变更，这样的话还能使用canal来获取增量数据吗？
如果不能直接支持的话，有没有别的方案呢？
感谢~

**Comment by agapple** [comment]
你们改动的binlog格式，需要遵守mysql binlog的扩展，比如实现IgnorableLogEvent
