### ISSUE TITLE
canal rdb 如果要支持DDL，源库和目标库的shecma或者库名必须一致么？

### ISSUE THREAD

**Issue by feideyang** [alibaba/canal#3677]
## Question

canal adapter 配置rdb ，一般DML 都可以支持，但是如果要支持DDL，源库和目标库的shecma或者库名必须一致么？我实现的数据库名一致时时可以DDL，不一致时就不支持DDL，请问实际情况时这样的么？

**Comment by feideyang** [comment]
@agapple

**Comment by feideyang** [comment]
官网没实现，自己改源码实现了

**Comment by zhang5324496** [comment]
> 官网没实现，自己改源码实现了

大佬，能分享下代码看看吗
