### ISSUE TITLE
How to solve the problem when starting service of adapter?

### ISSUE THREAD

**Issue by arthasking123** [alibaba/canal#3678]
![image](https://user-images.githubusercontent.com/16257131/126605092-140362f2-1d58-45ae-8cd4-96158702edad.png)

**Comment by Robert613** [comment]
我把这elasticsaerch     canalAdapters:
  - instance: product 
    groups:
    - groupId: g1
      outerAdapters:
      - name: logger
      - name: es6
        **hosts: http://127.0.0.1:9200******

**Comment by pingshengbuxiao** [comment]
1.1.5 only support full path like http://ip:port

**Comment by arthasking123** [comment]
![image](https://user-images.githubusercontent.com/16257131/126623571-c1995962-060f-4d9a-a91b-4d54bfe80f3c.png)
after modify the hosts to full path, the problem changed to this

**Comment by pingshengbuxiao** [comment]
change escore moduel  pom.xml  add <scope>provided</scope> like below
<dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>druid</artifactId>
            <scope>provided</scope>
        </dependency>

**Comment by ice-llz** [comment]
你好，我把代码拉下来编译无法通过。请问能将你编译好的jar包发一份到我邮箱吗？
867253045@qq.com
感激不尽，谢谢
