### ISSUE TITLE
客户端报错no match ack position

### ISSUE THREAD

**Issue by whyliyu** [alibaba/canal#368]
你们好，我在使用canal的过程中碰到了个奇怪的问题，描述如下
我的客户端代码是
while(!Thread.currentThread().isInterrupted()) {
    Message message = canalService.getWithoutAck(identity, 1, 1L, TimeUnit.SECONDS);
    long batchId = message.getId();
    if(batchId != -1) 
        canalService.ack(identity, batchId);
}
具体过程是每次取一条，然后进行ack，日志显示第一条也就是batch id为1的数据ack成功了，第二条数据也就是batch id为2的数据ack失败了，并且碰到以下的异常
com.alibaba.otter.canal.store.CanalStoreException: no match ack positionLogPosition[identity=LogIdentity[sourceAddress=/10.160.246.137:1379,slaveId=-1],postion=EntryPosition[included=false,journalName=mysql-bin.000001,position=130,serverId=1379,timestamp=1489048651000]]

请问这个异常可能是什么原因导致的呢

**Comment by agapple** [comment]
no match ack的意思是未按照batchId的顺序调用ack

**Comment by whyliyu** [comment]
哇，还以为这个问题要被忘掉了。。。
实际上是按照顺序ack的，但是仍然出现了这种状况，经过我跟踪代码，我发现如果消费者启动过快，而此时canal server没有取到任何binlog数据后，接下来binlog到来时就会发生这种情况。
我的CanalInstance是CanalInstanceWithManager，MetaManager是FileMixedMetaManager，LogPositionManager是MetaLogPositionManager，版本1.24.
在我这个三个搭配下以及在上述的特殊情况下就会发生这个问题，不知道其他搭配有没有问题

**Comment by agapple** [comment]
建议测试一下最新的1.1.2版本
