### ISSUE TITLE
canal消费端到某个时间点不消费

### ISSUE THREAD

**Issue by tengtengyin** [alibaba/canal#369]
用的canal/canal-deployer-1.0.24  最新版本,  订阅的mysql版本是mariadb的10.0.22
发现消费端运行到某一时刻,zk的位点和时间戳就不在变化,而且消费端的进程并没有挂掉,
也没有发现错误日志,

重新启动进程不好使,必须重新置成instance.properties的时间戳,删掉zk里位点,重新消费才好使

盼回复,谢谢!

**Comment by luyee** [comment]
没日志[允悲]

**Comment by wufengbin** [comment]
是不是阻塞了？

**Comment by JoyJava** [comment]
这么解决的？遇到同样问题， 没有日志很恼火。可以确定的是 client和server直接的问题

**Comment by ruanchengui** [comment]
+1
