### ISSUE TITLE
服务端能拿到binlog中的thread_id属性吗

### ISSUE THREAD

**Issue by wjc1163757514** [alibaba/canal#3691]
## Question

如题，想监控的时候把binlog的thread_id一并储存，但是没有找到这个属性，只有sql、表、库之类的字段

#210727  0:00:07 server id 1  end_log_pos 330 CRC32 0xc81a57dc 	Query	_**thread_id=179591**_	exec_time=0	

期望获取到179591这个值

**Comment by agapple** [comment]
begin事件里有threadId
commit事件里有transactionId
