### ISSUE TITLE
Docker QuickStart 只有服务启动日志，没有服务运行日志，非Docker都有运行日志，希望docker版本优化一下

### ISSUE THREAD

**Issue by feideyang** [alibaba/canal#3700]
## Why you need it?

![image](https://user-images.githubusercontent.com/19386918/127984037-000e527e-f194-458a-83e8-10f47a0a2af1.png)

## How it could be?

希望docker化以后，运行日志也可以输出，不是只有启动日志

**Comment by jagol1312** [comment]
run.sh里的VOLUMNS="-v $DATA:/home/admin/canal-server/logs"注释掉了，取消注释直接挂载日志出来看吧。
