### ISSUE TITLE
canal对接RocketMQ集群模式，使用partitionHash, binlog数据一直投递到Broker a 上

### ISSUE THREAD

**Issue by authorXiao** [alibaba/canal#3707]
- [ ] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment

* canal version  1.1.4
* mysql version  5.6.7

### Issue Description
Canal 对接 RocketMQ集群环境（2主2从集群，Broker a 和 Broker b），instance.properties配置信息如下
canal.mq.topic=migrate-my-test
# dynamic topic route by schema or table regex
#canal.mq.dynamicTopic=mytest1.user,mytest2\\..*,.*\\..*
canal.mq.partition=0
# hash partition config
#topic默认队列8
canal.mq.partitionsNum=8
canal.mq.partitionHash=cp_test.my_test:id^name,cp_test.my_test_2:id,cp_test.my_test_3:id,cp_test.my_test_4:id,cp_test.my_test_5:id,cp_test.my_test_6:id
解析的Binlog数据一直投递到Broker a, Broker b中无数据
### Expected behaviour
根据表名partitionHash, 不同的表可以分散到不现的Broker, 数据在RocketMQ上分布均匀
### Actual behaviour
解析的Binlog数据一直投递到Broker a, Broker b中无数据

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by MeetMax** [comment]
> > 印象中有修复过类似问题，先考虑升级下1.1.5版本吧
> 
> 用的就是1.1.5 试过kafka 和rocketmq 分区无效

partitionsNum 需要>= broker-a+broker-b 的 queue数，baoker-a、baoker-b才能均匀分配消息
