### ISSUE TITLE
spring版本2.5.6和应用的版本冲突了，有什么办法兼容下吗？

### ISSUE THREAD

**Issue by liutaihua** [alibaba/canal#371]
应用用canal-client的方式，应用用的是4.x的spring, 而canal在用的是2.5.6 spring boot会报：  
```
java.lang.NoSuchMethodError: org.springframework.core.annotation.AnnotationAwareOrderComparator.sort  
```  

有办法绕过吗

**Comment by liutaihua** [comment]
自问自答。用 exclusions 应该可以解决。

**Comment by wuchaooooo** [comment]
@liutaihua 请问去掉依赖后，用别的版本的spring，canal不会出莫名奇妙的bug吗？

**Comment by wuchaooooo** [comment]
@agapple 请问去掉依赖后，用别的版本的spring，canal不会出莫名奇妙的bug吗？

**Comment by agapple** [comment]
不会的，canal用的spring功能非常少
