### ISSUE TITLE
全量同步任务提示找不到任务

### ISSUE THREAD

**Issue by sine-wh** [alibaba/canal#3714]
curl -X POST http://127.0.0.1:8081/etl/es7/xxx.yml
提示
{"succeeded":false,"errorMessage":"Task not found"}

yml中的sql为多张表left join
删除xxx.yml时，canal-adapter控制台提示 Delete a es mapping config: xxx.yml of canal adapter
 添加xxx.yml时，canal-adapter控制台提示 Add a new es mapping config: xxx.yml to canal adapter

**Comment by sine-wh** [comment]
canal-adapter-1.1.5的全量同步接口为
http://ip:port/etl/es7/outerAdapterKey/xxx.yml

**Comment by Im-SAMW** [comment]
> 

请问是如何解决的？

**Comment by Im-SAMW** [comment]
> canal-adapter-1.1.5的全量同步接口为 http://ip:port/etl/es7/outerAdapterKey/xxx.yml

请问是如何解决的？我这里尝试了若干方法都不行
