### ISSUE TITLE
canal 订阅模式数据量太大，把内存撑爆了，有canal的最佳实践么？

### ISSUE THREAD

**Issue by dnfhujun** [alibaba/canal#372]
canal 订阅模式数据量太大，把内存撑爆了，有canal的最佳实践么？

**Comment by luyee** [comment]
batchsize 太大?

**Comment by lijing666** [comment]
确实connector.getWithoutAck(batchSize)这个batchSize是批次的概念，就算batchSize为1，如果数据库变更是类似update table1 set status=0 如果数据有500万，则此次返回的数据将有500万条，如果系统连续多次执行这种语句，则内存很快就会爆
