### ISSUE TITLE
canal-adapter srcDataSources配置多个源数据问题

### ISSUE THREAD

**Issue by ckxxm** [alibaba/canal#3727]
我在srcDataSources中配置了两个源数据库，但只有第一个生效了可以获取到数据，第二个没有任何反应，adapter启动时也没有报错。这会是什么原因，难道不能这样用？
srcDataSources:  
    defaultDS:
      url: jdbc:mysql://192.168.0.100:3306/schema1?useUnicode=true
      username: canal
      password: canal
    rcrmDS:
      url: jdbc:mysql://192.168.0.100:3306/schema2?useUnicode=true
      username: canal
      password: canal

**Comment by ax3353** [comment]
请问大佬解决了么？这种常规需求应该是支持的吧，但是不知道怎么配置

**Comment by ckxxm** [comment]
@ax3353  解决了，忘记说明了 。
其实比较简单，srcDataSources中配置多个数据源，格式就同我上面发的问题一样，然后在es7目录下的每个目标yml文件中要正确配置dataSourceKey和outerAdapterKey，这两个要和application.xml中srcDataSources、canalAdapters配置相同。如下：
application.xml
srcDataSources:  
    defaultDS: 
      url: jdbc:mysql://192.168.0.100:3306/schema1?useUnicode=true
      username: canal
      password: canal
    rcrmDS:
      url: jdbc:mysql://192.168.0.100:3306/schema2?useUnicode=true
      username: canal
      password: canal
  canalAdapters:
  - instance: example # canal instance Name or mq topic name
    groups:
    - groupId: g1
      outerAdapters:
      - name: es7 
        key: exampleKey 
        hosts: 192.168.0.100:9200 
        properties:
          mode: rest 
          cluster.name: es-cluster
=============================================================================
es7/file1.yml

dataSourceKey: defaultDS        #对应application中srcDataSources中的数据源之一
outerAdapterKey: exampleKey
destination: example
groupId: g1
esMapping:
  _index: canal_test
  _id: _id
  _type: _doc # type
  sql: "SELECT a.id as _id, a.name, a.desc FROM canal_test a"
  commitBatch: 3000

=============================================================================
es7/file2.yml

dataSourceKey: rcrmDS      #对应application中srcDataSources中的数据源之一
outerAdapterKey: exampleKey
destination: example
groupId: g1
esMapping:
  _index: index_attr
  _id: _id
  _type: _doc # type
  sql: "SELECT a.cuid as _id, a.cuid as cuid,a.label_cn, a.table_name,a.table_label,a.c1,a.column_name,a.data_type FROM attr a"
  commitBatch: 3000

**Comment by gaoqiang-0327** [comment]
deployer/conf 有 example 和 example1  是两个数据源。 canal.properties中的canal.destinations = example,example1
适配器adapter/conf/application.yml 中的这个参数怎么配： - instance: example # canal instance Name or mq topic name

**Comment by 1150549059** [comment]
不行啊，按照上面的方法，日志都不出来了

**Comment by 1150549059** [comment]
server:
  port: 8081
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
 
canal.conf:
  mode: tcp # 客户端的模式，可选tcp kafka rocketMQ
  flatMessage: true # 扁平message开关, 是否以json字符串形式投递数据, 仅在kafka/rocketMQ模式下有效
  zookeeperHosts:    # 对应集群模式下的zk地址
  syncBatchSize: 3000 # 每次同步的批数量
  retries: 0 # 重试次数, -1为无限重试
  timeout: # 同步超时时间, 单位毫秒
  accessKey:
  secretKey:
  consumerProperties:
    canal.tcp.server.host: 127.0.0.1:11111 #设置canal-server的地址
    canal.tcp.zookeeper.hosts:
    canal.tcp.batch.size: 500
    canal.tcp.username:
    canal.tcp.password:
  srcDataSources:
    defaultDS:
      url: jdbc:mysql://192.168.0.111:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: canal
      password: canal
    secondDS:
      url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: canal
      password: canal
  canalAdapters:
  - instance: example1 # canal instance Name or mq topic name
    groups:
    - groupId: g1
      outerAdapters:
      - name: logger
      - name: es7
        key: exampleKey1
        hosts:  http://127.0.0.1:9200 # 127.0.0.1:9200 for rest mode
        properties:
          mode: rest # or rest
          #security.auth: elastic:Hna1rcom #  only used for rest mode
          cluster.name: elasticsearch
  - instance: example2 # canal instance Name or mq topic name
    groups:
    - groupId: g2
      outerAdapters:
      - name: logger
      - name: es7
        key: exampleKey2
        hosts:  http://127.0.0.1:9200 # 127.0.0.1:9200 for rest mode
        properties:
          mode: rest # or rest
          #security.auth: elastic:Hna1rcom #  only used for rest mode
          cluster.name: elasticsearch

**Comment by 1150549059** [comment]
a.yml
dataSourceKey: defaultDS
outerAdapterKey: exampleKey1
destination: example1
groupId: g1
concurrent: true
esMapping:
    _index: a
    _id: id
    sql: "select 
            id,
            name,
            create_date,
            update_date
        from 
            a"
    commitBatch: 3000
_____________________________________
b.yml
dataSourceKey: secondDS
outerAdapterKey: exampleKey2
destination: example2
groupId: g2
concurrent: true
esMapping:
    _index: b
    _id: id
    sql: "select 
            id,
            name,
            create_date,
            update_date
        from 
            b"
    commitBatch: 3000
