### ISSUE TITLE
canal1.1.5 deploy连接超时

### ISSUE THREAD

**Issue by lianglinux5** [alibaba/canal#3733]
- [ ] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment

* canal version  1.1.5
* mysql version  5.7

canal.deployer启动时使用canal.admin连接  连接超时
deploy启动命令,canal admin部署成功
 bin/startup.sh local

报错原因
<img width="853" alt="error" src="https://user-images.githubusercontent.com/14293060/129861577-5ebec163-93e2-4b98-a0da-4be0560dcf60.png">

Caused by: java.lang.RuntimeException: requestGet remote error, request : http://127.0.0.1:8089/api/v1/config/server_polling?ip=127.0.0.1&port=11110&md5=&register=1&cluster=&name=

**Comment by agapple** [comment]
read time out，先检查下环境
