### ISSUE TITLE
canal adapter文档能否更新

### ISSUE THREAD

**Issue by nielizixiu** [alibaba/canal#3742]
目前的文档看着让人摸不着头脑，而且项目无法成功启动

**Comment by aboutZZ** [comment]
国产KPI产物，我还是敬而远之。md Docker搞了半天启动不起来，研究了下启动脚本，启动参数全部写死，无灵活性可言，一个中间件你给我来个`Xms2048m -Xmx3072m` ? 难道我们每个项目都像你阿里巴巴一样都是上千亿数据量？🤔

**Comment by nielizixiu** [comment]
最近这个整的好难受， 各种奇奇怪怪的问题，真希望能少些feature，多解决bug先

**Comment by nielizixiu** [comment]
磕磕绊绊算是整完了  文档稀稀拉拉全看一遍倒也解决不少问题~
