### ISSUE TITLE
KPI 项目

### ISSUE THREAD

**Issue by Jack9610** [alibaba/canal#3746]
## Question

代码跟文档写的跟玩似的
instance.properties 与数据库相关这么重要的配置居然放到example目录下，不知道的还以为是demo项目
bug一大堆，issue一个都不回复，feature 倒是一个版本接着一个版本上的没停下来过
阿里真的这么闲吗？？？

**Comment by aboutZZ** [comment]
+1
文档就是一坨翔，启动这玩意启动两天了

**Comment by zhang5324496** [comment]
issue回复率是真的低

**Comment by swq-github** [comment]
canal可能没人维护了吧。
https://blog.csdn.net/wankaimingzj/article/details/119349774

**Comment by feng99** [comment]
> canal可能没人维护了吧。
> https://blog.csdn.net/wankaimingzj/article/details/119349774

加油哇 超越canal

**Comment by feng99** [comment]
> canal可能没人维护了吧。
> https://blog.csdn.net/wankaimingzj/article/details/119349774

刚刚上线呀,    一周一版本  太猛了.
mysql同步到mysql
和
mysql同步到es
这2个最常用的   现在稳定吗?
效率快不快.

**Comment by feng99** [comment]
> canal可能没人维护了吧。
> https://blog.csdn.net/wankaimingzj/article/details/119349774

文档比canal写的详细 哈哈

**Comment by jagol1312** [comment]
文档一点都不详细，也不全面。

**Comment by agapple** [comment]
instance.properties这个文件给的是demo的配置例子，对文档和代码有建议的可以提交PR给我
