### ISSUE TITLE
使用canal-server:v1.1.4官方镜像，发现有重复发消息，相同版本部署ec2则没有问题

### ISSUE THREAD

**Issue by xjliang2007** [alibaba/canal#3747]
### environment

* canal v1.1.4
* mysql 5.7
* 部署2台server

### Issue Description
相同的配置，如果admin上启用两台server，一条记录变更则发送两条数据，必现。
只使用一台server的情况下，一条记录变更则正常发送一条数据。

**Comment by agapple** [comment]
印象中1.1.5有修复过类似问题，可以先考虑做下升级
