### ISSUE TITLE
master分支源码编译报错

### ISSUE THREAD

**Issue by tianshouzhi** [alibaba/canal#375]
看了下，master分支把netty 版本从3.x升到了4.x，netty的包名发生了改变，从org.jboss.netty-->io.netty。但是canal中使用到netty api的地方包名并没改过来，导致报错。

**Comment by luyee** [comment]
1.023 版本用的netty4.  这个版本不稳定，    1.0.24版本又回退了。。。

**Comment by agapple** [comment]
目前是 netty3和netty4都依赖了
