### ISSUE TITLE
canal+ kafka的分区参数疑惑

### ISSUE THREAD

**Issue by zhang5324496** [alibaba/canal#3750]
## Question
canal + kafka的采集分区参数

canal.mq.dynamicTopic=**_topicA:schema1\\.table1,topicA:schema2\\.table2_**
canal.mq.partitionsNum=3
canal.mq.partitionHash=**\.*\\\..\***

我阅读wiki的理解是
topicA 存放canal从 table1和table2增量同步的数据
自动创建topic，且分区数量为3   
分区策略是，按表分区，即表数据分开存放在不同的topic分区。

但是测试的结果和我理解的不一样
环境： linux centos 6
canal 1.1.15
mysql 5.7.42
kafka 2.12_2.2.0

case1：
采集table1和table2 到 topicA  符合预期
但是kafka的topicA的分区数量是1，  不符合预期的3.   
查看了相关的issue，作者说是kafka的topic要手动创建并指定分区数量 https://github.com/alibaba/canal/issues/3339

case2：
于是我手动创建了 topic， 指定分区数量为4

测试2次的结果都是：
数据分布在3个分区内， 每个分区table1和table2的数据都有。

我就疑惑了，canal.mq.partitionsNum是决定 数据分布在多少个分区内吗
canal.mq.partitionHash=.\*\\..\* 的效果也没办法理解了。

请路过的大佬的指导下这三个参数的含义，拜谢

================
附 wiki的部分资料

canal.mq.dynamicTopic -- 例子5：test0:test,test1:test1\\.test1，指定多个表达式，会将test库的表都发送到test0的topic下，test1\\.test1的表发送到对应的test1的topic下，其余的表发送到默认的canal.mq.topic值

canal.mq.partitionHash -- 例子5：.\*\\..\* ，不指定pk信息的正则匹配，将所有正则匹配的表,对应的hash字段为表名。 按表hash: 一张表的所有数据可以发到同一个分区，不同表之间会做散列 (会有热点表分区过大问题)
 
 
canal.mq.dynamicTopic，主要控制是否是单topic还是多topic，针对命中条件的表可以发到表名对应的topic、库名对应的topic、默认topic name
canal.mq.partitionsNum、canal.mq.partitionHash，主要控制是否多分区以及分区的partition的路由计算，针对命中条件的可以做到按表级做分区、pk级做分区等

**Comment by zhang5324496** [comment]
> canal.mq.partitionHash的作用是按照哪个列做分区，如果不指定，默认只会发送给其中1个分区

![image](https://user-images.githubusercontent.com/26056141/136726913-9b69303c-4f59-42f4-8ea5-07aa4c18f5ec.png)

例子5：.*\\..* ，不指定pk信息的正则匹配，将所有正则匹配的表,对应的hash字段为表名
                          按表hash: 一张表的所有数据可以发到同一个分区，不同表之间会做散列 (会有热点表分区过大问题)
例子6: test\\.test:id,.\\..* , 针对test的表按照id散列,其余的表按照table散列

如果我想按表级分区， 应该如何设置。文档 不是说  .\\..* 是安装table散列吗。

**Comment by agapple** [comment]
例6就是按照表table散列的例子

**Comment by bobo2992762778-lang** [comment]
我也遇到的同样的问题，自动创建的的Topic分区数是1，但是我的配置是：
# mq config
#canal.mq.topic=example
# dynamic topic route by schema or table regex
canal.mq.dynamicTopic=.*\\..*
canal.mq.partition=0
# hash partition config
canal.mq.partitionsNum=3
canal.mq.partitionHash=.*\\..*:$pk$,.*\\..*:id
#################################################

我的理解是配置项 canal.mq.partitionsNum=3 表示会自动创建3个分区，实际上分区数都是1，感觉这个配置没有生效。
