### ISSUE TITLE
canal-adapter全量同步rdb数据导入异常

### ISSUE THREAD

**Issue by 161250130** [alibaba/canal#3757]
## Question

用canal-adapter从mysql到mysql,增量操作可以，全量报错
{"succeeded":false,"errorMessage":"RDB 数据导入异常 =>java.lang.NullPointerException: Cannot invoke \"javax.sql.DataSource.getConnection()\" because \"ds\" is null"}

附上mysqluser.yml
dataSourceKey: defaultDS
destination: example
groupId: g1
outerAdapterKey: mysql1
concurrent: true
dbMapping:
  database: text
  table: userinfo
  targetTable: text1.userinfo    
  targetPk:
    id: user_id
  mapAll: true
  commitBatch: 1000

**Comment by chriszejun** [comment]
哥们，怎么解决的
