### ISSUE TITLE
指定binlog起始位置

### ISSUE THREAD

**Issue by whyliyu** [alibaba/canal#376]
你们好。
我现在想要启动canal后，把现有的binlog全部读取，所以我需要指定binlog的位置，但是因为权限问题，我无法使用show binary logs语句，请问有没有什么办法，来使canal自动从第一个binlog文件开始dump呢？

**Comment by whyliyu** [comment]
@agapple @luyee

**Comment by luyee** [comment]
个人使用姿势

从第一个开始需要保留所有的binlog文件 这个不现实吧。。。

用过的方案：
1，无更新的时段（比如凌晨3-4点）直接全量导入+自动获取位点就好了。
2，有数据更新的时段：
2.1  现在一般是小表直接mysqldump（mydumper+myloader） + 指定位点增量
2.2 xbackup +指定位点增量，可以指定表或者db进行部份恢复，不过这玩意有点坑是，如果是整个db恢复是需要db的datadir必须为空

3，最近发现了(debezium)[https://github.com/debezium/debezium],这个支持全量增量直接导入kafka

关于权限，权限这玩意找dba,运维开吧。。大不了完了在收回去呗。。或者要什么 让dba提供

拉取binlog  都是要开启权限的，参考文档：
```
GRANT SELECT, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'canal'@'%';
```

**Comment by whyliyu** [comment]
嗯，确实不现实，决定采用直接全量导入+自动获取位点的方案了
感谢回答

**Comment by javmain** [comment]
@whyliyu 自动获取位点是如何做到的？
