### ISSUE TITLE
Canal Grafna监控到Delay 延迟高

### ISSUE THREAD

**Issue by ndj888** [alibaba/canal#3771]
## Question
Version: canal v1.1.5 & docker image
Mq: AWS & rabbit mq 3.8.11
canal startup.sh 配置：
`  JAVA_OPTS="-server -Xms11264m -Xmx11264m -Xmn2048m -XX:SurvivorRatio=2 -XX:MetaspaceSize=512m -XX:MaxMetaspaceSize=512m -Xss256k -XX:-UseAdaptiveSizePolicy -XX:MaxTenuringThreshold=15 -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:+CMSParallelRemarkEnabled -XX:+UseCMSCompactAtFullCollection -XX:+UseFastAccessorMethods -XX:+UseCMSInitiatingOccupancyOnly -XX:+HeapDumpOnOutOfMemoryError"
`
node: 4core 16G
运行环境：k8s v1.19.13 + canal
grafna监控：
![](https://tva1.sinaimg.cn/large/008i3skNgy1gu914efdesj62580p2gpe02.jpg)
canal 资源监控：
![](https://tva1.sinaimg.cn/large/008i3skNgy1gu915cjtrfj620z0u0dn202.jpg)

**Comment by suood** [comment]
请问，怎么解决的？

**Comment by ndj888** [comment]
> 请问，怎么解决的？

检查相关消费端的Java 业务，看是否阻塞，非canal问题。

**Comment by ZaneZ7** [comment]
如果没有用canal的client，请问应该从何检查？
