### ISSUE TITLE
canal rollback之后该如何操作？

### ISSUE THREAD

**Issue by zhuwenxiang2** [alibaba/canal#3784]
## Question

采用canal-go作为canal client，当收到exception时，canal-go 执行 rollback。canal-go demo代码如下：
	for {

		message, err := connector.Get(100, nil, nil)
		if err != nil {
			log.Println(err)
			os.Exit(1)
		}
		messageSlice = append(messageSlice, message)
		batchId := message.Id
		if batchId == -1 || len(message.Entries) <= 0 {
			time.Sleep(300 * time.Millisecond)
			fmt.Println("===没有数据了===")
			continue
		}
		connector.RollBack(batchId)
		connector := client2.NewSimpleCanalConnector("xxxx", 11111, "bingo","xxx", "example", 60000,
			60*60*60*1000)
		err = connector.Connect()
		if err != nil {
			log.Println(err)
			os.Exit(1)
		}
		err = connector.Subscribe("canal\\..*")
		if err != nil {
			log.Println(err)
			os.Exit(1)
		}
		//printEntry(message.Entries)
	}

当回滚后，再执行get的时候发现batchid是在不断自增，canal-go在处理后续的数据，而不是回滚的数据？那么也就是说需要在客户端把rollback的数据记录下来，当不再报错后，就可以把这批没处理的数据统一处理完毕？

**Comment by lzlnooffene** [comment]
我认为应该不是，batchid就是每次get时自增的吧
