### ISSUE TITLE
最近同样也遇到了这个问题，采用的是Rabbitmq

### ISSUE THREAD

**Issue by wdqzdd** [alibaba/canal#3787]
最近同样也遇到了这个问题，采用的是RocketMQ，flatMessage=true,将partitionsNum设置为16，根据记录主键Hash分区,每次修改一条数据以后，根据hash策略会往一个队列里面塞入一条数据，但是其它15个队列，会发送15条消息体为"null"的数据，其根本原因在于`CanalRocketMQProducer`类中的以下代码(211行)：
``` java
FlatMessage[] partitionFlatMessage = MQMessageUtils.messagePartition(flatMessage,
                        partitionNum,
                        destination.getPartitionHash(),
                        mqProperties.isDatabaseHash());
```
`messagePartition`方法内部实现，每次都会根据partitionNum初始化一个new FlatMessage[partitionsNum]的数组，但数组中有且只有一个元素有数据，其余的都为null，然后227~230行在代码中构建`Message`:
``` java
List<Message> messages = flatMessagePart.stream()
                                .map(flatMessage -> new Message(topicName, JSON.toJSONBytes(flatMessage,
                                    SerializerFeature.WriteMapNullValue)))
                                .collect(Collectors.toList());
```
在循环构建的过程中，`flatMessage`可能为空，但并没有进行处理，而`JSON.toJSONBytes`会将null数据处理成字符串"null"。
目前本人的解决方案就是在循环构建的过程中，加上`filter(Objects::nonNull)`,来过滤掉null的`flatMessage`:
``` java
                            List<Message> messages = flatMessagePart.stream().filter(Objects::nonNull)
                                .map(flatMessage -> new Message(topicName, JSON.toJSONBytes(flatMessage,
                                    SerializerFeature.WriteMapNullValue)))
                                .collect(Collectors.toList());
```
重新打包部署以后，问题就解决了

_Originally posted by @Beauxie in https://github.com/alibaba/canal/issues/3267#issuecomment-749493984_

**Comment by wdqzdd** [comment]
![image](https://user-images.githubusercontent.com/27991992/133232081-c84790ae-845d-4d78-93f5-579d28fc5d80.png)

还有就是监控到的数据无论是新增还是更新，data  和 olddata都是空的。原来是好的。后面重启导致的。
三个instance，监控不同的表，到不同的队列。

**Comment by wdqzdd** [comment]
![Uploading image.png…]()

**Comment by wdqzdd** [comment]
![image](https://user-images.githubusercontent.com/27991992/133262858-4f1b5bf3-acc4-43c5-9127-12ea98d59fa4.png)

三个instance对应的canal.mq.topic不一样

**Comment by wdqzdd** [comment]
就像过滤条件不起作用一样

**Comment by zhang19980518** [comment]
老哥,方便贴一下你的canal.mq.topic吗   我这里配置的routing_key不生效

**Comment by zhang19980518** [comment]
> 就像过滤条件不起作用一样

老哥,方便贴一下你的canal.mq.topic吗 我这里配置的routing_key不生效
