### ISSUE TITLE
延迟情况下多条ddl语句引发schema不匹配的bug

### ISSUE THREAD

**Issue by sunryuan** [alibaba/canal#380]
在有多条ddl语句时,如果binlog解析存在延时,会引发如下错误：
com.alibaba.otter.canal.parse.exception.CanalParseException: parse row data failed.
Caused by: com.alibaba.otter.canal.parse.exception.CanalParseException: column size is not match for table:`xxdb`.`xxxtable`,39 vs 37。
原因如下：
binlog中有前后两条ddl语句a和b，由于解析落后，canal才解析到a，从db中获取最新的schema，得到了b操作后的schema。a和b之间的消息的表结构跟最新的schema不匹配。

**Comment by tyxx11** [comment]
我也遇到了同样的问题。。。求大神解答。。

**Comment by agapple** [comment]
下一个版本会解决

**Comment by zlywq** [comment]
根据源代码。canal取表结构的元信息不是从binlog中解析的，而是从mysql数据库中使用desc db1.table1去获取的，这样必然存在隐患。

使用下面的case即可重现问题。

先停止canal。

再在mysql主库上运行下列sql语句
use dbt1;
CREATE TABLE Usert1 (
  `userId` BIGINT NOT NULL AUTO_INCREMENT,
  `userNickName` varchar(20) NOT NULL DEFAULT '',
  `isSystem` TINYINT NOT NULL DEFAULT 0,
  `updateTime` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`userId`)
) ENGINE=InnoDB AUTO_INCREMENT=100000;
CREATE INDEX IDX_Usert1_mobile on `Usert1` (`mobile`); 
INSERT INTO Usert1(`userId`,`userNickName`,`isSystem`, `updateTime`)
    VALUES (101,'u101',1, UNIX_TIMESTAMP());
INSERT INTO Usert1(`userId`,`userNickName`,`isSystem`, `updateTime`)
    VALUES (201,'u201',1, UNIX_TIMESTAMP());
UPDATE Usert1 SET isSystem=0 WHERE userId=201;
DELETE FROM Usert1 WHERE userId=101;
SELECT * FROM Usert1;

ALTER TABLE Usert1 ADD COLUMN age INT DEFAULT 0;
ALTER TABLE Usert1 DROP COLUMN updateTime;
ALTER TABLE Usert1 change userNickName nickName varchar(20);

INSERT INTO Usert1(`userId`,`nickName`,`isSystem`, `age`)
    VALUES (301,'u301',1, 301);
INSERT INTO Usert1(`userId`,`nickName`,`isSystem`, `age`)
    VALUES (302,'u302',1, 302);
UPDATE Usert1 SET isSystem=3 WHERE userId=301;
DELETE FROM Usert1 WHERE userId=302;
SELECT * FROM Usert1;

再启动 canal.deployer-1.0.24 和 canal.example-1.0.24 。然后可以从canal.example-1.0.24的log输出看到如下输出。下面的输出中，nickName已经是新列名，而且本是updateTime列的值变成了age列的值。

================> binlog[log-bin.000007:5281] , executeTime : 1507805075000 , delay : -17643ms
 BEGIN ----> Thread id: 17
----------------> binlog[log-bin.000007:5407] , name[dbt1,Usert2] , eventType : INSERT , executeTime : 1507805075000 , delay : -17638ms
userId : 101    type=bigint(20)    update=true
nickName : u101    type=varchar(20)    update=true
isSystem : 1    type=tinyint(4)    update=true
age : 1507805075    type=int(11)    update=true
----------------
 END ----> transaction id: 105

**Comment by agapple** [comment]
新版本会支持ddl版本变更，可以随意回切到任意位点，DDL表结构也会同步回滚

**Comment by agapple** [comment]
新版本代码已经提交到master

**Comment by leesenlen** [comment]
@agapple master分支编译有点问题，啥时候出新版本1.0.25？
```
[ERROR] Failed to execute goal on project canal.parse: Could not resolve dependencies for project com.alibaba.otter:canal.parse:jar:1.0.25-SNAPSHOT: Failed to collect dependencies at com.alibaba:druid:jar:1.1.5-preview_14: Failed to read artifact descriptor for com.alibaba:druid:jar:1.1.5-preview_14: Could not transfer artifact com.alibaba:druid:pom:1.1.5-preview_14 from/to alibaba (http://code.alibabatech.com/mvn/releases/): Connect to code.alibabatech.com:80 [code.alibabatech.com/119.38.217.15] failed: 拒绝连接 (Connection refused) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

**Comment by agapple** [comment]
切换到druid 1.1.5正式版了

**Comment by EricYin2016** [comment]
master 编译无法成功

**Comment by EricYin2016** [comment]
} else if (isHeartBeat) {
                // 处理alisql模式的test.heartbeat心跳数据

**Comment by agapple** [comment]
已经修复

**Comment by fuchun** [comment]
请问老版本怎么跳过这个问题呢？

**Comment by agapple** [comment]
老版本只能跳过数据了

**Comment by agapple** [comment]
尝试26最新版本
