### ISSUE TITLE
canal 指定timestamp

### ISSUE THREAD

**Issue by crazy11show** [alibaba/canal#382]
1）请问为什么只指定timestamp，启动的时候找不到binlog位置？必须得要binlog filename一起指定才能找到位置呢？
我看文档里面是这样写着：
canal.instance.master.timestamp : 指定一个时间戳，canal会自动遍历mysql binlog，找到对应时间戳的binlog位点后，进行启动
2）还有我用binlog filename+ position指定时，他只会遍历这个binlog，不会执行下一个binlog是吗？
请大神帮忙解答一下，谢谢

**Comment by luyee** [comment]
timestamp 没用过，

binlog filename+ position也是会自动取下一个binlog的

**Comment by agapple** [comment]
LS正解

**Comment by jnliao** [comment]
单纯使用timestamp 时我试了也不行。但使用binlog filename+ position没问题。

**Comment by changeyoung2015** [comment]
单纯的使用timestamp我试了也不行，但binlog filename + position或者binlog filename + timestamp就可以

**Comment by YaErHub** [comment]
> 单纯的使用timestamp我试了也不行，但binlog filename + position或者binlog filename + timestamp就可以

请问filename是在哪里指定的呢
