### ISSUE TITLE
Canal Adapter是否处理双库双写回环问题

### ISSUE THREAD

**Issue by wangyd1005sy** [alibaba/canal#3831]
## Question

如处理，如何配置？

**Comment by wangyd1005sy** [comment]
修改源码解决的

**Comment by miaopass-future** [comment]
目前版本的canal还是不支持GTID解决这个问题么？

**Comment by dikeqin** [comment]
对向写入时添加标记,我用的是PXC，所以可以关闭给对象写数据时候关闭binlog，那对象就不会检测到变化，也就不会写回了。具体点是在新建连接时设置SET SESSION sql_log_bin = OFF，如果是需要binlog做集群内复制的，就给每个SQL加上标记，当检测这种标记时就抛弃变更，不再写回。
