### ISSUE TITLE
使用1.1.5版本进行canal注册到canal-admin上时，报错

### ISSUE THREAD

**Issue by FlashManXcy** [alibaba/canal#3837]
本地环境与服务测试环境均使用canal-admin使用1.1.5版本，canal使用1.1.5版本
本地环境 
使用最新代码，能够启动canal-admin服务和deployer的服务，并且能够注册到admin上
1.本地postman的Curl和参数

curl --location --request GET 'http://127.0.0.1:8089/api/v1/config/server_polling?ip=10.237.174.53&port=11110&md5=&register=true&cluster=' \
--header 'user: admin' \
--header 'passwd: 123456'

本地的canal-admin配置
application.xml
server:
  port: 8089
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

spring.datasource:
  address: 已配置，验证正确
  database: 已配置，验证正确
  username: 已配置，验证正确
  password: 已配置，验证正确
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://${spring.datasource.address}/${spring.datasource.database}?useUnicode=true&characterEncoding=UTF-8&useSSL=false
  hikari:
    maximum-pool-size: 30
    minimum-idle: 1

canal:
  adminUser:
  adminPasswd:
  
 本地的deployer服务
 canal.properties文件
 
 canal.register.ip = 10.237.174.53

# canal admin config
canal.admin.manager = 10.237.174.53:8089
canal.admin.port = 11110
canal.admin.user = admin
canal.admin.passwd = 123456
canal.admin.REQUEST_TIMEOUT = 500000
# admin auto register
canal.admin.register.auto = true
canal.admin.register.cluster =
  
  
测试服务器环境：

server:
  port: 8089
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

spring.datasource:
  address: 已配置，验证正确
  database: 已配置，验证正确
  username: 已配置，验证正确
  password: 已配置，验证正确
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://${spring.datasource.address}/${spring.datasource.database}?useUnicode=true&characterEncoding=UTF-8&useSSL=false
  hikari:
    maximum-pool-size: 30
    minimum-idle: 1

canal:
  adminUser:
  adminPasswd:
  
 
测试服务器的canal.properties文件
# register ip
canal.register.ip = 测试服务器ip

# canal admin config
canal.admin.manager = 测试服务器ip:8089
canal.admin.port = 11110
canal.admin.user = admin
canal.admin.passwd = 123456
# admin auto register
canal.admin.register.auto = true
canal.admin.register.cluster =
canal.admin.REQUEST_TIMEOUT = 500000

当进行连接的时候，会报错：Caused by: com.alibaba.otter.canal.common.CanalException: requestGet for canal config error: Required String parameter 'name' is not present。提示缺少name的这个参数，但是源码里边调用的接口并没有这个name参数。
请帮忙排查下原因，谢谢。

**Comment by whhe** [comment]
canal server那边这俩值是不是没填

> canal.admin.register.cluster =
canal.admin.register.name =

**Comment by FlashManXcy** [comment]
> canal server那边这俩值是不是没填
> 
> > canal.admin.register.cluster =
> > canal.admin.register.name =

在canal 服务上设置后，启动依然会报Caused by: com.alibaba.otter.canal.common.CanalException: requestGet for canal config error

**Comment by whhe** [comment]
贴下详细的报错信息

> > canal server那边这俩值是不是没填
> > > canal.admin.register.cluster =
> > > canal.admin.register.name =
> 
> 在canal 服务上设置后，启动依然会报Caused by: com.alibaba.otter.canal.common.CanalException: requestGet for canal config error

贴下详细的报错信息

**Comment by FlashManXcy** [comment]
> > > canal server那边这俩值是不是没填
> > > > canal.admin.register.cluster =
> > > > canal.admin.register.name =
> > 
> > 
> > 在canal 服务上设置后，启动依然会报Caused by: com.alibaba.otter.canal.common.CanalException: requestGet for canal config error
> 
> 贴下详细的报错信息

2021-09-28 10:56:06.685 [main] INFO  com.alibaba.otter.canal.deployer.CanalLauncher - ## set default uncaught exception handler
2021-09-28 10:56:06.737 [main] INFO  com.alibaba.otter.canal.deployer.CanalLauncher - ## load canal configurations
2021-09-28 10:56:07.162 [main] ERROR com.alibaba.otter.canal.deployer.CanalLauncher - ## Something goes wrong when starting up the canal Server:
com.alibaba.otter.canal.common.CanalException: load manager config failed.
Caused by: com.alibaba.otter.canal.common.CanalException: requestGet for canal config error: Required String parameter 'name' is not present
2021-09-28 11:00:35.174 [main] INFO  com.alibaba.otter.canal.deployer.CanalLauncher - ## set default uncaught exception handler
2021-09-28 11:00:35.211 [main] INFO  com.alibaba.otter.canal.deployer.CanalLauncher - ## load canal configurations
2021-09-28 11:00:35.634 [main] ERROR com.alibaba.otter.canal.deployer.CanalLauncher - ## Something goes wrong when starting up the canal Server:
com.alibaba.otter.canal.common.CanalException: load manager config failed.
Caused by: com.alibaba.otter.canal.common.CanalException: requestGet for canal config error: Required String parameter 'name' is not present

**Comment by FlashManXcy** [comment]
deploy 启动后，调的就是canal-admin中的这个接口。但是这个接口就是没有name这个参数
![image](https://user-images.githubusercontent.com/20548126/135049253-6cfdfbe2-3000-403c-8bed-932581c30c1f.png)

**Comment by whhe** [comment]
> deploy 启动后，调的就是canal-admin中的这个接口。但是这个接口就是没有name这个参数
> ![image](https://user-images.githubusercontent.com/20548126/135049253-6cfdfbe2-3000-403c-8bed-932581c30c1f.png)

这个name字段是1.15新加的 https://github.com/alibaba/canal/commit/17f4ee13e76bee5eb73a85b58d4c867b8621de19

**Comment by FlashManXcy** [comment]
> > deploy 启动后，调的就是canal-admin中的这个接口。但是这个接口就是没有name这个参数
> > ![image](https://user-images.githubusercontent.com/20548126/135049253-6cfdfbe2-3000-403c-8bed-932581c30c1f.png)
> 
> 这个name字段是1.15新加的 [17f4ee1](https://github.com/alibaba/canal/commit/17f4ee13e76bee5eb73a85b58d4c867b8621de19)

意思是说代码有更新，安装包也有更新是么？需要安装最新的包是么？然后代码也拉最新的代码？

**Comment by whhe** [comment]
> > > deploy 启动后，调的就是canal-admin中的这个接口。但是这个接口就是没有name这个参数
> > > ![image](https://user-images.githubusercontent.com/20548126/135049253-6cfdfbe2-3000-403c-8bed-932581c30c1f.png)
> > 
> > 
> > 这个name字段是1.15新加的 [17f4ee1](https://github.com/alibaba/canal/commit/17f4ee13e76bee5eb73a85b58d4c867b8621de19)
> 
> 意思是说代码有更新，安装包也有更新是么？需要安装最新的包是么？然后代码也拉最新的代码？

我是想说你图里的源码可能是1.1.5正式版之前的，安装包都用1.1.5的正式版应该是没问题的

**Comment by FlashManXcy** [comment]
![image](https://user-images.githubusercontent.com/20548126/135057362-efa05c0f-ef53-4cc4-bd26-11618cd5ca0b.png)
这个是我的canal配置，配置之后，重启服务，还是 会提示Caused by: com.alibaba.otter.canal.common.CanalException: requestGet for canal config error: Required String parameter 'name' is not present。然后我重新拉了下代码，本地启动了一下canal server，
![image](https://user-images.githubusercontent.com/20548126/135057536-c357f60e-b378-4abd-9922-20eb6caeb016.png)
这个已启动就可成功注册到我本地启动的canal-admin上去

**Comment by FlashManXcy** [comment]
注册的时候，canal-admin的包就会报这个错误，也就是name参数为空的错误
![image](https://user-images.githubusercontent.com/20548126/135058725-065688d1-e0ef-4835-96c9-56fa2f194279.png)

**Comment by FlashManXcy** [comment]
包用的就是这个版本的
![image](https://user-images.githubusercontent.com/20548126/135059192-b6716b56-565c-4517-b774-dcecce6d84f2.png)

**Comment by FlashManXcy** [comment]
我自己再排查下问题，多谢您的解答。

**Comment by FlashManXcy** [comment]
刚才上服务器上查了下，如果是这个版本的话， 是不是说明不是正式版的1.1.5呢？![Uploading image.png…]()

**Comment by FlashManXcy** [comment]
刚才上服务器上查了下，如果是这个版本的话， 是不是说明不是正式版的1.1.5呢
![image](https://user-images.githubusercontent.com/20548126/135060454-f3124d0b-b149-47d7-8acb-c657b8499217.png)

**Comment by FlashManXcy** [comment]
> > > > deploy 启动后，调的就是canal-admin中的这个接口。但是这个接口就是没有name这个参数
> > > > ![image](https://user-images.githubusercontent.com/20548126/135049253-6cfdfbe2-3000-403c-8bed-932581c30c1f.png)
> > > 
> > > 
> > > 这个name字段是1.15新加的 [17f4ee1](https://github.com/alibaba/canal/commit/17f4ee13e76bee5eb73a85b58d4c867b8621de19)
> > 
> > 
> > 意思是说代码有更新，安装包也有更新是么？需要安装最新的包是么？然后代码也拉最新的代码？
> 
> 我是想说你图里的源码可能是1.1.5正式版之前的，安装包都用1.1.5的正式版应该是没问题的

你好，问题已经解决，问题是因为使用了1.1.5-snapshot的版本，并非1.1.5正式版，谢谢您的帮助
