### ISSUE TITLE
adapter跑一段时间，就报“远程主机强迫关闭了一个现有的连接，error sync but ack ”的错误，请大佬们赐教！

### ISSUE THREAD

**Issue by zhangai0407** [alibaba/canal#3838]
![cccba76196c75f12c36666ec49dd006](https://user-images.githubusercontent.com/25814632/134633392-cdb6511e-c6d4-4238-a8ce-c65b24d1ab46.png)

**Comment by chenglutao** [comment]
canal.deployer 修改配置或者重启都会报这个错，重启下 canal.adapter就能解决，找不到服务了

**Comment by Kimihrio** [comment]
是不是commitBatch设置的值大了点  我测试同步es的时候用默认值3000跑一会就报错了  改成1000后就再也没出现过很稳定
