### ISSUE TITLE
canal1.1.5发送消息到rocketmq

### ISSUE THREAD

**Issue by ggq19911109** [alibaba/canal#3845]
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: org.apache.rocketmq.client.exception.MQBrokerException: CODE: 13  DESC: the message is illegal, maybe msg body or properties length not matched. msg body length limit 128k, msg properties length limit 32k

调小canal.mq.canalBatchSize = 4
canal.instance.memory.buffer.size = 2048
## memory store RingBuffer used memory unit size , default 1kb
canal.instance.memory.buffer.memunit = 1024

调整上面参数也没用, 有人遇到过吗

**Comment by agapple** [comment]
binlog消息体过大，如果调小batch也不行的话，需要过滤下大字段了
