### ISSUE TITLE
canal 1.1.5 cpu很高 数据经常丢失

### ISSUE THREAD

**Issue by lanyuange** [alibaba/canal#3856]
canal 1.1.5 版本 CPU很高，经常丢失数据，但是日志显示正常的  
CPU截图：
![image](https://user-images.githubusercontent.com/19629949/136654382-c453815f-a8ff-4d8a-b4e3-d051fea20b33.png)
jstack 查看占用CPU最高的线程，显示
![image](https://user-images.githubusercontent.com/19629949/136721385-d38cfe8f-b7a8-4f28-b992-ed9c42057c10.png)

10:23:44 - 10:24 出现数据丢失
meta.log
![image](https://user-images.githubusercontent.com/19629949/136654456-e8d8737e-8307-4517-a3a2-f7d49cb3dbd4.png)

**Comment by agapple** [comment]
canal.instance.parser.parallel=false，可以关闭MysqlMultiStageCoprocessor

**Comment by wz2cool** [comment]
请问我们也是会丢数据 有什么办法么
