### ISSUE TITLE
canal server 容器重启后canal-go 报 ack error

### ISSUE THREAD

**Issue by zhuwenxiang2** [alibaba/canal#3857]
## Question

当正在接收数据时，服务端容器重启，canal-go GetWithOutAck 方法会报 ack error
panic error: task 'process binlog' panic on time 2021-10-10 16:05:28.508966374 +0800 CST m=+117.892429765, cause by something goes wrong with reason:something goes wrong with channel: exception=com.alibaba.otter.canal.server.exception.CanalServerException: ack error , clientId:1001 batchId:210 is not exist , please check
请问有什么解决办法吗？

**Comment by zhuwenxiang2** [comment]
@agapple

**Comment by agapple** [comment]
server重启后报错是正常现象，client做一个重新启动即可
