### ISSUE TITLE
canal.instance.filter.regex匹配问题

### ISSUE THREAD

**Issue by cheekboy** [alibaba/canal#3858]
## Question
想要监听test1库下的t1 表
下面三个匹配规则哪个是正确的？
canal.instance.filter.regex=test1\\.t1
canal.instance.filter.regex=test1\.t1  
canal.instance.filter.regex=test1.t1  
项目中使用canal.instance.filter.regex=test1\\.t1这种匹配规则 发现偶尔会监听到其他库的数据。

**Comment by young-dev-coder** [comment]
遇到同样的问题

**Comment by agapple** [comment]
配置文件里的正则表达式请使用双斜杠
