### ISSUE TITLE
canal-admin instance配置命名拼写问题

### ISSUE THREAD

**Issue by jsq211** [alibaba/canal#3861]
## Question

![image](https://user-images.githubusercontent.com/37071736/137053538-db38bfef-cf03-475c-81b8-98b91f839410.png)
应该是 instance.properties吧
![image](https://user-images.githubusercontent.com/37071736/137053595-3cf76895-9131-473d-b34f-e8475bd968ba.png)

怪不得调试admin的时候接口名称对不上。。

**Comment by agapple** [comment]
已修复
