### ISSUE TITLE
【问题咨询】canal连接slave，binlog中server_id不一致是吗？

### ISSUE THREAD

**Issue by flowell** [alibaba/canal#3862]
### 前提
非gtid模式，canal连mysql-slave

### 问题描述
#359 中提到，findstartposition实现里，针对可能存在的vip模式会判断server_id。

如果canal连接的是slave并且slave已经开启log_slave_updates，由于slave的binlog中记录的是master的server_id，与当前连接的slave的server_id不一致，就会发生一次基于时间戳的查找。

我的理解有问题吗？

**Comment by agapple** [comment]
理解没错
