### ISSUE TITLE
java代码无法连接 canal的example

### ISSUE THREAD

**Issue by SkyXj** [alibaba/canal#3865]
## Question

process error!com.alibaba.otter.canal.protocol.exception.CanalClientException: failed to subscribe with reason: something goes wrong with channel:[id: 0x58b7e746, /192.168.2.39:9760 => /192.168.2.39:11111], exception=com.alibaba.otter.canal.server.exception.CanalServerException: destination:example should start first

but when i check the port 1111，
![image](https://user-images.githubusercontent.com/31305694/137247692-9c22f638-84cc-4038-b4c6-555103228b4c.png)

**Comment by agapple** [comment]
destination:example should start first
