### ISSUE TITLE
canal server重启，会从上次位点解析吗

### ISSUE THREAD

**Issue by zhumt** [alibaba/canal#387]

**Comment by f-zhao** [comment]
开启了HA的话，上次解析的位点应该会存在zk中，是会从上次位点解析的。

**Comment by zhumt** [comment]
我是用file持久化的，不支持HA，这样是否重启的时候也能从上次位点解析，另外，我结合otter使用，目前otter好像只支持内存模式，这样我重启后，是否会丢失服务断开期间的数据呢

**Comment by agapple** [comment]
不会丢，多看看WIKI和FAQ

**Comment by leesenlen** [comment]
@zhumt file模式会的在instance的配置下，会生产一个meta.dat文件记录上一次解析点
