### ISSUE TITLE
数据库日志格式为ROW,但是canal投递到mq中，会出现具体的sql语句statement格式的

### ISSUE THREAD

**Issue by wkztselina** [alibaba/canal#3873]
mysql 8.0
canal -1.1.5 
收集了所需要的row的log，但是同时也收到了很多statement格式的日志，想问问大佬有没有出现过这种问题，mysql的binlog配置是只有Row的

**Comment by querysky** [comment]
MySQL开启了这个binlog_rows_query_log_events这个配置。
如果不想生成这类信息，可以在canal.properties中设置
canal.instance.filter.query.dml = true
