### ISSUE TITLE
canal是否支持主从数据库监听

### ISSUE THREAD

**Issue by lianglinux5** [alibaba/canal#3875]
canal版本:canal.deployer-1.1.5
canal监听不到主从数据库数据的变化,看日志卡在了
 begin to find start position, it will be long time for reset or first position

**Comment by lanmaodage** [comment]
只要源库开了binlog 格式为row server_id不冲突 应该都是能支持的

**Comment by TheOctopus3430** [comment]
@lianglinux5 你好，我也遇到类似的问题，MySQL主从复制，Canal连接的是从库，也是一直卡在begin to find start position，虽然等待了很长时间但是最终运行正常了，定位问题是因为该MySQL数据库运行时间较长留存的binlog记录非常大需要一定的时间，在持续了1~2小时后正常拉取变更数据
