### ISSUE TITLE
canal-adapter es同步mysql数据时主SQL无法使用GroupBy

### ISSUE THREAD

**Issue by totoro52** [alibaba/canal#3876]
### environment

* canal version : 1.1.5
* mysql version : 8.0
* elasticsearch : 7.x

### Issue Description
在将mysql同步到es时，例如使用SQL： 
```
select  t1.id, t1.name, t2.dept_id from table1 as t1  left join table2  as t2 on t1.id = t2.table1_id group by dept_id
```
**结尾包含了group关键词，程序执行时直接拼接WHERE条件导致报错。
查阅了文档，文档描述禁止在主SQL后拼接条件，如需要则使用子查询，查阅了代码发现确实对子查询做了特殊处理。
但主SQL则直接拼接了Where，实际开发中SQL复杂到一定程度下虽然不一定会用到where，但肯定有场景是需要用到groupby等关键词的**

<img src="https://user-images.githubusercontent.com/25952444/138193739-69f0f244-bbcc-4821-8abe-58880babeb23.png" alt="图片替换文本" width="500" height="400" align="bottom" />

### Steps to reproduce

![3a0a9b9bd09ba543947f37a0f7275aa](https://user-images.githubusercontent.com/25952444/138194034-2351d14c-3f04-4aaa-8e2a-21c1a455e497.png)

**后续更改了填充方法，在填充where时对语句进行判断 ：**
![image](https://user-images.githubusercontent.com/25952444/138194215-7cf00850-0435-49a8-8ce9-7cceb09741b2.png)

**Comment by 1512033796** [comment]
你好，麻烦请问下，最后一张图修改的方法是在escore项目中的嘛？我修改好了要打那个项目的包呢？我用的canal1.1.6，看安装目录plugin中并没有与escore有关的项目！那我需要替换哪一个呢？

下面是我的plugin目录中的jar包内容
![image](https://user-images.githubusercontent.com/45383053/216563329-fbae13be-37b1-41b2-9e17-263f73029efc.png)
