### ISSUE TITLE
在canal-admin的可视化页面修改了密码为5位，重新登录密码有6位限制，登录不了，只能用sql去改密码

### ISSUE THREAD

**Issue by hzq0924** [alibaba/canal#3877]
- [ ] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment

* canal version
* mysql version

### Issue Description
在canal-admin的可视化页面修改了密码为5位，重新登录密码有6位限制，登录不了，只能用sql去改密码

### Actual behaviour

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by agapple** [comment]
最新代码已修复
