### ISSUE TITLE
挂在 conf 目录，以 docker 方式启动的时候失败

### ISSUE THREAD

**Issue by Bravoyk** [alibaba/canal#3879]
## Question

以 docker 形式启动，并且挂载 conf, 以及 logs 目录的时候， logs 目录能写入，conf 目录写不进去。

## 启动命令

docker run -d -it -h 0 \
    -e canal.instance.master.address=127.0.0.1:3306 \
    -e canal.instance.dbUsername=username \
    -e canal.instance.dbPassword=password \
    -e canal.instance.connectionCharset=UTF-8 \
    -e canal.instance.tsdb.enable=true \
    -e canal.instance.gtidon=false \
    -e canal.instance.filter.regex=*.* \
    --privileged=true \
    --name=canal-server \
    -v /root/www/canal/docker/data/logs:/home/admin/canal-server/logs \
    -v /root/www/canal/docker/data/conf:/home/admin/canal-server/conf \
    --net=host \
    -m 4096m \
    canal/canal-server

**Comment by agapple** [comment]
是直接启动失败还是？

**Comment by Bravoyk** [comment]
额 暂时没用 canal 先放一边了
