### ISSUE TITLE
Canal会不定期的报no data的情况

### ISSUE THREAD

**Issue by wuchase** [alibaba/canal#388]
我们像otter那样使用canal来获取binlog数据，但是运行了一段时候之后有个别channel任务的canal会不定时报长时间no data的情况，告警内容如：pid:24 nid:4 exception:mainstem:pid:24 canal elapsed 5000 seconds no data ，切换mainstem也不能解决问题，重启整个服务会恢复一段时间，不知道大神们有没有遇到类似问题，或者有啥解决方案？

**Comment by hittanic** [comment]
我们也有一样的问题，不过好像不影响同步

**Comment by agapple** [comment]
应该是canal早期版本的源端库无数据的问题，尝试升级一下otter和canal版本吧
