### ISSUE TITLE
当我使用canal kafka官方案例对接mysql时报错

### ISSUE THREAD

**Issue by whx1121** [alibaba/canal#3884]
## canal version
canal.deployer-1.1.4
## kafka version
kafka_2.11-1.1.1

对接时报错：
![image](https://user-images.githubusercontent.com/46316012/138820279-c50602f2-0d27-489f-a7d2-9f0f7653998d.png)

**Comment by agapple** [comment]
发送和接收的flatMessage估计不对齐
