### ISSUE TITLE
Canal支持Tidb的binlog转发kafka么

### ISSUE THREAD

**Issue by larry0xff** [alibaba/canal#3885]
因为文档中写的是使用mysql，不知道是否支持tidb

**Comment by hi-rustin** [comment]
可以使用 [TiCDC](https://docs.pingcap.com/zh/tidb/stable/ticdc-overview/)。

**Comment by agapple** [comment]
1.  tidb无法兼容mysql binlog，只能使用其内置工具
2. PolarDB-X作为分布式数据库，可以完全兼容mysql binlog，canal就可以正常对接。参考：https://github.com/alibaba/canal/issues/3494
