### ISSUE TITLE
batchSize设置为1的时候

### ISSUE THREAD

**Issue by lzb112** [alibaba/canal#3886]
奇怪，调用getWithoutAck(int batchSize, Long timeout, TimeUnit unit)

getWithoutAck(1,0L, TimeUnit.MILLISECONDS)

batchSize为1的时候需要修改2条或以上才会返回，batchSize为2的时候需要修改4条或以上才会返回

**Comment by agapple** [comment]
这个是根据memunit单位来看，不是以条数，而是以内存大小
