### ISSUE TITLE
canal-adapter release 1.1.5 的版本 java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by husenlinwei** [alibaba/canal#3889]
### 环境

* canal v1.1.5
* mysql 8.0.x

### 问题描述
在配置canal-adapter es7 启动时出现了这个NPE错误，canal工作一切正常。

![image](https://user-images.githubusercontent.com/32996734/139358771-6af3812b-3c87-47c4-b2d2-cb5994258fd7.png)

![image](https://user-images.githubusercontent.com/32996734/139358867-cde8d555-d287-488e-9949-8a2d277eaa39.png)

![image](https://user-images.githubusercontent.com/32996734/139360921-29476166-d76b-4f8c-806f-511b0c30b1ce.png)

### 我的 application.yml，参考官方指南配置

![image](https://user-images.githubusercontent.com/32996734/139358994-41acf207-48ce-46b0-81c7-b3310ea136e9.png)

我确信canal-adapter已经加载此文件，因为日志如下

![image](https://user-images.githubusercontent.com/32996734/139359094-c4d32782-e1b2-4d17-8080-8c22b078900a.png)

并且启动端口也是为配置文件里面的8081。

所以什么情况下会导致它没有正确解析properties模块？

**Comment by leetomlee123** [comment]
me too ,do u handle it
