### ISSUE TITLE
canal is not run any in node  failed to connect to:/1.0.0.1:7536 after retry 1 times

### ISSUE THREAD

**Issue by mi9944** [alibaba/canal#389]
2017-09-27/14:33:30.751||||^_^|uid:|clientIp:|deviceId:|^_^|[binlog main] ERROR c.a.o.c.client.impl.running.ClientRunningMonitor 137 - There is an error when execute initRunning method, with destination [es1].
434654-com.alibaba.otter.canal.protocol.exception.CanalClientException: java.net.ConnectException: Connection refused
434655-	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.doConnect(SimpleCanalConnector.java:171)
434656-	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.access$000(SimpleCanalConnector.java:48)
434657-	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector$1.processActiveEnter(SimpleCanalConnector.java:396)
434658-	at com.alibaba.otter.canal.client.impl.running.ClientRunningMonitor.processActiveEnter(ClientRunningMonitor.java:207)
434659-	at com.alibaba.otter.canal.client.impl.running.ClientRunningMonitor.initRunning(ClientRunningMonitor.java:118)
434660-	at com.alibaba.otter.canal.client.impl.running.ClientRunningMonitor.start(ClientRunningMonitor.java:92)
434661-	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.connect(SimpleCanalConnector.java:93)
434662-	at com.alibaba.otter.canal.client.impl.ClusterCanalConnector.connect(ClusterCanalConnector.java:63)
434663-	at com.alibaba.otter.canal.client.impl.ClusterCanalConnector.restart(ClusterCanalConnector.java:275)
434664-	at com.alibaba.otter.canal.client.impl.ClusterCanalConnector.getWithoutAck(ClusterCanalConnector.java:187)
434665-	at com.domain.es.canal.Consumer$HandlerThread.run(BinLogConsumer.java:194)
434666-Caused by: java.net.ConnectException: Connection refused
434667-	at sun.nio.ch.Net.connect0(Native Method)
434668-	at sun.nio.ch.Net.connect(Net.java:454)
434669-	at sun.nio.ch.Net.connect(Net.java:446)
434670-	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648)
434671-	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.doConnect(SimpleCanalConnector.java:132)
434672-	... 10 common frames omitted
434673-2017-09-27/14:33:30.759||||^_^|uid:|clientIp:|deviceId:|^_^|[binlog main] WARN  c.a.otter.canal.client.impl.ClusterCanalConnector 66 - failed to connect to:/1.0.0.1:7536 after retry 1 times
434674-2017-09-27/14:33:30.761||||^_^|uid:|clientIp:|deviceId:|^_^|[binlog main] WARN  c.a.o.c.client.impl.running.ClientRunningMonitor 174 - canal is not run any in node

**Comment by agapple** [comment]
Caused by: java.net.ConnectException: Connection refused

**Comment by sunyaf** [comment]
hi 我遇到啦相同的问题，你是怎么解决的呀
