### ISSUE TITLE
canal.metrics.pull.port = 11112

### ISSUE THREAD

**Issue by yx-Yaoxaing** [alibaba/canal#3891]
我想理解下 这个端口是干嘛用的哦 我看源码当中使用HttpServer启动了这个端口。canal.port = xxxxx 我知道是作为canal服务器的端口连接 但是这个我没有理解到。

**Comment by agapple** [comment]
统计信息的端口，可以参考:https://github.com/alibaba/canal/wiki/Prometheus-QuickStart
