### ISSUE TITLE
canal1.1.5采集阿里云的mysql8.0 rds到kafka insert或update类型都变成了query

### ISSUE THREAD

**Issue by lanmaodage** [alibaba/canal#3893]
kafka里面的数据长这样的：
{"data":null,"database":"","es":1635503718000,"id":327,"isDdl":false,"mysqlType":null,"old":null,"pkNames":null,"sql":"/* Query from DMS-WEBSQL-0-Qid_1635503718577 byuser 285909287365559970 */ INSERT INTO test01 values(1,\"liuj\")","sqlType":null,"table":"test01","ts":1635503747090,"type":"QUERY"}
或
{"data":null,"database":"","es":1635503713000,"id":55,"isDdl":false,"mysqlType":null,"old":null,"pkNames":null,"sql":"UPDATE `t_user` SET `last_visit_at`='2021-10-29 18:35:13' WHERE `id` = 99","sqlType":null,"table":"t_user","ts":1635503713996,"type":"QUERY"}
  全部都是query类型的，这个是bug吗@agapple

**Comment by BaliStarDUT** [comment]
https://github.com/alibaba/canal/wiki/FAQ

看看Q1能不能解答

**Comment by lanmaodage** [comment]
> https://github.com/alibaba/canal/wiki/FAQ
> 
> 看看Q1能不能解答

感谢老哥，顺便还处理了kafka分区0大量query类型数据导致数据异常倾斜的问题
得把这个
canal.instance.filter.query.dml=true
给加上

**Comment by lanmaodage** [comment]
> https://github.com/alibaba/canal/wiki/FAQ
> 
> 看看Q1能不能解答

rds的日志格式是没有问题的
把 canal.instance.filter.query.dml=true 加上，QUERY类型的全部没有了，也就是所有的数据都没有过来了，其它的instance倒正常，查了近7天的kafka消息全部是QUERY类型的，这好奇怪了

**Comment by lanmaodage** [comment]
找到问题了，在black里那表过滤了，导到采集的非query数据没有过来，但是这个black不影响query的采集！！

**Comment by helpisyou** [comment]
我配置了canal.instance.filter.query.dml=true依然过滤不了QUERY的日志。附上配置
![Uploading image.png…]()

**Comment by helpisyou** [comment]
我配置了canal.instance.filter.query.dml=true依然过滤不了QUERY的日志。附上配置
#binlog filter config
canal.instance.filter.druid.ddl=true
canal.instance.filter.query.dcl=true
canal.instance.filter.query.dml=true
canal.instance.filter.query.ddl=true

canal.instance.filter.druid.ddl = true
canal.instance.filter.table.error=true
canal.instance.filter.rows=false
canal.instance.filter.transaction.entry=true
canal.instance.filter.dml.insert=false
canal.instance.filter.dml.update=false
canal.instance.filter.dml.delete=false
