### ISSUE TITLE
新手求助-使用canal-admin之后报错

### ISSUE THREAD

**Issue by liyingjie1997** [alibaba/canal#3895]
![image](https://user-images.githubusercontent.com/87856183/139658577-f9311c5f-d231-41a4-a74d-f81d88b976dc.png)
2021-11-01 18:07:59.508 [New I/O server worker #3-2] ERROR c.a.o.c.common.zookeeper.running.ServerRunningMonitor - start failed
com.google.common.util.concurrent.UncheckedExecutionException: com.alibaba.otter.canal.server.exception.CanalServerException: can't find destination:example

使用canal-admin后用canal_local.properties启动的canal     sh bin/startup.sh local
然后在admin管理界面配置的instance和server 
配置内容和canal.properties相同
出现图中报错

没有用canal-admin之前直接用canal.properties 启动没有报错 sh bin/startup.sh

**Comment by agapple** [comment]
找不到example队列的配置

**Comment by Berzrk** [comment]
这问题出现在使用了canal_local.properties缺少了canal.destinations = example配置，真的看文档看得好懵 不知道怎么配
