### ISSUE TITLE
canal+rokectmq  一直死循环往队列里发送一样的消息

### ISSUE THREAD

**Issue by 13906568663** [alibaba/canal#3898]
## Question

![image](https://user-images.githubusercontent.com/38032667/139825574-480f4475-e4b9-459d-b5c8-e176c1b1b2a7.png)
一亿多条重复数据，点位一点都没有前进
![image](https://user-images.githubusercontent.com/38032667/139826440-7826a468-b649-4e25-9b38-870b8619af9d.png)
我们
测试环境的binlog是日删的
最近我们有改过对应的读取点位的值
错误日志因为时间有点久了，找不到了。我再想办法复现
我想知道可能是什么原因会造成这个问题

**Comment by 13906568663** [comment]
![lQLPDhrUqVcFYdnNAazNBfOww4reBGsi5F8BiarZOoBYAA_1523_428](https://user-images.githubusercontent.com/38032667/139830216-61bc9492-33b7-4753-a6e6-bd158a9c5108.png)
补充下 一直再死循环爆出来的错

**Comment by weigxnow** [comment]
遇到了同样的问题，版本：canal.deployer-1.1.5

**Comment by 13906568663** [comment]
目前在 动态topic的基础上又 增加了固定topic ，虽然没有在出现找不到topic的错，但是感觉 这个不是出现一直发重复的数据的问题

**Comment by weigxnow** [comment]
试试自动回复你好，您的邮件已收到，我尽快给你回复。

**Comment by HelloWorldJoe** [comment]
你好，请问这个问题找到原因了吗？我也遇到了一样的问题不知道是咋引起的

**Comment by weigxnow** [comment]
试试自动回复你好，您的邮件已收到，我尽快给你回复。
