### ISSUE TITLE
canal rocketMq动态topic无法匹配到topic

### ISSUE THREAD

**Issue by god8816** [alibaba/canal#3901]
### environment
mac

* canal version
*  1.5
* mysql version 5.7

### Actual behaviour
public static boolean matchDynamicTopic(String name, String dynamicTopicConfigs) {
        if (StringUtils.isEmpty(dynamicTopicConfigs)) {
            return false;
        }

        boolean res = false;
        List<DynamicTopicData> datas = dynamicTopicDatas.get(dynamicTopicConfigs);
        for (DynamicTopicData data : datas) {
            if (data.simpleName != null) {
                if (data.simpleName.equalsIgnoreCase(name)) {
                    res = true;
                    break;
                }
            } else if (name.contains(".")) {
                if (data.tableRegexFilter != null && data.tableRegexFilter.filter(name)) {
                    res = true;
                    break;
                }
            } else {
                if (data.schemaRegexFilter != null && data.schemaRegexFilter.filter(name)) {
                    res = true;
                    break;
                }
            }
        }
        return res;
    }

canal.mq.dynamicTopic=canal_tms_delivery_order_detail:tms_0\.tms_delivery_order_detail_..*,canal_tms_delivery_order_settlement:tms_0\.tms_delivery_order_settlement_..*,canal_tms_delivery_order_logistics:tms_0\.tms_delivery_order_logistics_..*,canal_tms_delivery_order:tms_0\.tms_delivery_order_..*

动态topic无法匹配：因为data.tableRegexFilter为空

**Comment by god8816** [comment]
canal.mq.dynamicTopic=canal_tms_delivery_order_detail:tms_0.tms_delivery_order_detail_\\..*,canal_tms_delivery_order_settlement:tms_0.tms_delivery_order_settlement_\\..*,canal_tms_delivery_order_logistics:tms_0.tms_delivery_order_logistics_\\..*,canal_tms_delivery_order:tms_0.tms_delivery_order_\\..*   这种也不行，我调试发现表达式多个\.导致无法匹配

**Comment by god8816** [comment]
![Uploading 企业微信截图_2eaa37cf-ab85-4ea9-9d12-13e105a24360.png…]()

**Comment by agapple** [comment]
转义符需要双斜杠
