### ISSUE TITLE
CLIENTAUTHENTICATION is NOT supported

### ISSUE THREAD

**Issue by zhujintao** [alibaba/canal#3905]
并发连接不通的服务端其中一个连接时报错something goes wrong when doing authentication:packet type=CLIENTAUTHENTICATION is NOT supported!

time="2021-11-04T10:54:28+08:00" level=info msg="something goes wrong when doing authentication:packet type=CLIENTAUTHENTICATION is NOT supported!" src=ncc
time="2021-11-04T10:54:28+08:00" level=info msg="<nil>" src=default

**Comment by zhujintao** [comment]
close.

**Comment by bain2018** [comment]
怎么解决的

**Comment by zDemon** [comment]
大佬，这个问题怎么解决的呢

**Comment by zhujintao** [comment]
> 大佬，这个问题怎么解决的呢
@bain2018 

并发的话，两个通道连错了。代码逻辑上看下

**Comment by zDemon** [comment]
> 

好的感谢，我用的是go的client，发现里面的SimpleCanalConnector如果多线程起多个connector就会有并发问题，导致这个issues的问题，以及ack也会乱序

**Comment by zDemon** [comment]
> > 大佬，这个问题怎么解决的呢
> > @bain2018
> 
> 并发的话，两个通道连错了。代码逻辑上看下

好的感谢，我用的是go的client，发现里面的SimpleCanalConnector如果多线程起多个connector就会有并发问题，导致这个issues的问题，以及ack也会乱序
