### ISSUE TITLE
Canal Client 1.1.5 依赖缺失包

### ISSUE THREAD

**Issue by codecontainer** [alibaba/canal#3906]
## Question

![image](https://user-images.githubusercontent.com/30923328/140295106-40d20e08-9a49-433e-bd9a-1e365925b88d.png)

参考1.1.4 版本应该缺失common, protocol 
仓库： 阿里Public

**Comment by agapple** [comment]
https://repo1.maven.org/maven2/com/alibaba/otter/canal.common/1.1.5/，仓库里有common相关的包
