### ISSUE TITLE
canal-1.1.4，客户端集群部署造成canal-server消息ack错乱

### ISSUE THREAD

**Issue by git-simm** [alibaba/canal#3907]
## Why you need it?

问题：使用canal-1.1.4，客户端集群部署（多客户端）连接canal-server，造成消息ack错乱。最终队列阻塞卡死。
分析：查阅了服务端源码，发现服务端可以根据clientId进行消息分组确认。但是提供的canal-client中实现的连接器将clientId写死成1001。导致多客户端并发ack时，server端响应失效
![企业微信截图_20211105112504](https://user-images.githubusercontent.com/22511408/140453350-182e2e22-5953-4fd0-8fb4-47f30d269c9a.png)

## How it could be?

1、自行处理：解决这个问题，可以自定义CanalConnector，将clientId属性暴露出来。集群中的每个客户端都单独分配clientId
2、源码改造：SimpleCanalConnector可以多提供一个构造器，把clientId暴露出来，供选用
![solution](https://user-images.githubusercontent.com/22511408/140453736-f1ab7cfc-fe6d-4dd1-a4e5-18fd508fa8c1.png)

**Comment by agapple** [comment]
目前canal-server不支持多client同时消费
