### ISSUE TITLE
CANAL从v1.0.25升级到v1.1.5监听MYSQL数据库ROCKETMQ获取不到TAG和KEY

### ISSUE THREAD

**Issue by samueljames** [alibaba/canal#3909]
## Question

升级之前TAG和KEY是自动生成获取的，请问怎么处理。
![image](https://user-images.githubusercontent.com/1705080/140676670-2d4cefce-8163-4804-ad4e-545a20e5dde1.png)

**Comment by agapple** [comment]
可以通过rocketmq.tag进行配置
