### ISSUE TITLE
canal 1.1.5 运行 demo 时rowChage.getRowDatasList()返回值为空，哪里配置有问题呀

### ISSUE THREAD

**Issue by wwj742907129** [alibaba/canal#3912]
## Question

![image](https://user-images.githubusercontent.com/20178001/141043393-29962b4a-3349-4f1a-a37a-4fc25268ca8f.png)
![image](https://user-images.githubusercontent.com/20178001/141043471-8f3b35e0-25d7-4e78-8db7-17c5ba408db0.png)
![image](https://user-images.githubusercontent.com/20178001/141043549-e3414a1a-57a5-4ec4-bab0-62efb638ee2d.png)

还有个问题就是，tcp开启后，本地添加的数据insert不会被代码canal的demo代码捕获，这是为啥呀。

**Comment by agapple** [comment]
需要开启binlog format为row模式，另外需要区分rows query log event的dml query事件
