### ISSUE TITLE
canal-adapter初始化数据的manager_ddl.sql脚本在哪里

### ISSUE THREAD

**Issue by dxdingdu** [alibaba/canal#3913]
如题，

文档：https://github.com/alibaba/canal/wiki/ClientAdapter
章节2.1.2 初始化数据
使用manager_ddl.sql脚本建表并初始化Demo数据，其中。。。
搜了整个github库都没找到manager_ddl.sql

**Comment by zhuchao941** [comment]
https://github.com/alibaba/canal/blob/master/admin/admin-web/src/main/resources/canal_manager.sql

用这个
