### ISSUE TITLE
canal-adapter配置文件srcDataSources的作用

### ISSUE THREAD

**Issue by dxdingdu** [alibaba/canal#3914]
tcp模式下使用canal-deploy作为binlog源，为什么还要配置名为“源数据库”的srcDataSources？
看文档，大部分样例中，srcDataSources的配置和outerAdapters里的jdbc url是一致的，为什么要这么重置配置？

**Comment by flowell** [comment]
srdDataSources是源数据库的url，不是目的数据库的URL。ETL功能里要从源库里load数据，就得连上源库。如果不用ETL功能，似乎不配置srcDataSources属性也不会报错。
