### ISSUE TITLE
Why does rdb client adapter change the order of `dml` in batch syncing

### ISSUE THREAD

**Issue by whhe** [alibaba/canal#3918]
## Question

The current version of the batch synchronization method in [RdbMirrorDbSyncService.java](https://github.com/alibaba/canal/blob/b54bea5e3337c9597c427a53071d214ff04628d1/client-adapter/rdb/src/main/java/com/alibaba/otter/canal/client/adapter/rdb/service/RdbMirrorDbSyncService.java) executes DDL first, and then assigns DML to different threads for synchronization. This process logic may change the order of `dml`, and it will cause unexpected errors if there are DML and DDL on the same table in one batch. I think it's a bug and want to fix it ASAP, please let me know if there is anything I missed about this design.

**Comment by flowell** [comment]
set concurrent to false in your rdb yaml configuration.
concurrent: false

**Comment by whhe** [comment]
> set concurrent to false in your rdb yaml configuration. concurrent: false

`concurrent` here is only related to the order of DML processing, DDL may still be executed in advance.

**Comment by flowell** [comment]
I have reconsidered your purposal. 
You are right because DDL execution is sync & block, DML execution may be delayed!
