### ISSUE TITLE
canal-server状态监控

### ISSUE THREAD

**Issue by nmgliangwei** [alibaba/canal#3924]
从canal-server 暴露给prometheus的里面没有找到管理 server 状态和Instance状态的指标.
比如从  canal-admin 停止了 server 或者 instance,可以暴露2个状态指标.这样可以从prometheus做告警.
主要是怕被人误操作, 点了停止,然后一直不启动.
@agapple

**Comment by agapple** [comment]
可以监控具体的延迟状态

**Comment by nmgliangwei** [comment]
@agapple 停止了 server 或者 instance ,  关于这个instance所有指标在 prometheus都没了, 所以延迟状态都拿不到了.
