### ISSUE TITLE
mysql批量更新未全部解析

### ISSUE THREAD

**Issue by hanxuanqing** [alibaba/canal#3925]
## Question
binlog中有一段多个id的update，但是看kafka中就只有2个id，这个是canal解析的有问题么？
用的是1.1.4的版本

**Comment by hanxuanqing** [comment]
是合并成list发送，全部处理即可

**Comment by hongen-superman** [comment]
兄弟，你这个问题咋解决的

**Comment by hongen-superman** [comment]
遍历entrys时解析storeValue获取到rowChage，再通过rowChage获取rowDatasList，这是正确的写法
CanalEntry.RowChange rowChage = CanalEntry.RowChange.parseFrom(entry.getStoreValue());
List<CanalEntry.RowData> rowDatasList = rowChage.getRowDatasList();

原BUG写成CanalEntry.RowData rowData = rowChage.getRowDatas(0);
这种方式解析单条sql的时候不会出现异常也能完全解析，仅当mysql端使用批量更新或批量插入例如：
update t_table set column= ‘1’ where id in （‘1’，‘2’，‘3’....）
会出现未完整解析的情况。

原因推测：当执行批量更新时。canal解析binlog日志会把数据集分散到rowDataList对象中，此时如果仅取第一条数据，就会造成数据更新不全的情况。
