### ISSUE TITLE
根据server_id过滤binlog

### ISSUE THREAD

**Issue by flowell** [alibaba/canal#3927]
## 需求描述
黑名单模式：server可以根据配置中的server_id来决定过滤哪些binlog。

## 需求背景
使用canal搭建双向同步/双主同步时，如果没有根据server_id过滤，会导致回环写。

**Comment by zjfwjm1987** [comment]
回环最后怎么处理的？

**Comment by agapple** [comment]
server_id有通过binlog event透传，可以在下游client处理

**Comment by miaopass-future** [comment]
> server_id 有通过日志传输透传，可以在日志下处理客户端事件

这个能详细说下怎么处理么，非常感谢
