### ISSUE TITLE
cancal  解析binlog的数据会保存多久？ 

### ISSUE THREAD

**Issue by Rock-liyi** [alibaba/canal#3933]
## Question

咨询一下，cancal  client 消费的时候，如果出现阻塞，消费不过来， cancal 会怎么处理？

**Comment by zhuchao941** [comment]
一般建议中间加一层kafka/rocketmq来做缓冲

**Comment by Rock-liyi** [comment]
> 一般建议中间加一层kafka/rocketmq来做缓冲

我看到有的实现是直接用的客户端从canal 消费，没有用到mq， 所以好奇 哪些场景需要使用Mq ， 哪些场景不需要使用？
