### ISSUE TITLE
Canal Admin 如何实现HA

### ISSUE THREAD

**Issue by PAcee1** [alibaba/canal#3936]
## Question
CanalAdmin实现Server HA后，如果CanalAdmin挂了，经测试 Server便不再具有HA
因为Admin挂掉后，某台Server挂掉切换时，会请求Admin读取instance信息，因为admin down无法拉取，导致再zk上可以看到running是新server但其实并没有实际工作 无法读取binlog

所以Admin本身可以实现HA吗

**Comment by PAcee1** [comment]
是否可以在被Admin管理的Server启动时，就加载instance 而非实际抢占到后

**Comment by agapple** [comment]
Admin可以部署多机啊

**Comment by jinpuxiang** [comment]
@agapple admin多机的话，需要配置轮询跳转地址(如nginx轮询转发)了吧，需要canal_server配置里用nginx转发源地址吧，这种方案可行吧
