### ISSUE TITLE
TimelineTransactionBarrier存在死锁bug

### ISSUE THREAD

**Issue by lulu2panpan** [alibaba/canal#394]
TimelineTransactionBarrier的isPermit方法中有如下代码
             `if (isTransactionBegin(event)) {
                    if (txState.compareAndSet(0, 1)) {
                        inTransaction.set(true);
                        return true; // 事务允许通过
                    }
                } else if (txState.compareAndSet(0, 2)) { // 非事务保护中
                    return true; // DDL/DCL允许通过
                }`
对于最后一个else if分支，不仅ddl和dcl的场景会进入，TransactionEnd时也可能会进入（当基于上次Position启动EventParser时，拿到的第一个事件类型是TransactionEnd）

再看TimelineTransactionBarrier的clear方法
`public void clear(Event event) {
        super.clear(event);

        if (isTransactionEnd(event)) {
            inTransaction.set(false); // 事务结束并且已经成功写入store，清理标记，进入重新排队判断，允许新的事务进入
            txState.compareAndSet(1, 0);
            // if (txState.compareAndSet(1, 0) == false) {
            // throw new
            // CanalSinkException("state is not correct in transaction");
            // }
        } else if (txState.intValue() == 2) {// 非事务中
            txState.compareAndSet(2, 0);
            // if (txState.compareAndSet(2, 0) == false) {
            // throw new
            // CanalSinkException("state is not correct in non-transaction");
            // }
        }
    }`
第一个if判断，应该多加一个条件“&& txState.intValue() != 2”，以应对上面说的TransactionEnd问题，否则txState的状态将一直为2，isPermit方法始终返回false，系统出现死锁

**Comment by lulu2panpan** [comment]
或者是把clear方法中的两个if的顺序调换一下

**Comment by agapple** [comment]
方便提交一个pull request给我？

**Comment by lulu2panpan** [comment]
好的，这两个忙完，就提
