### ISSUE TITLE
几百个DB需要进行增量同步，我该怎么弄？canal支持这么多的实例吗？

### ISSUE THREAD

**Issue by lzh123** [alibaba/canal#3947]
由于服务重构，需要将之前孤立的几百个DB数据同步到新服务下的DB中来，全量已经处理，增量方案用canal同步，但是有几百个DB，canal是否支持这么大量的

**Comment by zlxd76** [comment]
请问你这个问题解决了吗？

**Comment by agapple** [comment]
可以分成多个canal-server，每个server负责10多个db
