### ISSUE TITLE
canal如何实现只监听表字段的变化，对于同一个表中其他字段变化进行忽略。

### ISSUE THREAD

**Issue by yuanshishuju** [alibaba/canal#3949]
## Question

以下配置内容对整个表的字段都进行了监听，我这边想实现只对指定字段的变化进行监听。如何配置实现呢？

# table regex
canal.instance.filter.regex=hobby_content.t_content,hobby_content.t_label,hobby_customer.t_user
# table black regex
canal.instance.filter.black.regex=
# table field filter(format: schema1.tableName1:field1/field2,schema2.tableName2:field1/field2)
canal.instance.filter.field=hobby_content.t_label:label_name
canal.instance.filter.changed.field=true
# table field black filter(format: schema1.tableName1:field1/field2,schema2.tableName2:field1/field2)
#canal.instance.filter.black.field=

这个配置除了label_name 字段外，表内其他字段发生变化后。通过zookeeper也会监听到。

**Comment by agapple** [comment]
字段过滤只是把不需要的字段给丢弃，但还是会有event事件

**Comment by zzyymaggie** [comment]
> 字段过滤只是把不需要的字段给丢弃，但还是会有event事件

能把event事件去掉么？流量大的情况下，会导致写入kafka变慢，delay延时

**Comment by aaaasssdd** [comment]
实现过滤了吗？

**Comment by gongxk27** [comment]
@aaaasssdd 并没有，如上所说，配置了特定的字段，修改了其他字段还是会有消息上报，只是把不关心的字段丢弃了。
