### ISSUE TITLE
使用GroupEventSink时，数据变更不频繁同步卡住的解决方案

### ISSUE THREAD

**Issue by lulu2panpan** [alibaba/canal#395]
hi，agapple：
当使用GroupEventSink时，如果有一个或者多个分库一直没有binlog，那么所有paser线程都会卡在doSink方法上，导致有binlog产生的分库数据也无法消费。从代码注释上看，这么设计的原因，是为了相互协同，防止某个分库出现问题时，被落下，这样可以避免instance重启时丢数据。但同时也增大了Group模式的局限性，我们现在就有类似的场景，项目预期会有很大的数据量，提前进行了分库（8个库），但是还没有大批量推广，每天的数据量只有几千条，某些分库会长时间没有数据。

为了解决这个问题，我想到的方案有两个：
1、一个是利用心跳Sql，类似“insert into retl.xdual values(1,now()) on duplicate key update x=now()“，保证分库源源不断的有binlog产生，这样就不会卡住了。缺点是对业务系统有侵入，必须在业务库上创建一个辅助表
2、另外想到的一个方案是，改造MysqlEventParser，在内部类MysqlDetectingTimeTask的run方法中，当没有出现异常时，构造一个Heartbeat类型的Event，然后调用consumeTheEventAndProfilingIfNecessary方法，类似AbstractEventParser的buildHeartBeatTimeTask方法

你看还有没有更好的方案？

**Comment by agapple** [comment]
以前group模式的设计不太好，基于锁的方式性能太差

**Comment by lulu2panpan** [comment]
你们内部没怎么使用这种方案吗？性能差也是相对的，这种方式还是很方便的，之前8个分库需要创建8个实例，然后每个实例一堆映射配置，运维起来还是挺麻烦的。有时间的话，您那边可以想一想，看能不能有一个更好的方案，解决这种协同卡住的问题

**Comment by wingerx** [comment]
@agapple 对于group这种模式有什么好的思路吗？对于MySQL 分库分表的场景还是相当多的，但对于应用端其实不关心底层到底分了多少个库，不知道这块有什么好的建议？

**Comment by agapple** [comment]
参考：https://github.com/alibaba/canal/pull/522

**Comment by agapple** [comment]
升级一下canal 26版本试试

**Comment by toruneko** [comment]
感谢。比较关心26正式版什么时候发布。
目前我们在1.0.24上，通过patch解决死锁问题。
ps,先前1.0.25总是会出现线程卡死在connect于reconnect上。貌似在26版本里也解决了。
