### ISSUE TITLE
MYSQL数据同步至kafka，出现消息限制大小，该怎样处理？

### ISSUE THREAD

**Issue by cuishixu** [alibaba/canal#3952]
## Question

问题描述：
对数据库有批量操作（上千条数据更新），canal解析的单条数据大。
发送到kafka时，出现kafka的消息有限制。

调整过canal、kafka的消息限制到2M，还是有问题。
出现这样的情况，该怎样解决？

**Comment by agapple** [comment]
1.  调大kafka的最大包大小
2. 减少canal-server的批次大小
3. 过滤大字段
