### ISSUE TITLE
canal-adapter 1.1.5  可以高可用吗

### ISSUE THREAD

**Issue by cuishixu** [alibaba/canal#3953]
## Question

canal_deployer  作为服务server，解析mysql的binlog，canal-adapter的tcp模式连接服务server，是可以把数据同步至mysql。

我出现的问题是，假如canal-adapter挂掉，作为服务server还在跑着。当再次启动canal-adapter时，会造成数据丢失。

请问canal-adapter 1.1.5怎样高可用？

**Comment by xrff** [comment]
zookeeper

**Comment by cuishixu** [comment]
请问，怎样针对canal-adapter配置zk，做高可用？我看的里面的zk配置是针对canal_deployer 服务的高可用。

**Comment by alanredsheep** [comment]
我试过canal-adapter重启，可以断点续传

**Comment by pengchen211** [comment]
> 

canal-server端用阻塞队列保存binlog解析后的数据，当队列满时，若adapter没消费成功（返回ack）的话，server是不会再继续解析数据的，理论上是不会出现丢失

**Comment by agapple** [comment]
LS正解
