### ISSUE TITLE
ERROR c.a.o.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta - pls submit github issue

### ISSUE THREAD

**Issue by tangweichun** [alibaba/canal#3954]
2021-12-08 13:49:01.478 [[scheduler-table-meta-snapshot]] ERROR c.a.o.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta - pls submit github issue, show create table ddl:CREATE TABLE `t_etl_sino_newland_org_rel` (
  `ETL_SINO_NEWLAND_ORG_REL_ID` int NOT NULL AUTO_INCREMENT COMMENT '主键',
  `DW_SYNC_UNIQUE_ID` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL COMMENT '源端数据主键 备注:数组据使用，没有实际业务意义',
  `USER_ID` varchar(128) NOT NULL COMMENT '登录账号',
  `LOGIN_NAME` varchar(128) NOT NULL COMMENT '登录名',
  `ORG_ID` int NOT NULL COMMENT '项目id',
  `ORG_NAME` varchar(128) NOT NULL COMMENT '项目名称',
  `COMPANY` varchar(128) DEFAULT NULL COMMENT '公司名称',
  `IS_DEL` tinyint NOT NULL DEFAULT '0' COMMENT '是否删除 备注:0：正常 1：删除',
  `CREATED_TIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `LAST_MODIFIED_TIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
  `NOTE` varchar(512) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`ETL_SINO_NEWLAND_ORG_REL_ID`),
  UNIQUE KEY `DW_SYNC_UNIQUE_ID` (`DW_SYNC_UNIQUE_ID`),
  KEY `IDX_20211025105019948` (`CREATED_TIME`)
) ENGINE=InnoDB AUTO_INCREMENT=113286 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='账号项目公司关系表' , compare failed . 
 db : TableMeta [schema=`sinotrans`, table=T_ETL_SINO_NEWLAND_ORG_REL, fileds=
        FieldMeta [columnName=ETL_SINO_NEWLAND_ORG_REL_ID, columnType=int, nullable=false, key=true, defaultValue=null, extra=null, unique=false]
        FieldMeta [columnName=DW_SYNC_UNIQUE_ID, columnType=varchar(128), nullable=false, key=false, defaultValue=null, extra=null, unique=true]
        FieldMeta [columnName=USER_ID, columnType=varchar(128), nullable=false, key=false, defaultValue=null, extra=null, unique=false]
        FieldMeta [columnName=LOGIN_NAME, columnType=varchar(128), nullable=false, key=false, defaultValue=null, extra=null, unique=false]
        FieldMeta [columnName=ORG_ID, columnType=int, nullable=false, key=false, defaultValue=null, extra=null, unique=false]
        FieldMeta [columnName=ORG_NAME, columnType=varchar(128), nullable=false, key=false, defaultValue=null, extra=null, unique=false]
        FieldMeta [columnName=COMPANY, columnType=varchar(128), nullable=true, key=false, defaultValue=null, extra=null, unique=false]
        FieldMeta [columnName=IS_DEL, columnType=tinyint, nullable=false, key=false, defaultValue=0, extra=null, unique=false]
        FieldMeta [columnName=CREATED_TIME, columnType=datetime, nullable=false, key=false, defaultValue=CURRENT_TIMESTAMP, extra=null, unique=false]
        FieldMeta [columnName=LAST_MODIFIED_TIME, columnType=datetime, nullable=false, key=false, defaultValue=CURRENT_TIMESTAMP, extra=null, unique=false]
        FieldMeta [columnName=NOTE, columnType=varchar(512), nullable=true, key=false, defaultValue=null, extra=null, unique=false]
] 
 mem : TableMeta [schema=`sinotrans`, table=T_ETL_SINO_NEWLAND_ORG_REL, fileds=
        FieldMeta [columnName=ETL_SINO_NEWLAND_ORG_REL_ID, columnType=int, nullable=false, key=false, defaultValue=null, extra=null, unique=false]
        FieldMeta [columnName=DW_SYNC_UNIQUE_ID, columnType=varchar(128), nullable=false, key=false, defaultValue=null, extra=null, unique=true]
        FieldMeta [columnName=USER_ID, columnType=VARCHAR(128), nullable=false, key=false, defaultValue=null, extra=null, unique=false]
        FieldMeta [columnName=LOGIN_NAME, columnType=VARCHAR(128), nullable=false, key=false, defaultValue=null, extra=null, unique=false]
        FieldMeta [columnName=ORG_ID, columnType=INT, nullable=false, key=false, defaultValue=null, extra=null, unique=false]
        FieldMeta [columnName=ORG_NAME, columnType=VARCHAR(128), nullable=false, key=false, defaultValue=null, extra=null, unique=false]
        FieldMeta [columnName=COMPANY, columnType=VARCHAR(128), nullable=true, key=false, defaultValue=null, extra=null, unique=false]
        FieldMeta [columnName=IS_DEL, columnType=TINYINT, nullable=false, key=false, defaultValue=0, extra=null, unique=false]
        FieldMeta [columnName=CREATED_TIME, columnType=DATETIME, nullable=false, key=false, defaultValue=CURRENT_TIMESTAMP, extra=null, unique=false]
        FieldMeta [columnName=LAST_MODIFIED_TIME, columnType=DATETIME, nullable=false, key=false, defaultValue=CURRENT_TIMESTAMP, extra=null, unique=false]
        FieldMeta [columnName=NOTE, columnType=VARCHAR(512), nullable=true, key=false, defaultValue=null, extra=null, unique=false]

**Comment by xiaoma20082008** [comment]
这个字段`ETL_SINO_NEWLAND_ORG_REL_ID`从`非主键`改为`主键`了？
![image](https://user-images.githubusercontent.com/10076393/147328136-b109abd5-3c4c-4075-ac0a-02d91f972c59.png)

**Comment by tangweichun** [comment]
> 这个字段`ETL_SINO_NEWLAND_ORG_REL_ID`从`非主键`改为`主键`了？ ![image](https://user-images.githubusercontent.com/10076393/147328136-b109abd5-3c4c-4075-ac0a-02d91f972c59.png)

是的，创建表以后是有这个动作

**Comment by agapple** [comment]
看着是主键变更的原因，tsdb的刷新估计没处理好

**Comment by agapple** [comment]
验证了下1.1.6版本支持主键变更，ALTER TABLE test MODIFY id bigint AUTO_INCREMENT PRIMARY KEY;
