### ISSUE TITLE
canal丢失某个时间点的新增数据

### ISSUE THREAD

**Issue by snails-Jie** [alibaba/canal#3956]
1. 环境：mysql -> canal -> rocketmq ->消费服务 -->文件/mysql
2. canal的版本为1.1.5
3. 问题描述：
  3.1 在2021-12-03 22:34:00 至 2021-12-03 22:34:59这一分钟的时间段的新增订单（po_order）的记录，没有被记录（大概有21条，可能是业务的一次excel导入）。但34分钟之前和之后的数据都有被记录。
  3.2 rocektmq-client的日志、canal监听实例的日志、消费服务的应用日志都没有异常日志
![image](https://user-images.githubusercontent.com/52153033/145505444-17bcc62e-182b-4df6-8d6a-ac9afaaed4d3.png)
![image](https://user-images.githubusercontent.com/52153033/145505610-40b3fe34-f652-4c5e-9b22-3fe0d5c12b1d.png)

**Comment by agapple** [comment]
把canal的解析日志和客户端的日志都打印下，按照经验来看一般是client消费端的问题
