### ISSUE TITLE
Question: Will Log4j2 bug affects canal ?

### ISSUE THREAD

**Issue by 2014BDuck** [alibaba/canal#3957]
## Question
Hi. There is a bug of Apache Log4j2 being exposed recently. May I confirm if canal is safe to use, or will be affected (and could be fixed recently) ?

Related links: 
- https://mp.weixin.qq.com/s/WBbAthHY36qY0w9e4UUl4Q
- https://twitter.com/P0rZ9/status/1468949890571337731

**Comment by willmao** [comment]
canal admin和canal deployer使用logback打的日志，没啥问题
