### ISSUE TITLE
CanalClientException：java.io.IOException：Connection reset by peer

### ISSUE THREAD

**Issue by dangpf** [alibaba/canal#3958]
## Question

![微信图片_20211210134913](https://user-images.githubusercontent.com/13655991/145527426-e1c2dcf1-7d6b-45e8-b28e-6cf441895eab.png)

canal 使用的v1.1.4版本

**Comment by dingyufei615** [comment]
解决了吗 我也遇到这个问题

**Comment by fujia1992** [comment]
我也遇到这个问题了

**Comment by zhangweihong** [comment]
同样求问 怎么解决的
