### ISSUE TITLE
Canal Admin 新增集群的时候填入的zk地址起到什么作用呢

### ISSUE THREAD

**Issue by yalunwang** [alibaba/canal#3961]
## Question

Canal Admin 在新增集群的时候填入的zk地址起到什么作用呢？ 创建的两个集群填入的zk地址一样会有什么影响吗？麻烦大佬们回复一下

**Comment by yutaoChina** [comment]
会的

**Comment by agapple** [comment]
zookeeper集群主要用于多canal-server之间的高可用协同问题
