### ISSUE TITLE
使用mq的意义是什么？

### ISSUE THREAD

**Issue by xrff** [alibaba/canal#3962]
mq用来提升性能？用来削峰填谷增加稳定性？可否有相关文档介绍tcp模式和mq模式的区别？

**Comment by mxd-321** [comment]
使用mq，可以在源端和目标端之间做个缓冲。如果不使用mq时，比如源端推送比较猛烈，目标端写入数据比较缓慢，会导致目标端的数据库崩溃。所以在中间用mq做为缓冲，提升整体的稳定性吧，个人理解。

**Comment by agapple** [comment]
LS正解
