### ISSUE TITLE
如何拆分一个大的binlog报文

### ISSUE THREAD

**Issue by liujinhui1994** [alibaba/canal#3963]
## Question
我现在消费binlog日志，上游mysql会经常进行大批量的操作。kafka报文消息中单条kafka消息中会包含多条数据，是否又办法进行一个拆分呢？比如如果是一个大的报文，即：同一个报文中包含了100条数据，是否支持拆分成20条数据为一个报文进行发送？

**Comment by liujinhui1994** [comment]
@agapple  你可以帮助我吗？

**Comment by agapple** [comment]
目前binlog本身会有一定的拆包行为，canal在解析binlog后发送给MQ，可以通过设置partition策略来将大binlog拆分
