### ISSUE TITLE
[Docs] The download link in Zookeeper QuickStart needs to be updated

### ISSUE THREAD

**Issue by xy720** [alibaba/canal#3967]
- [x] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### Issue Description

![image](https://user-images.githubusercontent.com/22125576/146161752-2aa3874a-ba6e-4bf6-8785-f229d40c494d.png)

Suggest change to 

```
wget http://mirror.olnevhost.net/pub/apache/zookeeper/zookeeper-3.5.9/apache-zookeeper-3.5.9-bin.tar.gz
tar zxvf apache-zookeeper-3.5.9-bin.tar.gz
mv apache-zookeeper-3.5.9-bin /usr/local/zookeeper
```

**Comment by agapple** [comment]
tks

**Comment by agapple** [comment]
done
