### ISSUE TITLE
RowChange中isDdl字段值的问题

### ISSUE THREAD

**Issue by zhangxiang0823** [alibaba/canal#397]
使用官方提供的clent example，RowChange.parseFrom(entry.getStoreValue()); update、insert、delete语句转换结果 isDdl的值为true，且rowChage.getRowDatasList()的list长度为0.当前使用canal版本是1.0.24 mysql版本是5.6.26-log。请问是什么原因导致的解析问题。

**Comment by agapple** [comment]
确认使用为ROW模式，还有一点mysql 5.6会有rows query对象，可以canal.instance.filter.query.dml改为true
