### ISSUE TITLE
canal.instance.filter.transaction.entry =true 参数不起作用

### ISSUE THREAD

**Issue by llzzll** [alibaba/canal#3979]
canal1.1.5版本。开启了rocketmq模式。flatmessage=false

canal.instance.filter.transaction.entry 设为 true，其他filter为默认

message依旧是大量的TRANSACTIONBEGIN和TRANSACTIONEND

**Comment by zjfwjm1987** [comment]
请问，这个问题解决了吗?

**Comment by llzzll** [comment]
> 请问，这个问题解决了吗?

这个参数一直不起作用，后来看了下源码后。
把canal1.1.5\conf\XXXXXX\instance.properties的
canal.mq.dynamicTopic参数打开就行了
根据源码显示，开了动态topic时，canal不需要任何配置就会自动过滤掉transaction起止的binlog
