### ISSUE TITLE
docker v1.1.5构建 dynamicTopic配置单表单topic,在分表后的配置问题

### ISSUE THREAD

**Issue by ACBBQ** [alibaba/canal#3981]
### environment
docker image v1.1.5
mq
centos
### Issue Description
在分表情况下,dynamicTopic配置为
topic_0:database.table_0,topic_1:database.table_1,topic_2:database.table_2,
table_0,table_1,table_2都走了topic_0,理论上各走各的,不是吗

**Comment by agapple** [comment]
理解没错
