### ISSUE TITLE
请完善文档：请忽略artorias1024这孤儿

### ISSUE THREAD

**Issue by angleGhost** [alibaba/canal#3989]
能不能将admin和server的文档写清楚点？
application.yml配置文件中莫名其妙多出canal字段配置也不解释；
server中配置admin需要和数据库中的md5相同才能连接也不说明；
每个版本的配置文件变化也不说明；
真的是大写的无语！！！

**Comment by artorias1024** [comment]
- - 只会一味的索取，你又为canal 贡献什么了呢？

**Comment by angleGhost** [comment]
> * * 只会一味的索取，你又为canal 贡献什么了呢？

文档不好就是不好，这是事实。你废这么多话它还是不好。1.1.5版本模板配置文件部分字段没说明就是没说明啊，承认自己的缺点很难？你很自卑？我索取，我什么时候索取过？你爸妈没教你认字？还是没有爸妈啊？你不服我们可以线下“交流”，还引战，你不服就来干

**Comment by artorias1024** [comment]
> > * * 只会一味的索取，你又为canal 贡献什么了呢？
> 
> 文档不好就是不好，这是事实。你废这么多话它还是不好。1.1.5版本模板配置文件部分字段没说明就是没说明啊，承认自己的缺点很难？你很自卑？我索取，我什么时候索取过？你爸妈没教你认字？还是没有爸妈啊？你不服我们可以线下“交流”，还引战，你不服就来干

急了急了他急了。你感觉不好你就别用呗？你自己牛逼你就自己写一个出来 ok? 你要是感觉开源的不好用就去买商用的不行？ 跑过来逼逼赖赖，让别人给你完善文档，自己不会提PR? 伸手党果然牛逼。啥也不是。

**Comment by angleGhost** [comment]
> 

啊哟喂，这条舔狗舔的个叫专业啊，你看别人叼你吗？黑龙江的风把你爸妈吹死了？生出你个无脑儿，张口闭口就来？还别用，轮得到你说话吗？以为在阿里云开个服务器搭个博客就他妈的牛逼了。老子的问题你看了吗就开黄腔？脑子这个东西挺好，你就是没有啊，眼睛也没啥用，你说你这种算不算二级残疾啊，不会没给你发证吧。忘记了你是个孤儿。还会PR了，还伸手党说的就是你吧。我在给阿里做贡献的时候，你还在高考吧！你玩的明白吗？无知儿童，好好读书，不然对不起你过世的家人。整天在这里学狗叫，狗都嫌弃你，哈哈。

**Comment by artorias1024** [comment]
> > 
> 
> 啊哟喂，这条舔狗舔的个叫专业啊，你看别人叼你吗？黑龙江的风把你爸妈吹死了？生出你个无脑儿，张口闭口就来？还别用，轮得到你说话吗？以为在阿里云开个服务器搭个博客就他妈的牛逼了。老子的问题你看了吗就开黄腔？脑子这个东西挺好，你就是没有啊，眼睛也没啥用，你说你这种算不算二级残疾啊，不会没给你发证吧。忘记了你是个孤儿。还会PR了，还伸手党说的就是你吧。我在给阿里做贡献的时候，你还在高考吧！你玩的明白吗？无知儿童，好好读书，不然对不起你过世的家人。整天在这里学狗叫，狗都嫌弃你，哈哈。

我他妈笑了。还给尼玛给阿里做贡献。你给阿里贡献啥了。来来来，发出来我看看。还尼玛跑这儿来逼逼了。

**Comment by cody1993** [comment]
打工了一年，终于找到点发泄发泄 💯

**Comment by artorias1024** [comment]
@angleGhost 别关issues啊。让大家都来看看。

**Comment by LB-J** [comment]
@angleGhost 支持，事情要做就做好，要么就不做！这是责任！

**Comment by angleGhost** [comment]
> > > 
> > 
> > 
> > 啊哟喂，这条舔狗舔的个叫专业啊，你看别人叼你吗？黑龙江的风把你爸妈吹死了？生出你个无脑儿，张口闭口就来？还别用，轮得到你说话吗？以为在阿里云开个服务器搭个博客就他妈的牛逼了。老子的问题你看了吗就开黄腔？脑子这个东西挺好，你就是没有啊，眼睛也没啥用，你说你这种算不算二级残疾啊，不会没给你发证吧。忘记了你是个孤儿。还会PR了，还伸手党说的就是你吧。我在给阿里做贡献的时候，你还在高考吧！你玩的明白吗？无知儿童，好好读书，不然对不起你过世的家人。整天在这里学狗叫，狗都嫌弃你，哈哈。
> 
> 我他妈笑了。还给尼玛给阿里做贡献。你给阿里贡献啥了。来来来，发出来我看看。还尼玛跑这儿来逼逼了。

**Comment by angleGhost** [comment]
真她妈无语，黑龙江的都是这种无脑儿？承认无脑儿了？自己不是白嫖的？自己都白嫖还看不起其他人，来搞笑的？我说的问题不是真实存在的问题？1.1.5版本的文档写清楚了？搞不清楚瞎几把乱喷

**Comment by angleGhost** [comment]
> 打工了一年，终于找到点发泄发泄，成功逗笑了大家。感谢 @angleGhost

开源的项目这么多，文档没有问题才能少走弯路，作为阿里的仓库，这点算要求吗？而且我说的是请完善，有没有说要求完善。这逼人啥也不看，张口就来，估计是通电晚，咱们要理解！

**Comment by angleGhost** [comment]
> > > 
> > 
> > 
> > 啊哟喂，这条舔狗舔的个叫专业啊，你看别人叼你吗？黑龙江的风把你爸妈吹死了？生出你个无脑儿，张口闭口就来？还别用，轮得到你说话吗？以为在阿里云开个服务器搭个博客就他妈的牛逼了。老子的问题你看了吗就开黄腔？脑子这个东西挺好，你就是没有啊，眼睛也没啥用，你说你这种算不算二级残疾啊，不会没给你发证吧。忘记了你是个孤儿。还会PR了，还伸手党说的就是你吧。我在给阿里做贡献的时候，你还在高考吧！你玩的明白吗？无知儿童，好好读书，不然对不起你过世的家人。整天在这里学狗叫，狗都嫌弃你，哈哈。
> 
> 我他妈笑了。还给尼玛给阿里做贡献。你给阿里贡献啥了。来来来，发出来我看看。还尼玛跑这儿来逼逼了。

谁他妈跑这哔哔了？谁先哔哔的死全家好吧！真是脑子被炮崩了，还发出来给你看，你配吗？关了吧，这人非要证明自己无脑，来吧，满足你！

**Comment by angleGhost** [comment]
> @angleGhost 别关issues啊。让大家都来看看。

关了是想把你永远留在历史中，懂？标题没看到？没看到也没关系，我原谅你了，毕竟残疾嘛
