### ISSUE TITLE
MultiStageCoprocessor这个名称的线程占用CPU很高

### ISSUE THREAD

**Issue by funnyx6** [alibaba/canal#3990]
## Question

请问为什么canal这个进程下，有几个MultiStageCoprocessor这种名称的线程一直占用CPU很高？

**Comment by artorias1024** [comment]
关闭并行解析

**Comment by funnyx6** [comment]
> 关闭并行解析
这样会对解析binlog性能有什么影响？

**Comment by artorias1024** [comment]
> > 关闭并行解析
> > 这样会对解析binlog性能有什么影响？

理论上不会有影响

**Comment by funnyx6** [comment]
> > > 关闭并行解析
> > > 这样会对解析binlog性能有什么影响？
> 
> 理论上不会有影响

那这个并行解析的意义是什么，不是很理解。

**Comment by agapple** [comment]
并行解析可以关闭
