### ISSUE TITLE
使用canal 1.1.5 adapter，tcp连接，启动报错，AdapterProcessor - process error!

### ISSUE THREAD

**Issue by caipeishen** [alibaba/canal#4002]
## Question
java客户端可以接收到增量数据，使用canal 1.1.5 adapter，tcp连接，仅仅修改了canal.tcp.server.host，启动报错
AdapterProcessor - process error!
CanalClientException: java.net.ConnectException: Connection refused
![image](https://user-images.githubusercontent.com/47104943/148340044-434b6471-3033-492d-af8e-507a796b87df.png)

**Comment by aogg** [comment]
+1

**Comment by 982097710** [comment]
怎么解决的

**Comment by caipeishen** [comment]
使用canal-admin了吗，我记得用了这个将配置移到canal-admin就没有这个问题了

**Comment by caipeishen** [comment]
使用canal-admin了吗，我记得用了这个将配置移到canal-admin就没有这个问题了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月1日(星期二) 下午4:17
收件人: ***@***.***&gt;; 
抄送: "Cai ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [alibaba/canal] 使用canal 1.1.5 adapter，tcp连接，启动报错，AdapterProcessor - process error! (Issue #4002)





 
怎么解决的
 
&mdash;
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhaoyong123** [comment]
我使用docker 部署 canal-adapter 也遇到了这个问题，是端口号没有映射出来。
需要配置11111 。检查端口就好了
