### ISSUE TITLE
重启Canal导致数据重新写入kafka

### ISSUE THREAD

**Issue by Anandonzy** [alibaba/canal#4003]
近日canal升级漏洞安装包,重启canal Server 服务,发现同步mysql的binlog数据全部重新进入kafka一次,导致数据翻倍增加,想问一下有没有大佬遇到过这种问题,如何解决?

**Comment by yxd-hut** [comment]
重启的时候，时间戳有修改吗？

**Comment by Anandonzy** [comment]
什么都没有修改,好像canal底层记录的一个标志位(事物id),混乱了,然后本身01机器应该消费到第十条,02机器消费到第20条,然后重启的时候全部冲第十条开始消费了.感觉没走自己值钱记录的事物id

**Comment by agapple** [comment]
需要采用文件或者zookeeper模式记录上一次的位点
