### ISSUE TITLE
canal1.1.5 rocketmq无法连接 大佬帮个忙

### ISSUE THREAD

**Issue by yaochen990816** [alibaba/canal#4009]
canal.mq.servers和rocketmq.namesrv.addr 都配置了地址，但是好像就是读取不到
用的是admin1.1.5在线修改配置文件的 配置了地址 一直用的127.0.0.1不知道是哪里错了

ERROR c.a.o.c.c.rocketmq.producer.CanalRocketMQProducer - org.apache.rocketmq.remoting.exception.RemotingConnectException: connect to 127.0.0.1:10911 failed
java.lang.RuntimeException: org.apache.rocketmq.remoting.exception.RemotingConnectException: connect to 127.0.0.1:10911 failed

##################################################
##################################################
canal.mq.servers = 192.168.0.103:9876
rocketmq.producer.group = test
rocketmq.enable.message.trace = true
rocketmq.customized.trace.topic =
rocketmq.namespace =
rocketmq.namesrv.addr = 192.168.0.103:9876
rocketmq.retry.times.when.send.failed = 0
rocketmq.vip.channel.enabled = false
rocketmq.tag =

**Comment by agapple** [comment]
connect to 127.0.0.1:10911 failed，优先检查下网络

**Comment by beyondhjjyt** [comment]
我也是这个问题，解决了吗

**Comment by idealzouhu** [comment]
我使用 docker 启动所有中间件，也遇到了这个问题。这个要怎么解决啊？
我在配置文件里面没有看到 canal.mq.servers = 192.168.0.103:9876 这个配置选项
