### ISSUE TITLE
建议cancal1.1.5同步es7，重新出一个参考文档，目前会遇到很多问题，例如数据源打包问题

### ISSUE THREAD

**Issue by caipeishen** [alibaba/canal#4012]
## Question

求一个成功的事例

**Comment by lmikoto** [comment]
我这边之前写过一个，您可以参考一下
https://www.yuque.com/docs/share/6aa248ad-8dd4-4bfa-9c0b-288419d2cde6?# 《Canal同步mysql数据到es》

**Comment by caipeishen** [comment]
> 我这边之前写过一个，您可以参考一下 https://www.yuque.com/docs/share/6aa248ad-8dd4-4bfa-9c0b-288419d2cde6?# 《Canal同步mysql数据到es》

感谢，已经解决了
