### ISSUE TITLE
canal1.1.5 server监听mysql blog中文乱码

### ISSUE THREAD

**Issue by Ivan-try** [alibaba/canal#4013]
canal version ：1.1.5 windows
mysql version ： 5.7.33 linux
传输数据到client端采用rabbitmq方式
删除实例配置文件下的h2.mv.db、meta.dat后就不乱码了，运行一段时间后又乱码
且乱码字段类型都是text，但不是所有text类型字段都乱码
乱码如图，求解！
![image](https://user-images.githubusercontent.com/95672482/148915276-0763d502-377c-4110-8e8f-55050d0808c7.png)

**Comment by agapple** [comment]
是MQ里的消息乱码还是哪里？包括具体的字段类型以及测试数据，这些要描述清楚
