### ISSUE TITLE
otter node进程fullgc，导致同步点位不更新，一直死循环

### ISSUE THREAD

**Issue by 80552022** [alibaba/canal#402]
我们现在使用otter，遇到一个问题，我们把otter 部署到阿里云ECS机器上，同步RDS，发现一个奇怪的问题，当表（有几百万数据）添加一个字段后，并更新这个字段的默认值（1条update语句，更新几百万数据），发现otter一直在死循环的更新这几百万数据，查看select ，load详细日志也看到一直更新，并且是死循环，界面同步进度的点位一直固定在一个点，不前进，在这个过程中出现了很多次fullgc，不知道是否有影响。

**Comment by agapple** [comment]
看一下FAQ
