### ISSUE TITLE
canal-server连接mysql时Exited 139

### ISSUE THREAD

**Issue by Heyfans** [alibaba/canal#4026]
## Question

大佬们，求助！！！！！
我用docker-compose启动了一个mysql8.0
然后，执行
sh run.sh -e canal.auto.scan=false -e canal.destinations=test -e canal.instance.master.address=127.0.0.1:3306 -e canal.instance.dbUsername=mysql -e canal.instance.dbPassword=mysql -e canal.instance.connectionCharset=UTF-8 -e canal.instance.tsdb.enable=true -e canal.instance.gtidon=false
启动canal时，canal容器直接显示了Exited，没有任何log

!!!发现其他服务器上可以启动，只有这个服务器不行，不知道是不是什么环境变量的影响？？

**Comment by Heyfans** [comment]
我好像知道了原因额。。
canal用的centos6.7基础镜像，我在debian10的机器上根本跑不起来centos6.7的镜像，centos7的才可以QAQ

**Comment by shiny** [comment]
wsl 里也跑不起来，基础镜像也太旧了点

**Comment by jackhu1990** [comment]
阿里的特征，开源界的ie。

**Comment by jackhu1990** [comment]
在最新的Linux发行版中，出于安全原因，vsyscall默认为空。然而，这会破坏一些非常古老的二进制文件，它们与古代版本的glibc是静态链接的。配置vsyscall=emulate。比如wsl就要在.wslconfig配置(没有此文件需新建，注意后缀，不要建立txt)：
```
# Settings apply across all Linux distros running on WSL 2
[wsl2] 
# Sets additional kernel parameters, in this case enabling older Linux base images such as Centos 6
kernelCommandLine = vsyscall=emulate
```
配置后重启电脑。

**Comment by agapple** [comment]
1.1.7升级了docker基础镜像，最新使用centos 7.9，支持x86和arm
