### ISSUE TITLE
【BUG】MemoryEventStoreWithBuffer的cleanUntil存在问题

### ISSUE THREAD

**Issue by tsinbal** [alibaba/canal#4027]
在使用CanalServerWithEmbedded的get方法获取数据时，会直接触发ack，但是ack的同时会执行cleanUntil，导致获取的Message中的Event.ByteString被置为null

相关代码为
Event lastEvent = entries[getIndex(next)];
lastEvent.setEntry(null);
lastEvent.setRawEntry(null);

**Comment by gzydl** [comment]
MemoryEventStoreWithBuffer 存在问题，怎么解决？

**Comment by QuentinBoBoeree** [comment]
现象：当拉取到的Event是多条的时候，最后一条在ack的时候数据会被置空
