### ISSUE TITLE
启动group-instance订阅多个数据源到MQ，用zk持久化cursor数据会导致/1001/cursor节点被交替覆盖

### ISSUE THREAD

**Issue by yourse007** [alibaba/canal#4030]
背景：
canal自带的group-instance.xml里配置的MemoryLogPositionManager是纯粹基于内存记录logPosition，不满足HA；

问题：
将group-instance.xml里的MemoryLogPositionManager替换成FailbackLogPositionManager配置，会导致zk的/otter/canal/destinations/{dest}/1001/cursor数据被多个eventParser争抢覆盖

求解答：
如何对每个eventParser（即多个数据源）分别创建各自的cursor节点，让各自的logPosition互不影响

**Comment by yourse007** [comment]
看源码里CanalMQStarter创建ClientIdentity的时候把clientId写死成1001了，这样对于groupEventParser模式来讲是个bug吧。

**Comment by agapple** [comment]
不建议使用group-instance，性能会有一些问题

**Comment by yourse007** [comment]
请教下目前对于分库分表的订阅场景有什么方案吗？如果不用groupInstance，好像只能创建多个instance了

**Comment by zDemon** [comment]
> 

同求不用group instance，面对上百个分库的时候怎么处理
