### ISSUE TITLE
CanalEntry.Column 类型的 sqlType值得枚举有哪些？

### ISSUE THREAD

**Issue by YUHAI0** [alibaba/canal#4032]
## Question

我想根据这个值来定制我的同步sql是否加字符串的双引号。

**Comment by YUHAI0** [comment]
从代码级别找到varchar的类型为12，但不知道tinytext，text这些的。

**Comment by With-winds** [comment]
Canal 的 SqlType 枚举对应的是 JDBCType

**Comment by agapple** [comment]
LS正解
