### ISSUE TITLE
建议调整etl中jdbc的fetchSize策略

### ISSUE THREAD

**Issue by lmikoto** [alibaba/canal#4039]
当前fetchSize设置为Integer.MIN_VALUE，该策略会保持和server端的链接，占用大量资源，并且会在回调函数写入es，耗时很多，这些耗时都计算到了sql的查询时间里面了。观察rds监控，很多指标都会在etl的时候突增。

建议etl的时候分批操作。而不是使用fetchSize设置为Integer.MIN_VALUE

**Comment by agapple** [comment]
可以提交一个PR给我
