### ISSUE TITLE
canal HA zookeeper不更新position请大神指教

### ISSUE THREAD

**Issue by Sunninsky** [alibaba/canal#404]
如题，试了很多方式，虽然不更新zookeeper但是我不切换HA的时候，重启client端能够按照顺序执行，但是当我停掉一个切换server的时候，client又自动从之前的position运行。不明白是怎么回事，求大神指教。

**Comment by luyee** [comment]
不会，看下zk上的offset变化。 不变化配置就不对

**Comment by wolaiye1010** [comment]
server 都重启下，我刚开始也有这个问题，后来没有了
