### ISSUE TITLE
canal.instance.filter.field配置不是过滤监听的表字段吗

### ISSUE THREAD

**Issue by MumfordSons** [alibaba/canal#4042]
## Question

例如：
canal.instance.filter.field=test.order:state

但是其他字段更新的时候，也会有一条old为null的消息
{"data":[{"state":"3"}],"database":"test","es":1643108295000,"id":2,"isDdl":false,"mysqlType":{"state":"tinyint(4)"},"old":null,"pkNames":null,"sql":"","sqlType":{"state":-6},"table":"order","ts":1643108297579,"type":"UPDATE"}

**Comment by agapple** [comment]
这是过滤字段的配置
