### ISSUE TITLE
Canal1.1.5+MySQL8.0.28日志不停的刷WARN:Skipping unrecognized binlog event Unknown from: binlog.000005:20824

### ISSUE THREAD

**Issue by Sakura9797** [alibaba/canal#4047]
最近在学习canal的时候遇到了这个问题，日志摘取如下图
![image](https://user-images.githubusercontent.com/47418903/151643759-05050338-dd6a-4996-a059-8c3fab422e25.png)
另外我看了下我数据库中的binlog，发现最新的binlog的pos只到了20793，没有20824
![image](https://user-images.githubusercontent.com/47418903/151643854-2742b9c6-4b31-42c3-9460-2f4c81c40bd4.png)
另外结合canal的源码得知header.getLogPos()拿的是下一条日志的pos，于是我猜想是不是canal同步binlog的时候会拿到最新一条binlog的下一条，而下一条binlog实际上并不存在，所以报了这个错误呢（瞎猜的）？大家有没有遇到这种情况呢
![image](https://user-images.githubusercontent.com/47418903/151643868-12e08a8c-3fc1-4abf-bceb-74151f1907be.png)

**Comment by xiaoma20082008** [comment]
应该跟这两个有关 #3975  #3976

**Comment by agapple** [comment]
LS正解
