### ISSUE TITLE
非GTID模式调整为GTID模式，gtid属性值为空

### ISSUE THREAD

**Issue by daijunjian** [alibaba/canal#4050]
##env
canal.version=1.1.5
mysql.version=5.7

##question
以前是非GTID模式，现在调整为GTID模式，正常同步中，但发现zk上的position中的gtid属性值为空，gitd应该有值才对，请问大佬们这是怎么回事？
{"gtid":"","included":false,"journalName":"mysql-bin.000014","position":186042656}

**Comment by agapple** [comment]
需要重置下位点
