### ISSUE TITLE
一直报 com.taobao.tddl.dbsync.binlog.LogDecoder - Skipping unrecognized binlog event Unknown from: mysql-bin.000027:16062

### ISSUE THREAD

**Issue by run100** [alibaba/canal#4051]
- [ ] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment

* canal version 1.14
* mysql version mysql 8.0.28

### Issue Description
一直报 com.taobao.tddl.dbsync.binlog.LogDecoder - Skipping unrecognized binlog event Unknown from: mysql-bin.000027:16062
ddl 和 dml 正常

### Actual behaviour

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by xiaoma20082008** [comment]
应该跟这两个有关 #3975  #3976

**Comment by wly1618** [comment]
解决没？

**Comment by agapple** [comment]
修复代码已合并主干

**Comment by teeyog** [comment]
我这边也同样的错误，请问这个warn会导致丢数据吗，我的canal版本1.1.5，mysql版本8.0

**Comment by teeyog** [comment]
> 修复代码已合并主干
我这边也同样的错误，请问这个warn会导致丢数据吗，我的canal版本1.1.5，mysql版本8.0
