### ISSUE TITLE
binlog-format 在 MIXED 下如何获取 tableName

### ISSUE THREAD

**Issue by JohnsonCaii** [alibaba/canal#406]
如题，因为公司已经运营很长时间了，修改的话不知道会出多少问题（服务重启，从数据库更新）。

MIXED 下的信息实在是太少了，我只能拿到原声的SQL语句，是不是意味着只有对原声的SQL语句作语法分析拿出 tableName？

**Comment by agapple** [comment]
可以的，需要依赖一个sql parser即可

**Comment by agapple** [comment]
最新的26版本，已经通过完整SQL解析对应的表，可以完整获取

**Comment by JohnsonCaii** [comment]
thanks, 感谢回答
