### ISSUE TITLE
canal 1.1.5 在linux上面无法启动

### ISSUE THREAD

**Issue by PretendMask** [alibaba/canal#4066]
./startup.sh
【启动输出】
cd to /home/canal/bin for workaround relative path
LOG CONFIGURATION : /home/canal/bin/../conf/logback.xml
canal conf : /home/canal/bin/../conf/canal.properties
CLASSPATH :/home/canal/bin/../conf:/home/canal/bin/../lib/zookeeper-3.4.5.jar:/home/canal/bin/../lib/zkclient-0.10.jar:/home/canal/bin/../lib/spring-tx-5.0.5.RELEASE.jar:/home/canal/bin/../lib/spring-orm-5.0.5.RELEASE.jar:/home/canal/bin/../lib/spring-jdbc-5.0.5.RELEASE.jar:/home/canal/bin/../lib/spring-jcl-5.0.5.RELEASE.jar:/home/canal/bin/../lib/spring-expression-5.0.5.RELEASE.jar:/home/canal/bin/../lib/spring-core-5.0.5.RELEASE.jar:/home/canal/bin/../lib/spring-context-5.0.5.RELEASE.jar:/home/canal/bin/../lib/spring-beans-5.0.5.RELEASE.jar:/home/canal/bin/../lib/spring-aop-5.0.5.RELEASE.jar:/home/canal/bin/../lib/slf4j-api-1.7.12.jar:/home/canal/bin/../lib/simpleclient_pushgateway-0.4.0.jar:/home/canal/bin/../lib/simpleclient_httpserver-0.4.0.jar:/home/canal/bin/../lib/simpleclient_hotspot-0.4.0.jar:/home/canal/bin/../lib/simpleclient_common-0.4.0.jar:/home/canal/bin/../lib/simpleclient-0.4.0.jar:/home/canal/bin/../lib/protobuf-java-3.6.1.jar:/home/canal/bin/../lib/oro-2.0.8.jar:/home/canal/bin/../lib/netty-all-4.1.6.Final.jar:/home/canal/bin/../lib/netty-3.2.2.Final.jar:/home/canal/bin/../lib/mysql-connector-java-5.1.48.jar:/home/canal/bin/../lib/mybatis-spring-2.0.4.jar:/home/canal/bin/../lib/mybatis-3.5.4.jar:/home/canal/bin/../lib/logback-core-1.1.3.jar:/home/canal/bin/../lib/logback-classic-1.1.3.jar:/home/canal/bin/../lib/jsr305-3.0.2.jar:/home/canal/bin/../lib/joda-time-2.9.4.jar:/home/canal/bin/../lib/jctools-core-2.1.2.jar:/home/canal/bin/../lib/jcl-over-slf4j-1.7.12.jar:/home/canal/bin/../lib/javax.annotation-api-1.3.2.jar:/home/canal/bin/../lib/j2objc-annotations-1.1.jar:/home/canal/bin/../lib/httpcore-4.4.3.jar:/home/canal/bin/../lib/httpclient-4.5.1.jar:/home/canal/bin/../lib/h2-1.4.196.jar:/home/canal/bin/../lib/guava-22.0.jar:/home/canal/bin/../lib/fastjson-1.2.58.sec06.jar:/home/canal/bin/../lib/error_prone_annotations-2.0.18.jar:/home/canal/bin/../lib/druid-1.2.6.jar:/home/canal/bin/../lib/disruptor-3.4.2.jar:/home/canal/bin/../lib/connector.core-1.1.5.jar:/home/canal/bin/../lib/commons-logging-1.2.jar:/home/canal/bin/../lib/commons-lang3-3.7.jar:/home/canal/bin/../lib/commons-lang-2.6.jar:/home/canal/bin/../lib/commons-io-2.4.jar:/home/canal/bin/../lib/commons-compress-1.9.jar:/home/canal/bin/../lib/commons-codec-1.9.jar:/home/canal/bin/../lib/commons-beanutils-1.8.2.jar:/home/canal/bin/../lib/canal.store-1.1.5.jar:/home/canal/bin/../lib/canal.sink-1.1.5.jar:/home/canal/bin/../lib/canal.server-1.1.5.jar:/home/canal/bin/../lib/canal.protocol-1.1.5.jar:/home/canal/bin/../lib/canal.prometheus-1.1.5.jar:/home/canal/bin/../lib/canal.parse.driver-1.1.5.jar:/home/canal/bin/../lib/canal.parse.dbsync-1.1.5.jar:/home/canal/bin/../lib/canal.parse-1.1.5.jar:/home/canal/bin/../lib/canal.meta-1.1.5.jar:/home/canal/bin/../lib/canal.instance.spring-1.1.5.jar:/home/canal/bin/../lib/canal.instance.manager-1.1.5.jar:/home/canal/bin/../lib/canal.instance.core-1.1.5.jar:/home/canal/bin/../lib/canal.filter-1.1.5.jar:/home/canal/bin/../lib/canal.deployer-1.1.5.jar:/home/canal/bin/../lib/canal.common-1.1.5.jar:/home/canal/bin/../lib/aviator-2.2.1.jar:/home/canal/bin/../lib/animal-sniffer-annotations-1.14.jar:.:/usr/java/jdk-11.0.10/lib/dt.jar:/usr/java/jdk-11.0.10/lib
cd to /home/canal/bin for continue

【仅有的日志信息】：
[root@localhost canal]# tail -f canal_stdout.log 
Java HotSpot(TM) 64-Bit Server VM warning: Ignoring option PermSize; support was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: Ignoring option MaxPermSize; support was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
Unrecognized VM option 'UseCMSCompactAtFullCollection'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

【其他信息】
我的Java版本是java version "11.0.10" 2021-01-19 LTS
我是不是需要更改startup.sh脚本？如何更改？我不能更改我的jdk版本的
或许有我没有注意到的信息，
请告诉我具体发生的原因，谢谢

**Comment by PretendMask** [comment]
【解决】
根据canal_stdout.log 的错误提示我删除了startup.sh中  以下两个Java opt参数后canal成功启动
-XX:+UseCMSCompactAtFullCollection
-XX:+UseFastAccessorMethods

**Comment by agapple** [comment]
LS正解，可以考虑提交一个JVM参数优化的PR给我
