### ISSUE TITLE
请问canal-server的运行数据怎么查看呢？

### ISSUE THREAD

**Issue by KevinJay** [alibaba/canal#4069]
## 请问canal-server的运行数据怎么查看呢？

我安装的canal-server已经配置好，并且正常在运行。想请问下，目前canal-server运行的tps数据、解析速度等数据怎么查看呢？
我还没有安装canal-admin，是否可以通过什么命令查看？或者安装了canal-admin就能查看这些运行情况的数据么？

**Comment by agapple** [comment]
可以查看wiki ：https://github.com/alibaba/canal/wiki/Prometheus-QuickStart
