### ISSUE TITLE
canal 1.1.5 多表关联同步es（7.7.1） 新增数据同步报语法错误

### ISSUE THREAD

**Issue by diqi2017** [alibaba/canal#4072]
普通两表联查，没有where条件，但是会报where条件的语法错误：
![image](https://user-images.githubusercontent.com/28853704/155044125-cb19894f-a0b2-4e39-97ea-c59b2a77342f.png)
![image](https://user-images.githubusercontent.com/28853704/155044186-068fee12-dd7b-4547-b237-83e40bb5eb2d.png)
请大佬解惑是哪里出了问题

**Comment by 1512033796** [comment]
源码对group by的支持度不高，需要修改源码，具体可看https://blog.csdn.net/qq_41444892/article/details/128897217
