### ISSUE TITLE
WARN com.taobao.tddl.dbsync.binlog.LogDecoder - Skipping unrecognized binlog event Unknown from

### ISSUE THREAD

**Issue by wly1618** [alibaba/canal#4079]
目前使用的版本是1.4 我投递mysql8，现在报错如下
WARN com.taobao.tddl.dbsync.binlog.LogDecoder - Skipping unrecognized binlog event Unknown from: mysqlbin_117173306.000002:723726077

有没有解决的？

**Comment by agapple** [comment]
估计是这个：https://github.com/alibaba/canal/issues/4171
