### ISSUE TITLE
canal1.4/1.5不支持mysql 8.0.28

### ISSUE THREAD

**Issue by wly1618** [alibaba/canal#4081]
## Question

目前使用的版本是1.4/1.5 ,mysql8.0.28，一直报错 不停地刷：
WARN com.taobao.tddl.dbsync.binlog.LogDecoder - Skipping unrecognized binlog event Unknown from: mysqlbin_117173306.000002:723726077

**Comment by pruidong** [comment]
用1.1.6 在[v1.1.6-alpha-1](https://github.com/alibaba/canal/releases/tag/canal-1.1.6-alpha-1)   https://github.com/alibaba/canal/releases/tag/canal-1.1.6-alpha-1

**Comment by wly1618** [comment]
![image](https://user-images.githubusercontent.com/27405660/156289319-742a05a1-92eb-4eb8-aa90-c9945fc4a80d.png)
装了1.1.6 ，报了一个错误，

**Comment by wly1618** [comment]
> 用1.1.6 在[v1.1.6-alpha-1](https://github.com/alibaba/canal/releases/tag/canal-1.1.6-alpha-1) https://github.com/alibaba/canal/releases/tag/canal-1.1.6-alpha-1

**Comment by wly1618** [comment]
启动服务以后，服务器cup飙到400%，估计跟这个报错有关系

**Comment by pruidong** [comment]
> ![image](https://user-images.githubusercontent.com/27405660/156289319-742a05a1-92eb-4eb8-aa90-c9945fc4a80d.png) 装了1.1.6 ，报了一个错误，

配置文件按1.1.6重新配置过的?检查下配置文件

**Comment by wly1618** [comment]
![image](https://user-images.githubusercontent.com/27405660/156304889-78cc413a-d10e-4ec4-bf28-9de4f4bc6d76.png)
我这个配置测试了一下，如果换成mysql5.7就可以；

**Comment by wly1618** [comment]
您好


















在 2022-03-02 14:43:27，"prd" ***@***.***> 写道：

其他还需要改那个配置吗？

其他的没有要改的了吧，我是只改了 conf/example/instance.properties 这个文件,你参考我这个配置看看.

################################################### mysql serverId , v1.0.26+ will autoGen# canal.instance.mysql.slaveId=0# enable gtid use true/falsecanal.instance.gtidon=false



# position infocanal.instance.master.address=192.168.0.20:3306

canal.instance.master.journal.name=

canal.instance.master.position=

canal.instance.master.timestamp=

canal.instance.master.gtid=



# rds oss binlogcanal.instance.rds.accesskey=

canal.instance.rds.secretkey=

canal.instance.rds.instanceId=



# table meta tsdb infocanal.instance.tsdb.enable=true

#canal.instance.tsdb.url=jdbc:mysql://127.0.0.1:3306/canal_tsdb#canal.instance.tsdb.dbUsername=canal#canal.instance.tsdb.dbPassword=canal#canal.instance.standby.address =#canal.instance.standby.journal.name =#canal.instance.standby.position =#canal.instance.standby.timestamp =#canal.instance.standby.gtid=# username/passwordcanal.instance.dbUsername=canal

canal.instance.dbPassword=canal

canal.instance.connectionCharset = UTF-8

# enable druid Decrypt database passwordcanal.instance.enableDruid=false

#canal.instance.pwdPublicKey=MFwwDQYJKoZIhvcNA=# table regexcanal.instance.filter.regex=.*\\..*

# table black regexcanal.instance.filter.black.regex=mysql\\.slave_.*

# table field filter(format: schema1.tableName1:field1/field2,schema2.tableName2:field1/field2)#canal.instance.filter.field=test1.t_product:id/subject/keywords,test2.t_company:id/name/contact/ch# table field black filter(format: schema1.tableName1:field1/field2,schema2.tableName2:field1/field2)#canal.instance.filter.black.field=test1.t_product:subject/product_image,test2.t_company:id/name/contact/ch# mq configcanal.mq.topic=example

# dynamic topic route by schema or table regex#canal.mq.dynamicTopic=mytest1.user,mytest2\\..*,.*\\..*canal.mq.partition=0

# hash partition config#canal.mq.partitionsNum=3#canal.mq.partitionHash=test.table:id^name,.*\\..*#canal.mq.dynamicTopicPartitionNum=test.*:4,mycanal:6#################################################

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wly1618** [comment]
你那安装的数据库版本是多少?

**Comment by wly1618** [comment]
> 

你那安装的数据库版本是多少?

**Comment by wly1618** [comment]
MySQL 8.0.27与MySQL 8.0.28都是小版本更新，理论上差别不会太大，奇怪了

**Comment by Zero-Zheng** [comment]
兄弟，同样的错误，com.alibaba.otter.canal.parse.exception.CanalParseException: java.lang.IllegalArgumentException: unknow type : 12
你有解决吗？

**Comment by Zero-Zheng** [comment]
> 兄弟，同样的错误，com.alibaba.otter.canal.parse.exception.CanalParseException: java.lang.IllegalArgumentException: unknow type : 12 你有解决吗？

mysql:8.0.24版本

**Comment by pruidong** [comment]
> 

参数值传错了把，没遇到过这个问题.

**Comment by pruidong** [comment]
> 兄弟，同样的错误，com.alibaba.otter.canal.parse.exception.CanalParseException: java.lang.IllegalArgumentException: unknow type : 12 你有解决吗？

参数值传错了把，没遇到过这个问题.

**Comment by Zero-Zheng** [comment]
> 
canal.properties:
#################################################
######### 		common argument		#############
#################################################
# tcp bind ip
canal.ip =
# register ip to zookeeper
canal.register.ip =
canal.port = 11111
canal.metrics.pull.port = 11112
# canal instance user/passwd
# canal.user = canal
# canal.passwd = E3619321C1A937C46A0D8BD1DAC39F93B27D4458

# canal admin config
canal.admin.manager = 127.0.0.1:8090
canal.admin.port = 11110
canal.admin.user = admin
canal.admin.passwd = 4ACFE3202A5FF5CF467898FC58AAB1D615029441
# admin auto register
#canal.admin.register.auto = true
#canal.admin.register.cluster =
#canal.admin.register.name =

canal.zkServers =
# flush data to zk
canal.zookeeper.flush.period = 1000
canal.withoutNetty = false
# tcp, kafka, rocketMQ, rabbitMQ
canal.serverMode = tcp
# flush meta cursor/parse position to file
canal.file.data.dir = ${canal.conf.dir}
canal.file.flush.period = 1000
## memory store RingBuffer size, should be Math.pow(2,n)
canal.instance.memory.buffer.size = 16384
## memory store RingBuffer used memory unit size , default 1kb
canal.instance.memory.buffer.memunit = 1024 
## meory store gets mode used MEMSIZE or ITEMSIZE
canal.instance.memory.batch.mode = MEMSIZE
canal.instance.memory.rawEntry = true

## detecing config
canal.instance.detecting.enable = false
#canal.instance.detecting.sql = insert into retl.xdual values(1,now()) on duplicate key update x=now()
canal.instance.detecting.sql = select 1
canal.instance.detecting.interval.time = 3
canal.instance.detecting.retry.threshold = 3
canal.instance.detecting.heartbeatHaEnable = false

# support maximum transaction size, more than the size of the transaction will be cut into multiple transactions delivery
canal.instance.transaction.size =  1024
# mysql fallback connected to new master should fallback times
canal.instance.fallbackIntervalInSeconds = 60

# network config
canal.instance.network.receiveBufferSize = 16384
canal.instance.network.sendBufferSize = 16384
canal.instance.network.soTimeout = 30

# binlog filter config
canal.instance.filter.druid.ddl = true
canal.instance.filter.query.dcl = false
canal.instance.filter.query.dml = false
canal.instance.filter.query.ddl = false
canal.instance.filter.table.error = false
canal.instance.filter.rows = false
canal.instance.filter.transaction.entry = false
canal.instance.filter.dml.insert = false
canal.instance.filter.dml.update = false
canal.instance.filter.dml.delete = false

# binlog format/image check
canal.instance.binlog.format = ROW,STATEMENT,MIXED 
canal.instance.binlog.image = FULL,MINIMAL,NOBLOB

# binlog ddl isolation
canal.instance.get.ddl.isolation = false

# parallel parser config
canal.instance.parser.parallel = true
## concurrent thread number, default 60% available processors, suggest not to exceed Runtime.getRuntime().availableProcessors()
#canal.instance.parser.parallelThreadSize = 16
## disruptor ringbuffer size, must be power of 2
canal.instance.parser.parallelBufferSize = 256

# table meta tsdb info
canal.instance.tsdb.enable = true
canal.instance.tsdb.dir = ${canal.file.data.dir:../conf}/${canal.instance.destination:}
canal.instance.tsdb.url = jdbc:h2:${canal.instance.tsdb.dir}/h2;CACHE_SIZE=1000;MODE=MYSQL;
canal.instance.tsdb.dbUsername = canal
canal.instance.tsdb.dbPassword = canal
# dump snapshot interval, default 24 hour
canal.instance.tsdb.snapshot.interval = 24
# purge snapshot expire , default 360 hour(15 days)
canal.instance.tsdb.snapshot.expire = 360

#################################################
######### 		destinations		#############
#################################################
canal.destinations = spicy_instance,spicy_instance1
# conf root dir
canal.conf.dir = ../conf
# auto scan instance dir add/remove and start/stop instance
canal.auto.scan = true
canal.auto.scan.interval = 5
# set this value to 'true' means that when binlog pos not found, skip to latest.
# WARN: pls keep 'false' in production env, or if you know what you want.
canal.auto.reset.latest.pos.mode = false

canal.instance.tsdb.spring.xml = classpath:spring/tsdb/h2-tsdb.xml
#canal.instance.tsdb.spring.xml = classpath:spring/tsdb/mysql-tsdb.xml

canal.instance.global.mode = manager
canal.instance.global.lazy = false
canal.instance.global.manager.address = ${canal.admin.manager}
#canal.instance.global.spring.xml = classpath:spring/memory-instance.xml
canal.instance.global.spring.xml = classpath:spring/file-instance.xml
#canal.instance.global.spring.xml = classpath:spring/default-instance.xml

##################################################
######### 	      MQ Properties      #############
##################################################
canal.mq.flatMessage = true
canal.mq.canalBatchSize = 50
canal.mq.canalGetTimeout = 100
# Set this value to "cloud", if you want open message trace feature in aliyun.
canal.mq.accessChannel = local

canal.mq.database.hash = true
canal.mq.send.thread.size = 30
canal.mq.build.thread.size = 8

##################################################
######### 		    RabbitMQ	     #############
##################################################
rabbitmq.host=192.168.20.51:5672
rabbitmq.virtual.host=/
rabbitmq.exchange=canal.spicymedia
rabbitmq.username=admin
rabbitmq.password=xxxxxxx
rabbitmq.deliveryMode=

instance.propertios:
#################################################
## mysql serverId , v1.0.26+ will autoGen
# canal.instance.mysql.slaveId=0

# enable gtid use true/false
canal.instance.gtidon=false

# position info
canal.instance.master.address=192.168.20.50:3306
canal.instance.master.journal.name=
canal.instance.master.position=
canal.instance.master.timestamp=
canal.instance.master.gtid=

# table meta tsdb info
canal.instance.tsdb.enable=true
#canal.instance.tsdb.url=jdbc:mysql://192.168.20.50:3306/canal_tsdb
#canal.instance.tsdb.dbUsername=root
#canal.instance.tsdb.dbPassword=lankuadmin

#canal.instance.standby.address =
#canal.instance.standby.journal.name =
#canal.instance.standby.position =
#canal.instance.standby.timestamp =
#canal.instance.standby.gtid=

# username/password
canal.instance.dbUsername=root
canal.instance.dbPassword=xxxxxxx
canal.instance.connectionCharset = UTF-8
# enable druid Decrypt database password
canal.instance.enableDruid=false
#canal.instance.pwdPublicKey=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALK4BUxdDltRRE5/zXpVEVPUgunvscYFtEip3pmLlhrWpacX7y7GCMo2/JM6LeHmiiNdH1FWgGCpUfircSwlWKUCAwEAAQ==

# table regex
canal.instance.filter.regex=.*\\..*
# table black regex
canal.instance.filter.black.regex=
# table field filter(format: schema1.tableName1:field1/field2,schema2.tableName2:field1/field2)
#canal.instance.filter.field=test1.t_product:id/subject/keywords,test2.t_company:id/name/contact/ch
# table field black filter(format: schema1.tableName1:field1/field2,schema2.tableName2:field1/field2)
#canal.instance.filter.black.field=test1.t_product:subject/product_image,test2.t_company:id/name/contact/ch

# mq config
canal.mq.topic=canal.routing.key
# dynamic topic route by schema or table regex
#canal.mq.dynamicTopic=mytest1.user,mytest2\\..*,.*\\..*
canal.mq.partition=0
# hash partition config
#canal.mq.partitionsNum=3
#canal.mq.partitionHash=test.table:id^name,.*\\..*
#################################################


查找了很多，仅有楼主好像遇到相同问题。

**Comment by w237100760** [comment]
> > 兄弟，同样的错误，com.alibaba.otter.canal.parse.exception.CanalParseException: java.lang.IllegalArgumentException: unknow type : 12 你有解决吗？
> 
> mysql:8.0.24版本

我和你一样的错 解决了吗大哥

**Comment by pruidong** [comment]
> > > 兄弟，同样的错误，com.alibaba.otter.canal.parse.exception.CanalParseException: java.lang.IllegalArgumentException: unknow type : 12 你有解决吗？
> > 
> > 
> > mysql:8.0.24版本
> 
> 我和你一样的错 解决了吗大哥

我没遇到这个问题.

**Comment by Zero-Zheng** [comment]
> > > 兄弟，同样的错误，com.alibaba.otter.canal.parse.exception.CanalParseException: java.lang.IllegalArgumentException: unknow type : 12 你有解决吗？
> > 
> > 
> > mysql:8.0.24版本
> 
> 我和你一样的错 解决了吗大哥

我也还没解决，不过我是试用阶段，暂时先放弃了。 你的解决了吗？

**Comment by wly1618** [comment]
再建一个丛库MySQL版本低一些的，同步数据，依托低版本来实现

**Comment by SinyoWong** [comment]
> MySQL 8.0.27与MySQL 8.0.28都是小版本更新，理论上差别不会太大，奇怪了

确实是mysql版本问题，我尝试了8.0.28报同样错误，8.0.25是可以的。

**Comment by agapple** [comment]
https://github.com/alibaba/canal/issues/4171，应该是这个问题，mysql 8.0新增了type导致解析失败

**Comment by simonpipi** [comment]
我遇到了 java.lang.IllegalArgumentException: unknow type : 13的错误
