### ISSUE TITLE
JsonUtils中InetAddress序列化问题

### ISSUE THREAD

**Issue by kevinKaiF** [alibaba/canal#409]
JsonUtils中的InetAddressSerializer，序列化InetAddress对象是
``` java
InetAddress address = (InetAddress)object;
serializer.write(address.getHostName())
```
是获取getHostName来获取的，如果hosts中配置了主机名，那么这个值解析到的主机名
建议修改为 `address.getHostAddress()`直接获取IP
PS:JsonUtils中
``` java
 static {
        SerializeConfig.getGlobalInstance().put(InetAddress.class, JsonUtils.InetAddressSerializer.instance);
        SerializeConfig.getGlobalInstance().put(Inet4Address.class, JsonUtils.InetAddressSerializer.instance);
        SerializeConfig.getGlobalInstance().put(Inet6Address.class, JsonUtils.InetAddressSerializer.instance);
    }
```
这种方式是否太黑魔法，这样的话整个fastJson框架，在解析InetAddress对象的时候，全部是按照这种方式序列化的，而影响嵌入canal的应用程序？

**Comment by agapple** [comment]
希望保留hostname，而不是ip，特别针对是域名+vip模式的时候，域名会保持不变

**Comment by joooohnli** [comment]
我这遇到个问题：
配置文件填的数据库ip，在序列化到zk上时，会变成hostname。
又由于我们的域名解析配置的域名是不带.的，如这样： 1.2.3.4 xx
