### ISSUE TITLE
canal1.1.5  mysql批量更新或批量插入，canal生成的消息只有一条；请问能通过设置生成多条吗？

### ISSUE THREAD

**Issue by cwh2008** [alibaba/canal#4091]
您好！
   mysql批量更新或批量插入，canal生成的消息只有一条；请问能通过设置生成多条吗？
  如，一次插入多条数据insert into exam.canal_test(name) values ('232323232'),('ttttttt'),('ooooooo');
那么生成1条消息（如下），请问能通过设置，生成3条消息吗？谢谢
：{"data":[{"id":"15","name":"23232323222222","create_time":"2022-03-05 22:41:53","update_time":"2022-03-05 22:41:53"},{"id":"16","name":"ttttttt2222","create_time":"2022-03-05 22:41:53","update_time":"2022-03-05 22:41:53"},{"id":"17","name":"ooooooo222","create_time":"2022-03-05 22:41:53","update_time":"2022-03-05 22:41:53"}],"database":"exam","es":1646491313000,"id":2,"isDdl":false,"mysqlType":{"id":"int unsigned","name":"VARCHAR(100)","create_time":"TIMESTAMP","update_time":"TIMESTAMP"},"old":null,"pkNames":["id"],"sql":"","sqlType":{"id":4,"name":12,"create_time":93,"update_time":93},"table":"canal_test","ts":1646491313273,"type":"INSERT"}

**Comment by miumiu716** [comment]
threads: 1 试试

**Comment by agapple** [comment]
多条语句在binlog里是一个event事件，所以会对齐合并

**Comment by 542928492** [comment]
![e123868abad85baa9f49df612b9e1b9](https://user-images.githubusercontent.com/25193123/189878219-c78c76c4-76fc-4c22-8644-ddf8f7c0cdaf.jpg)
我想做成跟阿里云一样，一条binlog 一条mq。需要做什么配置呢。 我尝试修改batchSize=1 看起来没啥用
