### ISSUE TITLE
如何实现多个client订阅同一个canal-server，client 的filter 是 server 的filter 子集？

### ISSUE THREAD

**Issue by wowo666** [alibaba/canal#4096]
请问如何实现多个client订阅同一个canal-server（单机模式），client 的filter 是 server 的filter 子集？如： server.filter: "test.abc, test.bbc, test.ccc"  ； client-01.filter: "test.abc";   client-02.filter: "test.bbc"

**Comment by agapple** [comment]
多个client订阅需要多个destination

**Comment by yuandajn578** [comment]
也可以用MQ
