### ISSUE TITLE
canal-adapter启动出现es7 failed

### ISSUE THREAD

**Issue by herrywen-nanj** [alibaba/canal#4097]
- [ ] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment
canal v1.1.5
mysql 5.7
elasticsearch v7.17

### Issue Description
我启动的时候出现es7 failed，详细报错为下图一
![image](https://user-images.githubusercontent.com/33476935/157199862-676fa81d-f7d2-49a8-aa26-6c962c2e3b8b.png)

配置文件如下：
![image](https://user-images.githubusercontent.com/33476935/157200268-68a736c7-17e2-45ce-b04d-3f6f58ce4d78.png)
![9f45f9f8be6e916c8785512bd02abd6](https://user-images.githubusercontent.com/33476935/157200503-88f54f2c-ff11-41e8-acbd-cc1b7c8fb586.jpg)

es7的配置文件如下：
![image](https://user-images.githubusercontent.com/33476935/157199996-d4c3bed0-46ef-403e-9133-aae191b52b39.png)

**Comment by HZLHZLHZL** [comment]
将host: http://172.31.136.148:9200 改为 host: 172.31.136.148:9200   就可以了

**Comment by herrywen-nanj** [comment]
源代码编译替换client-adapter.es7x-1.1.5-jar-with-dependencies.jar，参考https://github.com/caipeishen/Learning-Note/blob/master/Canal/Canal%E5%90%8C%E6%AD%A5MySQL%E5%88%B0ES7.md
