### ISSUE TITLE
canal client可以获取到详细的insert语句，但是获取不到详细的rowdata

### ISSUE THREAD

**Issue by KaKa-Zao** [alibaba/canal#4107]
if (rowChange.getEventType() == CanalEntry.EventType.QUERY) {

                        System.out.println("eventType: "+ entry.getHeader().getEventType() + " sql --->  " + rowChange.getSql());
                        List<CanalEntry.RowData> rowDatas = rowChange.getRowDatasList();
                        System.out.println(rowDatas);
                        for (CanalEntry.RowData rowData : rowDatas) {
                            List<CanalEntry.Column> afterColumns = rowData.getAfterColumnsList();
                            List<CanalEntry.Column> beforeColumns = rowData.getBeforeColumnsList();
                            System.out.println("after: " + afterColumns);
                            System.out.println("before: " + beforeColumns);
                        }
                        continue;
                    }

**Comment by agapple** [comment]
检查下mysql binlog format
