### ISSUE TITLE
FileMixedLogPositionManager本地文件不存在时使用不了？

### ISSUE THREAD

**Issue by SeanSystem** [alibaba/canal#4111]
getLatestIndexBy当文件不存在时返回了nullPosition导致不会去拉取最新的position导致报错
 @Override
    public LogPosition getLatestIndexBy(String destination) {
        LogPosition logPosition = memoryLogPositionManager.getLatestIndexBy(destination);
        if (logPosition != null) {
            return logPosition;
        }
        logPosition = loadDataFromFile(dataFileCaches.get(destination));
        if (logPosition == null) {
            return nullPosition;
        }
        return logPosition;
    }

**Comment by agapple** [comment]
贴下具体业务报错的情况
