### ISSUE TITLE
启动adapter时报错，具体日志请看详情，有遇到过吗

### ISSUE THREAD

**Issue by cdicon-zxj** [alibaba/canal#4114]
## Question
java.lang.IllegalArgumentException: Could not resolve placeholder 'HOSTNAME%%.*' in value "history -a; history -a; printf "\033]0;%s@%s:%s\007" "${USER}" "${HOSTNAME%%.*}" "${PWD/#$HOME/\~}""
![1647770704(1)](https://user-images.githubusercontent.com/40374794/159157396-82788ca5-7011-467a-933a-84cb92cfd8af.png)

**Comment by 1535892832** [comment]
vim /etc/bashrc
unset PROMPT_COMMAND
 source /etc/bashrc

**Comment by agapple** [comment]
LS正解
