### ISSUE TITLE
Wsl下ubuntu系统docker无法启动canal-server容器，也没有日志，求解

### ISSUE THREAD

**Issue by ITenderL** [alibaba/canal#4115]
Wsl下ubuntu系统docker无法启动canal-server容器，也没有日志，求解

**Comment by xuzhongwang** [comment]
同样遇到这个问题，楼主解决了吗

**Comment by ITenderL** [comment]
没解决  后面没有在docker上部署canal，直接部署在服务器上了

**Comment by aboutZZ** [comment]
> 同样遇到这个问题，楼主解决了吗

官方docker镜像直接用sh脚本启动，没有日志输出，我这边改了下Dockerfile，运行时请自行修改启动参数。
[docker-canal-adapter](https://hub.docker.com/r/youmianzz/canal-adapter)

**Comment by agapple** [comment]
LS不错

**Comment by MutaoCn** [comment]
同遇到此问题

**Comment by pipa-yaoSir** [comment]
+1，这个问题怎么解决
