### ISSUE TITLE
canal-1.1.5 更改数据不能同步到  es 7

### ISSUE THREAD

**Issue by tumobi** [alibaba/canal#4119]
环境：macos、mysql 8、elasticsearch 7.17.1

canal 配置按教程：https://blog.csdn.net/qq_41028058/article/details/117994183

使用 `curl -X POST  http://localhost:8081/etl/es7/student.yml` 可以全量数据同步。

更改数据时，adapter.log 日志可以看到 adapter.logger 的输出，但是 es 里的数据没有变动。
<img width="1475" alt="image" src="https://user-images.githubusercontent.com/28944170/160062484-65016820-d1c9-4662-b33f-cea960390edc.png">

**Comment by FinchNie** [comment]
@tumobi 我也遇到了这个问题，请问你解决了吗

**Comment by tumobi** [comment]
> @tumobi 我也遇到了这个问题，请问你解决了吗

没有

**Comment by aston-xie** [comment]
canalAdapters:
  - instance: example # canal instance Name or mq topic name
    groups:
    - groupId: g1
      outerAdapters:
      - name: logger
      - name: es7
        hosts: http://127.0.0.1:9200  # 127.0.0.1:9200 for rest mode
        properties:
          mode: rest # ransport or rest
用这个方式

**Comment by aston-xie** [comment]
dataSourceKey: defaultDS
destination: example
groupId: g1
esMapping:
  _index: my_index
  _id: _id
#  upsert: true
#  pk: id
  sql: "SELECT id as _id, a, b, c from d"
#  objFields:
#    _labels: array:;
#etlCondition: "where d.create_time>={}"
  commitBatch: 3000
自己的yml要这样写

**Comment by FinchNie** [comment]
@aston-xie 请问可以说一下与原配置教程的区别和要修改的点吗

**Comment by tumobi** [comment]
> @aston-xie 请问可以说一下与原配置教程的区别和要修改的点吗

conf/es7/student.yml 更改 destination 的值
```
destination: example
```

**Comment by tumobi** [comment]
> dataSourceKey: defaultDS destination: example groupId: g1 esMapping: _index: my_index _id: _id sql: "SELECT id as _id, a, b, c from d" etlCondition: "where d.create_time>={}" commitBatch: 3000 自己的yml要这样写

> dataSourceKey: defaultDS destination: example groupId: g1 esMapping: _index: my_index _id: _id sql: "SELECT id as _id, a, b, c from d" etlCondition: "where d.create_time>={}" commitBatch: 3000 自己的yml要这样写

谢谢，问题已解决

**Comment by tumobi** [comment]
@aston-xie 谢谢，问题已解决

**Comment by FinchNie** [comment]
@tumobi @aston-xie 非常感谢，问题已解决
