### ISSUE TITLE
canal 1.1.5在linux上莫名其妙闪退

### ISSUE THREAD

**Issue by GankGintama** [alibaba/canal#4125]
canal 1.1.5在linux上莫名其妙就闪退了，canal.pid还在，也没有人手动kill掉，请问有方法追踪canal异常闪退吗？

**Comment by agapple** [comment]
看下dmesg，是不是主机kill

**Comment by GankGintama** [comment]
> 看下dmesg，是不是主机kill

好的 我查查

**Comment by GankGintama** [comment]
主机并没有kill掉canal的记录 请问还有什么方法定位canal闪退原因吗？
