### ISSUE TITLE
spring-beans漏洞如何修复

### ISSUE THREAD

**Issue by systemzsz** [alibaba/canal#4128]
## Question

spring-beans-3.2.18.RELEASE.jar包存在漏洞，但是替换新的版本没法兼容。请问如何解决。

**Comment by whhe** [comment]
用新版，#3182 修复了这个问题

**Comment by systemzsz** [comment]
canal-1.1.5用的是spring-beans-5.0.5.RELEASE.jar，没有修复这个问题。你指的是非正式发布版吗？那什么时候会发布正式版解决？

> 用新版，#3182 修复了这个问题
