### ISSUE TITLE
解析异常 请问如何处理

### ISSUE THREAD

**Issue by yangbeibei69** [alibaba/canal#4138]
<img width="1432" alt="image" src="https://user-images.githubusercontent.com/41147542/163515608-a0592026-4c0d-441c-9227-4a79d7bad4a9.png">

canal 1.1.5
mysql 5.7.25
数据库字符集utf8mb4

**Comment by agapple** [comment]
1.  给一个文本ddl  SQL
2. 先考虑升级1.1.6版本
