### ISSUE TITLE
关于heartbeat机制的优化

### ISSUE THREAD

**Issue by kinkeylau** [alibaba/canal#414]
现在canal与mySQL 数据库之间的heartbeat机制, 在打开detecting机制的时候(即通过发送sql语句查询的方式来探测远端是否活着) 是一直在以固定的间隔循环发送, 而没有根据现在是否有traffic的情况来决定发送, 即和binlog的heartbeat机制一样, 只有在没有traffic一段时间后才发送heartbeat消息

**Comment by agapple** [comment]
会以固定的频率发送heartbeat消息
