### ISSUE TITLE
mysql表字段发生变动，如何获取增加或者删除的字段名以及字段相关属性?

### ISSUE THREAD

**Issue by MichaelXu2015** [alibaba/canal#4142]
如一张表填加了某个字段，或者删除了某个字段，或者修改某个字段名,根据Demo代码是能获取到表的变动，但是只知道是eventType : ALTER，不知道具体变动的字段名以及是添加该字段还是删除了该字段。请问是否有API获取变动的字段名以及相关属性等?

**Comment by agapple** [comment]
client demo里获取一下ddl相关事件即可，获取之后可以解析具体的ddl语句
