### ISSUE TITLE
本地的canal.properties和canal-admin中的canal.properties优先级问题

### ISSUE THREAD

**Issue by zender-projects** [alibaba/canal#4143]
## Question

从deploy模块的CanalLauncher中发现如下代码， 配置文件的加载顺序是：先加载local canal.properties，再加载canal-admin的canal.properties，然后用local的配置覆盖 admin的配置，这不是有问题吗？ 如果用canal-admin肯定是admin的配置文件的优先级更高吧。
 managerProperties.putAll(properties);

**Comment by agapple** [comment]
允许本地客户端的一些个性化配置
