### ISSUE TITLE
canal-server instance 过滤DDL create database

### ISSUE THREAD

**Issue by saihide** [alibaba/canal#4145]
## Question

canal-server版本：1.1.5
使用方式：canal server接收到的binlog数据直接投递到MQ，阿里云的rocketmq(ons)
instance.properties 配置：
```
canal.instance.filter.regex=somedb\\..*
```
当mysql的实例有新库创建的时候，rocketmq(ons)会收到消息。

期望：canal server过滤mysql的实例新建库的DDL，不要推到mq。应该怎么配置呢？

谢谢！

**Comment by agapple** [comment]
```
canal.instance.filter.query.ddl = true
canal.instance.filter.query.dcl = true
canal.instance.filter.query.dml = true
```
