### ISSUE TITLE
source code compilation error

### ISSUE THREAD

**Issue by kennethToyuan** [alibaba/canal#4149]
[root@centos canal-canal-1.1.4]# mvn clean install -Dmaven.test.skip -Denv=release
[INFO] Scanning for projects...
Downloading: https://maven.aliyun.com/repository/public/org/sonatype/oss/oss-parent/7/oss-parent-7.pom
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project com.alibaba.otter:canal:1.1.4 (/tmp/canal-canal-1.1.4/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM: Could not transfer artifact org.sonatype.oss:oss-parent:pom:7 from/to aliyunmaven (https://maven.aliyun.com/repository/public): peer not authenticated and 'parent.relativePath' points at wrong local POM @ line 9, column 13 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
[root@centos canal-canal-1.1.4]# mvn -v
Apache Maven 3.0.5 (Red Hat 3.0.5-17)
Maven home: /usr/share/maven
Java version: 1.8.0_41, vendor: Oracle Corporation
Java home: /data/jdk/java-se-8u41-ri/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-1160.45.1.el7.x86_64", arch: "amd64", family: "unix"
[root@centos canal-canal-1.1.4]#

**Comment by agapple** [comment]
org.sonatype.oss:oss-parent:pom，这个文件下载不了
