### ISSUE TITLE
同步mariadb 10.6.7会报错，binlog解析失败

### ISSUE THREAD

**Issue by yangjing5514** [alibaba/canal#4150]
- [ ] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment

* canal version
* 1.1.6-snapshot
* mysql version
* mariadb 10.6.7

### Issue Description
解析binlog会报错，Read Q_FLAGS2_CODE error ：limit excceed 69

### Actual behaviour

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by yangjing5514** [comment]
报错截图如下：
![Uploading C8C0F59B-6284-4AE9-A441-0DB89692A936.png…]()

**Comment by agapple** [comment]
https://github.com/alibaba/canal/issues/4171，估计是8.0类似的问题
