### ISSUE TITLE
canal重复发送大量消息

### ISSUE THREAD

**Issue by ChenJie193** [alibaba/canal#4151]
## Question

数据库用的是阿里云的rds,利用canal监听rds然后发送mq到阿里云的RocketMQ服务,采用动态topic  canal.mq.dynamicTopic= 将不同表的数据发送到不同的topic。现在随机出现canal向mq发送消息的时候同一条数据库的修改重复大量发送mq消息。想问大家遇到过同样的情况没？

**Comment by wtlihao** [comment]
请问是怎么解决的？

**Comment by ChenJie193** [comment]
> 请问怎么解决的？

最后改了源码
![image](https://github.com/alibaba/canal/assets/29120785/8edd841c-1822-48d4-99eb-af5d1dba7cbe)
com.alibaba.otter.canal.connector.core.producer.MQMessageUtils#messageTopics在这个方法里加了一个判断条件

**Comment by wtlihao** [comment]
能讲解一下你是如何定位到这个问题的吗？为什么要加上EntryType.QUERY

**Comment by ChenJie193** [comment]
跟源码跟的
