### ISSUE TITLE
Docker部署Canal-Admin、Canal-Server、Rabbitmq，Canal-Server到Rabbitmq的消息同步经测试无问题，Canal-Admin创建单机Server，能联通Server，但配置instance后无法启动instance。

### ISSUE THREAD

**Issue by ChenpiDog** [alibaba/canal#4157]
- [ ] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment

* canal version
* mysql version

### Actual behaviour

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by ChenpiDog** [comment]
问题已解决，canal-admin配置instance，instance名需与canal.properties里的配置保持一致。

**Comment by zhaoyong123** [comment]
![image](https://user-images.githubusercontent.com/29479569/168280159-444c88a0-0ab7-4f77-bd69-64ec425bb22c.png)
你好，我也是instance配置启动不了，我控制台报这个错误
