### ISSUE TITLE
canal实例为啥启动不了

### ISSUE THREAD

**Issue by mobile664042** [alibaba/canal#4162]
## Question

![image](https://user-images.githubusercontent.com/1433479/167056136-27355e82-6e3e-4726-860c-5596e2caab18.png)

### ### 点启动，一直没啥反应，canal-admin与canal-server之间是怎么交互的，查看源发现只是改了数据库的而以。并没有把指令实时的发送到canal-server.

![image](https://user-images.githubusercontent.com/1433479/167056894-5ecf8bf8-b759-4776-88b9-ac12c5839dc7.png)

倒是发现这个Instance 管理页面的列表倒是会实时去canal-server获取状态。
![image](https://user-images.githubusercontent.com/1433479/167057234-f8123d79-aa81-4f25-b562-f4940b3f5612.png)

**Comment by s6341887** [comment]
canal-server的日志有打吗？

**Comment by mobile664042** [comment]
> canal-server的日志有打吗？

找到问题了， canal-server 启动的时候要加上 local参数。但是还不知道，canal-admin 与 canal-server之间是如何交互的。

**Comment by s6341887** [comment]
canal-server启动加local是因为需要指定canal-server使用的配置文件为local.properties，因为这个配置文件使用了admin的一些配置，如果不是用local的话，server能够正常启动，但是不能注册到admin，要注册到admin，就得用local这个配置文件启动，或者可以试试把local.properties的配置写到这个配置文件，或许，也可以生效，毕竟官方说的是以local.properties “覆盖” properties

**Comment by s6341887** [comment]
> > canal-server的日志有打吗？
> 
> 找到，canal-server 的问题启动时要加上 local 的，canal-admin canal-server 之间是如何与问题启动的。

canal-server启动加local是因为需要指定canal-server使用的配置文件为local.properties，因为这个配置文件使用了admin的一些配置，如果不是用local的话，server能够正常启动，但是不能注册到admin，要注册到admin，就得用local这个配置文件启动，或者可以试试把local.properties的配置写到这个配置文件，或许，也可以生效，毕竟官方说的是以local.properties “覆盖” properties

**Comment by s6341887** [comment]
> > canal-server的日志有打吗？
> 
> 找到，canal-server 的问题启动时要加上 local 的，canal-admin canal-server 之间是如何与问题启动的。

另外，我昨天在找我遇到的问题，没有找到我需要的答案，但是我偶然看到了server和admin的一部分交互，看起来就是改了数据库，所以我猜测，一部分调用了接口，一部分可能是定时去刷新了数据库，这个可能需要看源代码

**Comment by mobile664042** [comment]
> 

好像是canal-server主动去canal-admin获取数据库中的配置，但是那段代码没找到(比如停止或启动一个实例)

**Comment by s6341887** [comment]
> > 
> 
> 好像是canal-server主动去canal-admin获取数据库中的配置，但是那段代码没找到(比如停止或启动一个实例)

com/alibaba/otter/canal/admin/controller/NodeServerController.java 这个里面有admin的操作方法

**Comment by agapple** [comment]
1.  canal-server通过pull的方式轮训canal-admin的运维动作
2. canal-server客户端启动，需要使用local参数注册到canal-admin中才可以

**Comment by mobile664042** [comment]
> 2\. ，需要使用local参数注册到canal-admin中才可以

嗯，解决了，看了部分源码才明白。能帮我解释一下三个偏移量问题么。



![企业微信截图_1652445105155](https://user-images.githubusercontent.com/1433479/168712418-2a2cdcb0-8d88-4909-ae9d-3910d96bf0a3.png)
截图中的疑惑部分。
