### ISSUE TITLE
canal-adapter日志文件过大导致磁盘占满

### ISSUE THREAD

**Issue by JTjeff** [alibaba/canal#4165]
如题，使用docker部署的canal-adpter做主从同步，产生的日志文件越来越大，导致服务器磁盘占满，logback.xml已将日志设置成info形式，但日志还是越来越多

**Comment by s6341887** [comment]
可以用软连接将log文件挂到大容量磁盘，并且定期备份清理日志文件，我这边是这样的，或者您那边有什么别的好的处理方式可以与我分享一下吗？大家一起看看如何是最优解

**Comment by agapple** [comment]
LS正解
