### ISSUE TITLE
deploy配置rabbitmq，rabbitmq.deliveryMode无效和没有消息发送确认？

### ISSUE THREAD

**Issue by githuyong** [alibaba/canal#4166]
deploy的canal.property配置
##################################################
##################################################
rabbitmq.host =
rabbitmq.virtual.host =
rabbitmq.exchange =
rabbitmq.username =
rabbitmq.password =
rabbitmq.deliveryMode =

看代码，没有使用deliveryMode，也就是消息没有持久化。
还有rabbitmq也没有发送确认，这个能确认一下吗？

**Comment by agapple** [comment]
可以提交一个PR给我
