### ISSUE TITLE
canal发送kafka失败是否会导致binlog读取暂停？发送失败会有的策略？

### ISSUE THREAD

**Issue by s6341887** [alibaba/canal#4167]
遇到一个问题，canal发送kafka失败会有什么影响（线上环境kafka突然挂了，已经挂了两天，无人知晓，无法预估对业务的影响）

猜测1：停止对binlog的读取，需重启canal
猜测2：停止对binlog的读取，不断重试，直到发送成功后继续读取binlog
猜测3：继续读取binlog，不同的消息一直不断重试发送kafka，直到发送成功
猜测4：发送不成功就忽略掉，继续该读读

其中，猜测3 个人觉得不大可能，如果一直读取，且kafka一直写入失败，会消耗canal及其所在主机的资源，如果长时间无法恢复，一定会出现资源耗尽的情况

**Comment by s6341887** [comment]
昨天我看了一下源码，找了一会找到了这两个地方，动态启动了一个runner，线程池执行，而线程池是会吃掉异常的，所以可能是会继续读取binlog，但是发不进去的，丢失就丢失了

![image](https://user-images.githubusercontent.com/63495867/167762372-49466418-9377-4f7a-8c14-c4c1fdb6aa9b.png)

![image](https://user-images.githubusercontent.com/63495867/167762227-fa48e070-69dd-4f67-b75b-1f1c97ec1176.png)

**Comment by s6341887** [comment]
补充，考虑到offset的问题，可能出问题也不会有什么，毕竟偏移量不变

**Comment by agapple** [comment]
你要增加canal的监控，比如数据消费延迟

**Comment by s6341887** [comment]
> 你要增加canal的监控，比如数据消费延迟

监控这个之后会加，主要是这个是否影响，这个该怎么判断
