### ISSUE TITLE
canal解析库A，但当同实例下另一个库B删除了大量数据时，导致canal卡死

### ISSUE THREAD

**Issue by lilykyung** [alibaba/canal#417]
一个canal-server，一个instance，解析库A的变化，但是同实例下库B做了大量删除操作，导致canal解析库A卡死（可能不是卡死，日志一直显示正常，但是库A的变化一直解析不到，且日志中位点信息不再发生变化）

mysql版本：5.6
canal版本：1.0.16

ps：otter遇到过同样的问题，日志无异常，但是解析不到源库的数据

有没有人遇到过这个问题，该如何解决？

**Comment by agapple** [comment]
建议升级一下canal版本
