### ISSUE TITLE
canal-adapter报错: Not found primary key field in main table

### ISSUE THREAD

**Issue by Im-SAMW** [alibaba/canal#4170]
## Question

canal-adapter报错: Not found primary key field in main table

数据库表中有主键，esX/XXX.yml 中有配置 _id

**Comment by huangbule1989** [comment]
如何解决的？

**Comment by Im-SAMW** [comment]
> 如何解决的？

@huangbule1989 指定ES版本，然后直接下载的 Canal 有个jar包有问题，需要自行打包
