### ISSUE TITLE
配置中的kafka topic名称和在kafka 上自动创建的topic名称不一致

### ISSUE THREAD

**Issue by zuihaocanlan** [alibaba/canal#4176]
## Question

在1.1.4升级到1.1.5后，配置如下
canal.mq.dynamicTopic=canal_test_qa_test.selector_condition:test_qa_test\\.selector_condition
在kafka上创建的topic名称为canal_test_qa_test_selector_condition
“.”被解析成“_”了，这是1.1.5才改的吗

**Comment by agapple** [comment]
理解是对的
