### ISSUE TITLE
canal.adapter1.1.5同步mysql到es7中，报NullPointerException

### ISSUE THREAD

**Issue by qing9527** [alibaba/canal#4179]
deployer和adapter启动无报错，但是数据库新增一条测试数据后，adapter后台监控到数据变化，写入到ES中时报空指针。
配置文件看了几遍，找不到问题。

deployer启动无报错，adapter启动无报错。修改数据库记录有报错
![微信图片_20220520174718](https://user-images.githubusercontent.com/64877586/169502568-d95cb9d0-2df3-4480-9404-4310cc29f0cf.jpg)

这是相关配置文件
![微信图片_20220520175734](https://user-images.githubusercontent.com/64877586/169504344-2b2b3d2d-16af-4c42-93bb-a66460e2960f.jpg)
![微信图片_20220520175731](https://user-images.githubusercontent.com/64877586/169504386-63338da2-7854-4a64-8e95-737e57090c76.jpg)

**Comment by totoro52** [comment]
带上日志吧

**Comment by qing9527** [comment]
此问题已解决。修改adapter/conf/es7/yml配置文件中，sql:xxx as id(必须指明哪个列是主键)
