### ISSUE TITLE
编译报错，isHeartBeat这个变量找不到

### ISSUE THREAD

**Issue by yangpeng515** [alibaba/canal#418]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.2:compile (default-compile) on project canal.parse: Compilation failure: Compilation failure:
[ERROR] /Users/yes/Documents/workspace/idea/canal/parse/src/main/java/com/alibaba/otter/canal/parse/inbound/mysql/dbsync/LogEventConvert.java:[390,24] 找不到符号
[ERROR] 符号:   变量 isHeartBeat
[ERROR] 位置: 类 com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert
[ERROR] /Users/yes/Documents/workspace/idea/canal/parse/src/main/java/com/alibaba/otter/canal/parse/inbound/mysql/dbsync/LogEventConvert.java:[390,23] 非法的类型开始
[ERROR] -> [Help 1]

**Comment by developerworks** [comment]
同上, 

```
[INFO] -------------------------------------------------------------
[ERROR] /root/canal/parse/src/main/java/com/alibaba/otter/canal/parse/inbound/mysql/dbsync/LogEventConvert.java:[390,24] cannot find symbol
  symbol:   variable isHeartBeat
  location: class com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert
[ERROR] /root/canal/parse/src/main/java/com/alibaba/otter/canal/parse/inbound/mysql/dbsync/LogEventConvert.java:[390,23] illegal start of type
[INFO] 2 errors 

```

**Comment by erictanghu** [comment]
把最新那次的提交revert掉吧 应该是提交时漏掉了代码

**Comment by developerworks** [comment]
下面的命令可以解决编译的问题.

```
git reset --hard a3b9f6f1ebb21dd528effcceba2ac207f40b15e8
mvn clean install -Dmaven.test.skip -Denv=release
```

**Comment by agapple** [comment]
a9284b1b3967917ee6cef0e85787575e9b121e1e，已经修复
