### ISSUE TITLE
canal admin =》  Could not create connection to database server.

### ISSUE THREAD

**Issue by ChenghuaMi** [alibaba/canal#4201]
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2022-05-28 11:38:21.498 [main] ERROR org.springframework.boot.SpringApplication - Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'ebeanServer' defined in class path resource [com/alibaba/otter/canal/admin/config/EbeanConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.ebean.EbeanServer]: Factory method 'ebeanServer' threw exception; nested exception is javax.persistence.PersistenceException: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server.

server:
  port: 8089
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

spring.datasource:
  address: 192.168.0.216:3307
  database: canal_manager
  username: canal
  password: canal
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://${spring.datasource.address}/${spring.datasource.database}?useUnicode=true&characterEncoding=UTF-8&useSSL=false
  hikari:
    maximum-pool-size: 30
    minimum-idle: 1

canal:
  adminUser: admin
  adminPasswd: admin

数据库是用 docker 部署
         33060/tcp, 0.0.0.0:3307->3306/tcp                      mysql_master

**Comment by agapple** [comment]
Could not create connection to database server.

看上去是连不上数据库啊
