### ISSUE TITLE
1.1.6版本 没有了com.alibaba.otter.canal.protocol 这个包

### ISSUE THREAD

**Issue by zhaoyy0513** [alibaba/canal#4204]
换成新的1.1.6版本后，之前用的Message、CanalEntry这些类所在的 com.alibaba.otter.canal.protocol提示不存在，请求从哪里能看到修改呢
![image](https://user-images.githubusercontent.com/33887920/171114606-d542b633-f75d-4036-8df2-c405c72d26fc.png)
![image](https://user-images.githubusercontent.com/33887920/171114668-10218c1a-d1be-4a68-8bf6-387329d01b93.png)

**Comment by z1324090221** [comment]
我的也没有了！！！！
