### ISSUE TITLE
一个canal下destinations多个instance监听同一个库的问题

### ISSUE THREAD

**Issue by loveluckystar** [alibaba/canal#421]
一个canal下destinations写了2个instance，监听的库一样。我发现库里面的数据变更后，我的client会接收到两条一模一样的变更，这是怎么回事？有人遇到过吗？

**Comment by agapple** [comment]
一个instance一份数据

**Comment by mjjian0** [comment]
你说的 一份数据，是指一个数据库吗，一个instance对应一个数据库？

**Comment by mjjian0** [comment]
@loveluckystar 我也是写了三个instance对应一个库，然后通过filter过滤就不会有重复的数据，不过总是会有一个instance 的client 取不到变更数据。batchId为-1，size为0
