### ISSUE TITLE
canal 1.1.6 拉取 rds oss下载失败

### ISSUE THREAD

**Issue by zhuzejun123** [alibaba/canal#4210]
![image](https://user-images.githubusercontent.com/20276075/171613609-7c5d3271-54d0-4eda-8717-cd6de19573d6.png)

**Comment by agapple** [comment]
![image](https://user-images.githubusercontent.com/834743/173267963-8e9681b2-8282-4a53-88f5-3a6ce6d6b0d3.png)


rds oss binlog里没有符合条件的binlog文件
