### ISSUE TITLE
canal-admin与canal-server的问题

### ISSUE THREAD

**Issue by luckytanjunxin** [alibaba/canal#4213]
1、canal-admin与canal-server正常开启并正常通信，在admin里面设置好server的配置后可以关闭admin吗？因为服务器资源不够
2、canal-server有canal.properties和instance.properties两个配置文件，那如果canal-server在docker里面运行，那这两个配置文件里面的配置是不是都可以在dcoker的环境变量参数里面设置？

**Comment by s6341887** [comment]
您好，server启动后关闭admin，我没有尝试过是否会有影响，但关于server的配置使用变量设置，这一点我做过尝试，是可行的，不过我采用的是单instance变量，没有设置多个instance，多个instance的话，理论上可行，这一点我也十分有兴趣，之后我可以进行尝试，有任何结果我会再来评论

如果这期间您有任何结果，还望您不吝告知，谢谢

**Comment by agapple** [comment]
1.  可以关闭canal-admin，配置加载一次
2. 变量支持env设置
