### ISSUE TITLE
Why do u use Disruptor

### ISSUE THREAD

**Issue by HelloTo4x** [alibaba/canal#4214]
Hi, i am reading your project, i know you are using Disruptor, why do you choose it for middleware ? can u tell me what is Pros and Cons of Disruptor in the real world and your project ? Thank u

**Comment by s6341887** [comment]
嗨，您好，我看您地区来自中国，我就用中文回复您，我并非canal的开发者，看到您的提问，我对此也有兴趣，冒昧回复您的提问，表达我的理解，希望和您共同进步

关于Disruptor，它是一个高性能的内存队列，是一个有界队列，以环形数组实现，以我对它的认知，认为它有以下优点：

1、采用了数组，不用链表，避免了GC，并且由于CPU的区域加载机制，数组更节省资源
2、数组的长度是可以被2整除的，意味着可以进行位运算
3、采用了无锁设计，可以提升性能
4、采用缓存行填充，避免了伪共享
5、基于事件和驱动的生产消费模型

当然，它因为是有界的，所以一定会出现写入过快，发生数据覆盖的情况， 但是针对这一点，Disruptor也有一些自己的策略，这个您可以研究一下

总之，Disruptor其实在金融领域用的比较多，常规的场景，一般我们普通的内存队列就可以满足要求，看您的使用场景

**Comment by HelloTo4x** [comment]
thank u
