### ISSUE TITLE
本地文件覆盖了canal-admin的配置

### ISSUE THREAD

**Issue by luodadaRyan** [alibaba/canal#4215]
在使用了集群模式之后，读取的properties文件是 canal.properties, 这里面官方包带了很多配置。
我们想要的结果是canal-admin的集群配置覆盖本地文件，实现动态加载。

不太理解源码这里是为什么要本地覆盖远程？(com.alibaba.otter.canal.deployer.CanalLauncher#main)
```java
Properties managerProperties = canalConfig.getProperties();
// merge local
managerProperties.putAll(properties);
```

**Comment by Aresxue** [comment]
感觉上像个bug，这边把docker镜像中的canal.properties中的相关配置的key删除掉了，这样就能够使用admin中的配置，否则本地的空配置会覆盖掉远程配置导致集群不可用。

**Comment by agapple** [comment]
当时允许基于本地客户端的自定义一些配置，所以本地覆盖远程的配置，属于设计考虑
