### ISSUE TITLE
兼容PolarDB-X的show databases返回

### ISSUE THREAD

**Issue by agapple** [alibaba/canal#4216]
- [ ] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment

* canal version
* mysql version

### Issue Description

PolarDB-X show databases返回结果会有多列
![image](https://user-images.githubusercontent.com/834743/172985395-ee01ad6c-3fcb-43e4-9f68-324855379f7e.png)

需要兼容下正确获取database的情况

### Actual behaviour

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by lmzml** [comment]
这个BUG的修复，引发了另一个BUG的产生，现在无法配置监控全部的库，或者某个库下的所有表，启动实例时会引发异常
![微信截图_20220629144709](https://user-images.githubusercontent.com/97717237/176861577-0fda2626-0fb8-47ac-88f0-775b6f85f974.png)

**Comment by agapple** [comment]
https://github.com/alibaba/canal/pull/4217，已修复
