### ISSUE TITLE
 canal admin本地启动单机版，instance状态是【停止】，且始终无法开启

### ISSUE THREAD

**Issue by sherlock-art** [alibaba/canal#4222]
## Question

<img width="1195" alt="image" src="https://user-images.githubusercontent.com/66151680/173213206-66d345b7-d75a-41a5-be80-80bfb6da0f7e.png">
看源码好像是这两个必须匹配状态才会设置成1，请问这里的example是哪里来的
<img width="1187" alt="image" src="https://user-images.githubusercontent.com/66151680/173213263-ac5854dc-b077-4c93-9b20-d74a660c206a.png">
我把配置文件和数据库里的所有example都干掉了，这里还能查到

        SimpleAdminConnector connector = new SimpleAdminConnector("127.0.0.1", 11110, "admin", "admin");
        connector.connect();
不知道这两行是怎么查到的example呢，我该怎么让我的instance启动成功呢？

**Comment by GitHub-JXJ** [comment]
找到解决办法了嘛，同问
