### ISSUE TITLE
本地idea启动，一直报错 Could not initialize class com.sun.org.apache.xml.internal.serializer.Encodings  

### ISSUE THREAD

**Issue by poo0054** [alibaba/canal#4230]
## Question

Could not initialize class com.sun.org.apache.xml.internal.serializer.Encodings

jdk版本 jdk1.8.0_331  
然后maven一刷新 就会Could not initialize class com.sun.org.apache.xml.internal.serializer.Encodings
父级 'com.alibaba.otter:canal.admin:1.1.5-SNAPSHOT' 有问题

![image](https://user-images.githubusercontent.com/85894494/173773607-ebb5c440-d060-4228-9eb7-604d75fed7f5.png)

**Comment by poo0054** [comment]
现在main分支的jdk版本是需要11的嘛

**Comment by whhe** [comment]
应该是 idea 的 bug，回退到 2021.3.3 是没问题的。

**Comment by poo0054** [comment]
谢谢  已解决  用的idea 2022.1.3版本不行 现在已经降会2021.1.3了

**Comment by whhe** [comment]
找到一个解决办法，亲测 2022.2 也可以正常使用了 

https://youtrack.jetbrains.com/issue/IDEA-290474/Unable-to-import-Maven-project-javalangUnsupportedClassVersionError-comintellijlangpropertiescharsetNative2AsciiCharsetProvider#focus=Comments-27-5872553.0-0

**Comment by userName970910** [comment]
@whhe 这个解决方法没看懂啊，怎么解决

**Comment by fengjx** [comment]
me too
