### ISSUE TITLE
canal 成功启动但是不推送消息，第一次启动不会生成mate.dat 第二次启动生成mate.dat为空

### ISSUE THREAD

**Issue by 985177520** [alibaba/canal#4232]
## Question

![image](https://user-images.githubusercontent.com/43394661/173882452-2d828918-04bb-49b6-94e1-7a66cafce9e8.png)
![image](https://user-images.githubusercontent.com/43394661/173883082-7e131861-5613-41a6-8066-b3458e6c9b58.png)

日志显示启动成功

**Comment by iprotn** [comment]
### **我的是1.1.6同步mysql到rabbitMQ，但是MQ始终无法收到mysql变动消息，你的解决了吗**

**Comment by 985177520** [comment]
> ## Question
> ![image](https://user-images.githubusercontent.com/43394661/173882452-2d828918-04bb-49b6-94e1-7a66cafce9e8.png) ![image](https://user-images.githubusercontent.com/43394661/173883082-7e131861-5613-41a6-8066-b3458e6c9b58.png)
> 
> 日志显示启动成功
