### ISSUE TITLE
canal1.1.6同步mysql8.0.27到RabbitMQ，MQ一直无法收到消息

### ISSUE THREAD

**Issue by iprotn** [alibaba/canal#4237]
## Question

**canal1.1.6同步mysql8.0.27到RabbitMQ，MQ一直无法收到消息，看了网上很多配置，大多都差不多，跟着配置了，但是RabbitMQ始终收不到mysql变动消息推送，有什么好的解决办法或者比较完整的文章推荐吗**

**Comment by yreezy** [comment]
看下是不是报错了 mq的话
rdb的yml和launcher的yml的destination都需要配置成mq queue的

**Comment by iprotn** [comment]
> 看下是不是报错了 mq的话 rdb的yml和launcher的yml的destination都需要配置成mq queue的

需要有zookeeper环境吗，看QuickStart文档中还需要提供zk环境
