### ISSUE TITLE
用zookeeper对canal做高可用的时候，canal.instance.tsdb.dir 这个目录需要设置成共享磁盘让两个canal同时可以访问到吗？

### ISSUE THREAD

**Issue by otjoy** [alibaba/canal#4247]
看tsdb 的wiki，有个地方不是很理解：“基于磁盘的模式，可以结合存储计算分离的技术，canal failover之后只要在另一个计算节点上拉起，并加载云盘上的DB数据，做到多机冷备” 。正常情况下，只有一个canal提供服务，要是发生了failover，切到了另外一个canal上，刚刚的ddl怎么同步过去呢？看这句话的意思是要canal.instance.tsdb.dir 设置成共享磁盘目录吗？
https://github.com/alibaba/canal/wiki/TableMetaTSDB

**Comment by agapple** [comment]
tsdb可以选择一个远程的mysql
