### ISSUE TITLE
怎么maven构建client-adapter源码打成二进制包？

### ISSUE THREAD

**Issue by marker-wu** [alibaba/canal#4248]
请问各位大佬，怎么maven构建client-adapter源码打成二进制包？

**Comment by whhe** [comment]
```
./mvnw clean package -DskipTests=true -Prelease 
```

**Comment by marker-wu** [comment]
> ```
> ./mvnw clean package -DskipTests=true -Prelease 
> ```

貌似不行呀，执行后tagert目录结构跟官网下载的adapter结构不一样

**Comment by marker-wu** [comment]
> ```
> ./mvnw clean package -DskipTests=true -Prelease 
> ```

亲测有效，感谢
