### ISSUE TITLE
canal instance 报错 Table  base table doesn't exist (版本v 1.1.6)

### ISSUE THREAD

**Issue by zxxb24ever** [alibaba/canal#4263]
## 报错如下
![微信图片_20220628112858](https://user-images.githubusercontent.com/66420164/176085949-4aa8233d-e75e-4f4c-9af0-3ab397b925d5.png)

## instance 过滤规则如下
![微信图片_20220628113046sadasda](https://user-images.githubusercontent.com/66420164/176086407-99c23dff-1b7e-49c7-b9aa-a62a55009445.png)

## 问题解决
最后手动建了一张base table表才行 怎么会这样

**Comment by zxxb24ever** [comment]
好像要在黑名单把BASE TABLE过滤掉

**Comment by yreezy** [comment]
hi 
可以参考下
#4261 黑名单加过滤 猜想是equalsIgnoreCase的判断未生效 对于BASE TABLE
这个是一样的问题

**Comment by yreezy** [comment]
#4245 这个你也可以参考下 实际上是deployer包的问题

**Comment by itgcl** [comment]
换成1.1.4版本

**Comment by del-xiong** [comment]
[v1.1.6] Last pushed 16 days ago by [canal](https://hub.docker.com/u/canal)
因为他们2周前提交了个bug版本，换1.1.5即可

**Comment by AaronZhangL** [comment]
应该过滤掉所有SCHEMA名称下的BASE TABLE表名，修改文件[/home/admin/canal-server/conf/{your-db-schema-name}/instance.properties]中的下面设置：

canal.instance.filter.black.regex=.*\\.BASE TABLE.*

下面的写法只会过滤掉特定SCHEMA, new_energy的BASE TABLE表

canal.instance.filter.black.regex=new_energy\\.BASE.*

**Comment by agapple** [comment]
1.1.6-hotifx版本已修复
