### ISSUE TITLE
设置canal.instance.filter.regex不生效

### ISSUE THREAD

**Issue by zhilaohu32** [alibaba/canal#4265]
数据库binlog_rows_query_log_events=ON，设置canal.instance.filter.regex不生效；仍然会获取到非指定的库表相关binlog信息。将binlog_rows_query_log_events=OFF时，似乎看起来能够成功过滤（至少未出现指定之外的库表操作日志）。

**Comment by cyhbyw** [comment]
> 数据库binlog_rows_query_log_events=ON，设置canal.instance.filter.regex不生效；仍然会获取到非指定的库表相关binlog信息。将binlog_rows_query_log_events=OFF时，似乎看起来能够成功过滤（至少未出现指定之外的库表操作日志）。

**canal.instance.filter.query.dml = true**
我也遇到相同的问题，然后将上面这一行配置从 false 改为 true 就可以了，试试吧
