### ISSUE TITLE
首页readme.md里面的 canal的工作原理 图片没有显示完整

### ISSUE THREAD

**Issue by rainx** [alibaba/canal#427]

**Comment by agapple** [comment]
估计你需要翻墙看吧

**Comment by rainx** [comment]
like this ：

![图片](http://ww4.sinaimg.cn/large/0060lm7Tly1fm5mvsvfizj31kw0xt459.jpg)

**Comment by rainx** [comment]
@agapple

**Comment by agapple** [comment]
http://dl.iteye.com/upload/attachment/0080/3107/c87b67ba-394c-3086-9577-9db05be04c95.jpg，图片源地址
