### ISSUE TITLE
canal启动成功之后，kafka中无任何数据

### ISSUE THREAD

**Issue by 2hang5ong** [alibaba/canal#4271]
能启动成功，并且日志能看到已经找到了mysql binlog日志，但是kafka中无任何数据，而且，我故意把kafka的连接地址写错，日志也不会报kafka连接不上的错误，导致我没办法判断是我哪里出问题了，有人遇到过相同的问题么
instance.properties配置如下：
![image](https://user-images.githubusercontent.com/38459361/176653372-49aceb03-9008-4ca1-8648-d214e6282d13.png)

![image](https://user-images.githubusercontent.com/38459361/176653514-53c9c907-2a3a-4d5f-b597-b507d190b416.png)

用的1.1.5 SNAPSHOT 版本的

**Comment by chuangtianya** [comment]
请问解决了么，1.1.6遇到了同样的问题

**Comment by 2hang5ong** [comment]
解决了，我是因为在canal.properties的canal.serverMode = kafka（1.5以下的版本默认是tcp，应该改成kafka） 这个值没改过来。注意，这个值在配置文件是有的，直接改就行，如果写了两次，后面的会覆盖前面的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/canal"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月3日(星期天) 晚上6:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/canal] canal启动成功之后，kafka中无任何数据 (Issue #4271)





 
请问解决了么，1.1.6遇到了同样的问题

**Comment by chuangtianya** [comment]
> 解决了，我是因为在canal.properties的canal.serverMode = kafka（1.5以下的版本默认是tcp，应该改成kafka） 这个值没改过来。注意，这个值在配置文件是有的，直接改就行，如果写了两次，后面的会覆盖前面的
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "alibaba/canal" ***@***.***&gt;; 发送时间:&nbsp;2022年7月3日(星期天) 晚上6:19 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [alibaba/canal] canal启动成功之后，kafka中无任何数据 (Issue #4271) 请问解决了么，1.1.6遇到了同样的问题 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

感恩，确认了下我的配置就是kafka，测试了下跟这个问题是一样的
https://github.com/alibaba/canal/issues/4251
