### ISSUE TITLE
client-adpater针对跨库join场景的fix引发新的bug

### ISSUE THREAD

**Issue by yourse007** [alibaba/canal#4273]
- [ ] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment

* canal 1.1.6
* mysql 5.7

### Issue Description
[client-adpater针对跨库join的场景修复的bug](https://github.com/alibaba/canal/pull/4161/commits/1617f42cb3229f0d05ee30bda944d89a70266213)
这个fix逻辑有问题，会导致将destination + groupId + schema拼接在一起，然后才判断是否为null

### Steps to reproduce
```
+ (tableItem.getSchema() == null ? schema : tableItem.getSchema())
```

### Actual behaviour

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by agapple** [comment]
可以考虑提交一个PR给我
