### ISSUE TITLE
修复#4216这个BUG的同时，引发了另一个BUG的产生，现在无法配置监控全部的库，或者某个库下的所有表，启动实例时会引发异常

### ISSUE THREAD

**Issue by lmzml** [alibaba/canal#4274]
![微信截图_20220629144709](https://user-images.githubusercontent.com/97717237/176861992-a1650864-0a95-4b7d-870d-75338e0f7f65.png)

**Comment by lmzml** [comment]
![image](https://user-images.githubusercontent.com/97717237/176864852-606f970b-f229-4c83-a19c-df1090b6ae20.png)

**Comment by agapple** [comment]
1.1.6-hotfix已经做过修复
