### ISSUE TITLE
dump address /192.168.0.113:3306 has an error, retrying. caused by 

### ISSUE THREAD

**Issue by kingsKangKang** [alibaba/canal#4281]
一直报这个错误，下面是我的配置
MySQL8，canal.deployer1.1.6，本地环境，mysql用户名密码都可用并且也开启了bin-log模式
报错信息
![image](https://user-images.githubusercontent.com/44571572/177320369-59064ed3-203c-47af-987f-cf06b7e872df.png)
配置信息
![image](https://user-images.githubusercontent.com/44571572/177320282-d649e31e-fe05-4e98-be80-6ca489cc57e4.png)

**Comment by 15986901041** [comment]
我也是报了这个错，之前运行得好好的，今天启动就报这个

**Comment by lmzml** [comment]
![image](https://user-images.githubusercontent.com/97717237/177948551-5dffe00c-06e5-48b6-b0d0-accf4c7c9baa.png)
白名单不要配置监控全部库下的全部表，或者某个库下的全部表，应该就正常了，或者在黑名单配置中配置上 BASE TABLE，应该也能解决

**Comment by AaronZhangL** [comment]
应该过滤掉所有SCHEMA名称下的BASE TABLE表名，修改文件[/home/admin/canal-server/conf/{your-db-schema-name}/instance.properties]中的下面设置：

canal.instance.filter.black.regex=.*\\.BASE TABLE.*

下面的写法只会过滤掉特定SCHEMA, new_energy的BASE TABLE表

canal.instance.filter.black.regex=new_energy\\.BASE.*

**Comment by agapple** [comment]
1.1.6-hotfix已经做过修复
