### ISSUE TITLE
Parent 'com.alibaba.otter:canal:1.1.7-SNAPSHOT' has problems

### ISSUE THREAD

**Issue by liangliangoo** [alibaba/canal#4289]
mvn clean install 后，刷新项目还是找不到canal:1.1.7-SNAPSHOT

**Comment by liangliangoo** [comment]
<img width="622" alt="image" src="https://user-images.githubusercontent.com/65400457/178088920-cd0b2057-5830-4ea0-a15f-bb3e92c7c3bf.png">

**Comment by liangliangoo** [comment]
在MAC下不行，我又在windows环境下试了一下，是正常的，这是为什么呢？

**Comment by githubzzc** [comment]
最新的版本才1.1.6，你从哪里搞到1.1.7的？

**Comment by liangliangoo** [comment]
master分支

**Comment by liangliangoo** [comment]
> 最新的版本才1.1.6，你从哪里搞到1.1.7的？

master分支

**Comment by agapple** [comment]
这个和源码没关系，我这里mac+idea是正常的

**Comment by qiansj** [comment]
> <img alt="image" width="622" src="https://user-images.githubusercontent.com/65400457/178088920-cd0b2057-5830-4ea0-a15f-bb3e92c7c3bf.png">

试试 jdk 8+
