### ISSUE TITLE
能从canal能直接得到binlog的sql吗？

### ISSUE THREAD

**Issue by bayannur** [alibaba/canal#429]
example中的例子，打印的是类似以下的形似，canal能给出执行insert，update，delete，create table等命令的具体sql语句吗？delete from sharddb. tab_shard where id =5;

 BEGIN ----> Thread id: 18
----------------> binlog[mysql-bin.000005:1200] , name[sharddb,tab_shard] , eventType : DELETE , executeTime : 1512015314000 , delay : 709ms
id : 5    type=int(10) unsigned
randomstr : 14504    type=varchar(100)
create_time : 2017-11-28 05:00:35    type=timestamp
----------------
 END ----> transaction id: 20565
================> binlog[mysql-bin.000005:1251] , executeTime : 1512015314000 , delay : 709ms

**Comment by agapple** [comment]
binlog格式可以网上先了解一下
