### ISSUE TITLE
canal返回的信息CanalEntry.Entry里是否有字段能作为这个数据的版本信息

### ISSUE THREAD

**Issue by Yuanxiangz** [alibaba/canal#4292]
## Question

我们使用canal订阅数据库变更信息，但是有的表并没有version字段表明数据的版本，CanalEntry.Entry是否有字段能替代数据的版本信息？我们想通过版本区分数据是否表更以及数据的新旧。
考虑每次变更才会有binlog的数据产生，比如某条binlog数据的生成时间就可以作为version的替代。但我看了下CanalEntry.Entry中的字段似乎没有找到类似的
我注意到CanalEntry.Entry.header里有如下属性，不知道通过logfineName+logfileOffset是否能作为version的替代？logfileName后面的000004是否总是递增的？因为也要通过version判断数据的新老版本。

version: 1
logfileName: "mysql-bin.000004"
logfileOffset: 1101
serverId: 1
serverenCode: "UTF-8"
executeTime: 1657630809000
sourceType: MYSQL
schemaName: "houyiregiondb"
tableName: "vm"
eventLength: 115
eventType: UPDATE
props {
  key: "rowsCount"
  value: "1"
}

**Comment by duxinglangzi** [comment]
logfileName: "mysql-bin.000004"    里面 mysql-bin.000004 表示mysql数据库binlog文件。  后面的  000004 是递增的。

**Comment by agapple** [comment]
LS正解
