### ISSUE TITLE
CanalEntry.RowChange.parseFrom(entry.getStoreValue())  对数据行中null值的处理问题

### ISSUE THREAD

**Issue by whiletrue2009** [alibaba/canal#4293]
### 现象
我尝试下面的代码
```
CanalEntry.RowChange rowChange = CanalEntry.RowChange.parseFrom(entry.getStoreValue());
```
对于insert语句，如果数据行中有一列为int，值是null， parse 之后，得到的rowChange  中，对于的CanalEntry.Column 实例里面，value不是预期的null，而是""

![image](https://user-images.githubusercontent.com/7763579/178542284-08786817-7ae7-40d2-9402-4c5791bef61c.png)

### 分析
查看源码有下面的内容：
![image](https://user-images.githubusercontent.com/7763579/178541299-0f23c262-8780-4661-9a22-907dee9abfd0.png)

### 求助
是否不太合适？我有什么办法获得null而不是空字符串吗？

**Comment by agapple** [comment]
有一个isNull方法来判断
