### ISSUE TITLE
cannal客户端阻塞

### ISSUE THREAD

**Issue by niezl** [alibaba/canal#430]
客户端在获取Message时阻塞，阻塞以后无法获取数据，设置超时时间也不管用，在重启以后才可以获取数据。
Message message = connector.getWithoutAck(batchSize)

**Comment by shuhaoc** [comment]
可能是遇到大事务，canal的buffer size不够

**Comment by JoyJava** [comment]
这么解决的？

**Comment by agapple** [comment]
估计还是tcp链接被mysql主动断开，canal server未感知的问题

**Comment by JoyJava** [comment]
设置超时就可以了。
