### ISSUE TITLE
canal server初始化表结构有BUG，报 Table 'XXX.base table' doesn't exist

### ISSUE THREAD

**Issue by zswiori** [alibaba/canal#4304]
DatabaseTableMeta类第209行开始

        for (String schema : schemas) {
                // filter views
                packet = connection.query("show full tables from `" + schema + "` where Table_type = 'BASE TABLE'");
                int tableNameColumnIndex = 0; // default index is 0
                List<String> tables = new ArrayList<>();
                for (int line = 0; line < packet.getFieldValues().size() / columnSize; line++) {
                    String table = packet.getFieldValues().get(line * columnSize + tableNameColumnIndex);
                    String fullName = schema + "." + table;
                    if (blackFilter == null || !blackFilter.filter(fullName)) {
                        if (filter == null || filter.filter(fullName)) {
                            tables.add(table);
                        }
                    }
                }

                if (tables.isEmpty()) {
                    continue;
                }

                StringBuilder sql = new StringBuilder();
                for (String table : tables) {
                    sql.append("show create table `" + schema + "`.`" + table + "`;");
                }

                List<ResultSetPacket> packets = connection.queryMulti(sql.toString());
                for (ResultSetPacket onePacket : packets) {
                    if (onePacket.getFieldValues().size() > 1) {
                        String oneTableCreateSql = onePacket.getFieldValues().get(1);
                        memoryTableMeta.apply(INIT_POSITION, schema, oneTableCreateSql, null);
                    }
                }
            }

这个地方看着是要支持polardb-x的show table，但是会导致mysql出问题，把TABLE_TYPE的值“BASE TABLE”当成表名加到tables集合中，导致后面执行desc BASE TABLE直接报错。
看这段代码的意思应该是想在第二个for循环之前定义一个tableNameColumnIndex，然后想在for循环面对它做计算重新赋值，依此来跳过BASE TABLE，但是不知道作者是不是忘了，后面啥也没对它做，导致每张表后面都会跟着加进去一个BASE TABLE表。

**Comment by lmzml** [comment]
关于这个bug，已经有很多问题单了，貌似都没人维护了

**Comment by armyhcz** [comment]
不会是裁员把这个项目放弃了吧

**Comment by tangxutao** [comment]
已经有人解决了  修改配置文件 目前正常
canal.instance.filter.black.regex=.*\\.BASE.*

**Comment by AaronZhangL** [comment]
对于自建 MySQL , 需要先开启 Binlog 写入功能，配置 binlog-format 为 ROW 模式，my.cnf 中配置如下

[mysqld]
log-bin=mysql-bin # 开启 binlog
binlog-format=ROW # 选择 ROW 模式
server_id=1 # 配置 MySQL replaction 需要定义，不要和 canal 的 slaveId 重复

**Comment by agapple** [comment]
canal-1.1.6 hotfix版本已经修复
