### ISSUE TITLE
canal中监听h2.mv.db无限增大。

### ISSUE THREAD

**Issue by houziyu** [alibaba/canal#4306]
一开始使用canal进行binlog的订阅，后发现h2.mv.db文件越来越大。经过查看此文件发现有大量CREATE DATABASE IF NOT EXISTS `test`语句。经过排查以及阿里云工单沟通是由于DTS同步服务中会进行创建心跳库和表的。所导致的。
目前解决方法是让存储到mysql中不使用h2数据库。然后定期清理此库数据，但是不太好。想问一下从canal方面有什么方法可以屏蔽create语句吗？感谢。

**Comment by agapple** [comment]
可以忽略掉test库的订阅
