### ISSUE TITLE
BinlogDownloadQueue下载binlog文件时响应头没有Content-Length导致报错

### ISSUE THREAD

**Issue by shiyup** [alibaba/canal#4307]
## Question

canal版本：1.1.5
mysql版本：RDS MySQL 8.0
![image](https://user-images.githubusercontent.com/32081217/180115287-9842a019-7e3b-491d-b4c8-98f47227e3be.png)
下载文件时返回的响应头是Transfer-Encoding: chunked时，由于没有取到Content-Length导致了NPE

**Comment by agapple** [comment]
可以考虑提交一个PR给我
