### ISSUE TITLE
connector.getWithoutAck方法的batchSize不起作用

### ISSUE THREAD

**Issue by shuhaoc** [alibaba/canal#431]
使用过程中发现，无论batchSize传多少，起作用的是canal.properties里配置的buffer size而非方法入参batchSize。

**Comment by agapple** [comment]
bufferSize是一个当前内存里的最大记录值，你是不是设置太小了？batchSize > bufferSize

**Comment by shuhaoc** [comment]
@agapple 感谢回复！

我试了发现，batchSize是作用的，实际起作用的getWithoutAck batchSize * memunit。

比如

canal.instance.memory.buffer.size=16384
canal.instance.memory.buffer.memunit = 1024
canal.instance.memory.batch.mode = MEMSIZE

此时内存中的ring buffer大小应为16384 * 1024 B

如果客户端代码中getWithoutAck传2，那么每次批量获取的binlog数据量是不超过或略微超过2 * 1024 B，受server配置中的canal.instance.memory.buffer.memunit和canal.instance.memory.batch.mode配置影响。

我理解的对不对？

**Comment by agapple** [comment]
是的，理解正确
