### ISSUE TITLE
使用maven构建example工程，出现依赖问题 snapshot构建失败

### ISSUE THREAD

**Issue by n15902179169** [alibaba/canal#4311]
## Question

[ERROR] Failed to execute goal on project canal.example: Could not resolve dependencies for project com.alibaba.otter:canal.example:jar:1.1.7-SNAPSHOT: com.alibaba.otter:canal.client:jar:1.1.7-SNAPSHOT was not found in https://oss.sonatype.org/content/repositories/snapshots during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of sonatype has elapsed or updates are forced -> [Help 1]

**Comment by n15902179169** [comment]
进入https://oss.sonatype.org/content/repositories/snapshots ，显示Directory listing forbidden

**Comment by n15902179169** [comment]
https://github.com/alibaba/canal/wiki/ClientExample中的构建命令
mvn exec:java -Dexec.mainClass="com.alibaba.otter.canal.example.SimpleCanalClientTest"

**Comment by agapple** [comment]
mvn clean install exec:java -Dexec.mainClass="com.alibaba.otter.canal.example.SimpleCanalClientTest"
