### ISSUE TITLE
meta.dat  节点被清空

### ISSUE THREAD

**Issue by noaso** [alibaba/canal#4312]
## Question

adapter stop后 meta.dat里的内容被清空了

看log是触发了 FileMixedMetaManager.unsubscribe  ，super.unsubscribe 会删除节点。
<img width="777" alt="image" src="https://user-images.githubusercontent.com/1321164/180601954-921eda72-1489-4870-a6dc-51f06cf7393c.png">

1.如果单纯adapter重启 可以看到会接着last cursor position继续执行, meta.dat会被继续更新。

2.如果先adapter stop，再deployer stop 那meta.dat里adapter的节点信息就丢了

**Comment by agapple** [comment]
可以考虑提交一个PR给我
