### ISSUE TITLE
connector，adapter BIT长度大于1的情况类型转换错误

### ISSUE THREAD

**Issue by xesygao** [alibaba/canal#4319]
- [x] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment

* canal version 1.1.6
* mysql version 5.7.0

### Issue Description
canal同步没有考虑BIT长度大于1的情况，在connector，adapter中，BIT(>1) value被转成String,但是都被当成BOOLEN或TINYINT处理了
ERROR com.alibaba.otter.canal.connector.core.util.JdbcTypeUtil - table: xxx column: yyy, failed convert type 240 to -7
![image](https://user-images.githubusercontent.com/17232694/181145078-b83bf228-6751-42dc-9d0c-7ed356689ef4.png)

### Actual behaviour

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by agapple** [comment]
可以考虑提交一个PR给我
