### ISSUE TITLE
直接加入把db event push到kafka，最方便的做法改动哪块比较好？

### ISSUE THREAD

**Issue by liutaihua** [alibaba/canal#432]
把canal当databus用。目前是写个简易的canalClient，连接canal server指定的Destination, 但是这样client存在单点风险。  
想直接把发送kafka消息集中到canal内，利用已有的zk 热备的模式，避免单点.   

cannal源码从哪块做改动，插入这个功能比较好？

**Comment by wingerx** [comment]
canal 的client也可以是HA的

**Comment by liutaihua** [comment]
@wingerx 谢谢，那我去看下client代码去了。这样最好了。
