### ISSUE TITLE
1.1.6服务端启动之后，Java客户端连接但是 Connection refused

### ISSUE THREAD

**Issue by z1324090221** [alibaba/canal#4320]
## Question

Telnet 11111端口也不通，太奇怪了，明明防火墙都直接关闭了

**Comment by rocky-peng** [comment]
1. 检查canal绑的ip是不是和你telnet的ip一致
2. 如果一致，应该是canal没有启动成功

**Comment by liuyunxiah** [comment]
canal.serverMode = tcp
