### ISSUE TITLE
canal支持mysql字段里面的blob字段吗？获取到的是乱码

### ISSUE THREAD

**Issue by ab8846254** [alibaba/canal#4321]
canal支持mysql字段里面的blob字段吗？获取到的是乱码canal支持mysql字段里面的blob字段吗？获取到的是乱码canal支持mysql字段里面的blob字段吗？获取到的是乱码

**Comment by rocky-peng** [comment]
这个不是问题吧，既然都是blob了，数据库存的就是二进制，你读出来还原成本身的格式就行。我实验过没问题

**Comment by ab8846254** [comment]
> 这个不是问题吧，既然都是blob了，数据库存的就是二进制，你读出来还原成本身的格式就行。我实验过没问题

canal读取到的是一堆乱码，数据库blob字段存储的是文件或者图片，老哥加个联系方式？探讨下可以吗？

**Comment by rocky-peng** [comment]
你要把二进制还原成原本的文件，你直接打印二进制，当然乱码了
