### ISSUE TITLE
adapter同步简单sql数据到es报空指针的问题，头疼！！！求大佬赐教！！！

### ISSUE THREAD

**Issue by 1512033796** [alibaba/canal#4323]
## Question
mysql：8.0.29
es：7.17.3
adapter：1.1.6

我运行了adapter，想要将数据从mysql同步到es，adapter日志中有输出数据，但是同步到es报空指针！

报错信息如下：
![image](https://user-images.githubusercontent.com/45383053/181402037-9f51cf6f-a4aa-41b8-a4b7-170f5aac339d.png)

adapter的application.yum配置如下：
![image](https://user-images.githubusercontent.com/45383053/181401139-5870f6d6-e688-485b-b099-7619f7e009c6.png)

es7/aaa.yum配置文件如下：
![image](https://user-images.githubusercontent.com/45383053/181402424-0752518b-b3f7-4f0d-9602-7e20e8c25732.png)

表结构如下：
![image](https://user-images.githubusercontent.com/45383053/181401805-cffe0981-2f48-4cdc-b7e2-7148875687ab.png)

有大佬知道什么问题嘛？我看其他帖子有说是别名的问题，我这个sql都已经排除这些了，而且用的还是最基本的sql，不知道哪里有问题！！！

**Comment by smile-wind** [comment]
ES 索引建好了吗?

**Comment by 1512033796** [comment]
> ES 索引建好了吗?

是建好的，

**Comment by Qxx-799** [comment]
把 etlCondition:  "where c.id > {}" 加上试试

**Comment by 1512033796** [comment]
> 把 etlCondition: "where c.id > {}" 加上试试
也是一样的

**Comment by 1512033796** [comment]
解决了，兄弟们，是索引没有建好，原先的索引是直接在es_head里面建立的，相当于只建了一个名字，并没有建立字段。实际上建立索引需要调用新增索引的接口，并且将字段写上。且字段要和配置文件里面的sql的字段对应

**Comment by Axin-cool** [comment]
> 

是建立索引mapping吗
