### ISSUE TITLE
sql语句trace打印内容前置

### ISSUE THREAD

**Issue by liqi444** [alibaba/canal#4324]
adapter使用rdb mirror进行整库备份时会出现各种sql异常，异常语句本身在源数据库中可执行。
开启trace日志后发现异常日志前没有执行sql日志打印
查看代码com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService发现sql日志打印在异常catch后面，异常场景无法打印日志
当需要查看sql进行问题排查时，由于sql日志打印代码在异常后面，导致无法看到异常的sql语句

将sql日志打印前置或在finally中执行

**Comment by agapple** [comment]
你可以在异常时，额外在异常输出里打印下sql日志，可以考虑提交一个PR给我
