### ISSUE TITLE
canal 1.1.6 jdk1.8.0_301启动失败

### ISSUE THREAD

**Issue by leocoder0** [alibaba/canal#4334]
## Question

<img width="740" alt="image" src="https://user-images.githubusercontent.com/14870439/182803712-3c51e756-e7e4-4ff0-af94-d8f4044428b2.png">

**Comment by agapple** [comment]
0ef7b28c03a3231cdabd0bb3a54d8c90f44c9044

**Comment by agapple** [comment]
1.1.6时支持了jdk11的G1算法，需要针对jdk1.8做一个兼容
