### ISSUE TITLE
Canal 订阅Mysql Binlog日志，中文解析乱码

### ISSUE THREAD

**Issue by xingningbo** [alibaba/canal#4345]
Mysql version:5.7.33
canal: 1.1.6
描述：
canal订阅Mysql Binlog日志，flatMessage 设置为True，message 转换后的对象
<img width="1227" alt="image" src="https://user-images.githubusercontent.com/36439211/184101812-eb5ce7e6-98b7-4d7e-9c45-677d775b20fa.png">
#com.alibaba.otter.canal.connector.core.producer.MQMessageUtils#messageConverter
测试数据 course_name = 顶顶顶顶顶顶顶顶的sd测试

使用maxwell 订阅Mysql binlog日志 使用同数据展示
<img width="1744" alt="image" src="https://user-images.githubusercontent.com/36439211/184104064-6a24983f-5848-4481-80cb-2f465defd0e6.png">

**Comment by agapple** [comment]
canal你看的query event事件，不是dml event事件，这个和maxwell不是同一个对象

**Comment by agapple** [comment]
RowsQueryLogEvent默认是iso8859-1的编码，需要自行转码处理
