### ISSUE TITLE
canal-admin-1.1.6 启动没反应

### ISSUE THREAD

**Issue by leocoder0** [alibaba/canal#4359]
<img width="903" alt="image" src="https://user-images.githubusercontent.com/14870439/184830715-850a86e4-bb24-4da7-89a4-1b70e2418397.png">

各位大佬，为什么直接通过 sh bin/startup.sh 启动canal-admin没有反应，也没有任何日志？

**Comment by xalilo** [comment]
@leocoder0 大兄弟怎么解决的啊

**Comment by xalilo** [comment]
我自己切换成1.15就可以
