### ISSUE TITLE
1.1.6 server在admin 里面永远是停止状态，实际启动且集群里面也能看到，有遇到一样问题的么

### ISSUE THREAD

**Issue by ginshark** [alibaba/canal#4361]

**Comment by ginshark** [comment]
版本换回1.1.5就好了 。。。

**Comment by fox-says** [comment]
我遇到类似的问题，1.1.6 版本无论怎么搞，server都是断开状态，但是去修改集群配置之后，server却可以被admin控制并重启。。也没任何报错信息，但是就是断开状态，测试了一天了。 然后版本换成1.1.4，基本一样的配置，就没问题了。。。。这项目有点太迷了点！

**Comment by lkj2619** [comment]
+1

**Comment by agapple** [comment]
![image](https://user-images.githubusercontent.com/834743/189942284-e8d7af65-1c2b-4f12-935f-7f2796ac5aa5.png)

多看下文档：https://github.com/alibaba/canal/wiki/Canal-Admin-Guide
实测新版本是可以正常启动的，要注意在集群配置后，需要操作下并保存一次主配置，否则canal-server启动会失败

![image](https://user-images.githubusercontent.com/834743/189942650-0ed4581c-6d17-41be-82a5-6988932f4851.png)
