### ISSUE TITLE
当阿里云Rocket MQ的TOPIC为分区顺序消息时，在Canal设置partition等参数无效

### ISSUE THREAD

**Issue by wiwile** [alibaba/canal#4365]
现在我正在使用canal+rocket mq，
但目前我遇到的问题是，rocket mq的topic为分区顺序消息时，在Canal设置partition等参数无效。譬如，canal.mq.partition=1
在订阅这个topic时，通过getShardingKey获取的值都为null。如何解决？是否为bug?

**Comment by agapple** [comment]
问题没太看懂，getShardingKey是哪里的接口？
