### ISSUE TITLE
最新版本启动报错

### ISSUE THREAD

**Issue by zhengzhengzhengyi** [alibaba/canal#4366]
## Question

配置各项正常的 
java.lang.IllegalStateException: Extension instance(name: rabbitmq, class: interface com.alibaba.otter.canal.connector.core.spi.CanalMQProducer)  could not be instantiated: class could not be found

**Comment by LambdaV5** [comment]
跟踪调试代码发现可以将 canal.deployer-1.1.6\plugin中的jar包拷贝到  canal.deployer-1.1.6\lib\canal\plugin，就可以启动了

**Comment by agapple** [comment]
windows里有这个限制，linux下没问题
