### ISSUE TITLE
在LogEventConvert.parseOneRow方法中，添加扩展字段，client端，出现重复数据

### ISSUE THREAD

**Issue by shuhuiguo** [alibaba/canal#437]
在LogEventConvert.parseOneRow方法中，
添加扩展字段：rowDataBuilder.addProps(createSpecialPair("testName","testValue"));

client 端：
CanalEntry.RowData接收到重复key（testName） 的 Pair

**Comment by shuhuiguo** [comment]
找到原因了，是对canal的机制不熟悉导致的

**Comment by shuhuiguo** [comment]
这种方式才可以，不会重复，Pair.Builder builder = rowDataBuilder.addPropsBuilder();

**Comment by agapple** [comment]
没看懂具体问题
