### ISSUE TITLE
一天了，我还没明白各种配置文件是干嘛的，真厉害的项目！！！

### ISSUE THREAD

**Issue by lty628** [alibaba/canal#4371]
配置文件很乱
报错信息不明确
我只是想快速使用这个工具很难吗？
阿里的人你们自己找个人丢个你们写的文档，看看他们能懂吗？
行行行

**Comment by ifakeu** [comment]
社区版就这样咯，说明文档还是旧的，很多参数都靠自己摸索

**Comment by fengshengxie** [comment]
使用了，会出现异常停止并自动删除文件的情况。不知道什么鬼情况。https://github.com/alibaba/canal/issues/4381

**Comment by aboutZZ** [comment]
建议用 `Flink CDC`，生态比较好，文档完善，别浪费时间在这上面了

**Comment by cnlinjie** [comment]
同感，真TMD的服了，项目文档2019年的， 配置文件完全对不上，你们改配置的时候，能不能也改下文档？网上搜索的资料全TMD的是之前版本的，一个没用。
