### ISSUE TITLE
[proposal] make the parse module plugable

### ISSUE THREAD

**Issue by whhe** [alibaba/canal#4379]
## Why you need it?

The `parse` module is similar to the source connector for Kafka/Spark/Flink, which could be plugable by providing a set of interfaces for reading source log data. And if we do so, it will be easy to integrate data sources other than mysql.

## How it could be?

Now there are three modules which are related to `parse`:
- [canal.parse](https://mvnrepository.com/artifact/com.alibaba.otter/canal.parse)
- [canal.parse.dbsync](https://mvnrepository.com/artifact/com.alibaba.otter/canal.parse.dbsync)
- [canal.parse.driver](https://mvnrepository.com/artifact/com.alibaba.otter/canal.parse.driver)

Firstly, move all of them into the new `parse` module, and then add a common/core submodule and move the code for the common process into this module. For mysql related code, we can move it to another new submodule with name like  `canal.parse.mysql`. 

## Other related information

If the community agrees with this approach, I'd be happy to raise a pull request for it.

**Comment by agapple** [comment]
The idea of module design:
1. canal.dbsync This is a lib library for binlog parsing，which can satisfy your needs
2. canal.parse adds mysql HA support on the basis of dbsync parse library, and serializes it into canal data format
3. canal.driver is a lib library that replaces the mysql jdbc driver

**Comment by whhe** [comment]
> The idea of module design:
> 
> 1. canal.dbsync This is a lib library for binlog parsing，which can satisfy your needs
> 2. canal.parse adds mysql HA support on the basis of dbsync parse library, and serializes it into canal data format
> 3. canal.driver is a lib library that replaces the mysql jdbc driver

I think it would be better if the `canal.parse` module is not bound to a specific data source like MySQL, and the `AbstractEventParser` and `MultiStageCoprocessor` in it can be reused after a little modification. For now, if we want to add support for other data sources, we need rewrite the entire `canal.parse` module.
