### ISSUE TITLE
Java 客户端端无法监听变化

### ISSUE THREAD

**Issue by BigSnake1989** [alibaba/canal#4384]
## Question

server使用docker安装，
如下提示
`DOCKER_DEPLOY_TYPE=VM
==> INIT /alidata/init/02init-sshd.sh
==> EXIT CODE: 0
==> INIT /alidata/init/fix-hosts.py
==> EXIT CODE: 0
==> INIT DEFAULT
Generating SSH1 RSA host key:                              [  OK  ]
Starting sshd:                                             [  OK  ]
Starting crond:                                            [  OK  ]
==> INIT DONE
==> RUN /home/admin/app.sh
==> START ...
start canal ...
start canal successful
==> START SUCCESSFUL ...
tail: inotify cannot be used, reverting to polling: Function not implemented
tail: inotify cannot be used, reverting to polling: Function not implemented`

**Comment by BigSnake1989** [comment]
mac

**Comment by BigSnake1989** [comment]
![image](https://user-images.githubusercontent.com/3348756/187653872-650e72d3-5847-47ac-898b-f15c5366d9c1.png)

**Comment by agapple** [comment]
升级下1.1.7最新版
