### ISSUE TITLE
canal.instance.filter.query.dml=true

### ISSUE THREAD

**Issue by sherl0ckLiu** [alibaba/canal#4387]
![image](https://user-images.githubusercontent.com/108274057/187861875-58858062-cad5-4cc5-a7bb-2da836d845cd.png)
![image](https://user-images.githubusercontent.com/108274057/187861934-cb6253c8-b449-4204-8015-db0918a2a5ba.png)

如上图：
canal.serverMode = rabbitMQ下，
已经配置了canal.instance.filter.query相关所有变量为true，并且设置了监听的表，还是会收到没有监听且类型=query的消息，求救

**Comment by helpisyou** [comment]
请问解决了吗
