### ISSUE TITLE
parse faield : CREATE TABLE `columns_priv`

### ISSUE THREAD

**Issue by uniorder** [alibaba/canal#439]
Example的日志发现这个错误

**Comment by agapple** [comment]
应该是群里反馈的set类型不支持的问题，已经反馈给druid进行修复

**Comment by agapple** [comment]
https://github.com/alibaba/druid/commit/f8731f9182f01353e53331cf8ad590c6ca3db416

**Comment by uniorder** [comment]
Okay，我们暂时把这个功能给禁用掉了。
