### ISSUE TITLE
1.1.5canal server自动注册到canal admin失败

### ISSUE THREAD

**Issue by 1157242994** [alibaba/canal#4394]
配置文件adapter的canal_local.properties如下
# register ip
canal.register.ip = 192.168.86.130

# canal admin config
canal.admin.manager = 192.168.86.130:8089
canal.admin.port = 11110
canal.admin.user = admin
canal.admin.passwd = 6BB4837EB74329105EE4568DDA7DC67ED2CA2AD9
# admin auto register
canal.admin.register.auto = true
canal.admin.register.cluster = mydeployer-cluster
canal.admin.register.name = mydeployer-1

报错的信息如下
com.alibaba.otter.canal.common.CanalException: load manager config failed.
Caused by: com.alibaba.otter.canal.common.CanalException: requestGet for canal config error: auto cluster : mydeployer-cluster is not found.

**Comment by zangyunfeng** [comment]
我看这个问题已经关闭，打扰了一下，请问是怎么解决的

**Comment by immustard** [comment]
> 我看这个问题已经关闭，打扰了一下，请问是怎么解决的

你解决这个问题了么?
