### ISSUE TITLE
RocketMQ配置分区，集群模式下多消费实例，只有一个消费实例可以收到消息

### ISSUE THREAD

**Issue by zhangpf1127** [alibaba/canal#4400]
## 版本
1.1.6

## 分区配置
`canal.mq.dynamicTopic=trade:dy.*\\.trades,trade_his:dy.*\\.trades_his_xdaysago`
`canal.mq.partitionsNum=32`
`canal.mq.partitionHash=.*\\..*:tid`

tid是表的主键。

## 问题
阿里RocketMQ，集群模式下多消费实例，只有一个消费实例可以收到消息。
本以为是阿里RocketMQ的问题，提工单让他们技术查的结果是，未收到消息的消费实例分配的队列根本没有接收到消息。

帮忙看看还需要怎么去配置？

**Comment by zhangpf1127** [comment]
结贴，给后来的小伙伴。
折腾了好几天的问题，重新梳理了一下wiki上的设置，尝试通过设置canal.mq.enableDynamicQueuePartition来动态获取MQ服务端的分区数，使用阿里RocketMQ的小伙伴，如果有集群模式下只有一个消费实例能够收到消息的问题，可以尝试配置canal.mq.enableDynamicQueuePartition=true 试试。

**Comment by zcs19960929** [comment]
> 结贴，给后来的小伙伴。 折腾了好几天的问题，重新梳理了一下wiki上的设置，尝试通过设置canal.mq.enableDynamicQueuePartition来动态获取MQ服务端的分区数，使用阿里RocketMQ的小伙伴，如果有集群模式下只有一个消费实例能够收到消息的问题，可以尝试配置canal.mq.enableDynamicQueuePartition=true 试试。

感谢,我也是用的阿里RocketMQ.开始1.1.4怎么设置参数都不行,看了你的方法升到1.1.6后设置了这个参数就好了.不过升到1.1.6后启动canal会报错 不支持批处理....还需要改源码
