### ISSUE TITLE
Druid1.2.12与mysql-connector-java-5.1.48不兼容

### ISSUE THREAD

**Issue by adminpass** [alibaba/canal#4413]
### 版本
主线最新版本：Commits on Sep 15, 2022

### 问题
Druid升级到最新1.2.12（新增connectTimeout默认参数），与默认驱动（mysql-connector-java-5.1.48）不兼容，canal-adapter启动报NullPointerException，见下：

![error-info](https://user-images.githubusercontent.com/7523220/190373490-45037d77-a4f1-40f8-bf8e-292971fec306.png)

**Comment by Rmuyu** [comment]
我也发现了，兄弟你解决没？

**Comment by adminpass** [comment]
> 我也发现了，兄弟你解决没？

退回，换 1.2.11版本

**Comment by wenshao** [comment]
1.2.13版本修复了
