### ISSUE TITLE
有支持 Postgres 同步至 ElasticSearch 的计划吗？

### ISSUE THREAD

**Issue by tuobasai** [alibaba/canal#4415]
## Question

公司采用的是 Aliyun RDS Postgres，Search 方案采用的是阿里云 ElasticSearch 产品，现在有需求：

- 实现历史数据全量同步至 es
- 新增变更数据增量同步至 es

因为阿里云DTS不支持Postgres同步ElasticSearch，不知道这个开源项目能不能支持一下？

**Comment by adminpass** [comment]
不行，这是 mysql为主库，实现了 1->N

**Comment by zitongchen** [comment]
canal 的同步是基于 binlog 的，而 Postgres 不存在 binlog，Postgres 同步数据到 es 可以借助 debezium 工具。

**Comment by tuobasai** [comment]
好的，谢谢啦～
