### ISSUE TITLE
Deployer在外网连接阿里云账户时，无法进入

### ISSUE THREAD

**Issue by BlackAndCat** [alibaba/canal#4418]
[com.alibaba.otter.canal.parse.support.AuthenticationInfo] while setting bean property 'masterInfo'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.alibaba.otter.canal.parse.support.AuthenticationInfo#6dee4f1b' defined in class path resource [spring/file-instance.xml]: Initialization of bean failed; nested exception is java.lang.RuntimeException: 
**address[rm-******no.mysql.rds.aliyuncs.com] is illegal, eg.127.0.0.1:3306**

首先白名单，地址一类的错误可能性都翻来覆去查验了好几遍，只能认为问题出在deployer本身

canal Admin就没有这个问题。所以我该怎么用deployer，在外网进入阿里云服务器呢？

**Comment by BlackAndCat** [comment]
版本1.1.6

**Comment by agapple** [comment]
看着是你的配置不正确，需要写上端口号。 **address[rm-****no.mysql.rds.aliyuncs.com] is illegal, eg.127.0.0.1:3306
