### ISSUE TITLE
table meta生成snapshot比较方法有问题

### ISSUE THREAD

**Issue by jasonhx140** [alibaba/canal#442]
DatabaseTableMeta.applySnapshotToDB()方法中，先获取一个memoryTableMeta的副本tmpMemoryTableMeta，然后再去master库中去对比，然后如果一切正常则持久化snapshot.

但在和master库中ddl做对比时，却meta信息是从memoryTableMeta而不是tmpMemoryTableMeta，见compareTableMetaDbAndMemory()方法。

这样在多线程情况下，会导致数据不一致情况。

fix issue：对比时从tmpMemoryTableMeta中取meta信息。
>>>>>>
private boolean compareTableMetaDbAndMemory(MysqlConnection connection, final String schema, final String table) {
        TableMeta tableMetaFromMem = memoryTableMeta.find(schema, table);

<<<<<<
private boolean compareTableMetaDbAndMemory(MysqlConnection connection, final String schema, final String table，MemoryTableMeta            tmpMemoryTableMeta) {
        TableMeta tableMetaFromMem = tmpMemoryTableMeta.find(schema, table);
......

**Comment by agapple** [comment]
看的非常仔细，对这块TSDB比较理解，会有一个并发问题

**Comment by jasonhx140** [comment]
因为我们项目使用canal了，正好遇到这个问题了，当时做了一个定制的二次开发，正准备提交的，发现你们已经支持这个feature了。^_^!
还做了一个解决tableId not found的二次开发，正准备空闲时候提交到git上。
