### ISSUE TITLE
1.1.6版本 dynamicTopic配置后，无法生成对应规则topic

### ISSUE THREAD

**Issue by Rmuyu** [alibaba/canal#4421]
canal服务一直报错Error while fetching metadata with correlation id 538 : {=INVALID_TOPIC_EXCEPTION}。

具体配置如下，业务表均为日期分表，所以考虑使用.table_*格式来适配，然后将分表后的数据都汇入到同一个指定的topic中

canal.mq.dynamicTopic=coBox:collection\\.box_*

canal.mq.partitionsNum=3

canal.mq.partitionHash=.*\\..*:id

目前看来，这种配置不生效？大佬们有了解的吗？

**Comment by agapple** [comment]
canal.mq.topic默认topic也需要配置上，有一些query event无法命中topic规则，会发送到默认topic上
