### ISSUE TITLE
关于canal发消息到mq路由规则的问题

### ISSUE THREAD

**Issue by shawn-lu** [alibaba/canal#4422]
## Why you need it?
业务canal分片键不是一个完整的订单id,而是会有字段截取，比如订单id前几位。如果按完整的订单id作hash会导致消息发送队列不均匀。

## How it could be?
能否提供下配置或者扩展点，可以支持按分片键前几位或者字符串转化的方式来做消息路由

**Comment by agapple** [comment]
过于个性化的需求，建议直接维护内部canal分支吧
