### ISSUE TITLE
rabbitmq 插件支持密码加密

### ISSUE THREAD

**Issue by purple-T** [alibaba/canal#4424]
rabbitmq 公司监测出RabbitMQ明文漏洞。需要AMQP配置中禁用明文认证机制生效。请求设置后，canal连接报错，请问怎么设置？
Rabbitmq设置ssl连接参考：https://www.cnblogs.com/hellxz/p/15776987.html

**Comment by agapple** [comment]
可以提交一个PR给我

**Comment by olyhao** [comment]
请问这个问题解决了嘛，我是用canal连接aws rabbitmq服务一直失败，aws rabbitmq必须使用amqp tls加密，而且端口还是5671，请问怎么解决

> 可以提个公关给我

请问这个问题解决了嘛，我是用canal连接aws rabbitmq服务一直失败，aws rabbitmq必须使用amqp tls加密，而且端口还是5671，请问怎么解决
