### ISSUE TITLE
canal推送rocketmq消息包含白名单外的binlog

### ISSUE THREAD

**Issue by 493656894** [alibaba/canal#4429]
我使用了rocketmq进行binlog消息同步，但是消费到的消息里面，包含了白名单外的内容
canal黑白名单配置：
canal.instance.filter.regex=canal_manager.canal_data
canal.instance.filter.black.regex=mysql\\.slave_.*

1：往canal_data表里面新增一条数据，然后entries里面返回了三条数据，只有第二条包含了表名和表数据，第一条和第三条返回的不清楚是什么数据
![image](https://user-images.githubusercontent.com/19275999/192238485-005f5de5-a3bd-4062-a501-36eaacd388f0.png)
![image](https://user-images.githubusercontent.com/19275999/192238758-dc337d0d-64c2-4ef1-8ca0-1e53ffd3a8dc.png)

2：往test_table表里面新增一条数据，然后entries返回了两条数据（按白名单配置不应该返回数据才对），均不包含表名和表数据，如何可以过滤掉这些数据，避免产生大量多余的MQ消息影响系统性能？

**Comment by agapple** [comment]
一般是begin/commit 或者是 DML的query event

**Comment by farsunset** [comment]
> 一般是begin/commit 或者是 DML的query event
推送query 有什么意义？怎么禁止推送
