### ISSUE TITLE
问个问题我同一个数据库同一个schama不同的表，用多个不同的instance实例将配置互相隔离，canal最终会模拟多个节点拉取同一个配置吗

### ISSUE THREAD

**Issue by 985177520** [alibaba/canal#4430]
就相当于我配置了3个instance就拉取同样的binlog3次？

**Comment by agapple** [comment]
是的，拉取3份binlog

**Comment by 985177520** [comment]
> 是的，拉取3份binlog

可是大佬这样的话，如果我一个库下有多个表需要监听，我就只能在一个instance下管理，这样的话如果监听表过多就会显得很混乱。为什么不复用binlog呢- -如果是同一个库

**Comment by 985177520** [comment]
> 是的，拉取3份binlog

本质上只要是同一个库下binlog不同的instance直接复用不是更好吗0 0 ，拉取3份会有浪费问题，但是3份配置混合在一起会有维护问题
