### ISSUE TITLE
找不到 ClientAdapter 文档中提到的 SQL 脚本

### ISSUE THREAD

**Issue by senn-wen** [alibaba/canal#4432]
## ClientAdapter 文档中提到的 SQL 脚本缺失
> 文档：https://github.com/alibaba/canal/wiki/ClientAdapter

根据上述文档 2.2 节描述，应存在 manager_ddl.sql 脚本完成远程配置中心建表并初始化 Demo 数据，但是在文档中没有发现。

**Comment by agapple** [comment]
文档已更新.  https://raw.githubusercontent.com/alibaba/canal/master/admin/admin-web/src/main/resources/canal_manager.sql
