### ISSUE TITLE
canal-adapter的targetTable描述文档需要调整

### ISSUE THREAD

**Issue by qq592304796** [alibaba/canal#4434]
## Question

https://github.com/alibaba/canal/wiki/Sync-RDB#2-rdb%E8%A1%A8%E6%98%A0%E5%B0%84%E6%96%87%E4%BB%B6

targetTable: mytest.tb_user   # 目标数据源的库名.表名

从源码上看，现在好像拆分成
com.alibaba.otter.canal.client.adapter.rdb.support.SyncUtil#getDbTableName

targetDb: test
targetTable: purchase_order_task_mirror

两个字段了

**Comment by agapple** [comment]
两种写法都兼容
