### ISSUE TITLE
canal admin report “java.net.NoRouteToHostException: No route to host”

### ISSUE THREAD

**Issue by soliwolf** [alibaba/canal#4455]
## Question

My env:
    1. canal admin : v1.1.6
    2. canal deployer: v1.1.6
    3. zk(outer): 3.8.0
    4. jdk：java version "1.8.0_333"

My deploy:
    deploy with cluster model, with one cluster=mall

My problem:
    The canal admin service and the deployer service are running. 
    I try to stop the server from server managerment in canal admin, it apperes "**当前Server不是启动状态，无法停止**";  and then try to start the server from server managerment in canal admin, it apperes "**当前Server不是停止状态，无法启动**"; 
![image](https://user-images.githubusercontent.com/5688560/196331558-c384be45-a280-4785-b8d5-f7789fb8e088.png)

    Parse the log in canal admin, there are some exceptions, like "2022-10-15 17:44:47.867 [pool-4-thread-1] ERROR c.a.otter.canal.admin.connector.SimpleAdminConnectors - **java.net.NoRouteToHostException: No route to host**".
    Parse the zookeeper data, the data in '/otter/canal/cluster/destinations' is empty like below image.
![image](https://user-images.githubusercontent.com/5688560/195980236-ed0c8cbf-fa69-4d15-89b3-428ed465f3ba.png)

Anyone know how to solve the problem?

**Comment by agapple** [comment]
集群模式，canal_local.properties需要配置正确的cluster
