### ISSUE TITLE
/application 里srcDataSources 数据源配置 怎么配置阿里云数据库

### ISSUE THREAD

**Issue by zhang-yuanfu** [alibaba/canal#4457]
数据源是否支持公网，连接格式是不是只能支持ip+端口连接

**Comment by zhang-yuanfu** [comment]
@rewerma @agapple @lcybo 大佬能否解答下

**Comment by ChenJie193** [comment]
肯定支持啊，报错信息你也不贴

**Comment by zhang-yuanfu** [comment]
> 
报错信息就是连接不上，git服务器太烂了，上传不上，

**Comment by zhang-yuanfu** [comment]
> 肯定支持啊，报错信息你也不贴
不过我昨天看了看其他提的issues貌似是一样的配置方式

**Comment by zhang-yuanfu** [comment]
配置完现在出现了新的问题。。。
<img width="1588" alt="image" src="https://user-images.githubusercontent.com/51700759/196579457-a2432b5c-f2bb-43a3-a2c9-67654eece3c7.png"> 这个问题是因为哪个配置文件吗，我开始添加了application 和在es7里添加了对应的yml
,后面为了测试手动同步失败的原因把DataSources数据源和对应的yml都删除了。重启了service 及adapter 出现现在的报错

**Comment by ChenJie193** [comment]
你启动canal了吗 还是只启动了adapter

**Comment by zhang-yuanfu** [comment]
上面的问题是因为server启动时没有加上自定义的配置名称，启动时使用的默认的配置导致的

**Comment by yongzheJIN** [comment]
我没有报错，连接阿里云数据库，logs文件里面也正常打印日志，但就是目标库里面没有数据，这咋办啊？有遇到过吗？
