### ISSUE TITLE
canal.admin-1.1.6单机模式下启动，server总是显示为断开状态。

### ISSUE THREAD

**Issue by qq1063734335** [alibaba/canal#4458]
![image](https://user-images.githubusercontent.com/5792490/196318746-42dee928-0408-48ce-9894-5426ebd1361e.png)

canal.admin-1.1.6在单机模式下，server节点总是显示为断开状态。使用canal.admin-1.1.5配合canal.deployer-1.1.5、canal.deployer-1.1.6测试，可以正常显示为启动状态。

**Comment by agapple** [comment]
可以考虑升级下1.1.7-alpha版本

**Comment by yegaofei** [comment]
我也遇到了同样的问题，下载1.1.7-alpha版本后， 替换掉lib包里面的三个canal jar包重启就好了

**Comment by fengjx** [comment]
> 

请问下是什么原因，没找到对应的 pr
