### ISSUE TITLE
canal.instance.filter.black.regex不生效

### ISSUE THREAD

**Issue by qq592304796** [alibaba/canal#4459]
- [x] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment

* canal version
1.1.5
* mysql version
polardb-8.0.1.1.28

### Issue Description

https://help.aliyun.com/document_detail/212957.html?scm=20140722.S_help%40%40%E6%96%87%E6%A1%A3%40%40212957.S_0%2Bos.ID_212957-RL_access%E4%B8%AD%E8%A1%A8%E5%92%8C%E6%95%B0%E6%8D%AE%E5%BA%93%E7%9A%84%E5%85%B3%E7%B3%BB%E6%98%AF%20%20%20DOT-LOC_main-OR_ser-V_2-P0_1

DTS会在源库定时执CREATE DATABASE IF NOT EXISTS `test`命令以推进Binlog位点

canal.instance.filter.black.regex=mysql\\.slave_.*,.*\\.base table,test\\..*

{"data":null,"database":"`test`","es":1666101967000,"id":273,"isDdl":true,"mysqlType":null,"old":null,"pkNames":null,"sql":"CREATE DATABASE IF NOT EXISTS `test`","sqlType":null,"table":"","ts":1666101967931,"type":"QUERY"}

过滤不生效

### Actual behaviour

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by agapple** [comment]
create database默认不做filter，因为不符合 schema.tablename的过滤表达式，可以考虑提交一个PR给我
