### ISSUE TITLE
1.1.4 连不上mysql

### ISSUE THREAD

**Issue by hl976440572** [alibaba/canal#4461]
## Question

密码是正确的，部署到服务器上报错
![1e48ff6ca0e316e19e4eca3cca9fd57](https://user-images.githubusercontent.com/29592294/196655385-b19ae9c5-e788-4c86-b4af-7822ba3bdca8.png)

**Comment by ChenJie193** [comment]
尝试一下用别的连接工具是否可以连接mysql，或者是你的配置不对

**Comment by hl976440572** [comment]
用配置文件里面的密码和帐号是可以链接上的，并且服务器上的其他项目也能正常链接mysql，只有canal连不上




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月19日(星期三) 晚上6:13
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [alibaba/canal] 1.1.4 连不上mysql (Issue #4461)





 
尝试一下用别的连接工具是否可以连接mysql，或者是你的配置不对

**Comment by agapple** [comment]
1.  先尝试更新canal版本1.1.7，印象中有适配过mysql 8.0的auth认证流程
2. 如果还不行，那得检查下mysql使用的版本和协议认证是否和官方mysql保持一致了
