### ISSUE TITLE
主表含有group by适配问题

### ISSUE THREAD

**Issue by weiLin0722fjl** [alibaba/canal#4462]
### environment
* canal version 1.1.5
* mysql version  8.0.25

### Issue Description
canal使用kafka通信模式同步MySQL数据至ES，当配置到同步SQL主表含有group by语句时，出现SQL报错问题。

### Steps to reproduce
1、同步SQL配置如下：
select c.id as _id,
        c.id, 
        c.name, 
        .........
   from client c 
        LEFT JOIN xx
        LEFT JOIN xx
        LEFT JOIN xx
        LEFT JOIN xx
   GROUP BY c.id

2、canal拼接SQL代码如下：
ESSyncUtil类下
public static String appendCondition(String sql, String condition) {
        return sql + " WHERE " + condition + " ";
}

3、当拼接SQL时，直接将where条件添加在group by后面，造成语法错误

**Comment by zhang-yuanfu** [comment]
主sql不能使用where

**Comment by weiLin0722fjl** [comment]
@zhang-yuanfu 我的主SQL中并不包含where条件，canal拼接含有group by的sql会自动在后面添加where

**Comment by zhang-yuanfu** [comment]
我也是有这种需求发现不能使用where，我没有使用java 客户端不能重写他们的sql处理
<img width="974" alt="image" src="https://user-images.githubusercontent.com/51700759/198537261-fa82b8d1-42dc-480f-9598-398d11f4d0d5.png">

**Comment by weiLin0722fjl** [comment]
> 不是说主SQL不含where，主sql含有where，是否可以定制化ESSyncUtil类，判断主sql存在where的时候，后面不需要继续拼接where，而是拼接and

**Comment by weiLin0722fjl** [comment]
> 我也是有这种需求发现不能使用where，我没有使用java 客户端不能重写他们的sql处理 <img alt="image" width="974" src="https://user-images.githubusercontent.com/51700759/198537261-fa82b8d1-42dc-480f-9598-398d11f4d0d5.png">
下载源码下来，改下ESSyncUtil类，然后install替换 adapter/plugin中对应的jar包应该就可以了
