### ISSUE TITLE
Canal将数据发送到mq时，是否支持按表配置不同的tag？

### ISSUE THREAD

**Issue by anxinyh** [alibaba/canal#4468]
## Question

在dynamicTopic中配置哪些库哪些表发送到哪些topic的时候，是否支持发送到指定的tag呢？
比如现在规则是这样的 topicName:dbName\\.tableName，能否在某个地方加入对tag的定义？
我知道好像有全局的tag定义，但这并不满足业务需求，我需要的是可以给每张表都指定可以发送到MQ的哪个topic和tag

**Comment by agapple** [comment]
可以考虑提交一个PR给我，tag的生成看下是否有通用型
