### ISSUE TITLE
主sql不能使用where 条件 有没有什么方法可以实现 where

### ISSUE THREAD

**Issue by zhang-yuanfu** [alibaba/canal#4471]
## Question

我需要根据支付方式获取数据
<img width="520" alt="image" src="https://user-images.githubusercontent.com/51700759/198515319-0721361b-3ea0-4293-9b2a-a3dbcaf764a9.png">
全量同步可以，自动同步监听到binlog会有问题，更新sql
<img width="1331" alt="image" src="https://user-images.githubusercontent.com/51700759/198515717-5e9a7196-5642-4690-bf5d-8ced435ad1aa.png">

**Comment by zhang-yuanfu** [comment]
@agapple

**Comment by zhang-yuanfu** [comment]
有没有其他方式替代

**Comment by lsh1358046425** [comment]
找到解决方案了吗

**Comment by zhang-yuanfu** [comment]
> 找到解决方案了吗
索引新增支付方式字段，不在同步时做区分，在查询时根据这个字段筛选对应的数据
