### ISSUE TITLE
启动脚本的java命令能不能改成从JAVA_HOME中获取

### ISSUE THREAD

**Issue by tomatofrommars** [alibaba/canal#4473]
https://github.com/alibaba/canal/blob/0ef7b28c03a3231cdabd0bb3a54d8c90f44c9044/deployer/src/main/bin/startup.sh#L28-L32

系统里有jdk11和jdk17，`$(which java)`获取到的jdk17，canal并不支持。
我现在要使用jdk11的话，就得改上面的启动脚本，如果是从`JAVA_HOME`获取的话，我在启动前设置个环境变量就可以了。

**Comment by agapple** [comment]
一般JAVA_HOME和PATH是成对出现的，可以在startup.sh启动之前export PATH来解决
