### ISSUE TITLE
动态Topic配置Kafka分发，canal.mq.topic能否不配置

### ISSUE THREAD

**Issue by larry0xff** [alibaba/canal#4474]
![图](https://user-images.githubusercontent.com/20520265/199184727-00cbb2f3-be21-4607-86d2-a0d99d571b57.png)
动态Topic配置Kafka分发不同topic时，遇到如下问题：

配置方式参照如上图文档中示例5所示，库中有N个表，我只需要监听N-M个表，并通过不同的topic推送出去。
现在必须同时配置canal.mq.dynamicTopic和canal.mq.topic，否则canal会报错连接broker超时
按照文档所描述，不在canal.mq.dynamicTopic中配置的表变更都会推送到canal.mq.topic制定的默认topic，如果我不需要其他表的binlog，应该怎么配置呢？

**Comment by agapple** [comment]
可以配置binlog订阅条件：canal.instance.filter.regex
