### ISSUE TITLE
请问mysql和mariadb的binlog有啥区别，canal对mysql和mariadb的binlog解析有啥区别

### ISSUE THREAD

**Issue by Fugle666** [alibaba/canal#448]
如题，请问mysql和mariadb的binlog有啥区别，canal对mysql和mariadb的binlog解析有啥区别？
canal/dbsync/src/main/java/com/taobao/tddl/dbsync/binlog/event/mariadb/BinlogCheckPointLogEvent.java在这个类下，  public BinlogCheckPointLogEvent(LogHeader header, LogBuffer buffer, FormatDescriptionLogEvent descriptionEvent){
        super(header, buffer, descriptionEvent);
        // do nothing , just mariadb binlog checkpoint
    }中的// do nothing , just mariadb binlog checkpoint 是啥意思，这个类是怎么处理的

**Comment by agapple** [comment]
多看wiki，有描述

**Comment by Fugle666** [comment]
每找到，可以发个链接或者截图吗，谢谢

**Comment by shuhaoc** [comment]
@agapple  wiki上"BinlogChange(MariaDB5&amp;10)"好像已经删掉了

**Comment by Fugle666** [comment]
那你还有原版的吗

**Comment by agapple** [comment]
链接修复了
