### ISSUE TITLE
这个在binlog格式里就是bit类型，业务数据插入做下类型判断吧

### ISSUE THREAD

**Issue by HardyDou** [alibaba/canal#4486]
这个在binlog格式里就是bit类型，业务数据插入做下类型判断吧

_Originally posted by @agapple in https://github.com/alibaba/canal/issues/3736#issuecomment-939259245_
      

binlog 格式不是bit  canal 接受的数据都是正常的，就是落库时，将所有 >0的数字强制变成1 了。

**Comment by agapple** [comment]
落库时针对bit类型，需要按照long值写入目标库
