### ISSUE TITLE
cannel简介页面里的图挂了

### ISSUE THREAD

**Issue by patrickYang6625** [alibaba/canal#4488]
https://github.com/alibaba/canal/wiki/%E7%AE%80%E4%BB%8B
https://github.com/alibaba/canal/wiki/Introduction
![image](https://user-images.githubusercontent.com/12028898/201592201-a184ea94-2b30-4554-b59c-b6970f3a25fc.png)
![image](https://user-images.githubusercontent.com/12028898/201592256-c73d5334-4938-48fd-aca5-eb880db3d2b3.png)

**Comment by agapple** [comment]
可以正常打开，检查下是否墙的问题
