### ISSUE TITLE
当指定的pos刚好是rowdata(TableMap的下一条)数据时，canal server 端会陷入死循环BUG

### ISSUE THREAD

**Issue by wingerx** [alibaba/canal#449]
测试版本：canal 版本 1.0.24
1. Canal在实现该功能时，通过LogEventConvert.parseRowsEvent 解析event时抛出 TableIdNotFoundException， 但是parseRowsEvent 直接捕获了所有Exception，并重新抛出 CanalParseException，这样AbstractEventParser的parseThread 工作线程获取的一直都是Throwable的异常，无法感知到TableIdNotFoundException，导致陷入死循环；

2. 修改LogEventConvert.parseRowsEvent 使其抛出TableIdNotFoundException后，下次循环线程会感知needTransactionPosition变量已经会true，进入findTransactionBeginPosition方法后，会调用seek方法，但seek方法只解析事务头/尾，那么当前的seek方法中实现的sink的event事件就解析不到(因为rowdata数据被过滤了)，故reDump 一直都不会为true，从而也不会进入从头读取binlog的逻辑内，就又进入了主线程的死循环内。

PS:
个人简单分析，不知是否理解有误，抑或是findTransactionBeginPosition不是为了解决这个场景的?@agapple

**Comment by wingerx** [comment]
1. 将LogEventConvert.parseRowsEvent 在catch CanalParseException前加个catch TableIdNotFoundException并将其抛出，让上层继续感知；
2.

**Comment by wingerx** [comment]
修复建议：
1. 将LogEventConvert.parseRowsEvent 在catch CanalParseException前加个catch TableIdNotFoundException并将其抛出，让上层继续感知；
2. 将MysqlEventParser.findTransactionBeginPosition方法中的第一个mysqlConnection.seek改为mysqlConnection.dump 即可解决这个BUG

**Comment by agapple** [comment]
这个1.0.25我记得有修复过，可以先尝试一下

**Comment by wingerx** [comment]
ok，我切换到1.0.25重新试一下

**Comment by wingerx** [comment]
@agapple 我看了1.0.25的代码，但是并没有看到上面问题的修复，并且通过以下场景仍然可以非常容易复现：
1. binlog文件内容
![image](https://user-images.githubusercontent.com/33280738/33978900-d4cbc89a-e0dc-11e7-9104-bd4b3c083a0b.png)
图上标红的是rowdata 数据所在pos: 981
2. 指定 canal的启动位点即为 981这个位置
3. 启动server,观察日志如下：
![image](https://user-images.githubusercontent.com/33280738/33979023-720fb1de-e0dd-11e7-8baf-0c29da157c32.png)

可以看到一直处于循环启动的状态；

**Comment by agapple** [comment]
这块我关注一下
