### ISSUE TITLE
canal 服务端的密码是怎么生成的

### ISSUE THREAD

**Issue by SuperTangW** [alibaba/canal#4500]
## Question

我想知道服务端的这个密码的密文是怎么生成的，我想换个密码。。。
![image](https://user-images.githubusercontent.com/56583737/203284060-1f0c1f38-4820-45a9-bd65-bc90dee8a441.png)

**Comment by zhng1456** [comment]
这个应该只能看源码了，看下这个测试类
@SuperTangW 
`
package com.alibaba.otter.canal.server;

import java.security.NoSuchAlgorithmException;

import org.junit.Assert;
import org.junit.Test;

import com.alibaba.otter.canal.protocol.SecurityUtil;

public class SecurityUtilTest {

    @Test
    public void testSimple() throws NoSuchAlgorithmException {
        byte[] seed = { 1, 2, 3, 4, 5, 6, 7, 8 };
        // String str = "e3619321c1a937c46a0d8bd1dac39f93b27d4458"; // canal
        // passwd
        String str = SecurityUtil.scrambleGenPass("canal".getBytes());
        byte[] client = SecurityUtil.scramble411("canal".getBytes(), seed);
        boolean check = SecurityUtil.scrambleServerAuth(client, SecurityUtil.hexStr2Bytes(str), seed);
        Assert.assertTrue(check);
    }
}
`

**Comment by agapple** [comment]
https://github.com/alibaba/canal/wiki/Canal-Admin-ServerGuide

![image](https://user-images.githubusercontent.com/834743/210491864-747b3c8d-ca0d-428f-a83e-8d773209aecc.png)
