### ISSUE TITLE
canal-admin是否支持直接配置adapter

### ISSUE THREAD

**Issue by zhng1456** [alibaba/canal#4501]
## Question

目前存在表canal_adapter_config，DbRemoteConfigLoader中也支持直接读取表中数据了，能否直接通过admin界面快速配置adapter

**Comment by agapple** [comment]
暂时不支持，可以考虑提交一个PR给我

**Comment by YuGonge** [comment]
> 暂时不支持，可以考虑提交一个PR给我

你好现在支持了吗
