### ISSUE TITLE
canal server 集群模式, canal client 如何启动多个？

### ISSUE THREAD

**Issue by X-rapido** [alibaba/canal#4513]
#### 现有环境
- canal server V1.5
- zk 集群部署，两个 canal(server) ，一个 instance 名为 canal_index
- 一个 springboot + canal(client) 服务，连接 canal_index 实例，运行在 k8s pod
- runcher 维护 client pod

#### 已知
- 两个canal(server)，只会有一个工作，另一个处于阻塞状态
- 两个canal(client)，只会有一个工作，另一个处于阻塞状态

client 连接
```java
ClusterCanalConnector clusterConn = new ClusterCanalConnector(userName, password, destination, new ClusterNodeAccessStrategy(destination, ZkClientx.getZkClient(zkAddress)));
```

#### 问题
当 client pod 正常运行时，重启它，runcher 中 pod 会新增加一个 client 启动，启动完成后才会 remove 掉旧的 client，问题在于新创建的 client 会去连接 zk，发现已经有旧的 client 连接了，新 client 会进入阻塞状态，阻塞久了新 client pod 会不断重启，这导致旧的 client 不能删除，新的 client 启动永远处于阻塞。请问有没有一种优雅的方式可以解决这个问题？

比如：zk 的阻塞可以有超时时间，阻塞1分钟后自动断连，超过 30秒后，重试zk连接，再阻塞再断连，直至阻塞状态解除。这个过程，不会影响正常的项目启动。 目前想到这个思路，不知道 canal client 是否可以支持，或该如何实现？不知道大佬们有没有遇到过此类问题，请求指点。

**Comment by zhangxinping165** [comment]
@X-rapido 请问一下canal-client启动多个是如何解决的
