### ISSUE TITLE
Galera Mariadb cluster 配置多节点解析配置 

### ISSUE THREAD

**Issue by kleinstliuxin** [alibaba/canal#452]
请问，如果使用galera mariadb cluster的话，作为canal的master，根据文档
我需要写master和standby的信息，那么只需要配置各自的binlog file-name和position?
因为canal不支持GTID，3台的binlog信息不统一，能否达到正常切换的效果？

**Comment by agapple** [comment]
可以使用时间戳

**Comment by 564064202** [comment]
@agapple 现在支持GTID吗?

**Comment by ruochen** [comment]
有支持MariaDB GTID计划么？

**Comment by 564064202** [comment]
@ruochen @agapple GTID不就是mysql5.6的东西吗? @kleinstliuxin

**Comment by 564064202** [comment]
其实我们关心的是MariaDB Galera Cluster  作为master,然后canal连接过去...

**Comment by ruochen** [comment]
> @ruochen @agapple GTID不就是mysql5.6的东西吗? @kleinstliuxin

MariaDB的GTID实现和官方GTID不一样，binlog信息也不一样

**Comment by agapple** [comment]
MySQL默认的GTID已经支持了，MariaDB的没测试过
