### ISSUE TITLE
canal1.1.5版本中canal.mq.send.thread.size = 30 canal.mq.build.thread.size = 8 这两个参数生产中配置多少是合适的？单机是8C16G

### ISSUE THREAD

**Issue by HZLHZLHZL** [alibaba/canal#4530]
## Question

canal1.1.5版本中canal.mq.send.thread.size = 30 canal.mq.build.thread.size = 8 这两个参数生产中配置多少是合适的？单机是8C16G

**Comment by agapple** [comment]
可以保持默认值
