### ISSUE TITLE
cancal bind ip address error

### ISSUE THREAD

**Issue by kleinstliuxin** [alibaba/canal#454]
Something goes wrong when starting up the canal Server:
org.jboss.netty.channel.ChannelException: Failed to bind to xxxx
请问canal只能绑定本机ip吗？
如果是台vm，分配了一个映射的ip，指定绑定此IP就会报如上的错误。

**Comment by agapple** [comment]
可以指定绑定的ip

**Comment by kleinstliuxin** [comment]
1.0.25 绑定vm映射IP失败。只能绑定本机vm的私网ip。
![canal_err01](https://user-images.githubusercontent.com/34462344/34280405-6547bbc0-e6f2-11e7-9f3f-a08c14c2ceec.png)
