### ISSUE TITLE
canal1.1.6版本admin启动成功，配置deployer启动成功，日志显示成功，但是admin中一直显示断开状态

### ISSUE THREAD

**Issue by ttr5966** [alibaba/canal#4542]
## Question

![image](https://user-images.githubusercontent.com/61843308/208622737-aa5f6115-67ea-4412-bd49-60238388af9f.png)
这是我deployer的配置，
![image](https://user-images.githubusercontent.com/61843308/208622878-7188ee4c-8797-4b0a-bdb0-4132d47fcc00.png)
这是我admin的配置

**Comment by ttr5966** [comment]
然后canal1.1.7版本正常启动amdin、depolyer，adpater启动失败，一直提示这个
![image](https://user-images.githubusercontent.com/61843308/208623178-4cb1dcac-6b4f-4380-8ac7-3cef5c36328e.png)
这是我adpater的配置
![image](https://user-images.githubusercontent.com/61843308/208623250-8ddc3368-a278-4ca2-8163-84b1faf8dbc9.png)

**Comment by zhangpengke** [comment]
我也是，1.1.6版本启动没有报错，admin一直显示“断开”状态，问题解决了吗

**Comment by opcache** [comment]
> 我也是，1.1.6版本启动没有报错，admin一直显示“断开”状态，问题解决了吗
是用着没问题啊，可以用这个镜像docker pull  opcache/canal:admin

**Comment by YANG18642029437** [comment]
你点击 service 看提示有没有报错
<img width="1917" alt="image" src="https://user-images.githubusercontent.com/43190741/210041710-cf591533-665b-4c22-a1a3-5c2306293f8d.png">
如果有报错的话 应该是 jdk 版本问题

**Comment by ttr5966** [comment]
日志是没有报错的，jdk是1.8的，不清楚什么问题

**Comment by agapple** [comment]
可以先升级到jdk11
