### ISSUE TITLE
canal server是否能支持rabbitMq集群配置方式，类似rabbitmq.addresses= 192.168.100.101:5672,192.168.100.102:5672

### ISSUE THREAD

**Issue by heheyue** [alibaba/canal#4548]
功能需求：
     canal server 推送消息到rabbitmq 三节点集群。
当前状态：
     zookeeper 部署集群模式 
     canal server 集群模式  
     admin管理。
     当前canal 配置单节点rabbitmq功能可用。但想保证可用性。所以想连接rabbitmq集群。
     在配置rabbitmq集群字段部分时发现并不支持集群字段方式配置。不知道否有rabbitmq集群的配置方式，类似于java中rabbitmq部分的配置写法：
     rabbitmq.addresses= 192.168.100.101:5672,192.168.100.102:5672

**Comment by agapple** [comment]
可以考虑提交一个PR给我
