### ISSUE TITLE
请问 TCP 模式下 TRANSACTIONBEGIN TRANSACTIONEND 事物消息可以屏蔽吗

### ISSUE THREAD

**Issue by YANG18642029437** [alibaba/canal#4552]
<img width="391" alt="image" src="https://user-images.githubusercontent.com/43190741/210032904-0fb072df-3c7d-4813-8dcd-bc35426cba31.png">

**Comment by agapple** [comment]
无法完全屏蔽，用于更新位点。可以在client接收端直接过滤
