### ISSUE TITLE
server ha 模拟 宕机 something goes wrong when getWithoutAck data from server:null

### ISSUE THREAD

**Issue by maczhao** [alibaba/canal#456]
something goes wrong when getWithoutAck data from server:null
请问怎么破，谢谢

**Comment by agapple** [comment]
选择用canal1.0.25最新版吗？

**Comment by klc025107** [comment]
canal1.0.25现在也有这个问题。在canal的客户端报错。

**Comment by zhangyb0404** [comment]
我也碰到这个问题了   1.0.25

**Comment by agapple** [comment]
看一下服务端对应的异常

**Comment by klc025107** [comment]
昨天测试的时候在客户端出现异常，没有发现服务器端的异常。测试的过程中主要在两个方面客户端出现异常1.客户端启动并多次连接服务器端 2 服务器端在进行HA切换的时候客户端出现这个异常。
