### ISSUE TITLE
Client中 subscribe  筛选失效了

### ISSUE THREAD

**Issue by wz2cool** [alibaba/canal#457]
你好，我使用的是canal 1.0.24 deployer 和 client 都是这个版本， 第一次我设置client 中subscribe  是生效的，获取数据是可以正常筛选的，但是我改了deployer 中positon 并且删除了 meta.dat 想重新插入一下数据，发现我能下载到其他库的数据，其实我只要两张表。 请问大神这是什么问题

客户端筛选为：dm_data.person,dm_data.student

结果我下载到了其他数据库的数据
现在meta 数据可以看到 我只要dm_data 库的数据
![image](https://user-images.githubusercontent.com/11556152/34139754-70e7f47e-e4b1-11e7-8a96-133c720f9a58.png)

现在下载到其他库的数据了
![image](https://user-images.githubusercontent.com/11556152/34140115-7e1973be-e4b3-11e7-9150-d4e5f4e83c99.png)dm_

**Comment by wz2cool** [comment]
试过几次可以稳定重现， 删除conf 中实例中的meta.dat , 然后重启 重新指定instance.properties 中的position 就失效了， 现在workaround 就是在 instance.properties 再写一个筛选

**Comment by agapple** [comment]
client的subscribe的条件是每次都发送的吗？

**Comment by zaccheus** [comment]
遇到类似的问题，筛选一大串表，个别表就监测不到数据，但，设置为只监测这个表时，可以顺利监测到数据

**Comment by agapple** [comment]
参考：https://github.com/alibaba/canal/wiki/FAQ
