### ISSUE TITLE
canal监听从库收不到数据，但是通过工具直接改从库可以收到数据

### ISSUE THREAD

**Issue by Tyoukai** [alibaba/canal#4571]
## Question

架构如下所示：
主库a  -> 从库 b-> canal 服务端

主库a通过binlog将数据同步到从库b，之间正常同步，然后canal服务端当做从库b的从库，canal收到消息后，会将消息发送到kafka、
问题：主库a每天都有更新，从库b也都能收到a的消息并更新数据，但是canal 却接收不到数据。但是如果通过工具直接修改从库b的数据时，canal服务端就可以收到数据。请教下这个是什么原因？

**Comment by ViSearch** [comment]
同问

**Comment by albertfengjiajun** [comment]
同问

**Comment by agapple** [comment]
从库是否开启binlog？比如log_slave_updates参数
