### ISSUE TITLE
如何重启实例而不重启server

### ISSUE THREAD

**Issue by wz2cool** [alibaba/canal#459]
请问如何重启实例，因为想要应用position 的位置， 如果stop 再startup 的话 会导致其他实例也会收到影响

**Comment by agapple** [comment]
移除文件夹，然后再加回来

**Comment by wz2cool** [comment]
@agapple 嗯 好的 我去试试看， 能否把这个方法写到wiki 里面

**Comment by wz2cool** [comment]
测试有效 关闭issue
