### ISSUE TITLE
ddl 出现\305\241\305\202\342\211\240\305\233\304\226\303\241，直接打印是乱码

### ISSUE THREAD

**Issue by liuwenfeng554** [alibaba/canal#460]
eventType: ALTER
isDdl: true
sql: "ALTER TABLE `account_user_info_stream_test`\r\nADD COLUMN `test001`  varchar(255) NULL DEFAULT \'\' COMMENT \'\305\241\305\202\342\211\240\305\233\304\226\303\241\' AFTER `modifiedon`"
ddlSchemaName: "test"

**Comment by liuwenfeng554** [comment]
parse ddl sql : ALTER TABLE `account_user_info_stream_test` ADD COLUMN `test001` varchar(255) NULL DEFAULT '' COMMENT 'šł≠śĖá' AFTER `modifiedon`

**Comment by liuwenfeng554** [comment]
@agapple  这个该如何转码

**Comment by agapple** [comment]
默认应该是iso-8859-1的编码，按照这个转码一下看看

**Comment by liuwenfeng554** [comment]
试过 new String(sql, "ISO8859-1")...  没用 
从CanalEntry.Entry entry中获取
Entry result：header {
  version: 1
  logfileName: "mysql-bin.006352"
  logfileOffset: 1073084521
  serverId: 3
  serverenCode: "UTF-8"
  executeTime: 1513863317000
  sourceType: MYSQL
  schemaName: "test"
  tableName: "account_user_info_stream_test"
  eventLength: 203
  eventType: ALTER
}
entryType: ROWDATA
storeValue: "\020\005P\001Z\224\001alter table test.account_user_info_stream_test add  `test00001_14` varchar(25) not null  DEFAULT \'2\' comment \'\305\233\304\266\304\215\305\244\304\256\304\223\305\232\303\244\302\243\305\232\303\244\305\205\305\232\303\251\303\234\305\232\305\271\342\211\244\'r\004test"

CanalEntry.RowChange rowChange = null;
                try {
                    rowChange = CanalEntry.RowChange.parseFrom(entry.getStoreValue());
            ............

RowChange result：eventType: ALTER
isDdl: true
sql: "alter table test.account_user_info_stream_test add  `test00001_14` varchar(25) not null  DEFAULT \'2\' comment \'\305\233\304\266\304\215\305\244\304\256\304\223\305\232\303\244\302\243\305\232\303\244\305\205\305\232\303\251\303\234\305\232\305\271\342\211\244\'"
ddlSchemaName: "test"

是不是这里CanalEntry.RowChange.parseFrom 有问题 @agapple

**Comment by liuwenfeng554** [comment]
CanalEntry.Column  中文输出是正常   CanalEntry.RowChange 中文好像是直接上面类似于8进制的一串

**Comment by liuwenfeng554** [comment]
@agapple

**Comment by agapple** [comment]
你用debug模式，看一下从mysql binlog里收到的数据是啥吧，QueryLogEvent这个类

**Comment by liuwenfeng554** [comment]
采用2017-12-25 19:03:29,469 [binlog-parser-1] INFO  [com.taihe.cloud.binlog.InstanceListener] - cdcEvent:{ eventId:66,databaseName:test,tableName:`account_user_info_stream_test`
add,eventType:2,timestamp:1514199796000,timestampReceipt:1514199809467,binlogName:null,position:398723955,nextPostion:398724150,serverId:3,isDdl:true,sql:ALTER TABLE `account_user_info_stream_test`
ADD COLUMN `test002`  varchar(255) NULL COMMENT '中文' AFTER `test00001_2`,before:null,after:null}
{
  "eventId": 66,
  "databaseName": "test",
  "tableName": "`account_user_info_stream_test`\r\nadd",
  "eventType": 2,
  "timestamp": 1514199796000,
  "timestampReceipt": 1514199809467,
  "binlogName": null,
  "position": 398723955,
  "nextPostion": 398724150,
  "serverId": 3,
  "before": null,
  "after": null,
  "isDdl": true,
  "sql": "ALTER TABLE `account_user_info_stream_test`\r\nADD COLUMN `test002`  varchar(255) NULL COMMENT \u0027中文\u0027 AFTER `test00001_2`"
}

**Comment by liuwenfeng554** [comment]
因为没办法本地调试代码 我试了采用OpenReplicator解析MySQL binlog
2017-12-25 19:03:29,469 [binlog-parser-1] INFO  [com.taihe.cloud.binlog.InstanceListener] - cdcEvent:{ eventId:66,databaseName:test,tableName:`account_user_info_stream_test`
add,eventType:2,timestamp:1514199796000,timestampReceipt:1514199809467,binlogName:null,position:398723955,nextPostion:398724150,serverId:3,isDdl:true,sql:ALTER TABLE `account_user_info_stream_test`
ADD COLUMN `test002`  varchar(255) NULL COMMENT '中文' AFTER `test00001_2`,before:null,after:null}
{
  "eventId": 66,
  "databaseName": "test",
  "tableName": "`account_user_info_stream_test`\r\nadd",
  "eventType": 2,
  "timestamp": 1514199796000,
  "timestampReceipt": 1514199809467,
  "binlogName": null,
  "position": 398723955,
  "nextPostion": 398724150,
  "serverId": 3,
  "before": null,
  "after": null,
  "isDdl": true,
  "sql": "ALTER TABLE `account_user_info_stream_test`\r\nADD COLUMN `test002`  varchar(255) NULL COMMENT \u0027中文\u0027 AFTER `test00001_2`"
}
同样用canal  则显示解析乱码 
Entry result：header {
  version: 1
  logfileName: "mysql-bin.006360"
  logfileOffset: 398723955
  serverId: 3
  serverenCode: "UTF-8"
  executeTime: 1514199796000
  sourceType: MYSQL
  schemaName: "test"
  tableName: "account_user_info_stream_test"
  eventLength: 195
  eventType: ALTER
}
entryType: ROWDATA
storeValue: "\020\005P\001Z\200\001ALTER TABLE `account_user_info_stream_test`\r\nADD COLUMN `test002`  varchar(255) NULL COMMENT \'\305\241\305\202\342\211\240\305\233\304\226\303\241\' AFTER `test00001_2`r\004test"

2017-12-25 19:02:53,902 (main) [INFO - com.trcloud.hamal.stream.core.operator.impl.canal.CanalSource.fetchEvent(CanalSource.java:142)] RowChange result：eventType: ALTER
isDdl: true
sql: "ALTER TABLE `account_user_info_stream_test`\r\nADD COLUMN `test002`  varchar(255) NULL COMMENT \'\305\241\305\202\342\211\240\305\233\304\226\303\241\' AFTER `test00001_2`"
ddlSchemaName: "test"

2017-12-25 19:02:53,903 (main) [INFO - com.trcloud.hamal.stream.core.operator.impl.canal.CanalSource.buildEvent(CanalSource.java:179)] RowChange result：eventType: ALTER
isDdl: true
sql: "ALTER TABLE `account_user_info_stream_test`\r\nADD COLUMN `test002`  varchar(255) NULL COMMENT \'\305\241\305\202\342\211\240\305\233\304\226\303\241\' AFTER `test00001_2`"
ddlSchemaName: "test"

2017-12-25 19:02:53,904 (main) [INFO - com.trcloud.hamal.stream.core.operator.impl.canal.CanalSource.parseColumns(CanalSource.java:239)] parse ddl sql : ALTER TABLE `account_user_info_stream_test` ADD COLUMN `test002` varchar(255) NULL COMMENT 'šł≠śĖá' AFTER `test00001_2`
2017-12-25 19:02:53,914 (main) [INFO - com.trcloud.hamal.stream.core.operator.impl.canal.CanalSource.parseColumns(CanalSource.java:337)] ddl result map : {"test002":{"comment":"šł≠śĖá","curName":"test002","key":false,"nulled":true,"oldName":"","operPimay":false,"operType":"ADD","type":"varchar(255)"}}
2017-12-25 19:02:53,954 (main) [INFO - com.trcloud.hamal.stream.core.operator.impl.canal.Canal2SqlOperator.transform(Canal2SqlOperator.java:77)] sqlDecorators: [{"eventType":"ALTER","sql":"ALTER TABLE test.account_user_info_stream_test ADD COLUMN test002 varchar(255)  NULL DEFAULT '' ;COMMENT ON COLUMN test.account_user_info_stream_test.test002 IS 'šł≠śĖá';","storm_time":"2017-12-25 19:03:16","tableName":"account_user_info_stream_test"}]

**Comment by agapple** [comment]
![image](https://user-images.githubusercontent.com/834743/34376917-6f694958-eb29-11e7-81b1-90119700a9dd.png)

我这里验证可以拿到正确的编码，请确保建表，binlog dump的编码保持一致，我这里全部设置为utf8

**Comment by liuwenfeng554** [comment]
binlog dump的编码保持一致是指哪块？
建表及都看了 好像都是UTF8
mysql> show global variables like '%character%';
+--------------------------+-------------------------------------+
| Variable_name            | Value                               |
+--------------------------+-------------------------------------+
| character_set_client     | utf8                                |
| character_set_connection | utf8                                |
| character_set_database   | utf8                                |
| character_set_filesystem | binary                              |
| character_set_results    | utf8                                |
| character_set_server     | utf8                                |
| character_set_system     | utf8                                |
| character_sets_dir       | /usr/share/percona-server/charsets/ |
+--------------------------+-------------------------------------+
8 rows in set (0.00 sec)

mysql>

**Comment by liuwenfeng554** [comment]
最终定位问题
/**
     * Return next 16-bit unsigned int from buffer. (little-endian)
     * 
     * @see mysql-5.1.60/include/my_global.h - uint2korr
     */
    public final int getUint16() {
        if (position + 1 >= origin + limit) throw new IllegalArgumentException("limit excceed: "
                                                                               + (position - origin + 1));

        byte[] buf = buffer;
        return (0xff & buf[position++]) | ((0xff & buf[position++]) << 8);
    }
这段代码获取到45  不是33  想问下大神这里解析跟mysql版本有关吗？本地使用mysql版本5.6.27

**Comment by zgl1011** [comment]
麻烦问下最后怎么解决的，我也存在同样的现象。。。
