### ISSUE TITLE
canal admin version:1.1.5   Jackson 反序列化漏洞,位置:/lib/jackson-databind-2.9.5.jar

### ISSUE THREAD

**Issue by ylkhLMF** [alibaba/canal#4609]
- [ ] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment

* canal version
* mysql version

### Actual behaviour

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by agapple** [comment]
可以考虑提交一个PR给我
