### ISSUE TITLE
如何过滤指定的常量条件，如 where id = 1 and 999999 = 999999 

### ISSUE THREAD

**Issue by xslong** [alibaba/canal#4611]
## Question

针对指定表、字段的过滤使用我已经明白了，我现在有一个这样的需求：数据源库的部分删除SQL不想被同步，我的想法是在SQL上自定义一个标记，如 delete from table_name where id = 1 and 999999 = 999999 
 ，在Canal监听的时候捕获的到999999 = 999999 这个条件就过滤掉。
我现在遇到的问题是，调试中 CanalEntry.Entry 对象中没有关于 999999 = 999999的任何信息，只有数据库字段，所以没有办法实现过滤。

请教下是否是配置错误，或者其他的实现方法，谢谢！

![image](https://user-images.githubusercontent.com/5440930/220001777-5e201f22-103a-4495-97d6-05b8dd073e19.png)

**Comment by agapple** [comment]
binlog里只有修改的记录，没有对应的sql语句

一种高级的做法：
1.  打开rowsQueryLogEvent，默认会记录sql到binlog，和dml一起包裹在事务中
2.  解析到事务后，识别对应的rowsQuery的sql，判断一下，决定后续跟着的dml是否同步

这个方案要求对binlog有一定的了解和处理能力，比如事务的边界处理等

**Comment by xslong** [comment]
非常感谢
