### ISSUE TITLE
canal同步数据至aws rabbitmq

### ISSUE THREAD

**Issue by olyhao** [alibaba/canal#4618]
canal同步mysql数据至aws rabbitmq一直连接不上aws的rabbitmq服务，好像是因为aws对提供的rabbitmq做了tls认证，提供的连接端口是5671；我自建的rabbitmq可以正常连接，请问这个可以提供解决方案吗？

**Comment by olyhao** [comment]
@agapple 大哥我需要你的帮助

**Comment by agapple** [comment]
目前rabbitmq不支持tls，可以考虑提交一个PR给我
