### ISSUE TITLE
canal 时间戳指定

### ISSUE THREAD

**Issue by kleinstliuxin** [alibaba/canal#462]
看文档说：
canal.instance.master.timestamp : 指定一个时间戳，canal会自动遍历mysql binlog，找到对应时间戳的binlog位点后，进行启动
那么请问格式是什么？必须要同时写上position和timestamp吗？
canal.instance.standby.timestamp = 1513844601 报错，canal.instance.standby.timestamp = ‘2017-12-22 xx:xx:xx’ 也是一样的错误
错误如下截图：
![canal_err02](https://user-images.githubusercontent.com/34462344/34283126-062ed3c2-e705-11e7-93d5-802275d5a35b.png)

**Comment by kleinstliuxin** [comment]
position info conf:
canal.instance.master.address = xxxxxx:3306
canal.instance.master.journal.name = MariaDB-bin.000001
canal.instance.master.position =
canal.instance.master.timestamp = 1513845143

canal.instance.standby.address = xxxxxxxxx:3306
canal.instance.standby.journal.name = MariaDB-bin.000004
canal.instance.standby.position =
canal.instance.standby.timestamp = 1513844601

**Comment by agapple** [comment]
写着对应的timestamp即可
