### ISSUE TITLE
canal1.1.6版本上游对接阿里云RDS下游对接阿里rocketmq，配置的动态topic是没有问题的，但是上游换成自建mysql5.6版本后，开启动态topic就会有报错？有大佬遇到过？自建mysql和RDS相关参数是一样的。

### ISSUE THREAD

**Issue by HZLHZLHZL** [alibaba/canal#4623]
![image](https://user-images.githubusercontent.com/46432192/221133946-848086b6-f2af-453d-abc8-f84cae7ef052.png)
其他没有报错。

**Comment by HZLHZLHZL** [comment]
![image](https://user-images.githubusercontent.com/46432192/221134238-6414acd0-613f-4aff-899c-7e216489c0f2.png)
并且是配置了监听表的，并且阿里rocketmq也提前建好了相关topic的。

**Comment by agapple** [comment]
有可能是发送了ddl语句，印象中1.1.7修复过类似问题，可以考虑升级下
