### ISSUE TITLE
there are two problems about using rabbitmq receive messges

### ISSUE THREAD

**Issue by wang-xiaowu** [alibaba/canal#4630]
- [x] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment

* canal version: 1.1.6
* mysql version: 5.7

### Issue Description
1. filter propertie in class `RabbitMQCanalConnector` was declarated, but was not being used
![image](https://user-images.githubusercontent.com/44340137/223079062-e09b3304-ed5c-4e57-a027-a6eedb4bf05e.png)

2. canal-server/admin can not configure the default exchange(if i write '' or "", it reminds me `no exchange '' xxx`)
![image](https://user-images.githubusercontent.com/44340137/223079614-7be80212-6d74-4834-ba2c-07eb676c162c.png)

### Actual behaviour

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by agapple** [comment]
可以考虑提交一个PR给我

**Comment by agapple** [comment]
可以考虑提交一个PR给我
