### ISSUE TITLE
脑裂问题

### ISSUE THREAD

**Issue by zhangjun888** [alibaba/canal#464]
HA集群模式下：
1.首先启动canal-server1 ，启动成功，相应的destination实例启动成功。
2.启动canal-server2，没有启动成功，相应的destination实例也没有启动成功。
3.断掉canal-server1和zk的连接，比如我添加了一个防火墙，不允许canal-server1连接到zk，但是不断canal-server1和mysql的连接
4.这个时候zk中destination的running节点的信息变成canal-server2，但是canal-server1 中的destination实例仍在运行，仍然可以接收mysql的binlog进行解析。这样就出现了两个canal server的destination都处于运行的状态，
5.此时，我断掉canal-server1 ，这个时候zk中的destination无法自动切换到canal-server2，虽然canal-server2正在运行

**Comment by agapple** [comment]
第4部不是已经正常切换了吗？老的canal-server1会监听zk的状态变化，如果非当前运行会关闭内存里的destination

**Comment by suifengzhuliu** [comment]
在第四步的时候，zk的信息确实已经成功切换到cana-server2,  但是如果canal-server1一直连不上zk的情况下。它会不断报连接被拒绝，但是同时和canal-server2一样，也是在解析mysql的binlog

**Comment by agapple** [comment]
canal-server1使用的zk client会和zk server心跳机制，超过一段时间连不上，则自己会认为出现session timeout，然后关闭自己的binlog解析

**Comment by suifengzhuliu** [comment]
假死的canal-server1会和zk有心跳，timeout之后会关闭自己的binlog解析，比如我们设置的心跳时间是5秒，在这个5秒的心跳窗口时间之内，应该是canal-server1和canal-server2同时都在解析吧。

**Comment by suifengzhuliu** [comment]
当canal-server1假死，canal-server2切换成active状态的时候，应该对canal-server1进行隔离吧

**Comment by zhouluoyang0406** [comment]
现在假死这个可能性 有做什么处理么？

**Comment by littleneko** [comment]
> 假死的canal-server1会和zk有心跳，timeout之后会关闭自己的binlog解析，比如我们设置的心跳时间是5秒，在这个5秒的心跳窗口时间之内，应该是canal-server1和canal-server2同时都在解析吧。

@zhangjun888 请问你说的 *设置的心跳时间是5秒* 这个设置是在哪里？我没有找到，我现在的测试结果是canal和zk之间的网络断开后，canal instance 并不会停止

**Comment by agapple** [comment]
可以google一下zookeeper的sessionTimeout

**Comment by JichengSong** [comment]
我们最近也遇到了这个问题，canal版本1.1.4 ,  server1 server2 两台物理机做HA ，配置了100个左右destination ，运行一段时间后，多个destination在server1 server2同时存在；在canal admin 上只显示server1 或 server2 。 目前还在定位原因中.
