### ISSUE TITLE
Canal AdminWeb模块,自定义Model类中有冗余代码

### ISSUE THREAD

**Issue by fumingjian** [alibaba/canal#4643]
- [ ] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment

* canal version
*  canal 1.1.6 
* public abstract class Model extends io.ebean.Model
* mysql version
*

### Issue Description
![42a6bfeffa76077c39c91413a4f1049](https://user-images.githubusercontent.com/29276583/223948248-5f1e2b58-7afa-459b-896f-14cb4c44895e.png)

![e5100221fbf3a3bc06c36a44683136d](https://user-images.githubusercontent.com/29276583/223948567-3bc568ab-9f5f-45dc-8834-6f18a72202a8.png)

### Actual behaviour

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by fumingjian** [comment]
saveOrUpdate方法中 init调用应该清理掉

**Comment by agapple** [comment]
可以考虑提交一个PR给我
