### ISSUE TITLE
canal.instance.filter.black.field 配置的黑名单字段，当这些字段被修改后，依然会发mq消息，怎么处理

### ISSUE THREAD

**Issue by silver-space-dream** [alibaba/canal#4645]
## Question
canal.instance.filter.black.field 配置的黑名单字段，当这些字段被修改后，依然会发mq消息，怎么处理

**Comment by agapple** [comment]
从目前实现来看，blackFieldList更多是忽略对应字段，但是整个row记录还是会发送
