### ISSUE TITLE
yml配置追加问题

### ISSUE THREAD

**Issue by BeanCjc** [alibaba/canal#4648]
### Issue Description
在使用canal-adapter过程中,当rdb目录下存在多个mapping文件时,后面的配置会读取到前面配置文件的内容
例如第一个yml的mapping的targetPk为id,第二个yml的mapping的targetPk为log_id时,此时在对第二个yml配置读取并注入的时候读取到targetPk.id和targetPk.log_id两个配置项,就造成了配置错误

### Expected behaviour
merge my PR to fix this bug or do some others

**Comment by agapple** [comment]
https://github.com/alibaba/canal/pull/4560
