### ISSUE TITLE
使用run.sh运行docker直接退出，状态显示“Exited (139) 11 seconds ago”，logs为空

### ISSUE THREAD

**Issue by Conmi-WhiteJoker** [alibaba/canal#4661]
## Question
运行的命令行：
./run.sh -e canal.instance.master.address=172.16.2.127:3306 \
         -e canal.instance.dbUsername=root \
         -e canal.instance.dbPassword=root \
         -e canal.instance.connectionCharset=UTF-8 \
         -e canal.instance.tsdb.enable=true \
         -e canal.instance.gtidon=false \
         -e canal.instance.filter.regex=.*\\\..*

docker运行的命令：
docker run -d -it -h 0 -e canal.instance.master.address=172.16.2.127:3306 -e canal.instance.dbUsername=root -e canal.instance.dbPassword=root -e canal.instance.connectionCharset=UTF-8 -e canal.instance.tsdb.enable=true -e canal.instance.gtidon=false -e canal.instance.filter.regex=.*\..* --name=canal-server --net=host -m 4096m canal/canal-server

直接使用bash好像也不能运行，是1.1.6的镜像问题吗？

**Comment by Conmi-WhiteJoker** [comment]
测试了，只认centos，debian下无法运行~

**Comment by HeavenTonight** [comment]
我重新编写dockerfile构建了一个镜像，在debian11上运行正常，镜像大小160M,需要可以找我

**Comment by agapple** [comment]
> 我重新编写dockerfile构建了一个镜像，在debian11上运行正常，镜像大小160M,需要可以找我

可以提交一个PR给我

**Comment by laizhaoxue** [comment]
> 我重新编写dockerfile构建了一个镜像，在debian11上运行正常，镜像大小160M,需要可以找我

windows 下 docker desktop可以运行不
