### ISSUE TITLE
rowChange.getSql()无法获取dml的sql

### ISSUE THREAD

**Issue by wangpengshao** [alibaba/canal#4662]
## Question

![image](https://user-images.githubusercontent.com/53423907/225835021-6b09ec51-9eef-4651-90a7-80ac41200014.png)
![image](https://user-images.githubusercontent.com/53423907/225835061-dbf16372-b6b6-4128-939b-2d124e543baf.png)
rowChange.getSql()无法获取dml的sql，是使用方法有问题吗，还是需要修改哪些配置项。或者说canal本身能支持获取dml的sql语句的吗

**Comment by agapple** [comment]
row模式，针对DML默认没有SQL语句
