### ISSUE TITLE
Canal 支持 mysql8 的 binlog 压缩特性嘛？

### ISSUE THREAD

**Issue by MengXiangDing** [alibaba/canal#4663]
MySQL 8.0.20 版本增加了binlog日志事务压缩功能，请问 Canal 适配过这个特性嘛？

**Comment by mxd-321** [comment]
@agapple 大佬，请问 Canal 目前支持这个嘛？

**Comment by mxd-321** [comment]
https://github.com/alibaba/canal/issues/4388

应该是不支持

<img width="946" alt="image" src="https://user-images.githubusercontent.com/73006046/226235901-5ece5cfe-ad5a-4761-9a9d-d1009e372d9c.png">

**Comment by agapple** [comment]
不会因为binlog压缩而导致解析失败，但目前没有uncompress对应的binlog，有需求的话我可以支持下

相关需求，提问题到 #4388
