### ISSUE TITLE
canal.instance.filter.regex不生效

### ISSUE THREAD

**Issue by wangpengshao** [alibaba/canal#4664]
为了获取sql语句，将配置项binlog-rows-query-log-events设置为ture后，如下
binlog-rows-query-log-events = true， 之后就会出现过滤项canal.instance.filter.regex不生效，这个问题怎么解决呢

**Comment by agapple** [comment]
默认没有对rows-query-log-events进行filter过滤，没有完整解析

**Comment by DK-dzz** [comment]
请问一下，binlog-rows-query-log-events = true，导致canal.instance.filter.regex不生效的canal版本是多少？
