### ISSUE TITLE
关于时序表结构的疑问

### ISSUE THREAD

**Issue by zhuchao941** [alibaba/canal#4671]
## Question

https://github.com/alibaba/canal/wiki/TableMetaTSDB

我看了下时序表结构的设计，有个疑问
为什么是做了定时的checkpoint生成？我感觉每次ddl变更的时候做一次checkpoint的生成不是更好吗？ @agapple

**Comment by agapple** [comment]
ddl变更有可能会挺频繁的，特别是批量建表，每次都做checkpoint没必要
