### ISSUE TITLE
MySQL binlog_format 为 STATEMENT 能使用canal吗？

### ISSUE THREAD

**Issue by zhugw** [alibaba/canal#4674]
## Question

需求：
     有一个话题表（topic）同时有一个 话题文章关联表 （topic_relation）如果话题本身有更新或者话题关联关系有更新 如新增文章、删除文章 需通知下游重新生成该话题的静态页

生产环境MySQL (5.6.32)
binlog_format,STATEMENT

> 对于自建 MySQL , 需要先开启 Binlog 写入功能，配置 binlog-format 为 ROW 模式

binlog_format 为 STATEMENT 能使用canal吗？

**Comment by agapple** [comment]
canal可以支持statement模式
