### ISSUE TITLE
CanalServerException: destination:example1 should start first (服务端如何确认实例启动)

### ISSUE THREAD

**Issue by cloud-zhao** [alibaba/canal#468]
开启auto.scan 之后在 conf下增加了一个新实例example1 在日志可以可以看见

2017-12-29 14:24:01.056 [canal-instance-scan-0] INFO  c.a.o.canal.deployer.monitor.SpringInstanceConfigMonitor - auto notify start example1 successful.

日志说明新加的实例启动了。

但是客户端访问和服务端纪录的日志都只有

exception=com.alibaba.otter.canal.server.exception.CanalServerException: destination:example1 should start first

这种异常。很奇怪的是在服务端没有任何关于example1的日志消息产生，example是能正常产生日志的。

所以想咨询一下如何确定实例到底启动没有，既没有日志输出，也没有服务异常抛出，只有访问时才会产生一条 should start first的话，很难让人去跟踪问题所在。

**Comment by agapple** [comment]
你把lazy模式给设置为false

**Comment by cloud-zhao** [comment]
开启instance自动扫描
如果配置为true，canal.conf.dir目录下的instance配置变化会自动触发：
a. instance目录新增： 触发instance配置载入，lazy为true时则自动启动
b. instance目录删除：卸载对应instance配置，如已启动则进行关闭
c. instance.properties文件变化：reload instance配置，如已启动自动进行重启操作	
我是按这个提示把lazy 设置为 true的。原本默认就是false

**Comment by agapple** [comment]
我印象中lazy=false是默认值，lazy=true时会在第一次客户端访问时才会去初始化

**Comment by cloud-zhao** [comment]
哦，谢谢

**Comment by wwb-ruruo** [comment]
> 你把lazy模式给设置为false

软用没有

**Comment by ListenQ** [comment]
> 你把lazy模式给设置为false

设置了，但是依旧还是会报这个错误
