### ISSUE TITLE
Kakfa压缩配置，如何知道启动压缩了

### ISSUE THREAD

**Issue by JFishLover** [alibaba/canal#4684]
## conf/canal.properties里面的压缩参数

![image](https://user-images.githubusercontent.com/37490944/232361734-60001837-1412-47b6-be6e-099070d38105.png)
我的canal版本是1.15，因为发送的消息比较大，所以想在producer进行压缩，配置文件有kafka.compression.type这个参数，的配置如上图所示，但是当发送消息很大的时候，仍然报错，怎么知道我有没有成功压缩呢，或者怎么知道压缩前后的消息大小呢？求大神指导

**Comment by agapple** [comment]
可以调低canal.mq.canalBatchSize大小，减少每次发送MQ的包大小
