### ISSUE TITLE
jdk1.8版本 canal-v1.1.6 服务器启动后，管理端界面Server管理菜单中 canal_server 状态显示断开

### ISSUE THREAD

**Issue by lwx57280** [alibaba/canal#4690]
- [x] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment
* centos7
* canal -v1.1.6
* mysql -v8.0

### 以下是我canal-deployer 中对应本地配置文件
``` properties
# register ip
canal.register.ip = 192.168.11.39

# canal admin config
canal.admin.manager = 127.0.0.1:8089
canal.admin.port = 11110
canal.admin.user = admin
canal.admin.passwd = 4ACFE3202A5FF5CF467898FC58AAB1D615029441
# admin auto register
canal.admin.register.auto = true
canal.admin.register.cluster =
canal.admin.register.name =
                                                                   
```

<img width="372" alt="20230421114222" src="https://user-images.githubusercontent.com/33561119/233535988-39b5158b-9b55-4a22-8588-d9b97ef67dc0.png">

### Issue Description

jdk1.8 canal-v1.1.6 服务器启动后，管理界面Server管理菜单种 canal_server 状态显示断开
日志有报错，Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer; 

我尝试将jdk升级到jdk17版本后无法启动canal服务，当我再次将jdk改回原来的jdk1.8版后尝试再次启动服务发现此时jdk1.8 版本再也无法启动canal服务

请描述搭建环境时使用jdk版本与canal 版本对应关系

### Steps to reproduce

管理端界面如下：

<img width="856" alt="20230421115353" src="https://user-images.githubusercontent.com/33561119/233537121-e1a60532-a55c-44c1-96a4-a9393023bcbd.png">

Server管理列表页面，滚动条向右移动，点击操作查看日志报错：
Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer;

<img width="713" alt="20230421115522" src="https://user-images.githubusercontent.com/33561119/233537407-7d41b6fa-ddb6-4a88-8766-b7f3b1764b5e.png">

### Expected behaviour
期望管理界面状态显示启动，不报错

### Actual behaviour
实际页面Server管理、instance管理服务状态都显示断开，两处页面日志查看报错，不确定该使用jdk哪一个版本搭建canal环境

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by hnwkz** [comment]
大佬你解决了没？我碰到相同问题了，我怀疑是JDK的问题，想着要不要canal降版本

**Comment by guojianming** [comment]
我也一样，你们是怎么解决的

**Comment by DK-dzz** [comment]
遇到同样问题，测试更换到JDK15，执行启动脚本可刷新admin.pid文件，但依旧无法启动且也不打印日志。

**Comment by feifei888888** [comment]
同样遇到这个问题。从1.1.5升级到1.1.6     server是1.1.6  admin是1.1.5能正常显示启动， admin换成1.1.6后server显示断开。我的jdk1.8

**Comment by hnwkz** [comment]
我改成jdk17，问题解决了

**Comment by yuanpei2018** [comment]
我的改成jdk11解决了

**Comment by Im-SAMW** [comment]
各种坑，不升级了，Fuck！

**Comment by liuyunyun123** [comment]
看评论，先改成17，压根就启动不了，然后改成11，成功启动。1.1.6canal-admin
![image](https://github.com/alibaba/canal/assets/30256759/fc6b653e-6e4c-460b-8169-ee9e68efe565)

**Comment by agapple** [comment]
看上去是jdk8的兼容性问题，已有问题再跟踪，重复的问题我先关闭 #4358

**Comment by lwx57280** [comment]
> 大佬你解决了没？我碰到相同问题了，我怀疑是JDK的问题，想着要不要canal降版本

没有解决，后来没管了

**Comment by lwx57280** [comment]
暂未解决

> * [x]  I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.[x]  I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.
> 
> ### environment
> * centos7
> * canal -v1.1.6
> * mysql -v8.0
> 
> ### 以下是我canal-deployer 中对应本地配置文件
> # register ip
> canal.register.ip = 192.168.11.39
> 
> # canal admin config
> canal.admin.manager = 127.0.0.1:8089
> canal.admin.port = 11110
> canal.admin.user = admin
> canal.admin.passwd = 4ACFE3202A5FF5CF467898FC58AAB1D615029441
> # admin auto register
> canal.admin.register.auto = true
> canal.admin.register.cluster =
> canal.admin.register.name =
>                                                                    
> <img alt="20230421114222" width="372" src="https://user-images.githubusercontent.com/33561119/233535988-39b5158b-9b55-4a22-8588-d9b97ef67dc0.png">
> 
> ### Issue Description
> jdk1.8 canal-v1.1.6 服务器启动后，管理界面Server管理菜单种 canal_server 状态显示断开 日志有报错，Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer;
> 
> 我尝试将jdk升级到jdk17版本后无法启动canal服务，当我再次将jdk改回原来的jdk1.8版后尝试再次启动服务发现此时jdk1.8 版本再也无法启动canal服务
> 
> 请描述搭建环境时使用jdk版本与canal 版本对应关系
> 
> ### Steps to reproduce
> 管理端界面如下：
> 
> <img alt="20230421115353" width="856" src="https://user-images.githubusercontent.com/33561119/233537121-e1a60532-a55c-44c1-96a4-a9393023bcbd.png">
> 
> Server管理列表页面，滚动条向右移动，点击操作查看日志报错： Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer;
> 
> <img alt="20230421115522" width="713" src="https://user-images.githubusercontent.com/33561119/233537407-7d41b6fa-ddb6-4a88-8766-b7f3b1764b5e.png">
> 
> ### Expected behaviour
> 期望管理界面状态显示启动，不报错
> 
> ### Actual behaviour
> 实际页面Server管理、instance管理服务状态都显示断开，两处页面日志查看报错，不确定该使用jdk哪一个版本搭建canal环境
> 
> If there is an exception, please attach the exception trace:
> 
> ```
> Just put your stack trace here!
> ```

**Comment by keepsty** [comment]
mark，我们也是这个版本

**Comment by chanchinho911** [comment]
遇到类似的问题，结果是发现编译的时候用的jdk11，启动用的jdk8导致出问题，可以参考一下
