### ISSUE TITLE
canal显示connection reset

### ISSUE THREAD

**Issue by Atox03** [alibaba/canal#4696]
canal运行几个月了，一直正常，突然一段时间抛出异常显示connection reset，然后数据一直没有监听到，报错日志如下：
![18a8fca015d7f273a412af3c1508d108](https://user-images.githubusercontent.com/125858666/234541243-e0097a33-2f42-4c27-9a40-e7a501aa0cd3.png)

**Comment by agapple** [comment]
一般是数据库端主动断开连接，比如重启或者网络异常，这种默认会自动重试
