### ISSUE TITLE
canal 同步数据到sharing-proxy代理库，通过代理库的自定义分表规则保存到不同的分表中

### ISSUE THREAD

**Issue by Pluto-Charon** [alibaba/canal#4700]
## Question

canal adapter 初始化获取表结构时 SELECT * FROM targetTable where 1=2
该sql是没有分片键的，导致一直报错： Not allow DML operation without sharding conditions.
如何解决该问题呢？

**Comment by agapple** [comment]
这报错意思是指没带拆分条件
