### ISSUE TITLE
canal.client 升级1.1.6 没有 com.alibaba.otter.canal.protocol 相关类

### ISSUE THREAD

**Issue by cnn007** [alibaba/canal#4702]
## Question

   <dependency>
            <groupId>com.alibaba.otter</groupId>
            <artifactId>canal.client</artifactId>
            <version>1.1.4</version>
        </dependency>

从 1.1.4 版本升级 到 1.1.6 版本
代码报错没有 protocol 包
```
import com.alibaba.otter.canal.protocol.CanalEntry;
import com.alibaba.otter.canal.protocol.Message;
```

v.1.1.4 版本
![image](https://user-images.githubusercontent.com/13449400/236611066-21d693d8-fc2c-4811-8e1e-90e74a40d9a3.png)

v1.1.6版本
![image](https://user-images.githubusercontent.com/13449400/236611026-ad6ad55a-70a6-4789-b098-b3196645e526.png)

**Comment by knightdreams6** [comment]
<dependency>
      <groupId>com.alibaba.otter</groupId>
      <artifactId>canal.protocol</artifactId>
      <version>1.1.6</version>
    </dependency>
