### ISSUE TITLE
写入MQ时候增加限流功能

### ISSUE THREAD

**Issue by arkblue** [alibaba/canal#4708]
## How it could be?

购买的云产品rocketmq有上限TPS，平时binlog的变更TPS小于rocketMQ的上线TPS；但是当遇到批量数据订正、或者批量插入时候，短时间产生大量binlog，写入rocketmq的TPS也会急剧增加（平时值的 10～100倍）；为了极端毛刺场景购买更高规格的Rocketmq也不划算，同时下游业务也能接受极端情况的延迟。

另外，由于写入rocketmq超过的上限，会引起broker的流控，导致producer触发退避策略，但是退避后重试时TPS仍会超过rocketmq的上限，一直写入rocketmq失败。

在小公司，往往申请一个Rocketmq实例，共享给多个生产者（canal和业务系统），为了避免broker流控引起生产者之间相互影响，canal写入mq时候增加流控功能是一个比较普遍的需求。

**Comment by agapple** [comment]
可以考虑提交一个PR给我
