### ISSUE TITLE
请教：关于canal客户端报com.alibaba.otter.canal.protocol.exception.CanalClientException: java.io.IOException: end of stream when reading header这个错误

### ISSUE THREAD

**Issue by zhangmy6666** [alibaba/canal#471]
while (true) {
            Message message = connector.getWithoutAck(1); // 获取指定数量的数据
            long batchId = message.getId();
            int size = message.getEntries().size();
            if (batchId == -1 || size == 0) {
                System.out.println("empty count : " + emptyCount);
            } else {
                System.out.printf("message[batchId=%s,size=%s] \n", batchId, size);
            }
            try {
                Thread.sleep(40000);
            } catch (InterruptedException e) {
            }
            connector.ack(batchId); // 提交确认
        }
上面我取完数据，sleep个40秒，canal连接就会断掉，报标题说明的错，
但是我如果只是Thread.sleep(5000);，sleep个5秒之类的，不会有问题。。求指导这是啥原因。
基于最新版本1.0.25。

**Comment by shuhaoc** [comment]
遇到过同样问题，从日志上看是canal server主动关闭了连接，坐等权威回答

**Comment by agapple** [comment]
SimpleCanalConnector里设置的soTimeout会传递到server端进行超时管理，默认60秒

**Comment by mjjian0** [comment]
我也遇见了这个问题，等官方回应。

**Comment by mjjian0** [comment]
这个soTimeout时间的意思是，着这个时间段内，如果client没有处理完这批数据，server会终端client吗？

**Comment by mjjian0** [comment]
这个soTimeout时间的意思是，着这个时间段内，如果client没有处理完这批数据，server会终端client吗？

**Comment by mjjian0** [comment]
这个soTimeout时间的意思是，着这个时间段内，如果client没有处理完这批数据，server会终端client吗？我程序里client每批次取10000条数据，处理时间达到1分钟以上，然后就导致这个异常，而且这10000条数据会重复处理，然后每次都是1分钟以上，就循环报这个异常。把soTimeout改到120秒，就ok了。

**Comment by haiboyang** [comment]
这个问题怎么解决呢

**Comment by agapple** [comment]
https://github.com/alibaba/canal/issues/640，关注一下这个

**Comment by jianghaibolxy** [comment]
> [https://github.com/alibaba/canal/issues/640，关注一下这个](https://github.com/alibaba/canal/issues/640%EF%BC%8C%E5%85%B3%E6%B3%A8%E4%B8%80%E4%B8%8B%E8%BF%99%E4%B8%AA)

你好，这个链接没有了，请问这个问题该怎么处理

**Comment by lbx6z** [comment]
> > [https://github.com/alibaba/canal/issues/640，关注一下这个](https://github.com/alibaba/canal/issues/640%EF%BC%8C%E5%85%B3%E6%B3%A8%E4%B8%80%E4%B8%8B%E8%BF%99%E4%B8%AA)
> 
> 你好，这个链接没有了，请问这个问题该怎么处理

https://github.com/alibaba/canal/issues/640
