### ISSUE TITLE
重置消费位点binlog消费跟不上，修改资源配置不生效，如何配置资源？

### ISSUE THREAD

**Issue by Allen-Cao** [alibaba/canal#4712]
背景：第二天发现数据出现问题，需要重置binlog位点至当日凌晨1点，但由于凌晨数据量庞大，导致canal消费速度甚至不及正常时间速度。
问题：
消费binlog速度跟不上，于是我设置三个配置：
1、jvm ：startup.sh的参数 -server -Xms8192m -Xmx12288m -Xmn4096m 后面的为默认值
2、canal.instance.memory.buffer.size = 由262144扩大至1048576
3、network相关参数未修改

机器配置：32 Core * 128G
使用情况：负载0.6   内存使用4.5g，资源完全没有利用起来
求助：binlog消费依旧跟不上，为什么不使用xms的内存？怎么配置能够使资源得到充分的利用？

提问：
1、为什么不使用xms的内存？
2、资源配置是否有最优方案或建议，怎么配置能够使资源得到充分的利用？
2、binlog消费跟不上与什么原因有关？

以上，希望得到大神的解答，thanks~

**Comment by Allen-Cao** [comment]
补充：过程中store remain events和store remain mem基本接近0，应该是完全利用起来了

**Comment by agapple** [comment]
store remain events是指ringbuffer中堆积的binlog，看上去你的瓶颈是在源端binlog的生成或者解析上

你检查一下监控的delay，详细文档：https://github.com/alibaba/canal/wiki/Prometheus-QuickStart
