### ISSUE TITLE
canal.client 1.1.6 Message包结构的问题

### ISSUE THREAD

**Issue by A-linna** [alibaba/canal#4714]
当我使用canalclient1.1.6版本时没有Message类的包路径好像不太对
<dependency>
            <groupId>com.alibaba.otter</groupId>
            <artifactId>canal.client</artifactId>
            <version>1.1.6</version>
        </dependency>

<img width="1170" alt="image" src="https://github.com/alibaba/canal/assets/66893381/928a2bbe-ad49-422f-8e18-c4cb8c2c0f8f">

**Comment by yuanpei2018** [comment]
这个没问题，protocol被单独拆分出来作为一个module了，多加个依赖就行了

**Comment by it-xiaomi** [comment]
<dependency>
			<groupId>com.alibaba.otter</groupId>
			<artifactId>canal.client</artifactId>
			<version>1.1.6</version>
		</dependency>
		<dependency>
			<groupId>com.alibaba.otter</groupId>
			<artifactId>canal.common</artifactId>
			<version>1.1.6</version>
		</dependency>
		<dependency>
			<groupId>com.alibaba.otter</groupId>
			<artifactId>canal.protocol</artifactId>
			<version>1.1.6</version>
		</dependency>

**Comment by it-xiaomi** [comment]
<dependency>
			<groupId>com.alibaba.otter</groupId>
			<artifactId>canal.client</artifactId>
			<version>1.1.6</version>
		</dependency>
		<dependency>
			<groupId>com.alibaba.otter</groupId>
			<artifactId>canal.common</artifactId>
			<version>1.1.6</version>
		</dependency>
		<dependency>
			<groupId>com.alibaba.otter</groupId>
			<artifactId>canal.protocol</artifactId>
			<version>1.1.6</version>
		</dependency>

**Comment by it-xiaomi** [comment]
`<dependency>
			<groupId>com.alibaba.otter</groupId>
			<artifactId>canal.client</artifactId>
			<version>1.1.6</version>
		</dependency>
		<dependency>
			<groupId>com.alibaba.otter</groupId>
			<artifactId>canal.common</artifactId>
			<version>1.1.6</version>
		</dependency>
		<dependency>
			<groupId>com.alibaba.otter</groupId>
			<artifactId>canal.protocol</artifactId>
			<version>1.1.6</version>
		</dependency>`

**Comment by it-xiaomi** [comment]
```java
<dependency>
			<groupId>com.alibaba.otter</groupId>
			<artifactId>canal.client</artifactId>
			<version>1.1.6</version>
		</dependency>
		<dependency>
			<groupId>com.alibaba.otter</groupId>
			<artifactId>canal.common</artifactId>
			<version>1.1.6</version>
		</dependency>
		<dependency>
			<groupId>com.alibaba.otter</groupId>
			<artifactId>canal.protocol</artifactId>
			<version>1.1.6</version>
		</dependency>
```

**Comment by agapple** [comment]
LS正解
