### ISSUE TITLE
Could not find artifact com.alibaba.otter:connector.tcp:jar:jar-with-dependencies:1.1.7-SNAPSHOT in sonatype (https://oss.sonatype.org/content/repositories/snapshots)

### ISSUE THREAD

**Issue by Holinc19** [alibaba/canal#4737]
[INFO] canal client adapter launcher module for otter 1.1.7-SNAPSHOT FAILURE [ 41.393 s]
[INFO] canal client adapter kudu module for otter 1.1.7-SNAPSHOT SUCCESS [  5.796 s]
[INFO] canal client adapter phoenix module for otter 1.1.7-SNAPSHOT SUCCESS [ 25.166 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:16 min (Wall Clock)
[INFO] Finished at: 2023-05-29T14:08:11+08:00
[INFO] Final Memory: 284M/3476M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project client-adapter.launcher: Could not resolve dependencies for project com.alibaba.otter:client-adapter.launcher:jar:1.1.7-SNAPSHOT: The following artifacts could not be resolved: com.alibaba.otter:connector.tcp:jar:jar-with-dependencies:1.1.7-SNAPSHOT, com.alibaba.otter:connector.pulsarmq:jar:jar-with-dependencies:1.1.7-SNAPSHOT: Could not find artifact com.alibaba.otter:connector.tcp:jar:jar-with-dependencies:1.1.7-SNAPSHOT in sonatype (https://oss.sonatype.org/content/repositories/snapshots) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :client-adapter.launcher

Process finished with exit code 1

**Comment by agapple** [comment]
mvn clean install eclipse:eclipse
