### ISSUE TITLE
用了一段时间正常，突然就报错找不到表CanalParseException: com.taobao.tddl.dbsync.binlog.exception.TableIdNotFoundException: not found tableId:1699

### ISSUE THREAD

**Issue by leonidasFLQ** [alibaba/canal#4744]
##
CanalParseException: com.taobao.tddl.dbsync.binlog.exception.TableIdNotFoundException: not found tableId:1699

**Comment by agapple** [comment]
你链接的mysql是啥版本？TableId找不到一般是初次启动时的位点处于事务中
