### ISSUE TITLE
rocketmq acl配置

### ISSUE THREAD

**Issue by i-xiaobao** [alibaba/canal#4745]
## Question

我在rocketmq中开启了ACL权限控制，配置了rocketmq访问的用户名和密码。可是canal没有关于rocketmq用户名和密码的配置；还是说我没有找到？生产环境mq肯定需要用户名和密码来访问的

**Comment by agapple** [comment]
支持aliyun模式的ak/sk

```
canal.aliyun.accessKey =
canal.aliyun.secretKey =
```
