### ISSUE TITLE
canal怎么设置rocketMQ消息批次大小?

### ISSUE THREAD

**Issue by HuangWenTao-H** [alibaba/canal#4751]
## Question

参数：canal.mq.canalBatchSize = 1
调整到1，但是消息体还是很大，大概17KB左右，也试了canal.instance.memory.buffer.memunit参数，还是没效果，求大佬解答

**Comment by skboy** [comment]
同问

**Comment by agapple** [comment]
没办法严格控制发送给MQ的消息大小，而是通过binlog记录数来控制，一个binlog有可能带了大字段而超大

**Comment by guwenxiang** [comment]
@agapple 通过binlog记录数来控制是指哪个配置,不是canal.mq.canalBatchSize这个吗
