### ISSUE TITLE
能否支持通过字段值来过滤

### ISSUE THREAD

**Issue by Curtaingit** [alibaba/canal#4753]
## Why you need it?
在不同的场景下，表记录都会更新，但部分核心业务处理导致部分字段更新需要触发同步，非核心业务处理 可以不必触发同步

## How it could be?

增加对表字段的配置支持
canal.instance.filter.regex=table_name.column_name=value

**Comment by agapple** [comment]
支持字段过滤：
```
canal.instance.filter.field
canal.instance.filter.black.field
```

**Comment by DemoLiang** [comment]
> ## Why you need it?
> 在不同的场景下，表记录都会更新，但部分核心业务处理导致部分字段更新需要触发同步，非核心业务处理 可以不必触发同步
> 
> ## How it could be?
> 增加对表字段的配置支持 canal.instance.filter.regex=table_name.column_name=value
> 
> ## Other related information

这个问题解决了吗

**Comment by Curtaingit** [comment]
> > ## Why you need it?
> > 在不同的场景下，表记录都会更新，但部分核心业务处理导致部分字段更新需要触发同步，非核心业务处理 可以不必触发同步
> > ## How it could be?
> > 增加对表字段的配置支持 canal.instance.filter.regex=table_name.column_name=value
> > ## Other related information
> 
> 这个问题解决了吗

canal支持的是字段过滤。 不支持对字段的值过滤    后面我通过在程序中增加额外判断来解决的。
