### ISSUE TITLE
多个canal的java sdk客户端连接同一个canal可行吗？

### ISSUE THREAD

**Issue by HuangWenTao-H** [alibaba/canal#4755]
## Question

我尝试了，批量修改数据库时多个客户端同时处理会出现提交的偏移量混乱，（com.alibaba.otter.canal.meta.exception.CanalMetaManagerException: batchId:1148 is not the firstly:1147）
想请问各位大佬，这种场景有解决方案吗？

**Comment by agapple** [comment]
不可以同时多客户端订阅
