### ISSUE TITLE
数据不一致

### ISSUE THREAD

**Issue by NoClient** [alibaba/canal#4759]
## Question

数据库修改数据171238条，
Canal从Binlog读取数据到RabbitMQ中只有20000多条，十万条数据不见了。
![image](https://github.com/alibaba/canal/assets/52952291/1c8aee31-d0ce-42fa-9c21-505719868da9)
![image](https://github.com/alibaba/canal/assets/52952291/d3ea4087-9ea6-4271-8fc4-5c5785f465a1)

**Comment by cccdl** [comment]
我今天发现了一个问题，实际写入3条，但是监听只有1条

**Comment by NoClient** [comment]
这个我已找到原因，队列中的一条数据是binlog中的一条数据，记录对应binlog文件内容中数据的起始位置和结束位置，binlog文件中这段内容，对应数据表可能是多条数据操作，例如下图：一条binlog日志，记录数据表4条数据修改操作。
对应命令：show binlog events limit 5,10

![16867238036143](https://github.com/alibaba/canal/assets/52952291/45af959a-981f-4283-b6c1-ae8cc5e62e0a)

**Comment by NoClient** [comment]
已解决
