### ISSUE TITLE
canal-admin对于canal-高可用的影响

### ISSUE THREAD

**Issue by dengzhihang** [alibaba/canal#4779]
我做了一个测试，想验证下canal-admin进程挂掉对canal的影响，结果我发现当canal-admin进程不存在时，我将主消费节点canal服务停掉后，HA失效，消费无法进行了，就证明没有canal-admin,  canal自身高可用是失效的。 等我把canal-admin和主消费节点canal服务重新恢复时，canal消费instance状态还是停止状态，然后我重启了集群另一个节点的canal服务，消费才恢复。我想咨询几个问题
1 这种结果是不是符合预期，为什么需要重启集群另一个节点canal服务才会恢复消费
2 canal-admin本身能不能部署多个服务，防止这种情况的发生

**Comment by agapple** [comment]
canal-admin异常时，canal-server如果不重启的话还能正常工作

canal-server节点重启，HA切换需要通过canal-admin配置信息，如果此时canal-admin异常会导致启动失败
