### ISSUE TITLE
canal可以按需过滤binlog数据吗？cache刷新场景

### ISSUE THREAD

**Issue by soongp** [alibaba/canal#4785]
## Question

1.canal可以按需过滤binlog数据吗？cache刷新场景（是否有自己的filter？）
2.canal是否可以直接将binlog解析成相应的redis命令，直接传给redis服务。保证更新操作的强实时性，强一致性？

**Comment by agapple** [comment]
不支持直接同步redis，需要业务对接binlog消息后自己刷新
