### ISSUE TITLE
canal是否只支持mysql数据库？信创数据库goldenDB能支持吗？

### ISSUE THREAD

**Issue by fangjiangz** [alibaba/canal#4801]
由于客户需要使用国产信创的数据库，我们将原来的mysql数据库改成了goldenDB。应用层访问数据库的代码基本不用做什么修改。请问，canal支持将goldenDB中的增量数据同步到elasticsearch中吗？谢谢

**Comment by agapple** [comment]
大概率是不支持，需要goldenDB严格实现兼容mysql binlog格式才行

**Comment by AarZK** [comment]
可以支持的，GoldenDB 数据节点是完全兼容 binlog 格式的，只是 GoldenDB 通常对应用提供的服务端口并不直接与数据节点交互，对接 canal 时配置数据节点的 ip 和端口即可
