### ISSUE TITLE
canal_instance_client_bytes无监控数据

### ISSUE THREAD

**Issue by nondevops** [alibaba/canal#4803]
## Question

当前我们用的canal版本为1.1.6，使用prometheus采集了canal相关的监控数据，其中有一个指标canal_instance_client_bytes 是没有任何数据的，但官方文档介绍是可以被采集及有数据输出的。在metrics页面上搜索这个关键字“canal_instance_client_bytes“，只出现了2次关键字的位置，它的结构如截图：
<img width="422" alt="833edf3720917e1c391bf72a481bad2" src="https://github.com/alibaba/canal/assets/12181410/d27443a2-94a8-463d-a703-117b6ae41f87">

这种没有数据的监控对象，如何让这个指标产生数据呢？

**Comment by agapple** [comment]
这个参数是针对tcp模式，由client消费才会纳入统计，如果是MQ模式是不会统计
