### ISSUE TITLE
canal报表中dump和sink的block是指他现在是被其他步骤阻塞住了，还是指他自己繁忙程度

### ISSUE THREAD

**Issue by RekiOwl** [alibaba/canal#4809]
canal报表中dump和sink的block是指他现在是被其他步骤阻塞住了，还是指他自己繁忙程度

**Comment by agapple** [comment]
canal中引入了ringbuffer来做内存缓冲，blocking一般是因为缓冲区空或者满导致

参考文档：https://github.com/alibaba/canal/wiki/Prometheus-QuickStart
