### ISSUE TITLE
canal.instance.filter.regex 问题

### ISSUE THREAD

**Issue by elylon1101** [alibaba/canal#4814]
版本：1.1.6
1. 启动deployer和admin。然后在admin上面新建instance并配置canal.instance.filter.regex=.*\\..*
2. 启动instance
3. 启动canal-nodejs，启动时删除了连接信息中的filter
4. 测试插入数据一切正常
5. 进入admin修改instance的canal.instance.filter.regex=test\\.user并保存重启
6. 启动canal-nodejs，启动时删除了连接信息中的filter
7.  测试插入数据发现不能过滤
8. 打开deployer中conf对应的meta.dat文件，发现里面的filter还是.*\\..*

第二次测试，按照上面的流程在一开始就配置canal.instance.filter.regex=test\\.user启动测试可以正常过滤，然后再在admin里面去修改为其它的规则发现也不能过滤，同时对应的meta.dat中的filter还是一开始配置的test\\.user

**Comment by agapple** [comment]
```
test\\.user
```
