### ISSUE TITLE
建议新增ReportSlave消息

### ISSUE THREAD

**Issue by zhibinliu** [alibaba/canal#483]
现在连上Mysql时，连接成功后就直接RequestDump了，所以在Mysql上敲show slave hosts，看不到当前这条Canal连接。虽然不影响数据同步，但对于强迫症来说，好不舒服。

解决方案是在RequestDump之前发一条ReportSlave消息上报自己，再收回一条OK消息，就可以了。

消息内容代码如下：
[RegisterSlaveCommandPacket.java.txt](https://github.com/alibaba/canal/files/1610961/RegisterSlaveCommandPacket.java.txt)

然后在MysqlConnection.java中增加如下函数，在dump()中调用就好了。
    private void sendRegisterSlave() throws IOException {
    	RegisterSlaveCommandPacket cmd = new RegisterSlaveCommandPacket();
    	cmd.setReport_host(canalHost);
    	cmd.setReport_port(canalPort);
    	cmd.setReport_user(connector.getUsername());
    	cmd.setServerid(slaveId);
    	
    	byte[] cmdBody = cmd.toBytes();

        logger.info("Register slave {}", cmd);

        HeaderPacket header = new HeaderPacket();
        header.setPacketBodyLength(cmdBody.length);
        header.setPacketSequenceNumber((byte) 0x00);
        PacketManager.write(connector.getChannel(), new ByteBuffer[] { ByteBuffer.wrap(header.toBytes()),
                ByteBuffer.wrap(cmdBody) });
        
        ByteBuffer dest = ByteBuffer.allocate(1024);
        connector.getChannel().read(dest);

    }

其中的变量我是通过改Spring的xml，从配置文件中拿的。

**Comment by agapple** [comment]
挺好的优化，方便提交一个代码PR给我？

**Comment by JasonHuangHuster** [comment]
最新的release 没有带出这个特性吗？我下载了尝试，发现show slave hosts 仍然没有发现canal server信息。

**Comment by agapple** [comment]
26的测试版本应该有了

**Comment by JasonHuangHuster** [comment]
亲测 最新版1.10中没有噢。

**Comment by agapple** [comment]
只有在进入dump阶段才会有show slave hosts，针对位点定位阶段没有
