### ISSUE TITLE
Canal Kafka RocketMQ QuickStart中canal.mq.dynamicTopicPartitionNum参数能否标明下1.1.6开始？

### ISSUE THREAD

**Issue by zangjietutu** [alibaba/canal#4831]
### environment

* canal version 1.1.5

### Issue Description
在浏览 https://github.com/alibaba/canal/wiki/Canal-Kafka-RocketMQ-QuickStart 的时候发现 [mq相关参数说明 (>=1.1.5版本)](https://github.com/alibaba/canal/wiki/Canal-Kafka-RocketMQ-QuickStart#mq%E7%9B%B8%E5%85%B3%E5%8F%82%E6%95%B0%E8%AF%B4%E6%98%8E-115%E7%89%88%E6%9C%AC)的表格中 canal.mq.dynamicTopicPartitionNum 其实不是从1.1.5开始的，放在这边有点误导，麻烦可以在 后边增加个备注 这个是从1.1.6开始的。
<img width="1160" alt="image" src="https://github.com/alibaba/canal/assets/53146865/2c5d2521-f89b-4056-8ecb-2309ac933870">

**Comment by agapple** [comment]
https://github.com/alibaba/canal/blob/canal-1.1.5/deployer/src/main/resources/example/instance.properties，这个参数确认是1.1.5引入的
