### ISSUE TITLE
SAE 部署canal-server频繁 Connection reset by peer

### ISSUE THREAD

**Issue by lixocg** [alibaba/canal#4833]
SAE 部署canal-server，指定loadbalance到canal-server，频繁报Connection reset by peer异常，猜测是SAE是loadbalance检测报出来的，请问有什么办法能解决这个异常。
![image](https://github.com/alibaba/canal/assets/13638878/a87d6574-e1d9-49ff-815b-7d5c802bd859)

**Comment by zangjietutu** [comment]
解决了吗 @lixocg

**Comment by lixocg** [comment]
> 解决了吗 @lixocg

换成DTS了
