### ISSUE TITLE
MQ消息发送性能优化对多实例多topic是否有用

### ISSUE THREAD

**Issue by xiaoyu-x** [alibaba/canal#4838]
## Question

针对 MQ消息发送性能优化 #2258 优化，发送线程池和构造消息线程池是所有实例公用的，如果存在多实例和多topic，线程池资源被某个实例独占了，那么其他的实例的消息发送是不是就会一直阻塞。

**Comment by agapple** [comment]
多线程模式还是会共享一些资源，如果多topic可以适当调大一下并发数来提升吞吐量
