### ISSUE TITLE
canal重发数据导致乱序

### ISSUE THREAD

**Issue by TonyHowardPark** [alibaba/canal#4839]
## Question

canal报异常导致canal instance重启，会发送kafka的数据重复，导致kafka中的数据乱序，该问题如何可以解决了？
重复数据如下所示（从kafka中顺序消费拿到的数据）
type='INSERT', es=1692093849000, ts=1692093849314, update_time=2023-08-15 18:04:09,
type='UPDATE', es=1692093882000, ts=1692093887041, update_time=2023-08-15 18:04:43,
type='INSERT', es=1692093849000, ts=1692093849314, update_time=2023-08-15 18:04:09,

注：导致第一条和第三条一样，第三条记录重复了（不应该有第三条）：为什么会出现这个情况了？

**Comment by TonyHowardPark** [comment]
3条数据在kafka的同一个分区中

**Comment by agapple** [comment]
数据重复是无法避免的，一般是会出现  A B A B C 这样的重复模式
