### ISSUE TITLE
希望后续有对 Docker 支持的计划，环境调试特别不方便。

### ISSUE THREAD

**Issue by caryyu** [alibaba/canal#484]
我本来打算自己封装镜像的，我发现需要自己写 `docker entrypoint.sh` 不说，主要是日志还有配置的处理需要在应用层做一些工作果断放弃了，希望官方后续对 Docker 进行支持。

**Comment by freeme** [comment]
我们自己做了一个镜像，需要的话，可以交流一下，微信gary0526

**Comment by caryyu** [comment]
@freeme 你方便把你的 `dockerfile` 的仓库链接发一下吗？ 
> BTW: 你封装的镜像是改造过官方的代码吗？

我这边期望的镜像功能有如下两点主要特性：

* 日志可以统一输出并有效通过 `docker logging` 控制收集；
* 可以通过 `docker environment` 环境变量控制核心配置；

**Comment by pczhaoyun** [comment]
修改startup.sh文件，变成前台应用就好了。

**Comment by caryyu** [comment]
@pczhaoyun 脚本只是其中一方面，应用本身的日志和配置也要做相应适应性处理的，否则依然管理麻烦的。

**Comment by agapple** [comment]
@freeme 可以提交一个dockerfile PR

**Comment by okjesse** [comment]
是啊，有这个会方便很多

**Comment by agapple** [comment]
docker已经支持，参考：https://github.com/alibaba/canal/wiki/Docker-QuickStart
