### ISSUE TITLE
adapter配置多张表时,会有col污染的问题

### ISSUE THREAD

**Issue by suzumiy** [alibaba/canal#4844]
YamlUtils中的这段代码请确认是否有问题

![image](https://github.com/alibaba/canal/assets/51273374/764000c6-2290-40cc-8caf-c7afb95f8b07)
baseProperties中的属性会越来越多,最终包含所有配置的列名,然后赋值给了目标表配置

**Comment by agapple** [comment]
https://github.com/alibaba/canal/pull/4560，fixed
