### ISSUE TITLE
CanalParseException: parse row data failed（v1.0.25）

### ISSUE THREAD

**Issue by freeme** [alibaba/canal#485]
canal server重启后可以正常运行
以下是异常信息
-------------
2018-01-08 09:36:30.435 [pool-4-thread-1] INFO  com.alibaba.otter.canal.meta.FileMixedMetaManager - clientId:1001 cursor:[mysql-bin.000914,191343375,1515375389000] address[xxxxxx:3306]
2018/1/8 上午9:36:312018-01-08 09:36:31.435 [pool-4-thread-1] INFO  com.alibaba.otter.canal.meta.FileMixedMetaManager - clientId:1001 cursor:[mysql-bin.000914,191344652,1515375390000] address[xxxxxx:3306]
2018/1/8 上午9:36:322018-01-08 09:36:32.435 [pool-4-thread-1] INFO  com.alibaba.otter.canal.meta.FileMixedMetaManager - clientId:1001 cursor:[mysql-bin.000914,191346634,1515375391000] address[xxxxxx:3306]
2018/1/8 上午9:36:332018-01-08 09:36:33.435 [pool-4-thread-1] INFO  com.alibaba.otter.canal.meta.FileMixedMetaManager - clientId:1001 cursor:[mysql-bin.000914,191348091,1515375392000] address[xxxxxx:3306]
2018/1/8 上午9:36:342018-01-08 09:36:34.435 [pool-4-thread-1] INFO  com.alibaba.otter.canal.meta.FileMixedMetaManager - clientId:1001 cursor:[mysql-bin.000914,191349500,1515375393000] address[xxxxxx:3306]
2018/1/8 上午9:36:342018-01-08 09:36:34.475 [destination = xxxxxxx , address = xxxxxxxxxxx: 3306 , EventParser] WARN  c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - ERROR ## parse this event has an error , last position : [EntryPosition[included=false,journalName=mysql-bin.000914,position=191349531,serverId=200,timestamp=1515375394000]]
2018/1/8 上午9:36:34com.alibaba.otter.canal.parse.exception.CanalParseException: parse row data failed.
2018/1/8 上午9:36:34Caused by: com.alibaba.otter.canal.parse.exception.CanalParseException: com.google.common.util.concurrent.UncheckedExecutionException: java.io.IOException: should execute connector.connect() first
2018/1/8 上午9:36:34Caused by: com.google.common.util.concurrent.UncheckedExecutionException: java.io.IOException: should execute connector.connect() first
2018/1/8 上午9:36:34  at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4832) ~[guava-18.0.jar:na]
2018/1/8 上午9:36:34  at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.TableMetaCache.getTableMeta(TableMetaCache.java:160) ~[canal.parse-1.0.25.jar:na]
2018/1/8 上午9:36:34  at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.getTableMeta(LogEventConvert.java:759) ~[canal.parse-1.0.25.jar:na]
2018/1/8 上午9:36:34  at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parseRowsEvent(LogEventConvert.java:428) ~[canal.parse-1.0.25.jar:na]
2018/1/8 上午9:36:34  at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parse(LogEventConvert.java:114) ~[canal.parse-1.0.25.jar:na]
2018/1/8 上午9:36:34  at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parse(LogEventConvert.java:66) ~[canal.parse-1.0.25.jar:na]
2018/1/8 上午9:36:34  at com.alibaba.otter.canal.parse.inbound.AbstractEventParser.parseAndProfilingIfNecessary(AbstractEventParser.java:337) ~[canal.parse-1.0.25.jar:na]
2018/1/8 上午9:36:34  at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3$1.sink(AbstractEventParser.java:184) ~[canal.parse-1.0.25.jar:na]
2018/1/8 上午9:36:34  at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:145) [canal.parse-1.0.25.jar:na]
2018/1/8 上午9:36:34  at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:220) [canal.parse-1.0.25.jar:na]
2018/1/8 上午9:36:34  at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]
2018/1/8 上午9:36:34Caused by: java.io.IOException: should execute connector.connect() first
2018/1/8 上午9:36:34  at com.alibaba.otter.canal.parse.driver.mysql.MysqlQueryExecutor.<init>(MysqlQueryExecutor.java:30) ~[canal.parse.driver-1.0.25.jar:na]
2018/1/8 上午9:36:34  at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.query(MysqlConnection.java:87) [canal.parse-1.0.25.jar:na]
2018/1/8 上午9:36:34  at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.TableMetaCache.getTableMetaByDB(TableMetaCache.java:80) ~[canal.parse-1.0.25.jar:na]
2018/1/8 上午9:36:34  at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.TableMetaCache.access$000(TableMetaCache.java:30) ~[canal.parse-1.0.25.jar:na]
2018/1/8 上午9:36:34  at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.TableMetaCache$1.load(TableMetaCache.java:55) ~[canal.parse-1.0.25.jar:na]
2018/1/8 上午9:36:34  at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.TableMetaCache$1.load(TableMetaCache.java:50) ~[canal.parse-1.0.25.jar:na]
2018/1/8 上午9:36:34  at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527) ~[guava-18.0.jar:na]
2018/1/8 上午9:36:34  at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319) ~[guava-18.0.jar:na]
2018/1/8 上午9:36:34  at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282) ~[guava-18.0.jar:na]
2018/1/8 上午9:36:34  at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197) ~[guava-18.0.jar:na]
2018/1/8 上午9:36:34  at com.google.common.cache.LocalCache.get(LocalCache.java:3937) ~[guava-18.0.jar:na]
2018/1/8 上午9:36:34  at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941) ~[guava-18.0.jar:na]
2018/1/8 上午9:36:34  at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824) ~[guava-18.0.jar:na]
2018/1/8 上午9:36:34  at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4830) ~[guava-18.0.jar:na]
2018/1/8 上午9:36:34  ... 10 common frames omitted
2018/1/8 上午9:36:342018-01-08 09:36:34.479 [destination = weiming-test , address = xxxxxx:3306 , EventParser] ERROR c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - dump address xxxxxx:3306 has an error, retrying. caused by
2018/1/8 上午9:36:34com.alibaba.otter.canal.parse.exception.CanalParseException: com.alibaba.otter.canal.parse.exception.CanalParseException: parse row data failed.
2018/1/8 上午9:36:34Caused by: com.alibaba.otter.canal.parse.exception.CanalParseException: parse row data failed.
2018/1/8 上午9:36:34Caused by: com.alibaba.otter.canal.parse.exception.CanalParseException: com.google.common.util.concurrent.UncheckedExecutionException: java.io.IOException: should execute connector.connect() first
2018/1/8 上午9:36:34Caused by: com.google.common.util.concurrent.UncheckedExecutionException: java.io.IOException: should execute connector.connect() first
2018/1/8 上午9:36:34  at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4832) ~[guava-18.0.jar:na]
2018/1/8 上午9:36:34  at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.TableMetaCache.getTableMeta(TableMetaCache.java:160) ~[canal.parse-1.0.25.jar:na]
2018/1/8 上午9:36:34  at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.getTableMeta(LogEventConvert.java:759) ~[canal.parse-1.0.25.jar:na]
2018/1/8 上午9:36:34  at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parseRowsEvent(LogEventConvert.java:428) ~[canal.parse-1.0.25.jar:na]
2018/1/8 上午9:36:34  at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parse(LogEventConvert.java:114) ~[canal.parse-1.0.25.jar:na]
2018/1/8 上午9:36:34  at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parse(LogEventConvert.java:66) ~[canal.parse-1.0.25.jar:na]
2018/1/8 上午9:36:34  at com.alibaba.otter.canal.parse.inbound.AbstractEventParser.parseAndProfilingIfNecessary(AbstractEventParser.java:337) ~[canal.parse-1.0.25.jar:na]
2018/1/8 上午9:36:34  at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3$1.sink(AbstractEventParser.java:184) ~[canal.parse-1.0.25.jar:na]
2018/1/8 上午9:36:34  at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:145) ~[canal.parse-1.0.25.jar:na]
2018/1/8 上午9:36:34  at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:220) ~[canal.parse-1.0.25.jar:na]
2018/1/8 上午9:36:34  at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]
2018/1/8 上午9:36:34Caused by: java.io.IOException: should execute connector.connect() first
2018/1/8 上午9:36:34  at com.alibaba.otter.canal.parse.driver.mysql.MysqlQueryExecutor.<init>(MysqlQueryExecutor.java:30) ~[canal.parse.driver-1.0.25.jar:na]
2018/1/8 上午9:36:34  at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.query(MysqlConnection.java:87) ~[canal.parse-1.0.25.jar:na]
2018/1/8 上午9:36:34  at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.TableMetaCache.getTableMetaByDB(TableMetaCache.java:80) ~[canal.parse-1.0.25.jar:na]
2018/1/8 上午9:36:34  at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.TableMetaCache.access$000(TableMetaCache.java:30) ~[canal.parse-1.0.25.jar:na]
2018/1/8 上午9:36:34  at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.TableMetaCache$1.load(TableMetaCache.java:55) ~[canal.parse-1.0.25.jar:na]
2018/1/8 上午9:36:34  at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.TableMetaCache$1.load(TableMetaCache.java:50) ~[canal.parse-1.0.25.jar:na]
2018/1/8 上午9:36:34  at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527) ~[guava-18.0.jar:na]
2018/1/8 上午9:36:34  at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319) ~[guava-18.0.jar:na]
2018/1/8 上午9:36:34  at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282) ~[guava-18.0.jar:na]
2018/1/8 上午9:36:34  at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197) ~[guava-18.0.jar:na]
2018/1/8 上午9:36:34  at com.google.common.cache.LocalCache.get(LocalCache.java:3937) ~[guava-18.0.jar:na]
2018/1/8 上午9:36:34  at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941) ~[guava-18.0.jar:na]
2018/1/8 上午9:36:34  at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824) ~[guava-18.0.jar:na]
2018/1/8 上午9:36:34  at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4830) ~[guava-18.0.jar:na]
2018/1/8 上午9:36:34  ... 10 common frames omitted
2018/1/8 上午9:36:342018-01-08 09:36:34.480 [destination = weiming-test , address = xxxxxx:3306 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:weiming-test[com.alibaba.otter.canal.parse.exception.CanalParseException: com.alibaba.otter.canal.parse.exception.CanalParseException: parse row data failed.
2018/1/8 上午9:36:34Caused by: com.alibaba.otter.canal.parse.exception.CanalParseException: parse row data failed.
2018/1/8 上午9:36:34Caused by: com.alibaba.otter.canal.parse.exception.CanalParseException: com.google.common.util.concurrent.UncheckedExecutionException: java.io.IOException: should execute connector.connect() first
2018/1/8 上午9:36:34Caused by: com.google.common.util.concurrent.UncheckedExecutionException: java.io.IOException: should execute connector.connect() first
2018/1/8 上午9:36:34  at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4832)
2018/1/8 上午9:36:34  at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.TableMetaCache.getTableMeta(TableMetaCache.java:160)
2018/1/8 上午9:36:34  at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.getTableMeta(LogEventConvert.java:759)
2018/1/8 上午9:36:34  at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parseRowsEvent(LogEventConvert.java:428)
2018/1/8 上午9:36:34  at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parse(LogEventConvert.java:114)
2018/1/8 上午9:36:34  at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parse(LogEventConvert.java:66)
2018/1/8 上午9:36:34  at com.alibaba.otter.canal.parse.inbound.AbstractEventParser.parseAndProfilingIfNecessary(AbstractEventParser.java:337)
2018/1/8 上午9:36:34  at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3$1.sink(AbstractEventParser.java:184)
2018/1/8 上午9:36:34  at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:145)
2018/1/8 上午9:36:34  at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:220)
2018/1/8 上午9:36:34  at java.lang.Thread.run(Thread.java:745)
2018/1/8 上午9:36:34Caused by: java.io.IOException: should execute connector.connect() first
2018/1/8 上午9:36:34  at com.alibaba.otter.canal.parse.driver.mysql.MysqlQueryExecutor.<init>(MysqlQueryExecutor.java:30)
2018/1/8 上午9:36:34  at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.query(MysqlConnection.java:87)
2018/1/8 上午9:36:34  at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.TableMetaCache.getTableMetaByDB(TableMetaCache.java:80)
2018/1/8 上午9:36:34  at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.TableMetaCache.access$000(TableMetaCache.java:30)
2018/1/8 上午9:36:34  at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.TableMetaCache$1.load(TableMetaCache.java:55)
2018/1/8 上午9:36:34  at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.TableMetaCache$1.load(TableMetaCache.java:50)
2018/1/8 上午9:36:34  at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
2018/1/8 上午9:36:34  at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319)
2018/1/8 上午9:36:34  at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
2018/1/8 上午9:36:34  at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197)
2018/1/8 上午9:36:34  at com.google.common.cache.LocalCache.get(LocalCache.java:3937)
2018/1/8 上午9:36:34  at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941)
2018/1/8 上午9:36:34  at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824)
2018/1/8 上午9:36:34  at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4830)
2018/1/8 上午9:36:34  ... 10 more
2018/1/8 上午9:36:34]

**Comment by agapple** [comment]
参考 #482
