### ISSUE TITLE
官方 canal-server docker 镜像中配置文件的 bug

### ISSUE THREAD

**Issue by tonycody** [alibaba/canal#4851]
![image](https://github.com/alibaba/canal/assets/6773121/0896be9b-cdaf-41c5-a58f-e9582923d53e)

properties 等号两边搞空格干嘛？

因为这个空格，导致 canal.admin.passwd = 4ACFE3202A5FF5CF467898FC58AAB1D615029441 这个密码明明设置的是对的，但一直提示是错的。
整个 properties 文件格式化去掉等号两边的空格后就正常了。

还有一个 bug，默认给的 canal-admin 的密码是 admin，但 canal-admin 后台又不支持少于6个密码的密码。导致默认给出的示例是admin/admin 实际上按默认去实践，无法登录。而默认提示的 canal.admin.passwd 是基于 admin 加密的，全得改。

用户想尝试一下弄个 demo 的门槛太高了。

建议优化一下吧~

**Comment by agapple** [comment]
本地mac测试验证，会自动trim处理空格问题

**Comment by agapple** [comment]
https://github.com/alibaba/canal/commit/a216b55010a9542ba70897903ad5abac1b919ff2
