### ISSUE TITLE
canal 对接 RocketMQ，mq 接收不到消息

### ISSUE THREAD

**Issue by obey-destiny** [alibaba/canal#4859]
canal启动成功了，但是变更数据库表中的数据，MQ 接收不到消息，topic 也没有创建。
MySQL，binlog 日志开启了
RocketMQ，nameserve，broker，也启动成功

**Comment by agapple** [comment]
描述版本 + 复现步骤

**Comment by obey-destiny** [comment]
解决了，是regex 正则表达式写错了
