### ISSUE TITLE
canal_deployer。canal.destination配置无效

### ISSUE THREAD

**Issue by yongzheJIN** [alibaba/canal#4867]
- [x] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment
canal_deployer
* canal version 1.15
* mysql version 5.6

### Issue Description
我之前在canal建一个slave列表，分别为example和statistic，后来这个statistic不需要了我就在canal.property里面把这个文件给删除了。但没有直接删除statistic这个配置文件夹，他就一直还在监控这个slave。

### Steps to reproduce
新建一个slave，然后配置到canal.property里面，再在property里面把这个给删除了.

### Expected behaviour
正确的应该是，我在canal.property里面把他stastic删除之后，他就应该不监控了吧，即便我还有statistic这个文件夹

### Actual behaviour

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by agapple** [comment]
canal.auto.scan = false，关闭下这个参数
