### ISSUE TITLE
cancal集群使用k8s部署

### ISSUE THREAD

**Issue by wolf27w** [alibaba/canal#4884]
使用k8s部署时在amd64中是没有问题的，但是在arm64中部署就会出现异常，查看基础镜像使用的jdk是amd64的，更换成arm64的后每次启动都会提示
“Redirecting to /bin/systemctl start sshd.service
Failed to get D-Bus connection: Operation not permitted
Redirecting to /bin/systemctl start crond.service
Failed to get D-Bus connection: Operation not permitted”
看了一下，是提升特权模式的问题，但是在pod里添加了
“
          securityContext:
            privileged: true

”
还是一样的问题，感觉特权模式提升不了

**Comment by agapple** [comment]
目前dockerfile暂时不支持arm模式
