### ISSUE TITLE
客户端连接server密码不正确

### ISSUE THREAD

**Issue by nsarray** [alibaba/canal#4893]
服务端配置
canal.user=canal
canal.passwd=e3619321c1a937c46a0d8bd1dac39f93b27d4458

客户端的password应该怎么传？
看了下源码，发现服务端哈希过程中的seed是随机的，客户端没有这个seed的情况下，生成的密码应该怎么都不会正确吧？
同时看了下测试用例，客户端密码的生成也需要依赖seed，只有服务端和客户端seed一致的情况下，密码才能校验通过

```java
    @Test
    public void testSimple() throws NoSuchAlgorithmException {
        byte[] seed = { 1, 2, 3, 4, 5, 6, 7, 8 };
        // String str = "e3619321c1a937c46a0d8bd1dac39f93b27d4458"; // canal
        // passwd
        String str = SecurityUtil.scrambleGenPass("canal".getBytes());
        byte[] client = SecurityUtil.scramble411("canal".getBytes(), seed);
        boolean check = SecurityUtil.scrambleServerAuth(client, SecurityUtil.hexStr2Bytes(str), seed);
        Assert.assertTrue(check);
    }
```

**Comment by agapple** [comment]
https://github.com/alibaba/canal/wiki/Canal-Admin-ServerGuide#%E9%9D%A2%E5%90%91userpasswd%E7%9A%84%E5%AE%89%E5%85%A8acl%E6%9C%BA%E5%88%B6

**Comment by nsarray** [comment]
按文档里的试了无效，客户端无论是传e3619321c1a937c46a0d8bd1dac39f93b27d4458还是传e3619321c1a937c46a0d8bd1dac39f93b27d4458再加密后的串都无效，官方可否提供一个可用的客户端测试密码
