### ISSUE TITLE
Logback-classic-1.1.3.jar

### ISSUE THREAD

**Issue by PeanutVvl** [alibaba/canal#4908]
Logback是一个 Java 应用程序的日志记录框架。
Logback存在远程代码执行漏洞，有编辑配置文件所需权限的攻击者可以制作恶意配置，允许执行从 LDAP 服务器加载的任意代码。

修复建议：将 Logback  升级到 1.2.9 及以上版本

**Comment by agapple** [comment]
可以提交一个PR给我
