### ISSUE TITLE
关于canal过滤表的问题

### ISSUE THREAD

**Issue by DeepBlue98** [alibaba/canal#4910]
使用单机部署canal,配置了过滤规则订阅数据库实例的某个库下的某个表（此表产生的dml操作不多），canal订阅数据库的binlog并且过滤是怎么进行的？
1.同步指定表所在数据库实例的binlog,后续内部过滤表
2.同步指定表所在库的全部binlog，后续内部过滤表
3.同步指定表的的binlog

如为1或者2的过程，只需要同步单表的canal的部署配置，是否要考虑全数据库实例或者全库同步的配置呢？
在机器配置的选择上是否有参照原则呢？

**Comment by agapple** [comment]
第一条，客户端过滤

**Comment by DeepBlue98** [comment]
> 第一条，客户端过滤
 如果按照第一条所述，客户端过滤，那么部署的机器配置原则，是否考虑全实例的所有的binlog的量级呢？这样的设计似乎不太合理？还是canal内部有做这一步的设计去规避这个问题呢？
@agapple
