### ISSUE TITLE
Failed to get D-Bus connection: Operation not permitted

### ISSUE THREAD

**Issue by zuobee** [alibaba/canal#4911]
版本 canal/canal-server:v1.1.7
docker logs -f -n 500 canal-server 

DOCKER_DEPLOY_TYPE=VM
==> INIT /alidata/init/02init-sshd.sh
==> EXIT CODE: 0
==> INIT /alidata/init/fix-hosts.py
==> EXIT CODE: 0
==> INIT DEFAULT
Failed to get D-Bus connection: Operation not permitted
Failed to get D-Bus connection: Operation not permitted
==> INIT DONE
==> RUN /home/admin/app.sh
==> START ...
start canal ...
start canal successful
==> START SUCCESSFUL ...

**Comment by agapple** [comment]
https://serverfault.com/questions/824975/failed-to-get-d-bus-connection-operation-not-permitted，docker的权限问题

**Comment by niuren930** [comment]
@agapple 我这样测试了，每月作用。
