### ISSUE TITLE
canal 1.1.7 启动报错

### ISSUE THREAD

**Issue by wit-Zeman** [alibaba/canal#4914]
OpenJDK 64-Bit Server VM warning: ignoring option PermSize=96m; support was removed in 8.0
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
Error: Could not find or load main class com.alibaba.otter.canal.deployer.CanalLauncher

以下是Java版本
openjdk version "1.8.0_382"
OpenJDK Runtime Environment (build 1.8.0_382-b05)
OpenJDK 64-Bit Server VM (build 25.382-b05, mixed mode)

**Comment by agapple** [comment]
Could not find or load main class com.alibaba.otter.canal.deployer.CanalLauncher，你是下载二进制进行run的么？

**Comment by wit-Zeman** [comment]
> Could not find or load main class com.alibaba.otter.canal.deployer.CanalLauncher，你是下载二进制进行run的么？

已解决。下载的canal文件上传到Linux出错了，重新上传解压就能启动了。
