### ISSUE TITLE
1.1.6版本canal监听binlog日志，解析成entity对象后，rowDatas字段无值。求原因，求排查思路

### ISSUE THREAD

**Issue by cy-yz** [alibaba/canal#4919]
开发者您好，打扰下，请帮忙看下这个问题。
<img width="1164" alt="image" src="https://github.com/alibaba/canal/assets/54885282/b8b10a4d-63db-4efc-9cbe-4eee9bfd5a13">
rowData一直无法解析出值。sql字段是有值的。
1、未看到错误日志
2、请问解析binlog日志还需要特殊配置嘛
3、rowData的赋值底层逻辑有说明文档嘛
4、已经尝试各种方法了，就是无法解析出来，麻烦看下
数据库版本：5.7.1、canal版本：1.1.6

**Comment by chehongwei-git** [comment]
配置 canal.instance.master.journal.name=mysql-bin.249770  指定最新binlog日志试试

**Comment by agapple** [comment]
你这个是query_log_event把，只有SQL没有行记录
