### ISSUE TITLE
是否要设置getWithoutAck超时时间

### ISSUE THREAD

**Issue by wz2cool** [alibaba/canal#492]
说真的，我被这超时时间搞得头痛，我本来是不设置超时时间的，但是好像在弱网环境会卡主  #参考： #297 
后面我设置超时,以后发现，是说在规定时间内等待batchSize 填满？？？ 并且我测试的时候确实也是看到实在等待超时时间。
![image](https://user-images.githubusercontent.com/11556152/34977258-ca958ca0-fad4-11e7-9bc6-703c495e919f.png)

![image](https://user-images.githubusercontent.com/11556152/34976865-61b85a10-fad3-11e7-80ff-adc7770a9f4c.png)

我只想避免卡主，请问是否一定要设置超时时间

**Comment by wz2cool** [comment]
在 1.0.25 版本设置超时报错

![image](https://user-images.githubusercontent.com/11556152/34979214-9c6dc91c-fadb-11e7-9d00-32884b26ecc1.png)

**Comment by agapple** [comment]
建议设置timeout，主要是后端如果一直没有数据变更，会一直卡主

**Comment by wz2cool** [comment]
@agapple   嗯 好的 大概理解，所以batchSize 还不能设置很大对吧，填不满就一直卡主对吧
