### ISSUE TITLE
canal instance重启丢失部分消息

### ISSUE THREAD

**Issue by cdma-git** [alibaba/canal#4922]
当前使用canal rabbitmq连接器，将canal解析到的变更信息同步到rabbitmq消息队列。根据项目需求，需要动态更新instance里面监听的表范围，因为会调用canal api定时重启canal instance，观测一段时间发现从rabbitmq中拿到的消息偶发的会少几条。请问instance的频繁重启会导致消息丢失么

ps：查看canal的日志，发现如下报错
![image](https://github.com/alibaba/canal/assets/64626797/81771876-c46c-47d1-973d-1915203974e0)

**Comment by agapple** [comment]
如果选择file模式持久化位点，就不会丢消息

**Comment by ahjxxcr** [comment]
@agapple 如何选择file模式持久化位点啊？
