### ISSUE TITLE
启动成功，但是监听不到mysql的变化

### ISSUE THREAD

**Issue by 694752382** [alibaba/canal#4929]
![image](https://github.com/alibaba/canal/assets/34418198/d2cea479-a408-45dc-8014-5d6b40ec7532)
![image](https://github.com/alibaba/canal/assets/34418198/cbdea6e3-d6f7-453c-976a-b6749b36a0a6)
![image](https://github.com/alibaba/canal/assets/34418198/593e99d6-46eb-4781-8bd9-933bb0df1052)
![image](https://github.com/alibaba/canal/assets/34418198/3489c29d-0b12-49d2-bafe-5d417d607839)
如题，看着都正常就是监听不到东西，我doris里面也没收到新的变更数据

**Comment by 694752382** [comment]
mysql的版本是 8.0.34

**Comment by 694752382** [comment]
canal版本1.1.7

**Comment by agapple** [comment]
表达式注意下点号的转义符
