### ISSUE TITLE
1.0.25 版本设置超时报错

### ISSUE THREAD

**Issue by wz2cool** [alibaba/canal#493]
#492  我再这个bug中想解决读取卡主的问题，解决方案是说在1.0.25中使用新的机制参考 #297  但是我发现我设置超时会报错，不设置超时反而会正确

![image](https://user-images.githubusercontent.com/11556152/34980458-936b5baa-fadf-11e7-8497-7a00673f6810.png)

![image](https://user-images.githubusercontent.com/11556152/34981797-95c6a5f4-fae3-11e7-851f-4ec4359c51f1.png)

**Comment by agapple** [comment]
你这个超时和297的超时是两回事

**Comment by wz2cool** [comment]
@agapple   谢谢百忙之中回复啊， 在第一个问题里面建议是设置超时时间的，但是在1.0.25 我只要已设置 超时时间就报socketTimoutException, 但是在1.0.24 版本不会有这个错。 就是想问一下这个行为是否是一个预期结果呢。

**Comment by agapple** [comment]
1.0.25改动过canal server端读取mysql的超时机制，默认是3秒，不过你这个超时发送的频率也太高了，差网络条件？
