### ISSUE TITLE
com.alibaba.otter.canal.server.embedded.CanalServerWithEmbedded isn't start , please check

### ISSUE THREAD

**Issue by lemon-arrebol** [alibaba/canal#4930]
版本信息：
Canal-admin 版本：1.1.7
Canal-deployer 版本：1.1.7，单机部署模式，在Canal-admin创建节点进行管理

错误信息：
Canal-admin Server管理进行<停止>操作提示失败，Canal-deployer日志如下：
2023-11-01 14:50:01.666 [New I/O server worker #2-5] INFO  com.alibaba.otter.canal.deployer.CanalController - ## stop the canal server[10.19.208.150(127.0.0.1):11111]
2023-11-01 14:50:01.675 [New I/O server worker #2-5] ERROR c.a.otter.canal.deployer.admin.CanalAdminController - com.alibaba.otter.canal.server.embedded.CanalServerWithEmbedded isn't start , please check
com.alibaba.otter.canal.common.CanalException: com.alibaba.otter.canal.server.embedded.CanalServerWithEmbedded isn't start , please check

CanalServerWithEmbedded使用：
1、CanalController 构造函数初始化embeddedCanalServer如下
embeddedCanalServer = **_CanalServerWithEmbedded.instance();_**
canalServer = CanalServerWithNetty.instance();

2、CanalServerWithNetty 构造函数
private CanalServerWithNetty(){
    this.embeddedServer = **_CanalServerWithEmbedded.instance();_**
    this.childGroups = new DefaultChannelGroup();
}

从上面可知：CanalController.canalServer 和 CanalController.embeddedCanalServer  持有的CanalServerWithEmbedded 其实是同一个

Canal-admin对Canal-server发起关闭请求操作：
com.alibaba.otter.canal.admin.handler.SessionHandler#messageReceived
com.alibaba.otter.canal.deployer.admin.CanalAdminController#stop
com.alibaba.otter.canal.deployer.CanalStarter#stop(boolean)
com.alibaba.otter.canal.deployer.CanalController#stop  执行关闭操作如下：
（1）CanalServerWithNetty#stop  在这里会执行 embeddedServer.stop(); 方法
......
（2）CanalController.embeddedCanalServer.stop();  执行到这里时其实已经是【停止】状态了，导致在这里执行抛异常。这里是不是要判断下【启动】状态才需要关闭？

**Comment by D5ZangJie** [comment]
@agapple 这代码fix 了 是在哪个分支上？有没有发[Releases](https://github.com/alibaba/canal/releases)

**Comment by zhaobingshuang** [comment]
@agapple 你好，我也遇到相同的问题的，有什么临时解决方案吗

**Comment by zhaobingshuang** [comment]
> @agapple 你好，我也遇到相同的问题的，有什么临时解决方案吗

使用 [1.1.8-alpha](https://github.com/alibaba/canal/releases/tag/canal-1.1.8-alpha-1) 解决了
