### ISSUE TITLE
rabbitMQ默认配置未更新

### ISSUE THREAD

**Issue by xuandax** [alibaba/canal#4937]
- [x] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment

* canal 1.1.7
* mysql 8.0.18

### Issue Description
rabbitMQ默认配置中无以下两项
rabbitmq.queue = xxx
rabbitmq.routingKey = xxx

在instance.properties的 canal.mq.topic= xxx 生效后，以上两项会失效

**Comment by agapple** [comment]
rabbitmq.queue 更多的是一个配置声明，canal.mq.topic会决定最后的topic路由
