### ISSUE TITLE
canal默认admin.passwd风险说明及解决方案

### ISSUE THREAD

**Issue by agapple** [alibaba/canal#4941]
近期canal社区收到关于canal admin鉴权功能通过adminPassword默认值进行撞击，绕过身份验证安全漏洞的问题。

考虑默认的安全风险，计划v1.1.8版本做如下变更：
1.  canal admin针对与canal-server通讯时，使用application.yml中配置的canal.adminPassword
2.  canal-server使用canal.properties中配置canal.passwd和canal.admin.passwd，分别控制client链接server、以及server链接admin之间的权限控制

新版本移除自带的password默认值，并在password未传入或非法时阻止节点启动来提醒用户设置自定义password

**Comment by e345** [comment]
鼎力支持，加强系统安全。1.1.8希望能兼容8.0.33的binlog，大佬帮忙看看，单独发了issues：https://github.com/alibaba/canal/issues/4940

**Comment by agapple** [comment]
密码机制：https://github.com/alibaba/canal/wiki/Canal-Admin-ServerGuide#%E9%9D%A2%E5%90%91userpasswd%E7%9A%84%E5%AE%89%E5%85%A8acl%E6%9C%BA%E5%88%B6

**Comment by agapple** [comment]
![image](https://github.com/alibaba/canal/assets/834743/20f3b74f-5931-428a-b964-2d0752813b1d)

修复ClientAuthenticationHandler在auth认证失败时未及时终止后续packet包的处理流程，导致有越权访问binlog数据的风险
