### ISSUE TITLE
varchar类型的字段，编码格式gb2312，中文解析乱码 

### ISSUE THREAD

**Issue by chenqi14** [alibaba/canal#4946]
- [ ] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment

* canal version
* 1.1.6
* mysql version
  5.7.30
### Issue Description
varchar类型的字段，编码格式gb2312，中文解析乱码 

name字段中文乱码

CREATE TABLE `gb2312_test` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(129) CHARACTER SET gb2312 DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4;

### Actual behaviour

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by agapple** [comment]
需要设置canal.instance.connectionCharset = GBK

**Comment by chenqi14** [comment]
> 需要设置canal.instance.connectionCharset = GBK

这个配置是一个全局的配置，如果表里的字段有utf-8也有gbk的编码，还是有问题，要根据字段的字符集具体处理，不能设置一个全局的charset

CREATE TABLE `gb2312_test` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(132) CHARACTER SET gb2312 DEFAULT NULL,
  `name2` varchar(128) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4;

这里的name2是utf-8、name是gbk
