### ISSUE TITLE
按example下的例子写canal client订阅binlog数据，无法取到数据

### ISSUE THREAD

**Issue by olin017** [alibaba/canal#495]
按example下的例子写canal client订阅binlog数据，启动后，idea的控制台会不断输出DEBUG org.apache.zookeeper.ClientCnxn - Got ping response for sessionid这样的日志，在mysql>下执行DDL或DML操作无法输出binglog相关日志数据

**Comment by wingerx** [comment]
先好好看下wiki，应该是有地方配置不正确导致。

**Comment by clennpillo** [comment]
@olin017 我也遇到了一样的问题，
我用的版本是 1.0.25
mysql版本是 mysql  Ver 14.14 Distrib 5.7.21, for Linux (x86_64) using  EditLine wrapper
试过各种方法，始终无法获取到binglog变动。

**Comment by clennpillo** [comment]
请问你的问题解决了吗？可以说一下解决方法吗？

**Comment by clennpillo** [comment]
换成1.0.20，一样的配置，问题解决。为了进一步确定问题，再换成1.0.25，依旧无法获取任何db change。
具体原因不知道 ，建议不要用太新的版本。

**Comment by Aiyabeetle** [comment]
我想着有人也应该遇到了这个问题，刚好在这里找到了，1.0.25版本使用各种方法扔无法获取binlog更新，按楼上说的换成1.0.20版本解决问题，谢了小伙伴们。不清楚高版本为什么无法获取变动。

**Comment by fanpeng1100** [comment]
问题解决了吗？是否和binlog文件的名称格式有关？

**Comment by Aiyabeetle** [comment]
和canal版本有关系




| |
虫虫同学
邮箱：aiyabeetle@163.com
|

签名由 网易邮箱大师 定制

在2018年06月13日 09:37，fanpeng 写道：

问题解决了吗？是否和binlog文件的名称格式有关？

**Comment by agapple** [comment]
建议换成1.0.26
