### ISSUE TITLE
服务器断电后，重启数据库和canal服务，一直报Client requested master to start replication from position > file size

### ISSUE THREAD

**Issue by aywangchen** [alibaba/canal#500]
重启canalServer一直报这个错误Client requested master to start replication from position > file size，应该是数据不同步造成的吧，这种情况该怎么解决

**Comment by fefine** [comment]
当instance.xml中的canal.instance.master.position或者meta.dat中的position大于实际binlog的size的时候会报这个错。

**Comment by agapple** [comment]
LS正解

**Comment by tiantangpw** [comment]
修改  conf/example/meta.dat   里的journalName和position 为当前位置就行了。在mysql中用show master status;  查看当前binlog位置。

**Comment by aywangchen** [comment]
@tiantangpw 清楚了，谢谢

**Comment by lyl8213** [comment]
@tiantangpw 我也遇到这个问题，但是我用了zk，meta.dat里面没有journalName和position怎么办

**Comment by KinYu668** [comment]
> @tiantangpw 我也遇到这个问题，但是我用了zk，meta.dat里面没有journalName和position怎么办

问题解决了么，ZK的方式
