### ISSUE TITLE
推荐一个基于canal解析本地/阿里云Rds binlog的工具

### ISSUE THREAD

**Issue by zhuchao941** [alibaba/canal#5006]
https://github.com/zhuchao941/canal2sql

支持三种解析模式，欢迎试用，欢迎stars👏🏻

在线模式（online）：指定远程数据库地址，实时从对应数据库获取binlog并解析
binlog文件模式（file）：离线模式，指定binlog文件url（支持http/file等），读取对应文件并解析
阿里云rds模式（aliyun）：离线模式，指定对应的时间范围以及实例id（instanceId），读取符合条件的binlog文件列表并解析

**Comment by agapple** [comment]
点赞

**Comment by agapple** [comment]
已添加到readme

**Comment by zhuchao941** [comment]
> 已添加到readme

我天 感谢大佬支持~
