### ISSUE TITLE
canal.serverMode = rabbitMQ时，启动失败。tcp模式下没问题

### ISSUE THREAD

**Issue by Transcendss** [alibaba/canal#5008]
## Question

rabbitmq配置是正确的。example/instance.properties配置中的canal.mq.topic也配置成了routekey名称。

![WechatIMG18](https://github.com/alibaba/canal/assets/30683424/b08570d8-84d0-4ccd-ba6d-4134620d49c3)

**Comment by grassselfl** [comment]
最后怎么解决的呀
