### ISSUE TITLE
group模式cursor问题

### ISSUE THREAD

**Issue by suifengzhuliu** [alibaba/canal#501]
1.分库情况下总共10个库，配置了group-instance.xml。
2.有一个客户端来消费这些数据。
3.消费完了之后，服务端写cursor，在这个节点。/otter/canal/destinations/example/1001/cursor。格式化如下：{"@type":"com.alibaba.otter.canal.protocol.position.LogPosition","identity":{"slaveId":-1,"sourceAddress":{"address":"10.20.144.15","port":3306}},"postion":{"included":false,"journalName":"mysql-bin.002253","position":2574756,"timestamp":1363688722000}}
4.请问我总共配置了10个库，分别都消费了，这个在zk是怎么存储的呢?目前在zk中的cursor节点貌似只存储了一个吧

**Comment by agapple** [comment]
只存储时间戳
