### ISSUE TITLE
client-admin中目前是不支持adapter相关相关配置吗

### ISSUE THREAD

**Issue by jjljjl** [alibaba/canal#5032]
## Question
  看到admin中有管理adapter的表，但是页面没有看到相关操作

**Comment by agapple** [comment]
目前adapter管理的功能不完整，可以考虑提交一个PR给我

**Comment by mrzhao1** [comment]
支持的，在canal_config表中添加一条id=2的配置，content的数据就能替换adapter下application.yml文件信息，可以研究一下源码就明白了，只不过增删改查的接口就得自己写。
