### ISSUE TITLE
 ERROR ## findAsPerTimestampInSpecificLogFile has an error

### ISSUE THREAD

**Issue by yanglin2000168** [alibaba/canal#504]
![_qyd8 tx sr 6qc8 gb74g](https://user-images.githubusercontent.com/35767127/35331901-f8093d74-0143-11e8-9e2f-89528c232bc2.png)
配置
canal.instance.master.journal.name=
canal.instance.master.position=
也有相同错误，

**Comment by yanglin2000168** [comment]
![kqa al2uno vd1 0u_3h](https://user-images.githubusercontent.com/35767127/35332342-a2deabb6-0145-11e8-8d54-ac1735efdce7.png)

**Comment by agapple** [comment]
新版本已经修复
