### ISSUE TITLE
canal k8s ha 部署 重启 instances 会导致无法连接

### ISSUE THREAD

**Issue by ayers-ltd** [alibaba/canal#5046]
### 问题
k8s 高可用部署的canal v1.1.7
instance 刚启动能正常写kafka，但是手动停止重启后 报错，怎么都连不上，只能删了canal-server ，重新 注册canal-server 才能正常消费写入
一样的部署方式，canal v1.1.6 可以正常运行，重启instance 不报错, 基本排除人为配置写错

### environment

* canal version v1.1.7
* canal mysql version 5.7/8.0.31 / --default_authentication_plugin=mysql_native_password
* instance mysql version 8.0.31/gtid / --default_authentication_plugin=mysql_native_password
* kafka version 2.7

### canal config
canal.serverMode = kafka
canal.instance.tsdb.spring.xml = classpath:spring/tsdb/mysql-tsdb.xml
canal.instance.global.spring.xml = classpath:spring/default-instance.xml

canal.instance.tsdb.enable = true
canal.instance.tsdb.url=jdbc:mysql://mysql-0.mysql-hs.canal.svc.cluster.local:3306/canal_tsdb?useUnicode=true&characterEncoding=UTF-8&useSSL=false
canal.instance.tsdb.dbUsername = root
canal.instance.tsdb.dbPassword = root

#### 镜像
canal/canal-server:v1.1.7
canal/canal-admin:v1.1.7
mysql:8.0.31
registry.k8s.io/kubernetes-zookeeper:1.0-3.4.10

### 相关报错摘要
com.alibaba.druid.pool.DruidDataSource - get connection timeout retry
Caused by: java.sqlSOLException: connect error, url , driverClass com.mysqljdbc.Driver

#### 相关截图
![c9a53b6ae3bc2f7dd121f16be50c434](https://github.com/alibaba/canal/assets/57494369/712b5f1a-9304-4d89-a202-3df087dbe299)
![fa7a5e9f5ea9b9b5b249c271ec44efe](https://github.com/alibaba/canal/assets/57494369/8eef2093-e94a-4e39-9dbb-20dc77551a0b)

**Comment by agapple** [comment]
https://github.com/alibaba/canal/issues/4907，应该是这个问题，试一下1.1.8最新的包
