### ISSUE TITLE
client-adapter.rdb模块在转换时间时丢失精度

### ISSUE THREAD

**Issue by wbxlll** [alibaba/canal#5052]
- [x] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment

* canal version
* 1.1.8-SNAPSHOT
* mysql version
* 8.0.32

### Issue Description
1、当MySQL中的字段使用超过毫秒的精度时（即包含微秒）如datetime(6)、timestamp(6)时，超过毫秒的精度在client-adapter.rdb模块转换为java.sql的相关类型时丢失了。如2024-02-26 00:17:06.226321，转换后变为2024-02-26 00:17:06.226。
![image](https://github.com/alibaba/canal/assets/17880187/ac0a8ab9-86b6-4278-853b-b2a1a066c93e)
2、当MySQL中的字段使用超过秒的精度时（即包含毫秒、微秒），如time(6)时，超过秒的精度在client-adapter.rdb模块转换为java.sql的相关类型时丢失了。如23:58:03.138722，转换后变为23:58:03。

### Issue Track
我使用的是RocketMQ模式，从canal-server到RocketMQ这一段是正常的，RocketMQ中的消息还保留着精度。
![image](https://github.com/alibaba/canal/assets/17880187/f9f1a60b-4e14-4ace-9613-048c576c8a3e)
canal-adapter拿到MQ消息后到转换为写入rdb用的PreparedStatement时，从datatimestr转为java.sql.Timestamp和从timestr转为java.sql.Time时出现了精度丢失。
究其原因，datetimestr转Timestamp如下图所示，虽然java.sql.Timestamp支持到纳秒精度，但是先转换的java.util.Date不支持微秒精度，此时就已经丢失精度。
![image](https://github.com/alibaba/canal/assets/17880187/8f3b6243-109c-4783-a75d-f6f90b2b8c8f)
timestr转java.sql.Time如下图所示，先转的Date虽然支持到毫秒，但是java.sql.Time本身不支持秒以下精度，所以怎么转都没用。
![image](https://github.com/alibaba/canal/assets/17880187/d14cb18f-1052-42cb-a95c-155060f78ee7)

### 我的修复方法是
1、datetimestr转java.sql.Timestamp时，先判断datetimestr是否包含毫秒以下精度---->不包含走老逻辑，包含就转LocalDateTime，ISO-8601格式的LocalDateTime支持到纳秒，MySQL目前仅支持到微秒，因此足够覆盖MySQL的时间精度。转完LocalDateTime---->再转到Timestamp，Timestamp本身支持到纳秒，因此这次转换不会出现精度丢失。
2、timestr转java.sql.Time时，先判断timestr是否包含秒以下精度---->不包含走老逻辑，包含就使用setObject方法直接set进去，经测试MySQL不会出现异常（这里取决于JDBC驱动的实现）。

**Comment by JetthaiWayne** [comment]
還是遇到一樣的問題
MySQL : 8.0.31
Canal: canal-1.1.8-alpha-2

MySQL: 
- TIMESTAMP: **2024-07-05 05:44:46.297734**
Elasticsearch example logs:  
- DEBUG c.a.o.canal.client.adapter.es.core.service.ESSyncService - DML: {"data":[{"id":489788,"TIMESTAMP":"**2024-07-05 05:44:46.297**"}]}

**Comment by wn99hatebtc** [comment]
還是遇到一樣的問題
MySQL : 8.0.31
Canal: canal-1.1.8-alpha-2

MySQL:

TIMESTAMP: 2024-07-05 05:44:46.297734
Elasticsearch example logs:
DEBUG c.a.o.canal.client.adapter.es.core.service.ESSyncService - DML: {"data":[{"id":489788,"TIMESTAMP":"2024-07-05 05:44:46.297"}]}
