### ISSUE TITLE
blob 类型字段中文数据同步到kafka， json字段值乱码

### ISSUE THREAD

**Issue by Zy-THOMAS** [alibaba/canal#5056]
json 格式数据：
{"data":[{"name":"测试室","creator":"æµè¯"}],"databas   e":"test","es":1709015566000,"gtid":"","id":2,"isDdl":false,"mysqlType":{"name":"varchar(100)","creator":"varbinary(255)"},"old":null,"pkNames":null,"sql":"","sqlType":{"name":12,"creator":2004},"table":"session","ts":1709015566516,"type":"INSERT"}
 
表结构：
CREATE TABLE IF NOT EXISTS `session` (
  `name` varchar(100) NOT NULL DEFAULT '',
  `creator` varbinary(255) NOT NULL DEFAULT '' COMMENT '会话创建者id'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='会话管理';

通过go解析，不能正常转码解析，请问有其他处理办法吗？

**Comment by agapple** [comment]
构造一个复现的test场景
