### ISSUE TITLE
目前canal推荐使用哪个版本

### ISSUE THREAD

**Issue by jjljjl** [alibaba/canal#5057]
## Question

想咨询下，目前最高是1.1.8-SNAPSHOT版本，推荐使用哪个版本呢，1.1.7与1.1.8有哪些大的差异呢

**Comment by agapple** [comment]
推荐使用1.1.8-SNAPSHOT，修复个别1.1.7的已知问题

**Comment by jetginger** [comment]
@agapple 大佬，1.1.5 部署上去监听消息会打日志在 instance对应的文件目录的日志文件里面，但是1.1.7 就没打了，是默认不打印了，还是我配置1.1.7的没配对
![1712047645841](https://github.com/alibaba/canal/assets/32380830/149c29ab-fc23-4242-8e8a-803969bc4784)

**Comment by jetginger** [comment]
我很早之前使用过canal用于项目中，现在的canal是不是已经默认server不会输出成功监听消息的日志，需要启动canal client来接收消息，然后才会根据用户情况自行打印输出日志信息
