### ISSUE TITLE
mvn 运行 canal.example工程 jar 包丢失

### ISSUE THREAD

**Issue by Torival** [alibaba/canal#506]
在使用mvn exec:java -Dexec.mainClass="com.alibaba.otter.canal.example.SimpleCanalClientTest"运行canal.example工程时，提示俩个jar包丢失。
[WARNING] The POM for com.alibaba.otter:canal.client:jar:1.0.26-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for com.alibaba.otter:canal.protocol:jar:1.0.26-SNAPSHOT is missing, no dependency information available

**Comment by agapple** [comment]
mvn clean install eclipse:eclipse -Dmaven.test.skip
