### ISSUE TITLE
canal 1.1.7 deployer启动一刷获取数据库链接错误 

### ISSUE THREAD

**Issue by zhangchenbiao** [alibaba/canal#5063]
ERROR com.alibaba.druid.pool.DruidDataSource - create connection SQLException, url: , errorCode 0, state null
java.sql.SQLException: connect error, url , driverClass `com.mysql.jdbc.Driver`
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1775)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2916)

问题原因是拿到的tsdbJdbcUrl、tsdbJdbcUserName、tsdbJdbcPassword 都是空的，但是配置中都配了值的，不知道为啥是空的，经查代码 发现把下面代码中finally代码块中的代码注释掉就好了，但是不知道这么改会不会存在什么隐患

        protected synchronized void buildTableMetaTSDB(String tsdbSpringXml) {
                if (tableMetaTSDB != null) {
                    return;
                }
                try {
                    // 设置当前正在加载的通道，加载spring查找文件时会用到该变量
                    System.setProperty("canal.instance.tsdb.url", tsdbJdbcUrl);
                    System.setProperty("canal.instance.tsdb.dbUsername", tsdbJdbcUserName);
                    System.setProperty("canal.instance.tsdb.dbPassword", tsdbJdbcPassword);
                    // 初始化
                    this.tableMetaTSDB = tableMetaTSDBFactory.build(destination, tsdbSpringXml);
                } catch (Throwable e) {
                    logger.warn("failed to build TableMetaTSDB ",e);
                    throw new CanalParseException(e);
                } finally {
                    // reset
                    System.setProperty("canal.instance.tsdb.url", "");
                    System.setProperty("canal.instance.tsdb.dbUsername", "");
                    System.setProperty("canal.instance.tsdb.dbPassword", "");
                }
            }

**Comment by zhourui999** [comment]
用
<img width="214" alt="image" src="https://github.com/alibaba/canal/assets/40812600/6d1d4a40-d30f-4d03-9192-a176bc128f99">
这个版本

**Comment by zhangchenbiao** [comment]
问题原因是啥

**Comment by zhangchenbiao** [comment]
> 用 <img alt="image" width="214" src="https://private-user-images.githubusercontent.com/40812600/310375549-6d1d4a40-d30f-4d03-9192-a176bc128f99.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MDQyNzIsIm5iZiI6MTcwOTcwMzk3MiwicGF0aCI6Ii80MDgxMjYwMC8zMTAzNzU1NDktNmQxZDRhNDAtZDMwZi00ZDAzLTkxOTItYTE3NmJjMTI4Zjk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDA1NDYxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxYTkxNWUwOWNlNzIyNjcyNDMxNjJmY2UxOTEwNTM2NWYzZjIzMjI1MjMxNTJjZGQ2ODk1NjgyOWM1ZWNhMGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2BQNdukz0UBGsn7izdCV0SoVJMOvtTbatlHh8sgXn8k"> 这个版本

问题原因是啥

**Comment by agapple** [comment]
LS正解

**Comment by ListenQ** [comment]
> LS正解

但是 canal1.1.7 同步数据到mq中 每次第一次同步数据都会重复一条，这个是什么问题？可以解决吗
