### ISSUE TITLE
canal 通过 maxscale 连接 mysql 时报错，直接连接 mysql 主库或从库正常

### ISSUE THREAD

**Issue by yuniverser** [alibaba/canal#5064]
## Question

我部署了一个主从数据库，在使用 canal 通过 maxscale 连接 mysql 时发现会报错；报错内容如下：
<img width="1202" alt="image" src="https://github.com/alibaba/canal/assets/151110090/44395731-9fc8-420d-a405-326e6ddfb328">
这种问题是否有解决方案呢？

**Comment by agapple** [comment]
看着是maxscale不支持binlog协议的转发

**Comment by yuniverser** [comment]
maxscale 有 binlog server模式，我修改模式尝试一下。谢谢
