### ISSUE TITLE
canal rabbitmQ的MQ发送会不会存在消息丢失的情况

### ISSUE THREAD

**Issue by cdma-git** [alibaba/canal#5067]
看canal 1.1.5版本的代码，发送消息的时候并没有做事务机制或者发送确认机制处理，那是不是canal发送给rabbitmq的时候是会出现消息丢失的情况
![image](https://github.com/alibaba/canal/assets/64626797/09ab6d3e-595b-4c73-9aa4-66b6b10886b7)

**Comment by agapple** [comment]
如果这里发送失败了，外层会有retry机制，通过位点管理binlog的消费

**Comment by chenyunwei1985** [comment]
没有的等发布者确认会否造成消息丢失
