### ISSUE TITLE
canal集群后多个server重复发送消息

### ISSUE THREAD

**Issue by XJFLHM** [alibaba/canal#5069]
集群后我启动了两个server，数据库变更后就往kafka发送了两条变更消息，版本是1.5
![1710241191389](https://github.com/alibaba/canal/assets/162985785/e097c73f-65bf-474a-b278-9d2496f3b594)

**Comment by wangjw1989** [comment]
遇到一样的问题，两个server在运行同一个instance

**Comment by agapple** [comment]
确认是否使用了zookeeper作为元数据？

**Comment by vhypnus** [comment]
> 确认是否使用了zookeeper作为元数据？

如果使用了zookeeper是否会发送重复数据的问题，我也遇到了

![Uploading ba91eb47-48de-402d-b61e-a6c5668fa169.jpeg…]()
