### ISSUE TITLE
desc tableName 与 show create table tableName 对比不一致

### ISSUE THREAD

**Issue by zangyk** [alibaba/canal#507]
CREATE TABLE `IM_GROUP_USER` (
  `GROUPID` int(11) NOT NULL,
  `USERID` int(11) NOT NULL,
  `MANA` int(11) DEFAULT NULL,
  `NOTE` varchar(200) COLLATE gbk_bin DEFAULT NULL,
  UNIQUE KEY `IM_GROUP_USER_INDEX` (`GROUPID`,`USERID`)
) ENGINE=InnoDB DEFAULT CHARSET=gbk COLLATE=gbk_bin , compare failed . 
 db : TableMeta [schema=imserver, table=IM_GROUP_USER, fileds=
	FieldMeta [columnName=GROUPID, columnType=int(11), defaultValue=null, nullable=false, key=true]
	FieldMeta [columnName=USERID, columnType=int(11), defaultValue=null, nullable=false, key=true]
	FieldMeta [columnName=MANA, columnType=int(11), defaultValue=null, nullable=true, key=false]
	FieldMeta [columnName=NOTE, columnType=varchar(200), defaultValue=null, nullable=true, key=false]
] 
 mem : TableMeta [schema=imserver, table=IM_GROUP_USER, fileds=
	FieldMeta [columnName=GROUPID, columnType=int(11), defaultValue=null, nullable=false, key=false]
	FieldMeta [columnName=USERID, columnType=int(11), defaultValue=null, nullable=false, key=false]
	FieldMeta [columnName=MANA, columnType=int(11), defaultValue=null, nullable=true, key=false]
	FieldMeta [columnName=NOTE, columnType=varchar(200), defaultValue=null, nullable=true, key=false]
]

**Comment by agapple** [comment]
你这mysql是啥版本来着？看上去UNIQUE KEY IM_GROUP_USER_INDEX (GROUPID,USERID)，被当做了pk，发我一下desc imserver.IM_GROUP_USER 和  show create table imserver.IM_GROUP_USER 的结果

**Comment by agapple** [comment]
我本地重现了
