### ISSUE TITLE
client-adapter 怎么运行呢？

### ISSUE THREAD

**Issue by xufei56789** [alibaba/canal#5070]
## Question

需求：
mysql 更新数据自动同步到es里

环境版本：
mysql：8.2
elasticsearch：8.12
canal-server：latest

问题描述：
现在canal-server已经成功和mysql连接，从canal-server日志上看已经开始监听mysql的binlog,  client-adapter 怎么部署运行呢？

**Comment by agapple** [comment]
多看一下wiki文档
