### ISSUE TITLE
What Time Write META LOG?

### ISSUE THREAD

**Issue by InnerCodeDBA** [alibaba/canal#5083]
2024-03-19 00:00:40.485 - clientId:1001 cursor:[mysql-bin.002119,417501,1710690978000,100149732,]

Look it the date is  2024-03-19 00:00:40.485 by meta.log

this  is 1710690978000  of mysql binlog timestamp unix time stamp    2024/3/17 23:56:18  

differ housr 24!

The 2024-03-19 00:00:40.485  is  Canal  parse mysql binlog event time ?

**Comment by agapple** [comment]
是的，理解没错
