### ISSUE TITLE
服务端启动一直失败，求助！！

### ISSUE THREAD

**Issue by hsh075623201** [alibaba/canal#512]
canal.instance.tsdb.enable无论开启还是关闭都出现如下错误：

ERROR com.alibaba.druid.pool.DruidDataSource - create connection SQLException, url: jdbc:h2:../conf/example/h2;CACHE_SIZE=1000;MODE=MYSQL;, errorCode 28000, state 28000
org.h2.jdbc.JdbcSQLException: Wrong user name or password [28000-196]

我的instance配置：
`#################################################
## mysql serverId
canal.instance.mysql.slaveId=1234
# position info
canal.instance.master.address=192.168.3.200:3306
canal.instance.master.journal.name=mysql-bin.000001
canal.instance.master.position=
canal.instance.master.timestamp=

# table meta tsdb info
canal.instance.tsdb.enable=false
canal.instance.tsdb.dir=${canal.file.data.dir:../conf}/${canal.instance.destination:}
canal.instance.tsdb.url=jdbc:h2:${canal.instance.tsdb.dir}/h2;CACHE_SIZE=1001;MODE=MYSQL;
#canal.instance.tsdb.url=jdbc:mysql://127.0.0.1:3306/Test
#canal.instance.tsdb.dbUsername=canal
#canal.instance.tsdb.dbPassword=canal

#canal.instance.standby.address =
#canal.instance.standby.journal.name =
#canal.instance.standby.position = 
#canal.instance.standby.timestamp = 
# username/password
canal.instance.dbUsername=canal
canal.instance.dbPassword=canal
canal.instance.defaultDatabaseName=
canal.instance.connectionCharset=UTF-8
# table regex
canal.instance.filter.regex=Test\\..*
# table black regex
canal.instance.filter.black.regex=
#################################################
`

**Comment by HeChuanXUPT** [comment]
>b. canal的原理是模拟自己为mysql slave，所以这里一定需要做为mysql slave的相关权限.
CREATE USER canal IDENTIFIED BY 'canal';  
GRANT SELECT, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'canal'@'%';
-- GRANT ALL PRIVILEGES ON *.* TO 'canal'@'%' ;
FLUSH PRIVILEGES;

https://github.com/alibaba/canal/wiki/QuickStart
是mysql没有设置canal用户名和密码吗?

**Comment by hsh075623201** [comment]
@HeChuanXUPT 
  你好，确认不是权限问题。

**Comment by HeChuanXUPT** [comment]
@hsh075623201 
如果不使用tsdb的话，可以尝试使用下之前的版本 1.0.19 ， 1.0.19这个我是启动成功了的

**Comment by WilliamGai** [comment]
遇到同样的问题

**Comment by hsh075623201** [comment]
@WilliamGai 注释tsdb就可以了

**Comment by wanrui** [comment]
遇到同样的问题

**Comment by mjjian0** [comment]
@hsh075623201 请问下，你是把 tsdb的全注释了吗？
我注释了然后报异常：
java.sql.SQLException: connect error, url , driverClass org.h2.Driver

**Comment by agapple** [comment]
h2的问题, 有几个反馈了 , 如果对H2比较了解的可以尝试优化解决

**Comment by agapple** [comment]
h2作为table ddl的历史版本存储时，会基于H2的默认jdbc配置
```
canal.instance.tsdb.dir=${canal.file.data.dir:../conf}/${canal.instance.destination:}
canal.instance.tsdb.url=jdbc:h2:${canal.instance.tsdb.dir}/h2;CACHE_SIZE=1000;MODE=MYSQL;
canal.instance.tsdb.dbUsername=canal
canal.instance.tsdb.dbPassword=canal
```

解读一下，就是第一次时会创建conf/$instance$/$instance.mv.db，并设置访问密码为canal/canal，如果第二次重新打开时会校验xx.mv.db是否有多进程同时使用(会出现java.lang.IllegalStateException: The file is locked)，也会校验本次的访问密码是否和第一次创建时相同

如果真遇到一些莫名其妙的问题，万能的解决办法：删除conf/对应的xx.mv.db，会重新初始化一个h2本地文件
