### ISSUE TITLE
Default use of TLSv1 in AbstractRequest.java may cause potential security and  compatibility issue.

### ISSUE THREAD

**Issue by Anderson-Xia** [alibaba/canal#5126]
## Why you need it?
We've identified that the default TLS version used in [AbstractRequest.java](https://github.com/alibaba/canal/blob/master/parse/src/main/java/com/alibaba/otter/canal/parse/inbound/mysql/rds/request/AbstractRequest.java#L198) is TLSv1, which is outdated and deprecated.

## How it could be?
Given that TLSv1 is deprecated and poses potential security risks, we recommend to update the default TLS version to a more secure alternative. 
Additionally, it's worth noting that the latest MySQL version (8.0.28) no longer supports TLSv1 and TLSv1.1 protocols, which could lead to compatibility issues if not addressed.

## Reference 
MySQL Encrypted Connection TLS Protocols and Ciphers, https://dev.mysql.com/doc/refman/8.0/en/encrypted-connection-protocols-ciphers.html

**Comment by agapple** [comment]
可以考虑提交一个PR给我
