### ISSUE TITLE
我有一个需求，需要需要使用正则匹配数据库

### ISSUE THREAD

**Issue by hssssbb** [alibaba/canal#5129]
我有一个需求，需要需要使用正则匹配数据库
我在instance 中配置的参数如下: 
canal.instance.filter.regex=test_db_.*\\.ts_dd
用来匹配以 test_db_ 开头的数据库中的 ts_dd 表，但是我发现好像实际仍然读取了所有表，
请问，有解决方案吗？
canal 版本 v1.1.5

**Comment by hirolee88** [comment]
1.canal.instance.filter.regex不生效问题
首先确认一下是不是 binlog_rows_query_log_events=ON 这个开关打开了，如果不是的话就跳过
如果是的话，修改这一行配置 canal.instance.filter.query.dml = true （默认为 false，改为 true）试试
————————————————

                            版权声明：本文为博主原创文章，遵循 CC 4.0 BY-SA 版权协议，转载请附上原文出处链接和本声明。
                        
原文链接：https://blog.csdn.net/line_on_database/article/details/127494796

**Comment by jiugem** [comment]
@agapple canal.instance.filter.query.dml 默认值是否设置为 true 更好呢？
