### ISSUE TITLE
canal client的spring版本问题

### ISSUE THREAD

**Issue by JackEggie** [alibaba/canal#515]
canal client使用的还是3.2.9.RELEASE版本的spring，如果直接使用spring4的依赖会出现奇怪的异常。需要在项目中exclude掉spring相关的依赖，这么做总觉得会在使用过程中存在一些风险。

建议：

1. 能否跟上spring大版本升级，例：spring3 -> spring4
2. 如果canal使用spring的功能很少的话，能不能将spring的依赖设置为optional的。

reference：#371

**Comment by JackEggie** [comment]
另外，我在使用过程中，logback也同样有版本冲突的问题。也同样建议变为optional的依赖。

**Comment by agapple** [comment]
LS正解
