### ISSUE TITLE
canal-1.1.7测试用例失败

### ISSUE THREAD

**Issue by rearcherr** [alibaba/canal#5151]
在编写canal rpm包 mvn package 时测试用例运行失败，帮忙确认下是测试用例是否正确
dbsync/src/test/java/com/taobao/tddl/dbsync/binlog/JsonDiffConversionTest.java
![image](https://github.com/alibaba/canal/assets/51811773/b14d93c8-0b73-4a04-876e-f16f26894a8e)
![image](https://github.com/alibaba/canal/assets/51811773/ea0321d6-00fd-4036-b190-5c80e2c98d3a)

**Comment by agapple** [comment]
主干可以通过，重新更新下代码？
