### ISSUE TITLE
多个分中心向总中心同步数据 && 打开tsdb模式会造成canal的表结构和实际表结构不一致

### ISSUE THREAD

**Issue by aiden-liu413** [alibaba/canal#5166]
## Question

背景
三个分中心向总中心同步表A（包括ddl dml）
在总中心配置三个destination讲表A的数据同步到总中心的表A

1.在分中心1 在表A新加字段test1 ，由于开启了同步。所以test1会由canal同步新建到总中心的表A 即总中心表A也存在test1了
2.后续依次在分中心2，3增加表A的test1字段。剩余对应的两个destination因为在总中心的表A中已经存在test1字段了 所以会执行失败报错导致表结构不一致。分中心2，3后续同步表A的数据 test1字段都没有数据

可以通过设置
canal.instance.tsdb.enable = false 来解决此问题吗 @agapple

**Comment by agapple** [comment]
canal.instance.tsdb.enable不是用来处理DDL同步的，你应该考虑在同步时关闭DDL复制
