### ISSUE TITLE
Could not find first log file name in binary log index file如何优化

### ISSUE THREAD

**Issue by Phoebus888** [alibaba/canal#5171]
## Question

比如我底层数据库进行切换，数据可以同步过去，binlog会进行变更，这样就会产生Could not find first log file name in binary log index file
如何修改逻辑在出现Could not find first log file name in binary log index file执行show master status 找到最新点位进行同步
这样就可以保证没有延迟情况下不会有问题产生
现在出现这种问题就相当于binlog丢失，只能重新同步
现在flink-cdc就是这样逻辑

**Comment by newpurr** [comment]
请问是怎么解决的呢？
