### ISSUE TITLE
canal adapter 的syncBatchSize和batchSize，各自有什么作用？会不会影响同步的实时性

### ISSUE THREAD

**Issue by Devildutty0922** [alibaba/canal#5172]
canal adapter 的syncBatchSize和batchSize配置解读，各自有什么作用？当源数据库变动很少，长时间达不到syncBatchSize和batchSize，是不是意味着就不会发生同步？那岂不是影响数据同步的实时性

**Comment by agapple** [comment]
canal.mq.canalBatchSize = 50
canal.mq.canalGetTimeout = 100

canalGetTimeout可以控制最长的等待时间，单位ms
