### ISSUE TITLE
初始启动日志要求提Issues

### ISSUE THREAD

**Issue by hnwkz** [alibaba/canal#518]
ERROR c.a.o.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta - pls submit github issue, show create table ddl:CREATE TABLE `REPO_VER_REFS` (
  `NODE_ID` varbinary(16) NOT NULL,
  `REFS_DATA` longblob NOT NULL,
  UNIQUE KEY `REPO_VER_REFS_IDX` (`NODE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 , compare failed . 
 db : TableMeta [schema=urule, table=REPO_VER_REFS, fileds=
	FieldMeta [columnName=NODE_ID, columnType=varbinary(16), defaultValue=null, nullable=false, key=true]
	FieldMeta [columnName=REFS_DATA, columnType=longblob, defaultValue=null, nullable=false, key=false]
] 
 mem : TableMeta [schema=urule, table=REPO_VER_REFS, fileds=
	FieldMeta [columnName=NODE_ID, columnType=varbinary(16), defaultValue=null, nullable=false, key=false]
	FieldMeta [columnName=REFS_DATA, columnType=longblob, defaultValue=null, nullable=false, key=false]
]

**Comment by agapple** [comment]
类似问题，代码已经修复
