### ISSUE TITLE
canal 1.1.7计算远程配置文件md5值和api返回不一致，导致canal server反复重启

### ISSUE THREAD

**Issue by w517424787** [alibaba/canal#5180]
### environment

* canal 1.1.7

### Issue Description
canal server启动后，异步线程默认每隔5s去监听远程配置文件，根据第一次获取到的配置文件计算md5值，计算出的md5值与配置文件返回不一致，导致canal server反复重启。

具体代码问题点：processData方法
md5 = SecurityUtil.md5String(config.content);
这计算出的md5值与api请求返回的contentMd5不一致，导致canal server反复重启。

PlainCanal newCanalConfig = configClient.findServer(lastCanalConfig.getMd5());
  if (newCanalConfig != null) {
      // 远程配置canal.properties修改重新加载整个应用
      canalStater.stop();
      Properties managerProperties = newCanalConfig.getProperties();
      // merge local
      managerProperties.putAll(properties);
      canalStater.setProperties(managerProperties);
      canalStater.start();
      lastCanalConfig = newCanalConfig;
  }

### Actual behaviour

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by agapple** [comment]
可以考虑提交一个PR给我
