### ISSUE TITLE
canal在zk中存储的timestamp时区问题咨询

### ISSUE THREAD

**Issue by ZiaZiaZiaZia** [alibaba/canal#5181]
抽取的db服务器为0时区，canal服务器为东8区。

但是zk的znode中存储的timestamp字段为东8区的时间（即canal服务器的时间），binlog名称和postition都为db服务器中的内容
znode：/otter/canal/destinations/${destination}/1001/cursor

想咨询下是为什么

canal版本：1.1.5

**Comment by agapple** [comment]
位点存储的是binlog里解析出来的时间戳，zookeeper的node节点时间戳以zk集群为准
