### ISSUE TITLE
ES7xTemplate 321行 columnItem.getOwner() 空指针

### ISSUE THREAD

**Issue by sangliuc** [alibaba/canal#5184]
* canal version
1.17 & 1.18
* mysql version
8.0.33
### Issue Description
select id as _id, name from user;
就这么简单的sql，表明没有起别名，
 源码：if (columnItem.getOwner() == null || columnItem.getColumnName() == null) {
                continue;
            }

            if (!columnItem.getOwner().equals(owner)) {
                continue;
            }
第一个continue跳过去了，而columnItem.getOwner()是null；导致第二个if判断直接空指针

### Expected behaviour
sql表名不用别名 也能同步成功

**Comment by agapple** [comment]
可以考虑提交一个PR给我

**Comment by jjkk123456** [comment]
想问问owner变量代表什么含义

**Comment by sangliuc** [comment]
你按照我的示例测试下

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年07月31日 09:25 |
| 收件人 | alibaba/canal ***@***.***> |
| 抄送人 | sangliuc ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [alibaba/canal] ES7xTemplate 321行 columnItem.getOwner() 空指针 (Issue #5184) |

想问问owner变量代表什么含义

**Comment by jjkk123456** [comment]
哦哦哦，owner是表名的别名吧

**Comment by jjkk123456** [comment]
请问这个问题已经提pr了吗

**Comment by sangliuc** [comment]
还没，最近比较忙，暂时声名别名解决业务问题

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年07月31日 11:22 |
| 收件人 | alibaba/canal ***@***.***> |
| 抄送人 | sangliuc ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [alibaba/canal] ES7xTemplate 321行 columnItem.getOwner() 空指针 (Issue #5184) |

请问这个问题已经提pr了吗

**Comment by jjkk123456** [comment]
我刚刚修好啦，我提个pr吧

**Comment by sangliuc** [comment]
好的

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年07月31日 14:21 |
| 收件人 | alibaba/canal ***@***.***> |
| 抄送人 | sangliuc ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [alibaba/canal] ES7xTemplate 321行 columnItem.getOwner() 空指针 (Issue #5184) |

我刚刚修好啦，我提个pr吧
