### ISSUE TITLE
canal adapter1.1.7 同步数据至es8.14.1。etl全量同步成功，增量同步失败，未报错，es数据未同步。

### ISSUE THREAD

**Issue by RShawshank** [alibaba/canal#5188]
## Question

这是我的配置文件信息：
  canalAdapters:
  - instance: es 
    groups:
    - groupId: g1
      outerAdapters:
      - name: logger
      - name: es8                           # or es7
        key: esKey
        hosts: http://127.0.0.1:9200               # es 集群地址, 逗号分隔
        properties:
          mode: rest # or rest         # 可指定transport模式或者rest模式
          security.auth: elastic:xxxx      # only used for rest mode
          cluster.name: elastic       # es cluster name

增量同步时canal adpater可以正常打印INFO c.a.o.canal.client.adapter.logger.LoggerAdapterExample - DML。但是没有打印Affected indexs。

**Comment by jjkk123456** [comment]
后面解决了吗
