### ISSUE TITLE
canalAdmin创建实力成功，但是后台报Name or service not known

### ISSUE THREAD

**Issue by zhangliangrr** [alibaba/canal#5189]
## Question

canal-admin中instance启动成功，但是报错
![image](https://github.com/alibaba/canal/assets/29200530/95d61757-c718-465e-ab47-4006e442a569)
问题出现原因：
进行了系统迁移，由centos系统迁移至麒麟系统；使用k8s部署canal。

**Comment by agapple** [comment]
UnknowHostException，检查一下hostname -i配置
