### ISSUE TITLE
canal对库表的perl正则过滤，为何“库名.表名”的全匹配方式，获取不到日志？

### ISSUE THREAD

**Issue by ZhiXingHeYiApple** [alibaba/canal#519]
![image](https://user-images.githubusercontent.com/20380664/35789590-2cec3a0e-0a78-11e8-858c-54bf51ba011b.png)
mysql数据解析关注的表为可以通过"库名称\\..*"方式精确到具体的库，但使用mysql.test1,mysql.test2 这种方式无法解析对应表的日志？是不是canal文档上写的有出入？？

**Comment by hnwkz** [comment]
是否考虑下面这个点：
void subscribe(String filter)
               throws com.alibaba.otter.canal.protocol.exception.CanalClientException
客户端订阅，重复订阅时会更新对应的filter信息
 说明：
 a. 如果本次订阅中filter信息为空，则直接使用canal server服务端配置的filter信息
 b. 如果本次订阅中filter信息不为空，目前会直接替换canal server服务端配置的filter信息，以本次提交的为准
 
 TODO: 后续可以考虑，如果本次提交的filter不为空，在执行过滤时，是对canal server filter + 本次filter的交集处理，达到只取1份binlog数据，多个客户端消费不同的表
 
参数:
clientIdentity -
抛出:
com.alibaba.otter.canal.protocol.exception.CanalClientException

**Comment by fefine** [comment]
用mysql\\.test1，mysql\\.test2呢？

**Comment by agapple** [comment]
参考FAQ: https://github.com/alibaba/canal/wiki/FAQ
