### ISSUE TITLE
【v1.1.7】实例启动报错create connection SQLException, url: , errorCode 0, state null

### ISSUE THREAD

**Issue by panzehui** [alibaba/canal#5210]
## Question

一摸一样的的实例配置，一个正常启动，另外一个实例时启动报错。
![image](https://github.com/user-attachments/assets/eca8ac27-5b17-4f26-bfcc-7cf2a4b4deb7)

**Comment by agapple** [comment]
1.1.7老版本的已知问题，可以升级最新主干1.1.8

**Comment by helpisyou** [comment]
只能升级解决吗
