### ISSUE TITLE
kafka可能存在的数据覆盖现象

### ISSUE THREAD

**Issue by lwd-coding** [alibaba/canal#5213]
## Question

当poll很多数据，处理时间很长，这期间又发生网络问题导致心跳无法正常续期，server发现消费者续期时间已经超过session time out则会将该消费者踢出消费组重新触发分区的rebalance，此时该分区就会分配给其它消费者；这时候就会出现多个消费者同时消费同个分区的数据现象

**Comment by DongJigong** [comment]
这个问题应该是kafka的问题，kafka同一个topic 多个groupid，消息不会重复消费的，只会被其中一个groupid消费

**Comment by agapple** [comment]
LS正解
