### ISSUE TITLE
canal-server v1.1.7版本启动报错Failed to get D-Bus connection: Operation not permitted

### ISSUE THREAD

**Issue by Gshelldong** [alibaba/canal#5233]
## Question

# v1.1.6 基础镜像
canal/osadmin:v1 
docker/image/alidata/bin/main.sh

# 使用下面的命令启动没有问题
service sshd start
service crond start

# v1.1.7 基础镜像没有service 也没有systemd
canal/osadmin:v3-amd64
但是在启动脚本中使用下面的命令启动
docker/image/alidata/bin/main.sh
systemctl start sshd
systemctl start crond
在k8s中运行或者在docker中导致报错，相关文档中也没有说明这两个功能是用来干嘛的。
==> INIT DEFAULT
Failed to get D-Bus connection: Operation not permitted
Failed to get D-Bus connection: Operation not permitted
麻烦说明下这两个服务是否对canal-admin的功能有影响？
或者在直接去掉这sshd和crond服务，也可以减小镜像大小。
Thanks！！！
xiaoliao.gong@qq.com

**Comment by agapple** [comment]
这个报错可以忽略
