### ISSUE TITLE
在开启binlog_rows_query_log_events开关后解析binlog全部都是query类型

### ISSUE THREAD

**Issue by JackEggie** [alibaba/canal#524]
现象与 #517 相同 

在开启binlog_rows_query_log_events开关后，客户端抓到的dml语句为EventType.QUERY 类型，并且rowChange.getIsDdl()为false。

由于项目中需要针对ddl语句做不同的处理，因此想确认下，ddl语句的判断条件是什么？wiki中的 ![](https://camo.githubusercontent.com/73b451bd00ff40ec80ed3bd4904d4052fd34fa03/687474703a2f2f646c322e69746579652e636f6d2f75706c6f61642f6174746163686d656e742f303039302f363438332f36316366313161622d313932342d333730352d386236662d6534363431316263363036612e6a7067) 判断条件在这种状况下显然有问题。

**Comment by agapple** [comment]
isDdl的标

**Comment by mossGKX** [comment]
这个问题解决了吗，我的现在也是出现这个问题 ，数据库是5.8 的 ，

mysqld.cnf 配置如下：
symbolic-links = 0
server-id = 1
log-bin = /var/lib/mysql/mysql-bin
binlog_format = ROW
binlog-rows-query-log-events = true

但是拿到的 语句明明是update 语句 ，rowChange.getEventType() 确实query 类型的.

求解答？？？？？
