### ISSUE TITLE
多instance只有一个可以正常启动

### ISSUE THREAD

**Issue by GoSimplicity** [alibaba/canal#5242]
今天新增两个instance，启动后发现只有一个日志输出正常，其他的全部输出连接超时
![image](https://github.com/user-attachments/assets/83869738-0e63-400d-9a25-4bb11bf3135e)
![image](https://github.com/user-attachments/assets/f0daceae-4c30-4ffb-ba1b-8c1119c7e396)
只有一个instance是正常的，配置文件基本都一样只改了slaveId和mq.topic，路径什么的都没问题，但就是每次只有一个正常启动，请问这是什么问题该如何解决
![image](https://github.com/user-attachments/assets/1a4607c3-e766-4328-98d8-ce399763ac07)

**Comment by xie-wei-jun** [comment]
解决了嘛？大佬  我遇到同样问题

**Comment by GoSimplicity** [comment]
> 解决了嘛？大佬 我遇到同样问题

没有 已经麻了

**Comment by China-Wei** [comment]
> > 解决了嘛？大佬 我遇到同样问题
> 
> 没有 已经麻了

没人维护了吗，这么多问题没人回复

**Comment by agapple** [comment]
升级最新的1.1.8主干版本，已知问题
