### ISSUE TITLE
canal-1.1.8支持SSL连接数据库，如何配置

### ISSUE THREAD

**Issue by shidousanxia** [alibaba/canal#5244]
请问有相关文档吗，通过什么参数配置SSL？

**Comment by shidousanxia** [comment]
> [zhuSilence@d5dba78](https://github.com/zhuSilence/canal/commit/d5dba78b78183b7de1472cdc6500ac2c8dba6b66) ， 验证可以使用
谢谢，但我是想问和mysql建立连接的

**Comment by oyy123440** [comment]
我也想问下，canal如何认证连接mysql

**Comment by oyy123440** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by agapple** [comment]
主干支持通过ssl链接mysql

**Comment by oyy123440** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
