### ISSUE TITLE
增加普罗米修斯监控后，canal服务器出现大量的close_wait导致故障。

### ISSUE THREAD

**Issue by laomachaoshou** [alibaba/canal#5254]
## Question

监控为普罗米修斯
使用telegraf收集canal  metrics端口数据。
[root@######~]# netstat -antp |awk  '{print $6}'|sort|uniq -c
  79705 CLOSE_WAIT

**Comment by agapple** [comment]
检查下sysctl参数，可以将keepalive相关参数调快一点，让linux tcp机制尽早发现半开链接并回收

**Comment by HelonLee135** [comment]
老哥，canal 没有export 吧，你咋接入prometheis 监控的，难道仅仅是个端口监控么？
