### ISSUE TITLE
关于配置文件中的canal.instance.filter.regex和客户端中的subscribe的使用问题

### ISSUE THREAD

**Issue by youbeiyazhile** [alibaba/canal#5258]
版本：1.1.4
问题：
在使用过程中发现，如果canal.instance.filter.regex和subscribe时发现，如果两个同时存在，虽然subscribe会覆盖掉canal.instance.filter.regex配置，但是在第一次使用canal的时候，如果我先启动了canal服务，然后再启动自己的项目，那么就会先执行canal.instance.filter.regex配置去过滤mysql日志，而后再使用subscribe，这就会导致明明subscribe没有配置某个规则，但是还是被监听到了。

比如我只想要监听test_db.test表，在subscribe设置的也是这个表，canal.instance.filter.regex保持不变（默认所有表），我先启动了canal服务，然后改动了demo_db.demo表中的数据，这个时候再启动我的项目，那么我的项目就会收到来自demo_db.demo表的更新信息。

我不清楚这算不算时应该bug或者机制就是这样....

**Comment by agapple** [comment]
设计的问题，查看FAQ
