### ISSUE TITLE
message=Access denied for user 'xxx'@'%' to database 'performance_schema', sqlState=42000, sqlStateMarker=#

### ISSUE THREAD

**Issue by Moexi2019** [alibaba/canal#5261]
我想问下instance日志为什么报账号没有database 'performance_schema'的权限 为什么要这个权限

**Comment by Moexi2019** [comment]
![image](https://github.com/user-attachments/assets/0d06a4d8-8a72-4e78-b17f-36fc5e511a60)
s

**Comment by Moexi2019** [comment]
v1.1.6
v1.1.7
的server镜像都有一样的问题

**Comment by sunjiajie** [comment]
<img width="575" alt="Image" src="https://github.com/user-attachments/assets/70257761-0a4d-4798-9452-55b3d406ec63" />
我加了订阅规则，也还是报这个错
