### ISSUE TITLE
Instance假死

### ISSUE THREAD

**Issue by fefine** [alibaba/canal#527]
Server端运行正常，但是Instance全部线程无响应，日志等级开启为Info，并未发现异常日志
这是Server日志：
![http://7xo1fz.com1.z0.glb.clouddn.com/server.png](http://7xo1fz.com1.z0.glb.clouddn.com/server.png)
这是Instance日志：
![http://7xo1fz.com1.z0.glb.clouddn.com/server.png](http://7xo1fz.com1.z0.glb.clouddn.com/instance.png)
我在Instance中也开启了另外一个定时的线程，但是在卡死的时间内毫无响应。数据库在今天下午并无其他特殊操作。
问一下这有可能是什么问题？

**Comment by agapple** [comment]
没数据变更？

**Comment by fefine** [comment]
有，数据一直在变更

**Comment by handmail** [comment]
我这是canal server 启动时正常，binlog会被client消费掉。但如果几个小时，一直没有binlong产生，再产生binlog话，server就不会读到这些binlog。

**Comment by handmail** [comment]
@agapple 
如果没有数据变更，隔一段时间instance就不会再消费binlog了吧？
我测试的结果，为了避免这种情况，需要enable detecting，并使用 insert retl.xdual做为心跳sql.
还有其他的解决方法吗？

**Comment by agapple** [comment]
你用的是自己打包的1.0.25版本？

**Comment by fefine** [comment]
是的，下载的源码打包

**Comment by agapple** [comment]
@fefine 使用最新的26  alpha 2代码再试试，对于tcp加了so_timeout机制，可以响应长时间无binlog位点被mysql server主动断开的问题

**Comment by NPCSun** [comment]
Mark
