### ISSUE TITLE
canal1.1.5 无法去除mq中type: query的记录

### ISSUE THREAD

**Issue by helpisyou** [alibaba/canal#5284]
canal-server配置是
#binlog filter config
canal.instance.filter.druid.ddl = true
canal.instance.filter.query.dcl = true
canal.instance.filter.query.dml = true
canal.instance.filter.query.ddl = true
canal.instance.filter.table.error = false
canal.instance.filter.rows = false
canal.instance.filter.transaction.entry = true
canal.instance.filter.dml.insert = false
canal.instance.filter.dml.update = false
canal.instance.filter.dml.delete = false
# table regex
canal.instance.filter.regex=product\\.product,product\\.cancl_test

查看RDS binlog_rows_query_log_events的配置是OFF
重新加载canal配置后
一直都是显示以下的记录，无法进行过滤
<img width="1200" alt="WechatIMG2085" src="https://github.com/user-attachments/assets/d2ebfffd-b81e-4b81-93ea-0b4efb791db7">

**Comment by agapple** [comment]
canal.instance.filter.query.dml = true，照理是这个参数控制的，可以考虑试下最新版本
