### ISSUE TITLE
因canal消费者是单实例，目前消息都堆积在队列0上，导致并发问题增加。

### ISSUE THREAD

**Issue by Freddysir** [alibaba/canal#5287]
请问如何配置Canal或者是Rocketmq，让其123队列有消息传输？
![企业微信截图_17282940064583](https://github.com/user-attachments/assets/588d1a0d-df8f-453e-ad71-3738e14342dc)

**Comment by lostchai** [comment]
Canal server，instance 可以配置
```
canal.mq.partitionsNum=4
canal.mq.partitionHash=db.tableA:id,db.tableB:user_id
```
这只是示例，具体看文档解释，自己配置下，https://github.com/alibaba/canal/wiki/Canal-Kafka-RocketMQ-QuickStart

**Comment by lostchai** [comment]
但是一般情况下，是adapter out部分卡住了，才会导致堆积
