### ISSUE TITLE
数据同步失效 ERROR c.a.otter.canal.server.netty.handler.SessionHandler - something goes wrong with channel

### ISSUE THREAD

**Issue by uuz21181522** [alibaba/canal#5303]
## Question

你好！我使用了Canal作为MySQL和一个搜索型数据库MeiliSearch的中间件以实现数据同步。
我使用了一个while循环线程来定时捕捉binlog新增数据，一开始能够正常的数据同步，但如果这个线程or客户端（我不太确定是哪种情况）被意外终止，再次使用canal时数据捕获就会失效，并且弹出如下错误：

ERROR c.a.otter.canal.server.netty.handler.SessionHandler - something goes wrong with channel:[id: 0x23d9cad9, /127.0.0.1:46472 :> /127.0.0.1:11111], exception=java.nio.channels.ClosedChannelException

我发现在每次意外终止时，如果重置Mysql的binlog并删除canal的meta.dat，然后重新开启canal客户端，这个报错就会消失。

**Comment by dyrnq** [comment]
- <https://github.com/alibaba/canal/issues/1185>
- <https://github.com/alibaba/canal/issues/289>
