### ISSUE TITLE
mysql 5.7.36 ，canal 1.1.8读取binlog到rocketMQ缺失部分ddl语句（仅有alter修改表结构语句）

### ISSUE THREAD

**Issue by Zamas-cmd** [alibaba/canal#5305]
配置如下
![image](https://github.com/user-attachments/assets/f0c416d7-6edd-4ac2-aab0-391eaa8241ec)

**Comment by dyrnq** [comment]
是倒入到哪个topic了? 这俩参数看看是怎么配置了啊
```bash
canal.mq.topic
canal.mq.dynamicTopic
```

**Comment by Zamas-cmd** [comment]
> 是倒入到哪个topic了? 这俩参数看看是怎么配置了啊
> 
> ```shell
> canal.mq.topic
> canal.mq.dynamicTopic
> ```

![image](https://github.com/user-attachments/assets/6f1ce0c6-cad0-4a12-b0f9-38256beb0529)

**Comment by dyrnq** [comment]
我用1.1.8-alpha-3的，没有你这个问题啊

**Comment by Zamas-cmd** [comment]
解决了  配置canal只关注了固定的几个表  配置成整库就行了
