### ISSUE TITLE
监听mariadb变化，data字段和old字段长度不一致

### ISSUE THREAD

**Issue by tigerfsh** [alibaba/canal#5309]
![image](https://github.com/user-attachments/assets/2415114f-0ca2-4fd2-a1e9-1e3d136e6367)

### environment

* canal version 1.1.4
* mariadb version 10.3.14

### Issue Description

监听mariadb特定表的字段变化情况
### Steps to reproduce
批量更新，但是包含新值和旧值一样的情况
### Expected behaviour
data和old的长度一致，如果没变化，old中保留一个空字典

**Comment by agapple** [comment]
印象中有修复过，优先用新版本测试下
