### ISSUE TITLE
想问一下如果MemoryEventStoreWithBuffer中bufferMemUnit=16 *1024,会造成程序运行一段时间后卡主的情况吗？

### ISSUE THREAD

**Issue by weichong-maoxiaotong** [alibaba/canal#531]

**Comment by weichong-maoxiaotong** [comment]
MemoryEventStoreWithBuffer中，bufferSize    = 16 * 1024，bufferMemUnit=16 *1024，maxMemSize = batchSize * bufferMemUnit =  16 * 1024 * 16 *1024 ， 程序在正常运行2个多小时后卡住，会有mysql数据库 kill掉 socket 链接爆出，无其他明显异常 。 请问下是这个原因导致吗？

**Comment by fefine** [comment]
server的机器内存多大？

**Comment by weichong-maoxiaotong** [comment]
server jvm 内存配了8G，同步的数据库 binlog文件大小一天有80个G左右。


发自网易邮箱大师
在2018年02月22日 09:45，fefine 写道:

server的机器内存多大？

**Comment by fefine** [comment]
我这边也是出现了这样的问题, 但是不确定是什么地方的。

**Comment by weichong-maoxiaotong** [comment]
你的bufferMemUnit 配置为多少？
在2018年02月23日 09:27，fefine 写道:

我这边也是出现了这样的问题, 但是不确定是什么地方的。

**Comment by fefine** [comment]
默认配置，bufferSize = 16 * 1024，bufferMemUnit= 1024，这两个乘积是16MB，不应该出现内存不够的问题。

**Comment by weichong-maoxiaotong** [comment]
你那里卡住 表现为 什么症状？

**Comment by fefine** [comment]
你看一下这个issue[Instance假死](https://github.com/alibaba/canal/issues/527)

**Comment by agapple** [comment]
看着有点像socket超时卡主的问题，可以尝试一下最新的1.1.1版本
