### ISSUE TITLE
阿里云 rds oss binlog 有配置成功吗

### ISSUE THREAD

**Issue by callmedba** [alibaba/canal#5311]
## Question
canal 1.1.7 版本 

阅读过canal wiki和issue 以及google搜索到的多篇文章 ，配置 ak / sk 以及 rds id 

尝试过多次 ，无论是 位点 还是 时间戳 方式 ，均未成功从 oss 拉取到 rds 本地不存在但oss存在的binlog

请问有大佬成功过吗 ？

**Comment by callmedba** [comment]
主要是想确认 ：这条路能走通吗 ？ 如果可以，就再多尝试几次 ；如果不通 ，就放弃  😄

**Comment by cheng6563** [comment]
毛日志没打，你开个远程debug端口连上去直接单步调试就知道了

**Comment by cheng6563** [comment]
调了半天ok了，时间戳方式，要做这些：
1.示例配置文件里的配置项是错的，ak，sk要这么配置：
```
canal.instance.rds.instanceId=rm-12345
canal.aliyun.accesskey=123
canal.aliyun.secretkey=123456
```
2.给RAM账号加权限：
https://help.aliyun.com/zh/rds/apsaradb-rds-for-mysql/grant-backup-file-download-permissions-to-a-ram-user-with-read-only-permissions


再不行就远程调源码，主要看2个地方：
1. RdsBinlogEventParserProxy 看ak，sk有没有正确注入
2. RdsLocalBinlogEventParser 看有没有报错
