### ISSUE TITLE
canal-1.1.5使用一段时间不同步数据，没有报错信息

### ISSUE THREAD

**Issue by wuwei0727** [alibaba/canal#5326]
- [x] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment

* canal version 1.1.5
* mysql version 5.5.6

### Issue Description
为什么calal不同步数据？进程过段时间就会杀掉了。也没有报错日志。运行一段时间就会这样

### Actual behaviour

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by wuwei0727** [comment]
哪里可以看日志什么导致？目前排查不到。没有主动关掉calal进程。canal也没有生成对应的报错信息啥的

**Comment by dikeqin** [comment]
把deployer和adapter的日志级别调成info，打印出日志定位下

**Comment by wuwei0727** [comment]
在哪调？在源代码里面？

**Comment by dikeqin** [comment]
conf目录下有个logback.xml
![1732694648947](https://github.com/user-attachments/assets/c05f1b19-a1e1-4d73-83e3-ccc7f861e147)

**Comment by wuwei0727** [comment]
logback.xml
![image](https://github.com/user-attachments/assets/21f2ebb6-639b-4d30-bbe0-b88d4e156621)
![image](https://github.com/user-attachments/assets/eb77fddd-a492-470e-b68c-a4b3c4b0e139)

**Comment by wuwei0727** [comment]
每次用一段时间就不同步数据。但是进程还在。我查找搜索进程又找不到。然后启动，有提示我已经存在，需要结束掉

**Comment by dikeqin** [comment]
没有日志么？

**Comment by wuwei0727** [comment]
没有。没有任何报错

**Comment by dikeqin** [comment]
logs目录下？

**Comment by wuwei0727** [comment]
![image](https://github.com/user-attachments/assets/b01dc00c-28f8-49f8-ada4-0caede148798)
这是之前的日志。我看
![image](https://github.com/user-attachments/assets/26de500d-98b4-4958-b57e-8ac616fcf434)
了文件夹里面的日志没有报错，就似于这样断续的日志。

**Comment by dikeqin** [comment]
看下是不是你的服务器没有存储空间了。

**Comment by wuwei0727** [comment]
![image](https://github.com/user-attachments/assets/04851495-99e7-44f9-a0ae-1648dd157015)
内存还够

**Comment by dikeqin** [comment]
存储，df -h

**Comment by wuwei0727** [comment]
![Screenshot_2024-11-27-21-49-15-038_com netease uuremote](https://github.com/user-attachments/assets/778511d9-c9c8-4655-b1bf-c154df3b9651)
用的是有点多。这个会影响？日志生成不了就会这样？

**Comment by dikeqin** [comment]
没占满就没事，你可以看下example.log39880...的最后修改时间？还有它多大？

**Comment by wuwei0727** [comment]
图片是之前的，后面我清空日志重启了。现在有复现了。没有错误日志

**Comment by wuwei0727** [comment]
抱歉，我刚看到了错误日志：2024-11-28 15:38:23.294 [Thread-4] ERROR c.a.otter.canal.adapter.launcher.loader.AdapterProcessor - com.alibaba.otter.canal.protocol.exception.CanalClientException: java.io.IOException: 断开的管道 Error sync but ACK!

**Comment by wuwei0727** [comment]
已经解决了，重启deployer和adapter
