### ISSUE TITLE
canal启动报错ERROR com.alibaba.druid.pool.DruidDataSource - create connection RuntimeException

### ISSUE THREAD

**Issue by GoSimplicity** [alibaba/canal#5333]
<img width="1239" alt="image" src="https://github.com/user-attachments/assets/7415ffc1-b4d1-47aa-a921-169ce6531b0b">
<img width="1253" alt="Snipaste_2024-11-30_20-56-18" src="https://github.com/user-attachments/assets/266eb30e-b770-4fad-94b4-c982a0491705">

1.1.7版本问题出现

**Comment by HengGeZhiZou** [comment]
问题解决了吗，我也遇到了

**Comment by GoSimplicity** [comment]
> 问题解决了吗，我也遇到了

版本的问题 1.1.6版本就不会出现了

**Comment by agapple** [comment]
1.1.7版本的已知问题，遇到多个destination配置时会出现并发NPE问题，升级1.1.8即可
