### ISSUE TITLE
mysql binlog中blob数据丢失

### ISSUE THREAD

**Issue by hardWorkMe** [alibaba/canal#5346]
## Question

这是使用base64转换保证数据不会丢失 为啥开发者不这样做呢 直接使用ISO_8859_1 这样是不可逆的导致非文体数据丢失了
![Uploading Snipaste_2024-12-09_14-53-08.png…]()

**Comment by agapple** [comment]
历史设计问题，考虑兼容历史版本，不建议做修改了
