### ISSUE TITLE
SocketChannel中cache的一些问题

### ISSUE THREAD

**Issue by lcybo** [alibaba/canal#537]
作者你好！
最近项目也遇到了pr[#487](https://github.com/alibaba/canal/pull/487)中的问题，如果client消费不够快，canal server会将directByteBuf扩容到溢出。
pr[#487](https://github.com/alibaba/canal/pull/487)确实能解决问题，但会引发出pr[#536](https://github.com/alibaba/canal/pull/536)的问题。
pr[#536](https://github.com/alibaba/canal/pull/536) 有点问题：
1. MASTER_HEARTBEAT_PERIOD在使用change master to语句时的单位才是秒，canal不能使用change master to只能用set @MASTER_HEARTBEAT_PERIOD，单位是纳秒，可以测试一下。
2. 在读的时候动态去根据packetSize去调整ByteBuf，逻辑比较复杂。其实可以根据maxThreeBytes(略小于16M)直接设置初始capacity，结合pr[#487](https://github.com/alibaba/canal/pull/487)就可以了。
参见pr[#539](https://github.com/alibaba/canal/pull/539)

BTW，dump线程使用netty+nio让这里的代码复杂化了。直接用InputStream，然后设置一个较短的SO_TIMEOUT，比如1秒
1. 对于中断的场景：
try {
     return in.read(bytes, index, length);
} catch (SocketTimeoutException e) {
     //每个1s检查线程是否被中断
}
2. 对于需要timeout的场景：
try {
     return in.read(bytes, index, length);
} catch (SocketTimeoutException e) {
     //和现在的实现类似，判断accumulatedWaitTime+SO_TIMEOUT是否超过real timeout
}
这样可以应对中断场景和闪断阻塞的问题了，实现也会比较简单（感觉dump IO出的问题比较多）。
这只是我的proposal哈。

**Comment by agapple** [comment]
已经合并了PR代码
