### ISSUE TITLE
group模式下有时候数据库数据变动无法读取

### ISSUE THREAD

**Issue by wkxydcg** [alibaba/canal#540]
场景:两台机器 
机器一 ：部署canal server 和mysql1
机器二：部署 mysql2

instance.properties内容如下
canal.instance.master1.address=127.0.0.1:3306
canal.instance.master2.address=host2:3306

部署了canal server的那台机器数据库变动无法读取到

如果instance.properties修改为
canal.instance.master1.address=host1:3306
canal.instance.master2.address=host2:3306
则可以正确读取 

不知道是我配置问题 还是代码bug

**Comment by agapple** [comment]
基本未环境问题
