### ISSUE TITLE
canal1.0.25 在zookeeper 中不创建 cursor  不更新binlog位置信息

### ISSUE THREAD

**Issue by yuyetingqin** [alibaba/canal#541]
开始使用的是 canal_1.0.24,   zk_3.4.10中有cursor 节点，也有binlog位置信息(mysql_5.7.20)， 但是不更新zk中的binlog位置信息。后来升级到canal_1.0.25 还是不更新， 然后手动删除了 zk 下的 /otter 目录， 重新启动canal 结果都不创建 cursor 节点。  配置过程参考 https://github.com/alibaba/canal/wiki/AdminGuide  地址中写的。

**Comment by agapple** [comment]
1.0.25+版本之后默认启动时，会有一个定位位点的过程，https://github.com/alibaba/canal/releases/tag/canal-1.0.26-preview-2，使用这个版本的包试试
