### ISSUE TITLE
canal无法启动,mysql版本:5.6.39 ,使用canal版本1.0.25

### ISSUE THREAD

**Issue by hzfengjian** [alibaba/canal#544]
如下

**Comment by hzfengjian** [comment]
是不是重启后就无法连接上mysql了,一定要重启mysql才可以呢?

**Comment by agapple** [comment]
必现？

**Comment by agapple** [comment]
https://github.com/alibaba/canal/releases/tag/canal-1.0.26-preview-2，使用这个版本的包试试

**Comment by hzfengjian** [comment]
必现,这个包我试试,谢谢

**Comment by toruneko** [comment]
我也碰到这个问题，总是卡在读取位点之后的reconnect或者connect读位点。
