### ISSUE TITLE
[question]请问 canal 可以订阅从库的 binlog吗？

### ISSUE THREAD

**Issue by smileMrLee** [alibaba/canal#545]
canal 是以从库的角色对主库订阅 bin-log，现在我有两个疑问：
1.canal 是否支持订阅从库的bin-log？
2.canal 订阅主库的 bin-log 对主库的性能损耗，是否有必要迁移到订阅从库bin-log？

有哪位试验过订阅从库bin-log的，帮帮忙分析下，谢谢了。

**Comment by yookacn** [comment]
canal 是否支持订阅从库的bin-log？我也想知道这个问题。
目前我们有一个需求是把很多不同区域的库同步到一个总库，也在考虑canal怎么用一个客户端监听多个服务端的问题。
目前看example里面的集群客户端是一种主备模式，也不满足这种需求。
但是如果启动多个CanalConnectors应该可以解决吧。

**Comment by smileMrLee** [comment]
@yookacn 你是想一个canal-server，订阅多个master实例吗？

**Comment by yookacn** [comment]
@smileMrLee谢谢相告，我之前还没考虑到从服务端订阅多个实例，翻了一下代码找到了。这个可以满足我的需求。

**Comment by LintianShi** [comment]
@smileMrLee 请问"canal 是否支持订阅从库的bin-log?"这个问题有答案了吗？我也遇到了这个需求
