### ISSUE TITLE
执行有注释的ddl语句，canal解析ddl eventType为QUERY，binlog为row模式，是否是bug？

### ISSUE THREAD

**Issue by liuwenfeng554** [alibaba/canal#551]
**canal解析**
执行语句（带有注释）：
#测试start
#2018-02-22
#测试end
alter table test_2018 add loan_amount_backstage_adjust1 varchar(64) DEFAULT NULL COMMENT '测试内容：1：无，2：有' 

解析结果：
eventType: QUERY
isDdl：false
sql: "#\305\233\304\266\304\215\305\244\304\256\304\223start\r\n#2018-02-22\r\n#\305\233\304\266\304\215\305\244\304\256\304\223end\r\nalter table test_2018 add loan_amount_backstage_adjust varchar(64) DEFAULT NULL COMMENT \'\305\233\304\266\304\215\305\244\304\256\304\223\305\232\303\234\303\226\305\232\304\243\304\273\303\224\304\276\303\2661\303\224\304\276\303\266\305\233\303\263\342\200\240\303\224\304\276\304\2062\303\224\304\276\303\266\305\233\303\272\304\214\'"
ddlSchemaName: "test"
——————————————————————————————————————————
执行语句（无注释）：
alter table test_2018 add loan_amount_backstage_adjust1 varchar(64) DEFAULT NULL COMMENT '测试内容：1：无，2：有' 

解析结果：
eventType: ALTER
isDdl: true
sql: "alter table test_2018 add loan_amount_backstage_adjust1 varchar(64) DEFAULT NULL COMMENT \'\305\233\304\266\304\215\305\244\304\256\304\223\305\232\303\234\303\226\305\232\304\243\304\273\303\224\304\276\303\2661\303\224\304\276\303\266\305\233\303\263\342\200\240\303\224\304\276\304\2062\303\224\304\276\303\266\305\233\303\272\304\214\'"
ddlSchemaName: "test"

canal解析ddl eventType为QUERY，binlog且为row模式，insert update delete 都正常，这个是canal未考虑到吗?

**Comment by fefine** [comment]
mysql什么版本？

**Comment by agapple** [comment]
是带着#号的注释么？

**Comment by liuwenfeng554** [comment]
@agapple  是的

**Comment by liuwenfeng554** [comment]
@fefine 5.6.29

**Comment by liuwenfeng554** [comment]
@agapple 只要带有#号的注释 解析eventType: QUERY

**Comment by agapple** [comment]
升级canal到最新的版本，可以解决

**Comment by renjin1984** [comment]
@liuwenfeng554 ,感觉这个问题算一个坑，请问升级了解决了吗？

**Comment by liuwenfeng554** [comment]
@renjin1984 据说新的版本  还不够稳定  暂时没升  后续如果有时间看看
