### ISSUE TITLE
bug实在太多，canal.instance.master.position不起作用，也不报出一点有用的信息。

### ISSUE THREAD

**Issue by lchb369** [alibaba/canal#552]
canal.instance.master.journal.name=mysql-bin.000001
canal.instance.master.position=1
canal.instance.master.timestamp=1509862400000 
设置了偏移量但是不起作用，还是从总后一行开始扫描。
WARN  c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - prepare to find start position just last position

**Comment by agapple** [comment]
position最小值是4

**Comment by shitzman** [comment]
服务启动后修改instance.properties文件，需要清除meta.dat文件，才能重新获取配置的偏移量。
