### ISSUE TITLE
Centos下编不过

### ISSUE THREAD

**Issue by lchb369** [alibaba/canal#556]
[INFO] Total time: 2.336s
[INFO] Finished at: Thu Mar 15 13:48:55 CST 2018
[INFO] Final Memory: 18M/248M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project canal.parse: Could not resolve dependencies for project com.alibaba.otter:canal.parse:jar:1.0.26-SNAPSHOT: Failed to collect dependencies for [com.alibaba.otter:canal.common:jar:1.0.26-SNAPSHOT (compile), com.alibaba.otter:canal.protocol:jar:1.0.26-SNAPSHOT (compile), com.alibaba.otter:canal.meta:jar:1.0.26-SNAPSHOT (compile), com.alibaba.otter:canal.sink:jar:1.0.26-SNAPSHOT (compile), com.alibaba.otter:canal.parse.dbsync:jar:1.0.26-SNAPSHOT (compile), com.alibaba.otter:canal.filter:jar:1.0.26-SNAPSHOT (compile), com.alibaba.otter:canal.parse.driver:jar:1.0.26-SNAPSHOT (compile), com.alibaba:druid:jar:1.1.9 (compile), com.alibaba.fastsql:fastsql:jar:2.0.0_preview_135 (compile), mysql:mysql-connector-java:jar:5.1.40 (compile), org.apache.ibatis:ibatis-sqlmap:jar:2.3.4.726 (compile), com.h2database:h2:jar:1.4.196 (compile), org.apache.httpcomponents:httpclient:jar:4.5.1 (compile), org.apache.commons:commons-compress:jar:1.9 (compile), junit:junit:jar:4.12 (test), org.springframework:spring-test:jar:3.2.9.RELEASE (test)]: Failed to read artifact descriptor for com.alibaba.fastsql:fastsql:jar:2.0.0_preview_135: Could not transfer artifact com.alibaba.fastsql:fastsql:pom:2.0.0_preview_135 from/to alibaba (http://code.alibabatech.com/mvn/releases/): Connection to http://code.alibabatech.com refused: Connection refused (Connection refused) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]

**Comment by agapple** [comment]
重新更新一下代码，fastsql代码已经上传到maven仓库
