### ISSUE TITLE
com.alibaba.otter.canal.parse.exception.CanalParseException: parse row data failed.

### ISSUE THREAD

**Issue by KimHu01** [alibaba/canal#558]
com.alibaba.otter.canal.parse.exception.CanalParseException: parse row data failed.

**Comment by agapple** [comment]
更多的内容描述啊

**Comment by KimHu01** [comment]
![image](https://user-images.githubusercontent.com/18360996/37639699-6a6d3832-2c4d-11e8-9004-32a054adc0de.png)

**Comment by KimHu01** [comment]
otter还经常有假死现象，没有任何日志，channel没有挂起，pipeline也是工作中，但是当源库数据变化后，没有任何操作。重启channel之后基本就能恢复，不知道这是什么原因

**Comment by KimHu01** [comment]
otter manager，我不知道是不是我们用的方式不对。假如我有上百张表需要同步数据，没有更快捷的配置办法么？只能一个一个的搞？

**Comment by KimHu01** [comment]
otter的日志部分，建议加强，一大堆日志但却没有太多有价值信息输出
