### ISSUE TITLE
canal1.0.26/1.0.25 删除meta.dat 设定canal.instance.master.timestamp为1522209915000

### ISSUE THREAD

**Issue by harden123** [alibaba/canal#568]
启动后发现读取canal消息一会后，就读取到message的real size远远少于设定的batchSize，有时候甚至result is null。排除mysql的binlog记录数不够，有什么原因吗？

**Comment by harden123** [comment]
debug到SinkFunction.sink(EVENT event),每次event里解析出来的entry只有2条，拉取速度太慢了。

**Comment by agapple** [comment]
real size是按照内存大小获取的，非记录数
