### ISSUE TITLE
java.net.SocketTimeoutException

### ISSUE THREAD

**Issue by 123shenearth** [alibaba/canal#571]
1、canal 的server和client 跑一段时间之后出现这个异常，重启之后依然报这个异常，重新删掉meta.dat重新启动之后又有数据了请问这是为啥？
2、canal 不管是网络还是物理机出问题了，如何保证数据不丢失。
![default](https://user-images.githubusercontent.com/23053967/38133429-c0a550e4-3441-11e8-8080-79e82950539e.png)
如图我想从该位点重新开始同步数据，重启不好用，该如何做？

**Comment by agapple** [comment]
多看一下wiki
