### ISSUE TITLE
canal server 取不到RDS  binlog?

### ISSUE THREAD

**Issue by mjjian0** [alibaba/canal#579]
情况是这样的，我们mysql 是阿里云的rds，canal server启动后，canal client也启动，然后往mysql数据库并发写数据，刚开始是可以看到client有接到数据并解析到hbase的并且数据没有丢失。然后过段时间再并发写数据，client就接不到数据了。。。。当我重启canal server后，就看到client可以接到数据并解析了。

**Comment by songpengpeng** [comment]
部署的otter，也出现了运行一段时间(几天或者一个月)后，不能从canal接到数据，导致otter上的同步通道停止？

**Comment by mjjian0** [comment]
@songpengpeng 你配置了多个destination吗?destination 每个destination中的serveid是一样的吗？

**Comment by agapple** [comment]
@mjjian0 你用的是啥版本？建议是用1.0.24+以上的

**Comment by mjjian0** [comment]
这种情况下的  meta.dat  里面内容没有cursor和postion的信息。
几个destination目录中 meta.dat   clientId是一样的这个有关系吗？

**Comment by mjjian0** [comment]
@agapple 多个instance 配置的时候  canal.instance.rds.instanceId参数需要配置吗，保证唯一？？

**Comment by agapple** [comment]
你看到的是rds localbinlog解析的配置文件吧

**Comment by mjjian0** [comment]
@agapple   是 rds_instance.properties,这个不是 解析rds的库的配置吗

**Comment by agapple** [comment]
rds_instance只是拉取rds上的oss binlog，不作为解析用

**Comment by mjjian0** [comment]
@agapple 嗯，我们mysql是阿里云 rds，然后配置文件我就使用的这个。

**Comment by agapple** [comment]
参考FAQ： https://github.com/alibaba/canal/wiki/FAQ
