### ISSUE TITLE
关于数据库版本，5.7.18的咨询？

### ISSUE THREAD

**Issue by uniorder** [alibaba/canal#583]
目前我们的数据库是5.7.18，但是在你们的文档中说是支持5.7，括号中又特别注明了是5.7.13，那么是不是意味着仅测试了5.7.13？对于18版本有什么影响吗？

**Comment by agapple** [comment]
18版本没有做过测试，你可以做一下评测，一般小版本不太会有binlog变化

**Comment by uniorder** [comment]
好的，我们在正式环境中还没有遇到小版本问题，看了看change log，好像也没有特别指明binlog的变化。
