### ISSUE TITLE
1.0.19版本，canal.instance.filter.query.dcl\dml 过滤失效

### ISSUE THREAD

**Issue by fightingsz** [alibaba/canal#584]
1.0.19版本，canal.instance.filter.query.dcl\dml 过滤失效，仍然会打印update\delete\insert等日志

**Comment by Liubey** [comment]
你设置成true还是false？

**Comment by stevensam-lin** [comment]
我这边也是这样，设置了canal.instance.filter.query.dcl\dml都为true，然后会打印出create database的语句出来，而且isddl字段还是false
