### ISSUE TITLE
RowsQueryEvent不支持对表名的黑白名单filter.regex和filter.black.regex过滤呢

### ISSUE THREAD

**Issue by Liubey** [alibaba/canal#585]
是怎么考虑的，看源码LogEventConvert里面对ROWS_QUERY_LOG_EVENT、ANNOTATE_ROWS_EVENT都没过滤表名。
 另外

**Comment by Liubey** [comment]
另外对于文档中的canal.instance.filter.query.dml属性的描述：

> 是否忽略DML的query语句，比如insert/update/delete table.(mysql5.6的ROW模式可以包含statement模式的query记录)

有点看不懂，设置为true之后DML里排除select，还是排除insert/update/delete table？如果我使用canal是想同步数据到另一个存储介质，是不是可以设置成true？

**Comment by agapple** [comment]
RowsQueryLogEvent，只能获取到tableName，无法获取库名，表达式过滤的时候无法精确匹配
