### ISSUE TITLE
MemoryEventStoreWithBuffer event size不准确

### ISSUE THREAD

**Issue by Kosho1996** [alibaba/canal#586]
MemoryEventStoreWithBuffer
`    private long calculateSize(Event event) {
        // 直接返回binlog中的事件大小
        return event.getEntry().getHeader().getEventLength();
    }`

binlog事件经过Canal解析，实际内存占用是event_length的十倍以上，这样bufferSize * bufferMemUnit算出的实例内存占用就不准确了，是不是考虑改成event.getEntry().getSerializedSize();

**Comment by Kosho1996** [comment]
测试结果：
calculateSize 179，SerializedSize 1790
calculateSize 8291， ，SerializedSize 155000

**Comment by agapple** [comment]
是有这么一个问题，拿的是binlog里的大小，展开之后会补充字段，类型等信息，会比之前要膨胀很多

**Comment by agapple** [comment]
新的1.0.26版本已经按照序列化大小进行计算了
