### ISSUE TITLE
关于EventTransactionBuffer与MemoryEventStoreWithBuffer的一些疑问

### ISSUE THREAD

**Issue by zwangbo** [alibaba/canal#589]
# 我现在的理解
## EventTransactionBuffer

sink将event分发给EventTransactionBuffer，如果收集到一个完整的transaction，或者达到了buffer的size上限就会触发flush，将缓存数据通过callback经过filter等操作以后发送到MemoryEventStoreWithBuffer.

## MemoryEventStoreWithBuffer

接收到一个List<Event>（应该就是刚刚发过来的list事务），检查如果空位空间足够，就遍历list中的数据，逐条加入entries中。

每一次get数据的时候，是根据传入的batchSize来拿的，拿完以后会计算消息的PositionRange（这次get的头尾LogPosition），会set可被ack的点为这段消息中的最后一个TRANSACTIONBEGIN或者TRANSACTIONEND。这个ack会在元数据管理updateCursor时传进去，为了让cursor中总是记录的事务的开始或者结束。

# 我的疑问

现在我们在开发的东西，是希望以Transaction来作为单位来将消息发给下游的（如果过大的transaction会分割成多个transaction包，里面记录一个布尔值表示是否是事务结束包），现在主要矛盾是MemoryEventStoreWithBuffer里面存储的粒度是entry，所以根据batchSIze来拿的话拿出去可能同个事务中数据是会被分2次拿到的。

如果是从MemoryEventStoreWithBuffer拿出数据之后，再嵌套一个类似EventTransactionBuffer的缓存， ack的时候也还要保留原来的batchId来ack。

目前觉得可以去实现一个自己的MemoryTransactionStoreWithBuffer，里面的缓存的粒度用transaction包，这样每次get出来都是以transaction包为单位的形式，之后可以继承CanalInstanceWithManager覆盖里面的initEventStore方法，将MemoryEventStoreWithBuffer替换为自己实现的MemoryTransactionStoreWithBuffer。

想请教一下当时canal设计的考虑，以后有没有考虑提供按transaction包为单位的put，get，ack。然后我目前的想法是不是合理，不知道我上面的表述是不是够清楚，望回复。

**Comment by agapple** [comment]
要考虑大事务的情况，一般我们内部不建议这么玩。很多工作你可以在client层面来支持，比如client层面本身支持异步ack之后，你可以自己搞一个buffer，凑足一个事务后回调业务

**Comment by zwangbo** [comment]
感谢建议哈，client层面是可以做这个。但是我还有些考虑：

目前我们其实用了内嵌canal+一个消息中间件来提供下游数据订阅。现在是想要往消息中间件中发事务粒度的消息（业务中几乎都是小事务）。如果在canal client层getWithoutAck方法拿出batchSize数据，然后放入一个buffer，这样感觉代码结构上又多了一层，在batchSize个数据中包含多个事务的情况下，要协调根据事务发送消息给mq，以及消费完一个batchSize数据以后根据MessageId去ack canal。（因为这种情况下的发送给mq的Trasaction与从canal拉出来的MessageId没有什么联系。如果是server里面保证了get出来的一个Message就是一个事物包，那就直接发送完走ack逻辑就可以了）

如果考虑server层面按下面的做法是不是能避免大事务的影响呢：
考虑flush出一个事物包，包里加一个标记位。如果小事务就单独的事物包，标记位表示没有后续包；大事务就会因为buffer满以后切成多个，除了最后一个都标记为有后续包。这样子做的话应该也能处理大事务的问题吧。

我这样的需求，是不是实现在server端比较好呢，写完以后的感觉是getWithoutAck拿出来的数据是以事物包为单元的（大事务会是多个事物包（少数情况））。

**Comment by agapple** [comment]
如果是打标的方式，是建议在server上操作

**Comment by shang7053** [comment]
如果针对一个大表的一个大事物包含了太多数据，很容易引发OOM问题，之前项目里错误设置了batchSize（5*1024），结果client经常异常中止。这不是少见的情况，糟糕的历史系统，经常一个事物修改成千上万条数据，甚至来个清空表，表本身数据量还不小

**Comment by zwangbo** [comment]
@shang7053 嗯嗯，会有设置上限，针对大的事务会截断多次flush的

**Comment by jingshenbusi6530** [comment]
看了你的描述，又结合源码看了下
1、服务器端的canal.instance.transactionn.size这个参数的配置和client端的batchSize的设置是不是应该设置的一样会比较合理些？
2、如果一个完整事务数据的长度超过了客户端设置的这个batchSize，比如一个事务的实际长度是1.5倍个batchSize，第一次get获取一个batchSize的数据，再次get时，是不是只会给我返剩下的0.5倍的数据？会不会把下一个事务的数据也返回给我？ @zwangbo

**Comment by zwangbo** [comment]
@jingshenbusi6530 目前Canal中实现的消息获取是以Entry（Event）为粒度的（在MemoryEventStoreWithBuffer中），所以batchSize只是针对的拿多少个Entry，不会针对事务做截断返回。
所以感觉：
1. 这两个配置没有必然的联系，batchSize主要看自己这边的消费效率调整就好了。
2. 只要buff中储存了足够多的数据，每次一get都能拿到batchSize个Event，不会因为事务截断。（但是事务头尾进入MemoryEventStoreWithBuffer时，会被设置为可被ack的位点，也就是说ack一个MessageId的时候总是会选择一个BatchSize组中事务头尾的position）

**Comment by agapple** [comment]
LS理解正确
