### ISSUE TITLE
关于sqltype 的一些疑问

### ISSUE THREAD

**Issue by weitong1105** [alibaba/canal#591]
hi，
看CanalEntry.java 中 SqlType是字段在java中的类型
getSqlType()出来的是数值，抱歉，我没有找到数值对应的java类型，可以在那里查到吗？

thx

**Comment by weitong1105** [comment]
找到了。。。

**Comment by weitong1105** [comment]
找到了

**Comment by keji94** [comment]
> 找到了

在哪？

**Comment by jamieme** [comment]
参考java JDBCType类，canal的SqlType枚举对应的是JDBCType
