### ISSUE TITLE
开启druid.ddl=true以及使用tsdb，会出现改表结构一直报column size is not match的问题

### ISSUE THREAD

**Issue by wzh3839188** [alibaba/canal#592]
最近碰上一个问题，因为druid在解析我们的表结构的时候总是报错，无法通过。所以关掉了druid的ddl以及canal query ddl的识别。如果此时更新了业务表的列，例如增加列。在新的event来的时候，会发生，event里的fields数量多，而tableMeta里的列数少，而抛出异常。
` public TableMeta getTableMeta(String schema, String table, boolean useCache, EntryPosition position) {
        TableMeta tableMeta = null;
        if (tableMetaTSDB != null) {
            //TODO 觉得此处应该加上useCache判断，如果使用了cache，从缓存走。如果不使用cache，就走数据库直连查询
            tableMeta = tableMetaTSDB.find(schema, table);
            if (tableMeta == null) {
                // 因为条件变化，可能第一次的tableMeta没取到，需要从db获取一次，并记录到snapshot中
                String fullName = getFullName(schema, table);
                try {
                    ResultSetPacket packet = connection.query("show create table " + fullName);
                    String createDDL = null;
                    if (packet.getFieldValues().size() > 0) {
                        createDDL = packet.getFieldValues().get(1);
                    }
                    // 强制覆盖掉内存值
                    tableMetaTSDB.apply(position, schema, createDDL, "first");
                    tableMeta = tableMetaTSDB.find(schema, table);
                } catch (IOException e) {
                    throw new CanalParseException("fetch failed by table meta:" + fullName, e);
                }
            }
            return tableMeta;
        } else {
            if (!useCache) {
                tableMetaDB.invalidate(getFullName(schema, table));
            }

            return tableMetaDB.getUnchecked(getFullName(schema, table));
        }
    }`

**Comment by agapple** [comment]
你关掉了tsdb，就没法解决这个列不匹配的问题。如果针对DDL无法解析，建议反馈对应的DDL，推动TSDB的完善

**Comment by agapple** [comment]
用的是fastsql，和druid不同的package
