### ISSUE TITLE
canal集群模式下，客户端调用connector.subscribe("schema1\\..")无效

### ISSUE THREAD

**Issue by neil1573** [alibaba/canal#596]
hi ，dear, 
在使用canal进行开发的时候碰到了如下的问题：

1. 问题描述：
   canal集群环境下，客户端调用connector.subscribe("schema1\\..")无效，压根监听不到schema1数据库下的表数据变化的日志。并且修改回去connector.subscribe()再次重启客户端，之前能正常监听所有表的功能也立马失效。重启canal服务端也没用。但是修改canal服务端的zookeeper指向，再重启canal服务端，又能正常恢复监听所有的表。如果再次在客户端处调用带有filter参数的subscribe方法，则会重复上述问题。

2. 环境

   机器A canal server 1 (版本1.0.24)     机器B  canal server 2 (版本1.0.24)    机器C  zookeeper 

额外在问下：connector.subscribe中的filter写法有没有什么特殊的要求，只是一个正则表达式吗还是有什么其他的规则？？？？

QQ群加不进去，所以只有邮件问询，希望能受到你的回复，谢谢

**Comment by gurenyuan123** [comment]
如果要订阅的数据库是test，表是user和log
则调用
connector.subscribe("test.user,test.log");

**Comment by agapple** [comment]
LS正解
