### ISSUE TITLE
com.alibaba.otter.canal.protocol.exception.CanalClientException: java.io.IOException: Broken pipe；

### ISSUE THREAD

**Issue by gurenyuan123** [alibaba/canal#597]
当数据量小的时候没有问题，当有万级的数据同步插入时，canal就会报com.alibaba.otter.canal.protocol.exception.CanalClientException: java.io.IOException: Broken pipe
错误。
现象是canal一直读取插入万级的日志，循环调用。导致在mysql中先插入又删除，再插入删除，一直重复。请问是什么原因

**Comment by agapple** [comment]
https://github.com/alibaba/canal/issues/640，关注一下这个
