### ISSUE TITLE
一个rds   mysql库配置三个instance，只有两个能正常读到binlog？

### ISSUE THREAD

**Issue by mjjian0** [alibaba/canal#598]
rds上一个库的一个表分了一千张，所以配置了三个instance，然后每个过滤不同的表。但是只有两个instance能正常消费到binlog日志。另外一个instance即使 表有数据，也消费不到    batchId 返回的是-1

**Comment by CXninesuns** [comment]
我也碰到类似的问题，总是有instance没有去获取位点，log/instance文件夹下，没有生成meta.log文件

**Comment by mjjian0** [comment]
升级到1.0.26版本，正常了。
