### ISSUE TITLE
大数据量时,canal服务端报c.a.o.c.server.netty.handler.ClientAuthenticationHandler - idle timeout exceeds, close channel to save server resources

### ISSUE THREAD

**Issue by gurenyuan123** [alibaba/canal#599]
问题场景：
万级的数据进行insert操作时，canal服务端会报
c.a.o.c.server.netty.handler.ClientAuthenticationHandler - channel:[id: 0x3c24ea0e, /192.168.1.111:64402 => /192.168.1.111:11111] idle timeout exceeds, close channel to save server resources
错误``。
客户端的日志显示，订阅的binlog会一直重复出现(0-10000再循环0-10000),导致delay时间变得很长，别的表的同步就进不去了。
这种情况是要扩大canal的ringbuffer和客户端的batchsize吗，本地测试了一下都没有解决问题

**Comment by agapple** [comment]
你这个异常时链接idle timeout超时，最好你需要观察一下运行堆栈

**Comment by yueapple** [comment]
我也遇到这个问题了，怎么解决的

**Comment by wusthuke** [comment]
server端 batchMode设置为itemSize, 然后，client端的batchSize设置小一点，默认超时时间 30s ack掉就可以。

**Comment by agapple** [comment]
https://github.com/alibaba/canal/issues/640，关注一下这个

**Comment by DyzYpp** [comment]
解决了吗 我也遇到这个问题。
