### ISSUE TITLE
找不到 com.alibaba.fastsql:fastsql:jar:2.0.0_preview_228 包，改成com.alibaba.fastsql:fastsql:jar:2.0.0_preview_186

### ISSUE THREAD

**Issue by religiose** [alibaba/canal#604]
[ERROR] Failed to execute goal on project canal.parse: Could not resolve dependencies for project com.alibaba.otter:canal.parse:jar:1.0.26-SNAPSHOT: Failure to find com.alibaba.fastsql:fastsql:jar:2.0.0_preview_228 in http://maven.aliyun.com/nexus/content/groups/public was cached in the local repository, resolution will not be reattempted until the update interval of nexus-aliyun has elapsed or updates are forced -> [Help 1]

**Comment by hiwjd** [comment]
com.alibaba.fastsql:fastsql:jar:2.0.0_preview_228 这个包什么时候能放出呢？

**Comment by agapple** [comment]
看一下二进制发布包里有
