### ISSUE TITLE
事务较大的情况下binlog数据丢失

### ISSUE THREAD

**Issue by Lee-Think** [alibaba/canal#605]
在测试canal同步数据到es的时候，从mysql dump出一个表，导出的时候每250行切分为一个事务，然后把表truncate掉，再import导出的sql，发现同步完成后es中会比mysql少三百条左右的数据（总数据量4W+）。经调试发现是canal在同步binlog过程中发生了数据丢失，大部分事务都被完整同步了，有几个事务只同步过来不到100条数据。后来把事务每10行数据切分一个事务，就不会出现丢数据的情况了。请问一下这和网络状况有关吗？或者只是因为事务过大？

**Comment by JasonHuangHuster** [comment]
这个问题怎么处理了？
