### ISSUE TITLE
c.a.o.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta

### ISSUE THREAD

**Issue by SkingXiong** [alibaba/canal#612]
1.0.25版本
canal.instance.tsdb.enable=false

2018-04-27 17:11:17.990 [destination = billingondemandfee01db , address = /10.179.171.159:40002 , EventParser] ERROR c.a.o.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta - pls submit github issue, show create table ddl:CREATE TABLE `t_billing_accumulator_conf` (
  `serviceTypeCode` varchar(64) NOT NULL,
  `resourceTypeCode` varchar(64) NOT NULL,
  `accumulateFactorName` varchar(64) NOT NULL,
  `amount` int(11) NOT NULL,
  `measureId` int(11) NOT NULL,
  `logTime` datetime DEFAULT NULL,
  `memo` varchar(200) DEFAULT NULL,
  `extendParams` varchar(1024) DEFAULT NULL,
  UNIQUE KEY `uniqueRecord` (`serviceTypeCode`,`resourceTypeCode`,`accumulateFactorName`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 , compare failed .
 db : TableMeta [schema=billingondemandfee01db, table=t_billing_accumulator_conf, fileds=
        FieldMeta [columnName=serviceTypeCode, columnType=varchar(64), defaultValue=null, nullable=false, key=true]
        FieldMeta [columnName=resourceTypeCode, columnType=varchar(64), defaultValue=null, nullable=false, key=true]
        FieldMeta [columnName=accumulateFactorName, columnType=varchar(64), defaultValue=null, nullable=false, key=true]
        FieldMeta [columnName=amount, columnType=int(11), defaultValue=null, nullable=false, key=false]
        FieldMeta [columnName=measureId, columnType=int(11), defaultValue=null, nullable=false, key=false]
        FieldMeta [columnName=logTime, columnType=datetime, defaultValue=null, nullable=true, key=false]
        FieldMeta [columnName=memo, columnType=varchar(200), defaultValue=null, nullable=true, key=false]
        FieldMeta [columnName=extendParams, columnType=varchar(1024), defaultValue=null, nullable=true, key=false]
]
 mem : TableMeta [schema=billingondemandfee01db, table=t_billing_accumulator_conf, fileds=
        FieldMeta [columnName=serviceTypeCode, columnType=varchar(64), defaultValue=null, nullable=false, key=false]
        FieldMeta [columnName=resourceTypeCode, columnType=varchar(64), defaultValue=null, nullable=false, key=false]
        FieldMeta [columnName=accumulateFactorName, columnType=varchar(64), defaultValue=null, nullable=false, key=false]
        FieldMeta [columnName=amount, columnType=int(11), defaultValue=null, nullable=false, key=false]
        FieldMeta [columnName=measureId, columnType=int(11), defaultValue=null, nullable=false, key=false]
        FieldMeta [columnName=logTime, columnType=datetime, defaultValue=null, nullable=true, key=false]
        FieldMeta [columnName=memo, columnType=varchar(200), defaultValue=null, nullable=true, key=false]
        FieldMeta [columnName=extendParams, columnType=varchar(1024), defaultValue=null, nullable=true, key=false]
]
2018-04-27 17:11:20.911 [destination = billingondemandfee01db , address = /10.179.171.159:40002 , EventParser] ERROR c.a.o.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta - compare failed , check log

**Comment by agapple** [comment]
已知问题，可以使用1.0.26版本测试一下
