### ISSUE TITLE
在cluster client模式下无法获得排他锁时不能优雅停机

### ISSUE THREAD

**Issue by nbqyqx** [alibaba/canal#619]
com.alibaba.otter.canal.client.impl.SimpleCanalConnector:448
                mutex.get();// 阻塞等待 无法退出

**Comment by rewerma** [comment]
建议在CanalConnector接口中加一个stopSubscribe方法停止阻塞等待

**Comment by agapple** [comment]
你这个只能解决subscribe时阻塞的问题吧，如果是connect或者其他操作被mutex.get()锁定

**Comment by nbqyqx** [comment]
都可以在stop时用thread.interrupt退出，捕获并淹没异常只处理了subscribe，因为这个情况在cluster情况下很常见

Neal Hu
nealhu@apache.org

**Comment by agapple** [comment]
有PR提交提供了stopRunning的方法，可以退出
