### ISSUE TITLE
Caused by: java.net.ConnectException: Connection refused: connect

### ISSUE THREAD

**Issue by Cloudiver** [alibaba/canal#624]
canal服务端已经成功运行，新建maven项目测试，出现拒绝连接请求。

![](https://ww1.sinaimg.cn/large/005zWjpngy1fr2wcvwun6j310q0eemyo.jpg)

**Comment by agapple** [comment]
自己环境或者网络问题

**Comment by Guomnn** [comment]
哥们解决了吗

**Comment by jianghanfen** [comment]
遇到同样的问题，解决了吗？  发现canal server的11111端口没在监听

**Comment by toxmc** [comment]
一样的问题 mac 环境

**Comment by toxmc** [comment]
检查下是否存在如下配置.只有开启tcp模式才会监听11111端口
canal.serverMode=tcp
