### ISSUE TITLE
支持MySQL5.7的XA binlog事件

### ISSUE THREAD

**Issue by agapple** [alibaba/canal#626]
支持一下MySQL 5.7之后的XA能力：https://mysqlserverteam.com/improvements-to-xa-support-in-mysql-5-7/

`
TRANSACTION_CONTEXT_EVENT= 36,

  VIEW_CHANGE_EVENT= 37,

  /* Prepared XA transaction terminal event similar to Xid */
  XA_PREPARE_LOG_EVENT= 38,
`

**Comment by agapple** [comment]
http://mysql.taobao.org/monthly/2017/11/06/， 一片比较不错介绍MySQL XA

**Comment by zhmz1326** [comment]
上面地址去掉后面的逗号就能看了  http://mysql.taobao.org/monthly/2017/11/06/

**Comment by agapple** [comment]
输出格式类似：
`================> binlog[mysql-bin.000012:35614] 
 BEGIN ----> Thread id: 3 ------> XA START  X'63',X'',1


 END ----> transaction id: 0 ------> XA END  X'63',X'',1
================> binlog[mysql-bin.000012:36022]


----------------> binlog[mysql-bin.000012:35459]
 ------> XA ROLLBACK  X'62',X'',1

----------------> binlog[mysql-bin.000012:36209]
 ------> XA COMMIT  X'63',X'',1`
