### ISSUE TITLE
canal server经常会挂，而且进程不退出

### ISSUE THREAD

**Issue by lchb369** [alibaba/canal#627]
canal server经常会挂，而且进程不退出，根本监测不到server是不是挂了，本来写了个监控进程脚本挂了就重启，但是没什么用，每次重启都要删掉meta.dat ，否则会报 线程ID 不存在。。

希望能做的人性化点。

**Comment by lchb369** [comment]
补充一下，在亚马逊rds上用这个，域名访问，经常域名对应的IP会自动变动，变化时canal server就是解析不到ip，log里一直报错。只有重启canal server才能解决。维护很麻烦，是否可以加上自动重连功能

**Comment by agapple** [comment]
一直都有自动重试的机制，怀疑是jvm的dns cache，导致ip解析到的一直是同一个ip，可以尝试关闭jvm dns cache
