### ISSUE TITLE
DML 的 rowChage.getSql() 获取不到sql信息

### ISSUE THREAD

**Issue by rewerma** [alibaba/canal#628]
DML 的 rowChage.getSql() 获取不到sql信息

**Comment by zwangbo** [comment]
@rewerma getSql()方法是获取DDL语句的

**Comment by agapple** [comment]
LS正解

**Comment by rewerma** [comment]
那么DML就无法获取SQL了？maxwell是能够获取到sql，希望加入此功能

**Comment by agapple** [comment]
你要理解它获取的是什么event事件的sql，5.6之后有一个rowsQueryLogEvent，有对应DML的sql文本
