### ISSUE TITLE
同一个server 无法开启两个客户端订阅

### ISSUE THREAD

**Issue by libra1010** [alibaba/canal#630]
如题
启动一个server
然后在同一个客户端,用两个线程订阅, 会报 batchid 不存在,是因为订阅端必须唯一,还是因为某个订阅ID一致的原因?

**Comment by nbqyqx** [comment]
一个instance同时只能一个订阅成功，其他client会阻塞standby，等待工作中的client释放订阅后才能订阅成功

**Comment by agapple** [comment]
LS正解
