### ISSUE TITLE
MySQL驱动包支持Boolean类型，canal不支持boolean类型转换

### ISSUE THREAD

**Issue by kervin521** [alibaba/canal#631]
MySQL的驱动包中对tinyint的长度为1，对应sqlType=-7,转化为Java布尔类型，参考MySQL驱动源码

![image](https://user-images.githubusercontent.com/9798724/39748475-bff67406-52e2-11e8-9233-21df121524b9.png)

而Canal对对tinyint的长度为1，对应sqlType=-6，无法处理为Java的布尔类型

**Comment by agapple** [comment]
没有专门针对tinyint(1)做过特殊处理，目前统一按照了tinyint类型-6

**Comment by agapple** [comment]
可以考虑提交一个PR给我

**Comment by nbqyqx** [comment]
https://github.com/alibaba/canal/pull/682

**Comment by nbqyqx** [comment]
@agapple please assign the issue to me :)

**Comment by KaimingWan** [comment]
The fix still have some problem when sync data with tinyint(1) type. If not specify tinyInt1isBit in your jdbc url，the return java type is integer. Reference doc is https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-reference-type-conversions.html
