### ISSUE TITLE
binlog位点前移，ddl操作丢失

### ISSUE THREAD

**Issue by yueapple** [alibaba/canal#633]
canal 版本：1.0.25
手动设置cursor的timestamp至 t1，当前时间为t2，t2 > t1
如果t1~t2这段时间之内产生了ddl 操作，binlog 位点前移至t1，重新消费这段时间的binlog，ddl操作丢失

canal server log 如下：
canal.parse.inbound.mysql.tsdb.DatabaseTableMeta - dup apply for sql : CREATE TABLE     canal.parse.inbound.mysql.tsdb.DatabaseTableMeta - dup apply for sql : alter table screen_fee add

**Comment by agapple** [comment]
这不是ddl丢失，而是回到了T1时间之后，在重新解析发现在t1 -> t2中有ddl，重新加入到tsdb中发现已经加过了
