### ISSUE TITLE
canal 的file store 或mix store 有计划什么时候开发？

### ISSUE THREAD

**Issue by guixincui** [alibaba/canal#636]
如题。

**Comment by agapple** [comment]
暂时没有，可以对接一下数据写入到kafka中

**Comment by guixincui** [comment]
@agapple   这几天也在犹豫写到kafka还是rocketmq，有什么建议吗？

**Comment by agapple** [comment]
我觉得都可以把，我们公司用的是rocketmq

**Comment by firnsan** [comment]
@agapple 你好，想请教下。我们现在自研数据管道服务，其中一点不是很清楚，binlog解析之后写到mq是不是好一些？这样就可以通过mq提供订阅服务了，这是比较简单的做法，下游的client也可和管道服务进行解耦。

但是canal自己实现类似mq的一套复杂的订阅api，虽然有提供java客户端sdk，但是go、rust这些都没有，不方便使用。

所以，自己实现订阅api是基于什么考虑呢？是考虑mq的一些潜在的坑，比如消息大小限制、atmost once等因素吗？

**Comment by firnsan** [comment]
anybody here？

**Comment by agapple** [comment]
canal的server/client结构主要是基于运维管理的角度考虑，之前有想法是内置一套kafka的能力，但考虑成熟度，建议是直接用client接到数据后存储到MQ一份
