### ISSUE TITLE
为什么address存储的是hostname而不是 ip 

### ISSUE THREAD

**Issue by zygfengyuwuzu** [alibaba/canal#638]
{
  "@type": "com.alibaba.otter.canal.protocol.position.LogPosition",
  "identity": {
    "slaveId": -1,
    "sourceAddress": {
      "address": "DESKTOP-1RFA2LT",
      "port": 3306
    }
  },
  "postion": {
    "included": false,
    "journalName": "mysql-bin.000011",
    "position": 3382,
    "serverId": 1,
    "timestamp": 1526277481000
  }
}

**Comment by agapple** [comment]
默认序列化之后的结果，没有特殊处理
