### ISSUE TITLE
A slave with the same server_uuid/server_id as this slave has connected to the master

### ISSUE THREAD

**Issue by hphuangpu** [alibaba/canal#644]
MANAGER/NODE4.2.14在运行过程中不断出现相同的server_uuid/server_id，不知该如何消除这个错误？
pid:31 nid:11 exception:canal:MiddleEast:java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = A slave with the same server_uuid/server_id as this slave has connected to the master; the first event 'mysql-bin.000011' at 77235, the last event read from './mysql-bin.000012' at 150, the last byte read from './mysql-bin.000012' at 150.
    at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:95)
    at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:121)
    at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:209)
    at java.lang.Thread.run(Thread.java:748)

**Comment by hphuangpu** [comment]
这个问题通过删除原存储着server_uuid的auto.cnf文件，并通过重启Mysql数据库重新生成新的server_uuid后，目前不在报以上错误信息了，观察一段时间在追加评论。

**Comment by hphuangpu** [comment]
几天后，继续出现同样的故障报错。

**Comment by hphuangpu** [comment]
经过试验，暂时判断为如果pipline开启了超时或者延时的报警监控，并且这些监控开启了自动重启选项，那么当监控认为超时后，会开启新的同步进程，而事实上远端的node只是因为网速过慢影响了相应时间，并没有真正的挂掉，因此开启新的进程后就导致了重复的slave在请求master。出现了“A slave with the same server_uuid/server_id as this slave has connected to the master”的提示，目前在监控上，只保留了“异常”的监控，删掉了其余的监控，运行还算正常，正在观察。

**Comment by agapple** [comment]
解决问题就好，新的canal 1.0.26会采用随机uuid的做法来规避
