### ISSUE TITLE
TSDB show create table时没过滤View

### ISSUE THREAD

**Issue by dmsolr** [alibaba/canal#648]
开启TSDB之后，出现show create table找不到表的情况，仔细一看是因为我们的库中有一些view。

其实我有点不明白即是因为要用 show create table呢？像之前一样用 describe tablename 的方式不是很好吗？

**Comment by agapple** [comment]
show create table失败之后会回退到desc table name.  主要为解决unique key的获取，show create table针对多个唯一键时可以正确提取
