### ISSUE TITLE
最新release版本中 regex 过滤不起作用

### ISSUE THREAD

**Issue by JasonHuangHuster** [alibaba/canal#656]
canal-server 配置了regex如下

canal.instance.dbUsername=canal
canal.instance.dbPassword=canal
canal.instance.defaultDatabaseName=EDU_DISCOUNT_PRICE_TEST
canal.instance.connectionCharset=UTF-8
# table regex
#canal.instance.filter.regex=.*\\..*
canal.instance.filter.regex=EDU_DISCOUNT_PRICE_TEST\\..*
# table black regex
#canal.instance.filter.black.regex=ONLINE_EDU_TEST\\..*
#################################################

Client 代码 connector.subscribe("EDU_DISCOUNT_PRICE_TEST.t_online_discount");
同样配置了过滤，但是仍然有不相关的库的表更新信息。数据库确认binlog格式为 ROW

canal 定位问题真的很不方便。。。QQ群也加不进去，求解答。

**Comment by dydeve** [comment]
`connector.subscribe("EDU_DISCOUNT_PRICE_TEST.t_online_discount"); `
改成
`connector.subscribe("EDU_DISCOUNT_PRICE_TEST\\.t_online_discount");`

**Comment by agapple** [comment]
LS正解
