### ISSUE TITLE
当前master分支  SimpleCanalConnector#connect()方法  逻辑错误

### ISSUE THREAD

**Issue by dydeve** [alibaba/canal#662]
# 运行SimpleCanalClientTest的main方法，会出异常
`process error!java.lang.NullPointerException: null
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.writeWithHeader(SimpleCanalConnector.java:392) ~[classes/:na]
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.writeWithHeader(SimpleCanalConnector.java:380) ~[classes/:na]
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.getWithoutAck(SimpleCanalConnector.java:292) ~[classes/:na]
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.getWithoutAck(SimpleCanalConnector.java:280) ~[classes/:na]
	at com.alibaba.otter.canal.example.AbstractCanalClientTest.process(AbstractCanalClientTest.java:125) ~[classes/:na]
	at com.alibaba.otter.canal.example.AbstractCanalClientTest$2.run(AbstractCanalClientTest.java:85) [classes/:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_171]`

经排查，是SimpleCanalConnector的connect方法出错

```
public void connect() throws CanalClientException {
        if (connected) {
            return;
        }

        if (runningMonitor != null) {
            if (!runningMonitor.isStart()) {
                runningMonitor.start();
            }
        } else {
            waitClientRunning();
            if (!running) {
                return;
            }
            doConnect();
            if (filter != null) { // 如果存在条件，说明是自动切换，基于上一次的条件订阅一次
                subscribe(filter);
            }
            if (rollbackOnConnect) {
                rollback();
            }
        }

        connected = true;
    }

private void waitClientRunning() {
        try {
            if (zkClientx != null) {
                if (!connected) {// 未调用connect
                    throw new CanalClientException("should connect first");
                }

                running = true;

                mutex.get();// 阻塞等待
            }
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
            throw new CanalClientException(e);
        }
    }
```

running初始化为false，且仅有两个方法改变了他的值：waitClientRunning()  和  stopRunning() 。
connect()方法调用waitClientRunning()时，由于zkClienttx == null,所以running仍然为false，所以不会调用doConnect()，从而没有给writableChannel赋值，并导致异常堆栈里的空指针异常。

问题是这次提交造成的:[https://github.com/alibaba/canal/commit/4141049bb90ce6dc1ce05a58c95f2d974fdd5865](https://github.com/alibaba/canal/commit/4141049bb90ce6dc1ce05a58c95f2d974fdd5865) @rewerma

**Comment by skycanfly** [comment]
1、屏蔽两行代码就行了，
第一处：
public void connect() throws CanalClientException {
        if (connected) {
            return;
        }

        if (runningMonitor != null) {
            if (!runningMonitor.isStart()) {
                runningMonitor.start();
            }
        } else {
            waitClientRunning();
//            if (!running) {
//                return;
//            }
            doConnect();
            if (filter != null) { // 如果存在条件，说明是自动切换，基于上一次的条件订阅一次
                subscribe(filter);
            }
            if (rollbackOnConnect) {
                rollback();
            }
        }

        connected = true;
    }
第二处：
 public void subscribe(String filter) throws CanalClientException {
        waitClientRunning();
//        if (!running) {
//            return;
//        }
        try {
            writeWithHeader(Packet.newBuilder()
                .setType(PacketType.SUBSCRIPTION)
                .setBody(Sub.newBuilder()
                    .setDestination(clientIdentity.getDestination())
                    .setClientId(String.valueOf(clientIdentity.getClientId()))
                    .setFilter(filter != null ? filter : "")
                    .build()
                    .toByteString())
                .build()
                .toByteArray());
            //
            Packet p = Packet.parseFrom(readNextPacket());
            Ack ack = Ack.parseFrom(p.getBody());
            if (ack.getErrorCode() > 0) {
                throw new CanalClientException("failed to subscribe with reason: " + ack.getErrorMessage());
            }

            clientIdentity.setFilter(filter);
        } catch (IOException e) {
            throw new CanalClientException(e);
        }
    }
原因上面已经回答。zookeeper判断有问题。单机可有没有zookeeper

**Comment by agapple** [comment]
已修复
