### ISSUE TITLE
关于两个canal server配同一个instance的疑问

### ISSUE THREAD

**Issue by shenfl** [alibaba/canal#664]
两个canal server分别配置了两个instance：example1和example2，启动其中一个canal server，这时候这个server能够同步example1和example2这两个库的数据，这时候启动第二个canal server，这时候这个server无法消费example1和example2，这个时候集群就没有太大意义了，canal是否可以做类似rebalance之类的操作？比如rebalance之后canal server1和canal server2分别同步一个库的数据？

**Comment by XiaoyiPeng** [comment]
@shenfl  请问，你获取了想要的答案了吗？ rebalance 机制是如何做的？
