### ISSUE TITLE
Mac环境下自己编译出问题

### ISSUE THREAD

**Issue by hellobiek** [alibaba/canal#666]
依赖这个文件，获取不到。
http://code.alibabatech.com/mvn/releases/com/alibaba/fastsql/fastsql/2.0.0_preview_228/fastsql-2.0.0_preview_228.pom

麻烦把这个依赖放到一个可靠的源上。

[ERROR] Failed to execute goal on project canal.parse: Could not resolve dependencies for project com.alibaba.otter:canal.parse:jar:1.0.26-SNAPSHOT: Failed to collect dependencies at com.alibaba.fastsql:fastsql:jar:2.0.0_preview_228: Failed to read artifact descriptor for com.alibaba.fastsql:fastsql:jar:2.0.0_preview_228: Could not transfer artifact com.alibaba.fastsql:fastsql:pom:2.0.0_preview_228 from/to alibaba (http://code.alibabatech.com/mvn/releases/): Connect to code.alibabatech.com:80 [code.alibabatech.com/119.38.217.15] failed: Operation timed out -> [Help 1]

**Comment by ericjee** [comment]
same here

**Comment by agapple** [comment]
二进制发布包里有
