### ISSUE TITLE
Canal 设计基于Server Client模式的用意是什么？

### ISSUE THREAD

**Issue by nbqyqx** [alibaba/canal#669]
Canal 设计基于Server Client模式的用意是什么？
在Server端直接解析binlog并消费是不是更加可靠与高效？

**Comment by shuhaoc** [comment]
楼主这个问题可以这样问，分布式系统的意义是什么

**Comment by nbqyqx** [comment]
除了让可编程的客户端更轻量外，还有什么考虑？server同样可以做成分布式，目前也是支持server ha的

**Comment by agapple** [comment]
为了做方便运维管理，也可以直接嵌入式带入server，直连mysql

**Comment by nbqyqx** [comment]
对，这样的效率和可靠性会更高。我们打算封装下canal client的代码，支持配置成嵌入式server。另外还抽象了可扩展的outconnector spi机制，目前做了hbase，es，log4j的connector。到时候考虑贡献给社区

**Comment by liushaoqiangly** [comment]
12年我就已经取消客户端,引用server,做成Ha单活的服务,取名datapump;现在基于25Version重构成spring boot项目;DB连接遇到点问题

**Comment by agapple** [comment]
欢迎下载：https://github.com/alibaba/canal/releases/tag/canal-1.0.26-preview-3
