### ISSUE TITLE
server多个instance同时启动，每次只能最多5个工作

### ISSUE THREAD

**Issue by nbqyqx** [alibaba/canal#675]
一台canal server 部署了15个instance，每次起来只有5个instance能获取到位点信息。而且重启这五个不固定。
有其中一个报SHOW VIEW command没权限，需要给账号开这个权限？
文档里只提到select，replication slave，replication client权限

2018-06-06 19:18:22.458 [destination = mysql.05.upanb.cn , address = mysql.05.upanb.cn/192.168.250.214:3306 , EventParser] ERROR c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - dump address mysql.05.upanb.cn/192.168.250.214:3306 has an error, retrying. caused by
com.alibaba.otter.canal.parse.exception.CanalParseException: java.io.IOException: ErrorPacket [errorNumber=1142, fieldCount=-1, message=SHOW VIEW command denied to user 'canal'@'192.168.249.54' for table 'taglist', sqlState=42000, sqlStateMarker=#]
with command: show create table `pointstore`.`admin`;show create table `pointstore`.`blacklist`;show create table `pointstore`.`clearuk`;show create table `pointstore`.`duibaorder`;show create table `pointstore`.`point_detail_description`;show create table `pointstore`.`returnpoint`;show create table `pointstore`.`s_admin`;show create table `pointstore`.`t_adminlog`;show create table `pointstore`.`t_broker`;show create table `pointstore`.`t_broker_copy`;show create table `pointstore`.`t_brokercompany`;show create table `pointstore`.`t_exchangerule`;show create table `pointstore`.`t_luckproduct`;show create table `pointstore`.`t_luckrecord`;show create table `pointstore`.`t_luckrecord2`;show create table `pointstore`.`t_luckrecord3`;show create table `pointstore`.`t_luckrecord4`;show create table `pointstore`.`t_oauthinfo`;show create table `pointstore`.`t_oauthinfo_bak1`;show create table `pointstore`.`t_oauthinfo_copy`;show create table `pointstore`.`t_pointactivity`;show create table `pointstore`.`t_pointdetail_new`;show create table `pointstore`.`t_pointmain_new`;show create table `pointstore`.`t_pointmain_new_20180212`;show create table `pointstore`.`t_pointmain_new_bak`;show create table `pointstore`.`t_pointmain_new_copy`;show create table `pointstore`.`t_pointproduct`;show create table `pointstore`.`t_pointrule`;show create table `pointstore`.`t_pointsetting`;show create table `pointstore`.`t_pointstoreadminauthority`;show create table `pointstore`.`t_pointstoreinvoice`;show create table `pointstore`.`t_pointstorevisitlog`;show create table `pointstore`.`t_productinventory`;show create table `pointstore`.`t_productpic`;show create table `pointstore`.`t_productscategory`;show create table `pointstore`.`t_productsexchange_new`;show create table `pointstore`.`t_productsexpand`;show create table `pointstore`.`t_productshow`;show create table `pointstore`.`t_provincecityarea`;show create table `pointstore`.`t_ruletocity`;show create table `pointstore`.`taglist`;show create table `pointstore`.`test`;show create table `pointstore`.`timelist`;show create table `pointstore`.`v_brokerpoint`;show create table `pointstore`.`v_luckrecord`;show create table `pointstore`.`v_pointstoreinvoicetotal`;show create table `pointstore`.`v_pointstoreinvoicetotal_a`;show create table `pointstore`.`v_productshow`;show create table `pointstore`.`v_productshowlist`;show create table `pointstore`.`v_productwarehouse`;show create table `pointstore`.`yearlist`;
Caused by: java.io.IOException: ErrorPacket [errorNumber=1142, fieldCount=-1, message=SHOW VIEW command denied to user 'canal'@'192.168.249.54' for table 'taglist', sqlState=42000, sqlStateMarker=#]

2018-06-06 19:18:22.459 [destination = mysql.05.upanb.cn , address = mysql.05.upanb.cn/192.168.250.214:3306 , EventParser] INFO c.alibaba.otter.canal.parse.driver.mysql.MysqlConnector - disConnect MysqlConnection to mysql.05.upanb.cn/192.168.250.214:3306...
2018-06-06 19:18:22.459 [destination = mysql.05.upanb.cn , address = mysql.05.upanb.cn/192.168.250.214:3306 , EventParser] INFO c.alibaba.otter.canal.parse.driver.mysql.MysqlConnector - disConnect MysqlConnection to mysql.05.upanb.cn/192.168.250.214:3306..

**Comment by nbqyqx** [comment]
tsdb经常报错，可以不用吗？
2018-06-07 00:44:16.671 [destination = mysql.13.upanb.cn , address = mysql.13.upanb.cn/192.168.250.226:3306 , EventParser] ERROR c.a.o.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta - pls submit github issue, show create table ddl:CREATE TABLE `group_order_history_detail_new` (
  `result_id` int(11) NOT NULL DEFAULT '0' COMMENT '订单号',
  `year` int(11) NOT NULL DEFAULT '2018' COMMENT '年',
  `month` int(11) NOT NULL DEFAULT '2' COMMENT '月',
  `order_id` int(11) NOT NULL DEFAULT '0' COMMENT '订单中心单号',
  `product_id` int(11) NOT NULL DEFAULT '0' COMMENT '项目ID',
  `product_name` varchar(50) NOT NULL DEFAULT '' COMMENT '项目名称',
  `broker_id` int(11) NOT NULL DEFAULT '0' COMMENT '经纪人ID',
  `broker_name` varchar(50) NOT NULL DEFAULT '' COMMENT '经纪人名字',
  `broker_phone` varchar(50) NOT NULL DEFAULT '' COMMENT '经纪人电话号码',
  `building_id` int(11) NOT NULL DEFAULT '0' COMMENT '楼盘ID',
  `sale_id` int(11) NOT NULL DEFAULT '0' COMMENT '销售ID',
  `sale_name` varchar(50) NOT NULL DEFAULT '' COMMENT '销售人员名称',
  `sale_group_id` int(11) NOT NULL DEFAULT '0' COMMENT '销售小组ID',
  `sale_group_name` varchar(45) NOT NULL DEFAULT '' COMMENT '销售小组名字',
  `expand_id` int(11) NOT NULL DEFAULT '0' COMMENT '拓展ID',
  `expand_name` varchar(50) NOT NULL DEFAULT '' COMMENT '拓展人员名称',
  `expand_group_id` int(11) NOT NULL DEFAULT '0' COMMENT '拓展小组ID',
  `expand_group_name` varchar(45) NOT NULL DEFAULT '' COMMENT '拓展小组名称',
  `accounts_amount` bigint(20) NOT NULL DEFAULT '0' COMMENT '应收款',
  `out_accounts_amount` bigint(20) NOT NULL DEFAULT '0' COMMENT '应付款',
  `actual_ascription_amount` bigint(20) NOT NULL DEFAULT '0' COMMENT '归属收入（应收-应付）',
  `sale_actual_ascription_amount` bigint(20) NOT NULL DEFAULT '0' COMMENT '销售归属收入',
  `expand_actual_ascription_amount` bigint(20) NOT NULL DEFAULT '0' COMMENT '拓展归属收入',
  `public_amount` bigint(20) NOT NULL DEFAULT '0' COMMENT '公共池收入(归属收入)',
  `cav_accounts_amount` bigint(20) NOT NULL DEFAULT '0' COMMENT '低于180天的实际已收款',
  `out_cav_accounts_amount` bigint(20) NOT NULL DEFAULT '0' COMMENT '超过180天的实际已收款',
  `sale_divide_rate` double(5,4) NOT NULL DEFAULT '0.0000' COMMENT '销售拓展分成比例',
  `subscription_time` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP COMMENT '认购时间',
  `handle_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '客户成交日期',
  `confirm_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '上传回执单时间',
  `confirmation_cycle` int(11) NOT NULL DEFAULT '0' COMMENT '确认周期',
  `sale_actual_accounts_amount` bigint(20) NOT NULL DEFAULT '0' COMMENT '销售小组应收金额',
  `sale_actual_cav_accounts_amount` bigint(20) NOT NULL DEFAULT '0' COMMENT '销售小组已收金额',
  `expand_actual_accounts_amount` bigint(20) NOT NULL DEFAULT '0' COMMENT '拓展小组应收金额',
  `expand_actual_cav_accounts_amount` bigint(20) NOT NULL DEFAULT '0' COMMENT '拓展小组已收金额',
  `is_baoxiao` tinyint(4) NOT NULL DEFAULT '0' COMMENT '订单是否包销 非包销 0 包销 1 类包销',
  `actual_cost` bigint(20) NOT NULL DEFAULT '0' COMMENT '实际销售费用（实际易快报中提报申请支付的业绩提成金额）',
  `fixed_amount` bigint(20) NOT NULL DEFAULT '0' COMMENT '固定收益',
  `cav_fixed_amount` bigint(20) NOT NULL DEFAULT '0' COMMENT '已回固定收益',
  `receivable_commission` bigint(20) NOT NULL DEFAULT '0' COMMENT '应收佣金',
  `cav_commission` bigint(20) NOT NULL DEFAULT '0' COMMENT '已回佣金',
  `pay_commission` bigint(20) NOT NULL DEFAULT '0' COMMENT '应付佣金',
  `cav_commission` bigint(20) NOT NULL DEFAULT '0' COMMENT '已回佣金',
  `pay_commission` bigint(20) NOT NULL DEFAULT '0' COMMENT '应付佣金',
  `receivable_deal` bigint(20) NOT NULL DEFAULT '0' COMMENT '应收成交奖',
  `cav_deal` bigint(20) NOT NULL DEFAULT '0' COMMENT '已回成交奖',
  `pay_deal` bigint(20) NOT NULL DEFAULT '0' COMMENT '应付成交奖',
  `receivable_jump` bigint(20) NOT NULL DEFAULT '0' COMMENT '应收跳点',
  `cav_jump` bigint(20) NOT NULL DEFAULT '0' COMMENT '已回跳点',
  `pay_jump` bigint(20) NOT NULL DEFAULT '0' COMMENT '应付跳点',
  `receivable_premium` bigint(20) NOT NULL DEFAULT '0' COMMENT '应收溢价',
  `cav_premium` bigint(20) NOT NULL DEFAULT '0' COMMENT '已回溢价',
  `pay_premium` bigint(20) NOT NULL DEFAULT '0' COMMENT '应付溢价',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `close_time` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '订单关闭时间',
  `is_close` tinyint(4) NOT NULL DEFAULT '0' COMMENT '0：订单未关闭，1：订单关闭',
  `sys_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '系统时间',
  `is_delete` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否删除 0:未删除 1：删除',
  UNIQUE KEY `index` (`result_id`,`year`,`month`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 , compare failed .
 db : TableMeta [schema=tops_data_gdm, table=group_order_history_detail_new, fileds=
        FieldMeta [columnName=result_id, columnType=int(11), defaultValue=0, nullable=false, key=true]
        FieldMeta [columnName=year, columnType=int(11), defaultValue=2018, nullable=false, key=true]
        FieldMeta [columnName=month, columnType=int(11), defaultValue=2, nullable=false, key=true]
        FieldMeta [columnName=order_id, columnType=int(11), defaultValue=0, nullable=false, key=false]
        FieldMeta [columnName=product_id, columnType=int(11), defaultValue=0, nullable=false, key=false]
        FieldMeta [columnName=product_name, columnType=varchar(50), defaultValue=, nullable=false, key=false]
        FieldMeta [columnName=broker_id, columnType=int(11), defaultValue=0, nullable=false, key=false]
        FieldMeta [columnName=broker_name, columnType=varchar(50), defaultValue=, nullable=false, key=false]
        FieldMeta [columnName=broker_phone, columnType=varchar(50), defaultValue=, nullable=false, key=false]
        FieldMeta [columnName=building_id, columnType=int(11), defaultValue=0, nullable=false, key=false]
        FieldMeta [columnName=sale_id, columnType=int(11), defaultValue=0, nullable=false, key=false]
        FieldMeta [columnName=sale_name, columnType=varchar(50), defaultValue=, nullable=false, key=false]
        FieldMeta [columnName=sale_group_id, columnType=int(11), defaultValue=0, nullable=false, key=false]
        FieldMeta [columnName=sale_group_name, columnType=varchar(45), defaultValue=, nullable=false, key=false]
        FieldMeta [columnName=expand_id, columnType=int(11), defaultValue=0, nullable=false, key=false]
        FieldMeta [columnName=expand_name, columnType=varchar(50), defaultValue=, nullable=false, key=false]
        FieldMeta [columnName=expand_group_id, columnType=int(11), defaultValue=0, nullable=false, key=false]
        FieldMeta [columnName=expand_group_name, columnType=varchar(45), defaultValue=, nullable=false, key=false]
        FieldMeta [columnName=accounts_amount, columnType=bigint(20), defaultValue=0, nullable=false, key=false]
        FieldMeta [columnName=out_accounts_amount, columnType=bigint(20), defaultValue=0, nullable=false, key=false]
        FieldMeta [columnName=actual_ascription_amount, columnType=bigint(20), defaultValue=0, nullable=false, key=false]
        FieldMeta [columnName=sale_actual_ascription_amount, columnType=bigint(20), defaultValue=0, nullable=false, key=false]
        FieldMeta [columnName=expand_actual_ascription_amount, columnType=bigint(20), defaultValue=0, nullable=false, key=false]
        FieldMeta [columnName=public_amount, columnType=bigint(20), defaultValue=0, nullable=false, key=false]
        FieldMeta [columnName=cav_accounts_amount, columnType=bigint(20), defaultValue=0, nullable=false, key=false]
        FieldMeta [columnName=out_cav_accounts_amount, columnType=bigint(20), defaultValue=0, nullable=false, key=false]
  FieldMeta [columnName=cav_accounts_amount, columnType=bigint(20), defaultValue=0, nullable=false, key=false]
        FieldMeta [columnName=out_cav_accounts_amount, columnType=bigint(20), defaultValue=0, nullable=false, key=false]
        FieldMeta [columnName=sale_divide_rate, columnType=double(5,4), defaultValue=0.0000, nullable=false, key=false]
        FieldMeta [columnName=subscription_time, columnType=timestamp, defaultValue=0000-00-00 00:00:00, nullable=false, key=false]
        FieldMeta [columnName=handle_time, columnType=timestamp, defaultValue=CURRENT_TIMESTAMP, nullable=false, key=false]
        FieldMeta [columnName=confirm_time, columnType=timestamp, defaultValue=CURRENT_TIMESTAMP, nullable=false, key=false]
        FieldMeta [columnName=confirmation_cycle, columnType=int(11), defaultValue=0, nullable=false, key=false]
        FieldMeta [columnName=sale_actual_accounts_amount, columnType=bigint(20), defaultValue=0, nullable=false, key=false]
        FieldMeta [columnName=sale_actual_cav_accounts_amount, columnType=bigint(20), defaultValue=0, nullable=false, key=false]
        FieldMeta [columnName=expand_actual_accounts_amount, columnType=bigint(20), defaultValue=0, nullable=false, key=false]
        FieldMeta [columnName=expand_actual_cav_accounts_amount, columnType=bigint(20), defaultValue=0, nullable=false, key=false]
        FieldMeta [columnName=is_baoxiao, columnType=tinyint(4), defaultValue=0, nullable=false, key=false]
        FieldMeta [columnName=actual_cost, columnType=bigint(20), defaultValue=0, nullable=false, key=false]
        FieldMeta [columnName=fixed_amount, columnType=bigint(20), defaultValue=0, nullable=false, key=false]
        FieldMeta [columnName=cav_fixed_amount, columnType=bigint(20), defaultValue=0, nullable=false, key=false]
        FieldMeta [columnName=receivable_commission, columnType=bigint(20), defaultValue=0, nullable=false, key=false]
        FieldMeta [columnName=cav_commission, columnType=bigint(20), defaultValue=0, nullable=false, key=false]
        FieldMeta [columnName=pay_commission, columnType=bigint(20), defaultValue=0, nullable=false, key=false]
        FieldMeta [columnName=receivable_deal, columnType=bigint(20), defaultValue=0, nullable=false, key=false]
        FieldMeta [columnName=cav_deal, columnType=bigint(20), defaultValue=0, nullable=false, key=false]
        FieldMeta [columnName=pay_deal, columnType=bigint(20), defaultValue=0, nullable=false, key=false]
        FieldMeta [columnName=receivable_jump, columnType=bigint(20), defaultValue=0, nullable=false, key=false]
        FieldMeta [columnName=cav_jump, columnType=bigint(20), defaultValue=0, nullable=false, key=false]
        FieldMeta [columnName=pay_jump, columnType=bigint(20), defaultValue=0, nullable=false, key=false]
        FieldMeta [columnName=receivable_premium, columnType=bigint(20), defaultValue=0, nullable=false, key=false]
        FieldMeta [columnName=cav_premium, columnType=bigint(20), defaultValue=0, nullable=false, key=false]
        FieldMeta [columnName=pay_premium, columnType=bigint(20), defaultValue=0, nullable=false, key=false]
        FieldMeta [columnName=create_time, columnType=timestamp, defaultValue=CURRENT_TIMESTAMP, nullable=false, key=false]
        FieldMeta [columnName=close_time, columnType=timestamp, defaultValue=null, nullable=true, key=false]
        FieldMeta [columnName=is_close, columnType=tinyint(4), defaultValue=0, nullable=false, key=false]
        FieldMeta [columnName=sys_time, columnType=timestamp, defaultValue=CURRENT_TIMESTAMP, nullable=false, key=false]
        FieldMeta [columnName=is_delete, columnType=tinyint(4), defaultValue=0, nullable=false, key=false]
]
 mem : TableMeta [schema=tops_data_gdm, table=group_order_history_detail_new, fileds=
        FieldMeta [columnName=result_id, columnType=int(11), defaultValue=0, nullable=false, key=false]
        FieldMeta [columnName=year, columnType=int(11), defaultValue=2018, nullable=false, key=false]
        FieldMeta [columnName=month, columnType=int(11), defaultValue=2, nullable=false, key=false]
        FieldMeta [columnName=order_id, columnType=int(11), defaultValue=0, nullable=false, key=false]
        FieldMeta [columnName=product_id, columnType=int(11), defaultValue=0, nullable=false, key=false]
        FieldMeta [columnName=product_name, columnType=varchar(50), defaultValue=, nullable=false, key=false]
        FieldMeta [columnName=broker_id, columnType=int(11), defaultValue=0, nullable=false, key=false]
        FieldMeta [columnName=broker_name, columnType=varchar(50), defaultValue=, nullable=false, key=false]
        FieldMeta [columnName=broker_phone, columnType=varchar(50), defaultValue=, nullable=false, key=false]
        FieldMeta [columnName=building_id, columnType=int(11), defaultValue=0, nullable=false, key=false]
        FieldMeta [columnName=sale_id, columnType=int(11), defaultValue=0, nullable=false, key=false]
  FieldMeta [columnName=building_id, columnType=int(11), defaultValue=0, nullable=false, key=false]
        FieldMeta [columnName=sale_id, columnType=int(11), defaultValue=0, nullable=false, key=false]
        FieldMeta [columnName=sale_name, columnType=varchar(50), defaultValue=, nullable=false, key=false]
        FieldMeta [columnName=sale_group_id, columnType=int(11), defaultValue=0, nullable=false, key=false]
        FieldMeta [columnName=sale_group_name, columnType=varchar(45), defaultValue=, nullable=false, key=false]
        FieldMeta [columnName=expand_id, columnType=int(11), defaultValue=0, nullable=false, key=false]
        FieldMeta [columnName=expand_name, columnType=varchar(50), defaultValue=, nullable=false, key=false]
        FieldMeta [columnName=expand_group_id, columnType=int(11), defaultValue=0, nullable=false, key=false]
        FieldMeta [columnName=expand_group_name, columnType=varchar(45), defaultValue=, nullable=false, key=false]
        FieldMeta [columnName=accounts_amount, columnType=bigint(20), defaultValue=0, nullable=false, key=false]
        FieldMeta [columnName=out_accounts_amount, columnType=bigint(20), defaultValue=0, nullable=false, key=false]
        FieldMeta [columnName=actual_ascription_amount, columnType=bigint(20), defaultValue=0, nullable=false, key=false]
        FieldMeta [columnName=sale_actual_ascription_amount, columnType=bigint(20), defaultValue=0, nullable=false, key=false]
        FieldMeta [columnName=expand_actual_ascription_amount, columnType=bigint(20), defaultValue=0, nullable=false, key=false]
        FieldMeta [columnName=public_amount, columnType=bigint(20), defaultValue=0, nullable=false, key=false]
        FieldMeta [columnName=cav_accounts_amount, columnType=bigint(20), defaultValue=0, nullable=false, key=false]
        FieldMeta [columnName=out_cav_accounts_amount, columnType=bigint(20), defaultValue=0, nullable=false, key=false]
        FieldMeta [columnName=sale_divide_rate, columnType=double(5,4), defaultValue=0.0000, nullable=false, key=false]
        FieldMeta [columnName=subscription_time, columnType=timestamp, defaultValue=0000-00-00 00:00:00, nullable=false, key=false]
        FieldMeta [columnName=handle_time, columnType=timestamp, defaultValue=CURRENT_TIMESTAMP, nullable=false, key=false]
        FieldMeta [columnName=confirm_time, columnType=timestamp, defaultValue=CURRENT_TIMESTAMP, nullable=false, key=false]
        FieldMeta [columnName=confirmation_cycle, columnType=int(11), defaultValue=0, nullable=false, key=false]
        FieldMeta [columnName=sale_actual_accounts_amount, columnType=bigint(20), defaultValue=0, nullable=false, key=false]
        FieldMeta [columnName=sale_actual_cav_accounts_amount, columnType=bigint(20), defaultValue=0, nullable=false, key=false]
        FieldMeta [columnName=expand_actual_accounts_amount, columnType=bigint(20), defaultValue=0, nullable=false, key=false]
        FieldMeta [columnName=expand_actual_cav_accounts_amount, columnType=bigint(20), defaultValue=0, nullable=false, key=false]
        FieldMeta [columnName=is_baoxiao, columnType=tinyint(4), defaultValue=0, nullable=false, key=false]
        FieldMeta [columnName=actual_cost, columnType=bigint(20), defaultValue=0, nullable=false, key=false]
        FieldMeta [columnName=fixed_amount, columnType=bigint(20), defaultValue=0, nullable=false, key=false]
        FieldMeta [columnName=cav_fixed_amount, columnType=bigint(20), defaultValue=0, nullable=false, key=false]
        FieldMeta [columnName=receivable_commission, columnType=bigint(20), defaultValue=0, nullable=false, key=false]
        FieldMeta [columnName=cav_commission, columnType=bigint(20), defaultValue=0, nullable=false, key=false]
        FieldMeta [columnName=pay_commission, columnType=bigint(20), defaultValue=0, nullable=false, key=false]
        FieldMeta [columnName=receivable_deal, columnType=bigint(20), defaultValue=0, nullable=false, key=false]
        FieldMeta [columnName=cav_deal, columnType=bigint(20), defaultValue=0, nullable=false, key=false]
        FieldMeta [columnName=pay_deal, columnType=bigint(20), defaultValue=0, nullable=false, key=false]
        FieldMeta [columnName=receivable_jump, columnType=bigint(20), defaultValue=0, nullable=false, key=false]
        FieldMeta [columnName=cav_jump, columnType=bigint(20), defaultValue=0, nullable=false, key=false]
        FieldMeta [columnName=pay_jump, columnType=bigint(20), defaultValue=0, nullable=false, key=false]
        FieldMeta [columnName=receivable_premium, columnType=bigint(20), defaultValue=0, nullable=false, key=false]
        FieldMeta [columnName=cav_premium, columnType=bigint(20), defaultValue=0, nullable=false, key=false]
        FieldMeta [columnName=pay_premium, columnType=bigint(20), defaultValue=0, nullable=false, key=false]
        FieldMeta [columnName=create_time, columnType=timestamp, defaultValue=CURRENT_TIMESTAMP, nullable=false, key=false]
        FieldMeta [columnName=close_time, columnType=timestamp, defaultValue=null, nullable=true, key=false]
        FieldMeta [columnName=is_close, columnType=tinyint(4), defaultValue=0, nullable=false, key=false]
  FieldMeta [columnName=close_time, columnType=timestamp, defaultValue=null, nullable=true, key=false]
        FieldMeta [columnName=is_close, columnType=tinyint(4), defaultValue=0, nullable=false, key=false]
        FieldMeta [columnName=sys_time, columnType=timestamp, defaultValue=CURRENT_TIMESTAMP, nullable=false, key=false]
        FieldMeta [columnName=is_delete, columnType=tinyint(4), defaultValue=0, nullable=false, key=false]
]

**Comment by nbqyqx** [comment]
2018-06-07 00:59:47.133 [destination = mysql.04.upanb.cn , address = mysql.04.upanb.cn/192.168.250.213:3306 , EventParser] ERROR c.a.o.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta - pls submit github issue, show create table ddl:CREATE TABLE `tk_broker_tag` (
  `broker_id` bigint(20) NOT NULL COMMENT '经纪人id',
  `tag_id` bigint(20) NOT NULL COMMENT '标签id,表tk_tag的主键',
  `tag_count` bigint(20) NOT NULL DEFAULT '0' COMMENT '经纪人被评价该标签的次数',
  `sys_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY `IX_broker_tag` (`broker_id`,`tag_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 , compare failed .
 db : TableMeta [schema=tops_kber, table=tk_broker_tag, fileds=
        FieldMeta [columnName=broker_id, columnType=bigint(20), defaultValue=null, nullable=false, key=true]
        FieldMeta [columnName=tag_id, columnType=bigint(20), defaultValue=null, nullable=false, key=true]
        FieldMeta [columnName=tag_count, columnType=bigint(20), defaultValue=0, nullable=false, key=false]
        FieldMeta [columnName=sys_time, columnType=timestamp, defaultValue=CURRENT_TIMESTAMP, nullable=false, key=false]
]
 mem : TableMeta [schema=tops_kber, table=tk_broker_tag, fileds=
        FieldMeta [columnName=broker_id, columnType=bigint(20), defaultValue=null, nullable=false, key=false]
        FieldMeta [columnName=tag_id, columnType=bigint(20), defaultValue=null, nullable=false, key=false]
        FieldMeta [columnName=tag_count, columnType=bigint(20), defaultValue=0, nullable=false, key=false]
        FieldMeta [columnName=sys_time, columnType=timestamp, defaultValue=CURRENT_TIMESTAMP, nullable=false, key=false]
]

**Comment by agapple** [comment]
你这是啥版本？新的版本已经修复过这个问题

**Comment by nbqyqx** [comment]
1.0.25

Neal Hu
nealhu@apache.org

**Comment by agapple** [comment]
使用最新的1.0.26
