### ISSUE TITLE
com.alibaba.otter.canal.parse.exception.CanalParseException: can't find start position for example

### ISSUE THREAD

**Issue by kervin521** [alibaba/canal#678]
![image](https://user-images.githubusercontent.com/9798724/41083138-0893606a-6a63-11e8-89e7-9fad84702144.png)

![image](https://user-images.githubusercontent.com/9798724/41083182-1f12c8f8-6a63-11e8-81f8-66bb0c8e52d3.png)

**Comment by agapple** [comment]
找不到合适的位点
