### ISSUE TITLE
开启detecting，经常报Connection reset by peer

### ISSUE THREAD

**Issue by kenmanoy** [alibaba/canal#684]
看到其他issue说建议开启心跳，所以把它开启
canal.instance.detecting.enable =true
canal.instance.detecting.heartbeatHaEnable = true
结果很容易出错，报错时不影响数据捕获，第二天再看就无法捕获数据。关闭后正常。

**Comment by jingshenbusi6530** [comment]
1.0.25版本，我的这两个参数都是false，还是不稳定，我这是客户端间隔一段时间连，服务端就会出Connection reset by peer，但也不是必出现，在我们的α环境出，在我本地测试了一下午，就不出这个错

**Comment by DevWithLin** [comment]
建议更新到26版本的

**Comment by agapple** [comment]
https://github.com/alibaba/canal/issues/640，关注一下这个
