### ISSUE TITLE
canal server swap被占满，导致磁盘空间100%使用

### ISSUE THREAD

**Issue by bupt-yjw** [alibaba/canal#686]
如题，v1.0.26 alpha 2版本 canal server swap被占满，导致磁盘空间100%使用

**Comment by agapple** [comment]
swap内存？

**Comment by bupt-yjw** [comment]
%Cpu(s):  0.2 us,  0.2 sy,  0.0 ni, 99.6 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem:   8193776 total,  8050240 used,   143536 free,    87860 buffers
KiB Swap:        0 total,        0 used,        0 free,  6344652 cached
canal server的这个swap cached 只增不减，导致最终磁盘空间使用率为100%
当前：rootfs           60G   12G   46G  20% /
重启canal server以后，swap cached为0，磁盘空间恢复正常，然后就开始下一轮只增不减的过程了
