### ISSUE TITLE
监听不到binlog

### ISSUE THREAD

**Issue by fanpeng1100** [alibaba/canal#693]
使用1.0.23监听的时候，mysql的binlog配置log-bin=mysql186-bin这种结构，监听不到。请问是否和binlog文件名称有关系？

**Comment by agapple** [comment]
还没人反馈过类似问题，请描述重现步骤

**Comment by fanpeng1100** [comment]
应该是我来回切换集群模式造成的，清理zk下生成的文件就好了

**Comment by monkeyapples** [comment]
@lamsley  监听的是从库还是主库？

**Comment by lamsley** [comment]
@monkeyapples 只有一个库 看了库的binlog日志 都有变化 说明打开了binlog是成功的 但是只有canal客户端一直message为空

**Comment by lamsley** [comment]
监听的是主库，数据库的开启的binlog也是没有问题的 
最后保持原有的不变，改安装了1.0.24后就可以监听到
但是为什么1.1.2不可以 
是不是这两个版本配置方式不一样



lamsley@163.com
 
发件人： monkeyapples
发送时间： 2018-12-21 17:42
收件人： alibaba/canal
抄送： lamsley; Mention
主题： Re: [alibaba/canal] 监听不到binlog (#693)
@lamsley 监听的是从库还是主库？

**Comment by Maskedlaodi** [comment]
给你的MySQL用户赋权限没有呢

**Comment by Tigojiang** [comment]
我也是这个问题，sql给用户权限了

**Comment by ATCThunder** [comment]
我直接用admin,但是还是看不到日志变化，实际上是能监听的到
