### ISSUE TITLE
指定Filter不起作用，还是能够获取到全库的监听数据。

### ISSUE THREAD

**Issue by uniorder** [alibaba/canal#702]
`connector.subscribe("databaseName.tableName");`
这段代码我指定了filter，可还是能够收到所有表的binlog数据，请问是不是为哪里配置有问题？

**Comment by agapple** [comment]
搜索一下历史issue

**Comment by threedays163** [comment]
filter使用的是正则表达式，你这个正则要转义一下才能用，比如你这个例子：databaseName.tableName需要转义成

> databaseName\\.tableName

才能用。"."在正则中代表任意字符。“\.”含义才是点，由于单个反斜杠代表转义，因此也需要被转义，所以就变成上面那个样子了

**Comment by agapple** [comment]
看一下 FAQ : https://github.com/alibaba/canal/wiki/FAQ
