### ISSUE TITLE
当表设置的主键对字段长度进行限定时，canal不识别该列

### ISSUE THREAD

**Issue by linweijiang** [alibaba/canal#704]
CREATE TABLE `job_execution_script` (
  `app_id` INT(11) NOT NULL,
  `job_id` INT(11) NOT NULL,
  `script_name` VARCHAR(512) NOT NULL DEFAULT '',
  `committer_name` VARCHAR(128) NOT NULL DEFAULT '',
  PRIMARY KEY (`app_id`,`job_id`,`script_name`(100),`committer_name`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;
当表结构如上时，canal会报 “unknow column `script_name`(100)” 的ERROR~
谢谢~

**Comment by agapple** [comment]
你用的是最新的1.0.26版本么？这个我记得已经修复过

**Comment by linweijiang** [comment]
我用的是1.0.25版本的，这个问题还是存在~
