### ISSUE TITLE
数据处理失败，回滚后，会有重复处理的情况

### ISSUE THREAD

**Issue by mjjian0** [alibaba/canal#708]
因为是按 批次id   ack和rollback的，如果一个批次里的一条处理失败了，这个时候开始回滚，然后重新处理刚才处理失败的批次数据，如果那个批次的处理失败的之前的都是处理成功的，这次处理岂不是又重复处理了？ @agapple

**Comment by DevWithLin** [comment]
重复无法避免

**Comment by linweijiang** [comment]
那只能在自己的代码中去重

**Comment by wbsch52** [comment]
我遇到过这个情况, 我是是捕获异常后将当前批次的数据持久化到数据库记录异常信息. 然后正常提交该批次的数据, 为了避免重复处理.

**Comment by CodingSinger** [comment]
除了这个措施之外还需要避免处理了一半就异常崩溃的情况吧？
