### ISSUE TITLE
canal连接阿里云RDS

### ISSUE THREAD

**Issue by zhp8341** [alibaba/canal#711]
相关rds的配置文件好像没有啊？另外canal.instance.rds.open.url=https://rds.aliyuncs.com/ 这个配置是针对外网的  是否有内网地址？

**Comment by agapple** [comment]
这个是RDS binlog的openapi下载的配置，目前还未完全成型，如果需要使用可以了解一下代码

**Comment by agapple** [comment]
参考：https://github.com/alibaba/canal/wiki/FAQ
