### ISSUE TITLE
tableMetaTSDB找位点进入无限循环中

### ISSUE THREAD

**Issue by zhp8341** [alibaba/canal#716]
在这个类**MysqlEventParser** 下面这个方法
   **### /**
     * 根据给定的时间戳，在指定的binlog中找到最接近于该时间戳(必须是小于时间戳)的一个事务起始位置。
     * 针对最后一个binlog会给定endPosition，避免无尽的查询
     */
    private EntryPosition findAsPerTimestampInSpecificLogFile(MysqlConnection mysqlConnection,
                                                              final Long startTimestamp,
                                                              final EntryPosition endPosition,
                                                              final String searchBinlogFile,
                                                              final Boolean justForPositionTimestamp)**

我的配置文件里面指定了
canal.instance.master.journal.name=mysql-bin.000344
canal.instance.master.position=106199547

开启tsdb功能后

canal服务启动的时候 程序会进入这里找起始位点 由于没有找到这个位点程序会一致找下去甚至大于106199547 了还在找导致一直出于初始化阶段，然后就会出现 客户端无法创建cursor 。https://github.com/alibaba/canal/issues/715

**Comment by agapple** [comment]
是位点不存在还是？

**Comment by zhp8341** [comment]
show binlog events in'mysql-bin.000344'

mysql-bin.000344	106199500	Rotate	609344520	106199547	mysql-bin.000345;pos=4

这条是最后一条记录

**Comment by agapple** [comment]
你是拿到一个位点之后，一直没有新的数据么？

**Comment by zhp8341** [comment]
106199547 是mysql-bin.000344的最后一个位点， 但是下面是有 mysql-bin.000345文件的

**Comment by agapple** [comment]
最新的26版本优化了，判断退出条件为<=
