### ISSUE TITLE
canal.instance.filter.regex 这个属性值的长度有限制吗

### ISSUE THREAD

**Issue by shizhengchao** [alibaba/canal#720]
如题：因为需求里同一个mysql，需要取的不同数据库，表也不同，我担心这个值越来越大
请问有长度限制吗

**Comment by agapple** [comment]
正则表达式有长度限制，我印象中是4k

**Comment by shizhengchao** [comment]
@agapple 借此再问一个问题哈。canal server的读取binlog的进度是保存在哪的，意思是停止server后,binlog位置信息保存在哪。我需要拿到这个东西
