### ISSUE TITLE
canal server和mysql部署在同一台机器，解析binlog失败

### ISSUE THREAD

**Issue by smile0327** [alibaba/canal#722]
canal版本1.0.25 , mysql版本5.7.10 , 最开始我将canal server部署在跟mysql同一台机器上，启动正常，操作数据库记录，binlog日志有更新，但是canal的客户端未读取到。后来将canal server部署在其他机器上，就能正常捕获到binlog的信息了。不太清楚为什么会出现这种现象，或者是不是我漏了哪些配置？

**Comment by agapple** [comment]
canal 25版本不建议使用了

**Comment by smile0327** [comment]
更换了一个版本1.0.24，确实可以了
