### ISSUE TITLE
EventParser] ERROR c.a.o.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta

### ISSUE THREAD

**Issue by qingmu2017** [alibaba/canal#725]
EventParser] ERROR c.a.o.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta - pls submit github issue, 
 show create table ddl:CREATE TABLE `batch_job_seq` (
  `ID` bigint(20) NOT NULL,
  `UNIQUE_KEY` char(1) NOT NULL,
  UNIQUE KEY `UNIQUE_KEY_UN` (`UNIQUE_KEY`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 , compare failed . 
 db : TableMeta [schema=test, table=batch_job_seq, fileds=
	FieldMeta [columnName=ID, columnType=bigint(20), defaultValue=null, nullable=false, key=false]
	FieldMeta [columnName=UNIQUE_KEY, columnType=char(1), defaultValue=null, nullable=false, key=true]
] 
 mem : TableMeta [schema=test, table=batch_job_seq, fileds=
	FieldMeta [columnName=ID, columnType=bigint(20), defaultValue=null, nullable=false, key=false]
	FieldMeta [columnName=UNIQUE_KEY, columnType=char(1), defaultValue=null, nullable=false, key=false]
]

**Comment by agapple** [comment]
你这是老版本25的吧, 升级到26, 已经修复

**Comment by sky-mariner** [comment]
@qingmu2017 请问你这个问题升级到26后解决了吗？我现在用的是26-SNAPSHOT，还是有这个问题
