### ISSUE TITLE
jar包冲突 spring-code和canal.common

### ISSUE THREAD

**Issue by wangbingqiong** [alibaba/canal#728]
引用canal.client 1.0.12后，代码报出
org.springframework.core.MethodParameter（Cannot resolve method 'hasParameterAnnotation(java.lang.Class<>）
spring-code 4.3.14.RELEASE

操作
<dependency>
    <groupId>com.alibaba.otter</groupId>
    <artifactId>canal.client</artifactId>
    <version>1.0.12</version>
    <exclusions>
	......
	<exclusion>
		<artifactId>canal.common</artifactId>
		<groupId>com.alibaba.otter</groupId>
	</exclusion>
    </exclusions>
</dependency>后正常，
运行代码报错java.lang.NoClassDefFoundError: com/alibaba/otter/canal/common/utils/BooleanMutex
该如何解决？

**Comment by agapple** [comment]
你在canal版本也有点低了，升级一下到1.0.26
