### ISSUE TITLE
update 语句为什么是ddl ？

### ISSUE THREAD

**Issue by JasonHuangHuster** [alibaba/canal#729]
![image](https://user-images.githubusercontent.com/5965173/42147450-74b6f6e8-7e00-11e8-99a5-53c8061c88f5.png)

如图。

**Comment by JasonHuangHuster** [comment]
mysql 5.5.24   请问这个版本支持会有问题吗？
发现会有更新数据丢失的问题，还有会解析异常。。。
![image](https://user-images.githubusercontent.com/5965173/42151207-cd8a93f2-7e0e-11e8-8250-6ac2445ef3a3.png)

**Comment by agapple** [comment]
DDL语法解析错误，不会影响DML数据

**Comment by JasonHuangHuster** [comment]
手动更新数据库，观察发现有的数据能够在canal client 成功收到，有一些没有，因此就得出数据有丢失的结论。
“当前的canal开源版本支持5.7及以下的版本(阿里内部mysql 5.7.13, 5.6.10, mysql 5.5.18和5.1.40/48)”
因此5.5.24 官方版本，是不保证数据的可靠性，存在丢失的情况对吗？

**Comment by JasonHuangHuster** [comment]
“目前canal测试已支持mysql 5.7.13/5.6.10及以下的版本，mariadb 5.5.35和10.0.7(理论上可支持以下版本)”

但是这里描述来看。5.5.24 应该是支持的，因此不知道是什么原因。麻烦解答一下。谢谢！：D

**Comment by liangzhaoqiang** [comment]
> ![image](https://user-images.githubusercontent.com/5965173/42151092-603695a8-7e0e-11e8-8386-8920b4bc4d70.png)
> 
> 如图。

请问sql是怎么获取的？我想要获取dml的sql，但是只能获取到rowChage.getRowDatasList()
![image](https://user-images.githubusercontent.com/46156204/51965252-db5bb380-24a3-11e9-895e-f58b1f4f7756.png)

**Comment by agapple** [comment]
@liangzhaoqiang row模式的binlog里就没有SQL信息

**Comment by ruochen** [comment]
> @liangzhaoqiang row模式的binlog里就没有SQL信息

是否可以利用binlog2sql的思想组合出SQL信息？ 
毕竟SQL信息对排查和其他地方的用途还是不小的
