### ISSUE TITLE
canal 增加 create database支持

### ISSUE THREAD

**Issue by qmz** [alibaba/canal#730]
拉了1.0.26-preview3分支测试，目前canal在处理Query事件create database，没有对建库语句进行parser
调用逻辑
LogEventConvert#parseQueryEvent
-> DruidDdlParser.parse(queryString, event.getDbName());
-> fastsql_preview366#SQLCreateDatabaseStatement
目前没有fastsql的代码，大致修改如下，麻烦大神看看是否合适
![qq 20180702202624](https://user-images.githubusercontent.com/5847660/42163743-3e061f4e-7e36-11e8-8126-24af0d1386cf.jpg)

**Comment by qmz** [comment]
最新的trunk master也没有处理这个问题，fastsql什么时候开源<_-

**Comment by agapple** [comment]
你提交一个MR给我吧

**Comment by qmz** [comment]
#734 提了一个PR
