### ISSUE TITLE
canal显示连接成功，但是数据库改变的时候收不到订阅消息

### ISSUE THREAD

**Issue by CaroseKYS** [alibaba/canal#731]
canal启动并没有报错，但是无论怎么操作数据库，都没有数据库改变的日志打印出来。求大神指教。

![image](https://user-images.githubusercontent.com/8399936/42198827-071f8a10-7ebd-11e8-95ee-d0438707b334.png)

**Comment by JSK520** [comment]
解决了吗？

**Comment by agapple** [comment]
推荐用v1.1.1新版本了

**Comment by indextg** [comment]
楼主解决了问题吗？求教  我用的最新版版本1.1.3，也是不行的

**Comment by AaronZhang9511** [comment]
我最新1.1.3也不行

**Comment by 9958** [comment]
我也是，好奇怪
