### ISSUE TITLE
v1.0.24, canal.instance.filter.regex无效

### ISSUE THREAD

**Issue by miraisenshi** [alibaba/canal#733]
使用1.0.24版本
只需要监听两张表的binlog, 在instance.properties文件中有设定:
canal.instance.defaultDatabaseName = mall
canal.instance.filter.regex = mall.users,mall.users_extra_info

客户端代码没有写connector.subscribe()语句
但是接收到的仍然是mall数据库所有表的binlog
求解

**Comment by luyee** [comment]
正则应该只有硬编码是ok的，另外正则不支持复杂的～慎重
