### ISSUE TITLE
阿里云RDS如何使用GTID

### ISSUE THREAD

**Issue by luedongtech** [alibaba/canal#738]
阿里云上使用的RDS版本是5.6，之前用binlog+position的方式可以正常同步数据，尝试设置
``canal.instance.gtidon=true``后报错：
```
java.io.IOException: Received error packet: errno = 1236, 
sqlstate = HY000 errmsg = The slave is connecting using CHANGE MASTER TO MASTER_AUTO_POSITION = 1, 
but the master has purged binary logs containing GTIDs that the slave requires.
```
请问是不是需要修改RDS的配置？ 我的canal的版本是1.0.26

**Comment by agapple** [comment]
这个需要mysql设置gtid的能力, 你搜索一下errmsg就可以了, 或者看我gtid的issue

**Comment by awayings** [comment]
我也遇到类似的问题。检查过gtid已经启用了。有搜索到是因为主库上GIT_PURGED有值导致从库无法同步。其他帖子里面也没有知道原因。

**Comment by awayings** [comment]
我也遇到类似的问题。检查过gtid已经启用了。有搜索到是因为主库上GIT_PURGED有值导致从库无法同步。其他帖子里面也没有知道原因。 @agapple
