### ISSUE TITLE
wiki中的一些疑问

### ISSUE THREAD

**Issue by chenchuangc** [alibaba/canal#740]
AdminGuide  https://github.com/alibaba/canal/wiki/AdminGuide 中对 spring组装方式区别的介绍中是不是有一点模糊啊
![image](https://user-images.githubusercontent.com/13183268/42429351-1335062e-836b-11e8-9d1e-d0566544cbf8.png)
store不是只有内存模式么，这里的store的存储应该是只有memory,而不会存储到zookeeper和file当中吧。

**Comment by agapple** [comment]
你的理解是正确的, store这块只有memory的能力
