### ISSUE TITLE
canal service因删除log下面的temp日志而服务没有重启导致磁盘空间被占用

### ISSUE THREAD

**Issue by bupt-yjw** [alibaba/canal#745]
如题，canal 服务端发现磁盘被占用，但是没找到具体占用的问题，通过lsof |grep delete发现大量如下信息：
java      37924 37925       appops    2w      REG              254,1 50965216675     136005 /home/appops/canal/logs/canal/canal.log6671827459413464.tmp (deleted)
查了下，文件被删除，而进程还活着，因而造成占用空间的现象，需要kill掉进程才能恢复，但是服务总是通过kill掉来恢复肯定不方便，有什么好的解决方式吗

**Comment by zhangweiqiang-github** [comment]
大佬，这个问题有解决吗？

**Comment by Yanxinwei** [comment]
同问大佬,这个问题解决没有?如果解决的话,具体的解决方案是什么?

**Comment by ChenZebedee** [comment]
难道要定期restart一下吗？目前都是用手动restart来进行释放，不知道各位大佬有没有解决方案

**Comment by bupt-yjw** [comment]
把log级别调成error日志会小很多




发自网易邮箱大师


在2019年07月3日 18:11，zclynne<notifications@github.com> 写道：

难道要定期restart一下吗？目前都是用手动restart来进行释放，不知道各位大佬有没有解决方案

**Comment by bupt-yjw** [comment]
把log基本调成error，不需要他打出来的info日志




发自网易邮箱大师


在2019年07月3日 15:18，Yanxinwei<notifications@github.com> 写道：

同问大佬,这个问题解决没有?如果解决的话,具体的解决方案是什么?
