### ISSUE TITLE
canal server 连接数据库超时

### ISSUE THREAD

**Issue by sky-syk** [alibaba/canal#746]
server连接数据库超时，然后就不再重新连接了，过了大概两个小时后 ，又自动重新连接了，请问是哪个参数可以设置 超时之后过多长时间重新连接呢

**Comment by kervin521** [comment]
你换成v1.0.25版本吧，v1.0.26有问题

**Comment by DevWithLin** [comment]
我的没有问题？看一下日志？有报错吗？

**Comment by DevWithLin** [comment]
25版本已经标记不建议使用了，nio的问题

**Comment by kervin521** [comment]
@WithLin 26版本这不停的断开重连也太大啦（下午7点之后出现此情况比较多），换成25版本就没问题，看是否是定时器哪里有问题

**Comment by sky-syk** [comment]
@WithLin  报错就是简单的连接超时 connect timeout 感觉可能是网络波动引起的，但是 它隔了2个小时才去重新获取连接，是不是太太久了。超时之后 多久去重新获取连接，没有可以自己设置的参数么

**Comment by WithLin** [comment]
网络的问题重试就好了啊？ while(true) ,catch 的时候休息多久，做重试，就好了
