### ISSUE TITLE
canal的dump太慢怎么处理

### ISSUE THREAD

**Issue by kervin521** [alibaba/canal#748]
MySQL的show master status
mysql-bin.000093
canal的dump的zk中parse：
mysql-bin.000064

每个binlog大小100M

dump entry: 30~40 event/second

在MySQL中show full processlist:
显示canal的dump为 # writing to net

**Comment by DevWithLin** [comment]
你这是新版本的嘛？

**Comment by kervin521** [comment]
@WithLin v1.0.25，v1.0.26有问题有不停的断开重连数据库还有数据库连接超时问题

**Comment by kervin521** [comment]
@agapple

**Comment by agapple** [comment]
@kervin521 具体描述一下v1.0.26的问题, 你提的太笼统
