### ISSUE TITLE
GTID无法获取到

### ISSUE THREAD

**Issue by 282857484** [alibaba/canal#752]
![6b06917b225fc61a76d0b901b656ecc9](https://user-images.githubusercontent.com/5210147/42793757-40d64d60-89ae-11e8-8090-f69238c5ed5a.jpg)
我的主从都是开启的gtid，同步正常，只有在transactionend的时候会有事务id，其它时候无法获取到gtid和事务id

**Comment by agapple** [comment]
gtid的获取方式你看过example代码了吗？在扩展属性字段里

**Comment by 282857484** [comment]
哥，example里 entry.getHeader().getGtid() 打印出来是个空字符串

**Comment by agapple** [comment]
需要开启canal gtid的订阅

**Comment by 282857484** [comment]
instance.property
canal.instance.gtidon=true
把这个打开就ok！
thanks！！！

**Comment by qiuchunliu** [comment]
> instance.property
> canal.instance.gtidon=true
> 把这个打开就ok！
> thanks！！！

请问大佬，打开了这个开关也获取不到事务id

**Comment by chutianmen** [comment]
我也是打开GTID也获取不到
