### ISSUE TITLE
配置的filter.regex不生效，server没有过滤掉sys库数据，有时候也没过滤掉mysql库数据

### ISSUE THREAD

**Issue by arsenal1886** [alibaba/canal#755]
版本：1.0.26
binlog模式：ROW

instance.properties配置：
canal.instance.filter.regex=blacklist3\\..*
canal.instance.filter.black.regex=

server日志：
2018-07-17 15:45:09.388 [destination = xxxx , address = /xxxx:xxxx , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:xxxx[com.alibaba.otter.canal.parse.exception.CanalParseException: java.io.IOException: ErrorPacket [errorNumber=1142, fieldCount=-1, message=SHOW VIEW command denied to user 'xxxx'@'xxxx for table 'host_summary', sqlState=42000, sqlStateMarker=#]
 with command: show create table `sys`.`host_summary`;show create table `sys`.`host_summary_by_file_io`;show create table `sys`.`host_summary_by_file_io_type`;show create table `sys`.`host_summary_by_stages`;show create table `sys`.`host_summary_by_statement_latency`;show create table `sys`.`host_summary_by_statement_type`;show create table `sys`.`innodb_buffer_stats_by_schema`;show create table `sys`.`innodb_buffer_stats_by_table`;show create table `sys`.`innodb_lock_waits`;show create table `sys`.`io_by_thread_by_latency`;show create table `sys`.`io_global_by_file_by_bytes`;show create table `sys`.`io_global_by_file_by_latency`;show create table `sys`.`io_global_by_wait_by_bytes`;show create table `sys`.`io_global_by_wait_by_latency`;show create table `sys`.`latest_file_io`;show create table `sys`.`memory_by_host_by_current_bytes`;show create table `sys`.`memory_by_thread_by_current_bytes`;show create table `sys`.`memory_by_user_by_current_bytes`;show create table `sys`.`memory_global_by_current_bytes`;show create table `sys`.`memory_global_total`;show create table `sys`.`metrics`;show create table `sys`.`processlist`;show create table `sys`.`ps_check_lost_instrumentation`;show create table `sys`.`schema_auto_increment_columns`;show create table `sys`.`schema_index_statistics`;show create table `sys`.`schema_object_overview`;show create table `sys`.`schema_redundant_indexes`;show create table `sys`.`schema_table_lock_waits`;show create table `sys`.`schema_table_statistics`;show create table `sys`.`schema_table_statistics_with_buffer`;show create table `sys`.`schema_tables_with_full_table_scans`;show create table `sys`.`schema_unused_indexes`;show create table `sys`.`session`;show create table `sys`.`session_ssl_status`;show create table `sys`.`statement_analysis`;show create table `sys`.`statements_with_errors_or_warnings`;show create table `sys`.`statements_with_full_table_scans`;show create table `sys`.`statements_with_runtimes_in_95th_percentile`;show create table `sys`.`statements_with_sorting`;show create table `sys`.`statements_with_temp_tables`;show create table `sys`.`sys_config`;show create table `sys`.`user_summary`;show create table `sys`.`user_summary_by_file_io`;show create table `sys`.`user_summary_by_file_io_type`;show create table `sys`.`user_summary_by_stages`;show create table `sys`.`user_summary_by_statement_latency`;show create table `sys`.`user_summary_by_statement_type`;show create table `sys`.`version`;show create table `sys`.`wait_classes_global_by_avg_latency`;show create table `sys`.`wait_classes_global_by_latency`;show create table `sys`.`waits_by_host_by_latency`;show create table `sys`.`waits_by_user_by_latency`;show create table `sys`.`waits_global_by_latency`;show create table `sys`.`x$host_summary`;show create table `sys`.`x$host_summary_by_file_io`;show create table `sys`.`x$host_summary_by_file_io_type`;show create table `sys`.`x$host_summary_by_stages`;show create table `sys`.`x$host_summary_by_statement_latency`;show create table `sys`.`x$host_summary_by_statement_type`;show create table `sys`.`x$innodb_buffer_stats_by_schema`;show create table `sys`.`x$innodb_buffer_stats_by_table`;show create table `sys`.`x$innodb_lock_waits`;show create table `sys`.`x$io_by_thread_by_latency`;show create table `sys`.`x$io_global_by_file_by_bytes`;show create table `sys`.`x$io_global_by_file_by_latency`;show create table `sys`.`x$io_global_by_wait_by_bytes`;show create table `sys`.`x$io_global_by_wait_by_latency`;show create table `sys`.`x$latest_file_io`;show create table `sys`.`x$memory_by_host_by_current_bytes`;show create table `sys`.`x$memory_by_thread_by_current_bytes`;show create table `sys`.`x$memory_by_user_by_current_bytes`;show create table `sys`.`x$memory_global_by_current_bytes`;show create table `sys`.`x$memory_global_total`;show create table `sys`.`x$processlist`;show create table `sys`.`x$ps_digest_95th_percentile_by_avg_us`;show create table `sys`.`x$ps_digest_avg_latency_distribution`;show create table `sys`.`x$ps_schema_table_statistics_io`;show create table `sys`.`x$schema_flattened_keys`;show create table `sys`.`x$schema_index_statistics`;show create table `sys`.`x$schema_table_lock_waits`;show create table `sys`.`x$schema_table_statistics`;show create table `sys`.`x$schema_table_statistics_with_buffer`;show create table `sys`.`x$schema_tables_with_full_table_scans`;show create table `sys`.`x$session`;show create table `sys`.`x$statement_analysis`;show create table `sys`.`x$statements_with_errors_or_warnings`;show create table `sys`.`x$statements_with_full_table_scans`;show create table `sys`.`x$statements_with_runtimes_in_95th_percentile`;show create table `sys`.`x$statements_with_sorting`;show create table `sys`.`x$statements_with_temp_tables`;show create table `sys`.`x$user_summary`;show create table `sys`.`x$user_summary_by_file_io`;show create table `sys`.`x$user_summary_by_file_io_type`;show create table `sys`.`x$user_summary_by_stages`;show create table `sys`.`x$user_summary_by_statement_latency`;show create table `sys`.`x$user_summary_by_statement_type`;show create table `sys`.`x$wait_classes_global_by_avg_latency`;show create table `sys`.`x$wait_classes_global_by_latency`;show create table `sys`.`x$waits_by_host_by_latency`;show create table `sys`.`x$waits_by_user_by_latency`;show create table `sys`.`x$waits_global_by_latency`;
Caused by: java.io.IOException: ErrorPacket [errorNumber=1142, fieldCount=-1, message=SHOW VIEW command denied to user 'xxxx'@'xxxx' for table 'host_summary', sqlState=42000, sqlStateMarker=#]
 with command: show create table `sys`.`host_summary`;show create table `sys`.`host_summary_by_file_io`;show create table `sys`.`host_summary_by_file_io_type`;show create table `sys`.`host_summary_by_stages`;show create table `sys`.`host_summary_by_statement_latency`;show create table `sys`.`host_summary_by_statement_type`;show create table `sys`.`innodb_buffer_stats_by_schema`;show create table `sys`.`innodb_buffer_stats_by_table`;show create table `sys`.`innodb_lock_waits`;show create table `sys`.`io_by_thread_by_latency`;show create table `sys`.`io_global_by_file_by_bytes`;show create table `sys`.`io_global_by_file_by_latency`;show create table `sys`.`io_global_by_wait_by_bytes`;show create table `sys`.`io_global_by_wait_by_latency`;show create table `sys`.`latest_file_io`;show create table `sys`.`memory_by_host_by_current_bytes`;show create table `sys`.`memory_by_thread_by_current_bytes`;show create table `sys`.`memory_by_user_by_current_bytes`;show create table `sys`.`memory_global_by_current_bytes`;show create table `sys`.`memory_global_total`;show create table `sys`.`metrics`;show create table `sys`.`processlist`;show create table `sys`.`ps_check_lost_instrumentation`;show create table `sys`.`schema_auto_increment_columns`;show create table `sys`.`schema_index_statistics`;show create table `sys`.`schema_object_overview`;show create table `sys`.`schema_redundant_indexes`;show create table `sys`.`schema_table_lock_waits`;show create table `sys`.`schema_table_statistics`;show create table `sys`.`schema_table_statistics_with_buffer`;show create table `sys`.`schema_tables_with_full_table_scans`;show create table `sys`.`schema_unused_indexes`;show create table `sys`.`session`;show create table `sys`.`session_ssl_status`;show create table `sys`.`statement_analysis`;show create table `sys`.`statements_with_errors_or_warnings`;show create table `sys`.`statements_with_full_table_scans`;show create table `sys`.`statements_with_runtimes_in_95th_percentile`;show create table `sys`.`statements_with_sorting`;show create table `sys`.`statements_with_temp_tables`;show create table `sys`.`sys_config`;show create table `sys`.`user_summary`;show create table `sys`.`user_summary_by_file_io`;show create table `sys`.`user_summary_by_file_io_type`;show create table `sys`.`user_summary_by_stages`;show create table `sys`.`user_summary_by_statement_latency`;show create table `sys`.`user_summary_by_statement_type`;show create table `sys`.`version`;show create table `sys`.`wait_classes_global_by_avg_latency`;show create table `sys`.`wait_classes_global_by_latency`;show create table `sys`.`waits_by_host_by_latency`;show create table `sys`.`waits_by_user_by_latency`;show create table `sys`.`waits_global_by_latency`;show create table `sys`.`x$host_summary`;show create table `sys`.`x$host_summary_by_file_io`;show create table `sys`.`x$host_summary_by_file_io_type`;show create table `sys`.`x$host_summary_by_stages`;show create table `sys`.`x$host_summary_by_statement_latency`;show create table `sys`.`x$host_summary_by_statement_type`;show create table `sys`.`x$innodb_buffer_stats_by_schema`;show create table `sys`.`x$innodb_buffer_stats_by_table`;show create table `sys`.`x$innodb_lock_waits`;show create table `sys`.`x$io_by_thread_by_latency`;show create table `sys`.`x$io_global_by_file_by_bytes`;show create table `sys`.`x$io_global_by_file_by_latency`;show create table `sys`.`x$io_global_by_wait_by_bytes`;show create table `sys`.`x$io_global_by_wait_by_latency`;show create table `sys`.`x$latest_file_io`;show create table `sys`.`x$memory_by_host_by_current_bytes`;show create table `sys`.`x$memory_by_thread_by_current_bytes`;show create table `sys`.`x$memory_by_user_by_current_bytes`;show create table `sys`.`x$memory_global_by_current_bytes`;show create table `sys`.`x$memory_global_total`;show create table `sys`.`x$processlist`;show create table `sys`.`x$ps_digest_95th_percentile_by_avg_us`;show create table `sys`.`x$ps_digest_avg_latency_distribution`;show create table `sys`.`x$ps_schema_table_statistics_io`;show create table `sys`.`x$schema_flattened_keys`;show create table `sys`.`x$schema_index_statistics`;show create table `sys`.`x$schema_table_lock_waits`;show create table `sys`.`x$schema_table_statistics`;show create table `sys`.`x$schema_table_statistics_with_buffer`;show create table `sys`.`x$schema_tables_with_full_table_scans`;show create table `sys`.`x$session`;show create table `sys`.`x$statement_analysis`;show create table `sys`.`x$statements_with_errors_or_warnings`;show create table `sys`.`x$statements_with_full_table_scans`;show create table `sys`.`x$statements_with_runtimes_in_95th_percentile`;show create table `sys`.`x$statements_with_sorting`;show create table `sys`.`x$statements_with_temp_tables`;show create table `sys`.`x$user_summary`;show create table `sys`.`x$user_summary_by_file_io`;show create table `sys`.`x$user_summary_by_file_io_type`;show create table `sys`.`x$user_summary_by_stages`;show create table `sys`.`x$user_summary_by_statement_latency`;show create table `sys`.`x$user_summary_by_statement_type`;show create table `sys`.`x$wait_classes_global_by_avg_latency`;show create table `sys`.`x$wait_classes_global_by_latency`;show create table `sys`.`x$waits_by_host_by_latency`;show create table `sys`.`x$waits_by_user_by_latency`;show create table `sys`.`x$waits_global_by_latency`;
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlQueryExecutor.queryMulti(MysqlQueryExecutor.java:109)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.queryMulti(MysqlConnection.java:101)
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.dumpTableMeta(DatabaseTableMeta.java:173)
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.rollback(DatabaseTableMeta.java:127)
	at com.alibaba.otter.canal.parse.inbound.mysql.AbstractMysqlEventParser.processTableMeta(AbstractMysqlEventParser.java:84)
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:173)
	at java.lang.Thread.run(Thread.java:745)

**Comment by agapple** [comment]
debug看看DatabaseTableMeta.dumpTableMeta()是否filter条件没正确接收到，被client的subscribe条件给覆盖了

**Comment by arsenal1886** [comment]
应该是这个问题！
在server端双实例的切换。
client端配置如下都会影响到server端：
String filter = ".*";
String filter = "\\.*";
String filter = "\\.\\*";
String filter = ".*\\\\..*";

看了一下源码  如果设置成null，就不影响。
String filter = null;

具体的影响表现为，后启动的那个server会订阅server端filter之外的表，导致没权限报错，客户端getMessage就一直是空。
两个server实例配置：
canal.properties 除了canal.id canal.port都一样
instance.properties 除了 canal.instance.mysql.slaveId都一样。
canal.instance.filter.regex=blacklist3\\..*
