### ISSUE TITLE
 com.lmax.disruptor.FatalExceptionHandler handleEventException

### ISSUE THREAD

**Issue by yanconcon** [alibaba/canal#756]
刚了解canal，直接用canal.kafka-1.0.26-SNAPSHOT.tar包的时候会报一个com.alibaba.druid.pool.DruidDataSource - testWhileIdle is true, validationQuery not set，但还是可以用，但在用kafka包跑CanalLauncher.java的时候出现错误
![image](https://user-images.githubusercontent.com/26325971/42809370-19b008e0-89e8-11e8-8ba0-bc520efcb083.png)，请问是我哪里做错了吗。

**Comment by yanconcon** [comment]
真的找不到错误在哪里，楼主help me。
![image](https://user-images.githubusercontent.com/26325971/42810158-d57bd4ae-89e9-11e8-95a9-97a38b5d6402.png)，配置文件信息
![image](https://user-images.githubusercontent.com/26325971/42810224-04150a7e-89ea-11e8-954b-1855e2d8fe0b.png)

**Comment by yanconcon** [comment]
![image](https://user-images.githubusercontent.com/26325971/42813766-a1392646-89f4-11e8-82ea-3279b7b1e13a.png)
请问这个怎样子解决

**Comment by agapple** [comment]
![image](https://user-images.githubusercontent.com/834743/42819117-28463a7e-8a05-11e8-9058-64224e83e062.png)

**Comment by agapple** [comment]
出现重复的slaveId

**Comment by agapple** [comment]
优化了一下日志输出，去掉了无用的

**Comment by wingerx** [comment]
@yanconcon 我把主干的拉下来跑也遇到这个问题了。无论slaveId改成多少都没用
