### ISSUE TITLE
client切换时延问题

### ISSUE THREAD

**Issue by arsenal1886** [alibaba/canal#758]
部署了两个client端通过zk监听同一个destination，看了一下文档，貌似没有描述两个client切换时获取数据的时间间隔，两个client端都是通过while（true）方式不停的 subscribe、connect、getMessage。按理来说，时间间隔就应该是zk处理结点状态变化的时间，我设置的是 canal.zookeeper.flush.period=1000，从结果上来看每次间隔大约30S左右，和配置相差较大，请问，有办法缩短一下这个间隔吗，业务对实时性要求很高。

**Comment by agapple** [comment]
这是zookeeper的sessionTimeout，你网上找找参数调低一下
