### ISSUE TITLE
canal+OTTER client端batchid=-1

### ISSUE THREAD

**Issue by lihongyu666** [alibaba/canal#760]
canal版本：1.0.22
配置启动后，client端使用canalConnector.getWithoutAck(batchSize)getId();得到的值一直为-1。且在zk上1001node下cursor节点一直没有生成，canal端log正常。
client端log：

![image](https://user-images.githubusercontent.com/41414514/42923813-0c834b50-8b5a-11e8-83f4-bf00bdb56d34.png)

在canal端设置binlog名字以及position依旧创建不了cursor。且文件存在。
有人遇到过这样的问题吗？求教

**Comment by agapple** [comment]
看看canal server上的日志是否有异常
