### ISSUE TITLE
canal 1.0.26 偶尔断开连接然后从新连接后,部分同步停止

### ISSUE THREAD

**Issue by mycat-lulin** [alibaba/canal#764]
使用场景:
1,单台虚拟机连接20个数据库的同步任务,某一时刻突然出现大批量如下日志,但是从新连接后,部分数据库同步正常,部分数据库同步停止,zk的cursor不变化,停留在断开连接的地方.日志如下

MysqlConnector - |disConnect Mysql Connection to 10.x.x.x/10.x.x.x:3306.....
MysqlConnector - |connect Mysql Connection to 10.x.x.x/10.x.x.x:3306.....
MysqlConnector - |handshake initialization packet received, prepare the client authentication packet to send
MysqlConnector - |client authentication packet is sent out.

目前出现多次这种情况,原因未知.

**Comment by agapple** [comment]
信息太少，无法定位，可以看看当时的jstack

**Comment by mycat-lulin** [comment]
jstack后,发现唯一差别的地方在正常运行的canal的每个线程下面都会有这么2行:
 Locked ownable synchronizers:
   -  None

但运行暂停的每个线程下面什么都没有,而且通篇检索Locked ownable synchronizers:没有检索到
而运行正常的检索到150多个.这个最大的差别.

**Comment by kervin521** [comment]
+1

**Comment by mycat-lulin** [comment]
@kervin521 你也遇到这个问题了?还是让我提供更多的信息?现在在按照大神的意思,分析jstack.

**Comment by agapple** [comment]
有复现方法之后再reopen
