### ISSUE TITLE
canal监控对接一下prometheus+grafana

### ISSUE THREAD

**Issue by agapple** [alibaba/canal#765]
很多人反馈过如何有效的监控canal server，初步思考是选择目前比较流行的prometheus+grafana

监控的指标：
1.  server级别的状态 (instance list / client list) + (cpu / jvm gc / net / io ...)
2.  instance级别的状态 (delay /  tps /  ringbuffer / heartbeat ... )

如果大家已经做过类似的方案， 非常欢迎大家提交PR给我

**Comment by wingerx** [comment]
cpu/jvm gc 这些可以直接使用是simpleclient_hotspot提供的exports

**Comment by lcybo** [comment]
@agapple 最近正好学习相关内容，我可以提pr吗，差不多周末的时候。

**Comment by agapple** [comment]
非常欢迎两位提交PR

**Comment by lcybo** [comment]
根据 @agapple 的comments，结合自己使用的一些感受，说下实现canal server自身监控的一些想法，
先列出一些指标（以开启parallel模式解析为例），PS: 通过带instance tag可以将指标以instance级别收集，然后汇总：
1. 从read到store put
a. 表示inbound流量的canal_inbound_bytes
b. 表示dump线程pushlish events -> disruptor buffer阻塞时间片的 canal_dump_publish_blocking_time
c. 表示sink线程put events -> store阻塞时间片的 canal_sink_put_blocking_time
d. 通过CanalEventDownStreamHandler，可以获得代表延迟的 canal_instance_delay；各种Event type的分类统计；通过rowchange附带的rowData数量判断近期是否有批量SQL等等。

2. netty server端，使用SessionHandler调用write时，增加ChannelFutureListener回调，将client的请求和完成信息进行采样，包括destination, PacketType, write amount, batchId(仅对GET，判断是否空包), error code, response time 等
a. 表示outbound流量的canal_inbound_bytes
b. 各packetType包的分类统计
c. 空包率
d. 发生的error按error code统计
e. 响应时间

3. event store，比较天然的埋点：
a. TPS，根据ackSequence计算
b. 如果是memory模式，MPS，根据ackMemSize计算
c. store remain events 数量
d. store remain memory

一些场景：
- 1-b 无明显 blocking，1-d delay不断增加，1-a 流量较小 --> 可大致推断瓶颈在网络，是否带宽不够或流量被挤占。
- 1-b 有显著 blocking，1-c 无明显blocking（client消费很快）--> 可尝试增加canal.instance.parser.parallelThreadSize加快解析速度
- 1-b 和 1-c均有显著blocking, delay不断增加 --> 瓶颈在于client读写和消费
- 2-c 空包频率高 --> 可考虑调整优化get的timeout时间
- 2-b && 2-d --> client的行为是否正常

欢迎comments。
BTW, 新拉了一个分支metrics_support。

**Comment by agapple** [comment]
@lcybo 考虑的非常全面了，点赞一个

**Comment by lcybo** [comment]
:)

**Comment by lcybo** [comment]
<img width="910" alt="grafana" src="https://user-images.githubusercontent.com/15042781/44220795-30379600-a1b2-11e8-9f56-24dd8395f0bf.PNG">
贴一张预览图。家里的环境，traffic随便灌的，不太容易模拟复杂场景。

**Comment by lcybo** [comment]
<img width="251" alt="down" src="https://user-images.githubusercontent.com/15042781/44293887-3f0d6e00-a2c2-11e8-92e7-da3ccae6c991.PNG">
生成模板，增加datasource便利配置，instances切换

**Comment by lcybo** [comment]
提交了模板/canal/conf/metrics/Canal_instances_tmpl.json
对dashboard重新进行了排版
使用说明文档也已告一段落。
如果有问题，我会尽快修复。

**Comment by agapple** [comment]
![image](https://user-images.githubusercontent.com/834743/44321609-8ab74780-a47b-11e8-80c2-6d5baab962fa.png)

最后的效果图，具体可以参见：[[Prometheus QuickStart]]

**Comment by 54nidong** [comment]
@agapple  大佬，想请教个问题，
![image](https://user-images.githubusercontent.com/18343598/56403772-8f93fb80-6295-11e9-8721-03debe8acdc7.png)我配置canal监控的时候一个数据源对应多个destination，怎么单独给每一个destination配置告警规则呢？我现在的问题是我在一个destination里配置了告警规则，其他的destination就都是则个告警规则，怎么能让每个destination配置不同的告警规则呢？请教下大神

**Comment by Bruce2jiang** [comment]
@lcybo grafana可以使用6.5版本吗，我的现有监控是6.5版本

**Comment by 54nidong** [comment]
grafana 官网最新版本才到6.2了

  
  

 

 ------------------ 原始邮件 ------------------
  发件人: "Bruce2jiang"<notifications@github.com>;
 发送时间: 2019年6月10日(星期一) 上午8:23
 收件人: "alibaba/canal"<canal@noreply.github.com>;
 抄送: "倪东"<411870880@qq.com>;"Comment"<comment@noreply.github.com>;
 主题: Re: [alibaba/canal] canal监控对接一下prometheus+grafana (#765)

 

 
@lcybo grafana可以使用6.5版本吗，我的现有监控是6.5版本

**Comment by helloworldbenben** [comment]
哈喽，想请教下 canal HA模式下如何使用prometheus 做监控；  
     不胜感激

**Comment by 54nidong** [comment]
是这样的，在canal HA模式下，有多台canal机器地址，比如说192.168.1.22，192.168.1.23，192.168.1.24折3台机器，你要将这3台机器的IP地址和端口放到prometheus.yml里做监控，这样不管它服务挂不挂，你都监控到了。

  
  

 

 ------------------ 原始邮件 ------------------
  发件人: "helloworldbenben"<notifications@github.com>;
 发送时间: 2019年6月10日(星期一) 晚上7:41
 收件人: "alibaba/canal"<canal@noreply.github.com>;
 抄送: "倪东"<411870880@qq.com>;"Comment"<comment@noreply.github.com>;
 主题: Re: [alibaba/canal] canal监控对接一下prometheus+grafana (#765)

 

 
哈喽，想请教下 canal HA模式下如何使用prometheus 做监控；
不胜感激

**Comment by helloworldbenben** [comment]
谢谢老哥





------------------ 原始邮件 ------------------
发件人: "54nidong"<notifications@github.com>;
发送时间: 2019年6月10日(星期一) 晚上7:46
收件人: "alibaba/canal"<canal@noreply.github.com>;
抄送: "飞猪"<442961722@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [alibaba/canal] canal监控对接一下prometheus+grafana (#765)



是这样的，在canal HA模式下，有多台canal机器地址，比如说192.168.1.22，192.168.1.23，192.168.1.24折3台机器，你要将这3台机器的IP地址和端口放到prometheus.yml里做监控，这样不管它服务挂不挂，你都监控到了。 
 
    
    
 
   
 
  ------------------ 原始邮件 ------------------ 
   发件人: "helloworldbenben"<notifications@github.com>; 
  发送时间: 2019年6月10日(星期一) 晚上7:41 
  收件人: "alibaba/canal"<canal@noreply.github.com>; 
  抄送: "倪东"<411870880@qq.com>;"Comment"<comment@noreply.github.com>; 
  主题: Re: [alibaba/canal] canal监控对接一下prometheus+grafana (#765) 
 
   
 
   
 哈喽，想请教下 canal HA模式下如何使用prometheus 做监控； 
 不胜感激

**Comment by BigData-YC** [comment]
请问一下，instance挂掉了，怎么警告？？？？grafana里面

**Comment by Fernandoize** [comment]
想问下, canal HA模式在k8s里面有多个pod， 怎么一次性全部监控到

**Comment by lijtforgithub** [comment]
delay ack 数据没有怎么延迟 监控确实 week 怎么回事

**Comment by lijtforgithub** [comment]
![image](https://user-images.githubusercontent.com/21376296/132979296-fdabf0b6-bb49-43e1-b4d8-f092def0293c.png)
