### ISSUE TITLE
cancal启动正常，java客户端可以连接上，但有数据更改后客户端获取不到。

### ISSUE THREAD

**Issue by shisan** [alibaba/canal#766]
cancal启动正常，java客户端可以连接上，但有数据更改后客户端获取不到更改。下面是记录

谁遇到过这种情况，请帮忙下。谢谢。

2018-07-23 12:29:37.519 [destination = example , address = /127.0.01:3307 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:example[com.alibaba.otter.canal.parse.exception.CanalParseException: java.io.IOException: ErrorPacket [errorNumber=1046, fieldCount=-1, message=No database selected, sqlState=3D000, sqlStateMarker=#]
 with command: show create table `sbed`.`全速通库存`;show create table `sbed`.`商品备案信息表`;show create table `sbed`.`康多多库存`;show create table `sbed`.`没有GST的商品`;show create table `sbed`.`澳猫商品内部价`;show create table `sbed`.`澳猫商品申报价`;show create table `sbed`.`澳猫商品销售价`;show create table `sbed`.`网店管家商品总库存`;show create table `sbed`.`网店管家商品数据`;show create table `sbed`.`货品价格表`;show create table `sbed`.`QRTZ_BLOB_TRIGGERS`;show create table `sbed`.`QRTZ_CALENDARS`;show create table `sbed`.`QRTZ_CRON_TRIGGERS`;show create table `sbed`.`QRTZ_FIRED_TRIGGERS`;show create table `sbed`.`QRTZ_JOB_DETAILS`;show create table `sbed`.`QRTZ_LOCKS`;show create table `sbed`.`QRTZ_PAUSED_TRIGGER_GRPS`;show create table `sbed`.`QRTZ_SCHEDULER_STATE`;show create table `sbed`.`QRTZ_SIMPLE_TRIGGERS`;show create table `sbed`.`QRTZ_SIMPROP_TRIGGERS`;show create table `sbed`.`QRTZ_TRIGGERS`;show create table `sbed`.`sys_add_goods_advice`;show create table `sbed`.`sys_aomao_goods`;show create table `sbed`.`sys_aomao_goods_price`;show create table `sbed`.`sys_aomao_logistics`;show create table `sbed`.`sys_aomao_trade`;show create table `sbed`.`sys_aomao_trade_goods`;show create table `sbed`.`sys_aomao_user`;show create table `sbed`.`sys_aomao_user_group`;show create table `sbed`.`sys_aomao_user_inventory`;show create table `sbed`.`sys_attachment`;show create table `sbed`.`sys_au_data`;show create table `sbed`.`sys_auspost_base`;show create table `sbed`.`sys_auspost_log`;show create table `sbed`.`sys_auspost_order`;show create table `sbed`.`sys_common_map`;show create table `sbed`.`sys_config`;show create table `sbed`.`sys_content`;show create table `sbed`.`sys_content_taxonomy`;show create table `sbed`.`sys_currency`;show create table `sbed`.`sys_customer`;show create table `sbed`.`sys_customer_address`;show create table `sbed`.`sys_customer_category`;show create table `sbed`.`sys_customer_grade`;show create table `sbed`.`sys_dept`;show create table `sbed`.`sys_documents`;show create table `sbed`.`sys_eunionpay`;show create table `sbed`.`sys_excel_export`;show create table `sbed`.`sys_express`;show create table `sbed`.`sys_finance_log`;show create table `sbed`.`sys_finance_order`;show create table `sbed`.`sys_finance_order_goods`;show create table `sbed`.`sys_finance_refund`;show create table `sbed`.`sys_goods`;show create table `sbed`.`sys_goods_brand`;show create table `sbed`.`sys_goods_category`;show create table `sbed`.`sys_goods_price`;show create table `sbed`.`sys_goods_repertory`;show create table `sbed`.`sys_goods_return`;show create table `sbed`.`sys_goods_shop_price`;show create table `sbed`.`sys_goods_stock`;show create table `sbed`.`sys_goods_supplier`;show create table `sbed`.`sys_issue`;show create table `sbed`.`sys_issue_post`;show create table `sbed`.`sys_jingdong_refund`;show create table `sbed`.`sys_log`;show create table `sbed`.`sys_menu`;show create table `sbed`.`sys_order_detail`;show create table `sbed`.`sys_purchase`;show create table `sbed`.`sys_purchase_checkout`;show create table `sbed`.`sys_purchase_checkout_detail`;show create table `sbed`.`sys_purchase_detail`;show create table `sbed`.`sys_purchaseplan`;show create table `sbed`.`sys_purchaseplan_detail`;show create table `sbed`.`sys_quansutong_clearance`;show create table `sbed`.`sys_quansutong_express`;show create table `sbed`.`sys_quansutong_token`;show create table `sbed`.`sys_redbook_repertory`;show create table `sbed`.`sys_role`;show create table `sbed`.`sys_role_menu`;show create table `sbed`.`sys_sai_goods`;show create table `sbed`.`sys_sai_shipment_data`;show create table `sbed`.`sys_sai_stock`;show create table `sbed`.`sys_sale_num_goods`;show create table `sbed`.`sys_sales`;show create table `sbed`.`sys_sales_stock`;show create table `sbed`.`sys_schedule_job`;show create table `sbed`.`sys_schedule_job_log`;show create table `sbed`.`sys_shop`;show create table `sbed`.`sys_shop_delivery`;show create table `sbed`.`sys_shop_goods`;show create table `sbed`.`sys_shop_order`;show create table `sbed`.`sys_shop_order_goods`;show create table `sbed`.`sys_status`;show create table `sbed`.`sys_stock_all`;show create table `sbed`.`sys_stock_all_log`;show create table `sbed`.`sys_stock_all_num`;show create table `sbed`.`sys_stock_all_num_view`;show create table `sbed`.`sys_stock_allocation`;show create table `sbed`.`sys_stock_allocation_main`;show create table `sbed`.`sys_stock_goods`;show create table `sbed`.`sys_stock_store`;show create table `sbed`.`sys_stock_store_position`;show create table `sbed`.`sys_store`;show create table `sbed`.`sys_store_model`;show create table `sbed`.`sys_supplier`;show create table `sbed`.`sys_taobao_goods`;show create table `sbed`.`sys_taobao_goods_detail`;show create table `sbed`.`sys_taobao_goods_detail_item_imgs`;show create table `sbed`.`sys_taobao_goods_detail_location`;show create table `sbed`.`sys_taobao_goods_detail_prop_imgs`;show create table `sbed`.`sys_taobao_goods_detail_sku`;show create table `sbed`.`sys_taobao_goods_price`;show create table `sbed`.`sys_taobao_logistics_company`;show create table `sbed`.`sys_taobao_order`;show create table `sbed`.`sys_taobao_trade`;show create table `sbed`.`sys_taxonomy`;show create table `sbed`.`sys_third_nulaxgroup`;show create table `sbed`.`sys_tianmao_activity`;show create table `sbed`.`sys_tianmao_activity_goods`;show create table `sbed`.`sys_trade`;show create table `sbed`.`sys_trade_goods`;show create table `sbed`.`sys_trade_logistics`;show create table `sbed`.`sys_user`;show create table `sbed`.`sys_user_brand`;show create table `sbed`.`sys_user_formthead`;show create table `sbed`.`sys_user_role`;show create table `sbed`.`sys_user_store`;show create table `sbed`.`sys_user_token`;show create table `sbed`.`sys_value`;show create table `sbed`.`sys_wave_house_cost`;show create table `sbed`.`sys_yeebao_pay`;show create table `sbed`.`xhs_order`;show create table `sbed`.`xhs_order_detail`;show create table `sbed`.`xhs_stock`;
Caused by: java.io.IOException: ErrorPacket [errorNumber=1046, fieldCount=-1, message=No database selected, sqlState=3D000, sqlStateMarker=#]
 with command: show create table `sbed`.`全速通库存`;show create table `sbed`.`商品备案信息表`;show create table `sbed`.`康多多库存`;show create table `sbed`.`没有GST的商品`;show create table `sbed`.`澳猫商品内部价`;show create table `sbed`.`澳猫商品申报价`;show create table `sbed`.`澳猫商品销售价`;show create table `sbed`.`网店管家商品总库存`;show create table `sbed`.`网店管家商品数据`;show create table `sbed`.`货品价格表`;show create table `sbed`.`QRTZ_BLOB_TRIGGERS`;show create table `sbed`.`QRTZ_CALENDARS`;show create table `sbed`.`QRTZ_CRON_TRIGGERS`;show create table `sbed`.`QRTZ_FIRED_TRIGGERS`;show create table `sbed`.`QRTZ_JOB_DETAILS`;show create table `sbed`.`QRTZ_LOCKS`;show create table `sbed`.`QRTZ_PAUSED_TRIGGER_GRPS`;show create table `sbed`.`QRTZ_SCHEDULER_STATE`;show create table `sbed`.`QRTZ_SIMPLE_TRIGGERS`;show create table `sbed`.`QRTZ_SIMPROP_TRIGGERS`;show create table `sbed`.`QRTZ_TRIGGERS`;show create table `sbed`.`sys_add_goods_advice`;show create table `sbed`.`sys_aomao_goods`;show create table `sbed`.`sys_aomao_goods_price`;show create table `sbed`.`sys_aomao_logistics`;show create table `sbed`.`sys_aomao_trade`;show create table `sbed`.`sys_aomao_trade_goods`;show create table `sbed`.`sys_aomao_user`;show create table `sbed`.`sys_aomao_user_group`;show create table `sbed`.`sys_aomao_user_inventory`;show create table `sbed`.`sys_attachment`;show create table `sbed`.`sys_au_data`;show create table `sbed`.`sys_auspost_base`;show create table `sbed`.`sys_auspost_log`;show create table `sbed`.`sys_auspost_order`;show create table `sbed`.`sys_common_map`;show create table `sbed`.`sys_config`;show create table `sbed`.`sys_content`;show create table `sbed`.`sys_content_taxonomy`;show create table `sbed`.`sys_currency`;show create table `sbed`.`sys_customer`;show create table `sbed`.`sys_customer_address`;show create table `sbed`.`sys_customer_category`;show create table `sbed`.`sys_customer_grade`;show create table `sbed`.`sys_dept`;show create table `sbed`.`sys_documents`;show create table `sbed`.`sys_eunionpay`;show create table `sbed`.`sys_excel_export`;show create table `sbed`.`sys_express`;show create table `sbed`.`sys_finance_log`;show create table `sbed`.`sys_finance_order`;show create table `sbed`.`sys_finance_order_goods`;show create table `sbed`.`sys_finance_refund`;show create table `sbed`.`sys_goods`;show create table `sbed`.`sys_goods_brand`;show create table `sbed`.`sys_goods_category`;show create table `sbed`.`sys_goods_price`;show create table `sbed`.`sys_goods_repertory`;show create table `sbed`.`sys_goods_return`;show create table `sbed`.`sys_goods_shop_price`;show create table `sbed`.`sys_goods_stock`;show create table `sbed`.`sys_goods_supplier`;show create table `sbed`.`sys_issue`;show create table `sbed`.`sys_issue_post`;show create table `sbed`.`sys_jingdong_refund`;show create table `sbed`.`sys_log`;show create table `sbed`.`sys_menu`;show create table `sbed`.`sys_order_detail`;show create table `sbed`.`sys_purchase`;show create table `sbed`.`sys_purchase_checkout`;show create table `sbed`.`sys_purchase_checkout_detail`;show create table `sbed`.`sys_purchase_detail`;show create table `sbed`.`sys_purchaseplan`;show create table `sbed`.`sys_purchaseplan_detail`;show create table `sbed`.`sys_quansutong_clearance`;show create table `sbed`.`sys_quansutong_express`;show create table `sbed`.`sys_quansutong_token`;show create table `sbed`.`sys_redbook_repertory`;show create table `sbed`.`sys_role`;show create table `sbed`.`sys_role_menu`;show create table `sbed`.`sys_sai_goods`;show create table `sbed`.`sys_sai_shipment_data`;show create table `sbed`.`sys_sai_stock`;show create table `sbed`.`sys_sale_num_goods`;show create table `sbed`.`sys_sales`;show create table `sbed`.`sys_sales_stock`;show create table `sbed`.`sys_schedule_job`;show create table `sbed`.`sys_schedule_job_log`;show create table `sbed`.`sys_shop`;show create table `sbed`.`sys_shop_delivery`;show create table `sbed`.`sys_shop_goods`;show create table `sbed`.`sys_shop_order`;show create table `sbed`.`sys_shop_order_goods`;show create table `sbed`.`sys_status`;show create table `sbed`.`sys_stock_all`;show create table `sbed`.`sys_stock_all_log`;show create table `sbed`.`sys_stock_all_num`;show create table `sbed`.`sys_stock_all_num_view`;show create table `sbed`.`sys_stock_allocation`;show create table `sbed`.`sys_stock_allocation_main`;show create table `sbed`.`sys_stock_goods`;show create table `sbed`.`sys_stock_store`;show create table `sbed`.`sys_stock_store_position`;show create table `sbed`.`sys_store`;show create table `sbed`.`sys_store_model`;show create table `sbed`.`sys_supplier`;show create table `sbed`.`sys_taobao_goods`;show create table `sbed`.`sys_taobao_goods_detail`;show create table `sbed`.`sys_taobao_goods_detail_item_imgs`;show create table `sbed`.`sys_taobao_goods_detail_location`;show create table `sbed`.`sys_taobao_goods_detail_prop_imgs`;show create table `sbed`.`sys_taobao_goods_detail_sku`;show create table `sbed`.`sys_taobao_goods_price`;show create table `sbed`.`sys_taobao_logistics_company`;show create table `sbed`.`sys_taobao_order`;show create table `sbed`.`sys_taobao_trade`;show create table `sbed`.`sys_taxonomy`;show create table `sbed`.`sys_third_nulaxgroup`;show create table `sbed`.`sys_tianmao_activity`;show create table `sbed`.`sys_tianmao_activity_goods`;show create table `sbed`.`sys_trade`;show create table `sbed`.`sys_trade_goods`;show create table `sbed`.`sys_trade_logistics`;show create table `sbed`.`sys_user`;show create table `sbed`.`sys_user_brand`;show create table `sbed`.`sys_user_formthead`;show create table `sbed`.`sys_user_role`;show create table `sbed`.`sys_user_store`;show create table `sbed`.`sys_user_token`;show create table `sbed`.`sys_value`;show create table `sbed`.`sys_wave_house_cost`;show create table `sbed`.`sys_yeebao_pay`;show create table `sbed`.`xhs_order`;show create table `sbed`.`xhs_order_detail`;show create table `sbed`.`xhs_stock`;
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlQueryExecutor.queryMulti(MysqlQueryExecutor.java:109)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.queryMulti(MysqlConnection.java:101)
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.dumpTableMeta(DatabaseTableMeta.java:173)
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.rollback(DatabaseTableMeta.java:127)
	at com.alibaba.otter.canal.parse.inbound.mysql.AbstractMysqlEventParser.processTableMeta(AbstractMysqlEventParser.java:84)
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:173)
	at java.lang.Thread.run(Thread.java:748)
]

**Comment by agapple** [comment]
执行那段show指令看看啥错误

**Comment by shuaicloud** [comment]
同样的问题，canal1.1.1  ,怎么解决的。求助

**Comment by shuaicloud** [comment]
> 执行那段show指令看看啥错误

同样的问题，canal1.1.1 ,怎么解决的。求助

**Comment by agapple** [comment]
执行一下报错的那条show指令 @shuaicloud

**Comment by shuaicloud** [comment]
多谢@agapple  ，执行了多个show create table XXXXX;  没报错  ，mysql是5.7.18

**Comment by agapple** [comment]
5.7上执行多语句show create table，是没报错么？

**Comment by shuaicloud** [comment]
> 5.7上执行多语句show create table，是没报错么？

是的

**Comment by duxingzhe311** [comment]
@shisan 您最后怎么解决的？我也遇到了同样的问题，把canal降到1.0.23就好用。不太想降版本，还没找到解决办法。
