### ISSUE TITLE
指定canal.instance.master.timestamp时间戳消费无效

### ISSUE THREAD

**Issue by fanpeng1100** [alibaba/canal#770]
在instance中指定了时间戳，发现client还会拿到这个时间戳以前的log，如果想只消费这个时间戳之后的log，应该配置哪些呢？单独配置canal.instance.master.timestamp是不是不可以？

**Comment by agapple** [comment]
清理掉上一次的记录的位点信息，比如zookeeper节点和meta.dat文件

**Comment by ccc520** [comment]
请问你解决了吗？如何解决的，我的配置不起作用

canal.instance.master.address=10.1.5.231:3696
canal.instance.master.journal.name=mysql-bin.000001
canal.instance.master.position=
#start-time
canal.instance.master.timestamp=1558972800

**Comment by fanpeng1100** [comment]
清除zk下生成的记录文件再试试


 
---原始邮件---
发件人: "ccc520"<notifications@github.com>
发送时间: 2019年5月29日(星期三) 晚上6:59
收件人: "alibaba/canal"<canal@noreply.github.com>;
抄送: "Author"<author@noreply.github.com>;"fanpeng"<343405399@qq.com>;
主题: Re: [alibaba/canal] 指定canal.instance.master.timestamp时间戳消费无效 (#770)



请问你解决了吗？如何解决的，我的配置不起作用
 
canal.instance.master.address=10.1.5.231:3696
 canal.instance.master.journal.name=mysql-bin.000001
 canal.instance.master.position=
 #start-time
 canal.instance.master.timestamp=1558972800

**Comment by medlying** [comment]
我也是遇到这个问题，删了zk节点，重启instance，在看zk上的时间戳还是他自己刷新的一个时间点不是设置的时间啊

**Comment by WENZIZZHENG** [comment]
我也遇到这个问题，解决方案是重装一下canal（我部署的是单机）。原因估计历史配置没有能清除。

**Comment by solo30years** [comment]
来信收到 谢谢
