### ISSUE TITLE
[v1.0.26.alpha4] decode event时报limit exceed错误

### ISSUE THREAD

**Issue by gaoxiangyu** [alibaba/canal#776]
![image](https://user-images.githubusercontent.com/8179551/43183817-099b0e50-9019-11e8-8339-2d922e48b9ed.png)
decode event时报limit exceed错误
应该是和这个commit有关
https://github.com/alibaba/canal/commit/89726a636530b73a6b97cecc2b5bcee4fb464f86

**Comment by agapple** [comment]
mysql版本是啥？

**Comment by wingerx** [comment]
抱歉.@gaoxiangyu 
我依赖于 MySQL 5.7测试的，能把引起这个错误的MySQL 版本说下吗？方便我这边跟进，谢谢.

**Comment by gaoxiangyu** [comment]
5.6.28

**Comment by wingerx** [comment]
@gaoxiangyu 多谢，我跟进一下

**Comment by wingerx** [comment]
@agapple 这个问题我来跟进.
BTW，方便的时候请看下你的gmail
