### ISSUE TITLE
注释过长会引起数据错乱

### ISSUE THREAD

**Issue by yufengzhou123** [alibaba/canal#779]
注释本来是：
定向设置，32个字符，每个字符有3个值（0空1不限2确定值-指定{不分指定排除的也存为指定}3确定值-排除）第1个字符：应用渠道，第2个字符：网络环境，第3个字符：移动操作系统，第4个字符：平台版本号，第5个字符：地域定向，第6个字符：性别，第7个字符：年龄段，第8个字符：关键词【0没有；1不限；2指定；3排除；4；智能】，第9个字符：商业兴趣标签，第10个字符：AppList标签，第11个字符：设备价格标签，第12个字符：视频类型，第13个字符：运营商，第14个字符：自定义人群包
改成：
定向设置，32个字符，每个字符有3个值（0空1不限2确定值-指定{不分指定排除的也存为指定}3确定值-排除）第1个字符：应用渠道，第2个字符：网络环境，第3个字符：移动操作系统，第4个字符：平台版本号，第5个字符：地域定向，第6个字符：性别，第7个字符：年龄段，第8个字符：关键词【0没有；1不限；2指定；3排除；4；智能】，第9个字符：商业兴趣标签，第10个字符：AppList标签，第11个字符：设备价格标签，第12个字符：视频类型，第13个字符：运营商，第14个字符：自定义人群包，第15个字符：应用渠道-资讯版，第16个字符：平台版本号-资讯版

以后，有一个字段的数据出现错乱

**Comment by agapple** [comment]
给我一个完整的ddl  sql

**Comment by yufengzhou123** [comment]
alter table tb_ad_group modify `target_setting` varchar(64) NOT NULL DEFAULT '00000000000000000000000000000000' COMMENT '定向设置，32个字符，每个字符有3个值（0空1不限2确定值-指定{不分指定排除的也存为指定}3确定值-排除）第1个字符：应用渠道，第2个字符：网络环境，第3个字符：移动操作系统，第4个字符：平台版本号，第5个字符：地域定向，第6个字符：性别，第7个字符：年龄段，第8个字符：关键词【0没有；1不限；2指定；3排除；4；智能】，第9个字符：商业兴趣标签，第10个字符：AppList标签，第11个字符：设备价格标签，第12个字符：视频类型，第13个字符：运营商，第14个字符：自定义人群包，第15个字符：应用渠道-资讯版，第16个字符：平台版本号-资讯版';

**Comment by agapple** [comment]
最新的alpha 4解析没问题

**Comment by yufengzhou123** [comment]
想问您一下 如果不换版本。有什么方法吗。。。版本不是特别方便更换额
