### ISSUE TITLE
canal求解释下message，entries，transanctionID，batchid, event以及rowchange的关系

### ISSUE THREAD

**Issue by alexlgj** [alibaba/canal#783]
正在学习canal的使用，求大神梳理下canal中几个概念的关系：

目前我的理解是：一个message包含多个entry（其共同构成entries），一个entry对应一个eventtype（可以是insert/delete等），一个entry可以解析得到一个rowchange，一个rowchange可以解析得到多个rowdata，一个rowdata可以解析得到before的columns（方法getBeforeColumnsList）和after的columns。

- 问题1: 请问它们内部的关联是怎样的？
- 问题2: transactionID和batchID的区别？
- 问题3: entry.getHeader().getSchemaName())可以获取到mysql的schema，但是怎么获取mysql 的instance？

谢谢
求大神指点

**Comment by lcybo** [comment]
一个message就是get到的batch packet，batchId是其标识，是canal概念；transactionId是mysql事务相关的。mysql binlog 会将同表的同类型操作（insert, update等）的变更行merge为一个event以节省meta开销，entry是canal proto类型，对应mysql event。rowdata对应每一行数据。before和after对应变更前后，所以update兼具两者，insert只有after,delete只有before。在特殊情况下，比如开启ndb的一些参数，update会变成insert类型。

**Comment by alexlgj** [comment]
你好，谢谢你的指点，讲得很清楚。我还有个问题：我在mysql中只插入了一个row，但是canal中显示的entrys.size() 是3，那我如何知道哪个entry才对应我刚才插入的row呢？

**Comment by lcybo** [comment]
ls正解

**Comment by alexlgj** [comment]
感谢大神的回复，现在懂了。测试了几次，结果如下：

一次insert或delete或者update操作
entrys.size() is: 3

连续执行三次insert数据操作，再启动canal client
entrys.size() is: 9

当entry是transactionbegin或transactionend，对应的eventtype都是update
当entry是rowdata，对应的eventtype是对应的操作，即insert/delete/update

**Comment by alexlgj** [comment]
还遇到个问题，如何通过canal获取mysql database的instance名称，从entry的header中只找到了schema（通过entry.getHeader().getSchemaName())，但是怎么获取mysql 的instance？

**Comment by lcybo** [comment]
instance是指port区分的mysql实例吗？ 考虑一下用serverId区分

**Comment by alexlgj** [comment]
好的，非常感谢大神
