### ISSUE TITLE
canalserver支持一个instance实例抽取多库的么？

### ISSUE THREAD

**Issue by tc792617871** [alibaba/canal#784]
canalserver使用单库instance配置，不分组，然后在一个实例中抽取多个库的binlog日志。这种方式配置方法支持么？

**Comment by tc792617871** [comment]
已找到配置方法canal.instance.defaultDatabaseName=db1,db2。这个配置适用于同一个ip、port实例下不同库。库名之间使用逗号隔开。这样配置即可。

**Comment by agapple** [comment]
LS正解
