### ISSUE TITLE
用show processlist 命令看不到dump进程

### ISSUE THREAD

**Issue by fangchunsheng** [alibaba/canal#787]
[v1.0.26.alpha4]  canal启动起来后，开始dump,为什么在mysql端，用show processlist 命令看不到dump进程

**Comment by lcybo** [comment]
确认一下是不是开始消费数据了：
instance日志里有没有find start position : EntryPosition[included=false,journalName=xxxx,position=xxxx,serverId=<null>,gtid=<null>,timestamp=<null>].
然后meta.log有没有持续刷新

**Comment by agapple** [comment]
show slave hosts 可以看到canal的dump进程
