### ISSUE TITLE
为什么insert会被解析成ddl？

### ISSUE THREAD

**Issue by ltylty** [alibaba/canal#791]
RowChange对象信息如下。

unknownFields = {UnknownFieldSet@1470} ""
bitField0_ = 30
tableId_ = 0
eventType_ = {CanalEntry$EventType@1609} "INSERT"
isDdl_ = true
sql_ = "insert into `test`(`school_student_id`, `school_group_id`, `like_user_id`, `school_event_id`) values('114', '1', '66889278', '61')"
rowDatas_ = {Collections$EmptyList@1473}  size = 0
props_ = {Collections$EmptyList@1473}  size = 0
ddlSchemaName_ = "test"
memoizedIsInitialized = 1
memoizedSerializedSize = -1
memoizedSize = -1
memoizedHashCode = 0

**Comment by agapple** [comment]
1.  检查binlog是否为row模式
2. row模式下的RowsQueryLogEvent事件

**Comment by agapple** [comment]
https://github.com/alibaba/canal/wiki/FAQ
