### ISSUE TITLE
canal如何区分一次transaction中的多条记录rowdata

### ISSUE THREAD

**Issue by alexlgj** [alibaba/canal#797]
mysql中一次transaction可能包含多条记录（rowdata），那么canal是如何区分这些记录的呢？有没有类似oracle中的scn(system change number)来唯一标识对某个记录所做的更改？

**Comment by wingerx** [comment]
#751 看一下这个pr是不是满足你说的场景

**Comment by alexlgj** [comment]
pr? 不好意思，方便解释的详细点吗？

**Comment by alexlgj** [comment]
不好意思，刚没看到链接，谢谢
