### ISSUE TITLE
canal中的transaction ID获取和entry.getHeader().getLogfileOffset()偏移量的理解？

### ISSUE THREAD

**Issue by alexlgj** [alibaba/canal#798]
问题1: 
canal的一个message可能会对应mysql中的多个transaction，通过方法message.getEntries()可以获得List<Entry> entrys，entry又 分为transanctionBegin/ transactionEnd以及rowdata。
现在问题是，我在  > 获取transaction id<  的时候只有通过transactionEnd.getTransactionId拿到的是正常的数字，但是通过transactionbegin和rowdata获取到的则都是null。

 请问canal中还有其他方法获取到transaction id吗？

问题2: 

entry.getHeader().getLogfileOffset()获取的偏移量是当前（entry）rowdata在日志文件中的序号（即第几条日志）还是字节数（即该row前面的数据所占的字节数）？

求大神赐教！

谢谢

**Comment by lcybo** [comment]
自己动手通过mysqlbinlog --hexdump可以查看到commit才有xid。 offset是字节偏移。

**Comment by alexlgj** [comment]
棒，谢谢大神
