### ISSUE TITLE
关于canal接收到数据的排序问题?

### ISSUE THREAD

**Issue by zhonghui001** [alibaba/canal#799]
当同时同一个cust_id 依次进行新增 修改 删除 新增,canal接收到两条数据的数据:
如:
cust_id 类型 sql执行时间
001 add 1533002422
001 update 1533002422
001 delete 1533002423
001 add  1533002423
这样的话出现一个问题,我做数据仓库的拉链表的时候 无法知道 001 用户在1533002423毫秒情况下add和delete的顺序
我的问题是,这种情况下,还有其他的字段能提供对于同一个sql执行时间,对数据进行排序区分前后顺序

**Comment by agapple** [comment]
binlog里就是顺序关系

**Comment by lcybo** [comment]
mysql binlog机制比较复杂，内部很多优化。transaction内部只保证slave执行后的最终结果一致。
