### ISSUE TITLE
canal docker化打包支持

### ISSUE THREAD

**Issue by agapple** [alibaba/canal#801]
1.  增加Dockerfile，支持all in one的打包方式(centos + jdk + canal)
2. 参数层面，允许docker -e变量传递和修改 (java里通过System.getenv读取)
3. 交付形式
- 允许用户基于Dockerfile进行源码打包
- 上传到Docker hub，允许用户直接公网下载

**Comment by agapple** [comment]
对应的docker使用文档：https://github.com/alibaba/canal/wiki/Docker-QuickStart

**Comment by shihua-guo** [comment]
[root@publish temp]# cd canal/docker && sh build.sh
build.sh:行2: $'\r': 未找到命令
build.sh:行4: 未预期的符号 `$'in\r'' 附近有语法错误
'uild.sh:行4: `case "`uname`" in

**Comment by shihua-guo** [comment]
大佬，请问你这个脚本是用什么执行的。我运行都是语法错误
