### ISSUE TITLE
canalConnector.subscribe()会把线程阻塞，造成stop无法停止

### ISSUE THREAD

**Issue by zhangxin1988** [alibaba/canal#803]
当以zookeeper HA模式来启动多个Canal Client时，如果某个Canal Client已经成功subsribe，则当前启动的Canal Client会阻塞在canalConnector.subscribe()方法上。
此时再调用如下的stop方法，会阻塞在join处，造成无法正常的stop
    public void stop() {
        if (!running) {
            return;
        }
        //canalConnector.stopRunning();该版本的canal-client不支持
        running = false;
        if (thread != null) {
            try {
                **thread.join();**
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }
        KafkaProducerUtil.stop();
        MDC.remove("destination");

    }

**Comment by zhangxin1988** [comment]
我看新版的example的stop方法中增加了如下的代码，不知道是不是为了解决上面的问题的？
connector.stopRunning();

**Comment by zhangxin1988** [comment]
如果是，那么之前版本该怎么解决阻塞的问题呢？

**Comment by wingerx** [comment]
canal是通过这个机制来实现client端的HA的. 堵塞是为了避免同时有两个相同的client进行消费
