### ISSUE TITLE
canal如何处理mysql中的blob数据类型？

### ISSUE THREAD

**Issue by alexlgj** [alibaba/canal#804]
求大神请教canal中是如何处理mysql中的blob数据类型？
在网上查找到的资料如下（不知道是否正确）：

Canal 将 binlog 中的值序列化成了 String 格式给下游程序，因此在 Blob 格式的数据序列化成 String 时为了节省空间，强制使用了 IOS_8859_0 作为编码。因此，在如下情况下会造成中文乱码：

同步服务 JVM 使用了 UTF-8 编码
BLOB 字段中存储有中文字符

作者：haitaoyao
链接：https://www.jianshu.com/p/be3f62d4dce0
來源：简书
简书著作权归作者所有，任何形式的转载都请联系作者获得授权并注明出处。

求大神指导！

**Comment by agapple** [comment]
按照iso8859-1进行反解为bytes[]即可

**Comment by alexlgj** [comment]
谢谢指导！但是我将sqltype为longblob类型的字段使用iso8859-1反解为bytes[]再utf-8编码为string时，仍然是乱码：

这是longblob字段的内容：
<img width="1128" alt="canal-blob-getvalue" src="https://user-images.githubusercontent.com/28953872/43885058-677e5658-9bea-11e8-956c-edeb50a0da5b.png">

这是使用iso8859-1进行 反解：
<img width="1123" alt="iso" src="https://user-images.githubusercontent.com/28953872/43885109-8a92545a-9bea-11e8-9102-2b5a0c10ec0d.png">

我的代码如下：
if(column.getMysqlType().toUpperCase().equals("LONGBLOB")){
                    logger.info(">>>>>> is blob\n");
                    logger.info("\n>>>>>> column.getValue() is: " + column.getValue());
                    logger.info("\n\n\n\n\n\n>>>>>> new String(column.getValue().getBytes(\"iso8859-1\"),\"UTF-8\") is: " + new String(column.getValue().getBytes("iso8859-1")));
}


请教大神如何fix？

**Comment by lcybo** [comment]
用 getValueBytes方法拿原始bytes

**Comment by lcybo** [comment]
还是getBytesValue？用的爪机没办法确认。

**Comment by alexlgj** [comment]
能讲的详细点吗？大神

**Comment by alexlgj** [comment]
column没有还是getBytesValue方法

**Comment by alexlgj** [comment]
column没有getBytesValue方法，应该是getBytesValue

**Comment by alexlgj** [comment]
column没有getBytesValue方法，应该是getBytesValue

**Comment by agapple** [comment]
```
try {
                if (StringUtils.containsIgnoreCase(column.getMysqlType(), "BLOB")
                    || StringUtils.containsIgnoreCase(column.getMysqlType(), "BINARY")) {
                    // get value bytes
                    builder.append(column.getName() + " : "
                                   + new String(column.getValue().getBytes("ISO-8859-1"), "UTF-8"));
                } else {
                    builder.append(column.getName() + " : " + column.getValue());
                }
            } catch (UnsupportedEncodingException e) {
            }
```

**Comment by lcybo** [comment]
public java.lang.String getValue() {
                java.lang.Object ref = value_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                    //用getValue()这里就已经用utf8编码了
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        value_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            public com.google.protobuf.ByteString getValueBytes() {
                java.lang.Object ref = value_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                    value_ = b;
                    return b;
                } else {
                    //拿到原始的ByteString
                    return (com.google.protobuf.ByteString) ref;
                }
            }

**Comment by alexlgj** [comment]
@agapple @lcybo 好的，谢谢两位大神的指导，我这边网速不怎么样。回复慢了，不好意思

**Comment by lcybo** [comment]
做了个实验：

        byte[] bs = {-1, -2};   //byte是负数的情况，这个就看你数据库的编码了
        ByteString bstring = ByteString.copyFrom(bs);
        String utf = bstring.toStringUtf8();
        System.out.println(utf);    //丢数据了，变成了两个65533
        String iso = new String(utf.getBytes("ISO-8859-1"), "UTF-8");
        System.out.println(iso);    //没有办法还原，变成两个63

**Comment by alexlgj** [comment]
按照@agapple的方法可以成功解码（blob字段内容为中文“北京”）
column.getvalue得到；
"image\\\":\\\"å\\\\u008C\\\\u0097äº¬\\\",\\\

new String(column.getValue().getBytes("ISO-8859-1"), "UTF-8"))得到：
"image\\\":\\\"北京\

**Comment by alexlgj** [comment]
我用的canal是1.0.24版本，您例子中的是没有访问数据库，为什么说“//byte是负数的情况，这个就看你数据库的编码了”？

**Comment by lcybo** [comment]
如果有硬编码的东西（无序的128-255，非utf-8的编码），还是拿原始的byteString吧。

**Comment by lcybo** [comment]
如果canal放进去的string，就是用的iso-8859-1编码过的，那忽略我说的吧，逃了。

**Comment by alexlgj** [comment]
@lcybo 明白了，非常感谢，大大的赞

**Comment by agapple** [comment]
@lcybo 之前server端传blob类型时强转了string类型，比较合理的做法是用ByteString，但现在不能改，已改老用户的blob解析处理都会乱码了

**Comment by lcybo** [comment]
理解

**Comment by alexlgj** [comment]
两位大神，我还有些疑问：

1. 是不是canal server端会对mysql binlog的所有字段做iso-8859-1编码成string？
2. 对编码完全不懂， 能帮忙解释下为什么这样更改编码就能正确解析出存入blob类型的字符串（"北京“）：new String(column.getValue().getBytes("ISO-8859-1"), "UTF-8")) ？该代码中的不同编码的执行顺序是怎样的？

（我的理解是canal server对blob字段的byte数组做iso-8859-1编码，但是iso-8859-1编码不能表示中文“北京”（乱码）。这时执行column.getValue()方法会进入到：if (!(ref instanceof java.lang.String)) {   对ref进行utf8-string）

**Comment by alexlgj** [comment]
另外我想问下，column.getValueBytes().toByteArray()返回的是blob字段original 字节数组吗？还是总是utf-8编码的字节数组？



这是我的测试结果：

插入的blob字段值：
”0123abc"
java程序中打印插入的string的二进制数组内容：
>>>>>>Arrays.toString(”0123abc".getBytes())：
[48, 49, 50, 51, 97, 98, 99]
canal中获得的二进制数组内容：
>>>>>> Arrays.toString(column.getValueBytes().toByteArray()
[48, 49, 50, 51, 97, 98, 99]


blob字段值：”上”:
>>>>>>Arrays.toString(”上".getBytes())：
[-28, -72, -118]
>>>>>> Arrays.toString(column.getValueBytes().toByteArray()[-61, -92, -62, -72, -62, -118]


blob字段值：”上海”:
>>>>>>Arrays.toString(”上海".getBytes())：
[-28, -72, -118, -26, -75, -73]
>>>>>> Arrays.toString(column.getValueBytes().toByteArray()
[-61, -92, -62, -72, -62, -118, -61, -90, -62, -75, -62, -73]

**Comment by lcybo** [comment]
1.从agapple大神的描述，应该是只有blob和binary这么做了

**Comment by lcybo** [comment]
另一个问题，如果用iso编码成string。那么string内一个char实际上放的就是单个byte，打印出来是乱码，但实际数据格式没有丢失。

**Comment by lcybo** [comment]
getBytes("UTF-8")等同于用utf-8去编码那一堆乱码，打印出来的当然是乱码

**Comment by alexlgj** [comment]
我刚请教了下同学一些编码的知识，现在基本能理解了，谢谢大神的耐心指导，棒棒哒
