### ISSUE TITLE
关于position设置

### ISSUE THREAD

**Issue by alan5959249** [alibaba/canal#805]
请问我设置日志读取位置，是不是只需要设置instance.proerties中的jouralName和position就行，那meda.dat里的呢，为什么它与instance.proerties中的不一样呢，到底哪个生效？

**Comment by alan5959249** [comment]
我是用default-instance.xml,zk集群

**Comment by wingerx** [comment]
1. 使用default-instance.xml后，默认是通过zk管理位点信息的.所以 meda.dat在这里无效的
2. meda.dat针对的模式是file-instance.xml
3. instance.properties 中的位点与zk 位点 关系(以 default-instance.xml为例)
 * 当zk中位点中不存在时，canal启动的位点以 instance.properties中为准，若没有，则通过 `show master status` 取最新的位点信息

**Comment by alan5959249** [comment]
@wingerx 你好，我尝试删除了zk上的位点信息，让其重新生成，按照你的说法应该同步Instance.properties中的位点信息（我设置过了），但是却没有，这个原因可能是出在哪里呢

**Comment by wingerx** [comment]
1. Instance.properties中配置的只和启动时找位点有关
2. zk中记录的是client端消费成功后ack 时的位点
并不是说再instance.properties中配置了某位点信息，zk就会同步更新成这个位点.
