### ISSUE TITLE
com.alibaba.fastsql:fastsql:jar:2.0.0_preview_520

### ISSUE THREAD

**Issue by kimiliang123** [alibaba/canal#808]
mvn clean install的时候报错
[ERROR] Failed to execute goal on project canal.parse: Could not resolve dependencies for project com.alibaba.otter:canal.parse:jar:1.0.26-SNAPSHOT: Could not find artifact com.alibaba.fastsql:fastsql:jar:2.0.0_preview_520 in central (http://repo1.maven.org/maven2) -> [Help 1]

请问下这个怎么解决。谢谢

**Comment by kervin521** [comment]
你用2.0.0_preview_186吧，2.0.0_preview_520 并没有对外开放，另外配置maven仓库中心为：http://central.maven.org/maven2/

**Comment by wingerx** [comment]
2.0.0_preview_520 在release 里面有jar包
