### ISSUE TITLE
链接失效

### ISSUE THREAD

**Issue by whiney** [alibaba/canal#812]
### wiki的home

+ **相关资料**：与阿里巴巴的rocketMQ配合使用 连接失效

### wiki的Introduction

+ **知识科普**：mysql的Binlay Log介绍的第二个链接失效

+ **EventParser设计**：binlog event structure，详细信息请参考的连接 Page Not Found

**Comment by wingerx** [comment]
taobaodba的blog 已经不存在了.其他连接已经修复，tks.

**Comment by whiney** [comment]
@wingerx 可以说十分的效率了，赞一个。

**Comment by whiney** [comment]
原谅我的强迫症

README.md 里面关于RocketMQ的连接未更改。

https://github.com/apache/rocketmq

**Comment by agapple** [comment]
已修复
