### ISSUE TITLE
 NPE：MysqlEventParser TableMetaCacheWithStorage

### ISSUE THREAD

**Issue by qmz** [alibaba/canal#821]
如图，tableMetaStorageFactory为NULL时，storage值为null，后续就NullPointerException了
	at com.alibaba.otter.canal.parse.inbound.mysql.tablemeta.TableMetaCacheWithStorage.<init>(TableMetaCacheWithStorage.java:21)
![image](https://user-images.githubusercontent.com/5847660/43820893-1ccadbde-9b1a-11e8-9979-2ab94346dfdb.png)

**Comment by qmz** [comment]
#822

**Comment by agapple** [comment]
看我最新的master提交，已经去掉了tableMetaStorageFactory

**Comment by qmz** [comment]
ok
