### ISSUE TITLE
TableMetaCache.parseTableMetaByDesc 解析desc table 的结果 NullPointer

### ISSUE THREAD

**Issue by hyy613** [alibaba/canal#823]
mysql版本：5.6
desc table的packets解析中key错误。
    public static final String              COLUMN_NAME    = "COLUMN_NAME";
    public static final String              COLUMN_TYPE    = "COLUMN_TYPE";
    public static final String              IS_NULLABLE    = "IS_NULLABLE";
    public static final String              COLUMN_KEY     = "COLUMN_KEY";
    public static final String              COLUMN_DEFAULT = "COLUMN_DEFAULT";
    public static final String              EXTRA          = "EXTRA";

应该改为：
    public static final String              COLUMN_NAME    = "Field";
    public static final String              COLUMN_TYPE    = "Type";
    public static final String              IS_NULLABLE    = "Null";
    public static final String              COLUMN_KEY     = "Key";
    public static final String              COLUMN_DEFAULT = "Default";
    public static final String              EXTRA          = "Extra";

否则会在这一行报NullPointer
 meta.setColumnName(packet.getFieldValues().get(nameMaps.get(COLUMN_NAME) + i * size).intern());

**Comment by wingerx** [comment]
MySQL 版本是5.6.?

**Comment by hyy613** [comment]
mysql> select @@version ;
+--------------------+
| @@version          |
+--------------------+
| 5.6.28-cdb2016-log |
+--------------------+
1 row in set (0.01 sec)

mysql> desc test.test ;
+-------+---------+------+-----+---------+-------+
| Field | Type    | Null | Key | Default | Extra |
+-------+---------+------+-----+---------+-------+
| id    | int(11) | YES  |     | NULL    |       |
+-------+---------+------+-----+---------+-------+
1 row in set (0.01 sec)

**Comment by wingerx** [comment]
![image](https://user-images.githubusercontent.com/33280738/43878223-88545b3a-9bd0-11e8-9f31-6dccbc75e37a.png)

**Comment by wingerx** [comment]
取的是originalName，而非name

**Comment by hyy613** [comment]
![image](https://user-images.githubusercontent.com/7187362/43878339-234ac804-9bd1-11e8-99de-a4646bdb9c61.png)
哥们~~我这里把packet打出来是这样。是不是我的mysql版本和你那边的不一致
        System.out.println(packet);

**Comment by wingerx** [comment]
有可能.

**Comment by hyy613** [comment]
https://dev.mysql.com/doc/refman/8.0/en/columns-table.html

**Comment by wingerx** [comment]
![image](https://user-images.githubusercontent.com/33280738/43881977-9a81a8ac-9be0-11e8-9126-c6711b98eb16.png)
![image](https://user-images.githubusercontent.com/33280738/43881992-ad3b1fbe-9be0-11e8-97e7-11bad3d560c9.png)

我这边用5.6.28测出来的也是一致的。你那边的版本从哪里获取到的？

**Comment by hyy613** [comment]
哥。。我弄错了。。mysqlConnection连到另外一个数据库去了额。。。是个8.0.11版本的。
占用你这么久时间了，不好意思了。

**Comment by wingerx** [comment]
ok.
8.0版本目前暂不支持。

**Comment by hyy613** [comment]
打扰了~~issue关了吧。

**Comment by zclsoft** [comment]
有计划进行支持吗
