### ISSUE TITLE
canal + rocksmq 能确保数据不丢失么？ 

### ISSUE THREAD

**Issue by rfyiamcool** [alibaba/canal#843]
如果canal把数据推送到rocksmq后，rmq崩溃，另外mq没有及时flush落盘，数据丢失？ 

canal + rocksmq是否有丢失binlog的可能。

**Comment by agapple** [comment]
如果rmq奔溃前没有flush落盘，那是MQ设计问题，肯定会丢失数据，需要手工重新回来数据进行补充数据

**Comment by rfyiamcool** [comment]
ok @agapple
