### ISSUE TITLE
canal支持一下同步到elasticserach

### ISSUE THREAD

**Issue by agapple** [alibaba/canal#848]
目前mysql + es的组合会是一个比较共性的需求，期望能提供一个基于canal增量同步到elasticserach的能力

**Comment by lwjli** [comment]
canal数据是单表的, es数据一般是关联之后的宽表.

**Comment by agapple** [comment]
设计上可以考虑扩展点，实现宽表的join逻辑

**Comment by rewerma** [comment]
可以实现一层的左外关联的宽表的数据定位同步和整行同步，同时支持返回字段加函数和复合字段
