### ISSUE TITLE
canal sever-client heartbeat

### ISSUE THREAD

**Issue by pan3793** [alibaba/canal#851]
Server端的Idle检测，只是检测Socket读写通道的阻塞时间

Client与Server订阅关系建立后，CanalConnector没有提供纯粹的心跳检测方法，只能向Server端只能发送get请求才能证明自己活着，如果消费速度过慢，超时就会被Server端关闭Socket连接。

可否增加一个单纯的心跳检测实现？

**Comment by agapple** [comment]
短期内先调大超时时间吧
