### ISSUE TITLE
canal解析到的字段和值不匹配，大佬给看看呗

### ISSUE THREAD

**Issue by sky-syk** [alibaba/canal#852]
![image](https://user-images.githubusercontent.com/18712087/44260217-51e25d00-a246-11e8-9622-32655791da82.png)
这一行取到的rowchange 里边可以看到解析到的字段 和值 与原库的不符，甚至类型都不对，原库int  解析后是date了

**Comment by wingerx** [comment]
是不是发生ddl变更了?

**Comment by sky-syk** [comment]
@wingerx   比如说 原表 有一条insert，但是canal没有消费，如果原表又做了ddl，那么canal再消费之前的数据就会发生这种情况么

**Comment by wingerx** [comment]
是的，这种情况可以开启tsdb。

**Comment by sky-syk** [comment]
@wingerx  之前我记得也有这种情况啊。改了表结构的。。也没出现过这个问题
