### ISSUE TITLE
集群模式下如何共享zk?canal client端又 如何指定zk呢?

### ISSUE THREAD

**Issue by yin007008** [alibaba/canal#860]
有篇文章是提供了下面的方法:
##Production场景，HA模式下，比如使用ZK作为服务管理，此处至少指定“多数派ZK Node”的IP列表  
##如果你的多个Canal Cluster共享ZK，那么每个Canal还需要使用唯一的“rootpath”。  
canal.zkServers = 10.0.1.21:2818,10.0.1.22,10.0.2.21:2818/canal/g1 

我本机测试
canal.zkServers = localhost:2181/canal/g1
启动就直接报错了
Something goes wrong when starting up the canal Server:
java.lang.IllegalArgumentException: Path length must be > 0

如果原生不支持，是否就只有通过部署多套zk来隔离多个canal server 集群呢？

**Comment by agapple** [comment]
/canal/g1 这个不要带

**Comment by threedays163** [comment]
我也遇到这个问题, 现在的设计貌似只能一套zk支持一套canal server HA集群, 同一套canal server在zk的注册路径不能修改吗?

**Comment by yin007008** [comment]
canal本身就支持集群模式，在A canal server 启动完成后会在zk的destination的running有该节点的信息，B canal server启动后，如果是跟A canal server的destination有相同的名称的，会在zk的destination目录的cluster里面有该节点的信息，因为A已经running中了，所以这个节点是不会拉取binlog的，只有当A canal server 挂了后，会由ZK通知B去获取binlog，running信息变为B canal server，cluster里面A的信息也会没了

client端直管连接对应的destination的zk和destination name即可，当有多个client时也是通过zk调度实现HA的

问题已经解决了，之前问这个问题属于对canal不熟悉引起
