### ISSUE TITLE
kafka 版本wiki配置说明不详

### ISSUE THREAD

**Issue by weilixu7** [alibaba/canal#862]
canal_kafka的deploy版本，按照wiki配置方法，配置kafka.xml，其他的参考canal独立配置，kafka console消费没有输出，canal这边也没有日志反馈，有需要特别的配置吗

**Comment by rewerma** [comment]
canal_server不是直接从deploy模块下的target/canal/bin里启动的，而是从kafka模块下的target/canal/bin下启动，启动server后先观察有没有往kafka发送数据

**Comment by agapple** [comment]
参考文档：https://github.com/alibaba/canal/wiki/Canal-Kafka-RocketMQ-QuickStart

如有文档不明确，可以修改和反馈
