### ISSUE TITLE
为什么我传输到kafka那里显示的全是乱码

### ISSUE THREAD

**Issue by ZSH9053** [alibaba/canal#871]
配置都是按照文档来的，mysql的字符集是utf8
mysql-bin.000002« *UTF-80¨£¯Ԭ8BJP58025
XshellXshellXshellXshell8
mysql-bin.000002 *UTF-80򯰖,8BJPK w
mysql-bin.000002 *UTF-80򯰖,8Btest_heJbP'Xb
	rowsCount1򂎁Pa (0BdR	char(200)=
mysql-bin.000002® *UTF-80򯰖,8BJP58052
XshellXshellXshellXshell8
mysql-bin.000002 *UTF-80ȹ񱔬8BJPK w
mysql-bin.000002 *UTF-80ȹ񱔬8Btest_heJbP'Xb
	rowsCount1򂎁Pa (0BdR	char(200)=
mysql-bin.000002± *UTF-80ȹ񱔬8BJP58481
XshellXshellXshellXshell8
mysql-bin.000002 *UTF-80񺷰Ԭ8BJPK w
mysql-bin.000002 *UTF-80񺷰Ԭ8Btest_heJbP'Xb
	rowsCount1򂎁Pa (0BdR	char(200)=
mysql-bin.000002´ *UTF-80񺷰Ԭ8BJP58486
XshellXshellXshellXshellXshell8
mysql-bin.000002 *UTF-80º񔪸BJPK w
mysql-bin.000002 *UTF-80º񔪸Btest_heJbP'Xb
	rowsCount1򂎁Pa (0BdR	char(200)=
mysql-bin.000002· *UTF-80º񔪸BJP58491
XshellXshellXshellXshell8
mysql-bin.000002 *UTF-80񼱖,8BJPK w
mysql-bin.000002 *UTF-80񼱖,8Btest_heJbP'Xb
	rowsCount1򂎁Pa (0BdR	char(200)=
mysql-bin.000002º *UTF-80񼱖,8BJP58498
XshellXshellXshellXshel8*
mysql-bin.000002 *UTF-80тÿ°Ԭ8BJPK w
mysql-bin.000002 *UTF-80тÿ°Ԭ8Btest_heJbP'Xb
	rowsCount1򂎁Pa (0BdR	char(200)=
mysql-bin.000002½ *UTF-80тÿ°Ԭ8BJP58507
XshellXshellXshellXshell*       8
mysql-bin.000002 *UTF-80Ȇ±Ԭ8BJPK w
mysql-bin.000002  *UTF-80Ȇ±Ԭ8Btest_heJbP'Xb
	rowsCount1򂎁Pa (0BdR	char(200)=
mysql-bin.000002  *UTF-80Ȇ±Ԭ8BJP58520
XshellXshellXshellXshell*
8
mysql-bin.000002 ¡ *UTF-80¸²±Ԭ8BJPK w
mysql-bin.000002¢ *UTF-80¸²±Ԭ8Btest_heJbP'X
	rowsCount1򂎁Pa (0BdR	char(200)=
mysql-bin.000002â *UTF-80¸²±Ԭ8BJP58525
XshellXshellXshellXshell*
                        8
mysql-bin.000002££ *UTF-80׍±Ԭ8BJPK w
mysql-bin.000002¤ *UTF-80׍±Ԭ8Btest_heJbP'Xb
	rowsCount1򂎁Pa (0BdR	char(200)=
mysql-bin.000002Ƥ *UTF-80׍±Ԭ8BJP58538

**Comment by rewerma** [comment]
传到kafka的是message的序列化数据，客户端收到后会反序列化为message的
