### ISSUE TITLE
canal如何配置只监听更新状态，插入，删除都不监听

### ISSUE THREAD

**Issue by Dcein** [alibaba/canal#877]

**Comment by xiaokangzhao** [comment]
可以在根据CanalEntry.EventType自己过滤

**Comment by Dcein** [comment]
多谢大佬指点。




发自网易邮箱大师
在2018年8月24日 11:28，xiaokangzhao<notifications@github.com> 写道：

可以在根据CanalEntry.EventType自己过滤
