### ISSUE TITLE
canal deployer 1.0.14版本，在client端接受到的entry都是TRANSACTION_BEGIN和TRANSACTION_END

### ISSUE THREAD

**Issue by dream5son** [alibaba/canal#88]
具体现象是这样的，在canal的server端启动的一小段时间内接受到的数据是正常的，但是在过大约10分钟之后，客户端接受到的entry的entryType就全部为TRANSACTION_BEGIN和TRANSACTION_END了。

曾经怀疑是我写的客户端有问题，但是把客户端换成示例客户端还是一样的效果。

已经尝试将server端的日志级别设置为debug，但是没有得到什么有价值的调试信息。

麻烦提供一下解决此问题的思路，或者我的server端配置有问题，可能是哪儿的问题，谢谢！！！

**Comment by shijiebei2009** [comment]
同样的问题
connector.subscribe("actionlog\\d{8}");我想订阅所有actionlog打头接数字的表，结果没有ROWDATA了，是正则错了，还是哪里错了？

请教一下想订阅指定的库或者表，这个正则要怎么写？
