### ISSUE TITLE
connector.subscribe("xxx") 不起作用

### ISSUE THREAD

**Issue by xiyuan-lpy** [alibaba/canal#888]
canal.instance.filter.regex=fid_standard_product\\..*  我在server端定义监测这一整个库，在一个客户端connector.subscribe("fid_standard_product.fid_stock_report") 其中某个表，但是这个库里的其他表还是会同步过来，这个connector.subscribe为什么没起到过滤的作用呢

**Comment by agapple** [comment]
多看FAQ
