### ISSUE TITLE
并行解析 + Gtid .没有初始化LogContext中的gtidSet

### ISSUE THREAD

**Issue by hyy613** [alibaba/canal#890]
没有初始化LogContext中的gtidSet
    public final void putGtid(GtidLogEvent logEvent) {
        if (logEvent != null) {
            String gtid = logEvent.getSid().toString() + ":" + logEvent.getGno();
            if (gtidSet == null) {
                gtid = logEvent.getSid().toString() + ":1-" + logEvent.getGno();
                gtidSet = MysqlGTIDSet.parse(gtid);
            }
            gtidSet.update(gtid);
        }
    }
event中的当前server的gtid会覆盖掉zk cursor中的历史gtidSet（若干个server:start-end 组合）
下次再重启，dump报错。

**Comment by agapple** [comment]
是基于当前的主干代码么？

**Comment by hyy613** [comment]
基于1.1.0 release 这个commit . 
commit dd8b1ce9551b59b719516615e43193c467214ade (tag: canal-1.1.0)
Author: 七锋 <jianghang.loujh@alibaba-inc.com>
Date:   Mon Aug 20 13:28:57 2018 +0800

    [maven-release-plugin] prepare release canal-1.1.0

然后cherry-pick 了并行解析的gtid 的两个bug fix 
commit 0ca9fa129975ccb4884d8ca9c02c63b066461e6a
Author: winger <winger2049@gmail.com>
Date:   Sat Aug 25 09:17:13 2018 +0800

    fix bug: 并行解析模式下，开启gtid 会导致解析错误

commit 186b58396862cbea82781458625608400fe3e5c5
Author: winger <winger2049@gmail.com>
Date:   Sat Aug 25 03:54:38 2018 +0800

    fix bug: 并行解析模式下，开启gtid 会导致解析错误

**Comment by hyy613** [comment]
如果之前zk上存储的position有多个gtid集合，并且有的已经被mysql master purged掉。
很容易复现出来。
