### ISSUE TITLE
canal.deployer-1.1.0 cursor持久化频率问题

### ISSUE THREAD

**Issue by archongum** [alibaba/canal#891]
测试1：client重连时，meta.dat的修改时间发生更新，但数据还是没变。

测试2：由于测试1的问题，导致position没有更新。导致如果此时server重启，读取的还是“旧”的持久化cursor，client在“旧”的position消费。

**Comment by AlexGumHub** [comment]
issue canal版本：1.0.26 alpha5，1.1.0

**Comment by archongum** [comment]
[#882](https://github.com/alibaba/canal/issues/882)

**Comment by archongum** [comment]
[#882](https://github.com/alibaba/canal/issues/882)

**Comment by archongum** [comment]
#882

**Comment by archongum** [comment]
#882
