### ISSUE TITLE
创建或者删除index时，如果index名称中包含on字符串，那么解析table的名称会出现错误

### ISSUE THREAD

**Issue by zhangxin1988** [alibaba/canal#893]
比如：
CREATE INDEX `schema_new_index_version_s_idx` ON `tb_email_auth` (`status`)
由于version中包含on，此时解析处理的table名为_s_idx
修正方法：
com.alibaba.otter.canal.parse.inbound.mysql.ddl.SimpleDdlParser中的
 public static final String CREATE_INDEX_PATTERN   = "^\\s*CREATE\\s*(UNIQUE)?(FULLTEXT)?(SPATIAL)?\\s*INDEX\\s*(.*?)\\s+ON\\s+(.*?)$";
    public static final String DROP_INDEX_PATTERN     = "^\\s*DROP\\s*INDEX\\s*(.*?)\\s+ON\\s+(.*?)$";

ON前后的\s必须出现1次到多次（源码中是*,改为+）

**Comment by qmz** [comment]
其实simpparser应该deprecate移除掉了吧，这个支持不了其它复杂的场景
