### ISSUE TITLE
canal 到kafka 数据一致性的问题

### ISSUE THREAD

**Issue by ZSH9053** [alibaba/canal#895]
如果我设置多个partition，canal如何保证数据的一致性，有序性

**Comment by qmz** [comment]
无论kafka还是rocketmq都只能是单分区全局有序，或单分区有序。

如果表之间要没有强关联，是可以单个表hash到同一个分区保证单表有序的

**Comment by eingmarra** [comment]
好像听说canal的项目作者，可能正在实现多个分区，一个表，并保证顺序。不知道是否是真的（理论上，我觉得，如果有张索引表--按时间排序，先读取索引表，再读真正的数据，就可以实现读取放在多个分区上的binglog数据了）

**Comment by agapple** [comment]
#958
