### ISSUE TITLE
canal.kafka输出乱码

### ISSUE THREAD

**Issue by ddonline** [alibaba/canal#898]
CentOS Linux release 7.3.1611 (Core)  3.10.0-514.el7.x86_64
JDK：jdk-8u161-linux-x64.tar.gz
zookeeper：zookeeper-3.4.13.tar.gz
kafka：kafka_2.11-2.0.0.tgz
canal.kafka：canal.kafka-1.1.0.tar.gz
MySQL：5.7.22-log
按照https://github.com/alibaba/canal/wiki/Canal-Kafka-QuickStart配置
kafka中全是乱码
请问需要在那里调整

 bin/kafka-console-consumer.sh --bootstrap-server 192.168.10.110:9092 --topic example
*D
mysql-binlog.000012*UTF-80BJP401663
*?
mysql-binlog.000012*UTF-80BJPH 
mysql-binlog.000012*UTF-80BtestJtP+Xb
        _-+_C-+++1Pb?
id (0B1Ri++(11)

  +e_+ (0B1R
               +a_cha_(255)D
+y_-+-bi++-g.000012 *UTF-80,8BJP401877
*?
+y_-+-bi++-g.000012 *UTF-80,8BJPI >
+y_-+-bi++-g.000012 *UTF-80,8Beca_dJ+_c+a___ca_d__e-+e_+_+-gPTXb
        _-+_C-+++1Pb


**Comment by rewerma** [comment]
kafka数据投递传输的是数据包哦，收到数据后还要解包成对应的message，可参考client中的kafka实现

**Comment by zskang** [comment]
楼主怎么解决这个乱码的啊？我也遇到这样的问题 哎

**Comment by delta-qin** [comment]
最简单的方式：canal.mq.flatMessage设置为true，这样canal就不会使用protobuf对消息编码而是使用普通的json字符串，这样就会导致性能的下降。
