### ISSUE TITLE
数据消费一段后，canal-client无法拉取新的数据，确定db是在不断更新的。

### ISSUE THREAD

**Issue by JasonHuangHuster** [alibaba/canal#899]
![image](https://user-images.githubusercontent.com/5965173/44947782-0e424280-ae45-11e8-973a-b2c102d7d704.png)

使用最新版本。1.10

**Comment by agapple** [comment]
检查一下server端是否有报错

**Comment by JasonHuangHuster** [comment]
![image](https://user-images.githubusercontent.com/5965173/45035342-57d09e80-b08c-11e8-9bf8-bba18de5ae43.png)
server端，出现一个异常后，看到client自动重新subscribe的信息。然后client 就读不到数据了。

**Comment by JasonHuangHuster** [comment]
又一次，出现异常后，消费停止了。
![image](https://user-images.githubusercontent.com/5965173/45036036-fad5e800-b08d-11e8-8b33-a956e293438d.png)


mysql版本 5.6.28

**Comment by JasonHuangHuster** [comment]
getWithoutAck 使用无需确认的模式，出现上面问题。
使用get Ack的模式就没有问题了。

**Comment by agapple** [comment]
先考虑升级一下canal版本

**Comment by youbingchenyoubing** [comment]
这个问题有人解决了吗，我的canal server版本是1.0.24，也是使用getWithoutAck，canal server重启后，又能立马拉到数据

**Comment by JieZeng1993** [comment]
> 这个问题有人解决了吗，我的canal server版本是1.0.24，也是使用getWithoutAck，canal server重启后，又能立马拉到数据

你解决了吗
