### ISSUE TITLE
meta.bat的问题

### ISSUE THREAD

**Issue by 13772134994** [alibaba/canal#908]
为什么我启动服务不是生成的meta.bat文件而是生成的h2.mv.db文件？有没有大神解释一下！

**Comment by yin007008** [comment]
h2.mv.db文件默认会有，canal.instance.global.spring.xml = classpath:spring/default-instance.xml是写到zk上的，canal.instance.global.spring.xml = classpath:spring/file-instance.xml这个才是写本地的meta.bat

**Comment by agapple** [comment]
LS正解
