### ISSUE TITLE
canal如何把mysql的某些数据导入到redis的集群？

### ISSUE THREAD

**Issue by greenHard** [alibaba/canal#910]
目前已经有redis集群6台,canal客户端一台,在数据不更新的情况下,如何能把mysql中现有的某些表的数据导入到redis的集群中呢?

谢谢

**Comment by wingerx** [comment]
"在数据不更新的情况下“ ,这个前提不符合canal的工作原理，可能无法满足你的需求。可以看看yugong或者dataX是不是可以满足?

**Comment by greenHard** [comment]
明白了。谢谢
