### ISSUE TITLE
[v1.1.0]异常场景测试导致操作系统cannot allocate memory内存泄漏

### ISSUE THREAD

**Issue by kervin521** [alibaba/canal#913]
模拟MySQL-binlong文件内容跌断，对binlog文件删除一部分数据，canal在发送dump解析到此binlog文件时异常，异常持续长时间会导致内存泄漏。

操作系统日志：Fatal error : pthread_create() failed

最终导致操作系统cannot allocate memory,最后只能重启系统

**Comment by kervin521** [comment]
@agapple

**Comment by agapple** [comment]
你自己检查一下jvm所需要的内存参数和你机器的内存是否match

**Comment by kervin521** [comment]
@agapple    机器内存16G,canal使用默认内存

**Comment by chunshenyu** [comment]
@agapple
canal会不停的创建线程，数量达到30000+时，系统就没法分配内存了，canal会抛异常java.lang.OutOfMemoryError： unable to create new native thread，最终导致整个系统不可用，jvm参数使用默认值，创建的大量线程如下：
MultiStageCoprocessor-other-example-0
....
MultiStageCoprocessor-other-example-8
MultiStageCoprocessor-Parse-example-0
....
MultiStageCoprocessor-Parse-example-8

**Comment by agapple** [comment]
最新的master已经修复

**Comment by wallellen** [comment]
https://github.com/alibaba/canal/pull/1002
