### ISSUE TITLE
关于mysql主备切换

### ISSUE THREAD

**Issue by xesygao** [alibaba/canal#915]
两个问题，望指教
1、canal中设置备用库，主库宕机，切到备用库。之后主库恢复，备用库宕机，能切回主库么
2、canal是否支持vip，从而不关注物理节点的切换

**Comment by agapple** [comment]
1.  不会主动主库
2.  支持rds vip的模式

**Comment by xesygao** [comment]
@agapple tks

**Comment by theonesmx** [comment]
切换到备库以后，回退60s，数据重复问题怎么解决？靠主键么？如果修改了主键怎么办？例如：源端操作
1、insert id=1; 2、update id=2 where id=1; 源端目标端数据库都是一条数据id=2了现在。此时主库切换到备库，回退60s日志。又重做了步骤1和2，1成功，2失败（主键冲突）。此时目标库就变成id=1和id=2两条数据。数据不一致了和源端。

**Comment by agapple** [comment]
1.  insert可以考虑使用merge sql
2. update遇到主键冲突，拆为delete before pk + merge insert new pk
