### ISSUE TITLE
canal.instance.filter.transaction.entry 设置true后  zk cusor不更新

### ISSUE THREAD

**Issue by fifichasheng** [alibaba/canal#921]
canal.instance.filter.transaction.entry = true

{"@type":"com.alibaba.otter.canal.protocol.position.LogPosition","identity":{"slaveId":-1,"sourceAddress":{"address":"10.35.165.15","port":3306}},"postion":{"gtid":"","included":false,"journalName":"mysql-bin.000023","**position**":43893,"serverId":1,"timestamp":1536312619000}}

**Comment by agapple** [comment]
canal.instance.filter.transaction.entry不要随意设置, 会导致zk状态不更新
