### ISSUE TITLE
update 整张表后无限循环报错 no match ack positionLogPosition

### ISSUE THREAD

**Issue by yin007008** [alibaba/canal#924]
错误信息如下：
2018-09-10 12:09:57.669 [pool-7-thread-1] ERROR com.alibaba.otter.canal.kafka.producer.CanalKafkaStarter - no match ack positionLogPosition[identity=LogIdentity[sourceAddress=/47.97.169.27:3317,slaveId=-1],postion=EntryPosition[included=false,journalName=mysql-bin.000003,position=7080270,serverId=20183317,gtid=,timestamp=1536552101000]]

sql:
update t_order_shop_0024 set  modify_time = now() ;

# binlog filter config
canal.instance.filter.druid.ddl = true
canal.instance.filter.query.dcl = true
canal.instance.filter.query.dml = true
canal.instance.filter.query.ddl = true
canal.instance.filter.table.error = true
canal.instance.filter.rows = false
canal.instance.filter.transaction.entry = true

解析的binlog信息:
* Batch Id: [149136] ,count : [1] , memsize : [8064] , Time : 2018-09-10 12:30:11
* Start : [mysql-bin.000003:7080270:1536552101000(2018-09-10 12:01:41)] 
* End : [mysql-bin.000003:7080270:1536552101000(2018-09-10 12:01:41)] 

kafka的消息一直在增长，看日志binlog全部是上面这个mysql-bin.000003:7080270:1536552101000

**Comment by yin007008** [comment]
问题基本上查明:
canal.instance.filter.transaction.entry = true
过滤事务头尾设置为true之后，如果zk上没有点位信息，起始我给的一个5天前的timestamp，刚好又做了大批量更新就会无限循环报错

问题的关键点应该是canal.instance.filter.transaction.entry = true
这个设置为true了

**Comment by wingerx** [comment]
需要位点更新的使用的，不能将canal.instance.filter.transaction.entry设置为true

**Comment by agapple** [comment]
LS正解
