### ISSUE TITLE
Consider add filed executeTime at canal-adapter-common class Dml?

### ISSUE THREAD

**Issue by pan3793** [alibaba/canal#928]
Consider add filed executeTime? 
That's sql exactly execute time, more useful sometimes.

**Comment by Dcein** [comment]
[New I/O server worker #1-1] ERROR c.a.otter.canal.server.netty.handler.SessionHandler - something goes wrong with channel:[id: 0x6b1bba32, /192.10.0.46:57388 => /192.10.16.48:11111], exception=java.io.IOException: Connection reset by peer

**Comment by agapple** [comment]
solved on v1.1.1
