### ISSUE TITLE
Message 总是返回 RawEntries 如何解析？

### ISSUE THREAD

**Issue by JerryChin** [alibaba/canal#929]
请问如何将 `RawEntries` 中的`ByteString` 转为正常的业务对象？

**Comment by JerryChin** [comment]
搞清楚了，先解析出 `Entry` 再解析出 `RowChange`。

    Entry changeEntry = Entry.parseFrom(rawEntry);
    RowChange.parseFrom(changeEntry.getStoreValue());

**Comment by zender-projects** [comment]
非常有用

> 搞清楚了，先解析出 `Entry` 再解析出 `RowChange`。
> 
> ```
> Entry changeEntry = Entry.parseFrom(rawEntry);
> RowChange.parseFrom(changeEntry.getStoreValue());
> ```

非常有用
