### ISSUE TITLE
请问能拿到单条数据吗，否则往kafka发送只能是单分区，多分区顺序无法保证

### ISSUE THREAD

**Issue by undeadwing** [alibaba/canal#932]
请问1.10发送到kafka的话，现在只能是单分区发送，多分区顺序不能保证，我们希望能发送到不同分区，并且按照key进行hash分区，我的做法是把entrys拿出来遍历，再把rowchange拿出来遍历，最后得到一条rowdata，用库名加主键的值拼出key，按照key发送这条数据，就可以保证一条数据总是会到一个分区，但是觉着这样效率很低，请问之后会有能直接拿到单条数据的方法吗，还是现在就有呢？
修改后的代码如下：

public void send(KafkaProperties.Topic topic, Message message) throws IOException {
        
        //获取entrys
        List<ByteString> rawEntries = message.getRawEntries();
        for (ByteString rawEntry : rawEntries) {
            message.addEntry(CanalEntry.Entry.parseFrom(rawEntry));
        }
        //遍历entrys
        for (CanalEntry.Entry entry : message.getEntries()) {
            String tableName = entry.getHeader().getTableName();
            CanalEntry.RowChange rowChage = CanalEntry.RowChange.parseFrom(entry.getStoreValue());
            CanalEntry.EventType eventType = rowChage.getEventType();
//            遍历rowchange
            for (CanalEntry.RowData rowData : rowChage.getRowDatasList()) {
                String key = "";
                List<CanalEntry.Column> list = null;
                if (eventType == CanalEntry.EventType.DELETE) {
                    list = rowData.getBeforeColumnsList();
                } else {
                    list = rowData.getAfterColumnsList();
                }
                //重新封装
                CanalEntry.RowData.Builder rowDataBuilder = CanalEntry.RowData.newBuilder();
                for (CanalEntry.Column column : list) {
                    if (column.getIsKey()) {
                        key = tableName + "_" + column.getValue();
                    }
                    if (eventType == CanalEntry.EventType.DELETE) {
                        rowDataBuilder.addBeforeColumns(column);
                    } else {
                        rowDataBuilder.addAfterColumns(column);
                    }
                }
                CanalEntry.RowChange.Builder rowChangeBuilder = CanalEntry.RowChange.newBuilder();
                rowChangeBuilder.addRowDatas(rowDataBuilder);
                CanalEntry.RowChange rowChangeNew = rowChangeBuilder.build();

                CanalEntry.Entry.Builder entryBuilder = CanalEntry.Entry.newBuilder();
                entryBuilder.setHeader(entry.getHeader())
                        .setEntryType(entry.getEntryType())
                        .setStoreValue(rowChangeNew.toByteString());
                List<CanalEntry.Entry> listEntry = new ArrayList<>();
                listEntry.add(entryBuilder.build());
                Message messageNew = new Message(message.getId());
                messageNew.setEntries(listEntry);

                //按照rowkey进行hash分区发送
                ProducerRecord<String, Message> record;
                record = new ProducerRecord<String, Message>(topic.getTopic(), key, messageNew);
                producer.send(record);
                if (logger.isDebugEnabled()) {
                    logger.debug("send message to kafka topic: {} \n {}", topic.getTopic(), message.toString());
                }
            }
        }
    }

**Comment by rewerma** [comment]
后续的可以支持

**Comment by undeadwing** [comment]
感谢回复，但是看代码只能按批获取数据，不反序列化出来没法直接拆成单条吧

**Comment by wingerx** [comment]
其实也可以这样处理：canal 写入kafka的数据作为贴源的数据包存在，在Kafka之后可以做个sink进行分发、合并等预处理工作，因为无论如何必须要有个处理端对数据包进行解析，还有这部分贴源的数据一直是以Message包的形式存在于kafka中，无论后续的数据需要如何处理，贴源的数据会作为基础数据存，服务于不同的数据流应用场景中，扩展性也会很好。

**Comment by undeadwing** [comment]
@wingerx 嗯，感谢提供思路，分层能更好的进行解耦，是个不错的方法，但贴源层也只能是单分区，预处理分发部分也只能是单线程，整体性能跟现在是一样的。其实现在量也达不到不够用的程度，只是想看看是不是有更好的方式，所以来跟大家交流一下

**Comment by wingerx** [comment]
@undeadwing 把并发打开试了没？不知你目前数据库的tps是多少，延迟是多大？

**Comment by undeadwing** [comment]
@wingerx 我本来用group模式，接了5个mysql，发现很吃力，现在拆了，每个mysql接一个default模式的实例，单个实例过滤后tps正常也就几十到一百多吧，没有延迟，业务有时候会全表update一个字段，那时候会卡很久，tps也很高。之前没用kafka的时候，数据有错server端需要回退，然后client只能单线程追数，追的比较慢，所以现在想使用kafka多分区，之后出问题或者全表update多线程消费就很快了

**Comment by yin007008** [comment]
client如果消费逻辑组装数据很慢，这个消费性能太低了，client完全可以多线程消费，事务提交后记录一个offset到zk，如果kill-9，下次从这个offset重新开始消费，消费输出需要保证幂等；实际上消费线程池实践中都是出于饥饿状态，阻塞队列没有任务等待，刚开始上线的时候可以不考虑这个场景；如果需要保证顺序问题，在client消费的时候做一个hash后线程池绑定即可(初始化N个单线程的线程池)

如果能够在源头入kafka的时候就做好数据分发，client端就不用考虑并发的顺序问题了

**Comment by agapple** [comment]
多partition分区，最大的问题在于pk/uk的变更.  如果业务场景上能规避，那是比较perfect的. 

ps.  已经有人提交了多分区写出到kafka的方案，下一个版本就会带上

**Comment by agapple** [comment]
#958
