### ISSUE TITLE
canal.instance.filter.transaction.entry不起作用

### ISSUE THREAD

**Issue by yxzhang666** [alibaba/canal#937]
mysql版本 5.6.26
canalserver版本 1.0.24
问题1：
在canal.properties 里配置 canal.instance.filter.transaction.entry = true 之后
在canal client 里仍然可以看到entryType 有 transactionbegin 和 transactionend 
请问，怎么处理可以在server端去除掉 transcation

问题二：
在instance.properties里配置了canal.instance.filter.regex 之后
在canal client 里仍然可以看到未关注表的  transactionbegin 和 transactionend ，相比关注表，未关注表只是少了 query的eventType 和 dml的eventType
请问，canalserver能不能做到只去同步我关注表的binlog ，以此减少canalserver的负载

**Comment by wingerx** [comment]
问题2是由问题1未生效导致的，建议升级至1.1.1再试一下
ps: 
1. 开启canal.instance.filter.transaction.entry =true后，会导致无法ack，一旦同步出现问题，将有可能导致丢数据甚至批量数据重发的可能。
2. canal server 在1.1.0做了大量性能优化，之前版本的性能问题在1.1.0上应该得到大幅度缓解甚至解决。

**Comment by yassinBj** [comment]
感谢回答！目前的应用场景还不允许脱离ack ; 之后尝试一下1.1 版本

**Comment by godchou** [comment]
canal 1.1.4的版本是这样控制的吗？
if (lastTransactionCount.incrementAndGet() <= emptyTransctionThresold
                    && Math.abs(currentTimestamp - lastTransactionTimestamp) <= emptyTransactionInterval) {}

emptyTransctionThresold和emptyTransactionInterval这2个参数是基于什么设定的，可以调大这2个参数吗
