### ISSUE TITLE
canal1.1.0往kafka发送数据量和mysql产生的量不一致

### ISSUE THREAD

**Issue by mjjian0** [alibaba/canal#939]
我的kafka.yml是这样配置的：
retries: 0
batchSize: 1024
lingerMs: 0
bufferMemory: 33554432
# canal的批次大小，单位 k，量大建议改为1M
canalBatchSize: 50
filterTransactionEntry: true

canalDestinations:
  - canalDestination: elample
    topic: elample
    partition:

mysql用存储过程插入10000条数据，每次都只能在kafka消费到6千多条

**Comment by rewerma** [comment]
batchSize不能改太大，kafka消息体默认最大不能超过1M数据，所以canalBatchSize必须1M一下建议500K，batchSize可以按默认不需要修改

**Comment by mjjian0** [comment]
他这个单位不是字节的吗？1024按字节算的话不到1M的
我改成默认的也是一样的情况
retries: 0
batchSize: 16384
lingerMs: 1
bufferMemory: 33554432
# canal的批次大小，单位 k
canalBatchSize: 50
filterTransactionEntry: true

**Comment by mjjian0** [comment]
试过了，这几个参数，都是一样的情况，每次都是只能同步六千六百多条数据

**Comment by mjjian0** [comment]
我尝试了用storm和java 代码消费都会只能消费到部分数据，但是用canal-client消费就正常拿到10000条数据
