### ISSUE TITLE
GTID模式同步下报gtid_purged的错误

### ISSUE THREAD

**Issue by awayings** [alibaba/canal#950]
1.1.0版本启用gtid模式。源数据库gtid_purged有值，启动后报错。无法同步
ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:example[java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = The slave is connecting using CHANGE MASTER TO MASTER_AUTO_POSITION = 1, but the master has purged binary logs containing GTIDs that the slave requires.
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:102)

**Comment by wingerx** [comment]
可以先尝试用一下1.1.1的alpha版本

**Comment by agapple** [comment]
google这个errmsg
