### ISSUE TITLE
canal1.1.1在RDS上遇到的几个问题

### ISSUE THREAD

**Issue by moshaoai** [alibaba/canal#954]
使用的是RDS mysql5.6高可用版，2个RDS都申请了高权限账号，按照常规instance.properties配置，一个能够启动，一个报错。
2018-09-19 11:30:38.912 [destination = xxx, address = xxx/xxx:3306 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - dump addressxxx/xxx:3306 has an error, retrying. caused by
com.alibaba.otter.canal.parse.exception.CanalParseException: java.io.IOException: ErrorPacket [errorNumber=1142, fieldCount=-1, message=SHOW VIEW command denied to user 'canal'@'xxx' for table 'db_view', sqlState=42000, sqlStateMarker=#],好像高权限账号也没有Mysql库的db_view表的权限。
也没有这个权限，但是启动正常。
咨询了下阿里云工程师，说是canal.instance.filter.regex配置的问题，需要剔除mysql库的监听，然后启动正常，但是客户端收不到数据。
第二个问题，在服务端删除节点了，但是每次启动报错，can't find destination:{},用源码跟踪调试，发现还在启动原来删除的节点，太奇怪了。我把整个deployer包删除重新部署还是会启动那个删除的节点。 我用的是单机部署，没有使用zk，望有空解答下，谢谢。

**Comment by agapple** [comment]
老实说没太看懂你的问题

**Comment by moshaoai** [comment]
> 老实说没太看懂你的问题

背景是这样的，在ECS上单机部署了deploy server端，然后连了4个RDS。第一个问题是我们访问不了mysql下面的一些表，高权限账号也是不行，然后这块好像只能通过配置filter去掉mysql schema的监控。（当时收不到binlog数据应该是filter正则配置错误的问题）。第二个问题就是在deploy server的conf文件夹下删除了一个RDS的配置，但是重启了之后，canal 服务端还是去加载这个删除的配置，很奇怪，我把deploy工程删除重新部署还是会去加载，这个是我debug看到的。然后只能重启ECS了，重启之后就好了。所以这里怀疑是不是哪里缓存了conf下的节点。

**Comment by agapple** [comment]
缓存应该是没有的，都在conf目录下

**Comment by moshaoai** [comment]
> 缓存应该是没有的，都在conf目录下

另外，如果单机模式，server端的log数据如果不消费掉的话，会不会爆内存？这几天ECS莫名爆满了，内存优化这块有什么好的建议吗?或者换zk？

**Comment by agapple** [comment]
多看wiki，不会爆内存
