### ISSUE TITLE
canal.kafka的一些相关问题

### ISSUE THREAD

**Issue by whiney** [alibaba/canal#957]
目前用canal.kafka实现了一套数据增量到elasticsearch的项目。有一些问题请教？
1. 当client挂掉，这段时间内的增量数据，在client重启后，这些增量数据不会通知到client。会出现数据丢失问题吗？

2. 有没有关于cannal的监控方案。类似jmxtrans+InfluxDb+Grafana `对于kafka的监控。

**Comment by agapple** [comment]
多看一下文档，你想要的答案都有，监控有直接对接prometheus
