### ISSUE TITLE
kafka消息顺序问题

### ISSUE THREAD

**Issue by ttting** [alibaba/canal#959]
kafka只能保证partition 级消息的顺序， 对于一张表的某个记录需要保证严格的顺序，这个怎么处理？ canalDestinations 并没有对于kafka key做什么特殊处理

**Comment by rewerma** [comment]
默认全部发送打partition 0 
配置了pk hash的会发送到对应partition
#958

**Comment by fruit-forest** [comment]
pk hash貌似没有处理delete的情况，导致delete只按照表名hash

**Comment by agapple** [comment]
delete pk hash问题最新主干已经修复
