### ISSUE TITLE
canal client端获取的float类型字段的“精度”与mysql中的不一致

### ISSUE THREAD

**Issue by alexlgj** [alibaba/canal#961]
现象：
1. mysql中源表的字段类型： float(36,6) 
2. shell中查询到的该字段的值：  345.678894  （insert后查询）
3. insert操作触发canal之后，canal中获取到的值：345.6789   （获取方法：client端column.getValue()）

问题：
canal client端获取的float类型字段的“精度”与mysql中的不一致。

我曾经尝试改写 com.alibaba.otter.canal.common.utils.CanalToStringStyle.appendDetail方法，如下：

<img width="1230" alt="mysql float" src="https://user-images.githubusercontent.com/28953872/45869265-98355980-bdba-11e8-900c-fd9bebe6fcf0.png">

但是结果现实方法改写不起作用。

请问大神如何修正这个问题？

祝好！

**Comment by agapple** [comment]
告诉我一下重现的办法，mysql版本、canal版本、建表语句、测试SQL等等

**Comment by alexlgj** [comment]
已修复，修改已生效，之前不生效的原因是：我没有在intellij idea中将修改的源码重新打包jar并替换所安装的canal server中的lib下的对应jar。精度不一致的修复方法：parser模块下的logeventconvert的parseOneRow方法（ case Types.REAL:）将float转换为double再处理。

**Comment by alexlgj** [comment]
「现象：

mysql中源表的字段类型： float(36,6)
shell中查询到的该字段的值： 345.678894 （insert后查询）
insert操作触发canal之后，canal中获取到的值：345.6789 （获取方法：client端column.getValue()）
问题：
canal client端获取的float类型字段的“精度”与mysql中的不一致。」


这个”精度问题不一致问题“不是由于更改源码导致的。

********************************************
mysql版本：
Server version:		5.7.22-log MySQL Community Server (GPL)

canal版本：1.0.24

建表语句：
CREATE TABLE `all_types` (
  `varchar1` varchar(20) DEFAULT NULL,
  `inta` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `tinyint1` tinyint(4) DEFAULT NULL,
  `smallint1` smallint(6) DEFAULT NULL,
  `bigint1` bigint(20) DEFAULT NULL,
  `decimal1` decimal(65,30) DEFAULT NULL,
  `double1` double DEFAULT NULL,
  `date1` date DEFAULT NULL,
  `time1` time DEFAULT NULL,
  `year1` year(4) DEFAULT NULL,
  `datetime1` datetime DEFAULT NULL,
  `timestamp1` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `float1` float(36,6) DEFAULT NULL,
  PRIMARY KEY (`inta`)
) ENGINE=InnoDB AUTO_INCREMENT=111118 DEFAULT CHARSET=latin1

测试SQL：
insert into all_types values('a',111112,11,111,1111111,-1235666.6666688999870,123.1345775019860,sysdate(),sysdate(),'1999',sysdate(),sysdate(),345.67890110);

**Comment by alexlgj** [comment]
经过测试发现可能是因为在logeventconvert的parseOneRow方法中做了：
case Types.REAL: 
                        // 对象为number类型，直接valueof即可
                        columnBuilder.setValue(String.valueOf(value));
                        break;

String.valueOf(value)中如果value是float，则会导致精度丢失。

**Comment by agapple** [comment]
这个还不一定好改
1.  mysql自带的mysqlbinlog工具解析345.67890110直接变为345.679，canal解析为345.6789，如果强转为double则为345.67889404296875
2.  自己插入的是345.67890110，实际mysql存入的是345.678894
3.  mysql对于float的描述，存储上本身存在不精准的行为：https://dev.mysql.com/doc/refman/5.7/en/problems-with-float.html，考虑0.0001的精度误差

**Comment by alexlgj** [comment]
我是这样处理的，不知道是否正确：

float先转double，mysql存入的为345.678894，double为345.67889404296875，数据类型为float(36,6)，因此scale为6，double中小数点scale+1位即345.6788940，对double中小数点scale位进行4舍5入：
当小数点scale+1位数字>=5, 则小数店第scale位+1；否则不变化。因此345.6788940取6位是：345.678894。
经过了几次测试，目前发现经处理后的结果和mysql中存入结果一致。

**Comment by agapple** [comment]
没有可依托的可靠case，mysql自身的binlog解析代码也是直接float对象处理

**Comment by agapple** [comment]
insert语句直接插入345.6789，mysql里select出来的结果也是345.678894

**Comment by alexlgj** [comment]
是啊，这样的话确实是不好处理。

**Comment by alexlgj** [comment]
float这种类型本身决定的啦
