### ISSUE TITLE
tsdb持久化存储的方案使用mysql时可以正常监听到数据，改成h2之后就监听不到数据了

### ISSUE THREAD

**Issue by infoflow** [alibaba/canal#965]
版本是1.1.0
canal.properties中的h2配置
#table meta tsdb info
canal.instance.tsdb.enable=true
canal.instance.tsdb.dir=${canal.file.data.dir:../conf}/${canal.instance.destination:}
canal.instance.tsdb.url=jdbc:h2:${canal.instance.tsdb.dir}/h2;CACHE_SIZE=1000;MODE=MYSQL;
canal.instance.tsdb.dbUsername=canal
canal.instance.tsdb.dbPassword=canal

instance.properties 中的h2配置
#table meta tsdb info 
#记录按时间序列记录表结构 
canal.instance.tsdb.enable=true
#将表结构数据保存在h2 嵌入式数据库中
canal.instance.tsdb.url=jdbc:h2:${canal.instance.tsdb.dir}/h2;CACHE_SIZE=1000;MODE=MYSQL;
canal.instance.tsdb.dbUsername=canal
canal.instance.tsdb.dbPassword=canal

**Comment by infoflow** [comment]
打开h2 的数据库文件发现meta_history 和 meta_snapshot 中都没有数据。
![h2](https://user-images.githubusercontent.com/10652165/45876725-0cc5c380-bdce-11e8-8d64-dd5814762051.png)

**Comment by agapple** [comment]
问题太笼统，关注server异常日志

**Comment by javaerjiang** [comment]
线上环境出现了和楼主描述同样的问题,暂未排除出问题所在
