### ISSUE TITLE
Canal 运行一段时间,服务端报错?

### ISSUE THREAD

**Issue by greenHard** [alibaba/canal#967]
[New I/O server worker #1-2] ERROR c.a.otter.canal.server.netty.handler.SessionHandler - something goes wrong with channel:[id: 0x5c5493e4, /10.152.0.121:18964 => /10.193.
16.48:11111], exception=java.io.IOException: Connection reset by peer

canal 版本 1.1.0

**Comment by greenHard** [comment]
看其他issue,说是idleTimeout 这个空闲超时时间的问题,我看了下报错的点, 好像就是在1个小时之后报错。我想问下。我可以设置这个idleTimeout 参数的时间么。谢谢！

**Comment by agapple** [comment]
SimpleCanalConnector.idleTimeout

**Comment by hahaha11123** [comment]
请问是在哪里设置，SimpleCanalConnector只有soTimeout，1.1.1版本。
