### ISSUE TITLE
Question: canal v1.1.0, 为什么存在DatabaseTableMeta#compareTableMetaDbAndMemory这样的一个比较过程？

### ISSUE THREAD

**Issue by spccold** [alibaba/canal#971]
如题

**Comment by agapple** [comment]
为了确保基于内存tsdb维护的表结构正确性，在做snapshot之前和当前数据库做一下对比

**Comment by spccold** [comment]
在内存tsdb维护的表结构正确的情况下，下面两中情况仍然会导致DatabaseTableMeta#compareTableMetaDbAndMemory返回false
1. canal消费存在比较大的延迟，此时内存中的表结构和mysql真实的表结构存在差异
2. 回退位点，重复消费binlog，消费很慢，24小时内仍未追上最新的位点

**Comment by agapple** [comment]
snapshot会每间隔24小时定时发起，如果一次中对比失败，可以在下一次对比成功后记录

**Comment by spccold** [comment]
3Q, 我清楚这块的设计意图了
