### ISSUE TITLE
canal解析出的binlog文件名有乱码，导致服务重启后就再也无法定位日志位置

### ISSUE THREAD

**Issue by wkjun** [alibaba/canal#974]
```
cat  conf/example/meta.dat


{
	"clientDatas": [{
		"clientIdentity": {
			"clientId": 1001,
			"destination": "example"
		},
		"cursor": {
			"identity": {
				"slaveId": -1,
				"sourceAddress": {
					"address": "xxxxxxxxxxxx",
					"port": 3306
				}
			},
			"postion": {
				"gtid": "",
				"included": false,
				"journalName": "mysql-bin.000227\u000F»8\u0089",
				"position": 805106264,
				"serverId": 1352,
				"timestamp": 1538124951000
			}
		}
	}],
	"destination": "example"
}
```
服务端和 客户端都为：1.1.0 正式版本
数据库版本：Mariadb 10.1.19 版本

**Comment by liuhuanjs** [comment]
可以参考下,重写CanalEntry的getLogfileName()对binlog名称进行过滤,编译install
参考地址: https://blog.csdn.net/qq_20641565/article/details/78957181

**Comment by agapple** [comment]
@liuhuanjs 你们这样的改法算是比较hack. 

@wkjun 考虑把你当前binlog的文件导出发给我，我看一下mariadb是否在binlog格式上有一些变化

**Comment by wkjun** [comment]
@agapple  原文件和解析文件已经分别发到你gmail,请帮忙看下。
补充一点：服务器上binlog checksum 为未启用状态。

**Comment by agapple** [comment]
@wkjun  DirectLogFetcherTest基于这个测试类在你的mysql上跑一下吧，单纯的binlog文件解析没问题，感觉是mariadb是否在处理RotateLogEvent存在不兼容的情况，可以debug看看，给我一些你环境里看到的数据，这样可以有针对性的修复

**Comment by agapple** [comment]
我的意思是需要debug canalserver的代码，看下RotateLogEvent的解析过程

**Comment by chenyu9390** [comment]
![tim 20181018173553](https://user-images.githubusercontent.com/8199403/47145431-5259ab80-d2fc-11e8-8842-f6219a388359.png)
canal运行一段时间后乱码报错
![tim 20181018173800](https://user-images.githubusercontent.com/8199403/47145782-2a1e7c80-d2fd-11e8-93a2-7f8e6e5e1d3f.png)

**Comment by AlbertTao** [comment]
> @liuhuanjs 你们这样的改法算是比较hack.
> 
> @wkjun 考虑把你当前binlog的文件导出发给我，我看一下mariadb是否在binlog格式上有一些变化

这个问题把之前错错得对的情况暴露了出来。

先来解释这个问题的原因：这个乱码是由于binlog_checksum设置成了CRC32导致。
Dump日志前有这样一句：SET @master_binlog_checksum='@@global.binlog_checksum'
这句的原来的意思是设置slave端此次session的binlog_checksum与master端一致。但是经过测试
这句没有达到预期的效果。正确的是：SET @master_binlog_checksum=@@global.binlog_checksum（不用引号）。
在MySQL（5.7）上效果等同于‘NONE’，但是在MariaDB(10.3.10)上效果等同于'CRC32'。
侧面验证：第一句改成SET @master_binlog_checksum='NONE'之后，没有乱码。

再来解析代码中逻辑有问题的地方：
在LogDecoder.decode() 方法中有这样一句代码：
 int checksumAlg = LogEvent.BINLOG_CHECKSUM_ALG_UNDEF;
设置checksum的处所值，因为此时ROTATE_EVENT事件在FORMAT_DESCRIPTION_EVENT之前就已经出来了，所以第一次ROTATE_EVENT中的binlog名称由于没有忽略CRC32的4个字节的校验码，导致尾巴有4个乱码一样的字符。

通过上面的解释应该能解释为啥之前为啥是错错得对了。
1错 SET @master_binlog_checksum='@@global.binlog_checksum'
2错 int checksumAlg = LogEvent.BINLOG_CHECKSUM_ALG_UNDEF;
MySQL下等同于每次设置checksum为‘NONE’。

解决方案：
1. 改正 SET @master_binlog_checksum='@@global.binlog_checksum' ，改成  SET @master_binlog_checksum=@@global.binlog_checksum 与master段保持一致。
2. int checksumAlg = LogEvent.BINLOG_CHECKSUM_ALG_UNDEF; 初始化使用 global.binlog_checksum的值。

PS : 代码中的第二个错误点，只是指出了错误链的代表的点，实际的修改方案只是参考。（逃~

**Comment by agapple** [comment]
https://github.com/alibaba/canal/commit/7992b883d2e88aa19aaed88f0108512355c23353

1. SET @master_binlog_checksum='@@global.binlog_checksum'，出现引号应该是中间有一次合并代码导致，使用引号主要是为了规避mysql5.1/5.5老版本不支持binlog_checksum的系统变量加的.  
2. checksumAlg从目前来看，mysql和mariadb的行为不太一样，mariadb会对rotate_log_event也发送checksum，而mysql却不会，目前对mariadb做了下兼容处理

如果大家有遇到binlog乱码问题，请先明确mysql还是mariadb，是否开启了checksum

**Comment by AlbertTao** [comment]
1. 感觉规避的方法不太对，之所以能规避是因为加上引号就不是系统变量了，这样就引出了binlog_checksum在未定义值的情况下的问题。

2. 我觉得 这种行为的不一致，是由于SET @master_binlog_checksum='@@global.binlog_checksum' 这样的未定义的值引起的。mysql 和 mariadb 正常情况下对于ROTATE_EVENT的checksum是一致的。通过显式的设置SET @master_binlog_checksum='CRC32'  时，MySQL（5.6.41 5.6需要用新一些的版本）时会发送checksum的。

关于binlog文件名乱码的问题，如果master段一直是关闭checksum的话，改第一条（master_binlog_checksum）是没有问题的。但是当master端checksum是开启的话，
就需要调整下初始化checksumAlg参数。
还有一种比较粗暴的解决方案是。
SET @master_binlog_checksum='@@global.binlog_checksum' 改成
SET @master_binlog_checksum='NONE'。
这样变相将当前会话的binlog_checksum 与checksumAlg参数保持了一样的效果值。（都是未开启）

**Comment by agapple** [comment]
我现在手头没有mariadb，没法测试。 mysql的测试没问题的，如果有条件可以提交一个MR给我 @AlbertTao

**Comment by agapple** [comment]
最新的版本做了修复，读取master_binlog_checksum的值作为解析第一条rotate_event的checksum，大家可以尝试一下，如有问题继续反馈给我
