### ISSUE TITLE
数据一直在同步但数据量不对

### ISSUE THREAD

**Issue by xiyuan-lpy** [alibaba/canal#975]
ERROR c.a.otter.canal.server.netty.handler.SessionHandler - something goes wrong with channel:[id: 0x127a1b89, /5.39.221.52:60106 => 我的canal ip

每隔几秒就报一次这个错，大佬，是有人偷连我的canal吗 ，这个ip好像是荷兰的 5.39.221.52:60106

**Comment by agapple** [comment]
你自己不要暴露到公网上啊

**Comment by rewerma** [comment]
-_-#
