### ISSUE TITLE
canal-kafka-1.1.0版本，binlog没有变化的时候，cpu占用跑满一个核心99.99% cpu (50.00% of 2 core)

### ISSUE THREAD

**Issue by madfrog2047** [alibaba/canal#976]
使用canal-kafka-1.1.0版本，canal.properties使用的默认配置，启动后cpu占用就很高，binlog没有变化
服务器CPU信息
[cpuinfo.txt](https://github.com/alibaba/canal/files/2430253/cpuinfo.txt)

线程调用信息为：
![123](https://user-images.githubusercontent.com/16751056/46240746-a862bf80-c3de-11e8-9707-8a6bb6771a6e.png)

火焰图
![image](https://user-images.githubusercontent.com/16751056/46240795-5bcbb400-c3df-11e8-9e51-874821bc76fa.png)

是因为机器配置低还是其他原因

**Comment by rewerma** [comment]
请跟新最新版本
#904
