### ISSUE TITLE
同步位点问题

### ISSUE THREAD

**Issue by robert1070** [alibaba/canal#977]
canal 版本：1.0.24
源实例：RDS
问题：canal server在启动之后，配置了多个intancaes，如果在订阅的过程发生了rds主备切换或者实例迁移，怎么修复？(经过试过，修改配置文件只是将intances进行reload，修改信息不会同步至zk中，那么这个时候应该怎么做)

**Comment by 1241407808** [comment]
停止canal server，删除zookeeper中/otter/canal/destinations/${your_instance}/1001 整个znode，再重启canal server

**Comment by robert1070** [comment]
@1241407808 如果是对应的多个intances，重启server会对其他的intances有影响吗？

**Comment by 1241407808** [comment]
当然会，其他的instance会停掉；
canal server会把其他instance 的位点记录到zk中，下一次启动会按照对应的位点继续。

**Comment by robert1070** [comment]
多谢了
