### ISSUE TITLE
请问，客户端如何能获取 TableMeta 对象，谢谢！

### ISSUE THREAD

**Issue by eingmarra** [alibaba/canal#982]
如题，想在客户端获取 表中的主键或者唯一键。

但不知从何下手。
现在我们用的 canal 是1.0.22；据说1.0.26以后，canal增加tsdb来实时存储表结构信息；那客户端如何获取呢？直接connect到druid中拿？还是在批量拉取时，从返回的message或者其他对象中能获取到？

请不吝赐教，谢谢各位！

**Comment by agapple** [comment]
表的主键在返回的protobuf对象里已经有标识，isKey.  如果要获取唯一键，需要拿到表名去反查一下数据库表结构

**Comment by eingmarra** [comment]
明白了，谢谢！
