### ISSUE TITLE
问一个canal代码数据结构的问题

### ISSUE THREAD

**Issue by shizhengchao** [alibaba/canal#984]
RowChange rowChange中的getRowDatasList()可能 会返回多条吗？如果会 什么情况下会

**Comment by shizhengchao** [comment]
批量情况

**Comment by JasonJunJun** [comment]
@shizhengchao 你说的批量情况是什么呢？能够具体解释一下吗？

**Comment by shizhengchao** [comment]
> @shizhengchao 你说的批量情况是什么呢？能够具体解释一下吗？

就是批量插入或者更新数据库

**Comment by JasonJunJun** [comment]
好的，我试试这种情况，谢谢。

**Comment by JasonJunJun** [comment]
测试结果：
比如执行了`update table set update_time =now()`，那么`rowChange.getRowDatasList().size()`会等于表的行数。
