### ISSUE TITLE
server配置了多个实例，某个实例报错后如何恢复

### ISSUE THREAD

**Issue by chengkaisheng** [alibaba/canal#985]
server监听了多个库，有个库由于网络问题中断了一会，后面一直连不上，报timeout。
要重新接的话是不是只能重启server，还是说可以只重启出错的实例？
![default](https://user-images.githubusercontent.com/22339074/46599888-0e57f100-cb1b-11e8-81e4-38203ac9e231.PNG)

**Comment by agapple** [comment]
建议直接测试一下最新的1.1.1版本
