### ISSUE TITLE
canal.instance.filter.regex不生效

### ISSUE THREAD

**Issue by xiaoqitu7** [alibaba/canal#988]
尝试了两个mysql服务器，同样的配置，一个生效，另一个不生效。
已经检查bin log格式，是ROW格式。
用的是KafkaCanalConnector,subscribe()方法里没有用参数。
请问是什么原因？
服务器1 不生效
![image](https://user-images.githubusercontent.com/24933564/46660266-44fc3d00-cbe9-11e8-93f3-2f7218564f10.png)
![image](https://user-images.githubusercontent.com/24933564/46660815-79bcc400-cbea-11e8-9085-ee90f1eb5933.png)

服务器2 生效
![image](https://user-images.githubusercontent.com/24933564/46660299-534a5900-cbe9-11e8-9aca-ae68e98b27ed.png)
![image](https://user-images.githubusercontent.com/24933564/46660833-82ad9580-cbea-11e8-80d8-9ce49dbbf46b.png)

这两个服务器binlog的配置的不同会影响吗

**Comment by agapple** [comment]
看一下wiki里的FAQ，有几种常见的filter未生效的case
