### ISSUE TITLE
canal实现HA 并且发送消息到kafka集群,主备切换导致消息重复发送

### ISSUE THREAD

**Issue by Velsson** [alibaba/canal#991]
canal实现HA后,binlog的position记录到了zookeeper中,但将主应用暂停掉后,备用会将之前一段时间没有经由它处理的binlog重新投递到kafka中.是什么情况???

**Comment by Velsson** [comment]
在HA模式下 停止A,切换到B,再启动A,再停止B由A操作的zk上的cursor的position不更新,不知道是因为集成了Kafka还是其他原因??

**Comment by agapple** [comment]
已知问题，建议升级1.1.1新版本
