### ISSUE TITLE
使用CanalKafkaClientExample storeValue是乱码

### ISSUE THREAD

**Issue by xiaoqitu7** [alibaba/canal#992]
2018-10-10 17:25:19.304 [Thread-2] INFO  c.a.o.canal.client.running.kafka.CanalKafkaClientExample - Message[id=16,entries=[header {
  version: 1
  logfileName: "mysql-bin.000156"
  logfileOffset: 298158292
  serverId: 1
  serverenCode: "UTF-8"
  executeTime: 1539163519000
  sourceType: MYSQL
  schemaName: "payment"
  tableName: "tmp_canal_test"
  eventLength: 69
  eventType: UPDATE
  props {
    key: "rowsCount"
    value: "1"
  }
}
entryType: ROWDATA
storeValue: "\b\242\006\020\002P\000b\341\001\n\033\b\000\020\004\032\002id \001(\0000\000B\00245R\aint(11)\n\'\b\001\020\f\032\busername \000(\0000\000B\003111R\fvarchar(255)\n*\b\002\020\f\032\bpassword \000(\0000\000B\006123123R\fvarchar(255)\022\033\b\000\020\004\032\002id \001(\0000\000B\00245R\aint(11)\022\'\b\001\020\f\032\busername \000(\0000\000B\003111R\fvarchar(255)\022\'\b\002\020\f\032\bpassword \000(\0010\000B\003123R\fvarchar(255)"
],raw=true,rawEntries=[]]

请问一下怎么处理

**Comment by littleneko** [comment]
`storeValue`是`com.alibaba.otter.canal.protocol.RowChange`类型，需要进一步解析出来，具体可以看EntryProtocol.proto中的定义

**Comment by agapple** [comment]
LS正解
