### ISSUE TITLE
canal是否支持多个instance指向同一database 只是对应的白名单表不同?

### ISSUE THREAD

**Issue by Velsson** [alibaba/canal#994]
试了下设置多个instance 其中的instance.properties的数据库地址相同,仅仅是白名单指向不同的表(主要是为了一张表对应一个kafka的topic),但是在启动的时候报错实例化Datasource冲突?

**Comment by baibingzhi** [comment]
@Velsson 如果指向同一个database的canal server使用不同的 instance 注册到 zk，那么 zk 上 cursor 的position是不同的吧？
