### ISSUE TITLE
canal怎么处理源表delete的数据

### ISSUE THREAD

**Issue by fangzheng0518** [alibaba/canal#995]
如标题

**Comment by littleneko** [comment]
delete在binlog中就是一个只有before image的event，和insert/update没啥区别。你说的怎么处理是指？

**Comment by fangzheng0518** [comment]
> delete在binlog中就是一个只有before image的event，和insert/update没啥区别。你说的怎么处理是指？

好吧，其实是我表达的不清楚，应该是说，canal能解析binlog肯定能获取delete的语句。
我的问题应该是，获取到delete数据后，从canal抽取数据-->hive仓库。那hive仓库怎么处理这个删除的数据？
注意：
1、hive没有启用事务，不能delete操作

**Comment by jxyzmahuan** [comment]
这个是你hive要处理的啊，和canal有什么关系， 你可是试试 apache orc

**Comment by fangzheng0518** [comment]
> 这个是你hive要处理的啊，和canal有什么关系， 你可是试试 apache orc

好的，我试试。谢谢！
