### ISSUE TITLE
不知道为啥报这个做，是不是因为编码？

### ISSUE THREAD

**Issue by 282857484** [alibaba/canal#997]
2018-10-11 16:23:00.584 [[scheduler-table-meta-snapshot]] ERROR c.a.o.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta - pls submit github issue, show create table ddl:CREATE TABLE `template_config` (
  `id` bigint(50) NOT NULL,
  `module` varchar(100) DEFAULT '模板类型',
  `title` varchar(100) DEFAULT '字段名称',
  `field` varchar(100) DEFAULT '字段标记',
  `type` varchar(50) DEFAULT '字段类型',
  `isShow` tinyint(1) unsigned DEFAULT '0' COMMENT '业务可输入',
  `isNull` tinyint(1) DEFAULT '0' COMMENT ' 是否为空',
  `defaultValue` varchar(200) DEFAULT '默认值',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 , compare failed . 
 db : TableMeta [schema=ec_gome_bfs_uat, table=gome_cms_template_config, fileds=
        FieldMeta [columnName=id, columnType=bigint(50), nullable=false, key=true, defaultValue=null, extra=null, unique=false]
        FieldMeta [columnName=module, columnType=varchar(100), nullable=true, key=false, defaultValue=模板类型, extra=null, unique=false]
        FieldMeta [columnName=title, columnType=varchar(100), nullable=true, key=false, defaultValue=字段名称, extra=null, unique=false]
        FieldMeta [columnName=field, columnType=varchar(100), nullable=true, key=false, defaultValue=字段标记, extra=null, unique=false]
        FieldMeta [columnName=type, columnType=varchar(50), nullable=true, key=false, defaultValue=字段类型, extra=null, unique=false]
        FieldMeta [columnName=isShow, columnType=tinyint(1) unsigned, nullable=true, key=false, defaultValue=0, extra=null, unique=false]
        FieldMeta [columnName=isNull, columnType=tinyint(1), nullable=true, key=false, defaultValue=0, extra=null, unique=false]
        FieldMeta [columnName=defaultValue, columnType=varchar(200), nullable=true, key=false, defaultValue=默认值, extra=null, unique=false]
] 
 mem : TableMeta [schema=ec_gome_bfs_uat, table=gome_cms_template_config, fileds=
        FieldMeta [columnName=id, columnType=bigint(50), nullable=false, key=true, defaultValue=null, extra=null, unique=false]
        FieldMeta [columnName=module, columnType=varchar(100), nullable=true, key=false, defaultValue=????, extra=null, unique=false]
        FieldMeta [columnName=title, columnType=varchar(100), nullable=true, key=false, defaultValue=????, extra=null, unique=false]
        FieldMeta [columnName=field, columnType=varchar(100), nullable=true, key=false, defaultValue=????, extra=null, unique=false]
        FieldMeta [columnName=type, columnType=varchar(50), nullable=true, key=false, defaultValue=????, extra=null, unique=false]
        FieldMeta [columnName=isShow, columnType=tinyint(1) unsigned, nullable=true, key=false, defaultValue=0, extra=null, unique=false]
        FieldMeta [columnName=isNull, columnType=tinyint(1), nullable=true, key=false, defaultValue=0, extra=null, unique=false]
        FieldMeta [columnName=defaultValue, columnType=varchar(200), nullable=true, key=false, defaultValue=???, extra=null, unique=false]
]

**Comment by 282857484** [comment]
我开启了TSDB，这个应该是数据库和内存里的数据进行比对，怀疑是编码问题。跟踪canal代码跟不到指定位置。
 数据库是utf8，表是utf8.   
instance.properties文件里的采集是
canal.instance.connectionCharset=UTF-8
canal.instance.tsdb.url=jdbc:mysql://xx.xx.xx.xx:40001/canal_tsdb

报错的信息里都有中文与问号

**Comment by agapple** [comment]
可以debug QueryLogEvent的解析过程，看看clientCharset是否有正确解析到

**Comment by agapple** [comment]
后续有新的反馈,可以reopen
